#!/usr/bin/env python3
"""DUA Wave A2 Batch 19 — 160 concepts, all target subfields, push to 5500"""
import sqlite3, uuid, datetime

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def uid(): return "dua_" + uuid.uuid4().hex[:12]
def now(): return datetime.datetime.now(datetime.timezone.utc).isoformat()

RECORDS = [
    # ── 哲学・倫理学 (30 entries) ──
    (uid(),"ピュロン主義","Pyrrhonism","Ancient Greek skeptical philosophy founded by Pyrrho of Elis, maintaining suspension of judgment (epoché) on all matters as path to tranquility","哲学・倫理学","Western_Europe",-300,"https://en.wikipedia.org/wiki/Pyrrhonism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アカデメイア懐疑主義","Academic Skepticism","Skeptical philosophy of the Platonic Academy under Arcesilaus and Carneades, arguing probability as guide to action","哲学・倫理学","Western_Europe",-270,"https://en.wikipedia.org/wiki/Academic_skepticism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"自然神学","Natural Theology","Branch of theology arguing for God's existence through reason and natural evidence rather than revelation","哲学・倫理学","Western_Europe",1100,"https://en.wikipedia.org/wiki/Natural_theology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"目的論的倫理学","Teleological Ethics","Ethical theories evaluating actions based on their outcomes and ends, contrasting with deontological approaches","哲学・倫理学","Western_Europe",1700,"https://en.wikipedia.org/wiki/Teleology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"義務論的倫理学","Deontological Ethics","Ethical theory holding that morality of action depends on adherence to rules or duties, independent of consequences","哲学・倫理学","Western_Europe",1785,"https://en.wikipedia.org/wiki/Deontological_ethics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"徳倫理学の復活","Revival of Virtue Ethics","Late 20th century return to Aristotelian virtue ethics by Anscombe, MacIntyre, Foot, and others","哲学・倫理学","Western_Europe",1958,"https://en.wikipedia.org/wiki/Virtue_ethics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"マキャベリズム","Machiavellianism","Political philosophy emphasizing pragmatic statecraft and power over conventional morality, derived from Machiavelli","哲学・倫理学","Western_Europe",1532,"https://en.wikipedia.org/wiki/Machiavellianism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"啓蒙主義哲学","Philosophy of the Enlightenment","18th century intellectual movement emphasizing reason, individual rights, and empirical inquiry over tradition","哲学・倫理学","Western_Europe",1700,"https://en.wikipedia.org/wiki/Age_of_Enlightenment","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"功利主義の歴史","History of Utilitarianism","Development of utilitarian ethics from Bentham through Mill to contemporary forms like preference and rule utilitarianism","哲学・倫理学","Western_Europe",1789,"https://en.wikipedia.org/wiki/Utilitarianism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"社会契約論の伝統","Social Contract Tradition","Political philosophy tracing authority to hypothetical agreement among individuals, developed by Hobbes, Locke, Rousseau, and Rawls","哲学・倫理学","Western_Europe",1651,"https://en.wikipedia.org/wiki/Social_contract","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"主権理論","Theory of Sovereignty","Political philosophy concerning supreme authority within a territory, from Bodin through Hobbes to modern international law","哲学・倫理学","Western_Europe",1576,"https://en.wikipedia.org/wiki/Sovereignty","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アンベードカル反カースト哲学","Ambedkar Anti-Caste Philosophy","B.R. Ambedkar's philosophical framework challenging caste system through Buddhist conversion and radical social reform","哲学・倫理学","South_Asia",1936,"https://en.wikipedia.org/wiki/B._R._Ambedkar","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"西田幾多郎の哲学","Nishida Kitaro Philosophy","Japanese philosopher's system of pure experience and absolute nothingness synthesizing East Asian and Western thought","哲学・倫理学","East_Asia",1911,"https://en.wikipedia.org/wiki/Kitaro_Nishida","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"和辻哲郎の倫理学","Watsuji Tetsuro Ethics","Japanese philosopher's ethics of betweenness (aidagara) emphasizing relational and climatic dimensions of human existence","哲学・倫理学","East_Asia",1937,"https://en.wikipedia.org/wiki/Tetsur%C5%8D_Watsuji","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"龍樹の哲学","Nagarjuna Philosophy","2nd century Buddhist philosopher's Madhyamaka doctrine of emptiness and dependent origination","哲学・倫理学","South_Asia",150,"https://en.wikipedia.org/wiki/Nagarjuna","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ガンジーの真理把握","Gandhi Satyagraha","Mahatma Gandhi's philosophy of nonviolent resistance based on truth-force and civil disobedience","哲学・倫理学","South_Asia",1906,"https://en.wikipedia.org/wiki/Satyagraha","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"陽明学","Wang Yangming Neo-Confucianism","Ming dynasty Neo-Confucianism emphasizing unity of knowledge and action, innate moral knowledge (liangzhi)","哲学・倫理学","East_Asia",1521,"https://en.wikipedia.org/wiki/Wang_Yangming","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"イブン・ルシュドの哲学","Ibn Rushd Aristotelian Philosophy","Averroes' comprehensive commentaries on Aristotle, defending rationalism in Islamic philosophy","哲学・倫理学","West_Asia_North_Africa",1169,"https://en.wikipedia.org/wiki/Averroes","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アル=ファーラービーの政治哲学","Al-Farabi Political Philosophy","Islamic philosopher's synthesis of Plato and Aristotle applied to ideal state and prophecy","哲学・倫理学","West_Asia_North_Africa",900,"https://en.wikipedia.org/wiki/Al-Farabi","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ザラスシュトラ倫理学","Zoroastrian Ethics","Ethical system of Zoroastrianism based on truth (asha), good thoughts, words, and deeds","哲学・倫理学","West_Asia_North_Africa",-1500,"https://en.wikipedia.org/wiki/Zoroastrian_ethics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフリカ哲学認識論","African Philosophy Epistemology","Epistemological frameworks indigenous to African thought including ubuntu, communitarian knowledge, and oral tradition","哲学・倫理学","Sub_Saharan_Africa",1970,"https://en.wikipedia.org/wiki/African_philosophy","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"メソアメリカ哲学","Mesoamerican Philosophy","Indigenous philosophical traditions of Aztec, Maya, and other Mesoamerican civilizations concerning cosmos and ethics","哲学・倫理学","Latin_America",-500,"https://en.wikipedia.org/wiki/Aztec_philosophy","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アンデス宇宙論","Andean Cosmology","Indigenous Andean philosophical frameworks including Pachamama, ayni (reciprocity), and complementary duality","哲学・倫理学","Latin_America",-200,"https://en.wikipedia.org/wiki/Andean_cosmology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"オーストラリア先住民哲学","Aboriginal Australian Philosophy","Dreamtime ontology and relational metaphysics of Australian Aboriginal peoples","哲学・倫理学","Oceania",-50000,"https://en.wikipedia.org/wiki/Dreamtime","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"存在論的実在論","Ontological Realism","Philosophical position that reality exists independently of minds and representations","哲学・倫理学","Western_Europe",1900,"https://en.wikipedia.org/wiki/Philosophical_realism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"認識論的内在主義","Epistemic Internalism","View that justification for beliefs depends solely on factors internal to the believer's mental states","哲学・倫理学","Western_Europe",1980,"https://en.wikipedia.org/wiki/Internalism_and_externalism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"科学的実在論","Scientific Realism","Philosophical position that scientific theories describe reality including unobservable entities","哲学・倫理学","Western_Europe",1960,"https://en.wikipedia.org/wiki/Scientific_realism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"概念工学","Conceptual Engineering","Practice of assessing and revising concepts in language and thought to serve cognitive and practical purposes","哲学・倫理学","Western_Europe",2017,"https://en.wikipedia.org/wiki/Conceptual_engineering","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"規範的倫理学の理論","Normative Ethical Theory","Systematic theories about what makes actions right or wrong including consequentialism, deontology, virtue ethics","哲学・倫理学","Western_Europe",1750,"https://en.wikipedia.org/wiki/Normative_ethics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"環境倫理学の歴史","History of Environmental Ethics","Development of ethical frameworks concerning nature from land ethics to deep ecology and ecological justice","哲学・倫理学","Western_Europe",1949,"https://en.wikipedia.org/wiki/Environmental_ethics","url_present","dua_wave_a2","active",now(),now()),

    # ── 歴史学 (25 entries) ──
    (uid(),"世界史の方法論","World History Methodology","Methodological frameworks for studying history at global scale, connecting civilizations across regions","歴史学","Global_Synthesis",1963,"https://en.wikipedia.org/wiki/World_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"マルクス主義歴史学","Marxist Historiography","Historical analysis using materialist conception of history, class struggle, and modes of production","歴史学","Western_Europe",1848,"https://en.wikipedia.org/wiki/Historical_materialism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ウィッグ史観","Whig Historiography","Historical interpretation viewing past as inevitable progress toward liberal democracy, critiqued by Butterfield","歴史学","Western_Europe",1931,"https://en.wikipedia.org/wiki/Whig_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"歴史的記憶研究","Memory Studies in History","Interdisciplinary field examining how societies remember the past through monuments, rituals, and narratives","歴史学","Western_Europe",1980,"https://en.wikipedia.org/wiki/Memory_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"デジタル歴史学","Digital History","Application of digital tools and methods to historical research, including data visualization and network analysis","歴史学","Global_Synthesis",1994,"https://en.wikipedia.org/wiki/Digital_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"歴史社会学","Historical Sociology","Study of society and social change using historical methods, linking macro-structures to historical processes","歴史学","Western_Europe",1840,"https://en.wikipedia.org/wiki/Historical_sociology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"感情史","History of Emotions","Historical study of how emotions are experienced, expressed, and regulated across cultures and periods","歴史学","Western_Europe",1985,"https://en.wikipedia.org/wiki/History_of_emotions","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"身体史","History of the Body","Historical study of bodily practices, medical knowledge, and corporeal experience across cultures","歴史学","Western_Europe",1978,"https://en.wikipedia.org/wiki/Body_in_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"家族史","Family History","Historical study of family structures, kinship, marriage patterns, and domestic life across periods","歴史学","Western_Europe",1960,"https://en.wikipedia.org/wiki/Family_history_(discipline)","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"労働史","Labor History","Historical study of working-class movements, labor conditions, and industrial relations","歴史学","Western_Europe",1880,"https://en.wikipedia.org/wiki/Labor_history_(discipline)","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"疾病史","History of Disease","Historical study of epidemics, medical practices, and interactions between disease and society","歴史学","Global_Synthesis",1950,"https://en.wikipedia.org/wiki/History_of_medicine","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"イスラム史学","Islamic Historiography","Historical writing and methodology in the Islamic tradition from Ibn Khaldun to modern Arab historians","歴史学","West_Asia_North_Africa",1377,"https://en.wikipedia.org/wiki/Islamic_historiography","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"中国正史","Chinese Official Historiography","Dynastic histories (zhengshi) compiled by official historians as state-sanctioned narratives of Chinese dynasties","歴史学","East_Asia",-100,"https://en.wikipedia.org/wiki/Official_Chinese_historiography","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"インド歴史叙述","Indian Historical Writing","Historical traditions of South Asia including Puranas, chronicles, and modern Indian historiography","歴史学","South_Asia",-300,"https://en.wikipedia.org/wiki/Indian_historiography","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"口承史","Oral History Methodology","Historical methodology using oral testimonies and interviews as primary sources","歴史学","Global_Synthesis",1948,"https://en.wikipedia.org/wiki/Oral_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフリカ史学","African Historiography","Historical scholarship on Africa including precolonial traditions, decolonization, and pan-African narratives","歴史学","Sub_Saharan_Africa",1960,"https://en.wikipedia.org/wiki/African_historiography","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ラテンアメリカ史学","Latin American Historiography","Historical scholarship on Latin America from colonial chronicles to dependency theory and postcolonial approaches","歴史学","Latin_America",1500,"https://en.wikipedia.org/wiki/Historiography_of_Latin_America","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"宗教改革史学","Reformation Historiography","Historical scholarship on the Protestant and Catholic Reformations of 16th century Europe","歴史学","Western_Europe",1517,"https://en.wikipedia.org/wiki/Protestant_Reformation","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"大西洋史","Atlantic History","Transnational historical framework studying connections across the Atlantic world including slavery and colonialism","歴史学","Western_Europe",1990,"https://en.wikipedia.org/wiki/Atlantic_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"インド洋史","Indian Ocean History","Historical study of commercial, cultural, and ecological connections across the Indian Ocean world","歴史学","Global_Synthesis",1994,"https://en.wikipedia.org/wiki/Indian_Ocean_trade","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"太平洋史","Pacific History","Historical study of peoples, migrations, trade, and colonialism across the Pacific Ocean region","歴史学","Oceania",1966,"https://en.wikipedia.org/wiki/Pacific_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"帝国史学","Imperial Historiography","Historical study of empires, imperialism, and colonialism and their lasting effects","歴史学","Western_Europe",1960,"https://en.wikipedia.org/wiki/Imperialism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"都市史","Urban History","Historical study of cities, urbanization, and metropolitan life across cultures and periods","歴史学","Western_Europe",1920,"https://en.wikipedia.org/wiki/Urban_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"農村史","Rural History","Historical study of peasant communities, agrarian systems, and country life","歴史学","Western_Europe",1920,"https://en.wikipedia.org/wiki/Rural_history","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ジェンダーと歴史","Gender and History","Historical analysis of gendered experience, women's history, and masculinity studies","歴史学","Global_Synthesis",1970,"https://en.wikipedia.org/wiki/Women%27s_history","url_present","dua_wave_a2","active",now(),now()),

    # ── 文学・批評理論 (25 entries) ──
    (uid(),"ゴシック文学","Gothic Literature","Literary genre featuring horror, the supernatural, decay, and psychological terror originating in 18th century Britain","文学・批評理論","Western_Europe",1764,"https://en.wikipedia.org/wiki/Gothic_fiction","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"SFの批評理論","Science Fiction Criticism","Critical approaches to science fiction literature examining technology, utopia, posthumanism, and cognitive estrangement","文学・批評理論","Western_Europe",1972,"https://en.wikipedia.org/wiki/Science_fiction_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"探偵小説の理論","Detective Fiction Theory","Critical analysis of detective and mystery fiction conventions, hermeneutics, and cultural function","文学・批評理論","Western_Europe",1841,"https://en.wikipedia.org/wiki/Detective_fiction","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ロマンス小説理論","Romance Novel Theory","Critical analysis of romantic fiction conventions, female readership, and cultural ideologies","文学・批評理論","Western_Europe",1740,"https://en.wikipedia.org/wiki/Romance_novel","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"自伝研究","Autobiography Studies","Study of self-narrative, life writing, and memoir as literary forms and cultural practices","文学・批評理論","Western_Europe",1980,"https://en.wikipedia.org/wiki/Autobiography","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"旅行文学研究","Travel Literature Studies","Analysis of travel writing as genre intersecting literature, geography, imperialism, and cross-cultural encounter","文学・批評理論","Western_Europe",1960,"https://en.wikipedia.org/wiki/Travel_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"子供文学研究","Children's Literature Studies","Critical study of literature for children examining ideology, development, canon formation, and illustration","文学・批評理論","Western_Europe",1950,"https://en.wikipedia.org/wiki/Children%27s_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"グラフィック小説研究","Graphic Novel Studies","Academic study of comics and graphic novels as literary and visual medium","文学・批評理論","Western_Europe",1978,"https://en.wikipedia.org/wiki/Graphic_novel","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"世界文学論","World Literature Theory","Theories of how literature circulates globally, from Goethe's Weltliteratur to Moretti and Casanova","文学・批評理論","Global_Synthesis",1827,"https://en.wikipedia.org/wiki/World_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"翻訳研究","Translation Studies","Interdisciplinary study of translation as cultural practice, linguistic transfer, and intercultural communication","文学・批評理論","Global_Synthesis",1972,"https://en.wikipedia.org/wiki/Translation_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ハーレム・ルネサンス批評","Harlem Renaissance Criticism","Critical analysis of African American literary and artistic movement of 1920s Harlem","文学・批評理論","North_America",1920,"https://en.wikipedia.org/wiki/Harlem_Renaissance","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"マジック・リアリズム批評","Magic Realism Criticism","Critical analysis of literary style blending realistic narrative with magical elements, associated with Latin American literature","文学・批評理論","Latin_America",1940,"https://en.wikipedia.org/wiki/Magic_realism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフリカ文学批評","African Literature Criticism","Critical approaches to African literature examining colonial language, oral traditions, and postcolonial identity","文学・批評理論","Sub_Saharan_Africa",1958,"https://en.wikipedia.org/wiki/African_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"インド英語文学","Indian English Literature Criticism","Critical study of Indian literature in English from colonial period to contemporary postcolonial writing","文学・批評理論","South_Asia",1835,"https://en.wikipedia.org/wiki/Indian_English_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"日本近代文学批評","Japanese Modern Literature Criticism","Critical analysis of Meiji and post-Meiji Japanese literature exploring modernization, identity, and naturalism","文学・批評理論","East_Asia",1868,"https://en.wikipedia.org/wiki/Japanese_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"漢詩の批評","Classical Chinese Poetry Criticism","Critical analysis of classical Chinese poetry traditions including shi, ci, and fu forms","文学・批評理論","East_Asia",-300,"https://en.wikipedia.org/wiki/Chinese_poetry","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アラビア文学批評","Arabic Literature Criticism","Critical study of Arabic literary traditions from pre-Islamic poetry through Abbasid prose to modern Arabic novel","文学・批評理論","West_Asia_North_Africa",-500,"https://en.wikipedia.org/wiki/Arabic_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ナラトロジー","Narratology","Systematic study of narrative structure, story grammar, and how stories are constructed and received","文学・批評理論","Western_Europe",1969,"https://en.wikipedia.org/wiki/Narratology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"文体論","Stylistics","Linguistic analysis of literary style, examining phonological, grammatical, and semantic choices","文学・批評理論","Western_Europe",1960,"https://en.wikipedia.org/wiki/Stylistics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"受容美学","Reception Aesthetics","Reader-response theory examining how meaning is created in transaction between text and reader","文学・批評理論","Western_Europe",1967,"https://en.wikipedia.org/wiki/Reception_theory","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"オーラル・フォーミュラ理論","Oral-Formulaic Theory","Analysis of oral epic poetry composition using formulaic phrases, developed by Milman Parry and Albert Lord","文学・批評理論","Western_Europe",1930,"https://en.wikipedia.org/wiki/Oral-formulaic_composition","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"エコクリティシズム","Ecocriticism","Environmental approach to literary criticism examining representations of nature and ecological themes","文学・批評理論","North_America",1978,"https://en.wikipedia.org/wiki/Ecocriticism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"デジタル人文学文学研究","Digital Literary Studies","Application of computational methods to literary analysis including text mining and stylometry","文学・批評理論","Global_Synthesis",2000,"https://en.wikipedia.org/wiki/Digital_humanities","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"記憶と文学","Memory and Literature","Study of how literature represents and shapes cultural memory, trauma, and collective experience","文学・批評理論","Western_Europe",1990,"https://en.wikipedia.org/wiki/Memory_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ポストヒューマン文学批評","Posthuman Literary Criticism","Critical approaches examining literature through posthumanist, cyborg, and transhumanist frameworks","文学・批評理論","Western_Europe",1999,"https://en.wikipedia.org/wiki/Posthumanism","url_present","dua_wave_a2","active",now(),now()),

    # ── 言語学 (15 entries) ──
    (uid(),"語彙意味論","Lexical Semantics","Study of word meaning, semantic relations, and organization of the lexicon","言語学","Western_Europe",1960,"https://en.wikipedia.org/wiki/Lexical_semantics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"談話分析","Discourse Analysis","Study of language use in context beyond the sentence level, examining cohesion, coherence, and social functions","言語学","Western_Europe",1952,"https://en.wikipedia.org/wiki/Discourse_analysis","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"言語と文化","Language and Culture","Study of the relationship between linguistic structures and cultural practices, including linguistic relativity","言語学","Global_Synthesis",1929,"https://en.wikipedia.org/wiki/Linguistic_relativity","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"書記言語の研究","Writing Systems Research","Comparative study of writing systems including alphabetic, syllabic, logographic, and their historical development","言語学","Global_Synthesis",-3200,"https://en.wikipedia.org/wiki/Writing_system","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"言語接触","Language Contact","Study of linguistic phenomena arising when speakers of different languages interact, including borrowing and code-switching","言語学","Global_Synthesis",1880,"https://en.wikipedia.org/wiki/Language_contact","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"言語類型論","Linguistic Typology","Study of structural diversity across human languages to identify universal and cross-linguistic patterns","言語学","Global_Synthesis",1780,"https://en.wikipedia.org/wiki/Linguistic_typology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"形式意味論","Formal Semantics","Application of mathematical logic to natural language meaning including truth conditions and compositional semantics","言語学","Western_Europe",1970,"https://en.wikipedia.org/wiki/Formal_semantics_(linguistics)","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"コーパス言語学","Corpus Linguistics","Study of language based on systematic analysis of large bodies of natural text using computational methods","言語学","Western_Europe",1960,"https://en.wikipedia.org/wiki/Corpus_linguistics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"手話言語学","Sign Language Linguistics","Linguistic study of visual-gestural languages of deaf communities as fully natural human languages","言語学","North_America",1960,"https://en.wikipedia.org/wiki/Sign_language_linguistics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフロ・アジア語族","Afroasiatic Linguistics","Study of Afroasiatic language family including Semitic, Egyptian, Berber, Cushitic, and Chadic branches","言語学","West_Asia_North_Africa",-4000,"https://en.wikipedia.org/wiki/Afroasiatic_languages","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"オーストロネシア語族","Austronesian Linguistics","Study of world's largest language family by number of languages, spread across Southeast Asia and Pacific","言語学","Oceania",-3500,"https://en.wikipedia.org/wiki/Austronesian_languages","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"バントゥー語族","Bantu Linguistics","Study of Bantu language family spanning sub-Saharan Africa with complex noun class systems","言語学","Sub_Saharan_Africa",-3000,"https://en.wikipedia.org/wiki/Bantu_languages","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"語用論の歴史","History of Pragmatics","Development of pragmatics as a field studying language use in context, from Austin and Grice onward","言語学","Western_Europe",1955,"https://en.wikipedia.org/wiki/Pragmatics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"音声学と音韻論の歴史","History of Phonetics and Phonology","Development of the study of speech sounds from ancient Indian linguistics through structuralism to generative phonology","言語学","Global_Synthesis",-500,"https://en.wikipedia.org/wiki/History_of_linguistics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"計算言語学","Computational Linguistics","Interdisciplinary field applying computational methods to understanding and processing natural language","言語学","North_America",1950,"https://en.wikipedia.org/wiki/Computational_linguistics","url_present","dua_wave_a2","active",now(),now()),

    # ── 宗教学 (15 entries) ──
    (uid(),"比較宗教学の方法論","Comparative Religion Methodology","Systematic approaches to comparing religious traditions including phenomenology, typology, and hermeneutics","宗教学","Western_Europe",1870,"https://en.wikipedia.org/wiki/Comparative_religion","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"神話研究","Myth Studies","Comparative and structural analysis of mythological narratives across cultures","宗教学","Global_Synthesis",1860,"https://en.wikipedia.org/wiki/Mythology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"宗教社会学","Sociology of Religion","Sociological analysis of religious institutions, rituals, and their social functions","宗教学","Western_Europe",1893,"https://en.wikipedia.org/wiki/Sociology_of_religion","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"宗教心理学","Psychology of Religion","Psychological study of religious experience, belief, conversion, and spiritual development","宗教学","North_America",1902,"https://en.wikipedia.org/wiki/Psychology_of_religion","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"シャーマニズム研究","Shamanism Studies","Academic study of shamanic practices, worldviews, and altered states across indigenous cultures globally","宗教学","Global_Synthesis",1951,"https://en.wikipedia.org/wiki/Shamanism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"タントラ研究","Tantric Studies","Academic study of tantric traditions in Hinduism and Buddhism including ritual, yoga, and esoteric practices","宗教学","South_Asia",1900,"https://en.wikipedia.org/wiki/Tantra","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ユダヤ教学","Jewish Studies","Interdisciplinary academic study of Jewish history, literature, theology, and culture","宗教学","West_Asia_North_Africa",1819,"https://en.wikipedia.org/wiki/Jewish_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"イスラム神学","Islamic Theology","Systematic study of theological questions in Islam including kalam, Sufi traditions, and modern Islamic thought","宗教学","West_Asia_North_Africa",750,"https://en.wikipedia.org/wiki/Islamic_theology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"神道研究","Shinto Studies","Academic study of Japan's indigenous religious tradition including kami worship, shrine rituals, and mythology","宗教学","East_Asia",600,"https://en.wikipedia.org/wiki/Shinto","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"道教研究","Daoist Studies","Academic study of Daoism including classical texts, religious institutions, alchemy, and immortality practices","宗教学","East_Asia",-400,"https://en.wikipedia.org/wiki/Taoism","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフリカ伝統宗教","African Traditional Religion","Study of indigenous African religious systems including ancestor veneration, divination, and spirit possession","宗教学","Sub_Saharan_Africa",-2000,"https://en.wikipedia.org/wiki/African_traditional_religion","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"新宗教運動研究","New Religious Movements Studies","Academic study of new and emerging religious groups including cults, sects, and alternative spiritualities","宗教学","Global_Synthesis",1970,"https://en.wikipedia.org/wiki/New_religious_movement","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"宗教と政治","Religion and Politics","Study of interactions between religious authority, political power, and the negotiation of the secular","宗教学","Global_Synthesis",1950,"https://en.wikipedia.org/wiki/Religion_and_politics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"聖なるものの現象学","Phenomenology of the Sacred","Philosophical and phenomenological study of religious experience as encounter with the sacred","宗教学","Western_Europe",1917,"https://en.wikipedia.org/wiki/Sacred","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"先住民宗教研究","Indigenous Religion Studies","Academic study of indigenous and tribal religious traditions globally with attention to decolonization","宗教学","Global_Synthesis",1980,"https://en.wikipedia.org/wiki/Indigenous_religion","url_present","dua_wave_a2","active",now(),now()),

    # ── 古典学 (15 entries) ──
    (uid(),"ギリシア悲劇研究","Greek Tragedy Studies","Scholarly study of Aeschylus, Sophocles, and Euripides examining dramatic form, myth, and civic function","古典学","Western_Europe",-500,"https://en.wikipedia.org/wiki/Greek_tragedy","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ローマ詩研究","Roman Poetry Studies","Scholarly analysis of Latin poetry from Catullus and Virgil through Ovid examining genre, meter, and intertextuality","古典学","Western_Europe",-100,"https://en.wikipedia.org/wiki/Latin_poetry","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ヘレニズム文学","Hellenistic Literature","Greek literature of the Hellenistic period including Alexandrian scholarship, new comedy, and pastoral poetry","古典学","Western_Europe",-323,"https://en.wikipedia.org/wiki/Hellenistic_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"古代哲学テキスト研究","Ancient Philosophy Textual Studies","Philological study of ancient philosophical texts including manuscript traditions and reception history","古典学","Western_Europe",1450,"https://en.wikipedia.org/wiki/Classical_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ラテン文法学","Latin Grammar Tradition","Study of Latin grammatical tradition from Donatus and Priscian through medieval and Renaissance grammarians","古典学","Western_Europe",350,"https://en.wikipedia.org/wiki/Latin_grammar","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"碑文学","Epigraphy","Study of ancient inscriptions on stone, metal, and other durable materials as historical evidence","古典学","Global_Synthesis",-800,"https://en.wikipedia.org/wiki/Epigraphy","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"パピルス学","Papyrology","Study of ancient documents preserved on papyrus, primarily from Egypt, yielding literary and administrative texts","古典学","Western_Europe",1778,"https://en.wikipedia.org/wiki/Papyrology","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"古典受容研究","Classical Reception Studies","Study of how Greek and Roman antiquity has been interpreted and used in later cultures","古典学","Western_Europe",1980,"https://en.wikipedia.org/wiki/Classical_reception_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"メソポタミア文学","Mesopotamian Literature","Study of ancient Sumerian and Akkadian literary texts including Gilgamesh Epic and wisdom literature","古典学","West_Asia_North_Africa",-2600,"https://en.wikipedia.org/wiki/Mesopotamian_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"エジプト文学","Ancient Egyptian Literature","Study of ancient Egyptian literary texts including wisdom literature, love poetry, and funerary texts","古典学","West_Asia_North_Africa",-3000,"https://en.wikipedia.org/wiki/Ancient_Egyptian_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"サンスクリット文法学","Sanskrit Grammar Tradition","Study of Paninian grammar tradition and classical Sanskrit linguistic theory","古典学","South_Asia",-400,"https://en.wikipedia.org/wiki/Sanskrit_grammar","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"古典中国語","Classical Chinese Scholarship","Study of classical Chinese language, canonical texts, and commentarial traditions","古典学","East_Asia",-500,"https://en.wikipedia.org/wiki/Classical_Chinese","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アラビア語古典文法","Classical Arabic Grammar","Study of classical Arabic grammar tradition from Sibawayhi through medieval grammatical schools","古典学","West_Asia_North_Africa",760,"https://en.wikipedia.org/wiki/Classical_Arabic","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ビザンティン文学","Byzantine Literature","Study of Greek literature of the Byzantine Empire including chronicles, hagiography, and secular poetry","古典学","Western_Europe",330,"https://en.wikipedia.org/wiki/Byzantine_literature","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"中世ラテン文学","Medieval Latin Literature","Study of Latin literature of the medieval period including hagiography, scholastic texts, and Latin poetry","古典学","Western_Europe",500,"https://en.wikipedia.org/wiki/Medieval_Latin_literature","url_present","dua_wave_a2","active",now(),now()),

    # ── 美学・芸術理論 (15 entries) ──
    (uid(),"芸術哲学の歴史","History of Philosophy of Art","Development of aesthetic theory from Plato's condemnation of mimesis through Kant's critique to contemporary debates","美学・芸術理論","Western_Europe",-380,"https://en.wikipedia.org/wiki/Aesthetics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"音楽哲学","Philosophy of Music","Philosophical inquiry into the nature of music, its ontology, and its aesthetic and emotional power","美学・芸術理論","Western_Europe",1750,"https://en.wikipedia.org/wiki/Philosophy_of_music","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"建築美学","Architecture Aesthetics","Aesthetic theory applied to architecture examining beauty, function, space, and cultural meaning","美学・芸術理論","Western_Europe",1752,"https://en.wikipedia.org/wiki/Architectural_theory","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"映画理論の歴史","History of Film Theory","Development of cinema theory from early realism debates through psychoanalytic, semiotic, and feminist approaches","美学・芸術理論","Western_Europe",1916,"https://en.wikipedia.org/wiki/Film_theory","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"パフォーマンス研究","Performance Studies","Interdisciplinary study of theatrical, ritual, everyday, and political performance as cultural practice","美学・芸術理論","North_America",1970,"https://en.wikipedia.org/wiki/Performance_studies","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"写真理論","Photography Theory","Critical and aesthetic analysis of photography examining truth, representation, and power","美学・芸術理論","Western_Europe",1839,"https://en.wikipedia.org/wiki/Photography_and_the_law","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"デジタルアート研究","Digital Art Studies","Study of computer-generated and digital media art examining new aesthetics and technological mediation","美学・芸術理論","North_America",1960,"https://en.wikipedia.org/wiki/Digital_art","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ポピュラーアート研究","Popular Art Studies","Critical analysis of popular and mass cultural artistic forms including folk art, pop art, and subcultural aesthetics","美学・芸術理論","North_America",1950,"https://en.wikipedia.org/wiki/Popular_art","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"非西洋美学","Non-Western Aesthetics","Study of aesthetic traditions outside Western Europe including Japanese mono no aware, Chinese shanshui, and Indian rasa","美学・芸術理論","Global_Synthesis",1900,"https://en.wikipedia.org/wiki/Aesthetics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"ラサ美学","Rasa Aesthetics","Sanskrit aesthetic theory of emotional essences in art, developed by Bharata and Abhinavagupta","美学・芸術理論","South_Asia",-200,"https://en.wikipedia.org/wiki/Rasa_(aesthetics)","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"能楽の美学","Noh Aesthetics","Japanese aesthetic theory of Noh theater developed by Zeami emphasizing yugen and hana","美学・芸術理論","East_Asia",1400,"https://en.wikipedia.org/wiki/N%C5%8D","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"イスラム美術理論","Islamic Art Theory","Aesthetic and art theoretical frameworks in Islamic tradition including geometric patterns and calligraphy","美学・芸術理論","West_Asia_North_Africa",700,"https://en.wikipedia.org/wiki/Islamic_art","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"アフリカ美術理論","African Art Theory","Aesthetic frameworks for understanding African visual arts emphasizing function, ritual, and community","美学・芸術理論","Sub_Saharan_Africa",1900,"https://en.wikipedia.org/wiki/African_art","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"環境美学","Environmental Aesthetics","Aesthetic theory concerned with the natural environment, landscape, and everyday aesthetic experience","美学・芸術理論","North_America",1966,"https://en.wikipedia.org/wiki/Environmental_aesthetics","url_present","dua_wave_a2","active",now(),now()),
    (uid(),"関係美学","Relational Aesthetics","Art theory examining artworks defined by their intersubjective context and social relations, developed by Nicolas Bourriaud","美学・芸術理論","Western_Europe",1998,"https://en.wikipedia.org/wiki/Relational_aesthetics","url_present","dua_wave_a2","active",now(),now()),
]


def main():
    con = sqlite3.connect(DB)
    con.execute("PRAGMA journal_mode=WAL")
    cur = con.cursor()
    existing = set(r[0] for r in cur.execute("SELECT name_en FROM humanities_concept").fetchall())
    batch, inserted, skipped = [], 0, 0
    for rec in RECORDS:
        name_en = rec[2]
        if name_en in existing:
            skipped += 1
            continue
        existing.add(name_en)
        batch.append(rec)
        if len(batch) >= 500:
            cur.executemany("""INSERT INTO humanities_concept
                (id,name_ja,name_en,definition,subfield,culture_region,
                 era_start,source_url,verification_status,quality_flag,
                 status,created_at,updated_at)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)""", batch)
            con.commit()
            inserted += len(batch)
            batch = []
    if batch:
        cur.executemany("""INSERT INTO humanities_concept
            (id,name_ja,name_en,definition,subfield,culture_region,
             era_start,source_url,verification_status,quality_flag,
             status,created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)""", batch)
        con.commit()
        inserted += len(batch)
    total = cur.execute("SELECT COUNT(*) FROM humanities_concept").fetchone()[0]
    print(f"inserted={inserted}, skipped={skipped}")
    print(f"総件数: {total} (目標5500)")
    con.close()


if __name__ == "__main__":
    main()
