"""Batch 25 — Mathematics (20) + Statistics/Computation (20) = 40 concepts"""
import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

MATH_BATCH = [
    {
        "name_ja": "楕円曲線暗号", "name_en": "Elliptic Curve Cryptography",
        "definition": "有限体上の楕円曲線の離散対数問題の難しさを安全性の根拠とする公開鍵暗号方式。RSAより短い鍵長で同等の安全性を達成する。",
        "impact_summary": "スマートカード・TLS・ビットコインの公開鍵暗号の基盤となる現代暗号の主流技術。",
        "subfield": "数学", "school_of_thought": "暗号理論", "era_start": 1985,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Elliptic-curve_cryptography",
        "mathematical_formulation": r"y^2=x^3+ax+b\pmod{p},\quad\#E(\mathbb{F}_p)\approx p",
    },
    {
        "name_ja": "ペレルマンのポアンカレ予想の証明", "name_en": "Perelman's Proof of Poincaré Conjecture",
        "definition": "Grigori Perelman（2002-2003年）がリッチフロー理論を用いてポアンカレ予想を証明した。3次元単連結コンパクト多様体は3次元球面に位相同型であることを示した。",
        "impact_summary": "ミレニアム問題の一つを解決した20世紀最大の数学的業績の一つ。フィールズ賞辞退で有名。",
        "subfield": "数学", "school_of_thought": "幾何学", "era_start": 2002,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Poincar%C3%A9_conjecture",
        "mathematical_formulation": r"\frac{\partial g_{ij}}{\partial t}=-2R_{ij}\,({\rm Ricci\,flow})",
    },
    {
        "name_ja": "モジュラー形式と保型形式", "name_en": "Modular Forms and Automorphic Forms",
        "definition": "上半平面上でモジュラー群の変換に対して一定の変換規則を持つ複素解析関数。フェルマーの最終定理証明・ラングランズプログラムの中核。",
        "impact_summary": "整数論の最深部を結びつけるラングランズプログラムの中心対象。フェルマー最終定理の証明（1994年）で頂点に立つ。",
        "subfield": "数学", "school_of_thought": "整数論", "era_start": 1829,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Modular_form",
        "mathematical_formulation": r"f\!\left(\frac{az+b}{cz+d}\right)=(cz+d)^k f(z),\quad\begin{pmatrix}a&b\\c&d\end{pmatrix}\in\text{SL}_2(\mathbb{Z})",
    },
    {
        "name_ja": "スペクトル理論", "name_en": "Spectral Theory",
        "definition": "線形作用素（特に自己共役作用素・行列）の固有値・固有関数の解析。量子力学のハミルトニアンのスペクトル・グラフスペクトル・偏微分方程式の解析に応用される。",
        "impact_summary": "量子力学・グラフ理論・機械学習のPCAなど広範な分野の数学的基盤。",
        "subfield": "数学", "school_of_thought": "関数解析学", "era_start": 1900,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Spectral_theory",
        "mathematical_formulation": r"A\psi=\lambda\psi,\quad\sigma(A)=\{\lambda\in\mathbb{C}:(A-\lambda I)\text{ not invertible}\}",
    },
    {
        "name_ja": "ハミング符号と誤り訂正符号", "name_en": "Error-Correcting Codes",
        "definition": "デジタル通信・記憶媒体での誤りを検出・訂正するための符号理論。ハミング符号（1950）・BCH符号・リード-ソロモン符号・LDPCコード・ターボ符号等を含む。",
        "impact_summary": "CD・DVD・インターネット通信・深宇宙通信の信頼性を保証する情報理論の応用数学。",
        "subfield": "数学", "school_of_thought": "情報理論", "era_start": 1950,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Hamming_code",
        "mathematical_formulation": r"d_H(\mathbf{x},\mathbf{y})=\sum_{i=1}^n\mathbf{1}[x_i\ne y_i],\quad t\leq\lfloor(d-1)/2\rfloor",
    },
    {
        "name_ja": "オイラーの多面体定理とオイラー標数", "name_en": "Euler Characteristic and Polyhedron Formula",
        "definition": "多面体の頂点V・辺E・面Fが満たすV-E+F=2という関係（オイラーの多面体定理）。位相幾何学のオイラー標数として一般化され、位相不変量として多様体を分類する。",
        "impact_summary": "位相幾何学の礎となる定理。ガウス-ボネ定理・アティヤ-ジンガー定理へと発展する。",
        "subfield": "数学", "school_of_thought": "幾何学・位相幾何学", "era_start": 1750,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Euler_characteristic",
        "mathematical_formulation": r"V-E+F=2\,(\text{polyhedron}),\quad\chi=\sum_k(-1)^k b_k",
    },
    {
        "name_ja": "ゲルファント-ツェトリン基底と表現論", "name_en": "Gelfand-Tsetlin Basis",
        "definition": "半単純リー群（特にU(n)・GL(n)）の既約表現を組み合わせ論的に記述する正規直交基底の構成法。ロシアのゲルファント・ツェトリンが1950年に導入。",
        "impact_summary": "古典群の表現論・量子群・可積分系の計算手法の基盤として幅広く使われる代数的構成。",
        "subfield": "数学", "school_of_thought": "代数学", "era_start": 1950,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Gelfand%E2%80%93Tsetlin_basis",
        "mathematical_formulation": r"\lambda_1\geq\mu_1\geq\lambda_2\geq\mu_2\geq\cdots\geq\lambda_n\geq\mu_n\,({\rm interlacing\,condition})",
    },
    {
        "name_ja": "ワイルの指標公式", "name_en": "Weyl Character Formula",
        "definition": "ヘルマン・ワイルが1925年に証明したコンパクトリー群の既約表現の指標を最高ウェイトで明示的に与える公式。表現論の最重要定理の一つ。",
        "impact_summary": "物理・化学の対称性表現を扱う際の基礎として量子力学・素粒子物理に広く使われる。",
        "subfield": "数学", "school_of_thought": "代数学", "era_start": 1925,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Weyl_character_formula",
        "mathematical_formulation": r"\chi_\lambda=\frac{\sum_{w\in W}\varepsilon(w)e^{w(\lambda+\rho)}}{\sum_{w\in W}\varepsilon(w)e^{w(\rho)}}",
    },
    {
        "name_ja": "アルゴリズムの複雑性クラスとNTM", "name_en": "Computational Complexity Classes",
        "definition": "問題の難易度を分類する計算複雑性理論。P（多項式時間）・NP・PSPACE・EXP等のクラスとその包含関係を研究する。P≠NP問題はミレニアム懸賞問題。",
        "impact_summary": "暗号理論・アルゴリズム設計・AI限界の理論的基盤。P vs NPは計算機科学最大の未解決問題。",
        "subfield": "数学", "school_of_thought": "理論計算機科学", "era_start": 1971,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Computational_complexity_theory",
        "mathematical_formulation": r"\text{P}\subseteq\text{NP}\subseteq\text{PSPACE}\subseteq\text{EXP},\quad\text{P}\stackrel{?}{=}\text{NP}",
    },
    {
        "name_ja": "アラビア数学のアルジャブル", "name_en": "Al-Khwarizmi Algebra",
        "definition": "9世紀のムハンマド・イブン・ムーサー・アル＝フワーリズミーによる『アルジャブル・ワル・ムカーバラ』。代数学を体系化し「algebra（代数）」の語源となった。",
        "impact_summary": "現代代数学・アルゴリズム（algorithm：アル＝フワーリズミーから）の語源となったイスラム数学の頂点。",
        "subfield": "数学", "school_of_thought": "イスラム数学", "era_start": 830,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/The_Compendious_Book_on_Calculation_by_Completion_and_Balancing",
        "mathematical_formulation": r"x^2+10x=39\Rightarrow x=3\,(\text{al-Khwarizmi's example})",
    },
    {
        "name_ja": "マヤ数学と二十進法", "name_en": "Maya Mathematics and Vigesimal System",
        "definition": "古代マヤ文明が独自に発展させた二十進法・ゼロの概念・位取り記数法。精密な天文暦（ハアブ暦・ツォルキン暦）の計算に用いられた。",
        "impact_summary": "ユーラシアと独立してゼロと位取りを発明したアメリカ先住民の高度な数理体系。",
        "subfield": "数学", "school_of_thought": "先住民数学", "era_start": 300,
        "culture_region": "Americas_Indigenous",
        "source_url": "https://en.wikipedia.org/wiki/Maya_numerals",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "インカのキープ数理体系", "name_en": "Quipu: Inca Numerical System",
        "definition": "インカ帝国が使用した結縄（キープ）による記録・計算体系。縄の色・結び目の種類・位置が十進位取り記数を表現し、人口・物資の会計記録に使われた。",
        "impact_summary": "文字を持たないインカ文明が実現した高度な行政管理数理システム。バイナリ符号化の先駆とも解釈される。",
        "subfield": "数学", "school_of_thought": "先住民数学", "era_start": 1400,
        "culture_region": "Americas_Indigenous",
        "source_url": "https://en.wikipedia.org/wiki/Quipu",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "確率論の中心極限定理", "name_en": "Central Limit Theorem",
        "definition": "独立同分布の確率変数の和は、分布によらず正規分布に収束するという定理。Lyapunov条件・Berry-Esseen定理などの精密化がある。",
        "impact_summary": "統計的推測・誤差解析・物理の中心方程式として使われる確率論の最重要定理。",
        "subfield": "数学", "school_of_thought": "確率論", "era_start": 1733,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Central_limit_theorem",
        "mathematical_formulation": r"\frac{S_n-n\mu}{\sigma\sqrt{n}}\xrightarrow{d}N(0,1),\quad S_n=\sum_{i=1}^n X_i",
    },
    {
        "name_ja": "ディオファントス方程式と整数論", "name_en": "Diophantine Equations",
        "definition": "整数解を求める多項式方程式。ピタゴラス方程式・フェルマーの最終定理・ペル方程式・ビール予想が代表例。ヒルベルトの第10問題（可決不能性）と深く関連する。",
        "impact_summary": "整数論の中心的研究対象。フェルマーの最終定理証明（1994年）は20世紀最大の数学的事件。",
        "subfield": "数学", "school_of_thought": "整数論", "era_start": 250,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Diophantine_equation",
        "mathematical_formulation": r"x^n+y^n=z^n\,(n\geq3\text{ has no positive integer solutions: Fermat's Last Theorem})",
    },
    {
        "name_ja": "ブラウワーの不動点定理", "name_en": "Brouwer Fixed-Point Theorem",
        "definition": "連続写像 f:D^n→D^n（D^nは閉n次元球）は必ず不動点を持つという定理。ゲーム理論のナッシュ均衡存在証明・経済均衡の存在定理に応用される。",
        "impact_summary": "ゲーム理論のナッシュ均衡存在・経済一般均衡・微分方程式の解の存在の証明に使われる。",
        "subfield": "数学", "school_of_thought": "位相幾何学", "era_start": 1910,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Brouwer_fixed-point_theorem",
        "mathematical_formulation": r"\forall f\in C(D^n,D^n),\,\exists x^*:f(x^*)=x^*",
    },
    {
        "name_ja": "代数的位相幾何学のホモトピー群", "name_en": "Homotopy Groups",
        "definition": "位相空間の「穴」の代数的不変量を与える群。基本群π_1・高次ホモトピー群π_n。π_n(S^n)=Z（球面の高次ホモトピー群）などが重要な計算結果。",
        "impact_summary": "多様体・素粒子物理の位相的分類・ソリトン・スキルミオンの位相的安定性の数学的基盤。",
        "subfield": "数学", "school_of_thought": "位相幾何学", "era_start": 1895,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Homotopy_group",
        "mathematical_formulation": r"\pi_n(X,x_0)=[(S^n,s_0),(X,x_0)],\quad\pi_1(S^1)\cong\mathbb{Z}",
    },
    {
        "name_ja": "ベクトル束とChern類", "name_en": "Vector Bundles and Chern Classes",
        "definition": "多様体上のベクトル束の位相的不変量としてのChern類。物理では磁気モノポール・トポロジカル不変量・ベリー位相のChern数として現れる。",
        "impact_summary": "現代数学・理論物理学のトポロジカル分類の中心道具。トポロジカル物質のバルク-境界対応の数学的基礎。",
        "subfield": "数学", "school_of_thought": "微分幾何学", "era_start": 1946,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Chern_class",
        "mathematical_formulation": r"c_1(L)=\frac{i}{2\pi}\Omega\in H^2(M,\mathbb{Z}),\quad\Omega=\bar{\partial}\partial\log h",
    },
    {
        "name_ja": "陳省身の微分幾何学", "name_en": "Chern-Weil Theory",
        "definition": "中国系数学者・陳省身（1911-2004）が確立した接続・曲率の特性類理論。Chern-Gauss-Bonnet定理・Chern-Weil準同型が核心。数学のノーベル賞ともいうべき 首個Wolf賞受賞。",
        "impact_summary": "ゲージ場理論・弦理論・トポロジカル物理の数学的基盤を与えた20世紀最大の幾何学者。",
        "subfield": "数学", "school_of_thought": "微分幾何学", "era_start": 1944,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Chern%E2%80%93Weil_theory",
        "mathematical_formulation": r"\int_M e(\nabla)=\chi(M)\quad(\text{Chern-Gauss-Bonnet})",
    },
    {
        "name_ja": "数学的帰納法と超限帰納法", "name_en": "Mathematical Induction and Transfinite Induction",
        "definition": "自然数の命題を全ての自然数について証明する数学的帰納法と、その超限順序数への拡張（超限帰納法・超限再帰）。カントールの集合論と深く結びつく。",
        "impact_summary": "数学的証明の基本技法。超限帰納法は無限集合論・形式的証明論の基盤。",
        "subfield": "数学", "school_of_thought": "数理論理学", "era_start": 1655,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Mathematical_induction",
        "mathematical_formulation": r"P(0)\wedge\forall n[P(n)\Rightarrow P(n+1)]\Rightarrow\forall n\,P(n)",
    },
    {
        "name_ja": "インド数学のブラフマスプタシッダーンタ", "name_en": "Brahmagupta's Mathematics",
        "definition": "7世紀のインドの数学者ブラフマグプタ（628年『ブラフマスプタシッダーンタ』）。ゼロと負数の演算規則・ペル方程式の解法・三角形面積公式（ブラフマグプタの公式）を記した。",
        "impact_summary": "ゼロを数として扱い負数・ペル方程式を体系化したインド数学の最高峰の一つ。",
        "subfield": "数学", "school_of_thought": "インド数学", "era_start": 628,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Brahmasphutasiddhanta",
        "mathematical_formulation": r"K=\sqrt{(s-a)(s-b)(s-c)(s-d)},\quad s=\frac{a+b+c+d}{2}\,(\text{Brahmagupta's formula})",
    },
]

STAT_BATCH = [
    {
        "name_ja": "マルコフ連鎖モンテカルロ法", "name_en": "Markov Chain Monte Carlo Methods",
        "definition": "複雑な確率分布からサンプルを生成するアルゴリズム群。Metropolis-Hastings法・ギブスサンプリング・ハミルトニアンモンテカルロ（HMC）が主要手法。",
        "impact_summary": "ベイズ統計推論・量子多体系・ゲノム解析・機械学習の事後分布計算に不可欠な計算手法。",
        "subfield": "統計学・計算科学", "school_of_thought": "計算統計学", "era_start": 1953,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Markov_chain_Monte_Carlo",
        "mathematical_formulation": r"\alpha(x,x')=\min\!\left(1,\frac{\pi(x')q(x|x')}{\pi(x)q(x'|x)}\right)\,(\text{MH acceptance ratio})",
    },
    {
        "name_ja": "因果推論とポテンシャル結果モデル", "name_en": "Causal Inference and Potential Outcomes",
        "definition": "Neyman-Rubinの潜在的結果フレームワーク（1923/1974）とJudea Pearlの構造因果モデル（SCM）。観察研究から因果効果を推定する統計手法の基盤。",
        "impact_summary": "疫学・経済学・機械学習における観察研究の因果効果推定の標準的理論的枠組み。",
        "subfield": "統計学・計算科学", "school_of_thought": "計量経済学・疫学", "era_start": 1974,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Rubin_causal_model",
        "mathematical_formulation": r"\tau=E[Y(1)-Y(0)],\quad\text{ATE}=E[Y_i(1)-Y_i(0)]",
    },
    {
        "name_ja": "情報幾何学", "name_en": "Information Geometry",
        "definition": "確率分布の族をリーマン多様体として扱い、フィッシャー情報行列をリーマン計量とする幾何学的統計理論。甘利俊一（日本）が体系化。",
        "impact_summary": "統計推定・機械学習・神経科学のネットワーク幾何を統一する数理科学の橋渡し理論。",
        "subfield": "統計学・計算科学", "school_of_thought": "数理統計学", "era_start": 1985,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Information_geometry",
        "mathematical_formulation": r"g_{ij}=E\!\left[\frac{\partial\log p}{\partial\theta^i}\frac{\partial\log p}{\partial\theta^j}\right]\,({\rm Fisher\,metric})",
    },
    {
        "name_ja": "変分ベイズ推定", "name_en": "Variational Bayesian Inference",
        "definition": "事後分布の変分近似（最適化問題としての推論）を行う手法。ELBOを最大化することで複雑なモデルの近似事後分布を得る。VAE・トピックモデルで広く使われる。",
        "impact_summary": "大規模ベイズモデル・深層生成モデルの近似推論の標準手法。VAEの理論的基盤。",
        "subfield": "統計学・計算科学", "school_of_thought": "機械学習", "era_start": 1998,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Variational_Bayesian_methods",
        "mathematical_formulation": r"\text{ELBO}=E_{q(z)}[\log p(x|z)]-\text{KL}(q(z)\|p(z))\leq\log p(x)",
    },
    {
        "name_ja": "ガウス過程回帰", "name_en": "Gaussian Process Regression",
        "definition": "関数空間上のベイズ推定法。観測データに対してガウス過程を事前分布として用い、不確実性の定量化を伴う予測を行う。GPRとも呼ばれる。",
        "impact_summary": "材料設計・ハイパーパラメータ最適化（ベイズ最適化）・時系列予測の不確実性定量化に広く用いられる。",
        "subfield": "統計学・計算科学", "school_of_thought": "機械学習", "era_start": 1978,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Gaussian_process",
        "mathematical_formulation": r"f(x)\sim\mathcal{GP}(m(x),k(x,x')),\quad p(f^*|X,y,x^*)\sim\mathcal{N}(\mu^*,\Sigma^*)",
    },
    {
        "name_ja": "動的計画法と強化学習の数学", "name_en": "Dynamic Programming and Bellman Equations",
        "definition": "最適制御・強化学習の数学的基盤。ベルマン最適方程式はQ学習・価値反復法・方策勾配法の理論的根拠を与える。",
        "impact_summary": "AlphaGo・自動運転・ロボット制御など現代強化学習のすべての数学的基盤。",
        "subfield": "統計学・計算科学", "school_of_thought": "計算機科学", "era_start": 1957,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Bellman_equation",
        "mathematical_formulation": r"Q^*(s,a)=\sum_{s'}P(s'|s,a)\!\left[R(s,a,s')+\gamma\max_{a'}Q^*(s',a')\right]",
    },
    {
        "name_ja": "スパース回帰とLasso", "name_en": "Sparse Regression and LASSO",
        "definition": "L1正則化（LASSO）・L2正則化（Ridge）・ElasticNet等のスパース推定手法。高次元データにおいて変数選択と係数推定を同時に行う。Tibshirani（1996）が提案。",
        "impact_summary": "ゲノムワイド関連解析・脳イメージング・金融リスク管理の高次元データ解析の標準技術。",
        "subfield": "統計学・計算科学", "school_of_thought": "統計学", "era_start": 1996,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Lasso_(statistics)",
        "mathematical_formulation": r"\hat{\beta}=\arg\min_\beta\left\{\|y-X\beta\|_2^2+\lambda\|\beta\|_1\right\}",
    },
    {
        "name_ja": "カーネル法とSVM", "name_en": "Kernel Methods and Support Vector Machines",
        "definition": "カーネル関数を用いて特徴空間への非線形マッピングを暗黙的に実行する機械学習手法群。SVMはマージン最大化超平面を見つける分類アルゴリズム。Vapnik（1995）が提案。",
        "impact_summary": "生物情報学・テキスト分類・画像認識における高精度分類の基盤手法。深層学習登場前の主流技術。",
        "subfield": "統計学・計算科学", "school_of_thought": "機械学習", "era_start": 1995,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Support_vector_machine",
        "mathematical_formulation": r"\max_\alpha\sum_i\alpha_i-\frac{1}{2}\sum_{ij}\alpha_i\alpha_j y_iy_j K(x_i,x_j),\quad K(x,x')=\phi(x)\cdot\phi(x')",
    },
    {
        "name_ja": "期待値最大化アルゴリズム", "name_en": "Expectation-Maximization Algorithm",
        "definition": "潜在変数を含む確率モデルの最尤推定を行うイテレーティブアルゴリズム。Eステップで期待値計算、Mステップでパラメータ最大化を繰り返す。Dempsterら（1977）が一般化。",
        "impact_summary": "混合ガウス分布・隠れマルコフモデル・欠損データ推定などに広く使われる統計的機械学習の基本アルゴリズム。",
        "subfield": "統計学・計算科学", "school_of_thought": "統計学", "era_start": 1977,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm",
        "mathematical_formulation": r"Q(\theta|\theta^{(t)})=E_{Z|X,\theta^{(t)}}[\log L(\theta;X,Z)],\quad\theta^{(t+1)}=\arg\max_\theta Q",
    },
    {
        "name_ja": "極値統計学", "name_en": "Extreme Value Theory",
        "definition": "確率変数の最大値・最小値の分布を研究する統計理論。一般化極値分布（GEV）・Gumbel・Fréchet・Weibull分布が中心。金融リスク・気象極端現象・構造安全性に応用。",
        "impact_summary": "100年洪水・VaR（バリュー・アット・リスク）・地震ハザード評価の統計的基盤。",
        "subfield": "統計学・計算科学", "school_of_thought": "統計学", "era_start": 1928,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Extreme_value_theory",
        "mathematical_formulation": r"F(x)=\exp\!\left[-\left(1+\xi\frac{x-\mu}{\sigma}\right)^{-1/\xi}\right]\,({\rm GEV})",
    },
    {
        "name_ja": "乱択アルゴリズムとラスベガス法", "name_en": "Randomized Algorithms",
        "definition": "確率的な選択を利用するアルゴリズム。ラスベガス法（常に正確、計算時間がランダム）・モンテカルロ法（計算時間固定、誤り確率あり）の二種。Miller-Rabin素数判定が典型例。",
        "impact_summary": "暗号・グラフアルゴリズム・近似計算において決定論的アルゴリズムより高速な多くの問題で有効。",
        "subfield": "統計学・計算科学", "school_of_thought": "理論計算機科学", "era_start": 1976,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Randomized_algorithm",
        "mathematical_formulation": r"P[\text{error}]\leq\delta,\quad T=O(n\log n)\,(\text{e.g., randomized quicksort})",
    },
    {
        "name_ja": "自然言語処理の統計モデル", "name_en": "Statistical Natural Language Processing",
        "definition": "テキストを確率モデルで扱うNLP手法。隠れマルコフモデル・n-gramモデル・単語埋め込み（Word2Vec・GloVe）・言語モデル（LM perplexity）が基礎。",
        "impact_summary": "機械翻訳・文書分類・情報検索・大規模言語モデルの前身となる統計的言語モデリングの確立。",
        "subfield": "統計学・計算科学", "school_of_thought": "機械学習", "era_start": 1988,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Statistical_language_model",
        "mathematical_formulation": r"P(w_1,\ldots,w_n)=\prod_{i=1}^n P(w_i|w_{i-n+1},\ldots,w_{i-1})\,(n\text{-gram})",
    },
    {
        "name_ja": "トポロジカルデータ解析", "name_en": "Topological Data Analysis",
        "definition": "持続ホモロジー（persistent homology）を用いてデータの位相的構造（穴・連結成分等）を多スケールで解析する手法。バーコード・パーシスタンス図が可視化ツール。",
        "impact_summary": "生体分子・材料構造・神経データの複雑なトポロジカル特徴を捉える数学的データサイエンス。",
        "subfield": "統計学・計算科学", "school_of_thought": "位相幾何学・データサイエンス", "era_start": 2002,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Topological_data_analysis",
        "mathematical_formulation": r"H_k(K_\epsilon):\,\text{k-th homology group at scale }\epsilon,\quad\text{barcode}=\{[b_i,d_i)\}",
    },
    {
        "name_ja": "圧縮センシングとスパース回復", "name_en": "Compressed Sensing",
        "definition": "スパース信号（非ゼロ成分が少ない信号）を通常必要よりはるかに少ない測定数から完全に復元できるという定理。DonohoとCandesが2004年頃に確立。MRIの高速化に応用。",
        "impact_summary": "MRI撮像時間短縮・レーダー・天文観測など多くの信号処理分野で革命的高速化をもたらした。",
        "subfield": "統計学・計算科学", "school_of_thought": "信号処理", "era_start": 2004,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Compressed_sensing",
        "mathematical_formulation": r"\min_x\|x\|_1\text{ s.t. }Ax=b,\quad m=O(k\log(n/k))\ll n",
    },
    {
        "name_ja": "ニューラルネットワークの普遍近似定理", "name_en": "Universal Approximation Theorem",
        "definition": "少なくとも1つの隠れ層を持つニューラルネットワークが、十分な幅があれば任意の連続関数を任意精度で近似できるという定理。Cybenkoら（1989）が証明。",
        "impact_summary": "深層学習の理論的正当性を与える基礎定理。なぜニューラルネットが様々なタスクで機能するかの理論的根拠。",
        "subfield": "統計学・計算科学", "school_of_thought": "機械学習", "era_start": 1989,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Universal_approximation_theorem",
        "mathematical_formulation": r"\|f-f_{\rm NN}\|_\infty<\epsilon,\quad f_{\rm NN}(x)=\sum_{j=1}^N v_j\sigma(w_j\cdot x+b_j)",
    },
    {
        "name_ja": "ゼータ関数とリーマン予想", "name_en": "Riemann Zeta Function and Riemann Hypothesis",
        "definition": "ゼータ関数ζ(s)=Σn^{-s}の解析接続と自明でない零点の配置。リーマン予想は全ての非自明な零点のReal partが1/2であると主張する最重要未解決問題。",
        "impact_summary": "素数分布の精密予測・暗号理論と深く結びつく数学最大の未解決問題の一つ。",
        "subfield": "統計学・計算科学", "school_of_thought": "整数論", "era_start": 1859,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Riemann_hypothesis",
        "mathematical_formulation": r"\zeta(s)=\sum_{n=1}^\infty n^{-s}=\prod_p(1-p^{-s})^{-1},\quad\text{RH: Re}(\rho)=1/2",
    },
    {
        "name_ja": "アフリカ数学の伝統的パターン", "name_en": "African Mathematical Traditions",
        "definition": "コンゴ盆地のルンガ族の砂絵（lusona）・ナミビアの幾何学的パターン・エジプトのリンド数学パピルス（紀元前1650年頃）など、アフリカ各地の数学的実践。",
        "impact_summary": "西洋数学史が見落としてきたサブサハラアフリカの組み合わせ論・幾何学的伝統を再評価する研究分野。",
        "subfield": "統計学・計算科学", "school_of_thought": "民族数学", "era_start": -1650,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/African_mathematics",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "量子機械学習", "name_en": "Quantum Machine Learning",
        "definition": "量子コンピュータの重ね合わせ・もつれを利用した機械学習アルゴリズム。変分量子固有値ソルバー（VQE）・量子ニューラルネットワーク・HHL線形方程式ソルバー等。",
        "impact_summary": "量子コンピューティング×機械学習の融合領域。一部問題での量子スピードアップを目指す。",
        "subfield": "統計学・計算科学", "school_of_thought": "量子情報科学", "era_start": 2014,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_machine_learning",
        "mathematical_formulation": r"|\psi(\theta)\rangle=U(\theta)|0\rangle,\quad L=\langle\psi(\theta)|H|\psi(\theta)\rangle\,({\rm VQE})",
    },
    {
        "name_ja": "自動微分とテンソル計算フレームワーク", "name_en": "Automatic Differentiation",
        "definition": "コンピュータプログラムの微分を自動的に計算する技術。前向きモード・後ろ向きモード（バックプロップ）があり、深層学習フレームワーク（PyTorch・TensorFlow）の核心。",
        "impact_summary": "深層学習の実用化を支えるソフトウェア技術の基盤。任意の計算グラフの勾配を効率的に計算する。",
        "subfield": "統計学・計算科学", "school_of_thought": "計算機科学", "era_start": 1970,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Automatic_differentiation",
        "mathematical_formulation": r"\frac{\partial L}{\partial w_i}=\frac{\partial L}{\partial o}\cdot\frac{\partial o}{\partial w_i}\,({\rm reverse\,mode})",
    },
    {
        "name_ja": "形式言語理論とチョムスキー階層", "name_en": "Formal Language Theory and Chomsky Hierarchy",
        "definition": "Noam Chomskyが1956年に提案した文法の階層（正則・文脈自由・文脈依存・再帰的可算）。コンパイラ設計・自然言語処理・計算能力の分類の理論的基盤。",
        "impact_summary": "コンパイラ・プログラミング言語設計・計算複雑性理論の数学的基盤。チューリングマシンと密接に関係。",
        "subfield": "統計学・計算科学", "school_of_thought": "理論計算機科学", "era_start": 1956,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Chomsky_hierarchy",
        "mathematical_formulation": r"\text{Type 3}\subset\text{Type 2}\subset\text{Type 1}\subset\text{Type 0}",
    },
]

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    m = insert_batch(conn, MATH_BATCH)
    s = insert_batch(conn, STAT_BATCH)
    total = conn.execute("SELECT COUNT(*) FROM natural_discovery").fetchone()[0]
    conn.close()
    print(f"Batch25 math+stat: {m+s} inserted (math={m}, stat={s}). Total: {total}")
