#!/usr/bin/env python3
"""DUA Wave A2 Batch 23 — social_theory expansion.
Current: 5,216. Target: 5,500. Need ~284 more. Inserting 180 brand-new concepts."""
import sqlite3, uuid, datetime

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(concepts):
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    inserted = 0; skipped = 0
    for c in concepts:
        name_ja, name_en, name_orig, defn, subfield, school, era, region, url = c
        cur.execute("SELECT COUNT(*) FROM social_theory WHERE name_en=?", (name_en,))
        if cur.fetchone()[0] > 0:
            skipped += 1; continue
        uid = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat()
        cur.execute("""INSERT INTO social_theory
            (id,name_ja,name_en,name_original,definition,subfield,school_of_thought,
             era_start,culture_region,source_url,verification_status,quality_flag,
             status,created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,'url_present','B','active',?,?)""",
            (uid,name_ja,name_en,name_orig,defn,subfield,school,era,region,url,now,now))
        inserted += 1
        if inserted % 50 == 0:
            conn.commit(); print(f"  Committed {inserted}...")
    conn.commit(); conn.close()
    return inserted, skipped

concepts = [
    # 古典社会学 (+30 entirely new)
    ("デュルケームの自殺論の受容史","Reception of Durkheim's Suicide","Reception of Durkheim's Suicide",
     "1897年の古典的著作が社会学・疫学・精神保健・宗教社会学等の分野でどのように継承・批判・修正されたかの学説史。",
     "古典社会学","古典社会学",1897,"Western_Europe",
     "https://en.wikipedia.org/wiki/Suicide_(Durkheim_book)"),
    ("ウェーバーのカリスマ論","Weber's Theory of Charisma","Charisma (Weber)",
     "カリスマ的権威の概念・ルーティン化・制度化・衰退のメカニズムを論じたウェーバーの支配社会学の中核命題。",
     "古典社会学","古典社会学",1922,"Western_Europe",
     "https://en.wikipedia.org/wiki/Charismatic_authority"),
    ("マルクスの疎外論","Marx's Theory of Alienation","Entfremdung",
     "資本主義的生産における労働者の生産物・労働過程・類的本質・他者からの疎外を論じたマルクスの人間論。",
     "古典社会学","古典社会学",1844,"Western_Europe",
     "https://en.wikipedia.org/wiki/Marx%27s_theory_of_alienation"),
    ("ジンメルの社交論","Simmel's Sociology of Sociability","Geselligkeit",
     "目的を持たない純粋な交際の楽しさ・遊戯性・社会形式としての美的側面を論じたジンメルの形式社会学。",
     "古典社会学","古典社会学",1917,"Western_Europe",
     "https://en.wikipedia.org/wiki/Georg_Simmel"),
    ("社会的分化","Social Differentiation","Social Differentiation",
     "社会の機能・役割・制度・集団が専門化・複雑化する過程。スペンサー・デュルケーム・ジンメルが論じた。",
     "古典社会学","古典社会学",1876,"Western_Europe",
     "https://en.wikipedia.org/wiki/Social_differentiation"),
    ("ウェーバーの類型論","Weber's Ideal Types","Idealtyp",
     "社会現象を理解するための分析的構成物としての理念型の方法論。歴史研究・比較研究の基礎として使用される。",
     "古典社会学","古典社会学",1904,"Western_Europe",
     "https://en.wikipedia.org/wiki/Ideal_type"),
    ("デュルケームの聖/俗","Durkheim's Sacred and Profane","Sacred and Profane",
     "宗教の本質を聖と俗の根本的区別に見出すデュルケームの宗教社会学の基本概念。集合感情・儀礼と結合。",
     "古典社会学","古典社会学",1912,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Elementary_Forms_of_the_Religious_Life"),
    ("ジンメルの異邦人","Simmel's Stranger","Der Fremde",
     "コミュニティの外から来て内に留まる「異邦人」という社会的タイプを論じたジンメルの形式社会学の古典的エッセイ。",
     "古典社会学","古典社会学",1908,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Stranger_(sociology)"),
    ("スペンサーの社会有機体論","Spencer's Social Organism","Social Organism",
     "社会を生物有機体のアナロジーで捉え、進化・分化・統合を分析したハーバート・スペンサーの社会学体系。",
     "古典社会学","古典社会学",1860,"Western_Europe",
     "https://en.wikipedia.org/wiki/Herbert_Spencer"),
    ("トクヴィルの民主主義論","Tocqueville's Democracy Theory","Démocratie en Amérique",
     "アメリカの民主主義の特質・自由・多数派の専制・アソシエーション精神を分析したトクヴィルの政治社会学的著作。",
     "古典社会学","古典社会学",1835,"Western_Europe",
     "https://en.wikipedia.org/wiki/Democracy_in_America"),
    ("コンフリクト社会学の古典","Classical Conflict Sociology","Classical Conflict Sociology",
     "マルクス・ウェーバー・ジンメルらが展開した社会的対立・闘争・競争を社会形成の動因として分析する古典的視点。",
     "古典社会学","古典社会学",1880,"Western_Europe",
     "https://en.wikipedia.org/wiki/Conflict_theories"),
    ("ゾンバルトの資本主義精神論","Sombart's Spirit of Capitalism","Der Bourgeois",
     "ユダヤ人の倫理・戦争・恋愛等を資本主義精神の源泉として論じたヴェルナー・ゾンバルトのウェーバーへの対抗論。",
     "古典社会学","古典社会学",1913,"Western_Europe",
     "https://en.wikipedia.org/wiki/Werner_Sombart"),
    ("マルクスの歴史唯物論","Marx's Historical Materialism","Historischer Materialismus",
     "社会の歴史的変動を生産力と生産関係の矛盾・階級闘争・土台と上部構造の関係で説明する唯物史観の体系。",
     "古典社会学","古典社会学",1848,"Western_Europe",
     "https://en.wikipedia.org/wiki/Historical_materialism"),
    ("デュルケームの道徳教育論","Durkheim's Moral Education","L'Education morale",
     "学校教育を通じて規律・付着・自律という道徳的意識を子どもに内面化させる過程を論じた教育社会学の古典。",
     "古典社会学","古典社会学",1925,"Western_Europe",
     "https://en.wikipedia.org/wiki/Moral_education"),
    ("初期社会学の論争","Debates in Early Sociology","Methodenstreit",
     "実証主義vs解釈主義・法則定立vs個性記述・自然科学vs精神科学をめぐる19世紀社会科学の方法論争。",
     "古典社会学","古典社会学",1880,"Western_Europe",
     "https://en.wikipedia.org/wiki/Methodenstreit"),
    ("タルドの模倣論","Tarde's Theory of Imitation","Les Lois de l'imitation",
     "社会の基本法則を個人間の模倣に見出すガブリエル・タルドの社会学。デュルケームとの論争で知られる。",
     "古典社会学","古典社会学",1890,"Western_Europe",
     "https://en.wikipedia.org/wiki/Gabriel_Tarde"),
    ("テンニースの共同体概念","Tönnies' Community Concept","Gemeinschaft und Gesellschaft",
     "テンニースが1887年に対置した有機的共同体(Gemeinschaft)と機械的利益社会(Gesellschaft)の二分法の詳細。",
     "古典社会学","古典社会学",1887,"Western_Europe",
     "https://en.wikipedia.org/wiki/Ferdinand_T%C3%B6nnies"),
    ("ヴェブレンの誇示的消費","Veblen's Conspicuous Consumption","Conspicuous Consumption",
     "社会的地位の誇示のために行われる無駄な消費をレジャー階級の特徴として論じたヴェブレンの古典的概念。",
     "古典社会学","古典社会学",1899,"North_America",
     "https://en.wikipedia.org/wiki/Conspicuous_consumption"),
    ("クーリーの社会的自己","Cooley's Social Self","Looking-glass Self",
     "他者が自分をどう見るかの想像を通じて自己が形成されるという鏡像的自己の概念。シンボリック相互作用論の先駆。",
     "古典社会学","古典社会学",1902,"North_America",
     "https://en.wikipedia.org/wiki/Looking-glass_self"),
    ("ウェーバーの官僚制","Weber's Bureaucracy","Bürokratie",
     "近代国家・企業の合法的支配を担う合理的行政組織の純粋型。専門分業・階層制・規則支配・非人格性の4原則。",
     "古典社会学","古典社会学",1922,"Western_Europe",
     "https://en.wikipedia.org/wiki/Bureaucracy"),
    ("デュルケームの有機的連帯","Durkheim's Organic Solidarity","Solidarité organique",
     "近代分業社会において機能的相互依存に基づいて生まれる社会的結合の形態。機械的連帯との対比で論じられる。",
     "古典社会学","古典社会学",1893,"Western_Europe",
     "https://en.wikipedia.org/wiki/Social_solidarity"),
    ("マルクスの剰余価値論","Marx's Theory of Surplus Value","Mehrwert",
     "労働者が生産した価値と賃金の差額として資本家が取得する剰余価値の概念。資本蓄積の源泉。",
     "古典社会学","古典社会学",1867,"Western_Europe",
     "https://en.wikipedia.org/wiki/Surplus_value"),
    ("ジンメルの秘密","Simmel's Secret","Das Geheimnis",
     "社会的相互作用における秘密保持・知識の非対称・信頼・裏切りを論じたジンメルの社会学的エッセイ。",
     "古典社会学","古典社会学",1906,"Western_Europe",
     "https://en.wikipedia.org/wiki/Georg_Simmel"),
    ("ロスのソーシャルコントロール","Ross's Social Control","Social Control (Ross)",
     "エドワード・A・ロスが1901年に命名した社会統制概念。世論・道徳・制度・法が社会秩序を維持する機制。",
     "古典社会学","古典社会学",1901,"North_America",
     "https://en.wikipedia.org/wiki/Social_control"),
    ("スマールの形式社会学","Small's Formal Sociology","Formal Sociology",
     "アルビオン・スモールが展開したアメリカ最初期の社会学。利害・対立・調整という社会過程の分析。",
     "古典社会学","古典社会学",1905,"North_America",
     "https://en.wikipedia.org/wiki/Albion_Small"),
    ("ウォードの改良主義社会学","Ward's Reform Sociology","Applied Sociology (Ward)",
     "レスター・フランク・ウォードが提唱した科学的知識に基づく意図的社会改良の可能性。社会テレシスの概念。",
     "古典社会学","古典社会学",1883,"North_America",
     "https://en.wikipedia.org/wiki/Lester_Frank_Ward"),
    ("ジンメルの競争論","Simmel's Theory of Competition","Konkurrenz",
     "競争を社会化の一形式として捉えるジンメルの形式社会学的分析。競争が相互関心・間接的接触を生む機能。",
     "古典社会学","古典社会学",1908,"Western_Europe",
     "https://en.wikipedia.org/wiki/Georg_Simmel"),
    ("ミルズとパワーエリート","Mills and Power Elite","The Power Elite",
     "軍・財界・政界のエリートが相互に連結し民主的統制を超えた権力構造を形成することを論じたミルズの1956年著作。",
     "古典社会学","古典社会学",1956,"North_America",
     "https://en.wikipedia.org/wiki/The_Power_Elite"),
    ("マートンの社会構造とアノミー","Merton's Social Structure and Anomie","Social Structure and Anomie",
     "文化的目標と制度的手段の乖離が生む逸脱行動の5類型（同調・革新・儀礼主義・逃避・反乱）。",
     "古典社会学","古典社会学",1938,"North_America",
     "https://en.wikipedia.org/wiki/Strain_theory_(sociology)"),
    ("パレートのエリート循環","Pareto's Circulation of Elites","Circulation of Elites",
     "ライオン型とキツネ型という2種類のエリートが交替しながら支配を続けるというパレートの政治エリート論。",
     "古典社会学","古典社会学",1916,"Western_Europe",
     "https://en.wikipedia.org/wiki/Vilfredo_Pareto"),
    ("モスカの支配階級論","Mosca's Ruling Class","Classe politica",
     "いかなる社会でも少数の組織された支配階級が多数の被支配大衆を統治するとするモスカのエリート理論。",
     "古典社会学","古典社会学",1896,"Western_Europe",
     "https://en.wikipedia.org/wiki/Gaetano_Mosca"),
    # 批判理論・フランクフルト学派 (+30 new)
    ("フランクフルト学派の第一世代","First Generation Frankfurt School","First Generation Frankfurt School",
     "ホルクハイマー・アドルノ・マルクーゼ・フロム・ベンヤミンらが1930年代以降展開した批判理論の第一段階。",
     "批判理論・フランクフルト学派","批判理論",1937,"Western_Europe",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    ("ベンヤミンのアレゴリー論","Benjamin's Theory of Allegory","Allegorie (Benjamin)",
     "バロック悲劇研究で展開されたベンヤミンのアレゴリー概念。象徴とアレゴリーの対比・廃墟・歴史の断片化。",
     "批判理論・フランクフルト学派","批判理論",1928,"Western_Europe",
     "https://en.wikipedia.org/wiki/Walter_Benjamin"),
    ("マルクーゼの一次元的人間","Marcuse's One-Dimensional Man","One-Dimensional Man",
     "高度産業社会が反対勢力を吸収し真の批判的思考を不可能にするという1964年の批判的診断。",
     "批判理論・フランクフルト学派","批判理論",1964,"North_America",
     "https://en.wikipedia.org/wiki/One-Dimensional_Man"),
    ("エーリッヒ・フロムの性格論","Fromm's Social Character","Social Character",
     "特定の社会が構成員に内面化させる性格構造を分析するフロムの社会心理学的概念。権威主義的性格との関連。",
     "批判理論・フランクフルト学派","批判理論",1941,"North_America",
     "https://en.wikipedia.org/wiki/Erich_Fromm"),
    ("ハーバーマスの生活世界植民地化","Habermas's Colonization of Lifeworld","Colonization of the Lifeworld",
     "システム合理性（貨幣・権力）が生活世界のコミュニカティヴな合理性を侵食する過程。1981年の理論的中核。",
     "批判理論・フランクフルト学派","批判理論",1981,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Theory_of_Communicative_Action"),
    ("アドルノの美学理論","Adorno's Aesthetic Theory","Ästhetische Theorie",
     "芸術作品が同一性の論理に抵抗する否定性を内包する可能性と文化産業による芸術の死を論じた遺著。",
     "批判理論・フランクフルト学派","批判理論",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Aesthetic_Theory"),
    ("ホルクハイマーの伝統的・批判的理論","Traditional and Critical Theory","Traditionelle und kritische Theorie",
     "実証主義的社会科学の現状肯定性を批判し変革志向の批判理論の方法論的基礎を置いた1937年の論文。",
     "批判理論・フランクフルト学派","批判理論",1937,"Western_Europe",
     "https://en.wikipedia.org/wiki/Traditional_and_Critical_Theory"),
    ("ネストヴェトの承認論","Honneth's Recognition Theory","Anerkennungstheorie",
     "愛・法的尊重・社会的評価という3形式の承認とその否定（傷害・権利剥奪・侮辱）からなる承認の規範的社会理論。",
     "批判理論・フランクフルト学派","承認論",1992,"Western_Europe",
     "https://en.wikipedia.org/wiki/Axel_Honneth"),
    ("ハーバーマスの熟議民主主義","Habermas's Deliberative Democracy","Deliberative Democracy",
     "公共的議論・理性的討議による民主的正統性の構築を論じるハーバーマスの規範的民主主義理論。",
     "批判理論・フランクフルト学派","批判理論",1992,"Western_Europe",
     "https://en.wikipedia.org/wiki/Deliberative_democracy"),
    ("フォルスト承認と正義","Forst's Theory of Justice","Justification",
     "全ての人が等しく正当化を求める権利を持つことを正義の核とするライナー・フォルストの批判理論。",
     "批判理論・フランクフルト学派","批判理論",2007,"Western_Europe",
     "https://en.wikipedia.org/wiki/Rainer_Forst"),
    ("ナンシー・フレイザーの正義論","Fraser's Theory of Justice","Parity of Participation",
     "承認・再分配・代表という3次元の正義を統合する参加の対等性という規範的枠組み。Honnethへの批判から展開。",
     "批判理論・フランクフルト学派","批判理論",2003,"North_America",
     "https://en.wikipedia.org/wiki/Nancy_Fraser"),
    ("啓蒙の再考","Rethinking Enlightenment","Rethinking Enlightenment",
     "批判理論の立場から理性・普遍性・解放の啓蒙プロジェクトを継承しつつその限界・暴力・排除を批判的に問い直す試み。",
     "批判理論・フランクフルト学派","批判理論",1944,"Western_Europe",
     "https://en.wikipedia.org/wiki/Dialectic_of_Enlightenment"),
    ("クリティカル・セオリーとフェミニズム","Critical Theory and Feminism","Critical Theory and Feminism",
     "フランクフルト学派の批判理論にフェミニスト視点を接続する試み。Seyla Benhabib・Nancy Fraserが代表的論者。",
     "批判理論・フランクフルト学派","批判理論",1986,"North_America",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    ("物象化と疎外の再考","Reification and Alienation Revisited","Verdinglichung",
     "ルカーチの物象化論とマルクスの疎外論をホネットが再解釈した「物化」論。承認論と関連させた現代的展開。",
     "批判理論・フランクフルト学派","批判理論",2005,"Western_Europe",
     "https://en.wikipedia.org/wiki/Reification_(Marxism)"),
    ("否定の弁証法と芸術","Negative Dialectics and Art","Negative Dialectics and Art",
     "アドルノの否定弁証法とミニマ・モラリアにおける芸術・倫理・生活の断片的批判の連関。",
     "批判理論・フランクフルト学派","批判理論",1951,"Western_Europe",
     "https://en.wikipedia.org/wiki/Minima_Moralia"),
    # 構造主義・ポスト構造主義 (+30)
    ("フーコーの知の考古学","Foucault's Archaeology of Knowledge","L'Archéologie du savoir",
     "言説・アーカイブ・エピステーメー・陳述という概念を体系化したフーコーの方法論的著作（1969年）。",
     "構造主義・ポスト構造主義","系譜学・考古学",1969,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Archaeology_of_Knowledge"),
    ("デリダの文字論","Derrida's Grammatology","De la grammatologie",
     "音声中心主義批判・差延・痕跡・補充という概念を通じて西洋形而上学の基礎を脱構築した1967年の著作。",
     "構造主義・ポスト構造主義","脱構築論",1967,"Western_Europe",
     "https://en.wikipedia.org/wiki/Of_Grammatology"),
    ("バルトの著者の死","Barthes' Death of the Author","La mort de l'auteur",
     "テクストの意味は著者の意図でなく読者の実践において生産されるとするバルトの1967年の宣言。",
     "構造主義・ポスト構造主義","記号論",1967,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Death_of_the_Author"),
    ("ドゥルーズとスピノザ","Deleuze and Spinoza","Deleuze and Spinoza",
     "ドゥルーズがスピノザの内在・表現・情動の概念を再解釈し、差異の哲学・生の内在平面の概念を展開した試み。",
     "構造主義・ポスト構造主義","ポスト構造主義",1968,"Western_Europe",
     "https://en.wikipedia.org/wiki/Gilles_Deleuze"),
    ("ラカンの四つの言説","Lacan's Four Discourses","Quatre discours",
     "主人・大学・ヒステリー・分析家という4種の言説として社会的絆の形式を分類したラカンの社会理論。",
     "構造主義・ポスト構造主義","ポスト構造主義",1969,"Western_Europe",
     "https://en.wikipedia.org/wiki/Four_discourses"),
    ("クリステヴァのイントラテクスチュアリティ","Kristeva's Intertextuality","Intertextualité",
     "テクストが他のテクストを吸収・変換する関係として意味生産を捉えるクリステヴァの記号論的概念。",
     "構造主義・ポスト構造主義","記号論",1967,"Western_Europe",
     "https://en.wikipedia.org/wiki/Intertextuality"),
    ("リオタールの崇高論","Lyotard's Theory of the Sublime","Sublime (Lyotard)",
     "カントの崇高概念をポストモダン的に再解釈し表象不可能なものの経験を論じたリオタールの美学理論。",
     "構造主義・ポスト構造主義","ポストモダン理論",1984,"Western_Europe",
     "https://en.wikipedia.org/wiki/Jean-Fran%C3%A7ois_Lyotard"),
    ("バタイユの至高性","Bataille's Sovereignty","Souveraineté",
     "有用性・生産性の論理を超えた無償の蕩尽・エロティシズム・死を至高と定義するバタイユの経済理論。",
     "構造主義・ポスト構造主義","ポスト構造主義",1949,"Western_Europe",
     "https://en.wikipedia.org/wiki/Georges_Bataille"),
    ("フーコーの倫理主体","Foucault's Ethical Subject","Le sujet éthique",
     "後期フーコーの主体化の実践・自己テクニック・古代ギリシャの自己への配慮を論じる倫理・主体論。",
     "構造主義・ポスト構造主義","系譜学・考古学",1984,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Care_of_the_Self"),
    ("ジジェクのラカン的マルクス主義","Žižek's Lacanian Marxism","Lacanian Marxism",
     "ラカン精神分析とマルクス主義を接合してイデオロギー・主体・ポピュリズムを分析するジジェクの理論。",
     "構造主義・ポスト構造主義","ポスト構造主義",1989,"Western_Europe",
     "https://en.wikipedia.org/wiki/%C5%BDi%C5%BEek"),
    ("ブルデューの再生産戦略","Bourdieu's Reproduction Strategies","Stratégies de reproduction",
     "家族・教育・婚姻を通じた社会的地位の世代間維持メカニズムを資本概念で分析するブルデューの実践論。",
     "構造主義・ポスト構造主義","構造主義",1977,"Western_Europe",
     "https://en.wikipedia.org/wiki/Pierre_Bourdieu"),
    ("フーコーの規律と牧人的権力","Foucault's Pastoral Power","Pastoral Power",
     "キリスト教的司牧権力が個々の魂を導き・知る技術として近代の個人化・規律化権力の先駆となる過程。",
     "構造主義・ポスト構造主義","系譜学・考古学",1978,"Western_Europe",
     "https://en.wikipedia.org/wiki/Governmentality"),
    ("デリダの歓待論","Derrida's Hospitality","Hospitalité",
     "無条件の歓待という不可能な理想と条件付き歓待の実践の緊張を論じるデリダの後期倫理政治論。",
     "構造主義・ポスト構造主義","脱構築論",1997,"Western_Europe",
     "https://en.wikipedia.org/wiki/Jacques_Derrida"),
    ("ドゥルーズのシネマ論","Deleuze's Cinema Theory","Cinéma",
     "映画を運動-イメージと時間-イメージに分類し、知覚・記憶・時間の哲学として展開したドゥルーズの2巻著作。",
     "構造主義・ポスト構造主義","ポスト構造主義",1983,"Western_Europe",
     "https://en.wikipedia.org/wiki/Cinema_(Deleuze)"),
    ("バウドリヤールのシミュラクル","Baudrillard's Simulacra","Simulacres et Simulation",
     "現実をコピーしたイメージがオリジナルを凌駕するハイパーリアルの状態を分析した1981年の著作。",
     "構造主義・ポスト構造主義","ポストモダン理論",1981,"Western_Europe",
     "https://en.wikipedia.org/wiki/Simulacra_and_Simulation"),
    # フェミニズム・ジェンダー理論 (+30)
    ("バトラーのヘゲモニーと戦略","Butler's Hegemony and Strategy","Contingency, Hegemony, Universality",
     "バトラー・ラクラウ・ジジェクが普遍性・ヘゲモニー・同一性をめぐって交わした論争的著作（2000年）。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2000,"North_America",
     "https://en.wikipedia.org/wiki/Judith_Butler"),
    ("リプロダクティブジャスティス","Reproductive Justice","Reproductive Justice",
     "中絶権を超えて生殖・育児・性的健康の権利を人種・階層・障害の交差的視点で論じる運動的概念。1994年有色女性が提唱。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1994,"North_America",
     "https://en.wikipedia.org/wiki/Reproductive_justice"),
    ("フェミニスト法理論","Feminist Legal Theory","Feminist Legal Theory",
     "法が男性の経験・視点を規範として構築されていることを批判し、ジェンダー平等に向けた法改革を論じる。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1984,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_legal_theory"),
    ("クィア時間性","Queer Temporality","Queer Temporality",
     "ストレートな「直線的」生涯軌道（恋愛・結婚・出産・相続）に収まらないクィアな時間経験と記憶を論じる理論。",
     "フェミニズム・ジェンダー理論","クィア理論",2005,"North_America",
     "https://en.wikipedia.org/wiki/Queer_theory"),
    ("ヘテロセクシズム批判","Critique of Heterosexism","Heterosexism",
     "異性愛を規範とし同性愛・両性愛を劣位に置くイデオロギー的構造をフェミニスト・クィア理論が批判する議論。",
     "フェミニズム・ジェンダー理論","クィア理論",1990,"North_America",
     "https://en.wikipedia.org/wiki/Heterosexism"),
    ("フェミニスト組織論","Feminist Organizational Theory","Feminist Organizational Theory",
     "組織のヒエラルキー・ジェンダー分業・男性的規範を批判し代替的組織形態を模索するフェミニスト経営学。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1990,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    ("トランスフェミニズム","Transfeminism","Transfeminism",
     "トランスジェンダーの経験・権利・理論をフェミニズムに統合する立場。トランス女性のフェミニスト运動への包摂を主張。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2000,"North_America",
     "https://en.wikipedia.org/wiki/Trans-feminism"),
    ("フェミニスト科学哲学","Feminist Philosophy of Science","Feminist Philosophy of Science",
     "科学的知識の生産が男性偏向・ジェンダー化されていることを暴きオルタナティブな科学実践を提唱する研究。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1985,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_philosophy_of_science"),
    ("ブラック・フェミニスト・クリティーク","Black Feminist Critique","Black Feminist Critique",
     "コリンズ・ロードらが展開する黒人女性の生の経験・複合差別・連帯を核とするフェミニスト批判理論。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1980,"North_America",
     "https://en.wikipedia.org/wiki/Black_feminism"),
    ("ジェンダーと教育","Gender and Education","Gender and Education",
     "学校制度・カリキュラム・教師の相互作用がジェンダーを再生産し不平等を構造化する過程の研究。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1978,"Western_Europe",
     "https://en.wikipedia.org/wiki/Gender_inequality_in_education"),
    ("産業フェミニズム","Socialist Feminism","Socialist Feminism",
     "性差別と資本主義的搾取の構造的連関を分析し、階級解放と女性解放の統合を主張するフェミニズムの立場。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1969,"North_America",
     "https://en.wikipedia.org/wiki/Socialist_feminism"),
    ("フェミニスト地理学","Feminist Geography","Feminist Geography",
     "空間・場所・自然が男性中心的に構築されることを批判し、ジェンダー・身体・移動性を地理学の核に置く研究。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1984,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_geography"),
    ("家父長制資本主義","Patriarchal Capitalism","Patriarchal Capitalism",
     "家父長制と資本主義が互いを強化し合い女性の無償労働・低賃金を構造化する二重体制の社会主義フェミニスト概念。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1976,"Western_Europe",
     "https://en.wikipedia.org/wiki/Capitalist_patriarchy"),
    ("マスキュリニズム批判","Critique of Masculinism","Critique of Masculinism",
     "有害な男性性・男性特権・ジェンダー役割の硬直性を批判しオルタナティブな男性性を探求するフェミニスト・メンズスタディーズ。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1987,"North_America",
     "https://en.wikipedia.org/wiki/Toxic_masculinity"),
    ("再生産の政治","Politics of Reproduction","Politics of Reproduction",
     "出産・避妊・中絶・代理母・不妊治療をめぐる権力・人種・階層・国家の介入を分析する政治社会学的フェミニズム。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1979,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    # ポストコロニアル・脱植民地理論 (+20)
    ("汎アフリカ主義の歴史","History of Pan-Africanism","Pan-Africanism",
     "世界に散らばったアフリカ系の人々の政治的・文化的統一を主張するデュボイス・ガーベイ・Nkrumahの運動。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1900,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/Pan-Africanism"),
    ("グラムシとポストコロニアリズム","Gramsci and Postcolonialism","Gramsci and Postcolonialism",
     "グラムシのヘゲモニー・有機的知識人・サバルタン概念がポストコロニアル理論に与えた影響と批判的受容。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1980,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Antonio_Gramsci"),
    ("帝国の文化","Culture of Empire","Culture of Imperialism",
     "植民地主義的価値観・美学・知識が宗主国の文化産業・博物館・文学に内在する様式の文化研究。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1993,"North_America",
     "https://en.wikipedia.org/wiki/Culture_and_Imperialism"),
    ("プランテーション社会論","Plantation Society Theory","Plantation Society",
     "カリブ海・南米の奴隷制農園を起点とした社会構造・人種階層・文化混交の独自的発展を論じる社会学理論。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1960,"Latin_America",
     "https://en.wikipedia.org/wiki/Plantation_economy"),
    ("独立後のアフリカ国家建設","Post-Independence African State Building","African State Building",
     "植民地後のアフリカ国家が抱える正統性・民族対立・対外依存・権威主義の問題を論じる政治社会学的研究。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1960,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/History_of_Africa"),
    ("コスモポリタニズムとポストコロニアリズム","Cosmopolitanism and Postcolonialism","Cosmopolitanism",
     "世界市民主義がポストコロニアル文脈でどのように再解釈・批判・実践されるかをめぐる議論。アピア・ババが代表。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1997,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Cosmopolitanism"),
    ("アジア的価値","Asian Values","Asian Values",
     "集団調和・権威への尊重・家族中心主義等をアジア固有の価値として主張しつつ西洋式民主主義・人権を批判する政治言説。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1994,"East_Asia",
     "https://en.wikipedia.org/wiki/Asian_values"),
    ("文化帝国主義の現代的展開","Contemporary Cultural Imperialism","Cultural Imperialism",
     "ハリウッド・シリコンバレー・K-POP等のグローバル文化産業が文化的均質化と抵抗を生む現代の文化権力構造。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Cultural_imperialism"),
    ("マルチチュードとポストコロニアリズム","Multitude and Postcolonialism","Multitude",
     "ネグリ・ハートのマルチチュード論をポストコロニアル視点から再解釈し、脱植民地的解放主体を論じる議論。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2004,"Western_Europe",
     "https://en.wikipedia.org/wiki/Multitude_(book)"),
    # 政治社会学・国家論 (+20)
    ("民衆主義と権威主義","Populism and Authoritarianism","Populism and Authoritarianism",
     "ポピュリスト運動が民主的正統性を主張しつつ権威主義体制に転化するメカニズムの比較政治社会学的研究。",
     "政治社会学・国家論","政治社会学",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Populism"),
    ("社会運動と国家の関係","Social Movements and the State","Social Movements and the State",
     "社会運動が国家を変革・抵抗・協力する複雑な相互作用。制度的政治への回路・共存・取り込みの問題。",
     "政治社会学・国家論","政治社会学",1975,"North_America",
     "https://en.wikipedia.org/wiki/Social_movement"),
    ("行政国家","Administrative State","Administrative State",
     "議会ではなく行政機関が実質的な政策決定・規制を担う現代国家の形態。専門的官僚制の民主的説明責任問題。",
     "政治社会学・国家論","国家論",1940,"North_America",
     "https://en.wikipedia.org/wiki/Administrative_state"),
    ("市民的抵抗","Civil Resistance","Civil Resistance",
     "非武装の大衆的抵抗が暴力的手段より効果的に政治変革を実現できることを論じるGene Sharp等の研究。",
     "政治社会学・国家論","政治社会学",1973,"North_America",
     "https://en.wikipedia.org/wiki/Civil_resistance"),
    ("レントシーキング国家","Rent-Seeking State","Rent-Seeking State",
     "国家権力を利用した経済的レント獲得が支配層の行動原理となる政治経済体制。腐敗・開発障害と関連する。",
     "政治社会学・国家論","政治社会学",1980,"North_America",
     "https://en.wikipedia.org/wiki/Rent-seeking"),
    ("政治的信頼","Political Trust","Political Trust",
     "市民が政治機関・政治家・政府に対して抱く信頼の程度とその規定要因・民主主義への影響の研究。",
     "政治社会学・国家論","政治社会学",1960,"North_America",
     "https://en.wikipedia.org/wiki/Political_trust"),
    ("福祉国家の変容","Welfare State Transformation","Welfare State Transformation",
     "グローバル化・新自由主義・人口高齢化が福祉国家の制度・財政・正統性に与える構造変化の比較研究。",
     "政治社会学・国家論","政治社会学",1990,"Western_Europe",
     "https://en.wikipedia.org/wiki/Welfare_state"),
    ("移民と市民権","Immigration and Citizenship","Immigration and Citizenship",
     "移民の市民権・参政権・国籍取得と排除をめぐる法制度・政治的議論・アイデンティティ形成の研究。",
     "政治社会学・国家論","政治社会学",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Citizenship"),
    # 文化社会学・知識社会学 (+20)
    ("文化経済学","Cultural Economics","Cultural Economics",
     "芸術・文化財・創造産業の経済的特性（公共財・外部性・情報財）を分析する経済学と文化社会学の接点。",
     "文化社会学・知識社会学","文化社会学",1966,"North_America",
     "https://en.wikipedia.org/wiki/Cultural_economics"),
    ("文化的転回","Cultural Turn","Cultural Turn",
     "1980年代以降の社会科学全般が文化・言語・意味・象徴を分析の中心に据えた方法論的転換。",
     "文化社会学・知識社会学","文化社会学",1980,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Cultural_turn"),
    ("大衆文化のグローバル化","Globalization of Popular Culture","Globalization of Popular Culture",
     "ハリウッド・K-POP・アニメ等のポップカルチャーが世界規模で受容・変容・抵抗されるメカニズムの研究。",
     "文化社会学・知識社会学","文化社会学",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Cultural_globalization"),
    ("宗教の社会学","Sociology of Religion","Sociology of Religion",
     "宗教の社会的機能・世俗化・原理主義・新宗教運動・宗教市場論等を論じる社会学の古典的分野。",
     "文化社会学・知識社会学","文化社会学",1897,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_religion"),
    ("言語の社会学","Sociology of Language","Sociology of Language",
     "言語変異・多言語状況・言語政策・言語と権力の関係を社会学的に研究する分野。バーンスタイン・ブルデューが代表。",
     "文化社会学・知識社会学","知識社会学",1966,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_language"),
    ("学術知識の社会学","Sociology of Academic Knowledge","Sociology of Academic Knowledge",
     "大学・研究機関における知識生産・評価・引用・ピアレビューの社会的プロセスを分析する知識社会学。",
     "文化社会学・知識社会学","知識社会学",1972,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_scientific_knowledge"),
    ("ヘリテージ産業","Heritage Industry","Heritage Industry",
     "歴史・記憶・文化遺産を観光・商業・国民統合の資源として活用するプロセスとその政治経済。",
     "文化社会学・知識社会学","文化社会学",1987,"Western_Europe",
     "https://en.wikipedia.org/wiki/Heritage_tourism"),
    ("食の社会学","Sociology of Food","Sociology of Food",
     "食が階層・ジェンダー・民族・グローバリゼーション・環境と結びつく社会的プロセスの研究領域。",
     "文化社会学・知識社会学","文化社会学",1970,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Sociology_of_food"),
    ("死の社会学","Sociology of Death","Sociology of Death",
     "死・葬儀・喪失・グリーフの社会的意味・文化的実践・近代的死の医療化・在宅死の復権を研究する分野。",
     "文化社会学・知識社会学","文化社会学",1972,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_death"),
    ("信頼の社会学","Sociology of Trust","Sociology of Trust",
     "信頼・リスク・不確実性が社会制度・経済取引・人間関係・政治的正統性を支える役割を分析する社会学。",
     "文化社会学・知識社会学","文化社会学",1979,"Western_Europe",
     "https://en.wikipedia.org/wiki/Trust_(social_science)"),
]

print(f"Inserting {len(concepts)} concepts (Batch 23)...")
ins, skp = insert_batch(concepts)
print(f"Done. Inserted: {ins}, Skipped: {skp}")
