"""
DUA Wave A2 Batch 15 — Physics batch 5 (~50 concepts, subfield '物理学')
"""
import sqlite3
import uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

CONCEPTS = [
    {
        "name_ja": "ジョセフソン効果",
        "name_en": "Josephson Effect",
        "definition": "絶縁体薄膜で隔てられた二つの超伝導体間を流れる量子トンネル電流（直流・交流ジョセフソン効果）。Josephson(1962)が理論予測、Anderson-Rowell(1963)が実証。",
        "impact_summary": "SQUID（超伝導量子干渉計）による超高感度磁場測定、ボルト標準（電圧の量子基準）、量子コンピュータの超伝導量子ビットの物理的基盤。1973年Nobel賞受賞。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1962,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1973/josephson/lecture/",
        "mathematical_formulation": r"I = I_c\sin\varphi, \quad V = \frac{\hbar}{2e}\frac{d\varphi}{dt}",
        "data_completeness": 91,
    },
    {
        "name_ja": "量子ホール効果",
        "name_en": "Quantum Hall Effect",
        "definition": "2次元電子系に強磁場と低温を印加したとき、ホール抵抗が正確にh/ne²（nは整数）に量子化される現象（整数量子ホール効果）。分数量子ホール効果も発見されている。",
        "impact_summary": "von Klitzing(1980, 1985 Nobel)が整数QHEを発見。抵抗の国際標準（クリッツィング定数）に使用。Tsui・Störmer・Laughlin(1998 Nobel)が分数QHEを発見・説明。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1980,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1985/summary/",
        "mathematical_formulation": r"R_{xy} = \frac{h}{ne^2}, \quad n = 1, 2, 3, \ldots",
        "data_completeness": 92,
    },
    {
        "name_ja": "スピングラスと乱雑系物理",
        "name_en": "Spin Glasses and Disordered Systems",
        "definition": "ランダム結合を持つスピン系が低温で凍結した磁気秩序（スピングラス相）を示す現象の理論。Edwards-Anderson模型・レプリカ法・山路理論が主要理論手法。",
        "impact_summary": "Parisi(2021 Nobel)がスピングラスのレプリカ対称性の破れを解析。最適化問題（巡回セールスマン問題）・深層学習のエネルギーランドスケープ理解・神経回路理論への波及。",
        "subfield": "物理学", "school_of_thought": "Statistical Mechanics", "era_start": 1975,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/2021/parisi/lecture/",
        "mathematical_formulation": r"H = -\sum_{ij}J_{ij}S_iS_j, \quad J_{ij} \sim \mathcal{N}(0, J^2/N)",
        "data_completeness": 88,
    },
    {
        "name_ja": "二次元超伝導とKosterlitz-Thouless転移",
        "name_en": "Kosterlitz-Thouless Transition",
        "definition": "2次元系（薄膜・液体ヘリウム膜・XY模型）における位相転移の一種。渦-反渦の結合・解離がトポロジカルな相転移を起こす。Kosterlitz・Thouless(2016 Nobel)が理論化。",
        "impact_summary": "2次元物質（グラフェン・MoS₂・超薄膜超伝導体）のトポロジカル物性理解に不可欠。Haldaneとともに2016年Nobel賞。量子相転移とトポロジーの接続を確立した先駆的仕事。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1973,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/physics/2016/kosterlitz/lecture/",
        "mathematical_formulation": r"F = 2\pi(2E_c - \mu_V)\ln(R/a) \quad \text{vortex free energy}",
        "data_completeness": 88,
    },
    {
        "name_ja": "一般相対性理論の検証実験",
        "name_en": "Experimental Tests of General Relativity",
        "definition": "アインシュタインの一般相対性理論を観測・実験で検証する研究群。重力レンズ・水星の近日点移動・重力赤方偏移・パルサータイミング・重力波が主要な検証手段。",
        "impact_summary": "GPSの相対論補正（重力・速度補正）がなければ1日あたり11km以上の誤差。重力波直接検出（LIGO 2015）が一般相対論の極限領域での精密検証を可能にした。",
        "subfield": "物理学", "school_of_thought": "General Relativity", "era_start": 1919,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.84.540",
        "mathematical_formulation": r"G_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^4}T_{\mu\nu}",
        "data_completeness": 92,
    },
    {
        "name_ja": "相転移と臨界現象（スケーリング則）",
        "name_en": "Phase Transitions and Critical Phenomena",
        "definition": "物質が固体・液体・気体等の相を転移する際に示す臨界点近傍の普遍的挙動（臨界指数・スケーリング則・普遍クラス）を統一的に記述する統計力学の理論体系。",
        "impact_summary": "Wilson(1972, 1982 Nobel)が繰り込み群を導入し臨界現象の普遍性を解明。磁気転移・液体-気体臨界点・超流動転移・高温超伝導の理解基盤。素粒子物理のゲージ理論とも深く連関。",
        "subfield": "物理学", "school_of_thought": "Statistical Mechanics", "era_start": 1869,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/physics/1982/wilson/lecture/",
        "mathematical_formulation": r"C \propto |T-T_c|^{-\alpha}, \quad M \propto |T-T_c|^\beta, \quad \chi \propto |T-T_c|^{-\gamma}",
        "data_completeness": 91,
    },
    {
        "name_ja": "フォトニクスと統合光回路",
        "name_en": "Photonics and Integrated Photonic Circuits",
        "definition": "光子を情報・エネルギー搬送媒体とするデバイス・システム・回路の科学と工学。シリコンフォトニクス・光導波路・光スイッチ・光量子情報処理が主要領域。",
        "impact_summary": "光ファイバー通信（インターネット基盤）・データセンター内光インターコネクト・LiDAR・ボソンサンプリング量子コンピューティングへの応用。Kao(2009 Nobel, 光ファイバー)が開拓。",
        "subfield": "物理学", "school_of_thought": "Optics", "era_start": 1960,
        "culture_region": "East_Asia",
        "source_url": "https://www.nobelprize.org/prizes/physics/2009/kao/lecture/",
        "data_completeness": 88,
    },
    {
        "name_ja": "マクスウェルの悪魔と情報熱力学",
        "name_en": "Maxwell's Demon and Information Thermodynamics",
        "definition": "分子を選別するMaxwellの思考実験が提起した「情報と熱力学第二法則の関係」。Szilard・Brillouin・Landauer・Bennetらが情報消去とエントロピー増大の等価性を解明。",
        "impact_summary": "計算の熱的コスト（Landauer原理: 1ビット消去=kTln2エネルギー）・量子情報熱力学・フィードバック制御下の熱機関（情報機関）の理論基盤。量子コンピュータの発熱問題と直結。",
        "subfield": "物理学", "school_of_thought": "Statistical Mechanics", "era_start": 1871,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nature.com/articles/nphys2169",
        "mathematical_formulation": r"\Delta S_{\text{system}} + \Delta S_{\text{memory}} \geq 0, \quad \Delta E \geq k_BT\ln 2",
        "data_completeness": 88,
    },
    {
        "name_ja": "超対称性とその破れ",
        "name_en": "Supersymmetry and Its Breaking",
        "definition": "フェルミオンとボゾンを交換する対称性（超対称性）を時空の基本対称性として組み込む素粒子理論の枠組み。SUSY破れのメカニズムが弱い力の階層性問題を解く鍵とされる。",
        "impact_summary": "LHCでSUSY粒子（スクォーク・グルイーノ・ニュートラリーノ）が未発見のまま（2023年時点）だが、弦理論の数学的整合性・暗黒物質候補として理論的重要性を保持。",
        "subfield": "物理学", "school_of_thought": "String Theory", "era_start": 1971,
        "culture_region": "Europe_Western",
        "source_url": "https://home.cern/science/physics/supersymmetry",
        "data_completeness": 85,
    },
    {
        "name_ja": "エキゾチック状態の物質（分数統計・エニオン）",
        "name_en": "Anyons and Fractional Statistics",
        "definition": "2次元系に現れるボゾンともフェルミオンとも異なる中間的交換統計（分数統計）を持つ準粒子（エニオン）。分数量子ホール効果の準粒子がエニオンの物理的実現。",
        "impact_summary": "トポロジカル量子計算の中核概念（非可換エニオンによるトポロジカル量子ゲート）。Microsoft・Google等がトポロジカル量子ビットとして研究中。Wilczek(フォノンのエニオン理論, 1982)が命名。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1982,
        "culture_region": "North_America",
        "source_url": "https://link.aps.org/doi/10.1103/PhysRevLett.49.957",
        "mathematical_formulation": r"\psi_1\psi_2 = e^{i\theta}\psi_2\psi_1, \quad 0 < \theta < \pi",
        "data_completeness": 87,
    },
    {
        "name_ja": "軽元素の宇宙論的合成（BBN）",
        "name_en": "Big Bang Nucleosynthesis (BBN)",
        "definition": "ビッグバン後約3分間に宇宙全体の温度が核融合可能な領域にあった時期に起きた軽元素（H・D・³He・⁴He・⁷Li）の生成過程。観測的ヘリウム量が宇宙論パラメータ検証に使われる。",
        "impact_summary": "水素75%・ヘリウム25%の宇宙元素組成がBBNで決まることをAlpher・Bethe・Gamow(1948)が提唱。CMB温度揺らぎとの整合性が標準宇宙論（ΛCDM）の三本柱の一つ。",
        "subfield": "物理学", "school_of_thought": "Cosmology", "era_start": 1948,
        "culture_region": "North_America",
        "source_url": "https://www.annualreviews.org/doi/10.1146/annurev-astro-091916-055313",
        "mathematical_formulation": r"n/p = e^{-(m_n - m_p)c^2/k_BT} \approx 1/7 \text{ at freeze-out}",
        "data_completeness": 90,
    },
    {
        "name_ja": "ポーラロンと電子-格子相互作用",
        "name_en": "Polarons and Electron-Lattice Coupling",
        "definition": "結晶中の電子が格子変形を引き起こし自身と一体化した複合準粒子（ポーラロン）を形成する現象。Fröhlichポーラロン・Holsteinポーラロン・マグノンポーラロンが区別される。",
        "impact_summary": "ペロブスカイト太陽電池の高い光電変換効率の起源・有機半導体の電荷輸送・高温超伝導体の異常金属状態の理解に重要。マテリアルズインフォマティクスとの連携で材料設計に応用。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1933,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.89.015003",
        "mathematical_formulation": r"E_p = E - \alpha\hbar\omega_{\text{LO}}, \quad m_p^* = m^*\left(1+\frac{\alpha}{6}+\cdots\right)",
        "data_completeness": 86,
    },
    {
        "name_ja": "宇宙インフレーション",
        "name_en": "Cosmic Inflation",
        "definition": "ビッグバン直後（10⁻³⁶〜10⁻³²秒）に宇宙が超指数関数的に膨張したとする理論（Guth 1980・Linde・Starobinsky等）。宇宙の平坦性・地平線問題・モノポール問題を解決する。",
        "impact_summary": "CMBの温度揺らぎのほぼ平坦なパワースペクトルがインフレーション予言と一致（WMAP・Planck）。原始重力波の検出（Bモード偏光）がインフレーション検証の最前線課題（BICEP/Keck・CMB-S4）。",
        "subfield": "物理学", "school_of_thought": "Cosmology", "era_start": 1980,
        "culture_region": "North_America",
        "source_url": "https://www.physics.princeton.edu/~steinh/inflation.pdf",
        "mathematical_formulation": r"a(t) \propto e^{Ht}, \quad H = \sqrt{\frac{8\pi G V(\phi)}{3c^2}}",
        "data_completeness": 90,
    },
    {
        "name_ja": "中性子散乱と物質構造解析",
        "name_en": "Neutron Scattering and Structural Analysis",
        "definition": "中性子を物質に照射し散乱パターンから結晶構造・磁気構造・水素位置・動的挙動（フォノン・磁気励起）を決定する分析手法。X線に比べ水素・軽元素・磁気構造に強い。",
        "impact_summary": "SNS（米国）・J-PARC（日本/East_Asia）・ISIS（英国）等の大型中性子施設が高分子・生体分子・超伝導体・電池材料の精密構造解析を実施。Shull・Brockhouse(1994 Nobel)が確立。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1946,
        "culture_region": "East_Asia",
        "source_url": "https://mlfinfo.jp/en/",
        "data_completeness": 88,
    },
    {
        "name_ja": "可積分系とソリトン",
        "name_en": "Integrable Systems and Solitons",
        "definition": "コルテヴェーグ-ド・フリース（KdV）方程式などの非線形偏微分方程式が持つ孤立波解（ソリトン）と、逆散乱変換法による完全可積分系の数学的理論。",
        "impact_summary": "光ファイバー通信（ソリトン伝播による無歪み信号）・浅水波（津波理論）・ボース-アインシュタイン凝縮・弦理論の可積分性に応用。Zabusky・Kruskal(1965)がKdVソリトンを数値発見。",
        "subfield": "物理学", "school_of_thought": "Mathematical Physics", "era_start": 1895,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/PhysRevLett.15.240",
        "mathematical_formulation": r"\frac{\partial u}{\partial t} + 6u\frac{\partial u}{\partial x} + \frac{\partial^3 u}{\partial x^3} = 0",
        "data_completeness": 88,
    },
    {
        "name_ja": "テンソルネットワーク法",
        "name_en": "Tensor Network Methods",
        "definition": "量子多体系の状態を行列積状態（MPS）・テンソル積状態（PEPS）・多重スケールエンタングルメント繰り込み（MERA）等のテンソルネットワークで表現する計算手法群。",
        "impact_summary": "DMRGの一般化として理解され、強相関電子系・量子エラー訂正・機械学習との接続が活発。量子コンピュータのシミュレーション・古典的難問（テンソルコントラクション）の解決に使用。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1992,
        "culture_region": "North_America",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.93.045003",
        "mathematical_formulation": r"|\Psi\rangle = \sum_{\{s\}}M^{s_1}M^{s_2}\cdots M^{s_N}|s_1 s_2\cdots s_N\rangle",
        "data_completeness": 87,
    },
    {
        "name_ja": "ブラックホール情報パラドックス",
        "name_en": "Black Hole Information Paradox",
        "definition": "Hawking放射によってブラックホールが蒸発するとき、内部に落ちた情報が失われるか否かという問題。量子力学のユニタリ性と一般相対論（ホライズン無毛定理）の根本的矛盾。",
        "impact_summary": "Page曲線・アイランド公式・ホログラフィック・エンタングルメントエントロピー（Ryu-Takayanagi式）がユニタリ性を保つ方向で進展。量子重力理論の最重要未解決問題。",
        "subfield": "物理学", "school_of_thought": "Quantum Gravity", "era_start": 1975,
        "culture_region": "Europe_Western",
        "source_url": "https://www.annualreviews.org/doi/10.1146/annurev-astro-082708-101711",
        "mathematical_formulation": r"S_{\text{BH}} = \frac{A}{4G\hbar}, \quad T_H = \frac{\hbar c^3}{8\pi G M k_B}",
        "data_completeness": 87,
    },
    {
        "name_ja": "モット絶縁体と強相関電子系",
        "name_en": "Mott Insulator and Strongly Correlated Electrons",
        "definition": "バンド理論では金属と予測されるが電子-電子クーロン相互作用（Hubbard U）が強いため絶縁体となる状態（Mott絶縁体）。遷移金属酸化物・銅酸化物高温超伝導体が代表例。",
        "impact_summary": "銅酸化物高温超伝導のunderdoped領域・有機Mott絶縁体・光格子でのMott転移観測など。Mott(1977 Nobel)が確立。トポロジカルMott絶縁体・フラクトン等の新奇相も探索中。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1949,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.70.1039",
        "mathematical_formulation": r"n_{c} a_H^3 \approx 0.26 \quad \text{(Mott criterion)}",
        "data_completeness": 88,
    },
    {
        "name_ja": "分子動力学シミュレーション",
        "name_en": "Molecular Dynamics Simulation",
        "definition": "原子・分子の運動をニュートン方程式（または量子力学的力場）で数値積分し平衡・非平衡の熱力学的・動力学的性質を計算する手法。古典MD・ab initio MDが主要種別。",
        "impact_summary": "タンパク質折りたたみ・材料破壊・薬物-受容体ドッキング・流体力学のナノスケール記述に使用。Karplus・Levitt・Warshel(2013 Nobel, 多スケールMD)・Shaw(Anton専用機)が革新。",
        "subfield": "物理学", "school_of_thought": "Computational Physics", "era_start": 1957,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2013/summary/",
        "mathematical_formulation": r"m_i\ddot{\mathbf{r}}_i = -\nabla_i U(\mathbf{r}_1,\ldots,\mathbf{r}_N)",
        "data_completeness": 90,
    },
    {
        "name_ja": "場の量子論の経路積分形式",
        "name_en": "Path Integral Formulation of Quantum Field Theory",
        "definition": "Feynman(1948)が提唱した、量子力学・場の量子論を経路の重みづき和として定式化する手法。摂動論（Feynmanダイアグラム）・格子ゲージ理論・インスタントンが展開される基盤。",
        "impact_summary": "QEDの繰り込み（Schwinger・Tomonaga・Feynman 1965 Nobel）・QCDの非摂動効果（格子QCD）・弦理論の世界面積分の共通的枠組み。量子コンピュータによる格子QCDへの応用が進む。",
        "subfield": "物理学", "school_of_thought": "Particle Physics", "era_start": 1948,
        "culture_region": "North_America",
        "source_url": "https://www.feynmanlectures.caltech.edu/",
        "mathematical_formulation": r"Z = \int \mathcal{D}\phi \, e^{iS[\phi]/\hbar} = \int \mathcal{D}\phi \, e^{-S_E[\phi]/\hbar}",
        "data_completeness": 91,
    },
    {
        "name_ja": "ヴィリアル定理と自己重力系",
        "name_en": "Virial Theorem and Self-Gravitating Systems",
        "definition": "時間平均の運動エネルギーとポテンシャルエネルギーの間の普遍的関係（2⟨K⟩=−⟨V⟩）を記述するビリアル定理。銀河・星団・星間ガス雲・プラズマの力学安定性に適用される。",
        "impact_summary": "Zwicky(1933)が銀河団にビリアル定理を適用し暗黒物質の初の証拠を発見。星団の動的年齢・恒星大気の圧力・プラズマ閉じ込め条件の導出に使用。",
        "subfield": "物理学", "school_of_thought": "Classical Mechanics", "era_start": 1870,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.82.2257",
        "mathematical_formulation": r"\langle T\rangle = -\frac{1}{2}\langle \mathbf{r}\cdot\nabla V\rangle = -\frac{1}{2}\langle U\rangle",
        "data_completeness": 88,
    },
    {
        "name_ja": "電子正孔対と励起子",
        "name_en": "Excitons and Electron-Hole Pairs",
        "definition": "半導体・絶縁体内で光吸収によって生成される電子と正孔がクーロン力で束縛された準粒子（励起子）。Wannier-Mott型（弱結合）とFrenkel型（強結合）が区別される。",
        "impact_summary": "LED・太陽電池・有機EL・量子ドット発光の光物理基盤。2D材料（遷移金属ダイカルコゲナイド）の強い励起子束縛エネルギーが室温量子光学デバイスへの道を開く。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1931,
        "culture_region": "Europe_Eastern",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.90.021001",
        "mathematical_formulation": r"E_{\text{binding}} = -\frac{m_r e^4}{2\hbar^2\varepsilon^2 n^2}",
        "data_completeness": 88,
    },
    {
        "name_ja": "低温物理とヘリウムの超流動",
        "name_en": "Low-Temperature Physics and Superfluid Helium",
        "definition": "ヘリウム⁴が2.17 K以下で示す粘性ゼロの超流動状態（Kapitza点）の物理。Landauの二流体モデル・量子渦・ロトン励起・Helium-3の超流動（p波ペアリング）が主要トピック。",
        "impact_summary": "Kapitza(1978 Nobel, 超流動発見)・Landau(1962 Nobel, 二流体理論)・Lee・Osheroff・Richardson(1996 Nobel, ³He超流動)。希釈冷凍機（量子コンピュータの冷却）・中性子星内核のp波超流動との類比。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1938,
        "culture_region": "Europe_Eastern",
        "source_url": "https://www.nobelprize.org/prizes/physics/1978/kapitza/lecture/",
        "mathematical_formulation": r"\mathbf{v}_s = \frac{\hbar}{m}\nabla\phi, \quad \oint\mathbf{v}_s\cdot d\mathbf{l} = \frac{n\hbar}{m}",
        "data_completeness": 90,
    },
    {
        "name_ja": "カオスとローレンツアトラクター",
        "name_en": "Chaos Theory and Lorenz Attractor",
        "definition": "決定論的方程式が示す初期値鋭敏依存性（バタフライ効果）と不規則な軌道のダイナミクス（カオス）。Lorenz(1963)の大気対流モデルが典型例。リャプノフ指数・フラクタル次元が定量指標。",
        "impact_summary": "天気予報のアンサンブル法（予測可能性の限界の定量化）・心拍数変動解析・人口動態モデル・暗号学への応用。Mandelbrot（フラクタル）・Feigenbaum（分岐カスケード）と連動し複雑系科学を形成。",
        "subfield": "物理学", "school_of_thought": "Nonlinear Dynamics", "era_start": 1963,
        "culture_region": "North_America",
        "source_url": "https://link.aps.org/doi/10.1175/1520-0469(1963)020<0130:DNF>2.0.CO;2",
        "mathematical_formulation": r"\lambda = \lim_{t\to\infty}\frac{1}{t}\ln\frac{|\delta\mathbf{x}(t)|}{|\delta\mathbf{x}(0)|}",
        "data_completeness": 90,
    },
    {
        "name_ja": "量子鍵配送（QKD）の物理原理",
        "name_en": "Quantum Key Distribution Physical Principles",
        "definition": "量子力学の不確定性原理と量子複製不可能定理（No-Cloning定理）に基づく無条件安全な暗号鍵配送プロトコル。BB84・E91（量子もつれ使用）が代表的プロトコル。",
        "impact_summary": "盗聴が原理的に検出可能な暗号通信。中国の「墨子」衛星が1,200km QKDを実証（2017）。ポスト量子暗号（NIST選定）と並行してハイブリッド量子暗号が標準化へ。",
        "subfield": "物理学", "school_of_thought": "Quantum Information", "era_start": 1984,
        "culture_region": "East_Asia",
        "source_url": "https://www.nature.com/articles/nature23456",
        "data_completeness": 88,
    },
    {
        "name_ja": "ラマン散乱と非弾性散乱分光",
        "name_en": "Raman Scattering and Inelastic Light Scattering",
        "definition": "入射光が分子と相互作用しフォノン・振動・回転のエネルギー分だけシフトして散乱される非弾性散乱（ラマン効果）。ストークス線・反ストークス線が分子の振動状態を反映。",
        "impact_summary": "Raman(South_Asia, 1930 Nobel, インド)の発見が文化的・科学的象徴。非接触・非破壊分析として宝石鑑定・グラフェン品質評価・がん診断（SERS）・考古学に応用。",
        "subfield": "物理学", "school_of_thought": "Optics", "era_start": 1928,
        "culture_region": "South_Asia",
        "source_url": "https://www.nobelprize.org/prizes/physics/1930/raman/lecture/",
        "data_completeness": 91,
    },
    {
        "name_ja": "オングストローム技術と走査型プローブ顕微鏡",
        "name_en": "Scanning Probe Microscopy",
        "definition": "鋭い探針（プローブ）で表面を走査し原子スケールの形状・電子状態・力・磁気を測定するナノ計測手法。STM（走査型トンネル顕微鏡）・AFM・MFMが主要種別。",
        "impact_summary": "Binnig・Rohrer(1986 Nobel, STM)が原子表面の直接観察を実現。個別原子操作（IBMの原子で書いた「IBM」ロゴ）・単分子接合・DNAの力学特性測定へ応用。",
        "subfield": "物理学", "school_of_thought": "Condensed Matter Physics", "era_start": 1981,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1986/binnig/lecture/",
        "mathematical_formulation": r"I_{\text{tunnel}} \propto e^{-2\kappa d}, \quad \kappa = \sqrt{2m\phi}/\hbar",
        "data_completeness": 90,
    },
]

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    n = insert_batch(conn, CONCEPTS)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM natural_discovery")
    grand = cursor.fetchone()[0]
    conn.close()
    print(f"Batch15 physics5: {n} inserted. Total: {grand}")
