"""Batch 26 — Biology/Life Sciences (25) + Earth/Environment (20) = 45 concepts"""
import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

BIO_BATCH = [
    {
        "name_ja": "テロメアとテロメラーゼ", "name_en": "Telomeres and Telomerase",
        "definition": "染色体末端を保護するテロメアのDNA反復配列（TTAGGG）と、その伸長酵素テロメラーゼ。老化・がん・幹細胞生物学に深く関わる。2009年ノーベル生理学・医学賞。",
        "impact_summary": "老化の分子機構・がん細胞の無限増殖・幹細胞の自己複製能の分子基盤として重要。",
        "subfield": "生命科学・生物学", "school_of_thought": "分子生物学", "era_start": 1978,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/medicine/2009/summary/",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "オートファジー", "name_en": "Autophagy",
        "definition": "細胞が不要なタンパク質・細胞小器官を自己消化するプロセス。大隅良典（日本）が酵母の遺伝子スクリーニングでATG遺伝子群を同定し、2016年ノーベル生理学・医学賞を受賞。",
        "impact_summary": "神経変性疾患・がん・老化・感染症への適応において中心的な役割を持つ細胞内品質管理機構。",
        "subfield": "生命科学・生物学", "school_of_thought": "細胞生物学", "era_start": 1963,
        "culture_region": "East_Asia",
        "source_url": "https://www.nobelprize.org/prizes/medicine/2016/summary/",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "タンパク質折りたたみとシャペロン", "name_en": "Protein Folding and Chaperones",
        "definition": "アミノ酸配列から三次元構造へのタンパク質折りたたみ問題（アンフィンセンのドグマ）と、折りたたみを補助する分子シャペロン（Hsp70・Hsp90・GroEL）の機能。",
        "impact_summary": "AlphaFold2（2021年）による計算的解決・創薬標的・神経変性疾患の凝集体形成の分子機構。",
        "subfield": "生命科学・生物学", "school_of_thought": "構造生物学", "era_start": 1961,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Protein_folding",
        "mathematical_formulation": r"E_{\rm fold}=E_{\rm vdW}+E_{\rm elec}+E_{\rm H-bond}+E_{\rm solv}",
    },
    {
        "name_ja": "幹細胞と組織再生", "name_en": "Stem Cells and Tissue Regeneration",
        "definition": "自己複製能と分化能を持つ幹細胞（ES細胞・造血幹細胞・神経幹細胞・間葉系幹細胞等）と、それを利用した再生医療の生物学的基盤。",
        "impact_summary": "臓器再生・疾患モデル・創薬スクリーニングへの応用が急速に進む再生医学の核心概念。",
        "subfield": "生命科学・生物学", "school_of_thought": "発生生物学", "era_start": 1961,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Stem_cell",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "ゲノム刷り込みとエピジェネティクス", "name_en": "Genomic Imprinting and Epigenetics",
        "definition": "親の起源に依存してどちらか一方の対立遺伝子のみが発現するゲノム刷り込み。DNAメチル化・ヒストン修飾・X染色体不活化など広義のエピジェネティクスを含む。",
        "impact_summary": "Prader-Willi症候群・Angelman症候群・がん・老化の分子機構の解明に重要なエピゲノム制御。",
        "subfield": "生命科学・生物学", "school_of_thought": "エピジェネティクス", "era_start": 1984,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Genomic_imprinting",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "生態系の栄養カスケード", "name_en": "Trophic Cascades",
        "definition": "頂点捕食者の存在が食物網全体の生態系構造を間接的に制御する現象。オオカミの再導入によるイエローストーン国立公園の生態系回復が著名な事例。",
        "impact_summary": "頂点捕食者の保全が生態系全体の安定性・炭素固定に与える影響の理解に不可欠。",
        "subfield": "生命科学・生物学", "school_of_thought": "生態学", "era_start": 1980,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Trophic_cascade",
        "mathematical_formulation": r"\frac{dN_i}{dt}=r_iN_i-\sum_j a_{ij}N_iN_j\,({\rm Lotka-Volterra\,web})",
    },
    {
        "name_ja": "植物の二次代謝産物と生態", "name_en": "Plant Secondary Metabolites and Ecology",
        "definition": "植物が生産するアルカロイド・フラボノイド・テルペン・フェノール類などの二次代謝産物。防御・授粉者誘引・アレロパシーなど多様な生態的機能を持つ。",
        "impact_summary": "医薬品（キニーネ・モルヒネ・タキソール）の原料。アフリカ・アジアの伝統薬の分子基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "植物生態学", "era_start": 1950,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Secondary_metabolite",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "集団遺伝学とハーディ-ワインベルク平衡", "name_en": "Population Genetics and Hardy-Weinberg Equilibrium",
        "definition": "大集団・ランダム交配・突然変異なしの理想的集団では対立遺伝子頻度が世代を超えて一定に保たれる（HW平衡）。自然選択・遺伝的浮動・移住からの逸脱が進化の動力。",
        "impact_summary": "自然選択・遺伝的浮動・集団構造の検出・保全遺伝学・疾患関連研究の統計的基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "集団遺伝学", "era_start": 1908,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Hardy%E2%80%93Weinberg_principle",
        "mathematical_formulation": r"p^2+2pq+q^2=1,\quad p+q=1\,(p=\text{allele freq})",
    },
    {
        "name_ja": "RNA二次構造と触媒活性", "name_en": "RNA Secondary Structure and Ribozymes",
        "definition": "RNAが自分自身を触媒として機能するリボザイムの発見（Cech・Altman, 1989年ノーベル化学賞）。tRNAのクローバー葉構造・スプライソソームのRNA成分が代表例。",
        "impact_summary": "「RNAワールド仮説」の根拠となり、生命の起源・RNAベース医薬の理論的基盤を与えた。",
        "subfield": "生命科学・生物学", "school_of_thought": "分子生物学", "era_start": 1982,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/1989/summary/",
        "mathematical_formulation": r"\Delta G_{\rm fold}=\sum_{\rm loops}\Delta G_{\rm loop}+\sum_{\rm pairs}\Delta G_{\rm pair}",
    },
    {
        "name_ja": "生物時計とサーカディアンリズムの分子機構", "name_en": "Molecular Mechanisms of Circadian Clock",
        "definition": "CLOCK・BMAL1・Period・Cryptochrome遺伝子群による転写翻訳フィードバックループが概日時計の分子的基盤。Hall・Rosbash・Young（2017年ノーベル生理学・医学賞）が解明。",
        "impact_summary": "睡眠障害・代謝疾患・時間療法（がん治療の投与タイミング）に直結する概日リズムの分子機構。",
        "subfield": "生命科学・生物学", "school_of_thought": "分子生物学", "era_start": 1984,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/medicine/2017/summary/",
        "mathematical_formulation": r"\frac{d[P]}{dt}=v_s\frac{K_I^n}{K_I^n+[P]^n}-k_d[P]\,({\rm Goodwin\,oscillator})",
    },
    {
        "name_ja": "インド伝統医学アーユルヴェーダの薬草学", "name_en": "Ayurveda Pharmacobotany",
        "definition": "3,000年以上の歴史を持つインドの伝統医学体系における植物薬学。ターメリック（クルクミン）・アシュワガンダ・ニーム等が現代科学で再評価されている。",
        "impact_summary": "現代医薬の多くが伝統植物知識を起点に開発された（キニーネ・アスピリン等）。南アジア生物多様性保護とも関連。",
        "subfield": "生命科学・生物学", "school_of_thought": "伝統医学", "era_start": -1500,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Ayurveda",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "ウイルスの分子生物学と複製機構", "name_en": "Viral Molecular Biology and Replication",
        "definition": "ウイルスのゲノム（DNA・RNA・レトロウイルス）の複製・翻訳・パッケージングの分子機構。コロナウイルス・インフルエンザ・HIV・ヘルペスウイルスの複製サイクル。",
        "impact_summary": "COVID-19ワクチン・抗ウイルス薬（レムデシビル・ノイラミニダーゼ阻害薬）開発の分子生物学的基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "ウイルス学", "era_start": 1890,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Viral_replication",
        "mathematical_formulation": r"R_0=\beta\cdot\tau\cdot c\,({\rm basic\,reproduction\,number})",
    },
    {
        "name_ja": "発生生物学のモルフォゲン勾配", "name_en": "Morphogen Gradients in Development",
        "definition": "胚発生において濃度勾配を形成するシグナル分子（Bicoid・Dpp・Wnt・Shh等）が細胞の位置情報を提供するTuring型パターン形成機構。2019年ノーベル生理学・医学賞関連。",
        "impact_summary": "体節・肢の形成・神経管発生のパターン形成の分子機構。Turingの数理生物学予言（1952年）の実証。",
        "subfield": "生命科学・生物学", "school_of_thought": "発生生物学", "era_start": 1952,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Morphogen",
        "mathematical_formulation": r"\frac{\partial u}{\partial t}=D_u\nabla^2u+f(u,v),\quad\frac{\partial v}{\partial t}=D_v\nabla^2v+g(u,v)\,({\rm Turing})",
    },
    {
        "name_ja": "ゲノムワイド関連解析", "name_en": "Genome-Wide Association Studies",
        "definition": "多数の個体のゲノム全体の一塩基多型（SNP）と表現型・疾患リスクの統計的関連を探索する手法。100万〜数百万のSNPを対象とし、多因子遺伝病の遺伝的因子を特定する。",
        "impact_summary": "複雑な疾患（糖尿病・統合失調症・身長等）の遺伝的リスク因子の同定。精密医療・薬剤標的探索に応用。",
        "subfield": "生命科学・生物学", "school_of_thought": "ゲノム科学", "era_start": 2005,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Genome-wide_association_study",
        "mathematical_formulation": r"-\log_{10}(p)\geq7.3\,({\rm GWAS\,significance\,threshold})\approx5\times10^{-8}",
    },
    {
        "name_ja": "共生と内部共生説", "name_en": "Endosymbiosis Theory",
        "definition": "真核細胞のミトコンドリアと葉緑体は、それぞれα-プロテオバクテリアとシアノバクテリアが宿主細胞に取り込まれ内部共生化したという理論。Margulisが強力に支持した（1967年）。",
        "impact_summary": "真核生物の起源・細胞進化の最重要理論。リン・マーギュリスの学説が最初は否定されたが後に確立された。",
        "subfield": "生命科学・生物学", "school_of_thought": "進化生物学", "era_start": 1905,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Endosymbiont_theory",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "長鎖ノンコーディングRNA", "name_en": "Long Non-Coding RNAs",
        "definition": "200塩基以上のタンパク質をコードしないRNA分子（lncRNA）。XIST・HOTAIR等が染色体制御・エピジェネティクス・がん遺伝子制御に関与する。",
        "impact_summary": "ゲノムの「暗黒物質」として、遺伝子発現制御の新層を形成するRNAネットワークの重要構成要素。",
        "subfield": "生命科学・生物学", "school_of_thought": "分子生物学", "era_start": 2001,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Long_non-coding_RNA",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "アフリカの植物生態と熱帯雨林", "name_en": "African Tropical Forest Ecology",
        "definition": "コンゴ盆地熱帯雨林（世界第2位の面積）の生態学。高密度炭素貯蔵・固有種の多様性・ドライリーフフォレストの動態。気候変動への影響を受けやすい地球の「肺」。",
        "impact_summary": "地球の炭素循環・生物多様性の核心。農業・採掘との競合で急速に縮小しつつある生態系の記録と保全。",
        "subfield": "生命科学・生物学", "school_of_thought": "熱帯生態学", "era_start": 1970,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Congo_Basin",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "抗生物質耐性の分子進化", "name_en": "Antibiotic Resistance Evolution",
        "definition": "細菌が抗菌薬に対して耐性を獲得する分子メカニズム。酵素的不活化・標的変異・排出ポンプ・透過性低下・遺伝子水平伝播（プラスミド・トランスポゾン）が主要機構。",
        "impact_summary": "世界的公衆衛生危機であるAMR（薬剤耐性）問題の分子生物学的基盤。WHO優先事項の一つ。",
        "subfield": "生命科学・生物学", "school_of_thought": "微生物学", "era_start": 1940,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Antimicrobial_resistance",
        "mathematical_formulation": r"MIC\,({\rm minimum\,inhibitory\,concentration}),\quad s=1-w\,({\rm selection\,coefficient})",
    },
    {
        "name_ja": "メタゲノミクスと腸内細菌叢", "name_en": "Metagenomics and Human Microbiome",
        "definition": "環境サンプル・腸内サンプルから培養せずに微生物の遺伝情報を直接解読するメタゲノミクス。Human Microbiome Projectが人体の100兆個の微生物生態系を解明した。",
        "impact_summary": "腸内細菌と免疫・精神・代謝疾患の関係を解明し、プロバイオティクス・糞便移植の科学的基盤を与えた。",
        "subfield": "生命科学・生物学", "school_of_thought": "微生物学", "era_start": 2004,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Metagenomics",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "感染症の数理モデルとSIRモデル", "name_en": "Mathematical Epidemiology and SIR Model",
        "definition": "KermackとMcKendrickが1927年に提案した感染症伝播のSIR（感受性者・感染者・回復者）モデル。基本再生産数R0が疾病の流行・根絶を決定する。",
        "impact_summary": "COVID-19パンデミック・エボラ・インフルエンザのシミュレーションと公衆衛生介入の評価の理論的基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "疫学", "era_start": 1927,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology",
        "mathematical_formulation": r"\frac{dI}{dt}=\beta SI-\gamma I,\quad R_0=\frac{\beta}{\gamma},\quad\text{herd immunity: }p>1-1/R_0",
    },
    {
        "name_ja": "アマゾンの生態系多様性", "name_en": "Amazonian Biodiversity",
        "definition": "南米アマゾン盆地の熱帯雨林生態系。地球上の既知生物種の10%以上が生息し、先住民の伝統的知識体系と高い固有種多様性を持つ。",
        "impact_summary": "地球最大の熱帯雨林生態系の記録・保全。先住民の生物多様性知識の保護と主権の問題を含む。",
        "subfield": "生命科学・生物学", "school_of_thought": "熱帯生態学", "era_start": 1960,
        "culture_region": "Americas_Indigenous",
        "source_url": "https://en.wikipedia.org/wiki/Amazon_biome",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "ゲノム解読と次世代シーケンシング", "name_en": "Next-Generation Sequencing",
        "definition": "Sanger法に次ぐ高速・大量シーケンシング技術（Illumina・PacBio・Oxford Nanopore等）。ヒトゲノム解読コストを1兆分の1以下に低下させ、医療・農業・法医学を変革した。",
        "impact_summary": "精密医療・農業育種・感染症サーベイランス・古代DNA解析を革命的に変えた技術基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "ゲノム科学", "era_start": 2005,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/DNA_sequencing",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "神経可塑性と経験依存的変化", "name_en": "Synaptic Plasticity and Hebbian Learning",
        "definition": "使用依存的にシナプス強度が変化する神経可塑性。LTP・LTD・STDP（スパイク時間依存可塑性）が主要なメカニズム。Hebb則（1949年）が理論的枠組みを提供した。",
        "impact_summary": "記憶・学習の細胞レベル機構。リハビリ医学・神経人工知能・てんかんのメカニズム研究の基盤。",
        "subfield": "生命科学・生物学", "school_of_thought": "神経科学", "era_start": 1949,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Synaptic_plasticity",
        "mathematical_formulation": r"\Delta w_{ij}=\eta x_i x_j\,({\rm Hebb}),\quad\Delta w\propto\exp\!\left(-\frac{\Delta t}{\tau}\right)\,({\rm STDP})",
    },
    {
        "name_ja": "中国伝統医学の本草綱目", "name_en": "Bencao Gangmu (Chinese Materia Medica)",
        "definition": "明代の李時珍が1596年に著した中国の本草書の集大成。1,892種の薬物を記録し、系統分類・効能・処方を詳述した。屠呦呦のアルテミシニン（2015年ノーベル医学賞）の原典的根拠。",
        "impact_summary": "中国伝統医学のビッグデータ。アルテミシニン等現代医薬の起点。WHO伝統医学戦略でも参照される。",
        "subfield": "生命科学・生物学", "school_of_thought": "伝統医学", "era_start": 1596,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Bencao_Gangmu",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "サーカディアンリズムと光周性", "name_en": "Photoperiodism and Seasonal Biology",
        "definition": "植物・昆虫・鳥類が日長変化を感知して季節応答（開花・休眠・渡り）を制御する光周性。フィトクロム・時計遺伝子の制御下にある。",
        "impact_summary": "農業での開花期制御・渡り鳥の保全・光周性紊乱による生物多様性変化の理解に重要。",
        "subfield": "生命科学・生物学", "school_of_thought": "植物生物学", "era_start": 1920,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Photoperiodism",
        "mathematical_formulation": None,
    },
]

EARTH_BATCH = [
    {
        "name_ja": "海洋熱塩循環", "name_en": "Thermohaline Circulation",
        "definition": "温度・塩分差に駆動される深層海洋大循環。深水形成（北大西洋・南極）・底層流・湧昇流からなる「海洋コンベヤーベルト」。気候・炭素循環の調節に中心的役割。",
        "impact_summary": "地球気候の長期安定化・炭素・栄養塩の輸送の鍵。気候変動による弱体化がヨーロッパ寒冷化リスクとして議論される。",
        "subfield": "地球科学・環境科学", "school_of_thought": "海洋学", "era_start": 1958,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Thermohaline_circulation",
        "mathematical_formulation": r"\rho=\rho_0[1-\alpha(T-T_0)+\beta(S-S_0)]\,({\rm seawater\,density})",
    },
    {
        "name_ja": "土壌炭素貯留と土壌形成", "name_en": "Soil Carbon Sequestration and Pedogenesis",
        "definition": "土壌有機炭素（SOC）の形成・貯留・無機化のプロセス。ドクチャエフ（ロシア）の土壌科学の基礎（1883年）と現代の炭素農業（リジェネラティブ農業）に続く。",
        "impact_summary": "陸域炭素循環の鍵。農地管理による土壌炭素固定が気候変動緩和と食料安全保障を同時に達成する手段として注目。",
        "subfield": "地球科学・環境科学", "school_of_thought": "土壌科学", "era_start": 1883,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Soil_carbon",
        "mathematical_formulation": r"\frac{dC}{dt}=I-k\cdot C,\quad k=k_0 e^{-E_a/RT}\,({\rm temperature\,dependence})",
    },
    {
        "name_ja": "地震波の伝播と地球内部構造", "name_en": "Seismic Wave Propagation and Earth Interior",
        "definition": "P波・S波・表面波の速度が地球内部の密度・弾性率を反映することを利用した地球内部構造の探査。モホ不連続面・核-マントル境界・内核の発見に至った。",
        "impact_summary": "地球コア・マントルの構造解明。火山・断層・油田探査の基礎。地震ハザード評価に不可欠。",
        "subfield": "地球科学・環境科学", "school_of_thought": "固体地球物理学", "era_start": 1909,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Seismology",
        "mathematical_formulation": r"v_P=\sqrt{\frac{K+4G/3}{\rho}},\quad v_S=\sqrt{\frac{G}{\rho}}",
    },
    {
        "name_ja": "大気エアロゾルと気候強制力", "name_en": "Atmospheric Aerosols and Radiative Forcing",
        "definition": "大気中の固体・液体粒子（エアロゾル）が太陽放射を散乱・吸収し、雲核となることで気候に影響する。硫酸塩・ブラックカーボン・鉱物ダストが主要成分。",
        "impact_summary": "気候変動における「不確実性の主要因」であり、微粒子による大気汚染と気候強制力の二重の問題。",
        "subfield": "地球科学・環境科学", "school_of_thought": "大気科学", "era_start": 1975,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Aerosol",
        "mathematical_formulation": r"RF=-\frac{S_0}{4}(1-f_c)\cdot\tau\cdot\beta_{\rm scat}\,({\rm aerosol\,RF\,simplified})",
    },
    {
        "name_ja": "氷床力学と海面上昇", "name_en": "Ice Sheet Dynamics and Sea Level Rise",
        "definition": "グリーンランド・南極氷床の動態（流動・融解・崩壊）と、その地球温暖化による海面上昇への寄与。氷床底部の熱水潤滑・マリンアイスシート不安定性が重要。",
        "impact_summary": "2100年までの海面上昇は0.3-1.0m（RCPシナリオ依存）と予測され、低平地沿岸の数億人に直接影響。",
        "subfield": "地球科学・環境科学", "school_of_thought": "氷河学", "era_start": 1970,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Ice_sheet_dynamics",
        "mathematical_formulation": r"\frac{\partial H}{\partial t}+\nabla\cdot(\bar{u}H)=\dot{a}-\dot{m}\,({\rm continuity})",
    },
    {
        "name_ja": "地熱エネルギーとマグマ活動", "name_en": "Geothermal Energy and Magmatic Systems",
        "definition": "地球内部の放射性崩壊熱・残留熱によって駆動される地熱系。火山地帯の熱水貯留層・増強型地熱システム（EGS）を利用した再生可能エネルギー。",
        "impact_summary": "アイスランド・日本・ニュージーランドなど火山国のベースロード電力。EGSにより地熱資源を世界規模に拡大する研究が進む。",
        "subfield": "地球科学・環境科学", "school_of_thought": "地球物理学", "era_start": 1904,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Geothermal_energy",
        "mathematical_formulation": r"q=-k\frac{dT}{dz}\,({\rm Fourier\,heat\,conduction\,in\,crust})",
    },
    {
        "name_ja": "湖沼学と内水面生態系", "name_en": "Limnology and Freshwater Ecosystems",
        "definition": "湖・河川・湿地の物理・化学・生物学的特性の総合的研究。富栄養化・水温成層・湖沼底質の年縞（バルブ堆積物）による古気候復元も含む。",
        "impact_summary": "淡水資源管理・水質保全・古気候復元の科学的基盤。スウェーデンの年縞解析は気候変動の精密な証拠源。",
        "subfield": "地球科学・環境科学", "school_of_thought": "湖沼学", "era_start": 1892,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Limnology",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "インドモンスーンと季節変動", "name_en": "Indian Monsoon System",
        "definition": "インド洋と陸地の熱容量差が駆動する季節的降水システム。南アジアの農業・水資源・経済に決定的な影響を持つ。ENSO・大気チベット高原加熱との相互作用が重要。",
        "impact_summary": "南アジア15億人の農業・水供給・生態系の基盤。気候変動による変動が食料安全保障に直結。",
        "subfield": "地球科学・環境科学", "school_of_thought": "気候学", "era_start": 1686,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/South_Asian_monsoon",
        "mathematical_formulation": r"\nabla\cdot(\rho\mathbf{v})=-\frac{\partial\rho}{\partial t}\,({\rm continuity}),\quad P=P_0e^{-z/H}\,({\rm barometric})",
    },
    {
        "name_ja": "太陽活動と宇宙天気", "name_en": "Solar Activity and Space Weather",
        "definition": "太陽黒点活動・コロナ質量放出（CME）・太陽フレアが地球の電離層・磁気圏・人工衛星・送電網に影響を与える宇宙天気現象。11年周期の太陽活動サイクル。",
        "impact_summary": "GPS・通信衛星・電力グリッドへの影響。1989年の太陽嵐によるケベック大停電が著名事例。",
        "subfield": "地球科学・環境科学", "school_of_thought": "宇宙地球物理学", "era_start": 1843,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Space_weather",
        "mathematical_formulation": r"R_z=\frac{1}{k}\sum_g(10G+N)\,({\rm Wolf\,sunspot\,number})",
    },
    {
        "name_ja": "深海底生態系と熱水噴出孔", "name_en": "Deep-Sea Ecosystems and Hydrothermal Vents",
        "definition": "海底の熱水噴出孔周辺に光合成なしに化学合成独立栄養生物（細菌・古細菌）を基盤とする生態系が存在する。1977年の発見は生命の定義を拡張した。",
        "impact_summary": "生命の起源・生命可能域の拡大（エウロパ等の海洋衛星への応用）・新規酵素・医薬品の供給源。",
        "subfield": "地球科学・環境科学", "school_of_thought": "深海科学", "era_start": 1977,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Hydrothermal_vent",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "地球大気の大循環", "name_en": "General Circulation of the Atmosphere",
        "definition": "ハドレー循環・フェレル循環・極循環からなる三細胞モデルと、コリオリ力・山岳・陸海分布の影響を受けた実際の大気大循環。熱帯収束帯・偏西風・貿易風を支配する。",
        "impact_summary": "気候帯・降水分布・嵐のトラック・季節変化の原動力。気候変動による循環変化が農業・水資源に影響。",
        "subfield": "地球科学・環境科学", "school_of_thought": "気象学", "era_start": 1735,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Atmospheric_circulation",
        "mathematical_formulation": r"f=2\Omega\sin\phi\,({\rm Coriolis\,parameter}),\quad\frac{\partial\mathbf{v}}{\partial t}+(\mathbf{v}\cdot\nabla)\mathbf{v}=-\nabla p/\rho+\mathbf{g}+f\hat{z}\times\mathbf{v}",
    },
    {
        "name_ja": "ナイル川流域の水文学", "name_en": "Nile Basin Hydrology",
        "definition": "世界最長の川（6,650 km）のナイル川流域（11カ国、338万 km²）の水資源管理・季節洪水・アッスワンダム等の水工学。エジプト文明の基盤となった年間洪水の地形・気候メカニズム。",
        "impact_summary": "水・食料・エネルギーの安全保障が競合するトランスバウンダリー水資源問題の代表事例。",
        "subfield": "地球科学・環境科学", "school_of_thought": "水文学", "era_start": -3000,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Nile",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "生物地球化学サイクルの統合", "name_en": "Integrated Biogeochemical Cycles",
        "definition": "炭素・窒素・リン・硫黄・水の生物地球化学的循環の相互作用と、人間活動による攪乱（化石燃料燃焼・農業窒素投入・リン鉱採掘）の地球システムへの影響。",
        "impact_summary": "地球の物質循環を統一的に理解するシステム地球科学の核心。プラネタリーバウンダリーの科学的基盤。",
        "subfield": "地球科学・環境科学", "school_of_thought": "地球システム科学", "era_start": 1970,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Biogeochemical_cycle",
        "mathematical_formulation": r"\frac{dC_{\rm atm}}{dt}=F_{\rm fossil}+F_{\rm land}-F_{\rm ocean}-F_{\rm biome}",
    },
    {
        "name_ja": "岩石磁気と古地磁気", "name_en": "Rock Magnetism and Paleomagnetism",
        "definition": "岩石に保存された地磁気情報（古地磁気）から大陸移動・地磁気逆転・古環境を復元する研究。海底拡大の証拠（磁気縞模様）がプレートテクトニクス確立に決定的役割を果たした。",
        "impact_summary": "プレートテクトニクス革命の物的証拠を提供した。地磁気逆転の年代測定による地質年代決定の基準。",
        "subfield": "地球科学・環境科学", "school_of_thought": "固体地球物理学", "era_start": 1906,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Paleomagnetism",
        "mathematical_formulation": r"\mathbf{B}=\mathbf{B}_{\rm dipole}+\mathbf{B}_{\rm nondipole},\quad B_r=-\frac{\partial V}{\partial r}",
    },
    {
        "name_ja": "東アジアの黄砂と大気輸送", "name_en": "Asian Dust and Long-Range Atmospheric Transport",
        "definition": "ゴビ砂漠・タクラマカン砂漠から発生する黄砂（鉱物ダスト）が偏西風によって東アジア・太平洋・北米まで輸送される現象。鉄施肥・放射強制力・大気エアロゾルに関連。",
        "impact_summary": "東アジアの春季大気汚染・太平洋の鉄肥沃化・気候影響をもたらす長距離大気輸送の代表事例。",
        "subfield": "地球科学・環境科学", "school_of_thought": "大気科学", "era_start": 1980,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Asian_Dust",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "崩壊断層帯と地震サイクル", "name_en": "Fault Mechanics and Seismic Cycle",
        "definition": "弾性リバウンド理論に基づく地震サイクル（応力蓄積→地震→緩和）・断層帯の摩擦構成則・速度弱化・強化・地震前兆現象の断層力学。",
        "impact_summary": "地震予知・確率論的地震ハザード評価・建築基準の科学的基盤。日本の地震予測研究が世界をリードする。",
        "subfield": "地球科学・環境科学", "school_of_thought": "固体地球物理学", "era_start": 1906,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Seismic_cycle",
        "mathematical_formulation": r"\tau=\mu_0+a\ln\!\left(\frac{v}{v_0}\right)+b\ln\!\left(\frac{v_0\theta}{d_c}\right)\,({\rm rate-state\,friction})",
    },
    {
        "name_ja": "砂漠化と乾燥地生態系", "name_en": "Desertification and Dryland Ecology",
        "definition": "気候変動・過耕作・森林伐採によって乾燥地が砂漠化するプロセス。サハラ・サヘル地帯の南進・アラル海縮小・グリーンベルト運動（ワンガリ・マータイ）が著名事例。",
        "impact_summary": "世界の1/3の陸地が乾燥地であり、15億人の生計が関わる地球規模の土地劣化問題。",
        "subfield": "地球科学・環境科学", "school_of_thought": "環境科学", "era_start": 1977,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Desertification",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "プレートテクトニクスとリソスフェアダイナミクス", "name_en": "Plate Tectonics and Lithospheric Dynamics",
        "definition": "地球の外殻を構成する十数枚の剛体プレートが相互に移動する理論。拡大・収束・すれ違い境界での地震・火山・造山活動を統一的に説明する20世紀最大の地球科学革命。",
        "impact_summary": "地球科学のコペルニクス的転換。地震帯・火山帯・鉱床分布の理解と資源探査の基盤。",
        "subfield": "地球科学・環境科学", "school_of_thought": "固体地球物理学", "era_start": 1912,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Plate_tectonics",
        "mathematical_formulation": r"v_{\rm spreading}=\frac{dr}{dt}=1\text{--}20\,\text{cm/yr},\quad\tau_{\rm mantle}\sim10^{21}\,\text{Pa·s}",
    },
    {
        "name_ja": "永久凍土とメタン放出", "name_en": "Permafrost and Methane Emission",
        "definition": "北極・高山の永久凍土が融解することで有機炭素が微生物分解されCO2・CH4が放出される気候フィードバック。シベリア・アラスカ・カナダの凍土が主要な炭素貯蔵源。",
        "impact_summary": "気候変動のティッピングポイントの一つ。融解した永久凍土からのメタン放出が温暖化を加速させる正のフィードバック。",
        "subfield": "地球科学・環境科学", "school_of_thought": "気候科学", "era_start": 1943,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Permafrost",
        "mathematical_formulation": r"F_{\rm CH_4}\propto e^{T/T_0}\cdot\theta_{\rm water}\cdot(1-f_{\rm oxid})",
    },
    {
        "name_ja": "大気汚染と健康影響の疫学", "name_en": "Air Pollution Epidemiology",
        "definition": "PM2.5・NO2・オゾン等の大気汚染物質の健康影響を疫学的に定量する研究。WHO基準（PM2.5年平均5μg/m³）は全球の年間700万人超の早期死亡のエビデンスに基づく。",
        "impact_summary": "アジア・アフリカの都市大気汚染対策の科学的根拠。環境正義・気候政策との連携が重要な研究領域。",
        "subfield": "地球科学・環境科学", "school_of_thought": "環境疫学", "era_start": 1952,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health",
        "mathematical_formulation": r"RR=\exp(\beta\cdot\Delta PM_{2.5}),\quad\beta\approx0.006\text{ per }\mu\text{g/m}^3",
    },
]

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    b = insert_batch(conn, BIO_BATCH)
    e = insert_batch(conn, EARTH_BATCH)
    total = conn.execute("SELECT COUNT(*) FROM natural_discovery").fetchone()[0]
    conn.close()
    print(f"Batch26 bio+earth: {b+e} inserted (bio={b}, earth={e}). Total: {total}")
