#!/usr/bin/env python3
"""DUA Wave A2 Batch 24 — social_theory expansion final push.
Current: 5,299. Target: 5,500. Need ~201 more. Inserting 220 brand-new concepts."""
import sqlite3, uuid, datetime

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(concepts):
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    inserted = 0; skipped = 0
    for c in concepts:
        name_ja, name_en, name_orig, defn, subfield, school, era, region, url = c
        cur.execute("SELECT COUNT(*) FROM social_theory WHERE name_en=?", (name_en,))
        if cur.fetchone()[0] > 0:
            skipped += 1; continue
        uid = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat()
        cur.execute("""INSERT INTO social_theory
            (id,name_ja,name_en,name_original,definition,subfield,school_of_thought,
             era_start,culture_region,source_url,verification_status,quality_flag,
             status,created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,'url_present','B','active',?,?)""",
            (uid,name_ja,name_en,name_orig,defn,subfield,school,era,region,url,now,now))
        inserted += 1
        if inserted % 50 == 0:
            conn.commit(); print(f"  Committed {inserted}...")
    conn.commit(); conn.close()
    return inserted, skipped

concepts = [
    # 古典社会学 (+30)
    ("ゾンバルトの戦争と資本主義","Sombart's War and Capitalism","Krieg und Kapitalismus",
     "戦争が資本主義的技術革新・組織革命・市場拡大の駆動力であることを論じたゾンバルトの歴史社会学的著作1913年。",
     "古典社会学","古典社会学",1913,"Western_Europe",
     "https://en.wikipedia.org/wiki/Werner_Sombart"),
    ("マルクスの原始蓄積","Marx's Primitive Accumulation","Ursprüngliche Akkumulation",
     "資本主義の成立に先立つ暴力的な共有地囲い込み・植民地収奪・農民追放による資本の初期蓄積。",
     "古典社会学","古典社会学",1867,"Western_Europe",
     "https://en.wikipedia.org/wiki/Primitive_accumulation_of_capital"),
    ("ウェーバーの法社会学","Weber's Sociology of Law","Rechtssoziologie",
     "法を合理化・形式的合理性・実質的合理性の観点から比較分析し、近代西洋法の特質を論じた法社会学。",
     "古典社会学","古典社会学",1922,"Western_Europe",
     "https://en.wikipedia.org/wiki/Max_Weber"),
    ("デュルケームの犯罪機能論","Durkheim's Function of Crime","Normal Crime",
     "犯罪は社会の病理ではなく集合道徳の境界設定・社会的結束の強化・変革の予告という正常機能を持つとする命題。",
     "古典社会学","古典社会学",1895,"Western_Europe",
     "https://en.wikipedia.org/wiki/%C3%89mile_Durkheim"),
    ("ジンメルの都市と精神生活","Simmel's Metropolis and Mental Life","Die Großstädte und das Geistesleben",
     "1903年の古典的エッセイ。都市の過密刺激が知性的自己防衛・ブラゼ態度・個人主義を生むメカニズム。",
     "古典社会学","古典社会学",1903,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Metropolis_and_Mental_Life"),
    ("ミルズの社会学的想像力","Mills' Sociological Imagination","The Sociological Imagination",
     "個人的問題と社会的争点の結びつきを洞察する批判的思考能力。1959年の著作で公共社会学の基礎となった。",
     "古典社会学","古典社会学",1959,"North_America",
     "https://en.wikipedia.org/wiki/The_Sociological_Imagination"),
    ("マートンの準拠集団論","Merton's Reference Group Theory","Reference Group Theory",
     "個人が自己評価・態度形成の基準として用いる集団の概念。現実の所属集団と異なる準拠集団への志向を論じる。",
     "古典社会学","古典社会学",1957,"North_America",
     "https://en.wikipedia.org/wiki/Reference_group"),
    ("パーソンズのAGIL図式","Parsons' AGIL Paradigm","AGIL paradigm",
     "適応(A)・目標達成(G)・統合(I)・潜在的パターン維持(L)の4機能的要件によって社会システムを分析する枠組み。",
     "古典社会学","機能主義",1956,"North_America",
     "https://en.wikipedia.org/wiki/AGIL_paradigm"),
    ("パーソンズの行為理論","Parsons' Theory of Action","The Structure of Social Action",
     "ウェーバー・デュルケーム・パレート・マーシャルを統合し行為・規範・価値を基礎とした社会学理論体系。",
     "古典社会学","機能主義",1937,"North_America",
     "https://en.wikipedia.org/wiki/Talcott_Parsons"),
    ("マンハイムのユートピア論","Mannheim's Utopia Theory","Ideologie und Utopie",
     "イデオロギーが現存秩序を正当化し、ユートピアが変革への志向を表すという知識社会学の核心概念。1929年。",
     "古典社会学","古典社会学",1929,"Western_Europe",
     "https://en.wikipedia.org/wiki/Ideology_and_Utopia"),
    ("ゴッフマンの自己呈示戦略","Goffman's Self-Presentation Strategy","Impression Management",
     "日常的相互作用において人々が意図的に自己イメージを管理・演出する戦略的過程。演劇的比喩で分析。",
     "古典社会学","相互作用論",1959,"North_America",
     "https://en.wikipedia.org/wiki/Impression_management"),
    ("ゴッフマンのスティグマ論","Goffman's Theory of Stigma","Stigma (Goffman)",
     "社会的に価値を損なうとされる属性（身体・人格・集団的帰属）がどのように差別・排除・アイデンティティ戦略を生むかの分析。",
     "古典社会学","相互作用論",1963,"North_America",
     "https://en.wikipedia.org/wiki/Stigma_(book)"),
    ("コリンズの相互作用儀礼連鎖","Collins' Interaction Ritual Chains","Interaction Ritual Chains",
     "感情的エネルギーと連帯象徴の充電を通じて社会的絆が生産・維持される微視的メカニズム。",
     "古典社会学","相互作用論",2004,"North_America",
     "https://en.wikipedia.org/wiki/Randall_Collins"),
    ("ブルーマーのシンボリック相互作用論","Blumer's Symbolic Interactionism","Symbolic Interactionism",
     "社会生活が事物・行為・状況に与えられた意味の解釈過程として成立することを強調するブルーマーの社会学方法論。",
     "古典社会学","相互作用論",1969,"North_America",
     "https://en.wikipedia.org/wiki/Symbolic_interactionism"),
    ("コリンズの暴力の社会学","Collins' Sociology of Violence","Violence: A Micro-sociological Theory",
     "暴力が相互作用の緊張・恐怖・感情エネルギーの突破として生まれる微視的社会学的分析。2008年の主著。",
     "古典社会学","相互作用論",2008,"North_America",
     "https://en.wikipedia.org/wiki/Randall_Collins"),
    ("ホーマンズの交換理論","Homans' Exchange Theory","Social Behavior: Its Elementary Forms",
     "人間行動を行動主義的学習理論と経済交換の論理から説明するホーマンズの微視的社会学。",
     "古典社会学","交換理論",1961,"North_America",
     "https://en.wikipedia.org/wiki/George_C._Homans"),
    ("ブラウの社会交換論","Blau's Social Exchange Theory","Exchange and Power",
     "組織内の権力・地位・インテグレーションを社会的交換の不均衡から説明するブラウの交換・組織理論。",
     "古典社会学","交換理論",1964,"North_America",
     "https://en.wikipedia.org/wiki/Peter_Blau"),
    ("エマーソンの権力-依存関係論","Emerson's Power-Dependence Theory","Power-Dependence Relations",
     "社会的権力を依存関係の逆数として定式化し、コミットメント・連合形成・コスト削減を分析したエマーソン。",
     "古典社会学","交換理論",1962,"North_America",
     "https://en.wikipedia.org/wiki/Richard_M._Emerson"),
    ("ガーフィンケルの違反実験","Garfinkel's Breaching Experiments","Breaching Experiment",
     "日常的な社会的期待を意図的に侵犯することで人々が使用する暗黙の規則・修復実践を露わにする研究方法。",
     "古典社会学","エスノメソドロジー",1967,"North_America",
     "https://en.wikipedia.org/wiki/Breaching_experiment"),
    ("会話分析の創始","Foundation of Conversation Analysis","Conversation Analysis",
     "サックス・シェグロフ・ジェファーソンが確立した日常会話の順番交替・修復・優先構造の体系的研究手法。",
     "古典社会学","エスノメソドロジー",1974,"North_America",
     "https://en.wikipedia.org/wiki/Conversation_analysis"),
    # 批判理論・フランクフルト学派 (+30)
    ("クリティカルディスコース分析","Critical Discourse Analysis","Critical Discourse Analysis",
     "言語使用・テクストが権力・イデオロギー・社会的不平等を再生産する様式をフェアクロフ・ファン・ダイクらが分析する方法。",
     "批判理論・フランクフルト学派","批判理論",1989,"Western_Europe",
     "https://en.wikipedia.org/wiki/Critical_discourse_analysis"),
    ("批判理論と宗教","Critical Theory and Religion","Critical Theory and Religion",
     "フランクフルト学派が宗教を啓蒙批判・世俗化・ユートピア的衝動の観点から論じた試み。ホルクハイマーの「神学的動機」等。",
     "批判理論・フランクフルト学派","批判理論",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    ("自然支配批判","Critique of Domination of Nature","Naturbeherrschung",
     "人間の自然支配と人間同士の支配が同一の啓蒙的合理性に根ざすとするアドルノ・ホルクハイマーの批判的命題。",
     "批判理論・フランクフルト学派","批判理論",1944,"North_America",
     "https://en.wikipedia.org/wiki/Dialectic_of_Enlightenment"),
    ("偽りの欲求","False Needs","False Needs",
     "マルクーゼが提唱した概念。資本主義体制が大衆に植え付ける欲求が真の解放ではなく抑圧を再生産する疑似欲求。",
     "批判理論・フランクフルト学派","批判理論",1964,"North_America",
     "https://en.wikipedia.org/wiki/False_needs"),
    ("批判理論の実践的転回","Practical Turn in Critical Theory","Practical Turn",
     "ハーバーマス以後の批判理論が言語・実践・承認・正義という具体的問題に向かった方法論的転換。",
     "批判理論・フランクフルト学派","批判理論",1980,"Western_Europe",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    ("批判理論とグローバリゼーション","Critical Theory and Globalization","Critical Theory and Globalization",
     "グローバル資本主義・超国家的ガバナンス・世界市民的正義をめぐる批判理論の現代的展開。",
     "批判理論・フランクフルト学派","批判理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    ("物化と承認の弁証法","Dialectic of Reification and Recognition","Verdinglichung und Anerkennung",
     "ホネットが物化（他者を物として扱うこと）を承認の欠如として再定式化した批判的社会哲学。2005年著作。",
     "批判理論・フランクフルト学派","承認論",2005,"Western_Europe",
     "https://en.wikipedia.org/wiki/Axel_Honneth"),
    ("社会批判の根拠","Grounds for Social Criticism","Immanente Kritik",
     "外部からの理想規範ではなく社会の自己了解・内在的矛盾に根拠を求めるヘーゲル的・マルクス的批判方法論。",
     "批判理論・フランクフルト学派","批判理論",1975,"Western_Europe",
     "https://en.wikipedia.org/wiki/Immanent_critique"),
    ("加速主義批判","Critique of Accelerationism","Critique of Accelerationism",
     "資本主義・技術加速を解放の条件とする思想への批判理論的応答。加速は解放でなく支配強化という反論。",
     "批判理論・フランクフルト学派","批判理論",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Accelerationism"),
    ("批判理論と民主主義の危機","Critical Theory and Democratic Crisis","Democratic Crisis",
     "ハーバーマス以後の批判理論がポピュリズム・権威主義・脱民主化に対してどう応答するかの規範的論争。",
     "批判理論・フランクフルト学派","批判理論",2016,"Western_Europe",
     "https://en.wikipedia.org/wiki/Frankfurt_School"),
    # 構造主義・ポスト構造主義 (+25)
    ("ラカンの鏡像段階","Lacan's Mirror Stage","Stade du miroir",
     "幼児が鏡像を通じて統一的自己を想像的に同一化する過程を論じた精神分析理論。主体形成の基礎。",
     "構造主義・ポスト構造主義","ポスト構造主義",1949,"Western_Europe",
     "https://en.wikipedia.org/wiki/Mirror_stage"),
    ("フーコーの主体化","Foucault's Subjectivation","Subjectivation",
     "個人が自己を対象化・理解・変容する実践を通じて主体として形成される過程。後期フーコーの中心テーマ。",
     "構造主義・ポスト構造主義","系譜学・考古学",1982,"Western_Europe",
     "https://en.wikipedia.org/wiki/Subject_(philosophy)"),
    ("ドゥルーズの器官なき身体","Body Without Organs","Corps sans organes",
     "アントナン・アルトーから借用したドゥルーズ=ガタリの概念。器官的組織化以前の強度・欲望の平面。",
     "構造主義・ポスト構造主義","ポスト構造主義",1972,"Western_Europe",
     "https://en.wikipedia.org/wiki/Body_without_organs"),
    ("バフチンとポスト構造主義","Bakhtin and Post-Structuralism","Dialogism",
     "バフチンの対話性・ポリフォニー・カーニバル概念がポスト構造主義・文化研究に与えた理論的影響。",
     "構造主義・ポスト構造主義","記号論",1965,"Western_Europe",
     "https://en.wikipedia.org/wiki/Mikhail_Bakhtin"),
    ("レヴィナスと他者倫理","Levinas and Ethics of Alterity","Éthique comme philosophie première",
     "他者の顔への無限の責任を倫理の根底に置くレヴィナスの思想。デリダ・バトラーのポスト構造主義倫理学と対話。",
     "構造主義・ポスト構造主義","ポスト構造主義",1961,"Western_Europe",
     "https://en.wikipedia.org/wiki/Emmanuel_Levinas"),
    ("ネグリの帝国論","Negri's Empire Theory","Empire (Negri and Hardt)",
     "主権・ネーション・資本を超えた脱中心的世界権力「帝国」とその潜在的対抗力「マルチチュード」の理論。",
     "構造主義・ポスト構造主義","ポスト構造主義",2000,"Western_Europe",
     "https://en.wikipedia.org/wiki/Empire_(Hardt_and_Negri_book)"),
    ("アガンベンのホモ・サケル","Agamben's Homo Sacer","Homo Sacer",
     "例外状態と「剥き出しの生」の概念を通じて近代政治の生政治的核心を暴いたアガンベンの政治哲学。",
     "構造主義・ポスト構造主義","ポスト構造主義",1995,"Western_Europe",
     "https://en.wikipedia.org/wiki/Homo_Sacer"),
    ("バトラーの喪の不可能性","Butler's Impossible Mourning","Precarious Life",
     "誰の死が公的に哀悼に値するかを規定する権力構造を論じたバトラーの9・11後の政治的省察。",
     "構造主義・ポスト構造主義","ポスト構造主義",2004,"North_America",
     "https://en.wikipedia.org/wiki/Precarious_Life_(book)"),
    ("バリバールのシトワイアンネテ","Balibar's Citizenships","La proposition de l'égaliberté",
     "自由と平等の不可分の結合としての市民性を論じるバリバールの政治哲学。国民国家・グローバル正義との緊張。",
     "構造主義・ポスト構造主義","ポスト構造主義",1989,"Western_Europe",
     "https://en.wikipedia.org/wiki/%C3%89tienne_Balibar"),
    ("ランシエールの感性の分配","Rancière's Distribution of the Sensible","Partage du sensible",
     "政治を可視と不可視・言語と雑音の境界を書き換える行為として定義するランシエールの政治美学。",
     "構造主義・ポスト構造主義","ポスト構造主義",2000,"Western_Europe",
     "https://en.wikipedia.org/wiki/Jacques_Ranci%C3%A8re"),
    ("ムフのラディカル民主主義","Mouffe's Radical Democracy","Radical Democracy",
     "対立と闘争を民主主義から排除するのでなく敵対性を友好的競争（アゴニズム）として制度化する政治理論。",
     "構造主義・ポスト構造主義","ポスト構造主義",1993,"Western_Europe",
     "https://en.wikipedia.org/wiki/Chantal_Mouffe"),
    # フェミニズム・ジェンダー理論 (+25)
    ("再生産的未来主義批判","Critique of Reproductive Futurism","Reproductive Futurism",
     "「子供の未来のために」という政治的修辞が同性愛・非規範的主体を排除するEdelman等のクィア批判。",
     "フェミニズム・ジェンダー理論","クィア理論",2004,"North_America",
     "https://en.wikipedia.org/wiki/Queer_theory"),
    ("フェミニスト精神分析","Feminist Psychoanalysis","Feminist Psychoanalysis",
     "ラカン・フロイト精神分析のジェンダー・バイアスを批判しつつ女性の欲望・主体性・症候を再理論化する試み。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1974,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    ("セクシュアリティと医療化","Sexuality and Medicalization","Medicalization of Sexuality",
     "性的欲望・行動・アイデンティティが医学的カテゴリーによって正常/異常に分類される社会的過程の批判的研究。",
     "フェミニズム・ジェンダー理論","クィア理論",1978,"North_America",
     "https://en.wikipedia.org/wiki/Medicalization"),
    ("トランスジェンダー研究","Transgender Studies","Transgender Studies",
     "トランスジェンダーの経験・歴史・医療・法・運動・表象を学際的に研究する新興学問領域。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1990,"North_America",
     "https://en.wikipedia.org/wiki/Transgender_studies"),
    ("フェミニスト外交政策","Feminist Foreign Policy","Feminist Foreign Policy",
     "ジェンダー平等・女性の安全・権力構造の変革を外交政策の中心に置くスウェーデン発の政策枠組み。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2014,"Western_Europe",
     "https://en.wikipedia.org/wiki/Feminist_foreign_policy"),
    ("マルチスピーシーズフェミニズム","Multispecies Feminism","Multispecies Feminism",
     "フェミニスト理論を人間以外の種・動物・植物との関係に拡張するHaraway・アニマルスタディーズとの接続。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2003,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    ("第4波フェミニズム","Fourth Wave Feminism","Fourth Wave Feminism",
     "SNS・#MeToo・インターセクショナリティを中心に2010年代以降展開するフェミニズムの波。デジタル空間での連帯と運動。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2012,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Fourth-wave_feminism"),
    ("フェミニスト経済学","Feminist Economics","Feminist Economics",
     "経済学の男性中心的前提を批判し、ケア労働・無償労働・生産・再生産の複合体として経済を再定義する研究。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1992,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_economics"),
    ("性的資本","Erotic Capital","Erotic Capital",
     "身体的魅力・社会的スキル・性的表現能力が社会的・経済的資源として機能することを論じるHakim概念。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2010,"Western_Europe",
     "https://en.wikipedia.org/wiki/Erotic_capital"),
    ("フェミニスト統治性","Feminist Governmentality","Feminist Governmentality",
     "フーコーの統治性概念をジェンダー・セクシュアリティ・身体管理の観点から批判的に展開するフェミニスト研究。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1990,"North_America",
     "https://en.wikipedia.org/wiki/Governmentality"),
    ("フェミニスト認識論の争点","Debates in Feminist Epistemology","Feminist Standpoint Epistemology",
     "スタンドポイント・経験知・客観性・価値自由をめぐるフェミニスト認識論の内部論争。HardingとLongino等の対話。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1991,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_epistemology"),
    # ポストコロニアル・脱植民地理論 (+20)
    ("アフロペシミズム","Afropessimism","Afropessimism",
     "黒人性が奴隷制・社会的死・一般的な人間性からの排除によって根本的に異なる立場に置かれているとするWildersonらの理論。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2010,"North_America",
     "https://en.wikipedia.org/wiki/Afropessimism"),
    ("脱植民地化カリキュラム","Decolonizing the Curriculum","Decolonizing the Curriculum",
     "学校・大学の教育内容から植民地的知識体系・欧州中心主義を排除し周縁化された知識を回復する教育実践。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",2015,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Decolonization_of_knowledge"),
    ("ラテンアメリカ解放神学","Latin American Liberation Theology","Teología de la liberación",
     "グティエレス等が1960年代以降展開した貧者への優先的選択・構造的罪・解放の実践を核とする神学思想。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1968,"Latin_America",
     "https://en.wikipedia.org/wiki/Liberation_theology"),
    ("ネグリチュード運動","Négritude Movement","Négritude",
     "セゼール・サンゴール等フランス語圏のアフリカ・カリブ系知識人が1930年代に展開した黒人文化・価値の再評価運動。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1935,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/N%C3%A9gritude"),
    ("植民地責任","Colonial Responsibility","Colonial Responsibility",
     "旧宗主国が植民地支配によって生じた歴史的損害について謝罪・賠償・修復的責任を負うべきかをめぐる法的・倫理的議論。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Colonial_reparations"),
    ("ポストコロニアルトラウマ理論","Postcolonial Trauma Theory","Postcolonial Trauma Theory",
     "植民地暴力・強制移住・文化破壊が集合的・世代的に引き継がれる心理的傷を分析する文学・社会学的枠組み。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2001,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Postcolonialism"),
    ("南アジアのポストコロニアル国家","South Asian Postcolonial State","South Asian Postcolonial State",
     "インド・パキスタン・バングラデシュ独立後の国家形成・民族紛争・民主主義・開発の政治社会学的分析。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1947,"South_Asia",
     "https://en.wikipedia.org/wiki/Partition_of_India"),
    ("脱植民地建築","Decolonial Architecture","Decolonial Architecture",
     "植民地支配が都市計画・建築様式・空間組織に刻んだ権力構造を批判し先住民・地域の知識に基づく建築を模索する実践。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Decoloniality"),
    ("先住民の主権","Indigenous Sovereignty","Indigenous Sovereignty",
     "先住民族の土地・自己決定・文化・知識に対する主権を国際法・政治哲学・運動の観点から論じる研究。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1975,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Indigenous_sovereignty"),
    ("世界システムとポストコロニアリズム","World-System and Postcolonialism","World-System and Postcolonialism",
     "ウォーラーステインの世界システム論とポストコロニアル理論の対話。南北格差・植民地的分業・ヘゲモニー移行。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/World-systems_theory"),
    # 政治社会学・国家論 (+20)
    ("民主的合法性","Democratic Legitimacy","Democratic Legitimacy",
     "民主的手続きによって政治権力が正統性を獲得するメカニズム。手続き的・実質的・熟議的正統性の諸説。",
     "政治社会学・国家論","政治社会学",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Political_legitimacy"),
    ("国家の失敗","State Failure","State Failure",
     "政府の基本的機能（安全・法の支配・公共サービス・正統性）が崩壊する状態。コンゴ・ソマリア等が事例。",
     "政治社会学・国家論","国家論",1993,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Failed_state"),
    ("政策移転","Policy Transfer","Policy Transfer",
     "政策アイデア・制度・プログラムが国家間・組織間で移植・借用される過程。グローバル政策収斂の要因分析。",
     "政治社会学・国家論","政治社会学",1993,"Western_Europe",
     "https://en.wikipedia.org/wiki/Policy_transfer"),
    ("政治ネットワーク","Political Network","Political Network",
     "政策決定に関与する国家・利益集団・専門家・国際機関のネットワーク的ガバナンス構造の分析。",
     "政治社会学・国家論","政治社会学",1995,"Western_Europe",
     "https://en.wikipedia.org/wiki/Policy_network_analysis"),
    ("権威主義の持続","Authoritarian Persistence","Authoritarian Persistence",
     "権威主義体制が民主化圧力・経済危機・大衆運動にもかかわらず存続するメカニズムの比較政治社会学。",
     "政治社会学・国家論","比較政治社会学",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Authoritarianism"),
    ("ハイブリッド体制","Hybrid Regime","Hybrid Regime",
     "民主的要素と権威主義的要素が混在する体制。競争的権威主義・選挙主義・illiberal democracy等の類型を含む。",
     "政治社会学・国家論","比較政治社会学",2002,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Hybrid_regime"),
    ("腐敗の政治社会学","Political Sociology of Corruption","Corruption",
     "公権力の私的利用・賄賂・依怙贔屓を社会的・制度的文脈で分析する政治社会学。反腐敗運動・制度設計と連動。",
     "政治社会学・国家論","政治社会学",1967,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Political_corruption"),
    ("国際社会化","International Socialization","International Socialization",
     "国際規範・条約・組織が国内政治アクターの選好・行動・アイデンティティを変容させる過程の研究。",
     "政治社会学・国家論","政治社会学",1998,"Western_Europe",
     "https://en.wikipedia.org/wiki/Socialization"),
    ("新制度主義政治学","New Institutionalism in Political Science","New Institutionalism",
     "制度が政治行動・政策結果を制約・機会を提供する独立変数として機能することを論じる政治社会学の主流パラダイム。",
     "政治社会学・国家論","政治社会学",1984,"North_America",
     "https://en.wikipedia.org/wiki/New_institutionalism"),
    ("政党システム","Party System","Party System",
     "複数政党間の競争・連立・分極化のパターンを比較分析する政治社会学の中心的分析単位。Sartoriの類型が標準的。",
     "政治社会学・国家論","政治社会学",1976,"Western_Europe",
     "https://en.wikipedia.org/wiki/Party_system"),
    # 文化社会学・知識社会学 (+20)
    ("数字の社会学","Sociology of Numbers","Sociology of Quantification",
     "統計・指標・ランキング・数量化が社会的現実を構築・管理・競争化する権力的プロセスの研究。Porter等が代表。",
     "文化社会学・知識社会学","知識社会学",1995,"North_America",
     "https://en.wikipedia.org/wiki/Sociology_of_quantification"),
    ("感情の社会学","Sociology of Emotions","Sociology of Emotions",
     "感情が社会的に構築・管理・規範化される過程。感情ルール・感情労働・感情資本主義の概念と研究。",
     "文化社会学・知識社会学","文化社会学",1975,"North_America",
     "https://en.wikipedia.org/wiki/Sociology_of_emotions"),
    ("危機の文化社会学","Cultural Sociology of Crisis","Cultural Sociology of Crisis",
     "社会的危機（パンデミック・金融崩壊・戦争）が文化・意味・連帯を変容させる過程の文化社会学的分析。",
     "文化社会学・知識社会学","文化社会学",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Cultural_sociology"),
    ("観光の社会学","Sociology of Tourism","Sociology of Tourism",
     "観光が近代性・視線・真正性・場所のアイデンティティ・南北格差を構築する社会的実践の研究。MacCannell等。",
     "文化社会学・知識社会学","文化社会学",1973,"North_America",
     "https://en.wikipedia.org/wiki/Sociology_of_tourism"),
    ("科学の政治経済","Political Economy of Science","Political Economy of Science",
     "研究資金・知的財産・学術資本主義・産学連携が科学知識の生産・方向・公開性を規定する構造の研究。",
     "文化社会学・知識社会学","知識社会学",1990,"North_America",
     "https://en.wikipedia.org/wiki/Academic_capitalism"),
    ("集合記憶の政治","Politics of Collective Memory","Politics of Memory",
     "歴史認識・記念碑・博物館・謝罪・国民統合に使用される過去の政治的利用をめぐる記憶の闘争。",
     "文化社会学・知識社会学","文化社会学",1992,"Western_Europe",
     "https://en.wikipedia.org/wiki/Collective_memory"),
    ("身体文化","Body Culture","Body Culture",
     "スポーツ・ファッション・美容・医療・ダンス等において身体が社会的・文化的意味を付与される実践の研究。",
     "文化社会学・知識社会学","文化社会学",1980,"Western_Europe",
     "https://en.wikipedia.org/wiki/Body_culture"),
    ("プロフェッションの社会学","Sociology of Professions","Sociology of Professions",
     "医師・弁護士・教師等の専門職が知識独占・参入規制・倫理規範・自律性を通じて地位を維持する社会的メカニズム。",
     "文化社会学・知識社会学","知識社会学",1958,"North_America",
     "https://en.wikipedia.org/wiki/Sociology_of_the_professions"),
    ("ポップカルチャーとデジタル","Popular Culture and Digital Media","Popular Culture and Digital Media",
     "TikTok・YouTube・Spotifyがポップカルチャーの生産・流通・ファンコミュニティを変容させる文化社会学的研究。",
     "文化社会学・知識社会学","文化社会学",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_media"),
    ("農村社会学","Rural Sociology","Rural Sociology",
     "農村・農業・農民コミュニティの社会変動・都市農村関係・農業政策・農村ジェントリフィケーションの研究。",
     "文化社会学・知識社会学","文化社会学",1895,"North_America",
     "https://en.wikipedia.org/wiki/Rural_sociology"),
    # 生活世界・現象学的社会学 (+20)
    ("記憶と場所","Memory and Place","Memory and Place",
     "特定の場所・景観・建築が集合記憶・アイデンティティ・ノスタルジアを喚起する現象学的・社会学的研究。",
     "生活世界・現象学的社会学","現象学的社会学",1992,"Western_Europe",
     "https://en.wikipedia.org/wiki/Place_attachment"),
    ("食事の現象学","Phenomenology of Eating","Phenomenology of Eating",
     "食べる行為を身体経験・感覚・儀礼・他者との共食として分析する現象学的・文化的アプローチ。",
     "生活世界・現象学的社会学","現象学的社会学",2000,"Western_Europe",
     "https://en.wikipedia.org/wiki/Food_and_eating_experiences"),
    ("睡眠の社会学","Sociology of Sleep","Sociology of Sleep",
     "睡眠が社会的時間管理・労働体制・ジェンダー・健康格差・監視と結びつく社会的現象としての研究。",
     "生活世界・現象学的社会学","現象学的社会学",2008,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_sleep"),
    ("日常的抵抗","Everyday Resistance","Everyday Resistance",
     "スコットが論じた、公然たる反乱ではなく農民・弱者が日常的に行うサボタージュ・噂・回避による抵抗形態。",
     "生活世界・現象学的社会学","現象学的社会学",1985,"North_America",
     "https://en.wikipedia.org/wiki/Everyday_resistance"),
    ("道徳的経済","Moral Economy","Moral Economy",
     "スコット・トンプソンが論じた、市場論理に先立つ共同体の互酬・公正観念に基づく農民の経済道徳。",
     "生活世界・現象学的社会学","現象学的社会学",1971,"Western_Europe",
     "https://en.wikipedia.org/wiki/Moral_economy"),
    ("趣味と生活スタイル","Taste and Lifestyle","Taste and Lifestyle",
     "ブルデューの階層論を超えて文化的嗜好・余暇実践・消費スタイルが生活世界でどう意味づけられるかの研究。",
     "生活世界・現象学的社会学","現象学的社会学",1979,"Western_Europe",
     "https://en.wikipedia.org/wiki/Lifestyle_(sociology)"),
    ("労働の現象学","Phenomenology of Work","Phenomenology of Work",
     "働く経験の意味・身体的関与・時間感覚・疎外・自己実現を第一人称的視点から記述する研究。",
     "生活世界・現象学的社会学","現象学的社会学",1960,"Western_Europe",
     "https://en.wikipedia.org/wiki/Work_experience"),
    ("快楽主義の社会学","Sociology of Hedonism","Sociology of Hedonism",
     "消費社会・余暇文化における快楽追求の社会的意味・道徳的論争・身体経験の研究。Campbellの「ロマン主義的倫理」と関連。",
     "生活世界・現象学的社会学","現象学的社会学",1987,"Western_Europe",
     "https://en.wikipedia.org/wiki/Hedonism"),
    ("移動の現象学","Phenomenology of Mobility","Phenomenology of Mobility",
     "歩行・通勤・旅行・移住における身体的経験・場所感覚・時間性を記述するモビリティ研究の現象学的枠組み。",
     "生活世界・現象学的社会学","現象学的社会学",2006,"Western_Europe",
     "https://en.wikipedia.org/wiki/Mobilities_paradigm"),
    ("ものの現象学","Phenomenology of Things","Thing Theory",
     "日常的な物体・道具・テクノロジーが人間経験・実践・アイデンティティに参与する様式を論じる物質文化論。",
     "生活世界・現象学的社会学","現象学的社会学",2001,"North_America",
     "https://en.wikipedia.org/wiki/Material_culture"),
    # 環境社会学・人新世 (+15)
    ("気候心理学","Climate Psychology","Climate Psychology",
     "気候変動への不安・否認・グリーフ・行動変容を心理学的視点で研究する新興領域。ソラスタルジアを含む。",
     "環境社会学・人新世","環境社会学",2003,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Eco-anxiety"),
    ("植物の知性論","Plant Intelligence Theory","Plant Intelligence",
     "植物のコミュニケーション・学習・記憶・社会的行動を論じる研究がポストヒューマン倫理・環境哲学に与える衝撃。",
     "環境社会学・人新世","人新世論",2013,"Western_Europe",
     "https://en.wikipedia.org/wiki/Plant_cognition"),
    ("絶滅の生態政治学","Extinction Biopolitics","Extinction Biopolitics",
     "種の絶滅を生命権力・資本主義的損傷・植民地的自然観の帰結として分析するマルチスピーシーズ政治学。",
     "環境社会学・人新世","政治生態学",2015,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Holocene_extinction"),
    ("アグロエコロジー","Agroecology","Agroecology",
     "生態学的原則を農業に適用し生物多様性・土壌健全性・コミュニティ自律を重視する農業哲学・実践・科学。",
     "環境社会学・人新世","環境社会学",1980,"Latin_America",
     "https://en.wikipedia.org/wiki/Agroecology"),
    ("環境と健康の不平等","Environmental Health Inequalities","Environmental Health Inequalities",
     "大気汚染・有害物質・気候変動への暴露が人種・階層・地域によって不均等に分布する構造的不平等の研究。",
     "環境社会学・人新世","環境社会学",1987,"North_America",
     "https://en.wikipedia.org/wiki/Environmental_health"),
]

print(f"Inserting {len(concepts)} concepts (Batch 24)...")
ins, skp = insert_batch(concepts)
print(f"Done. Inserted: {ins}, Skipped: {skp}")
