"""Batch 24 — Physics (30) + Chemistry (20) = 50 concepts"""
import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

PHYS_BATCH = [
    {
        "name_ja": "経路積分法", "name_en": "Path Integral Formulation",
        "definition": "Feynmanが定式化した量子力学の経路積分表示。粒子が全ての可能な経路を同時に取る確率振幅を積分することで量子振幅を計算する。",
        "impact_summary": "場の量子論・重力量子化・金融工学まで広く応用される量子力学の強力な定式化。",
        "subfield": "物理学", "school_of_thought": "量子場理論", "era_start": 1948,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Path_integral_formulation",
        "mathematical_formulation": r"K(x_f,t_f;x_i,t_i)=\int\mathcal{D}[x(t)]\exp\!\left(\frac{i}{\hbar}S[x(t)]\right)",
    },
    {
        "name_ja": "スキルミオン", "name_en": "Magnetic Skyrmions",
        "definition": "磁性体中に現れるトポロジカルに保護された渦状スピン構造。ナノスケールで安定に存在し、次世代スピントロニクスデバイスへの応用が期待される。",
        "impact_summary": "省エネ磁気メモリ・スピントロニクスの次世代候補として活発に研究されるトポロジカル磁性体現象。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 2009,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Magnetic_skyrmion",
        "mathematical_formulation": r"Q=\frac{1}{4\pi}\int\mathbf{n}\cdot\left(\frac{\partial\mathbf{n}}{\partial x}\times\frac{\partial\mathbf{n}}{\partial y}\right)dxdy",
    },
    {
        "name_ja": "量子ドット", "name_en": "Quantum Dots",
        "definition": "ナノメートルサイズの半導体結晶。量子閉じ込め効果によりサイズ依存の光学特性を示す。2023年ノーベル化学賞（Bawendi, Brus, Ekimov）。",
        "impact_summary": "LEDディスプレイ・太陽電池・生体イメージングなど幅広い応用を持つナノフォトニクスの基礎。",
        "subfield": "物理学", "school_of_thought": "ナノフォトニクス", "era_start": 1983,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2023/summary/",
        "mathematical_formulation": r"E_n=\frac{\hbar^2\pi^2 n^2}{2m^*R^2}",
    },
    {
        "name_ja": "弱局在と量子補正", "name_en": "Weak Localization and Quantum Corrections",
        "definition": "電子の量子干渉により金属薄膜の電気抵抗が低温で増大する現象。時間反転対称性の破れによって磁場で抑制される。",
        "impact_summary": "トポロジカル絶縁体・グラフェン電子輸送の量子補正を明らかにする重要な実験ツール。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 1979,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Weak_localization",
        "mathematical_formulation": r"\Delta\sigma=\frac{\alpha e^2}{\pi h}\ln\!\left(\frac{\tau_\phi}{\tau}\right)",
    },
    {
        "name_ja": "ボーア模型と水素原子", "name_en": "Bohr Model and Hydrogen Atom",
        "definition": "Niels Bohrが1913年に提案した水素原子の量子力学的模型。電子が離散的なエネルギー準位を持つと仮定し、スペクトル線を説明した。",
        "impact_summary": "量子力学発展の出発点となった半古典的原子模型。量子数・エネルギー準位の概念を導入。",
        "subfield": "物理学", "school_of_thought": "原子物理学", "era_start": 1913,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Bohr_model",
        "mathematical_formulation": r"E_n=-\frac{m_e e^4}{8\epsilon_0^2 h^2}\frac{1}{n^2}=-\frac{13.6\,\text{eV}}{n^2}",
    },
    {
        "name_ja": "マヨラナフェルミオン", "name_en": "Majorana Fermions",
        "definition": "自分自身が反粒子である特殊なフェルミオン。トポロジカル超伝導体の端に現れるマヨラナ束縛状態はトポロジカル量子計算への応用が期待される。",
        "impact_summary": "トポロジカル量子計算・ノイズ耐性量子ビットの実現候補として集中的に研究されるエキゾチック準粒子。",
        "subfield": "物理学", "school_of_thought": "トポロジカル物理学", "era_start": 2008,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Majorana_fermion",
        "mathematical_formulation": r"\gamma=\gamma^\dagger,\quad\{\gamma_i,\gamma_j\}=2\delta_{ij}",
    },
    {
        "name_ja": "フォノン散乱と熱伝導", "name_en": "Phonon Scattering and Thermal Conductivity",
        "definition": "格子振動量子（フォノン）の散乱機構が固体の熱伝導率を決定する。アンハーモニック散乱・不純物散乱・境界散乱が主要な機構。",
        "impact_summary": "熱電変換・半導体放熱・ナノ構造熱管理の設計に不可欠な熱伝導メカニズムの理解。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 1929,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Thermal_conductivity_of_silicon",
        "mathematical_formulation": r"\kappa=\frac{1}{3}Cv\ell,\quad\frac{1}{\tau}=\frac{1}{\tau_U}+\frac{1}{\tau_N}+\frac{1}{\tau_B}",
    },
    {
        "name_ja": "アンダーソン局在", "name_en": "Anderson Localization",
        "definition": "不規則ポテンシャル中で電子波動関数が空間的に局在化する現象。P.W. Andersonが1958年に予言し、1977年ノーベル物理学賞の受賞対象。",
        "impact_summary": "無秩序系における電子・光・音波の局在を統一的に説明する基礎概念。金属絶縁体転移の理論的根拠。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 1958,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Anderson_localization",
        "mathematical_formulation": r"\psi(\mathbf{r})\sim e^{-|\mathbf{r}-\mathbf{r}_0|/\xi},\quad\xi\text{: localization length}",
    },
    {
        "name_ja": "核磁気共鳴の物理", "name_en": "Nuclear Magnetic Resonance Physics",
        "definition": "外部磁場中で核スピンが特定の電磁波を吸収・放射する共鳴現象の物理。Bloch方程式とLarmor歳差運動が基礎理論。1952年ノーベル物理学賞。",
        "impact_summary": "MRI・NMR分光法・量子情報処理の基盤となる核スピン共鳴の物理的原理。",
        "subfield": "物理学", "school_of_thought": "原子核物理学", "era_start": 1946,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_magnetic_resonance",
        "mathematical_formulation": r"\frac{d\mathbf{M}}{dt}=\gamma\mathbf{M}\times\mathbf{B}-\frac{M_x\hat{x}+M_y\hat{y}}{T_2}-\frac{(M_z-M_0)\hat{z}}{T_1}",
    },
    {
        "name_ja": "ジョセフソン効果", "name_en": "Josephson Effect",
        "definition": "二つの超伝導体をトンネル接合で結合したとき電圧ゼロでも超電流が流れる現象（直流効果）と、電圧をかけると交流電流が生じる現象（交流効果）。1973年ノーベル物理学賞。",
        "impact_summary": "量子電圧標準・SQUID・超伝導量子ビットの動作原理として重要な超伝導マクロ量子現象。",
        "subfield": "物理学", "school_of_thought": "超伝導物理学", "era_start": 1962,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Josephson_effect",
        "mathematical_formulation": r"I=I_c\sin\varphi,\quad\frac{d\varphi}{dt}=\frac{2eV}{\hbar}",
    },
    {
        "name_ja": "格子ゲージ理論", "name_en": "Lattice Gauge Theory",
        "definition": "場の量子論を格子（離散時空）上に定式化した数値計算手法。クォーク閉じ込め・ハドロン質量の非摂動論的計算を可能にする。",
        "impact_summary": "量子色力学（QCD）の非摂動的研究と強結合現象の数値シミュレーションの基盤。",
        "subfield": "物理学", "school_of_thought": "素粒子物理学", "era_start": 1974,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Lattice_QCD",
        "mathematical_formulation": r"S_{\rm LGT}=\beta\sum_{\square}\left(1-\frac{1}{N_c}\text{Re}\,\text{Tr}\,U_\mu U_\nu U_\mu^\dagger U_\nu^\dagger\right)",
    },
    {
        "name_ja": "磁気抵抗効果", "name_en": "Magnetoresistance Effects",
        "definition": "磁場によって材料の電気抵抗が変化する現象群。巨大磁気抵抗（GMR: 1988年、2007年ノーベル物理学賞）・トンネル磁気抵抗（TMR）・コロッサル磁気抵抗（CMR）を含む。",
        "impact_summary": "ハードディスク磁気ヘッド技術の革命をもたらしたスピントロニクスの基礎的発見。",
        "subfield": "物理学", "school_of_thought": "スピントロニクス", "era_start": 1988,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/physics/2007/summary/",
        "mathematical_formulation": r"\text{GMR}=\frac{R_{AP}-R_P}{R_P},\quad\text{TMR}=\frac{G_P-G_{AP}}{G_{AP}}",
    },
    {
        "name_ja": "断熱定理と量子ポンプ", "name_en": "Adiabatic Theorem and Quantum Pumping",
        "definition": "系のハミルトニアンがゆっくり変化するとき量子状態が瞬時固有状態に留まるという定理。ベリー位相と幾何学的量子輸送（量子ポンプ）の基礎。",
        "impact_summary": "量子アニーリング・トポロジカル不変量・断熱量子計算の理論的基盤。",
        "subfield": "物理学", "school_of_thought": "量子力学", "era_start": 1928,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Adiabatic_theorem",
        "mathematical_formulation": r"\gamma_n=i\oint\langle n(\mathbf{R})|\nabla_\mathbf{R}|n(\mathbf{R})\rangle\cdot d\mathbf{R}",
    },
    {
        "name_ja": "オーバートーン分光と分子振動", "name_en": "Molecular Vibrations and Overtone Spectroscopy",
        "definition": "分子の化学結合は量子調和振動子として振動し、赤外・ラマン分光で観測できる。倍音・結合音などのオーバートーンバンドも重要な構造情報を提供する。",
        "impact_summary": "食品・医薬品・環境モニタリングのNIR分光分析の理論的基盤となる分子振動の量子論。",
        "subfield": "物理学", "school_of_thought": "分子物理学", "era_start": 1923,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Molecular_vibration",
        "mathematical_formulation": r"E_v=\hbar\omega\left(v+\frac{1}{2}\right)-\hbar\omega x_e\left(v+\frac{1}{2}\right)^2",
    },
    {
        "name_ja": "宇宙線と高エネルギー粒子物理", "name_en": "Cosmic Rays and High-Energy Particle Astrophysics",
        "definition": "宇宙から飛来する高エネルギー荷電粒子（主に陽子）の検出・起源・加速機構の研究。空気シャワー観測により超高エネルギー粒子の特性を解明する。",
        "impact_summary": "陽電子・ミュオンの発見など素粒子物理の発展に貢献し、宇宙の最高エネルギー現象を探る。",
        "subfield": "物理学", "school_of_thought": "宇宙線物理学", "era_start": 1912,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Cosmic_ray",
        "mathematical_formulation": r"J(E)\propto E^{-\gamma},\quad\gamma\approx2.7\,(E<4\times10^{15}\,\text{eV})",
    },
    {
        "name_ja": "光電子分光法", "name_en": "Photoelectron Spectroscopy",
        "definition": "光を照射して放出される光電子のエネルギー分布を測定し、固体・分子の電子状態・バンド構造・化学結合を解析する手法。UPS・XPS・ARPES等を含む。",
        "impact_summary": "表面化学・バンド構造・トポロジカル物質の実験的研究に不可欠な電子分光技術。",
        "subfield": "物理学", "school_of_thought": "表面物理学", "era_start": 1954,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/X-ray_photoelectron_spectroscopy",
        "mathematical_formulation": r"E_k=h\nu-E_b-\phi,\quad E_b=E_f-E_i",
    },
    {
        "name_ja": "量子ウォーク", "name_en": "Quantum Walk",
        "definition": "古典ランダムウォークの量子版。重ね合わせ状態で複数の経路を同時に歩くことで古典より速い拡散を示し、量子アルゴリズムの基礎となる。",
        "impact_summary": "量子計算における探索アルゴリズムの高速化・量子シミュレーションの基本プリミティブ。",
        "subfield": "物理学", "school_of_thought": "量子情報科学", "era_start": 1993,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_walk",
        "mathematical_formulation": r"|\psi(t)\rangle=U^t|\psi(0)\rangle,\quad U=S(C\otimes I)",
    },
    {
        "name_ja": "中性子星と核物質", "name_en": "Neutron Stars and Nuclear Matter",
        "definition": "超高密度の崩壊した恒星で、核密度を超える状態方程式が支配する。質量・半径測定から核力の理解が深まり、重力波観測（2017年ノーベル物理学賞関連）とも密接に関連。",
        "impact_summary": "極限核物質・クォーク物質・パルサー天体物理の交差点として核物理と天体物理を繋ぐ。",
        "subfield": "物理学", "school_of_thought": "天体物理学", "era_start": 1934,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Neutron_star",
        "mathematical_formulation": r"M_{\max}\approx0.7\left(\frac{\hbar c}{G}\right)^{3/2}\frac{1}{m_n^2}\approx3M_\odot",
    },
    {
        "name_ja": "希土類磁石の物理", "name_en": "Rare-Earth Magnets Physics",
        "definition": "NdFeB・SmCo等の希土類永久磁石は4f電子の強いスピン軌道結合により巨大な磁気異方性を示す。現代モーターの高性能化に不可欠。",
        "impact_summary": "EV・風力発電・MRIに使われる最強永久磁石の物理的基盤。中国が世界の希土類生産の大半を担う。",
        "subfield": "物理学", "school_of_thought": "磁性物理学", "era_start": 1966,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Rare-earth_magnet",
        "mathematical_formulation": r"K_1=\frac{\Delta E}{\sin^2\theta V},\quad\mu_0 H_A=\frac{2K_1}{\mu_0 M_s}",
    },
    {
        "name_ja": "アインシュタイン固体モデル", "name_en": "Einstein Solid Model",
        "definition": "固体の比熱を量子調和振動子の独立振動として計算した最初の量子論的模型（1907年）。低温での比熱の実験値を古典論より良く説明した。",
        "impact_summary": "固体比熱の量子的理解の出発点。Debyeモデルへの発展を導いた量子固体物理の先駆。",
        "subfield": "物理学", "school_of_thought": "統計力学", "era_start": 1907,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Einstein_solid",
        "mathematical_formulation": r"C_V=3Nk_B\left(\frac{\Theta_E}{T}\right)^2\frac{e^{\Theta_E/T}}{(e^{\Theta_E/T}-1)^2}",
    },
    {
        "name_ja": "磁場中の量子輸送", "name_en": "Quantum Transport in Magnetic Fields",
        "definition": "磁場下での電子輸送現象。ランダウ準位・シュブニコフ・ドハース振動・整数・分数量子ホール効果が含まれる。1980年・1998年ノーベル物理学賞。",
        "impact_summary": "基礎物理定数の精密測定・トポロジカル物質の電子輸送特性解明に中心的な役割。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 1930,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Landau_levels",
        "mathematical_formulation": r"E_{n,k_z}=\hbar\omega_c\!\left(n+\tfrac{1}{2}\right)+\frac{\hbar^2 k_z^2}{2m^*},\quad\omega_c=\frac{eB}{m^*}",
    },
    {
        "name_ja": "光圧と放射圧", "name_en": "Radiation Pressure and Optical Forces",
        "definition": "電磁波が物体に及ぼす力（放射圧）。レーザー冷却・光ピンセット（2018年ノーベル物理学賞）の基礎であり、太陽帆宇宙船の推進原理でもある。",
        "impact_summary": "光ピンセットによる単一分子操作・レーザー冷却・光圧推進の基礎となる光力学の根幹。",
        "subfield": "物理学", "school_of_thought": "光学・フォトニクス", "era_start": 1873,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Radiation_pressure",
        "mathematical_formulation": r"P_{\rm rad}=\frac{I}{c}\,({\rm absorption}),\quad P_{\rm rad}=\frac{2I}{c}\,({\rm reflection})",
    },
    {
        "name_ja": "ポーラロン", "name_en": "Polaron",
        "definition": "電子がイオン結晶の格子歪みと相互作用して形成する準粒子。有機半導体・ペロブスカイト太陽電池の電荷輸送を支配する。",
        "impact_summary": "有機エレクトロニクス・ペロブスカイト光電変換の電荷輸送メカニズムの基礎理論。",
        "subfield": "物理学", "school_of_thought": "凝縮系物理学", "era_start": 1933,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Polaron",
        "mathematical_formulation": r"m_p^*=m_e^*\left(1+\frac{\alpha}{6}+\cdots\right),\quad\alpha=\frac{e^2}{\hbar}\sqrt{\frac{m_e^*}{2\hbar\omega_{\rm LO}}}\left(\frac{1}{\epsilon_\infty}-\frac{1}{\epsilon_0}\right)",
    },
    {
        "name_ja": "インド古典力学のヴァイシェーシカ学派", "name_en": "Vaisheshika Atomism",
        "definition": "古代インドのカナーダ（紀元前600-100年頃）が提唱した原子論的自然哲学。物質は不可分な極微（パラマーヌ）から構成されるという概念を展開した。",
        "impact_summary": "ギリシャ原子論と独立に発展した南アジアの原子論哲学。インド自然哲学における物質観の基盤。",
        "subfield": "物理学", "school_of_thought": "古代自然哲学", "era_start": -500,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Vaisheshika",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "アラビア科学の光学理論", "name_en": "Ibn al-Haytham Optics",
        "definition": "11世紀のイブン・アル＝ハイサム（アルハゼン）による『光学の書（Kitab al-Manazir）』。視覚の入射理論・暗箱・反射・屈折の数理的研究を展開し近代光学の父とされる。",
        "impact_summary": "中世イスラム科学の最高峰の一つ。近代実験科学の方法論と幾何光学の基礎を確立した。",
        "subfield": "物理学", "school_of_thought": "イスラム科学", "era_start": 1011,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Book_of_Optics",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "電弱理論の自発的対称性の破れ", "name_en": "Spontaneous Symmetry Breaking in Electroweak Theory",
        "definition": "ヒッグス機構によりゲージ対称性が自発的に破れ、W・Zボソンが質量を獲得する電弱統一理論の核心概念。2012年LHCでヒッグスボソンを発見。",
        "impact_summary": "素粒子の標準模型の核心であり、2012年ヒッグス発見（2013年ノーベル物理学賞）で完成した。",
        "subfield": "物理学", "school_of_thought": "素粒子物理学", "era_start": 1964,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Higgs_mechanism",
        "mathematical_formulation": r"V(\phi)=-\mu^2|\phi|^2+\lambda|\phi|^4,\quad\langle|\phi|\rangle=v=\sqrt{\mu^2/(2\lambda)}",
    },
    {
        "name_ja": "スーパーラジアンスと集団放射", "name_en": "Superradiance and Collective Emission",
        "definition": "Dickが1954年に予言した現象。多くの二準位原子が集団的に同期して超高速・超高強度の光パルスを放射する量子光学効果。",
        "impact_summary": "量子光学・量子多体系・原子レーザーの理論的基盤となる集団量子現象。",
        "subfield": "物理学", "school_of_thought": "量子光学", "era_start": 1954,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Superradiance",
        "mathematical_formulation": r"I_{\rm SR}\propto N^2 I_{\rm single},\quad\tau_{\rm SR}\propto 1/N",
    },
    {
        "name_ja": "散逸系と揺動散逸定理", "name_en": "Fluctuation-Dissipation Theorem",
        "definition": "熱平衡系での自発的ゆらぎと外部摂動への線形応答（散逸）を結びつける定理。ジョンソンノイズ・ブラウン運動・電気インピーダンスに適用される。",
        "impact_summary": "非平衡統計力学・電気回路雑音理論・生物物理の基礎となる普遍的な熱統計力学の定理。",
        "subfield": "物理学", "school_of_thought": "統計力学", "era_start": 1951,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Fluctuation-dissipation_theorem",
        "mathematical_formulation": r"S(\omega)=\frac{2k_BT}{\omega}\,\text{Im}\,\chi(\omega)",
    },
    {
        "name_ja": "荷電粒子の加速器物理", "name_en": "Accelerator Physics",
        "definition": "荷電粒子を高エネルギーに加速する装置の設計・制御の物理。サイクロトロン・シンクロトロン・リニアックの動作原理と粒子ビームの位相空間体積（エミッタンス）制御。",
        "impact_summary": "素粒子実験・癌治療・放射光生成に使われる現代科学技術の中枢インフラの物理基盤。",
        "subfield": "物理学", "school_of_thought": "加速器物理学", "era_start": 1930,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Accelerator_physics",
        "mathematical_formulation": r"T=(\gamma-1)m_0c^2,\quad p=\gamma m_0 v,\quad qBr=\gamma m_0 v",
    },
]

CHEM_BATCH = [
    {
        "name_ja": "自由エネルギー摂動法", "name_en": "Free Energy Perturbation",
        "definition": "二つの状態間の自由エネルギー差を計算機シミュレーションで求める手法。薬物設計・溶媒和エネルギー計算に広く用いられる。",
        "impact_summary": "創薬における結合自由エネルギー予測の標準的な計算化学手法。2013年ノーベル化学賞の応用分野。",
        "subfield": "化学", "school_of_thought": "計算化学", "era_start": 1985,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Free_energy_perturbation",
        "mathematical_formulation": r"\Delta F_{AB}=-k_BT\ln\langle e^{-(H_B-H_A)/k_BT}\rangle_A",
    },
    {
        "name_ja": "金属有機構造体", "name_en": "Metal-Organic Frameworks",
        "definition": "金属イオンと有機配位子が自己集合して形成する多孔性配位高分子。巨大な比表面積を持ちガス吸着・触媒・薬物送達に利用される。",
        "impact_summary": "CO2回収・水素貯蔵・薬物徐放の次世代材料として急速に発展する機能性多孔性材料。",
        "subfield": "化学", "school_of_thought": "材料化学", "era_start": 1999,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Metal%E2%80%93organic_framework",
        "mathematical_formulation": r"S_{\rm BET}=\frac{n_m N_A\sigma}{M},\quad[\text{from BET adsorption isotherm}]",
    },
    {
        "name_ja": "有機光レドックス触媒", "name_en": "Organic Photoredox Catalysis",
        "definition": "可視光を吸収した有機色素が励起状態で電子移動を媒介する光触媒機構。マクミラン（2021年ノーベル化学賞共同受賞）が発展させた双対触媒系も重要。",
        "impact_summary": "穏和な条件での炭素−炭素結合形成・ラジカル合成を可能にする現代有機合成の鍵技術。",
        "subfield": "化学", "school_of_thought": "有機合成化学", "era_start": 2008,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Photoredox_catalysis",
        "mathematical_formulation": r"E^*_{\rm ox}=E_{\rm ox}-\Delta E_{0,0},\quad E^*_{\rm red}=E_{\rm red}+\Delta E_{0,0}",
    },
    {
        "name_ja": "溶媒和と双極子相互作用", "name_en": "Solvation and Solvent Effects",
        "definition": "溶質分子が溶媒分子と相互作用することで安定化される現象。双極子相互作用・水素結合・疎水効果が主要な寄与。Marcus溶媒和理論が電子移動を記述する。",
        "impact_summary": "反応速度・選択性・生体分子の折りたたみを決定する溶媒効果の統一的理論。",
        "subfield": "化学", "school_of_thought": "物理化学", "era_start": 1956,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Solvation",
        "mathematical_formulation": r"\Delta G_{\rm solv}=-\frac{N_A z^2 e^2}{8\pi\epsilon_0 r}\left(1-\frac{1}{\epsilon_r}\right)\quad(\text{Born model})",
    },
    {
        "name_ja": "超分子集合体と自己組織化", "name_en": "Supramolecular Self-Assembly",
        "definition": "分子間の非共有結合相互作用（水素結合・π-πスタッキング・ファンデルワールス力）によって自発的に秩序構造を形成するプロセス。1987年ノーベル化学賞の延長線上。",
        "impact_summary": "ナノカプセル・人工細胞膜・自己修復材料・薬物送達システムの分子設計の基盤。",
        "subfield": "化学", "school_of_thought": "超分子化学", "era_start": 1987,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Supramolecular_chemistry",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "分子機械とカテナン", "name_en": "Molecular Machines and Catenanes",
        "definition": "機械的に結合した分子（機械的に組み合わせた分子 MIM）。カテナン・ロタキサン・分子モーターが代表例。2016年ノーベル化学賞（Sauvage, Stoddart, Feringa）。",
        "impact_summary": "ナノロボット・薬物放出制御・スマートマテリアルへの応用が期待される分子機械の確立。",
        "subfield": "化学", "school_of_thought": "超分子化学", "era_start": 1983,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2016/summary/",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "固体NMRと結晶構造解析", "name_en": "Solid-State NMR Spectroscopy",
        "definition": "固体試料の核磁気共鳴。魔角回転（MAS）等の技術により化学シフト・カップリング・構造情報を得る。無機材料・タンパク質凝集体・薬物多形の解析に重要。",
        "impact_summary": "X線解析が困難な不規則固体・膜タンパク質・医薬多形の構造解明に不可欠な分光法。",
        "subfield": "化学", "school_of_thought": "分析化学", "era_start": 1958,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Solid-state_nuclear_magnetic_resonance",
        "mathematical_formulation": r"\delta_{\rm iso}=\frac{\delta_{11}+\delta_{22}+\delta_{33}}{3},\quad\text{MAS: }\omega_r^2\gg\omega_{\rm CS}^2",
    },
    {
        "name_ja": "ペロブスカイト太陽電池の化学", "name_en": "Perovskite Solar Cell Chemistry",
        "definition": "ABX3型ペロブスカイト構造の有機-無機ハイブリッド材料（CH3NH3PbI3等）を光活性層に用いた次世代太陽電池。変換効率が急速に向上し25%超を達成。",
        "impact_summary": "2012年以降急速に効率が向上した次世代薄膜太陽電池。日本・韓国・中国の研究が先導。",
        "subfield": "化学", "school_of_thought": "材料化学", "era_start": 2009,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Perovskite_solar_cell",
        "mathematical_formulation": r"\eta=\frac{J_{sc}V_{oc}FF}{P_{in}},\quad\text{PCE}>25\%",
    },
    {
        "name_ja": "オスモシスと膜分離化学", "name_en": "Osmosis and Membrane Separation Chemistry",
        "definition": "半透膜を通じた溶媒の移動（浸透）と逆浸透圧膜による淡水化・純水製造の化学。ファントホッフの浸透圧式が基礎理論。",
        "impact_summary": "海水淡水化・医療透析・食品濃縮の基盤となる膜分離の化学原理。中東・北アフリカで重要。",
        "subfield": "化学", "school_of_thought": "物理化学", "era_start": 1877,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Osmosis",
        "mathematical_formulation": r"\Pi=iMRT=\frac{n_{\rm solute}RT}{V}",
    },
    {
        "name_ja": "燃料電池の電気化学", "name_en": "Fuel Cell Electrochemistry",
        "definition": "水素や炭化水素の酸化反応から直接電気エネルギーを取り出す電気化学装置。陽極（酸化）・陰極（還元）でのButler-Volmer式に基づく電極反応が基礎。",
        "impact_summary": "カーボンニュートラル社会の鍵技術。自動車・分散電源・宇宙開発に応用されるクリーンエネルギー変換。",
        "subfield": "化学", "school_of_thought": "電気化学", "era_start": 1839,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Fuel_cell",
        "mathematical_formulation": r"E_{\rm cell}=E^\circ-\frac{RT}{nF}\ln Q,\quad\Delta G=-nFE",
    },
    {
        "name_ja": "遷移金属触媒によるC-H活性化", "name_en": "C-H Activation by Transition Metal Catalysts",
        "definition": "通常不活性なC-H結合を遷移金属触媒（Pd・Rh・Ru等）で直接官能基化する反応。原料からの直接変換で廃棄物を削減する原子効率の高い合成戦略。",
        "impact_summary": "医薬品・農薬・機能性材料合成の工程短縮を実現する現代有機合成の最重要領域の一つ。",
        "subfield": "化学", "school_of_thought": "有機金属化学", "era_start": 1993,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/C%E2%80%93H_activation",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "熱重量分析と示差走査熱量測定", "name_en": "Thermal Analysis: TGA and DSC",
        "definition": "熱重量分析（TGA）は温度変化による試料質量変化を測定し、示差走査熱量測定（DSC）は熱流を測定する。融点・結晶化・分解温度・相転移の同定に使われる。",
        "impact_summary": "医薬品多形・高分子・無機材料の熱安定性と相転移の標準的な特性評価法。",
        "subfield": "化学", "school_of_thought": "分析化学", "era_start": 1915,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Thermogravimetric_analysis",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "酵素触媒の反応速度論", "name_en": "Enzyme Kinetics",
        "definition": "ミカエリス-メンテン速度式に基づく酵素-基質複合体形成と生成物放出の速度論的解析。Km・Vmax・kcat等のパラメータが酵素活性を定量化する。",
        "impact_summary": "医薬品酵素阻害剤設計・代謝工学・バイオプロセス最適化の理論的基盤。",
        "subfield": "化学", "school_of_thought": "生化学", "era_start": 1913,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics",
        "mathematical_formulation": r"v=\frac{V_{\max}[S]}{K_m+[S]},\quad K_m=\frac{k_{-1}+k_{\rm cat}}{k_1}",
    },
    {
        "name_ja": "アフリカの伝統的な金属製錬化学", "name_en": "African Traditional Metallurgy Chemistry",
        "definition": "サブサハラアフリカにおける鉄・銅・青銅の製錬技術。タンザニアのハヤ族の高温製錬（1400℃超）はヨーロッパより早く達成された。炭素と鉄酸化物の還元反応が基本。",
        "impact_summary": "西洋技術史が見落としてきたアフリカ独自の金属化学の実践。考古学と化学分析で再評価が進む。",
        "subfield": "化学", "school_of_thought": "技術史・民族化学", "era_start": -1000,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/History_of_metallurgy_in_sub-Saharan_Africa",
        "mathematical_formulation": r"\text{Fe}_2\text{O}_3+3\text{CO}\rightarrow2\text{Fe}+3\text{CO}_2\,(T>1200^\circ\text{C})",
    },
    {
        "name_ja": "インドのラサシャーストラ錬金術", "name_en": "Indian Rasashastra Alchemy",
        "definition": "8-12世紀のインドで発展した水銀・硫黄・金属酸化物を用いた薬学体系。アーユルヴェーダと融合した独自の精製・錬成（マーラナ）プロセスを持つ。",
        "impact_summary": "インド独自の金属-医薬化学体系。現代での安全性研究も含め民族薬学の重要事例。",
        "subfield": "化学", "school_of_thought": "伝統知化学", "era_start": 800,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Rasa_shastra",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "同位体化学と重水素標識", "name_en": "Isotope Chemistry and Deuterium Labeling",
        "definition": "安定同位体（2H・13C・15N・18O）を使って分子の代謝経路・反応機構・構造を追跡する手法。重水素化医薬品（H/D交換）は薬物代謝改善にも用いられる。",
        "impact_summary": "反応機構解明・代謝追跡・重水素化医薬品設計に不可欠な同位体標識化学の方法論。",
        "subfield": "化学", "school_of_thought": "物理有機化学", "era_start": 1934,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Isotope_labeling",
        "mathematical_formulation": r"k_H/k_D=\exp\left[\frac{\Delta E_{ZPE}}{k_BT}\right]\approx2-7\,(\text{primary KIE})",
    },
    {
        "name_ja": "二酸化炭素の化学的固定", "name_en": "CO2 Chemical Fixation and Utilization",
        "definition": "CO2を化学原料として転換する反応。尿素合成・カーボネート合成・電気化学的還元によるギ酸・メタノール生成が主要プロセス。カーボンリサイクル戦略の核心。",
        "impact_summary": "気候変動対策の鍵技術。炭素資源循環と脱炭素化学産業への移行を可能にする。",
        "subfield": "化学", "school_of_thought": "グリーンケミストリー", "era_start": 1990,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Carbon_capture_and_utilization",
        "mathematical_formulation": r"\text{CO}_2+\text{H}_2\rightarrow\text{HCOOH}\,(\Delta G^\circ=-32\,\text{kJ/mol at }25^\circ\text{C})",
    },
    {
        "name_ja": "コンビナトリアル化学とハイスループット合成", "name_en": "Combinatorial Chemistry",
        "definition": "多数の化合物を並列的に合成しスクリーニングする手法。固相合成・スプリット-プール法により数万〜数百万の化合物ライブラリを一度に構築し創薬をリードする。",
        "impact_summary": "1990年代の創薬革命をもたらしたハイスループット合成・スクリーニングの基盤技術。",
        "subfield": "化学", "school_of_thought": "医薬化学", "era_start": 1992,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Combinatorial_chemistry",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "ゼオライトと多孔性触媒", "name_en": "Zeolites and Porous Catalysts",
        "definition": "SiO4・AlO4四面体が三次元的に規則配列した結晶性アルミノシリケート。均一なナノ細孔を持ち形状選択的触媒・イオン交換・分子篩として石油精製・化学合成に使われる。",
        "impact_summary": "石油精製クラッキング・自動車排ガス触媒・洗剤添加剤など現代化学産業の基幹多孔性材料。",
        "subfield": "化学", "school_of_thought": "無機化学", "era_start": 1756,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Zeolite",
        "mathematical_formulation": None,
    },
    {
        "name_ja": "ピラー層状ダブル水酸化物", "name_en": "Layered Double Hydroxides",
        "definition": "水酸化マグネシウムに類似した層状構造を持つ複合水酸化物（ハイドロタルサイト）。層間に陰イオンを取り込み触媒・薬物送達・難燃剤として利用される。",
        "impact_summary": "環境浄化・薬物送達・フレームリターダントとして多様な応用を持つ層状無機機能材料。",
        "subfield": "化学", "school_of_thought": "無機化学", "era_start": 1942,
        "culture_region": "Western_Europe_North_America",
        "source_url": "https://en.wikipedia.org/wiki/Layered_double_hydroxides",
        "mathematical_formulation": None,
    },
]

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    p = insert_batch(conn, PHYS_BATCH)
    c = insert_batch(conn, CHEM_BATCH)
    total = conn.execute("SELECT COUNT(*) FROM natural_discovery").fetchone()[0]
    conn.close()
    print(f"Batch24 phys+chem: {p+c} inserted (phys={p}, chem={c}). Total: {total}")
