"""
DUA Wave A2 Batch 13 — Physics supplement (~55 concepts, subfield '物理学')
Target: continue closing physics gap
"""
import sqlite3
import uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

BATCH1 = [
    {
        "name_ja": "断熱定理と量子ポンプ",
        "name_en": "Adiabatic Theorem and Quantum Pumping",
        "definition": "系のハミルトニアンが十分ゆっくり変化するとき、系は瞬間固有状態に留まるという定理（Born-Fock 1928）。幾何学的位相（Berry位相）やトポロジカルポンプと結びつく。",
        "impact_summary": "量子コンピューティング（断熱型量子計算・D-Waveの原理）、トポロジカル絶縁体の数学的記述、量子センサーへの応用基盤。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Mechanics",
        "era_start": 1928,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/PhysRevLett.51.2167",
        "mathematical_formulation": r"\gamma_n = i\oint \langle n(\mathbf{R})|\nabla_{\mathbf{R}}|n(\mathbf{R})\rangle \cdot d\mathbf{R}",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子ドットと人工原子",
        "name_en": "Quantum Dots and Artificial Atoms",
        "definition": "3次元的に閉じ込められた（ナノスケール）電子系。離散エネルギー準位を持ち原子に類似した電子構造を示す。半導体・コロイド・自己組織化型が存在。",
        "impact_summary": "量子ドットLED（QLED TV）・量子コンピュータ（スピン量子ビット）・バイオイメージング（蛍光量子ドット）・光電変換への応用。Brus・Bawendi・Ekimov(2023 Nobel)が確立。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1981,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2023/summary/",
        "mathematical_formulation": r"E_n \propto \frac{n^2\hbar^2\pi^2}{2m^* L^2}, \quad \Delta E \propto \frac{1}{R^2}",
        "data_completeness": 90,
    },
    {
        "name_ja": "摩擦と摩耗の物理（トライボロジー）",
        "name_en": "Tribology — Physics of Friction and Wear",
        "definition": "接触面間の摩擦・摩耗・潤滑を研究する物理工学分野。アモントン則（摩擦力∝垂直抗力）、境界潤滑、ナノトライボロジー（AFMによる原子スケール摩擦）を含む。",
        "impact_summary": "機械効率・エネルギー損失（世界エネルギーの約23%が摩擦損失）・機械部品寿命に直結。MEMS・ハードディスク・航空エンジン設計に不可欠。",
        "subfield": "物理学",
        "school_of_thought": "Classical Mechanics",
        "era_start": 1699,
        "culture_region": "Europe_Western",
        "source_url": "https://www.tribology.org/what-is-tribology/",
        "mathematical_formulation": r"F_f = \mu F_N, \quad \mu_s > \mu_k",
        "data_completeness": 85,
    },
    {
        "name_ja": "格子振動とフォノン",
        "name_en": "Lattice Vibrations and Phonons",
        "definition": "結晶格子の集団的振動をボソン準粒子（フォノン）として量子化して記述する理論。音響フォノンと光学フォノン、デバイ模型とアインシュタイン模型が基本。",
        "impact_summary": "熱伝導・比熱・熱電変換・超伝導（電子-フォノン相互作用）の基礎。熱電材料設計・半導体熱管理、固体レーザー（ラマン散乱）に直結。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1912,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.73.515",
        "mathematical_formulation": r"C_V = 9Nk_B\left(\frac{T}{\Theta_D}\right)^3\int_0^{\Theta_D/T}\frac{x^4 e^x}{(e^x-1)^2}dx",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子多体問題とハバード模型",
        "name_en": "Quantum Many-Body Problem and Hubbard Model",
        "definition": "多数の相互作用する電子系の量子力学的記述。ハバード模型は最も単純な格子電子相関模型で、金属-絶縁体転移・高温超伝導・磁性を理解するための基本モデル。",
        "impact_summary": "高温超伝導の理論的理解（銅酸化物超伝導体）・トポロジカル絶縁体・量子スピン液体の理論基盤。テンソルネットワーク・量子モンテカルロ・変分モンテカルロが数値解法として発展。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1963,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.78.17",
        "mathematical_formulation": r"\hat{H} = -t\sum_{\langle i,j\rangle,\sigma}(c^\dagger_{i\sigma}c_{j\sigma}+\text{h.c.}) + U\sum_i n_{i\uparrow}n_{i\downarrow}",
        "data_completeness": 88,
    },
    {
        "name_ja": "光格子と量子シミュレーター",
        "name_en": "Optical Lattices and Quantum Simulators",
        "definition": "レーザー光の定常波で形成されたポテンシャル格子に超冷原子を閉じ込め、固体物理模型（ハバード模型等）を精密にシミュレートする量子シミュレーション手法。",
        "impact_summary": "高温超伝導・量子磁性の未解決問題を原子系で探索可能にした。Bloch（ミュンヘン）らが2002年にBose-Hubbard模型の相転移を実証。量子コンピュータの実験台としても機能。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Optics",
        "era_start": 1987,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nature.com/articles/415039a",
        "data_completeness": 88,
    },
    {
        "name_ja": "核スピンとNMR物理",
        "name_en": "Nuclear Spin Physics and NMR",
        "definition": "原子核が持つスピン角運動量と磁気モーメントの量子力学。外部磁場中でのラーモア歳差運動・RF励起・緩和（T1/T2）が基本。MRI・固体NMR・量子情報処理に応用。",
        "impact_summary": "Bloch・Purcell(1952 Nobel)が発見、Lauterbur・Mansfield(2003 Nobel, MRI)が医療応用を開拓。固体NMRによるタンパク質・材料の構造解析が化学・生物学の主要ツール。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Mechanics",
        "era_start": 1946,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/physics/1952/summary/",
        "mathematical_formulation": r"\frac{d\mathbf{M}}{dt} = \gamma \mathbf{M}\times\mathbf{B} - \frac{M_x\hat{x}+M_y\hat{y}}{T_2} - \frac{(M_z-M_0)\hat{z}}{T_1}",
        "data_completeness": 90,
    },
    {
        "name_ja": "物質波と電子回折（ド・ブロイ波）",
        "name_en": "Matter Waves and Electron Diffraction",
        "definition": "電子・中性子・原子などの粒子が波動性を示すというド・ブロイの仮説（1924）。Davisson-Germerによる電子回折実験（1927）で確認。電子顕微鏡・中性子散乱の原理。",
        "impact_summary": "電子顕微鏡（TEM・SEM）・中性子回折による結晶構造解析・原子間力顕微鏡の理論的基盤。量子力学の実証実験として物理学史の転換点。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Mechanics",
        "era_start": 1924,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1929/broglie/lecture/",
        "mathematical_formulation": r"\lambda = \frac{h}{p} = \frac{h}{mv}, \quad p = \hbar k",
        "data_completeness": 90,
    },
    {
        "name_ja": "液晶の物理",
        "name_en": "Liquid Crystal Physics",
        "definition": "液体と結晶の中間相（液晶相）の物理。ネマティック・スメクティック・コレステリック液晶における配向秩序・欠陥・光学異方性・電場応答を扱う。",
        "impact_summary": "液晶ディスプレイ（LCD）の基礎。TFT-LCD・IPS液晶・有機液晶の物理が現代ディスプレイ産業を支える。Reinitzer(1888)が発見。de Gennes(1991 Nobel)が理論体系化。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1888,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1991/gennes/lecture/",
        "mathematical_formulation": r"F = \int\left[\frac{K_1}{2}(\nabla\cdot\hat{n})^2 + \frac{K_2}{2}(\hat{n}\cdot\nabla\times\hat{n})^2 + \frac{K_3}{2}(\hat{n}\times\nabla\times\hat{n})^2\right]dV",
        "data_completeness": 88,
    },
    {
        "name_ja": "物理宇宙論における大規模構造",
        "name_en": "Large-Scale Structure of the Universe",
        "definition": "銀河・銀河団・フィラメント・ボイドで構成される宇宙の大規模構造の形成・進化。暗黒物質・重力不安定性・バリオン音響振動（BAO）が形成の駆動力。",
        "impact_summary": "スローン・デジタル・スカイサーベイ（SDSS）・2dFGRS等の銀河サーベイが宇宙の3D地図を作成。BAOが暗黒エネルギーの標準定規として宇宙論パラメータ推定に活用。",
        "subfield": "物理学",
        "school_of_thought": "Cosmology",
        "era_start": 1970,
        "culture_region": "North_America",
        "source_url": "https://www.sdss.org/surveys/",
        "mathematical_formulation": r"P(k) = A k^{n_s} T(k)^2, \quad \xi(r) = \int \frac{d^3k}{(2\pi)^3} P(k) e^{i\mathbf{k}\cdot\mathbf{r}}",
        "data_completeness": 88,
    },
]

BATCH2 = [
    {
        "name_ja": "メソスコピック物理とアンドレーエフ反射",
        "name_en": "Mesoscopic Physics and Andreev Reflection",
        "definition": "マクロとミクロの中間スケール（メソスコピック系）の量子輸送現象。コンダクタンス量子化・弾道輸送・アンドレーエフ反射（正常金属-超伝導接合での正孔再帰）が核心。",
        "impact_summary": "量子点接触・カーボンナノチューブ・マヨラナ粒子探索・トポロジカル超伝導接合の実験的基盤。ランダウアー-ビュッティカーの散乱理論が定式化。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1957,
        "culture_region": "Europe_Eastern",
        "source_url": "https://link.aps.org/doi/10.1103/RevModPhys.69.731",
        "mathematical_formulation": r"G = \frac{2e^2}{h}\sum_n T_n, \quad G_0 = \frac{2e^2}{h} \approx 77.5\,\mu\text{S}",
        "data_completeness": 87,
    },
    {
        "name_ja": "インドの力学思想（ヴァイシェーシカ学派の原子論）",
        "name_en": "Indian Atomism — Vaisheshika Physics",
        "definition": "紀元前6世紀〜紀元後数世紀に発展したインド哲学・自然哲学学派ヴァイシェーシカ（Kanāda創始）による原子論的世界観。不可分な最小粒子「パラマーヌ」が物質の基本単位とされた。",
        "impact_summary": "ギリシア原子論と独立して展開された非西洋原子概念の代表例。現代の物理学史研究・非西洋科学思想研究において重要。インド数論哲学・仏教物理学との比較文化的意義も大きい。",
        "subfield": "物理学",
        "school_of_thought": "History of Physics",
        "era_start": -600,
        "culture_region": "South_Asia",
        "source_url": "https://plato.stanford.edu/entries/atomism-ancient/#IndAto",
        "data_completeness": 80,
    },
    {
        "name_ja": "光の回折と干渉（ヤングの実験）",
        "name_en": "Diffraction and Interference of Light",
        "definition": "光が障害物の縁や細隙を通過するときに曲がる（回折）および複数波が重なり合う（干渉）波動現象。Young(1801)の二重スリット実験が波動説の決定的証拠。",
        "impact_summary": "干渉縞・回折格子が分光学・結晶解析・ホログラフィーの基礎。X線回折（Bragg反射）でDNA二重らせん・タンパク質構造が解明。LIGOの重力波検出もマイケルソン干渉計の原理。",
        "subfield": "物理学",
        "school_of_thought": "Classical Physics",
        "era_start": 1801,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1915/w-bragg/lecture/",
        "mathematical_formulation": r"d\sin\theta = m\lambda, \quad I(\theta) = I_0\left(\frac{\sin(\pi d\sin\theta/\lambda)}{\pi d\sin\theta/\lambda}\right)^2",
        "data_completeness": 90,
    },
    {
        "name_ja": "レーザー冷却とBose-Einstein凝縮（原子冷却）",
        "name_en": "Laser Cooling and Bose-Einstein Condensation",
        "definition": "レーザー光の光圧を利用して原子をマイクロケルビン以下に冷却する技術。十分低温でボース粒子系は一つの量子状態に凝縮（BEC）する。",
        "impact_summary": "Chu・Cohen-Tannoudji・Phillips(1997 Nobel, レーザー冷却)・Cornell・Wieman・Ketterle(2001 Nobel, BEC)。原子時計・量子センサー・量子シミュレーション・BECレーザーの基盤。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Optics",
        "era_start": 1975,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/physics/2001/summary/",
        "mathematical_formulation": r"n_0 = N\left[1-\left(\frac{T}{T_c}\right)^3\right], \quad T_c = \frac{2\pi\hbar^2}{mk_B}\left(\frac{n}{\zeta(3/2)}\right)^{2/3}",
        "data_completeness": 91,
    },
    {
        "name_ja": "弦理論のコンパクト化と余剰次元",
        "name_en": "String Theory Compactification and Extra Dimensions",
        "definition": "超弦理論が要求する10次元（または11次元M理論）のうち、余剰6次元を小さく丸めて4次元時空を得る数学的手続き。カラビ-ヤウ多様体が候補として研究される。",
        "impact_summary": "素粒子模型（Standard Modelの派生）・インフレーション宇宙論・暗黒エネルギーの理論的枠組みを提供。Kaluza-Klein理論（1921）を起源とし、南部陽一郎（East_Asia）の弦理論への貢献と接続。",
        "subfield": "物理学",
        "school_of_thought": "String Theory",
        "era_start": 1985,
        "culture_region": "North_America",
        "source_url": "https://www.sns.ias.edu/~witten/papers/",
        "data_completeness": 85,
    },
    {
        "name_ja": "重力レンズ効果",
        "name_en": "Gravitational Lensing",
        "definition": "重力（時空の曲率）によって光の経路が曲がる現象。強重力レンズ（アインシュタインリング）・弱重力レンズ（銀河形状の統計的歪み）・マイクロレンズが区別される。",
        "impact_summary": "暗黒物質の分布マッピング・遠方クェーサーの発見・宇宙の大規模構造解析に使用。1919年の日食観測でEinsteinの一般相対論が検証。HST・Euclid衛星が弱重力レンズ宇宙論を推進。",
        "subfield": "物理学",
        "school_of_thought": "General Relativity",
        "era_start": 1919,
        "culture_region": "Europe_Western",
        "source_url": "https://www.esa.int/Science_Exploration/Space_Science/Euclid",
        "mathematical_formulation": r"\theta_E = \sqrt{\frac{4GM}{c^2}\frac{D_{ls}}{D_l D_s}}, \quad \hat{\alpha} = \frac{4GM}{bc^2}",
        "data_completeness": 88,
    },
    {
        "name_ja": "チェレンコフ放射",
        "name_en": "Cherenkov Radiation",
        "definition": "荷電粒子が媒質中で光の位相速度を超えて運動するとき放出される電磁放射。青い発光が特徴。Pavel Cherenkov(1934)が発見。",
        "impact_summary": "高エネルギー粒子検出器（Cherenkov検出器）の原理。ニュートリノ観測所（スーパーカミオカンデ・IceCube）・宇宙線望遠鏡（CTA）・医療用PET装置の基本物理。1958年Nobel賞。",
        "subfield": "物理学",
        "school_of_thought": "Particle Physics",
        "era_start": 1934,
        "culture_region": "Europe_Eastern",
        "source_url": "https://www.nobelprize.org/prizes/physics/1958/summary/",
        "mathematical_formulation": r"\cos\theta_c = \frac{1}{\beta n}, \quad \frac{dE}{dx} = \frac{q^2}{c^2}\int_{\beta n>1}\omega\left(1-\frac{1}{\beta^2 n^2}\right)d\omega",
        "data_completeness": 88,
    },
    {
        "name_ja": "イスラーム光学（イブン・アル＝ハイサム）",
        "name_en": "Islamic Optics — Ibn al-Haytham",
        "definition": "11世紀エジプトのイブン・アル＝ハイサム（アルハーゼン）が著した『光学の書』（Kitāb al-Manāẓir）。視覚の放射説を否定し光が目に入る説を実験的に確立。反射・屈折・暗箱を体系化。",
        "impact_summary": "現代光学の直接の先駆者。カメラオブスキュラ・レンズ設計・眼の解剖との接続がヨーロッパ光学革命（Kepler・Newton）を準備した。実験的科学方法論の先駆けとしても評価される。",
        "subfield": "物理学",
        "school_of_thought": "History of Physics",
        "era_start": 1011,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://www.britannica.com/biography/Ibn-al-Haytham",
        "data_completeness": 85,
    },
    {
        "name_ja": "熱輻射と赤外線分光",
        "name_en": "Thermal Radiation and Infrared Spectroscopy",
        "definition": "有限温度の物体が放射する電磁波（熱輻射）のスペクトル。Stefan-Boltzmann則・Wienの変位則・Planckの黒体放射式が基本法則。赤外吸収分光が分子同定に応用。",
        "impact_summary": "地球温暖化（温室効果気体の赤外吸収）・工業温度計測（赤外カメラ）・宇宙背景放射・星形成環境の観測の物理的基礎。Planckの量子論(1900)の起点となった歴史的転換点。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Mechanics",
        "era_start": 1879,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1918/planck/lecture/",
        "mathematical_formulation": r"B_\nu(T) = \frac{2h\nu^3}{c^2}\frac{1}{e^{h\nu/k_BT}-1}",
        "data_completeness": 92,
    },
    {
        "name_ja": "宇宙線とミュオン",
        "name_en": "Cosmic Rays and Muons",
        "definition": "宇宙から地球に降り注ぐ高エネルギー荷電粒子（一次宇宙線）と大気との相互作用で生成される二次粒子（ミュオン・中性子・パイオン等）の物理。",
        "impact_summary": "ミュオンの発見（Anderson 1936）が相対論的時間遅延を実証。宇宙線観測（Pierre Auger天文台）が超高エネルギー宇宙線起源の解明を目指す。ミュオントモグラフィーが火山・核施設の非破壊検査に応用。",
        "subfield": "物理学",
        "school_of_thought": "Particle Physics",
        "era_start": 1912,
        "culture_region": "Europe_Western",
        "source_url": "https://www.auger.org/index.php/science/cosmic-rays",
        "data_completeness": 87,
    },
]

BATCH3 = [
    {
        "name_ja": "電子スピン共鳴（ESR）とスピントロニクス",
        "name_en": "Electron Spin Resonance and Spintronics",
        "definition": "不対電子（スピン1/2粒子）が磁場中でマイクロ波を吸収する共鳴現象（ESR）、および電子スピン自由度を情報キャリアとする電子工学（スピントロニクス）。",
        "impact_summary": "GMR（巨大磁気抵抗効果, Grünberg・Fert 2007 Nobel）がハードディスク読み取り革命を起こした。磁気メモリ（MRAM）・スピンFETの実現を目指す次世代エレクトロニクス。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1944,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/2007/summary/",
        "mathematical_formulation": r"h\nu = g\mu_B B, \quad \mathbf{m}_s = g_s\mu_B\mathbf{S}/\hbar",
        "data_completeness": 88,
    },
    {
        "name_ja": "アインシュタインの1905年論文群",
        "name_en": "Einstein's Annus Mirabilis Papers (1905)",
        "definition": "1905年にEinsteinが発表した4篇の革命的論文：(1)光量子仮説(光電効果説明)、(2)ブラウン運動の確率論的記述、(3)特殊相対性理論、(4)E=mc²の質量-エネルギー等価。",
        "impact_summary": "量子力学・統計力学・相対論という20世紀物理学の3本柱を1年で形成。Nobel賞(1921)は光電効果論文に対して授与。現代物理学・宇宙論・核技術の共通的起点。",
        "subfield": "物理学",
        "school_of_thought": "Theoretical Physics",
        "era_start": 1905,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1921/einstein/lecture/",
        "mathematical_formulation": r"E = mc^2, \quad E_k = h\nu - \phi, \quad \langle x^2\rangle = 2Dt",
        "data_completeness": 93,
    },
    {
        "name_ja": "中国近代物理学（楊振寧と弱い相互作用の非保存）",
        "name_en": "Chinese Contributions to Modern Physics — Yang and Parity Non-Conservation",
        "definition": "Yang Chen-Ning（楊振寧）とTsung-Dao Lee（李政道）が1956年に提唱した弱い相互作用におけるパリティ非保存の理論。宇称保存則が弱い力では破れることを予言し、翌年実験的に検証された。",
        "impact_summary": "1957年Nobel物理学賞受賞。自然界の基本対称性に関する概念を根本から変革。Yang-Mills理論（ゲージ場理論）と並び、20世紀素粒子物理学に対する中国人物理学者の最重要貢献。",
        "subfield": "物理学",
        "school_of_thought": "Particle Physics",
        "era_start": 1956,
        "culture_region": "East_Asia",
        "source_url": "https://www.nobelprize.org/prizes/physics/1957/summary/",
        "data_completeness": 88,
    },
    {
        "name_ja": "磁気流体力学（MHD）",
        "name_en": "Magnetohydrodynamics (MHD)",
        "definition": "導電性流体（プラズマ・液体金属）と磁場の相互作用を記述する電磁流体力学。Alfvén波・磁気ダイナモ・磁気リコネクションが主要現象。",
        "impact_summary": "太陽コロナ加熱・太陽フレア・地球ダイナモ（地磁気の生成）・核融合炉（トカマク）プラズマ閉じ込めの基礎理論。Alfvén(1970 Nobel)が理論体系化。",
        "subfield": "物理学",
        "school_of_thought": "Plasma Physics",
        "era_start": 1942,
        "culture_region": "Europe_Western",
        "source_url": "https://www.nobelprize.org/prizes/physics/1970/alfven/lecture/",
        "mathematical_formulation": r"\frac{\partial\rho}{\partial t}+\nabla\cdot(\rho\mathbf{v})=0, \quad \rho\frac{D\mathbf{v}}{Dt} = -\nabla p + \mathbf{J}\times\mathbf{B}",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子カオスと量子エルゴード定理",
        "name_en": "Quantum Chaos and Quantum Ergodicity",
        "definition": "古典系においてカオス的挙動を示す系を量子化したとき現れる特徴（エネルギー準位の統計・エイゲンファンクションの分布）を研究する分野。Berry-Tabor予想・BGS予想が基本。",
        "impact_summary": "原子核励起スペクトル・ランダム行列理論・量子コンピュータのデコヒーレンスと熱化（ETH：固有状態熱化仮説）の理解に重要。リーマンゼータ零点との数学的接続も注目。",
        "subfield": "物理学",
        "school_of_thought": "Theoretical Physics",
        "era_start": 1977,
        "culture_region": "Europe_Western",
        "source_url": "https://link.aps.org/doi/10.1103/PhysRevLett.52.1",
        "mathematical_formulation": r"P(s) = \frac{\pi s}{2}e^{-\pi s^2/4} \quad \text{(Wigner-Dyson GUE)}",
        "data_completeness": 85,
    },
    {
        "name_ja": "暗黒物質候補とその検出",
        "name_en": "Dark Matter Candidates and Detection",
        "definition": "宇宙の物質・エネルギーの約27%を占めると推定される暗黒物質の粒子的性質を解明する研究分野。WIMP・アクシオン・ステライルニュートリノ等が候補。",
        "impact_summary": "XENONnT・LUX-ZEPLIN・PandaX等の液体キセノン検出器、AMS-02（宇宙線対消滅）、大型ハドロン衝突型加速器（LHC）でWIMPを探索中。未検出の問題が宇宙論の最前線課題。",
        "subfield": "物理学",
        "school_of_thought": "Particle Physics",
        "era_start": 1933,
        "culture_region": "Europe_Western",
        "source_url": "https://xenonexperiment.org/",
        "data_completeness": 87,
    },
    {
        "name_ja": "量子インターネットと量子通信",
        "name_en": "Quantum Internet and Quantum Communication",
        "definition": "量子もつれ・量子テレポーテーション・量子暗号（QKD）を用いた安全な情報通信ネットワーク。量子中継器・光ファイバー量子通信・衛星量子通信が主要手法。",
        "impact_summary": "中国の「墨子」衛星（2016）が1,200 km量子鍵配送を実証。EUのQuantum Flagship・米国のNQI・日本の量子通信ロードマップが国家戦略レベルで推進中。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Information",
        "era_start": 1984,
        "culture_region": "East_Asia",
        "source_url": "https://www.nature.com/articles/nature23461",
        "data_completeness": 88,
    },
    {
        "name_ja": "ソフトマター物理（高分子・コロイド・生体膜）",
        "name_en": "Soft Matter Physics",
        "definition": "高分子・液晶・コロイド・泡沫・ゲル・生体膜など熱揺らぎで容易に変形する系の統計力学・レオロジー・自己組織化を研究する分野。de Gennesが体系化。",
        "impact_summary": "化粧品・食品・生体材料・タイヤ・塗料など日常素材の物理。レオロジー・粘弾性・相分離・自己組織化ナノ構造の理解が医薬品送達系・次世代材料に応用。",
        "subfield": "物理学",
        "school_of_thought": "Condensed Matter Physics",
        "era_start": 1970,
        "culture_region": "Europe_Western",
        "source_url": "https://www.softmatterjournal.org/",
        "mathematical_formulation": r"f_{\text{free}} = \frac{3k_BT}{2Nb^2}R^2 \quad \text{(Gaussian chain)}",
        "data_completeness": 87,
    },
    {
        "name_ja": "ハミルトン力学と解析力学",
        "name_en": "Hamiltonian Mechanics and Analytical Mechanics",
        "definition": "ラグランジュ形式から発展したハミルトン正準形式：一般化座標と一般化運動量による力学系の記述。ポワソン括弧・正準変換・ハミルトン-ヤコビ方程式が主要ツール。",
        "impact_summary": "量子力学への橋渡し（{q,p}→[x,p]=iℏ）・積分可能系・カオスの理論的基盤。宇宙力学・粒子加速器設計・プラズマ閉じ込めの軌道計算に使用。",
        "subfield": "物理学",
        "school_of_thought": "Classical Mechanics",
        "era_start": 1833,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/H02714",
        "mathematical_formulation": r"\dot{q}_i = \frac{\partial H}{\partial p_i}, \quad \dot{p}_i = -\frac{\partial H}{\partial q_i}",
        "data_completeness": 92,
    },
    {
        "name_ja": "原子時計と精密測定",
        "name_en": "Atomic Clocks and Precision Measurement",
        "definition": "原子の超精密な電子遷移周波数（マイクロ波・光周波数）を基準とする時計。セシウム原子時計が国際秒の定義標準。光格子時計・イオントラップ時計で精度がさらに向上。",
        "impact_summary": "GPS衛星のナノ秒精度（相対論補正を含む）・VLBI天文基準・重力波検出器のタイミング・量子センサー（重力測定・暗黒物質探索）の基盤技術。",
        "subfield": "物理学",
        "school_of_thought": "Quantum Optics",
        "era_start": 1955,
        "culture_region": "Europe_Western",
        "source_url": "https://www.bipm.org/en/time-frequency.html",
        "mathematical_formulation": r"\nu_{Cs} = 9\,192\,631\,770\,\text{Hz} \quad \text{(defining constant of SI second)}",
        "data_completeness": 90,
    },
]

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    n1 = insert_batch(conn, BATCH1)
    n2 = insert_batch(conn, BATCH2)
    n3 = insert_batch(conn, BATCH3)
    total = n1 + n2 + n3
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM natural_discovery")
    grand = cursor.fetchone()[0]
    conn.close()
    print(f"Batch13 physics4: {total} inserted (B1={n1}, B2={n2}, B3={n3}). Total: {grand}")
