"""
DUA Wave A2 Batch 4 — Physics (additional 80 concepts)
Target subfield: 物理学 (currently 473, need +337 toward 810)
"""
import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

CONCEPTS = [
    # Classical Mechanics deep dive
    {
        "name_ja": "ラグランジュ力学",
        "name_en": "Lagrangian Mechanics",
        "name_original": "Mécanique analytique",
        "definition": "一般化座標と最小作用の原理に基づきニュートン力学を変分法で再定式化した体系。拘束条件を自然に扱い、座標変換に対する不変性を持つ。",
        "impact_summary": "解析力学の基礎を確立し、量子力学・場の理論・最適制御の数学的基盤となった。",
        "subfield": "物理学",
        "school_of_thought": "解析力学",
        "era_start": 1788,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Lagrangian_mechanics",
        "mathematical_formulation": r"L = T - V,\quad \frac{d}{dt}\frac{\partial L}{\partial \dot{q}_i} - \frac{\partial L}{\partial q_i} = 0",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ハミルトン力学",
        "name_en": "Hamiltonian Mechanics",
        "name_original": None,
        "definition": "位相空間上の正準変数（座標と運動量）でニュートン力学を記述し、時間発展をハミルトン方程式で表現する体系。",
        "impact_summary": "統計力学・量子力学・カオス理論の基礎。シンプレクティック幾何学と深く結びつく。",
        "subfield": "物理学",
        "school_of_thought": "解析力学",
        "era_start": 1833,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Hamiltonian_mechanics",
        "mathematical_formulation": r"\dot{q}_i = \frac{\partial H}{\partial p_i},\quad \dot{p}_i = -\frac{\partial H}{\partial q_i}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "最小作用の原理",
        "name_en": "Principle of Least Action",
        "name_original": None,
        "definition": "物理系の運動は作用積分を極値にする経路に沿って進むという変分原理。モーペルテュイ・オイラー・ラグランジュらが発展させた。",
        "impact_summary": "力学・場の理論・量子力学・一般相対論に統一的な数学的骨格を与え、対称性と保存則を結ぶ。",
        "subfield": "物理学",
        "school_of_thought": "変分原理",
        "era_start": 1744,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Principle_of_least_action",
        "mathematical_formulation": r"S = \int_{t_1}^{t_2} L(q,\dot{q},t)\,dt,\quad \delta S = 0",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ネーターの定理",
        "name_en": "Noether's Theorem",
        "name_original": None,
        "definition": "物理系のラグランジアンが連続対称性を持つとき、対応する保存量（保存則）が存在するという定理。エミー・ネーターが1915年に証明。",
        "impact_summary": "エネルギー・運動量・角運動量保存則を対称性から導き、素粒子物理学の保存則を系統的に理解する枠組みを与えた。",
        "subfield": "物理学",
        "school_of_thought": "対称性原理",
        "era_start": 1915,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Noether%27s_theorem",
        "mathematical_formulation": r"J^\mu = \frac{\partial \mathcal{L}}{\partial(\partial_\mu \phi)}\delta\phi - K^\mu,\quad \partial_\mu J^\mu = 0",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "カオス理論",
        "name_en": "Chaos Theory",
        "name_original": None,
        "definition": "決定論的系が初期条件の微小変化に対して指数関数的に発散する振る舞いを示す現象を研究する理論。ローレンツが気象モデルで発見。",
        "impact_summary": "気象・流体・生態・経済系など複雑系の予測限界を明らかにし、複雑適応系研究の礎となった。",
        "subfield": "物理学",
        "school_of_thought": "非線形科学",
        "era_start": 1963,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Chaos_theory",
        "mathematical_formulation": r"\delta(t) \approx \delta_0 e^{\lambda t},\quad \lambda = \lim_{t\to\infty}\frac{1}{t}\ln\frac{|\delta(t)|}{|\delta_0|}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "レノーマリゼーション群",
        "name_en": "Renormalization Group",
        "name_original": None,
        "definition": "観測スケールを変えたときの物理系の振る舞いの変化を記述する理論的枠組み。ウィルソンが相転移と素粒子物理学を統一的に扱う方法を確立。",
        "impact_summary": "臨界現象の普遍性クラスを説明し、QEDの発散を制御し、有効場の理論の概念的基盤を提供した。",
        "subfield": "物理学",
        "school_of_thought": "量子場理論",
        "era_start": 1971,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Renormalization_group",
        "mathematical_formulation": r"\beta(g) = \mu\frac{\partial g}{\partial \mu},\quad g(\mu') = g(\mu) + \beta(g)\ln(\mu'/\mu) + O(g^3)",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "アンダーソン局在",
        "name_en": "Anderson Localization",
        "name_original": None,
        "definition": "不規則なポテンシャルを持つ媒質中で電子や波動が拡散せず局在化する現象。フィリップ・アンダーソンが1958年に理論的に予言。",
        "impact_summary": "金属絶縁体転移・量子干渉効果・トポロジカル物質の理解に不可欠な概念。",
        "subfield": "物理学",
        "school_of_thought": "凝縮系物理",
        "era_start": 1958,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Anderson_localization",
        "mathematical_formulation": r"\psi(r) \sim e^{-|r-r_0|/\xi},\quad \xi = \text{localization length}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "量子エンタングルメント",
        "name_en": "Quantum Entanglement",
        "name_original": None,
        "definition": "複数の量子系が分離不能な状態となり、一方の測定が他方の状態を瞬時に決定する非局所的相関。アインシュタイン・ポドルスキー・ローゼンが1935年に提起。",
        "impact_summary": "量子情報・量子暗号・量子コンピュータの核心概念。ベルの不等式違反により実験的に確認。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 1935,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_entanglement",
        "mathematical_formulation": r"|\Psi\rangle = \frac{1}{\sqrt{2}}(|00\rangle + |11\rangle),\quad \rho_{AB} \neq \rho_A \otimes \rho_B",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "量子誤り訂正",
        "name_en": "Quantum Error Correction",
        "name_original": None,
        "definition": "デコヒーレンスやゲートエラーから量子情報を保護するための符号化理論。ショアコード・スタビライザー形式が代表的。",
        "impact_summary": "フォールトトレラント量子計算の実現に向けた理論的基盤。閾値定理と組み合わさりスケーラブルな量子コンピュータを理論的に正当化。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 1995,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_error_correction",
        "mathematical_formulation": r"|0_L\rangle = \frac{1}{2\sqrt{2}}(|000\rangle+|111\rangle)^{\otimes 3},\quad d = 3",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "トポロジカル絶縁体",
        "name_en": "Topological Insulator",
        "name_original": None,
        "definition": "バルクが絶縁体でありながら表面・端に時間反転対称性に保護されたギャップレス状態を持つ物質。ケーンとメレが2005年に理論予言。",
        "impact_summary": "量子スピンホール効果・マヨラナ粒子・トポロジカル量子計算への道を開いた。",
        "subfield": "物理学",
        "school_of_thought": "トポロジカル物質科学",
        "era_start": 2005,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Topological_insulator",
        "mathematical_formulation": r"\mathbb{Z}_2\text{ invariant: }\nu = \frac{1}{\pi}\oint_{\text{BZ}} A_k\,dk \mod 2",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子スピン液体",
        "name_en": "Quantum Spin Liquid",
        "name_original": None,
        "definition": "磁性体でありながら絶対零度に至っても磁気秩序を持たず、スピン間の量子揺らぎが強い新しい量子相。アンダーソンがRVB状態として1973年に提案。",
        "impact_summary": "高温超伝導の機構解明や分数化準粒子・エニオンとの関係から量子物質研究の最前線。",
        "subfield": "物理学",
        "school_of_thought": "強相関電子系",
        "era_start": 1973,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_spin_liquid",
        "mathematical_formulation": r"\hat{H} = J\sum_{\langle ij\rangle}\mathbf{S}_i\cdot\mathbf{S}_j,\quad \langle\mathbf{S}\rangle = 0 \text{ at } T=0",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "くりこみ理論（QED）",
        "name_en": "Renormalization in QED",
        "name_original": None,
        "definition": "量子電気力学の無限大発散をくりこみにより有限な観測量に変換する手続き。シュウィンガー・ファインマン・朝永振一郎が独立に1948年に完成。",
        "impact_summary": "電子の異常磁気モーメントを超高精度で予言し、QEDを最精密な物理理論とした。",
        "subfield": "物理学",
        "school_of_thought": "量子場理論",
        "era_start": 1948,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_electrodynamics#Renormalization",
        "mathematical_formulation": r"a_e = \frac{\alpha}{2\pi} - 0.328\left(\frac{\alpha}{\pi}\right)^2 + \cdots \approx 0.00115965",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "カシミール効果",
        "name_en": "Casimir Effect",
        "name_original": None,
        "definition": "真空中の近接した二枚の導体板間に、量子真空揺らぎに起因する引力が働く現象。カシミールが1948年に予言し、実験で確認。",
        "impact_summary": "量子真空の実在性を示し、ナノ機器への応用やダークエネルギー・宇宙定数問題の議論に関わる。",
        "subfield": "物理学",
        "school_of_thought": "量子場理論",
        "era_start": 1948,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Casimir_effect",
        "mathematical_formulation": r"F/A = -\frac{\pi^2\hbar c}{240 d^4}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "超弦理論",
        "name_en": "Superstring Theory",
        "name_original": None,
        "definition": "素粒子を点粒子でなく1次元の弦として扱い、重力を含む全相互作用を統一しようとする理論。10次元・11次元を要求する。",
        "impact_summary": "万物の理論の有力候補として理論物理学の主流となり、ホログラフィー原理やAdS/CFT対応を生んだ。",
        "subfield": "物理学",
        "school_of_thought": "量子重力",
        "era_start": 1984,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Superstring_theory",
        "mathematical_formulation": r"S = -\frac{T}{2}\int d^2\sigma\,\eta^{ab}\partial_a X^\mu\partial_b X_\mu,\quad D=10",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "AdS/CFT対応",
        "name_en": "AdS/CFT Correspondence",
        "name_original": None,
        "definition": "反ド・ジッター時空における重力理論と境界上の共形場理論が等価という双対性。マルダセナが1997年に提案したホログラフィー原理の具体的実現。",
        "impact_summary": "強結合ゲージ理論・クォークグルーオン・量子重力・凝縮系物理に多角的応用を持つ現代理論物理の中核。",
        "subfield": "物理学",
        "school_of_thought": "弦理論",
        "era_start": 1997,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/AdS/CFT_correspondence",
        "mathematical_formulation": r"Z_{\text{CFT}}[J] = Z_{\text{string}}[\phi|_{\partial AdS} = J]",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ホーキング放射",
        "name_en": "Hawking Radiation",
        "name_original": None,
        "definition": "ブラックホールが量子効果により黒体輻射に類似した熱放射を放出するとスティーヴン・ホーキングが1974年に理論的に予言した現象。",
        "impact_summary": "量子重力・ブラックホール情報問題・熱力学の法則を結びつけ、量子重力理論の最重要テストケースとなっている。",
        "subfield": "物理学",
        "school_of_thought": "量子重力",
        "era_start": 1974,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Hawking_radiation",
        "mathematical_formulation": r"T_H = \frac{\hbar c^3}{8\pi G M k_B}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ブラックホール熱力学",
        "name_en": "Black Hole Thermodynamics",
        "name_original": None,
        "definition": "ブラックホールがエントロピー・温度・熱力学法則に対応する性質を持つことを示す理論体系。ベッケンシュタイン・ホーキング・バルディーンらが1970年代に確立。",
        "impact_summary": "ホログラフィー原理・量子重力・情報パラドックスの出発点となり、理論物理学最大の未解決問題を提起した。",
        "subfield": "物理学",
        "school_of_thought": "量子重力",
        "era_start": 1973,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Black_hole_thermodynamics",
        "mathematical_formulation": r"S_{BH} = \frac{k_B A}{4 l_P^2} = \frac{k_B c^3 A}{4G\hbar}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "インフレーション宇宙論",
        "name_en": "Cosmic Inflation",
        "name_original": None,
        "definition": "ビッグバン直後に宇宙が指数関数的に急膨張したとするモデル。地平線問題・平坦性問題を解決し、CMBの温度揺らぎを生成する。",
        "impact_summary": "標準宇宙論の核心理論となり、スカラー場によるインフラトン・原始重力波・非ガウス性予言を通じて観測で検証されつつある。",
        "subfield": "物理学",
        "school_of_thought": "宇宙論",
        "era_start": 1980,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Inflation_(cosmology)",
        "mathematical_formulation": r"a(t) \propto e^{Ht},\quad H = \sqrt{\frac{8\pi G V(\phi)}{3}}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "スピントロニクス",
        "name_en": "Spintronics",
        "name_original": None,
        "definition": "電子の電荷だけでなくスピン自由度を利用して情報処理・記憶を実現する分野。GMR（巨大磁気抵抗効果）の発見が起点。",
        "impact_summary": "HDDの読み取りヘッドを革命的に改良し、MRAMなどスピンデバイスの開発へ。フェルト・グリュンベルクの2007年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "凝縮系物理",
        "era_start": 1988,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Spintronics",
        "mathematical_formulation": r"\text{GMR} = \frac{R_{AP}-R_P}{R_P},\quad \Delta R \propto 1-\cos\theta",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子ホール効果（整数）",
        "name_en": "Integer Quantum Hall Effect",
        "name_original": None,
        "definition": "2次元電子系を強磁場・極低温に置くと，ホール抵抗が基本定数の比 h/e² の整数倍で精密に量子化する現象。フォン・クリッツィングが1980年に発見。",
        "impact_summary": "抵抗の国際標準として採用され、トポロジカル物理学の先駆となった。1985年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "凝縮系物理",
        "era_start": 1980,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_Hall_effect",
        "mathematical_formulation": r"R_H = \frac{h}{ne^2} = \frac{25812.8\,\Omega}{n},\quad n\in\mathbb{Z}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "分数量子ホール効果",
        "name_en": "Fractional Quantum Hall Effect",
        "name_original": None,
        "definition": "整数の代わりに1/3・2/5など有理数倍でホール抵抗が量子化する現象。ツァイとストーマーが1982年に発見し、ラフリンが合成フェルミオン理論で説明。",
        "impact_summary": "分数化準粒子・エニオン・トポロジカル量子計算の物理的基盤として理論・実験両面で活発に研究。1998年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "凝縮系物理",
        "era_start": 1982,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Fractional_quantum_Hall_effect",
        "mathematical_formulation": r"R_H = \frac{h}{\nu e^2},\quad \nu = \frac{p}{2mp\pm 1}\in\mathbb{Q}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ジョセフソン効果",
        "name_en": "Josephson Effect",
        "name_original": None,
        "definition": "超伝導体を薄い絶縁層で隔てたジャンクションにおいて、電圧なしにクーパー対が量子トンネルにより流れる現象。ジョセフソンが1962年に予言。",
        "impact_summary": "電圧の量子標準・SQUID・量子コンピュータの超伝導量子ビット（トランズモン）の基礎。",
        "subfield": "物理学",
        "school_of_thought": "超伝導・量子素子",
        "era_start": 1962,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Josephson_effect",
        "mathematical_formulation": r"I = I_c\sin\varphi,\quad \frac{d\varphi}{dt} = \frac{2eV}{\hbar}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "マヨラナ粒子",
        "name_en": "Majorana Fermion",
        "name_original": None,
        "definition": "自分自身が反粒子となるフェルミオン。マヨラナが1937年に理論的に予言。凝縮系物理ではトポロジカル超伝導体の端状態として実現が期待される。",
        "impact_summary": "トポロジカル量子計算・ノンアーベリアニョン・ニュートリノ質量問題に深く関わる。",
        "subfield": "物理学",
        "school_of_thought": "素粒子・凝縮系物理",
        "era_start": 1937,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Majorana_fermion",
        "mathematical_formulation": r"\gamma = \gamma^\dagger,\quad \{\gamma_i,\gamma_j\} = 2\delta_{ij}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "光子の量子光学",
        "name_en": "Quantum Optics",
        "name_original": None,
        "definition": "光の量子性（光子）と物質との相互作用を量子力学的に記述する分野。コヒーレント状態・絞り込み光・キャビティQEDなどを含む。",
        "impact_summary": "量子情報・量子通信・量子センシング・レーザー冷却の理論基盤。グラウバーの2005年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "量子光学",
        "era_start": 1963,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_optics",
        "mathematical_formulation": r"|\\alpha\rangle = e^{-|\alpha|^2/2}\sum_{n=0}^\infty \frac{\alpha^n}{\sqrt{n!}}|n\rangle",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "レーザー冷却",
        "name_en": "Laser Cooling",
        "name_original": None,
        "definition": "レーザー光の輻射圧を利用して原子を数マイクロケルビン以下に冷却する技術。チュー・コーエン＝タヌジ・フィリップスが1997年ノーベル賞。",
        "impact_summary": "光格子時計・原子干渉計・BEC実現・量子シミュレーターの基礎技術。",
        "subfield": "物理学",
        "school_of_thought": "量子光学",
        "era_start": 1985,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Laser_cooling",
        "mathematical_formulation": r"F = \frac{\hbar k \Gamma}{2}\frac{I/I_s}{1+I/I_s+(2\Delta/\Gamma)^2}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "核磁気共鳴（物理）",
        "name_en": "Nuclear Magnetic Resonance (Physics)",
        "name_original": None,
        "definition": "外部磁場中の核スピンがラーモア周波数で共鳴吸収・放出する現象。ブロッホとパーセルが1946年に独立発見。",
        "impact_summary": "MRIの物理原理・化学構造解析・量子コンピュータの初期実証プラットフォームとして幅広い応用。",
        "subfield": "物理学",
        "school_of_thought": "磁気共鳴",
        "era_start": 1946,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_magnetic_resonance",
        "mathematical_formulation": r"\omega_0 = \gamma B_0,\quad \frac{dM}{dt} = M\times\gamma B",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "宇宙線物理学",
        "name_en": "Cosmic Ray Physics",
        "name_original": None,
        "definition": "宇宙から降り注ぐ高エネルギー荷電粒子（陽子・原子核・電子）の起源・伝播・相互作用を研究する分野。ヘスが1912年に発見。",
        "impact_summary": "陽電子・μ粒子・π中間子など初期素粒子の発見の場。ウルトラ高エネルギー宇宙線の起源は現代の謎。",
        "subfield": "物理学",
        "school_of_thought": "素粒子・宇宙物理",
        "era_start": 1912,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Cosmic_ray",
        "mathematical_formulation": r"E_{\max} \approx ZeBR_{\text{source}},\quad \text{GZK cutoff: }E \gtrsim 5\times10^{19}\,\text{eV}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "磁気流体力学",
        "name_en": "Magnetohydrodynamics",
        "name_original": "MHD",
        "definition": "電気伝導性流体（プラズマ・液体金属）と磁場の相互作用を連続体力学と電磁気学の組み合わせで記述する分野。アルベンが1942年に基礎を確立。",
        "impact_summary": "太陽コロナ・地球磁場・核融合プラズマの理論基盤。アルベン波の発見で1970年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "プラズマ物理",
        "era_start": 1942,
        "culture_region": "Europe_Northern",
        "source_url": "https://en.wikipedia.org/wiki/Magnetohydrodynamics",
        "mathematical_formulation": r"\frac{\partial\mathbf{B}}{\partial t} = \nabla\times(\mathbf{v}\times\mathbf{B}) + \eta\nabla^2\mathbf{B}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "デバイモデル",
        "name_en": "Debye Model",
        "name_original": None,
        "definition": "固体の熱容量をフォノン（格子振動）の量子として扱い、低温でT³則（デバイT³則）を導くモデル。デバイが1912年に提案。",
        "impact_summary": "固体比熱の温度依存性を正確に再現し、アインシュタインモデルを改良した凝縮系物理の基礎。",
        "subfield": "物理学",
        "school_of_thought": "固体物理",
        "era_start": 1912,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Debye_model",
        "mathematical_formulation": r"C_V = 9Nk_B\left(\frac{T}{\Theta_D}\right)^3\int_0^{\Theta_D/T}\frac{x^4 e^x}{(e^x-1)^2}dx",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ランダウ準位",
        "name_en": "Landau Levels",
        "name_original": None,
        "definition": "均一磁場中の2次元電子が(n+1/2)ℏωcで量子化されたエネルギー準位をとる現象。ランダウが1930年に量子力学的に解析。",
        "impact_summary": "量子ホール効果の説明に不可欠な概念。グラフェンの相対論的ランダウ準位など現代物理に発展。",
        "subfield": "物理学",
        "school_of_thought": "量子力学",
        "era_start": 1930,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Landau_levels",
        "mathematical_formulation": r"E_n = \hbar\omega_c\left(n+\frac{1}{2}\right),\quad \omega_c = \frac{eB}{m}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "核融合プラズマ",
        "name_en": "Nuclear Fusion Plasma",
        "name_original": None,
        "definition": "軽元素原子核（重水素・三重水素）を超高温プラズマ状態で融合させエネルギーを取り出す試み。ITER・NIF・慣性閉じ込め方式が代表的。",
        "impact_summary": "エネルギー問題の究極解として数十年にわたり研究されており、2022年NIF点火成功が新たな里程標。",
        "subfield": "物理学",
        "school_of_thought": "プラズマ核融合",
        "era_start": 1952,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_fusion",
        "mathematical_formulation": r"\text{D}+\text{T}\to{}^4\text{He}(3.52\,\text{MeV})+n(14.06\,\text{MeV}),\quad Q=17.59\,\text{MeV}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "中性子星・パルサー（物理）",
        "name_en": "Neutron Star Interior Physics",
        "name_original": None,
        "definition": "超高密度中性子星の内部構造（ハドロン・クォーク・奇妙粒子凝縮）と状態方程式を探求する分野。超流動中性子・陽子超伝導が理論的に予言される。",
        "impact_summary": "重力波観測によるEOSの制約・マルチメッセンジャー天文学の中心課題。",
        "subfield": "物理学",
        "school_of_thought": "核物理・天体物理",
        "era_start": 1967,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Neutron_star",
        "mathematical_formulation": r"\rho_{\text{center}}\sim 10^{14-15}\,\text{g/cm}^3,\quad M_{\max} \approx 2-3 M_\odot \text{ (Tolman-Oppenheimer-Volkoff)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "フォトニック結晶",
        "name_en": "Photonic Crystal",
        "name_original": None,
        "definition": "屈折率が周期的に変調した構造体で、特定の周波数帯（フォトニックバンドギャップ）の光の伝播が禁止される。ジョン・ヤブロノビッチとサジーブ・ジョンが1987年に独立提案。",
        "impact_summary": "低閾値レーザー・光集積回路・スーパープリズムなど光デバイスの革新に応用。",
        "subfield": "物理学",
        "school_of_thought": "フォトニクス",
        "era_start": 1987,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Photonic_crystal",
        "mathematical_formulation": r"\nabla\times\left(\frac{1}{\varepsilon(\mathbf{r})}\nabla\times\mathbf{H}\right) = \frac{\omega^2}{c^2}\mathbf{H}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "メタマテリアル",
        "name_en": "Metamaterial",
        "name_original": None,
        "definition": "自然界に存在しない負の屈折率など特殊な電磁気的特性を持つように人工的に設計された構造物。ヴェセラゴが1968年に理論予言、2000年代に実現。",
        "impact_summary": "スーパーレンズ・電磁クローキング・完全吸収体など極端な光制御を可能にする。",
        "subfield": "物理学",
        "school_of_thought": "フォトニクス・波動工学",
        "era_start": 2000,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Metamaterial",
        "mathematical_formulation": r"n = \sqrt{\varepsilon_r\mu_r} < 0 \Rightarrow k\perp S,\quad \mathbf{k} \text{ and } \mathbf{S} \text{ antiparallel}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "固体NMR分光法",
        "name_en": "Solid-State NMR Spectroscopy",
        "name_original": None,
        "definition": "固体試料の核磁気共鳴を魔角回転（MAS）などの手法で測定し、結晶構造・分子配向・ダイナミクスを解析する。",
        "impact_summary": "タンパク質繊維・ゼオライト・電池材料など溶液NMR・X線解析が困難な系の構造解析に不可欠。",
        "subfield": "物理学",
        "school_of_thought": "磁気共鳴",
        "era_start": 1958,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Solid-state_nuclear_magnetic_resonance",
        "mathematical_formulation": r"\mathcal{H}_\text{CS} = \delta_\text{iso}B_0 I_z + \delta_\text{aniso}\left[\frac{3\cos^2\theta-1}{2} - \eta\sin^2\theta\cos 2\phi\right]",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "電子スピン共鳴",
        "name_en": "Electron Spin Resonance",
        "name_original": "EPR / ESR",
        "definition": "不対電子を持つ系に電磁波を照射してスピン遷移を測定する分光法。ザヴォイスキーが1944年に発見。",
        "impact_summary": "ラジカル反応機構・金属タンパク質活性部位・量子コンピュータの電子スピン量子ビット研究に応用。",
        "subfield": "物理学",
        "school_of_thought": "磁気共鳴",
        "era_start": 1944,
        "culture_region": "Europe_Eastern",
        "source_url": "https://en.wikipedia.org/wiki/Electron_paramagnetic_resonance",
        "mathematical_formulation": r"h\nu = g\mu_B B_0,\quad g \approx 2.002 \text{ (free electron)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ゼーマン効果",
        "name_en": "Zeeman Effect",
        "name_original": None,
        "definition": "外部磁場中でスペクトル線が分裂する現象。ゼーマンが1896年に発見し、原子スペクトルに角運動量が関与することを示した。",
        "impact_summary": "原子の電子構造解明・天体磁場測定・原子時計・スピントロニクスの歴史的起点。",
        "subfield": "物理学",
        "school_of_thought": "原子・光学物理",
        "era_start": 1896,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Zeeman_effect",
        "mathematical_formulation": r"\Delta E = -\mu_z B = m_l\mu_B B,\quad \mu_B = \frac{e\hbar}{2m_e}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "シュタルク効果",
        "name_en": "Stark Effect",
        "name_original": None,
        "definition": "外部電場によりエネルギー準位が分裂・シフトする現象。ヨハネス・シュタルクが1913年に発見。摂動論の格好の例題。",
        "impact_summary": "原子の電気分極率測定・リドベルグ原子の電場感度・量子計算での個別アドレッシングに応用。",
        "subfield": "物理学",
        "school_of_thought": "原子物理",
        "era_start": 1913,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Stark_effect",
        "mathematical_formulation": r"\Delta E_n^{(2)} = -\frac{3}{2}\alpha_0 E^2 n^4 a_0^3,\quad \alpha_0 = 4\pi\varepsilon_0 a_0^3",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "変分モンテカルロ法",
        "name_en": "Variational Monte Carlo",
        "name_original": "VMC",
        "definition": "試行波動関数のパラメータをモンテカルロサンプリングで最適化し、多体量子系の基底状態エネルギーを計算する方法。",
        "impact_summary": "神経量子状態・量子化学・核物質など解析解のない多体系の高精度計算に使われる。",
        "subfield": "物理学",
        "school_of_thought": "計算物理",
        "era_start": 1965,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Variational_Monte_Carlo",
        "mathematical_formulation": r"E[\psi_T] = \frac{\langle\psi_T|H|\psi_T\rangle}{\langle\psi_T|\psi_T\rangle} \geq E_0",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "密度行列繰り込み群",
        "name_en": "Density Matrix Renormalization Group",
        "name_original": "DMRG",
        "definition": "1次元量子格子系の基底状態を密度行列の最も重要な固有ベクトルを逐次的に選択することで高精度に求める数値手法。ホワイトが1992年に開発。",
        "impact_summary": "スピン鎖・ハバードモデル・ポリマー電子構造の精密解析。テンソルネットワーク理論の母体。",
        "subfield": "物理学",
        "school_of_thought": "計算物理",
        "era_start": 1992,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Density_matrix_renormalization_group",
        "mathematical_formulation": r"|\\psi\rangle = \sum_{\{s\}} A^{s_1}A^{s_2}\cdots A^{s_N}|s_1 s_2\cdots s_N\rangle",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "断熱量子計算",
        "name_en": "Adiabatic Quantum Computation",
        "name_original": None,
        "definition": "系のハミルトニアンを初期の容易に準備できる基底状態から最終的に解くべき問題を符号化したハミルトニアンへ断熱的に変化させて解を得る量子計算。",
        "impact_summary": "量子アニーリング（D-Waveなど）の理論基盤。組み合わせ最適化・機械学習への応用が期待。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 2000,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Adiabatic_quantum_computation",
        "mathematical_formulation": r"H(s) = (1-s)H_0 + sH_{\text{prob}},\quad T \gg \hbar/\Delta_{\min}^2",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "相転移の臨界現象",
        "name_en": "Critical Phenomena in Phase Transitions",
        "name_original": None,
        "definition": "相転移の臨界点近傍で相関長が発散し、物理量がべき乗則に従う現象。ウィルソンのくりこみ群で普遍クラスが確立。",
        "impact_summary": "磁性体・液体・高分子など多様な系が同じ臨界指数を持つ普遍性を解明し、ウィルソンの1982年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "統計力学",
        "era_start": 1960,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Critical_phenomena",
        "mathematical_formulation": r"\xi \sim |t|^{-\nu},\quad C \sim |t|^{-\alpha},\quad M \sim |t|^\beta,\quad t = (T-T_c)/T_c",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "イジングモデル",
        "name_en": "Ising Model",
        "name_original": None,
        "definition": "格子点上のスピン変数（±1）が隣接スピンと相互作用する最も単純な磁性モデル。2次元では厳密解（オンサーガー解）が存在し相転移を示す。",
        "impact_summary": "統計力学・機械学習（ボルツマンマシン）・量子アニーリングの基礎モデル。",
        "subfield": "物理学",
        "school_of_thought": "統計力学",
        "era_start": 1925,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Ising_model",
        "mathematical_formulation": r"H = -J\sum_{\langle i,j\rangle}s_i s_j - h\sum_i s_i,\quad Z = \sum_{\{s\}}e^{-\beta H}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ブラウン運動の物理",
        "name_en": "Brownian Motion (Physics)",
        "name_original": None,
        "definition": "液体中の微粒子が溶媒分子との衝突により不規則に揺動する現象。アインシュタインが1905年に理論を確立し、アトムの実在を証明。",
        "impact_summary": "揺動散逸定理・確率過程・熱統計力学の基礎。ランジュバン方程式・フォッカー＝プランク方程式へと発展。",
        "subfield": "物理学",
        "school_of_thought": "統計力学",
        "era_start": 1905,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Brownian_motion",
        "mathematical_formulation": r"\langle x^2(t)\rangle = 2Dt,\quad D = \frac{k_BT}{6\pi\eta r}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "フォノンとデバイ・ボルン近似",
        "name_en": "Phonon Physics",
        "name_original": None,
        "definition": "結晶格子の量子化された振動モード。音響・光学フォノン、電子フォノン相互作用を含む固体物理学の中心概念。",
        "impact_summary": "超伝導（BCS理論）・熱伝導・熱電材料・格子熱容量の微視的理解を与える。",
        "subfield": "物理学",
        "school_of_thought": "固体物理",
        "era_start": 1907,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Phonon",
        "mathematical_formulation": r"E_n = (n+\frac{1}{2})\hbar\omega_k,\quad C_V = \sum_k \frac{(\hbar\omega_k)^2}{k_BT^2}\frac{e^{\hbar\omega_k/k_BT}}{(e^{\hbar\omega_k/k_BT}-1)^2}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ペロフスカイト構造物理",
        "name_en": "Perovskite Physics",
        "name_original": None,
        "definition": "ABX3型ペロフスカイト構造を持つ物質群の電子・光・強誘電体特性を研究する分野。有機無機ハイブリッド型は太陽電池として注目。",
        "impact_summary": "高温超伝導・マルチフェロイック・ペロフスカイト太陽電池（効率25%超）など現代材料科学の主流。",
        "subfield": "物理学",
        "school_of_thought": "物性物理",
        "era_start": 1990,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Perovskite_(structure)",
        "mathematical_formulation": r"t = \frac{r_A+r_X}{\sqrt{2}(r_B+r_X)},\quad 0.9 < t < 1.0 \Rightarrow \text{stable perovskite}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "時間結晶",
        "name_en": "Time Crystal",
        "name_original": None,
        "definition": "空間的な結晶が空間並進対称性を自発的に破るように、時間の並進対称性を自発的に破る非平衡物質相。ウィルチェクが2012年に提案し、2021年に実現。",
        "impact_summary": "非平衡量子物質の新しい相として量子コンピュータで実証。フロケ系・多体局在と深く関連。",
        "subfield": "物理学",
        "school_of_thought": "非平衡物理",
        "era_start": 2012,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Time_crystal",
        "mathematical_formulation": r"\langle\hat{O}(t)\rangle = \langle\hat{O}(t+T)\rangle,\quad T \neq T_{\text{drive}}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "非平衡熱力学",
        "name_en": "Non-Equilibrium Thermodynamics",
        "name_original": None,
        "definition": "平衡から遠く離れた系の散逸・自己組織化・エントロピー生成を扱う熱力学。プリゴジンが1977年ノーベル賞を受賞。",
        "impact_summary": "散逸構造・ベナール対流・生命システムの開放系熱力学に理論的基盤を与えた。",
        "subfield": "物理学",
        "school_of_thought": "非線形科学",
        "era_start": 1945,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Non-equilibrium_thermodynamics",
        "mathematical_formulation": r"\sigma = \sum_k J_k X_k \geq 0,\quad J_k = \sum_l L_{kl}X_l",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ゆらぎの定理",
        "name_en": "Fluctuation Theorem",
        "name_original": None,
        "definition": "確率的熱力学において、エントロピー生成量のゆらぎが正負の確率比についての精密な等式を与える定理群。エバンスら1993年。",
        "impact_summary": "非平衡微小系（コロイド・モータータンパク質）のエントロピー生成を記述し、熱力学第二法則のゆらぎへの延長。",
        "subfield": "物理学",
        "school_of_thought": "統計力学",
        "era_start": 1993,
        "culture_region": "Oceania",
        "source_url": "https://en.wikipedia.org/wiki/Fluctuation_theorem",
        "mathematical_formulation": r"\frac{P(\Sigma_t = A)}{P(\Sigma_t = -A)} = e^A,\quad \Sigma_t = \int_0^t \sigma\,ds",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "イスラーム光学—イブン・アル＝ハイサムの反射・屈折理論",
        "name_en": "Ibn al-Haytham Optics — Reflection and Refraction",
        "name_original": "كتاب المناظر",
        "definition": "イブン・アル＝ハイサム（アルハーゼン）が著書『Kitāb al-Manāẓir』（1011-1021年）で確立した光の反射・屈折・カメラオブスクラ・視覚の経験的理論。",
        "impact_summary": "ヨーロッパ科学革命における光学の前身。フェルマーの最小時間原理・ニュートン光学の基礎に連なる非西洋科学の金字塔。",
        "subfield": "物理学",
        "school_of_thought": "イスラーム光学",
        "era_start": 1011,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Book_of_Optics",
        "mathematical_formulation": r"\text{Law of reflection: }\theta_i = \theta_r;\quad \text{Refraction: }n_1\sin\theta_1 = n_2\sin\theta_2\text{ (later Snell)}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ケーラ学派の無限級数と微積分の先駆",
        "name_en": "Kerala School Infinite Series",
        "name_original": "Nilakantha Somayaji",
        "definition": "14-16世紀のインド・ケーラ地方の数学者ニーラカンタ・サマーヤージらがπ・三角関数の無限級数展開を記述。グレゴリー・ライプニッツより約200年先行。",
        "impact_summary": "微積分発見の文化的独立性を示す非西洋科学の重要な例。伝播ルートは未解明だが先行性は認められている。",
        "subfield": "物理学",
        "school_of_thought": "南アジア数理科学",
        "era_start": 1400,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Kerala_school_of_astronomy_and_mathematics",
        "mathematical_formulation": r"\pi = 4\left(1-\frac{1}{3}+\frac{1}{5}-\frac{1}{7}+\cdots\right)=4\sum_{k=0}^\infty\frac{(-1)^k}{2k+1}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "和算と円理（江戸日本の物理数学）",
        "name_en": "Wasan — Japanese Traditional Mathematics",
        "name_original": "和算",
        "definition": "江戸時代（17-19世紀）に独自発展した日本の数学体系。関孝和の行列式・建部賢弘の円理（π計算）など西洋とは独立した成果を持つ。",
        "impact_summary": "鎖国期における自律的科学発展の事例として科学史に重要。算額の奉納文化は民衆的科学普及の形態。",
        "subfield": "物理学",
        "school_of_thought": "東アジア数理科学",
        "era_start": 1680,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Japanese_mathematics",
        "mathematical_formulation": r"\pi = 3.14159265358979\ldots\text{ (Takebe, 1722, by iterative method)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ナノ磁性・スキルミオン",
        "name_en": "Skyrmion (Magnetic)",
        "name_original": None,
        "definition": "磁性体中に現れるスピン構造のトポロジカルに安定なソリトン。スカーミオン数（整数）で特徴付けられ、極低電流で駆動できる。",
        "impact_summary": "超高密度スキルミオン記憶素子・トポロジカルスピントロニクスの注目対象。",
        "subfield": "物理学",
        "school_of_thought": "ナノ磁性",
        "era_start": 2009,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Magnetic_skyrmion",
        "mathematical_formulation": r"Q = \frac{1}{4\pi}\int \mathbf{n}\cdot\left(\frac{\partial\mathbf{n}}{\partial x}\times\frac{\partial\mathbf{n}}{\partial y}\right)dxdy \in \mathbb{Z}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "量子ウォーク",
        "name_en": "Quantum Walk",
        "name_original": None,
        "definition": "古典的ランダムウォークの量子力学的類似。コインと位置の重ね合わせにより2次元格子上では弾道的拡散（∝t）を示す。",
        "impact_summary": "量子アルゴリズム（グローバー探索の一般化）・量子シミュレーション・光合成エネルギー輸送モデルに応用。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 1993,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_walk",
        "mathematical_formulation": r"|\psi(t)\rangle = (C\otimes S)^t|\psi(0)\rangle,\quad \sigma^2 \propto t^2 \text{ (ballistic)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "光格子量子シミュレーター",
        "name_en": "Optical Lattice Quantum Simulator",
        "name_original": None,
        "definition": "レーザーで作成した周期ポテンシャル（光格子）中に超冷却原子を捕獲し、ハバードモデル・格子ゲージ理論などを量子エミュレートする装置。",
        "impact_summary": "スーパーフルイド・モット絶縁体転移を観測し、高温超伝導・量子磁性の解明を目指す。",
        "subfield": "物理学",
        "school_of_thought": "量子シミュレーション",
        "era_start": 2002,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Optical_lattice",
        "mathematical_formulation": r"H = -t\sum_{\langle ij\rangle}c_i^\dagger c_j + U\sum_i n_{i\uparrow}n_{i\downarrow}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "光子の粒子性と波動性の実験的検証",
        "name_en": "Wave-Particle Duality of Photon",
        "name_original": None,
        "definition": "光が波動（干渉・回折）と粒子（光電効果・コンプトン散乱）両方の性質を示すという量子力学の根幹原理の実験的証拠。",
        "impact_summary": "量子力学の「相補性」概念の核心。二重スリット実験の単光子版で実験的に実証され、量子力学の世界観を確立した。",
        "subfield": "物理学",
        "school_of_thought": "量子力学",
        "era_start": 1905,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Wave%E2%80%93particle_duality",
        "mathematical_formulation": r"E = h\nu,\quad p = \frac{h}{\lambda} = \hbar k",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ファラデー効果",
        "name_en": "Faraday Effect",
        "name_original": None,
        "definition": "磁場中の透明媒質を通る直線偏光の偏光面が磁場方向に回転する現象（磁気光学効果）。マイケル・ファラデーが1845年に発見。",
        "impact_summary": "光と電磁場の相互作用の発見として電磁気学の統一に寄与。磁気光学記録・光アイソレーターに応用。",
        "subfield": "物理学",
        "school_of_thought": "電磁光学",
        "era_start": 1845,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Faraday_effect",
        "mathematical_formulation": r"\beta = VBd,\quad V = \text{Verdet constant}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ラーマン分光法",
        "name_en": "Raman Spectroscopy",
        "name_original": None,
        "definition": "分子に光を当てたとき入射光と異なる振動数の散乱光が生じる現象（ラーマン散乱）を利用した分析法。チャンドラセカーラ・V・ラーマンが1928年に発見。",
        "impact_summary": "非破壊・非侵襲の分子構造解析として材料・医療・宝石鑑定・宇宙探査に広く応用。",
        "subfield": "物理学",
        "school_of_thought": "分光学",
        "era_start": 1928,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Raman_spectroscopy",
        "mathematical_formulation": r"\Delta\nu = \nu_0 - \nu_{\text{Raman}} = \nu_{\text{vib}},\quad I_R \propto |\partial\alpha/\partial Q|^2 I_0",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "超音波とソノグラフィーの物理",
        "name_en": "Ultrasound Physics and Sonography",
        "name_original": None,
        "definition": "可聴域を超える超音波（2-20MHz）の生体・材料中伝播、反射・吸収を利用した非破壊検査・医療画像化。ランジュバンの圧電超音波が起源。",
        "impact_summary": "胎児エコー・心エコー・材料探傷試験など安全で低コストな画像診断・検査の基盤。",
        "subfield": "物理学",
        "school_of_thought": "応用音響学",
        "era_start": 1917,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Medical_ultrasound",
        "mathematical_formulation": r"Z = \rho c,\quad R = \left(\frac{Z_2-Z_1}{Z_2+Z_1}\right)^2",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "超流動（液体ヘリウム3）",
        "name_en": "Superfluidity in Helium-3",
        "name_original": None,
        "definition": "フェルミオンである³Heが極低温（〜2mK）でクーパー対を形成してBCS的超流動状態となる。さらにアンダーソン＝ブリンクマン＝モレル相では三重項ペアリングが生じる。",
        "impact_summary": "異方的超伝導体との類推・トポロジカル超流動・宇宙論（宇宙紐のアナロジー）に関連。リー・オシェロフ・リチャードソンの1996年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "低温物理",
        "era_start": 1972,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Superfluid_helium-3",
        "mathematical_formulation": r"\Delta_{\mathbf{k}} = \Delta_0(\hat{k}_x\pm i\hat{k}_y)\hat{\mathbf{z}},\quad \text{(ABM phase)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ミューオン（μ粒子）の発見と性質",
        "name_en": "Muon Discovery",
        "name_original": None,
        "definition": "宇宙線実験でアンダーソンとネダーマイヤーが1936年に発見した電子の約207倍の質量を持つレプトン。弱い相互作用と重力にしか感じない。",
        "impact_summary": "素粒子の世代構造（世代問題）の発見につながる。ミューオン異常磁気モーメントは標準モデルを超える新物理探索の最前線。",
        "subfield": "物理学",
        "school_of_thought": "素粒子物理",
        "era_start": 1936,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Muon",
        "mathematical_formulation": r"m_\mu = 105.66\,\text{MeV}/c^2 \approx 207 m_e,\quad \tau_\mu = 2.197\,\mu\text{s}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "Wボソン・Zボソンの発見",
        "name_en": "W and Z Boson Discovery",
        "name_original": None,
        "definition": "弱い相互作用を媒介するWボソン（±）とZボソンがCERNのSppS衝突型加速器でルッビアとファン・デル・メールのチームにより1983年に発見。",
        "impact_summary": "電弱統一理論（グラショウ・サラム・ワインバーグ）の直接検証。1984年ノーベル賞。",
        "subfield": "物理学",
        "school_of_thought": "素粒子物理",
        "era_start": 1983,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/W_and_Z_bosons",
        "mathematical_formulation": r"m_W = 80.37\,\text{GeV}/c^2,\quad m_Z = 91.19\,\text{GeV}/c^2,\quad \sin^2\theta_W \approx 0.231",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ディラック方程式",
        "name_en": "Dirac Equation",
        "name_original": None,
        "definition": "ポール・ディラックが1928年に導いた相対論的量子力学の方程式。電子のスピンを自然に含み、反粒子（陽電子）の存在を予言。",
        "impact_summary": "素粒子物理学の量子場理論の出発点。反物質概念・スピン1/2粒子の統一的記述を確立。",
        "subfield": "物理学",
        "school_of_thought": "相対論的量子力学",
        "era_start": 1928,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Dirac_equation",
        "mathematical_formulation": r"(i\gamma^\mu\partial_\mu - m)\psi = 0,\quad \{\gamma^\mu,\gamma^\nu\} = 2g^{\mu\nu}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "超対称性（SUSY）",
        "name_en": "Supersymmetry",
        "name_original": "SUSY",
        "definition": "ボソンとフェルミオンを交換する対称性を持つ標準モデルの拡張理論。各粒子にスーパーパートナー（スクォーク・スレプトン・ニュートラリーノ等）を予言。",
        "impact_summary": "階層問題・ダークマター候補・弦理論との整合性から長年探索されているが、LHCでまだ発見されていない。",
        "subfield": "物理学",
        "school_of_thought": "素粒子物理",
        "era_start": 1973,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Supersymmetry",
        "mathematical_formulation": r"Q|\text{boson}\rangle = |\text{fermion}\rangle,\quad \{Q,\bar{Q}\} = 2P^\mu\gamma_\mu",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "大統一理論",
        "name_en": "Grand Unified Theory",
        "name_original": "GUT",
        "definition": "電磁・弱・強の3つの相互作用を高エネルギー（10^16 GeV）で統一する理論群。陽子崩壊・磁気モノポールを予言するが未確認。",
        "impact_summary": "バリオン非対称性・宇宙論的磁気モノポールの説明に使われ、素粒子宇宙論の重要な枠組み。",
        "subfield": "物理学",
        "school_of_thought": "素粒子物理",
        "era_start": 1974,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Grand_unified_theory",
        "mathematical_formulation": r"SU(5)\supset SU(3)\times SU(2)\times U(1),\quad M_X\approx 10^{14-16}\,\text{GeV}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "核スピン量子計算",
        "name_en": "NMR Quantum Computing",
        "name_original": None,
        "definition": "核スピンを量子ビットとし、NMRパルスシーケンスでグローバル操作を行う量子コンピュータ。コーウル・ゲルシェンフェルドが1997年に実証。",
        "impact_summary": "初期の量子アルゴリズム（グローバー・ドイチュ）の実証に使われたが，スケーラビリティの課題から超伝導回路等に主役を譲った。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 1997,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_magnetic_resonance_quantum_computer",
        "mathematical_formulation": r"U = e^{-i\mathbf{I}_x\phi}\cdot e^{-i J_{12} I_z^1 I_z^2 \tau}",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "光ピンセット",
        "name_en": "Optical Tweezers",
        "name_original": None,
        "definition": "集束レーザービームの光輻射圧勾配力を利用して微粒子・生体分子を非接触で捕捉・操作する技術。アシュキンが1986年に発明。2018年ノーベル賞。",
        "impact_summary": "DNA・モータータンパク・細胞の単分子力学測定。生物物理学の精密測定ツールとして革命的。",
        "subfield": "物理学",
        "school_of_thought": "生物物理学",
        "era_start": 1986,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Optical_tweezers",
        "mathematical_formulation": r"F_{\text{grad}} = \frac{\pi n_m r^3}{c}\left(\frac{m^2-1}{m^2+2}\right)\nabla I",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "蛍光共鳴エネルギー移動（FRET）",
        "name_en": "Fluorescence Resonance Energy Transfer",
        "name_original": "FRET",
        "definition": "ドナー蛍光体の励起エネルギーがアクセプターに双極子-双極子相互作用で移動する現象。距離（1-10nm）に敏感でナノルーラーと呼ばれる。",
        "impact_summary": "タンパク質folding・DNA/RNA構造・細胞内シグナル伝達を1分子レベルで観測する生物物理の標準ツール。",
        "subfield": "物理学",
        "school_of_thought": "生物物理学",
        "era_start": 1948,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/F%C3%B6rster_resonance_energy_transfer",
        "mathematical_formulation": r"E = \frac{1}{1+(r/R_0)^6},\quad R_0 = \left(\frac{9\kappa^2\Phi_D J}{128\pi^5 n^4 N_A}\right)^{1/6}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "表面プラズモン共鳴",
        "name_en": "Surface Plasmon Resonance",
        "name_original": "SPR",
        "definition": "金属薄膜表面の自由電子集団振動（プラズモン）が光と共鳴する現象。全反射減衰（ATR）法でラベルフリーの分子間相互作用をリアルタイム計測。",
        "impact_summary": "創薬ターゲット同定・抗体親和性測定・バイオセンサーの標準プラットフォーム。",
        "subfield": "物理学",
        "school_of_thought": "ナノフォトニクス",
        "era_start": 1968,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Surface_plasmon_resonance",
        "mathematical_formulation": r"k_{sp} = \frac{\omega}{c}\sqrt{\frac{\varepsilon_m\varepsilon_d}{\varepsilon_m+\varepsilon_d}},\quad \varepsilon_m < -\varepsilon_d",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "プランク定数の精密決定",
        "name_en": "Precise Determination of Planck Constant",
        "name_original": None,
        "definition": "キブルバランス（ワットバランス）やX線干渉計を用いてプランク定数hを精密測定し、SI単位系（kg）の定義基礎とする国際計量の取り組み。",
        "impact_summary": "2019年SI改訂でhが固定値として定義され、質量の量子基準を確立した科学的・実用的マイルストーン。",
        "subfield": "物理学",
        "school_of_thought": "精密測定・計量学",
        "era_start": 2019,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Kibble_balance",
        "mathematical_formulation": r"h = 6.62607015\times10^{-34}\,\text{J}\cdot\text{s} \text{ (exact, SI 2019)}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "量子容量と量子チャネル容量",
        "name_en": "Quantum Channel Capacity",
        "name_original": None,
        "definition": "量子通信チャネルが伝送できる量子情報の最大レートを定める理論。古典容量・量子容量・プライベート容量の3種類の量子シャノン理論を含む。",
        "impact_summary": "量子通信ネットワーク・量子インターネット設計の理論基盤。エラー訂正不能な雑音下での量子情報の限界を定める。",
        "subfield": "物理学",
        "school_of_thought": "量子情報科学",
        "era_start": 1996,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_capacity",
        "mathematical_formulation": r"Q(\mathcal{E}) = \max_{\rho} I_c(\rho,\mathcal{E}),\quad I_c = S(\mathcal{E}(\rho))-S_e(\rho,\mathcal{E})",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "重力場の数値相対論",
        "name_en": "Numerical Relativity",
        "name_original": None,
        "definition": "一般相対性理論の非線形場方程式をコンピュータで数値解析し、ブラックホール合体・中性子星合体・重力波形を計算する分野。",
        "impact_summary": "2015年のLIGOによる重力波初検出に必須の波形テンプレートを提供。GW150914などの解析の背後にある計算基盤。",
        "subfield": "物理学",
        "school_of_thought": "数値相対論",
        "era_start": 2005,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Numerical_relativity",
        "mathematical_formulation": r"G_{\mu\nu} = 8\pi T_{\mu\nu},\quad \partial_t\gamma_{ij} = -2\alpha K_{ij}+\mathcal{L}_\beta\gamma_{ij}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ブラックホールシャドウの撮像",
        "name_en": "Black Hole Shadow Imaging",
        "name_original": None,
        "definition": "VLBI（超長基線干渉法）を地球規模で組んだイベント・ホライズン・テレスコープ（EHT）がM87銀河中心ブラックホールのシャドウを2019年に初撮像。",
        "impact_summary": "ブラックホール存在の直接画像証拠。光環・シャドウサイズから質量測定が可能になり、一般相対論の強重力場での検証となった。",
        "subfield": "物理学",
        "school_of_thought": "天体物理・一般相対論",
        "era_start": 2019,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Event_Horizon_Telescope",
        "mathematical_formulation": r"r_{\text{shadow}} \approx 5.2 r_s,\quad r_s = 2GM/c^2",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
]


def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute(
            "SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],)
        )
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute(
            """
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,
            (
                uid,
                c["name_ja"],
                c["name_en"],
                c.get("name_original"),
                c["definition"],
                c["impact_summary"],
                c["subfield"],
                c["school_of_thought"],
                c["era_start"],
                c["culture_region"],
                c["source_url"],
                c.get("mathematical_formulation"),
                c.get("verification_status", "url_present"),
                "active",
                c.get("data_completeness", 85),
                now,
                now,
            ),
        )
        inserted += 1
    conn.commit()
    return inserted


if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    batch_size = 50
    total = 0
    for i in range(0, len(CONCEPTS), batch_size):
        batch = CONCEPTS[i : i + batch_size]
        n = insert_batch(conn, batch)
        total += n
        print(f"  Batch {i//batch_size+1}: {n} inserted (running total: {total})")
    conn.close()
    conn2 = sqlite3.connect(DB_PATH)
    count = conn2.execute("SELECT COUNT(*) FROM natural_discovery").fetchone()[0]
    conn2.close()
    print(f"\nBatch4 physics2: {total} concepts inserted")
    print(f"Total in table: {count}")
