"""
DUA Wave A2 Batch 5 — Chemistry (additional 80 concepts)
Target subfield: 化学 (currently 229, need +290 toward 519)
"""
import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

CONCEPTS = [
    {
        "name_ja": "分子軌道法（MO法）",
        "name_en": "Molecular Orbital Theory",
        "name_original": "MO Theory",
        "definition": "電子を原子核の全体にわたって非局在化した分子軌道に配置し、電子構造を記述する量子化学的方法。ハンド・マリケン・レンナード＝ジョーンズが発展させた。",
        "impact_summary": "芳香族安定性・共役系・遷移金属錯体・励起状態の理解に不可欠。計算化学の出発点。",
        "subfield": "化学",
        "school_of_thought": "量子化学",
        "era_start": 1932,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Molecular_orbital_theory",
        "mathematical_formulation": r"\psi_{\text{MO}} = c_1\phi_1 + c_2\phi_2,\quad \det(H_{ij}-E S_{ij}) = 0",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "結合価殻電子対反発理論",
        "name_en": "VSEPR Theory",
        "name_original": "Valence Shell Electron Pair Repulsion",
        "definition": "分子の立体構造を電子対（結合・孤立電子対）の反発最小化で予測する理論。ギルスピーとニホームが1957年に確立。",
        "impact_summary": "化学教育の分子幾何学の基礎として、H2O・NH3・SF6などの構造を直感的に説明する。",
        "subfield": "化学",
        "school_of_thought": "無機化学",
        "era_start": 1957,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/VSEPR_theory",
        "mathematical_formulation": r"\text{steric number} = \text{bonds} + \text{lone pairs},\quad AX_n E_m",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "配位子場理論",
        "name_en": "Ligand Field Theory",
        "name_original": "LFT",
        "definition": "配位子の電場が遷移金属イオンのd軌道を分裂させ、色・磁性・反応性を決定する理論。結晶場理論をMO法と融合させた。",
        "impact_summary": "錯体化学の色彩・スピン状態・触媒活性の統一的説明。太陽電池・MRI造影剤設計に応用。",
        "subfield": "化学",
        "school_of_thought": "無機化学",
        "era_start": 1951,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Ligand_field_theory",
        "mathematical_formulation": r"\Delta_o = E(e_g) - E(t_{2g}),\quad \text{CFSE} = -0.4\Delta_o n_{t_{2g}} + 0.6\Delta_o n_{e_g}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "電子移動反応（マーカス理論）",
        "name_en": "Marcus Theory of Electron Transfer",
        "name_original": None,
        "definition": "溶液中の電子移動速度定数を反応自由エネルギーと再組織化エネルギーで記述する理論。ルドルフ・マーカスが1956年に提唱し1992年ノーベル賞。",
        "impact_summary": "光合成・呼吸鎖・有機太陽電池・腐食反応の電子移動速度を定量的に理解する基盤。",
        "subfield": "化学",
        "school_of_thought": "物理有機化学",
        "era_start": 1956,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Marcus_theory",
        "mathematical_formulation": r"k_{ET} = \frac{2\pi}{\hbar}|H_{DA}|^2 \frac{1}{\sqrt{4\pi\lambda k_BT}}e^{-\frac{(\Delta G^\circ+\lambda)^2}{4\lambda k_BT}}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "フロンティア電子理論（FMO理論）",
        "name_en": "Frontier Molecular Orbital Theory",
        "name_original": "FMO Theory",
        "definition": "化学反応はフロンティア軌道（HOMO・LUMO）の相互作用で制御されるという理論。福井謙一が1952年に提案し1981年ノーベル賞。",
        "impact_summary": "ペリ環状反応・酸塩基・求電子・求核反応の選択性・配向性を電子軌道から説明。",
        "subfield": "化学",
        "school_of_thought": "物理有機化学",
        "era_start": 1952,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Frontier_molecular_orbital_theory",
        "mathematical_formulation": r"\Delta E \approx -\frac{(c_r^{HOMO}\cdot c_s^{LUMO})^2}{\epsilon_{HOMO}-\epsilon_{LUMO}}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "ウッドワード＝ホフマン則",
        "name_en": "Woodward-Hoffmann Rules",
        "name_original": None,
        "definition": "ペリ環状反応の許容・禁止を分子軌道の対称性（熱・光条件下での）で説明する規則。1965年ウッドワードとホフマンが提唱。",
        "impact_summary": "有機合成の立体化学制御の理論的基礎。電子環化・シグマトロピー・環化付加を統一的に扱う。",
        "subfield": "化学",
        "school_of_thought": "有機化学",
        "era_start": 1965,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Woodward%E2%80%93Hoffmann_rules",
        "mathematical_formulation": r"\text{Thermal: }[4n+2]\text{ supra-supra allowed; }[4n]\text{ supra-antara allowed}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "固相合成法（SPPS）",
        "name_en": "Solid-Phase Peptide Synthesis",
        "name_original": "SPPS",
        "definition": "ペプチドを固定された担体樹脂上で逐次合成するメリフィールド法（1963年）。保護基の着脱サイクルで精製不要の長鎖ペプチド合成を実現。",
        "impact_summary": "天然・非天然アミノ酸含有ペプチド薬・タンパク質断片の合成を自動化し、創薬・ワクチン・素材開発を変えた。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学",
        "era_start": 1963,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Solid-phase_synthesis",
        "mathematical_formulation": r"\text{Fmoc-AA-OH} + H_2N\text{-Resin} \xrightarrow{\text{coupling}} \text{Fmoc-AA-NH-Resin}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "リビング重合",
        "name_en": "Living Polymerization",
        "name_original": None,
        "definition": "連鎖移動・停止反応が起きず分子量と末端官能基を精密制御できる重合。アニオン重合（ジーグラー・スアワラ）から原子移動ラジカル重合（ATRP）まで多様。",
        "impact_summary": "ブロック共重合体・スターポリマー・グラフトポリマーなど精密構造ポリマーの合成基盤。",
        "subfield": "化学",
        "school_of_thought": "高分子化学",
        "era_start": 1956,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Living_polymerization",
        "mathematical_formulation": r"\bar{X}_n = \frac{[\text{monomer}]_0}{[\text{initiator}]_0},\quad D = M_w/M_n \to 1",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ゾルゲル法",
        "name_en": "Sol-Gel Process",
        "name_original": None,
        "definition": "金属アルコキシドの加水分解・縮合反応によりゾルからゲルを経て酸化物薄膜・バルク・ナノ粒子を合成する湿式化学法。",
        "impact_summary": "低温での複合酸化物合成・光ファイバー母材・反射防止コーティング・触媒担体・機能性薄膜製造に広用。",
        "subfield": "化学",
        "school_of_thought": "無機材料化学",
        "era_start": 1971,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Sol-gel_process",
        "mathematical_formulation": r"M(OR)_n + H_2O \to M(OH)_n + ROH;\quad -M-OH + HO-M- \to -M-O-M- + H_2O",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "触媒的不斉合成（アシンメトリック触媒）",
        "name_en": "Asymmetric Catalysis",
        "name_original": None,
        "definition": "キラルな遷移金属錯体・有機小分子が触媒として不斉中心を持つ生成物を高エナンチオ選択的に生成する手法。野依良治・ノウルズ・シャープレスが2001年ノーベル賞。",
        "impact_summary": "医薬品・農薬・フレーバーの不斉合成を効率化し、従来の分割・天然物抽出を代替する化学産業の基盤技術。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学",
        "era_start": 1980,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Asymmetric_synthesis",
        "mathematical_formulation": r"\text{ee} = \frac{[R]-[S]}{[R]+[S]}\times100\%,\quad \Delta\Delta G^\ddagger = RT\ln\left(\frac{k_R}{k_S}\right)",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "メタセシス反応",
        "name_en": "Olefin Metathesis",
        "name_original": None,
        "definition": "アルケンの二重結合をルテニウム・モリブデン触媒（グラブス触媒・シュロック触媒）を介して組み替える反応。グラブス・シュロック・ショーバンが2005年ノーベル賞。",
        "impact_summary": "天然物・医薬品・高分子合成の革命的なC-C結合形成。ルーフィング材（ROMP）・製薬プロセスに工業応用。",
        "subfield": "化学",
        "school_of_thought": "有機金属化学",
        "era_start": 1970,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Olefin_metathesis",
        "mathematical_formulation": r"2\text{R}CH=CH_2 \xrightarrow{\text{cat.}} \text{R}CH=CH\text{R} + CH_2=CH_2",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "フローケミストリー",
        "name_en": "Flow Chemistry",
        "name_original": None,
        "definition": "連続流通反応器中で化学反応を行う手法。マイクロリアクターや管状反応器で温度・混合・圧力を精密制御し安全に危険反応を実施できる。",
        "impact_summary": "医薬品連続製造・爆発性反応・光化学反応の安全実施・小スケール高速合成スクリーニングに有効。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学",
        "era_start": 2000,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Flow_chemistry",
        "mathematical_formulation": r"\text{Residence time} = V/Q,\quad \text{Da} = k\tau c_0^{n-1}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "電気化学的CO2還元",
        "name_en": "Electrochemical CO2 Reduction",
        "name_original": None,
        "definition": "再生可能電力を使いCO2を電気触媒で選択的にCO・メタノール・エチレン等の有価物に変換する反応。2015年以降急速に発展。",
        "impact_summary": "炭素循環・電燃料合成・電化学プラント化学の核心技術として脱炭素産業に位置づけられる。",
        "subfield": "化学",
        "school_of_thought": "電気化学",
        "era_start": 1985,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Electrochemical_reduction_of_carbon_dioxide",
        "mathematical_formulation": r"CO_2 + 2H^+ + 2e^- \to CO + H_2O,\quad E^\circ = -0.52\,\text{V vs. SHE}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "酵素触媒反応の動力学",
        "name_en": "Enzyme Kinetics",
        "name_original": None,
        "definition": "酵素と基質の複合体形成・分解を記述するミカエリス＝メンテン方程式に代表される反応速度論。KmとVmaxが主要パラメータ。",
        "impact_summary": "医薬品設計（阻害剤のIC50・Ki）・代謝工学・食品産業・バイオプロセス最適化の定量基盤。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 1913,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics",
        "mathematical_formulation": r"v = \frac{V_{\max}[S]}{K_m+[S]},\quad K_m = \frac{k_{-1}+k_2}{k_1}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "シトクロムP450（CYP）",
        "name_en": "Cytochrome P450",
        "name_original": "CYP enzymes",
        "definition": "ヘムタンパク質群で、分子状酸素を活性化し基質を酸化する生体触媒。薬物代謝・ステロイド合成・毒素解毒に中心的役割を担う。",
        "impact_summary": "医薬品の薬物動態・相互作用・毒性試験の主要ターゲット。生物触媒合成への応用も急増。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 1958,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Cytochrome_P450",
        "mathematical_formulation": r"\text{RH} + O_2 + \text{NADPH} + H^+ \to \text{ROH} + \text{NADP}^+ + H_2O",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "金属有機構造体（MOF）",
        "name_en": "Metal-Organic Framework",
        "name_original": "MOF",
        "definition": "金属イオンと有機配位子が自己組織化して形成する多孔性結晶ネットワーク。BET表面積が5,000-7,000 m²/gに達する最高多孔度材料。",
        "impact_summary": "CO2貯蔵・水素貯蔵・薬物送達・分離膜・触媒など多機能性ガス・液体分離材料として注目。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 1999,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Metal-organic_framework",
        "mathematical_formulation": r"S_{\text{BET}} = \frac{n_m N_A \sigma}{1},\quad \text{MOF-5: }3,800\,\text{m}^2/\text{g}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "共有結合有機構造体（COF）",
        "name_en": "Covalent Organic Framework",
        "name_original": "COF",
        "definition": "共有結合のみで構成された2次元・3次元の周期多孔性ポリマー結晶。ヤーギらが2005年に初報告。軽量・熱安定・高比表面積。",
        "impact_summary": "光触媒・エネルギー貯蔵・センシング・キラル分離のプラットフォーム材料として急速に発展。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 2005,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Covalent_organic_framework",
        "mathematical_formulation": r"2 R-CHO + H_2N-R'-NH_2 \to R-CH=N-R'-N=CH-R + 2H_2O \text{ (imine-COF)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ナノ粒子の合成と機能化",
        "name_en": "Nanoparticle Synthesis and Functionalization",
        "name_original": None,
        "definition": "1-100nmスケールの金属・酸化物・量子ドット・ポリマーナノ粒子を精密に合成し、表面修飾により機能を付与する化学。",
        "impact_summary": "がん温熱療法（金ナノ粒子）・MRI造影（酸化鉄）・LED（量子ドット）・触媒への応用が急拡大。",
        "subfield": "化学",
        "school_of_thought": "ナノ化学",
        "era_start": 1993,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Nanoparticle",
        "mathematical_formulation": r"d \propto \left(\frac{\text{[monomer]}}{\text{[nuclei]}}\right)^{1/3},\quad \varepsilon_\text{Au NP} \sim 10^8\,\text{M}^{-1}\text{cm}^{-1}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "シングルモレキュール化学",
        "name_en": "Single-Molecule Chemistry",
        "name_original": None,
        "definition": "1分子レベルで化学反応・構造・ダイナミクスを観測する実験手法群。蛍光・STM・AFM・光ピンセットを組み合わせる。",
        "impact_summary": "アンサンブル平均に隠れた不均一性・中間体・揺らぎを直接観測し、酵素反応機構・DNA複製・タンパク質折り畳みを解明。",
        "subfield": "化学",
        "school_of_thought": "物理化学",
        "era_start": 1989,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Single-molecule_experiment",
        "mathematical_formulation": r"k_{\text{obs}} = k_{\text{on}}[L] + k_{\text{off}},\quad \langle\tau_\text{bound}\rangle = k_{\text{off}}^{-1}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "タンパク質のフォールディング",
        "name_en": "Protein Folding",
        "name_original": None,
        "definition": "一次配列から3次元構造への折り畳み過程。アンフィンセンの熱力学仮説（1973年）から始まり、AlphaFold2（2021年）がAIで構造予測を革命的に解決。",
        "impact_summary": "創薬・酵素設計・疾患（プリオン・アルツハイマー）理解に不可欠。エネルギー地形の「ファネル」モデルが現代的理解。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 1973,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Protein_folding",
        "mathematical_formulation": r"G_{\text{fold}} = H_{\text{fold}} - TS_{\text{fold}},\quad \Delta G_U = RT\ln(K_U)",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "質量分析法（MS）",
        "name_en": "Mass Spectrometry",
        "name_original": "MS",
        "definition": "分子をイオン化して質量電荷比で分離・検出する分析法。ESI（エレクトロスプレー）・MALDI・FT-ICRなど多様なイオン化法と質量計。",
        "impact_summary": "プロテオミクス・代謝物解析・食品安全・環境分析・宇宙化学で不可欠。フェン・田中耕一の2002年ノーベル賞。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1913,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Mass_spectrometry",
        "mathematical_formulation": r"m/z = \frac{\text{ionic mass}}{\text{charge}},\quad t = L\sqrt{\frac{2m}{zeU}}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "高速液体クロマトグラフィー（HPLC）",
        "name_en": "High-Performance Liquid Chromatography",
        "name_original": "HPLC",
        "definition": "高圧ポンプで溶媒を固定相充填カラムに通し、分析物を分離・定量する液体クロマトグラフィー。逆相・イオン交換・サイズ排除など多様。",
        "impact_summary": "医薬品品質管理・食品成分分析・環境汚染物モニタリングの必須分析基盤。ウルトラHPLC（UHPLC）で分析時間を1/10に短縮。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1967,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/High-performance_liquid_chromatography",
        "mathematical_formulation": r"N = 16\left(\frac{t_R}{W}\right)^2,\quad R_s = \frac{2(t_{R2}-t_{R1})}{W_1+W_2}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "キャピラリー電気泳動",
        "name_en": "Capillary Electrophoresis",
        "name_original": "CE",
        "definition": "細管内で電場をかけてイオンの移動度差を利用して分離する分析法。高分解能・少量試料・DNA・タンパク質・小分子の高速分離が可能。",
        "impact_summary": "ヒトゲノムプロジェクトのDNA塩基配列決定に使われた毛細管電気泳動がゲノム革命を加速。医薬品不純物分析にも重要。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1981,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Capillary_electrophoresis",
        "mathematical_formulation": r"\mu_{ep} = \frac{q}{6\pi\eta r},\quad N = \frac{\mu_{ep}V}{2D}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "蛍光分光法と蛍光顕微鏡",
        "name_en": "Fluorescence Spectroscopy",
        "name_original": None,
        "definition": "蛍光色素の励起・発光スペクトルを測定し、分子環境・濃度・相互作用を分析する手法。共焦点・二光子・超解像顕微鏡に発展。",
        "impact_summary": "細胞内シグナル・タンパク質局在・mRNAの時空間的解析の標準ツール。GFP・量子ドット・有機色素が普及。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1955,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Fluorescence_spectroscopy",
        "mathematical_formulation": r"F = 2.303\varepsilon cl\Phi_F I_0,\quad \Phi_F = \frac{k_r}{k_r+k_{nr}}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "核オーバーハウザー効果（NOE）",
        "name_en": "Nuclear Overhauser Effect",
        "name_original": "NOE",
        "definition": "NMRにおいてスピン格子緩和を通じて空間的に近接する核スピン間の信号強度が変化する効果。5Å以内の距離情報を提供。",
        "impact_summary": "タンパク質・核酸の溶液NMR構造決定の決定的手段。薬物-受容体相互作用・構造変化の追跡に応用。",
        "subfield": "化学",
        "school_of_thought": "物理化学",
        "era_start": 1955,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_Overhauser_effect",
        "mathematical_formulation": r"\eta = \frac{\sigma}{\rho} = \frac{\gamma_S}{\gamma_I}\cdot f(\tau_c,\omega),\quad r \propto (\text{NOE intensity})^{-1/6}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "赤外分光法（IR）",
        "name_en": "Infrared Spectroscopy",
        "name_original": "IR Spectroscopy",
        "definition": "分子の振動・回転エネルギー準位への赤外線吸収を測定し官能基同定・構造解析を行う分析法。FT-IRが現代の標準装置。",
        "impact_summary": "有機・無機・高分子化学の普及型構造確認ツール。ATR法・時間分解IR・2D IRが最前線分析に展開。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1905,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Infrared_spectroscopy",
        "mathematical_formulation": r"\tilde{\nu} = \frac{1}{\lambda} = \frac{\sqrt{k/\mu}}{2\pi c},\quad \mu = \frac{m_1 m_2}{m_1+m_2}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "熱分析（DSC・TGA）",
        "name_en": "Thermal Analysis (DSC/TGA)",
        "name_original": None,
        "definition": "温度変化に伴う材料の熱特性（融点・ガラス転移・燃焼・分解）を示差走査熱量計（DSC）・熱重量分析（TGA）で定量する分析法。",
        "impact_summary": "ポリマー・医薬品・食品・無機材料の品質管理・加工条件最適化の必須ツール。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1962,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Differential_scanning_calorimetry",
        "mathematical_formulation": r"\Delta H = \int_{T_1}^{T_2} C_p\,dT,\quad T_g\text{ from inflection point of }C_p\text{ vs }T",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "古代ギリシャ原子論（デモクリトス）",
        "name_en": "Democritus Atomism",
        "name_original": "ἄτομος",
        "definition": "物質は分割不可能な最小単位「アトム（原子）」から構成されるとするデモクリトスの哲学的原子論（BC 400年頃）。ルクレティウスを通じてローマ・近代に伝承。",
        "impact_summary": "近代原子論の思想的先駆。ボイル・ドルトンの科学的原子論の系譜的起点として科学史上重要。",
        "subfield": "化学",
        "school_of_thought": "古代科学哲学",
        "era_start": -400,
        "culture_region": "Europe_Southern",
        "source_url": "https://en.wikipedia.org/wiki/Democritus",
        "mathematical_formulation": r"\text{Atom: indivisible, eternal, infinite variety of shapes; void between them}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "アラビア錬金術—ジャービル・イブン・ハイヤーンの元素理論",
        "name_en": "Jabir ibn Hayyan Alchemy",
        "name_original": "جابر بن حيان",
        "definition": "ジャービル（ゲーベル、721-815年）がアリストテレスの四元素論を発展させ、水銀・硫黄理論や実験的錬金術を確立。蒸留・結晶化・昇華の技術を系統化。",
        "impact_summary": "化学実験法の始祖として評価され、近代化学の祖先的存在。塩酸・王水の発見に関連する記述が残る。",
        "subfield": "化学",
        "school_of_thought": "イスラーム錬金術",
        "era_start": 780,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Jabir_ibn_Hayyan",
        "mathematical_formulation": r"\text{Sulfur-Mercury theory: } \text{metals} = f(\text{S,Hg proportions});\quad \text{elixir}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "宋代中国の化学技術—火薬・磁器・製鉄",
        "name_en": "Song Dynasty Chemical Technology",
        "name_original": "宋代化学技术",
        "definition": "宋代（960-1279年）の中国では、火薬（硝石・硫黄・木炭の精密配合）・磁器（高火度・釉薬化学）・銑鉄製錬（コークス相当の石炭製鉄）が世界最先端。",
        "impact_summary": "火薬の西伝が中世ヨーロッパを変容させ、磁器は世界の陶芸・貿易・化学工業の先駆。石炭製鉄は産業革命以前の最先端。",
        "subfield": "化学",
        "school_of_thought": "東アジア技術化学",
        "era_start": 1000,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Science_and_technology_of_the_Song_dynasty",
        "mathematical_formulation": r"\text{Gunpowder: }75\% \text{KNO}_3 + 15\% \text{C} + 10\% \text{S (optimal)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "インドのアーユルヴェーダ薬化学（ラサシャーストラ）",
        "name_en": "Rasa Shastra — Indian Alchemical Medicine",
        "name_original": "रस शास्त्र",
        "definition": "8-12世紀頃に確立したインドの金属・鉱物を薬剤化する化学的医学体系。水銀・硫黄・金・銅の精製・解毒・加工法が記述される。",
        "impact_summary": "南アジアの伝統医薬の技術基盤であり、現代アーユルヴェーダ製剤との連続性を持つ非西洋化学の一形態。",
        "subfield": "化学",
        "school_of_thought": "南アジア薬化学",
        "era_start": 800,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Rasa_shastra",
        "mathematical_formulation": r"\text{Bhasma: metal calcined to ash, particle size }<1\mu\text{m; mercury detoxification by sulfidation}",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "光触媒（半導体光触媒）",
        "name_en": "Semiconductor Photocatalysis",
        "name_original": None,
        "definition": "半導体（TiO2・g-C3N4・BiVO4）が光を吸収して生成した電子・ホールで酸化還元反応（水分解・有機分解）を行う化学。藤嶋昭・本多健一が1972年に発見。",
        "impact_summary": "光触媒水素製造・空気浄化・抗菌・セルフクリーニング材料の科学的基盤。Honda-Fujishima効果として世界的に認知。",
        "subfield": "化学",
        "school_of_thought": "表面化学",
        "era_start": 1972,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Photocatalysis",
        "mathematical_formulation": r"TiO_2 + h\nu \to e^- + h^+;\quad H_2O + 2h^+ \to \frac{1}{2}O_2 + 2H^+;\quad 2H^+ + 2e^- \to H_2",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "双性イオンと両性電解質",
        "name_en": "Zwitterion and Ampholyte",
        "name_original": None,
        "definition": "アミノ酸などが同一分子内に正・負の電荷を持つ双性イオン状態をとる現象。等電点（pI）でゼータ電位ゼロ。",
        "impact_summary": "タンパク質の溶解性・沈殿・電気泳動・バッファー設計の基礎概念。2D電気泳動・等電点集束の原理。",
        "subfield": "化学",
        "school_of_thought": "物理化学",
        "era_start": 1932,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Zwitterion",
        "mathematical_formulation": r"pI = \frac{pK_{a1}+pK_{a2}}{2},\quad \text{net charge }=0 \text{ at }pI",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "コロイドの安定性（DLVO理論）",
        "name_en": "DLVO Theory of Colloid Stability",
        "name_original": None,
        "definition": "デルヤーギン・ランダウ・フェルウェイ・オーバービークが確立したコロイド粒子間の静電反発とファンデルワールス引力の競合によるコロイド安定性理論。",
        "impact_summary": "牛乳・ペイント・薬物ナノ粒子・廃水処理凝集のコロイド安定性設計の基礎理論。",
        "subfield": "化学",
        "school_of_thought": "コロイド化学",
        "era_start": 1941,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/DLVO_theory",
        "mathematical_formulation": r"V_{\text{total}} = V_{\text{EDL}} + V_{\text{vdW}},\quad V_{\text{EDL}} \propto e^{-\kappa h}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "界面活性剤の自己会合",
        "name_en": "Surfactant Self-Assembly",
        "name_original": None,
        "definition": "両親媒性分子（界面活性剤）が臨界ミセル濃度（CMC）を超えると自発的にミセル・二分子膜・液晶などの自己組織構造を形成する現象。",
        "impact_summary": "洗剤・乳化剤・薬物キャリア（リポソーム）・テンプレート合成（メソポーラスシリカ）に不可欠な化学原理。",
        "subfield": "化学",
        "school_of_thought": "コロイド化学",
        "era_start": 1936,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Micelle",
        "mathematical_formulation": r"\Delta G_{\text{mic}} = RT\ln(\text{CMC}),\quad g = \frac{v}{a_0 l_c} \text{ (packing parameter)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "固体酸触媒",
        "name_en": "Solid Acid Catalysis",
        "name_original": None,
        "definition": "ゼオライト・ヘテロポリ酸・酸化物などブレンステッド・ルイス酸点を持つ固体触媒が炭化水素の異性化・クラッキング・アルキル化を実施する。",
        "impact_summary": "石油精製（FCC・水素化分解）・ファインケミカル・バイオマス変換プロセスの基盤。ゼオライトは石油化学の革命。",
        "subfield": "化学",
        "school_of_thought": "触媒化学",
        "era_start": 1960,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Solid_acid_catalyst",
        "mathematical_formulation": r"H_0 = pK_{BH^+} + \log\frac{[BH^+]}{[B]},\quad H_0 < 0 \Rightarrow \text{superacid}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "有機金属化合物の結合論（18電子則）",
        "name_en": "18-Electron Rule in Organometallics",
        "name_original": None,
        "definition": "遷移金属錯体が18個の価電子を満たすと安定な構成となる経験則。CO・シクロペンタジエニル・その他配位子の電子数勘定による。",
        "impact_summary": "有機金属化学の反応設計・触媒サイクル理解・新錯体合成の実用的指針。",
        "subfield": "化学",
        "school_of_thought": "有機金属化学",
        "era_start": 1930,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/18-electron_rule",
        "mathematical_formulation": r"n_e = \text{metal VE} + \sum_L(\text{ligand donation}),\quad n_e = 18 \Rightarrow \text{stable}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "C-H活性化反応",
        "name_en": "C-H Activation",
        "name_original": None,
        "definition": "遷移金属触媒を使い炭化水素の不活性なC-H結合を直接官能基化する反応。事前の官能基化が不要で原子効率・ステップ効率が高い。",
        "impact_summary": "医薬品・農薬・材料の後期段階修飾（LSF）に革命をもたらす。2020年代以降産業応用が急増。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学",
        "era_start": 1993,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/C%E2%80%93H_activation",
        "mathematical_formulation": r"R-H + [M] \to R-[M]-H \xrightarrow{\text{reductive elim.}} R-X + [M]",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "有機半導体と有機電子デバイス",
        "name_en": "Organic Semiconductors",
        "name_original": None,
        "definition": "共役π電子系を持つ有機分子・高分子が半導体特性を示す材料群。OFET・OLED・有機太陽電池などに応用。",
        "impact_summary": "フレキシブルエレクトロニクス・ウェアラブルデバイス・大面積ディスプレイへの応用。白川英樹のポリアセチレン導電化（2000年ノーベル賞）が先駆。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 1977,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Organic_semiconductor",
        "mathematical_formulation": r"\mu = \mu_0 \exp\left(-\frac{\Delta}{k_BT}\right),\quad \Delta = \text{hopping barrier}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "量子ドットの量子閉じ込め効果",
        "name_en": "Quantum Confinement in Quantum Dots",
        "name_original": None,
        "definition": "半導体結晶のサイズがド・ブロイ波長以下になると、バルクと異なるサイズ依存の光学特性（サイズ調整可能な蛍光）が現れる現象。エキモフが1980年代に観測。",
        "impact_summary": "量子ドットLED（QD-LED）・蛍光バイオイメージング・太陽電池（スペクトル変換）の光吸収・発光材料として普及。",
        "subfield": "化学",
        "school_of_thought": "ナノ化学",
        "era_start": 1985,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Quantum_dot",
        "mathematical_formulation": r"E_g(d) = E_g(\infty) + \frac{\pi^2\hbar^2}{2\mu d^2} - \frac{1.8e^2}{4\pi\varepsilon_0\varepsilon_r d}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "生体模倣触媒（バイオミメティック触媒）",
        "name_en": "Biomimetic Catalysis",
        "name_original": None,
        "definition": "酵素の活性中心構造・反応機構を模倣した人工触媒を設計する分野。ポルフィリン鉄錯体・ビオリンク類似化合物などが代表。",
        "impact_summary": "生物触媒の高活性・高選択性を人工系で実現し、医薬品合成・エネルギー変換・CO2固定に応用。",
        "subfield": "化学",
        "school_of_thought": "生体無機化学",
        "era_start": 1975,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Biomimetics",
        "mathematical_formulation": r"k_{\text{cat}}/K_M \leq 10^9\,\text{M}^{-1}\text{s}^{-1}\text{ (diffusion limit)}",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "カルベン化学",
        "name_en": "Carbene Chemistry",
        "name_original": None,
        "definition": "2価炭素種（2個の非結合電子を持つ中性炭素）を反応中間体・有機金属配位子として利用する化学。N-ヘテロ環式カルベン（NHC）は汎用配位子。",
        "impact_summary": "金属触媒のメタセシス・C-H活性化・カルベン挿入反応の実現に必須。NHCはグラブス触媒の不可欠成分。",
        "subfield": "化学",
        "school_of_thought": "有機化学",
        "era_start": 1950,
        "culture_region": "Europe_Central",
        "source_url": "https://en.wikipedia.org/wiki/Carbene",
        "mathematical_formulation": r":CR_2\text{ (singlet or triplet)},\quad \Delta E_{ST} = E_T - E_S",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "反応機構の実験的証明（同位体効果・ハンメット則）",
        "name_en": "Physical Organic Chemistry — Hammett Equation",
        "name_original": None,
        "definition": "置換基の電子的効果が有機反応速度・平衡定数に与える影響をσ（置換基定数）とρ（感応定数）で定量するハンメット式。",
        "impact_summary": "有機反応機構の解明・薬物設計のQSAR・電子密度変化の定量に標準的に使われる物理有機化学の基礎。",
        "subfield": "化学",
        "school_of_thought": "物理有機化学",
        "era_start": 1937,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Hammett_equation",
        "mathematical_formulation": r"\log\frac{k}{k_0} = \rho\sigma,\quad \sigma_p(\text{NO}_2) = +0.78;\quad \sigma_p(\text{OCH}_3) = -0.27",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "緑色化学の12原則",
        "name_en": "Green Chemistry 12 Principles",
        "name_original": None,
        "definition": "アナスタスとワーナーが1998年に提唱した廃棄物防止・原子効率・無害試薬・再生可能原料などを重視する化学設計の倫理的枠組み。",
        "impact_summary": "製薬・化学産業の環境設計指針として世界的に採用。E-ファクター・原子効率などの定量指標を生んだ。",
        "subfield": "化学",
        "school_of_thought": "環境化学",
        "era_start": 1998,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Green_chemistry",
        "mathematical_formulation": r"E\text{-factor} = \frac{\text{waste (kg)}}{\text{product (kg)}},\quad \text{AE} = \frac{M_{\text{product}}}{\sum M_{\text{reactants}}}\times100\%",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "クリックケミストリー",
        "name_en": "Click Chemistry",
        "name_original": None,
        "definition": "シャープレスが2001年に提唱した「迅速・高収率・高選択的・副産物最小」の有機合成原則。アジド＝アルキン環化付加（CuAAC・SPAAC）が代表反応。2022年ノーベル賞。",
        "impact_summary": "バイオコンジュゲーション・化学生物学・材料機能化・薬物送達系の構築に革命的ツールを提供。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学",
        "era_start": 2001,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Click_chemistry",
        "mathematical_formulation": r"R-N_3 + R'-C\equiv CH \xrightarrow{Cu(I)} \text{triazole},\quad k_{\text{CuAAC}}\sim 10^1\text{–}10^2\,\text{M}^{-1}\text{s}^{-1}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "生体直交化学",
        "name_en": "Bioorthogonal Chemistry",
        "name_original": None,
        "definition": "細胞・生体内で非天然の化学反応を生体分子を傷つけずに行う技術。テトラジン-ノルボルネン逆電子要求Diels-Alder反応が代表。バーロジーらが開発。2022年ノーベル賞。",
        "impact_summary": "生細胞内の分子標識・薬物送達の時空間制御・プロテオミクスの新手法として急成長。",
        "subfield": "化学",
        "school_of_thought": "化学生物学",
        "era_start": 2003,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Bioorthogonal_chemistry",
        "mathematical_formulation": r"k_2(\text{IEDDA Tz-TCO}) \sim 10^4\text{–}10^6\,\text{M}^{-1}\text{s}^{-1}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "ロタキサンとカテナン（機械的結合分子）",
        "name_en": "Rotaxane and Catenane",
        "name_original": None,
        "definition": "化学結合でなく機械的絡み合い（軸通過・環貫通）で構成される分子マシン構成要素。ストッダート・フェランガ・サヴァージュが2016年ノーベル賞。",
        "impact_summary": "分子シャトル・分子スイッチ・分子モーター・薬物放出トリガーなど分子マシン設計の基本ビルディングブロック。",
        "subfield": "化学",
        "school_of_thought": "超分子化学",
        "era_start": 1991,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Rotaxane",
        "mathematical_formulation": r"\Delta G_{\text{switch}} = -RT\ln K_{AB},\quad K_{AB} = [A]/[B] = e^{-\Delta G/RT}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "フォトクロミズム",
        "name_en": "Photochromism",
        "name_original": None,
        "definition": "光照射により可逆的に構造・色が変化する分子変換現象。アゾベンゼン（トランス→シス）・ジアリールエテン・スピロピランなどが代表。",
        "impact_summary": "光スイッチ・光記録・スマートガラス・光制御薬物送達の機能材料として応用。",
        "subfield": "化学",
        "school_of_thought": "光化学",
        "era_start": 1899,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Photochromism",
        "mathematical_formulation": r"A \xrightarrow{h\nu_1} B,\quad B \xrightarrow{h\nu_2 \text{ or }\Delta} A",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "カーボンナノチューブの化学",
        "name_en": "Carbon Nanotube Chemistry",
        "name_original": "CNT",
        "definition": "グラフェンシートを筒状に巻いた1次元炭素ナノ構造体。単層（SWCNT）と多層（MWCNT）がある。飯島澄男が1991年に電子顕微鏡で観察。",
        "impact_summary": "高強度繊維・FET電子デバイス・ナノ薬物送達・複合材料・エネルギー貯蔵の材料として研究が継続。",
        "subfield": "化学",
        "school_of_thought": "ナノ化学",
        "era_start": 1991,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Carbon_nanotube",
        "mathematical_formulation": r"E_g \approx \frac{0.9}{d}\,\text{eV}\,(n,m)\text{ chiral vector},\quad d = \frac{a}{\pi}\sqrt{n^2+nm+m^2}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "二次元材料化学（MoS2・h-BN）",
        "name_en": "2D Materials Beyond Graphene",
        "name_original": None,
        "definition": "グラフェン以外の二硫化モリブデン（MoS2）・六方晶窒化ホウ素（h-BN）・黒リンなど遷移金属ダイカルコゲニドを含む2次元材料群の化学。",
        "impact_summary": "半導体（MoS2）・絶縁体（h-BN）・強磁性体など多様な電子特性が1原子層で実現し、ヘテロ積層で新機能が生まれる。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 2010,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Transition_metal_dichalcogenide_monolayers",
        "mathematical_formulation": r"E_g(\text{MoS}_2 \text{ monolayer}) = 1.8\,\text{eV (direct)},\quad E_g(\text{bulk}) = 1.2\,\text{eV (indirect)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "ポストゲノム代謝物解析（メタボロミクス）",
        "name_en": "Metabolomics",
        "name_original": None,
        "definition": "細胞・組織・生体液中の全代謝物（分子量＜1500）を網羅的に同定・定量するシステム解析。NMR・MS・クロマトグラフィーを組み合わせる。",
        "impact_summary": "糖尿病・がん代謝・腸内細菌-宿主代謝相互作用の解明。精密医療のバイオマーカー発見に貢献。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 1999,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Metabolomics",
        "mathematical_formulation": r"\text{Flux: }v = \frac{d[\text{metabolite}]}{dt},\quad \text{FBA: }\max c^Tv \text{ s.t. }Sv=0",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "合成生物学の化学的基盤",
        "name_en": "Chemical Biology of Synthetic Biology",
        "name_original": None,
        "definition": "人工的に設計した遺伝子回路・代謝経路・非天然アミノ酸を生細胞に実装する分野の化学的側面。PURE系・無細胞合成系も含む。",
        "impact_summary": "工業用化学品・バイオ医薬品・細胞内センサーの細胞工場化、非天然核酸・タンパク質の設計に展開。",
        "subfield": "化学",
        "school_of_thought": "化学生物学",
        "era_start": 2000,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Chemical_biology",
        "mathematical_formulation": r"\text{Genetic circuit: }\frac{d[P]}{dt} = \alpha\frac{[TF]^n}{K^n+[TF]^n} - \delta[P]",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "プロテオミクス・ショットガン法",
        "name_en": "Shotgun Proteomics",
        "name_original": None,
        "definition": "タンパク質混合物をプロテアーゼで消化後、LC-MS/MSで網羅的ペプチド同定・定量を行う大規模タンパク質解析法。",
        "impact_summary": "細胞・組織のタンパク質発現プロファイル・翻訳後修飾・タンパク質間相互作用の大規模解析を実現。疾患バイオマーカー探索に貢献。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 2001,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Shotgun_proteomics",
        "mathematical_formulation": r"\text{SEQUEST score: }Sp = \frac{\sum_i I_i \cdot y_i}{\sum_j I_j},\quad XCorr > 2.5 \text{ (confident)}",
        "verification_status": "url_present",
        "data_completeness": 82,
    },
    {
        "name_ja": "電気化学インピーダンス分光法",
        "name_en": "Electrochemical Impedance Spectroscopy",
        "name_original": "EIS",
        "definition": "電気化学系に異なる周波数の小振幅交流電圧を印加し、各周波数でのインピーダンス（Z'＋jZ''）を測定して界面反応・イオン輸送・腐食を解析。",
        "impact_summary": "電池内部抵抗・固体電解質界面（SEI）解析・腐食速度・燃料電池性能診断の標準手法。",
        "subfield": "化学",
        "school_of_thought": "電気化学",
        "era_start": 1975,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Electrochemical_impedance_spectroscopy",
        "mathematical_formulation": r"Z(\omega) = Z'(\omega)+jZ''(\omega),\quad \text{Nyquist plot: }-Z'' \text{ vs }Z'",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "原子層堆積（ALD）",
        "name_en": "Atomic Layer Deposition",
        "name_original": "ALD",
        "definition": "前駆体を交互に自己制限反応で供給し、原子1層ずつ精密に薄膜を成長させる気相堆積法。アルミナ・HfO2・Pt・ZnOなど多様。",
        "impact_summary": "FinFET・EUVリソグラフィー・DRAM・バッテリー電極の高誘電率・高選択性薄膜形成の標準プロセス。",
        "subfield": "化学",
        "school_of_thought": "表面化学",
        "era_start": 1974,
        "culture_region": "Europe_Northern",
        "source_url": "https://en.wikipedia.org/wiki/Atomic_layer_deposition",
        "mathematical_formulation": r"\text{GPC (growth per cycle)} = \Delta t/\text{cycle},\quad t \approx 0.1\text{–}1\,\text{\AA/cycle}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "超臨界流体と超臨界抽出",
        "name_en": "Supercritical Fluid",
        "name_original": None,
        "definition": "臨界点以上の温度・圧力で液体と気体の区別がなくなる超臨界状態の流体（SC-CO2など）。溶媒特性をチューナブルに制御できる。",
        "impact_summary": "カフェイン除去・医薬品有効成分抽出・コーティング乾燥（エアロゲル製造）・環境調和型溶媒として実用化。",
        "subfield": "化学",
        "school_of_thought": "物理化学",
        "era_start": 1869,
        "culture_region": "Europe_Western",
        "source_url": "https://en.wikipedia.org/wiki/Supercritical_fluid",
        "mathematical_formulation": r"T_c = \frac{8a}{27Rb},\quad P_c = \frac{a}{27b^2} \text{ (van der Waals)}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "高エントロピー合金",
        "name_en": "High-Entropy Alloy",
        "name_original": "HEA",
        "definition": "5種以上の主要元素を等モル量または準等モル量含み、高い配置エントロピーで安定化された多主成分合金。イエとツァイが2004年に独立提唱。",
        "impact_summary": "高強度・耐放射線・耐食性・低温靭性など従来合金を超える特性を示し、原子力・航空・医療デバイスに応用。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 2004,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/High-entropy_alloy",
        "mathematical_formulation": r"S_{\text{conf}} = -R\sum_{i=1}^n x_i\ln x_i \geq 1.5R \Rightarrow \text{HEA}",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "光電子分光（XPS/UPS）",
        "name_en": "X-ray Photoelectron Spectroscopy",
        "name_original": "XPS / ESCA",
        "definition": "X線・紫外線照射で放出される光電子の運動エネルギー分布から元素組成・酸化状態・化学結合を表面分析する手法。ジーグバーンが1960年代に開発。",
        "impact_summary": "触媒表面・半導体プロセス・腐食・バイオ材料の表面化学状態の非破壊定量分析の標準技術。1981年ノーベル賞。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1964,
        "culture_region": "Europe_Northern",
        "source_url": "https://en.wikipedia.org/wiki/X-ray_photoelectron_spectroscopy",
        "mathematical_formulation": r"E_B = h\nu - E_k - \phi,\quad E_k = E_B(\text{Cu }2p_{3/2}) = 932.6\,\text{eV}",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "中性子散乱による構造解析",
        "name_en": "Neutron Scattering",
        "name_original": None,
        "definition": "中性子を物質に照射して弾性・非弾性散乱を測定し、原子・分子の位置・振動・磁気構造を解析する手法。水素検出・磁性体研究に独自の強みを持つ。",
        "impact_summary": "ポリマー・タンパク質の水素配置・磁気秩序・触媒反応中間体の解析。X線と相補的な構造解析ツール。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1946,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Neutron_scattering",
        "mathematical_formulation": r"S(Q,\omega) = \frac{1}{2\pi\hbar}\int dt\,e^{i\omega t}I(Q,t),\quad I(Q,t) = \langle\rho(Q,0)\rho^*(-Q,t)\rangle",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "放射光X線解析（シンクロトロン）",
        "name_en": "Synchrotron X-ray Analysis",
        "name_original": None,
        "definition": "電子加速器（シンクロトロン）が発生する高輝度・波長可変X線を使い、タンパク質結晶・ナノ材料・触媒のその場観察・高分解能構造解析を行う。",
        "impact_summary": "創薬・バッテリー・半導体・文化財分析まで幅広い産業・研究応用を支える20世紀後半最大の分析インフラ。",
        "subfield": "化学",
        "school_of_thought": "分析化学",
        "era_start": 1980,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Synchrotron_radiation",
        "mathematical_formulation": r"B = \frac{\alpha\gamma^4}{4\pi^2 R^2},\quad \lambda_c = \frac{4\pi R}{3\gamma^3}\text{ (critical wavelength)}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "フリーラジカル重合",
        "name_en": "Free Radical Polymerization",
        "name_original": None,
        "definition": "開始剤由来のラジカルによってモノマーが連鎖的に重合し高分子を与える反応。ポリスチレン・PMMA・PVCなどの主要工業プロセス。",
        "impact_summary": "世界の高分子生産量の多くを占める工業的に最も重要な重合反応。ATRPやRAFT重合の発展で精密制御が可能に。",
        "subfield": "化学",
        "school_of_thought": "高分子化学",
        "era_start": 1937,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Radical_polymerization",
        "mathematical_formulation": r"R_p = k_p[M][M\cdot],\quad \overline{X}_n = \frac{R_p}{R_t^{1/2}} \propto [M][I]^{-1/2}",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "生命起源の化学—RNA世界仮説",
        "name_en": "RNA World Hypothesis",
        "name_original": None,
        "definition": "生命が最初に登場したとき、RNAが遺伝情報保持と触媒機能（リボザイム）の両方を担ったとする仮説。チェックとオルトマンのリボザイム発見（1989年ノーベル賞）が支持根拠。",
        "impact_summary": "生命起源研究の現代的中心仮説。リボザイムの酵素的進化・原始ゲノム・リボソームの化学進化を統一的に説明。",
        "subfield": "化学",
        "school_of_thought": "生化学",
        "era_start": 1986,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/RNA_world",
        "mathematical_formulation": r"\text{Ribozyme: }k_{\text{cat}} = 1\text{–}10^3\,\text{min}^{-1}\ll\text{protein enzyme }(10^3\text{–}10^6\,\text{min}^{-1})",
        "verification_status": "url_present",
        "data_completeness": 88,
    },
    {
        "name_ja": "分子認識とホストゲスト化学",
        "name_en": "Host-Guest Chemistry",
        "name_original": None,
        "definition": "冠状エーテル・シクロデキストリン・カリクサレン・クリプタンドなどホスト分子がゲスト分子を選択的に包接する超分子相互作用。クラム・レーン・ペダーセンが1987年ノーベル賞。",
        "impact_summary": "分子認識・センサー・薬物封入・分子機械・テンプレート合成の概念的・実用的基盤。",
        "subfield": "化学",
        "school_of_thought": "超分子化学",
        "era_start": 1967,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Host%E2%80%93guest_chemistry",
        "mathematical_formulation": r"K_a = \frac{[\text{HG}]}{[\text{H}][\text{G}]},\quad \Delta G^\circ = -RT\ln K_a",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
    {
        "name_ja": "コンビナトリアル化学とハイスループットスクリーニング",
        "name_en": "Combinatorial Chemistry and HTS",
        "name_original": None,
        "definition": "化合物ライブラリを組み合わせ合成し、高速ロボット測定（HTS）で生物活性・物性を網羅的スクリーニングする手法。1990年代に創薬で爆発的に普及。",
        "impact_summary": "リード化合物探索を従来の1000倍速化。失敗コスト低減とAI予測との融合で現代製薬の中核プロセスに。",
        "subfield": "化学",
        "school_of_thought": "医薬化学",
        "era_start": 1991,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Combinatorial_chemistry",
        "mathematical_formulation": r"N_{\text{library}} = \prod_{i=1}^k n_i,\quad Z' = 1 - \frac{3(\sigma_s+\sigma_c)}{|\mu_s-\mu_c|} \geq 0.5",
        "verification_status": "url_present",
        "data_completeness": 85,
    },
    {
        "name_ja": "電池化学—インターカレーション機構",
        "name_en": "Battery Intercalation Chemistry",
        "name_original": None,
        "definition": "リチウムイオンが正極（LiCoO2・LFP・NMC）・負極（グラファイト・シリコン）に可逆的に挿入・脱離する蓄電反応機構。グディナフらが1980年代に確立。",
        "impact_summary": "モバイル機器・EV・グリッド蓄電のエネルギー密度と寿命を決定する化学。グディナフ・ウィッティンガム・吉野彰の2019年ノーベル賞。",
        "subfield": "化学",
        "school_of_thought": "材料化学",
        "era_start": 1979,
        "culture_region": "Americas_North",
        "source_url": "https://en.wikipedia.org/wiki/Intercalation_(chemistry)",
        "mathematical_formulation": r"\text{LiCoO}_2 \rightleftharpoons \text{Li}_{1-x}\text{CoO}_2 + x\text{Li}^+ + xe^-,\quad E = E^\circ - \frac{RT}{nF}\ln Q",
        "verification_status": "url_present",
        "data_completeness": 90,
    },
]


def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            uid, c["name_ja"], c["name_en"], c.get("name_original"),
            c["definition"], c["impact_summary"], c["subfield"],
            c["school_of_thought"], c["era_start"], c["culture_region"],
            c["source_url"], c.get("mathematical_formulation"),
            c.get("verification_status", "url_present"), "active",
            c.get("data_completeness", 85), now, now,
        ))
        inserted += 1
    conn.commit()
    return inserted


if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    batch_size = 50
    total = 0
    for i in range(0, len(CONCEPTS), batch_size):
        batch = CONCEPTS[i:i+batch_size]
        n = insert_batch(conn, batch)
        total += n
        print(f"  Batch {i//batch_size+1}: {n} inserted (running total: {total})")
    conn.close()
    conn2 = sqlite3.connect(DB_PATH)
    count = conn2.execute("SELECT COUNT(*) FROM natural_discovery").fetchone()[0]
    conn2.close()
    print(f"\nBatch5 chemistry2: {total} concepts inserted")
    print(f"Total in table: {count}")
