"""
DUA Wave A2 Batch 12 — Chemistry supplement (~60 concepts, subfield '化学')
Target: close gap from ~282 to ~579 (+297)
"""
import sqlite3
import uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

BATCH1 = [
    {
        "name_ja": "触媒作用の理論",
        "name_en": "Catalysis Theory",
        "definition": "反応物の活性化エネルギーを下げることで化学反応速度を増大させる触媒の作用機序を説明する理論。均一系・不均一系触媒の区別、Langmuir-Hinshelwood機構などを包含する。",
        "impact_summary": "工業化学の中核。ハーバー・ボッシュ法、接触式硫酸製造、石油精製において不可欠。ノーベル化学賞(Sabatier 1912, Haber 1918, Langmuir 1932)を生んだ分野。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1835,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/catalysis/",
        "mathematical_formulation": r"r = k \frac{K_A p_A \cdot K_B p_B}{(1+K_A p_A+K_B p_B)^2}",
        "data_completeness": 90,
    },
    {
        "name_ja": "ハーバー・ボッシュ法",
        "name_en": "Haber-Bosch Process",
        "definition": "窒素と水素から高温高圧・鉄触媒下でアンモニアを合成する工業プロセス。大気中窒素の固定を実現し、農業用肥料生産を革命的に変えた。",
        "impact_summary": "現代農業の基盤。世界人口の約半数が本プロセス由来の肥料に依存。Fritz Haber(1918 Nobel)・Carl Bosch(1931 Nobel)が開発。年間1.8億トンのアンモニアを生産。",
        "subfield": "化学",
        "school_of_thought": "Industrial Chemistry",
        "era_start": 1909,
        "culture_region": "Europe_Western",
        "source_url": "https://www.chemistryworld.com/features/the-haber-bosch-process/3007917.article",
        "mathematical_formulation": r"N_2 + 3H_2 \rightleftharpoons 2NH_3 \quad \Delta H = -92\,\text{kJ/mol}",
        "data_completeness": 92,
    },
    {
        "name_ja": "配位化学",
        "name_en": "Coordination Chemistry",
        "definition": "金属イオンが配位子（電子対供与体）と結合して形成する錯体（配位化合物）の構造・反応性・性質を扱う化学の分野。Wernerの配位理論が基礎。",
        "impact_summary": "触媒設計、医薬品（シスプラチン）、MRI造影剤、色素・顔料に応用。Alfred Werner(1913 Nobel)、後にWilkinson(1973 Nobel)が有機金属錯体を開拓。",
        "subfield": "化学",
        "school_of_thought": "Inorganic Chemistry",
        "era_start": 1893,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/C01245",
        "mathematical_formulation": r"[M(L)_n]^{z+} \quad \Delta_o = \text{crystal field splitting}",
        "data_completeness": 88,
    },
    {
        "name_ja": "放射性同位体と放射性崩壊",
        "name_en": "Radioactive Isotopes and Decay",
        "definition": "原子核が自発的に放射線（α線・β線・γ線）を放出して別の核種に変換される現象。半減期、崩壊系列、核反応の基本法則を包含する。",
        "impact_summary": "放射性炭素年代測定(Libby 1960 Nobel)、核医学診断・治療、原子力発電の基盤。Marie Curieによるラジウム・ポロニウム発見(1898)が起点。",
        "subfield": "化学",
        "school_of_thought": "Nuclear Chemistry",
        "era_start": 1898,
        "culture_region": "Europe_Eastern",
        "source_url": "https://www.iaea.org/topics/nuclear-physics",
        "mathematical_formulation": r"N(t) = N_0 e^{-\lambda t}, \quad t_{1/2} = \frac{\ln 2}{\lambda}",
        "data_completeness": 90,
    },
    {
        "name_ja": "電気化学的酸化還元",
        "name_en": "Electrochemical Redox",
        "definition": "電子の移動を伴う酸化還元反応を電気化学的に制御・測定する体系。ネルンストの式、標準電極電位、ファラデーの法則が基本原理。",
        "impact_summary": "電池・燃料電池・電解の理論的基盤。リチウムイオン電池(Goodenough 2019 Nobel)、水電解水素製造、電気めっき産業に直結。",
        "subfield": "化学",
        "school_of_thought": "Electrochemistry",
        "era_start": 1834,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/E01975",
        "mathematical_formulation": r"E = E^\circ - \frac{RT}{nF}\ln Q",
        "data_completeness": 90,
    },
    {
        "name_ja": "コロイドと界面化学",
        "name_en": "Colloid and Interface Chemistry",
        "definition": "サイズ1–1000 nmの粒子が分散媒中に分散したコロイド系、および界面（気液・液液・固液）における現象を扱う化学分野。",
        "impact_summary": "食品科学、塗料、化粧品、医薬品ナノ粒子、洗浄剤の基礎。The Svedberg(1926 Nobel)が超遠心分離でコロイド研究を確立。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1869,
        "culture_region": "Europe_Western",
        "source_url": "https://www.iupac.org/what-we-do/iupac-projects/?project=2016-011-2-100",
        "mathematical_formulation": r"\frac{\partial c}{\partial t} = D\nabla^2 c - \mu \nabla \cdot (c \mathbf{F})",
        "data_completeness": 85,
    },
    {
        "name_ja": "ポリマー化学",
        "name_en": "Polymer Chemistry",
        "definition": "高分子（ポリマー）の合成・構造・性質・応用を扱う化学。付加重合・縮合重合・リビング重合など多様な重合反応機構を含む。",
        "impact_summary": "プラスチック・ゴム・繊維・接着剤など現代材料の基盤。Staudinger(1953 Nobel)が巨大分子概念を確立。Ziegler-Nattaによるポリオレフィン合成(1963 Nobel)が工業化を加速。",
        "subfield": "化学",
        "school_of_thought": "Materials Chemistry",
        "era_start": 1920,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/polymer-chemistry/",
        "mathematical_formulation": r"M_n = \sum_i N_i M_i / \sum_i N_i, \quad M_w = \sum_i N_i M_i^2 / \sum_i N_i M_i",
        "data_completeness": 90,
    },
    {
        "name_ja": "緑色化学",
        "name_en": "Green Chemistry",
        "definition": "化学物質・プロセスの設計において廃棄物発生・有害物質使用・エネルギー消費を最小化する原則の体系。Anastas & Warner(1998)の12原則が基本枠組み。",
        "impact_summary": "持続可能な化学生産への転換。原子効率・廃棄物最少化・再生可能原料・触媒使用の最大化を促進。医薬品・農薬・材料の環境負荷低減に直結。",
        "subfield": "化学",
        "school_of_thought": "Sustainable Chemistry",
        "era_start": 1991,
        "culture_region": "North_America",
        "source_url": "https://www.acs.org/greenchemistry/what-is-green-chemistry.html",
        "mathematical_formulation": r"\text{Atom Economy} = \frac{M_{\text{product}}}{M_{\text{all reactants}}} \times 100\%",
        "data_completeness": 88,
    },
    {
        "name_ja": "固体状態化学",
        "name_en": "Solid-State Chemistry",
        "definition": "結晶格子・アモルファス固体など固相の合成・構造・物性変化を扱う化学分野。格子エネルギー、欠陥化学、イオン伝導が主要テーマ。",
        "impact_summary": "電池電極材料・超伝導体・半導体・セラミックスの基礎。リチウムイオン電池正極材(LiCoO₂)の設計はSolid-State Chemistryの成果。",
        "subfield": "化学",
        "school_of_thought": "Inorganic Chemistry",
        "era_start": 1900,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/dalton-transactions/",
        "mathematical_formulation": r"U = -\frac{N_A M z^+ z^- e^2}{4\pi\epsilon_0 r_0}\left(1-\frac{1}{n}\right)",
        "data_completeness": 87,
    },
    {
        "name_ja": "イスラーム化学（錬金術からの系譜）",
        "name_en": "Islamic Alchemy and Proto-Chemistry",
        "definition": "8–13世紀のイスラーム世界で発展した蒸留・昇華・結晶化などの実験技術と物質変換理論。Jabir ibn Hayyān（ジャービル）を中心に発展し、ヨーロッパ近代化学の先駆けとなった。",
        "impact_summary": "硫酸・硝酸・塩酸の発見、蒸留器・アランビックの発明、系統的実験記録。Arabic語起源の化学用語（alkali, alcohol, aldehyde等）が現代に残る。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": 776,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://www.encyclopedia.com/science/encyclopedias-almanacs-transcripts-and-maps/jabir-ibn-hayyan",
        "data_completeness": 85,
    },
    {
        "name_ja": "インド化学の伝統（ラサシャーストラ）",
        "name_en": "Indian Rasashastra and Medicinal Chemistry",
        "definition": "古代・中世インドで発展した金属・鉱物・植物の精製・変換・薬用利用体系。Nāgārjuna（2–3世紀）らが水銀精製・合金製造・薬物学を体系化。Ayurvedaと結合。",
        "impact_summary": "亜鉛の製錬技術（Zawar遺跡、9世紀）、水銀化合物の医薬利用、インド伝統医学の化学的基盤。現代の水銀毒性研究・伝統薬物化学研究の遡上に必須。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": 200,
        "culture_region": "South_Asia",
        "source_url": "https://www.academia.edu/37023410/Rasashastra_the_ancient_art_of_Indian_chemistry",
        "data_completeness": 82,
    },
    {
        "name_ja": "中国本草学と化学",
        "name_en": "Chinese Bencao and Phytochemistry",
        "definition": "『神農本草経』（1世紀）から李時珍『本草綱目』（1596）に至る中国本草学の系譜において発展した薬物の分類・精製・成分同定。金丹術（煉丹術）も含む。",
        "impact_summary": "火薬（硝酸カリウム・木炭・硫黄）の発明（唐代）、砒素化合物・水銀の薬用利用、植物アルカロイドの経験的同定。現代の天然物化学・中薬研究の起点。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": 100,
        "culture_region": "East_Asia",
        "source_url": "https://www.sciencedirect.com/science/article/pii/S0367326X1300231X",
        "data_completeness": 83,
    },
    {
        "name_ja": "燃焼化学とフロジストン説の克服",
        "name_en": "Combustion Chemistry and Overthrow of Phlogiston",
        "definition": "酸素によって燃焼を説明するLavoisierの化学革命（1770–1790年代）。質量保存の法則の確立とフロジストン説の否定が中核。",
        "impact_summary": "近代化学の誕生点。元素の定義・命名法の改革・定量的化学分析の基礎を確立（Lavoisier 1789「化学要論」）。燃焼工学・エンジン設計の理論的起源。",
        "subfield": "化学",
        "school_of_thought": "Analytical Chemistry",
        "era_start": 1772,
        "culture_region": "Europe_Western",
        "source_url": "https://www.chemheritage.org/historical-profile/antoine-lavoisier",
        "mathematical_formulation": r"m_{\text{reactants}} = m_{\text{products}} \quad \text{(Law of Conservation of Mass)}",
        "data_completeness": 90,
    },
    {
        "name_ja": "化学熱力学",
        "name_en": "Chemical Thermodynamics",
        "definition": "化学反応における熱・仕事・エントロピー・ギブズ自由エネルギーの関係を扱う。自発変化の方向・平衡定数・反応エンタルピー・化学ポテンシャルを包含。",
        "impact_summary": "反応可能性・平衡設計の基礎。化学工業における反応条件最適化、熱機関設計、相変化制御に必須。Hess(1840)・van't Hoff(1901 Nobel)・Gibbs(1870s)が基礎構築。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1840,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/G02629",
        "mathematical_formulation": r"\Delta G = \Delta H - T\Delta S, \quad K_{eq} = e^{-\Delta G^\circ / RT}",
        "data_completeness": 92,
    },
    {
        "name_ja": "光化学反応",
        "name_en": "Photochemistry",
        "definition": "光（紫外線・可視光）の吸収によって引き起こされる化学反応を扱う分野。励起状態、蛍光・リン光、光合成、オゾン層光化学が主要テーマ。",
        "impact_summary": "太陽光発電（光触媒TiO₂）、医薬品光線力学療法、大気化学（成層圏オゾン破壊）、フォトリソグラフィーの基礎。Ciamician(1912)が先駆。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1912,
        "culture_region": "Europe_Western",
        "source_url": "https://www.iupac.org/projects/project-details/?project_nr=2016-011-2-100",
        "mathematical_formulation": r"A = \varepsilon c l \quad \text{(Beer-Lambert)}, \quad \Phi = \frac{n_{\text{product}}}{n_{\text{absorbed photons}}}",
        "data_completeness": 87,
    },
]

BATCH2 = [
    {
        "name_ja": "質量分析法",
        "name_en": "Mass Spectrometry",
        "definition": "分子を気化・イオン化し質量電荷比(m/z)で分離・検出する分析手法。ESI、MALDI、TOFなど多様なイオン化・分離法が存在する。",
        "impact_summary": "プロテオミクス・代謝物解析・環境分析・同位体地球化学の基盤ツール。Thomson(1906 Nobel, 先駆)・Aston(1922 Nobel)・Fenn・田中耕一(East_Asia, 2002 Nobel)がESI/MALDIを開拓。",
        "subfield": "化学",
        "school_of_thought": "Analytical Chemistry",
        "era_start": 1913,
        "culture_region": "East_Asia",
        "source_url": "https://www.asms.org/about-asms/mass-spectrometry",
        "mathematical_formulation": r"\frac{m}{z} = \frac{2V}{v^2}, \quad \text{TOF: } t = L\sqrt{\frac{m}{2zeV}}",
        "data_completeness": 90,
    },
    {
        "name_ja": "核磁気共鳴分光法",
        "name_en": "Nuclear Magnetic Resonance Spectroscopy",
        "definition": "磁場中に置いた原子核（主に¹H・¹³C）が電磁波を吸収・放出する現象を利用した構造解析手法。化学シフト・カップリング定数が分子構造情報を与える。",
        "impact_summary": "有機化合物・タンパク質の立体構造決定に不可欠。Bloch・Purcell(1952 Nobel)が発見、Ernst(1991 Nobel)・Wüthrich(2002 Nobel)が多次元NMRを開発。MRIの理論的基盤。",
        "subfield": "化学",
        "school_of_thought": "Analytical Chemistry",
        "era_start": 1946,
        "culture_region": "North_America",
        "source_url": "https://www.bruker.com/en/products/mr/nmr.html",
        "mathematical_formulation": r"\nu_L = \frac{\gamma B_0}{2\pi}, \quad \delta = \frac{\nu_{\text{sample}} - \nu_{\text{ref}}}{\nu_{\text{ref}}} \times 10^6 \, \text{ppm}",
        "data_completeness": 91,
    },
    {
        "name_ja": "クロマトグラフィー",
        "name_en": "Chromatography",
        "definition": "混合物を移動相と固定相の相互作用の差によって分離する手法の総称。ガスクロ(GC)・液体クロ(HPLC)・薄層クロ(TLC)・サイズ排除クロが主要種別。",
        "impact_summary": "医薬品・食品・環境分析の必須ツール。Tswett(1906)が植物色素分離で発明。Martin・Synge(1952 Nobel)がペーパークロマトグラフィー理論を確立。現代分析化学の中核。",
        "subfield": "化学",
        "school_of_thought": "Analytical Chemistry",
        "era_start": 1903,
        "culture_region": "Europe_Eastern",
        "source_url": "https://www.chromsoc.com/history-of-chromatography/",
        "mathematical_formulation": r"N = 5.54\left(\frac{t_R}{w_{1/2}}\right)^2, \quad R_s = \frac{2(t_{R2}-t_{R1})}{w_1+w_2}",
        "data_completeness": 88,
    },
    {
        "name_ja": "分子間力",
        "name_en": "Intermolecular Forces",
        "definition": "分子間に働くファンデルワールス力（分散力・誘起双極子・双極子間）・水素結合・イオン-双極子相互作用などの非共有結合性引力・斥力の総称。",
        "impact_summary": "沸点・溶解度・タンパク質折りたたみ・医薬品-受容体結合の理論的基礎。London(1937)の分散力理論、Watson-Crick(1953)の塩基対水素結合が代表的成果。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1873,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/I03040",
        "mathematical_formulation": r"V_{\text{LJ}}(r) = 4\varepsilon\left[\left(\frac{\sigma}{r}\right)^{12}-\left(\frac{\sigma}{r}\right)^6\right]",
        "data_completeness": 89,
    },
    {
        "name_ja": "有機合成計画（レトロシンセシス）",
        "name_en": "Retrosynthetic Analysis",
        "definition": "複雑な目標有機分子を単純な出発物質から合成するルートを逆向きに解析する方法論（E.J. Corey, 1967）。合成等価体・官能基変換・骨格切断が主要操作。",
        "impact_summary": "医薬品・天然物の全合成戦略の基礎。コーリーはこれにより1990年ノーベル化学賞を受賞。コンピュータ支援合成計画(CASP)・AI駆動合成計画の理論的基盤。",
        "subfield": "化学",
        "school_of_thought": "Organic Chemistry",
        "era_start": 1967,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/1990/corey/lecture/",
        "data_completeness": 90,
    },
    {
        "name_ja": "超分子化学",
        "name_en": "Supramolecular Chemistry",
        "definition": "共有結合を超えた非共有結合（水素結合・疎水性効果・π-π相互作用等）によって構築される高次分子集合体（ホスト-ゲスト錯体・自己集合体）の化学。",
        "impact_summary": "人工イオンチャネル・分子マシン・薬物内包ナノカプセルへ応用。Pedersen・Cram・Lehn(1987 Nobel)がクラウンエーテル・クリプタンドで確立。",
        "subfield": "化学",
        "school_of_thought": "Organic Chemistry",
        "era_start": 1967,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/1987/summary/",
        "mathematical_formulation": r"K_a = \frac{[HG]}{[H][G]}, \quad \Delta G = -RT\ln K_a",
        "data_completeness": 88,
    },
    {
        "name_ja": "錯体触媒による選択的反応",
        "name_en": "Transition Metal Catalysis",
        "definition": "パラジウム・ルテニウム・ロジウム等の遷移金属錯体が触媒として機能する有機反応群。カップリング反応・オレフィンメタセシス・不斉水素化が代表例。",
        "impact_summary": "Heck・根岸・鈴木カップリング(East_Asia, 2010 Nobel)、Grubbs・Schrock・Chauvin メタセシス(2005 Nobel)、Knowles・野依・Sharplessによる不斉触媒(East_Asia, 2001 Nobel)。医薬品合成に革命。",
        "subfield": "化学",
        "school_of_thought": "Organic Chemistry",
        "era_start": 1972,
        "culture_region": "East_Asia",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2010/summary/",
        "data_completeness": 92,
    },
    {
        "name_ja": "タンパク質工学",
        "name_en": "Protein Engineering",
        "definition": "目的の機能・安定性・特異性を持つタンパク質を設計・改変・進化させる化学・生物工学分野。定向進化・合理的設計・計算設計が主要アプローチ。",
        "impact_summary": "工業酵素・抗体医薬・バイオ燃料触媒の開発基盤。Arnold(定向進化, 2018 Nobel)・Winter・Smith(ファージディスプレイ, 2018 Nobel)が確立。AlphaFold2(2021)が構造予測を変革。",
        "subfield": "化学",
        "school_of_thought": "Biochemistry",
        "era_start": 1984,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2018/summary/",
        "data_completeness": 90,
    },
    {
        "name_ja": "カーボンナノチューブとフラーレン",
        "name_en": "Carbon Nanotubes and Fullerenes",
        "definition": "炭素原子のみからなるナノスケール構造体。フラーレン（C₆₀球状）は1985年Kroto・Curl・Smalleyが発見（1996 Nobel）、カーボンナノチューブは飯島澄男（East_Asia, 1991）が発見。",
        "impact_summary": "ナノエレクトロニクス・複合材料・薬物送達・センサーへの応用展開。SWCNTの電子的性質（金属性/半導体性）はカーボン素子の可能性を開く。",
        "subfield": "化学",
        "school_of_thought": "Materials Chemistry",
        "era_start": 1985,
        "culture_region": "East_Asia",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/1996/summary/",
        "data_completeness": 90,
    },
    {
        "name_ja": "計算化学",
        "name_en": "Computational Chemistry",
        "definition": "量子力学・分子力学・分子動力学シミュレーションを用いて分子の構造・反応・性質を計算機上で予測・解析する分野。DFT・ab initio・半経験的法が主要手法。",
        "impact_summary": "医薬品設計（CADD）・触媒設計・材料探索の加速ツール。Kohn・Pople(1998 Nobel, DFT/計算化学)・Karplus・Levitt・Warshel(2013 Nobel, 多段階シミュレーション)が確立。",
        "subfield": "化学",
        "school_of_thought": "Theoretical Chemistry",
        "era_start": 1930,
        "culture_region": "North_America",
        "source_url": "https://www.nobelprize.org/prizes/chemistry/2013/summary/",
        "mathematical_formulation": r"E[\rho] = T[\rho] + V_{ne}[\rho] + J[\rho] + E_{xc}[\rho]",
        "data_completeness": 90,
    },
    {
        "name_ja": "農薬化学と作物保護化学",
        "name_en": "Agrochemistry and Crop Protection Chemistry",
        "definition": "害虫・病原菌・雑草から農作物を保護するための農薬（殺虫剤・殺菌剤・除草剤）の合成・作用機序・環境運命を研究する応用化学分野。",
        "impact_summary": "緑の革命（除草剤・農薬）が20世紀の食料増産を支えた。ただしDDT問題（Carson 1962「沈黙の春」）・ネオニコチノイドの生態影響から持続可能農薬化学へ転換中。",
        "subfield": "化学",
        "school_of_thought": "Applied Chemistry",
        "era_start": 1940,
        "culture_region": "North_America",
        "source_url": "https://www.acs.org/content/acs/en/pressroom/newsreleases/2012/agrochemical-science.html",
        "data_completeness": 85,
    },
    {
        "name_ja": "食品化学",
        "name_en": "Food Chemistry",
        "definition": "食品の成分（炭水化物・タンパク質・脂質・ビタミン・ミネラル・風味物質・食品添加物）の化学的性質と加工・保存・栄養価変化を研究する応用化学分野。",
        "impact_summary": "食品保存技術・栄養強化・アレルゲン除去・機能性食品開発の基礎。マイヤール反応（非酵素的褐変）・脂質酸化・タンパク質変性の理解が食品品質管理に直結。",
        "subfield": "化学",
        "school_of_thought": "Applied Chemistry",
        "era_start": 1847,
        "culture_region": "Europe_Western",
        "source_url": "https://www.ift.org/food-science-and-technology/food-chemistry",
        "data_completeness": 85,
    },
    {
        "name_ja": "医薬品化学（創薬化学）",
        "name_en": "Medicinal Chemistry and Drug Discovery",
        "definition": "生物活性を持つ医薬品候補化合物の設計・合成・最適化を行う化学分野。構造-活性相関（SAR）・バイオアベイラビリティ・薬物代謝（ADMET）が核心概念。",
        "impact_summary": "抗生物質・抗がん剤・抗ウイルス薬・精神薬などの開発基盤。ペニシリン(Fleming 1928)・スルファ剤・抗HIV薬・分子標的薬（イマチニブ）が代表例。",
        "subfield": "化学",
        "school_of_thought": "Organic Chemistry",
        "era_start": 1935,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/medicinal-chemistry/",
        "data_completeness": 88,
    },
    {
        "name_ja": "アフリカの冶金技術（伝統的な鉄製錬）",
        "name_en": "African Iron Smelting Traditions",
        "definition": "サハラ以南アフリカで独自に発展した木炭・鉄鉱石による製鉄技術（BC1400年頃〜）。一部地域では高温プロセス（前炉製鋼）がヨーロッパより先行していた可能性がある。",
        "impact_summary": "農具・武器の自給生産を可能にしアフリカ諸社会の経済基盤を形成。ルワンダ・タンザニアのHaya族の炭素鋼製造（BC200年）の証拠は非西洋冶金の先進性を示す。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": -1400,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://www.britannica.com/technology/iron-processing/Africa",
        "data_completeness": 80,
    },
    {
        "name_ja": "フローケミストリー（連続フロー合成）",
        "name_en": "Flow Chemistry",
        "definition": "管型反応器（マイクロリアクター・メゾリアクター）中で反応物を連続的に流しながら化学反応を実施する合成手法。バッチ合成に比べ混合・熱移動・安全性に優れる。",
        "impact_summary": "危険な中間体（ジアゾ化合物・有機アジド）の安全合成・医薬品連続製造への応用が急速拡大。AstraZeneca・ファイザー等製薬企業が採用。GMP連続生産の主流技術へ。",
        "subfield": "化学",
        "school_of_thought": "Process Chemistry",
        "era_start": 2000,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/reaction-chemistry-engineering/",
        "data_completeness": 87,
    },
]

BATCH3 = [
    {
        "name_ja": "化学結合理論（共有結合・イオン結合）",
        "name_en": "Chemical Bonding Theory",
        "definition": "原子間の電子共有（共有結合）・電子移動（イオン結合）・金属結合によって分子・結晶が形成されるメカニズムを記述する理論体系。Lewis構造・VB理論・MO理論が柱。",
        "impact_summary": "すべての化学反応・材料設計の基礎。Lewis(1916)・Pauling(1954 Nobel、電気陰性度・共鳴)・Hückel(芳香族性)が確立。現代の量子化学計算で精密化。",
        "subfield": "化学",
        "school_of_thought": "Theoretical Chemistry",
        "era_start": 1916,
        "culture_region": "North_America",
        "source_url": "https://goldbook.iupac.org/terms/view/C00988",
        "mathematical_formulation": r"\hat{H}\Psi = E\Psi, \quad E = \frac{\langle\Psi|\hat{H}|\Psi\rangle}{\langle\Psi|\Psi\rangle}",
        "data_completeness": 92,
    },
    {
        "name_ja": "同位体化学",
        "name_en": "Isotope Chemistry",
        "definition": "同じ元素でも中性子数が異なる同位体の化学的・物理的性質の差異（同位体効果）を利用した化学分析・トレーシング・年代測定の手法体系。",
        "impact_summary": "炭素14年代測定(Libby 1960 Nobel)・水素同位体(重水素)・安定同位体比分析（δ¹³C・δ¹⁸O）が古気候・生態・食品真正性検証に応用。原子力燃料濃縮にも重要。",
        "subfield": "化学",
        "school_of_thought": "Nuclear Chemistry",
        "era_start": 1913,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/I03321",
        "mathematical_formulation": r"\delta = \left(\frac{R_{\text{sample}}}{R_{\text{standard}}}-1\right)\times 1000\,\permil",
        "data_completeness": 88,
    },
    {
        "name_ja": "酵素反応速度論",
        "name_en": "Enzyme Kinetics",
        "definition": "酵素（生体触媒）の基質濃度・pH・温度依存的な反応速度を記述する理論。Michaelis-Menten式が基本、酵素阻害・アロステリック制御・マルチサブユニット酵素も包含。",
        "impact_summary": "医薬品設計（酵素阻害薬：ACE阻害薬・プロテアーゼ阻害薬）・バイオプロセス最適化の基盤。Michaelis・Menten(1913)・Lineweaver・Burk変換法が標準解析ツール。",
        "subfield": "化学",
        "school_of_thought": "Biochemistry",
        "era_start": 1913,
        "culture_region": "Europe_Western",
        "source_url": "https://www.ncbi.nlm.nih.gov/books/NBK22430/",
        "mathematical_formulation": r"v = \frac{V_{\max}[S]}{K_M + [S]}, \quad K_M = \frac{k_{-1}+k_2}{k_1}",
        "data_completeness": 91,
    },
    {
        "name_ja": "溶液化学と電解質",
        "name_en": "Solution Chemistry and Electrolytes",
        "definition": "溶質・溶媒の相互作用、溶液の束一的性質（沸点上昇・凝固点降下・浸透圧）、電解質の解離・活量・Debye-Hückel理論を扱う化学分野。",
        "impact_summary": "電池電解質・生体内イオン環境・海水淡水化・化学工業プロセスの基礎。Arrhenius(電解質理論, 1903 Nobel)・van't Hoff(束一的性質, 1901 Nobel)が確立。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1884,
        "culture_region": "Europe_Western",
        "source_url": "https://goldbook.iupac.org/terms/view/E01981",
        "mathematical_formulation": r"\log \gamma_\pm = -A|z_+z_-|\sqrt{I}, \quad I = \frac{1}{2}\sum_i c_i z_i^2",
        "data_completeness": 88,
    },
    {
        "name_ja": "エネルギー変換材料化学（太陽電池・燃料電池）",
        "name_en": "Energy Conversion Materials Chemistry",
        "definition": "太陽光・化学エネルギーを電気エネルギーへ変換するための材料（シリコン・ペロブスカイト・白金触媒・固体酸化物）の合成・界面制御・電荷移動を研究する分野。",
        "impact_summary": "再生可能エネルギー社会への移行の鍵。ペロブスカイト太陽電池(2009〜)の急速な効率向上(3%→26%)・固体高分子型燃料電池・水電解水素製造の材料開発が焦点。",
        "subfield": "化学",
        "school_of_thought": "Materials Chemistry",
        "era_start": 1954,
        "culture_region": "North_America",
        "source_url": "https://www.nrel.gov/pv/cell-efficiency.html",
        "mathematical_formulation": r"\eta = \frac{P_{\max}}{P_{\text{incident}}} = \frac{J_{sc}\cdot V_{oc}\cdot FF}{P_{\text{in}}}",
        "data_completeness": 88,
    },
    {
        "name_ja": "メソアメリカの染色化学",
        "name_en": "Mesoamerican Dye Chemistry",
        "definition": "アステカ・マヤ等メソアメリカ文明で発展したコチニール（赤）・インディゴ（藍）・アナト－（黄）などの天然染料化学。コチニールはカルミン酸を主成分とする複合天然色素。",
        "impact_summary": "コチニールはスペイン征服後ヨーロッパ最重要染料となり、16–18世紀の染色産業・絵画を支えた。天然染料化学・化学史における非ヨーロッパの貢献の典型例。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": 1000,
        "culture_region": "Americas_Indigenous",
        "source_url": "https://www.sciencedirect.com/science/article/pii/S0143720819302499",
        "data_completeness": 82,
    },
    {
        "name_ja": "高分子電解質とバイオポリマー",
        "name_en": "Polyelectrolytes and Biopolymers",
        "definition": "電荷を持つ高分子（DNA・RNA・タンパク質・多糖等のバイオポリマー）、および合成ポリ電解質の溶液中構造・ゲル化・複合体形成を扱う化学分野。",
        "impact_summary": "ドラッグデリバリー系・ヒドロゲル創傷被覆材・自己組織化ナノ材料の基礎。腸内細菌バイオフィルムの電解質ゲル構造、DNA圧縮・ヒストンとの相互作用も包含。",
        "subfield": "化学",
        "school_of_thought": "Physical Chemistry",
        "era_start": 1940,
        "culture_region": "Europe_Western",
        "source_url": "https://www.rsc.org/journals-books-databases/find-an-article/soft-matter/",
        "data_completeness": 85,
    },
    {
        "name_ja": "化学センサーとバイオセンサー",
        "name_en": "Chemical Sensors and Biosensors",
        "definition": "特定の化学種（イオン・分子・タンパク質）を認識し電気・光シグナルへ変換するデバイス。イオン選択電極・グルコースバイオセンサー（酵素電極）・SPRが代表例。",
        "impact_summary": "血糖センサー（糖尿病管理）・環境モニタリング（水質・大気汚染）・食品安全・ウイルス診断（COVID-19抗原検査）に不可欠。市場規模は2030年に300億USD超と推定。",
        "subfield": "化学",
        "school_of_thought": "Analytical Chemistry",
        "era_start": 1962,
        "culture_region": "Europe_Western",
        "source_url": "https://www.mdpi.com/journal/sensors",
        "data_completeness": 87,
    },
    {
        "name_ja": "大気化学とエアロゾル",
        "name_en": "Atmospheric Chemistry and Aerosols",
        "definition": "大気中の気相・液相・固相（エアロゾル粒子）の化学反応、オゾン層化学、PM2.5・光化学スモッグ・酸性雨の形成機構を研究する環境化学分野。",
        "impact_summary": "CFCによるオゾン層破壊の解明(Molina・Rowland・Crutzen 1995 Nobel)がモントリオール議定書を生んだ。気候変動(エアロゾルの放射強制力)・都市大気汚染対策の科学的基盤。",
        "subfield": "化学",
        "school_of_thought": "Environmental Chemistry",
        "era_start": 1970,
        "culture_region": "North_America",
        "source_url": "https://www.eac-acp.net/atmospheric-chemistry",
        "data_completeness": 88,
    },
    {
        "name_ja": "南アジアの鉄鋼技術（ウーツ鋼）",
        "name_en": "South Asian Wootz Steel and Iron Technology",
        "definition": "古代インド（紀元前300年〜）で生産されたウーツ鋼（高炭素鋼）の製錬技術。特殊な炭素偏析・カーバイド微細構造が「ダマスカス鋼」の素材。近代冶金学への先駆的貢献。",
        "impact_summary": "中東・ヨーロッパで珍重された刃物素材の起源。炭素含有量制御という近代製鋼学の先駆的成果として化学史・材料史研究者が注目。",
        "subfield": "化学",
        "school_of_thought": "History of Chemistry",
        "era_start": -300,
        "culture_region": "South_Asia",
        "source_url": "https://www.sciencedirect.com/science/article/abs/pii/S1044580320302667",
        "data_completeness": 80,
    },
]

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (uid, c["name_ja"], c["name_en"], c.get("name_original"),
              c["definition"], c["impact_summary"], c["subfield"],
              c["school_of_thought"], c["era_start"], c["culture_region"],
              c["source_url"], c.get("mathematical_formulation"),
              c.get("verification_status", "url_present"), "active",
              c.get("data_completeness", 85), now, now))
        inserted += 1
    conn.commit()
    return inserted

if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    n1 = insert_batch(conn, BATCH1)
    n2 = insert_batch(conn, BATCH2)
    n3 = insert_batch(conn, BATCH3)
    total = n1 + n2 + n3
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM natural_discovery")
    grand = cursor.fetchone()[0]
    conn.close()
    print(f"Batch12 chemistry2: {total} inserted (B1={n1}, B2={n2}, B3={n3}). Total: {grand}")
