#!/usr/bin/env python3
"""
DUA Wave A2 Batch 2: 化学拡張 (+350 concepts)
AK内では概念史・歴史的発見・非西洋科学軸で差別化
"""

import sqlite3, uuid
from datetime import datetime, timezone

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"
BATCH_SIZE = 50

concepts = [
    # === 化学の歴史的発見 ===
    {
        "name_ja": "元素の発見史：電気分解による新元素単離",
        "name_en": "Discovery of Elements via Electrolysis (Davy)",
        "name_original": "Elektrolytische Elementauftrennung",
        "definition": "ハンフリー・デービーが1807-08年に電気分解を用いてナトリウム・カリウム・カルシウム・マグネシウム・バリウム・ストロンチウムを単離した一連の発見。電気化学と元素化学を結びつけた先駆的業績。",
        "impact_summary": "電気化学的方法による元素単離の確立。アルミニウム・フッ素など多くの元素の工業的単離法の先駆。電池（ボルタ電池）を分析道具として活用した最初の例。",
        "subfield": "化学",
        "school_of_thought": "無機・電気化学史",
        "era_start": 1807,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Humphry_Davy",
        "mathematical_formulation": r"m = \frac{QM}{nF} = \frac{ItM}{nF} \quad \text{（ファラデーの電気分解法則）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ドルトンの原子論",
        "name_en": "Dalton's Atomic Theory",
        "name_original": "Daltonsche Atomtheorie",
        "definition": "ジョン・ドルトンが1803-08年に提唱した近代原子論。各元素は固有の質量を持つ原子から成り、化合物は原子が整数比で結合して形成されるという定量的な化学の基礎理論。",
        "impact_summary": "近代化学の理論的基盤。倍数比例の法則・定比例の法則を原子論で統一的に説明。原子量の概念を導入し定量的化学分析の枠組みを確立した。",
        "subfield": "化学",
        "school_of_thought": "原子論・化学史",
        "era_start": 1803,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Dalton%27s_atomic_theory",
        "mathematical_formulation": r"m_A : m_B = n_A : n_B, \quad \text{（倍数比例の法則）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "元素の周期律の発見（メンデレーエフ）",
        "name_en": "Mendeleev's Periodic Law Discovery",
        "name_original": "Периодический закон",
        "definition": "ドミトリ・メンデレーエフが1869年に発表した、元素を原子量順に並べると性質が周期的に繰り返すという法則。未発見元素（ガリウム・ゲルマニウム等）を予言し、実験的に確認された。",
        "impact_summary": "化学の最大の組織化原理。量子力学による電子配置との接続（1920年代）で完全に理解された。118元素を包含する現代の周期表の基礎。",
        "subfield": "化学",
        "school_of_thought": "無機化学・元素化学史",
        "era_start": 1869,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Periodic_table",
        "mathematical_formulation": r"Z = \text{原子番号（電子配置の整数}, \quad [He]2s^22p^6 = \text{Ne閉殻}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "有機化学の合成化学革命（ウェーラーの尿素合成）",
        "name_en": "Wöhler's Synthesis of Urea and Organic Chemistry Revolution",
        "name_original": "Wöhlers Harnstoffsynthese",
        "definition": "フリードリッヒ・ウェーラーが1828年に無機物（シアン酸アンモニウム）から有機物（尿素）を合成した実験。「生命力」なしに有機物が作れることを示し、有機化学を無機化学の延長として理解する契機となった。",
        "impact_summary": "生気論の打破と有機合成化学の出発点。医薬品・農薬・プラスチック・染料の合成化学産業の理論的先駆。現代製薬産業の哲学的基盤を提供した。",
        "subfield": "化学",
        "school_of_thought": "有機化学史",
        "era_start": 1828,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/W%C3%B6hler_synthesis",
        "mathematical_formulation": r"NH_4OCN \xrightarrow{\Delta} (NH_2)_2CO \quad \text{（尿素合成）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "キラリティーと不斉炭素の発見",
        "name_en": "Discovery of Chirality and Asymmetric Carbon",
        "name_original": "Chiralität",
        "definition": "パスツールが1848年に酒石酸塩の結晶分割で光学活性を発見し、ファント・ホッフとル・ベルが1874年に炭素四面体型を提唱して立体化学を創始した。分子の鏡像関係（エナンチオマー）が生物活性に決定的な違いをもたらす。",
        "impact_summary": "創薬における不斉合成の基礎（サリドマイド事件の教訓を含む）。2001年ノーベル化学賞（野依良治・シャープレス・ノールス）。生命分子のホモキラリティー問題と生命起源研究に直結。",
        "subfield": "化学",
        "school_of_thought": "立体化学史",
        "era_start": 1874,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Chirality_(chemistry)",
        "mathematical_formulation": r"[\alpha]^T_\lambda = \frac{\alpha}{l \cdot c} \quad \text{（旋光度定義）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ベンゼン環の構造（ケクレの夢）",
        "name_en": "Kekulé's Benzene Ring Structure",
        "name_original": "Kekulé-Struktur",
        "definition": "アウグスト・ケクレが1865年に提唱した、ベンゼンが6個の炭素と6個の水素からなる六員環構造という仮説。共鳴構造・芳香族性の概念の出発点となり、芳香族化合物の化学を拓いた。",
        "impact_summary": "有機化学における芳香族化学の基礎。染料・医薬品・プラスチック（フェノール樹脂等）・農薬の有機合成の理論的出発点。量子化学（分子軌道論）による後の厳密な理解への橋渡し。",
        "subfield": "化学",
        "school_of_thought": "有機構造化学史",
        "era_start": 1865,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Benzene",
        "mathematical_formulation": r"\text{C}_6\text{H}_6, \quad \Delta H_f = +82.9 \text{ kJ/mol}, \quad \pi\text{系共鳴安定化} \approx 150 \text{ kJ/mol}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "DNAの二重らせん構造発見",
        "name_en": "Discovery of DNA Double Helix Structure",
        "name_original": "DNA-Doppelhelix",
        "definition": "ワトソンとクリックがフランクリン・ウィルキンスのX線回折データを基に1953年に発表したDNAの二重らせん構造モデル。相補的塩基対（A-T、G-C）による遺伝情報複製の化学的機構を示した。",
        "impact_summary": "20世紀生物科学最大の発見。1962年ノーベル生理学・医学賞。遺伝子工学・PCR・ゲノム解析・遺伝子治療のすべての基礎。フランクリンへの貢献認定問題は科学史のジェンダー問題として重要。",
        "subfield": "化学",
        "school_of_thought": "生化学・分子生物学史",
        "era_start": 1953,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Nucleic_acid_double_helix",
        "mathematical_formulation": r"\text{A-T}: 2\text{水素結合}, \quad \text{G-C}: 3\text{水素結合}, \quad \text{螺旋ピッチ} = 3.4 \text{ nm}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "触媒の発見と化学工業への応用",
        "name_en": "Discovery of Catalysis and Industrial Chemistry",
        "name_original": "Katalyse",
        "definition": "ベルセリウスが1835年に「触媒」の概念を命名し、オストワルドが化学平衡・反応速度との関係を理論化（1909年ノーベル賞）。ハーバー・ボッシュ法（1913年）によるアンモニア合成が人類の食料生産を革命した。",
        "impact_summary": "現代化学産業の根幹。ハーバー・ボッシュ法は現在の世界人口70-80億人の食料生産を支えるとも言われる。自動車触媒・石油精製・製薬合成すべてに触媒が不可欠。",
        "subfield": "化学",
        "school_of_thought": "触媒・工業化学史",
        "era_start": 1835,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Catalysis",
        "mathematical_formulation": r"k = A e^{-E_a/RT}, \quad E_a(\text{触媒}) < E_a(\text{無触媒})",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ハーバー・ボッシュ法（窒素固定）",
        "name_en": "Haber-Bosch Process for Nitrogen Fixation",
        "name_original": "Haber-Bosch-Verfahren",
        "definition": "フリッツ・ハーバーが発見しカール・ボッシュが工業化した（1913年）、大気中の窒素からアンモニアを合成する高温高圧触媒反応。鉄触媒・500℃・200気圧での平衡反応を工業スケールで実現した。",
        "impact_summary": "1918年ノーベル化学賞（ハーバー）、1931年ノーベル化学賞（ボッシュ）。肥料生産で世界の農業を支え推定30億人の命を救う。一方で化学兵器開発への関与という倫理的問題も持つ。",
        "subfield": "化学",
        "school_of_thought": "工業化学・触媒史",
        "era_start": 1913,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Haber_process",
        "mathematical_formulation": r"N_2 + 3H_2 \rightleftharpoons 2NH_3, \quad K_p(500°C) \approx 6\times10^{-3} \text{ atm}^{-2}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "X線結晶解析の確立",
        "name_en": "Establishment of X-ray Crystallography",
        "name_original": "Röntgenkristallographie",
        "definition": "フォン・ラウエが1912年にX線回折を発見し、ブラッグ父子が1913年にブラッグの法則を確立した結晶構造決定法。タンパク質・DNA・無機化合物の三次元構造決定の標準的手法となった。",
        "impact_summary": "1914年ノーベル物理学賞（ラウエ）、1915年ノーベル物理学賞（ブラッグ父子）。DNA二重らせん・インスリン・ミオグロビン・酵素構造決定の基礎技術。現代創薬の不可欠な道具。",
        "subfield": "化学",
        "school_of_thought": "構造化学・分析化学史",
        "era_start": 1912,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/X-ray_crystallography",
        "mathematical_formulation": r"n\lambda = 2d\sin\theta \quad \text{（ブラッグの法則）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ポリマー化学の創始（シュタウディンガー）",
        "name_en": "Foundation of Polymer Chemistry (Staudinger)",
        "name_original": "Makromoleküle",
        "definition": "ヘルマン・シュタウディンガーが1922年に提唱した高分子（マクロ分子）概念。当時主流だった小分子の会合体説を否定し、共有結合で繋がった長鎖高分子が実在することを主張して激しい論争の末に証明した。",
        "impact_summary": "1953年ノーベル化学賞。プラスチック・繊維・ゴム・接着剤などの高分子材料産業の理論基盤。生体高分子（タンパク質・核酸・多糖）理解の基礎概念でもある。",
        "subfield": "化学",
        "school_of_thought": "高分子化学史",
        "era_start": 1922,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Hermann_Staudinger",
        "mathematical_formulation": r"\overline{M}_n = \frac{\sum n_i M_i}{\sum n_i}, \quad \overline{M}_w = \frac{\sum n_i M_i^2}{\sum n_i M_i}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "核磁気共鳴（NMR）化学シフトの発見",
        "name_en": "Discovery of NMR Chemical Shift",
        "name_original": "Chemische Verschiebung",
        "definition": "プロクターとユーが1950年に発見した、同じ原子核でも化学環境の違いにより共鳴周波数（化学シフト）が異なる現象。この発見によりNMRが化学構造決定の強力な道具となった。",
        "impact_summary": "有機化学・生化学における構造決定の革命。1D→2D→多次元NMRへの発展によりタンパク質立体構造解析（2002年ノーベル化学賞、ヴュートリッヒ）が可能に。",
        "subfield": "化学",
        "school_of_thought": "分析化学・分光学史",
        "era_start": 1950,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Chemical_shift",
        "mathematical_formulation": r"\delta = \frac{\nu_{\text{sample}} - \nu_{\text{ref}}}{\nu_{\text{ref}}} \times 10^6 \text{ ppm}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "密度汎関数理論（DFT）の確立",
        "name_en": "Establishment of Density Functional Theory (DFT)",
        "name_original": "Dichtefunktionaltheorie",
        "definition": "ホーエンベルク・コーンが1964年に定式化し、コーン・シャムが1965年に実用的手法として確立した量子化学計算の理論。電子密度を基本変数とし、多電子系の正確なシュレーディンガー方程式を近似的に解く。",
        "impact_summary": "1998年ノーベル化学賞（コーン）。現代計算化学・材料科学の標準手法。年間50万件以上の論文で使用。創薬・触媒設計・新材料探索に不可欠な第一原理計算の基礎。",
        "subfield": "化学",
        "school_of_thought": "計算化学・量子化学史",
        "era_start": 1964,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Density_functional_theory",
        "mathematical_formulation": r"E[\rho] = T_s[\rho] + \int v(\vec{r})\rho(\vec{r})d\vec{r} + J[\rho] + E_{xc}[\rho]",
        "verification_status": "url_present",
    },
    {
        "name_ja": "グリーン化学の12原則",
        "name_en": "12 Principles of Green Chemistry",
        "name_original": "Green Chemistry",
        "definition": "アナスタスとワーナーが1998年に提唱した持続可能な化学の設計原則。廃棄物の予防・原子効率・無害な溶媒・触媒・再生可能原料など12の原則で化学プロセスの環境負荷を最小化する。",
        "impact_summary": "化学産業の持続可能性パラダイムの転換。プレジデンタルグリーンケミストリー賞設立（1996年）。バイオベース化学品・酵素触媒・連続フロー化学の発展を促した。",
        "subfield": "化学",
        "school_of_thought": "持続可能化学史",
        "era_start": 1998,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Green_chemistry",
        "mathematical_formulation": r"E\text{-factor} = \frac{m_{\text{waste}}}{m_{\text{product}}}, \quad AE = \frac{M_{\text{product}}}{\sum M_{\text{reactants}}} \times 100\%",
        "verification_status": "url_present",
    },
    {
        "name_ja": "化学熱力学と自由エネルギー（ギブス）",
        "name_en": "Chemical Thermodynamics and Gibbs Free Energy",
        "name_original": "Gibbs'sche freie Energie",
        "definition": "ジョサイア・ウィラード・ギブスが1873-78年に体系化した化学熱力学の理論体系。ギブス自由エネルギーG=H-TSの概念により化学反応の自発性・平衡・相変化を定量的に予測可能にした。",
        "impact_summary": "化学・化学工学の最重要熱力学量の確立。電気化学（ネルンスト方程式）・相平衡（相律）・化学平衡定数Kとの接続。反応工学・冶金学・材料設計の理論基盤。",
        "subfield": "化学",
        "school_of_thought": "化学熱力学史",
        "era_start": 1876,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Gibbs_free_energy",
        "mathematical_formulation": r"G = H - TS, \quad \Delta G = \Delta H - T\Delta S, \quad \Delta G^\circ = -RT\ln K",
        "verification_status": "url_present",
    },
    {
        "name_ja": "酵素触媒の機構（ミカエリス・メンテン）",
        "name_en": "Enzyme Catalysis Mechanism (Michaelis-Menten)",
        "name_original": "Michaelis-Menten-Kinetik",
        "definition": "ミカエリスとメンテンが1913年に定式化した酵素反応速度論。基質濃度と反応速度の双曲線関係を記述し、最大速度Vmaxとミカエリス定数Kmを定義した。生化学・創薬・バイオプロセス設計の基盤。",
        "impact_summary": "生体触媒の定量的理解の基礎。酵素阻害剤設計（抗生物質・抗ウイルス薬・抗がん剤）の理論的枠組み。バイオリアクター設計・代謝フラックス解析にも応用される。",
        "subfield": "化学",
        "school_of_thought": "生化学・酵素化学史",
        "era_start": 1913,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics",
        "mathematical_formulation": r"v = \frac{V_{\max}[S]}{K_m + [S]}, \quad K_m = \frac{k_{-1}+k_2}{k_1}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "核磁気共鳴分光法による蛋白質構造解析",
        "name_en": "Protein Structure Determination by NMR",
        "name_original": "NMR-Proteinstrukturbestimmung",
        "definition": "クルト・ヴュートリッヒが1980年代に確立した溶液NMRによるタンパク質立体構造決定法。NOE法・多次元NMR・NOESY・HOHAHAなどの手法を組み合わせ、結晶化不要で溶液中のタンパク質構造を決定できる。",
        "impact_summary": "2002年ノーベル化学賞。構造ゲノミクス・創薬標的同定への寄与。X線結晶解析と相補的な手法として生命科学の基盤技術となった。",
        "subfield": "化学",
        "school_of_thought": "構造生化学史",
        "era_start": 1984,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Nuclear_magnetic_resonance_spectroscopy_of_proteins",
        "mathematical_formulation": r"\langle r^{-6}\rangle \propto \sigma_{\text{NOE}}, \quad \text{NOESY cross-peak} \propto r_{ij}^{-6}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "電気化学ポテンシャルとネルンスト方程式",
        "name_en": "Electrochemical Potential and Nernst Equation",
        "name_original": "Nernstsche Gleichung",
        "definition": "ヴァルター・ネルンストが1889年に導いた電極電位と溶液濃度の関係式。ギブス自由エネルギーと電気的仕事を結びつけ、電池起電力・膜電位・イオン輸送の定量的理解を可能にした。",
        "impact_summary": "1920年ノーベル化学賞（ネルンスト）。電池技術・電気メッキ・センサー・神経細胞の静止膜電位理解の基礎。リチウムイオン電池の熱力学設計に直結する。",
        "subfield": "化学",
        "school_of_thought": "電気化学史",
        "era_start": 1889,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Nernst_equation",
        "mathematical_formulation": r"E = E^\circ - \frac{RT}{nF}\ln Q = E^\circ - \frac{0.0592}{n}\log Q \text{ (25°C)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "クロマトグラフィーの発明と発展",
        "name_en": "Invention and Development of Chromatography",
        "name_original": "Chromatographie",
        "definition": "ミハイル・ツヴェットが1906年に植物色素分離のために発明したカラムクロマトグラフィーを起点に、TLC・GC・HPLC・イオンクロマトグラフィーへと発展した混合物分離・分析手法の系譜。",
        "impact_summary": "分析化学・有機化学・生化学の標準的分離精製ツール。製薬業の医薬品精製・食品分析・環境モニタリング・フォレンジック化学に不可欠。ノーベル賞受賞物質の多くがクロマトグラフィーで分離精製された。",
        "subfield": "化学",
        "school_of_thought": "分析化学史",
        "era_start": 1906,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Chromatography",
        "mathematical_formulation": r"R_f = \frac{d_{\text{substance}}}{d_{\text{solvent}}}, \quad N = 16\left(\frac{t_R}{w}\right)^2 \text{ (理論段数)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "合成染料の発見とドイツ染料工業",
        "name_en": "Discovery of Synthetic Dyes and German Dye Industry",
        "name_original": "Synthetische Farbstoffe",
        "definition": "ウィリアム・パーキンが1856年にアニリンからモーブを偶然合成したことに始まる合成染料産業の勃興。バイエル・ヘキスト・BASFなどドイツ化学工業の発展を促し、医薬品産業（アスピリン・スルファ剤・サルバルサン）の先駆ともなった。",
        "impact_summary": "有機化学産業の起源。コールタール化学から医薬品・農薬・プラスチックへの展開を生んだ。マラリア治療薬（キニーネ代替）の開発動機ともなり、熱帯医学の進歩に貢献。",
        "subfield": "化学",
        "school_of_thought": "有機化学産業史",
        "era_start": 1856,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Mauveine",
        "mathematical_formulation": r"\text{Azo dye: } \text{Ar}-\text{N}=\text{N}-\text{Ar}', \quad \lambda_{\max} \propto \pi\text{共役長}",
        "verification_status": "url_present",
    },
    # === 非西洋化学史 ===
    {
        "name_ja": "イスラム錬金術と蒸留技術",
        "name_en": "Islamic Alchemy and Distillation Technology",
        "name_original": "الكيمياء الإسلامية",
        "definition": "ジャービル・イブン・ハイヤーン（8-9世紀）を代表とするイスラム黄金期の錬金術師が確立した実験的化学。硫酸・硝酸・王水の製造、蒸留装置（アランビック）の発明、触媒概念の先駆的記述などを含む。",
        "impact_summary": "ヨーロッパ錬金術への直接的影響。「アルコール」「アルカリ」「エリクサー」など多くの化学用語のアラビア語起源。蒸留技術は香水・医薬品・アルコール製造の基礎。",
        "subfield": "化学",
        "school_of_thought": "イスラーム黄金期化学史",
        "era_start": 780,
        "culture_region": "West_Asia_North_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Jabir_ibn_Hayyan",
        "mathematical_formulation": r"\text{蒸留原理: } P^*(T) = P^\circ e^{-\Delta H_{\text{vap}}/RT} \text{（クラウジウス・クラペイロン）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "中国の火薬の発明",
        "name_en": "Chinese Invention of Gunpowder",
        "name_original": "火药",
        "definition": "唐代中国（9世紀頃）に道教の錬丹術師が硝石・硫黄・炭素の混合物（黒色火薬）を発見した歴史的発明。宋代に軍事利用され、13世紀にモンゴルを経てイスラム世界・ヨーロッパに伝わり世界史を変えた。",
        "impact_summary": "火器・採掘・花火・爆破技術の基礎。封建制度の崩壊と近代国家形成に寄与（マルクス・エンゲルスが「世界史的転換点」として言及）。近代的爆薬（ニトログリセリン・TNT等）の前史。",
        "subfield": "化学",
        "school_of_thought": "中国化学技術史",
        "era_start": 850,
        "culture_region": "East_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Gunpowder",
        "mathematical_formulation": r"2KNO_3 + S + 3C \to K_2S + N_2 + 3CO_2 \quad \text{（黒色火薬の燃焼反応の近似）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "インド伝統医学（アーユルヴェーダ）の薬草化学",
        "name_en": "Phytochemistry in Indian Ayurvedic Medicine",
        "name_original": "आयुर्वेद",
        "definition": "紀元前6世紀頃から体系化されたインドの伝統医学アーユルヴェーダに含まれる薬草・金属・鉱物の医療利用の化学知識体系。スシュルタ本集・チャラカ本集に記載された水銀・砒素・鉛の薬用法、植物アルカロイドの活用など。",
        "impact_summary": "生薬化学の古代的基盤。レセルピン（降圧薬）・カルカミン・ターメリック（クルクミン）など多くの薬効物質がアーユルヴェーダ植物から現代薬学へ。インド政府が伝統医学の近代化を推進中。",
        "subfield": "化学",
        "school_of_thought": "インド伝統科学史",
        "era_start": -600,
        "culture_region": "South_Asia",
        "source_url": "https://en.wikipedia.org/wiki/Ayurveda",
        "mathematical_formulation": r"\text{レセルピン: } C_{33}H_{40}N_2O_9, \quad \text{クルクミン: } C_{21}H_{20}O_6",
        "verification_status": "url_present",
    },
    {
        "name_ja": "古代エジプトのパピルス化学技術",
        "name_en": "Ancient Egyptian Chemical Technologies in Papyrus",
        "name_original": "Papyrus Leiden-Stockholm",
        "definition": "ライデン・ストックホルムパピルス（3-4世紀）に記録された染色・金属偽造・美容品製造の化学技術。硫黄・水銀・塩類を用いた黄金色金属の製法・染料の調製法が記載され、ヨーロッパ錬金術の源流の一つ。",
        "impact_summary": "錬金術と実用化学技術の接合点。ミイラ作製（ナトロン塩・樹脂）・ガラス製造・金属加工など古代エジプトの化学的知識の高度さを示す。",
        "subfield": "化学",
        "school_of_thought": "古代化学技術史",
        "era_start": -3000,
        "culture_region": "Sub_Saharan_Africa",
        "source_url": "https://en.wikipedia.org/wiki/Leiden_Papyrus_X",
        "mathematical_formulation": r"Na_2CO_3 \cdot 10H_2O \text{ (ナトロン)}, \quad \text{ミイラ乾燥: } \Delta m/\Delta t \propto A \cdot (RH_0 - RH)",
        "verification_status": "url_present",
    },
    {
        "name_ja": "酸素の発見（プリーストリー・シェーレ・ラボアジェ）",
        "name_en": "Discovery of Oxygen (Priestley, Scheele, Lavoisier)",
        "name_original": "Sauerstoffnachweis",
        "definition": "シェーレ（1771-72年、非公表）とプリーストリー（1774年）が独立に「脱フロギストン気体」として発見し、ラボアジェが「酸素」と命名して燃焼の酸化理論（1777年）を確立した歴史的発見の連鎖。",
        "impact_summary": "フロギストン説の打倒と近代化学命名法の確立。「化学革命」の中核的発見。製鋼・医療（酸素吸入）・ロケット推進剤など広汎な応用を持つ。",
        "subfield": "化学",
        "school_of_thought": "化学命名法・化学革命史",
        "era_start": 1774,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Oxygen",
        "mathematical_formulation": r"2H_2O_2 \xrightarrow{MnO_2} 2H_2O + O_2, \quad \Delta H^\circ = -196 \text{ kJ/mol}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "反応速度論と活性化エネルギー（アレニウス）",
        "name_en": "Chemical Kinetics and Activation Energy (Arrhenius)",
        "name_original": "Arrhenius-Gleichung",
        "definition": "スヴァンテ・アレニウスが1889年に提唱した反応速度の温度依存性の定量的関係式。活性化エネルギーEaの概念を導入し、温度が10K上昇すると反応速度が約2倍になる経験則の理論的根拠を与えた。",
        "impact_summary": "触媒設計・食品保存・医薬品安定性・材料劣化予測の理論基盤。1903年ノーベル化学賞（アレニウス）。遷移状態理論（エヴァンス・ポランニー、1935年）への発展。",
        "subfield": "化学",
        "school_of_thought": "化学反応速度論史",
        "era_start": 1889,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Arrhenius_equation",
        "mathematical_formulation": r"k = Ae^{-E_a/RT}, \quad \ln k = \ln A - \frac{E_a}{R} \cdot \frac{1}{T}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ナイロンの発明（キャロザース）",
        "name_en": "Invention of Nylon (Carothers)",
        "name_original": "Nylon",
        "definition": "ウォレス・キャロザースがデュポン社で1935年に発明した最初の完全合成繊維。ポリアミド系高分子で縮合重合によって製造される。天然シルクの代替として戦時中の軍用品・女性用ストッキングで普及した。",
        "impact_summary": "合成繊維産業の起源。ポリエステル・アクリル・ポリプロピレンなど後続の合成繊維の先駆。高分子材料の工業的設計のモデルケース。キャロザースの自殺は科学者のメンタルヘルス問題の象徴的事例。",
        "subfield": "化学",
        "school_of_thought": "高分子化学・産業化学史",
        "era_start": 1935,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Nylon",
        "mathematical_formulation": r"n\text{H}_2\text{N}(\text{CH}_2)_6\text{NH}_2 + n\text{HOOC}(\text{CH}_2)_4\text{COOH} \to [\text{PA66}]_n + 2n\text{H}_2\text{O}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ペニシリンの発見と医薬品化学",
        "name_en": "Discovery of Penicillin and Medicinal Chemistry",
        "name_original": "Penicillin-Entdeckung",
        "definition": "アレクサンダー・フレミングが1928年にカビから偶然発見し、フローリー・チェインが1940-45年に精製・臨床応用した最初の抗生物質。β-ラクタム環が細菌の細胞壁合成酵素を阻害する作用機序。",
        "impact_summary": "1945年ノーベル生理学・医学賞。感染症治療の革命。第二次世界大戦の死者数を大幅に減らした。抗生物質耐性問題（薬剤耐性菌）という21世紀の公衆衛生課題の先駆的文脈でもある。",
        "subfield": "化学",
        "school_of_thought": "医薬品化学史",
        "era_start": 1928,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Penicillin",
        "mathematical_formulation": r"\text{β-ラクタム環}: C_9H_{11}N_2O_4S^- \text{ (ペニシリンG)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "アスピリンの化学史",
        "name_en": "Chemical History of Aspirin",
        "name_original": "Acetylsalicylsäure",
        "definition": "ヤナウスキーが1853年にサリチル酸のアセチル化を初めて行い、ドレッサーがバイエル社で1899年に「アスピリン」として商品化した鎮痛・解熱・抗血小板薬。柳の皮の民間薬から始まる有効成分の精製・化学修飾・工業化の過程。",
        "impact_summary": "世界初の大量生産医薬品。COX阻害機構の発見（ヴェイン、1971年）で1982年ノーベル生理学・医学賞。心筋梗塞予防への応用で現在も年間40,000トン以上生産される。",
        "subfield": "化学",
        "school_of_thought": "医薬品化学史",
        "era_start": 1899,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Aspirin",
        "mathematical_formulation": r"C_9H_8O_4, \quad \text{アセチルサリチル酸} + H_2O \to \text{サリチル酸} + CH_3COOH",
        "verification_status": "url_present",
    },
    {
        "name_ja": "フラーレンとナノカーボン材料の発見",
        "name_en": "Discovery of Fullerenes and Nanocarbon Materials",
        "name_original": "Fulleren",
        "definition": "クロート・スモーリー・カールが1985年に発見したサッカーボール型炭素クラスター（C60、バックミンスターフラーレン）。続いてカーボンナノチューブ（飯島澄男、1991年）、グラフェン（2004年）へと展開したナノカーボン科学の嚆矢。",
        "impact_summary": "1996年ノーベル化学賞。ナノテクノロジーの基礎概念の一つ。太陽電池・超伝導体・薬物送達・強化材料など多方面の応用研究を促した。",
        "subfield": "化学",
        "school_of_thought": "ナノ化学・材料化学史",
        "era_start": 1985,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Fullerene",
        "mathematical_formulation": r"C_{60}: I_h\text{対称性}, \quad 12\text{五員環}+20\text{六員環}, \quad d = 0.71\text{ nm}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "タンパク質の一次構造決定（サンガー法）",
        "name_en": "Protein Primary Structure Determination (Sanger Method)",
        "name_original": "Sanger-Methode",
        "definition": "フレデリック・サンガーが1951-55年にインスリンのアミノ酸配列を完全決定した手法。DNF（ジニトロフルオロベンゼン）法によるN末端分析とペプチド分解を組み合わせ、タンパク質が特定の配列を持つことを初めて証明した。",
        "impact_summary": "1958年ノーベル化学賞（最初のノーベル化学賞、後にDNA配列決定法でも1980年に2度目）。配列決定の概念を確立し、後のDNA塩基配列決定（次世代シーケンサー）の先駆。",
        "subfield": "化学",
        "school_of_thought": "生化学・タンパク質化学史",
        "era_start": 1951,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Sanger_sequencing",
        "mathematical_formulation": r"n\text{残基タンパク質: } 20^n\text{通りの配列可能性}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "オゾン層破壊とハロゲン化炭素化学",
        "name_en": "Ozone Depletion and Halocarbon Chemistry",
        "name_original": "Ozonlochchemie",
        "definition": "モリーナとロウランドが1974年に理論的に予測し、1985年にファーマン・ガードナーらが南極上空で実測したオゾン層破壊現象。CFCなどハロゲン化炭素が成層圏で塩素ラジカルを生成してオゾンを触媒的に破壊するメカニズム。",
        "impact_summary": "1995年ノーベル化学賞（クルッツェン・モリーナ・ロウランド）。モントリオール議定書（1987年）による国際的規制とCFC代替品開発の成功例。環境化学の政策への直結事例。",
        "subfield": "化学",
        "school_of_thought": "環境化学史",
        "era_start": 1974,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Ozone_depletion",
        "mathematical_formulation": r"Cl + O_3 \to ClO + O_2, \quad ClO + O \to Cl + O_2 \quad \text{（触媒サイクル）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "リチウムイオン電池の化学",
        "name_en": "Chemistry of Lithium-Ion Batteries",
        "name_original": "Lithium-Ionen-Batterie",
        "definition": "グッドイナフ（正極LiCoO₂、1980年）・ウィティンガム（負極概念）・吉野彰（炭素負極、1985年）が完成させた二次電池。リチウムイオンの正負極間を往来するインターカレーション反応を基本原理とする。",
        "impact_summary": "2019年ノーベル化学賞（グッドイナフ・ウィティンガム・吉野）。スマートフォン・電気自動車・蓄電システムのエネルギー源。日本発の革新的電池技術として産業・環境政策に直結。",
        "subfield": "化学",
        "school_of_thought": "電気化学・材料化学史",
        "era_start": 1980,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Lithium-ion_battery",
        "mathematical_formulation": r"\text{充電: } LiCoO_2 \to Li_{1-x}CoO_2 + xLi^+ + xe^-, \quad E = 3.7\text{ V}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "有機EL（OLED）の化学的発見",
        "name_en": "Chemical Discovery of Organic EL (OLED)",
        "name_original": "Organische Leuchtdiode",
        "definition": "タン・ヴァンスライクが1987年にイーストマン・コダックで発明した有機発光ダイオード（OLED）。π共役有機分子に電圧を印加すると発光する電界発光現象を実用化レベルに引き上げた発明。",
        "impact_summary": "スマートフォン・有機ELテレビの基盤技術。フレキシブルディスプレイ・照明の応用が進む。日本発の白色OLEDで城戸淳二らが寄与。再来のノーベル賞候補とも目される。",
        "subfield": "化学",
        "school_of_thought": "有機エレクトロニクス史",
        "era_start": 1987,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/OLED",
        "mathematical_formulation": r"\eta_{EQE} = \frac{eN_{\text{photon}}}{I/e}, \quad \Phi_{PL} = \frac{k_r}{k_r + k_{nr}}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "超分子化学とホスト・ゲスト化学",
        "name_en": "Supramolecular Chemistry and Host-Guest Chemistry",
        "name_original": "Supramolekulare Chemie",
        "definition": "ペデルセン・クラム・レーンが1960-80年代に確立した、分子間の非共有結合（水素結合・π-π相互作用・疎水性効果等）による組織化された超分子構造の化学。クラウンエーテル・クリプタンド・シクロデキストリンなどを含む。",
        "impact_summary": "1987年ノーベル化学賞（ペデルセン・クラム・レーン）。薬物包接・センサー・自己組織化ナノ材料・分子機械（2016年ノーベル化学賞）の基盤概念。生体認識の化学モデル。",
        "subfield": "化学",
        "school_of_thought": "超分子化学史",
        "era_start": 1967,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Supramolecular_chemistry",
        "mathematical_formulation": r"K_a = \frac{[H \cdot G]}{[H][G]}, \quad \Delta G^\circ = -RT\ln K_a",
        "verification_status": "url_present",
    },
    {
        "name_ja": "分子機械の設計と合成",
        "name_en": "Design and Synthesis of Molecular Machines",
        "name_original": "Molekulare Maschinen",
        "definition": "ソバージュ・ストッダート・フェリンガが1980-90年代に開発した、機械的に連結した分子で外部刺激により動作するロタキサン・カテナン・分子モーターなどの分子機械。",
        "impact_summary": "2016年ノーベル化学賞。ナノスケール機械デバイスの概念実証。薬物送達・表面コーティング・ナノアクチュエーターの将来技術に向けた基礎。",
        "subfield": "化学",
        "school_of_thought": "超分子・ナノ化学史",
        "era_start": 1983,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Molecular_machine",
        "mathematical_formulation": r"\text{Rotaxane: アクスル + ホイール}, \quad v_{\text{motor}} = k_{cat}/K_m \text{ (光駆動回転)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "組み合わせ化学とハイスループットスクリーニング",
        "name_en": "Combinatorial Chemistry and High-Throughput Screening",
        "name_original": "Kombinatorische Chemie",
        "definition": "メリフィールドの固相合成法（1963年）を基盤に1990年代に確立した、大量の化合物ライブラリーを一度に合成し生物活性をスクリーニングする手法。創薬の「ヒット化合物」探索を劇的に加速した。",
        "impact_summary": "1984年ノーベル化学賞（メリフィールド）。製薬業の研究開発を変革。HTS（ハイスループットスクリーニング）と合わせて年間数百万化合物の活性評価を可能にした。",
        "subfield": "化学",
        "school_of_thought": "創薬化学史",
        "era_start": 1990,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Combinatorial_chemistry",
        "mathematical_formulation": r"N_{\text{library}} = \prod_{i=1}^{n} m_i, \quad \text{(n段階×各m種類)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "クリック化学（バイオオーソゴナル化学）",
        "name_en": "Click Chemistry and Bioorthogonal Chemistry",
        "name_original": "Klickchemie",
        "definition": "シャープレスが2001年に提唱した「クリック反応」の概念と、バートッツィが2003年に生体内で使える「バイオオーソゴナル反応」として発展させた、高収率・高選択的・生体適合的な結合形成反応の化学。",
        "impact_summary": "2022年ノーベル化学賞（シャープレス・メルダル・バートッツィ）。生体分子のラベリング・薬物コンジュゲート・材料機能化・がん診断への応用。銅触媒アジド-アルキン環化付加が代表反応。",
        "subfield": "化学",
        "school_of_thought": "生物有機化学史",
        "era_start": 2001,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Click_chemistry",
        "mathematical_formulation": r"R-N_3 + R'-\text{alkyne} \xrightarrow{CuI} \text{1,4-triazole}, \quad k_2 > 10^{-4} \text{ M}^{-1}\text{s}^{-1}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "アルファ折り畳み問題とAlphaFoldの衝撃",
        "name_en": "Protein Folding Problem and AlphaFold Impact",
        "name_original": "Proteinfaltungsproblem",
        "definition": "タンパク質の一次配列からの立体構造予測という「タンパク質折り畳み問題」がAnfinsenが1972年に提唱し（ノーベル化学賞）、DeepMindのAlphaFold2（2020年）がCASP14で解決した。AI×化学の融合の象徴的事例。",
        "impact_summary": "計算生物学・創薬・生命科学全般への革命的影響。2024年ノーベル化学賞（ハサビス・ジャンパー・ベーカー）。従来数年かかった構造決定が数分で可能になりゲノム全蛋白質の構造予測が実現。",
        "subfield": "化学",
        "school_of_thought": "計算化学・AI化学史",
        "era_start": 2020,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/AlphaFold",
        "mathematical_formulation": r"E[\text{structure}] = f(\{r_{ij}\}, \{\theta\}, \{q\}), \quad \text{GDT\_TS} > 90 \text{ (CASP14)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "電子顕微鏡による原子分解能構造観察",
        "name_en": "Atomic-Resolution Structural Observation by Electron Microscopy",
        "name_original": "Elektronenmikroskopie",
        "definition": "ルスカが1931年に発明した電子顕微鏡（1986年ノーベル物理学賞）から、冷凍電子顕微鏡（クライオEM）法（ヘンダーソン・フランク・デュボシェ）まで発展した原子分解能観察技術。",
        "impact_summary": "2017年ノーベル化学賞（クライオEM）。X線結晶解析が困難な膜タンパク質・ウイルス・非晶質材料の構造決定を可能にした。COVID-19ワクチン開発においてスパイクタンパク質構造決定に直結。",
        "subfield": "化学",
        "school_of_thought": "構造化学・計測技術史",
        "era_start": 1975,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Cryo-electron_microscopy",
        "mathematical_formulation": r"\lambda = \frac{h}{\sqrt{2m_e eV}}, \quad \delta \approx 0.61\lambda/\sin\alpha \text{ (Abbe分解能)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "量子化学計算（ハートリー・フォック法）",
        "name_en": "Quantum Chemical Calculations (Hartree-Fock Method)",
        "name_original": "Hartree-Fock-Methode",
        "definition": "ハートリーが1928年に提唱し、フォックが1930年に交換項を加えて完成させた多電子系の自己無撞着場（SCF）法。各電子が他の電子の平均ポテンシャル中を運動するという近似で、分子の電子構造を計算する。",
        "impact_summary": "計算量子化学の基礎。MP2・CCSD(T)などポスト-HF法・DFTのベースライン。コンピュータの発展と合わせて分子の性質予測が実験前に可能となった計算化学の礎。",
        "subfield": "化学",
        "school_of_thought": "量子化学史",
        "era_start": 1930,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Hartree%E2%80%93Fock_method",
        "mathematical_formulation": r"F|\psi_i\rangle = \epsilon_i|\psi_i\rangle, \quad F = h + \sum_j (J_j - K_j)",
        "verification_status": "url_present",
    },
    {
        "name_ja": "不斉触媒合成（野依良治・ノールス・シャープレス）",
        "name_en": "Asymmetric Catalytic Synthesis (Noyori, Knowles, Sharpless)",
        "name_original": "Asymmetrische Katalyse",
        "definition": "キラルな遷移金属触媒を用いてラセミ体でなく特定のエナンチオマーを優先的に合成する不斉触媒合成。ノールスのRh-DIPAMP触媒（1972年）、野依のRu-BINAP触媒（1980年）、シャープレスの不斉エポキシ化（1980年）が三本柱。",
        "impact_summary": "2001年ノーベル化学賞。医薬品合成の根本的革新（カルビドパ・ナプロキセン・レボドパなど多数）。製薬業で不斉合成が常識となり、ラセミ体医薬品から光学活性体医薬品への転換を促した。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学史",
        "era_start": 1972,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Asymmetric_hydrogenation",
        "mathematical_formulation": r"ee = \frac{|[R]-[S]|}{[R]+[S]} \times 100\%, \quad \Delta\Delta G^\ddagger = -RT\ln(ee_R/ee_S)",
        "verification_status": "url_present",
    },
    {
        "name_ja": "メタセシス反応と触媒設計",
        "name_en": "Olefin Metathesis and Catalyst Design",
        "name_original": "Olefinmetathese",
        "definition": "グラッブス・シュロック・チョーバンが開発したアルケンの二重結合の組み換え反応。グラッブス第一・第二触媒（Ru錯体）が空気・水に安定な実用的触媒として医薬品・材料・石油化学での応用を可能にした。",
        "impact_summary": "2005年ノーベル化学賞。複雑な有機分子の合成ルート短縮に革命をもたらした。エポシロンB（抗がん剤）・ゾシコノチド・ピンポイント合成への応用で製薬・材料産業を変革。",
        "subfield": "化学",
        "school_of_thought": "有機金属化学史",
        "era_start": 1970,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Olefin_metathesis",
        "mathematical_formulation": r"R_1\text{CH}=\text{CH}R_2 + R_3\text{CH}=\text{CH}R_4 \xrightarrow{Ru} R_1\text{CH}=\text{CH}R_3 + R_2\text{CH}=\text{CH}R_4",
        "verification_status": "url_present",
    },
    {
        "name_ja": "酵素の結晶化とリゾチームの構造決定",
        "name_en": "Crystallization of Enzymes and Lysozyme Structure",
        "name_original": "Lysozymstruktur",
        "definition": "サムナーが1926年にウレアーゼを初めて結晶化して酵素がタンパク質であることを証明し（1946年ノーベル化学賞）、フィリップスが1965年にリゾチームの立体構造をX線解析で決定した。初の酵素立体構造決定。",
        "impact_summary": "酵素化学・構造生化学の里程標。酵素の活性部位・基質結合・触媒機構の原子レベル理解の出発点。タンパク質工学・理性的創薬（structure-based drug design）の先駆。",
        "subfield": "化学",
        "school_of_thought": "生化学・構造化学史",
        "era_start": 1965,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Lysozyme",
        "mathematical_formulation": r"\text{活性部位: Glu35（酸）+ Asp52（塩基）, 基質結合 }\Delta G \approx -30\text{ kJ/mol}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ATP合成酵素の回転触媒機構",
        "name_en": "Rotary Catalysis Mechanism of ATP Synthase",
        "name_original": "ATP-Synthase",
        "definition": "ポール・ボイヤーとジョン・ウォーカーが1990年代に解明したATP合成酵素の結合変化機構。F0サブユニットの回転とF1サブユニットの触媒部位の構造変化が連動して駆動するナノモーター的機構。",
        "impact_summary": "1997年ノーベル化学賞（ボイヤー・ウォーカー）。生命のエネルギー通貨ATPの生産機構の解明。ミトコンドリア機能・細胞呼吸・代謝疾患理解の根本。分子モーターの自然界最良の実例。",
        "subfield": "化学",
        "school_of_thought": "生化学・バイオエネルギー史",
        "era_start": 1994,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/ATP_synthase",
        "mathematical_formulation": r"\Delta G_{ATP} = \Delta G^\circ + RT\ln\frac{[ADP][P_i]}{[ATP]} \approx -54\text{ kJ/mol (体内)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "ポルフィリン化学とヘモグロビン",
        "name_en": "Porphyrin Chemistry and Hemoglobin",
        "name_original": "Hämoglobin",
        "definition": "フィッシャーがヘムの合成（1930年ノーベル化学賞）を達成し、ペルーツが1959-60年にヘモグロビンの立体構造をX線解析で決定した（1962年ノーベル化学賞）。酸素運搬の協同効果（ヒル係数）の構造的基盤を解明。",
        "impact_summary": "呼吸生理学・鎌状赤血球症・高高度適応の理解の基礎。人工血液・酸素キャリア・光線力学的療法（PDT）のポルフィリン系光増感剤の基盤。",
        "subfield": "化学",
        "school_of_thought": "生化学・タンパク質化学史",
        "era_start": 1959,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Hemoglobin",
        "mathematical_formulation": r"\theta = \frac{[O_2]^n}{K_d^n + [O_2]^n} \quad \text{（ヒル方程式）}, \quad n \approx 2.8",
        "verification_status": "url_present",
    },
    {
        "name_ja": "光合成の化学機構（カルビン回路）",
        "name_en": "Chemical Mechanism of Photosynthesis (Calvin Cycle)",
        "name_original": "Calvin-Zyklus",
        "definition": "メルビン・カルビンがアルビン・ベンソンらと1950年代に放射性炭素（¹⁴C）を使って解明したCO₂固定の化学回路。RuBisCO酵素によるCO₂固定、3PGAを経てGAPへの還元、RuBPの再生の3段階からなる。",
        "impact_summary": "1961年ノーベル化学賞。植物・藻類・一部細菌の一次生産の基礎。人工光合成・CO₂資源化・作物改良（高光合成効率C4植物）の理論基盤。地球の炭素循環の核心機構。",
        "subfield": "化学",
        "school_of_thought": "生化学・光合成化学史",
        "era_start": 1950,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Calvin_cycle",
        "mathematical_formulation": r"3CO_2 + 9ATP + 6NADPH \to G3P + 9ADP + 8P_i + 6NADP^+",
        "verification_status": "url_present",
    },
    {
        "name_ja": "シリコン半導体の化学的純化",
        "name_en": "Chemical Purification of Silicon Semiconductors",
        "name_original": "Siliziumreinigung",
        "definition": "シーメンスプロセス（トリクロロシランの水素還元、1950年代）とゾーン精製法（ファイファー、1952年）によりシリコンを99.9999999%（イレブン・ナイン）純度まで精製する技術。現代半導体産業の化学的基盤。",
        "impact_summary": "集積回路・太陽電池・センサーの製造に不可欠な高純度シリコンの生産技術。シリコンバレーの名称の起源。太陽光発電コスト低下（2010年代の劇的下落）の物質的基盤。",
        "subfield": "化学",
        "school_of_thought": "無機・材料化学産業史",
        "era_start": 1952,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Siemens_process",
        "mathematical_formulation": r"SiHCl_3 + H_2 \to Si + 3HCl, \quad \text{純度: } 10^{-10}\text{～}10^{-11}\text{ (不純物分率)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "燃料電池の化学原理",
        "name_en": "Chemical Principles of Fuel Cells",
        "name_original": "Brennstoffzelle",
        "definition": "グローブが1839年に発明した水素と酸素を電気化学的に反応させて電力を得る装置。PEM型（固体高分子）・SOFCなど種類があり、水素社会実現の鍵技術として各国が研究開発を推進中。",
        "impact_summary": "アポロ宇宙船の電源として宇宙開発に貢献（1965年以降）。脱炭素社会の有力技術として水素エネルギーシステムの核心。排出物が水のみという環境特性。",
        "subfield": "化学",
        "school_of_thought": "電気化学・エネルギー化学史",
        "era_start": 1839,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Fuel_cell",
        "mathematical_formulation": r"H_2 + \frac{1}{2}O_2 \to H_2O, \quad \Delta G = -237 \text{ kJ/mol}, \quad \eta = \Delta G / \Delta H = 83\%",
        "verification_status": "url_present",
    },
    {
        "name_ja": "カップリング反応とパラジウム触媒化学",
        "name_en": "Cross-Coupling Reactions and Palladium Catalysis",
        "name_original": "Palladium-katalysierte Kreuzkupplung",
        "definition": "鈴木章・根岸英一・ヘックが1970-80年代に開発したパラジウム触媒を用いた炭素-炭素結合形成反応（鈴木カップリング・根岸カップリング・ヘック反応）。有機ホウ素・亜鉛・臭化アリールなどを接合する。",
        "impact_summary": "2010年ノーベル化学賞（鈴木・根岸・ヘック）。医薬品（イブルチニブ等）・農薬・電子材料・天然物合成の標準的手法。年間何千もの製品合成に使用される。",
        "subfield": "化学",
        "school_of_thought": "有機金属化学・合成化学史",
        "era_start": 1972,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Suzuki_reaction",
        "mathematical_formulation": r"R-X + R'-B(OH)_2 \xrightarrow{Pd, Base} R-R' + X-B(OH)_2",
        "verification_status": "url_present",
    },
    {
        "name_ja": "単分子分光法と蛍光顕微鏡",
        "name_en": "Single-Molecule Spectroscopy and Fluorescence Microscopy",
        "name_original": "Einzelmolekülspektroskopie",
        "definition": "ベッツィッヒ・モーナー・ヘルが1990-2000年代に開発した超解像蛍光顕微鏡（STED・PALM・STORM）。光の回折限界（アッベの限界）を超えてナノメートルスケールの生体分子を観察可能にした。",
        "impact_summary": "2014年ノーベル化学賞。生細胞内のタンパク質・DNA・小胞の動態をリアルタイム観察。神経科学・がん研究・ウイルス感染過程の超解像可視化を実現。",
        "subfield": "化学",
        "school_of_thought": "分析化学・光学顕微鏡史",
        "era_start": 1994,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Super-resolution_microscopy",
        "mathematical_formulation": r"d_{\min} = \frac{\lambda}{2n\sin\alpha} \text{ (アッベ限界)}, \quad d_{\text{STED}} \approx \frac{\lambda}{2n\sin\alpha\sqrt{1+I/I_s}}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "アミノ酸コドンと遺伝暗号の解読",
        "name_en": "Deciphering the Genetic Code (Amino Acid Codons)",
        "name_original": "Genetischer Code",
        "definition": "ニーレンバーグ・コラナ・ホーリーが1960年代に解読した61個のコドンと20種アミノ酸の対応関係（遺伝暗号表）。64通りのコドンのうち3つが終止コドン。生命の普遍的分子言語の解明。",
        "impact_summary": "1968年ノーベル生理学・医学賞。組換えDNA技術・遺伝子編集・mRNAワクチン（COVID-19ワクチン）の理論的基盤。全生物に共通の遺伝暗号は共通祖先の証拠でもある。",
        "subfield": "化学",
        "school_of_thought": "分子生物学・生化学史",
        "era_start": 1961,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Genetic_code",
        "mathematical_formulation": r"4^3 = 64\text{コドン} \to 20\text{アミノ酸} + 3\text{終止コドン}, \quad \text{縮重（縮退）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "固相ペプチド合成（メリフィールド合成）",
        "name_en": "Solid-Phase Peptide Synthesis (Merrifield Synthesis)",
        "name_original": "Festphasenpeptidsynthese",
        "definition": "ロバート・ブルース・メリフィールドが1963年に開発した、固体の支持体に結合させながらアミノ酸を順次連結してペプチドを合成する手法。自動化が容易で任意の配列のペプチド・タンパク質合成を可能にした。",
        "impact_summary": "1984年ノーベル化学賞。インスリン・成長ホルモン・GLP-1（オゼンピック等）などペプチド医薬品製造の基盤。コンビナトリアル化学・創薬スクリーニングの物質供給技術。",
        "subfield": "化学",
        "school_of_thought": "有機合成化学史",
        "era_start": 1963,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Solid-phase_synthesis",
        "mathematical_formulation": r"Y = (1-\epsilon)^n \quad \text{（n段階合成、各段収率 }1-\epsilon\text{）}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "中性子回折と水素結合の研究",
        "name_en": "Neutron Diffraction and Hydrogen Bond Research",
        "name_original": "Neutronenbeugung",
        "definition": "シャルが1949年に確立した中性子回折法。X線が苦手な軽元素（特に水素）の正確な位置決定が可能で、水・氷・生体分子の水素結合の精密構造解析に不可欠。核スピン情報も含む構造決定の補完的手法。",
        "impact_summary": "水・タンパク質・核酸の水素結合ネットワークの精密理解に貢献。燃料電池の電解質・水素貯蔵材料の研究に直結。原子炉からの中性子ビーム利用が産業応用を拡大した。",
        "subfield": "化学",
        "school_of_thought": "構造化学・分析化学史",
        "era_start": 1949,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Neutron_diffraction",
        "mathematical_formulation": r"n\lambda = 2d\sin\theta, \quad \lambda_n = \frac{h}{\sqrt{2m_n E}}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "フラッシュフォトリシスと化学反応過渡状態",
        "name_en": "Flash Photolysis and Transient Chemical States",
        "name_original": "Blitzphotolyse",
        "definition": "ノリッシュとポーターが1949年に開発した超高速フラッシュ光を用いた光化学反応中間体の時間分解観察法。マイクロ秒→ナノ秒→フェムト秒へと時間分解能が向上し、化学反応の遷移状態を観察可能にした。",
        "impact_summary": "1967年ノーベル化学賞。光合成の光反応・酵素反応・大気光化学の速度論的研究の基盤。ツェワイルのフェムト秒化学（1999年ノーベル化学賞）への発展につながった。",
        "subfield": "化学",
        "school_of_thought": "物理化学・反応速度論史",
        "era_start": 1949,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Flash_photolysis",
        "mathematical_formulation": r"A(t) = A_0 e^{-kt} + A_{\infty}, \quad k = k_r + k_{nr}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "抗生物質ストレプトマイシンの発見",
        "name_en": "Discovery of Streptomycin Antibiotic",
        "name_original": "Streptomycin",
        "definition": "ゼルマン・ワックスマンが1943年に放線菌Streptomyces griseusから単離した最初の結核治療薬。ペニシリンが効かないグラム陰性菌にも有効な初のアミノグリコシド系抗生物質。",
        "impact_summary": "1952年ノーベル生理学・医学賞。結核死亡率を劇的に低下させた。土壌微生物からの抗生物質スクリーニングという方法論の確立。アクチノマイシン・クロロマイセチンなど多数の抗生物質発見につながった。",
        "subfield": "化学",
        "school_of_thought": "医薬品化学史",
        "era_start": 1943,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Streptomycin",
        "mathematical_formulation": r"C_{21}H_{39}N_7O_{12}, \quad \text{MIC}_{M.tb} \approx 0.02 \text{ μg/mL}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "レドックス化学と生体内酸化還元",
        "name_en": "Redox Chemistry and Biological Oxidation-Reduction",
        "name_original": "Redoxreaktionen",
        "definition": "電子移動を基本とする酸化還元（レドックス）反応の体系的理解。ナルンスト電位・酸化還元電位・標準電極電位から生体内のNAD⁺/NADH・FAD/FADH₂・チトクロム電子伝達系まで貫く共通原理。",
        "impact_summary": "生命エネルギー代謝の中核概念。ATP産生（ミトコンドリア電子伝達系）・光合成・酵素反応・腐食防止・電池・リチウムイオン電池すべてに関わるレドックス化学の普遍性。",
        "subfield": "化学",
        "school_of_thought": "電気化学・生化学史",
        "era_start": 1890,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Redox",
        "mathematical_formulation": r"E_{\text{cell}} = E^\circ_{\text{cathode}} - E^\circ_{\text{anode}}, \quad \Delta G = -nFE_{\text{cell}}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "溶液化学と疎水性効果",
        "name_en": "Solution Chemistry and Hydrophobic Effect",
        "name_original": "Hydrophober Effekt",
        "definition": "フランクとエヴァンスが1945年に概念化し、カウッフマンが理論化した疎水性効果。非極性分子が水溶液中で集積する現象のエントロピー起動力。タンパク質折り畳み・膜形成・ミセル形成・薬物結合の駆動力。",
        "impact_summary": "生体膜・タンパク質構造・核酸二重鎖の安定性の根本的駆動力。創薬における疎水性ポケットへの結合設計。洗剤・乳化剤・界面活性剤の分子設計の理論基盤。",
        "subfield": "化学",
        "school_of_thought": "溶液化学・生化学史",
        "era_start": 1945,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Hydrophobic_effect",
        "mathematical_formulation": r"\Delta G_{\text{transfer}} = \Delta H - T\Delta S, \quad \Delta S < 0 \text{ (水分子の秩序化)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "メソポーラス材料とゼオライト化学",
        "name_en": "Mesoporous Materials and Zeolite Chemistry",
        "name_original": "Zeolith-Chemie",
        "definition": "天然に存在するアルミノシリケート骨格のゼオライト（アルミナとシリカの三次元多孔質結晶）と、1992年にMobil社が開発したM41Sメソポーラスシリカの化学。規則的なナノ細孔が触媒・吸着・分離機能を提供する。",
        "impact_summary": "石油精製（FCC触媒）・洗剤製造・水処理・CO₂吸着の工業触媒として世界で年間数百万トン使用。薬物送達・燃料電池・光触媒のナノ材料基盤として研究が活発。",
        "subfield": "化学",
        "school_of_thought": "無機材料化学史",
        "era_start": 1756,
        "culture_region": "Global_Synthesis",
        "source_url": "https://en.wikipedia.org/wiki/Zeolite",
        "mathematical_formulation": r"\text{Si/Al比} = \frac{n_{Si}}{n_{Al}}, \quad S_{BET} = \frac{n_m N_A \sigma}{m} \text{ (BET比表面積)}",
        "verification_status": "url_present",
    },
    {
        "name_ja": "放射線化学と放射線分解",
        "name_en": "Radiation Chemistry and Radiolysis",
        "name_original": "Strahlenchemie",
        "definition": "電離放射線（γ線・X線・電子線・重粒子）が物質と相互作用して起こる化学反応の学問。水の放射線分解（OH・・e⁻aq・H₂O₂生成）・DNA損傷・放射線滅菌・放射線重合などを扱う。",
        "impact_summary": "原子力産業（放射線廃棄物処理）・放射線治療（がん放射線療法）・食品照射（滅菌・保存）・放射線測定器開発の理論基盤。ハドロン療法（重粒子線治療）の物理化学的根拠。",
        "subfield": "化学",
        "school_of_thought": "核化学・放射線化学史",
        "era_start": 1910,
        "culture_region": "Western_Europe",
        "source_url": "https://en.wikipedia.org/wiki/Radiation_chemistry",
        "mathematical_formulation": r"G \text{(収率)} = \frac{\Delta N}{100\text{ eV}}, \quad D = \frac{E_{\text{absorbed}}}{m} \text{ (吸収線量 Gy)}",
        "verification_status": "url_present",
    },
    # 追加50件目まで (化学合計50件以上)
    {
        "name_ja": "界面化学とラングミュア・ブロジェット膜",
        "name_en": "Surface Chemistry and Langmuir-Blodgett Films",
        "name_original": "Langmuir-Blodgett-Schicht",
        "definition": "アービング・ラングミュアが1932年（ノーベル化学賞）に確立した界面単分子膜の化学。ランミュア・ブロジェット法で基板上に精密な単分子層を積層でき、分子エレクトロニクス・センサー・光デバイスの材料科学に応用される。",
        "impact_summary": "1932年ノーベル化学賞。ナノスケール薄膜材料の制御された形成の先駆。超薄膜デバイス・バイオセンサー・光学フィルムの基盤技術。自己組織化単分子膜（SAM）研究の先駆。",
        "subfield": "化学",
        "school_of_thought": "界面化学・材料化学史",
        "era_start": 1917,
        "culture_region": "North_America",
        "source_url": "https://en.wikipedia.org/wiki/Langmuir%E2%80%93Blodgett_film",
        "mathematical_formulation": r"p\Gamma = \gamma_0 - \gamma, \quad \Gamma = \frac{1}{N_A \sigma}",
        "verification_status": "url_present",
    },
]

def insert_batch(conn, batch):
    cursor = conn.cursor()
    now = datetime.now(timezone.utc).isoformat()
    inserted = 0
    for c in batch:
        cursor.execute("SELECT id FROM natural_discovery WHERE name_en = ?", (c["name_en"],))
        if cursor.fetchone():
            continue
        uid = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO natural_discovery (
                id, name_ja, name_en, name_original, definition, impact_summary,
                subfield, school_of_thought, era_start, culture_region,
                source_url, mathematical_formulation, verification_status,
                status, data_completeness, created_at, updated_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            uid, c.get("name_ja",""), c.get("name_en",""), c.get("name_original",""),
            c.get("definition",""), c.get("impact_summary",""),
            c.get("subfield",""), c.get("school_of_thought",""),
            c.get("era_start", 2000), c.get("culture_region","Western_Europe"),
            c.get("source_url",""), c.get("mathematical_formulation",""),
            c.get("verification_status","url_present"),
            "active", 85, now, now
        ))
        inserted += 1
    conn.commit()
    return inserted

def main():
    conn = sqlite3.connect(DB_PATH)
    total = 0
    batch = []
    for i, c in enumerate(concepts):
        batch.append(c)
        if len(batch) >= BATCH_SIZE:
            n = insert_batch(conn, batch)
            total += n
            print(f"  Batch {i//BATCH_SIZE+1}: {n} inserted (total so far: {total})")
            batch = []
    if batch:
        n = insert_batch(conn, batch)
        total += n
    print(f"\nBatch2 化学: {total} concepts inserted")
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM natural_discovery")
    print(f"Total in table: {cursor.fetchone()[0]}")
    conn.close()

if __name__ == "__main__":
    main()
