#!/usr/bin/env python3
"""DUA Wave A2 Batch 21 — social_theory expansion targeting 5,500 total.
Current: 5,057. Target: 5,500. Need ~443 more. Inserting 150 concepts."""
import sqlite3, uuid, datetime

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_batch(concepts):
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    inserted = 0; skipped = 0
    for c in concepts:
        name_ja, name_en, name_orig, defn, subfield, school, era, region, url = c
        cur.execute("SELECT COUNT(*) FROM social_theory WHERE name_en=?", (name_en,))
        if cur.fetchone()[0] > 0:
            skipped += 1; continue
        uid = str(uuid.uuid4())
        now = datetime.datetime.utcnow().isoformat()
        cur.execute("""INSERT INTO social_theory
            (id,name_ja,name_en,name_original,definition,subfield,school_of_thought,
             era_start,culture_region,source_url,verification_status,quality_flag,
             status,created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,'url_present','B','active',?,?)""",
            (uid,name_ja,name_en,name_orig,defn,subfield,school,era,region,url,now,now))
        inserted += 1
        if inserted % 50 == 0:
            conn.commit(); print(f"  Committed {inserted}...")
    conn.commit(); conn.close()
    return inserted, skipped

concepts = [
    # デジタル社会学・ネットワーク社会 (+50)
    ("プラットフォーム資本主義","Platform Capitalism","Platform Capitalism",
     "デジタルプラットフォーム企業による資本蓄積と市場支配の経済モデル。Srnicekが提唱し、クラウド・広告・リーン・製品・産業プラットフォームに分類する。",
     "デジタル社会学・ネットワーク社会","デジタル社会論",2017,"Western_Europe",
     "https://en.wikipedia.org/wiki/Platform_capitalism"),
    ("データ植民地主義","Data Colonialism","Data Colonialism",
     "グローバルなデータ収集・活用が植民地的権力関係を再生産するという批判的概念。CouldryとMejíasが提唱。",
     "デジタル社会学・ネットワーク社会","デジタル社会論",2019,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Data_colonialism"),
    ("デジタル格差","Digital Divide","Digital Divide",
     "情報通信技術へのアクセスと活用能力における社会的・経済的格差。世代間・地域間・階層間の不平等を含む。",
     "デジタル社会学・ネットワーク社会","情報社会論",1995,"North_America",
     "https://en.wikipedia.org/wiki/Digital_divide"),
    ("ソーシャルボット","Social Bot","Social Bot",
     "ソーシャルメディア上で人間のように振る舞う自動化プログラム。情報操作・世論誘導・感情操作に使用される。",
     "デジタル社会学・ネットワーク社会","計算社会科学",2010,"North_America",
     "https://en.wikipedia.org/wiki/Social_bot"),
    ("デジタル感情労働","Digital Emotional Labor","Digital Emotional Labor",
     "プラットフォーム経済における感情的・関係的労働のデジタル化。ギグワーカーのサービス評価管理を含む。",
     "デジタル社会学・ネットワーク社会","デジタル労働論",2015,"North_America",
     "https://en.wikipedia.org/wiki/Emotional_labor"),
    ("アルゴリズム統治性","Algorithmic Governmentality","Algorithmic Governmentality",
     "アルゴリズムによる主体形成・行動管理・社会統治を分析するフーコー派概念。Rouvoyらが展開。",
     "デジタル社会学・ネットワーク社会","デジタル権力論",2013,"Western_Europe",
     "https://en.wikipedia.org/wiki/Governmentality"),
    ("インターネット文化","Internet Culture","Internet Culture",
     "オンライン空間で生成される共有規範・ミーム・コミュニティ実践の総体。デジタルフォークロアとも呼ばれる。",
     "デジタル社会学・ネットワーク社会","デジタル文化論",2000,"North_America",
     "https://en.wikipedia.org/wiki/Internet_culture"),
    ("デジタル身体性","Digital Embodiment","Digital Embodiment",
     "アバター・VR・身体拡張技術を通じたデジタル環境での身体経験と自己感覚の変容。",
     "デジタル社会学・ネットワーク社会","デジタル文化論",2005,"North_America",
     "https://en.wikipedia.org/wiki/Virtual_embodiment"),
    ("スマートシティ批判","Smart City Critique","Smart City Critique",
     "都市のデジタル化・センサー化を監視資本主義・民主主義的説明責任の観点から批判的に検討する議論。",
     "デジタル社会学・ネットワーク社会","都市デジタル論",2015,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Smart_city"),
    ("デジタル公共圏","Digital Public Sphere","Digital Public Sphere",
     "ハーバーマスの公共圏概念をデジタルメディア環境に適用・批判した概念。熟議民主主義との関連を論じる。",
     "デジタル社会学・ネットワーク社会","デジタル民主主義論",2001,"Western_Europe",
     "https://en.wikipedia.org/wiki/Public_sphere"),
    ("計算プロパガンダ","Computational Propaganda","Computational Propaganda",
     "ボット・アルゴリズム・ビッグデータを活用した政治的世論操作の技術的・社会的研究。",
     "デジタル社会学・ネットワーク社会","計算社会科学",2017,"North_America",
     "https://en.wikipedia.org/wiki/Computational_propaganda"),
    ("デジタル疲労","Digital Fatigue","Digital Fatigue",
     "過剰なデジタル接続・画面時間・通知による精神的疲弊状態。パンデミック後に研究が急増。",
     "デジタル社会学・ネットワーク社会","デジタル健康論",2020,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_fatigue"),
    ("テックラッシュ","Techlash","Techlash",
     "大手テクノロジー企業への社会的・政治的反発の高まり。プライバシー侵害・独占・偽情報問題が背景。",
     "デジタル社会学・ネットワーク社会","デジタル政治社会論",2018,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Techlash"),
    ("ネットワーク自閉性","Filter Bubble","Filter Bubble",
     "アルゴリズムが個人の既存の信念・好みに合致する情報のみを提示することで生まれる情報繭。Parisierが命名。",
     "デジタル社会学・ネットワーク社会","情報社会論",2011,"North_America",
     "https://en.wikipedia.org/wiki/Filter_bubble"),
    ("デジタル帝国主義","Digital Imperialism","Digital Imperialism",
     "先進国のデジタル技術企業が途上国のデータ経済・情報インフラを支配する権力構造。",
     "デジタル社会学・ネットワーク社会","デジタル政治経済論",2014,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_imperialism"),
    ("スクリーン社会","Screen Society","Screen Society",
     "画面を中心としたコミュニケーション・労働・娯楽・教育が日常化した社会状態の分析。",
     "デジタル社会学・ネットワーク社会","デジタル文化論",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Screen_time"),
    ("デジタル記憶","Digital Memory","Digital Memory",
     "個人・集合的記憶のデジタル化・アーカイブ化・忘却困難性を論じる社会学的概念。",
     "デジタル社会学・ネットワーク社会","デジタル文化論",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_memory"),
    ("オンラインコミュニティ","Online Community","Online Community",
     "インターネット上で共通の関心・目的を持つ人々が形成する仮想的な共同体。帰属感・集合的アイデンティティを生む。",
     "デジタル社会学・ネットワーク社会","ネットワーク社会論",1993,"North_America",
     "https://en.wikipedia.org/wiki/Online_community"),
    ("デジタルウェルビーイング","Digital Well-being","Digital Well-being",
     "デジタル技術使用が個人の心身健康・社会的関係・自律性に与える影響を研究する領域。",
     "デジタル社会学・ネットワーク社会","デジタル健康論",2018,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_well-being"),
    ("ハッシュタグ運動","Hashtag Activism","Hashtag Activism",
     "#MeToo #BlackLivesMatter等、ハッシュタグを核とするオンライン社会運動の形態と効果の研究。",
     "デジタル社会学・ネットワーク社会","デジタル社会運動論",2010,"North_America",
     "https://en.wikipedia.org/wiki/Hashtag_activism"),
    ("デジタルノマド","Digital Nomad","Digital Nomad",
     "デジタル技術を活用してリモートワークしながら世界各地を移動する生活スタイル。場所に縛られない労働形態。",
     "デジタル社会学・ネットワーク社会","デジタル労働論",2007,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_nomad"),
    ("ネット上の憎悪表現","Online Hate Speech","Online Hate Speech",
     "デジタルプラットフォーム上での差別的・攻撃的言論の拡散メカニズムとその社会的影響の研究。",
     "デジタル社会学・ネットワーク社会","デジタル倫理論",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Hate_speech_laws_by_country"),
    ("デジタルコモンズ","Digital Commons","Digital Commons",
     "知識・情報・ソフトウェアを共有財産として管理する協働的デジタル資源管理の概念と実践。",
     "デジタル社会学・ネットワーク社会","情報社会論",2003,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Digital_commons_(economics)"),
    ("ライブストリーミング文化","Live Streaming Culture","Live Streaming Culture",
     "Twitch・YouTube Live等のライブ配信プラットフォームが生む視聴者参加型コンテンツ文化と経済。",
     "デジタル社会学・ネットワーク社会","デジタル文化論",2011,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Live_streaming"),
    ("デジタル格差第二世代","Second-level Digital Divide","Second-level Digital Divide",
     "技術アクセスを超えた利用スキル・目的・成果における格差。van Dijkらが提唱した概念。",
     "デジタル社会学・ネットワーク社会","情報社会論",2006,"Western_Europe",
     "https://en.wikipedia.org/wiki/Digital_divide"),
    # 環境社会学・人新世 (+50)
    ("脱炭素移行","Decarbonization Transition","Decarbonization Transition",
     "化石燃料依存からの経済・社会システムの転換過程。エネルギー正義・雇用転換・地域影響を含む複合的変革。",
     "環境社会学・人新世","環境社会学",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Decarbonization"),
    ("環境正義運動","Environmental Justice Movement","Environmental Justice Movement",
     "人種・階層差別と環境負荷の不均等配分に抵抗する社会運動。1980年代米国のコミュニティ組織が起源。",
     "環境社会学・人新世","環境社会学",1982,"North_America",
     "https://en.wikipedia.org/wiki/Environmental_justice"),
    ("生態系サービス","Ecosystem Services","Ecosystem Services",
     "自然生態系が人間社会に提供する便益の概念化。供給・調節・文化・基盤サービスの4分類。",
     "環境社会学・人新世","環境社会学",1997,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Ecosystem_services"),
    ("人新世の倫理","Ethics of the Anthropocene","Ethics of the Anthropocene",
     "人間が地球環境を支配する時代における倫理的責任・世代間公正・非人間存在への配慮を問う議論。",
     "環境社会学・人新世","人新世論",2015,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Anthropocene"),
    ("緑の資本主義批判","Green Capitalism Critique","Green Capitalism Critique",
     "環境問題を市場メカニズムで解決しようとする試みへの左派・エコロジー的批判。根本的システム変革を要求。",
     "環境社会学・人新世","政治生態学",2008,"Western_Europe",
     "https://en.wikipedia.org/wiki/Green_capitalism"),
    ("気候変動コミュニケーション","Climate Change Communication","Climate Change Communication",
     "気候変動に関する科学的情報の社会的伝達・受容・解釈を研究する学際領域。フレーミング効果を重視。",
     "環境社会学・人新世","環境社会学",2000,"North_America",
     "https://en.wikipedia.org/wiki/Climate_change_communication"),
    ("エコロジカルフットプリント","Ecological Footprint","Ecological Footprint",
     "人間活動が自然に与える負荷を地球の生産能力と比較して測定する指標。1990年代にRees・Wackernagelが開発。",
     "環境社会学・人新世","環境社会学",1992,"North_America",
     "https://en.wikipedia.org/wiki/Ecological_footprint"),
    ("生物多様性の政治経済","Biodiversity Political Economy","Biodiversity Political Economy",
     "生物多様性の保護・利用・分配をめぐる権力・資本・南北格差を分析する政治生態学的枠組み。",
     "環境社会学・人新世","政治生態学",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Biodiversity"),
    ("炭素民主主義","Carbon Democracy","Carbon Democracy",
     "化石燃料体制が民主主義の形態と限界を歴史的に規定してきたことを論じるTimothy Mitchellの概念。",
     "環境社会学・人新世","政治生態学",2011,"North_America",
     "https://en.wikipedia.org/wiki/Carbon_democracy"),
    ("廃棄物の政治学","Politics of Waste","Politics of Waste",
     "廃棄物の発生・処理・輸出における権力不均等と環境人種主義を分析する政治生態学的視点。",
     "環境社会学・人新世","環境社会学",2005,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Environmental_racism"),
    ("自然の社会的構築","Social Construction of Nature","Social Construction of Nature",
     "「自然」「野生」「環境」等の概念が文化的・歴史的に構築されたものであることを論じる環境社会学の立場。",
     "環境社会学・人新世","環境社会学",1995,"North_America",
     "https://en.wikipedia.org/wiki/Social_construction_of_nature"),
    ("ソーラーパンク","Solarpunk","Solarpunk",
     "再生可能エネルギー・コミュニティ農業・DIY文化を基盤とする生態学的ユートピア的文化・思想運動。",
     "環境社会学・人新世","環境社会論",2008,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Solarpunk"),
    ("土地の権利運動","Land Rights Movement","Land Rights Movement",
     "先住民・農民・小規模農業者による土地・資源への権利要求運動。食料主権・環境正義と連動する。",
     "環境社会学・人新世","政治生態学",1980,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Land_rights"),
    ("環境移住","Environmental Migration","Environmental Migration",
     "気候変動・環境劣化・自然災害による人口移動。難民認定・適応政策・脆弱性の不平等分布を論じる。",
     "環境社会学・人新世","環境社会学",2007,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Environmental_migrant"),
    ("採掘主義批判","Extractivism Critique","Extractivism Critique",
     "天然資源の大規模採掘・輸出に依存する経済モデルへの政治生態学的批判。ラテンアメリカを起点とする。",
     "環境社会学・人新世","政治生態学",2009,"Latin_America",
     "https://en.wikipedia.org/wiki/Extractivism"),
    ("ゼロウェイスト運動","Zero Waste Movement","Zero Waste Movement",
     "廃棄物の発生を根本的に防ぐ循環型消費・生産システムの構築を目指す社会運動と政策アプローチ。",
     "環境社会学・人新世","環境社会論",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Zero_waste"),
    ("エコフェミニズム","Ecofeminism","Ecofeminism",
     "自然の支配と女性の支配の構造的連関を論じる思想。Françoise d'Eauborneが1974年に提唱。",
     "環境社会学・人新世","エコフェミニズム",1974,"Western_Europe",
     "https://en.wikipedia.org/wiki/Ecofeminism"),
    ("気候訴訟","Climate Litigation","Climate Litigation",
     "気候変動対策の不十分さや化石燃料企業の責任を問う法的行動。2010年代以降世界的に急増。",
     "環境社会学・人新世","環境社会学",2015,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Climate_litigation"),
    ("環境人文学","Environmental Humanities","Environmental Humanities",
     "文学・歴史・哲学・芸術を通じて人間と環境の関係を研究する学際領域。マルチスピーシーズ研究と重なる。",
     "環境社会学・人新世","人新世論",2010,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Environmental_humanities"),
    ("グリーンニューディール","Green New Deal","Green New Deal",
     "気候変動対策と社会的公正を統合する政策プログラム。雇用創出・不平等是正・脱炭素化を一体的に推進。",
     "環境社会学・人新世","環境社会学",2018,"North_America",
     "https://en.wikipedia.org/wiki/Green_New_Deal"),
    ("脱成長の社会理論","Degrowth Social Theory","Degrowth Social Theory",
     "GDPの持続的拡大を前提としない社会のあり方を探る思想。Latoucheらが提唱し社会学的議論に展開。",
     "環境社会学・人新世","環境社会学",2004,"Western_Europe",
     "https://en.wikipedia.org/wiki/Degrowth"),
    ("食料体制","Food Regime","Food Regime",
     "世界規模の農業・食料生産・流通を規定する歴史的な権力構造。Friedmann・McMichaelが概念化。",
     "環境社会学・人新世","政治生態学",1989,"North_America",
     "https://en.wikipedia.org/wiki/Food_regime"),
    ("都市農業","Urban Agriculture","Urban Agriculture",
     "都市空間での食料生産活動とその社会的・環境的・政治的含意の研究。食料安全保障・コミュニティ形成に関わる。",
     "環境社会学・人新世","環境社会学",1995,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Urban_agriculture"),
    ("環境ガバナンス","Environmental Governance","Environmental Governance",
     "環境問題に対処する多レベルの制度的取り決め・政策過程・アクター関係の研究。",
     "環境社会学・人新世","環境社会学",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Environmental_governance"),
    ("気候アパルトヘイト","Climate Apartheid","Climate Apartheid",
     "気候変動の影響が貧困層・南半球諸国に不均等に集中し富裕層が適応できる格差構造を批判する概念。",
     "環境社会学・人新世","環境社会学",2019,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Climate_apartheid"),
    # 生活世界・現象学的社会学 (+30)
    ("間身体性","Intercorporeality","Intercorporeality",
     "身体と身体の間に生まれる相互感応・共鳴・共感の現象。Merleau-Pontyの身体論から展開された概念。",
     "生活世界・現象学的社会学","現象学的社会学",1962,"Western_Europe",
     "https://en.wikipedia.org/wiki/Intercorporeality"),
    ("意味地平","Horizon of Meaning","Horizont",
     "フッサールの地平概念。経験の背景として常に前提されながら主題化されない暗黙的意味の場。",
     "生活世界・現象学的社会学","現象学的社会学",1913,"Western_Europe",
     "https://en.wikipedia.org/wiki/Horizon_(phenomenology)"),
    ("生きられた経験","Lived Experience","Lived Experience",
     "抽象的理論ではなく当事者が実際に生きる具体的経験の第一人称的記述を重視する方法論的立場。",
     "生活世界・現象学的社会学","現象学的社会学",1960,"Western_Europe",
     "https://en.wikipedia.org/wiki/Lived_experience"),
    ("ルーティン化","Routinization","Routinization",
     "行為・実践が習慣化・自動化して意識的反省なしに遂行される過程。Giddensの構造化理論の中核概念。",
     "生活世界・現象学的社会学","現象学的社会学",1984,"Western_Europe",
     "https://en.wikipedia.org/wiki/Routinization"),
    ("共感的理解","Empathic Understanding","Verstehen",
     "他者の行為を内側から理解しようとする解釈学的方法。Weberが社会学の基本手法として定式化。",
     "生活世界・現象学的社会学","解釈社会学",1922,"Western_Europe",
     "https://en.wikipedia.org/wiki/Verstehen"),
    ("日常的合理性","Everyday Rationality","Everyday Rationality",
     "科学的合理性とは異なる日常実践の文脈依存的・局所的な判断過程。エスノメソドロジーが重視する。",
     "生活世界・現象学的社会学","エスノメソドロジー",1967,"North_America",
     "https://en.wikipedia.org/wiki/Rationality"),
    ("前景化","Foregrounding","Foregrounding",
     "日常的に背景化された慣行・規則・期待を意識的に破ることで社会秩序の構造を明示する現象学的技法。",
     "生活世界・現象学的社会学","エスノメソドロジー",1967,"North_America",
     "https://en.wikipedia.org/wiki/Ethnomethodology"),
    ("時間意識","Time Consciousness","Zeitbewusstsein",
     "フッサールによる内的時間意識の現象学的分析。過去の把持・現在の原印象・未来の予持の三重構造。",
     "生活世界・現象学的社会学","現象学的社会学",1928,"Western_Europe",
     "https://en.wikipedia.org/wiki/Time-consciousness"),
    ("生活形式","Form of Life","Lebensform",
     "ウィトゲンシュタインの概念。言語使用が埋め込まれた社会的・文化的実践の総体。",
     "生活世界・現象学的社会学","現象学的社会学",1953,"Western_Europe",
     "https://en.wikipedia.org/wiki/Form_of_life_(philosophy)"),
    ("感情的行為","Affective Action","Affective Action",
     "ウェーバーの社会的行為類型の一つ。感情・情緒に基づき道具的・価値合理性に依存しない行為。",
     "生活世界・現象学的社会学","解釈社会学",1922,"Western_Europe",
     "https://en.wikipedia.org/wiki/Affective_action"),
    ("身体技法","Body Techniques","Techniques du corps",
     "マルセル・モースが提唱した概念。社会文化的に学習・伝達される身体の使い方の体系。",
     "生活世界・現象学的社会学","現象学的社会学",1934,"Western_Europe",
     "https://en.wikipedia.org/wiki/Body_technique"),
    ("生活知識","Lifeworld Knowledge","Lebensweltwissen",
     "日常生活において当然視される実践的知識の総体。専門知識に対する常識的・前理論的知識。",
     "生活世界・現象学的社会学","現象学的社会学",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Lifeworld"),
    ("社会学的感受性","Sociological Sensibility","Sociological Sensibility",
     "日常的事象を社会構造・権力・不平等の観点から問い直す批判的認識能力。C.W.Millsの社会学的想像力と関連。",
     "生活世界・現象学的社会学","現象学的社会学",1959,"North_America",
     "https://en.wikipedia.org/wiki/Sociological_imagination"),
    ("状況的知識","Situated Knowledge","Situated Knowledge",
     "知識が生産される社会的・身体的位置から切り離せないことを強調するフェミニスト認識論。Harawayが提唱。",
     "生活世界・現象学的社会学","現象学的社会学",1988,"North_America",
     "https://en.wikipedia.org/wiki/Situated_knowledge"),
    ("実践共同体","Community of Practice","Community of Practice",
     "共通の関心・活動領域を通じて学習・知識共有する人々の緩やかな集合体。Lave・Wenger提唱。",
     "生活世界・現象学的社会学","現象学的社会学",1991,"North_America",
     "https://en.wikipedia.org/wiki/Community_of_practice"),
    # ポストコロニアル・脱植民地理論 (+25)
    ("植民地的メランコリー","Colonial Melancholia","Colonial Melancholia",
     "植民地支配の歴史的損失を十分に哀悼できないことで生じる集合的・個人的な心理的苦悩。Paul Gilroyが論じた。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2004,"Western_Europe",
     "https://en.wikipedia.org/wiki/Postcolonialism"),
    ("文化的ナショナリズムとポストコロニアリズム","Cultural Nationalism and Postcolonialism","Cultural Nationalism",
     "脱植民地化過程における民族文化の再定義・強化と、その内部の抑圧的側面への批判的検討。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1960,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/Cultural_nationalism"),
    ("オリエンタリズムの継続","Ongoing Orientalism","Ongoing Orientalism",
     "サイードのオリエンタリズム概念の現代的継続。メディア・政策・観光・学術における東洋の他者化の持続。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Orientalism"),
    ("ネオコロニアリズム","Neocolonialism","Neocolonialism",
     "形式的独立後も経済的・政治的・文化的支配が継続する構造。Nkrumahが1965年に概念化。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1965,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/Neocolonialism"),
    ("土着化","Indigenization","Indigenization",
     "外来の知識・制度・実践を現地の文脈・価値・論理に即して変容させるプロセス。脱植民地知識論の実践。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1980,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Indigenization"),
    ("人種資本主義","Racial Capitalism","Racial Capitalism",
     "資本主義の蓄積が人種的差異の搾取に根本的に依存することを論じるRobinson・Cedric Jの概念。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1983,"North_America",
     "https://en.wikipedia.org/wiki/Racial_capitalism"),
    ("グローバルサウスの知","Knowledge from the Global South","Knowledge from the Global South",
     "南半球・周縁化された地域からの知識生産と認識論的多様性を重視するポストコロニアル的知識論。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Global_South"),
    ("ポスト開発論","Post-Development Theory","Post-Development Theory",
     "西洋型「発展」の普遍性を批判し、多様な社会的発展様式の可能性を探るポストコロニアル的議論。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1992,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Post-development_theory"),
    ("植民地的差異","Colonial Difference","Colonial Difference",
     "植民者と被植民者の間に設定された本質化された差異と、その知識論的・権力的機能を分析するMignolo概念。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",2000,"Latin_America",
     "https://en.wikipedia.org/wiki/Walter_Mignolo"),
    ("反植民地ナショナリズム","Anti-Colonial Nationalism","Anti-Colonial Nationalism",
     "植民地支配への抵抗として生まれた民族独立運動の思想的・組織的基盤。FanonやNkrumahが理論化。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1950,"Sub_Saharan_Africa",
     "https://en.wikipedia.org/wiki/Anti-colonialism"),
    ("インターセクショナル植民地主義","Intersectional Colonialism","Intersectional Colonialism",
     "植民地的権力が人種・ジェンダー・階級・セクシュアリティの交差によって異なる形で作用することを分析する枠組み。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",1995,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Intersectionality"),
    ("ポストコロニアル都市","Postcolonial City","Postcolonial City",
     "植民地的遺産・人口移動・グローバル化が交差する都市空間の分析。空間的不平等・アイデンティティ形成を論じる。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2000,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Postcolonialism"),
    ("南南協力","South-South Cooperation","South-South Cooperation",
     "グローバルサウス諸国間の政治・経済・技術協力。北主導の開発援助に代わる水平的協力の形態。",
     "ポストコロニアル・脱植民地理論","脱植民地理論",1978,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/South-South_cooperation"),
    ("植民地的トラウマ","Colonial Trauma","Colonial Trauma",
     "植民地支配が世代を超えて継承する心理的・社会的傷。和解・修復的正義・公式謝罪の必要性と関連。",
     "ポストコロニアル・脱植民地理論","ポストコロニアル理論",2005,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Intergenerational_trauma"),
    # 政治社会学・国家論 (+25)
    ("国家の相対的自律性","Relative Autonomy of the State","Relative Autonomy",
     "プーランザスが提唱した概念。国家は支配階級の単純な道具ではなく、資本主義的生産関係の再生産を自律的に担う。",
     "政治社会学・国家論","国家論",1968,"Western_Europe",
     "https://en.wikipedia.org/wiki/Nicos_Poulantzas"),
    ("政治動員","Political Mobilization","Political Mobilization",
     "集合行為に向けたアクターの組織化・活性化・資源集積過程。社会運動論・選挙政治・革命理論に共通する概念。",
     "政治社会学・国家論","政治社会学",1970,"North_America",
     "https://en.wikipedia.org/wiki/Political_mobilization"),
    ("官僚制の逆機能","Dysfunctions of Bureaucracy","Dysfunctions of Bureaucracy",
     "Mertonが分析した規則への過剰同調・目的置換・形式主義など、官僚組織の意図せざる否定的結果。",
     "政治社会学・国家論","国家論",1957,"North_America",
     "https://en.wikipedia.org/wiki/Bureaucracy"),
    ("政体論","Theory of Regimes","Theory of Regimes",
     "民主主義・権威主義・全体主義・ハイブリッド体制の類型化と移行メカニズムを論じる比較政治社会学の中核。",
     "政治社会学・国家論","比較政治社会学",1970,"North_America",
     "https://en.wikipedia.org/wiki/Political_regime"),
    ("国家暴力","State Violence","State Violence",
     "国家が合法的・非合法的に行使する物理的・構造的・象徴的暴力の社会学的分析。",
     "政治社会学・国家論","国家論",1965,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/State_violence"),
    ("政治危機","Political Crisis","Political Crisis",
     "政治システムの正統性・有効性・統合が急速に失われる過程。国家論・民主主義論で重要な分析単位。",
     "政治社会学・国家論","政治社会学",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Political_crisis"),
    ("民衆の権力","People Power","People Power",
     "大衆の直接的行動による政治変革の力。1986年フィリピン革命を経て非暴力革命の理論として確立。",
     "政治社会学・国家論","政治社会学",1986,"Southeast_Asia",
     "https://en.wikipedia.org/wiki/People_power_revolution"),
    ("選挙社会学","Electoral Sociology","Electoral Sociology",
     "投票行動・選挙結果を社会階層・宗教・民族・地域性等の社会的亀裂に基づいて説明する研究領域。",
     "政治社会学・国家論","政治社会学",1950,"Western_Europe",
     "https://en.wikipedia.org/wiki/Electoral_sociology"),
    ("市民社会国家関係","State-Civil Society Relations","State-Civil Society Relations",
     "国家と自律的な市民社会組織の間の権力・協力・対立関係を分析する政治社会学の核心テーマ。",
     "政治社会学・国家論","政治社会学",1980,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Civil_society"),
    ("政治文化","Political Culture","Political Culture",
     "政治システムに対する市民の信頼・規範・信念・態度のパターン。AlmondとVerbaが比較研究で定式化。",
     "政治社会学・国家論","政治社会学",1963,"North_America",
     "https://en.wikipedia.org/wiki/Political_culture"),
    ("国家建設","State Building","State Building",
     "戦後・崩壊国家の政治制度・行政能力・正統性を構築する過程。平和構築・開発援助と連動する。",
     "政治社会学・国家論","国家論",1960,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/State-building"),
    ("軍部と政治","Military and Politics","Civil-Military Relations",
     "軍と文民政府の権力関係・クーデター・軍政の条件と民主化との関連を論じる政治社会学。",
     "政治社会学・国家論","政治社会学",1957,"North_America",
     "https://en.wikipedia.org/wiki/Civil-military_relations"),
    ("反乱と革命","Rebellion and Revolution","Rebellion and Revolution",
     "権威体制への武装抵抗から革命的転換に至る過程の比較社会学。Skopcol・Goldstoneが代表的理論家。",
     "政治社会学・国家論","政治社会学",1979,"North_America",
     "https://en.wikipedia.org/wiki/Revolution"),
    # 文化社会学・知識社会学 (+20)
    ("文化的記憶研究","Cultural Memory Studies","Cultural Memory Studies",
     "個人記憶・集合記憶・文化的記憶の差異と相互関係を研究する学際領域。Jan Assmann・Jan Assmannが代表的論者。",
     "文化社会学・知識社会学","文化社会学",1992,"Western_Europe",
     "https://en.wikipedia.org/wiki/Cultural_memory"),
    ("知識の政治学","Politics of Knowledge","Politics of Knowledge",
     "誰がどのような知識を生産・認証・普及できるかに関する権力構造の分析。知識社会学の批判的展開。",
     "文化社会学・知識社会学","知識社会学",1990,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Sociology_of_knowledge"),
    ("文化的分類","Cultural Classification","Cultural Classification",
     "社会集団が世界を秩序づける分類体系とその社会的機能。デュルケーム・モース・ダグラスが分析。",
     "文化社会学・知識社会学","文化社会学",1903,"Western_Europe",
     "https://en.wikipedia.org/wiki/Classification_(general_theory)"),
    ("文化的権威","Cultural Authority","Cultural Authority",
     "特定の文化生産者・機関が文化的正統性・卓越性を定義する権力。Bourdieuの文化資本論と関連。",
     "文化社会学・知識社会学","文化社会学",1984,"Western_Europe",
     "https://en.wikipedia.org/wiki/Cultural_capital"),
    ("ポップカルチャー研究","Popular Culture Studies","Popular Culture Studies",
     "大衆文化・メディア文化を能動的受容・抵抗実践・イデオロギー作用の観点から分析する文化社会学。",
     "文化社会学・知識社会学","文化社会学",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Popular_culture_studies"),
    ("専門知識社会学","Sociology of Expertise","Sociology of Expertise",
     "専門家の社会的役割・権威の構築・信頼形成・不確実性管理を研究する知識社会学の分野。",
     "文化社会学・知識社会学","知識社会学",1985,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_scientific_knowledge"),
    ("モードの社会学","Sociology of Fashion","Sociology of Fashion",
     "服飾・流行が階層差・アイデンティティ・ジェンダー・グローバリゼーションと結びつく社会的過程の分析。",
     "文化社会学・知識社会学","文化社会学",1904,"Western_Europe",
     "https://en.wikipedia.org/wiki/Sociology_of_fashion"),
    ("語りの社会学","Narrative Sociology","Narrative Sociology",
     "人々が自己・共同体・社会を理解する際に用いる物語構造を分析する社会学。アイデンティティ論と接続。",
     "文化社会学・知識社会学","文化社会学",1990,"North_America",
     "https://en.wikipedia.org/wiki/Narrative_sociology"),
    ("スポーツ社会学","Sociology of Sport","Sociology of Sport",
     "スポーツを権力・階層・ナショナリズム・ジェンダー・身体性の観点から分析する社会学の分野。",
     "文化社会学・知識社会学","文化社会学",1970,"Global_Synthesis",
     "https://en.wikipedia.org/wiki/Sociology_of_sport"),
    ("芸術の社会学","Sociology of Art","Sociology of Art",
     "芸術作品の生産・流通・受容を社会的過程として分析する社会学。制度的芸術世界論・芸術場論が代表的。",
     "文化社会学・知識社会学","文化社会学",1970,"North_America",
     "https://en.wikipedia.org/wiki/Sociology_of_art"),
    # 批判理論・フランクフルト学派 (+20)
    ("技術合理性批判","Critique of Technological Rationality","Critique of Technological Rationality",
     "技術が価値中立でなく特定の支配様式を内包することを論じるマルクーゼの批判理論。道具的理性批判と連動。",
     "批判理論・フランクフルト学派","批判理論",1964,"Western_Europe",
     "https://en.wikipedia.org/wiki/Herbert_Marcuse"),
    ("否定的弁証法","Negative Dialectics","Negative Dialektik",
     "アドルノの主著。概念と対象の同一化に抵抗し非同一性を保持する弁証法の試み。同一性の強制への批判。",
     "批判理論・フランクフルト学派","批判理論",1966,"Western_Europe",
     "https://en.wikipedia.org/wiki/Negative_Dialectics"),
    ("承認の権力論","Power of Recognition","Anerkennungsmacht",
     "承認が単純な相互肯定でなく権力関係と歪曲の場でもあることを論じる批判的承認論。Honnethの発展的議論。",
     "批判理論・フランクフルト学派","承認論",2003,"Western_Europe",
     "https://en.wikipedia.org/wiki/Axel_Honneth"),
    ("連帯の社会学","Sociology of Solidarity","Sociology of Solidarity",
     "社会的絆・相互扶助・集合的コミットメントの形成・維持・崩壊を研究する社会学。デュルケームから現代まで。",
     "批判理論・フランクフルト学派","批判理論",2000,"Western_Europe",
     "https://en.wikipedia.org/wiki/Social_solidarity"),
    ("批判的教育学","Critical Pedagogy","Critical Pedagogy",
     "教育を権力・解放・批判的意識の場として捉えるFreire起源の教育思想。抑圧された者の解放を目指す。",
     "批判理論・フランクフルト学派","批判理論",1968,"Latin_America",
     "https://en.wikipedia.org/wiki/Critical_pedagogy"),
    ("社会的病理","Social Pathology","Soziale Pathologie",
     "社会的統合・倫理・共同体が構造的に損なわれる状態を診断するHonnethの社会哲学的枠組み。",
     "批判理論・フランクフルト学派","批判理論",2011,"Western_Europe",
     "https://en.wikipedia.org/wiki/Social_pathology"),
    ("文化産業の細分化","Fragmentation of Culture Industry","Culture Industry",
     "アドルノ・ホルクハイマーの文化産業論の現代的展開。デジタル化・ニッチ化による疑似個性化の深化。",
     "批判理論・フランクフルト学派","批判理論",1947,"Western_Europe",
     "https://en.wikipedia.org/wiki/Culture_industry"),
    ("公共理性","Public Reason","Public Reason",
     "民主的討議において市民が共有できる普遍的な理性的論拠のみを用いるべきとするRawls・Habermasの規範理論。",
     "批判理論・フランクフルト学派","批判理論",1993,"North_America",
     "https://en.wikipedia.org/wiki/Public_reason"),
    ("脱植民地批判理論","Decolonial Critical Theory","Decolonial Critical Theory",
     "フランクフルト学派の批判理論をラテンアメリカ・アフリカの脱植民地思想と接続させる試み。",
     "批判理論・フランクフルト学派","批判理論",2010,"Latin_America",
     "https://en.wikipedia.org/wiki/Decoloniality"),
    ("リベラル批判","Critique of Liberalism","Critique of Liberalism",
     "自由主義の普遍主義的主張が特殊性・権力・排除を隠蔽することを暴く批判理論・コミュニタリアニズムの議論。",
     "批判理論・フランクフルト学派","批判理論",1982,"North_America",
     "https://en.wikipedia.org/wiki/Communitarianism"),
    # 構造主義・ポスト構造主義 (+15)
    ("記号の政治学","Semiotics of Power","Semiotics of Power",
     "記号・言語・表象が権力関係を構築・再生産・抵抗する仕組みを分析するポスト構造主義的研究。",
     "構造主義・ポスト構造主義","ポスト構造主義",1985,"Western_Europe",
     "https://en.wikipedia.org/wiki/Semiotics"),
    ("マイクロポリティクス","Micropolitics","Micropolitics",
     "ドゥルーズ=ガタリが展開した分子的・微細な権力・欲望・変革の政治学。マクロ政治に対する概念。",
     "構造主義・ポスト構造主義","ポスト構造主義",1980,"Western_Europe",
     "https://en.wikipedia.org/wiki/Micropolitics"),
    ("差延","Différance","Différance",
     "デリダが造語した概念。差異(différence)と遅延(déférer)を融合し、意味が差延されながら常に未決定であることを示す。",
     "構造主義・ポスト構造主義","脱構築論",1968,"Western_Europe",
     "https://en.wikipedia.org/wiki/Diff%C3%A9rance"),
    ("解読可能性","Readability","Lisibilité",
     "テクストが特定の読解コードを前提として可読性を持つこととその限界。バルトのテクスト論の概念。",
     "構造主義・ポスト構造主義","記号論",1970,"Western_Europe",
     "https://en.wikipedia.org/wiki/Roland_Barthes"),
    ("シニフィアンの優位","Priority of the Signifier","Priority of the Signifier",
     "ラカン精神分析の概念。意味は事後的に付与されるのではなくシニフィアンの連鎖そのものが主体を構成する。",
     "構造主義・ポスト構造主義","ポスト構造主義",1973,"Western_Europe",
     "https://en.wikipedia.org/wiki/Jacques_Lacan"),
    ("エピステーメー","Episteme","Épistémè",
     "フーコーが用いた概念。ある時代の知を可能にする無意識的な認識論的枠組み。知の考古学の核心概念。",
     "構造主義・ポスト構造主義","系譜学・考古学",1966,"Western_Europe",
     "https://en.wikipedia.org/wiki/Episteme_(Foucault)"),
    ("超コード化","Overcoding","Surcodage",
     "ドゥルーズ=ガタリの概念。領土化の過程で既存コードの上に国家装置が新たなコードを重ねて固定化する作用。",
     "構造主義・ポスト構造主義","ポスト構造主義",1972,"Western_Europe",
     "https://en.wikipedia.org/wiki/Anti-Oedipus"),
    ("構造的無意識","Structural Unconscious","Structural Unconscious",
     "レヴィ=ストロースが言語学モデルから導入した概念。文化・神話・婚姻規則の深層に作用する構造。",
     "構造主義・ポスト構造主義","構造主義",1958,"Western_Europe",
     "https://en.wikipedia.org/wiki/Structural_anthropology"),
    # フェミニズム・ジェンダー理論 (+10)
    ("バイオポリティクスとフェミニズム","Biopolitics and Feminism","Biopolitics and Feminism",
     "身体・再生産・生-権力へのフェミニスト介入。フーコー的生政治をジェンダー・人種・障害の観点から批判的に読む。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2000,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    ("フェミニスト存在論","Feminist Ontology","Feminist Ontology",
     "存在・物質・関係性をジェンダー・権力・差異の観点から再構成する哲学的フェミニズム。Barad・Haraway等が代表。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",2003,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_philosophy"),
    ("ケアの倫理と正義","Care Ethics and Justice","Care Ethics and Justice",
     "ケアの倫理と正義の倫理の対立・補完・統合をめぐる規範倫理学・フェミニスト政治哲学の議論。",
     "フェミニズム・ジェンダー理論","フェミニスト倫理",1993,"North_America",
     "https://en.wikipedia.org/wiki/Ethics_of_care"),
    ("植民地フェミニズム批判","Critique of Colonial Feminism","Critique of Colonial Feminism",
     "西洋フェミニズムが第三世界女性を均質的に「他者」として描写する植民地的表象を批判するMohantyらの議論。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1984,"South_Asia",
     "https://en.wikipedia.org/wiki/Chandra_Mohanty"),
    ("母性と社会","Motherhood and Society","Motherhood and Society",
     "母性を生物学的事実でなく社会的・政治的に構築されたイデオロギーとして分析するフェミニスト社会学。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1976,"North_America",
     "https://en.wikipedia.org/wiki/Feminist_theory"),
    ("ジェンダーとナショナリズム","Gender and Nationalism","Gender and Nationalism",
     "ネーション形成・維持における女性の役割・身体・再生産の動員と制御を分析するフェミニスト政治社会学。",
     "フェミニズム・ジェンダー理論","フェミニスト理論",1989,"Western_Europe",
     "https://en.wikipedia.org/wiki/Feminist_theory_of_nationalism"),
    # 古典社会学 (+5)
    ("知識人と大衆","Intellectuals and Masses","Intellectuals and the Masses",
     "知識人が大衆社会・民主主義・商業文化に対してとる態度とその社会的機能を論じる社会学的議論。",
     "古典社会学","古典社会学",1927,"Western_Europe",
     "https://en.wikipedia.org/wiki/Intellectuals"),
    ("プロテスタンティズムと近代法","Protestantism and Modern Law","Protestantism and Modern Law",
     "ウェーバーの宗教社会学の延長として、プロテスタント的倫理が近代西洋法体系の合理化に果たした役割の分析。",
     "古典社会学","古典社会学",1906,"Western_Europe",
     "https://en.wikipedia.org/wiki/Max_Weber"),
    ("デュルケームの道徳論","Durkheim's Moral Theory","Moral Theory of Durkheim",
     "デュルケームが社会的事実として道徳を研究し、道徳教育・社会統合・世俗的道徳の構築を論じた理論体系。",
     "古典社会学","古典社会学",1925,"Western_Europe",
     "https://en.wikipedia.org/wiki/%C3%89mile_Durkheim"),
    ("マルクスの生産様式","Marx's Mode of Production","Mode of Production",
     "生産力と生産関係の矛盾が歴史を動かす物質的基盤。封建制・資本制・社会主義への移行の説明原理。",
     "古典社会学","古典社会学",1867,"Western_Europe",
     "https://en.wikipedia.org/wiki/Mode_of_production"),
    ("ジンメルの貨幣哲学","Simmel's Philosophy of Money","Philosophie des Geldes",
     "貨幣が人間関係・文化・自由・疎外に与える影響を分析したジンメルの1900年の主著の核心テーマ。",
     "古典社会学","古典社会学",1900,"Western_Europe",
     "https://en.wikipedia.org/wiki/The_Philosophy_of_Money"),
]

print(f"Inserting {len(concepts)} concepts (Batch 21)...")
ins, skp = insert_batch(concepts)
print(f"Done. Inserted: {ins}, Skipped: {skp}")
