#!/usr/bin/env python3
"""電気電子工学 Batch 4: ee_b4_001–050"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
    ("ee_b4_001","電力変換器熱設計","Power Converter Thermal Design","",
     "パワー半導体の発熱をヒートシンク・TIM・相変化材料・液冷で放熱しジャンクション温度を許容値以内に維持する設計技術。",
     "EV牽引インバータの熱設計がモジュール寿命と電力密度の双方を決定する核心技術。",
     "電気電子工学","熱・パワーエレクトロニクス",1980,None,"手法","電力変換・EV",
     "パワーデバイスの高発熱密度を効率的に放熱する必要がある電力変換器設計","EV牽引インバータ・太陽光PCS・UPS",
     "デバイスジャンクション温度のサイクル耐性(ΔTj)をどう確保するか？TIMの経年劣化は？",
     "空冷自然対流","熱抵抗,ジャンクション温度,TIM,液冷システム","thermal design,junction temperature,TIM,heat sink,liquid cooling",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/8048508",
     "欧米","high",
     r"熱抵抗: $R_{th,JC} = (T_J - T_C)/P_{loss}$. Foster等価回路: $Z_{th}(t) = \sum_i R_i(1-e^{-t/\tau_i})$. 寿命: $N_f \propto \Delta T_j^{-n} \exp(E_a/kT_{Jm})$ ($n\approx5\text{-}6$). $P_{cond} = V_{CE0}I_D + r_C I_D^2$.",
     "url_present"),

    ("ee_b4_002","超音波センシング","Ultrasonic Sensing","",
     "圧電変換器を用いた距離計測・流量測定・材料検査・医療診断のためのパルスエコー・連続波超音波技術。",
     "超音波流量計が非侵襲でパイプライン流量を精密計測し石油・ガス産業の計量精度を確保。",
     "電気電子工学","センサ工学",1940,None,"手法","センシング・計測・医療",
     "非接触・非侵襲での内部構造や流体計測が必要な場合","工業流量計・医療エコー・自動車パーキングセンサ",
     "音速の温度依存性をどう補正するか？多重反射・クロストークの除去は？",
     "光学センシング","超音波センサ,圧電素子,超音波流量計,NDT","ultrasonic sensing,piezoelectric,ToF,flow measurement,NDT",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/1455799",
     "欧米","high",
     r"ToF距離: $d = c \cdot t_{ToF}/2$. 音速温度補正: $c(T) = 331.3\sqrt{1+T/273.15}$ m/s. 超音波流量: $v_f = \frac{D}{2\cos\theta}\frac{f_{up}-f_{down}}{f_0}$. アレー解像度: $\delta x = \lambda/NA$.",
     "url_present"),

    ("ee_b4_003","デジタル電源制御","Digital Power Control","",
     "マイコン・DSP・FPGAを用いてPWM変換器をデジタル制御しアナログ制御より高度な適応制御・保護・通信機能を実現する技術。",
     "データセンター電源のデジタル制御でPMBus通信と電力最適化を実現し電力効率を95%以上に向上。",
     "電気電子工学","パワーエレクトロニクス",2000,None,"手法","電源設計・データセンター",
     "高精度・適応的・通信可能な電源制御システム設計","サーバー電源・通信機器電源・産業用UPS",
     "デジタル制御のサンプリング遅延が安定性に与える影響は？ADC分解能の要件は？",
     "アナログ制御IC","デジタル電源制御,PMBus,DSP,PWM制御","digital power control,PMBus,DSP,adaptive control,switched mode",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/4285548",
     "欧米","high",
     r"デジタルPID: $d(k) = K_p e(k) + K_i T_s \sum e + K_d\frac{e(k)-e(k-1)}{T_s}$. z変換PID: $D(z) = K_p + K_i\frac{T_s z}{z-1} + K_d\frac{z-1}{T_s z}$. 安定条件: z平面内で閉ループ極 $|z| < 1$.",
     "url_present"),

    ("ee_b4_004","光集積回路","Photonic Integrated Circuit","PIC",
     "光導波路・変調器・分波器・光検出器・レーザーを単一チップ上に集積した光ICの設計・製造技術。InP・SiPh基板で実現。",
     "データセンター400G光トランシーバのPIC化でコスト・消費電力・サイズを10分の1に削減。",
     "電気電子工学","フォトニクス・光通信",1985,None,"手法","光通信・データセンター",
     "複数の光機能素子をチップ統合した高度な光信号処理が必要な場合","高速光通信トランシーバ・LiDAR・光量子コンピュータ",
     "InP上の能動・受動素子の集積プロセス整合は？PIC設計EDAツールの現状は？",
     "ディスクリート光部品","光集積回路,InP,シリコンフォトニクス,光コンポーネント","PIC,photonic integrated circuit,InP,silicon photonics,laser integration",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/6247979",
     "欧米","high",
     r"导波路伝搬損失: $\alpha_{WG} \sim 0.1$ dB/cm (InP),$3$ dB/cm (Si wire). Ring変調器: $\Delta\lambda = (\partial\lambda/\partial n_{eff})\cdot\Delta n_{eff}$. MZI消光比: $ER = 20\log_{10}[(E_1+E_2)/(E_1-E_2)]$ dB.",
     "url_present"),

    ("ee_b4_005","スマートグリッドセキュリティ","Smart Grid Cybersecurity","",
     "SCADA・AMI・EV充電等のスマートグリッドコンポーネントへのサイバー攻撃を検知・防御するセキュリティ技術体系。",
     "ウクライナ停電事件(2015・2016)がICS/SCADAへのサイバー攻撃の現実的脅威を世界に示した。",
     "電気電子工学","サイバーセキュリティ",2010,None,"枠組","セキュリティ・インフラ",
     "電力インフラのサイバー攻撃対策・セキュリティ設計が必要な場合","電力系統SCADA・スマートメータ・変電所制御",
     "レガシーICSの暗号化レトロフィットをどう実施するか？誤検知率の管理は？",
     "物理セキュリティのみ","SCADA,ICS,スマートグリッドセキュリティ,電力インフラ","smart grid security,SCADA,ICS,anomaly detection,IEC 62351",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/9220798",
     "欧米","high",
     r"異常検知: $\chi^2_{test} = \sum_i (O_i - E_i)^2/E_i > \chi^2_{\alpha,df}$. フォールストゥポレランス: $N_{min\_operational} = N - f$ ($f$:故障許容数). CVSS v3: $Score = 10 \times Exploitability \times Impact$.",
     "url_present"),

    ("ee_b4_006","マルチバンドアンテナ","Multiband Antenna","",
     "単一アンテナ構造で複数の周波数帯(700MHz・2.4GHz・5GHz・28GHz等)を同時またはスイッチングで対応する小型アンテナ技術。",
     "スマートフォンの5Gマルチバンドアンテナ設計で金属筐体内への実装技術が進化。",
     "電気電子工学","アンテナ工学",1990,None,"手法","無線通信・スマートフォン",
     "限られたスペースで複数通信規格に対応するアンテナ設計","スマートフォン・タブレット・IoTモジュール",
     "各バンドのアイソレーション確保と近傍金属の影響は？SAR適合は？",
     "シングルバンドアンテナ","マルチバンドアンテナ,MIMO,スマートフォンアンテナ,LTE/5G","multiband antenna,MIMO,smartphone antenna,LTE,5G NR",
     "active","primary",80,8,
     "https://ieeexplore.ieee.org/document/8454438",
     "東アジア","high",
     r"VSWR: $VSWR = (1+|\Gamma|)/(1-|\Gamma|)$. $S_{11} < -6$ dB (帯域). アイソレーション: $S_{12} < -15$ dB. ECC: $ECC = |\sum_{ij}\int\int [F_i(\theta,\phi)\cdot F_j^*(\theta,\phi)]d\Omega|^2/\eta_{rad,i}\eta_{rad,j}$.",
     "url_present"),

    ("ee_b4_007","集積電気化学センサ","Integrated Electrochemical Sensor","",
     "CMOS回路と電極をチップ上に集積して生体物質・環境汚染物質・食品安全を高感度検出するバイオセンサ技術。",
     "チップ集積型電気化学センサがコロナウイルス抗原を5分で検出するポイントオブケア診断を実現。",
     "電気電子工学","バイオエレクトロニクス",2000,None,"手法","医療診断・環境モニタリング",
     "小型・高感度・リアルタイムの化学・生体物質検出が必要な場合","ポイントオブケア診断・食品安全・環境監視",
     "非特異的吸着の抑制と表面機能化の安定性は？校正頻度の最小化は？",
     "大型分析機器","電気化学センサ,バイオセンサ,アンペロメトリー,ポイントオブケア","electrochemical sensor,biosensor,amperometry,point-of-care,LOD",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/8792123",
     "欧米","high",
     r"Nernst方程式: $E = E^0 + \frac{RT}{nF}\ln\frac{a_{ox}}{a_{red}}$. LOD = $3\sigma_{blank}/m$ ($m$:感度). CV: $i_p = 0.4463 n F A C_0^*\sqrt{\frac{nFvD}{RT}}$ (Randles–Sevcik). $SNR = 20\log_{10}(S/N)$.",
     "url_present"),

    ("ee_b4_008","並列計算アーキテクチャ","Parallel Computing Architecture","",
     "GPU・TPU・FPGA・メニーコアプロセッサを用いてデータ並列・タスク並列・パイプライン並列で大規模計算を高速化する設計。",
     "NVIDIA A100 GPUがAI学習の計算速度を前世代比20倍向上させLLM開発を可能にした。",
     "電気電子工学","計算機アーキテクチャ",1970,None,"枠組","高性能計算・AI",
     "大規模並列計算・AI学習・科学シミュレーションが必要なシステム設計","DNN学習・物理シミュレーション・ビッグデータ処理",
     "Amdahlの法則による並列化効率の理論的限界は？メモリ帯域幅ボトルネックは？",
     "逐次処理CPU","並列計算,GPU,TPU,SIMD,Amdahl則","parallel computing,GPU,TPU,SIMD,Amdahl,memory bandwidth",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/7755583",
     "欧米","high",
     r"Amdahl則: $S_p = 1/(f_{serial} + (1-f_{serial})/p)$. Roofline: $Perf = \min(P_{peak}, I \cdot B_{mem})$ ($I$:演算強度). GPU並列効率: $E = S_p/p$. TPU行列積: $\text{TOPS} = 2N^3/t_{compute}$.",
     "url_present"),

    ("ee_b4_009","核融合炉プラズマ計測","Fusion Reactor Plasma Diagnostics","",
     "トカマク型核融合炉のプラズマ温度・密度・電流分布をトムソン散乱・中性粒子ビーム・干渉計等で計測する技術体系。",
     "ITER(国際核融合実験炉)の50種類以上の計測システムが核融合研究の中枢データを提供。",
     "電気電子工学","プラズマ工学・計測",1960,None,"手法","核融合・プラズマ工学",
     "高温プラズマ($10^8$K)の精密診断が必要な核融合実験装置","ITER・JT-60SA・核融合商用炉の制御",
     "超高温環境での計測器具の耐久性をどう確保するか？複数計測の整合性確認は？",
     "古典的プローブ計測","トムソン散乱,プラズマ計測,核融合,トカマク","Thomson scattering,plasma diagnostics,fusion,Langmuir probe,interferometry",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/7875944",
     "欧米","high",
     r"トムソン散乱電子温度: $T_e = \Delta\lambda^2 / (2\lambda_0^2)\cdot m_e c^2/k_B$. プラズマ電流: $I_p = \oint B_\theta dl / \mu_0$. 密度干渉: $\phi = n_e r_e \lambda L$. Lawson条件: $n\tau_E T > 3\times 10^{21}$ m$^{-3}$·s·keV.",
     "url_present"),

    ("ee_b4_010","コードレスHDMIと映像無線伝送","Wireless Video Transmission","",
     "60GHz WiGig・IEEE 802.11ad/ay・WirelessHD等のmmWave無線を用いて非圧縮・低遅延の映像を無線伝送する技術。",
     "プロジェクター・テレビへのケーブルレス接続でスマートオフィス環境の配線コストを削減。",
     "電気電子工学","映像・無線通信",2010,None,"手法","映像通信・AV機器",
     "非圧縮・低遅延・高解像度の映像をケーブルレスで伝送する必要がある場合","ホームシアター・会議室プロジェクター・VR映像伝送",
     "60GHz障害物遮断への対応(LOS確保)は？複数デバイス共存時の干渉管理は？",
     "HDMI有線接続","WiGig,60GHz,802.11ad,低遅延映像伝送","WiGig,60GHz,802.11ad,uncompressed video,low latency",
     "active","primary",78,7,
     "https://ieeexplore.ieee.org/document/6218154",
     "欧米","high",
     r"60GHz自由空間損失: $PL = 20\log_{10}(4\pi d f/c)$ ($d=5m$: $\approx88$ dB@60GHz). 非圧縮4K60: $4096\times2160\times60\times24\approx12.7$ Gbps. 802.11ay: $Max 100+$ Gbps(MU-MIMO). Beamforming gain: $G_{BF}=20\log_{10}(N)$.",
     "url_present"),

    ("ee_b4_011","電気化学インピーダンス分光","Electrochemical Impedance Spectroscopy","EIS",
     "広周波数帯域の微小交流信号でバッテリー・燃料電池・腐食の内部インピーダンスを測定し劣化・健全性を診断する技術。",
     "EV電池のオンラインSOH(健全性状態)推定でEIS計測を車載化し予知保全を実現。",
     "電気電子工学","電気化学・電池工学",1970,None,"手法","電池・腐食・燃料電池診断",
     "電気化学システムの内部状態・界面特性を非破壊で詳細分析する必要がある場合","LIB劣化診断・燃料電池MEA評価・腐食計測",
     "等価回路モデルのパラメータ同定精度は？高周波インダクタンス補正は？",
     "単純電圧・電流計測","電気化学インピーダンス分光,バッテリー劣化,SOH,Nyquist線図","EIS,impedance spectroscopy,battery SOH,Nyquist plot,equivalent circuit",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/8409949",
     "欧米","high",
     r"インピーダンス: $Z(\omega) = Z'(\omega) + jZ''(\omega)$. Randles等価回路: $Z = R_s + \frac{R_{ct}}{1+j\omega R_{ct}C_{dl}} + Z_W$. Warburg拡散: $Z_W = \sigma\omega^{-1/2}(1-j)$. DRT: $Z(\omega) = \int_0^\infty \frac{\gamma(\tau)}{1+j\omega\tau}d\tau$.",
     "url_present"),

    ("ee_b4_012","ロボット作業制御","Robot Task and Motion Planning","TMP",
     "ロボットの高レベルタスク計画(シンボリック)と低レベルモーション計画(幾何学的)を統合したTAMP(Task and Motion Planning)技術。",
     "Googleのロボット研究でLLMをシンボリックプランナーとして使用しロボットの日常作業汎化を実証。",
     "電気電子工学","ロボット工学・AI",2015,None,"枠組","ロボット・AI",
     "複雑な複数ステップ作業のロボット自律実行が必要な場合","産業ロボット自律作業・家庭用サービスロボット",
     "シンボリック計画と物理シミュレーションのインタフェースは？失敗リカバリー計画は？",
     "固定プログラムロボット","タスクアンドモーション計画,TAMP,シンボリックAI,ロボット学習","TAMP,task and motion planning,robot learning,symbolic AI,manipulation",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/9196535",
     "欧米","high",
     r"STRIPS計画: $\pi = (a_1,...,a_n)$ s.t. $S_0 \xrightarrow{a_1} S_1 \cdots \xrightarrow{a_n} S_n \models G$. 軌道最適化: $\min \int_0^T c(q,\dot{q})dt$, s.t. $q(0)=q_0, q(T)=q_f$. LLMプランナー: $P(a|c,h) \sim LLM(prompt)$.",
     "url_present"),

    ("ee_b4_013","回路信頼性加速試験","Circuit Reliability Accelerated Test","",
     "HAST(高加速温湿度試験)・HTOL(高温動作試験)・電気移行試験等で電子回路の長期信頼性を短時間で評価する手法。",
     "スマートフォン向けICの品質保証でHTOL 1,000時間試験がMTBF 10万時間以上を保証する。",
     "電気電子工学","信頼性工学",1965,None,"手法","品質保証・信頼性",
     "電子部品・回路の製品寿命を短期間で評価する信頼性保証設計","スマートフォンIC・自動車ECU・産業用電子基板",
     "加速係数の妥当性検証をどう行うか？製品使用条件との対応関係は？",
     "実稼働寿命試験","信頼性加速試験,HTOL,電気移行,MTTF,JEDEC規格","accelerated life testing,HTOL,electromigration,MTTF,reliability",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/6234548",
     "欧米","high",
     r"電気移行: $MTTF = A J^{-n}\exp(E_a/k_B T)$ (Black則,$J$:電流密度). HTOL加速係数: $AF = \exp[E_a/k(1/T_U - 1/T_A)]$. 電圧加速: $AF_V = \exp[\beta(V_A-V_U)]$. 故障分布: $F(t) = 1-\exp[-(t/\eta)^\beta]$ (Weibull).",
     "url_present"),

    ("ee_b4_014","電気自動車バッテリーマネジメント","EV Battery Management System","BMS",
     "セル電圧・温度・電流計測に基づいてSOC・SOH推定・セルバランシング・保護回路を統合管理するリチウムイオン電池制御システム。",
     "BMS精度向上でEVの電池利用率を90%以上に高め航続距離と電池寿命を同時最大化。",
     "電気電子工学","EV・電池工学",2000,None,"枠組","EV・エネルギー貯蔵",
     "大容量リチウムイオン電池パックの安全・高効率運用が必要な場合","EV・定置型蓄電・ドローン・UPS",
     "SOC推定精度と演算リソースのトレードオフは？多直並列セルのバランシング効率は？",
     "単純電圧監視","BMS,SOC推定,セルバランシング,カルマンフィルタ","BMS,SOC,SOH,cell balancing,Kalman filter,EV battery",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/9382245",
     "東アジア","high",
     r"EKF-SOC: $\hat{x}_{k|k} = \hat{x}_{k|k-1} + K_k(z_k - H\hat{x}_{k|k-1})$. $K_k = P_{k|k-1}H^T(HP_{k|k-1}H^T+R)^{-1}$. Coulomb counting: $SOC(t) = SOC_0 + \frac{1}{C_{bat}}\int_0^t I dt$. バランシング損失: $P_{bal} = (V_{max}-V_{min})/R_{bal}$.",
     "url_present"),

    ("ee_b4_015","有機発光ダイオード駆動","OLED Driving Technology","",
     "AMOLED(能動行列駆動OLED)のTFT電流駆動回路・ELVSS補償・輝度均一化アルゴリズムを実装するディスプレイ駆動技術。",
     "折りたたみスマートフォンのAMOLEDで曲げ応力に耐える薄型TFTバックプレーン設計が実現。",
     "電気電子工学","ディスプレイ工学",2007,None,"手法","ディスプレイ・民生電子",
     "高輝度均一性・長寿命のOLEDディスプレイ駆動回路設計","スマートフォン・フォルダブル・大型OLED TV",
     "OLEDの劣化(Burn-in)補償アルゴリズムの実装コストは？電流균一化回路の面積は？",
     "LCD駆動","AMOLED,TFT,OLED劣化補償,フォルダブルディスプレイ","AMOLED,TFT,OLED degradation,foldable display,current programming",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/7835209",
     "東アジア","high",
     r"OLED電流-電圧: $J = J_0\exp(V/n V_T)$. TFT駆動: $I_{OLED} = \frac{\mu C_{ox}W}{2L}(V_{GS}-V_{th})^2$ (飽和). 劣化補償: $\Delta V_{th}(t) = A\ln(1+Bt)$. 輝度均一化: $L_{target} = I_{OLED}\cdot\eta_{OLED}(t)$.",
     "url_present"),

    ("ee_b4_016","赤外線センサシステム","Infrared Sensor System","",
     "InSb・MCT・マイクロボロメータ等の赤外線検出器を用いた非接触温度計測・夜間監視・ガス検知システムの設計技術。",
     "スマートフォン内蔵の低コストIRセンサが体温計・顔認識の一般普及を実現。",
     "電気電子工学","センサ工学",1950,None,"手法","温度計測・セキュリティ・産業",
     "非接触温度計測・夜間視覚・ガス濃度検出が必要なセンサシステム設計","サーモグラフィカメラ・産業炉温度制御・COVID体温スクリーニング",
     "大気中のIR透過窓(3-5μm・8-14μm)の選択と使用環境適合は？冷却型vs非冷却型の選択は？",
     "接触温度計","赤外線センサ,LWIR,マイクロボロメータ,サーモグラフィ","infrared sensor,LWIR,microbolometer,thermography,non-contact thermometry",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/4488101",
     "欧米","high",
     r"Stefan-Boltzmann: $M_e = \varepsilon\sigma T^4$. ウィーン変位則: $\lambda_{max} T = 2898$ μm·K. NETD(温度分解能): $NETD = \frac{V_{noise}}{dV/dT}$. 焦点面アレー: $D^* = \frac{\sqrt{A_{det}\Delta f}}{NEP}$ [cm·Hz$^{1/2}$/W].",
     "url_present"),

    ("ee_b4_017","パルス電力工学","Pulsed Power Engineering","",
     "コンデンサ・インダクタ・クロストロンを用いて短時間に超高電圧・超大電流パルスを生成する技術。プラズマ・レーダー・レーザー励起に使用。",
     "ICF(慣性閉じ込め核融合)実験のNIF施設でMJクラスのレーザーパルスを生成し核融合点火を実証。",
     "電気電子工学","パルス電力・プラズマ",1960,None,"手法","核融合・レーダー・医療",
     "超短時間(μs以下)の超高電力パルスが必要なシステム設計","レールガン・電磁パルス試験・電子線ビーム加速器",
     "誘電体の部分放電耐性と絶縁破壊をどう防止するか？パルス繰返し動作の熱管理は？",
     "連続電力供給","パルス電力,コンデンサバンク,インパルス,Marx発生器","pulsed power,Marx generator,capacitor bank,high voltage pulse",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/7869476",
     "欧米","high",
     r"Marx発生器: $V_{out} = N \times V_{charge}$ ($N$:段数). LC回路パルス: $V(t) = V_0\cos(\omega t)$,$\omega=1/\sqrt{LC}$. Peak電流: $I_{peak} = V_0\sqrt{C/L}$. エネルギー: $E = \frac{1}{2}CV^2 = \frac{1}{2}LI^2$.",
     "url_present"),

    ("ee_b4_018","台湾半導体ファウンドリ技術","Taiwan Semiconductor Foundry Technology","",
     "TSMCが確立したファウンドリビジネスモデルと先端半導体製造技術(EUVリソグラフィー・CoWoS・SoIC)の技術経営的考察。",
     "TSMC N3プロセスとCoWoSパッケージングがNVIDIA H100/B200のAI計算性能を支える世界的技術基盤となった。",
     "電気電子工学","半導体産業",1987,None,"枠組","半導体産業・製造",
     "先端半導体製造・ファウンドリ戦略・技術ロードマップの分析","CPU・GPU・AI半導体の製造委託設計",
     "地政学リスク(台湾海峡)とサプライチェーン多様化の課題は？Intelファウンドリとの競合は？",
     "自社一貫製造(IDM)","TSMC,ファウンドリ,EUV,CoWoS,先端半導体","TSMC,foundry,EUV,advanced packaging,CoWoS,geopolitics",
     "active","secondary",78,9,
     "https://www.tsmc.com/english/dedicatedFoundry/technology/logic/l_3nm",
     "東アジア","high",
     r"トランジスタ密度: $\rho_{N3} \approx 290M$ Tr/mm$^2$. スケーリング改善: $PPAf = Power\_Density\times Performance\times Area\times frequency$. CoWoS帯域幅: $BW_{HBM3} = 819$ GB/s (H100). 製造歩留: $Y = e^{-A_0 D_0}$ (Poisson).",
     "url_present"),

    ("ee_b4_019","超低電力設計","Ultra-Low Power Design","ULP",
     "閾値電圧以下動作(サブスレッショルド)・DVFS・クロックゲーティング・パワーゲーティングを組み合わせてICの消費電力をμW以下に抑える設計技術。",
     "ULP設計によるBLE SoC(nRF52840等)がバッテリー交換無しで10年動作するIoTノードを実現。",
     "電気電子工学","超低電力VLSI",2000,None,"手法","IoT・ウェアラブル・医療",
     "バッテリー容量・エネルギーハーベスト電力で長期動作するIoTデバイス設計","BLEセンサノード・医療植込み機器・農業IoT",
     "サブスレッショルド動作での速度-電力トレードオフは？製造ばらつきへの感度は？",
     "高速高性能設計","ULP,サブスレッショルド,DVFS,電力ゲーティング,IoT","ULP,subthreshold,DVFS,power gating,IoT,ultra-low power",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/5658581",
     "欧米","high",
     r"サブスレッショルド電流: $I_{sub} = \frac{W}{L}\mu_0 C_{ox}\frac{kT}{q}^2 e^{(V_{GS}-V_{th})/(nkT/q)}$. 動的電力: $P_{dyn} = \alpha C_L V_{DD}^2 f$. DVFS省電力比: $P_{ratio} = (V_{low}/V_{high})^2 (f_{low}/f_{high})$.",
     "url_present"),

    ("ee_b4_020","マシンビジョン検査","Machine Vision Inspection","",
     "カメラ・照明・画像処理アルゴリズム・Deep Learningを統合して製造ラインの外観欠陥・寸法を高速自動検査するシステム。",
     "半導体ウェーハ検査での機械学習ベース欠陥分類がスループット1000倍・検出漏れゼロを実現。",
     "電気電子工学","コンピュータビジョン・製造",1980,None,"手法","製造品質検査・自動化",
     "製造ラインの外観欠陥・寸法・異物の自動高速検査が必要な場合","半導体ウェーハ・PCB・食品・自動車部品",
     "欠陥種類の変化(新規欠陥)への対応と良品流出率管理は？検査速度と精度のバランスは？",
     "人手による外観検査","機械ビジョン,外観検査,Deep Learning,欠陥検出","machine vision,defect detection,deep learning inspection,AOI,semiconductor inspection",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/8754188",
     "東アジア","high",
     r"F1スコア: $F1 = 2 P\cdot R/(P+R)$. 検出感度: $SNR_{image} = \mu_{signal}/\sigma_{noise}$. 欠陥密度: $D_{defect}$ [個/cm$^2$]. CNN精度: $Accuracy = (TP+TN)/(TP+TN+FP+FN) \geq 99.9\%$.",
     "url_present"),

    ("ee_b4_021","医療用超音波イメージング","Medical Ultrasound Imaging","",
     "アレーアンテナの遅延加算ビームフォーミングとBモード・カラードップラー・エラストグラフィを組み合わせた超音波診断装置技術。",
     "ポイントオブケア超音波(POCUS)のスマートフォン接続型デバイス化で途上国医療診断を革新。",
     "電気電子工学","医療電子工学",1970,None,"枠組","医療診断・センシング",
     "生体内部の高分解能・リアルタイムイメージングが必要な医療診断","産婦人科・循環器・救急の超音波診断",
     "組織の音速ばらつきによる画像劣化の補正は？ポータブル化での画質-コストトレードオフは？",
     "X線CT","超音波診断,ビームフォーミング,Bモード,エラストグラフィ","ultrasound imaging,B-mode,elastography,phased array,POCUS",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/7762961",
     "欧米","high",
     r"横方向分解能: $\delta_x = \lambda f/D$ ($f$:焦点深度,$D$:開口). 軸方向: $\delta_z = c\tau/2$. ドップラー速度: $v = \frac{f_D c}{2f_0\cos\theta}$. エラストグラフィ: $E = 3\rho v_s^2$ ($v_s$:剪断波速度).",
     "url_present"),

    ("ee_b4_022","中国AIチップ産業","China AI Chip Industry","",
     "HuaweiのAscend・Biren・Cambricon等の中国製AIアクセラレータ開発動向と米国輸出規制への対応戦略の技術経営的考察。",
     "米国の半導体輸出規制(EAR)がHuawei・Baiduのデータセンターチップ調達を制約し中国独自開発を加速。",
     "電気電子工学","AIハードウェア・産業政策",2015,None,"枠組","AI半導体・産業政策",
     "中国AI産業における半導体自給化・技術追従戦略の分析","データセンターAI・スマートシティ・産業AI",
     "7nm以下での中国自製プロセスの実現可能性は？EDAツール・設計知財の国産化は？",
     "NVIDIA GPU","Ascend,中国AIチップ,輸出規制,Cambricon,AI半導体","China AI chip,Ascend,export control,AI semiconductor,Cambricon",
     "active","secondary",75,5,
     "https://www.semiconductors.org/chips4america/",
     "東アジア","high",
     r"AI性能指標: $TFLOPS_{BF16} = 2 \times N_{cores} \times f_{clock}$. NVIDIAとの性能ギャップ: $G_{perf} = TFLOPS_{A100}/TFLOPS_{Ascend910}$. 輸出規制閾値(2023): A100/H100等のAGPU性能/BW積が制限対象.",
     "url_present"),

    ("ee_b4_023","スパースコーディング・圧縮センシング","Sparse Coding and Compressed Sensing","CS",
     "信号の疎な表現を利用してNyquistレートを大幅に下回るサンプリング数から元信号を完全に復元できる理論と応用技術。",
     "MRIの撮影時間を従来比10倍以上高速化した圧縮センシングMRIがCandès・Rombergの理論から実用化。",
     "電気電子工学","信号処理・圧縮",2006,None,"理論","MRI・通信・センサ",
     "信号が特定基底で疎な場合にサブナイキストサンプリングから復元する必要がある場合","MRI高速撮影・レーダー・スパースチャネル推定",
     "RIP(制限等長条件)の充足をどう設計・検証するか？再構成アルゴリズムの計算コストは？",
     "ナイキストサンプリング","圧縮センシング,疎性,L1正則化,LASSO","compressed sensing,sparsity,L1 minimization,RIP,LASSO",
     "active","primary",85,8,
     "https://ieeexplore.ieee.org/document/1580791",
     "欧米","high",
     r"CS復元: $\min \|x\|_1$ s.t. $Ax = y$ ($A\in\mathbb{R}^{m\times n}$,$m\ll n$). RIP: $|\|Ax\|_2^2/\|x\|_2^2 - 1| \leq \delta_s$ for $s$-sparse $x$. Basis Pursuit: $\hat{x} = \arg\min\|x\|_1$ s.t. $\|Ax-y\|_2 \leq\epsilon$.",
     "url_present"),

    ("ee_b4_024","トランジスタスケーリングの限界と3D集積","Transistor Scaling Limits and 3D Integration","",
     "MooreのスケーリングがSi技術の物理限界に近づく中でGAAFET・CFET・3D Stacking(SoIC・X-Cube等)で性能向上を継続する技術戦略。",
     "TSMCの3D Fabric(SoIC)がCPU・GPU・メモリの積層を実現し半導体の第2のスケーリング時代を開拓。",
     "電気電子工学","半導体工学",2015,None,"枠組","半導体・先端パッケージ",
     "従来のトランジスタ微細化限界を超えた性能向上が必要な半導体設計","次世代CPU・GPU・AIアクセラレータの高密度集積",
     "3D積層でのチップ間電熱管理・TSV信頼性・ウェーハレベルボンディング歩留まりは？",
     "2Dスケーリング","GAAFET,CFETトランジスタ,3D集積,SoIC,TSV","GAAFET,3D integration,chiplet,SoIC,advanced packaging,TSV",
     "active","primary",80,5,
     "https://ieeexplore.ieee.org/document/9912039",
     "東アジア","high",
     r"GAA移動度: $\mu_{eff,GAA} > \mu_{FinFET}$ (全周ゲート). $I_{on}/I_{off} > 10^7$. TSV熱抵抗: $R_{TSV} = L/(kA)$. 3D積層密度: $\rho_{3D} = N_{tier}\cdot\rho_{2D}$. 帯域幅密度: $BW/area_{3D} > BW/area_{2D}$.",
     "url_present"),

    ("ee_b4_025","電子機器の耐放射線設計","Radiation-Hardened Electronics Design","RadHard",
     "宇宙線・原子炉環境での高エネルギー粒子による半導体の単粒子効果(SEE)・総電離線量(TID)への耐性を確保する設計技術。",
     "宇宙探査機(Mars Rover等)の長期ミッションで耐放射線設計が数年間の正常動作を保証。",
     "電気電子工学","宇宙・核電子工学",1960,None,"手法","宇宙・原子力・医療機器",
     "放射線環境での長期動作信頼性が必要な電子システム設計","人工衛星・原子力施設制御・放射線治療装置",
     "TMR(三重冗長)のコスト対効果と宇宙線での多重ビット反転対応は？",
     "民生用電子設計","耐放射線設計,SEU,TID,TMR,宇宙電子","radiation hardening,SEU,TID,TMR,space electronics",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/1650609",
     "欧米","high",
     r"SEUクロスセクション: $\sigma_{SEU}(E) = \sigma_{sat}[1-\exp(-(E-E_{th})/W)]$. TID閾値電圧シフト: $\Delta V_{th} = q N_{ot}/C_{ox}$. TMR信頼性: $P_{correct} = 1-(3P_{fail}^2 - 2P_{fail}^3) \approx 1 - 3P_{fail}^2$.",
     "url_present"),

    ("ee_b4_026","スマートセンサシステム","Smart Sensor System","",
     "センシング・信号処理・AI推論・通信を単一ノードに統合して自律的にデータを取得・処理・送信するインテリジェントセンサ。",
     "工場内スマートセンサが機械の振動・温度・音響を統合分析して予兆保全を自律実行。",
     "電気電子工学","IoT・センサシステム",2010,None,"枠組","製造・医療・スマートシティ",
     "エッジでのリアルタイムデータ処理と長期自立動作が必要なセンサシステム","予知保全センサ・スマートビル・農業IoT",
     "センシング精度とエッジ処理電力・通信コストのトレードオフは？Over-the-Air更新の信頼性は？",
     "ダムセンサ+クラウド処理","スマートセンサ,エッジAI,IoT,予知保全","smart sensor,edge AI,IoT,predictive maintenance,MEMS",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/9169723",
     "欧米","high",
     r"センサフュージョン: $\hat{x} = K_1 z_1 + K_2 z_2$,$K_i = \sigma_j^2/(\sigma_i^2+\sigma_j^2)$. 予知保全警報: $P(failure|features) > \theta_{alert}$. BLE通信消費: $E_{tx} = P_{tx}\cdot t_{tx}$.",
     "url_present"),

    ("ee_b4_027","燃料電池コントローラ設計","Fuel Cell Controller Design","",
     "PEM燃料電池スタックのエアコンプレッサ・水素供給弁・冷却ポンプを統合制御してMEA保護と出力最大化を実現する制御技術。",
     "FCV(燃料電池車)の燃料電池システムECUがμs制御でスタック寿命5,000時間以上を保証。",
     "電気電子工学","制御工学・燃料電池",2005,None,"手法","水素エネルギー・EV",
     "FC発電システムの高効率・長寿命運用のための制御設計","FCV・定置型FC発電・ドローンFCシステム",
     "過渡応答時のFCフラッディング防止と水管理の制御設計は？デグラデーション補償は？",
     "個別部品操作","燃料電池制御,空気過剰率,水管理,MPC","fuel cell control,excess ratio,water management,MPC,EMS",
     "active","primary",78,6,
     "https://ieeexplore.ieee.org/document/9082823",
     "東アジア","high",
     r"空気過剰率: $\lambda_{O2} = \dot{m}_{O2,supplied}/(0.21\cdot\dot{m}_{air})$. MPC制御: $\min_{u}\sum_{k=0}^{N}\|y_k-y_{ref}\|_Q^2 + \|u_k\|_R^2$. 電気化学効率: $\eta_{FC} = V_{cell}/E_{Nernst}$.",
     "url_present"),

    ("ee_b4_028","マイクロ波電力伝送","Microwave Power Transmission","MPT",
     "マイクロ波・ミリ波を用いて長距離(数km〜宇宙)で電力を伝送する技術。宇宙太陽光発電(SSPS)の地上受電に関係。",
     "JAXA・NASAが宇宙太陽光発電のkm級マイクロ波送電プロジェクトで可能性実証を進行中。",
     "電気電子工学","エネルギー伝送",1968,None,"手法","宇宙エネルギー・遠距離電力",
     "長距離無線での大電力伝送・宇宙発電の地上受電が必要な場合","SSPS・無人機連続飛行電力供給・IoTセンサ給電",
     "送受電効率と電磁波安全基準(MPE)への整合は？送電ビームの精密指向制御は？",
     "ワイヤー送電","マイクロ波電力伝送,SSPS,レクテナ,ビームフォーミング","MPT,microwave power transfer,SSPS,rectenna,retrodirective",
     "active","primary",78,4,
     "https://ieeexplore.ieee.org/document/7745416",
     "東アジア","high",
     r"Friis伝搬: $P_r = P_t G_t G_r (\lambda/4\pi d)^2$. レクテナ効率: $\eta_{rect} = P_{DC}/P_{RF}$. MPE限界: $S_{max} = 1$ mW/cm$^2$ (@2.45GHz,一般公衆). SSPS設計: $P_{earth} = P_{solar}\eta_{conv}\eta_{MPT}\eta_{rect}$.",
     "url_present"),

    ("ee_b4_029","フィールドバス通信プロトコル","Fieldbus Communication Protocol","",
     "PROFIBUS・DeviceNet・Foundation Fieldbus・CANopen等の産業用リアルタイム通信プロトコルとその設計・実装技術。",
     "PROFIBUSが世界4,400万ノード以上で採用され工場自動化の通信基盤を20年間支えた。",
     "電気電子工学","産業ネットワーク",1987,None,"枠組","工場自動化・制御",
     "PLCとセンサ・アクチュエータ間のリアルタイム制御通信が必要な場合","工場自動化・プロセス制御・製造ロボット",
     "レガシーフィールドバスとTSNイーサネットへの移行戦略は？セキュリティは？",
     "アナログ4-20mA信号","フィールドバス,PROFIBUS,DeviceNet,CANopen","fieldbus,PROFIBUS,DeviceNet,CANopen,industrial protocol",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5338434",
     "欧米","high",
     r"PROFIBUS-DP速度: $12$ Mbps@$< 100$m. 最大ノード: 126スレーブ/マスタ. CAN調停: CSMA/CR(フレームID→ビットワイズOR). バスサイクル: $T_{cycle} = N_{node}\cdot T_{message} + T_{overhead}$.",
     "url_present"),

    ("ee_b4_030","磁気共鳴分光法の電気工学","MRS-based Electrical Engineering Systems","",
     "NMR・MRI原理の工業・医療応用:MRIコイル設計・傾斜磁場増幅器・パルスシーケンス設計・信号受信システムの電気工学的側面。",
     "MRI傾斜磁場コイルの高速スイッチング技術が脳構造の高分解能画像取得を可能にし神経科学を革新。",
     "電気電子工学","医療電子工学",1970,None,"枠組","医療診断・計測",
     "MRI・NMR機器の傾斜磁場・RF系・受信系の設計が必要な場合","MRI装置設計・fMRI・分光測定",
     "傾斜磁場の高速スイッチングでの渦電流・音響ノイズ対策は？RFコイルの受信感度最適化は？",
     "X線・CT","NMR,MRI,傾斜磁場コイル,Larmor周波数,受信コイル","MRI,NMR,gradient coil,Larmor frequency,receive coil,RF amplifier",
     "active","primary",80,8,
     "https://ieeexplore.ieee.org/document/8070344",
     "欧米","high",
     r"Larmor周波数: $\omega_0 = \gamma B_0$ ($\gamma_{H} = 2\pi\times 42.58$ MHz/T). 傾斜磁場: $B_z(x) = B_0 + G_x x$. SNR: $SNR \propto B_0^{7/4} T^{-1}$. 受信コイル感度: $S = \mu_0 I / (2r)$.",
     "url_present"),

    ("ee_b4_031","印刷・インクジェット電子","Printed and Inkjet Electronics","",
     "導電性インク・有機半導体インク等をインクジェット・スクリーン印刷でフレキシブル基板上に塗布し回路・センサ・TFTを製造する技術。",
     "印刷アンテナ・センサタグが大面積・低コスト・フレキシブルIoTラベルの大量製造を実現。",
     "電気電子工学","印刷エレクトロニクス",2000,None,"手法","IoT・フレキシブル・大面積",
     "低コスト・大面積・曲面への電子回路形成が必要な場合","IoTタグ・RFIDラベル・フレキシブルディスプレイ",
     "印刷薄膜の均一性と電気特性の量産再現性は？アニール温度と基板耐熱性の整合は？",
     "フォトリソグラフィー","印刷エレクトロニクス,インクジェット,導電性インク,フレキシブルTFT","printed electronics,inkjet,conductive ink,flexible TFT,roll-to-roll",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/5467034",
     "欧米","high",
     r"インクジェット液滴径: $d_{drop} = 2(3V_{drop}/4\pi)^{1/3}$. 導電性: $\sigma_{Ag-ink} \sim 10^6$ S/m(焼結後,$\ll$バルク銀$6.3\times10^7$). 線幅: $w = d_{drop}\sqrt[3]{3V_{drop}/\pi h_{dry}}$ ($h_{dry}$:乾燥膜厚).",
     "url_present"),

    ("ee_b4_032","中国スマートグリッド展開","China Smart Grid Deployment","",
     "国家電網公司(SGCC)が推進する全国スマートグリッドインフラ展開:AMI・HVDC・分散型再エネ統合の技術と政策の考察。",
     "中国のHVDC超長距離送電網(3,000km以上)が再エネの地域間融通を実現し電力コストを低減。",
     "電気電子工学","電力系統・産業政策",2009,None,"枠組","電力系統・スマートグリッド",
     "国家規模のスマートグリッドインフラ整備・再エネ大量導入の事例研究","HVDC・大規模蓄電・系統管理センター設計",
     "中国の超長距離HVDCラインの安定性はどう確保するか？サイバーセキュリティ対策は？",
     "従来AC送電系統","中国国家電網,HVDC,スマートグリッド,AMI,再エネ統合","China SGCC,HVDC,smart grid,AMI,renewable integration",
     "active","secondary",78,7,
     "https://ieeexplore.ieee.org/document/8370107",
     "東アジア","high",
     r"HVDC電力: $P_{HVDC} = V_{DC} I_{DC}$. 損失: $P_{loss} = I_{DC}^2 R_{line}$. HVDC長距離優位点: 損失 $< 3\%$/1000km vs. AC $\sim 6\%$. AMI計量: $\pm 0.5\%$ 精度,15分間隔データ.",
     "url_present"),

    ("ee_b4_033","ハイブリッドスイッチング電源","Hybrid Switching Power Supply","",
     "ハードスイッチングとソフトスイッチング(ZVS/ZCS)を組み合わせてスイッチング損失を最小化する高効率電源トポロジー設計。",
     "LLC共振コンバータがサーバー電源の効率80 PLUS Titanium(96%以上)の要件達成に貢献。",
     "電気電子工学","パワーエレクトロニクス",1990,None,"手法","電源設計・データセンター",
     "高周波高効率の電力変換器設計が必要な場合","サーバー電源・EV OBC・レーザー電源",
     "共振タンク回路の設計とパラメータ最適化は？軽負荷時効率の改善策は？",
     "ハードスイッチングフルブリッジ","LLC共振コンバータ,ZVS,ZCS,ソフトスイッチング","LLC resonant converter,ZVS,ZCS,soft switching,server power supply",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/4803714",
     "欧米","high",
     r"LLC共振周波数: $f_r = 1/(2\pi\sqrt{L_r C_r})$. ZVS条件: $V_{DS}=0$ before turn-on→$\frac{1}{2}L_r I_{pk}^2 > \frac{1}{2}C_{oss}V_{in}^2$. 効率: $\eta = P_{out}/P_{in} = V_{out}I_{out}/V_{in}I_{in}$.",
     "url_present"),

    ("ee_b4_034","圧電MEMS","Piezoelectric MEMS","",
     "PZT・AlN・LiNbO3等の圧電薄膜をMEMSに集積したエネルギーハーベスター・アクチュエータ・超音波変換器。",
     "スマートフォンの指紋センサにBAW(Bulk Acoustic Wave)圧電共振器が使われ高感度検出を実現。",
     "電気電子工学","MEMS",1990,None,"手法","センサ・アクチュエータ・通信",
     "微小な圧電素子の精密アクチュエーション・センシングが必要な場合","超音波トランスデューサ・BAWフィルタ・エネルギーハーベスタ",
     "圧電材料の疲労劣化と初期分極の安定性は？製造歩留まり管理は？",
     "静電気MEMS","圧電MEMS,PZT,BAWフィルタ,圧電ハーベスタ","piezoelectric MEMS,PZT,BAW,resonator,energy harvester",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/8060562",
     "東アジア","high",
     r"圧電方程式: $D = d_{33}\sigma + \varepsilon^T E$,$S = s^E \sigma + d_{33}E$. 共振周波数: $f_r = \frac{1}{2L}\sqrt{E_c/\rho}$ (厚さ縦モード). 結合係数: $k_{eff}^2 = (f_a^2-f_r^2)/f_a^2$.",
     "url_present"),

    ("ee_b4_035","分散型エネルギーリソース管理","Distributed Energy Resource Management","DERMS",
     "太陽光・蓄電池・EVチャージャー・需要応答等の分散型電力リソースを系統運用者が統合的に制御・最適化するシステム技術。",
     "カリフォルニア州DERMSが数百万台の屋根上太陽光・EVをリアルタイム制御し系統安定化に活用。",
     "電気電子工学","スマートグリッド",2015,None,"枠組","スマートグリッド・エネルギー管理",
     "大量の分散型リソースを統合して系統安定化・再エネ活用を最大化する必要がある場合","配電系統・Virtual Power Plant・マイクログリッド",
     "大量DERのリアルタイム通信・制御レイテンシをどう確保するか？サイバー攻撃脆弱性は？",
     "従来の集中型発電制御","DERMS,VPP,需要応答,分散エネルギー,スマートグリッド","DERMS,VPP,demand response,distributed energy,EMS",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/8755992",
     "欧米","high",
     r"OPF(最適潮流): $\min \sum_g c_g(P_g)$ s.t. 潮流・電圧・容量制約. VPP集合出力: $P_{VPP} = \sum_i P_{DER,i}$. 需要応答弾力性: $\varepsilon = \frac{\Delta Q/Q}{\Delta P/P}$.",
     "url_present"),

    ("ee_b4_036","バイポーラ接合トランジスタ高周波設計","BJT High-Frequency Design","HBT",
     "ヘテロ接合バイポーラトランジスタ(HBT:SiGe・InP・GaAs)の高周波小信号モデリングとRF増幅器・ミキサー・発振器設計。",
     "SiGe HBTが100GHz以上のfT/fmaxを実現し5G・自動車レーダー・光通信ドライバに採用。",
     "電気電子工学","高周波回路設計",1951,None,"手法","RF・マイクロ波・ミリ波",
     "fT/fmax > 100GHzの高周波増幅・発振・ミキサー設計が必要な場合","5Gフロントエンド・77GHz自動車レーダー・光通信",
     "高速スイッチング時のカーク効果(Kirk effect)制御は？熱設計による高電力動作限界は？",
     "Si MOSFET","HBT,SiGe,InP,高周波トランジスタ,マイクロ波","HBT,SiGe,InP,high frequency,RF amplifier,fT",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/7106512",
     "欧米","high",
     r"遮断周波数: $f_T = g_m/(2\pi C_{tot})$. 最大発振周波数: $f_{max} = \frac{f_T}{2\sqrt{r_b g_{CE}+f_T/f_T'}}$. Spartan法雑音指数: $NF = 10\log_{10}(F)$. 利得帯域幅積: $GBW = A_v \cdot f_{3dB}$.",
     "url_present"),

    ("ee_b4_037","メモリ技術革新","Emerging Memory Technology","",
     "MRAM・FeRAM・RRAM・PCRAM等の次世代不揮発性メモリの動作原理・信頼性・集積化技術。AIオンチップメモリへの応用。",
     "STT-MRAMの量産化でNVDIMMとL3キャッシュ代替が実現しサーバー電力消費を低減。",
     "電気電子工学","半導体メモリ",2000,None,"手法","AI・コンピューティング",
     "高速・不揮発・高密度・低電力メモリの新世代設計が必要な場合","AIアクセラレータのニアメモリ計算・IoT不揮発メモリ",
     "RRAM/PCRAMのサイクル耐性(Endurance)と不揮発保持特性のバランスは？ばらつきの大きさへの対処は？",
     "DRAM・NAND Flash","MRAM,RRAM,FeRAM,PCRAM,次世代メモリ","MRAM,RRAM,PCRAM,FeRAM,STT-MRAM,emerging memory",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/9219611",
     "欧米","high",
     r"STT-MRAM書込: $I_{write} = \frac{2e}{\hbar}\frac{M_s V \alpha}{\eta}\frac{1}{\ln(\pi/2\Delta)}(H_k/2 + H_{app})$. 熱安定性: $\Delta = K_u V/k_B T > 60$. Endurance: RRAM $> 10^{12}$サイクル目標.",
     "url_present"),

    ("ee_b4_038","光無線・LiFi","Light Fidelity (LiFi) Communication","LiFi",
     "LED照明の高速変調を利用した可視光・近赤外線による室内データ通信技術。WiFiの補完・代替としてセキュアな局所通信を実現。",
     "IEEE 802.11bb (LiFi)が2023年に標準化されGbps級室内通信の実用化道筋を提示。",
     "電気電子工学","光通信・IoT",2011,None,"手法","室内通信・IoT・医療",
     "電磁波干渉環境(病院・航空機・工場)での高速室内通信が必要な場合","病院病棟・製造ラインクリーンルーム・機密情報施設",
     "光線通信(LoS)依存とブロッキングへの対策は？移動端末への追尾アルゴリズムは？",
     "WiFi","LiFi,可視光通信,VLC,IEEE802.11bb,LED変調","LiFi,VLC,IEEE 802.11bb,LED communication,optical wireless",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/8454398",
     "欧米","high",
     r"LiFi変調帯域: $BW = 1/(2\pi \tau_{LED})$($\tau$:LED応答時間). OOK受信感度: $P_{min} = \frac{Q_{th}^2}{2 R^2}\cdot\sigma_n^2$. SNR: $SNR = \frac{(R \cdot P_r)^2}{\sigma_{shot}^2 + \sigma_{thermal}^2}$. 理論容量: $C = B\log_2(1+SNR)$.",
     "url_present"),

    ("ee_b4_039","マルチフィジックスシミュレーション","Multi-Physics Simulation","",
     "電磁場・熱・力学・流体・化学を連成して電子機器・MEMS・バッテリーの複合物理現象を同時シミュレーションするCAE手法。",
     "EV電池パックの電磁-熱-構造連成シミュレーションでサーマルランナウェイの予測精度を向上。",
     "電気電子工学","計算電磁気学",2000,None,"手法","設計シミュレーション・電子機器",
     "複数の物理現象の相互作用が重要なデバイス・システム設計","MEMS設計・バッテリー熱管理・RF-熱連成",
     "異なる物理場の時定数スケール差をどう扱うか？連成方程式の安定な数値解法は？",
     "単一物理シミュレーション","マルチフィジックス,COMSOL,連成解析,電磁-熱-構造","multi-physics,COMSOL,coupled simulation,electromagnetic-thermal",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/9079494",
     "欧米","high",
     r"電磁-熱連成: $\nabla^2 T = -\sigma|E|^2/k$ (Joule熱). 構造-熱: $\sigma_{thermal} = E\alpha\Delta T/(1-\nu)$. 連成反復: $\{F_1(u_1,u_2)=0,F_2(u_1,u_2)=0\}$ → Gauss-Seidel反復収束条件.",
     "url_present"),

    ("ee_b4_040","電子顕微鏡制御","Electron Microscope Control System","",
     "TEM・SEM・STEMの電子ビーム制御・試料ステージ駆動・検出器信号処理を統合したナノスケール観察装置の電気系設計。",
     "STEMのABF法(明視野環状検出)が水素原子を直接観察可能にし材料科学・電池研究を刷新。",
     "電気電子工学","計測・制御",1940,None,"手法","材料解析・半導体評価",
     "ナノ・原子スケールの高精度構造解析が必要な計測システム設計","半導体欠陥解析・新材料開発・生体分子観察",
     "電子ビームの球面収差補正レンズ(Cs補正)の設計は？試料汚染の抑制は？",
     "光学顕微鏡","TEM,SEM,STEM,収差補正,ナノスケール観察","TEM,SEM,STEM,aberration correction,electron microscopy",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/8019312",
     "欧米","high",
     r"ブラッグ条件: $n\lambda = 2d\sin\theta$. SEM分解能: $d_{SE} = 0.61\lambda/\sin\alpha = 0.61\sqrt{h/eV}/\sin\alpha$. 球面収差: $d_{cs} = 0.5C_s\alpha^3$. 最適開口: $\alpha_{opt} = (0.77\lambda/C_s)^{1/4}$.",
     "url_present"),

    ("ee_b4_041","ソリッドステートバッテリー","Solid-State Battery","SSB",
     "液体電解質を固体電解質(酸化物・硫化物・ポリマー)に置き換えて安全性・エネルギー密度・寿命を向上させた次世代電池技術。",
     "トヨタが2027-2028年のEV向けSSB量産を目標に掲げ次世代EV技術競争の焦点となった。",
     "電気電子工学","電池工学",2010,None,"手法","EV・エネルギー貯蔵",
     "高エネルギー密度・安全・長寿命の次世代電池設計が必要な場合","EV・航空電動化・宇宙機電源",
     "固体電解質の界面抵抗(固-固界面)とリチウムデンドライト抑制は？低温動作性能は？",
     "液体電解質リチウムイオン電池","全固体電池,固体電解質,Li金属負極,界面抵抗","solid-state battery,solid electrolyte,Li metal,interface resistance,SSB",
     "active","primary",80,4,
     "https://ieeexplore.ieee.org/document/9690099",
     "東アジア","high",
     r"イオン伝導度: $\sigma_{Li+} = \frac{n_{Li}q^2D_{Li}}{k_BT}$ (Nernst-Einstein). 界面抵抗: $R_{int} = t_{SEI}/(\sigma_{SEI}A)$. エネルギー密度: $E = C\cdot V_{nom}/m_{cell}$ [Wh/kg]. 目標: $> 400$ Wh/kg.",
     "url_present"),

    ("ee_b4_042","ロボット制御ソフトウェア設計","Robot Control Software Architecture","ROS",
     "ROS(Robot Operating System)・ROS2を用いたロボットソフトウェアのモジュール化・通信・リアルタイム制御・シミュレーション統合設計。",
     "ROS2 Humble/Ironがリアルタイム保証・DDS通信・セキュリティ機能でロボット産業の標準OSとして普及。",
     "電気電子工学","ロボット工学",2007,None,"枠組","ロボット・自動運転",
     "複雑なロボットシステムのソフトウェアアーキテクチャ設計が必要な場合","産業ロボット・自律走行・ドローン制御",
     "リアルタイム制約(1ms周期制御)とROS2のDDS通信オーバーヘッドの整合は？",
     "モノリシックロボット制御プログラム","ROS,ROS2,DDS,リアルタイムロボット制御,Nav2","ROS2,DDS,real-time control,navigation,moveit",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/8460701",
     "欧米","high",
     r"ROS2通信遅延: $t_{latency} = t_{serialize} + t_{network} + t_{deserialize}$. RT制御: $T_{jitter} < 100\mu s$ (DDS Cyclone+PREEMPT_RT). Nav2コスト関数: $f_{path} = \lambda_1 d_{goal} + \lambda_2 \sum obstacles$.",
     "url_present"),

    ("ee_b4_043","電力品質計測","Power Quality Measurement","",
     "高調波歪み(THD)・電圧変動・フリッカ・アンバランス・電力フェージングをIEC 61000規格に基づき計測・解析する技術。",
     "再エネ・インバータ機器の大量普及で電力品質問題が顕在化し精密計測・解析の重要性が増大。",
     "電気電子工学","電力系統工学",1980,None,"手法","電力品質・系統設計",
     "電力品質評価・電力設備の適合認証が必要な場合","工場・データセンター・再エネ連系の電力品質管理",
     "高調波源の特定と電力系統内伝搬の解析は？機器固有の高調波耐性との整合は？",
     "電圧・電流の基礎計測","高調波,THD,電力品質,IEC61000,電圧フリッカ","power quality,harmonic,THD,IEC 61000,flicker,voltage sag",
     "active","primary",80,8,
     "https://ieeexplore.ieee.org/document/7932231",
     "欧米","high",
     r"THD: $THD_V = \sqrt{\sum_{h=2}^\infty V_h^2}/V_1$. フリッカ: $P_{st} = \sqrt{\sum_i w_i P_i^2}$ (IEC61000-4-15). 不平衡度: $V_U = V_{negative}/V_{positive}\times 100\%$. IEC許容: $THD \leq 8\%$.",
     "url_present"),

    ("ee_b4_044","ピエゾ電気マイクロフォン","Piezoelectric Microphone","",
     "圧電薄膜(PVDF・PZT・AlN)を用いたMEMSマイクロフォンの設計・製造・信号処理回路技術。スマートフォン・補聴器に搭載。",
     "MEMS MEMSマイクロフォンが従来ECMを置き換えスマートフォン・Alexa・AirPodsの音声認識基盤を支える。",
     "電気電子工学","音響MEMS",1990,None,"手法","音声認識・IoT・医療",
     "小型・低電力・高感度の音声入力デバイス設計","スマートスピーカー・ウェアラブル・補聴器・IoT機器",
     "等価雑音レベル(A-weighted SNR)と感度のトレードオフは？パッケージング音響設計は？",
     "ダイナミックマイクロフォン","MEMSマイク,圧電マイク,音圧感度,SNR","MEMS microphone,piezoelectric,condenser,SNR,acoustic sensor",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/9181544",
     "東アジア","high",
     r"感度: $S = V_{out}/P_{sound}$ [dB re 1V/Pa]. SNR = $20\log_{10}(p_{ref}/\sigma_{noise})$. 共振周波数: $f_r = \frac{1}{2\pi}\sqrt{k_{m}/(m_{plate}+m_{air})}$. Lumped model: $Q = \omega_r m / b_{damp}$.",
     "url_present"),

    ("ee_b4_045","衛星通信システム","Satellite Communication System","",
     "GEO・MEO・LEO衛星コンステレーションによるブロードバンド・IoT・測位通信システムの電気工学的設計技術。",
     "Starlink(SpaceX)のLEOコンステレーション(5000機超)が農村・海洋・航空でのブロードバンドを革命化。",
     "電気電子工学","衛星通信",1960,None,"枠組","通信・宇宙・IoT",
     "広域・グローバルカバレッジの通信インフラ設計","衛星ブロードバンド・IoT衛星・衛星測位",
     "LEOの大頻繁ハンドオフと遅延最小化は？スペースデブリ回避の軌道管理は？",
     "GEO単衛星中継","LEOコンステレーション,Starlink,OneWeb,衛星ブロードバンド","LEO constellation,Starlink,satellite broadband,Ka-band,phased array",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/9052669",
     "欧米","high",
     r"リンクバジェット: $P_r = P_t + G_t - FSPL + G_r - L_{misc}$ [dBW]. FSPL: $FSPL = 20\log_{10}(4\pi d f/c)$. 遅延: $t_{LEO} \approx 2 \times 550km / c \approx 3.7ms$. Eb/N0: $E_b/N_0 = P_r/(k_B T_s R_b)$.",
     "url_present"),

    ("ee_b4_046","プロセッサキャッシュ設計","Cache Memory Design","",
     "L1/L2/L3キャッシュの組み合わせアソシアティビティ・置換ポリシー・コヒーレンスプロトコル(MESI等)の設計技術。",
     "Apple M2チップの192MB L2/L3共有キャッシュがメモリバンド幅ボトルネックを解消しCPU-GPU連携性能を向上。",
     "電気電子工学","計算機アーキテクチャ",1968,None,"手法","プロセッサ設計",
     "高速プロセッサのメモリ階層設計が必要な場合","CPU・GPU・AI推論チップのキャッシュ設計",
     "キャッシュラインの競合(Thrashing)とキャッシュコヒーレンス(MESI)のオーバーヘッドは？",
     "メインメモリ直接アクセス","Lキャッシュ,MESI,コヒーレンス,キャッシュミス","cache memory,MESI protocol,associativity,cache miss,LLC",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/9090952",
     "欧米","high",
     r"ヒット率: $H = (N_{access}-N_{miss})/N_{access}$. AMAT: $AMAT = t_{hit} + (1-H)\cdot t_{miss}$. LRU置換: $V(line) = t_{last\_access}$. MESI: $P_{invalidate} = N_{shared}/N_{total}$.",
     "url_present"),

    ("ee_b4_047","GaN電力デバイスの信頼性","GaN Power Device Reliability","",
     "GaN HEMTのトラッピング効果・電流コラプス・ゲート酸化膜信頼性・熱管理の定量的評価と信頼性設計技術。",
     "EV・5G基地局でのGaN採用拡大には従来Si比の信頼性実証が不可欠で車載認定規格(AEC-Q101)への適合が焦点。",
     "電気電子工学","パワー半導体信頼性",2010,None,"手法","EV・5G・電力変換",
     "GaNパワーデバイスの長期信頼性保証が必要な機器設計","EV牽引インバータ・5G基地局PA・太陽光PCS",
     "電流コラプス(表面トラップ)の回復時間と動作温度の関係は？加速試験での活性化エネルギーは？",
     "Si MOSFET信頼性設計","GaN信頼性,電流コラプス,トラッピング,AEC-Q101","GaN reliability,current collapse,trapping,AEC-Q101,HTOL",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/7368497",
     "欧米","high",
     r"電流コラプス比: $CR = I_{D,pulse}/I_{D,DC}$. 活性化エネルギー: $Ea = k_B\ln(AF_T)/(1/T_1 - 1/T_2)$. TDDB(ゲート絶縁: $t_{BD} = A \exp(B/E_{ox}) \exp(Ea/k_B T)$. 信頼性目標: $FIT < 1$ @ $T_j = 175^\circ C$.",
     "url_present"),

    ("ee_b4_048","日本パワエレ技術の貢献","Japan's Contribution to Power Electronics","",
     "三菱電機・日立・東芝・富士電機等の日本企業によるIGBT・SiC・パワーモジュールの技術開発とその産業・社会への貢献。",
     "新幹線のVVVFインバータ(IGBT)が日本製電力変換技術の象徴となり世界の高速鉄道に普及した。",
     "電気電子工学","パワーエレクトロニクス産業",1985,None,"枠組","パワーエレクトロニクス産業",
     "日本パワエレ産業の技術史・競争力分析","鉄道・自動車・再エネ向けパワーモジュール産業の動向分析",
     "SiC・GaN化合物半導体での日本の競争力維持戦略は？材料サプライチェーンの確保は？",
     "欧米半導体企業","IGBT,SiC,パワーモジュール,日本製造,VVVFインバータ","IGBT,SiC,power module,Japan,VVVF inverter,power electronics industry",
     "active","secondary",78,8,
     "https://www.meti.go.jp/press/2022/06/20220602002/20220602002.html",
     "東アジア","high",
     r"IGBT損失: $P_{IGBT} = V_{ce0}I_D + r_c I_D^2$(導通) + $E_{sw}f$(スイッチング). 鉄道インバータ効率: $\eta = P_{motor}/(P_{motor}+P_{inverter\_loss}) \geq 97\%$. SiC Schottky: $V_F \approx 0.7$V vs. Si $\approx 0.9$V.",
     "url_present"),

    ("ee_b4_049","低軌道衛星軌道制御","LEO Satellite Orbit Control","",
     "ホールスラスタ・冷ガスジェットを用いたLEO衛星のAtmospheric drag補償・軌道維持・衝突回避マヌーバ制御技術。",
     "SpaceX Starlinkが自律的な衝突回避を統計的に実行しデブリ衝突リスクを管理しながら稼動。",
     "電気電子工学","宇宙・制御工学",1970,None,"手法","宇宙・衛星工学",
     "LEO衛星の精密軌道制御・寿命管理・デブリ回避が必要な場合","通信衛星コンステレーション・観測衛星・軍事衛星",
     "大気抵抗のモデル誤差とスラスタ推力の不確実性への対応は？自律回避判断の信頼性は？",
     "地上制御コマンドのみ","LEO軌道制御,ホールスラスタ,デブリ回避,大気抵抗補償","LEO orbit control,Hall thruster,collision avoidance,atmospheric drag",
     "active","primary",78,6,
     "https://ieeexplore.ieee.org/document/9055241",
     "欧米","high",
     r"大気抵抗: $F_D = \frac{1}{2}C_D \rho v^2 A$. ΔV計算: $\Delta V = \frac{F_{thrust}}{m_{sat}}\cdot t_{burn}$. 衝突確率: $P_c = \frac{1}{2\pi\sigma_r\sigma_t}\exp(-\frac{r^2}{2\sigma_r^2}-\frac{t^2}{2\sigma_t^2})A_{cross}$.",
     "url_present"),

    ("ee_b4_050","バイオメトリクス認証システム","Biometric Authentication System","",
     "指紋・虹彩・顔・声紋・静脈パターン等の生体特徴量から個人認証を行うセンサ・信号処理・テンプレートマッチングシステム。",
     "スマートフォンのFace ID・指紋センサが生体認証をユビキタス化しパスワード認証を置換し始めた。",
     "電気電子工学","生体認証・セキュリティ",1969,None,"枠組","セキュリティ・民生電子・IoT",
     "パスワード不要の高信頼個人認証が必要なシステム設計","スマートフォン・入退室管理・オンライン本人確認",
     "双子などの生体類似者への誤認・なりすまし(Presentation Attack)への対策は？テンプレート漏洩時の対応は？",
     "パスワード認証","生体認証,指紋認識,顔認識,FRR/FAR,FIDO","biometrics,fingerprint,face recognition,FAR,FRR,FIDO,liveness detection",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5539935",
     "東アジア","high",
     r"ROC指標: $FAR = FP/(FP+TN)$,$FRR = FN/(FN+TP)$. EER: $FAR = FRR$. 指紋特徴量: minutiae数 $\sim 80$-$100$/指. 顔認証精度: $TAR@FAR=0.001\% > 99\%$ (最先端2024). FIDO2: WebAuthn公開鍵認証.",
     "url_present"),
]

if __name__ == "__main__":
    ins, sk = insert_records(records)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Inserted: {ins}, Skipped: {sk}")
    print(f"Total: {total}")
