#!/usr/bin/env python3
"""電気電子工学 Batch 2: +50件"""
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def ins(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    ok = sk = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id,name_ja,name_en,name_original,definition,impact_summary,subfield,
                 school_of_thought,era_start,era_end,methodology_level,target_domain,
                 application_conditions,when_to_apply,framing_questions,opposing_concept_names,
                 keywords_ja,keywords_en,status,source_reliability,data_completeness,
                 technology_readiness_level,source_url,culture_region,culture_confidence,
                 genealogy_narrative,verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            ok += 1
        except sqlite3.IntegrityError:
            sk += 1
    conn.commit()
    conn.close()
    return ok, sk

records = [
("ee_b2_001","マクスウェル方程式","Maxwell's Equations","Maxwell equations",
 "電磁場の振る舞いを記述する4つの偏微分方程式の組。ガウスの法則（電場・磁場）・ファラデーの誘導法則・アンペールの法則を統一し、電磁波の存在を予言した。",
 "アンテナ・導波管・光学素子・電磁適合性設計の絶対基盤。電磁波工学全般の理論的礎。","電気電子工学","古典電磁気学",1865,None,
 "基礎理論","アンテナ・回路・光学","電磁現象全般","電磁場の完全な記述が必要な場合",
 "変位電流項はなぜアンペールの法則を修正したか","量子電磁力学（QED）",
 "マクスウェル方程式,電磁場,電磁波,ガウス,ファラデー","Maxwell equations,electromagnetic field,EM wave,Gauss,Faraday",
 "active","primary",98,1,"https://en.wikipedia.org/wiki/Maxwell%27s_equations","United_Kingdom",90,
 "∇·E=ρ/ε₀; ∇·B=0; ∇×E=-∂B/∂t; ∇×B=μ₀J+μ₀ε₀∂E/∂t","url_present"),

("ee_b2_002","キルヒホッフの法則","Kirchhoff's Circuit Laws","KCL/KVL",
 "電気回路の電流保存（KCL: 各ノードで流入=流出）と電圧保存（KVL: 閉ループの電圧和=0）を述べる回路解析の基本法則。あらゆる集中定数回路の解析基盤。",
 "回路解析・SPICE シミュレーション・電源設計の出発点。電気工学教育の必須基礎。","電気電子工学","古典回路理論",1845,None,
 "基礎理論","電気回路全般","集中定数近似が成立する低周波回路","回路の電流・電圧を系統的に求める場合",
 "分布定数回路ではKCL/KVLはどのように修正されるか","テブナン・ノートン定理",
 "キルヒホッフ,KCL,KVL,回路解析,ノード","Kirchhoff,KCL,KVL,circuit analysis,node",
 "active","primary",98,1,"https://en.wikipedia.org/wiki/Kirchhoff%27s_circuit_laws","Germany",90,
 "KCL: Σi_k=0 at node; KVL: Σv_k=0 around loop; basis of nodal/mesh analysis","url_present"),

("ee_b2_003","演算増幅器","Operational Amplifier","Op-Amp",
 "差動入力で極めて高いオープンループ利得を持つ集積回路。負帰還と組み合わせて反転・非反転増幅・積分・微分・比較・フィルタなど多様なアナログ機能を実現する。",
 "アナログ信号処理・センサインターフェース・オーディオ・計測器の基本ビルディングブロック。741・LM741以来の標準部品。","電気電子工学","アナログ回路",1941,None,
 "アナログ回路設計","信号処理・センサ・制御","アナログ演算が必要","汎用アナログ信号処理の実装",
 "理想演算増幅器の仮定はどのような周波数特性で破綻するか","コンパレータ（帰還なし）・トランジスタ回路",
 "演算増幅器,オペアンプ,アナログ回路,増幅器,フィードバック","op-amp,operational amplifier,analog circuit,amplifier,feedback",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Operational_amplifier","North_America",90,
 "ideal: A_OL→∞, Rin→∞, Rout→0; closed-loop: Av=-Rf/Rin (inverting)","url_present"),

("ee_b2_004","フーリエ変換と信号スペクトル","Fourier Transform and Signal Spectrum","Fourier Transform",
 "時間領域信号を周波数成分の重ね合わせとして表現する数学的変換。FFTアルゴリズムにより計算量O(n log n)で実現し、スペクトル解析・フィルタ設計・音声/画像処理の基盤となる。",
 "通信・音声・画像・レーダ・地震解析のスペクトル解析の基盤。FFT（高速フーリエ変換）は20世紀最重要アルゴリズムの一つに選ばれる。","電気電子工学","信号処理理論",1822,None,
 "信号解析","通信・音声・画像・制御","定常または準定常信号のスペクトル解析","時間域から周波数域への変換",
 "短時間フーリエ変換（STFT）はウェーブレットとどう使い分けるか","ウェーブレット変換（非定常信号）・ラプラス変換（LTI系）",
 "フーリエ変換,FFT,スペクトル,信号処理,周波数","Fourier transform,FFT,spectrum,signal processing,frequency",
 "active","primary",98,1,"https://en.wikipedia.org/wiki/Fourier_transform","France",90,
 "X(f)=∫x(t)e^(-j2πft)dt; FFT: O(N log N) via DFT butterfly; Parseval: ∫|x|²=∫|X|²","url_present"),

("ee_b2_005","ナイキスト-シャノンのサンプリング定理","Nyquist-Shannon Sampling Theorem","Nyquist Theorem",
 "帯域制限信号を完全に再構成するには、最高周波数の2倍以上のサンプリングレートが必要であることを示す定理。デジタル音声・画像・通信の基礎を確立した。",
 "CD音質（44.1kHz=2×22.05kHz）・デジタルカメラ（CCD/CMOSのサンプリング）・ADCデザインの直接的根拠。デジタル信号処理の第一原理。","電気電子工学","信号処理理論",1928,None,
 "基礎理論","A/D変換・通信・音声","帯域制限信号のデジタル化","アナログ信号をデジタル変換する際の最小サンプリングレート設計",
 "エイリアシングはなぜサンプリング定理違反で生じるか","Delta-Sigma変換（オーバーサンプリング）",
 "ナイキスト,サンプリング定理,ADC,エイリアシング,デジタル信号処理","Nyquist,sampling theorem,ADC,aliasing,digital signal processing",
 "active","primary",98,1,"https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem","North_America",90,
 "f_s > 2f_max; x(t)=Σx[n]sinc(t/T-n); aliasing: f_alias=|f-k·f_s|","url_present"),

("ee_b2_006","FIRフィルタ・IIRフィルタ","FIR and IIR Digital Filters","Digital Filters",
 "有限インパルス応答（FIR）フィルタは常に安定で線形位相特性を持ち、無限インパルス応答（IIR）フィルタは少ない係数で急峻な特性を実現する。用途に応じて設計手法（ウィンドウ法・バターワース・チェビシェフ）が選択される。",
 "音声処理・通信受信機・医用信号処理・制御システムのデジタルフィルタ設計の標準手法。DSPチップのコア機能。","電気電子工学","デジタル信号処理",1960,None,
 "フィルタ設計","音声・通信・医療・制御","デジタル信号の帯域制限・雑音除去","線形位相（FIR）または計算量節約（IIR）の選択",
 "FIRのウィンドウ法とIIRのバイリニア変換はどう使い分けるか","アナログフィルタ（バターワース・チェビシェフ）",
 "FIRフィルタ,IIRフィルタ,デジタルフィルタ,信号処理,DSP","FIR filter,IIR filter,digital filter,signal processing,DSP",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Finite_impulse_response","North_America",90,
 "FIR: H(z)=Σh[n]z^-n (all zeros); IIR: H(z)=B(z)/A(z); stability: poles inside |z|<1","url_present"),

("ee_b2_007","CMOSトランジスタとロジックゲート","CMOS Transistor and Logic Gates","CMOS Logic",
 "p型とn型MOSトランジスタを相補的に組み合わせ、待機時の電流を極小にしながら論理演算を実現するデジタル回路技術。現代デジタル集積回路の普遍的実装方式。",
 "Intel・AMD・ARMアーキテクチャのCPU・GPU・メモリの全デジタル回路の実装基盤。スマートフォンから量子コンピュータ制御回路まで。","電気電子工学","半導体デジタル回路",1963,None,
 "デジタル回路設計","CPU・GPU・FPGA・ASIC","デジタル論理演算","低消費電力デジタル回路の実装",
 "FinFETはプレーナMOSFETに比べショートチャネル効果をどう抑制するか","TTLロジック（バイポーラ）・GaN HEMTパワー回路",
 "CMOS,トランジスタ,論理ゲート,デジタル回路,集積回路","CMOS,transistor,logic gate,digital circuit,integrated circuit",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/CMOS","North_America",90,
 "V_IL<V_th<V_IH; static power: I_leak×V_DD; dynamic: C_L×V_DD²×f","url_present"),

("ee_b2_008","RTL設計とVHDL/Verilog","RTL Design and Hardware Description Languages","RTL/HDL",
 "レジスタ転送レベル（RTL）でハードウェアの動作を記述するHDL言語（VHDL/Verilog/SystemVerilog）を用い、論理合成ツールで実際のゲート回路に自動変換するデジタル設計手法。",
 "FPGA・ASIC設計の標準ワークフロー。Xilinx・Intel（Altera）FPGA開発や台積電・サムスンへのASIC発注に使用。","電気電子工学","デジタルハードウェア設計",1983,None,
 "ハードウェア設計","FPGA・ASIC・SoC","カスタムデジタル回路の設計","ハードウェア動作を記述して論理合成する場合",
 "RTL設計とHLS（高位合成）はどのレベルの抽象度で異なるか","回路図入力（スキマティック）・HLS（C/C++からの合成）",
 "RTL設計,VHDL,Verilog,FPGA,ASIC,論理合成","RTL design,VHDL,Verilog,FPGA,ASIC,logic synthesis",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Register-transfer_level","North_America",90,
 "RTL: state registers + combinational logic; synthesis maps to cell library (AND/OR/FF)","url_present"),

("ee_b2_009","位相同期ループ","Phase-Locked Loop","PLL",
 "参照信号との位相差をフィードバックして電圧制御発振器（VCO）の周波数・位相を追従させる閉ループ制御回路。クロック生成・周波数合成・復調・ジッタ低減に使用。",
 "CPU・GPU・通信チップのクロック生成、ラジオ受信機の周波数合成、SDH/SONET同期の基本回路。すべての同期デジタルシステムに内在。","電気電子工学","アナログ・混載回路",1932,None,
 "回路設計","クロック生成・通信・測定","周波数・位相の精密制御","高精度クロックまたは周波数合成が必要な場合",
 "PLLのループフィルタ設計は帯域幅とジッタトレードオフにどう影響するか","DLL（遅延同期ループ）・水晶発振器",
 "PLL,位相同期ループ,VCO,クロック生成,周波数合成","PLL,phase-locked loop,VCO,clock generation,frequency synthesis",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Phase-locked_loop","North_America",90,
 "θ_err→LF→V_ctrl→VCO→θ_out; ω_n=√(K_d·K_o/τ); ζ for stability","url_present"),

("ee_b2_010","電力変換 — DC-DCコンバータ","Power Conversion — DC-DC Converter","DC-DC Converter",
 "スイッチング素子とインダクタ・コンデンサを用いてDC電圧を昇圧（ブーストコンバータ）・降圧（バックコンバータ）・反転（バックブーストコンバータ）する電力変換回路。高効率（90-98%）。",
 "スマートフォン充電・サーバ電源・EV・太陽光発電インバータの電力変換の核心技術。電力電子工学の主要応用。","電気電子工学","電力電子工学",1959,None,
 "電力変換回路","EV・再エネ・電子機器電源","DC電圧変換・高効率が必要","バッテリや再エネからの電圧変換",
 "スイッチング周波数とインダクタ・コンデンサ体積のトレードオフをどう設計するか","線形電圧レギュレータ（低効率・シンプル）",
 "DC-DCコンバータ,電力変換,スイッチング電源,EV,太陽光","DC-DC converter,power conversion,switching power supply,EV,solar",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/DC-to-DC_converter","North_America",90,
 "buck: V_out=D·V_in; boost: V_out=V_in/(1-D); efficiency η=P_out/P_in>90%","url_present"),

("ee_b2_011","インバータと三相交流駆動","Inverter and Three-Phase AC Drive","Power Inverter",
 "DC電力をスイッチング（PWM変調）によりAC波形に変換するインバータ回路。三相モータ駆動・系統連系・UPS・EV駆動系の核心。シリコンカーバイド（SiC）パワーデバイスで高周波高効率化が進む。",
 "工場の可変速モータ駆動・EV推進・風力・太陽光の系統連系インバータで電力システムの電動化を支える。","電気電子工学","電力電子工学",1960,None,
 "電力変換","EV・産業モータ・再エネ系統連系","AC可変速制御または系統連系が必要","DC→AC変換とモータ制御の組み合わせ",
 "SiC-MOSFETはSiと比べどのような特性でインバータ効率を改善するか","サイリスタ整流器（一方向整流）",
 "インバータ,三相交流,PWM,SiC,電力電子","inverter,three-phase AC,PWM,SiC,power electronics",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Power_inverter","Japan",90,
 "PWM: duty=V_ref/V_dc; THD=√(Σ V_n²)/V_1; SiC: 10× freq, ×3 breakdown field vs Si","url_present"),

("ee_b2_012","電磁両立性設計","Electromagnetic Compatibility Design","EMC Design",
 "電子機器が意図せず発する電磁雑音（EMI）を規制値内に抑え、外部からの電磁干渉（EMS）に耐性を持たせる設計技術。グラウンドプレーン・シールド・フィルタ・PCBレイアウト最適化を使用。",
 "FCC・CE・VCCI規格への適合が製品市場投入の前提。自動車（CISPR25）・医療機器（IEC 60601）・産業機器の必須設計プロセス。","電気電子工学","電磁両立性",1970,None,
 "EMC設計","全電子機器","電磁干渉放射・感受性の規制対応","製品の電磁適合認証取得",
 "差動モードノイズと共通モードノイズはそれぞれどのように対策するか","シールド（放射低減）・バイパスキャパシタ（電源ノイズ）",
 "EMC,電磁両立性,EMI,EMS,シールド,グラウンド","EMC,electromagnetic compatibility,EMI,EMS,shield,ground",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Electromagnetic_compatibility","North_America",90,
 "EMI limit: CISPR32 Class B; CM choke: Z_CM=jωL; shield effectiveness SE=20log(E_0/E_s)","url_present"),

("ee_b2_013","アナログ-デジタル変換器設計","Analog-to-Digital Converter Design","ADC Design",
 "連続アナログ信号を離散デジタル数値に変換するADC回路。逐次比較型（SAR）・パイプライン型・デルタシグマ型など多様なアーキテクチャが性能（速度・分解能・消費電力）のトレードオフに応じて使われる。",
 "センサ・通信受信機・医療画像・音声処理・レーダの入力段で不可欠。ADCの性能が全アナログ入力系の性能上限を決定する。","電気電子工学","アナログ・混載回路",1926,None,
 "混載回路設計","センサシステム・通信・医療","アナログ入力のデジタル化","精度・速度・消費電力のトレードオフに応じたADC選択",
 "ENOB（有効ビット数）はSNDRからどのように計算するか","DAC（逆変換）・サンプルホールド回路",
 "ADC,アナログデジタル変換,SAR,デルタシグマ,分解能","ADC,analog-to-digital converter,SAR,delta-sigma,resolution",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Analog-to-digital_converter","North_America",90,
 "ENOB=(SNDR-1.76)/6.02; SAR: binary search O(N cycles); ΔΣ: noise shaping + OSR","url_present"),

("ee_b2_014","フィールドプログラマブルゲートアレイ","Field Programmable Gate Array","FPGA",
 "論理ブロック・配線スイッチ・DSPブロック・メモリブロックを含む再プログラム可能なハードウェア基板。RTL設計をASICコスト・期間なしで実装できる。AI推論・通信・計測の高速プロトタイピングに使用。",
 "データセンタ（Microsoft Azure FPGAサーバ）・高頻度取引・5G基地局・医療機器の特化ハードウェアアクセラレーション。NVIDIAによるMellanox/Xilinxの買収が戦略的重要性を示す。","電気電子工学","プログラマブルロジック",1985,None,
 "ハードウェア実装","AI推論・通信・高速処理・プロトタイプ","汎用CPUでは不足な並列処理が必要","ASICほど大量生産しないが高性能な専用回路が必要な場合",
 "FPGAとASICとGPUはそれぞれどのようなワークロードに適するか","ASIC（高量産・低消費）・GPU（大規模並列計算）",
 "FPGA,プログラマブルロジック,RTL,ハードウェアアクセラレーション,Xilinx","FPGA,programmable logic,RTL,hardware acceleration,Xilinx",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Field-programmable_gate_array","North_America",90,
 "LUT4 implements any 4-input logic; routing crossbar; CLB: LUT+FF+carry chain","url_present"),

("ee_b2_015","OFDMと多重アクセス技術","OFDM and Multiple Access Techniques","OFDM / OFDMA",
 "搬送波を多数の直交サブキャリアに分割して並列伝送する直交周波数分割多重（OFDM）。4G LTE・5G NR・Wi-Fi・DAB放送の物理層変調方式として採用。PAPR問題・CP挿入・ガードバンド設計が実装課題。",
 "4G/5G/Wi-Fi 6（802.11ax）の物理層の中核技術。マルチパスフェージングへの耐性とスペクトル効率の高さから2000年代以降の無線通信標準を定義。","電気電子工学","無線通信",1966,None,
 "無線変調技術","4G/5G/Wi-Fi・ADSL・DAB","マルチパスフェージング環境","広帯域高速無線通信",
 "OFDM のPAPR問題はなぜパワーアンプ効率を低下させるか","CDMAスペクトラム拡散（3G）・SC-FDMA（LTEアップリンク）",
 "OFDM,4G,5G,Wi-Fi,マルチパス,サブキャリア","OFDM,4G,5G,Wi-Fi,multipath,subcarrier",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Orthogonal_frequency-division_multiplexing","Europe",90,
 "y[k]=Σ x[n]e^(j2πnk/N) (IDFT at TX); CP length ≥ max delay spread; PAPR≈10log(N) dB","url_present"),

("ee_b2_016","MIMOアンテナ技術","MIMO Antenna Technology","MIMO",
 "Multiple-Input Multiple-Output。送受信双方に複数アンテナを使用し、空間多重・ダイバーシティ・ビームフォーミングによってスペクトル効率を大幅に向上させる無線通信技術。4G/5G必須技術。",
 "LTE（最大8×8 MIMO）・5G NR（マッシブMIMO 64-256アンテナ）・Wi-Fi 6Eの空間多重の基盤。シャノン容量の実用的な拡大手段。","電気電子工学","無線通信",1996,None,
 "アンテナ・無線","4G/5G・Wi-Fi・衛星通信","マルチパス環境・空間多重","無線スループットを大幅に向上させる場合",
 "ビームフォーミングと空間多重はどのようなチャネル条件でそれぞれ有効か","SISOアンテナ（単一送受信）",
 "MIMO,マッシブMIMO,5G,ビームフォーミング,空間多重","MIMO,massive MIMO,5G,beamforming,spatial multiplexing",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/MIMO","North_America",90,
 "C=log₂det(I+(SNR/N_t)HH†) b/s/Hz; SVD: H=UΣV†; Σ² eigenvalues=channel gains","url_present"),

("ee_b2_017","エラー訂正符号 — ターボ符号とLDPC","Error Correction — Turbo and LDPC Codes","Turbo/LDPC Codes",
 "反復復号アルゴリズムを用いてシャノン限界に近い性能を達成する誤り訂正符号。ターボ符号は3G標準に、LDPC符号は4G・5G NR・DVB-S2・Wi-Fi 6に採用。信頼伝播（Belief Propagation）が復号アルゴリズム。",
 "3G（ターボ符号）・4G/5G NR・DVB-S2・IEEE 802.11nの誤り訂正の中核。シャノン限界0.04dB以内に迫る実用符号。","電気電子工学","通信符号理論",1993,None,
 "誤り訂正符号","移動通信・衛星通信・記憶媒体","ノイズの多いチャネルでの信頼性通信","シャノン限界に近い通信効率が必要な場合",
 "ターボ符号とLDPCの復号計算量とレイテンシのトレードオフはどうか","畳み込み符号（ビタービ復号）・リードソロモン符号",
 "ターボ符号,LDPC,誤り訂正,シャノン,通信符号","turbo code,LDPC,error correction,Shannon,channel coding",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Turbo_code","France",90,
 "Eb/N0 within 0.04dB of Shannon limit; LDPC BP: H·c^T=0 over GF(2); iteration decoding","url_present"),

("ee_b2_018","電力系統安定化と保護リレー","Power System Stability and Protection Relays","Power System Protection",
 "送配電系統における系統安定性（電圧・周波数・位相）の維持と、故障発生時の選択的かつ高速な遮断を行う保護リレーシステム。距離継電器・差動継電器・デジタル保護が標準。",
 "電力グリッドの信頼性を担保する重要インフラ技術。停電被害の最小化と再エネ大量連系に伴う系統安定化に不可欠。","電気電子工学","電力システム工学",1900,None,
 "電力工学","送配電系統・変電所・スマートグリッド","電力系統の安定运用","停電防止・系統保護の設計",
 "再生可能エネルギーの大量連系はなぜ系統慣性を低下させ安定性に影響するか","従来の機械式継電器",
 "電力系統保護,継電器,安定性,スマートグリッド,送配電","power system protection,relay,stability,smart grid,transmission",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Power_system_protection","Europe",90,
 "swing equation: M·dω/dt=P_m-P_e-D·ω; impedance relay: Z_measured<Z_set","url_present"),

("ee_b2_019","量子ドットと量子光学素子","Quantum Dots and Quantum Photonic Devices","Quantum Dots",
 "電子を3次元すべてに量子閉じ込めした半導体ナノ構造（量子ドット）。サイズ依存の離散エネルギー準位を持ち、LEDバックライト（Samsung QLED）・量子コンピュータの量子ビット・単一光子源として応用される。",
 "QLED TV・量子通信の単一光子源・量子コンピュータの光量子ビットとして産業化が進む。次世代ディスプレイと量子情報の接点技術。","電気電子工学","量子電子工学",1983,None,
 "量子ナノ技術","ディスプレイ・量子通信・量子コンピュータ","量子閉じ込め効果の活用","量子効果を利用したナノ光源・発光素子",
 "量子ドットの蛍光波長はどのようにサイズで制御するか","バルク半導体LED・有機EL（OLED）",
 "量子ドット,QLED,単一光子源,量子通信,ナノテクノロジー","quantum dot,QLED,single photon source,quantum communication,nanotechnology",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Quantum_dot","North_America",90,
 "E_n = ħ²π²n²/(2m*L²); confinement ΔE∝1/L²; emission λ tunable by dot size d","url_present"),

("ee_b2_020","ニューロモルフィックコンピューティング","Neuromorphic Computing","Neuromorphic Chips",
 "生物の神経回路を模倣したスパイキングニューラルネットワーク（SNN）をハードウェアで実装し、事象駆動・超低消費電力で推論するアーキテクチャ。Intel Loihi・IBM TrueNorthが代表実装。",
 "エッジAI・ウェアラブル・ロボット感覚処理での超低電力推論。GPUの1000分の1の消費電力で時系列センサ処理を実現することを目標とする次世代AIチップ技術。","電気電子工学","AI専用ハードウェア",2014,None,
 "スペシャルパーパスハードウェア","エッジAI・ロボット・IoT","超低消費電力の事象駆動AI処理","バッテリ駆動デバイスでの常時AI推論",
 "SNNの訓練はANNと比べてなぜ勾配計算が困難か","Von Neumann型GPU・特定用途ASIC（TPU）",
 "ニューロモルフィック,スパイキングニューラルネットワーク,Loihi,エッジAI,低消費電力","neuromorphic,spiking neural network,Loihi,edge AI,low power",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Neuromorphic_engineering","North_America",90,
 "LIF neuron: τ_m·dV/dt=-(V-V_rest)+R·I; spike: V>V_th → reset; STDP learning rule","url_present"),

("ee_b2_021","ガリウムナイトライドパワーデバイス","Gallium Nitride Power Devices","GaN Power Electronics",
 "ワイドバンドギャップ半導体GaNを用いた高電子移動度トランジスタ（HEMT）。Siより高い絶縁破壊電場・高電子移動度により、高周波・高電圧・低損失パワー変換を実現する。",
 "急速充電器（GaN充電器は小型・軽量）・5G基地局パワーアンプ・EV充電インフラの次世代電力デバイス。SiCと並ぶ第三世代半導体の主力。","電気電子工学","パワー半導体",2005,None,
 "パワーデバイス","急速充電・5G・EV","Si限界を超える高周波高電圧変換","小型高効率電力変換",
 "GaNはSiCと比べてどのような用途に有利か","SiC MOSFET（高電圧・高耐熱）・Si IGBT（大電流・低コスト）",
 "GaN,ワイドバンドギャップ,HEMT,パワーデバイス,急速充電","GaN,wide bandgap,HEMT,power device,fast charging",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Gallium_nitride","Japan",90,
 "E_b(GaN)=3.3 MV/cm vs Si 0.3; R_on·A ∝ 1/E_b³; f_switching to MHz range","url_present"),

("ee_b2_022","フォトニクス集積回路","Silicon Photonics and Photonic ICs","Silicon Photonics",
 "シリコンプラットフォーム上に光導波路・変調器・受光器・グレーティングカプラを集積した光電子集積回路。データセンタ間の光相互接続・LiDAR・量子光学の基盤技術。",
 "データセンタ高速光インターコネクト（400G/800G）・自動運転LiDAR・量子通信の実用基盤技術。Intel・IBM・Luxteraが産業化を推進。","電気電子工学","光電子工学",2004,None,
 "フォトニクス","データセンタ・LiDAR・量子通信","高密度光通信・光センシング","CMOSファブで製造できる光回路",
 "シリコン光変調器はなぜPNジャンクションのプラズマ分散効果を利用するか","III-V族化合物半導体フォトニクス",
 "シリコンフォトニクス,フォトニクス集積回路,光インターコネクト,LiDAR","silicon photonics,photonic IC,optical interconnect,LiDAR",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Silicon_photonics","North_America",90,
 "waveguide: n_Si=3.45 > n_SiO2=1.44; MZM: ΔΦ=π·V/V_π; bandwidth >50 GHz","url_present"),

("ee_b2_023","スパース信号処理と圧縮センシング","Compressed Sensing and Sparse Signal Processing","Compressed Sensing",
 "信号がスパース（疎）な表現を持つ場合、ナイキスト定理より少ない計測数で信号を完全に再構成できることを示す理論。L1正則化（LASSO）と乱択計測行列がキー技術。",
 "MRI撮影時間短縮（Candès・Romberg・Tao 2006）・レーダ解像度向上・無線スペクトル推定の革新技術。医用MRIの撮影時間を2-10倍短縮。","電気電子工学","信号処理理論",2004,None,
 "信号処理","MRI・レーダ・通信・センサ","信号がスパースな変換域を持つ","計測回数を減らして信号を復元したい場合",
 "限制等距性条件（RIP）はなぜスパース信号の完全復元を保証するか","ナイキストサンプリング・完全計測",
 "圧縮センシング,スパース信号,MRI,LASSO,乱択計測","compressed sensing,sparse signal,MRI,LASSO,random measurements",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Compressed_sensing","North_America",90,
 "RIP: (1-δ_s)||x||²≤||Ax||²≤(1+δ_s)||x||²; recover: min||x||_1 s.t. Ax=b","url_present"),

("ee_b2_024","カルマンフィルタ","Kalman Filter","Kalman Filter",
 "線形ガウスシステムの状態推定に用いる再帰的ベイズフィルタ。予測（時間更新）と観測更新の2ステップで最適な最小分散推定を提供。非線形系にはEKF・UKF・粒子フィルタが使用される。",
 "GPS/INS統合ナビゲーション・ロボットの自己位置推定（SLAM）・株価予測・宇宙機軌道推定の標準フィルタリング手法。アポロ計画の軌道計算に使用。","電気電子工学","制御・推定理論",1960,None,
 "状態推定","自律移動・航法・制御","線形ガウス状態空間モデル","ノイズのある観測から最適状態推定が必要な場合",
 "拡張カルマンフィルタと無香カルマンフィルタはどのように非線形を扱うか","移動平均・最小二乗法（非再帰的）",
 "カルマンフィルタ,状態推定,SLAM,GPS,ベイズ","Kalman filter,state estimation,SLAM,GPS,Bayesian",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Kalman_filter","Hungary",90,
 "K=PH^T(HPH^T+R)^-1; x̂=x̂_pred+K(z-Hx̂_pred); P=(I-KH)P_pred","url_present"),

("ee_b2_025","テストアンドDFT（テスト設計容易化）","Design for Testability — Scan Chain","DFT/Scan",
 "集積回路の製造テストを容易にするため、フリップフロップをシフトレジスタ（スキャンチェーン）として接続し、内部状態を外部から読み書き可能にする設計技術。ATPG・バウンダリスキャン（JTAG）と組み合わせる。",
 "高品質半導体製品の出荷前テストの基盤。テストカバレッジ（故障検出率）99%以上が要求される自動車・医療用LSIに必須。","電気電子工学","テスト・信頼性工学",1975,None,
 "LSI設計","半導体テスト・品質保証","大規模デジタルIC製造テスト","内部故障の高カバレッジテスト",
 "スタックアットモデルの故障検出とトランジションの故障検出はどう異なるか","機能テスト（テストパターンなし・カバレッジ低）",
 "DFT,スキャンチェーン,JTAG,ATPG,半導体テスト","DFT,scan chain,JTAG,ATPG,semiconductor test",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Design_for_testing","North_America",90,
 "stuck-at fault model: line s@0 or s@1; ATPG: set FF values via scan; coverage=detected/total","url_present"),

("ee_b2_026","SAR ADCアーキテクチャ","Successive Approximation Register ADC","SAR ADC",
 "比較器とデジタルアナログ変換器（DAC）を用いた2進探索でアナログ入力をデジタル変換する逐次比較型ADC。Nビット変換にN比較でシンプルかつ低消費電力。マイクロコントローラ・ウェアラブル・IoTセンサに標準搭載。",
 "STM32・PIC・Arduino等マイコン内蔵ADCとして最も普及するアーキテクチャ。ウェアラブル・医療センサの省電力計測の標準。","電気電子工学","アナログ・混載回路",1954,None,
 "ADC回路","マイコン・IoT・ウェアラブル・医療センサ","中速・中精度（8-16bit）・低消費電力","IoTセンサの計測ノードのADC",
 "SAR ADCの電力とデルタシグマADCの精度のトレードオフはどうか","デルタシグマADC（高精度・低速）・フラッシュADC（高速・高消費）",
 "SAR ADC,逐次比較,ADC,低消費電力,センサ","SAR ADC,successive approximation,ADC,low power,sensor",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Successive-approximation_ADC","North_America",90,
 "N-cycle binary search; MSB trial first; ENOB limited by DAC matching and kT/C noise","url_present"),

("ee_b2_027","ミリ波レーダとイメージング","Millimeter Wave Radar and Imaging","mmWave Radar",
 "76-81GHz帯のミリ波を使用した近距離・高精度レーダシステム。ドップラー速度・方位・距離を高分解能で計測し、自動車ADASの死角検知・工場内人体検知・医療イメージングに使用される。",
 "自動車ADAS（死角検知・緊急ブレーキ）・スマートファクトリーの安全センサ・5G Fixed Wireless Accessの主要応用。Texas Instruments IWRシリーズが産業標準。","電気電子工学","RFセンシング",2000,None,
 "レーダシステム","自動車・スマートファクトリー・医療","近距離高分解能センシング","非接触での高精度距離・速度・方位計測",
 "mmWaveレーダとLiDARはどのような気象条件で性能差が出るか","LiDAR（光学・高角度分解能）・カメラ（テクスチャ・低コスト）",
 "ミリ波レーダ,FMCW,ADAS,自動車,スマートファクトリー","mmWave radar,FMCW,ADAS,automotive,smart factory",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Millimetre-wave_radar","North_America",90,
 "FMCW: R=f_beat·c/(2·slope); v=f_doppler·λ/2; range res=c/(2·BW)","url_present"),

("ee_b2_028","5G NR物理層設計","5G NR Physical Layer Design","5G NR",
 "3GPP Release 15以降で標準化されたNew Radio（NR）の物理層。Sub-6GHzとmmWave対応の可変ニューメロロジー（μ=0-4、サブキャリア間隔15-240kHz）・マッシブMIMO・LDPC/Polar符号が特徴。",
 "グローバル5Gネットワーク（2019-現在）の技術基盤。3GPP Release 17-18で産業用IoT・Non-Terrestrial Network（NTN）・RedCapに拡張。","電気電子工学","移動通信標準",2017,None,
 "無線通信標準","スマートフォン・産業用IoT・NTN","最新世代移動通信","Sub-6GHzまたはmmWave高速無線通信",
 "5G NRのフレーム構造でTDD/FDDはどのように柔軟なスロット割当てを実現するか","4G LTE（固定ニューメロロジー・最大8×8 MIMO）",
 "5G NR,3GPP,物理層,OFDM,マッシブMIMO","5G NR,3GPP,physical layer,OFDM,massive MIMO",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/5G_NR","Europe",90,
 "SCS: Δf=2^μ×15kHz; slot=14 OFDM sym; max 100MHz BW @sub-6; 400MHz @mmW","url_present"),

("ee_b2_029","センサフュージョンとSLAM","Sensor Fusion and SLAM","SLAM",
 "異なるモダリティのセンサ（カメラ・LiDAR・IMU・GPS）のデータを融合して自己位置と環境地図を同時に推定するアルゴリズム。グラフベースSLAM・EKF-SLAM・LiDARオドメトリが主要手法。",
 "自律移動ロボット（ROS・Spot）・自動運転車・ドローン・ARヘッドセットの自己位置推定の中核技術。","電気電子工学","ロボット知覚",2001,None,
 "ロボット知覚","自律走行・ドローン・AR・スマート倉庫","環境地図不明の自律移動","動的環境での地図と自己位置の同時推定",
 "Visual SLAMとLiDAR SLAMはどのような環境でそれぞれ優位か","GPS+地図（GPS有効環境での位置推定）",
 "SLAM,センサフュージョン,LiDAR,自動運転,ロボット","SLAM,sensor fusion,LiDAR,autonomous driving,robot",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Simultaneous_localization_and_mapping","Australia",90,
 "GraphSLAM: min Σ||z_t-h(x_t)||²_Σ^-1; loop closure detects revisited locations","url_present"),

("ee_b2_030","超伝導量子ビット — トランズモン","Superconducting Qubit — Transmon","Transmon Qubit",
 "ジョセフソン接合を含む超伝導回路で実現する量子ビット。電荷量子ビット（クーパーペアボックス）を進化させたトランズモンはチャージノイズに対する頑健性を持ち、Google・IBM・Rigettiの量子プロセッサで採用。",
 "Google Sycamore・IBM Falcon・Eagle・Condorプロセッサの量子ビット実装。量子超越性実証（2019）に使用されたハードウェア。","電気電子工学","量子デバイス工学",2007,None,
 "量子ビット実装","量子コンピュータ","希釈冷凍機（15mK以下）・マイクロ波制御","超伝導量子プロセッサの量子ビット",
 "トランズモンとフラックスニウムはどのような性能トレードオフがあるか","イオントラップ量子ビット・フォトニック量子ビット",
 "超伝導量子ビット,トランズモン,Josephson接合,量子コンピュータ","superconducting qubit,transmon,Josephson junction,quantum computing",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Transmon","North_America",90,
 "H=4E_C(n-n_g)²-E_J·cos(φ); E_J/E_C>>1 (transmon regime); T1~100μs","url_present"),

("ee_b2_031","中国半導体自給政策と東アジアICサプライチェーン","East Asian IC Supply Chain and Self-Sufficiency","East Asia Semiconductor Industry",
 "日本・韓国・台湾・中国を中心とする東アジア半導体エコシステム。TSMC（台湾）の極端紫外線露光による2nm以下製造、Samsung/SK Hynixの3D NANDとHBM、日本の半導体材料・製造装置独占、中国のSMICによる国産化推進が複雑に絡み合う。",
 "世界半導体製造の80%以上が東アジアに集中。米中半導体戦争・輸出規制・CHIPsActが示す通り、地政学的焦点となっている。日本のラピダスによる2nm挑戦も進行中。","電気電子工学","東アジア半導体産業",1970,None,
 "産業・地政学","半導体産業政策・サプライチェーン","東アジア半導体産業","ICサプライチェーンの地政学的分析",
 "台湾積体電路製造（TSMC）のファウンドリモデルはどのようにファブレス設計を可能にしたか","垂直統合型IDM（Intel・Samsung）",
 "東アジア,半導体,TSMC,SMIC,サプライチェーン,地政学","East Asia,semiconductor,TSMC,SMIC,supply chain,geopolitics",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Semiconductor_industry","East_Asia",95,
 "TSMC market cap >$800B; EUV: NA=0.33→0.55(high-NA); SMIC N+2≈7nm-class","url_present"),

("ee_b2_032","日本の半導体材料産業","Japanese Semiconductor Materials Dominance","Japan Semiconductor Materials",
 "日本がフォトレジスト・高純度フッ化水素・シリコンウェーハ・EUVペリクルなどの半導体材料において世界市場を独占または寡占する産業構造。信越化学・SUMCO・JSR・東京応化工業・ステラケミファ等が中核企業。",
 "フォトレジスト（JSR・東京応化・信越化学で世界シェア90%以上）・シリコンウェーハ（信越化学・SUMCO60%超）など、最先端半導体製造の要件を満たせる材料は日本に集中。2019年対韓規制が示した地政学リスク。","電気電子工学","東アジア半導体産業",1970,None,
 "産業分析","材料サプライチェーン","半導体材料の供給戦略","高純度半導体材料のサプライチェーン分析",
 "EUVフォトレジストでなぜ日本企業が強いのか","SOXを活用した化学メーカー（DOW・BASF）",
 "日本,半導体材料,フォトレジスト,シリコンウェーハ,信越化学","Japan,semiconductor materials,photoresist,silicon wafer,Shin-Etsu",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Semiconductor_industry_in_Japan","Japan",98,
 "Japan: >90% EUV photoresist; >60% silicon wafer; >70% HF for wet etch; JSR+TOK dominant","url_present"),

("ee_b2_033","韓国メモリ半導体産業","Korean Memory Semiconductor Industry","Korea DRAM/NAND",
 "Samsung Electronics・SK Hynixが主導する韓国DRAMおよびNANDフラッシュ産業。世界DRAMシェア70%超・NAND 50%超。3D V-NAND・HBM（高帯域幅メモリ）でAIメモリ需要を主導する。",
 "AIブーム下でHBM3E需要が急増し、Samsung・SK Hynixの戦略的地位が急浮上。HBM3Eの歩留まり競争が世界AI半導体サプライチェーンの焦点。","電気電子工学","東アジア半導体産業",1983,None,
 "産業分析","メモリ産業・AI半導体","メモリ半導体の市場・技術分析","DRAMとNANDのサプライチェーン",
 "HBM（高帯域幅メモリ）とDDR5は何が異なるか","Micron（DRAM・NAND米国）・YMTC（中国NAND）",
 "韓国,Samsung,SK Hynix,DRAM,HBM,NAND","Korea,Samsung,SK Hynix,DRAM,HBM,NAND",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Samsung_Electronics","East_Asia",98,
 "Samsung+SK Hynix: ~73% DRAM; HBM: 2.5D stacking with TSV; bandwidth >1TB/s","url_present"),

("ee_b2_034","インド電子製造政策","India Electronics Manufacturing and PLI","India Electronics",
 "2020年以降インド政府がPLI（生産連動インセンティブ）スキームで推進する国内電子製造の育成政策。Apple iPhone・Samsung組立の移転・Tata Electronics・Foxconn・Vedanta-Foxconnの半導体工場計画が進む。",
 "中国+1戦略の受け皿として世界最大のApple iPhone組立拠点の一部がインドに移転。2026年以降の半導体製造開始を目指すが歩留まり・インフラ課題がある。","電気電子工学","南アジア電子産業",2020,None,
 "産業政策","電子機器製造・半導体","製造業政策の産業分析","新興電子製造拠点としてのインドの分析",
 "中国・台湾・韓国との比較でインド電子製造のどの点が競争上の弱点か","Vietnam（電子組立代替地）・Mexico（北米サプライチェーン）",
 "インド,PLI,電子製造,iPhone,半導体工場","India,PLI,electronics manufacturing,iPhone,semiconductor fab",
 "active","primary",82,1,"https://en.wikipedia.org/wiki/Electronics_industry_in_India","South_Asia",95,
 "PLI: $6.5B for mobile manufacturing; Apple India revenue FY24: ~$6B; 28nm fab: Tata+PSMC","url_present"),

("ee_b2_035","電力線通信とスマートメーター","Power Line Communication and Smart Meters","PLC/AMI",
 "既存の電力線をデータ通信媒体として使用する電力線通信（PLC）技術。スマートメーター・家電制御（HEMS）・電力会社の自動検針インフラ（AMI）に使用。OFDM変調で雑音の多い電力線チャネルに対応。",
 "日本電力会社のスマートメーター（2016-2024全戸展開）・欧州G3-PLC・北米PRIME標準によるAMIの基盤技術。電力インフラデジタル化の中核。","電気電子工学","電力通信インフラ",1990,None,
 "通信技術","スマートグリッド・AMI・HEMS","電力線を既存インフラとして通信に活用","新規配線なしで電力デバイス通信が必要な場合",
 "電力線チャネルの周波数依存減衰と雑音はどのようにOFDMサブキャリアマッピングで対応するか","Zigbee・Wi-SUN（無線・スマートメーター代替）",
 "電力線通信,PLC,スマートメーター,AMI,スマートグリッド","PLC,power line communication,smart meter,AMI,smart grid",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Power-line_communication","Japan",90,
 "PRIME/G3-PLC: OFDM on 3-500kHz; attenuation: 1dB/100m at 100kHz; impulsive noise","url_present"),

("ee_b2_036","バイオメディカル信号計測","Biomedical Signal Measurement","Biomedical Signal Processing",
 "心電図（ECG）・脳波（EEG）・筋電図（EMG）・血圧・血中酸素飽和度（SpO2）などの生体信号を高精度・低ノイズで計測するための電子回路・信号処理技術の体系。",
 "ウェアラブルヘルスデバイス（Apple Watch心電図・Oura Ring）・植込み型除細動器（ICD）・集中治療室モニタリングの技術基盤。","電気電子工学","バイオメディカルエレクトロニクス",1960,None,
 "計測システム","医療機器・ウェアラブル","生体信号の正確な計測と処理","ヒトの生理信号をリアルタイム計測・解析する場合",
 "ECGのコモンモード除去比（CMRR）はなぜ60Hz電源ノイズに対して重要か","超音波エコー・X線CT（非電気的生体計測）",
 "ECG,EEG,バイオメディカル,生体信号,ウェアラブル","ECG,EEG,biomedical,biosignal,wearable",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Biomedical_signal_processing","North_America",90,
 "ECG amp: CMRR>80dB; gain≈1000; noise<1μV RMS; ADC ≥12bit; bandwidth 0.05-150Hz","url_present"),

("ee_b2_037","光ファイバ通信システム","Optical Fiber Communication System","Optical Fiber",
 "シリカガラスの全反射を利用して光信号を伝送する通信システム。WDM（波長分割多重）・EDFA（エルビウム添加ファイバ増幅器）・DSP補償により10Tbps超の長距離高速伝送を実現する。",
 "インターネットバックボーン・海底ケーブル・5Gフロントホール/バックホールの基盤。光ファイバの伝送速度は無線通信に比べて桁違いに高い。","電気電子工学","光通信",1970,None,
 "通信インフラ","骨格ネットワーク・海底ケーブル・データセンタ接続","超大容量長距離通信","高密度光通信リンクの設計",
 "コヒーレント光通信はなぜ直接検波より高い周波数利用効率を達成するか","銅線（電気通信・帯域制限）",
 "光ファイバ,WDM,EDFA,コヒーレント光通信,海底ケーブル","optical fiber,WDM,EDFA,coherent optical,submarine cable",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Optical_fiber","United_Kingdom",90,
 "NA=√(n₁²-n₂²); dispersion limit: B²·L<10^17 b²·s^-1·m (SMF); EDFA: 1530-1565nm","url_present"),

("ee_b2_038","ハードウェアセキュリティ — PUFと耐タンパ設計","Hardware Security — PUF and Tamper Resistance","Hardware Security / PUF",
 "製造ばらつきを利用してICごとに固有の応答を生成するPhysical Unclonable Function（PUF）と、物理的解析攻撃（側チャネル攻撃・故障注入）に対する耐タンパ設計。IoT機器・決済端末のハードウェアルートオブトラストを構成。",
 "IoT機器認証（PKIに依存しないデバイスID）・スマートカード・HSM（ハードウェアセキュリティモジュール）のセキュリティ基盤。EMVチップカードの不正コピー防止。","電気電子工学","ハードウェアセキュリティ",2002,None,
 "セキュリティ設計","IoT・決済端末・認証基盤","ハードウェアレベルのセキュリティが必要","デバイス固有ID・耐タンパ実装",
 "側チャネル攻撃（電力解析・電磁解析）はどのように暗号実装を破るか","ソフトウェア暗号（サイドチャネル脆弱性が高い）",
 "PUF,ハードウェアセキュリティ,耐タンパ,側チャネル攻撃,IoT認証","PUF,hardware security,tamper resistance,side channel attack,IoT authentication",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Physical_unclonable_function","North_America",90,
 "PUF: challenge→response pair (CRP); Arbiter PUF: path delay diff from process variation","url_present"),

("ee_b2_039","アダプティブビームフォーミング","Adaptive Beamforming","Adaptive Array Beamforming",
 "アレーアンテナの重み係数を適応アルゴリズム（LMS・RLS・MVDR）で動的に最適化し、目標方向への利得最大化と干渉方向へのヌル形成を同時に実現する信号処理技術。",
 "4G/5G基地局の干渉抑制・レーダ・ソナー・音声マイクアレイ（会議システム・スマートスピーカ）の指向性制御に使用。","電気電子工学","アレー信号処理",1965,None,
 "信号処理","無線基地局・レーダ・音声","複数アンテナ/マイクで干渉抑制が必要","ビームを動的に目標方向に向ける場合",
 "MVDR（Capon）ビームフォーマとLCMVビームフォーマの制約の違いはどうか","固定ビームフォーミング（位相シフタのみ）",
 "適応ビームフォーミング,MVDR,LMS,アレーアンテナ,5G","adaptive beamforming,MVDR,LMS,array antenna,5G",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Beamforming","North_America",90,
 "MVDR: w=R^-1·a(θ_0)/(a(θ_0)^H·R^-1·a(θ_0)); LMS: w←w+μ·e·x*","url_present"),

("ee_b2_040","Bluetoothと近距離無線通信","Bluetooth and Short-Range Wireless","Bluetooth / BLE",
 "2.4GHz帯での近距離無線通信規格Bluetoothと省電力版BLE（Bluetooth Low Energy）。AFH（適応周波数ホッピング）で干渉回避し、BLEはコイン電池で何年も動作する超低電力プロファイルを持つ。",
 "スマートフォン周辺機器・ウェアラブル・IoTセンサ・医療機器・工場モニタリングの標準近距離無線通信。AirPods・Apple Watch・Fitbitの無線バックボーン。","電気電子工学","無線通信",1994,None,
 "近距離無線","ウェアラブル・IoT・スマートホーム","低消費電力近距離デバイス間通信","コイン電池で数ヶ月-数年動作するセンサノード",
 "BLEとZigbeeはメッシュネットワーク構成でどう異なるか","Wi-Fi（高帯域・高電力）・Zigbee（低レート・メッシュ）",
 "Bluetooth,BLE,近距離無線,IoT,ウェアラブル","Bluetooth,BLE,short-range wireless,IoT,wearable",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Bluetooth_Low_Energy","Europe",90,
 "BLE: 2.4GHz ISM; 1Mbps PHY; adv channels: 37-39; peak current 15mA; avg <1mA","url_present"),

("ee_b2_041","太陽電池とペロブスカイト次世代技術","Solar Cell and Perovskite Next-Gen Technology","Photovoltaics",
 "光起電力効果を用いて太陽光を直接電気に変換する太陽電池。結晶シリコン（標準）・CdTe・CIGS薄膜・ペロブスカイト（ハロゲン化鉛型：25%超効率）・タンデム型（43%超）の技術系譜がある。",
 "太陽光発電コストが10年で90%低下しグリッドパリティを達成。ペロブスカイト/Siタンデムセルは30%効率を突破し次世代商業化が進む。日本（ソニー・Panasonic・積水化学）・韓国・中国が競合。","電気電子工学","光電子デバイス",1954,None,
 "太陽光発電","再エネ発電・ビル統合太陽光・宇宙太陽光発電","太陽光エネルギー変換","低コスト高効率太陽電池の技術選択",
 "ペロブスカイト太陽電池の安定性問題はどのような封止・組成で改善されているか","風力発電・蓄電池",
 "太陽電池,ペロブスカイト,再生可能エネルギー,光起電力,タンデム","solar cell,perovskite,renewable energy,photovoltaics,tandem",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Perovskite_solar_cell","Japan",90,
 "η=J_sc·V_oc·FF/P_in; Si limit 29.4% (Auger); perovskite/Si tandem >33% certified","url_present"),

("ee_b2_042","ロボット制御アーキテクチャ — ROS","Robot Operating System","ROS / ROS2",
 "ロボットのセンサ・アクチュエータ・アルゴリズムをトピック・サービス・アクション通信でつなぐミドルウェアフレームワーク。ROS1からROS2（DDS通信・リアルタイム対応）に移行し、産業ロボット・自動運転のデファクトスタンダードとなった。",
 "Boston Dynamics・Toyota Research Institute・自動運転スタックのロボットソフトウェア基盤。ROSパッケージエコシステムで数千の再利用可能アルゴリズムが公開。","電気電子工学","ロボットシステム",2007,None,
 "ロボットミドルウェア","サービスロボット・自動運転・産業ロボット","複数センサ・アクチュエータの統合制御","オープンソースのロボットソフトウェアスタック構築",
 "ROS1とROS2はリアルタイム性と信頼性においてどう異なるか","PLCラダー制御（産業向けリアルタイム）・MATLAB Simulink",
 "ROS,ロボット制御,ミドルウェア,自動運転,センサ統合","ROS,robot operating system,middleware,autonomous driving,sensor integration",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Robot_Operating_System","North_America",90,
 "publish-subscribe over topics; DDS (ROS2) for QoS; lifecycle nodes; ROS2: real-time capable","url_present"),

("ee_b2_043","デジタルツインと産業IoT","Digital Twin and Industrial IoT","Digital Twin / IIoT",
 "物理アセットのリアルタイムデジタル複製（デジタルツイン）と産業機器・センサをネットワーク接続するIIoT（産業IoT）の融合。設備故障予測・プロセス最適化・製品設計のバーチャル検証を実現する。",
 "Siemens・GE・Boschがデジタルツインプラットフォームを主導。Industry 4.0の中核概念として製造業のDXを推進。風力タービン・航空エンジン・スマートファクトリーに実装。","電気電子工学","スマートマニュファクチャリング",2002,None,
 "産業DX","製造業・エネルギー・インフラ","物理システムのリアルタイムデジタル化","設備保全・プロセス最適化・設計検証の効率化",
 "デジタルツインにおけるサイバーフィジカルシステムのレイテンシ要件はどう定義するか","CAD/CAEシミュレーション（非リアルタイム）",
 "デジタルツイン,IIoT,Industry 4.0,スマートファクトリー,予知保全","digital twin,IIoT,Industry 4.0,smart factory,predictive maintenance",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Digital_twin","North_America",90,
 "DT synchronization: sensor→edge→cloud→model update <1s; anomaly: Mahalanobis distance","url_present"),

("ee_b2_044","ワイヤレス給電と電磁誘導充電","Wireless Power Transfer","WPT / Qi Charging",
 "電磁誘導または磁気共鳴によって非接触でエネルギーを伝送する技術。Qi規格（WPC）が15W～100Wまでのスマートフォン・ウェアラブル充電を標準化し、EV向け大電力ワイヤレス充電（SAE J2954：最大22kW）も進む。",
 "全スマートフォン（iPhone・Galaxy）のQiワイヤレス充電の標準技術。EVワイヤレス充電インフラが世界都市で展開中。ペースメーカーへの無線給電も研究段階。","電気電子工学","ワイヤレスエネルギー",1990,None,
 "エネルギー伝送","スマートフォン・EV・医療機器","非接触でエネルギー伝送が必要","ケーブルレス充電・動的EV充電",
 "磁気共鳴型（WiTricity）と電磁誘導型はどのような距離特性の違いがあるか","有線充電（高効率）・太陽電池（遠距離エネルギー）",
 "ワイヤレス給電,Qi,電磁誘導,EV充電,WPC","wireless power transfer,Qi,electromagnetic induction,EV charging,WPC",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Wireless_power_transfer","South_Korea",90,
 "η=k²Q₁Q₂/(1+k²Q₁Q₂); k: coupling coeff; Qi 1.3: 15W; J2954: 3.7/7.2/11/22kW","url_present"),

("ee_b2_045","二次電池 — リチウムイオン電池の電気化学","Lithium-Ion Battery Electrochemistry","Li-ion Battery",
 "正極（LiCoO2・NMC・LFP）・負極（グラファイト・シリコン）・電解液（LiPF6）の電気化学反応でエネルギーを蓄放するリチウムイオン電池。エネルギー密度・充電速度・サイクル寿命・安全性のトレードオフが設計課題。",
 "スマートフォン・ノートPC・EV・電力貯蔵システムの主要エネルギー蓄積技術。吉野彰氏のノーベル賞（2019）。全固体電池が次世代候補として開発中。","電気電子工学","電池・エネルギー貯蔵",1991,None,
 "エネルギー貯蔵","EV・スマートフォン・電力貯蔵","高エネルギー密度・再充電可能エネルギー貯蔵","電動モビリティ・ポータブル電子機器の電源",
 "NMC・LFP・LCO正極材料のエネルギー密度と安全性はどうトレードオフするか","鉛蓄電池（低コスト・重い）・全固体電池（開発中）",
 "リチウムイオン電池,EV,全固体電池,電気化学,エネルギー貯蔵","lithium-ion battery,EV,solid-state battery,electrochemistry,energy storage",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Lithium-ion_battery","Japan",95,
 "OCV=f(SOC); C-rate: 1C=full charge/discharge in 1h; cycle life: >1000 at 80% retention","url_present"),

("ee_b2_046","電力半導体パッケージング","Power Semiconductor Packaging","Power Module Packaging",
 "IGBT・SiC MOSFET・GaN HEMTをはじめとするパワー半導体チップを熱的・電気的・機械的に信頼性高く実装するパッケージング技術。DCB（直接銅接合）基板・はんだ接合・ワイヤボンディング・次世代SiC向けシンタリングが主要技術。",
 "EV インバータ・産業用電源・鉄道インバータ（Mitsubishi・富士電機・Infineon・ON Semi）のパワーモジュールの信頼性を決定する製造技術。","電気電子工学","パワーエレクトロニクス実装",1980,None,
 "パッケージング技術","EV・産業インバータ・鉄道","大電力・高温・高信頼性実装","パワー半導体の熱設計と長寿命化",
 "シンタリング接合は従来はんだに比べどのような熱サイクル耐久性を提供するか","ワイヤボンディング（従来）・はんだ接合",
 "パワーモジュール,パッケージング,SiC,EV,熱抵抗","power module,packaging,SiC,EV,thermal resistance",
 "active","primary",85,1,"https://en.wikipedia.org/wiki/Power_semiconductor_device","Japan",90,
 "R_th(j-c): SiC die→substrate→heatsink; sintering: 50MPa AgNP at 250°C; ΔT<150°C","url_present"),

("ee_b2_047","スペクトラムセンシングと認知無線","Spectrum Sensing and Cognitive Radio","Cognitive Radio",
 "プライマリユーザー（免許局）の不在を検知してスペクトラムを機会的に二次利用する認知無線技術。エネルギー検出・マッチドフィルタ・サイクロステーショナリ検出が主要センシング手法。電波資源の効率利用を目的とする。",
 "TV帯域の動的スペクトラム共用（CBRS・3.5GHz）・DoD周波数共有・5G NRのスペクトラムシェアリングの理論的基盤。","電気電子工学","無線スペクトラム管理",2005,None,
 "無線資源管理","スペクトラム共用・5G・防衛通信","電波周波数の動的共用","周波数資源の効率的利用",
 "誤検知確率と見逃し確率のROCトレードオフはどのように閾値設定に影響するか","周波数帯域固定割当て（従来免許制度）",
 "認知無線,スペクトラムセンシング,CBRS,動的周波数共用","cognitive radio,spectrum sensing,CBRS,dynamic spectrum access",
 "active","primary",82,1,"https://en.wikipedia.org/wiki/Cognitive_radio","North_America",90,
 "energy det: T=Σ|y_i|² > λ; P_d=Q(√(2SNR)-(λ-N)/√N); ROC: P_d vs P_fa","url_present"),

("ee_b2_048","電気自動車の充電インフラ","EV Charging Infrastructure","EV Charging / V2G",
 "電気自動車への充電供給システム。AC普通充電（Level 1/2: 3.3-22kW）・DC急速充電（CCS・CHAdeMO・NACS: 50-350kW）・Vehicle-to-Grid（V2G: 電力網への放電）の3層構造で構成される。",
 "Tesla Supercharger・日本CHAdeMO標準（急速充電器世界普及基盤）・欧米CCS・NACSSのグローバル標準化競争。V2Gは系統安定化リソースとしての可能性を持つ。","電気電子工学","電動モビリティ",2008,None,
 "インフラシステム","EV普及・グリッド統合","EV充電インフラ設計と規格選択","EV急速充電と電力網統合",
 "CHAdeMOとCCS/NACSSの規格争いはどのような地政学的・産業的要因で展開したか","水素燃料電池車（FCEV）充填インフラ",
 "EV充電,CHAdeMO,CCS,V2G,急速充電","EV charging,CHAdeMO,CCS,V2G,fast charging",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Charging_station","Japan",90,
 "CHAdeMO: DC up to 400kW v3.0; CCS Combo: 350kW; NACS: Tesla→Ford→GM adoption","url_present"),

("ee_b2_049","集積回路の消費電力最適化","IC Power Optimization","Low-Power VLSI Design",
 "動的電力（CMOSスイッチング C·V²·f）と静止電力（リーク電流）を削減するVLSI設計技術。クロックゲーティング・電圧スケーリング（DVFS）・マルチVth・電源領域分割（パワーゲーティング）が主要手法。",
 "スマートフォンSoC（Apple A-series・Snapdragon）・クラウドサーバ・バッテリ駆動IoTの消費電力削減の鍵。Dark Siliconの時代において消費電力管理がIC設計の第一優先課題。","電気電子工学","低消費電力設計",1990,None,
 "IC設計","SoC・モバイル・IoT・データセンタ","消費電力が重要な全デジタルIC","バッテリ寿命または発熱が制約になる場合",
 "DVFSは電力削減にどのような二次効果をもたらすか","高性能優先設計（冷却前提）",
 "低消費電力設計,DVFS,クロックゲーティング,SoC,パワーゲーティング","low power design,DVFS,clock gating,SoC,power gating",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Low-power_electronics","North_America",90,
 "P_dyn=αCVf; P_leak=I_leak·V; DVFS: P∝V²f; clock gating: toggle power reduction","url_present"),

("ee_b2_050","光無線通信とLiFi","Free-Space Optical and LiFi Communication","FSO / LiFi",
 "可視光・赤外線・紫外線を伝送媒体とする光無線通信。LiFi（Light Fidelity）はLED照明をデータ変調して10Gbps超の超高速室内通信を実現し、RFと補完的に使用される。免許不要の高帯域通信。",
 "データセンタのラック間光無線接続・軍事・宇宙・水中通信への応用が進む。LiFiはpureLiFi・Signify（Philips）が商業化。6Gの候補技術。","電気電子工学","光無線通信",2011,None,
 "無線通信","室内高速通信・データセンタ・水中通信","電磁干渉が禁止または免許不要の高帯域が必要","RFが使えない環境での高速通信",
 "LiFiの指向性とフォグによる減衰はどのようなカバレッジ制限を生じるか","Wi-Fi（RF・非見通し線・広域）",
 "LiFi,光無線通信,FSO,可視光通信,6G","LiFi,free-space optical,FSO,visible light communication,6G",
 "active","primary",82,1,"https://en.wikipedia.org/wiki/LiFi","United_Kingdom",90,
 "LiFi: modulated LED; B>10Gbps OFDM; atmospheric: α∝wavelength; turbulence: Rytov","url_present"),
]

ok, sk = ins(records)
print(f"Inserted: {ok}, Skipped: {sk}")
import sqlite3 as sq
c2 = sq.connect(DB)
t = c2.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
print(f"Total: {t}")
c2.close()
