import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("ee_b5_001","デジタルツイン電力システム高度版","Advanced Power System Digital Twin","Digital Twin Power Grid",
 "電力系統の物理モデルとリアルタイム計測データを融合したデジタルツインにより、潮流解析・安定性評価・故障診断を高速実行する手法。PMU計測値をEKFで同化しモデルを更新する。",
 "広域停電リスク低減と最適制御に貢献。中国・欧州で大規模実証。",
 "電気電子工学","デジタル電力工学",2018,None,"system","電力系統",
 "PMU密度>0.1台/変電所、通信遅延<100ms","系統運用高度化・再エネ統合時","どのノードが安定性ボトルネックか",
 "静的潮流解析","デジタルツイン,電力系統,PMU,拡張カルマンフィルタ,安定性",
 "digital twin,power system,PMU,EKF,stability",
 "active","secondary",82,7,
 "https://ieeexplore.ieee.org/document/9000000","グローバル",0.7,
 r"状態推定: $\hat{x}_{k|k} = \hat{x}_{k|k-1} + K_k(z_k - h(\hat{x}_{k|k-1}))$、カルマンゲイン $K_k = P_{k|k-1}H_k^T(H_kP_{k|k-1}H_k^T+R_k)^{-1}$。",
 "url_present"),

("ee_b5_002","フォトニック集積回路設計","Photonic Integrated Circuit Design","PIC Design",
 "シリコンフォトニクスや化合物半導体基板上に導波路・変調器・受光器・光源を集積する回路設計手法。モードソルバ・FDTDシミュレーションで光学特性を最適化する。",
 "データセンター光インターコネクト・LiDARへの応用が急拡大。",
 "電気電子工学","フォトニクス工学",2010,None,"device","光通信・センシング",
 "シングルモード導波路設計、ファウンドリPDK利用時","高速光通信・集積センサ設計時","挿入損失とクロストークのトレードオフをどう解決するか",
 "個別光学部品","フォトニクス,シリコン,導波路,FDTD,変調器",
 "photonics,silicon,waveguide,FDTD,modulator",
 "active","secondary",83,8,
 "https://www.nature.com/articles/nphoton.2012.190","欧米",0.75,
 r"マッハツェンダー変調器の位相変調: $\Delta\phi = \pi V/V_\pi$、消光比 $ER = 20\log_{10}\left|\cos(\Delta\phi/2)\right|$ dB。",
 "url_present"),

("ee_b5_003","高電圧直流送電制御","HVDC Control","High Voltage Direct Current Control",
 "長距離・海底送電に用いるHVDCシステムの制御技術。LCC-HVDCとVSC-HVDCの制御方式、潮流制御・電圧安定化・短絡電流抑制を扱う。",
 "再エネ大規模連系・系統間連系に不可欠な技術。欧州・中国で多数運用中。",
 "電気電子工学","電力変換工学",2000,None,"system","電力系統",
 "500kV以上の長距離送電、海底ケーブル","再エネ広域連系・非同期系統連系時","MMCのサブモジュール数増加の影響は何か",
 "交流送電","HVDC,MMC,VSC,LCC,潮流制御",
 "HVDC,MMC,VSC,LCC,power flow control",
 "active","secondary",84,9,
 "https://ieeexplore.ieee.org/document/7740849","欧米",0.8,
 r"MMC内部エネルギー平衡: $W_{sum} = \frac{1}{2}C_{SM}\sum v_{Cj}^2$、出力電圧 $v_{out} = \sum_{j=1}^{N} s_j v_{Cj}$、$s_j \in \{0,1\}$。",
 "url_present"),

("ee_b5_004","量子センシング工学","Quantum Sensing Engineering","Quantum Sensing",
 "量子力学的効果（超伝導量子干渉計・NVセンタ・原子干渉計）を利用した超高感度センシング手法。重力・磁場・回転・時間の精密計測に用いる。",
 "GPSに依存しない慣性航法・医療用脳磁計・地下資源探査への応用が期待される。",
 "電気電子工学","量子工学",2010,None,"device","センシング・計測",
 "極低温環境または室温NVセンタ、振動ノイズ隔離","超精密計測・量子通信インフラ構築時","標準量子限界を超えるためのスクイーズドステートの効果は何か",
 "古典センサ","量子センシング,SQUID,NVセンタ,原子干渉計,感度",
 "quantum sensing,SQUID,NV center,atom interferometry,sensitivity",
 "active","secondary",80,5,
 "https://www.nature.com/articles/s41567-021-01223-x","欧米",0.75,
 r"NVセンタ磁気感度: $\eta \approx \frac{h}{g\mu_B}\frac{1}{C\sqrt{I_0 T_2}}$ [T/$\sqrt{\text{Hz}}$]、$T_2$はスピンデコヒーレンス時間。",
 "url_present"),

("ee_b5_005","スパース信号処理・圧縮センシング応用","Sparse Signal Processing and Compressed Sensing Applications","Compressed Sensing Applications",
 "スパース表現と圧縮センシング理論を実装した信号処理システム設計。LASSO・OMP・SPGLアルゴリズムによる再構成と、アンダーサンプリングMRI・レーダーへの適用を扱う。",
 "サンプリングレート大幅削減によるシステムコスト低下。MRI撮影時間短縮で実用化済み。",
 "電気電子工学","信号処理工学",2006,None,"algorithm","医療・通信・レーダー",
 "信号のスパース性（非ゼロ係数<20%）、RIP条件を満たす計測行列","低サンプリングコスト計測・高速イメージング時","RIPを保証する計測行列はどう設計するか",
 "Nyquistサンプリング","スパース,圧縮センシング,LASSO,MRI,再構成",
 "sparse,compressed sensing,LASSO,MRI,reconstruction",
 "active","primary",88,9,
 "https://ieeexplore.ieee.org/document/4472240","欧米",0.85,
 r"LASSO最適化: $\hat{x} = \arg\min_x \|y - Ax\|_2^2 + \lambda\|x\|_1$、RIP条件: $\delta_{2s} < \sqrt{2}-1$でRIPを満たす行列$A$があれば$s$スパース信号を正確に再構成可能。",
 "url_present"),

("ee_b5_006","中国超高圧送電技術","China Ultra High Voltage Transmission Technology","China UHV Technology",
 "中国国家電網が開発・運用する1000kV交流および±800kV直流超高圧送電（UHV）技術。西部の再エネを東部に送電する世界最長・最大容量システム。",
 "中国エネルギー安全保障に不可欠。技術輸出により国際標準化に影響。2023年時点で延長3万km超運用中。",
 "電気電子工学","高電圧工学",2009,None,"system","電力系統",
 "大容量長距離送電、地形的障壁超越時","電力格差解消・大規模再エネ統合時","絶縁設計と電磁環境の中国固有の課題は何か",
 "従来500kV送電","超高圧,UHV,中国,送電,再生可能エネルギー",
 "UHV,China,transmission,renewable energy,grid",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/7469477","東アジア",0.9,
 r"送電損失: $P_{loss} = \frac{P^2 R}{V^2}$、UHVで$V$を1000kVに上げると損失は$V^2$に反比例して大幅低減。送電容量 $S = \frac{V_1 V_2}{X}\sin\delta$。",
 "url_present"),

("ee_b5_007","マイクロ波電力伝送設計","Microwave Power Transmission System Design","MPT System Design",
 "マイクロ波ビームを用いた非接触電力伝送システムの設計手法。フェーズドアレイ送信アンテナのビーム形成、整流アンテナ（レクテナ）の効率最大化、電磁安全性評価を含む。",
 "宇宙太陽光発電・ドローン給電への応用。日本・中国・米国が研究競争中。",
 "電気電子工学","電磁波工学",2000,None,"device","エネルギー伝送",
 "見通し内通信路、10m〜数km距離","SPS実証・ドローン持続飛行実現時","レクテナ効率とビーム形成精度のトレードオフは何か",
 "有線電力伝送","マイクロ波,電力伝送,レクテナ,フェーズドアレイ,SPS",
 "microwave,power transmission,rectenna,phased array,SPS",
 "active","secondary",79,5,
 "https://ieeexplore.ieee.org/document/9316929","東アジア",0.8,
 r"レクテナ変換効率: $\eta_{rec} = \frac{P_{DC}}{P_{RF}} = \frac{I_L^2 R_L}{P_{RF}}$。ビーム集電効率 $\eta_{beam} = 1 - e^{-2r^2/w^2}$、$w$はビームウエスト、$r$はアパーチャ半径。",
 "url_present"),

("ee_b5_008","ロボット触覚センサ設計","Robot Tactile Sensor Design","Tactile Sensor Design",
 "ロボットハンドの把持・操作に必要な触覚情報（法線力・せん断力・滑り・硬さ）を取得するセンサの設計手法。圧電・容量・光学・磁気方式と信号処理アルゴリズムを統合する。",
 "精密把持・医療ロボット・人型ロボット開発に不可欠。",
 "電気電子工学","ロボット工学・センサ",2005,None,"device","ロボティクス",
 "接触面積と空間分解能のトレードオフ設計、耐久性要求","精密把持・柔軟物操作・テレオペレーション時","滑りの早期検出にはどの物理量が最も有効か",
 "力覚センサ（6軸）","触覚センサ,把持,ロボット,圧電,容量",
 "tactile sensor,grasping,robot,piezoelectric,capacitive",
 "active","secondary",80,7,
 "https://ieeexplore.ieee.org/document/9001218","欧米",0.75,
 r"法線力計測（容量方式）: $C = \varepsilon A/d$、変位 $\delta d$ により $\Delta C/C = -\Delta d/d$。せん断力は差動容量 $C_1 - C_2$ で推定。",
 "url_present"),

("ee_b5_009","通信用高速DSP設計","High-Speed DSP for Communications","Communications DSP Design",
 "無線通信ベースバンド処理に特化したDSP/FPGAアーキテクチャ設計手法。FFT・Viterbiデコーダ・LDPC/Turboデコーダのパイプライン・並列化実装を扱う。",
 "5G NR基地局の処理遅延低減に直結。FPGAアクセラレータ設計の基盤。",
 "電気電子工学","デジタル信号処理",2000,None,"algorithm","無線通信",
 "リアルタイム処理要求（<1ms遅延）、FPGA/ASICリソース制約","基地局・端末ベースバンド高速化時","クリティカルパスのスループットボトルネックはどこか",
 "汎用プロセッサ実装","DSP,FPGA,FFT,LDPCデコーダ,パイプライン",
 "DSP,FPGA,FFT,LDPC decoder,pipeline",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/8253498","欧米",0.75,
 r"Cooley-Tukey FFT演算量: $O(N\log_2 N)$、Nバタフライ演算 $W_N^k = e^{-j2\pi k/N}$。パイプライン化により毎クロック1出力達成。",
 "url_present"),

("ee_b5_010","電力半導体デバイスシミュレーション","Power Semiconductor Device Simulation","Power Device Simulation",
 "SiC・GaN等のワイドバンドギャップ半導体デバイスの電気特性・スイッチング損失・熱特性をデバイスシミュレータ（Sentaurus・Silvaco）で解析する手法。",
 "デバイス設計最適化によりインバータ効率1〜3%向上。製造前の設計検証に必須。",
 "電気電子工学","半導体工学",2005,None,"simulation","電力変換",
 "ドープ濃度・構造パラメータの明確化、数値収束条件設定","デバイス構造最適化・新材料評価時","移動度モデルの選択がスイッチング損失予測精度に与える影響は何か",
 "経験的コンパクトモデル","デバイスシミュレーション,SiC,GaN,スイッチング損失,ドリフト拡散",
 "device simulation,SiC,GaN,switching loss,drift-diffusion",
 "active","secondary",83,8,
 "https://ieeexplore.ieee.org/document/7891169","欧米",0.8,
 r"ドリフト拡散電流密度: $J_n = qn\mu_n E + qD_n\nabla n$、$J_p = qp\mu_p E - qD_p\nabla p$。ポアソン方程式: $\nabla^2\phi = -\frac{q}{\varepsilon}(p - n + N_D - N_A)$。",
 "url_present"),

("ee_b5_011","日本SiCパワーデバイス開発","Japan SiC Power Device Development","Japan SiC Power Device",
 "三菱電機・ロームを中心とした日本のSiC MOSFETおよびSBD開発。チャネル移動度改善・ゲート酸化膜信頼性・パッケージ技術の日本固有アプローチ。",
 "世界市場シェア拡大。EV・産業インバータの高効率化に貢献。ロームがSiC垂直統合製造を確立。",
 "電気電子工学","半導体工学",2010,None,"device","電力変換・EV",
 "SiCウエハ品質・製造設備投資","EV・鉄道・太陽光インバータ高効率化時","日本のSiCデバイスが欧米と差別化できる点は何か",
 "シリコンIGBT","SiC,MOSFET,日本,ローム,三菱電機",
 "SiC,MOSFET,Japan,Rohm,Mitsubishi Electric",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/8779519","東アジア",0.9,
 r"SiC MOSFET オン抵抗: $R_{on} = \frac{4V_{BR}^2}{\varepsilon_s \mu_n E_c^3}$、$E_c$は絶縁破壊電界(SiC: ~2.5 MV/cm, Si: ~0.3 MV/cm)。",
 "url_present"),

("ee_b5_012","ミリ波レーダー信号処理","Millimeter Wave Radar Signal Processing","mmWave Radar Signal Processing",
 "76〜81GHz帯ミリ波レーダーの信号処理アルゴリズム設計。FMCW波形・CFAR検出・MUSIC/ESPRIT測角・Doppler処理による高分解能3Dイメージング手法。",
 "自動車用ADASのキーセンサとして標準搭載。産業・医療センシングにも拡大中。",
 "電気電子工学","電磁波工学",2015,None,"algorithm","自動車・センシング",
 "76〜81GHz帯ライセンス、チャープ帯域幅>1GHz","自動運転・ジェスチャー認識・在人検知時","クラッター除去と歩行者検出の両立戦略は何か",
 "カメラ・LiDAR","ミリ波レーダー,FMCW,CFAR,MUSIC,自動車",
 "mmWave radar,FMCW,CFAR,MUSIC,automotive",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/8828004","欧米",0.8,
 r"FMCW距離推定: $R = \frac{c \cdot f_{beat}}{2S}$、$S = B/T_c$はチャープレート。速度推定: $v = \frac{\lambda f_D}{2}$、$\lambda$は波長。",
 "url_present"),

("ee_b5_013","電磁波吸収体設計","Electromagnetic Wave Absorber Design","EM Absorber Design",
 "特定周波数帯の電磁波を吸収する材料・構造設計手法。Salisbury Screen・Jaumann Absorber・FSS-backed吸収体のインピーダンス整合設計と広帯域化技術を扱う。",
 "EMC対策・ステルス技術・5G基地局の電磁環境改善に利用。",
 "電気電子工学","電磁波工学",1990,None,"device","EMC・通信",
 "対象周波数帯・吸収率目標（>20dB）・薄型化制約","電磁干渉低減・ステルス性付与時","広帯域吸収と薄型化のトレードオフをどう解決するか",
 "シールド","電磁波吸収,Salisbury Screen,FSS,インピーダンス整合,EMC",
 "EM absorber,Salisbury Screen,FSS,impedance matching,EMC",
 "active","secondary",78,9,
 "https://ieeexplore.ieee.org/document/6582649","欧米",0.75,
 r"Salisbury Screen反射係数: $\Gamma = \frac{Z_{in} - \eta_0}{Z_{in} + \eta_0}$、$Z_{in} = R_s \| jZ_0\cot(\beta d)$、$R_s = \eta_0$で完全吸収。",
 "url_present"),

("ee_b5_014","韓国ディスプレイ駆動技術","Korea Display Driver Technology","Korea OLED/LCD Driver IC",
 "サムスン・LGが主導する高解像度ディスプレイ用駆動ICの設計技術。AMOLEDパネルの画素補償アルゴリズム・高速インターフェース（MIPI DSI）・電源管理ICの統合設計手法。",
 "世界ディスプレイ市場での韓国シェア維持に直結。スマートフォン・TV向けで技術リーダーシップ。",
 "電気電子工学","ディスプレイ工学",2010,None,"device","ディスプレイ",
 "AMOLEDパネル仕様・解像度・リフレッシュレート要件","高精細TV・スマートフォン・AR/VR向け時","画素補償精度とゲート遅延の関係をどう最適化するか",
 "LCD駆動IC","ディスプレイ,OLED,駆動IC,韓国,画素補償",
 "display,OLED,driver IC,Korea,pixel compensation",
 "active","secondary",83,9,
 "https://ieeexplore.ieee.org/document/9252130","東アジア",0.9,
 r"AMOLEDのIR-drop補正: $V_{prog} = V_{th} + \sqrt{I_{target}/k'(W/L)}$、補正後輝度誤差 $<1\%$を達成するための$V_{th}$センシング精度要件。",
 "url_present"),

("ee_b5_015","電力系統慣性低下対策","Power System Low Inertia Countermeasures","Low Inertia Grid Stability",
 "再エネ大量導入による系統慣性低下に対処する手法。仮想同期発電機（VSG）・周波数応答制御・FFR（超高速周波数応答）・ESS協調制御を組み合わせた安定化設計。",
 "再エネ100%系統での周波数安定維持に不可欠。欧州・豪州で実証進む。",
 "電気電子工学","電力システム工学",2015,None,"system","電力系統",
 "慣性定数H<3s、再エネ比率>50%","系統周波数安定化・脱炭素電力系統設計時","VSGの等価慣性定数をどう最適化するか",
 "従来同期発電機依存","仮想同期発電機,VSG,慣性,周波数応答,再エネ",
 "VSG,virtual synchronous generator,inertia,frequency response,renewable",
 "active","secondary",81,7,
 "https://ieeexplore.ieee.org/document/9023454","欧米",0.8,
 r"VSG揺動方程式: $J\frac{d\omega}{dt} = T_m - T_e - D(\omega - \omega_0)$、等価慣性 $H_{VSG} = \frac{J\omega_0^2}{2S_n}$ [s]。",
 "url_present"),

("ee_b5_016","バイオメディカルRFID設計","Biomedical RFID System Design","Biomedical RFID Design",
 "医療用インプラント・体内センサへのパッシブRFID適用手法。電磁界人体吸収（SAR）制約下でのアンテナ設計・電力搬送効率最大化・データ通信セキュリティを扱う。",
 "インプラント型血糖センサ・心臓ペースメーカモニタリングへの応用。",
 "電気電子工学","バイオメディカル工学",2008,None,"device","医療",
 "SAR<1.6W/kg（FCC）・2.45GHz帯ISM使用","体内センサデータ収集・インプラント追跡時","生体組織の誘電率変動がリンク効率に与える影響は何か",
 "有線医療デバイス","RFID,インプラント,SAR,アンテナ,バイオメディカル",
 "RFID,implant,SAR,antenna,biomedical",
 "active","secondary",78,7,
 "https://ieeexplore.ieee.org/document/6712072","欧米",0.75,
 r"リンク効率: $\eta = \frac{k^2 Q_1 Q_2}{(1+k^2 Q_1 Q_2)}$、$k$: 結合係数、$Q_1,Q_2$: 一次・二次コイル品質係数。SAR: $SAR = \frac{\sigma|E|^2}{2\rho}$ [W/kg]。",
 "url_present"),

("ee_b5_017","超伝導量子コンピュータ制御回路","Superconducting Quantum Computer Control Electronics","SC Qubit Control",
 "超伝導量子ビット（トランズモン）の制御に必要な極低温エレクトロニクス設計手法。マイクロ波パルス生成・I/Qミキサ較正・4K〜mK間の信号配線・クロストーク低減を扱う。",
 "量子コンピュータのスケールアップの鍵。IBMがQubit数拡大のボトルネックと認識。",
 "電気電子工学","量子工学",2015,None,"system","量子コンピューティング",
 "極低温冷却設備（mKオーダー）・マイクロ波信号発生器","量子ゲート高忠実度実現・量子誤り訂正実装時","クロストークと熱侵入のトレードオフはどう解決するか",
 "室温エレクトロニクス","量子ビット,超伝導,トランズモン,制御回路,極低温",
 "qubit,superconducting,transmon,control electronics,cryogenics",
 "active","secondary",79,5,
 "https://www.nature.com/articles/nature23460","欧米",0.8,
 r"トランズモンエネルギー: $E_{01} = \sqrt{8E_JE_C} - E_C$、$E_J = \Phi_0^2/(8\pi^2 L_J)$、$E_C = e^2/(2C_\Sigma)$。Rabi駆動: $H_{drive} = -d\Omega\cos(\omega_d t)\hat{n}$。",
 "url_present"),

("ee_b5_018","ワイヤレス電力伝送効率最大化","WPT Efficiency Optimization","Wireless Power Transfer Optimization",
 "磁気共鳴型・誘導型ワイヤレス電力伝送の効率最大化手法。インピーダンス整合・コイル設計最適化・周波数追従制御・異物検知を含む統合設計フロー。",
 "EV充電・医療インプラント・家電への普及が加速。Qi2規格で15W標準化達成。",
 "電気電子工学","電力変換工学",2007,None,"device","エネルギー伝送",
 "10cm以下の伝送距離・MHz帯周波数・数W〜数kW電力","EV充電・スマートフォン・インプラント給電時","コイルミスアライメント耐性と効率のトレードオフは何か",
 "有線充電","ワイヤレス電力伝送,Qi,共鳴,インピーダンス整合,EV",
 "WPT,Qi,resonance,impedance matching,EV charging",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/7543741","欧米",0.8,
 r"結合効率: $\eta_{link} = \frac{k^2\omega^2 M^2}{(R_1 + R_{ext,1})(R_2 + R_{ext,2})}$、最適負荷 $R_{L,opt} = R_2\sqrt{1+k^2Q_1Q_2}$。",
 "url_present"),

("ee_b5_019","台湾半導体パッケージング先端技術","Taiwan Advanced Semiconductor Packaging","Taiwan Advanced Packaging",
 "台湾ASEグループ・TSMCが主導するCoWoS・SoIC・3D-ICパッケージング技術。チップレット統合・TSV形成・Cu-Cu直接ボンディングの設計・製造プロセス手法。",
 "HBM-AI加速器統合のデファクト技術。NVIDIAのGPU・Apple SoCに採用済み。",
 "電気電子工学","半導体製造工学",2018,None,"process","半導体製造",
 "露光・エッチング・平坦化プロセス精度<1μm","HPC/AI向けチップレット統合・高帯域メモリ実装時","Cu-Cu直接ボンディングの収率と信頼性の最適化は何か",
 "従来ワイヤボンド","CoWoS,SoIC,チップレット,TSV,台湾",
 "CoWoS,SoIC,chiplet,TSV,Taiwan TSMC",
 "active","secondary",84,9,
 "https://ieeexplore.ieee.org/document/9895006","東アジア",0.92,
 r"TSV熱膨張応力: $\sigma = E_{Cu}\alpha_{Cu}\Delta T / (1-\nu)$、Cu-Cu bonding界面強度 $\sigma_{bond} > 200$ MPa達成条件。",
 "url_present"),

("ee_b5_020","電磁過渡解析","Electromagnetic Transient Analysis","EMT Analysis",
 "電力系統の過渡現象（雷・開閉サージ・短絡）をATP/EMTP・PSCAD等でシミュレーションする手法。絶縁協調・保護リレー設定・GIS設計に不可欠。",
 "変電所設計の標準的検証手法として世界中で利用。絶縁設計合理化によりコスト削減。",
 "電気電子工学","電力システム工学",1970,None,"simulation","電力系統",
 "系統モデル（変圧器・ケーブル・避雷器）の精度確保","絶縁協調設計・保護継電器整定時","分散定数線路モデルとJMartinモデルの使い分け基準は何か",
 "実系統実験","電磁過渡,EMTP,PSCAD,絶縁協調,サージ",
 "EMT,EMTP,PSCAD,insulation coordination,surge",
 "active","primary",86,9,
 "https://ieeexplore.ieee.org/document/6522444","欧米",0.85,
 r"JMarti線路モデル: $V(x,t) = V^+(t-x/v) + V^-(t+x/v)$、特性インピーダンス $Z_c = \sqrt{L/C}$、伝播速度 $v = 1/\sqrt{LC}$。",
 "url_present"),

("ee_b5_021","韓国5G通信チップ設計","Korea 5G Communication Chip Design","Korea 5G Chip",
 "サムスン・LG・SKTが推進する5G NR向けベースバンドプロセッサ・RF SoC設計。Massive MIMO処理・mmWave RFフロントエンド・低遅延スケジューラの統合設計アプローチ。",
 "5G標準化への貢献と商用インフラ展開をリード。サムスンExynos Modem 5100が先導。",
 "電気電子工学","無線通信工学",2018,None,"device","無線通信",
 "5G NR標準準拠・Sub-6GHz/mmWave両対応","5G基地局・端末ベースバンド開発時","eMBB・URLLC・mMTCの異種トラフィック処理をどう共存させるか",
 "4G LTEチップ","5G,NR,韓国,SoC,Massive MIMO",
 "5G,NR,Korea,SoC,Massive MIMO",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/8869705","東アジア",0.88,
 r"5G NR PDSCH符号化利得: $C = B\log_2(1+SNR)$ [bps]、Massive MIMOアレイゲイン $G_{array} = 10\log_{10}(M)$ [dB]、$M$はアンテナ数。",
 "url_present"),

("ee_b5_022","熱電変換デバイス設計","Thermoelectric Device Design","TEG Design",
 "温度差から直接電力を生成する熱電発電（TEG）モジュールの設計手法。ゼーベック係数・電気伝導率・熱伝導率の最適化（ZT最大化）、カスケード構造設計、廃熱回収システムへの統合を扱う。",
 "IoTセンサ自立電源・自動車廃熱回収・宇宙探査機電源として実用化。",
 "電気電子工学","エネルギー変換工学",1990,None,"device","エネルギー収穫",
 "温度差ΔT>50K、廃熱源の安定性","廃熱回収・自立電源・宇宙電源設計時","ZT=1以上を達成するためのナノ構造化材料選定基準は何か",
 "電磁誘導発電","熱電変換,ZT値,ゼーベック,廃熱回収,ナノ構造",
 "thermoelectric,ZT value,Seebeck,waste heat,nanostructure",
 "active","secondary",80,8,
 "https://www.science.org/doi/10.1126/science.1158899","欧米",0.8,
 r"熱電性能指数: $ZT = \frac{S^2\sigma T}{\kappa} = \frac{S^2 T}{\rho\kappa}$、$S$: ゼーベック係数、$\sigma$: 電気伝導率、$\kappa$: 熱伝導率。最大効率 $\eta_{max} = \eta_C \frac{\sqrt{1+ZT}-1}{\sqrt{1+ZT}+T_C/T_H}$。",
 "url_present"),

("ee_b5_023","磁気ギアードモータ設計","Magnetic Geared Motor Design","Magnetic Gear Motor",
 "機械的歯車を磁気的に置き換えた磁気ギア・磁気ギアードモータの設計手法。トルク密度・速度変換比・鉄損最小化の最適設計と、風力発電・EVへの適用を扱う。",
 "機械的摩耗なし・高信頼性・高トルク密度の特徴で注目。英国・中国で研究活発。",
 "電気電子工学","電気機械工学",2001,None,"device","電動機・発電機",
 "低速大トルク・高信頼性要求時","風力直駆・EV高効率駆動時","磁気変速比と最大トルク密度の設計最適化は何か",
 "機械歯車変速機","磁気ギア,トルク密度,PM,風力,EV",
 "magnetic gear,torque density,PM,wind power,EV",
 "active","secondary",77,7,
 "https://ieeexplore.ieee.org/document/1643429","欧米",0.75,
 r"磁気ギア変速比: $G_r = p_s/p_r$、$p_s$: 内側極対数、$p_r$: 外側極対数。最大伝達トルク $T_{max} = \frac{\pi}{2\mu_0}\frac{B_s B_r L r^2}{g}$。",
 "url_present"),

("ee_b5_024","中国AIチップ設計生態系","China AI Chip Design Ecosystem","China AI Chip Development",
 "ファーウェイAscend・カンブリコン・寒武紀等が主導する中国AI推論・学習チップの設計エコシステム。NPUアーキテクチャ・コンパイラスタック・AIフレームワーク統合の国産化戦略。",
 "米国輸出規制下での技術自立化戦略の中核。MindSpore/PaddlePaddleとの統合が加速。",
 "電気電子工学","AI専用ハードウェア",2016,None,"system","AI/HPC",
 "AIフレームワーク対応・NPUアーキテクチャ設計","国産AI基盤整備・ML推論コスト削減時","メモリ帯域幅とNPU演算能力のバランスをどう設計するか",
 "GPUクラスタ（NVIDIA依存）","AIチップ,NPU,中国,Ascend,カンブリコン",
 "AI chip,NPU,China,Ascend,Cambricon",
 "active","secondary",80,7,
 "https://ieeexplore.ieee.org/document/9063127","東アジア",0.9,
 r"NPUの演算効率: $\eta_{ops} = \frac{FLOPS_{actual}}{FLOPS_{peak}}$、メモリ律速条件 $I < \frac{FLOPS_{peak}}{BW_{mem}}$ [$\frac{FLOP}{byte}$]。",
 "url_present"),

("ee_b5_025","電力品質改善装置設計","Power Quality Improvement Device Design","Power Quality Conditioner",
 "電圧フリッカ・高調波・電圧不平衡・瞬時電圧低下を補償するAPF・STATCOM・DVR・UPSの設計手法。リアルタイム検出アルゴリズムと高速PWM制御を統合する。",
 "精密製造・データセンター・医療施設の電力品質確保に必須。",
 "電気電子工学","電力品質工学",1995,None,"device","電力系統・産業",
 "高調波歪み率THD>5%・電圧変動>10%","精密機器保護・電力品質規制適合時","アクティブフィルタの応答速度と補償精度のトレードオフは何か",
 "受動フィルタ","電力品質,APF,STATCOM,DVR,高調波",
 "power quality,APF,STATCOM,DVR,harmonics",
 "active","secondary",82,8,
 "https://ieeexplore.ieee.org/document/7006805","欧米",0.8,
 r"APF補償電流: $i_c^* = i_L - i_L^{(1)}$（基本波成分除去）。PQ理論: 瞬時有効電力 $p = v\cdot i$、無効電力 $q = v\times i$（3相）。",
 "url_present"),

("ee_b5_026","量子鍵配送ネットワーク実装","QKD Network Implementation","QKD Network Engineering",
 "BB84・E91プロトコルに基づく量子鍵配送ネットワークの実装技術。光子源・単光子検出器・量子中継器・QKD管理ソフトウェアの統合設計を扱う。",
 "中国が世界初の量子衛星Miciusで2000kmQKD実証。欧州SECOQC・日本東芝実験も先行。",
 "電気電子工学","量子通信工学",2003,None,"system","通信セキュリティ",
 "光ファイバ損失補償（中継器または衛星）・単光子検出器冷却","量子安全通信インフラ構築時","距離限界突破のための量子中継器と衛星QKDの使い分け基準は何か",
 "公開鍵暗号","QKD,BB84,量子通信,量子中継,セキュリティ",
 "QKD,BB84,quantum communication,repeater,security",
 "active","secondary",80,5,
 "https://www.nature.com/articles/nature23655","東アジア",0.85,
 r"BB84鍵レート（損失有り）: $R_{key} \approx Q\eta_{opt}\eta_{det}[1-h(e_{bit})-h(e_{ph})]$、$h(x) = -x\log_2 x -(1-x)\log_2(1-x)$：二値エントロピー関数。",
 "url_present"),

("ee_b5_027","音響メタマテリアル設計","Acoustic Metamaterial Design","Acoustic Metamaterial Engineering",
 "負の質量密度・負の弾性率を持つ音響メタマテリアルの設計手法。局所共鳴構造・共鳴クロークの解析と、防音・音響レンズ・弾性波制御への適用を扱う。",
 "従来材料の限界を超えた音響制御が可能。建築防音・水中音響・医療超音波への応用研究が活発。",
 "電気電子工学","電磁波・音響工学",2000,None,"device","音響制御",
 "音波波長スケール周期構造設計（λ/10以下の局所共鳴体）","低周波防音・音響クローキング・超解像音響イメージング時","負の等価質量密度を実現するための局所共鳴体の設計パラメータは何か",
 "従来多孔質吸音材","音響メタマテリアル,局所共鳴,防音,負の弾性率,弾性波",
 "acoustic metamaterial,local resonance,sound insulation,negative modulus,elastic wave",
 "active","secondary",76,5,
 "https://www.science.org/doi/10.1126/science.289.5485.1734","欧米",0.78,
 r"等価媒体密度: $\rho_{eff}(\omega) = \rho_0\left(1 - \frac{\omega_0^2}{\omega^2 - \omega_0^2}\right)$、$\omega_0$: 局所共鳴周波数。バンドギャップ条件: $\rho_{eff} < 0$。",
 "url_present"),

("ee_b5_028","スマートグリッドサイバーセキュリティ","Smart Grid Cybersecurity","Power Grid Cybersecurity",
 "電力系統へのサイバー攻撃（FDI・MITM・DoS）の検知・防御手法。異常検知（機械学習ベース）・電力系統暗号化通信・セキュア制御プロトコル（IEC 62351）設計を扱う。",
 "ウクライナ停電事件（2015年）を契機に研究が急増。ICS-CERTの脅威報告が増加中。",
 "電気電子工学","情報セキュリティ",2015,None,"system","電力・制御システム",
 "ICS/SCADA環境・OTネットワーク分離・IEC 61850対応","電力インフラ保護・国家重要インフラ防御時","FDI攻撃をリアルタイム検知するための状態推定ベース異常検知の限界は何か",
 "IT系セキュリティのみ","スマートグリッド,サイバーセキュリティ,FDI攻撃,IEC 62351,異常検知",
 "smart grid,cybersecurity,FDI attack,IEC 62351,anomaly detection",
 "active","secondary",80,8,
 "https://ieeexplore.ieee.org/document/9272685","欧米",0.8,
 r"FDI攻撃モデル: $\tilde{z} = z + a$、$a = Hc$（Hは計測行列）で誤差$r = \tilde{z} - H\hat{x} = 0$を達成しBDDを回避。検知条件: $\|a\|_0 > \text{spark}(H)-1$。",
 "url_present"),

("ee_b5_029","電気自動車パワートレイン最適設計","EV Powertrain Optimal Design","EV Powertrain Design",
 "EVのモータ・インバータ・バッテリーパックを統合したパワートレイン最適設計手法。エネルギー管理戦略・回生制動制御・熱管理の多目的最適化を含む。",
 "航続距離延伸・充電時間短縮・コスト削減の三要素を同時最適化する鍵技術。",
 "電気電子工学","電気機械工学",2010,None,"system","電気自動車",
 "バッテリー仕様・モータ出力要件・熱制約","EV設計・パワートレイン効率最大化時","モータ高回転化とインバータスイッチング周波数のトレードオフは何か",
 "内燃機関パワートレイン","EV,パワートレイン,モータ,インバータ,エネルギー管理",
 "EV,powertrain,motor,inverter,energy management",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/9112125","欧米",0.82,
 r"EV走行エネルギー: $E_{drive} = \int_0^T [F_{air}+F_{roll}+F_{grade}+ma]v\, dt$、回生回収率 $\eta_{regen} = E_{regen}/E_{brake}$。最適EMSで全体効率+15\%達成。",
 "url_present"),

("ee_b5_030","中国スマートシティ電力インフラ","China Smart City Power Infrastructure","China Smart City Power",
 "中国のスマートシティ構想における電力インフラ設計。マイクログリッド・V2G統合・エネルギーインターネット・国家電網SG-EIM標準に基づく統合管理アーキテクチャ。",
 "百都市スマートシティ計画の電力基盤として実装中。データ駆動型負荷管理で15%削減実証。",
 "電気電子工学","スマート電力工学",2015,None,"system","スマートシティ",
 "通信インフラ（5G/光）整備、中央管理プラットフォーム","スマートシティ電力管理・V2G統合時","エネルギーインターネットのセキュリティと相互運用性をどう確保するか",
 "従来集中型電力管理","スマートシティ,エネルギーインターネット,V2G,中国,マイクログリッド",
 "smart city,energy internet,V2G,China,microgrid",
 "active","secondary",80,7,
 "https://ieeexplore.ieee.org/document/8636547","東アジア",0.88,
 r"エネルギーインターネット電力潮流: $P_{EI} = P_{gen} + P_{storage} - P_{load} - P_{export}$、V2G需給調整 $\Delta P_{V2G} = \sum_{i=1}^{N_{EV}} P_{charge,i}^* - P_{actual,i}$。",
 "url_present"),

("ee_b5_031","ハードウェアセキュリティモジュール設計","Hardware Security Module Design","HSM Design",
 "暗号鍵の生成・保管・演算を物理的に保護するHSMの設計手法。物理的耐タンパー性・サイドチャネル攻撃耐性（DPA・EMA対策）・真性乱数生成器の実装を扱う。",
 "金融インフラ・PKIシステム・自動車HSMとして標準化。FIPS 140-2/3認証が必須要件。",
 "電気電子工学","情報セキュリティ",2000,None,"device","セキュリティシステム",
 "FIPS 140-2 Level 3以上・物理環境保護・EMシールド","金融・PKI・自動車セキュリティ実装時","サイドチャネル攻撃耐性の評価基準はどのように設定するか",
 "ソフトウェア暗号実装","HSM,サイドチャネル,DPA,FIPS,耐タンパー性",
 "HSM,side channel,DPA,FIPS,tamper resistance",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/8598771","欧米",0.8,
 r"差分電力解析(DPA): $\Delta D[k] = \frac{1}{|S_1|}\sum_{i\in S_1}T_i - \frac{1}{|S_0|}\sum_{i\in S_0}T_i$、相関 $\rho(H_b, T) = \frac{E[H_b T]-E[H_b]E[T]}{\sigma_{H_b}\sigma_T}$。",
 "url_present"),

("ee_b5_032","カーボンナノチューブFET研究","Carbon Nanotube FET Research","CNT-FET Research",
 "カーボンナノチューブを半導体チャネルとする電界効果トランジスタの研究動向。バリスティック輸送・切り替え速度・統合課題（整列・金属性CNT除去）と次世代ロジックへの可能性を扱う。",
 "シリコン限界を超えるポストシリコン候補として研究が継続。IBMが2nm以下の概念実証。",
 "電気電子工学","ナノエレクトロニクス",2001,None,"device","ロジック集積回路",
 "半導体性CNT純度>99%・チャネル整列技術","ポストシリコンロジック研究・高速低消費電力デバイス開発時","CNT-FETの統合プロセスとシリコンCMOS互換性の両立は可能か",
 "シリコンMOSFET","CNT,FET,バリスティック輸送,ポストシリコン,ナノ",
 "CNT,FET,ballistic transport,post-silicon,nano",
 "active","secondary",75,4,
 "https://www.nature.com/articles/nature12122","欧米",0.78,
 r"CNT電気伝導: $G = \frac{4e^2}{h}T$（バリスティック輸送、$T$: 透過率）。バンドギャップ $E_g = \frac{2\gamma a_{CC}}{d}$、$d$: CNT直径、$\gamma \approx 2.7$ eV。",
 "url_present"),

("ee_b5_033","インテリジェント変電所自動化","Intelligent Substation Automation","Smart Substation IEC61850",
 "IEC 61850規格に基づくデジタル変電所自動化システムの設計手法。GOOSE/SV通信・IED間インターオペラビリティ・サイバーセキュリティ対策を統合したシステム構成を扱う。",
 "変電所の無人化・信頼性向上・保護リレー動作高速化（<4ms）に貢献。中国・欧州で標準化済み。",
 "電気電子工学","電力システム工学",2003,None,"system","電力インフラ",
 "IEC 61850対応IED・光ファイバ通信網・セキュリティゾーン設計","デジタル変電所構築・保護自動化時","GOOSE通信の信頼性と遅延保証をどう確保するか",
 "従来ハードワイヤード変電所","デジタル変電所,IEC 61850,GOOSE,IED,保護自動化",
 "digital substation,IEC 61850,GOOSE,IED,protection automation",
 "active","secondary",84,9,
 "https://ieeexplore.ieee.org/document/7927936","東アジア",0.8,
 r"GOOSE遅延要件: $T_{total} = T_{proc} + T_{comm} < 4$ ms（保護トリップ）。SV（サンプル値）フレームレート: 80/256 samples/cycle、同期精度 $< 1\mu$s。",
 "url_present"),

("ee_b5_034","光無線通信（FSO）高信頼化","Free Space Optical Communication Reliability","FSO Reliability Enhancement",
 "大気揺らぎ・雨・霧による光無線通信（FSO）の信頼性改善手法。適応光学・空間ダイバーシティ・MIMO-FSO・ハイブリッドRF/FSOシステムの設計を扱う。",
 "ラストワンマイル高速通信・衛星間通信に有望。大気乱流補償により可用性99.9%達成事例。",
 "電気電子工学","光通信工学",2000,None,"system","無線通信",
 "視程>1km（通常条件）・適応光学補償システム","バックホール高速化・衛星光通信時","大気乱流強度分類（弱/中/強）に応じた最適補償戦略は何か",
 "RF無線通信","FSO,光無線通信,大気乱流,適応光学,MIMO",
 "FSO,optical wireless,atmospheric turbulence,adaptive optics,MIMO",
 "active","secondary",78,8,
 "https://ieeexplore.ieee.org/document/7010962","欧米",0.75,
 r"FSO受信SNR（対数正規モデル）: $\text{SNR} = \frac{(P_r)^2}{N_0 B}$、対数振幅分散 $\sigma_\chi^2 = 0.124 k^{7/6} C_n^2 L^{11/6}$（弱乱流）。",
 "url_present"),

("ee_b5_035","ニューロモーフィック回路設計","Neuromorphic Circuit Design","Neuromorphic Engineering",
 "生物神経回路を模倣したスパイキングニューラルネットワーク（SNN）チップの設計手法。LIF・Izhikevichニューロン回路・STDPシナプス・オンチップ学習の低消費電力VLSI実装を扱う。",
 "従来DNN比で100倍以上の電力効率向上可能性。エッジAI・ロボット制御への応用研究が活発。",
 "電気電子工学","AI専用ハードウェア",2014,None,"device","AIエッジコンピューティング",
 "SNNモデル設計・時間符号化スキーム・スパイク通信インターフェース","超低消費電力AIエッジ・感覚処理時","SNNの学習精度とDNNとの差をどう埋めるか",
 "従来DNN加速器","ニューロモーフィック,SNN,LIF,STDP,低消費電力",
 "neuromorphic,SNN,LIF,STDP,low power",
 "active","secondary",78,5,
 "https://www.science.org/doi/10.1126/science.aam8830","欧米",0.8,
 r"LIFニューロン: $C_m\frac{dV}{dt} = -\frac{V-V_{rest}}{R_m} + I_{syn}(t)$、閾値超過で発火し$V \leftarrow V_{reset}$。STDPウィンドウ: $\Delta w = A_+e^{-|\Delta t|/\tau_+}$（因果）。",
 "url_present"),

("ee_b5_036","電子部品の信頼性加速試験","Accelerated Life Testing for Electronic Components","Electronic Component ALT",
 "電子部品（コンデンサ・IGBT・LEDパッケージ）の寿命推定のための加速試験設計手法。アレニウス・アイリング・逆べき乗則モデルの選択と、加速係数推定・信頼性予測統計を扱う。",
 "製品保証期間設定・フィールド故障率低減の基盤。IEC 60068・JEDEC標準に準拠。",
 "電気電子工学","信頼性工学",1980,None,"evaluation","電子機器設計",
 "故障物理モデルの特定・加速因子（温度・電圧・湿度）の設定","電子機器保証寿命設定・故障解析時","加速試験で観測されない故障モードへの対処は何か",
 "実時間寿命試験","加速試験,アレニウス,寿命推定,IGBT,信頼性",
 "accelerated life test,Arrhenius,lifetime estimation,IGBT,reliability",
 "active","primary",83,9,
 "https://ieeexplore.ieee.org/document/7745503","欧米",0.82,
 r"アレニウスモデル: $L = A \exp\left(\frac{E_a}{k_B T}\right)$、加速係数 $AF = \exp\left[\frac{E_a}{k_B}\left(\frac{1}{T_{use}}-\frac{1}{T_{test}}\right)\right]$。",
 "url_present"),

("ee_b5_037","スマートメータシステム設計","Smart Meter System Design","Advanced Metering Infrastructure",
 "AMIの核心となるスマートメータ（電力・ガス・水道）の設計手法。電力量計測（IEC 62053）・通信プロトコル（DLMS/COSEM）・不正検知・プライバシー保護の統合設計を扱う。",
 "需要応答・ピークシフト・電力盗用検知に貢献。日本・中国・欧米で1億台超普及。",
 "電気電子工学","スマート電力工学",2005,None,"device","スマートグリッド",
 "通信インフラ（PLC/RF/光）・計測精度クラス0.5S","需要応答プログラム・電力小売り自由化対応時","通信信頼性と計測精度のバランスをどう確保するか",
 "アナログ電力量計","スマートメータ,AMI,DLMS,需要応答,PLC",
 "smart meter,AMI,DLMS,demand response,PLC",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/7084655","グローバル",0.8,
 r"電力量計測: $W = \int_0^T v(t)i(t)dt$、デジタル計測 $W = \frac{1}{N}\sum_{n=0}^{N-1}v_n i_n \cdot T$。通信遅延要件: $T_{comm} < 2$ s（デマンドレスポンス）。",
 "url_present"),

("ee_b5_038","日本パワーエレクトロニクス鉄道応用","Japan Railway Power Electronics","Japan Railway Power Converter",
 "新幹線・在来線向けパワーエレクトロニクス技術の日本固有発展。三相インバータ・VVVFインバータ・回生制動システム・SiC適用と、日立・東芝・三菱電機の開発アプローチ。",
 "鉄道エネルギー効率化に寄与。日本の回生制動技術は世界標準の原型。SiC適用で新幹線損失40%減を実証。",
 "電気電子工学","電力変換工学",1985,None,"device","鉄道・交通",
 "鉄道車両仕様・安全規格（鉄道技術基準）準拠","新幹線・在来線電車性能向上時","回生電力の変電所への返送効率向上策は何か",
 "直流モーター駆動","VVVF,インバータ,鉄道,SiC,日本",
 "VVVF,inverter,railway,SiC,Japan",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/8726062","東アジア",0.92,
 r"VVVFインバータ出力電圧: $V_{ph} = \frac{V_{dc}}{2}m_a\sin(\omega_1 t)$、$m_a$: 変調指数。回生電力 $P_{regen} = \eta_{regen} M v \frac{dv}{dt}$。",
 "url_present"),

("ee_b5_039","フレキシブルエレクトロニクス製造","Flexible Electronics Manufacturing","Flexible/Stretchable Electronics Fabrication",
 "柔軟・伸縮性基板上に電子回路を形成するフレキシブルエレクトロニクスの製造プロセス。ロールツーロール印刷・レーザーアブレーション・transfer印刷・薄膜デポジションを扱う。",
 "ウェアラブルセンサ・電子皮膚・スマートテキスタイルの製造基盤。中国・韓国が製造量産で先行。",
 "電気電子工学","電子製造工学",2010,None,"process","ウェアラブル・医療",
 "基板柔軟性要件・解像度・収率目標","スマートウェアラブル・体表センサ製造時","電気性能と柔軟性のトレードオフを材料設計でどう解決するか",
 "剛体基板PCB","フレキシブルエレクトロニクス,ロールツーロール,薄膜,ウェアラブル,印刷",
 "flexible electronics,roll-to-roll,thin film,wearable,printing",
 "active","secondary",81,7,
 "https://www.nature.com/articles/s41586-019-1602-2","東アジア",0.82,
 r"薄膜転写力学: 島-橋構造の最大ひずみ $\varepsilon_{max} = t_s/2R_{min}$、$t_s$:基板厚、$R_{min}$:最小曲率半径。導電性維持条件: $\varepsilon_{critical} < 1\%$（金属薄膜）。",
 "url_present"),

("ee_b5_040","分散型エネルギーリソース管理","Distributed Energy Resource Management","DERMS Advanced",
 "太陽光・蓄電池・EV・需要応答を集約管理するDERMS（分散エネルギーリソース管理システム）の高度化手法。Market Clearing・最適潮流・階層型制御アーキテクチャを含む。",
 "配電系統の再エネ高浸透率下での安定運用に必須。欧州・米国で実証プロジェクト多数。",
 "電気電子工学","電力システム工学",2015,None,"system","配電系統",
 "系統情報リアルタイム取得・DER通信プロトコル（IEEE 2030.5）","再エネ大量導入・電力市場参加時","VPP（仮想発電所）のアグリゲーション最適化にどのアルゴリズムが有効か",
 "集中型給電指令","DERMS,DER,VPP,最適潮流,需要応答",
 "DERMS,DER,VPP,optimal power flow,demand response",
 "active","secondary",80,7,
 "https://ieeexplore.ieee.org/document/9165786","欧米",0.8,
 r"DERMS最適化: $\min \sum_i c_i P_{DER,i}$ s.t. $\sum_i P_{DER,i} = P_{load} - P_{grid}$、電圧制約 $V_{min} \leq V_i \leq V_{max}$。",
 "url_present"),

("ee_b5_041","インダクタ設計・統合技術","Power Inductor Design and Integration","Integrated Power Inductor",
 "スイッチング電源用インダクタの高周波・高電流密度・低損失設計手法。コア材料選択（フェライト・メタグラス・空芯）・巻線設計・PCB統合・3Dプリント磁性コアへの展開を扱う。",
 "電源小型化・高効率化の要。スマートフォン・データセンターPDNの最重要受動部品。",
 "電気電子工学","電力変換工学",1990,None,"device","電源回路",
 "スイッチング周波数・電流仕様・損失予算","高周波スイッチング電源・高電力密度インバータ設計時","コア損失とDC偏磁の同時最小化戦略は何か",
 "大型巻線トランス","インダクタ,コア損失,フェライト,高周波,統合電源",
 "inductor,core loss,ferrite,high frequency,integrated power",
 "active","secondary",80,8,
 "https://ieeexplore.ieee.org/document/8419165","欧米",0.78,
 r"インダクタコア損失（Steinmetzモデル）: $P_{loss} = k f^\alpha B_{pk}^\beta$、$k,\alpha,\beta$は材料定数。インダクタンス $L = \mu_0\mu_r N^2 A/l$、飽和電流 $I_{sat}: B = \mu_0\mu_r H = B_{sat}$。",
 "url_present"),

("ee_b5_042","先端CMOSロジック設計","Advanced CMOS Logic Design","Sub-5nm CMOS Logic",
 "5nm以下のCMOSプロセスノードにおけるロジック設計手法。FinFET・GAAFET（ナノシートFET）構造設計・物理設計ルール・タイミング解析・低電圧動作手法を扱う。",
 "TSMCのN3・N2プロセスでApple/NVIDIAのフラッグシップSoCに採用。性能・消費電力の世界最先端。",
 "電気電子工学","半導体工学",2020,None,"device","ロジック集積回路",
 "EUVリソグラフィ・プロセスDRC準拠・STA収束","スマートフォン・HPC向けSoC設計時","GAA FETのゲート制御性向上が短チャネル効果に与える影響は何か",
 "平面MOSFET（長チャネル）","GAAFET,FinFET,N2プロセス,EUV,先端ロジック",
 "GAAFET,FinFET,N2 process,EUV,advanced logic",
 "active","secondary",82,9,
 "https://ieeexplore.ieee.org/document/9816855","東アジア",0.85,
 r"短チャネル効果: SCE抑制のためのゲート長 $L_{g,min} \approx \lambda = \sqrt{\frac{\varepsilon_{Si}}{\varepsilon_{ox}}t_{Si}t_{ox}}$（片側ゲート）。GAAでは$t_{Si}$を全周でゲート包囲。",
 "url_present"),

("ee_b5_043","超音波非破壊評価高度化","Advanced Ultrasonic NDT","Phased Array Ultrasonic Testing",
 "フェーズドアレイ超音波（PAUT）・全波形インバージョン・AIを組み合わせた次世代NDT手法。複合材き裂・溶接欠陥の高分解能イメージングと定量評価を扱う。",
 "原子力・航空・圧力容器の保守検査品質向上。ASME・ISO規格でPAUT標準化済み。",
 "電気電子工学","超音波工学",2000,None,"evaluation","非破壊検査",
 "対象材料の音速・減衰特性測定、欠陥サイズ目標分解能（λ/2以下）","溶接検査・複合材欠陥評価・原子力保守時","全波形インバージョンの計算コストと実用化の障壁は何か",
 "X線検査","フェーズドアレイ超音波,PAUT,NDT,全波形インバージョン,欠陥検出",
 "phased array UT,PAUT,NDT,full waveform inversion,defect detection",
 "active","secondary",83,9,
 "https://ieeexplore.ieee.org/document/8481573","欧米",0.8,
 r"PAUT電子走査: ビームステアリング角 $\theta = \arcsin(c\Delta\tau/d)$、$\Delta\tau$: 遅延時間差、$d$: 素子ピッチ。横分解能 $\Delta x = 1.22\lambda F/D$。",
 "url_present"),

("ee_b5_044","高速アナログデジタル変換器設計","High-Speed ADC Design","High-Speed ADC Architecture",
 "10bit/1GS以上のサンプリングレートを持つ高速ADCの設計手法。フラッシュ型・SAR型・パイプライン型・時間インターリーブ型のアーキテクチャ選択と、ジッタ・非線形誤差補正を扱う。",
 "5G基地局・レーダー・高速計測器のキーコンポーネント。TI・ADIが市場をリード。",
 "電気電子工学","アナログ集積回路",2005,None,"device","無線通信・計測",
 "サンプリングレート・SNR・ENOB・消費電力仕様","通信受信機・レーダーデジタル受信機設計時","時間インターリーブADCのチャンネル間ミスマッチ補正の最新手法は何か",
 "低速ADC","ADC,高速,パイプライン,時間インターリーブ,ジッタ",
 "ADC,high-speed,pipeline,time-interleaved,jitter",
 "active","secondary",83,8,
 "https://ieeexplore.ieee.org/document/7728124","欧米",0.8,
 r"ADC ENOB（実効ビット数）: $ENOB = \frac{SINAD - 1.76}{6.02}$、SINAD [dB]はSNDR。ジッタによるSNR限界: $SNR_{jitter} = -20\log_{10}(2\pi f_{in}\sigma_j)$ [dB]。",
 "url_present"),

("ee_b5_045","海洋エネルギー変換システム","Ocean Energy Conversion System","Wave/Tidal Energy Converter",
 "波力・潮流・海洋温度差を電力に変換する海洋エネルギーシステムの設計手法。波力発電（OWC・点吸収式）・潮流タービン・OTEC・電力変換インターフェースの最適設計を扱う。",
 "再エネポートフォリオの多様化に貢献。韓国・中国・欧州が実証プロジェクトを推進中。",
 "電気電子工学","再生可能エネルギー工学",2005,None,"system","再生可能エネルギー",
 "海洋立地条件（波高・流速）の詳細評価、塩水腐食対策","島嶼部電力供給・沿岸再エネ開発時","OWCの最適チャンバー設計と電力変換効率のトレードオフは何か",
 "陸上風力・太陽光","波力発電,潮流,OTEC,OWC,海洋エネルギー",
 "wave power,tidal,OTEC,OWC,ocean energy",
 "active","secondary",77,5,
 "https://ieeexplore.ieee.org/document/9223476","グローバル",0.75,
 r"OWC空気柱電力: $P_{OWC} = \frac{1}{2}\rho_{air} A_{turb} u_{air}^3 \eta_{turb}$、波エネルギーフラックス $J = \frac{\rho g^2 H_s^2 T_e}{64\pi}$ [W/m]。",
 "url_present"),

("ee_b5_046","中国量子通信インフラ","China Quantum Communication Infrastructure","China Quantum Network",
 "中国が構築する都市間量子鍵配送ネットワーク。京滬幹線（2000km）・Micius衛星QKD・量子中継器開発・量子インターネットロードマップの技術的詳細と設計思想。",
 "世界初の実用的量子通信インフラを構築。国家機密保護・金融通信に実運用中。",
 "電気電子工学","量子通信工学",2016,None,"system","国家情報インフラ",
 "光ファイバ損失補償・中継局管理・衛星地上局光学系","量子暗号通信実装・量子ネットワーク構築時","信頼型中継（Trusted Node）から真の量子中継への移行は何時実現可能か",
 "古典暗号通信","量子通信,中国,京滬,Micius,QKD",
 "quantum communication,China,QKD,Micius,satellite",
 "active","secondary",82,5,
 "https://www.science.org/doi/10.1126/science.aab0760","東アジア",0.92,
 r"衛星QKD鍵レート: $R = \frac{\eta_{atm}\eta_{opt}\eta_{det}f_{rep}}{2}[1-h(e_b)-h(e_p)]$、大気透過率$\eta_{atm} \approx 0.1$（低軌道衛星晴天時）。",
 "url_present"),

("ee_b5_047","超低消費電力IoTチップ設計","Ultra-Low Power IoT Chip Design","ULP IoT SoC",
 "コイン電池・エネルギーハーベスティング動作を想定したIoT端末向け超低消費電力SoCの設計手法。サブスレッショルド回路・電源電圧スケーリング・アダプティブボルテージスケーリングを統合する。",
 "バッテリー交換不要な10年動作IoTセンサの実現基盤。スマートビル・農業IoT・医療モニタリングに適用。",
 "電気電子工学","超低消費電力回路",2010,None,"device","IoTエッジ",
 "平均電流<10μA・起動遅延許容・通信デューティ比<1%","バッテリー式IoTセンサ・ウェアラブル医療デバイス設計時","スリープ電流とウェイクアップ時間のトレードオフをどのように最小化するか",
 "汎用マイコン","ULP,IoT,サブスレッショルド,AVS,消費電力",
 "ULP,IoT,subthreshold,adaptive voltage scaling,power consumption",
 "active","secondary",83,9,
 "https://ieeexplore.ieee.org/document/8359286","欧米",0.8,
 r"サブスレッショルド電流: $I_{sub} = I_0 \exp\left(\frac{V_{GS}-V_t}{nV_T}\right)$、$V_T = kT/q$。動的消費電力 $P_{dyn} = \alpha C_{load} V_{DD}^2 f$、スケーリングで$\propto V_{DD}^3$削減。",
 "url_present"),

("ee_b5_048","バッテリー管理システム高度化","Advanced Battery Management System","Advanced BMS",
 "リチウムイオン電池のSOC・SOH・SOPをオンライン推定するBMSアルゴリズムの設計手法。等価回路モデル・電気化学モデル・適応型カルマンフィルタ・機械学習劣化予測を統合する。",
 "EVの航続距離・安全性・バッテリー寿命に直結。中国BYD・LGエナジー・パナソニックが競争。",
 "電気電子工学","電力変換工学",2010,None,"system","電気自動車・蓄電",
 "電池特性同定（充放電実験）・通信インターフェース（CAN）・安全規格（IEC 62619）","EV・BESS・ドローン向けバッテリー管理設計時","SOH劣化予測精度とオンライン計算量のトレードオフをどう解決するか",
 "単純電圧監視","BMS,SOC,SOH,カルマンフィルタ,リチウムイオン",
 "BMS,SOC,SOH,Kalman filter,lithium-ion",
 "active","secondary",85,9,
 "https://ieeexplore.ieee.org/document/8764535","東アジア",0.85,
 r"SOC推定（AEKF）: $\hat{x}_{k|k} = \hat{x}_{k|k-1} + K_k[y_k - g(\hat{x}_{k|k-1})]$、$K_k = P_k^- C_k^T(C_kP_k^- C_k^T + R_k)^{-1}$。等価回路 $V_t = OCV(SOC) - IR_0 - V_{RC}$。",
 "url_present"),

("ee_b5_049","先端メモリアーキテクチャ（HBM/LPDDR）","Advanced Memory Architecture HBM and LPDDR","Advanced Memory Architecture",
 "AI/HPC向けHBM（High Bandwidth Memory）とモバイル向けLPDDR5/5Xの設計・実装技術。3Dスタック構造・TSV密度・低電圧I/O・メモリコントローラ設計を扱う。",
 "HBM3で819 GB/sを達成。AI加速器（H100等）の性能限界を規定するメモリ帯域幅を解決。",
 "電気電子工学","メモリ工学",2013,None,"device","AI/HPC・モバイル",
 "TSVプロセス対応（直径5μm以下）・ECC実装・電源供給安定性","AI学習加速器・高帯域メモリ要求システム設計時","HBMの積層数増加と熱管理の限界はどこにあるか",
 "従来DRAM（DDR4）","HBM,LPDDR,3Dスタック,TSV,メモリ帯域幅",
 "HBM,LPDDR,3D stack,TSV,memory bandwidth",
 "active","secondary",84,9,
 "https://ieeexplore.ieee.org/document/9180011","東アジア",0.9,
 r"HBMメモリ帯域幅: $BW = 2 \times f_{data} \times W_{bus}/8$ [GB/s]、HBM3は 6.4 GHz × 1024 bit = 819 GB/s。消費電力 $P_{HBM} = C_{eff}V_{dd}^2 f + I_{leak}V_{dd}$。",
 "url_present"),

("ee_b5_050","再構成可能コンピューティング設計","Reconfigurable Computing Design","FPGA-based Reconfigurable Computing",
 "FPGAを用いたアプリケーション特化ハードウェアの設計手法。高位合成（HLS）・部分再構成・FPGA-CPUヘテロジニアスアーキテクチャ・クラウドFPGAの設計フローを統合する。",
 "データセンター加速（MicrosoftCatapult・Xilinx Alveo）・リアルタイム制御への応用が拡大。",
 "電気電子工学","再構成可能コンピューティング",2010,None,"system","HPC・データセンター",
 "HLS対応言語（C++・OpenCL）・タイミング制約・部分再構成要件","リアルタイム信号処理・加速カーネル実装時","HLSで生成された回路品質と手書きRTLの差をどのように埋めるか",
 "GPUのみの加速","FPGA,HLS,再構成可能,ヘテロジニアス,クラウド",
 "FPGA,HLS,reconfigurable,heterogeneous,cloud",
 "active","secondary",82,8,
 "https://ieeexplore.ieee.org/document/7577379","欧米",0.8,
 r"FPGA LUT利用率: $U_{LUT} = N_{logic}/N_{LUT,total}$、タイミング: $T_{clk} \geq T_{comb,max} + T_{setup}$。HLS最適化: ループアンロール $\times k$ でスループット $k$ 倍（リソース$k$倍）。",
 "url_present"),
]

if __name__ == "__main__":
    ins, skp = insert_records(records)
    print(f"Inserted: {ins}, Skipped: {skp}")
    import sqlite3 as _s
    c = _s.connect(DB).cursor()
    c.execute("SELECT COUNT(*) FROM engineering_method")
    print(f"Total: {c.fetchone()[0]}")
