#!/usr/bin/env python3
"""機械工学 Batch 2: mech_b2_001 - mech_b2_050"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

RECORDS = [
    ("mech_b2_001","油圧・空気圧システム設計","Hydraulic/Pneumatic System Design","Fluid Power System",
     "油圧・空気圧を動力媒体として用いるアクチュエータ・制御弁・ポンプの設計体系。バルブ特性・アキュムレータ・シール設計が核心。",
     "建設機械・プレス機・航空機操舵系の高出力密度動力伝達を担い、電動化との競合の中で精密制御能力で差別化が進んでいる。",
     "機械工学","流体動力・機械要素",1900,None,"実装技法","動力伝達・制御",
     "高出力密度・防爆環境・大推力が必要","掘削機・プレス・航空機フライトコントロール",
     "漏れリスクと環境負荷は許容できるか？電動化との競争力は？","電動アクチュエータ",
     "油圧システム,空気圧,比例弁,アキュムレータ,シール",
     "hydraulic system,pneumatic,proportional valve,accumulator,seal",
     "active","primary",85,9,
     "https://www.ifpe.com/","グローバル",0.9,
     "$$P = \\frac{Q \\Delta p}{\\eta_{vol}\\eta_{mech}}, \\quad F_{cyl} = A \\cdot p - F_{friction}$$",
     "url_present"),

    ("mech_b2_002","機械設計における信頼性設計","Probabilistic Mechanical Design","Probabilistic Design",
     "荷重・材料強度のばらつきを確率論的に扱う設計手法。信頼性指標β（ハーゾルド指標）・モンテカルロシミュレーションが主要手法。",
     "決定論的安全率設計を超え、確率論的な故障確率の定量化と最適安全率の合理的設定を可能にする。",
     "機械工学","信頼性・確率設計",1960,None,"設計原則","構造安全設計",
     "荷重・強度のばらつきが大きい部品","航空・核・土木構造の安全設計",
     "確率モデルの推定に十分なデータはあるか？尾部の分布仮定は？","決定論的安全率",
     "確率論的設計,信頼性指標,モンテカルロ,FORM,安全率",
     "probabilistic design,reliability index,Monte Carlo,FORM,safety factor",
     "active","primary",87,8,
     "https://doi.org/10.1115/1.2910930","グローバル",0.9,
     "$$\\beta = \\frac{\\mu_g}{\\sigma_g}, \\quad P_f = \\Phi(-\\beta) \\text{ (Hasofer-Lind reliability index)}$$",
     "url_present"),

    ("mech_b2_003","再生可能エネルギー機械設計","Renewable Energy Machine Design","RE Machine Design",
     "風力タービン・潮力発電・波力発電・太陽熱集熱器などの再生可能エネルギー変換機械の設計技術体系。",
     "脱炭素社会実現の核心技術として急速に進化し、オフショア風力・浮体式洋上風力が次世代設計の最前線となっている。",
     "機械工学","エネルギー変換機械",2000,None,"設計・最適化技法","再生可能エネルギー",
     "再生可能エネルギー資源が利用可能","洋上風力・太陽熱・潮力発電システム",
     "Betz限界内に設計できているか？荒天・塩害への耐久設計は？","化石燃料発電機",
     "風力タービン,洋上風力,Betz限界,LCOE,ブレード設計",
     "wind turbine,offshore wind,Betz limit,LCOE,blade design",
     "active","secondary",87,8,
     "https://doi.org/10.1016/j.rser.2022.112395","グローバル",0.9,
     "$$P_{wind} = \\frac{1}{2}\\rho A v^3 C_p, \\quad C_{p,max} = \\frac{16}{27} \\approx 0.593 \\text{ (Betz limit)}$$",
     "url_present"),

    ("mech_b2_004","生体力学","Biomechanics","Biomechanics",
     "人体・生体の力学的挙動を解析する学問分野。歩行解析・衝撃吸収・インプラント設計・スポーツバイオメカニクスが対象。",
     "人工関節・スポーツ用品・義肢設計・自動車衝突安全に応用され、人体の精密なデジタルモデル化が医療の革新を推進する。",
     "機械工学","バイオメカニクス",1960,None,"理論・アルゴリズム","医療・スポーツ工学",
     "人体・生体運動・インプラント設計","人工関節・義肢・衝突安全・リハビリ",
     "生体組織の非線形粘弾性モデルは適切か？in vivoとin vitroの差異は？","静的構造解析",
     "生体力学,歩行解析,骨折解析,インプラント,有限要素モデル",
     "biomechanics,gait analysis,fracture analysis,implant,FEM",
     "active","primary",88,8,
     "https://www.asbweb.org/","グローバル",0.9,
     "$$\\tau_{bone} = \\frac{M \\cdot c}{I}, \\quad E_{cartilage} \\approx 0.5\\text{-}5 \\text{ MPa (biphasic)}$$",
     "url_present"),

    ("mech_b2_005","超音速・高速空気力学","Supersonic and High-Speed Aerodynamics","Supersonic Aerodynamics",
     "マッハ数1以上の衝撃波・膨張波・境界層干渉を扱う高速空気力学。衝撃波管理・ウェーブドラッグ低減が設計核心。",
     "超音速旅客機（X-59）・極超音速機・宇宙往還機のコンセプト設計に欠かせない理論体系を提供する。",
     "機械工学","高速空気力学",1947,None,"理論・アルゴリズム","航空宇宙機設計",
     "Ma > 0.8 以上の飛行速度","超音速機・極超音速機・再突入カプセル",
     "衝撃波の位置を制御できるか？熱遮蔽は必要か？","亜音速空力設計",
     "超音速,衝撃波,マッハ数,ウェーブドラッグ,極超音速",
     "supersonic,shock wave,Mach number,wave drag,hypersonic",
     "active","primary",88,7,
     "https://doi.org/10.2514/3.47789","グローバル",0.9,
     "$$M_2^2 = \\frac{1 + (\\gamma-1)/2 \\cdot M_1^2}{\\gamma M_1^2 - (\\gamma-1)/2} \\text{ (normal shock)}$$",
     "url_present"),

    ("mech_b2_006","工場レイアウト最適化","Factory Layout Optimization","Facility Layout",
     "工場内の機械・設備・搬送経路の配置を最適化してマテリアルハンドリングコストと生産効率を改善する設計手法。",
     "セル生産・AGV・デジタルファクトリーとの統合で、工場設計の意思決定精度を大幅に向上させている。",
     "機械工学","生産システム工学",1950,None,"設計・最適化技法","工場設計",
     "新工場設計・既存工場再配置","物流コスト削減・生産リードタイム短縮",
     "将来の製品ミックス変化への対応は？AGVルートは実現可能か？","直感的配置",
     "工場レイアウト,SLP,FLP,デジタルファクトリー,AGV",
     "facility layout,SLP,FLP,digital factory,AGV",
     "active","primary",85,8,
     "https://doi.org/10.1016/0305-0548(86)90048-6","グローバル",0.9,
     "$$\\min \\sum_{i \\neq j} f_{ij} d_{ij} \\text{ (Quadratic Assignment Problem for layout)}$$",
     "url_present"),

    ("mech_b2_007","形状記憶合金応用","Shape Memory Alloy Applications","SMA Applications",
     "加熱により変形を回復する形状記憶合金（ニチノール等）をアクチュエータ・カプリング・医療器具に応用する設計技法。",
     "血管内ステント・矯正用ワイヤー・サーモスタット弁・宇宙展開機構への応用で、ユニークな温度応答機能を工学利用する。",
     "機械工学","スマート材料工学",1963,None,"実装技法","スマートデバイス設計",
     "温度変化に応じた形状変化が必要","医療機器・宇宙機構・HVAC弁",
     "変態温度の設計精度は？サイクル疲労特性は？","通常弾性材料",
     "形状記憶合金,SMA,ニチノール,スーパーエラスティック,相変態",
     "shape memory alloy,SMA,nitinol,superelastic,phase transformation",
     "active","primary",85,8,
     "https://doi.org/10.1016/j.actamat.2018.08.048","グローバル",0.9,
     "$$\\sigma_{SMA} = f(\\varepsilon, T, \\xi_{martensite}), \\quad \\Delta T_{hys} = A_s - M_f \\approx 20\\text{-}40 K$$",
     "url_present"),

    ("mech_b2_008","摩擦攪拌溶接","Friction Stir Welding","FSW",
     "回転ツールの摩擦熱と塑性流動を利用してアルミニウム・銅・鋼などを固相接合する製造技術。The Welding Instituteが1991年発明。",
     "航空機燃料タンク（Boeing）・新幹線アルミ車体・EV電池ケースに採用され、溶接欠陥が少なく高疲労強度の接合を実現する。",
     "機械工学","材料接合工学",1991,None,"実装技法","軽量構造接合",
     "アルミ合金・銅・軟鋼の接合","航空機構造・鉄道車両・EV電池ケース",
     "ツール磨耗の管理は？穴（キーホール）処理は？","MIG/TIG溶接",
     "摩擦攪拌溶接,FSW,固相接合,アルミ溶接,ショルダー",
     "friction stir welding,FSW,solid-state joining,aluminum welding,shoulder",
     "active","primary",88,9,
     "https://doi.org/10.1179/095066099101528430","グローバル",0.9,
     "$$Q_{FSW} = \\frac{2\\pi}{3}\\mu F_z \\omega r_s^3, \\quad T_{peak} \\approx 0.8 T_m \\text{ (Al alloys)}$$",
     "url_present"),

    ("mech_b2_009","スマート材料設計","Smart Materials Design","Smart Materials",
     "圧電・磁歪・エレクトロクロミック・光応答材料を活性化してセンシング・アクチュエーション・エネルギー収集を行う設計技法。",
     "自己感知構造材（Self-Sensing）・エネルギーハーベスティング・適応型光学系への応用で次世代スマート構造を実現する。",
     "機械工学","スマート材料工学",1990,None,"設計原則","スマートシステム設計",
     "センシングとアクチュエーションの統合が必要","振動制御・マイクロポンプ・NVH抑制",
     "電気的・機械的応答の線形性は確認されているか？温度依存性は？","受動材料",
     "スマート材料,圧電,磁歪,エネルギーハーベスト,自己感知",
     "smart materials,piezoelectric,magnetostrictive,energy harvesting,self-sensing",
     "active","primary",85,8,
     "https://doi.org/10.1080/15376494.2014.903314","グローバル",0.9,
     "$$d_{33} = \\frac{S_3}{E_3} \\text{ (piezo coupling)}, \\quad P_{harvest} = \\frac{\\omega^2 \\xi_m \\xi_e Y_0^2}{(\\xi_m + \\xi_e)^2}$$",
     "url_present"),

    ("mech_b2_010","機械システムの安全設計","Machine Safety Design","Machine Safety",
     "EN ISO 13849・IEC 62061に基づき機械システムの安全機能・安全カテゴリ・PL（性能レベル）・SILを設計する手法。",
     "EUのMachinery Directive適合のために必須となり、協働ロボット・プレス機・産業ゲート等の安全設計の国際標準となっている。",
     "機械工学","安全工学",2006,None,"設計原則","機械安全設計",
     "人間と機械が相互作用する全システム","CE認証・安全規格適合",
     "リスク評価は実施されているか？誰が操作するか？","事後対策",
     "機械安全,ISO13849,PLe,SIL,安全コントローラ",
     "machine safety,ISO13849,PLe,SIL,safety controller",
     "active","primary",90,9,
     "https://www.iso.org/standard/69883.html","欧米",0.9,
     "$$\\text{PL} = f(\\text{Category}, \\text{MTTFd}, \\text{DCavg}) \\in \\{a,b,c,d,e\\}$$",
     "url_present"),

    ("mech_b2_011","電気自動車パワートレイン設計","EV Powertrain Design","EV Powertrain",
     "電動モータ・インバータ・バッテリー・変速機を統合した電気自動車の動力系設計。800V高電圧アーキテクチャが現代標準。",
     "BEV普及の技術的核心であり、エネルギー密度・充電速度・回生制動効率のトレードオフが設計の中心課題となっている。",
     "機械工学","電動化・自動車工学",2010,None,"設計・最適化技法","電動輸送機設計",
     "BEV・PHEV設計","航続距離最大化・充電速度向上・回生制動",
     "充電インフラの電圧規格は？熱管理システムの設計は？","内燃機関パワートレイン",
     "EVパワートレイン,BEV,800V,PMSM,回生制動",
     "EV powertrain,BEV,800V architecture,PMSM,regenerative braking",
     "active","secondary",88,9,
     "https://doi.org/10.1109/TTE.2023.3235234","グローバル",0.9,
     "$$W_{range} = \\frac{E_{battery}}{P_{avg}} = \\frac{E_{battery}}{(F_{aero}+F_{roll}+F_{accel})v/\\eta_{PT}}$$",
     "url_present"),

    ("mech_b2_012","複合材料設計","Composite Material Design","Composite Design",
     "CFRP・GFRP・金属基複合材の積層設計・成形プロセス設計・破壊モード解析を行う設計技法。CLT（古典積層板理論）が理論基盤。",
     "航空機胴体・風力タービンブレード・スポーツ用品の軽量高剛性化を実現し、CFRPが航空宇宙の標準構造材料となった。",
     "機械工学","複合材料工学",1960,None,"設計・最適化技法","軽量構造設計",
     "軽量・高強度・高剛性が求められる構造","航空機主翼・風力ブレード・プレッシャーベッセル",
     "繊維方向配置の最適化は？層間剥離（デラミネーション）の評価は？","金属構造",
     "CFRP,複合材料,積層設計,CLT,デラミネーション",
     "CFRP,composite material,laminate design,CLT,delamination",
     "active","primary",90,8,
     "https://doi.org/10.1016/j.compscitech.2020.108398","グローバル",0.9,
     "$$A_{ij} = \\sum_k Q_{ij}^{(k)} h_k, \\quad D_{ij} = \\frac{1}{3}\\sum_k Q_{ij}^{(k)}(z_k^3 - z_{k-1}^3) \\text{ (CLT)}$$",
     "url_present"),

    ("mech_b2_013","粉末冶金技術","Powder Metallurgy","Powder Metallurgy",
     "金属粉末を成形・焼結して部品を製造する技法。選択的レーザー焼結（SLS）を含む積層造形との融合が進んでいる。",
     "超硬工具・多孔質軸受・複雑形状部品の量産に不可欠で、AM（積層造形）との組み合わせで設計自由度が飛躍的に拡大した。",
     "機械工学","材料製造工学",1900,None,"実装技法","金属部品製造",
     "高融点金属・複雑形状・多孔質構造が必要","超硬工具・含油軸受・フィルタ材",
     "焼結密度と孔率のトレードオフは？粉末の品質管理は？","鋳造・鍛造",
     "粉末冶金,焼結,SLS,超硬合金,金属積層造形",
     "powder metallurgy,sintering,SLS,cemented carbide,metal AM",
     "active","primary",88,8,
     "https://www.mpif.org/","グローバル",0.9,
     "$$\\rho_{sintered} = \\rho_{theor}(1 - P), \\quad D_{grain} \\propto \\exp\\left(-\\frac{Q}{RT}\\right) t^{1/n}$$",
     "url_present"),

    ("mech_b2_014","産業IoTセンサネットワーク","Industrial IoT Sensor Network","IIoT Sensor Network",
     "製造設備・インフラに分散したセンサを無線・有線で接続し、データを収集・解析する産業用IoTシステム設計。",
     "予知保全・品質トレーサビリティ・エネルギー管理の基盤として、スマートファクトリーの実現を推進する核心技術。",
     "機械工学","IoT・スマート製造",2012,None,"実装技法","スマート製造",
     "製造設備・インフラの状態監視","予知保全・品質管理・エネルギー最適化",
     "データ通信プロトコル（OPC-UA等）は？エッジ処理かクラウドかの判断は？","手動点検",
     "IIoT,OPC-UA,PLC,エッジコンピューティング,予知保全",
     "IIoT,OPC-UA,PLC,edge computing,predictive maintenance",
     "active","secondary",85,8,
     "https://www.opcfoundation.org/","グローバル",0.9,
     "$$\\text{Data rate: } R = B \\log_2(1+SNR), \\quad \\text{latency} < 10 \\text{ ms for control}$$",
     "url_present"),

    ("mech_b2_015","切削加工最適化","Cutting Process Optimization","Machining Optimization",
     "切削条件（速度・送り量・切削深さ）・工具材種・クーラント戦略を最適化して生産性・工具寿命・表面品質を向上させる技術。",
     "AI・IoT統合による自動工具摩耗検知と切削条件適応制御が次世代製造の競争力を決定する重要技術領域となっている。",
     "機械工学","製造工学・生産技術",1907,None,"設計・最適化技法","切削加工",
     "NC/CNC加工","生産性最大化・工具費削減・面粗さ確保",
     "テイラーの工具寿命式は適用できるか？切削熱の影響は？","経験的条件設定",
     "切削最適化,テイラー式,工具摩耗,切削力,MQL",
     "machining optimization,Taylor equation,tool wear,cutting force,MQL",
     "active","primary",88,9,
     "https://doi.org/10.1016/j.cirp.2020.05.006","グローバル",0.9,
     "$$VT^n = C \\text{ (Taylor tool life)}, \\quad F_c = K_c \\cdot f^{x} \\cdot a_p^{y} \\cdot V^z$$",
     "url_present"),

    ("mech_b2_016","原子力機器設計","Nuclear Equipment Design","Nuclear Equipment Design",
     "原子炉・蒸気発生器・格納容器などの原子力機器の設計に適用される圧力容器規格（ASME Section III）・耐震設計の体系。",
     "Fukushima後の安全基準強化（SA対策）・SMR（小型モジュール炉）設計で新局面を迎え、廃炉工学も重要分野となっている。",
     "機械工学","原子力工学",1950,None,"設計原則","原子力システム",
     "原子力プラント・高放射線環境","原子炉圧力容器・格納容器・冷却系配管",
     "中性子照射脆化はどう評価するか？LOCA解析の保守性は？","通常圧力容器設計",
     "原子力機器設計,ASME III,圧力容器,耐震設計,SA対策",
     "nuclear equipment design,ASME III,pressure vessel,seismic design,severe accident",
     "active","primary",90,8,
     "https://www.asme.org/codes-standards/find-codes-standards/bpvc-iii-nd-section-iii-appendices","グローバル",0.9,
     "$$\\sigma_{allowable} = \\min\\left(\\frac{S_u}{3}, \\frac{S_y}{1.5}\\right), \\quad \\text{fatigue: } K_f S_a \\leq S_{allowable}$$",
     "url_present"),

    ("mech_b2_017","クリープ・高温強度設計","Creep and High-Temperature Strength Design","Creep Design",
     "高温環境での時間依存変形（クリープ）と強度低下を考慮した設計技法。ラーソン・ミラーパラメータ・Norton則が基本。",
     "蒸気タービン・ガスタービン・核融合装置の高温部品設計に必須で、耐熱合金の設計許容値の根拠となる。",
     "機械工学","材料力学・高温材料",1950,None,"理論・アルゴリズム","高温機器設計",
     "400℃以上で長時間使用される金属部品","タービン翼・ボイラー管・反応炉容器",
     "クリープ破断寿命の予測精度は？材料のロット間ばらつきは？","室温強度設計のみ",
     "クリープ設計,ラーソンミラー,Norton則,高温強度,耐熱合金",
     "creep design,Larson-Miller,Norton law,high-temperature strength,superalloy",
     "active","primary",88,8,
     "https://doi.org/10.1016/j.msea.2019.138641","グローバル",0.9,
     "$$\\dot{\\varepsilon} = A \\sigma^n \\exp(-Q/RT) \\text{ (Norton creep)}, \\quad LMP = T(\\log t_r + C)$$",
     "url_present"),

    ("mech_b2_018","非線形有限要素解析","Nonlinear Finite Element Analysis","Nonlinear FEA",
     "材料非線形（弾塑性・超弾性）・幾何学非線形（大変形）・接触非線形を扱う有限要素解析の拡張手法。",
     "自動車クラッシュシミュレーション・ゴムシール設計・金属成形解析など実用工業問題の高精度予測を可能にした。",
     "機械工学","計算力学",1970,None,"実装技法","非線形構造解析",
     "降伏・大変形・接触が関わる問題","クラッシュ解析・成形・シール・生体組織",
     "収束性は確保できるか？接触アルゴリズムの精度は？","線形解析",
     "非線形FEA,弾塑性,大変形,接触解析,クラッシュシミュレーション",
     "nonlinear FEA,elastoplastic,large deformation,contact analysis,crash simulation",
     "active","primary",90,9,
     "https://www.lsdyna.com/","グローバル",0.9,
     "$$K_T \\Delta u = \\Delta F, \\quad K_T = \\frac{\\partial F}{\\partial u} \\text{ (tangent stiffness, Newton-Raphson)}$$",
     "url_present"),

    ("mech_b2_019","ガスダイナミクス","Gas Dynamics","Gas Dynamics",
     "圧縮性流体の高速流れを扱う流体力学分野。衝撃波管・ノズル設計・圧縮機翼型が主要応用。ランキン-ユゴニオ方程式が基本。",
     "ロケットエンジンノズル・超音速風洞・爆発物設計の理論的基盤として、宇宙機推進と防衛技術を支えている。",
     "機械工学","流体力学・推進",1880,None,"理論・アルゴリズム","推進・高速飛行設計",
     "Ma > 0.3 の圧縮性効果が無視できない流れ","ロケットノズル・超音速インテーク・圧力容器破裂",
     "等エントロピー流れの仮定は成立するか？摩擦・熱伝達の影響は？","非圧縮性流体解析",
     "ガスダイナミクス,衝撃波,ノズル設計,ランキンユゴニオ,膨張扇",
     "gas dynamics,shock wave,nozzle design,Rankine-Hugoniot,expansion fan",
     "active","primary",90,8,
     "https://doi.org/10.2514/3.62853","グローバル",0.9,
     "$$p_2/p_1 = 1 + \\frac{2\\gamma}{\\gamma+1}(M_1^2-1), \\quad A^*: \\frac{A}{A^*} = \\frac{1}{M}\\left[\\frac{2}{\\gamma+1}\\left(1+\\frac{\\gamma-1}{2}M^2\\right)\\right]^{\\frac{\\gamma+1}{2(\\gamma-1)}}$$",
     "url_present"),

    ("mech_b2_020","インバータ・モータ制御","Inverter and Motor Control","Inverter Motor Control",
     "三相インバータ・PWM変調・ベクトル制御（FOC）・直接トルク制御（DTC）によるACモータの高精度トルク・速度制御技術。",
     "EV・工作機械・エレベータ・空調コンプレッサの高効率制御を実現し、インバータ普及による省エネを大幅に推進した。",
     "機械工学","電力変換・モータ制御",1980,None,"実装技法","電動システム",
     "AC誘導・PMモータの可変速制御","EV・工作機械・ポンプ・コンプレッサ",
     "dq変換の座標変換精度は？デッドタイム補償は必要か？","固定速度制御",
     "インバータ,ベクトル制御,FOC,DTC,PWM",
     "inverter,field-oriented control,FOC,DTC,PWM",
     "active","primary",90,9,
     "https://doi.org/10.1109/TIE.2020.3012526","グローバル",0.9,
     "$$\\mathbf{v}_{dq} = R_s\\mathbf{i}_{dq} + L\\frac{d\\mathbf{i}_{dq}}{dt} + j\\omega_e\\psi_{dq}, \\quad T = \\frac{3p}{2}\\psi_f i_q$$",
     "url_present"),

    ("mech_b2_021","機械要素設計（軸受・シール）","Mechanical Component Design - Bearings and Seals","Bearing and Seal Design",
     "転がり軸受・すべり軸受・シール・カップリングの設計・選定・寿命予測の体系的手法。ISO 281が転がり軸受寿命算定の国際標準。",
     "回転機械の長寿命化・摩擦低減・漏れ防止に不可欠で、適切な設計は機械の総合効率向上と保全コスト削減を実現する。",
     "機械工学","機械要素設計",1900,None,"設計原則","回転機械設計",
     "回転部・摺動部・シール部を有する機械全般","工作機械・自動車・ポンプ・コンプレッサ",
     "基本動定格荷重と実負荷の比は？润滑方式は？","溶接固定構造",
     "軸受設計,ISO281,油膜潤滑,シール設計,L10寿命",
     "bearing design,ISO281,hydrodynamic lubrication,seal design,L10 life",
     "active","primary",90,9,
     "https://www.iso.org/standard/54434.html","グローバル",0.9,
     "$$L_{10} = \\left(\\frac{C}{P}\\right)^p \\cdot 10^6, \\quad p=3 \\text{ (ball)}, 10/3 \\text{ (roller)}$$",
     "url_present"),

    ("mech_b2_022","クリーンルーム設計","Cleanroom Design","Cleanroom Design",
     "半導体・医薬品製造に必要な清浄度（ISO 14644）を維持する空気清浄・温湿度管理・気流制御設計技法。FFU・HEPA・層流が主要概念。",
     "半導体微細化を支える清浄度管理の基盤技術であり、COVID-19後の医療品製造クリーンルームへの需要も拡大している。",
     "機械工学","精密環境工学",1960,None,"設計原則","精密製造環境",
     "半導体・医薬品・バイオ・精密測定","半導体ウエハ工程・無菌製剤製造",
     "気流パターン（層流/乱流）の選択は？人員管理プロトコルは？","通常工場",
     "クリーンルーム,ISO14644,HEPA,FFU,層流",
     "cleanroom,ISO14644,HEPA,FFU,laminar flow",
     "active","primary",88,9,
     "https://www.iso.org/standard/53394.html","グローバル",0.9,
     "$$N_{particles} \\propto \\frac{1}{Q_{air}} \\text{ (particle count decrease with ACH increase)}$$",
     "url_present"),

    ("mech_b2_023","航空機構造疲労設計","Aircraft Structural Fatigue Design","Aircraft Fatigue Design",
     "航空機機体の反復荷重による疲労破壊を防ぐためのSafe-Life・Damage Tolerance・Fail-Safeの三つの設計哲学と解析手法体系。",
     "コメット機事故（1954）を契機に確立され、現代航空機の長寿命・高安全性の基盤となっている重要設計分野。",
     "機械工学","航空宇宙工学",1960,None,"設計原則","航空機構造設計",
     "航空機機体・エンジン構造","型式証明取得・定期検査間隔設定",
     "Damage Tolerance基準のき裂寸法は妥当か？検査頻度と検出確率の関係は？","従来の安全率設計",
     "航空機疲労設計,Damage Tolerance,Safe Life,残留強度,き裂進展",
     "aircraft fatigue design,damage tolerance,safe life,residual strength,crack propagation",
     "active","primary",90,9,
     "https://www.faa.gov/aircraft/air_cert/design_approvals/structural_methodology","グローバル",0.9,
     "$$K_I = \\sigma \\sqrt{\\pi a} F(a/W), \\quad \\frac{da}{dN} = C(\\Delta K)^m \\Rightarrow N_f = \\int_{a_0}^{a_c} \\frac{da}{C(\\Delta K)^m}$$",
     "url_present"),

    ("mech_b2_024","ロケット推進設計","Rocket Propulsion Design","Rocket Propulsion",
     "液体・固体・ハイブリッドロケットエンジンの推力生成・燃焼効率・膨張比最適化を設計する技術体系。ツィオルコフスキー方程式が基本。",
     "SpaceX Falconによる再使用ロケット・Starlinkの大量打ち上げが宇宙アクセスコストを劇的に削減し、新宇宙産業を創出した。",
     "機械工学","宇宙推進工学",1926,None,"設計・最適化技法","宇宙輸送機設計",
     "宇宙輸送・探査機推進","軌道打ち上げ・軌道変換・惑星着陸",
     "推進剤の比推力と密度比推力のトレードオフは？熱遮蔽の設計は？","大気圏内エンジン",
     "ロケット推進,比推力,Isp,ツィオルコフスキー,再使用ロケット",
     "rocket propulsion,specific impulse,Isp,Tsiolkovsky,reusable rocket",
     "active","primary",88,7,
     "https://doi.org/10.2514/3.62904","グローバル",0.9,
     "$$\\Delta v = I_{sp} g_0 \\ln\\frac{m_0}{m_f} \\text{ (Tsiolkovsky)}, \\quad c^* = \\sqrt{\\frac{\\gamma R T_c}{\\gamma+1}\\left(\\frac{2}{\\gamma+1}\\right)^{\\frac{\\gamma+1}{\\gamma-1}}}$$",
     "url_present"),

    ("mech_b2_025","廃棄物熱利用工学","Waste Heat Recovery Engineering","Waste Heat Recovery",
     "工業プロセスや輸送機器から排出される排熱を有効利用するランキンサイクル・ヒートポンプ・熱電変換の設計技法体系。",
     "製鉄・化学・データセンターなど排熱大量発生産業でのCO2削減手段として注目され、産業部門脱炭素の重要戦略となっている。",
     "機械工学","エネルギー回収工学",1980,None,"設計・最適化技法","エネルギーシステム",
     "大量排熱が存在する産業プロセス","鉄鋼・化学プラント・データセンター",
     "排熱温度と回収温度のマッチングは？経済性（投資回収）は？","排熱放棄",
     "廃熱回収,ORC,熱電変換,ヒートポンプ,エクセルギー効率",
     "waste heat recovery,ORC,thermoelectric,heat pump,exergy efficiency",
     "active","secondary",85,8,
     "https://doi.org/10.1016/j.energy.2022.124897","グローバル",0.9,
     "$$\\eta_{ORC} = 1 - T_L/T_H, \\quad ZT = \\frac{S^2 \\sigma T}{\\kappa} \\text{ (thermoelectric figure of merit)}$$",
     "url_present"),

    ("mech_b2_026","機械設計の倫理と持続可能性","Engineering Ethics and Sustainability","Engineering Ethics",
     "機械設計における倫理責任・持続可能性・ライフサイクルアセスメント（LCA）・循環経済原則の体系。NSPE倫理綱領が参照基準。",
     "IPCC・SDGsの要求と製品責任法の観点から、機械エンジニアが環境・社会への影響を設計段階から評価する責任が高まっている。",
     "機械工学","工学倫理・持続可能設計",1970,None,"設計原則","持続可能設計",
     "全ての製品設計","環境負荷最小化・安全性確保・社会的責任",
     "製品の全ライフサイクルCO2は算定されているか？解体・再利用の設計は？","機能のみを重視した設計",
     "LCA,循環経済,工学倫理,DfE,サステナブル設計",
     "LCA,circular economy,engineering ethics,DfE,sustainable design",
     "active","primary",88,9,
     "https://www.nspe.org/resources/ethics/code-ethics","グローバル",0.9,
     "$$\\text{LCA: } \\sum_{i} GWP_i \\cdot m_i \\text{ [kg CO}_2\\text{-eq]} \\text{ over cradle-to-grave}$$",
     "url_present"),

    ("mech_b2_027","工業炉・熱処理設備設計","Industrial Furnace and Heat Treatment Design","Industrial Furnace Design",
     "焼入れ・焼き鈍し・浸炭・窒化などの熱処理プロセスを実現する工業炉の温度制御・雰囲気管理・熱効率設計の技法体系。",
     "自動車ギア・航空機部品・工具鋼の品質を決定する熱処理の精度管理が、製造品質の核心技術の一つとなっている。",
     "機械工学","材料加工・生産技術",1900,None,"実装技法","材料熱処理",
     "金属部品の機械的性質改善","焼入れ・浸炭焼入れ・焼きなまし・時効処理",
     "温度均一性は±何℃が必要か？AMS 2750（高温計測）に対応しているか？","機械的加工のみ",
     "工業炉,熱処理,浸炭,焼入れ,AMS2750",
     "industrial furnace,heat treatment,carburizing,hardening,AMS2750",
     "active","primary",88,9,
     "https://www.ihs.com/products/aerospace-standards-ams.html","グローバル",0.9,
     "$$C(x,t) = C_s - (C_s - C_0)\\,\\text{erf}\\left(\\frac{x}{2\\sqrt{Dt}}\\right) \\text{ (carburizing profile)}$$",
     "url_present"),

    ("mech_b2_028","宇宙環境設計","Space Environment Design","Space Environment Engineering",
     "真空・放射線・熱サイクル・デブリなどの宇宙環境における機器・構造の設計技法。ECSS規格が欧州標準。",
     "商業衛星・宇宙ステーション実験装置・月面探査機の設計に不可欠で、宇宙ビジネス拡大（NewSpace）に伴い設計人材の需要が増大している。",
     "機械工学","宇宙システム工学",1960,None,"設計原則","宇宙機設計",
     "宇宙空間で使用する機器全般","衛星・宇宙ステーション設備・月惑星探査機",
     "放射線被曝量（Total Ionizing Dose）は許容できるか？熱サイクル試験は実施するか？","地上用電子機器",
     "宇宙環境,放射線耐性,熱制御,デブリ回避,ECSS",
     "space environment,radiation hardening,thermal control,debris avoidance,ECSS",
     "active","primary",88,7,
     "https://ecss.nl/","グローバル",0.9,
     "$$T_{surface} = T_{eq}(1-A)^{1/4}, \\quad \\text{TID} = \\int \\dot{D}(E) \\phi(E) dE$$",
     "url_present"),

    ("mech_b2_029","インフラ資産管理","Infrastructure Asset Management","Infrastructure Asset Management",
     "橋梁・道路・ダム・水道・エネルギー設備などのインフラ資産を効率よく保全・更新するためのライフサイクルコスト最小化戦略。",
     "高度経済成長期に建設したインフラの老朽化が世界的課題となり、PAS55・ISO 55000に基づく資産管理が標準実践となっている。",
     "機械工学","インフラ保全工学",2000,None,"プロセス・方法論","社会インフラ管理",
     "公共インフラ・産業設備","道路・橋梁・水処理・送電線の長期保全計画",
     "リスクベース保全と定期保全のどちらが経済的か？BIM連携は？","故障してから修理",
     "資産管理,ISO55000,LCC,リスクベース保全,BIM",
     "asset management,ISO55000,LCC,risk-based maintenance,BIM",
     "active","secondary",85,8,
     "https://www.iso.org/standard/55089.html","グローバル",0.9,
     "$$\\text{LCC} = C_{capital} + \\sum_{t=1}^{L}\\frac{C_{O\\&M,t} + C_{failure,t}}{(1+r)^t}$$",
     "url_present"),

    ("mech_b2_030","製品ライフサイクル管理","Product Lifecycle Management","PLM",
     "製品のコンセプト・設計・製造・運用・廃棄までの全ライフサイクルを統合管理するシステムと方法論。Siemens Teamcenter・PTCが代表的ツール。",
     "航空・自動車・防衛産業での複数万点の部品管理・変更管理・デジタルスレッドの中核インフラとして機能する。",
     "機械工学","製品管理・DX",1990,None,"プロセス・方法論","製品開発管理",
     "大規模複雑製品の開発・製造・保守","設計変更管理・構成管理・デジタルツイン連携",
     "BOMの構造は部門間で整合しているか？変更承認プロセスは？","ExcelベースBOM",
     "PLM,製品ライフサイクル,BOM,Teamcenter,デジタルスレッド",
     "PLM,product lifecycle management,BOM,Teamcenter,digital thread",
     "active","secondary",85,9,
     "https://www.plm.automation.siemens.com/","グローバル",0.9,
     "$$\\text{Engineering change impact} = \\sum_{parts\\_affected} \\frac{\\Delta cost_i \\cdot risk_i}{lead\\_time_i}$$",
     "url_present"),

    ("mech_b2_031","量子計測・精密測定","Quantum Metrology and Precision Measurement","Quantum Metrology",
     "量子効果を利用して極限精度の測定を実現する技術。原子時計・重力波検出（LIGO）・量子センシング（NV中心）が代表的応用。",
     "LIGOが2015年重力波を初検出し、量子計測がマクロ自然現象の観測に革命をもたらした。GPS・ナビゲーション精度の根拠でもある。",
     "機械工学","精密計測・量子工学",1990,None,"理論・アルゴリズム","精密計測",
     "極限精度の時間・長さ・重力・磁場測定","原子時計・重力波検出・量子コンパス",
     "ハイゼンベルク限界に近づけているか？ノイズのフロアは何か？","古典的計測",
     "量子計測,重力波,LIGO,原子時計,NV中心",
     "quantum metrology,gravitational wave,LIGO,atomic clock,NV center",
     "active","primary",90,6,
     "https://doi.org/10.1103/PhysRevLett.116.061102","グローバル",0.9,
     "$$\\Delta x \\Delta p \\geq \\hbar/2 \\text{ (Heisenberg)}, \\quad \\delta x_{HL} = 1/N \\text{ vs. } \\delta x_{SQL} = 1/\\sqrt{N}$$",
     "url_present"),

    ("mech_b2_032","統計的工程管理","Statistical Process Control","SPC",
     "製造工程の品質特性を管理図で継続的に監視し、特殊要因による工程異常を早期検知・除去する統計的品質管理手法。",
     "シューハート管理図・CpkはISO・自動車QS-9000・AS9100の基本要求事項として、量産品の品質保証を支えている。",
     "機械工学","品質工学",1924,None,"設計原則","製造品質管理",
     "量産製品の継続的品質監視","不良率削減・工程能力指数向上",
     "管理図の種類（X-R, P, C）の選択は適切か？測定系のGage R&Rは？","最終検査のみ",
     "SPC,管理図,Cpk,工程能力,シューハート",
     "SPC,control chart,Cpk,process capability,Shewhart",
     "active","primary",92,9,
     "https://asq.org/quality-resources/statistical-process-control","グローバル",0.9,
     "$$C_p = \\frac{USL - LSL}{6\\sigma}, \\quad C_{pk} = \\min\\left(\\frac{USL-\\bar{x}}{3\\sigma}, \\frac{\\bar{x}-LSL}{3\\sigma}\\right)$$",
     "url_present"),

    ("mech_b2_033","機械加工の中国・アジア展開","Manufacturing Expansion in China and Asia","Asian Manufacturing Expansion",
     "中国・ベトナム・タイ・インドへの製造拠点展開に関わる工程設計・品質移転・サプライチェーン構築の工学的実践体系。",
     "China+1戦略・フレンドショアリングの中で製造拠点の多元化が加速し、ベトナム・インド・メキシコへの移転工学が重要化している。",
     "機械工学","東アジア工学・グローバル製造",2000,None,"プロセス・方法論","グローバル製造戦略",
     "アジア市場向け・コスト最適化製造","自動車・電機・機械部品のアジア製造",
     "品質管理体制の移転は可能か？ローカルサプライヤーの能力は？","国内集約製造",
     "中国製造,China+1,ベトナム展開,グローバルサプライチェーン,製造移転",
     "China manufacturing,China+1,Vietnam expansion,global supply chain,manufacturing transfer",
     "active","secondary",80,8,
     "https://www.made-in-china.com/","東アジア",0.85,
     "$$\\text{TCO} = C_{mfg} + C_{quality} + C_{logistics} + C_{IP\\_risk} + C_{regulatory}$$",
     "url_present"),

    ("mech_b2_034","流体騒音制御","Flow-Induced Noise Control","Aero-Acoustic Control",
     "流体の乱流・キャビテーション・渦剥離が発生する騒音を設計段階で低減するための解析・設計手法。LES・BEMが主要ツール。",
     "航空機降着装置・自動車ドアミラー・空調送風機・水中推進器の騒音基準適合に必要で、電動化でエンジン騒音が減りかえって重要性が増している。",
     "機械工学","音響・流体工学",1952,None,"理論・アルゴリズム","騒音設計",
     "高速流体・キャビテーション・突起物","航空機騒音・自動車風切り音・水中推進器",
     "音源の種類（単極・双極・四重極）は？流体-音響連成の強さは？","遮音材での対処のみ",
     "空力騒音,Lighthill方程式,LES,BEM,キャビテーション騒音",
     "aeroacoustic noise,Lighthill equation,LES,BEM,cavitation noise",
     "active","primary",85,7,
     "https://doi.org/10.1098/rspa.1952.0060","グローバル",0.9,
     "$$\\frac{\\partial^2 \\rho'}{\\partial t^2} - c_0^2 \\nabla^2 \\rho' = \\frac{\\partial^2 T_{ij}}{\\partial x_i \\partial x_j} \\text{ (Lighthill)}$$",
     "url_present"),

    ("mech_b2_035","流れの可視化技術","Flow Visualization Techniques","Flow Visualization",
     "PIV・シュリーレン・LDV・PSP・高速度カメラを用いた流体流れの定量・定性的可視化技法の体系。",
     "CFD検証・タービン翼間流れ計測・エンジン燃焼解析に不可欠で、高速イメージング技術の進歩と共に分解能が飛躍的に向上した。",
     "機械工学","流体計測技術",1960,None,"検証技法","流体実験・CFD検証",
     "流体流れの構造把握・CFD検証","PIV流速場・シュリーレン衝撃波・LDV速度測定",
     "測定分解能と測定範囲のトレードオフは？シード粒子の追随性は？","圧力センサのみ",
     "PIV,シュリーレン,LDV,PSP,流体可視化",
     "PIV,Schlieren,LDV,PSP,flow visualization",
     "active","primary",88,8,
     "https://doi.org/10.1088/0957-0233/8/12/002","グローバル",0.9,
     "$$\\mathbf{u}(x,t) = \\frac{\\Delta\\mathbf{x}}{\\Delta t} \\text{ (PIV)}, \\quad \\sigma_{PIV} < 0.1 \\text{ px (subpixel accuracy)}$$",
     "url_present"),

    ("mech_b2_036","工作機械設計","Machine Tool Design","Machine Tool Design",
     "旋盤・フライス盤・研削盤・マシニングセンタなど工作機械本体の精度・剛性・熱変位・振動特性を最適化する設計技術。",
     "日本の工作機械（ファナック・マキノ・森精機）は世界最高精度を誇り、半導体装置・航空部品の精密加工を支えている。",
     "機械工学","精密機械設計",1800,None,"設計・最適化技法","精密製造機械設計",
     "精密な機械加工が必要な製造業全般","半導体製造装置・航空部品・光学部品加工",
     "熱変位補正は実施しているか？主軸剛性と回転精度のトレードオフは？","手動加工",
     "工作機械設計,マシニングセンタ,熱変位,主軸精度,剛性",
     "machine tool design,machining center,thermal displacement,spindle accuracy,stiffness",
     "active","primary",90,9,
     "https://www.jimtof.org/","東アジア",0.9,
     "$$\\delta_{thermal} = \\alpha L \\Delta T, \\quad f_c = \\frac{1}{2\\pi}\\sqrt{K/M} \\text{ (spindle modal)}$$",
     "url_present"),

    ("mech_b2_037","流体力学数値安定化手法","Numerical Stabilization in Fluid Mechanics","Stabilized FEM/FVM",
     "対流支配流れや圧力-速度連成問題での数値不安定（チェッカーボード・ウィグル）を抑制する安定化有限要素・有限体積法。",
     "SUPG・PSPG・VMS（変分マルチスケール法）が現代CFDコードの基盤となり、高レイノルズ数流れの安定した数値解析を実現した。",
     "機械工学","計算力学",1982,None,"理論・アルゴリズム","CFD数値手法",
     "対流支配流れ・乱流・高Re数の計算","航空機翼型・タービン翼・建築周りの流れ",
     "安定化パラメータτは適切か？格子ペクレ数は管理されているか？","中央差分（不安定）",
     "SUPG,PSPG,安定化有限要素,VMS,ペクレ数",
     "SUPG,PSPG,stabilized FEM,VMS,Peclet number",
     "active","primary",85,8,
     "https://doi.org/10.1016/0045-7825(86)90025-3","欧米",0.9,
     "$$\\tau_{SUPG} = \\left[\\left(\\frac{2}{\\Delta t}\\right)^2 + \\left(\\frac{2\\|\\mathbf{u}\\|}{h}\\right)^2 + \\left(\\frac{4\\nu}{h^2}\\right)^2\\right]^{-1/2}$$",
     "url_present"),

    ("mech_b2_038","柔軟構造動特性解析","Flexible Structure Dynamics","Flexible Structure Dynamics",
     "翼・アンテナ・太陽電池パネルなどの柔軟構造の振動・たわみ・姿勢制御連成問題を解析する有限要素ベースの動特性解析技法。",
     "大型宇宙構造・超長翼風力発電機・フレキシブルロボットの設計に不可欠で、幾何学非線形効果を含む精度の高い数値手法が求められる。",
     "機械工学","構造動力学",1970,None,"理論・アルゴリズム","柔軟体動力学",
     "変形が大きく剛体仮定が成立しない構造","大型宇宙構造・長スパン橋梁・風力ブレード",
     "モード削減の精度は？非線形変形の寄与はどの程度か？","剛体力学モデル",
     "柔軟構造,モード展開,Craig-Bampton法,大変形,宇宙構造",
     "flexible structure,modal expansion,Craig-Bampton,large deformation,space structure",
     "active","primary",87,7,
     "https://doi.org/10.2514/2.6784","グローバル",0.9,
     "$$M\\ddot{q} + K q = 0, \\quad q = \\Phi \\eta \\text{ (modal superposition)}, \\quad r \\ll n \\text{ (reduced DOF)}$$",
     "url_present"),

    ("mech_b2_039","電磁両立性（EMC）設計","Electromagnetic Compatibility Design","EMC Design",
     "電子機器の電磁ノイズ放射と耐ノイズ性（イミュニティ）を設計段階から確保するためのEMC設計技法。IEC 61000が主要規格。",
     "EV・スマート家電・医療機器の認証取得に必須で、シールド設計・フィルタリング・PCBレイアウトの最適化が設計核心となる。",
     "機械工学","電磁工学・電子設計",1979,None,"設計原則","電子機器設計",
     "電子機器・無線機器・電動システム","CE認証・FCC認証・医療機器規格",
     "放射エミッションと伝導エミッションのどちらが問題か？接地設計は適切か？","後付けシールド",
     "EMC,電磁両立性,シールド設計,フィルタ,PCBレイアウト",
     "EMC,electromagnetic compatibility,shielding,filter,PCB layout",
     "active","primary",88,9,
     "https://www.iec.ch/emc/","グローバル",0.9,
     "$$\\text{SE} = 20\\log_{10}\\frac{E_0}{E_t} \\text{ (shielding effectiveness [dB])}$$",
     "url_present"),

    ("mech_b2_040","フレキシブルエレクトロニクス機械設計","Flexible Electronics Mechanical Design","Flexible Electronics Design",
     "曲げ・伸縮する基板上に構築する電子デバイスの力学設計。Serpentineパターン・島-橋構造・可逆変形の設計が核心。",
     "スマートスキン・ウェアラブル医療モニタ・折り畳みスマートフォンの実現に向け、機械工学と電子工学の融合が急速に進んでいる。",
     "機械工学","マイクロ・ナノ工学",2006,None,"設計原則","ウェアラブル・フレキシブルデバイス",
     "変形が必要な電子デバイス","スマートスキン・ウェアラブルヘルスモニタ・折りたたみディスプレイ",
     "最小曲げ半径での歪みは許容値以下か？繰り返し変形への耐久性は？","剛体PCB",
     "フレキシブルエレクトロニクス,蛇行パターン,島橋構造,伸縮電極",
     "flexible electronics,serpentine pattern,island-bridge,stretchable electrode",
     "active","secondary",83,7,
     "https://doi.org/10.1038/s41586-019-1806-7","グローバル",0.9,
     "$$\\varepsilon_{max} = \\frac{t}{2R} \\text{ (beam bending)}, \\quad \\varepsilon_{serpentine} \\approx 0.05 \\ll \\varepsilon_{Si,fail} \\approx 1\\%$$",
     "url_present"),

    ("mech_b2_041","工業デザイン・形状設計","Industrial Design and Form Design","Industrial Design",
     "製品の外観・使いやすさ・ブランド性を工学的制約の中で実現する工業デザインの方法論。CAD曲面設計・KANSEIエンジニアリングが主要手法。",
     "アップル・ダイソン・ソニーのデザイン主導製品がプレミアム市場を席巻し、機能と審美性の統合がプロダクト競争力の核心となった。",
     "機械工学","工業デザイン",1919,None,"設計原則","製品企画・設計",
     "消費者向け製品・ブランド競合が激しい市場","家電・自動車内装・スマートフォン",
     "製造コストと意匠の自由度のトレードオフは？ユーザーテストは実施したか？","機能優先設計",
     "工業デザイン,KANSEI工学,曲面設計,Class-A,CMF",
     "industrial design,Kansei engineering,surface design,Class-A,CMF",
     "active","primary",88,9,
     "https://www.jida.or.jp/","グローバル",0.9,
     "$$\\text{Kansei: } Y = f(X_1, ..., X_n) \\text{ (design parameters → sensory evaluation regression)}$$",
     "url_present"),

    ("mech_b2_042","エネルギー貯蔵システム設計","Energy Storage System Design","Energy Storage Design",
     "リチウムイオン電池・全固体電池・フライホイール・圧縮空気・揚水発電などのエネルギー貯蔵システムの機械・電気設計。",
     "再生可能エネルギーの間欠性を補う系統安定化と、EV・ドローン・宇宙機の電源として社会インフラの変革を支えている。",
     "機械工学","エネルギー工学",2000,None,"設計・最適化技法","エネルギーシステム",
     "再生可能エネルギー統合・EV・バックアップ電源","グリッドスケールBESS・EV電池パック・UPS",
     "サイクル劣化速度は？熱暴走（サーマルランアウェイ）対策は？","発電機のみ",
     "エネルギー貯蔵,BESS,全固体電池,フライホイール,熱管理",
     "energy storage,BESS,solid-state battery,flywheel,thermal management",
     "active","secondary",87,8,
     "https://doi.org/10.1016/j.rser.2022.112830","グローバル",0.9,
     "$$E = QV = C_{total} \\cdot V^2 / 2, \\quad \\text{energy density} \\propto \\frac{\\Delta G_{rxn}}{M_{electrode}}$$",
     "url_present"),

    ("mech_b2_043","大型宇宙構造物設計","Large Space Structure Design","Large Space Structure",
     "軌道上で展開・組み立てる大型太陽電池アレイ・アンテナ・居住モジュールの設計技法。軽量化・収納展開・熱変形制御が核心。",
     "ISS・新型宇宙ステーション・SpaceX Starshipなどの宇宙インフラ整備が加速し、大型宇宙構造の設計需要が急拡大している。",
     "機械工学","宇宙構造工学",1980,None,"設計・最適化技法","宇宙システム設計",
     "軌道上で展開する大型構造物","太陽電池パドル・大型アンテナ・太陽帆",
     "展開信頼性は？熱サイクルによる寸法安定性は？","地上固定構造物",
     "大型宇宙構造,太陽電池パドル,展開機構,熱変形,軌道上組立",
     "large space structure,solar paddle,deployable mechanism,thermal distortion,orbital assembly",
     "active","primary",85,7,
     "https://www.nasa.gov/centers-and-facilities/langley/in-space-assembly/","グローバル",0.9,
     "$$\\delta_{thermal} = \\alpha L \\Delta T, \\quad f_n = \\frac{1}{2\\pi}\\sqrt{EI/\\rho A L^4} \\text{ (beam in orbit)}$$",
     "url_present"),

    ("mech_b2_044","医療機器設計規制","Medical Device Design Regulation","Medical Device Regulation",
     "FDA QSR 21 CFR 820・EU MDR 2017/745・JIS T 14971（リスクマネジメント）に適合した医療機器の設計・検証・承認プロセス。",
     "市場拡大するウェアラブル医療機器・AIデバイスに対してFDA・PMDAの規制強化が進み、設計管理とリスクマネジメントの統合が求められている。",
     "機械工学","医療機器工学",1990,None,"設計原則","医療機器規制対応",
     "医療機器（クラスI〜III）の設計","FDA510(k)・PMA・CEマーキング取得",
     "リスク分析（ISO 14971）は実施したか？臨床データの要求レベルは？","一般消費財設計",
     "医療機器設計,FDA,MDR,ISO14971,DHF",
     "medical device design,FDA,MDR,ISO14971,design history file",
     "active","primary",90,9,
     "https://www.fda.gov/medical-devices/device-advice-comprehensive-regulatory-assistance","グローバル",0.9,
     "$$\\text{Risk} = P(harm) \\times S(harm), \\quad \\text{Residual risk acceptable iff} < \\text{threshold}$$",
     "url_present"),

    ("mech_b2_045","爆発・衝撃工学","Explosion and Shock Engineering","Explosion and Shock",
     "爆発・弾丸衝突・構造衝撃の力学的挙動を解析・防護設計する技法。ハギオニオ状態方程式・SPH・LSDYNAが主要手法。",
     "防衛・原子力格納容器・建築物テロ対策・自動車クラッシュなどの安全設計に不可欠な衝撃・爆発力学の工学体系。",
     "機械工学","衝撃・爆発力学",1940,None,"理論・アルゴリズム","防護・安全構造設計",
     "爆発荷重・高速衝突・構造衝撃が作用する設計","装甲・格納容器・橋梁防護・クラッシュ",
     "材料の高ひずみ速度特性データはあるか？衝撃圧力の持続時間は？","静荷重設計",
     "爆発工学,衝撃工学,高ひずみ速度,SPH,Hugoniot",
     "blast engineering,shock engineering,high strain rate,SPH,Hugoniot",
     "active","primary",85,7,
     "https://doi.org/10.1016/j.ijimpeng.2009.02.007","グローバル",0.9,
     "$$p - p_0 = \\frac{\\rho_0 c_0 u_p}{1 - s u_p / c_0} \\text{ (Hugoniot EOS)}$$",
     "url_present"),

    ("mech_b2_046","水中音響・ソナー設計","Underwater Acoustics and Sonar Design","Underwater Acoustics",
     "水中における音波の伝播・散乱・吸収を利用したソナー（パッシブ・アクティブ）の設計と海洋音響学の工学応用体系。",
     "潜水艦探知・海洋探査・鯨類生態調査・水中ロボット誘導に不可欠で、海底資源探査や気候変動モニタリングでも活用される。",
     "機械工学","音響・海洋工学",1912,None,"実装技法","海中システム設計",
     "水中音波通信・探知・探査","潜水艦探知・魚群探知・海底マッピング",
     "多重伝播路（レイ軌跡）の複雑さは？バックグラウンドノイズは？","電磁波（水中では無効）",
     "水中音響,ソナー,レイ追跡,ビームフォーミング,音響ドップラー",
     "underwater acoustics,sonar,ray tracing,beamforming,acoustic Doppler",
     "active","primary",85,7,
     "https://dosits.org/","グローバル",0.9,
     "$$c_{water} \\approx 1500 + 4.6T - 0.055T^2 + 0.0003T^3 + 1.39(S-35) + 0.017z$$",
     "url_present"),

    ("mech_b2_047","ガスタービン燃焼不安定性制御","Combustion Instability Control in Gas Turbines","Combustion Instability Control",
     "プレミックス燃焼器で発生する圧力振動（サーモアコースティック不安定）を検知・制御する技法。レイリー基準が理論的基盤。",
     "低NOx燃焼器（リーンプレミックス）の実用化に必須の課題であり、能動制御と受動的ダンパー設計が主要解決アプローチ。",
     "機械工学","燃焼・音響工学",1970,None,"設計原則","ガスタービン設計",
     "低NOxリーンプレミックス燃焼器","ガスタービン・航空エンジン燃焼器",
     "ニュートラル安定性の余裕は？フィードバック制御の実装は可能か？","拡散燃焼器（NOx高）",
     "燃焼不安定性,サーモアコースティック,レイリー基準,燃焼振動",
     "combustion instability,thermoacoustic,Rayleigh criterion,combustion oscillation",
     "active","primary",87,7,
     "https://doi.org/10.1017/CBO9780511800214","グローバル",0.9,
     "$$\\oint p'(x,t) \\dot{q}'(x,t) \\, dt > 0 \\Rightarrow \\text{unstable (Rayleigh criterion)}$$",
     "url_present"),

    ("mech_b2_048","極低温工学","Cryogenic Engineering","Cryogenic Engineering",
     "液体窒素（77K）以下の極低温環境での材料・機器・システムの設計・運転技術。LNG・超電導・宇宙推進の基盤。",
     "液体水素推進（ロケット）・超電導送電・MRI冷却・量子コンピュータ冷却で不可欠となり、水素社会実現の核心技術として重要性が増している。",
     "機械工学","低温工学",1908,None,"実装技法","低温システム設計",
     "極低温が必要なシステム（<-150℃）","液体水素タンク・超電導モータ・MRI・量子冷却",
     "熱侵入量（断熱性能）は十分か？ボイルオフ率は許容できるか？","常温設計",
     "極低温工学,液体水素,超電導,パラ水素,断熱設計",
     "cryogenic engineering,liquid hydrogen,superconducting,para-hydrogen,insulation design",
     "active","primary",88,7,
     "https://doi.org/10.1016/j.cryogenics.2019.103040","グローバル",0.9,
     "$$\\dot{Q}_{boiloff} = \\frac{k A \\Delta T}{L} \\text{ (conduction)}, \\quad \\text{MLI: } k_{eff} < 0.001 \\text{ W/m/K}$$",
     "url_present"),

    ("mech_b2_049","風力タービン構造設計","Wind Turbine Structural Design","Wind Turbine Structure",
     "風力タービンブレード・タワー・基礎の構造強度・疲労・バックリングを設計・検証する技法。IEC 61400規格が国際標準。",
     "洋上風力の大型化（15-20MW級・羽根長100m超）に伴い、CFRP材料・疲労設計・荷重計測の高度化が業界の最前線となっている。",
     "機械工学","再生可能エネルギー工学",1990,None,"設計原則","風力発電設計",
     "風力タービン設計・型式認証","ブレード強度・タワー疲労・基礎沈下",
     "DLC（設計荷重ケース）の網羅性は？疲労安全係数は規格に適合しているか？","建築構造設計",
     "風力タービン構造,IEC61400,ブレード設計,DLC,疲労安全係数",
     "wind turbine structure,IEC61400,blade design,DLC,fatigue safety factor",
     "active","primary",88,8,
     "https://www.iec.ch/dyn/www/f?p=103:7:0::::FSP_ORG_ID:1376","グローバル",0.9,
     "$$M_{blade,root} = \\int_0^R \\left(\\frac{1}{2}\\rho c(r) V_{rel}^2 C_l r\\right) dr, \\quad \\text{DLC 1.1: normal operation}$$",
     "url_present"),

    ("mech_b2_050","熱エラストマー設計","Elastomer and Rubber Design","Elastomer Design",
     "ゴム・シリコーン・熱可塑性エラストマー（TPE）の非線形弾性・クリープ・疲労・耐環境性を設計する材料工学的手法。",
     "自動車タイヤ・シール・防振・医療チューブに不可欠で、超弾性材料の数値解析（Mooney-Rivlinモデル）が設計の精度を支えている。",
     "機械工学","高分子・ゴム材料工学",1940,None,"設計原則","ゴム・エラストマー設計",
     "大変形・弾性回復・耐環境性が必要","タイヤ・Oリング・防振マウント・医療チューブ",
     "圧縮永久ひずみ（CS）の許容値は？温度範囲での硬度変化は？","金属ばね",
     "エラストマー設計,Mooney-Rivlin,超弾性,ゴム疲労,Oリング",
     "elastomer design,Mooney-Rivlin,hyperelastic,rubber fatigue,O-ring",
     "active","primary",85,9,
     "https://doi.org/10.1016/j.ijsolstr.2021.111166","グローバル",0.9,
     "$$W = C_{10}(I_1-3) + C_{01}(I_2-3) \\text{ (Mooney-Rivlin strain energy)}$$",
     "url_present"),
]

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

if __name__ == "__main__":
    ins, sk = insert_records(RECORDS)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Inserted: {ins}, Skipped: {sk}")
    print(f"Total: {total}")
