#!/usr/bin/env python3
"""engineering_method batch insert — 材料工学・ナノテク Batch 5 (mat_b5_001–050)"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("mat_b5_001","コールドスプレー成膜法","Cold Spray Deposition","Cold Spray / Kinetic Spray","固体粒子を超音速ガス流で加速し、基材への運動エネルギーのみで皮膜を形成するプロセス。熱的損傷ゼロで酸化皮膜も形成しない。","航空宇宙・自動車の耐摩耗・腐食保護皮膜。Cu/Alの電気接点修復にも使用。","材料工学・ナノテク","材料プロセス工学","1990",None,"プロセス手法","金属皮膜","粒子速度300–1200m/s, Tp<Tmの条件","耐酸化性重視・熱歪み回避コーティング","なぜ粒子は熱を加えずに結合するか","溶射・PVD","コールドスプレー,動的噴射,皮膜形成,固相接合","cold spray,kinetic spray,coating,solid state bonding","active","secondary",85,7,"https://www.asminternational.org/web/guests/home?p_p_id=com_liferay_portal_search_web_portlet_SearchPortlet","グローバル",0.7,r"Particle bonding criterion: $v_p > v_{cr} \approx \sqrt{\frac{4\sigma_y}{\rho}}$, where $v_{cr}$ typical 300–900 m/s","url_present"),

("mat_b5_002","高エントロピー合金設計","High-Entropy Alloy Design","HEA / Multi-Principal Element Alloy","5種以上の主成分元素を等モル比近傍で配合し、単一固溶体相を安定化させる合金設計原理。CALPHAD+機械学習で組成最適化。","極低温から高温まで優れた機械的特性・腐食耐性。次世代航空エンジン材料候補。","材料工学・ナノテク","計算材料工学","2004",None,"材料設計","構造材料","固溶体安定条件: ΔSmix≥1.5R, δ<6.6%","高性能多機能材料設計","エントロピー安定化のメカニズムは何か","従来合金","高エントロピー合金,多主成分合金,固溶体,CALPHAD","HEA,multi-principal element alloy,solid solution,entropy stabilization","active","primary",90,6,"https://doi.org/10.1002/adem.200300567","グローバル",0.85,r"Configurational entropy: $\Delta S_{mix} = -R\sum_{i=1}^{n} x_i \ln x_i$, max at equimolar ($n=5$: $\Delta S=1.61R$)","url_present"),

("mat_b5_003","超臨界流体抽出・分散","Supercritical Fluid Processing","SCF Processing / scCO₂ Impregnation","CO₂等の超臨界流体（Tc=31.1°C, Pc=7.38MPa）を利用し、ナノ粒子分散・多孔体作製・薬剤含浸を行う手法。","ゼロ溶媒残留の薬剤担持・航空機CFRP前駆体含浸に応用。","材料工学・ナノテク","グリーンケミストリー","1980",None,"プロセス手法","多孔体・複合材","T>Tc, P>Pc の超臨界条件","溶媒残留ゼロを要求する医薬・食品グレード製品","なぜ超臨界CO₂は固体を膨潤させるか","有機溶媒抽出","超臨界流体,CO₂,多孔体,薬剤含浸,ナノ分散","supercritical fluid,CO₂,aerogel,drug loading,nano dispersion","active","secondary",80,7,"https://doi.org/10.1039/c3gc41037k","グローバル",0.75,r"Solubility parameter: $\delta_{sc} \approx 1.25 \rho_{sc}^{1/2}$ MPa$^{1/2}$; density at 10 MPa, 40°C: $\rho \approx 700$ kg/m³","url_present"),

("mat_b5_004","マイクロ波焼結法","Microwave Sintering","Microwave-Assisted Sintering","2.45GHzマイクロ波を材料内部で直接吸収させ均一加熱・急速焼結を実現する手法。従来焼結より昇温速度100倍以上。","WC/Coセメンタイト、Al₂O₃セラミクスの微細組織制御。エネルギー消費75%削減。","材料工学・ナノテク","材料プロセス工学","1975",None,"プロセス手法","セラミクス・粉末冶金","マイクロ波透過性材料,高周波炉設備","微細結晶粒・高密度を短時間で達成したい場合","材料が均一にマイクロ波を吸収できる条件は","通常電気炉焼結","マイクロ波焼結,均一加熱,急速焼結,セラミクス","microwave sintering,rapid sintering,uniform heating,ceramics","active","secondary",80,7,"https://doi.org/10.1111/j.1551-2916.2008.02327.x","グローバル",0.75,r"Power density: $P = \sigma |E|^2 = 2\pi f \varepsilon_0 \varepsilon'' |E|^2$; skin depth $\delta_s = (2/\mu\sigma\omega)^{1/2}$","url_present"),

("mat_b5_005","自己治癒ポリマー材料","Self-Healing Polymer","Intrinsic / Extrinsic Self-Healing","ダメージ発生時に自律的に修復する機能を持つポリマー。内包マイクロカプセル型と可逆共有結合型（DA反応など）に分類。","コーティング・軟ロボット・電子皮膚への応用。寿命延長と環境負荷低減。","材料工学・ナノテク","スマート材料","2001",None,"材料設計","スマートポリマー","可逆結合形成能 or マイクロカプセル含有","長期信頼性・自律メンテナンスが必要な用途","修復反応は熱力学的に自発的か","従来修理依存材料","自己治癒,スマートポリマー,マイクロカプセル,DA反応","self-healing polymer,microcapsule,Diels-Alder,covalent adaptation","active","primary",85,6,"https://doi.org/10.1038/nature01390","グローバル",0.8,r"DA equilibrium: $\Delta G = \Delta H - T\Delta S$; retro-DA onset $T\sim 120$°C for typical furan-maleimide pairs","url_present"),

("mat_b5_006","日本NIMS材料DB・情報統合","NIMS Materials Database InfoMat","NIMS AtomWork / NIMS MatNavi","物質・材料研究機構(NIMS)が構築・公開する世界最大級の材料データベース群。結晶構造・相図・機械特性を国際標準形式で提供。","国際材料インフォマティクスの基盤インフラ。MPDSやMaterials Projectと相互参照。","材料工学・ナノテク","材料インフォマティクス","1998",None,"情報基盤","材料データ管理","オープンデータ政策,FAIR原則への準拠","材料設計の出発点として系統的データが必要な場合","どの組成空間を優先探索すべきか","文献分散情報","NIMS,材料DB,AtomWork,MatNavi,インフォマティクス","NIMS,materials database,AtomWork,MatNavi,informatics","active","primary",90,9,"https://mits.nims.go.jp/","東アジア",0.98,r"Database coverage: $>$350,000 phase diagrams; $>$60,000 crystal structures; API endpoint: \texttt{https://mits.nims.go.jp/api/v2/}","url_present"),

("mat_b5_007","中国C/C複合材高温焼成","China C/C Composite High-Temp Sintering","C/C Composite Processing China","中国航空宇宙・核融合向けに開発された炭素繊維強化炭素複合材（C/C）の高温CVD焼成・機械加工技術。HT処理2800°Cまで。","J-20戦闘機ブレーキ・DF-41ミサイルノズル・ITER第一壁への応用。","材料工学・ナノテク","高温材料工学","1990",None,"プロセス手法","高温構造材料","CVD炉,温度>2000°C,不活性雰囲気","極高温・再突入熱防護が必要な航空宇宙部品","C/C材の酸化保護コーティングはどう機能するか","C/SiC複合材","C/C複合材,炭素繊維,CVD,高温構造","C/C composite,carbon fiber,CVD,high temperature structure","active","secondary",85,8,"https://www.sciencedirect.com/science/article/pii/S0008622321009933","東アジア",0.9,r"CVI rate: $\dot{r}_{dep} = k_0 \exp(-E_a/RT) \cdot p_{CH_4}^n$; typical $E_a \sim 150$ kJ/mol","url_present"),

("mat_b5_008","韓国2D材料・MoS₂電子デバイス","Korea 2D Material MoS₂ Electronics","Monolayer MoS₂ FET Korea","KAIST・SNU・Samsungが主導するMoS₂等遷移金属ダイカルコゲナイド(TMD)の単層成長・FET集積技術。直接バンドギャップ1.8eV。","次世代2D半導体トランジスタ。シリコン限界超えの超薄膜チャネル材料。","材料工学・ナノテク","2D材料工学","2011",None,"デバイス統合","半導体","CVD成長,転写技術,低界面欠陥密度","シリコン置換超薄膜チャネルが必要な場合","TMDの電子移動度をどう向上させるか","Graphene FET","MoS₂,TMD,2D材料,FET,直接バンドギャップ","MoS₂,TMD,2D material,FET,direct bandgap","active","primary",88,5,"https://doi.org/10.1038/nnano.2011.165","東アジア",0.92,r"Bandgap: $E_g^{bulk}=1.2$ eV (indirect) $\to$ $E_g^{ML}=1.8$ eV (direct); $\mu_e \approx 200$ cm²V⁻¹s⁻¹ in hBN-encapsulated device","url_present"),

("mat_b5_009","金属積層造形・粉末床溶融結合","Metal AM Powder Bed Fusion","SLM / LPBF / EBM","金属粉末床にレーザーまたは電子ビームを走査して局所溶融・凝固を繰り返す積層造形法。内部孔率0.1%以下が達成可能。","Ti-6Al-4V・Inconel 718・AlSi10Mgの複雑形状部品製造。トポロジー最適化設計と組み合わせて軽量化50%以上。","材料工学・ナノテク","積層造形工学","1988",None,"プロセス手法","金属部品製造","レーザー/電子ビーム設備,不活性雰囲気,精密温度制御","従来加工困難な複雑形状が必要な場合","残留応力・変形をどう予測・制御するか","鋳造・鍛造","積層造形,粉末床溶融結合,SLM,EBM,金属AM","metal AM,powder bed fusion,SLM,EBM,laser melting","active","primary",90,8,"https://doi.org/10.1016/j.pmatsci.2016.01.002","グローバル",0.85,r"Hatch overlap: $E_V = P/(v \cdot h \cdot t)$ J/mm³; porosity target $<0.1\%$ at $E_V\sim 60$–80 J/mm³ for Ti-6Al-4V","url_present"),

("mat_b5_010","台湾CoWoS先進パッケージング材料","Taiwan CoWoS Advanced Packaging Materials","CoWoS / InFO Material Stack","TSMCが主導するCoWoS（Chip-on-Wafer-on-Substrate）・InFO（Integrated Fan-Out）向け低膨張率絶縁材・Cu再配線層材料の設計技術。","AI/HPC向け2.5D/3D IC実現。帯域幅2倍・消費電力30%削減。","材料工学・ナノテク","半導体パッケージ材料","2009",None,"材料設計","半導体パッケージ","CTE≈3ppm/K の低膨張材料,高解像度フォトリソ","AIチップの高密度集積・帯域幅向上が必要な場合","CTE不一致による熱応力を最小化するには","FC-BGA従来パッケージ","CoWoS,InFO,先進パッケージング,RDL,低CTE","CoWoS,InFO,advanced packaging,RDL,low CTE material","active","primary",92,9,"https://ieeexplore.ieee.org/document/7017355","東アジア",0.98,r"Thermal stress: $\sigma_{th} = E \cdot \Delta\alpha \cdot \Delta T / (1-\nu)$; target $\Delta\alpha < 0.5$ ppm/K between die and substrate","url_present"),

("mat_b5_011","バイオインスパイアード材料設計","Bioinspired Material Design","Biomimetic Materials Engineering","自然界の生体構造（ナクレ、蜘蛛糸、ロータス効果など）を工学材料に模倣する設計手法。階層構造・自己組織化を利用。","ナクレ模倣積層複合材（靭性×3000）・蜘蛛糸模倣繊維（強度>鋼）・撥水コーティングへの応用。","材料工学・ナノテク","バイオインスパイアード工学","1990",None,"材料設計","複合材・機能性表面","生体構造の精密模倣が可能な加工技術","自然構造の特性を工業スケールで再現したい場合","どの階層スケールが性能に最も寄与するか","純工学的設計","バイオインスパイアード,生体模倣,ナクレ,蜘蛛糸,階層構造","bioinspired,biomimetic,nacre,spider silk,hierarchical structure","active","primary",85,6,"https://doi.org/10.1126/science.1059866","グローバル",0.8,r"Toughness of nacre: $G_c \approx 3000 \times$ monolithic CaCO$_3$; crack deflection energy: $\Gamma = 2\gamma + G_{platelet}$","url_present"),

("mat_b5_012","レーザー誘起前方転写（LIFT）","Laser-Induced Forward Transfer","LIFT Printing","供与基板上の薄膜材料にレーザーパルスを照射し、受容基板へ微量液滴・ソリッドヴォクセルを転写印刷する手法。","金属・生体細胞・電子インクの高分解能プリンティング。エレクトロニクス修理・バイオプリンティングに応用。","材料工学・ナノテク","プリンタブル材料","1986",None,"プロセス手法","薄膜・電子部品修理","パルスレーザー,光吸収層,1–50μm精度","ピクセル単位の高精度材料堆積","転写量の再現性をどう確保するか","インクジェット","LIFT,レーザー転写,バイオプリント,マイクロ印刷","LIFT,laser printing,bio-printing,micro deposition","active","secondary",80,6,"https://doi.org/10.1063/1.464966","グローバル",0.75,r"Threshold fluence: $F_{th} \approx \frac{\rho c_p (T_m - T_0) d}{\alpha (1-R) \tau^{1/2}}$; typical $F_{th}\sim 0.1$–1 J/cm²","url_present"),

("mat_b5_013","高分子ブレンド相溶化技術","Polymer Blend Compatibilization","Reactive Compatibilization / Block Copolymer Compatibilization","相溶性の低い2種以上のポリマーのブレンド時に界面活性剤（相溶化剤）または反応性官能基を利用して微細分散・接着力向上を実現する技術。","PA/PE・PET/PC等の廃プラスチック再生・高性能ブレンド材料の製造に不可欠。","材料工学・ナノテク","高分子材料工学","1975",None,"材料設計","高分子ブレンド","反応押出機または相溶化ブロック共重合体","非相溶ポリマーの高性能ブレンド・廃プラ再生","界面エネルギーをどう最小化するか","単一ポリマー使用","ポリマーブレンド,相溶化,反応性押出,界面張力","polymer blend,compatibilization,reactive extrusion,interfacial tension","active","secondary",85,8,"https://doi.org/10.1021/ma00044a002","グローバル",0.75,r"Interfacial tension: $\gamma_{12} = \gamma_1 + \gamma_2 - 2\phi(\gamma_1^d \gamma_2^d)^{1/2} - 2\phi(\gamma_1^p \gamma_2^p)^{1/2}$","url_present"),

("mat_b5_014","電気泳動堆積法（EPD）","Electrophoretic Deposition","EPD Coating","荷電セラミクス・ナノ粒子懸濁液に直流電場を印加し、電極上に均一薄膜を堆積させる電気化学的成膜法。","YSZ電解質膜（SOFC）・HA骨格コーティング・グラフェン薄膜の均一成膜。","材料工学・ナノテク","電気化学材料プロセス","1940",None,"プロセス手法","薄膜・コーティング","荷電粒子懸濁液,均一電場,導電性基材","複雑形状・大面積への均一薄膜堆積","堆積速度と膜質のトレードオフをどう管理するか","スパッタリング・CVD","EPD,電気泳動,薄膜,セラミクスコーティング,SOFC","EPD,electrophoretic deposition,thin film,SOFC,ceramic coating","active","secondary",80,7,"https://doi.org/10.1016/j.jeurceramsoc.2010.01.028","グローバル",0.75,r"Hamaker equation: $m = \mu \varepsilon E C A t$, yield $Y = \frac{m}{C_0 V} = \frac{\mu \varepsilon E t}{L}$","url_present"),

("mat_b5_015","磁性ナノ粒子合成・表面修飾","Magnetic Nanoparticle Synthesis & Functionalization","Fe₃O₄/γ-Fe₂O₃ MNP","共沈法・熱分解法でFe₃O₄ナノ粒子（10–20nm）を合成し、PEG・抗体・薬剤でコーティングするバイオ応用設計手法。","MRI造影剤・磁気温熱療法・薬物デリバリー・磁気分離に使用。","材料工学・ナノテク","ナノバイオ材料","1981",None,"材料設計","バイオ医療材料","Superparamagnetic条件: d<20nm、低毒性表面修飾","生体内磁気誘導・MRI造影・温熱療法","サイズと磁化率のトレードオフをどう設計するか","非磁性ナノ粒子","磁性ナノ粒子,Fe₃O₄,MRI,磁気温熱,薬物デリバリー","magnetic nanoparticle,Fe₃O₄,MRI,magnetic hyperthermia,drug delivery","active","primary",88,7,"https://doi.org/10.1021/cr068445e","グローバル",0.8,r"Blocking temperature: $T_B = \frac{K_{eff} V}{25 k_B}$; superparamagnetism at $d < d_c \approx 20$ nm for Fe₃O₄","url_present"),

("mat_b5_016","中国BOE/天馬AMOLED製造技術","China BOE/Tianma AMOLED Manufacturing","BOE OLED Flexible Panel Technology","BOE・天馬微電子が量産する低温多結晶シリコン（LTPS）-AMOLED・柔軟ディスプレイの製造技術。IJP（インクジェット印刷）有機層を開発中。","スマートフォン・折畳み端末向けOLEDパネルの国産化。中国市場占有率急拡大。","材料工学・ナノテク","ディスプレイ材料","2013",None,"製造技術","ディスプレイ","クリーンルームGen6以上,LTPS TFT,有機蒸着設備","中国国産OLEDパネル量産","発光効率と寿命のトレードオフをどう最適化するか","Samsung/LG OLED","AMOLED,LTPS,中国OLEDパネル,BOE,柔軟ディスプレイ","AMOLED,LTPS,China OLED,BOE,flexible display","active","secondary",85,8,"https://ieeexplore.ieee.org/document/9699312","東アジア",0.93,r"EL efficiency: $\eta_{EQE} = \gamma \cdot \chi \cdot q \cdot \eta_{out}$; target $\eta_{EQE} > 20\%$ for green OLED (TADF/phosphorescent)","url_present"),

("mat_b5_017","形状記憶セラミクス","Shape Memory Ceramics","ZrO₂-Based Shape Memory Ceramics","ジルコニア（ZrO₂）の正方晶→単斜晶相変態を利用した形状記憶・超弾性効果を発現するセラミクス。マルテンサイト変態を応用。","マイクロアクチュエーター・歯科矯正ワイヤー代替・熱スイッチへの応用研究段階。","材料工学・ナノテク","スマート材料","2015",None,"材料設計","アクチュエーター・ウェアラブル","ZrO₂単結晶またはオリゴクリスタル、ナノスケール拘束","高温環境でのセラミクスアクチュエーター","ポリクリスタルで亀裂破壊を避けるには","形状記憶合金(SMA)","形状記憶セラミクス,ジルコニア,超弾性,相変態","shape memory ceramic,zirconia,superelasticity,martensitic transformation","active","primary",75,4,"https://doi.org/10.1126/science.aaf2403","グローバル",0.8,r"Transformation strain: $\varepsilon_{tr} \approx 1\%$ for ZrO₂ (tetragonal$\to$monoclinic); energy stored: $W = \int \sigma\, d\varepsilon_{tr}$","url_present"),

("mat_b5_018","日本JFEスチール方向性電磁鋼板","JFE/Nippon Steel Grain-Oriented Electrical Steel","Hi-B Grain-Oriented Silicon Steel","JFEスチールが量産するHi-B方向性電磁鋼板（Fe-3%Si）。Goss方位{110}<001>集合組織を精密制御し鉄損を最小化。","変圧器鉄心の省エネ化。IEC基準B等級で鉄損W17/50≦0.80W/kg達成。エコデザイン規制対応。","材料工学・ナノテク","電磁材料工学","1934",None,"製造技術","電力インフラ","Goss集合組織形成の冷延・焼鈍制御","変圧器・モーターコア低損失化","方位選択度をどう定量的に評価するか","無方向性電磁鋼板","方向性電磁鋼板,Goss集合組織,鉄損,変圧器,省エネ","grain-oriented steel,Goss texture,iron loss,transformer,energy saving","active","primary",92,9,"https://www.jfe-steel.co.jp/en/research/report/index.html","東アジア",0.97,r"Core loss: $W = W_{hys} + W_{eddy} = k_h f B^n + k_e (f t B)^2$; Hi-B target $W_{17/50} \leq 0.80$ W/kg","url_present"),

("mat_b5_019","配向成長薄膜・エピタキシャル酸化物","Epitaxial Oxide Thin Film Growth","PLD / MBE Epitaxial Oxide","パルスレーザー堆積法（PLD）または分子線エピタキシー（MBE）を用い、原子層精度で機能性酸化物（LaMnO₃, BaTiO₃等）のエピタキシャル薄膜を成長させる技術。","強誘電・強磁性・超電導酸化物の界面新機能研究。MottoRicercaのコンデンサ・スピントロニクスデバイスへの応用。","材料工学・ナノテク","薄膜エピタキシー","1965",None,"実験技術","機能性薄膜・デバイス","UHV(<10⁻⁸Torr),ターゲット材,格子整合基板","酸化物デバイス・界面物性研究","基板との格子不整合はどう薄膜特性に影響するか","スパッタリング成膜","エピタキシャル,酸化物薄膜,PLD,MBE,強誘電体","epitaxial oxide,PLD,MBE,ferroelectric,perovskite film","active","primary",87,5,"https://doi.org/10.1038/nmat3223","グローバル",0.8,r"Misfit strain: $\varepsilon_m = (a_s - a_f)/a_f$; critical thickness $h_c \approx \frac{b(1-\nu\cos^2\theta)}{8\pi f(1+\nu)\sin\theta}\ln(h_c/b)$ (Matthews-Blakeslee)","url_present"),

("mat_b5_020","カーボンナノチューブ配向制御","Aligned CNT Growth & Integration","Vertically Aligned CNT / CNT Forest","化学気相成長（CVD）法でFe/Al₂O₃触媒パターンから垂直配向カーボンナノチューブ（VA-CNT）を成長させ、熱界面材料・電極として統合する技術。","熱伝導率>1000W/mK・比表面積>1000m²/g。ヒートシンク・スーパーキャパシタ電極に応用。","材料工学・ナノテク","カーボンナノ材料","1991",None,"プロセス手法","熱管理・エネルギー材料","CVD炉,Fe触媒,C₂H₂/H₂ガス","高放熱・高比表面積が必要なデバイス","CNTと基板の熱・電気接触抵抗をどう最小化するか","グラファイト放熱材","CNT,垂直配向,CNTフォレスト,熱界面材料,スーパーキャパシタ","aligned CNT,CNT forest,thermal interface material,supercapacitor","active","primary",85,7,"https://doi.org/10.1038/35065525","グローバル",0.8,r"Thermal conductivity of individual MWCNT: $\kappa \approx 3000$ W m⁻¹K⁻¹; effective $\kappa_{eff}$ of array: 10–100 W m⁻¹K⁻¹","url_present"),

("mat_b5_021","液体金属・ガリウム合金エレクトロニクス","Liquid Metal Gallium Electronics","EGaIn / Galinstan Soft Electronics","室温液体のEGaIn（Ga-In共晶）やGalinstan（Ga-In-Sn）を伸縮性配線・軟ロボットアクチュエーターに利用する材料技術。","ウェアラブルセンサー・軟ロボット・自己修復配線に応用。伸び率600%でも導電性維持。","材料工学・ナノテク","ソフトマテリアル","2008",None,"材料設計","ウェアラブル・ソフトロボット","マイクロ流路,表面酸化制御(Ga₂O₃)","大変形に対応した導電経路設計","表面酸化膜の形成をどう利用・抑制するか","固体金属配線","液体金属,ガリウム合金,EGaIn,伸縮配線,ソフトロボット","liquid metal,EGaIn,Galinstan,stretchable conductor,soft robotics","active","primary",82,6,"https://doi.org/10.1002/adma.200702364","グローバル",0.8,r"Conductivity of EGaIn: $\sigma \approx 3.4\times10^4$ S/cm; surface tension $\gamma \approx 624$ mN/m (Ga₂O₃ skin)","url_present"),

("mat_b5_022","中国超高圧合成ダイヤモンド工具","China HPHT Diamond Tool Manufacturing","HPHT Synthetic Diamond China","中国が世界シェア約90%を占める高圧高温（HPHT）合成ダイヤモンド・CBN（立方晶窒化ホウ素）の量産技術と工具成形技術。","半導体・宝石・石材加工用超砥粒工具の世界供給。日系ダイヤモンド工具市場に代替圧力。","材料工学・ナノテク","超硬工具材料","1963",None,"製造技術","超硬工具","5–6GPa, 1300–1600°C HPHT装置","切削・研磨用超硬工具の低コスト量産","焼結助剤（Co/Ni/SiC）が硬度と耐熱性に与える影響は","天然ダイヤモンド","HPHT,合成ダイヤモンド,CBN,超砥粒工具,中国生産","HPHT,synthetic diamond,CBN,superabrasive,China production","active","secondary",88,9,"https://doi.org/10.1016/j.diamond.2020.107937","東アジア",0.92,r"Graphite-diamond transition: $P_{eq}(T) = 2.73 + 0.027 T$ GPa ($T$ in K); hardness $H_v \approx 90$ GPa (diamond)","url_present"),

("mat_b5_023","ナノインプリントリソグラフィ（NIL）","Nanoimprint Lithography","NIL / T-NIL / UV-NIL","ハードモールドをポリマー薄膜に押し付けて10nm以下のパターンを転写するリソグラフィ技術。電子ビーム描画より1000倍高速。","HDD磁気記録パターン・フォトニックデバイス・量子ドット LED製造に応用。","材料工学・ナノテク","ナノ製造技術","1995",None,"製造技術","半導体・光学デバイス","平坦基板,ナノモールド,<5nm位置精度","EUV代替・大面積ナノパターニングが必要な場合","モールド離型と欠陥密度の管理方法は","フォトリソグラフィ","ナノインプリント,NIL,ナノパターニング,フォトニクス","nanoimprint lithography,NIL,nano patterning,photonics","active","primary",85,7,"https://doi.org/10.1126/science.272.5258.85","グローバル",0.82,r"Pattern transfer pressure: $P_{NIL} \approx 40$–100 bar; residual layer thickness $t_{RLT} = t_0 - \sqrt{t_0^2 - t_f^2}$ (continuity approx.)","url_present"),

("mat_b5_024","原子層エッチング（ALE）","Atomic Layer Etching","ALE / Digital Etching","反応ガスの自己停止吸着と低エネルギーイオン照射を交互に繰り返し、原子層単位で制御されたエッチングを実現する技術。","5nm以下FinFET・GAA-FETの精密加工。ALD（原子層堆積）の逆プロセスとして対称的技術。","材料工学・ナノテク","ナノ加工技術","2004",None,"製造技術","半導体ナノ加工","プラズマ装置,自己停止吸着ガス,低エネルギーイオン","原子層精度の等方・異方性エッチングが必要な場合","ALE選択性と材料ダメージのバランスは","RIEドライエッチング","ALE,原子層エッチング,半導体,GAA-FET,ナノ加工","ALE,atomic layer etching,semiconductor,GAA-FET,plasma etching","active","primary",88,7,"https://doi.org/10.1116/1.4913379","グローバル",0.82,r"Etch per cycle: $\Delta t_{cycle} = \frac{2n_s m_{atom}}{J_{ion} Y_{sputter}}$; self-limiting condition: $E_{ion} < E_{sp}^{bulk}$ but $> E_{sp}^{modified}$","url_present"),

("mat_b5_025","磁気冷凍材料・MCE材料","Magnetocaloric Materials","Magnetocaloric Effect / MCE Material","磁場の印加・除去により等温エントロピー変化・断熱温度変化が生じる磁気熱量効果（MCE）を利用した固体冷凍材料。","フロン代替の環境負荷ゼロ冷凍。室温付近でΔTad>2K/Tが目標。Gd合金が代表材料。","材料工学・ナノテク","磁性材料工学","1976",None,"材料設計","冷凍・空調","強い1次・2次磁気相転移, 低磁気ヒステリシス","フロンフリー固体冷凍システム","ヒステリシスロスをどう最小化するか","ガス圧縮冷凍","磁気冷凍,MCE,磁気熱量効果,Gd合金,固体冷凍","magnetocaloric,MCE,solid state cooling,Gd alloy,refrigeration","active","primary",80,5,"https://doi.org/10.1016/j.jmmm.2005.01.008","グローバル",0.8,r"$\Delta T_{ad} = -\frac{T}{C_H}\left(\frac{\partial M}{\partial T}\right)_H \Delta H$; Maxwell relation: $\Delta S_M = \int_0^H\left(\frac{\partial M}{\partial T}\right)_H dH$","url_present"),

("mat_b5_026","固体電解質・全固体電池設計","Solid Electrolyte Design for All-Solid-State Battery","SSB Solid Electrolyte: LLZO / LGPS / Li₃PS₄","Li₇La₃Zr₂O₁₂（LLZO）・Li₁₀GeP₂S₁₂（LGPS）等の固体電解質を用いた全固体リチウム電池の設計。イオン伝導率目標>10⁻³S/cm。","液体電解液電池の安全問題を解消。EVへの次世代電池。トヨタ・Samsung・QuantumScapeが開発中。","材料工学・ナノテク","電気化学材料","2011",None,"材料設計","エネルギー貯蔵","イオン伝導率>1mS/cm,低界面抵抗,Li金属負極相溶性","次世代高安全・高エネルギー密度電池","固体電解質/電極界面抵抗をどう低減するか","液体電解質電池","全固体電池,固体電解質,LLZO,LGPS,Liイオン","all-solid-state battery,solid electrolyte,LLZO,LGPS,lithium battery","active","primary",85,7,"https://doi.org/10.1038/nmat3066","グローバル",0.85,r"Ionic conductivity: $\sigma_i = \frac{n_i z_i^2 e^2 D_i}{k_B T}$ (Nernst-Einstein); LGPS: $\sigma \approx 12$ mS/cm at 27°C","url_present"),

("mat_b5_027","韓国LGエナジー・三星SDIリチウム電池陰極材","Korea LG/Samsung SDI Anode Material","Si-C Composite Anode Korea","韓国LGエナジーソリューション・三星SDIが量産するSi-C複合負極材（Si:C=10–20:80–90）。シリコン膨張をナノ構造で抑制。","エネルギー密度300Wh/kg超のEV電池実現。理論容量Si:3579mAh/g対C:372mAh/g。","材料工学・ナノテク","電気化学材料","2017",None,"材料設計","EV電池","ナノSi-Cコンポジット,SEI安定化,バインダー設計","高エネルギー密度EV電池負極材","サイクル中の体積変化(300%)をどう吸収するか","黒鉛負極","Si-C複合負極,リチウムイオン電池,EV,シリコン膨張","Si-C composite anode,lithium battery,EV,silicon expansion","active","primary",90,8,"https://doi.org/10.1038/s41586-021-03819-6","東アジア",0.93,r"Volume expansion: $\Delta V/V_{Li_{15}Si_4} \approx 280\%$; composite stress: $\sigma = E_{eff}\varepsilon$; target cycle life $>$1000 at 80% SOH","url_present"),

("mat_b5_028","グリーン水素製造用光触媒材料","Photocatalyst for Green Hydrogen Production","Photocatalytic Water Splitting","可視光吸収半導体（GaN:ZnO, BaTaO₂N等）と助触媒（Rh, Pt）を組み合わせ、太陽光で水分解してH₂を製造する光触媒系の材料設計。","2030年水素コスト目標120円/Nm³に向けた太陽光H₂製造。HEKETは量子収率56%達成（355nm照射）。","材料工学・ナノテク","エネルギー材料","1972",None,"材料設計","エネルギー変換","バンドギャップ1.8–2.2eV, ストラドリング型バンド位置","太陽光直接水素製造","電荷再結合をどう抑制するか","電解水素","光触媒,水分解,水素製造,半導体,バンドギャップ","photocatalysis,water splitting,hydrogen,semiconductor,bandgap engineering","active","primary",82,6,"https://doi.org/10.1038/nmat3151","グローバル",0.82,r"Efficiency: $\eta_{STH} = \frac{\dot{n}_{H_2} \cdot \Delta G_{H_2O}}{P_{solar} \cdot A}$; Honda-Fujishima: $E_g \geq 1.23$ eV + overpotential correction","url_present"),

("mat_b5_029","セラミクス射出成形（CIM）","Ceramic Injection Molding","CIM / Powder Injection Molding","熱可塑性バインダーに混練したセラミクス粉末を射出成形し、脱脂・焼結で複雑形状部品を得る粉末加工技術。","歯科ジルコニアクラウン・自動車酸素センサー・スマートフォンジルコニアバックパネルの量産。","材料工学・ナノテク","セラミクス加工","1979",None,"製造技術","精密セラミクス部品","射出成形機,高充填粉末(50–65vol%),脱脂炉","複雑形状・小型精密セラミクス部品の量産","脱脂・焼結時の寸法変化をどう管理するか","プレス成形","CIM,セラミクス射出成形,ジルコニア,粉末加工","CIM,ceramic injection molding,zirconia,powder processing","active","secondary",88,9,"https://doi.org/10.1111/jace.14752","グローバル",0.8,r"Solids loading: $\phi_{solids} \approx 0.64\phi_{max}$ for optimum viscosity; shrinkage: $\Delta L/L_0 = 1 - (\phi_{green}/\phi_{sinter})^{1/3}$","url_present"),

("mat_b5_030","日本信越化学・東ソーZigma塩化ビニル材料","Shin-Etsu/Tosoh PVC & Silicone Materials","Shin-Etsu PVC / Silicone Engineering","信越化学工業・東ソーが世界トップシェアを持つポリ塩化ビニル（PVC）・シリコーン樹脂の高純度合成・配合設計技術。","建材・医療チューブ・電気絶縁材のグローバル供給。信越化学シリコーン世界シェア>30%。","材料工学・ナノテク","高分子材料工学","1926",None,"製造技術","化学材料","高純度モノマー,懸濁/乳化重合,Ziegler-Natta触媒","PVC・シリコーン高機能グレード材料の開発","可塑剤の長期移行・環境問題をどう技術的に解決するか","他汎用樹脂","PVC,シリコーン,信越化学,配合設計,高純度重合","PVC,silicone,Shin-Etsu,compounding,suspension polymerization","active","primary",92,9,"https://www.shinetsu.co.jp/en/ir/","東アジア",0.95,r"PVC degree of polymerization: $DP = \bar{M}_n/M_0$; free radical termination: $k_t[\text{M}^\bullet]^2$ dominates chain length","url_present"),

("mat_b5_031","マルチフェロイック複合材料","Multiferroic Composite Materials","Magnetoelectric Multiferroic Composites","圧電体（BaTiO₃/PZT）と磁歪材料（Terfenol-D/NiFe₂O₄）を積層・複合化し、磁場-電場相互変換（ME効果）を強化した複合材料。","磁気センサー・エネルギーハーベスター・次世代MRAMへの応用。産出ME係数>1V/(cm·Oe)。","材料工学・ナノテク","スマート材料","1972",None,"材料設計","センサー・アクチュエーター","圧電相+磁歪相の精密接合,界面応力伝達","磁場−電場変換デバイス設計","界面結合強度が複合ME効果をどう決定するか","単相マルチフェロイック","マルチフェロイック,ME効果,圧電体,磁歪,複合材料","multiferroic,magnetoelectric,piezoelectric,magnetostrictive,composite","active","primary",80,5,"https://doi.org/10.1103/RevModPhys.74.973","グローバル",0.8,r"ME coefficient: $\alpha_{ME} = \frac{\delta E}{\delta H} = \frac{k_{me} d_{33}^{PE} \lambda_{piezomagnetic}}{s^{PE} + s^{MS}}$; target $>1$ mV/(cm·Oe)","url_present"),

("mat_b5_032","水中ロボット・耐圧複合材容器","Deep-Sea Composite Pressure Vessel","Carbon Fiber Composite for Deep-Sea ROV","炭素繊維強化プラスチック（CFRP）とチタン・セラミクスを組み合わせた深海ROV・AUV向け耐圧容器の設計。水深6000m（60MPa）対応。","KAIKO・SHINKAI 6500・有人深海探査の軽量耐圧ハウジング。海底資源探査に不可欠。","材料工学・ナノテク","海洋・極限材料","1985",None,"材料設計","海洋探査機器","CFRP積層設計, 耐塩水・疲労特性, 水密シール","深海60MPa耐圧・軽量容器設計","静水圧下での層間剥離をどう防ぐか","チタン単体容器","耐圧容器,CFRP,深海ROV,海洋探査,圧力容器","pressure vessel,CFRP,deep-sea ROV,composite hull","active","secondary",82,7,"https://doi.org/10.1016/j.compstruct.2019.111393","グローバル",0.78,r"Hoop stress (thin wall): $\sigma_\theta = pD/(2t)$; CFRP design: $[\pm 54.7°]_n$ layup for equibiaxial loading at 60 MPa","url_present"),

("mat_b5_033","中国COMAC C919複合材翼","China COMAC C919 Composite Wing","C919 CFRP Wing Structure","COMACのC919旅客機向けに開発された炭素繊維複合材翼構造（一次構造CFRP適用率12%）。翼スパー・リブ・外板の積層・接合設計。","中国国産民間航空機の材料自立化。Tiはチタン合金とCFRP複合。FAA/EASA認証取得へ。","材料工学・ナノテク","航空材料工学","2008",None,"材料設計","民間航空機構造","AS4/T800クラスCFRP,オートクレーブ成形,非破壊検査","中国国産民間機の軽量化・強度設計","CFRPとアルミ接合部の電食をどう防ぐか","アルミ合金翼","C919,CFRP翼,中国航空,複合材構造,COMAC","C919,CFRP wing,COMAC,composite structure,aviation","active","secondary",85,8,"https://www.sciencedirect.com/science/article/pii/S1000936119302171","東アジア",0.9,r"Wing bending stiffness: $EI = E_{11}^{CFRP} I_{spar} + E_{Al} I_{rib}$; CFRP weight saving vs Al: $\approx 20$–30\%","url_present"),

("mat_b5_034","インクジェット有機半導体印刷","Inkjet-Printed Organic Semiconductor","Solution-Processed OFET / OLED","有機半導体（TIPS-pentacene, PEDOT:PSS等）のインク調製とインクジェット印刷による薄膜トランジスタ・OLED製造。Roll-to-Roll対応。","フレキシブル電子・ウェアラブルセンサー・印刷RFID。製造コストがシリコンの1/10以下。","材料工学・ナノテク","有機材料工学","2000",None,"製造技術","フレキシブル電子","インクジェット機器,ピエゾ駆動ノズル,固形分2–5wt%","低温・大面積・低コストプリンタブル電子デバイス","印刷膜の結晶配向と移動度の関係は","蒸着有機半導体","有機半導体,インクジェット印刷,OFET,フレキシブル","organic semiconductor,inkjet printing,OFET,flexible electronics","active","primary",82,6,"https://doi.org/10.1038/nature02120","グローバル",0.8,r"Coffee ring effect: $j_r = \frac{(2-\alpha)D_0 c_s}{(1-\alpha)(t_f-t)^{1-1/(2-\alpha)}}$; suppress via co-solvent (high bp) addition","url_present"),

("mat_b5_035","中性子照射耐性ステンレス・ODS鋼","Radiation-Tolerant Steel / ODS Alloy","ODS Ferritic Steel for Nuclear","酸化物分散強化（ODS）フェライト鋼（Y₂O₃粒子分散 in Fe-Cr）の設計・メカニカルアロイング製造法。中性子照射脆化を抑制。","核融合炉・高速炉の炉壁・燃料被覆管材料。ITER TBM候補。照射スウェリング<0.1%/dpa達成。","材料工学・ナノテク","原子力材料","1991",None,"材料設計","原子力構造材料","MA法+HIP焼結,Y₂O₃<25nm分散,高Cr(14–18%)","中性子照射環境での高温強度・照射耐性が必要な場合","ナノ分散Y₂O₃の照射照射下安定性のメカニズムは","316Lオーステナイトステンレス","ODS鋼,酸化物分散強化,核融合炉,照射耐性,高速炉","ODS steel,oxide dispersion strengthened,nuclear,radiation tolerance,ferritic","active","primary",82,6,"https://doi.org/10.1016/j.jnucmat.2007.01.200","グローバル",0.8,r"Swelling rate: $\dot{S} \propto \exp(-E_V/k_BT) \cdot \dot{\phi}$; sink strength $k^2 = \rho_d b^{-2} + N_{ox} \pi r_{ox}^2$ for ODS","url_present"),

("mat_b5_036","量子ドット蛍光体・LEDダウンコンバーター","Quantum Dot Fluorophore for LED","QD Phosphor / QD-LED Down Converter","CdSe/ZnS・InP/ZnS・ペロブスカイトCsPbX₃量子ドット（QD）を蛍光体としてLEDに適用するダウンコンバーション技術。FWHM<30nm。","色域coverage DCI-P3 100%以上の超高色純度ディスプレイ。QD-TV・プロ用モニターに採用。","材料工学・ナノテク","量子材料","1998",None,"材料設計","ディスプレイ・照明","QD合成技術,FWHM<30nm,RoHS対応（InP系）","超高色純度ディスプレイ・照明","カドミウムフリーQDで同等性能を得るには","希土類蛍光体","量子ドット,蛍光体,LED,QD-TV,色純度","quantum dot,QD phosphor,LED,display,color gamut","active","primary",90,8,"https://doi.org/10.1002/adma.200600393","グローバル",0.85,r"QD bandgap tuning: $E_g(r) = E_{g,bulk} + \frac{\hbar^2\pi^2}{2\mu r^2} - \frac{1.8e^2}{4\pi\varepsilon_0\varepsilon r}$ (Brus model)","url_present"),

("mat_b5_037","高分子電解質燃料電池膜（PEM）","PEM Fuel Cell Membrane","Nafion / PFSA PEM","パーフルオロスルホン酸ポリマー（Nafion等）の固体高分子電解質膜の設計・製造技術。プロトン伝導率>100mS/cm at 80°C。","水素燃料電池車（FCEV）・定置用水素発電のコア部材。トヨタMirai・ホンダClarityに採用。","材料工学・ナノテク","電気化学材料","1966",None,"材料設計","エネルギー変換","高プロトン伝導率, 低ガスクロスオーバー, 化学安定性","水素FCEVの電解質膜設計","薄膜化とガスクロスオーバーのトレードオフをどう管理するか","アルカリ膜(AEM)","PEM,Nafion,燃料電池,プロトン交換膜,水素","PEM,Nafion,fuel cell,proton exchange membrane,hydrogen","active","primary",90,9,"https://doi.org/10.1021/cr0207123","グローバル",0.85,r"Proton transport: $J_H = -D_H \nabla c_H - \frac{z F D_H c_H}{RT}\nabla\phi$; Nafion conductivity: $\sigma \approx 0.1$ S/cm at 80°C, 100\% RH","url_present"),

("mat_b5_038","超親水・超疏水コーティング","Superhydrophilic and Superhydrophobic Coating","Lotus Effect Coating / Anti-Icing Coating","ナノ・マイクロ階層構造と低表面エネルギー化を組み合わせた接触角>150°の超疏水・<5°の超親水コーティング技術。","自己洗浄外装・防氷翼・防曇レンズ・抗菌表面への応用。耐久性が実用化の課題。","材料工学・ナノテク","表面工学","1997",None,"材料設計","表面機能化","ナノ構造形成技術,フッ素系低表面エネルギー剤","防氷・自己洗浄・防曇が必要な部品","Cassie-Baxterからの Wenzel遷移をどう防ぐか","平滑疎水面","超疏水,ロータス効果,接触角,自己洗浄,防氷","superhydrophobic,lotus effect,contact angle,self-cleaning,anti-icing","active","primary",85,7,"https://doi.org/10.1039/b712675h","グローバル",0.82,r"Cassie-Baxter: $\cos\theta^* = f_1\cos\theta_1 - f_2$; CA $>$150° when $f_2 \to 1$ (air fraction); Wenzel: $\cos\theta^* = r\cos\theta$","url_present"),

("mat_b5_039","金属有機骨格体（MOF）設計","Metal-Organic Framework Design","MOF / Porous Coordination Polymer","金属イオンと有機リンカーの自己組織化による多孔性ナノ材料の設計・合成。BET比表面積>7000m²/gを達成。","CO₂回収・水素貯蔵・薬物送達・センサーへの応用。MOF-5・ZIF-8・MIL-101が代表例。","材料工学・ナノテク","多孔性材料","1995",None,"材料設計","エネルギー・環境材料","溶媒熱合成,金属ノード-有機リンカー設計","高容量ガス吸着・分離・薬物担持材料","水分安定性と高比表面積の両立方法は","ゼオライト","MOF,金属有機骨格体,多孔性,CO₂回収,水素貯蔵","MOF,metal-organic framework,porous material,CO₂ capture,hydrogen storage","active","primary",88,6,"https://doi.org/10.1126/science.1041088","グローバル",0.85,r"Langmuir capacity: $n_{ads} = \frac{n_m K p}{1+Kp}$; BET: $\frac{1}{n(p_0/p-1)} = \frac{c-1}{n_m c}\cdot\frac{p}{p_0} + \frac{1}{n_m c}$","url_present"),

("mat_b5_040","韓国POSCO高強度AHSS自動車鋼板","POSCO Advanced High-Strength Steel for Automotive","POSCO AHSS / DP/TRIP/TWIP Steel","POSCOが開発・量産する二相鋼（DP）・変態誘起塑性鋼（TRIP）・双晶誘起塑性鋼（TWIP）の自動車構造用鋼板。強度1500MPa超。","自動車ボディの軽量化30%・衝突安全性向上。ギガスチール採用でUHS-AHSS世界シェア上位。","材料工学・ナノテク","自動車材料工学","1995",None,"製造技術","自動車部品","連続焼鈍・ホットプレス,成形性-強度バランス","衝突安全性重視・軽量化自動車鋼板","TWIP効果の積層欠陥エネルギー依存性をどう制御するか","従来高張力鋼板","AHSS,POSCO,DP鋼,TRIP鋼,TWIP鋼","AHSS,POSCO,dual phase steel,TRIP,TWIP,automotive","active","primary",92,9,"https://doi.org/10.1016/j.jmst.2020.06.026","東アジア",0.93,r"TWIP: $SFE = 16 + 1.67\%Mn - 0.81\%Cr + 32.29\%N$ mJ/m²; $\varepsilon_{uniform} > 50\%$ at SFE 20–50 mJ/m²","url_present"),

("mat_b5_041","超軽量発泡アルミ・メタルフォーム","Metal Foam / Aluminum Foam Engineering","Closed-Cell / Open-Cell Metal Foam","溶融アルミに発泡剤（TiH₂）を添加・凝固または粉末冶金で製造する超軽量金属発泡体。密度0.1–1.0g/cm³。","エネルギー吸収（衝撃・振動減衰）・遮音・断熱・軽量サンドイッチ構造への応用。","材料工学・ナノテク","軽量材料","1990",None,"材料設計","軽量構造材料","相対密度0.05–0.3, 均一セル径, 発泡制御","衝撃吸収・軽量化が同時に必要な場合","発泡プロセスでの均一性確保方法は","ハニカム構造","メタルフォーム,アルミ発泡体,衝撃吸収,軽量化","metal foam,aluminum foam,energy absorption,lightweight","active","secondary",80,7,"https://doi.org/10.1016/S1359-6454(96)00292-3","グローバル",0.78,r"Gibson-Ashby: $E^*/E_s \approx C_1(\rho^*/\rho_s)^2$; $\sigma_y^*/\sigma_{ys} \approx C_2(\rho^*/\rho_s)^{3/2}$ for open-cell foam","url_present"),

("mat_b5_042","透明ポリイミドフィルム","Transparent Polyimide Film","Colorless Polyimide / CPI Film","全芳香族・半脂環式構造の無色透明ポリイミドフィルムの合成設計。Tg>300°C・透過率>88%@550nmを両立。","折畳み端末カバーウインドウ・フレキシブルOLEDバックプレーン・宇宙太陽電池基板への応用。","材料工学・ナノテク","高分子材料工学","2006",None,"材料設計","フレキシブル電子","脂環族モノマー設計,CTE<20ppm/K,低複屈折","折畳み端末・ウェアラブル透明基板","着色（黄変）を抑えながら熱安定性を維持するには","PET/PEN基板","透明ポリイミド,CPI,折畳み端末,フレキシブル基板","colorless polyimide,CPI,foldable display,flexible substrate","active","primary",88,8,"https://doi.org/10.1021/acs.macromol.9b00869","グローバル",0.82,r"CTE match: $|\alpha_{CPI} - \alpha_{ITO}| < 3$ ppm/K; optical: Abbe number $V_d = (n_d - 1)/(n_F - n_C) > 50$ target","url_present"),

("mat_b5_043","光ファイバー母材・線引き技術","Optical Fiber Preform Fabrication","VAD / MCVD / OVD Optical Fiber","気相軸付け法（VAD）・改良化学気相堆積法（MCVD）などで製造するシリカ光ファイバー母材と1900°C線引き製造技術。","通信用シングルモードファイバーの損失0.15dB/km達成。古河電工・住友電工が世界トップ。","材料工学・ナノテク","光通信材料","1970",None,"製造技術","光通信インフラ","高純度SiCl₄/GeCl₄原料,VAD炉,線引き炉","低損失光ファイバー製造","GeO₂添加コアの屈折率プロファイル最適化方法は","銅ケーブル","光ファイバー,VAD,MCVD,シリカ,古河・住友","optical fiber,VAD,MCVD,silica,preform fabrication","active","primary",95,9,"https://doi.org/10.1364/AO.22.001661","東アジア",0.95,r"Loss equation: $\alpha = A/\lambda^4 + B\exp(-C/\lambda) + \alpha_{IR}$; Rayleigh scattering limit: 0.15 dB/km at 1550 nm","url_present"),

("mat_b5_044","金属ガラス（バルク非晶質合金）","Bulk Metallic Glass","BMG / Bulk Amorphous Alloy","Zr-, Cu-, Pd-基多成分系合金を臨界冷却速度（<10³K/s）以下で鋳造し、結晶化を抑制した金属ガラスを得る材料設計。","高強度（>1GPa）・高弾性限（2%）・ゼロ磁気ヒステリシス・超精密鋳造性。スポーツ用品・医療器具・電子部品筐体に応用。","材料工学・ナノテク","アモルファス材料","1960",None,"材料設計","精密機械・スポーツ用品","多成分共晶近傍組成,低臨界冷却速度,鋳造設備","高強度・精密形状・磁気特性が同時に必要な場合","結晶化核形成をどう抑制するか","結晶合金","バルク金属ガラス,BMG,非晶質合金,Zr合金,高強度","bulk metallic glass,BMG,amorphous alloy,Zr-based","active","primary",85,7,"https://doi.org/10.1126/science.267.5206.1947","グローバル",0.8,r"Kauzmann temperature: $T_K < T_g$; GFA: $\gamma = T_x/(T_g + T_l)$; Poisson ratio $\nu > 0.32$ for ductile BMG","url_present"),

("mat_b5_045","導電性ハイドロゲル・生体電子材料","Conducting Hydrogel for Bioelectronics","PEDOT:PSS Hydrogel / Tough Hydrogel Bioelectronics","PEDOT:PSS・ポリアニリン等の導電性ポリマーとPAAm/アルギン酸等の高含水ゲルを複合化した生体適合性電子材料。伸び率>1000%・導電率>100S/cm。","脳インターフェース・心臓パッチ・軟ロボット人工筋肉への応用。機械的生体模倣と電気機能を両立。","材料工学・ナノテク","バイオエレクトロニクス材料","2012",None,"材料設計","バイオ医療デバイス","高含水率(>80%)・生体適合性・低界面インピーダンス","脳・神経・筋肉の電気計測・刺激デバイス","インプラント長期安定性をどう確保するか","金属電極","導電性ハイドロゲル,PEDOT:PSS,脳インターフェース,生体電子","conducting hydrogel,PEDOT:PSS,brain interface,bioelectronics","active","primary",82,6,"https://doi.org/10.1038/s41563-019-0452-1","グローバル",0.8,r"Electrical impedance: $Z = R_s + 1/(j\omega C_{dl})$; target $|Z| < 1$ M$\Omega$ at 1 kHz for neural probe","url_present"),

("mat_b5_046","日本日立金属・TDK希土類磁石高性能化","Hitachi Metals / TDK Rare-Earth Magnet High Performance","Nd-Fe-B Grain Boundary Diffusion Process","日立金属・TDKが開発した粒界拡散法（GBD）によるNdFeB焼結磁石の高保磁力化（Hcj>2700kA/m）技術。Dy使用量を80%削減。","EV駆動モーター・風力発電機への応用。Dy資源リスクを解消しながら保磁力を確保。","材料工学・ナノテク","磁性材料工学","2008",None,"製造技術","希土類磁石","GBD装置,Dy₂O₃/DyF₃拡散材,焼結磁石表面処理","EV/風力向け高性能Ndマグネット","粒界相組成が磁壁固着エネルギーをどう決定するか","均一Dy添加磁石","NdFeB磁石,粒界拡散,Dy,保磁力,EV","NdFeB magnet,grain boundary diffusion,Dy,coercivity,EV motor","active","primary",92,9,"https://doi.org/10.1016/j.jmmm.2010.02.070","東アジア",0.97,r"Coercivity: $H_{cj} \approx 2K_1/(\mu_0 M_s) - N_{eff} M_s$; GBD improves $\alpha$-factor: $H_{cj} = \alpha \frac{2K_1}{\mu_0 M_s} - N M_s$","url_present"),

("mat_b5_047","エアロゲル断熱材","Aerogel Thermal Insulation","Silica / Polymer Aerogel Blanket","シリカ・ポリイミド・セルロース系エアロゲルの超臨界乾燥・常圧乾燥製造とブランケット成形技術。熱伝導率0.012–0.020W/mK達成。","LNG船・宇宙服・建築断熱・電池熱管理への超薄型断熱応用。羊毛の3–4倍性能。","材料工学・ナノテク","断熱材料工学","1931",None,"材料設計","断熱材","相対密度<5%,超臨界CO₂乾燥または常圧乾燥","超薄型・高断熱が必要な空間制約のある用途","機械的脆性をどう改善するか（ポリマー複合化）","グラスウール・ロックウール","エアロゲル,断熱材,シリカ,熱伝導率,LNG","aerogel,thermal insulation,silica,thermal conductivity,LNG","active","primary",85,7,"https://doi.org/10.1039/b903483c","グローバル",0.82,r"Thermal conductivity: $\lambda = \lambda_{solid} + \lambda_{gas} + \lambda_{rad}$; Knudsen effect: $\lambda_{gas}(p) = \lambda_0/(1+2\beta Kn)$ suppresses gas conduction","url_present"),

("mat_b5_048","ダイヤモンド半導体・パワーデバイス","Diamond Semiconductor Power Device","CVD Diamond Power Electronics","マイクロ波CVDで合成したtype IIaダイヤモンド（バンドギャップ5.5eV）を用いたSchottkyダイオード・FETの設計。Baliga Figure of Merit>1000×Si。","超高耐圧（>10kV）・超低損失パワーデバイス。日本産業技術総合研究所・元素戦略プロジェクトが主導。","材料工学・ナノテク","パワーデバイス材料","2004",None,"材料設計","パワーエレクトロニクス","p型B-doped diamond, n型P-doped, 低欠陥CVD成長","超高耐圧・超低損失次世代パワーデバイス","p型とn型両方のドーピングを低欠陥で達成するには","SiC・GaNパワーデバイス","ダイヤモンド半導体,CVD,パワーデバイス,バンドギャップ","diamond semiconductor,CVD,power device,wide bandgap","active","primary",72,4,"https://doi.org/10.1063/5.0006324","東アジア",0.8,r"Baliga FOM: $B_{FOM} = \varepsilon_s \mu E_{br}^3$; diamond: $B_{FOM} \approx 24000\times$ Si; $E_{br}=10$ MV/cm, $\mu_h=2000$ cm²/Vs","url_present"),

("mat_b5_049","高圧水素貯蔵タンク複合材設計","High-Pressure H₂ Storage Composite Tank","Type IV CFRP H₂ Pressure Vessel","炭素繊維強化プラスチック（CFRP）フィラメントワインディングとポリエチレン内張りライナーを組み合わせた70MPa水素タンクの設計。","トヨタ Mirai・ホンダClarityのFCV用タンク。比重量エネルギー密度>5kWh/kg。","材料工学・ナノテク","エネルギー材料","2002",None,"材料設計","FCVタンク","CFRP T700/T800, PolyE liner, ISO 11439, JIS-T0900","FCV用70MPa高圧水素タンク設計","水素透過と疲労破壊の連成効果をどう評価するか","金属タンク（Type I/II）","水素タンク,CFRP,フィラメントワインディング,FCV,70MPa","H₂ tank,CFRP,filament winding,FCV,Type IV vessel","active","primary",90,9,"https://doi.org/10.1016/j.ijhydene.2019.01.238","東アジア",0.92,r"Hoop stress: $\sigma_\theta = pR/t$; netting theory winding angle: $\alpha = \arctan\sqrt{2}$ (55°) for equibiaxial; burst safety factor $\geq 2.25$","url_present"),

("mat_b5_050","セルフアセンブリ・ブロック共重合体リソグラフィ","Block Copolymer Directed Self-Assembly","BCP DSA Lithography","ポリスチレン-ブロック-PMMA（PS-b-PMMA）等のブロック共重合体の相分離自己組織化を利用し、5–50nmラインパターンをガイドパターン上に形成するリソグラフィ技術。","EUVリソグラフィの補完・パターン細分化（フリークエンシーダブリング）に利用。IBMとHynixが実証。","材料工学・ナノテク","ナノ製造技術","2003",None,"製造技術","半導体","ガイドパターン精度,χN値,溶媒アニール","EUV後の5–10nmフィン・コンタクトパターニング","χNパラメータの温度・ブロック長依存性をどう利用するか","フォトリソグラフィ","ブロック共重合体,DSA,リソグラフィ,相分離,半導体","BCP,directed self-assembly,DSA,lithography,semiconductor","active","primary",85,6,"https://doi.org/10.1126/science.1130360","グローバル",0.82,r"Lamellar period: $L_0 = a\chi^{1/6}N^{2/3}$; order-disorder transition: $(\chi N)_{ODT} \approx 10.5$ for symmetric BCP","url_present"),
]

if __name__ == "__main__":
    ins, skp = insert_records(records)
    print(f"Inserted: {ins}, Skipped: {skp}")
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM engineering_method")
    print(f"Total: {c.fetchone()[0]}")
    conn.close()
