import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("mat_b1_001","トポロジカル絶縁体設計","Topological Insulator Design","Topological Insulator Engineering",
 "バルクが絶縁体でありながら表面に伝導チャネルを持つトポロジカル絶縁体の設計手法。Berry位相・Z2不変量・スピン-軌道相互作用に基づくバンド構造設計とMBE成長制御を扱う。",
 "スピントロニクス・量子コンピューティングへの応用が期待。Bi2Se3・Bi2Te3が代表物質。2016年ノーベル物理学賞の背景。",
 "材料工学・ナノテク","量子材料工学",2007,None,"device","量子エレクトロニクス",
 "スピン軌道結合が強い重元素系・低温MBE成長","スピントロニクス素子・マヨラナ粒子探索時","Z2不変量の変化を材料設計でどう制御するか",
 "通常絶縁体","トポロジカル絶縁体,Z2不変量,Berry位相,スピン軌道,Bi2Se3",
 "topological insulator,Z2 invariant,Berry phase,spin-orbit,Bi2Se3",
 "active","secondary",80,5,
 "https://www.science.org/doi/10.1126/science.1133734","欧米",0.82,
 r"Z2不変量: $(-1)^{\nu} = \prod_{i=1}^{4}\delta_i$、$\delta_i = \sqrt{\det[w(\Gamma_i)]}/Pf[w(\Gamma_i)]$。表面状態分散: $E = \hbar v_F(\vec{k}\times\vec{n})\cdot\vec{\sigma}$（スピン運動量ロッキング）。",
 "url_present"),

("mat_b1_002","高エントロピー合金設計","High-Entropy Alloy Design","HEA Design",
 "5種類以上の主要元素を等モル比または近等モル比で混合した高エントロピー合金（HEA）の組成・微細組織設計手法。CALPHAD計算・機械学習による組成最適化・変形機構解析を含む。",
 "CoCrFeMnNiのCantor合金が高強度・高靭性の同時達成を実証。極低温・高放射線環境での優位性が確認。",
 "材料工学・ナノテク","合金工学",2004,None,"material","極限環境構造材料",
 "主要元素5種以上・混合エントロピー>1.5R・単相固溶体形成条件","核融合炉・宇宙・極低温構造材設計時","固溶体安定化と格子歪強化のどちらが高強度の主因か",
 "従来合金（単一主元素）","HEA,高エントロピー合金,CALPHAD,固溶体,Cantor合金",
 "HEA,high entropy alloy,CALPHAD,solid solution,Cantor alloy",
 "active","secondary",83,8,
 "https://www.nature.com/articles/nmat3449","欧米",0.83,
 r"混合エントロピー: $\Delta S_{mix} = -R\sum_{i=1}^n x_i\ln x_i$（等モル: $\Delta S_{mix} = R\ln n$）。格子歪エネルギー: $\Delta G_{strain} \propto \delta^2$、$\delta = \sqrt{\sum_i x_i(1-r_i/\bar{r})^2}$。",
 "url_present"),

("mat_b1_003","2次元材料合成・デバイス化","2D Material Synthesis and Device Integration","2D Material Engineering",
 "グラフェン・hBN・MoS2・WS2等の2次元材料の化学気相成長（CVD）・転写・スタッキング・デバイス集積の手法。ファンデルワールスヘテロ構造のバンドエンジニアリングを含む。",
 "グラフェンがノーベル物理学賞2010年受賞。MoS2トランジスタがシリコン限界後継に期待。",
 "材料工学・ナノテク","ナノ材料工学",2004,None,"process","エレクトロニクス・光学",
 "超高真空CVD設備・2次元材料転写装置・vdWヘテロ構造積層","ポストシリコンデバイス・フォトニクスデバイス設計時","大面積均一CVDグラフェンの欠陥密度低減の限界は何か",
 "バルク半導体","グラフェン,MoS2,2次元材料,CVD,ファンデルワールス",
 "graphene,MoS2,2D material,CVD,van der Waals",
 "active","secondary",85,8,
 "https://www.science.org/doi/10.1126/science.1158877","欧米",0.85,
 r"グラフェンバンド構造: $E = \pm\hbar v_F|k|$、$v_F \approx 10^6$ m/s。MoS2バンドギャップ: バルク$E_g=1.2$ eV（間接）、単層$E_g=1.8$ eV（直接）。移動度: $\mu_{graphene} > 10^4$ cm$^2$/(Vs)。",
 "url_present"),

("mat_b1_004","金属積層造形微細組織制御","Metal Additive Manufacturing Microstructure Control","Metal AM Microstructure Engineering",
 "SLM・EBM・DED等の金属積層造形プロセスにおける凝固速度・温度勾配・熱応力を制御して目標微細組織を得る設計手法。柱状→等軸粒変換・析出強化・ポロシティ低減戦略を含む。",
 "アルミ・チタン・ニッケル超合金のニアネットシェイプ造形で航空宇宙コスト30%削減。",
 "材料工学・ナノテク","材料加工工学",2010,None,"process","航空宇宙・医療インプラント",
 "金属粉末特性（粒度・流動性）・プロセスパラメータ（レーザ出力・速度）の制御","航空機部品・医療インプラント・ツール製造時","ポロシティと残留応力の同時低減のための最適プロセス設計は何か",
 "従来の切削加工","SLM,EBM,金属AM,微細組織,ポロシティ",
 "SLM,EBM,metal AM,microstructure,porosity",
 "active","secondary",84,8,
 "https://www.nature.com/articles/s41578-021-00349-3","欧米",0.83,
 r"冷却速度と微細組織: $G/R$ (温度勾配/成長速度) 比が柱状粒-等軸粒遷移を決定。SLM二次デンドライトアーム間隔: $\lambda_2 = A\dot{T}^{-n}$、$\dot{T}$: 冷却速度、$n\approx0.3$。",
 "url_present"),

("mat_b1_005","有機半導体薄膜設計","Organic Semiconductor Thin Film Design","Organic Thin Film Transistor Engineering",
 "共役有機分子・高分子を用いたOFETおよびOPVの薄膜設計手法。分子配向・結晶化制御・電荷移動度最大化・バルクヘテロ接合モルフォロジー最適化を扱う。",
 "フレキシブルエレクトロニクス・大面積印刷太陽電池の基盤技術。PBDB-T:ITIC系でOPV効率17%超を達成。",
 "材料工学・ナノテク","有機エレクトロニクス材料",2000,None,"material","フレキシブルエレクトロニクス",
 "分子構造のHOMO-LUMOレベル制御・薄膜形成プロセス（スピンコート・蒸着）","印刷OPV・フレキシブルOFET・ウェアラブルセンサ設計時","結晶性と電荷移動度のトレードオフをどの分子設計で解決するか",
 "無機半導体","有機半導体,OFET,OPV,電荷移動度,バルクヘテロ接合",
 "organic semiconductor,OFET,OPV,charge mobility,bulk heterojunction",
 "active","secondary",82,8,
 "https://www.nature.com/articles/natrevmats.2016.34","欧米",0.8,
 r"Marcus電荷移動レート: $k_{ET} = \frac{2\pi}{\hbar}|H_{AB}|^2\frac{1}{\sqrt{4\pi\lambda k_BT}}\exp\left(-\frac{(\Delta G^0+\lambda)^2}{4\lambda k_BT}\right)$、$\lambda$: 再配置エネルギー。",
 "url_present"),

("mat_b1_006","相変化メモリ材料設計","Phase Change Memory Material Design","PCM Material Engineering",
 "Ge-Sb-Te系材料の結晶-非晶質相転移を利用した不揮発性メモリの材料設計手法。相変化速度・結晶化エネルギー・熱的安定性・材料スケーリングの最適化を含む。",
 "Samsung・Micronが量産化。3D XPoint（Intel Optane）の基盤材料として採用。次世代NVMの候補。",
 "材料工学・ナノテク","電子材料工学",2000,None,"material","不揮発性メモリ",
 "GST組成設計・デバイス集積プロセス（CVD/ALD）・スケーリング評価","次世代メモリ・ストレージクラスメモリ設計時","データ保持性と書き込み速度のトレードオフをどう最適化するか",
 "シリコンフラッシュメモリ","相変化メモリ,GST,PCM,不揮発性,結晶化",
 "phase change memory,GST,PCM,nonvolatile,crystallization",
 "active","secondary",82,8,
 "https://www.nature.com/articles/nmat2599","東アジア",0.82,
 r"GST結晶化速度: $k(T) = k_0\exp(-E_a/k_BT)$。Avrami核形成成長: $X(t) = 1-\exp(-kt^n)$、$n$: Avrami指数。相変化エネルギー差: $\Delta G_{cryst-amorph}$が電気抵抗コントラスト($\sim10^3$)を生む。",
 "url_present"),

("mat_b1_007","中国希土類材料産業戦略","China Rare Earth Material Strategy","China Rare Earth Engineering",
 "中国が主導する希土類元素（REE）の採掘・精製・永久磁石（NdFeB）・蛍光体・触媒材料のサプライチェーン支配と技術開発戦略。希土類磁石のHc・Br・最大エネルギー積の日本・中国共同開発史。",
 "世界の希土類生産の60%以上を支配。EV・風力発電・半導体製造の戦略資源として地政学的重要性が急増。",
 "材料工学・ナノテク","機能性材料工学",1990,None,"material","EV・電気機器・国防",
 "希土類鉱山地政学リスク管理・NdFeB磁石設計","EV駆動モータ・風力発電・国防電子機器設計時","中国依存リスクを軽減するための希土類代替材料の開発進捗は何か",
 "フェライト磁石","希土類,NdFeB,中国,サプライチェーン,永久磁石",
 "rare earth,NdFeB,China,supply chain,permanent magnet",
 "active","secondary",85,9,
 "https://www.nature.com/articles/nmat3433","東アジア",0.92,
 r"NdFeB磁石性能: 最大エネルギー積 $(BH)_{max} = B_r^2/(4\mu_0)$（理想的反磁化曲線）。保磁力 $H_c$ は粒界相組成で制御。$T_{Curie}=585$ K、低減対策としてDy/Tb置換（$(BH)_{max}$低下vs$H_c$向上）。",
 "url_present"),

("mat_b1_008","セラミック超伝導体設計","Ceramic High-Temperature Superconductor Design","HTS Ceramic Engineering",
 "YBCOおよびBiSSCO系銅酸化物高温超伝導体のバルク・薄膜・テープ線材の設計手法。ピン止め中心の制御・臨界電流密度最大化・加工プロセス（コーティング法）最適化を扱う。",
 "MRI・加速器・送電ケーブルへの応用。2次世代HTS線材（REBa2Cu3O7）が77Kで4MA/cm2を達成。",
 "材料工学・ナノテク","超伝導材料工学",1987,None,"material","電力・医療・加速器",
 "超伝導転移温度Tc・臨界電流密度Jc・不可逆磁場Hirr・機械特性の総合評価","超伝導電力機器・MRI・量子コンピュータ設計時","ランダムピン止めと秩序ピン止めのどちらがJc最大化に有効か",
 "低温超伝導体（NbTi）","高温超伝導,YBCO,臨界電流,ピン止め,線材",
 "HTS,YBCO,critical current,flux pinning,coated conductor",
 "active","secondary",82,7,
 "https://www.nature.com/articles/s41578-021-00287-0","欧米",0.82,
 r"Bean臨界状態モデル: $J_c = \frac{\Delta H}{d}$（均一Jc仮定）。Anderson-Kim熱活性化フラックスクリープ: $J = J_c[1-\frac{k_BT}{U_0}\ln(\frac{t}{t_0})]$。",
 "url_present"),

("mat_b1_009","ピエゾエレクトリック材料・アクチュエータ設計","Piezoelectric Material and Actuator Design","Piezoelectric Actuator Engineering",
 "PZT・PMN-PT・鉛フリー（BaTiO3・KNN）圧電材料を用いたアクチュエータ・センサ・エネルギーハーベスタの設計手法。分極処理・電界誘起歪み・疲労特性の最適化を含む。",
 "超音波モータ・インクジェット・医療超音波の核心材料。EU RoHS規制で鉛フリー移行が急務。",
 "材料工学・ナノテク","機能性材料工学",1950,None,"device","精密機器・医療",
 "使用温度（Tc以下）・電場印加条件・耐疲労性要求","超音波デバイス・精密位置決め・エネルギーハーベスタ設計時","鉛フリー圧電材料でPZT性能を代替できる候補は何か",
 "電磁式アクチュエータ","圧電,PZT,PMN-PT,鉛フリー,アクチュエータ",
 "piezoelectric,PZT,PMN-PT,lead-free,actuator",
 "active","secondary",82,9,
 "https://www.science.org/doi/10.1126/science.aav3780","欧米",0.8,
 r"圧電方程式: $S_i = s_{ij}^E T_j + d_{ki}E_k$（逆圧電）、$D_i = d_{ij}T_j + \varepsilon_{ij}^T E_j$（正圧電）。PZT $d_{33}\approx600$ pm/V、BaTiO3 $d_{33}\approx85$ pm/V。",
 "url_present"),

("mat_b1_010","磁性薄膜スピントロニクスデバイス","Magnetic Thin Film Spintronics Device","Spintronics Device Engineering",
 "GMR・TMR・スピン流・スピンホール効果を利用した磁気抵抗メモリ（MRAM）・スピントルク発振器の設計手法。磁気異方性制御・スピン依存輸送・交換バイアス最適化を扱う。",
 "STT-MRAMが2020年から量産開始（Samsung・Everspin）。電源断時情報保持の優位性でSRAM代替候補。",
 "材料工学・ナノテク","スピントロニクス材料",1990,None,"device","不揮発性メモリ・センサ",
 "磁気異方性エネルギー密度・スイッチング電流密度・保磁力設計","MRAM・磁気センサ・量子コンピュータインターフェース設計時","STT-MRAMの書き込みエラーレートをどう10⁻¹⁵以下に抑えるか",
 "半導体メモリ（DRAM）","スピントロニクス,GMR,TMR,MRAM,スピントルク",
 "spintronics,GMR,TMR,MRAM,spin torque",
 "active","secondary",83,8,
 "https://www.nature.com/articles/s41578-021-00346-6","欧米",0.82,
 r"TMR比: $\frac{R_{AP}-R_P}{R_P} = \frac{2P_1P_2}{1-P_1P_2}$（Julliere式）。STT臨界電流: $I_c = \frac{2e\alpha M_s V}{\hbar\eta}(H_k + 2\pi M_s)$。",
 "url_present"),

("mat_b1_011","カーボンファイバー複合材設計","Carbon Fiber Reinforced Composite Design","CFRP Structural Design",
 "CFRPの積層設計・破壊靭性評価・疲労特性・マトリクス系（エポキシ・BMI・ポリイミド）選択の設計手法。层間破壊・衝撃後圧縮強度（CAI）・修理設計を含む。",
 "Boeing 787のCFRP比率50%超を実現した設計手法の基盤。航空宇宙・EV・風力ブレードに不可欠。",
 "材料工学・ナノテク","複合材料工学",1970,None,"material","航空宇宙・自動車・風力",
 "積層角・ファイバー体積率・使用環境（温湿度）の明確化","軽量構造部品・航空機胴体・風力ブレード設計時","層間破壊とCFRP耐衝撃性のトレードオフはどう解決するか",
 "アルミ合金構造","CFRP,積層設計,層間破壊,CAI,複合材",
 "CFRP,layup design,delamination,CAI,composite",
 "active","secondary",85,9,
 "https://www.sciencedirect.com/science/article/pii/S0266353816302123","欧米",0.83,
 r"積層板面内剛性: $[A] = \sum_k [Q]_k (z_{k+1}-z_k)$、曲げ剛性: $[D] = \frac{1}{3}\sum_k [Q]_k (z_{k+1}^3-z_k^3)$。層間破壊靭性 $G_{Ic}$（モードI）はDCB試験で評価。",
 "url_present"),

("mat_b1_012","日本超伝導材料産業","Japan Superconductor Material Industry","Japan HTS Wire Industry",
 "住友電工・フジクラ・昭和電線が主導するYBCO系2次世代超伝導線材の量産化技術。ハステロイテープへの多層コーティング・連続製造プロセス・電力ケーブル応用の日本固有アプローチ。",
 "世界市場の主要プレーヤー。地中超伝導送電ケーブル（東電）・MEGAWATTモータへの実用化が進む。",
 "材料工学・ナノテク","超伝導材料工学",2000,None,"process","電力・医療・交通",
 "HTS線材の品質基準（Ic>100A/cm幅@77K）・製造コスト削減目標","超伝導電力機器・MRI・量子センシング応用時","HTS線材の製造コストをIEA目標$50/kAm以下にするための課題は何か",
 "低温超伝導線材（NbTi）","日本,超伝導線材,YBCO,住友電工,フジクラ",
 "Japan,HTS wire,YBCO,Sumitomo Electric,Fujikura",
 "active","secondary",82,8,
 "https://ieeexplore.ieee.org/document/7866682","東アジア",0.92,
 r"臨界電流密度（磁場角度依存）: $J_c(H,\theta) = J_{c0}/(1+H/H_{c2})^\beta \cdot f(\theta)$、異方性関数$f(\theta)$はc軸ピン止めで角度依存を最小化。",
 "url_present"),

("mat_b1_013","自己修復材料システム","Self-Healing Material System Design","Self-Healing Materials Engineering",
 "機械的損傷を自律的に修復する自己修復材料のシステム設計。マイクロカプセル封入型・血管型ネットワーク・内在型（可逆共有結合・水素結合・金属配位結合）の各機構とトリガー設計を扱う。",
 "CFRP寿命延伸・ソフトロボット耐久性向上への応用。White型マイクロカプセルが2001年に概念実証。",
 "材料工学・ナノテク","機能性材料工学",2001,None,"material","構造材料・ソフトロボティクス",
 "損傷スケール（マクロ/マイクロ）・修復時間・修復効率の目標設定","CFRP寿命延伸・インフラ保守・ソフトロボット耐久化時","修復効率と材料力学的性能のトレードオフはどう最小化するか",
 "定期メンテナンス","自己修復,マイクロカプセル,可逆結合,CFRP,材料",
 "self-healing,microcapsule,reversible bond,CFRP,materials",
 "active","secondary",79,6,
 "https://www.nature.com/articles/35065836","欧米",0.8,
 r"修復効率: $\eta = K_{IC}^{healed}/K_{IC}^{virgin}$。マイクロカプセル壁厚設計: $t = pd/(4\sigma_{wall})$（内圧$p$、直径$d$、壁材強度$\sigma_{wall}$）。ジエルスアルダー可逆架橋: $r_{DA} \propto \exp(-E_{DA}/RT)$。",
 "url_present"),

("mat_b1_014","多孔質材料・MOF設計","Porous Material and MOF Design","Metal-Organic Framework Engineering",
 "金属有機構造体（MOF）の細孔設計・機能化・安定化手法。CO2吸着・水素貯蔵・薬物送達・触媒応用のためのリンカー選択・金属ノード設計・細孔修飾の最適化を扱う。",
 "MOF-5・ZIF-8・MIL-101が代表例。CO2回収でCCSコスト半減の可能性。水素貯蔵でDOE目標への接近。",
 "材料工学・ナノテク","多孔質材料工学",2000,None,"material","エネルギー・医療・環境",
 "目標分子のサイズ・極性・吸脱着条件（温度・圧力）","CO2回収・H2貯蔵・吸着冷却・薬物送達設計時","MOFのスケールアップ合成と安定性のトレードオフはどう解決するか",
 "ゼオライト","MOF,金属有機構造体,多孔質,CO2吸着,H2貯蔵",
 "MOF,metal-organic framework,porous,CO2 capture,H2 storage",
 "active","secondary",83,8,
 "https://www.science.org/doi/10.1126/science.1079283","欧米",0.83,
 r"Langmuir等温線: $n = n_{max}\frac{K_{ad}P}{1+K_{ad}P}$。MOF BET表面積: $SA = \frac{N_{A}\cdot a_m \cdot n_m}{m}$、ZIF-8で$\sim1800$ m$^2$/g。Henry定数$K_H = \lim_{P\to0}n/P$で低圧吸着性評価。",
 "url_present"),

("mat_b1_015","ニッケル超合金タービンブレード設計","Nickel Superalloy Turbine Blade Design","Ni Superalloy Blade Engineering",
 "航空エンジン・発電用ガスタービンブレードのNi基超合金の組成・単結晶成長・熱処理・コーティング（TBC・MCrAlY）設計手法。クリープ・酸化・疲労複合損傷の評価を含む。",
 "民間航空エンジンの燃費向上の根幹。単結晶ブレード（DS/SX）が1700°C超の燃焼ガス環境に耐える。",
 "材料工学・ナノテク","超合金材料工学",1970,None,"material","航空・エネルギー",
 "製造プロセス（ブリッジマン法等）・稼働温度・累積損傷モデル","高温タービンブレード・燃焼器設計時","γ'析出強化とクリープ変形の組み合わせメカニズムをどう設計に組み込むか",
 "ステンレス鋼","Ni超合金,単結晶,TBC,クリープ,タービンブレード",
 "Ni superalloy,single crystal,TBC,creep,turbine blade",
 "active","primary",85,9,
 "https://www.sciencedirect.com/science/article/pii/S135964540600172X","欧米",0.85,
 r"Norton-Baileycreepレート: $\dot{\varepsilon} = A\sigma^n\exp(-Q/RT)$。γ'体積分率最適化: 60〜70%で最大クリープ強度。TBC熱膨張ミスマッチ応力: $\sigma_{th} = \frac{E_{TBC}\Delta\alpha\Delta T}{1-\nu_{TBC}}$。",
 "url_present"),

("mat_b1_016","ペロブスカイト太陽電池材料設計","Perovskite Solar Cell Material Design","Perovskite PV Engineering",
 "ABX3構造ハライドペロブスカイト光吸収層の組成設計・欠陥制御・界面パッシベーション・安定性改善手法。PCE最大化とデバイス寿命延伸の同時達成を目指す多目的最適化を扱う。",
 "2024年時点でPCE26.7%（タンデム）を達成。シリコン太陽電池に匹敵。コスト・毒性（鉛）・安定性が課題。",
 "材料工学・ナノテク","太陽電池材料工学",2012,None,"material","太陽光発電",
 "高品質MAPbI3薄膜成膜（スピンコート/蒸着）・電子・正孔輸送層設計","高効率低コスト太陽電池・タンデム型太陽電池設計時","鉛フリーペロブスカイトでPCE>20%達成の材料候補は何か",
 "シリコン太陽電池","ペロブスカイト,太陽電池,PCE,鉛フリー,界面",
 "perovskite,solar cell,PCE,lead-free,interface",
 "active","secondary",84,8,
 "https://www.nature.com/articles/nenergy.2016.142","欧米",0.83,
 r"ペロブスカイト開放電圧: $V_{OC} = \frac{nk_BT}{q}\ln\left(\frac{J_{SC}}{J_0}+1\right)$。PCE$=J_{SC}\cdot V_{OC}\cdot FF/P_{in}$。欠陥密度-寿命: $\tau = 1/(k_{trap}N_t)$で欠陥密度$N_t$低減が重要。",
 "url_present"),

("mat_b1_017","韓国バッテリー材料開発","Korea Battery Material Development","Korea Li-ion Battery Materials",
 "LG化学・サムスンSDI・SKイノベーションが主導する正極材（NCM・NCA・LFP）・負極材（シリコン複合体）・電解質・セパレータの材料開発と垂直統合サプライチェーン戦略。",
 "世界EV電池市場シェアの約30%を韓国3社が占有（2023年）。全固体電池移行の量産技術開発でも先行。",
 "材料工学・ナノテク","電池材料工学",2000,None,"material","電気自動車・蓄電",
 "電池仕様（エネルギー密度・出力・寿命・安全性）のバランス設計","EVバッテリーパック・定置型蓄電設計時","NCM系とLFP系の選択基準をどのように市場セグメントに応じて使い分けるか",
 "鉛蓄電池","韓国,リチウムイオン電池,NCM,LFP,全固体電池",
 "Korea,Li-ion battery,NCM,LFP,solid state battery",
 "active","secondary",84,9,
 "https://www.nature.com/articles/s41560-021-00792-6","東アジア",0.9,
 r"NCM正極容量: $C_{cathode} = \frac{n_{Li}F}{M_W}\times 1000$ [mAh/g]、NMC811の理論値$\approx200$ mAh/g。SiOx負極膨張: $\varepsilon_{vol} \approx 3.6(x_{Si}/x_{SiOx}) \times 280\%$（Si完全リチウム化体積変化）。",
 "url_present"),

("mat_b1_018","機能勾配材料設計","Functionally Graded Material Design","FGM Engineering",
 "組成・微細組織・特性が連続的に変化する機能勾配材料（FGM）の設計手法。熱応力緩和・耐熱性と機械強度の両立のための組成プロファイル設計とSPS・CVD製造プロセスを扱う。",
 "宇宙機熱保護システム・原子炉壁材・骨格インプラントへの応用。日本の材料科学者が1987年に概念提唱。",
 "材料工学・ナノテク","複合材料工学",1987,None,"material","宇宙・原子力・医療",
 "熱応力解析（FEM）・組成プロファイル最適化・製造プロセス選択","熱衝撃・高温環境下構造材設計・骨格インプラント設計時","組成勾配の最適化で熱応力を最大何%低減できるか",
 "均質材料","機能勾配材料,FGM,熱応力,SPS,宇宙",
 "FGM,functionally graded material,thermal stress,SPS,aerospace",
 "active","secondary",79,7,
 "https://link.springer.com/article/10.1023/A:1004010629390","東アジア",0.88,
 r"FGM熱応力（単純化）: $\sigma_{th} = -\frac{E(z)\alpha(z)\Delta T}{1-\nu(z)} + \text{const}$。組成プロファイル: $P(z) = (P_m - P_c)(z/h)^n + P_c$、$n$: べき指数（$n=1$で線形勾配）。",
 "url_present"),

("mat_b1_019","電磁波シールド材料設計","Electromagnetic Shielding Material Design","EMI Shielding Material Engineering",
 "電磁障害（EMI）を遮蔽するための複合材料・コーティング・構造設計手法。金属薄膜・カーボン系（グラフェン・CNT・カーボンブラック）・MXene複合材の遮蔽効果（SE）最適化を扱う。",
 "5G/6G機器・軍用電子機器・自動車ECUの電磁両立性（EMC）確保に不可欠。MXeneが100dB超の高SE実証。",
 "材料工学・ナノテク","電磁波材料工学",2000,None,"material","EMC・通信・自動車",
 "目標周波数帯・SE目標値（>20dB）・重量制約","5G基地局・電子機器EMCシールド・軍用電子設計時","軽量かつ高SEを両立するMXene複合材のアスペクト比最適化は何か",
 "金属筐体","EMIシールド,MXene,グラフェン,SE,電磁波",
 "EMI shielding,MXene,graphene,shielding effectiveness,EMC",
 "active","secondary",80,8,
 "https://www.science.org/doi/10.1126/science.aaz0795","欧米",0.8,
 r"遮蔽効果(SE): $SE = 20\log_{10}(E_i/E_t)$ [dB]。$SE = SE_R + SE_A + SE_M$（反射・吸収・多重反射）。吸収部分: $SE_A = 8.68 \cdot t/\delta$、$\delta = \sqrt{2/(\omega\mu\sigma)}$（表皮深さ）。",
 "url_present"),

("mat_b1_020","形状記憶合金アクチュエータ設計","Shape Memory Alloy Actuator Design","SMA Actuator Engineering",
 "NiTiなどの形状記憶合金（SMA）を用いたアクチュエータ・構造適応システムの設計手法。マルテンサイト変態・疲労特性・ヒステリシス補償・バイアス力設計を扱う。",
 "医療用ステント・ロボット人工筋肉・航空機可変形状翼への応用。NiTiは最大8%ひずみと高回復力を示す。",
 "材料工学・ナノテク","機能性材料工学",1970,None,"device","医療・ロボット・航空",
 "変態温度Af・マルテンサイト開始温度Ms・最大回復ひずみの仕様設定","医療インプラント・ソフトロボット筋肉・適応構造設計時","SMAのヒステリシスを制御系でどのように補償するか",
 "油圧・電磁アクチュエータ","形状記憶合金,NiTi,マルテンサイト変態,アクチュエータ,ロボット",
 "shape memory alloy,NiTi,martensitic transformation,actuator,robot",
 "active","secondary",80,8,
 "https://www.sciencedirect.com/science/article/pii/S0079642514000863","欧米",0.8,
 r"Tanaka-Liang-Brinson構成則: $\dot{\sigma} = E(\xi)\dot{\varepsilon} + \Theta\dot{T} + \Omega(\xi)\dot{\xi}$、$\xi$: マルテンサイト体積率。変態ひずみ: $\varepsilon^{tr} = H\xi$（最大変態ひずみ$H\approx0.08$ for NiTi）。",
 "url_present"),

("mat_b1_021","量子ドット材料設計","Quantum Dot Material Design","QD Synthesis and Device Engineering",
 "半導体量子ドット（CdSe・InP・PbS・CsPbBr3ペロブスカイトQD）の合成・配位子交換・サイズ分散制御・デバイス（QLED・QD-LCD・光検出器）集積の設計手法。",
 "Samsung QLED TVにInP QDが採用。重金属フリーInP QDが欧州RoHS対応として普及中。",
 "材料工学・ナノテク","ナノ材料工学",1993,None,"material","ディスプレイ・照明・通信",
 "目標発光波長・量子収率（>90%）・RoHS適合性","QD-LCD・マイクロLED補完・フォトディテクタ設計時","InP QDのPLQYをCdSeに匹敵させるための表面化学設計は何か",
 "希土類蛍光体","量子ドット,InP,CdSe,QLED,ディスプレイ",
 "quantum dot,InP,CdSe,QLED,display",
 "active","secondary",82,8,
 "https://www.nature.com/articles/nature10851","東アジア",0.82,
 r"量子ドットバンドギャップ: $E_g(d) = E_{g,bulk} + \frac{\hbar^2\pi^2}{2\mu d^2} - \frac{1.8e^2}{\varepsilon d}$（Brus式）、$\mu^{-1}=m_e^{-1}+m_h^{-1}$。PLスペクトル半値幅 $\Delta\lambda < 20$ nm（高品質QD）。",
 "url_present"),

("mat_b1_022","バイオミメティック材料設計","Biomimetic Material Design","Bioinspired Materials Engineering",
 "生体組織・生物構造を模倣したバイオミメティック材料の設計手法。ゲッコーヤモリ接着・蓮の葉超撥水・クモの糸高強度・骨の階層構造のナノ・マクロ設計を扱う。",
 "超疎水性コーティング・生体接着パッチ・高性能軽量複合材への応用が活発。",
 "材料工学・ナノテク","機能性材料工学",1998,None,"material","コーティング・医療・繊維",
 "対象生体構造の形態学的・機械的特性の詳細解析","防汚コーティング・生体接着・軽量高強度複合材設計時","人工クモ糸の引張強度で天然品（1.3GPa）を上回るための製糸プロセス設計は何か",
 "従来合成高分子","バイオミメティック,超撥水,ゲッコー接着,クモの糸,骨",
 "biomimetic,superhydrophobic,gecko adhesion,spider silk,bone",
 "active","secondary",79,7,
 "https://www.nature.com/articles/s41578-023-00533-9","欧米",0.78,
 r"Cassie-Baxter超撥水接触角: $\cos\theta^* = \phi_s(\cos\theta + 1) - 1$（$\phi_s$: 固体面積分率）。ゲッコー接着力: $F = n \cdot A_{pillar} \cdot \tau_{vdW}$、vdWせん断応力$\tau_{vdW} \approx 10^5$ N/m$^2$。",
 "url_present"),

("mat_b1_023","中国先端材料産業政策","China Advanced Materials Industry Policy","China Materials 2025 Strategy",
 "中国製造2025の重点10分野に含まれる先端材料（高性能複合材・次世代半導体材料・バイオ材料・新エネルギー材料）の国産化戦略。希土類・SiCウエハ・炭素繊維の垂直統合政策の技術的背景。",
 "SiCウエハ国産化率2023年で約20%に向上。炭素繊維（T800相当）の国産化で航空宇宙依存脱却が進行中。",
 "材料工学・ナノテク","材料政策・産業",2015,None,"system","製造・エネルギー・国防",
 "国家材料技術路線図・産学官連携プログラム","中国材料産業分析・サプライチェーンリスク評価時","中国のSiCウエハ国産化が日本・米国材料企業に与える影響は何か",
 "材料輸入依存","中国,先端材料,製造2025,SiC,炭素繊維",
 "China,advanced materials,Made in China 2025,SiC,carbon fiber",
 "active","secondary",80,9,
 "https://ieeexplore.ieee.org/document/9163248","東アジア",0.88,
 r"材料自給率目標: $\text{自給率} = \frac{W_{domestic}}{W_{total}} \times 100\%$。政府補助効果の試算: 単位補助$\Delta s$に対する国産比率上昇 $\Delta x = \frac{\partial x}{\partial s}\Delta s$（産業政策効果弾性）。",
 "url_present"),

("mat_b1_024","コロイド結晶・フォトニック結晶設計","Colloidal Crystal and Photonic Crystal Design","Photonic Crystal Engineering",
 "周期的誘電体構造（フォトニック結晶）のバンドギャップ設計と自己組織化コロイド結晶の合成手法。1D・2D・3Dフォトニック結晶のフォトニックバンド計算・欠陥導入・光閉じ込め設計を扱う。",
 "LEDの光取り出し効率向上・レーザー発振しきい値低下・光ファイバセンサへの応用。",
 "材料工学・ナノテク","フォトニクス材料工学",1987,None,"material","光通信・照明・センシング",
 "設計波長・誘電率コントラスト・製造プロセス精度（λ/10以下）","LED効率向上・光集積回路・カラーフィルタ設計時","完全フォトニックバンドギャップと製造精度のトレードオフをどう設計するか",
 "均質光学材料","フォトニック結晶,コロイド,バンドギャップ,光閉じ込め,LED",
 "photonic crystal,colloidal,bandgap,light confinement,LED",
 "active","secondary",79,7,
 "https://www.nature.com/articles/386143a0","欧米",0.8,
 r"フォトニックバンドギャップ条件（1D多層膜）: $\cos(K\Lambda) = \cos(k_1d_1)\cos(k_2d_2) - \frac{1}{2}(n_1/n_2+n_2/n_1)\sin(k_1d_1)\sin(k_2d_2)$、$K$: Bloch波数。",
 "url_present"),

("mat_b1_025","触媒材料設計・機械学習支援","Catalyst Material Design with Machine Learning","ML-Assisted Catalysis Engineering",
 "均一触媒・不均一触媒の活性・選択性・耐久性を機械学習で加速設計する手法。DFT計算データ・実験データの統合とGNNによる触媒予測・高スループットスクリーニングを扱う。",
 "Open Catalyst Projectが数百万のDFT計算データで触媒探索を加速。触媒設計コスト90%削減の事例も。",
 "材料工学・ナノテク","計算材料科学",2018,None,"algorithm","化学・エネルギー触媒",
 "DFTデータベース（OC20等）・実験検証のための合成プロセス確立","CO2還元触媒・アンモニア合成・燃料電池触媒設計時","機械学習触媒予測の信頼性指標（不確実性定量化）をどう設計するか",
 "ヒューリスティック触媒スクリーニング","触媒材料,機械学習,DFT,GNN,高スループット",
 "catalyst,machine learning,DFT,GNN,high-throughput",
 "active","secondary",81,7,
 "https://www.nature.com/articles/s41586-020-2177-8","欧米",0.82,
 r"Sabatier火山型曲線: $\Delta G_{ads}^{opt}$が最大活性を与える最適吸着エネルギー。GNN予測誤差: $MAE = \frac{1}{N}\sum_i|E_{pred,i}-E_{DFT,i}|$、目標$<0.1$ eV/原子。",
 "url_present"),

("mat_b1_026","電極触媒（電解水素製造）材料","Electrocatalyst for Water Splitting","HER/OER Electrocatalyst Design",
 "水電解による水素製造のための水素発生反応（HER）・酸素発生反応（OER）触媒の材料設計手法。白金族代替（遷移金属リン化物・窒化物・単原子触媒）の過電圧低減・安定性向上を扱う。",
 "グリーン水素コスト低減の鍵技術。白金代替触媒でHER過電圧<50mV達成例が増加中。",
 "材料工学・ナノテク","電気化学材料工学",2010,None,"material","水素エネルギー",
 "電解質（酸性/アルカリ/中性）・電流密度目標・安定性（>1000h）要件","グリーン水素製造・燃料電池電極・CO2還元設計時","AEM/PEM電解槽向けの最適OER触媒は何か",
 "Pt/Ir系貴金属触媒","HER,OER,電解水素,単原子触媒,過電圧",
 "HER,OER,water splitting,single atom catalyst,overpotential",
 "active","secondary",82,8,
 "https://www.nature.com/articles/nenergy.2016.34","欧米",0.82,
 r"Butlerー Volmer式: $j = j_0[\exp(\alpha n F\eta/RT) - \exp(-(1-\alpha)nF\eta/RT)]$。Tafelスロープ: $b = RT/(\alpha n F)$ [V/decade]。HER経路: Volmer ($\Delta G_H^*$) → Heyrovsky/Tafel step。",
 "url_present"),

("mat_b1_027","医療用インプラント材料設計","Medical Implant Material Design","Biomedical Implant Materials Engineering",
 "チタン合金・コバルトクロム合金・PEEK・ハイドロキシアパタイトコーティングを組み合わせた整形外科・歯科・心血管インプラントの材料設計手法。骨結合・腐食耐性・疲労寿命・生体適合性の同時最適化。",
 "人工股関節・骨固定スクリュー・冠動脈ステントの材料標準。ISO 10993生体適合性試験準拠。",
 "材料工学・ナノテク","生体材料工学",1970,None,"material","医療デバイス",
 "生体適合性（ISO 10993）・機械強度・腐食耐性・骨結合性の全項目評価","整形外科インプラント・歯科インプラント・心血管デバイス設計時","表面改質でのオッセオインテグレーション促進と感染抑制の両立はどう設計するか",
 "ステンレス鋼インプラント","チタン合金,インプラント,ハイドロキシアパタイト,生体適合性,骨結合",
 "titanium alloy,implant,hydroxyapatite,biocompatibility,osseointegration",
 "active","secondary",84,9,
 "https://www.nature.com/articles/s41578-022-00400-7","欧米",0.83,
 r"Ti-6Al-4V弾性率: $E\approx114$ GPa（骨: 10-30 GPa）。弾性率ミスマッチ（応力シールディング）低減のため多孔質設計: $E_{porous} = E_s(1-\rho/\rho_s)^2$（Gibsonモデル）。",
 "url_present"),

("mat_b1_028","導電性高分子材料","Conducting Polymer Engineering","Conjugated Polymer Device Engineering",
 "PEDOT:PSS・ポリアニリン・ポリチオフェン等の導電性高分子の合成・ドーピング・薄膜形成・デバイス（OPV・OFET・有機電極・イオントロニクス）への応用設計手法。",
 "フレキシブルエレクトロニクス・バイオエレクトロニクスの界面材料として不可欠。PEDOT:PSSが最も実用化。",
 "材料工学・ナノテク","有機エレクトロニクス材料",1990,None,"material","エレクトロニクス・バイオ",
 "ドーピング方法・溶液加工条件・界面特性（功函数）設計","有機電極・イオントロニクス・バイオセンサ設計時","PEDOT:PSSの電気伝導率を1000 S/cm以上に安定的に向上させる手法は何か",
 "金属電極材料","導電性高分子,PEDOT:PSS,ドーピング,イオントロニクス,フレキシブル",
 "conducting polymer,PEDOT:PSS,doping,iontronics,flexible",
 "active","secondary",80,8,
 "https://www.nature.com/articles/nmat2946","欧米",0.8,
 r"PEDOT:PSS伝導率: $\sigma = ne\mu$、モルフォロジー最適化（DMSO添加）で$\sigma > 1000$ S/cm。ドーピングレベル: $p = N_A/(N_A+N_{neutral}) \times 100\%$、PEDOT$\approx33\%$ドープ状態が標準。",
 "url_present"),

("mat_b1_029","核融合炉材料設計","Fusion Reactor Material Design","Plasma-Facing Material Engineering",
 "ITERおよびDEMO向け核融合炉のプラズマ対向材（タングステン・炭素・液体リチウム）・構造材（低放射化フェライト鋼RAFM）・超伝導磁石材料の設計手法。中性子照射脆化・熱負荷耐性を扱う。",
 "ITER建設中（2030年代運転開始目標）。CFs核融合スタートアップへの素材供給に注目集まる。",
 "材料工学・ナノテク","核材料工学",2000,None,"material","核融合エネルギー",
 "中性子照射耐性・熱負荷（10MW/m2）・真空適合性の評価","ITER・DEMO・民間核融合炉材料設計時","タングステンの中性子照射脆化をどうナノ構造化で抑制するか",
 "ステンレス鋼","核融合材料,タングステン,RAFM,中性子照射,プラズマ対向材",
 "fusion material,tungsten,RAFM,neutron irradiation,plasma-facing",
 "active","secondary",78,4,
 "https://www.sciencedirect.com/science/article/pii/S2214785321020009","欧米",0.8,
 r"照射損傷: $d = \frac{N_d}{N_{atoms}} = \int_0^{\phi t}\sigma_d\phi d(\phi t)$ [dpa]（displacement per atom）。Orowan強化: $\Delta\sigma = M\frac{0.8\mu b}{\sqrt{2}\pi}\frac{1}{\overline{L}}$（欠陥分散強化）。",
 "url_present"),

("mat_b1_030","表面改質・コーティング工学","Surface Modification and Coating Engineering","Surface Engineering Advanced",
 "PVD・CVD・電解メッキ・熱溶射・プラズマ窒化・DLCコーティングによる表面機能化の設計手法。耐摩耗・耐腐食・超撥水・生体適合性・光学機能付与の多目的最適化を扱う。",
 "切削工具寿命5〜10倍延長・自動車部品耐久性向上・航空機ブレードのTBC適用で実用化が確立。",
 "材料工学・ナノテク","表面工学",1980,None,"process","製造・航空・医療",
 "基材と被膜の密着性・使用環境（摩耗・腐食・温度）条件の明確化","切削工具・航空機部品・医療インプラント表面処理時","PVDとCVDの選択基準と密着性の最適化は何か",
 "無処理材料表面","PVD,CVD,DLC,TBC,表面改質",
 "PVD,CVD,DLC,TBC,surface modification",
 "active","secondary",83,9,
 "https://www.sciencedirect.com/science/article/pii/S0257897217311799","欧米",0.82,
 r"コーティング密着力（スクラッチ試験）: $L_c$ [N]で評価。TBC熱伝導率: $\kappa_{YSZ} \approx 2$ W/(mK) vs $\kappa_{Ni} \approx 90$ W/(mK)。DLC硬度: $H > 20$ GPa（ta-C）。",
 "url_present"),

("mat_b1_031","ナノ粒子合成・応用工学","Nanoparticle Synthesis and Application Engineering","Nanoparticle Engineering",
 "金属・酸化物・量子ドット・デンドリマー・リポソームナノ粒子の合成・サイズ制御・表面機能化・生体内挙動設計の手法。創薬DDS・磁気ハイパーサーミア・光触媒への応用を統合。",
 "liposome製剤（Doxil・mRNA-LNP）が承認済み。金ナノ粒子を用いた診断が臨床応用中。",
 "材料工学・ナノテク","ナノ材料工学",1990,None,"material","医療・エネルギー・環境",
 "目標サイズ（1-100nm）・表面化学（PEG化・抗体結合）・生体適合性評価","がん治療DDS・診断造影剤・光触媒設計時","EPR効果に依存しない次世代DDS設計の方向性は何か",
 "バルク材料","ナノ粒子,DDS,リポソーム,金ナノ,光触媒",
 "nanoparticle,DDS,liposome,gold nanoparticle,photocatalyst",
 "active","secondary",83,8,
 "https://www.nature.com/articles/nnano.2012.149","欧米",0.82,
 r"LaMer核形成-成長モデル: 核形成率 $J = A\exp(-\Delta G^*/k_BT)$、$\Delta G^* = \frac{16\pi\gamma^3v_m^2}{3(k_BT\ln S)^2}$（$S$: 過飽和度）。Oswald熟成: $r^3 - r_0^3 = \frac{8\gamma D v_m^2 c_\infty}{9RT}t$。",
 "url_present"),

("mat_b1_032","センサ材料・ガス検知材料設計","Sensor and Gas Detection Material Design","Chemical Sensor Material Engineering",
 "金属酸化物（SnO2・ZnO）・MOF・グラフェン・ポリマー系ガスセンサ材料の設計手法。感度・選択性・応答速度・動作温度の最適化とSurface acoustic wave（SAW）・抵抗変化型・光学型センサへの統合。",
 "IoTガスセンサ・工業安全監視・医療呼気診断への展開。電子鼻（e-nose）への応用が加速。",
 "材料工学・ナノテク","機能性材料工学",1980,None,"material","IoT・産業・医療",
 "ターゲットガス種・検出濃度範囲・選択性要件・動作環境（温湿度）","室内空気質監視・工業リーク検知・医療呼気解析時","MOFベースセンサの選択性向上のための細孔修飾戦略は何か",
 "電気化学センサ（白金電極）","ガスセンサ,SnO2,MOF,グラフェン,e-nose",
 "gas sensor,SnO2,MOF,graphene,electronic nose",
 "active","secondary",79,8,
 "https://www.nature.com/articles/s41578-021-00317-x","欧米",0.8,
 r"Langmuir-Hinshelwood機構（金属酸化物センサ）: $\Delta R/R_0 = k[G]^n$（$[G]$: ガス濃度、$n$: 反応次数）。SAWセンサ周波数シフト: $\Delta f/f_0 = -(S_m\Delta m + S_e\Delta\varepsilon)$。",
 "url_present"),

("mat_b1_033","生体組織工学・足場材料設計","Tissue Engineering Scaffold Design","Biomaterial Scaffold Engineering",
 "生体組織再生のための足場（スキャフォールド）材料設計手法。PLA・PCL・ハイドロゲル（アルギン酸・コラーゲン）・脱細胞化マトリクスのポロシティ・力学特性・分解速度・細胞親和性の最適化。",
 "皮膚・骨・心臓組織の再生医療への応用が臨床試験段階に。バイオプリンティングと組み合わせた3D組織構築が加速。",
 "材料工学・ナノテク","生体材料工学",1990,None,"material","再生医療・医療機器",
 "対象組織の力学特性・分解期間・血管新生要件","骨再生・皮膚再生・心筋パッチ・軟骨修復設計時","スキャフォールドの孔径・ポロシティと細胞浸透・栄養輸送の最適バランスは何か",
 "合成移植片","足場材料,組織工学,ハイドロゲル,3Dバイオプリント,再生医療",
 "scaffold,tissue engineering,hydrogel,3D bioprinting,regenerative medicine",
 "active","secondary",81,7,
 "https://www.nature.com/articles/s41578-021-00343-9","欧米",0.8,
 r"スキャフォールド弾性率: $E_{scaffold} = E_s(1-p)^2$（$p$: ポロシティ）。薬物放出（Korsmeyer-Peppas）: $M_t/M_\infty = kt^n$（$n<0.5$: Fickian拡散、$n>0.5$: non-Fickian）。",
 "url_present"),

("mat_b1_034","磁性材料計算設計（第一原理）","First-Principles Magnetic Material Design","Ab initio Magnetic Material Engineering",
 "密度汎関数理論（DFT）・DFT+U・GWA計算による磁性材料（強磁性・反強磁性・フラストレート磁性・マルチフェロイクス）のバンド構造・交換積分・磁気異方性の第一原理設計。",
 "NdFeBの磁気異方性設計・トポロジカル磁性体の予測・2次元磁性体（CrI3）発見に貢献。",
 "材料工学・ナノテク","計算材料科学",1980,None,"algorithm","磁性デバイス・スピントロニクス",
 "計算クラスタ（DFT計算量: O(N³)）・実験検証との連携","永久磁石・スピントロニクス・量子磁性研究時","DFT+Uでの$U$値選択が磁気特性予測精度に与える影響はどう評価するか",
 "経験的磁性モデル","DFT,磁性,磁気異方性,GGA+U,第一原理",
 "DFT,magnetism,magnetic anisotropy,GGA+U,first principles",
 "active","secondary",80,8,
 "https://www.nature.com/articles/s41578-022-00401-6","欧米",0.8,
 r"Heisenberg交換: $H = -\sum_{ij}J_{ij}\vec{S}_i\cdot\vec{S}_j$、DFT計算値$J_{ij} = \frac{\partial^2 E}{\partial\theta_i\partial\theta_j}$。磁気異方性エネルギー: $K_u = E([100]) - E([001])$ [J/m$^3$]。",
 "url_present"),

("mat_b1_035","複合材料リサイクル技術","Composite Material Recycling Technology","CFRP Recycling Engineering",
 "CFRP・FRP複合材料の繊維回収・樹脂除去・再利用のための化学・溶剤・熱分解・流体超臨界分解リサイクル手法の設計。回収CF性能（引張強度保持率）・コスト評価・LCA統合を扱う。",
 "EU End-of-Life Vehicle指令（ELV）対応・航空機廃棄物削減のための実用化が急務。超臨界水分解で引張強度95%保持を実証。",
 "材料工学・ナノテク","材料循環工学",2010,None,"process","リサイクル・航空・自動車",
 "廃複合材料の組成・エポキシ樹脂種・スケール（研究→量産）","航空機廃棄・EV部品・スポーツ用品CFRP再利用時","回収CF強度保持率と経済的リサイクルコストの現状の乖離はどれほどか",
 "埋め立て・焼却","CFRPリサイクル,炭素繊維回収,超臨界分解,LCA,循環経済",
 "CFRP recycling,carbon fiber recovery,supercritical decomposition,LCA,circular economy",
 "active","secondary",78,6,
 "https://www.sciencedirect.com/science/article/pii/S0959652622037131","欧米",0.78,
 r"超臨界水分解: $T_c = 374°C$、$P_c = 22.1$ MPa以上で水の密度・誘電率が変化し非極性有機物を溶解。回収CF収率: $Y_{CF} = W_{CF,out}/W_{CFRP,in} \times (1-V_m)^{-1}$。",
 "url_present"),

("mat_b1_036","電気化学キャパシタ（スーパーキャパシタ）材料","Electrochemical Capacitor Material Design","Supercapacitor Material Engineering",
 "電気二重層キャパシタ（EDLC）・擬似容量型（RuO2・MnO2・MXene・導電性高分子）のエネルギー・パワー密度最大化のための電極材料・電解質・セル設計手法。",
 "ハイブリッドEV・UPS・再エネバッファとして実用化。MXene電極でエネルギー密度100Wh/kg達成事例。",
 "材料工学・ナノテク","電気化学材料工学",1990,None,"material","エネルギー貯蔵",
 "充放電時定数（秒〜分）・温度範囲・サイクル寿命（>100万回）要件","急速充放電・ピークパワー補助・UPS設計時","電池とキャパシタのハイブリッドにおける最適エネルギー分配比は何か",
 "リチウムイオン電池","スーパーキャパシタ,EDLC,MXene,擬似容量,エネルギー密度",
 "supercapacitor,EDLC,MXene,pseudocapacitance,energy density",
 "active","secondary",82,8,
 "https://www.science.org/doi/10.1126/science.1216744","欧米",0.82,
 r"EDLC容量: $C = \varepsilon_0\varepsilon_r A/d$、$d\approx$1nm（双電気層厚）。エネルギー密度: $E = CV^2/2$、パワー密度: $P = V^2/(4R_{ESR})$。Ragone plot: $P = E/t_{discharge}$で特性化。",
 "url_present"),

("mat_b1_037","熱電材料高性能化","High-Performance Thermoelectric Material Design","Thermoelectric Material Engineering",
 "ZT>1の高性能熱電材料設計手法。ナノ構造化（熱伝導率低減）・バンドエンジニアリング（パワーファクター増大）・複数フォノン散乱機構の統合設計とBi2Te3・PbTe・ハーフホイスラーの比較評価。",
 "廃熱回収・宇宙機電源・冷却モジュールに実用化。SnSeの単結晶でZT=2.6が報告（2014年）。",
 "材料工学・ナノテク","熱電材料工学",1990,None,"material","エネルギー変換",
 "温度差・作動温度範囲・パワーファクターS²σ最大化","廃熱電源・自動車熱電・宇宙機電源設計時","ナノ構造化によるカッパ低減と電子移動度の劣化抑制のトレードオフはどう解決するか",
 "従来金属熱電材料","熱電材料,ZT値,ナノ構造化,Bi2Te3,PbTe",
 "thermoelectric material,ZT value,nanostructuring,Bi2Te3,PbTe",
 "active","secondary",82,8,
 "https://www.science.org/doi/10.1126/science.1174276","欧米",0.82,
 r"フォノンガラス電子結晶（PGEC）: $ZT = \frac{S^2\sigma T}{\kappa_e+\kappa_L}$、$\kappa_L$低減が主目標。Callaway式: $\kappa_L = \frac{1}{3}C_v v_s^2\tau_{ph}$、ナノ構造で$\tau_{ph}$短縮。",
 "url_present"),

("mat_b1_038","台湾先端半導体材料開発","Taiwan Advanced Semiconductor Materials","Taiwan Semiconductor Material R&D",
 "工業技術研究院・台湾大学・台湾清華大・TSMCが推進する次世代半導体材料（GaN・SiC・III-V族・2D材料）研究開発エコシステム。国産ウエハ・エピ技術の高度化戦略。",
 "台積電のN2プロセス向けGAAFET材料・次世代化合物半導体の国産エコシステム構築が進行中。",
 "材料工学・ナノテク","半導体材料工学",2015,None,"system","半導体製造",
 "ウエハ品質（EPD・欠陥密度）・プロセス整合性・ファウンドリPDK適合","次世代半導体ロードマップ材料選定・国産化戦略時","台湾のIII-V族半導体エコシステムがIntelやIMECと競合できる領域は何か",
 "シリコンウエハのみ","台湾,半導体材料,GaN,III-V族,2D材料",
 "Taiwan,semiconductor material,GaN,III-V,2D material",
 "active","secondary",79,7,
 "https://ieeexplore.ieee.org/document/9643584","東アジア",0.87,
 r"GaN転位密度とリーク電流: $I_{leak} \propto \exp(-E_a/kT)\cdot N_{disloc}$。SiC欠陥: BPD（基底面転位）密度$<1$cm$^{-2}$がデバイス信頼性の鍵。$R_{on,sp} = 4V_{BR}^2/(\varepsilon_s\mu_n E_c^3)$でSiC優位性。",
 "url_present"),

("mat_b1_039","固体電解質・全固体電池材料","Solid Electrolyte and All-Solid-State Battery","Solid-State Battery Material Design",
 "硫化物系（Li6PS5Cl・LGPS）・酸化物系（LLZO・LATP）・高分子系固体電解質の設計手法。イオン伝導率・界面抵抗・機械的安定性・製造プロセス統合の多目的最適化を扱う。",
 "トヨタが2027年全固体電池EV量産を宣言。エネルギー密度2倍・充電時間半減・安全性向上が期待。",
 "材料工学・ナノテク","電池材料工学",2010,None,"material","EV・航空・医療",
 "イオン伝導率>10⁻³ S/cm・機械的強度・電気化学窓・大気安定性","全固体EV電池・医療植込み電池・航空航宙設計時","硫化物系固体電解質の大気安定性と高伝導率のトレードオフはどう解決するか",
 "液体電解質リチウムイオン電池","全固体電池,LGPS,LLZO,固体電解質,イオン伝導",
 "all-solid-state battery,LGPS,LLZO,solid electrolyte,ionic conductivity",
 "active","secondary",83,7,
 "https://www.nature.com/articles/nenergy.2016.30","東アジア",0.85,
 r"Nernst-Planckイオン輸送: $J_i = -D_i\nabla c_i - \frac{z_i F D_i}{RT}c_i\nabla\phi$。LGPS伝導率: $\sigma = 1.2\times10^{-2}$ S/cm (室温)。界面抵抗: $R_{int} = R_{bulk} - R_{eff}$、界面改質でT$<10\mu\Omega$cm$^2$目標。",
 "url_present"),

("mat_b1_040","ハードコーティング・工具材料設計","Hard Coating and Cutting Tool Material Design","Hard Coating Engineering",
 "TiN・TiAlN・DLC・cBN・多層ナノコーティングを切削工具・金型に施すハードコーティングの設計手法。硬度・弾性率・残留応力・熱安定性の最適化とPVDプロセス設計を含む。",
 "TiAlN系多層コーティングが高速切削工具の標準。切削速度2倍・工具寿命5倍の実績。",
 "材料工学・ナノテク","表面工学",1985,None,"process","切削工具・金型",
 "切削条件（速度・送り・切り込み）・被削材種・冷却方法（ドライ/湿式）","高速切削・難削材加工・金型成形工具設計時","TiAlNとAlTiNの違いがドライ切削に与える影響は何か",
 "無コーティング超硬","TiAlN,DLC,cBN,ハードコーティング,切削工具",
 "TiAlN,DLC,cBN,hard coating,cutting tool",
 "active","secondary",83,9,
 "https://www.sciencedirect.com/science/article/pii/S0257897201012069","欧米",0.8,
 r"コーティング硬度（ナノインデンテーション）: $H = P_{max}/A_c$（$A_c$:接触投影面積）。弾性回復率: $\eta_e = (h_{max}-h_{rest})/h_{max}$。nACo（nc-TiAlN/a-Si3N4）: $H>40$ GPa。",
 "url_present"),

("mat_b1_041","原子層堆積法（ALD）材料プロセス","Atomic Layer Deposition Materials and Process","ALD Process Engineering",
 "原子層堆積法（ALD）による超薄膜・コンフォーマル・高アスペクト比膜（Al2O3・HfO2・ZnO・Pt）の成膜設計手法。自己制御機構・成長速度（GPC）・前駆体設計・温度窓の最適化を扱う。",
 "先端半導体ゲート絶縁膜（HfO2: 45nm世代から標準）・リチウムイオン電池コーティング・MEMSに不可欠。",
 "材料工学・ナノテク","薄膜材料工学",1970,None,"process","半導体・電池・MEMS",
 "前駆体の飽和条件・成膜温度ウィンドウ・膜厚精度（Å単位）","先端ロジック・DRAM・LiB保護コーティング設計時","新規前駆体の自己制御性を評価するための最適スクリーニング手法は何か",
 "化学気相成長（CVD）","ALD,原子層堆積,HfO2,前駆体,薄膜",
 "ALD,atomic layer deposition,HfO2,precursor,thin film",
 "active","primary",84,9,
 "https://www.nature.com/articles/s41578-021-00299-w","東アジア",0.82,
 r"ALD自己制御成長速度: $GPC = n_{precursor}\cdot a_{reac}/A_{site}$ [Å/cycle]。HfO2誘電率: $k\approx25$（vs SiO2: $k=3.9$）、EOT$= k_{SiO2}/k_{HfO2}\times t_{HfO2}$。",
 "url_present"),

("mat_b1_042","中国カーボンファイバー産業化","China Carbon Fiber Industrialization","China Carbon Fiber Production",
 "中国航材・恒神股份・光威復材が主導するPAN系炭素繊維の国産化。T700/T800相当品の製造技術向上・宇宙・航空・風力ブレード向け大量生産体制の構築戦略。",
 "中国炭素繊維生産量が2023年に日本・米国に次ぐ3位。防衛・宇宙用途での自立化が安全保障上の優先課題。",
 "材料工学・ナノテク","複合材料工学",2010,None,"process","航空・風力・スポーツ",
 "PAN前駆体純度・炭化・黒鉛化プロセス制御・品質検査体制","防衛・宇宙・航空機炭素繊維自給率向上時","中国のT800相当炭素繊維がTorayと同等品質を達成するための残課題は何か",
 "輸入炭素繊維依存","中国,炭素繊維,PAN,T800,国産化",
 "China,carbon fiber,PAN,T800,industrialization",
 "active","secondary",80,8,
 "https://ieeexplore.ieee.org/document/9756832","東アジア",0.88,
 r"PAN炭素化反応温度: 安定化（200-300°C）→炭化（1000-1600°C）→黒鉛化（>2000°C）。引張強度と黒鉛化温度の関係: $\sigma_f = \sigma_0\exp(-\Delta E_a/RT)$、黒鉛化度$g$で弾性率$E \propto g$。",
 "url_present"),

("mat_b1_043","ソフトロボティクス材料設計","Soft Robotics Material Design","Soft Matter Actuator Engineering",
 "シリコンエラストマー・ハイドロゲル・液晶エラストマー・形状記憶高分子を用いたソフトアクチュエータの設計手法。空気圧駆動・化学駆動・光駆動の各種ソフトロボット材料の変形機構解析と製造。",
 "医療用ソフトグリッパー・嚥下補助デバイス・海底探査ソフトロボットへの応用が実証段階。",
 "材料工学・ナノテク","ソフト材料工学",2011,None,"material","ロボティクス・医療",
 "作動方式（空気圧/化学/熱/光）・変形量・力出力・耐久性要件","医療補助ロボット・食品ハンドリング・探査ロボット設計時","ソフトアクチュエータのエネルギー変換効率向上の限界はどこにあるか",
 "剛性ロボットアクチュエータ","ソフトロボット,シリコン,液晶エラストマー,空気圧,変形",
 "soft robot,silicone,liquid crystal elastomer,pneumatic,deformation",
 "active","secondary",78,6,
 "https://www.science.org/doi/10.1126/science.aal3735","欧米",0.78,
 r"シリコンビーム変形（Euler-Bernoulli）: $\delta = PL^3/(3EI)$、$I = bh^3/12$。空気圧バルーン収縮圧: $P = \frac{2\gamma}{r} + E_{wall}\frac{t(r-r_0)}{r_0^2}$（厚肉弾性殻）。",
 "url_present"),

("mat_b1_044","電気浸透・電気泳動材料輸送","Electroosmosis and Electrophoresis in Material Transport","Electrokinetic Material Transport Engineering",
 "マイクロ・ナノチャネルにおける電気浸透流・電気泳動による粒子分離・薬物送達・エネルギー変換の設計手法。Debye長・ゼータ電位・電気二重層の制御と診断チップ（Lab-on-chip）への統合を扱う。",
 "DNA電気泳動ゲル分析・マイクロ流体電気浸透ポンプ・がん細胞分離デバイスへの応用。",
 "材料工学・ナノテク","電気化学材料工学",1980,None,"method","バイオ医療・分析化学",
 "チャネルゼータ電位（>|20|mV）・イオン強度・電場強度","Lab-on-chip・DNA分析・細胞選別・薬物経皮送達時","高アスペクト比チャネルでの電気浸透流の均一性をどう保証するか",
 "機械ポンプ","電気浸透,電気泳動,Debye長,ゼータ電位,Lab-on-chip",
 "electroosmosis,electrophoresis,Debye length,zeta potential,Lab-on-chip",
 "active","secondary",78,8,
 "https://www.rsc.org/publishing/journals/microfluidicsnanofluidics/","欧米",0.78,
 r"Helmholtz-Smoluchowski電気浸透速度: $v_{eo} = -\frac{\varepsilon\zeta}{\mu}E$。Debye長: $\lambda_D = \sqrt{\varepsilon k_BT/(2n_0e^2)}$。電気泳動移動度: $\mu_{ep} = \frac{q}{6\pi\eta r}$（Stokes-Einstein）。",
 "url_present"),

("mat_b1_045","材料インフォマティクス基盤設計","Materials Informatics Platform Design","Materials Informatics Engineering",
 "機械学習・第一原理計算・高スループット実験を統合した材料インフォマティクスプラットフォームの設計手法。Materials Project・AFLOW・NOMAD等のDBと連携したGaussian Process・GNN材料予測パイプラインを扱う。",
 "新材料発見サイクルを年単位から月単位へ短縮。GoogleのGNoMEが220万の安定結晶構造を予測（2023年）。",
 "材料工学・ナノテク","計算材料科学",2011,None,"system","材料設計一般",
 "高品質実験データ・DFT計算基盤・予測モデルの不確実性定量化","新規機能性材料設計・組成最適化・特性予測時","GNoMEで予測された構造の実験実証率をどう効率化するか",
 "Trial-and-Error実験","材料インフォマティクス,GNN,Materials Project,高スループット,GNoME",
 "materials informatics,GNN,Materials Project,high-throughput,GNoME",
 "active","secondary",82,7,
 "https://www.nature.com/articles/s41586-023-06735-9","欧米",0.83,
 r"Gaussian Processサロゲート: $f(x)\sim GP(m(x),k(x,x'))$、獲得関数（EI）: $\alpha_{EI}(x) = (f^*-\mu(x))\Phi(z)+\sigma(x)\phi(z)$、$z=(f^*-\mu)/\sigma$。",
 "url_present"),

("mat_b1_046","透明導電膜設計","Transparent Conducting Oxide and Film Design","TCO Film Engineering",
 "ITO（インジウムスズ酸化物）・AZO（アルミニウム亜鉛酸化物）・金属メッシュ・導電性高分子（PEDOT）・銀ナノワイヤーを用いた透明導電膜の設計手法。可視光透過率・シート抵抗のトレードオフ最適化と代替材料開発。",
 "タッチパネル・OPV・OLED・ELシールドの不可欠材料。インジウム枯渇リスクでITO代替材料開発が急務。",
 "材料工学・ナノテク","光学材料工学",1970,None,"material","ディスプレイ・太陽電池・タッチパネル",
 "可視光透過率>85%・シート抵抗<10Ω/□・機械的フレキシビリティ要件","フレキシブルディスプレイ・OPV・タッチパネル設計時","ITO代替の銀ナノワイヤーのヘイズと導電性のトレードオフをどう管理するか",
 "金属電極","ITO,AZO,透明導電膜,銀ナノワイヤー,PEDOT",
 "ITO,AZO,transparent conductor,silver nanowire,PEDOT",
 "active","secondary",82,9,
 "https://www.nature.com/articles/nmat2635","東アジア",0.82,
 r"ITO性能: $T\cdot (R_{sh})^{-1/2}$（FOMスコア）。Drude伝導率: $\sigma = ne^2\tau/m^*$、電子濃度$n\sim10^{20}$cm$^{-3}$で$R_{sh} < 10\Omega/\square$。透過率-抵抗: $T = (1+188.5R_{sh}\sigma_\infty/\sigma_{DC})^{-2}$。",
 "url_present"),

("mat_b1_047","ゾル-ゲル法材料コーティング","Sol-Gel Process Coating Engineering","Sol-Gel Thin Film Design",
 "アルコキシドを原料としたゾル-ゲルプロセスによる酸化物薄膜（SiO2・TiO2・ZrO2・多成分系）の設計手法。加水分解・縮合反応制御・熱処理・多孔質構造設計とコーティング・ファイバー・バルクへの成形。",
 "光学反射防止コーティング・防汚撥水膜・触媒担体・バイオセラミックへの応用が広範。",
 "材料工学・ナノテク","セラミック材料工学",1970,None,"process","光学・触媒・医療",
 "アルコキシド濃度・pH・H2O/Si比（r値）・乾燥収縮制御","光学コーティング・多孔質材料・バイオセラミック設計時","ゾル-ゲルコーティングのクラック発生を最小化するための臨界膜厚設計は何か",
 "CVD/PVDコーティング","ゾル-ゲル,SiO2,TiO2,コーティング,多孔質",
 "sol-gel,SiO2,TiO2,coating,porous",
 "active","primary",80,9,
 "https://www.sciencedirect.com/science/article/pii/S0927796X09001011","欧米",0.8,
 r"加水分解速度: $r_{hyd} = k_{hyd}[Si(OR)_4][H_2O]^n$。クラック臨界厚: $h_c = K_{IC}/(E\varepsilon_0)$ [nm]（$K_{IC}$:破壊靭性、$\varepsilon_0$:乾燥ひずみ）。比表面積: $SA = 4r_{pore}^{-1}V_{pore}$ (BETより)。",
 "url_present"),

("mat_b1_048","電子線照射材料改質","Electron Beam Irradiation Material Modification","EB Irradiation Engineering",
 "電子線照射によるポリマー架橋・滅菌・食品保存・半導体製造（EBリソグラフィ）・複合材料硬化の材料改質手法。線量・エネルギー・線量率の設計と材料への影響（G値）評価を扱う。",
 "医療機器滅菌の標準プロセス（ISO 11137）。EBリソグラフィが5nm以下パターニングで最高分解能を維持。",
 "材料工学・ナノテク","放射線材料工学",1950,None,"process","医療・食品・半導体",
 "照射線量（kGy）・透過深度・材料の線量-応答特性（G値）評価","医療滅菌・食品保存・高分子架橋・EBリソグラフィ時","EBリソグラフィの近接効果補正を自動化する最新手法は何か",
 "ガンマ線滅菌","電子線照射,架橋,滅菌,EBリソグラフィ,G値",
 "electron beam irradiation,crosslinking,sterilization,EBL,G-value",
 "active","secondary",80,9,
 "https://ieeexplore.ieee.org/document/7386620","欧米",0.8,
 r"電子線架橋G値: $G_{crosslink} = \frac{\#crosslinks \times N_A}{100 eV \times \rho \times dose}$。EBリソグラフィ近接効果: $\rho_{exp}(r) = \frac{1}{\pi(1+\eta)}\left[\frac{1}{\beta_f^2}e^{-r^2/\beta_f^2}+\frac{\eta}{\beta_b^2}e^{-r^2/\beta_b^2}\right]$。",
 "url_present"),

("mat_b1_049","イオン交換膜材料設計","Ion Exchange Membrane Material Design","IEM Engineering",
 "燃料電池・電解水素製造・海水淡水化・レドックスフロー電池のためのイオン交換膜（Nafion・スルホン化PI・AEM）の設計手法。イオン伝導率・化学安定性・機械特性・選択透過性の最適化。",
 "PEFCのNafion膜が実用化標準。アニオン交換膜（AEM）電解槽で貴金属フリー触媒との組み合わせ研究が活発。",
 "材料工学・ナノテク","高分子材料工学",1970,None,"material","エネルギー・水処理",
 "プロトン/アニオン選択性・湿潤条件・電流密度・温度範囲","燃料電池・電解槽・海水淡水化・レドックス電池設計時","Nafionに代わる低コスト・高性能PEMの材料設計方向性は何か",
 "無機固体電解質","Nafion,イオン交換膜,AEM,PEM,燃料電池",
 "Nafion,ion exchange membrane,AEM,PEM,fuel cell",
 "active","secondary",82,8,
 "https://www.nature.com/articles/nenergy.2016.177","欧米",0.82,
 r"Grotthusプロトン伝導: $\sigma = n\mu e = \frac{ne^2\tau}{m^*}$（PEMでは$\sigma > 0.1$ S/cm@80°C）。溶媒和状態: $\lambda = H_2O$/SO$_3^-$、Nafionで$\lambda \sim 20-25$（完全加湿）。",
 "url_present"),

("mat_b1_050","磁場援用材料加工（MASP）","Magnetic Field Assisted Material Processing","MASP Engineering",
 "強磁場を利用した材料加工・凝固組織制御・電着・化学合成の設計手法。テスラ超強磁場中での粒子配向・析出制御・電解メッキ厚・磁気泳動を活用した高機能材料製造を扱う。",
 "CFRP繊維配向強化・単結晶成長制御・磁性粒子複合材の異方性付与に応用。高磁場センターでの研究が活発。",
 "材料工学・ナノテク","磁気材料工学",2000,None,"process","構造材料・電子材料",
 "超伝導磁石設備（>10T）・プロセス時間・材料磁気感受率","高機能材料の配向制御・析出強化・磁性複合材製造時","磁場援用の効果が他の加工因子（温度・圧力）と比較して独立に大きい材料系は何か",
 "通常凝固・電着プロセス","磁場援用加工,MASP,配向制御,強磁場,電着",
 "magnetic field assisted processing,MASP,alignment control,high field,electrodeposition",
 "active","secondary",75,5,
 "https://www.sciencedirect.com/science/article/pii/S1359645421008429","東アジア",0.8,
 r"磁場中粒子配向力: $F = \frac{V\Delta\chi}{2\mu_0}\nabla B^2$（$\Delta\chi$: 磁気感受率異方性、$V$: 粒子体積）。磁気泳動速度: $v = \frac{V\Delta\chi\nabla B^2}{6\pi\eta r\mu_0}$。",
 "url_present"),
]

if __name__ == "__main__":
    ins, skp = insert_records(records)
    print(f"Inserted: {ins}, Skipped: {skp}")
    import sqlite3 as _s
    c = _s.connect(DB).cursor()
    c.execute("SELECT COUNT(*) FROM engineering_method")
    print(f"Total: {c.fetchone()[0]}")
