import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("mat_b2_001","グラフェン合成法","Graphene Synthesis Methods","Graphene CVD/Exfoliation",
 "化学気相蒸着法(CVD)や機械的剥離法によりグラフェンを高品質合成する手法。単原子層炭素の電子・熱・機械特性を制御する。",
 "電子デバイス・センサー・複合材料の性能向上に貢献。2010年ノーベル物理学賞受賞技術の基盤。",
 "材料工学・ナノテク","ナノ材料工学",2004,None,"method","電子・複合材料",
 "清浄基板・制御雰囲気・精密温度管理","大面積均一薄膜が必要な場合",
 "CVD vs 剥離のトレードオフは?ドーピング制御は?","非晶質炭素膜","グラフェン,CVD合成,ナノ材料,二次元材料","graphene,CVD,nanosheet,2D material",
 "active","primary",90,7,"https://doi.org/10.1126/science.1158877","欧米",0.9,
 r"$E = \hbar v_F k$, $v_F \approx 10^6$ m/s (フェルミ速度)。CVD成長速度: $r = A \exp(-E_a/k_BT) \cdot p_{CH_4}$","url_present"),

("mat_b2_002","カーボンナノチューブ合成・分散","Carbon Nanotube Synthesis and Dispersion","CNT SWCNT MWCNT",
 "アーク放電・レーザー蒸発・CVD法によりSWCNT/MWCNTを合成し、界面活性剤や共有結合修飾で分散させる手法。",
 "複合材料強化・電気伝導体・ナノエレクトロニクスの基幹材料として産業応用が広がった。",
 "材料工学・ナノテク","ナノ材料工学",1991,None,"method","複合材料・電子",
 "触媒粒子径制御・合成雰囲気制御","高アスペクト比強化材が必要な場合",
 "カイラリティ制御は?バンドル解繊は?","バルク炭素繊維","カーボンナノチューブ,CNT,ナノ複合材料","carbon nanotube,CNT,nanocomposite",
 "active","primary",88,6,"https://doi.org/10.1038/354056a0","欧米",0.9,
 r"Young率 $E \approx 1$ TPa, 引張強度 $\sigma \approx 100$ GPa。熱伝導率 $\kappa > 3000$ W/(m·K)","url_present"),

("mat_b2_003","量子ドット蛍光材料設計","Quantum Dot Fluorescent Material Design","QD fluorescence engineering",
 "CdSe/ZnSやInP/ZnSなど半導体量子ドットのサイズ・組成・シェル構造を制御し、量子収率・安定性・発光波長を最適化する手法。",
 "ディスプレイ・照明・生体イメージングの色純度と輝度を飛躍的に向上させた。",
 "材料工学・ナノテク","ナノ材料工学",1993,None,"method","光学・ディスプレイ",
 "粒径均一性・表面パッシベーション制御","色純度・量子収率最大化が必要な場合",
 "重金属フリー代替は?フォトブリーチング防止は?","有機蛍光色素","量子ドット,蛍光材料,ナノ結晶","quantum dot,QD,fluorescence,nanocrystal",
 "active","primary",87,7,"https://doi.org/10.1126/science.281.5385.2013","欧米",0.9,
 r"Brus方程式: $E_g(r) = E_{g,bulk} + \frac{\hbar^2\pi^2}{2r^2}\left(\frac{1}{m_e^*}+\frac{1}{m_h^*}\right) - \frac{1.8e^2}{4\pi\epsilon\epsilon_0 r}$","url_present"),

("mat_b2_004","ペロブスカイト太陽電池プロセス設計","Perovskite Solar Cell Process Design","Perovskite PV ABX3",
 "ABX3型ペロブスカイト光吸収層のスピンコーティング・蒸着・印刷プロセスと界面パッシベーションにより高効率太陽電池を作製する手法。",
 "変換効率25%超を達成し、低コスト太陽電池の主要候補として研究開発が加速。",
 "材料工学・ナノテク","エネルギー材料工学",2009,None,"method","エネルギー変換",
 "湿度管理・界面制御・封止技術","低コスト高効率光電変換が必要な場合",
 "長期安定性確保は?Pb代替は?","従来Si太陽電池","ペロブスカイト,太陽電池,光電変換","perovskite,solar cell,ABX3,photovoltaics",
 "active","primary",89,6,"https://doi.org/10.1038/s41563-018-0115-4","欧米",0.9,
 r"PCE $= \frac{J_{sc} \cdot V_{oc} \cdot FF}{P_{in}}$。ショックレー-クワイサー限界 ~33%。$J_{sc}$改善: $E_g \approx 1.2-1.6$ eV最適","url_present"),

("mat_b2_005","高エントロピー合金組成探索","High Entropy Alloy Composition Search","HEA multi-principal element",
 "5種以上の主要元素を等モル比近傍で混合し、混合エントロピー最大化による単相固溶体安定化と優れた力学特性を実現する設計手法。",
 "CrMnFeCoNi系HEAが超低温・放射線環境での優れた靭性を示し、次世代構造材料として注目。",
 "材料工学・ナノテク","計算材料工学",2004,None,"method","構造材料",
 "VEC(価電子数)15~8範囲・CALPHAD計算支援","極限環境用高性能合金設計時",
 "微細組織制御は?加工性向上は?","従来合金鋼","高エントロピー合金,HEA,多主成分合金","HEA,high entropy alloy,multi-principal element",
 "active","primary",86,6,"https://doi.org/10.1016/j.actamat.2016.08.081","欧米",0.9,
 r"混合エントロピー: $\Delta S_{mix} = -R\sum_{i=1}^n c_i \ln c_i \geq 1.5R$ (等モル5成分)。VEC $= \sum c_i(VEC)_i$","url_present"),

("mat_b2_006","中国希土類分離精製技術","China Rare Earth Separation and Refification","Rare Earth Hydrometallurgy China",
 "中国が確立した溶媒抽出・イオン交換による希土類元素の高純度分離精製プロセス。バックストラクション段数最適化と混合抽出剤設計が核心技術。",
 "世界の希土類供給の85%以上を中国が担い、ハイテク産業のサプライチェーンに決定的影響を与えている。",
 "材料工学・ナノテク","希土類材料工学",1980,None,"method","資源・電子材料",
 "複数希土類元素の分離係数差活用","希土類高純度単体が必要な場合",
 "分離係数をさらに向上させるには?環境負荷低減は?","従来共沈法","希土類,溶媒抽出,分離精製,レアアース","rare earth,solvent extraction,separation,China",
 "active","primary",88,8,"https://doi.org/10.1016/j.hydromet.2014.02.011","東アジア",0.95,
 r"分配比: $D = [M]_{org}/[M]_{aq}$。分離係数: $\beta_{A/B} = D_A/D_B$。理論段数: $N = \frac{\ln(\beta \cdot (F-1)/F)}{\ln\beta}$","url_present"),

("mat_b2_007","金属積層造形プロセス最適化","Metal Additive Manufacturing Process Optimization","Metal AM SLM EBM DED",
 "選択的レーザー溶融(SLM)・電子ビーム溶融(EBM)・指向性エネルギー堆積(DED)の熱履歴・残留応力・ポロシティを制御し、ニアネットシェイプ部品を製造する手法。",
 "航空宇宙・医療インプラントの複雑形状部品製造を可能にし、材料歩留まりを大幅改善。",
 "材料工学・ナノテク","製造プロセス工学",2000,None,"method","航空宇宙・医療",
 "レーザーパワー・走査速度・層厚の最適化","複雑内部構造部品が必要な場合",
 "残留応力除去は?後処理HIPは?","鋳造・鍛造","金属積層造形,SLM,3Dプリント,残留応力","metal AM,SLM,EBM,additive manufacturing",
 "active","primary",88,7,"https://doi.org/10.1016/j.progpolymsci.2017.10.005","欧米",0.9,
 r"溶融池深さ: $d = \frac{2AP}{\pi v_s \rho C_p (T_m - T_0) \sqrt{\pi \alpha}}$。ポロシティ: $\phi \propto \exp(-P/(v_s \cdot h \cdot t))$","url_present"),

("mat_b2_008","鉄鋼TRIP効果設計","TRIP Steel Microstructure Design","Transformation Induced Plasticity Steel",
 "オーステナイト→マルテンサイト変態誘起塑性(TRIP)を利用した高強度・高延性鉄鋼の組成・熱処理設計手法。",
 "自動車軽量化に貢献する高強度鋼(980MPa級)の主要設計手法として自動車産業で広く採用。",
 "材料工学・ナノテク","鉄鋼材料工学",1967,None,"method","自動車・構造",
 "残留オーステナイト安定性制御・C/Si/Mn組成最適化","高強度・高成形性が必要な場合",
 "マルテンサイト変態開始温度Ms制御は?","高強度・低延性鋼","TRIP鋼,変態誘起塑性,高強度鋼","TRIP steel,transformation induced plasticity,AHSS",
 "active","primary",87,9,"https://doi.org/10.1016/S1359-6454(01)00051-4","欧米",0.9,
 r"Olson-Cohen変態速度論: $\dot{f} = \alpha \dot{\varepsilon}(1-f)\exp(-\beta f/\varepsilon)$。Ms = $512 - 453C - 16.9Ni + 15Cr - 9.5Mo$","url_present"),

("mat_b2_009","MOF多孔性材料合成設計","Metal-Organic Framework Synthesis Design","MOF porous coordination polymer",
 "金属イオンと有機リンカーの自己組織化により設計された多孔性金属有機構造体を合成し、比表面積・細孔径・機能基を精密制御する手法。",
 "ガス貯蔵・分離・触媒・薬物送達の革新的プラットフォームとして研究が急増。",
 "材料工学・ナノテク","機能性材料工学",1995,None,"method","ガス分離・触媒",
 "溶媒熱合成・pH制御・テンプレート法","高比表面積・選択的吸着が必要な場合",
 "水安定性向上は?スケールアップは?","ゼオライト","MOF,多孔性材料,金属有機構造体,ガス吸着","MOF,metal-organic framework,porous,gas storage",
 "active","primary",88,6,"https://doi.org/10.1126/science.1124439","欧米",0.9,
 r"BET比表面積: $\frac{1}{v[(p_0/p)-1]} = \frac{c-1}{v_m c}\frac{p}{p_0} + \frac{1}{v_m c}$。MOF-5: $S_{BET} > 3000$ m²/g","url_present"),

("mat_b2_010","日本磁石材料設計技術","Japan Rare Earth Magnet Design","Nd-Fe-B Sintered Magnet Japan",
 "住友特殊金属・TDK等が確立したNd-Fe-B系焼結磁石の配向焼結プロセスとDy添加による保磁力向上技術。モーター・発電機の高効率化を支える。",
 "EV・風力発電・ハードディスクの基幹材料。日本企業が世界の高性能磁石市場をリード。",
 "材料工学・ナノテク","磁性材料工学",1984,None,"method","電磁・エネルギー",
 "焼結雰囲気制御・配向磁場強度・Dy粒界拡散","高保磁力・高エネルギー積が必要な場合",
 "Dy代替技術は?熱安定性向上は?","フェライト磁石","Nd-Fe-B磁石,希土類磁石,保磁力,日本","Nd-Fe-B,rare earth magnet,coercivity,Japan",
 "active","primary",90,9,"https://doi.org/10.1016/j.jmmm.2011.08.028","東アジア",0.95,
 r"最大エネルギー積: $(BH)_{max} = \frac{B_r^2}{4\mu_0}$。$B_r \approx 1.4$ T, $H_{cJ} > 2400$ kA/m (Dy添加Nd-Fe-B)","url_present"),

("mat_b2_011","原子層堆積膜設計","Atomic Layer Deposition Film Design","ALD self-limiting growth",
 "前駆体の自己停止型表面反応を利用して原子層単位で膜厚・組成を制御するALDプロセスの設計手法。",
 "半導体High-k絶縁膜・バリア膜・コンフォーマルコーティングの標準技術として確立。",
 "材料工学・ナノテク","薄膜プロセス工学",1977,None,"method","半導体・コーティング",
 "前駆体飽和条件・パージ時間・温度ウィンドウ確認","サブnm精度の膜厚制御が必要な場合",
 "成長速度向上は?新規前駆体設計は?","CVD","ALD,原子層堆積,High-k,薄膜","ALD,atomic layer deposition,self-limiting,thin film",
 "active","primary",90,9,"https://doi.org/10.1016/j.jcrysgro.2007.07.012","欧米",0.9,
 r"GPC (成長速度/サイクル): 0.05–0.15 nm/cycle。温度ウィンドウ: $T_{min} < T < T_{max}$。膜厚 $d = n \cdot GPC$","url_present"),

("mat_b2_012","韓国二次電池電解質設計","Korea Li-ion Battery Electrolyte Design","Li-ion Electrolyte SEI Korea",
 "LiPF6/有機溶媒系電解質の添加剤設計によりSEI膜安定化・低温特性・安全性を向上させる技術。サムスン・LGが主導。",
 "EV・スマートフォン用高性能リチウムイオン電池の信頼性・エネルギー密度向上に直結。",
 "材料工学・ナノテク","電気化学材料工学",1991,None,"method","エネルギー貯蔵",
 "添加剤濃度最適化・SEI膜組成分析","サイクル寿命・安全性向上が必要な場合",
 "固体電解質への移行は?添加剤相乗効果は?","水系電解質","リチウムイオン電池,電解質,SEI,韓国","Li-ion battery,electrolyte,SEI,Korea",
 "active","primary",89,9,"https://doi.org/10.1021/acs.chemrev.8b00422","東アジア",0.95,
 r"Butler-Volmer式: $i = i_0\left[\exp\left(\frac{\alpha_a F\eta}{RT}\right) - \exp\left(-\frac{\alpha_c F\eta}{RT}\right)\right]$。SEI抵抗 $R_{SEI} < 50\ \Omega\cdot\text{cm}^2$","url_present"),

("mat_b2_013","耐熱セラミックスTBC設計","Thermal Barrier Coating Design","TBC YSZ bond coat",
 "イットリア安定化ジルコニア(YSZ)トップコートと金属ボンドコートからなる熱遮蔽コーティングの組成・微構造・残留応力設計手法。",
 "航空機エンジンのタービン入口温度を大幅に引き上げ、燃料効率と推力を向上。",
 "材料工学・ナノテク","高温材料工学",1970,None,"method","航空宇宙・エネルギー",
 "熱サイクル試験・スパレーション寿命評価","高温酸化・熱疲労環境での耐久性が必要な場合",
 "熱伝導率さらなる低減は?CMAS腐食対策は?","無コーティング超合金","TBC,熱遮蔽コーティング,YSZ,タービン","TBC,thermal barrier coating,YSZ,turbine",
 "active","primary",88,8,"https://doi.org/10.1016/j.actamat.2007.09.045","欧米",0.9,
 r"TBC熱伝導率: $\kappa_{YSZ} \approx 2.0$ W/(m·K)。フーリエ則: $q = -\kappa \nabla T$。フロー温度差: $\Delta T = q \cdot t/\kappa$","url_present"),

("mat_b2_014","形状記憶合金アクチュエータ設計","Shape Memory Alloy Actuator Design","SMA NiTi superelastic",
 "NiTi(ニチノール)合金のマルテンサイト変態温度・回復応力・変態歪みを組成・熱処理で制御し、アクチュエータ・医療デバイスに応用する手法。",
 "ステント・カテーテル・医療ロボットに不可欠な機能材料として産業的重要性が高い。",
 "材料工学・ナノテク","機能性材料工学",1963,None,"method","医療・ロボット",
 "Af温度・回復応力・低サイクル疲労評価","体温駆動アクチュエーション・超弾性が必要な場合",
 "変態回数劣化対策は?Cu-Al-Mn代替は?","圧電アクチュエータ","形状記憶合金,NiTi,超弾性,アクチュエータ","SMA,NiTi,shape memory alloy,superelastic",
 "active","primary",88,8,"https://doi.org/10.1016/j.pmatsci.2005.08.001","欧米",0.9,
 r"変態エンタルピー: $\Delta H \approx 20-30$ J/g。Clausius-Clapeyron: $\frac{dT}{d\sigma} = -\frac{T_0 \varepsilon_0}{\Delta H}$","url_present"),

("mat_b2_015","有機薄膜太陽電池バルクヘテロジャンクション設計","Organic Solar Cell BHJ Design","OPV bulk heterojunction morphology",
 "電子供与体・受容体の相溶性・ドメイン寸法・結晶性を溶媒添加剤・熱処理で制御し、エクシトン解離効率とキャリア移動度を最大化する手法。",
 "印刷プロセス対応の柔軟太陽電池として研究が進み、PCE18%超を達成する非フラーレン系が台頭。",
 "材料工学・ナノテク","有機材料工学",1995,None,"method","エネルギー変換",
 "溶媒添加剤・アニール条件・活性層膜厚最適化","印刷可能フレキシブル太陽電池が必要な場合",
 "安定性向上は?タンデム構造との組合せは?","無機太陽電池","有機太陽電池,バルクヘテロジャンクション,非フラーレン","OPV,organic solar cell,bulk heterojunction,non-fullerene",
 "active","primary",85,5,"https://doi.org/10.1038/s41563-021-01219-z","欧米",0.9,
 r"Shockley-Queisser: $PCE_{max} \approx 33\%$。Marcus電子移動: $k_{ET} = \frac{2\pi}{\hbar}|H_{AB}|^2\frac{1}{\sqrt{4\pi\lambda k_BT}}\exp\left(-\frac{(\Delta G+\lambda)^2}{4\lambda k_BT}\right)$","url_present"),

("mat_b2_016","台湾半導体パッケージング技術","Taiwan Advanced Semiconductor Packaging","CoWoS InFO 2.5D 3D IC TSMC",
 "TSMCが開発したCoWoS(Chip-on-Wafer-on-Substrate)・InFO(Integrated Fan-Out)による2.5D/3D集積パッケージング技術。RDL設計と熱管理が核心。",
 "AI加速器・スマートフォンSoCの性能・消費電力比を飛躍的に向上。Appleが採用し普及加速。",
 "材料工学・ナノテク","半導体パッケージング",2012,None,"method","半導体",
 "熱膨張係数マッチング・RDL設計・バンプピッチ微細化","帯域幅・電力効率最大化が必要な場合",
 "チップレット異種集積は?熱抵抗低減は?","従来ワイヤボンディング","半導体パッケージング,CoWoS,3D IC,台湾","CoWoS,InFO,advanced packaging,chiplet,Taiwan",
 "active","primary",90,9,"https://doi.org/10.1109/ECTC.2016.319","東アジア",0.95,
 r"熱抵抗: $\theta_{JA} = \theta_{JC} + \theta_{CA}$。バンプ接続抵抗: $R_{bump} = \rho L/A$。帯域幅: $BW \propto N_{TSV}/L$","url_present"),

("mat_b2_017","スピントロニクスMRAM設計","Spintronics MRAM Design","STT-MRAM MTJ spin transfer",
 "スピン移行トルク(STT)によるトンネル磁気抵抗(TMR)素子の磁化反転を利用したMRAMセル設計。CoFeB/MgO/CoFeB磁気トンネル接合の最適化が鍵。",
 "IoT・組み込みAIの不揮発性メモリとして、従来SRAMの低消費電力代替として実用化が進む。",
 "材料工学・ナノテク","スピントロニクス",2000,None,"method","半導体・メモリ",
 "TMR比・スイッチング電流・リテンション評価","不揮発・高速・低電力メモリが必要な場合",
 "SOT-MRAMへの移行は?熱安定性指標は?","SRAM","スピントロニクス,MRAM,STT,磁気トンネル接合","MRAM,STT,spintronics,magnetic tunnel junction",
 "active","primary",88,7,"https://doi.org/10.1038/nnano.2013.29","欧米",0.9,
 r"TMR比: $TMR = \frac{R_{AP}-R_P}{R_P} = \frac{2P_1P_2}{1-P_1P_2}$。熱安定性: $\Delta = K_u V/k_BT > 40$","url_present"),

("mat_b2_018","セラミック射出成形技術","Ceramic Injection Molding","CIM PIM powder injection",
 "セラミック粉末とバインダーを混練しインジェクション成形した後、脱脂・焼結して複雑形状セラミック部品を製造する手法。",
 "医療・電子・自動車部品の複雑形状セラミック部品を低コスト・大量生産可能にした。",
 "材料工学・ナノテク","セラミックス工学",1980,None,"method","製造・医療",
 "バインダー配合・脱脂プロファイル・焼結収縮制御","複雑形状高硬度部品が必要な場合",
 "寸法精度向上は?バインダー残留除去は?","プレス成形","セラミック射出成形,CIM,粉末射出成形","CIM,ceramic injection molding,sintering",
 "active","primary",85,8,"https://doi.org/10.1007/s10853-011-5988-7","欧米",0.85,
 r"焼結収縮率 $\sim 15-20\%$。粒成長モデル: $G^n - G_0^n = Kt$, $n=2-4$。相対密度目標 $\rho/\rho_0 > 0.98$","url_present"),

("mat_b2_019","バイオミメティック構造材料設計","Biomimetic Structural Material Design","nacre bone hierarchical structure",
 "貝殻(アラゴナイト積層)・骨(コラーゲン/ハイドロキシアパタイト階層)の階層構造を模倣し、高強度・高靭性の複合材料を設計する手法。",
 "セラミックスの脆性を克服する「タフネス倍増」戦略として先端防弾・航空宇宙材料に応用。",
 "材料工学・ナノテク","バイオミメティクス",1990,None,"method","複合材料・防弾",
 "界面接着強度・積層構造制御・欠陥導入設計","軽量高靭性が必要な場合",
 "スケールアップ製造は?界面摩擦制御は?","均質セラミックス","バイオミメティクス,階層構造,貝殻,骨","biomimetics,nacre,bone,hierarchical structure",
 "active","primary",86,5,"https://doi.org/10.1126/science.1154705","欧米",0.9,
 r"Griffith破壊靭性: $K_{IC} = Y\sigma\sqrt{\pi a}$。積層複合体: $K_{IC,comp} = K_{IC,0}(1 + \xi\cdot\phi_{brick})$","url_present"),

("mat_b2_020","電気化学インピーダンス分光","Electrochemical Impedance Spectroscopy","EIS Nyquist Bode analysis",
 "電気化学系に微小交流電圧を印加し、周波数依存インピーダンスを計測して界面反応・拡散・電荷移動過程を分離解析する手法。",
 "電池・燃料電池・腐食・電気めっきの劣化メカニズム解明と品質管理に不可欠なキャラクタリゼーション技術。",
 "材料工学・ナノテク","電気化学材料工学",1970,None,"method","電気化学",
 "等価回路モデル・周波数範囲設定・擾乱振幅制御","界面反応を非破壊解析する場合",
 "等価回路の非一意性問題は?固体電解質への適用は?","直流分極法","電気化学インピーダンス,EIS,Nyquist図,等価回路","EIS,impedance spectroscopy,Nyquist,equivalent circuit",
 "active","primary",88,9,"https://doi.org/10.1016/j.electacta.2019.01.181","欧米",0.9,
 r"インピーダンス: $Z(\omega) = Z'(\omega) - jZ''(\omega)$。Randles回路: $Z = R_s + \frac{R_{ct}}{1+j\omega R_{ct}C_{dl}} + Z_W$","url_present"),

("mat_b2_021","中国カーボンファイバー国産化","China Carbon Fiber Indigenization","T800 T1000 carbon fiber China COMAC",
 "中国がCOMACのC919・C929向けに進めるT800/T1000グレード炭素繊維の国産化プロジェクト。PAN前駆体の高純度化・炭化炉精度向上が核心。",
 "中国の航空宇宙・防衛産業の自立化に直結する戦略的材料技術。2025年以降の国産化率向上が目標。",
 "材料工学・ナノテク","複合材料工学",2010,None,"method","航空宇宙・国防",
 "PAN繊維品質・炭化温度プロファイル・表面処理制御","航空機構造材料の国産化が必要な場合",
 "東レT800との品質差縮小は?プリプレグ国産化は?","炭素繊維輸入依存","炭素繊維,PAN,国産化,中国,航空宇宙","carbon fiber,PAN,indigenization,China,COMAC",
 "active","primary",87,7,"https://doi.org/10.1016/j.compositesa.2019.105679","東アジア",0.95,
 r"引張強度: $\sigma_T > 5.5$ GPa (T800相当)。弾性率: $E > 294$ GPa。$\text{LOI}=(\%O_2+\%N_2\cdot0.67)/100$","url_present"),

("mat_b2_022","水素脆化防止鋼設計","Hydrogen Embrittlement Prevention Steel Design","HE HELP HEDE steel",
 "水素トラップサイト(炭化物・逆位相境界)の制御とMs温度・残留オーステナイト量の最適化により水素脆化感受性を低減する鋼材設計手法。",
 "水素貯蔵タンク・燃料電池車部品・高圧配管の信頼性を確保するために不可欠な技術。",
 "材料工学・ナノテク","鉄鋼材料工学",1960,None,"method","エネルギー・構造",
 "水素侵入量評価・拡散係数測定・トラップエネルギー計算","水素環境での高強度鋼使用時",
 "可逆・不可逆トラップの区別は?内部水素vs外部水素は?","耐水素脆化合金","水素脆化,鋼材,トラップサイト,水素エネルギー","hydrogen embrittlement,steel,trap site,hydrogen energy",
 "active","primary",87,7,"https://doi.org/10.1016/j.actamat.2012.01.038","欧米",0.9,
 r"水素拡散: $J = -D_{eff}\nabla C_H$。トラップ結合エネルギー: $E_{trap} = RT\ln(K_T)$。臨界水素濃度: $C_{crit} \approx 0.1-1$ ppm","url_present"),

("mat_b2_023","機能性ポリマー超分子設計","Supramolecular Polymer Design","host-guest hydrogen bond dynamic covalent",
 "水素結合・ホスト-ゲスト相互作用・金属配位による可逆的な超分子相互作用を利用した自己修復・刺激応答性ポリマーの設計手法。",
 "自己修復コーティング・薬物放出・ソフトロボットの新材料として注目。",
 "材料工学・ナノテク","高分子材料工学",1990,None,"method","コーティング・医療",
 "結合エネルギー・交換速度・機械特性バランス設計","動的結合による自己修復が必要な場合",
 "修復速度と強度のトレードオフは?マルチ刺激応答は?","従来熱硬化性樹脂","超分子ポリマー,自己修復,水素結合,ビトリマー","supramolecular polymer,self-healing,hydrogen bond,vitrimers",
 "active","primary",85,5,"https://doi.org/10.1038/nmat4704","欧米",0.9,
 r"結合エネルギー目安: H結合 $\Delta G \approx 5-65$ kJ/mol, 配位結合 $\approx 30-200$ kJ/mol。修復効率: $\eta = E_{after}/E_{before} \times 100\%$","url_present"),

("mat_b2_024","無機ペロブスカイト光触媒設計","Inorganic Perovskite Photocatalyst Design","BiVO4 g-C3N4 Z-scheme photocatalysis",
 "バンドエンジニアリングと異種接合(Z-スキーム)により、可視光応答性光触媒の電荷分離効率と酸化還元電位を同時最適化する設計手法。",
 "水分解・CO2還元・環境浄化への太陽光エネルギー利用の基盤技術として世界的に研究が活発。",
 "材料工学・ナノテク","エネルギー材料工学",1972,None,"method","エネルギー変換・環境",
 "バンドギャップ・フラットバンド電位・キャリア寿命評価","太陽光駆動化学変換が必要な場合",
 "量子効率向上は?スケールアップ反応器設計は?","電気分解","光触媒,水分解,Z-スキーム,バンドエンジニアリング","photocatalysis,water splitting,Z-scheme,band engineering",
 "active","primary",86,5,"https://doi.org/10.1039/C4CS00500G","欧米",0.9,
 r"Nernst式: $E = E^0 - \frac{RT}{nF}\ln Q$。量子収率: $\Phi = \frac{\text{反応分子数}}{\text{吸収光子数}}$。$E_{CB} < E_{H_2/H_2O} = 0\ \text{V vs NHE}$","url_present"),

("mat_b2_025","炭素繊維強化プラスチック成形プロセス","CFRP Molding Process Design","autoclave RTM filament winding CFRP",
 "オートクレーブ・RTM(樹脂トランスファー成形)・フィラメントワインディングによるCFRPの繊維配向・繊維体積率・空孔率を制御する成形プロセス設計。",
 "航空機・自動車・スポーツ用品の軽量化の主役技術として確立。Boeing787・Airbus A350で採用。",
 "材料工学・ナノテク","複合材料工学",1965,None,"method","航空宇宙・自動車",
 "プリプレグ積層設計・硬化サイクル最適化・NDI検査","高比強度・比剛性部品が必要な場合",
 "OOA(オートクレーブ外硬化)への移行は?リサイクル性は?","金属構造材","CFRP,炭素繊維強化プラスチック,RTM,積層設計","CFRP,carbon fiber,autoclave,RTM,composite",
 "active","primary",90,9,"https://doi.org/10.1016/j.compositesa.2020.105741","欧米",0.9,
 r"クラシック積層理論: $[A,B,D]$ マトリクス。剛性: $A_{ij} = \sum_k \bar{Q}_{ij}^{(k)} h_k$。破壊: Tsai-Wu基準 $F_1\sigma_1 + F_{11}\sigma_1^2 + 2F_{12}\sigma_1\sigma_2 + ... \leq 1$","url_present"),

("mat_b2_026","超臨界流体プロセス","Supercritical Fluid Process Design","scCO2 extraction impregnation",
 "CO2・水の臨界点以上の超臨界流体の高溶解性・低粘度・高拡散性を利用した抽出・乾燥・含浸・粒子生成プロセスの設計手法。",
 "医薬品・食品・材料製造の環境負荷低減と機能性向上に貢献。エアロゲル製造の基盤技術。",
 "材料工学・ナノテク","化学工学プロセス",1982,None,"method","製薬・食品・材料",
 "臨界温度・圧力管理・密度制御","溶媒フリー処理・ナノ粒子生成が必要な場合",
 "コスト削減は?混合溶媒添加量は?","有機溶媒抽出","超臨界流体,scCO2,エアロゲル,ナノ粒子","supercritical fluid,scCO2,aerogel,nanoparticle",
 "active","primary",85,7,"https://doi.org/10.1016/j.supflu.2012.01.005","欧米",0.85,
 r"van der Waals方程式: $(P+a/V_m^2)(V_m - b) = RT$。臨界点 CO2: $T_c=304.1$ K, $P_c=7.38$ MPa","url_present"),

("mat_b2_027","フォノニクス熱制御設計","Phononic Crystal Thermal Control","phononic crystal thermal conductivity",
 "周期的な密度・弾性定数変調によりフォノン伝播を制御し、熱伝導率の異方性制御・熱整流・フォノニックバンドギャップを実現する材料設計手法。",
 "電子冷却・熱電変換効率向上・熱管理の新原理として注目される基礎研究。",
 "材料工学・ナノテク","熱材料工学",2000,None,"method","熱管理・エネルギー",
 "格子周期と波長マッチング・界面散乱最大化","ナノスケール熱流制御が必要な場合",
 "実用スケールへのスケールアップは?製造可能性は?","均質材料","フォノニクス,熱伝導率制御,フォノニック結晶","phononic crystal,thermal control,heat management",
 "active","primary",82,4,"https://doi.org/10.1103/PhysRevLett.79.3294","欧米",0.9,
 r"格子熱伝導率: $\kappa = \frac{1}{3}C_v v_s \ell$。フォノン散乱: $\frac{1}{\tau} = \frac{1}{\tau_N} + \frac{1}{\tau_U} + \frac{1}{\tau_{imp}}$","url_present"),

("mat_b2_028","磁性流体・磁気応答ソフト材料設計","Ferrofluid and Magneto-responsive Soft Material Design","MRE magnetorheological fluid",
 "磁性ナノ粒子を分散させたスマート流体(MRF)や弾性体(MRE)の磁場応答性レオロジー・弾性率変化を設計し、振動制御・ダンパーに応用する手法。",
 "車両サスペンション・医療デバイス・精密機器の振動抑制に実用化。",
 "材料工学・ナノテク","機能性材料工学",1948,None,"method","振動制御・医療",
 "粒子粒径・界面活性剤・磁場強度設計","外部磁場制御可能なスマートダンパーが必要な場合",
 "沈降安定性向上は?粒子クラスタリング防止は?","従来ダンパー","磁性流体,MRF,磁気応答材料,スマート材料","ferrofluid,MRF,magnetorheological,smart material",
 "active","primary",84,8,"https://doi.org/10.1016/S0065-2156(08)70295-9","欧米",0.85,
 r"Bingham流体: $\tau = \tau_y(H) + \eta\dot{\gamma}$。降伏応力: $\tau_y \propto \mu_0\phi M_s^2/d$","url_present"),

("mat_b2_029","日本CFRP自動車構造設計","Japan CFRP Automotive Structure Design","CFRP monocoque Japan Toray Teijin",
 "東レ・帝人がHonda NSX・BMW i3等と共同開発したCFRPモノコック・ルーフの高速成形(RTM/HP-RTM)と接着接合技術。",
 "量産車への適用で車体軽量化30-50%を実現。日本の素材・製造技術が世界の自動車産業をリード。",
 "材料工学・ナノテク","複合材料工学",2005,None,"method","自動車",
 "サイクルタイム短縮・接着接合強度・コスト削減","量産CFRP部品が必要な場合",
 "リサイクル循環系構築は?接着剤劣化評価は?","アルミ車体","CFRP,自動車,東レ,帝人,RTM,軽量化","CFRP automotive,Toray,Teijin,HP-RTM,lightweight",
 "active","primary",88,8,"https://doi.org/10.1016/j.compositesa.2019.04.030","東アジア",0.95,
 r"比剛性: $E/\rho \approx 38$ GPa/(g/cm³) (CFRP vs 鋼 25, Al 25.5)。HP-RTMサイクル: $t_{cycle} < 5$ min","url_present"),

("mat_b2_030","コンクリート高耐久化設計","High Durability Concrete Design","HPC UHPC supplementary cementitious",
 "フライアッシュ・スラグ・シリカフュームの補助セメント材料と水セメント比低減・アルカリ骨材反応抑制によりコンクリートの長期耐久性を向上させる設計手法。",
 "橋梁・トンネル・海洋構造物の設計寿命延長(100年超)と維持管理コスト大幅削減に貢献。",
 "材料工学・ナノテク","セメント・コンクリート工学",1970,None,"method","土木・建築",
 "水/結合材比≤0.35・養生条件・暴露環境評価","塩害・中性化・凍害環境での長寿命化が必要な場合",
 "アルカリ骨材反応完全抑制は?UHPC経済性は?","普通コンクリート","高耐久コンクリート,UHPC,フライアッシュ,ASR抑制","HPC,UHPC,durability,supplementary cementitious",
 "active","primary",87,9,"https://doi.org/10.1016/j.cemconres.2011.04.012","欧米",0.9,
 r"圧縮強度 UHPC: $f'_c > 150$ MPa。塩化物拡散: $C(x,t) = C_s\left[1-\text{erf}\left(\frac{x}{2\sqrt{D_a t}}\right)\right]$","url_present"),

("mat_b2_031","光学薄膜多層設計","Optical Thin Film Multilayer Design","antireflection high-reflectance filter coating",
 "TiO2/SiO2等の高屈折率・低屈折率材料を交互積層し、干渉効果により反射防止・高反射・バンドパスフィルターを実現する多層光学薄膜設計手法。",
 "カメラ・眼鏡・天文望遠鏡・レーザー光学系の性能に不可欠な精密光学コーティング技術。",
 "材料工学・ナノテク","光学材料工学",1935,None,"method","光学・精密機器",
 "膜厚均一性・屈折率・吸収損失制御","特定波長域の反射率・透過率設計が必要な場合",
 "広帯域化は?レーザー耐性向上は?","バルク光学素子","光学薄膜,AR coating,干渉フィルター,多層膜","optical thin film,AR coating,interference filter,multilayer",
 "active","primary",88,9,"https://doi.org/10.1364/OL.27.000120","欧米",0.9,
 r"反射率(単層AR): $R = \left(\frac{n_1-n_0n_2/n_1}{n_1+n_0n_2/n_1}\right)^2$。最適: $n_1 = \sqrt{n_0 n_2}$, $d = \lambda/4n_1$","url_present"),

("mat_b2_032","ゾルゲル機能コーティング設計","Sol-Gel Functional Coating Design","sol-gel hydrolysis condensation",
 "金属アルコキシドの加水分解・縮合反応によりSiO2・TiO2・ZrO2系機能性薄膜を低温プロセスで製膜する手法。","耐スクラッチ・防汚・光触媒・抗菌コーティングとして建材・光学・医療に広く応用。",
 "材料工学・ナノテク","表面・コーティング工学",1960,None,"method","表面処理・光学",
 "前駆体濃度・pH・乾燥焼成条件制御","低温プロセスでの機能性薄膜が必要な場合",
 "クラック発生防止は?有機-無機ハイブリッド化は?","CVD","ゾルゲル,コーティング,TiO2,機能性薄膜","sol-gel,coating,TiO2,functional film",
 "active","primary",85,8,"https://doi.org/10.1016/j.jnoncrysol.2007.01.067","欧米",0.85,
 r"加水分解: $\equiv Si-OR + H_2O \rightarrow \equiv Si-OH + ROH$。縮合: $\equiv Si-OH + HO-Si\equiv \rightarrow \equiv Si-O-Si\equiv + H_2O$","url_present"),

("mat_b2_033","多孔質シリコン製造・応用","Porous Silicon Fabrication and Application","PSi electrochemical etching photoluminescence",
 "電気化学的エッチングによりシリコンに制御された多孔質構造を形成し、フォトルミネッセンス・バイオセンサー・薬物送達・リチウム電池負極への応用を展開する手法。",
 "バンドギャップエンジニアリングによる光学特性制御と生体適合性から生体センサーへの実用化が進む。",
 "材料工学・ナノテク","半導体材料工学",1956,None,"method","センサー・医療",
 "電流密度・HF濃度・照明条件の精密制御","ナノ構造Si特性活用が必要な場合",
 "機械的脆弱性克服は?表面酸化安定化は?","バルクSi","多孔質シリコン,フォトルミネッセンス,バイオセンサー","porous silicon,PSi,photoluminescence,biosensor",
 "active","primary",83,6,"https://doi.org/10.1038/nature01086","欧米",0.85,
 r"多孔率: $P = 1 - \rho_{PSi}/\rho_{Si}$。Bethe格子: $\kappa \propto P^{1.5}$。発光ピーク: $E_{PL} \propto 1/d^2$","url_present"),

("mat_b2_034","エポキシ複合材料界面設計","Epoxy Composite Interface Design","sizing agent fiber matrix interface",
 "炭素繊維・ガラス繊維表面のサイジング剤とエポキシマトリクスの界面結合力を最大化するための表面処理・カップリング剤・サイジング配合設計手法。",
 "CFRP・GFRPの層間せん断強度と疲労特性の向上に不可欠な基礎技術として確立。",
 "材料工学・ナノテク","複合材料工学",1970,None,"method","複合材料",
 "接触角・IFSS測定・サイジング加熱減量評価","繊維/マトリクス界面強度最大化が必要な場合",
 "ナノ粒子界面強化との組合せは?","未処理繊維","界面設計,サイジング,カップリング剤,IFSS","interface design,sizing agent,coupling agent,IFSS",
 "active","primary",86,8,"https://doi.org/10.1016/j.compositesa.2019.02.033","欧米",0.9,
 r"界面せん断強度(IFSS) Kelly-Tyson: $\tau_i = F_{max}/(2\pi r l_c)$。臨界繊維長: $l_c = \sigma_f d/(2\tau_i)$","url_present"),

("mat_b2_035","誘電体セラミック設計","Dielectric Ceramic Design","BaTiO3 MLCC PZT ferroelectric",
 "BaTiO3・PZT系強誘電体セラミックスの組成・ドープ・微細組織制御により誘電率・圧電定数・絶縁性を最適化する設計手法。",
 "MLCCはスマートフォン1台に1000個超搭載。PZTアクチュエータはインクジェット・医用超音波の核心。",
 "材料工学・ナノテク","電子セラミックス工学",1950,None,"method","電子・医療",
 "焼成温度・ドーパント濃度・粒径制御","高誘電率・圧電特性が必要な場合",
 "Pb-free化は?低温焼結は?","電解コンデンサ","誘電体セラミックス,BaTiO3,MLCC,PZT","dielectric ceramic,BaTiO3,MLCC,PZT,ferroelectric",
 "active","primary",90,9,"https://doi.org/10.1016/j.jeurceramsoc.2014.02.006","欧米",0.9,
 r"誘電率: $\epsilon_r \sim 10^4$ (BaTiO3 Tc付近)。圧電定数: $d_{33} = 2\epsilon_0\epsilon_r \cdot Q_{11} \cdot P_s$","url_present"),

("mat_b2_036","韓国ディスプレイOLED材料設計","Korea OLED Display Material Design","OLED emitter host TADF thermally activated","韓国サムスン・LGが主導するOLEDディスプレイ向け蛍光・燐光・TADF発光材料の分子設計とデバイス積層最適化技術。",
 "有機ELスマートフォン・テレビの普及を牽引。TADFによる100%内部量子効率の実現で重金属フリー化が加速。",
 "材料工学・ナノテク","有機材料工学",1987,None,"method","ディスプレイ",
 "HOMO/LUMOレベル設計・スピン多重度制御","高効率有機発光材料が必要な場合",
 "長寿命化は?青色TADF材料は?","LCD","OLED,TADF,発光材料,有機EL,韓国","OLED,TADF,emitter,organic EL,Korea",
 "active","primary",90,9,"https://doi.org/10.1038/nature12116","東アジア",0.95,
 r"TADF速度論: $k_{TADF} = k_{RISC}\cdot\Phi_{ISC}$。内部QY: $\Phi_{PL} = k_r/(k_r+k_{nr})$。$\Delta E_{ST} < 0.1$ eV必須","url_present"),

("mat_b2_037","超伝導線材設計","Superconducting Wire Design","HTS REBCO BSCCO coated conductor",
 "REBCO(希土類バリウム銅酸化物)・BSCCO系高温超伝導線材のRABiTS/IBAD基板・バッファ層・超伝導層の結晶配向と臨界電流密度を最大化する設計技術。",
 "MRI・加速器・超伝導送電・核融合炉の実現に不可欠な基幹材料技術。",
 "材料工学・ナノテク","超伝導材料工学",1986,None,"method","エネルギー・医療",
 "in-plane配向度・ピン止め欠陥導入・磁場中Ic評価","液体窒素温度での大電流輸送が必要な場合",
 "機械強度向上は?交流損失低減は?","液体He超伝導","高温超伝導,REBCO,コーテッドコンダクター,臨界電流","HTS,REBCO,coated conductor,critical current",
 "active","primary",88,5,"https://doi.org/10.1088/0953-2048/26/9/093001","欧米",0.9,
 r"Jc-B特性: $J_c(B) = J_{c0}(b/B_0)^{-\alpha}$。ピン止め力: $F_p = J_c \times B$。GL理論: $\kappa = \lambda/\xi$","url_present"),

("mat_b2_038","生分解性ポリマー設計","Biodegradable Polymer Design","PLA PHB PCL hydrolysis degradation",
 "ポリ乳酸(PLA)・PHB・PCLの分子量・結晶化度・共重合組成を制御し、機械特性と生分解速度を同時最適化するバイオポリマー設計手法。",
 "医療用縫合糸・薬物送達・プラスチック代替として持続可能社会の基幹材料。",
 "材料工学・ナノテク","バイオ材料工学",1985,None,"method","医療・環境",
 "分子量分布・結晶性・加水分解速度評価","生体内分解・環境分解が必要な場合",
 "機械強度と分解速度の両立は?コスト削減は?","石油系プラスチック","生分解性ポリマー,PLA,PHB,バイオプラスチック","biodegradable polymer,PLA,PHB,bioplastics",
 "active","primary",85,7,"https://doi.org/10.1016/j.progpolymsci.2008.06.002","欧米",0.85,
 r"加水分解速度: $-\frac{d[COOH]}{dt} = k[H_2O][COOH]^n$。Mn低下: $\ln(Mn/Mn_0) = -k_h t$","url_present"),

("mat_b2_039","核融合炉第一壁材料設計","Fusion Reactor First Wall Material Design","W Be PFC plasma facing material",
 "ITERのタングステン・ベリリウムプラズマ対向材料の熱負荷・粒子フラックス・中性子照射に対する再結晶・スパッタリング・スウェリング耐性を設計する手法。",
 "ITER・DEMOの実現に向けて国際協力で進む世界最先端材料開発。中国・日本・欧州が主要貢献国。",
 "材料工学・ナノテク","核融合材料工学",1990,None,"method","エネルギー",
 "中性子照射量・熱負荷・スパッタ収率評価","プラズマ対向環境での耐久性が必要な場合",
 "高フラックス試験施設でのスクリーニングは?","ステンレス鋼","核融合炉,タングステン,プラズマ対向材料,ITER","fusion reactor,W,plasma facing material,ITER",
 "active","primary",85,4,"https://doi.org/10.1016/j.jnucmat.2007.01.010","欧米",0.9,
 r"熱流束: $q = h_c(T_s - T_{coolant})$。スパッタ収率: $S \propto (E - E_{th})^{0.5}$。照射硬化: $\Delta\sigma_y = \alpha\mu b\sqrt{N d}$","url_present"),

("mat_b2_040","光ファイバー製造設計","Optical Fiber Manufacturing Design","MCVD OVD VAD silica preform",
 "変性化学気相蒸着(MCVD)・OVD・VAD法によりGeO2ドープSiO2プリフォームを作製し、線引きにより低損失・分散制御光ファイバーを製造する設計手法。",
 "インターネット通信インフラの基盤技術。シングルモードファイバーの損失0.15dB/km実現が世界通信革命を可能にした。",
 "材料工学・ナノテク","光学材料工学",1970,None,"method","通信・センサー",
 "プリフォーム屈折率プロファイル・線引速度・コーティング設計","超低損失・大容量光通信が必要な場合",
 "マルチコアファイバー設計は?非線形効果抑制は?","銅線通信","光ファイバー,VAD,シリカ,分散制御","optical fiber,VAD,silica,preform,single mode",
 "active","primary",90,9,"https://doi.org/10.1364/OL.1.000182","欧米",0.9,
 r"伝搬損失: $\alpha = A/\lambda^4 + B$ (Rayleigh散乱+IR吸収)。最低損失 $\sim 0.15$ dB/km at 1550 nm。数値開口: $NA = \sqrt{n_1^2 - n_2^2}$","url_present"),

("mat_b2_041","チタン合金冶金設計","Titanium Alloy Metallurgical Design","Ti-6Al-4V alpha-beta microstructure",
 "Ti-6Al-4V等α+β型チタン合金の相変態・結晶粒微細化・テクスチャ制御による強度-延性-疲労バランス最適化設計手法。",
 "航空機機体・エンジン・医療インプラントの必須軽量高強度材料として確立。Boeing787の約15%がTi合金。",
 "材料工学・ナノテク","金属材料工学",1954,None,"method","航空宇宙・医療",
 "相分率・Widmanstätten組織・β変態温度評価","高比強度・生体適合性が必要な場合",
 "粉末AM加工との組合せは?ELI(Extra Low Interstitial)化は?","ステンレス鋼","チタン合金,Ti-6Al-4V,航空宇宙,医療インプラント","titanium alloy,Ti-6Al-4V,aerospace,biomedical",
 "active","primary",90,9,"https://doi.org/10.1016/j.actamat.2010.12.001","欧米",0.9,
 r"β transus: $T_\beta \approx 995°C$。Hall-Petch: $\sigma_y = \sigma_0 + k_y d^{-1/2}$。比強度: $\sigma/\rho \approx 200$ MPa/(g/cm³)","url_present"),

("mat_b2_042","半導体エピタキシャル成長制御","Semiconductor Epitaxial Growth Control","MBE MOCVD heterostructure quantum well",
 "分子線エピタキシー(MBE)・有機金属化学気相堆積(MOCVD)による半導体ヘテロ構造・量子井戸の格子整合・不整合緩和・表面再構成制御設計手法。",
 "LEDからレーザー・HEMT・量子カスケードレーザーまで、現代光電子デバイスの基盤製造技術。",
 "材料工学・ナノテク","半導体材料工学",1958,None,"method","半導体・光電子",
 "格子定数マッチング・成長速度・基板温度精密制御","原子層精度のヘテロ接合が必要な場合",
 "転位密度低減は?新規III-V族材料設計は?","バルク成長","MBE,MOCVD,エピタキシャル成長,量子井戸","MBE,MOCVD,epitaxial growth,quantum well",
 "active","primary",90,9,"https://doi.org/10.1002/9783527810147","欧米",0.9,
 r"臨界膜厚(Matthews-Blakeslee): $h_c = \frac{b}{8\pi f}\frac{1-\nu\cos^2\alpha}{1+\nu}\ln(h_c/b)$。格子不整合: $f = (a_s-a_l)/a_l$","url_present"),

("mat_b2_043","ナノ粒子表面修飾設計","Nanoparticle Surface Functionalization Design","ligand exchange passivation PEGylation",
 "量子ドット・磁性ナノ粒子・Au NP等の表面リガンド交換・シラン化・PEG化・抗体結合により分散安定性・生体適合性・標的認識機能を付与する設計手法。",
 "がん診断・DDS・造影剤・センサーの機能化ナノ粒子設計の基盤技術として確立。",
 "材料工学・ナノテク","バイオナノ材料工学",1990,None,"method","医療・センサー",
 "ゼータ電位・流体力学径・機能基密度評価","生体中での安定分散・標的認識が必要な場合",
 "PEGの免疫回避効果劣化は?Stealth粒子設計は?","裸ナノ粒子","ナノ粒子,表面修飾,PEG化,DDS","nanoparticle,surface functionalization,PEGylation,DDS",
 "active","primary",87,6,"https://doi.org/10.1038/nmat2404","欧米",0.9,
 r"ゼータ電位: $\zeta = \epsilon\psi_0/\eta\kappa^{-1}$。Debye長: $\kappa^{-1} = \sqrt{\epsilon k_BT/(e^2\sum n_i z_i^2)}$","url_present"),

("mat_b2_044","圧延熱処理制御圧延技術","Controlled Rolling and Thermomechanical Processing","TMCP accelerated cooling ferrite","制御圧延・加速冷却(TMCP)により鋼材のオーステナイト結晶粒微細化・析出強化・組織制御を同時に達成し、強度・靭性を向上させる製造技術。",
 "造船・建築・海洋構造物・パイプラインの高強度鋼製造の標準技術として世界の鉄鋼産業に普及。",
 "材料工学・ナノテク","鉄鋼材料工学",1960,None,"method","構造・造船",
 "圧延温度・圧下率・冷却速度・停止温度の精密制御","高強度低温靭性鋼が必要な場合",
 "超微細粒鋼(UFG)化は?TMCP+予ひずみは?","調質鋼","TMCP,制御圧延,加速冷却,高強度鋼","TMCP,controlled rolling,accelerated cooling,high strength steel",
 "active","primary",90,9,"https://doi.org/10.2355/isijinternational.33.1073","欧米",0.9,
 r"Hall-Petch: $\sigma_y = \sigma_i + k/\sqrt{d}$。析出強化: $\Delta\sigma = M\cdot 0.4Gb/\pi(1-\nu)^{0.5}\cdot\ln(r/b)/\lambda$","url_present"),

("mat_b2_045","中国次世代電池材料研究","China Next-Generation Battery Material Research","solid-state sodium-ion China CATL BYD",
 "CATLがリードする全固体リチウム・ナトリウムイオン電池の電解質・正負極材料設計と界面制御技術。コバルトフリー・リチウムフリー化を目標。",
 "EV・グリッドエネルギー貯蔵の中国主導でのパラダイムシフト。2030年以降の世界電池市場を左右する。",
 "材料工学・ナノテク","電気化学材料工学",2015,None,"method","エネルギー貯蔵",
 "界面インピーダンス低減・機械的強度・サイクル耐久性","次世代高エネルギー密度電池が必要な場合",
 "固体電解質とのコンタクト確保は?製造コストは?","液体電解質Li電池","全固体電池,ナトリウムイオン電池,CATL,中国","solid-state battery,sodium-ion,CATL,China,energy storage",
 "active","primary",87,5,"https://doi.org/10.1038/s41560-022-01055-0","東アジア",0.95,
 r"エネルギー密度: $E = \int_0^Q V(q)dq$。固体電解質イオン伝導率目標: $\sigma > 10^{-2}$ S/cm。Nernst: $V = V^0 - \frac{RT}{nF}\ln Q$","url_present"),

("mat_b2_046","多孔質アルミナ陽極酸化設計","Anodic Aluminum Oxide Nanostructure Design","AAO template self-organized nanopore",
 "アルミニウムの二段階陽極酸化による自己組織化ナノポーラスアルミナ(AAO)の細孔径・配列・深さを制御し、ナノワイヤー・ナノチューブ・フィルターのテンプレートとして活用する手法。",
 "磁気記録・MEMS・生体センサー・フィルター膜のナノ構造製造プラットフォームとして確立。",
 "材料工学・ナノテク","ナノ材料工学",1995,None,"method","センサー・フィルター",
 "電解液種・電圧・温度・陽極酸化時間制御","規則配列ナノ構造テンプレートが必要な場合",
 "大面積均一化は?細孔径のさらなる微細化は?","リソグラフィー","AAO,陽極酸化,ナノポーラス,テンプレート","AAO,anodic aluminum oxide,nanopore,template",
 "active","primary",86,7,"https://doi.org/10.1038/376015a0","欧米",0.9,
 r"ポア直径: $D_p \approx k \cdot U$ (k≈2.5 nm/V for H2SO4)。セル間距離: $d_{cell} \approx 2.5 \cdot U$ (nm). 充填率$\approx\pi/(2\sqrt{3})$","url_present"),

("mat_b2_047","熱電材料設計・最適化","Thermoelectric Material Design and Optimization","ZT Seebeck Peltier TE module",
 "Seebeck係数・電気伝導率・熱伝導率の相反特性をバンドエンジニアリング・ナノ構造化で同時最適化し、ZT値を向上させる熱電材料設計手法。",
 "廃熱発電・精密冷却素子として産業・軍事・医療に展開。GeTe・SnSe等の新材料がZT>2を達成。",
 "材料工学・ナノテク","エネルギー材料工学",1821,None,"method","エネルギー変換",
 "ドーピング・ナノ構造化・エネルギーフィルタリング","廃熱回収・精密冷却が必要な場合",
 "効率の理論限界突破は?フレキシブル化は?","蒸気タービン","熱電材料,ZT,Seebeck係数,ペルチェ","thermoelectric,ZT,Seebeck,Peltier",
 "active","primary",87,7,"https://doi.org/10.1126/science.1115439","欧米",0.9,
 r"ZT = $S^2\sigma T/\kappa$。カルノー効率: $\eta_{max} = \left(\frac{\sqrt{1+ZT}-1}{\sqrt{1+ZT}+T_C/T_H}\right)\cdot\frac{T_H-T_C}{T_H}$","url_present"),

("mat_b2_048","電子セラミックス高精度焼結","Electronic Ceramics Precision Sintering","flash sintering SPS FAST densification",
 "スパーク・プラズマ焼結(SPS)・フラッシュ焼結による急速加熱で結晶粒成長を抑制しながら完全緻密化を実現する電子セラミックス精密焼結技術。",
 "NTC/PTC素子・MLCC・IGBTパッケージ基板の歩留まりと特性を向上。従来焼結の1/10以下の時間で完結。",
 "材料工学・ナノテク","電子セラミックス工学",1990,None,"method","電子部品",
 "加熱速度・圧力・電流密度・雰囲気制御","ナノ結晶維持での高密度化が必要な場合",
 "大型化・連続プロセス化は?フラッシュ焼結の機構解明は?","従来焼結","SPS,フラッシュ焼結,電子セラミックス,高速緻密化","SPS,flash sintering,electronic ceramics,densification",
 "active","primary",85,7,"https://doi.org/10.1016/j.ceramint.2019.09.041","欧米",0.85,
 r"SPS緻密化速度: $\dot{\rho} = A\exp(-Q/RT) \cdot (P/G^n)$。粒成長抑制: $d = d_0\exp(-t/\tau)$","url_present"),

("mat_b2_049","日本GaN半導体パワーデバイス設計","Japan GaN Power Device Design","GaN HEMT SiC wide bandgap Japan",
 "日本のRohm・富士電機が主導するGaN/SiCパワーデバイスのエピ設計・ゲート絶縁・パッケージング技術。EV・インバーターの電力変換効率向上が目標。",
 "炭化ケイ素・窒化ガリウムの第三世代半導体が従来Si比で100倍以上の高圧・高温動作を実現。",
 "材料工学・ナノテク","半導体材料工学",2000,None,"method","電力電子",
 "2DEG密度・ゲート絶縁膜信頼性・ブレークダウン電圧評価","高圧・高周波・高温電力変換が必要な場合",
 "GaN-on-Si低コスト化は?p-GaNゲート最適化は?","Si MOSFET","GaN,SiC,パワーデバイス,HEMT,日本","GaN,SiC,power device,HEMT,Japan",
 "active","primary",90,8,"https://doi.org/10.1038/s41928-019-0335-9","東アジア",0.95,
 r"2DEG密度: $n_s = \frac{\sigma_{SP}+\sigma_{pz}}{e} - \frac{\epsilon\phi_b}{ed}$。$R_{on} \propto V_B^{2.5}/\mu_n\epsilon_{GaN}E_c^3$","url_present"),

("mat_b2_050","マイクロ波焼結・加熱プロセス","Microwave Sintering and Heating Process","microwave volumetric heating ceramic sintering",
 "マイクロ波の誘電加熱によりセラミックス・複合材料を体積均一加熱し、従来表面加熱に比べて焼結時間・エネルギーを大幅削減する製造プロセス設計手法。",
 "アルミナ・SiC・ジルコニアの焼結時間を1/10以下に短縮。炭化ケイ素系では均質微細組織が得られる。",
 "材料工学・ナノテク","製造プロセス工学",1975,None,"method","セラミックス製造",
 "マイクロ波周波数・電力密度・試料配置設計","急速均一焼結が必要な場合",
 "大型化・量産ラインへの適用は?誘電率変化への対応は?","従来炉焼結","マイクロ波焼結,誘電加熱,セラミックス","microwave sintering,dielectric heating,ceramics",
 "active","primary",84,6,"https://doi.org/10.1111/j.1551-2916.2009.03107.x","欧米",0.85,
 r"Lambert-Beer則: $P_{absorbed} = P_0(1-e^{-\alpha d})$。侵入深さ: $\delta_p = \lambda/(2\pi\tan\delta\sqrt{\epsilon_r})$","url_present"),
]

if __name__ == "__main__":
    inserted, skipped = insert_records(records)
    print(f"Inserted: {inserted}, Skipped: {skipped}")
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Total: {total}")
