import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("cs_b3_001","大規模言語モデルファインチューニング","Large Language Model Fine-Tuning","LLM Fine-Tuning",
 "事前学習済み大規模言語モデルをタスク特化データで微調整する手法。SFT（教師あり）・RLHF・DPO・LoRA・QLoRAによるパラメータ効率的ファインチューニングを含む。",
 "GPT-4・LLaMA等のLLMを特定ドメイン（医療・法律・コード）に高精度適合させる中核技術。",
 "CS/情報工学","機械学習工学",2020,None,"algorithm","NLP・AI応用",
 "タスク特化データセット（1K件以上）・GPU計算資源・モデルアーキテクチャ情報","ドメイン特化LLM構築・AIアシスタントアライメント時","RLHFとDPOの品質対計算コストトレードオフをどう評価するか",
 "フルスクラッチ学習","LLM,ファインチューニング,LoRA,RLHF,DPO",
 "LLM,fine-tuning,LoRA,RLHF,DPO",
 "active","secondary",85,9,
 "https://arxiv.org/abs/2305.18290","欧米",0.85,
 r"LoRA更新: $W' = W + \Delta W = W + BA$、$B\in\mathbb{R}^{d\times r}$、$A\in\mathbb{R}^{r\times k}$、$r \ll \min(d,k)$。パラメータ削減率: $\frac{2rk}{dk} = \frac{2r}{d}$。",
 "url_present"),

("cs_b3_002","グラフニューラルネットワーク設計","Graph Neural Network Design","GNN Architecture Design",
 "グラフ構造データ（分子・ソーシャルネットワーク・知識グラフ）を学習するGNNのアーキテクチャ設計。GCN・GraphSAGE・GAT・GIN・MPNNのメッセージパッシング機構と過平滑化対策。",
 "創薬・交通予測・推薦システム・不正検知に広く応用。分子特性予測でDL研究を革新。",
 "CS/情報工学","機械学習工学",2017,None,"algorithm","グラフ学習・科学AI",
 "グラフ構造データ（ノード・エッジ・属性）・ホモフィリー or ヘテロフィリー判断","分子設計・知識グラフ推論・SNS解析時","過平滑化と表現力のトレードオフをどう解決するか",
 "CNNによる画像学習","GNN,GCN,GAT,メッセージパッシング,グラフ",
 "GNN,GCN,GAT,message passing,graph",
 "active","secondary",85,9,
 "https://arxiv.org/abs/1901.00596","欧米",0.85,
 r"GCN伝播: $H^{(l+1)} = \sigma(\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2}H^{(l)}W^{(l)})$、$\tilde{A}=A+I$、$\tilde{D}_{ii}=\sum_j\tilde{A}_{ij}$。GINの表現力: WL testsと等価。",
 "url_present"),

("cs_b3_003","連合学習システム設計","Federated Learning System Design","FL System Engineering",
 "分散デバイス上のデータを集約せずモデルを協調学習する連合学習システムの設計手法。FedAvg・FedProx・通信効率化・差分プライバシー統合・クライアント選択戦略を扱う。",
 "医療・金融・スマートフォン向けプライバシー保護AI学習の標準手法。Googleがスマートフォン予測入力で実用化。",
 "CS/情報工学","分散機械学習",2017,None,"system","プライバシー保護AI",
 "IIDまたは非IIDデータ分布の把握・通信帯域制約・クライアント数設計","プライバシー制約下AI学習・クロスサイロ協調学習時","非IIDデータによる精度劣化を補正するための最適アグリゲーション戦略は何か",
 "中央集権型学習","連合学習,FedAvg,差分プライバシー,プライバシー,分散学習",
 "federated learning,FedAvg,differential privacy,distributed training",
 "active","primary",87,8,
 "https://arxiv.org/abs/1602.05629","欧米",0.85,
 r"FedAvg: $w_{t+1} = \sum_{k=1}^{K}\frac{n_k}{n}w_{t+1}^k$、各クライアント更新 $w_{t+1}^k = w_t - \eta\nabla\mathcal{L}_k(w_t)$、$E$エポック実行。通信量削減率 $\frac{E\cdot B}{|D|}$。",
 "url_present"),

("cs_b3_004","拡散モデル実装・応用","Diffusion Model Implementation and Applications","Diffusion Model Engineering",
 "DDPMとスコアマッチングに基づく拡散生成モデルの実装手法。DDIM高速サンプリング・Classifier-Free Guidance・LDM（潜在拡散）・ControlNetによる条件付け生成を扱う。",
 "Stable Diffusion・DALL-E 3・Soraの基盤技術。画像・動画・3D生成の標準手法となった。",
 "CS/情報工学","生成モデル工学",2020,None,"algorithm","画像・動画生成",
 "拡散過程の設定（ノイズスケジュール）・条件付け方法の設計","テキストto画像・動画生成・医療画像合成時","CFGの強度と多様性のトレードオフはどう制御するか",
 "GAN","拡散モデル,DDPM,Stable Diffusion,スコアマッチング,生成AI",
 "diffusion model,DDPM,Stable Diffusion,score matching,generative AI",
 "active","secondary",86,9,
 "https://arxiv.org/abs/2006.11239","欧米",0.87,
 r"DDPM損失: $\mathcal{L} = \mathbb{E}_{t,x_0,\epsilon}\|\epsilon - \epsilon_\theta(\sqrt{\bar\alpha_t}x_0+\sqrt{1-\bar\alpha_t}\epsilon,t)\|^2$、$\bar\alpha_t = \prod_{s=1}^t(1-\beta_s)$。",
 "url_present"),

("cs_b3_005","強化学習実システム設計","Reinforcement Learning Real System Design","RL for Real-World Systems",
 "実環境での強化学習適用に必要な安全性・サンプル効率・報酬設計・Sim-to-Transfer・モデルベースRL手法の設計。ロボット制御・自動運転・データセンター冷却への応用を扱う。",
 "DeepMindがAlphaGo・AlphaFoldで実証。Googleデータセンター冷却でエネルギー40%削減達成。",
 "CS/情報工学","強化学習工学",2015,None,"algorithm","ロボティクス・自動化",
 "報酬関数設計・安全制約の明確化・シミュレータの精度評価","ロボット制御・ゲームAI・リソース最適化時","スパース報酬問題をどのように探索効率的に解決するか",
 "ルールベース制御","強化学習,SAC,PPO,モデルベースRL,Sim-to-Real",
 "reinforcement learning,SAC,PPO,model-based RL,Sim-to-Real",
 "active","secondary",84,8,
 "https://arxiv.org/abs/1801.01290","欧米",0.83,
 r"SAC目標: $J(\pi) = \mathbb{E}\left[\sum_t\gamma^t\left(r_t + \alpha\mathcal{H}(\pi(\cdot|s_t))\right)\right]$、エントロピー項 $\alpha\mathcal{H} = -\alpha\sum_a\pi(a|s)\log\pi(a|s)$で探索促進。",
 "url_present"),

("cs_b3_006","中国AI研究エコシステム","China AI Research Ecosystem","China AI Research Infrastructure",
 "百度・アリババ・テンセント・ファーウェイ・国立大学が形成する中国AI研究体制。PaddlePaddle・MindSpore・国産データセット・政府AI計画（次世代AI計画2017）との連携構造。",
 "2022年AI論文数で米国を超えたと報告。医療診断・顔認証・自動運転で世界競争をリード。",
 "CS/情報工学","AI研究政策",2017,None,"system","国家AI戦略",
 "国家AI計画・産学官連携スキーム・データ資源政策","中国AI政策分析・グローバルAI競争評価時","AI研究成果の質（引用数・産業応用）と量の乖離をどう評価するか",
 "シリコンバレー型AI開発","中国AI,PaddlePaddle,MindSpore,次世代AI計画,産学官",
 "China AI,PaddlePaddle,MindSpore,AI plan,government",
 "active","secondary",80,8,
 "https://www.science.org/doi/10.1126/science.ade7967","東アジア",0.88,
 r"AI競争力指数（相対化）: 論文数・被引用数・特許数・AI投資額・AI人材数の加重平均スコア $S = \sum_i w_i \cdot \text{rank}_i^{-1}$で定量化。",
 "url_present"),

("cs_b3_007","セキュアマルチパーティ計算","Secure Multi-Party Computation","MPC Engineering",
 "複数パーティが秘密データを明かさずに共同計算を行うMPCプロトコルの実装技術。ガーブルド回路・秘密分散（Shamir）・Oblivious Transfer・ABYフレームワークの設計を扱う。",
 "プライバシー保護機械学習・金融合同分析・医療データ連携に実用化が進む。",
 "CS/情報工学","暗号工学",2000,None,"algorithm","プライバシー保護計算",
 "通信コスト許容範囲・セキュリティモデル（半正直 or 悪意）の設定","プライバシー保護ML・機密データ共同分析時","MPC計算コストを実用許容範囲に収めるための最新最適化手法は何か",
 "信頼できる第三者計算","MPC,秘密分散,ガーブルド回路,Shamir,プライバシー",
 "MPC,secret sharing,garbled circuit,Shamir,privacy",
 "active","secondary",82,7,
 "https://eprint.iacr.org/2016/250","欧米",0.82,
 r"Shamir秘密分散: 秘密$s$を$f(x) = s + a_1x+\cdots+a_{t-1}x^{t-1}$ (mod $p$) として $n$点$(i,f(i))$に分散、$t$点以上でLagrange補間 $s = \sum_{i=1}^t y_i\prod_{j\ne i}\frac{-j}{i-j}$ で復元。",
 "url_present"),

("cs_b3_008","自動プログラム合成","Automated Program Synthesis","Program Synthesis and AutoProgramming",
 "仕様・例・自然言語から自動的にプログラムを生成する手法。帰納的プログラム合成・SAT/SMTによる検証・LLMコード生成（Copilot・CodeLlama）の比較と品質保証手法。",
 "ソフトウェア開発生産性の革命的向上。GitHub Copilotが1000万人超の開発者に利用される。",
 "CS/情報工学","ソフトウェア工学",2000,None,"algorithm","ソフトウェア開発",
 "仕様の形式化またはLLMによる自然言語理解・テストスイート設計","コード生成・テスト自動化・バグ修正自動化時","LLM生成コードの正確性検証と安全性保証はどう実現するか",
 "手動プログラミング","プログラム合成,LLMコード生成,Copilot,SMT,形式検証",
 "program synthesis,LLM code generation,Copilot,SMT,formal verification",
 "active","secondary",82,8,
 "https://arxiv.org/abs/2108.07732","欧米",0.82,
 r"SMT検証: $\exists x: \phi_{spec}(x,prog(x)) = False$が充足可能ならバグあり。LLMパス率 $P_{pass@k} = 1-\binom{n-c}{k}/\binom{n}{k}$（$c$: 正解数、$n$: サンプル数）。",
 "url_present"),

("cs_b3_009","コンテナオーケストレーション最適化","Container Orchestration Optimization","Kubernetes Advanced Scheduling",
 "Kubernetesクラスタにおける高度なスケジューリング・オートスケーリング・サービスメッシュ・コスト最適化の設計手法。HPA・VPA・KEDA・Istio・eBPFによる観測性を統合する。",
 "クラウドネイティブインフラの標準基盤。Fortune 500の90%以上がKubernetes利用中。",
 "CS/情報工学","クラウド工学",2016,None,"system","クラウドインフラ",
 "k8sクラスタ環境・リソース要求の明確化・SLO/SLA設定","マイクロサービス基盤・大規模SaaS運用時","コスト最適化と応答性能SLOの同時達成戦略は何か",
 "仮想マシン管理","Kubernetes,コンテナ,スケジューリング,Istio,eBPF",
 "Kubernetes,container,scheduling,Istio,eBPF",
 "active","secondary",84,9,
 "https://dl.acm.org/doi/10.1145/2741948.2741964","欧米",0.85,
 r"HPAスケーリング: $replicas_{desired} = \lceil replicas_{current} \times \frac{metric_{current}}{metric_{target}}\rceil$。Binpacking: $\min \sum_j y_j$ s.t. $\sum_{i\in j} r_i \leq C y_j$（$y_j \in \{0,1\}$）。",
 "url_present"),

("cs_b3_010","量子アルゴリズム実装","Quantum Algorithm Implementation","Quantum Algorithm Engineering",
 "量子コンピュータ上でのVQE・QAOA・量子機械学習・Shorアルゴリズムの実装手法。ノイズ耐性最適化（NISQ対応）・回路深度削減・誤り軽減技術（ZNE・PEC）を扱う。",
 "量子化学シミュレーション・組み合わせ最適化・暗号解読で古典計算を超えるポテンシャル。",
 "CS/情報工学","量子コンピューティング",2019,None,"algorithm","量子コンピューティング",
 "NISQ量子コンピュータ（50-1000 qubit）・ノイズキャラクタリゼーション","量子優位性実証・量子化学計算・暗号研究時","VQEのバレンプラトー問題をどう回避するか",
 "古典アルゴリズム","量子アルゴリズム,VQE,QAOA,NISQ,誤り軽減",
 "quantum algorithm,VQE,QAOA,NISQ,error mitigation",
 "active","secondary",80,4,
 "https://arxiv.org/abs/2101.08448","欧米",0.8,
 r"VQE期待値: $E(\theta) = \langle\psi(\theta)|H|\psi(\theta)\rangle = \sum_k c_k\langle\psi(\theta)|P_k|\psi(\theta)\rangle$。パラメータシフト則: $\partial_\theta E = \frac{E(\theta+\pi/2)-E(\theta-\pi/2)}{2}$。",
 "url_present"),

("cs_b3_011","日本国産AIコンパイラ開発","Japan AI Compiler Development","Japan AI Compiler Stack",
 "富士通・NEC・産総研が推進する国産AIコンパイラ・MLフレームワーク開発。AiMath・VE向けMLコンパイラ・富士通Fugakuに最適化されたAI学習基盤の設計思想と技術アプローチ。",
 "国産スパコンFugakuへのAI最適化で国際競争力維持。NEC SX-Aurora TSUBASA向け最適化でHPC×AIを統合。",
 "CS/情報工学","AIシステム工学",2019,None,"system","スパコン・AIインフラ",
 "国産プロセッサアーキテクチャへの最適化・MPI並列対応","Fugaku・SX-Auroraを用いた科学AI計算時","NECベクトルプロセッサの特性を活かしたAIカーネル最適化の鍵は何か",
 "GPU専用フレームワーク","AIコンパイラ,Fugaku,NEC,富士通,国産AI",
 "AI compiler,Fugaku,NEC,Fujitsu,Japan HPC AI",
 "active","secondary",78,6,
 "https://www.fujitsu.com/global/documents/about/research/technologies/aitech/","東アジア",0.85,
 r"コンパイラ最適化目標: $T_{exec} = T_{mem} + T_{compute}$の削減。ループタイリング: タイルサイズ$B$で $T_{cache} \propto \frac{N^3}{B^3}\cdot B^2 = \frac{N^3}{B}$（$O(N^3/B)$キャッシュミス）。",
 "url_present"),

("cs_b3_012","説明可能AI（XAI）実装","Explainable AI Implementation","XAI Engineering",
 "ブラックボックスDNNの予測根拠を解釈する説明手法の実装。LIME・SHAP・GradCAM・LIME・Integrated Gradients・対話的説明システムの設計と評価指標（忠実性・簡潔性）を扱う。",
 "医療診断・信用審査・自動運転における規制適合（EU AI Act）と信頼性構築に不可欠。",
 "CS/情報工学","信頼性AIエンジニアリング",2016,None,"algorithm","医療・金融・自動車AI",
 "モデルアクセス（ブラックボックス or ホワイトボックス）・説明の粒度設定","規制適合AI・医療診断支援・信用リスク説明時","局所説明と大域説明の使い分け基準をどのように設定するか",
 "ブラックボックス推論","XAI,SHAP,LIME,GradCAM,信頼性AI",
 "XAI,SHAP,LIME,GradCAM,trustworthy AI",
 "active","secondary",84,9,
 "https://arxiv.org/abs/1705.07874","欧米",0.83,
 r"SHAP値: $\phi_i(f,x) = \sum_{S\subseteq F\setminus\{i\}}\frac{|S|!(|F|-|S|-1)!}{|F|!}[f(S\cup\{i\})-f(S)]$。Shapley公理（効率性・対称性・ダミー性・加法性）を満たす唯一の解。",
 "url_present"),

("cs_b3_013","MLOpsパイプライン構築","MLOps Pipeline Engineering","MLOps System Design",
 "ML実験管理・自動学習パイプライン・モデルレジストリ・デプロイ・モニタリング・ドリフト検知を統合したMLOpsシステムの設計手法。MLflow・Kubeflow・ZenML・SageMakerの比較を含む。",
 "ML本番化の失敗率を低減し、モデル更新サイクルを週次から日次へ短縮する実践基盤。",
 "CS/情報工学","ソフトウェアエンジニアリング・ML",2018,None,"system","ML本番運用",
 "MLパイプラインの要件定義（実験管理・デプロイ・監視）・クラウドor オンプレ選択","ML本番化・モデル継続的改善サイクル構築時","データドリフトとコンセプトドリフトを早期検知する統計的手法は何か",
 "アドホックML実験","MLOps,MLflow,Kubeflow,ドリフト検知,モデルデプロイ",
 "MLOps,MLflow,Kubeflow,drift detection,model deployment",
 "active","secondary",84,9,
 "https://arxiv.org/abs/2205.02302","欧米",0.83,
 r"データドリフト検知（MMD）: $MMD^2(P,Q) = \mathbb{E}_{x,x'\sim P}[k(x,x')] - 2\mathbb{E}_{x\sim P,y\sim Q}[k(x,y)] + \mathbb{E}_{y,y'\sim Q}[k(y,y')]$。",
 "url_present"),

("cs_b3_014","形式検証支援ツール設計","Formal Verification Tool Design","Model Checker and Theorem Prover Engineering",
 "ソフトウェア・ハードウェアの正当性を数学的に証明するツールの設計。SAT/SMTソルバ（Z3・CVC5）・モデル検査（TLA+・SPIN）・定理証明（Lean4・Coq・Isabelle）の応用設計を扱う。",
 "航空機制御・医療機器・セキュリティクリティカルシステムの安全認証に必須。",
 "CS/情報工学","形式手法工学",1990,None,"method","安全クリティカルシステム",
 "形式仕様の記述・状態空間の有限化・検証性能の見積もり","DO-178C/IEC 61508認証・セキュリティ証明・コンパイラ検証時","状態爆発問題への対処として抽象化とシンボリック実行のどちらが有効か",
 "テストのみによる品質保証","形式検証,SAT,SMT,Z3,モデル検査",
 "formal verification,SAT,SMT,Z3,model checking",
 "active","secondary",82,9,
 "https://dl.acm.org/doi/10.1145/2908080.2908081","欧米",0.82,
 r"DPLL(T)アルゴリズム: $SAT(\phi) = \text{DPLL}(\phi[x:=\top]) \lor \text{DPLL}(\phi[x:=\bot])$。SMT: $\phi = \phi_{bool} \land \phi_T$、ブール満足可能割り当てを理論ソルバ$T$で確認。",
 "url_present"),

("cs_b3_015","コンピュータビジョン基盤モデル","Computer Vision Foundation Models","Vision Foundation Model Engineering",
 "SAM・CLIP・DINO・DINOv2等の大規模視覚基盤モデルの実装と応用設計。ゼロショット検出・セグメンテーション・視覚言語モデル（VLM）・マルチモーダル融合を扱う。",
 "医療画像解析・衛星画像解析・自動車知覚の汎化性能を革新。SAMが2023年に全物体セグメンテーションを実現。",
 "CS/情報工学","コンピュータビジョン工学",2021,None,"algorithm","画像・映像解析",
 "大規模事前学習済みモデルのアクセス・タスク適合のためのプロンプト設計","ゼロショット画像認識・汎用物体検出・VLMアプリケーション時","基盤モデルのゼロショット性能とドメイン特化モデルの差はどう評価するか",
 "教師あり個別タスクモデル","SAM,CLIP,視覚基盤モデル,ゼロショット,VLM",
 "SAM,CLIP,vision foundation model,zero-shot,VLM",
 "active","secondary",84,8,
 "https://arxiv.org/abs/2304.02643","欧米",0.85,
 r"CLIPゼロショット: $p(y|x) = \frac{\exp(\cos(f_I(x),f_T(y))/\tau)}{\sum_{y'}\exp(\cos(f_I(x),f_T(y'))/\tau)}$。InfoNCE損失: $\mathcal{L} = -\frac{1}{N}\sum_i\log\frac{e^{s_{ii}/\tau}}{\sum_j e^{s_{ij}/\tau}}$。",
 "url_present"),

("cs_b3_016","アルゴリズム的フェアネス実装","Algorithmic Fairness Implementation","Algorithmic Fairness Engineering",
 "AI・MLシステムにおける公平性保証の実装手法。個人的公平性・群間公平性（統計的パリティ・機会の均等・予測的公平性）の測定指標と制約付き最適化・前処理・後処理技術を扱う。",
 "採用・融資・司法における差別的AI使用への規制対応（EU AI Act・米国FHA）に不可欠。",
 "CS/情報工学","信頼性AIエンジニアリング",2016,None,"method","規制適合AI",
 "保護属性の特定・公平性指標の選択・適法性評価","採用・融資・医療AI公平性審査時","公平性と予測精度のトレードオフをPareto改善できる手法は何か",
 "精度のみ最適化","公平性,AI,差別,統計的パリティ,機会均等",
 "fairness,AI,discrimination,statistical parity,equalized odds",
 "active","secondary",82,8,
 "https://arxiv.org/abs/1609.07236","欧米",0.82,
 r"統計的パリティ: $P(\hat{y}=1|A=0) = P(\hat{y}=1|A=1)$。機会均等: $P(\hat{y}=1|y=1,A=0) = P(\hat{y}=1|y=1,A=1)$。公平性制約付き最適化: $\min\mathcal{L}(\theta)$ s.t. $|DP_0-DP_1|\leq\epsilon$。",
 "url_present"),

("cs_b3_017","韓国半導体設計自動化研究","Korea EDA and VLSI Design Automation","Korea EDA Research",
 "サムスン・SKハイニックス・カイスト・ソウル大が推進するEDA（電子設計自動化）ツール開発。配置配線・論理合成・AI支援レイアウト最適化（Samsung AutoPlace）の技術アプローチ。",
 "最先端プロセスのマスク数増加に伴うEDAツール需要増加。Samsung AutoPlaceがAI配置で30%効率化実証。",
 "CS/情報工学","EDA工学",2018,None,"system","半導体設計",
 "RTL設計完了・プロセスPDK・タイミング制約","VLSI物理設計・フォームファクタ最小化時","AIベースEDAの生成解と人手最適化解の差はどう定量評価するか",
 "手動レイアウト設計","EDA,VLSI,配置配線,AI設計,韓国",
 "EDA,VLSI,place and route,AI design,Korea",
 "active","secondary",79,8,
 "https://ieeexplore.ieee.org/document/9372170","東アジア",0.87,
 r"配置最適化（解析的）: $\min\sum_{(u,v)\in E}w_{uv}[(x_u-x_v)^2+(y_u-y_v)^2]$（HPWL近似）、半周配線長(HPWL)$= (x_{max}-x_{min})+(y_{max}-y_{min})$。",
 "url_present"),

("cs_b3_018","ストリーミングデータ処理","Streaming Data Processing Systems","Stream Processing Engineering",
 "リアルタイムデータストリーム処理システム（Apache Kafka・Flink・Spark Streaming・RisingWave）の設計手法。ウィンドウ集計・正確一度処理・低遅延保証・スケールアウトを扱う。",
 "金融取引監視・IoTデータ分析・不正検知のリアルタイム処理インフラとして標準化。",
 "CS/情報工学","分散システム工学",2014,None,"system","リアルタイムデータ基盤",
 "データ発生レート・処理遅延要件（<1秒）・スケール要件の明確化","金融アラート・センサデータリアルタイム分析・広告入札時","Exactly-Onceセマンティクスと処理スループットのトレードオフは何か",
 "バッチ処理","Kafka,Flink,ストリーミング,ウィンドウ集計,リアルタイム",
 "Kafka,Flink,streaming,window aggregation,real-time",
 "active","secondary",85,9,
 "https://dl.acm.org/doi/10.14778/2824032.2824076","欧米",0.83,
 r"ウィンドウ集計（タンブリング）: $A_w = agg(\{x_t : w\cdot T \leq t < (w+1)T\})$。遅延データ処理: ウォーターマーク $W(t) = \max_{e\leq t}(e_{time}) - \delta$、$\delta$は許容遅延。",
 "url_present"),

("cs_b3_019","ゼロトラストセキュリティアーキテクチャ","Zero Trust Security Architecture","Zero Trust Engineering",
 "境界ベースのセキュリティを廃し「Never Trust Always Verify」原則に基づくゼロトラストアーキテクチャの設計手法。マイクロセグメンテーション・継続認証・SASE・IAP・BeyondCorpの実装を扱う。",
 "クラウド移行・リモートワーク普及でゼロトラストが企業セキュリティの標準モデルに。NIST SP 800-207が規範。",
 "CS/情報工学","サイバーセキュリティ工学",2010,None,"architecture","セキュリティ設計",
 "アイデンティティ基盤（IdP）の整備・資産インベントリの完全化・ログ収集基盤","クラウド移行・内部脅威対策・ランサムウェア対策時","最小権限と業務効率性のバランスをどう設計するか",
 "ペリメータセキュリティ（VPN/FW）","ゼロトラスト,SASE,BeyondCorp,マイクロセグメンテーション,IAM",
 "zero trust,SASE,BeyondCorp,micro-segmentation,IAM",
 "active","secondary",85,9,
 "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207.pdf","欧米",0.85,
 r"リスクスコア（継続認証）: $R(t) = f(I_{device},I_{user},I_{network},I_{behavior})$、$R > \theta_{high}$でセッション切断。条件付きアクセス: $Access = \bigcap_i Policy_i(context)$。",
 "url_present"),

("cs_b3_020","大規模分散トレーニング最適化","Large-Scale Distributed Training Optimization","Distributed DL Training",
 "数千GPUにまたがるLLM・大規模DNNの分散学習最適化手法。データ並列・モデル並列・パイプライン並列・ZeRO最適化・通信圧縮・勾配チェックポイントを統合するDeepSpeed・Megatron-LMの設計。",
 "GPT-4・LLaMA-3等の規模の大規模モデル学習の実現基盤。DeepSpeedがOOM問題を解決。",
 "CS/情報工学","分散機械学習",2020,None,"system","LLM学習インフラ",
 "GPU数・モデルサイズ・バッチサイズの3方向並列設計・通信トポロジー（InfiniBand/NVLink）","100B+パラメータモデル学習・マルチノードGPUクラスタ運用時","モデル並列・データ並列・パイプライン並列の最適組み合わせの決定法は何か",
 "シングルGPU学習","分散学習,DeepSpeed,ZeRO,Megatron-LM,LLM",
 "distributed training,DeepSpeed,ZeRO,Megatron-LM,LLM",
 "active","secondary",85,9,
 "https://arxiv.org/abs/1910.02054","欧米",0.85,
 r"ZeRO段階3: パラメータ・勾配・オプティマイザ状態を$N_{GPU}$で分割。メモリ/GPU: $M_{total}/N_{GPU}$。通信オーバーヘッド: $2\psi/N_{GPU}\cdot(\text{allreduce})$、$\psi$: パラメータ数。",
 "url_present"),

("cs_b3_021","アジャイル品質エンジニアリング","Agile Quality Engineering","Continuous Testing and QA Automation",
 "アジャイル開発サイクルに組み込んだ継続的テスト・品質自動化の設計手法。テスト駆動開発・BDD・継続的インテグレーション・カオスエンジニアリング・シフトレフトセキュリティを統合する。",
 "リリース頻度向上とバグ率低減を両立。GitLabが2週間スプリントでCI/CDを世界標準化。",
 "CS/情報工学","ソフトウェア工学",2010,None,"method","ソフトウェア品質",
 "CI/CDパイプライン整備・テストカバレッジ目標設定・フィーチャーフラグ管理","高頻度リリース・品質確保・DevOps成熟度向上時","E2Eテストのフレーキーネスをどう体系的に排除するか",
 "ウォーターフォール型テスト","TDD,BDD,CI/CD,カオスエンジニアリング,アジャイルQA",
 "TDD,BDD,CI/CD,chaos engineering,agile QA",
 "active","secondary",83,9,
 "https://dl.acm.org/doi/10.1145/2950290.2983993","欧米",0.82,
 r"テストカバレッジ目標設定: $C_{branch} = \frac{|branches\_tested|}{|branches\_total|}$。変異スコア: $MS = \frac{|killed\_mutants|}{|total\_mutants|-|equivalent|}$、高MS\rightarrow高テスト品質。",
 "url_present"),

("cs_b3_022","台湾AI産業応用","Taiwan AI Industry Application","Taiwan AI Application Ecosystem",
 "台湾の製造業・医療・農業向けAI応用開発エコシステム。工業技術研究院（ITRI）・台湾大学・台積電AIラボ・半導体製造AI検査の産業実装モデルと国際競争力分析。",
 "半導体製造における画像AI検査でゼロディフェクト達成事例。TSMC AIファブ構想のグローバル影響。",
 "CS/情報工学","AI産業応用",2018,None,"system","製造・医療・農業AI",
 "製造データ可用性・ドメイン専門家との協働・台湾独自規制環境","スマート製造・農業AI・医療画像診断時","台湾の製造AI成功モデルを他国に移転する際の最大の障壁は何か",
 "汎用AI適用","台湾,AI,製造,ITRI,TSMC",
 "Taiwan,AI,manufacturing,ITRI,TSMC",
 "active","secondary",79,8,
 "https://ieeexplore.ieee.org/document/9325053","東アジア",0.88,
 r"製造AI品質指標: 不良検出率 $DR = TP/(TP+FN)$、誤報率 $FAR = FP/(FP+TN)$。AUC最大化制約: $\min_{model}FAR$ s.t. $DR \geq 0.99$（ゼロディフェクト目標）。",
 "url_present"),

("cs_b3_023","サーバーレスコンピューティング設計","Serverless Computing Design","FaaS Architecture Design",
 "AWS Lambda・Google Cloud Functions・Azure FunctionsによるFaaS設計の最適パターン。コールドスタート低減・ステートレス設計・イベント駆動アーキテクチャ・コスト最適化を統合する。",
 "スタートアップのインフラコストを大幅削減。イベント処理・バックエンドAPIのデファクト実装手法に。",
 "CS/情報工学","クラウド工学",2014,None,"architecture","クラウドアプリケーション",
 "ステートレス処理への分解・実行時間<15分・バースト性のあるワークロード","従量制スケーリング・マイクロサービス分解・イベント処理時","コールドスタートのP99レイテンシをどの程度まで許容し設計するか",
 "常時起動サーバー","サーバーレス,Lambda,FaaS,イベント駆動,コールドスタート",
 "serverless,Lambda,FaaS,event-driven,cold start",
 "active","secondary",84,9,
 "https://dl.acm.org/doi/10.1145/3377811.3380438","欧米",0.82,
 r"コールドスタートレイテンシモデル: $T_{cold} = T_{alloc} + T_{init} + T_{load}$。Keepalive最適化: ウォームインスタンス比率 $p_w = 1-e^{-\lambda/\mu}$（$\lambda$: リクエスト率、$\mu$: コンテナ廃棄率）。",
 "url_present"),

("cs_b3_024","ロボット計画学習統合","Robot Task and Motion Planning with Learning","Robot TAMP+Learning",
 "古典的タスクおよびモーション計画（TAMP）と機械学習を統合したロボット自律化手法。PDDLタスク計画・RRT* モーション計画・学習ベーススキル取得・Foundation Modelとの融合を扱う。",
 "汎用ロボットの自律行動範囲拡大に直結。FoundationModelベースロボット（RT-2）で言語指示従いを実証。",
 "CS/情報工学","ロボットソフトウェア工学",2018,None,"algorithm","汎用ロボット",
 "環境モデル（部分的でも可）・スキルライブラリの構築・センサ融合","家庭用ロボット・倉庫自動化・医療補助ロボット開発時","シンボリック計画と連続空間計画のギャップをどのように埋めるか",
 "手動プログラムロボット","TAMP,PDDL,RRT,Foundation Model,ロボット計画",
 "TAMP,PDDL,RRT,Foundation Model,robot planning",
 "active","secondary",79,6,
 "https://arxiv.org/abs/2212.06817","欧米",0.8,
 r"RRT*コスト収束: $c^* = \lim_{n\to\infty}c(T_n)$（漸近的最適性）、収束レート $|c(T_n)-c^*| = O(\log(n)/n)^{1/d}$。PDDL行動コスト最小化: $\min\sum_{a\in\pi}cost(a)$。",
 "url_present"),

("cs_b3_025","エッジAI推論最適化","Edge AI Inference Optimization","TinyML and Edge AI Optimization",
 "組み込み・エッジデバイスでのDNN推論最適化手法。量子化（INT8/INT4）・枝刈り・知識蒸留・Neural Architecture Search・TensorRT・TFLite・ONNX Runtime最適化を統合する。",
 "スマートフォン・IoT・自動車ECUへのAI搭載を実現。TinyMLで10mW以下のマイコンにDNNを搭載。",
 "CS/情報工学","組み込みAI工学",2018,None,"algorithm","エッジ・IoT・自動車",
 "ターゲットハードウェアの計算・メモリ・電力制約・精度要件","スマートカメラ・ウェアラブル・車載AIシステム設計時","量子化による精度劣化を最小化しながら4bit量子化を達成する手法は何か",
 "クラウドAI推論","量子化,枝刈り,TinyML,エッジAI,知識蒸留",
 "quantization,pruning,TinyML,edge AI,knowledge distillation",
 "active","secondary",86,9,
 "https://arxiv.org/abs/1712.01887","東アジア",0.82,
 r"PTQ量子化誤差: $\|W - Q(W)\|^2 \leq \frac{\Delta^2}{3}$、$\Delta = (W_{max}-W_{min})/2^b$（$b$: ビット数）。知識蒸留損失: $\mathcal{L} = (1-\alpha)\mathcal{L}_{CE} + \alpha T^2 \mathcal{L}_{KD}$。",
 "url_present"),

("cs_b3_026","マルチモーダルAIシステム","Multimodal AI System Design","Multimodal AI Engineering",
 "テキスト・画像・音声・動画・センサデータを統合処理するマルチモーダルAIシステムの設計手法。クロスアテンション・モダリティアライメント・GPT-4V・Gemini・LLaVAアーキテクチャを扱う。",
 "医療診断・自動運転・ロボット認知の複合知覚を実現。GPT-4VによるVQA性能が人間水準に到達。",
 "CS/情報工学","マルチモーダルAI工学",2021,None,"algorithm","医療・自動車・ロボット",
 "各モダリティのエンコーダ設計・アライメントデータの収集・融合戦略の選択","VQA・医療レポート生成・マルチモーダルチャットbot構築時","モダリティ間の意味的整合をどのように学習させるか",
 "単一モダリティAI","マルチモーダル,クロスアテンション,GPT-4V,LLaVA,Gemini",
 "multimodal,cross-attention,GPT-4V,LLaVA,Gemini",
 "active","secondary",84,8,
 "https://arxiv.org/abs/2304.08485","欧米",0.85,
 r"クロスモーダルアテンション: $Attn(Q_{text},K_{img},V_{img}) = softmax\left(\frac{Q_{text}K_{img}^T}{\sqrt{d_k}}\right)V_{img}$。CLIP類似度: $s = \frac{f_I(x)\cdot f_T(y)}{\|f_I(x)\|\|f_T(y)\|}$。",
 "url_present"),

("cs_b3_027","サイバーフィジカルシステム設計","Cyber-Physical System Design","CPS Engineering",
 "物理プロセスとデジタル制御を緊密に統合するCPSの設計手法。リアルタイム制約・安全性・信頼性・攻撃耐性を満たすアーキテクチャ設計とWaterfall/アジャイル検証を統合する。",
 "スマートファクトリー・自動運転・スマートグリッド・医療機器の設計基盤。IEC 61511等で安全規格化。",
 "CS/情報工学","組み込みシステム工学",2008,None,"architecture","製造・交通・医療",
 "リアルタイム制約（<1ms）・安全整合性レベル（SIL）・フォールトトレランス設計","インダストリー4.0・スマートモビリティ・スマートグリッド設計時","CPSのデジタルツインと物理系の同期遅延をどう許容するか",
 "純粋デジタルシステム","CPS,リアルタイム,安全性,スマートファクトリー,デジタルツイン",
 "CPS,real-time,safety,smart factory,digital twin",
 "active","secondary",82,8,
 "https://dl.acm.org/doi/10.1145/3131672.3131673","欧米",0.82,
 r"リアルタイムスケジューリング（EDF）: $U = \sum_i C_i/T_i \leq 1$（可スケジュール条件）。CPS応答時間解析: $R_i = C_i + \sum_{j\in hp(i)}\lceil R_i/T_j\rceil C_j$（応答時間繰り返し計算）。",
 "url_present"),

("cs_b3_028","プログラム解析・脆弱性検出","Program Analysis for Vulnerability Detection","Static/Dynamic Program Analysis",
 "ソフトウェアの脆弱性を静的・動的解析で検出する手法。データフロー解析・タイント解析・ファジング（AFL++）・シンボリック実行（angr）・LLMベース脆弱性検出の比較と組み合わせを扱う。",
 "ソフトウェアサプライチェーン攻撃（SolarWinds等）対策の中核技術。GitHubが静的解析ツールを標準統合。",
 "CS/情報工学","セキュリティ工学",2005,None,"method","ソフトウェアセキュリティ",
 "ソースコードまたはバイナリのアクセス・テスト実行環境・脆弱性クラスの特定","OSS監査・セキュリティ審査・脆弱性ハンティング時","ファジングとシンボリック実行のハイブリッド（Concolic）手法が最も有効な状況は何か",
 "マニュアルコードレビュー","プログラム解析,ファジング,タイント解析,AFL,angr",
 "program analysis,fuzzing,taint analysis,AFL,angr",
 "active","secondary",83,9,
 "https://www.ndss-symposium.org/ndss-paper/afl/","欧米",0.83,
 r"タイント伝播: $T(v_1 \oplus v_2) = T(v_1) \cup T(v_2)$、$T(v[idx]) = T(v) \cup T(idx)$（conservative）。ファジングカバレッジ: $C_{branch} = |unique\_branches\_hit|$、AFL power schedule $p_i = \frac{c_i}{\sum_j c_j}$。",
 "url_present"),

("cs_b3_029","グラフデータベース設計","Graph Database Design","Graph DB Engineering",
 "Neo4j・ArangoDB・Amazon Neptune等のグラフDBのスキーマ設計・クエリ最適化・分散グラフ処理の手法。知識グラフ・推薦システム・詐欺検知のデータモデリングを扱う。",
 "MetaのSocialGraph・AmazonのProduct Graph・Googleの知識グラフの基盤技術として大規模実用化。",
 "CS/情報工学","データベース工学",2010,None,"system","知識グラフ・推薦・詐欺検知",
 "エンティティ・関係の明確化・トラバーサルパターンの分析・スケール要件","ソーシャルネットワーク分析・推薦エンジン・不正取引検知設計時","RDBとグラフDBの使い分けの境界条件はどのように定義するか",
 "リレーショナルDB","グラフDB,Neo4j,知識グラフ,Cypher,グラフアルゴリズム",
 "graph database,Neo4j,knowledge graph,Cypher,graph algorithm",
 "active","secondary",83,9,
 "https://dl.acm.org/doi/10.1145/3340531.3412773","欧米",0.82,
 r"グラフ検索複雑度（BFS）: $O(V+E)$、深さ$d$のトラバーサル $O(b^d)$（$b$: 平均分岐度）。PageRank: $PR(v) = (1-d)/N + d\sum_{u\to v}PR(u)/L(u)$、収束時間 $O(\log N/\varepsilon)$。",
 "url_present"),

("cs_b3_030","日本オープンソース開発コミュニティ","Japan Open Source Software Community","Japan OSS Development",
 "まつもとゆきひろ（Ruby）・田中哲（YARV）・日本Rubyの会等が形成する日本発OSSエコシステム。Ruby on Railsの国際標準化・日本Linuxカーネルコントリビューター・オープン標準策定への貢献。",
 "Ruby on RailsがWebフレームワークの世界標準に。日本人エンジニアのLinuxカーネルコントリビュートが持続。",
 "CS/情報工学","OSS工学",2000,None,"system","Web開発・OSS",
 "コミュニティガバナンス・国際コミュニケーション・ライセンス選択","国際OSS貢献・Rubyエコシステム活用時","日本発OSSが国際標準化されるための鍵となる要因は何か",
 "商用ソフトウェア開発","Ruby,OSSコミュニティ,まつもと,RubyVM,Linuxカーネル",
 "Ruby,OSS community,Matz,RubyVM,Linux kernel",
 "active","secondary",80,9,
 "https://www.ruby-lang.org/en/about/","東アジア",0.88,
 r"Rubyオブジェクトメモリ: オブジェクト$obj$は最小40byte（64bit RVALUE構造体）。YARV命令セット: $\text{opt\_plus}(a,b) \Rightarrow \text{stack}[sp] = a+b$（特化命令でインタプリタオーバーヘッド削減）。",
 "url_present"),

("cs_b3_031","テキスト分類・情報抽出パイプライン","Text Classification and Information Extraction Pipeline","NLP IE Pipeline",
 "文書分類・固有表現認識・関係抽出・イベント検出を統合したNLP情報抽出パイプラインの設計手法。BERTファインチューニング・SpaCy・Haystack・RAGとの統合を扱う。",
 "法的文書解析・医療記録NLP・ニュース監視システムの自動化基盤。",
 "CS/情報工学","NLP工学",2019,None,"algorithm","文書理解・情報検索",
 "アノテーション済み訓練データ（数百件以上）・前処理パイプラインの設計","法律・医療・金融文書の自動解析時","低リソース言語での情報抽出精度向上のためのtransfer学習戦略は何か",
 "ルールベースNLP","NER,関係抽出,BERT,RAG,情報抽出",
 "NER,relation extraction,BERT,RAG,information extraction",
 "active","secondary",84,9,
 "https://arxiv.org/abs/1810.04805","欧米",0.83,
 r"BERTトークナイゼーション後のNER損失（CRF）: $\mathcal{L} = -\log P(y|x) = -\log\frac{\exp(\sum_t s(y_{t-1},y_t,x))}{\sum_{\tilde y}\exp(\sum_t s(\tilde y_{t-1},\tilde y_t,x))}$。",
 "url_present"),

("cs_b3_032","分散データベーストランザクション管理","Distributed Database Transaction Management","Distributed ACID Transaction",
 "地理的分散DBにおけるACIDトランザクションの実現手法。2PL・2PCプロトコル・Paxos/Raft合意・CockroachDB・Spanner・Percolatorの設計と一貫性モデル（線形化可能性・最終一致性）の選択。",
 "Google Spannerが世界規模でACIDを実現し分散DBの概念を刷新。",
 "CS/情報工学","分散システム工学",2000,None,"system","分散データベース",
 "分散トランザクション要件（CAP定理の制約）・地理的遅延の許容範囲・一貫性レベル設定","グローバルサービス・金融送金・在庫管理システム設計時","ネットワーク分断時に可用性と一貫性のどちらを優先するか",
 "単一ノードRDB","2PC,Paxos,Raft,Spanner,線形化可能性",
 "2PC,Paxos,Raft,Spanner,linearizability",
 "active","secondary",84,9,
 "https://dl.acm.org/doi/10.14778/2536206.2536225","欧米",0.83,
 r"Raft合意: リーダー選出で過半数$(n+1)/2$の投票を要求。TrueTime不確実性（Spanner）: $\epsilon \leq 7$ ms、外部一貫性: $t_{abs}(e_1) < t_{abs}(e_2)$ iff $commit_1 < start_2$。",
 "url_present"),

("cs_b3_033","AIによる科学的発見支援","AI-Assisted Scientific Discovery","AI for Science",
 "AlphaFold2・GNoME・FunSearch等のAIツールによる科学的発見（タンパク質折り畳み・材料探索・数学定理発見）の手法。AI生成仮説・実験設計・結果解釈を含む科学的知識生産の変革。",
 "AlphaFold2が2億超のタンパク質構造を解析し生命科学の研究速度を革新。Nature誌が2023年科学成果No.1に選出。",
 "CS/情報工学","科学AI工学",2020,None,"algorithm","生命科学・材料科学",
 "高品質な科学データベース・ドメイン専門家との協働・モデル解釈性評価","タンパク質設計・新材料探索・数学証明支援時","AIの発見をどのように実験的に検証し知識として確立するか",
 "従来実験・シミュレーション","AlphaFold2,科学AI,GNoME,タンパク質設計,AI for Science",
 "AlphaFold2,AI for science,GNoME,protein design,scientific discovery",
 "active","secondary",85,8,
 "https://www.nature.com/articles/s41586-021-03819-2","欧米",0.85,
 r"AlphaFold2の誤差: $RMSD_{backbone} < 1\text{ Å}$ for easy targets. Evoformerアテンション: $A_{ij} = softmax_j\left(\frac{q_i^Tk_j}{\sqrt{d}}+b_{ij}\right)$、$b_{ij}$はペアwise bias（構造情報）。",
 "url_present"),

("cs_b3_034","デジタルアイデンティティ管理","Digital Identity Management","Digital Identity Engineering",
 "自己主権型ID（SSI）・分散型識別子（DID）・検証可能クレデンシャル（VC）・OpenID Connect・FIDO2を組み合わせたデジタルアイデンティティシステムの設計手法。",
 "EU eIDAS 2.0・国際SDG金融包摂・マイナンバーカードのデジタル化基盤として標準化が進む。",
 "CS/情報工学","アイデンティティ工学",2015,None,"system","認証・プライバシー",
 "信頼ルートの設計・W3C DID/VC標準準拠・秘密鍵管理","デジタル政府・金融包摂・学術認証システム構築時","中央集権型IDと分散型IDの実際のセキュリティリスクの比較はどう評価するか",
 "中央集権型認証（LDAP）","DID,VC,SSI,FIDO2,eIDAS",
 "DID,VC,SSI,FIDO2,eIDAS",
 "active","secondary",79,7,
 "https://www.w3.org/TR/did-core/","欧米",0.8,
 r"DIDドキュメント検証: DID$\xrightarrow{resolve}$DID Doc$\xrightarrow{verify}$PublicKey$\xrightarrow{verify}$VC Signature。ゼロ知識証明（ZKP）: $\exists w: V(x,w)=1$ without revealing $w$。",
 "url_present"),

("cs_b3_035","リアルタイム3Dレンダリング最適化","Real-Time 3D Rendering Optimization","GPU Rasterization and Ray Tracing Optimization",
 "ゲームエンジン・メタバース・XR向けリアルタイム3Dレンダリングの最適化手法。LOD・カリング・レイトレーシング（DLSS・FSR）・ジオメトリシェーダ・メッシュシェーダの統合設計。",
 "Xbox/PS5のリアルタイムレイトレーシング・NVIDIA DLSSが2Dレンダリングの品質閾値を突破。",
 "CS/情報工学","コンピュータグラフィクス工学",2018,None,"algorithm","ゲーム・XR・メタバース",
 "ターゲットGPUの性能プロファイル・フレームレート目標（60fps/120fps）・グラフィクスAPI選択","ゲームエンジン最適化・メタバース構築・産業3D可視化時","レイトレーシングとラスタライズの品質-コストトレードオフの最適分割点は何か",
 "固定機能パイプライン","レイトレーシング,DLSS,メッシュシェーダ,LOD,リアルタイム3D",
 "ray tracing,DLSS,mesh shader,LOD,real-time 3D",
 "active","secondary",83,9,
 "https://arxiv.org/abs/2110.09087","欧米",0.82,
 r"レンダリング方程式: $L_o(x,\omega_o) = L_e(x,\omega_o) + \int_\Omega f_r(x,\omega_i,\omega_o)L_i(x,\omega_i)(\omega_i\cdot n)d\omega_i$。DLSS超解像: 低解像度→高解像度にニューラルアップスケール。",
 "url_present"),

("cs_b3_036","知識グラフ構築・補完","Knowledge Graph Construction and Completion","Knowledge Graph Engineering",
 "エンティティ・関係の自動抽出と知識グラフ（KG）の構築手法。OpenIE・REBEL・TransE・RotatE等のKGE手法・リンク予測・知識グラフ補完・LLMとのRAG統合を扱う。",
 "Google Knowledge Graph・Wikidata・業界特化KGの自動構築・品質向上に利用。LLMのファクト強化基盤。",
 "CS/情報工学","知識工学",2013,None,"algorithm","情報検索・AI推論",
 "エンティティアラインメント基準・KGEモデルの評価指標（MRR・Hits@K）設定","LLMファクト強化・エンタープライズKG構築・推薦システム時","KGEの表現力と解釈性のトレードオフをどう設計するか",
 "RDBによる関係管理","知識グラフ,KGE,TransE,リンク予測,RAG",
 "knowledge graph,KGE,TransE,link prediction,RAG",
 "active","secondary",83,8,
 "https://arxiv.org/abs/1301.3666","欧米",0.82,
 r"TransEスコア: $d(h+r,t) = \|h+r-t\|$（低スコアが正しいトリプル）。RotatEの関係モデリング: $t = h \circ r$（複素数空間でのHadamard積）。MRR $= \frac{1}{|T|}\sum_i\frac{1}{rank_i}$。",
 "url_present"),

("cs_b3_037","量子機械学習アルゴリズム","Quantum Machine Learning Algorithms","QML Engineering",
 "量子コンピュータを用いた機械学習アルゴリズムの設計。量子カーネル法・変分量子分類器（VQC）・量子ニューラルネットワーク・量子確率的勾配降下法の実装と古典MLとの性能比較。",
 "NIQ量子コンピュータでの量子優位性が議論中。理論的には指数的高速化可能性を示す手法が複数提案。",
 "CS/情報工学","量子コンピューティング",2019,None,"algorithm","量子機械学習",
 "NISQデバイスアクセス・古典-量子ハイブリッド設計・量子データエンコーディング","量子優位性実証・高次元特徴空間分類時","量子カーネルが古典カーネルを超えるための必要十分条件は何か",
 "古典機械学習","量子機械学習,VQC,量子カーネル,QNN,NISQ",
 "quantum machine learning,VQC,quantum kernel,QNN,NISQ",
 "active","secondary",76,3,
 "https://www.nature.com/articles/s41534-019-0148-9","欧米",0.75,
 r"量子カーネル: $k(x,x') = |\langle\phi(x)|\phi(x')\rangle|^2 = |\langle 0|U^\dagger(x)U(x')|0\rangle|^2$。VQC勾配: パラメータシフト則 $\nabla_\theta f = \frac{f(\theta+\pi/2)-f(\theta-\pi/2)}{2}$。",
 "url_present"),

("cs_b3_038","ソフトウェアデファインドネットワーキング","Software Defined Networking Advanced","Advanced SDN and Network Automation",
 "OpenFlow・P4・ONOS・OpenDaylightを用いたSDN制御プレーン設計の高度化。インテント駆動ネットワーク・NetDevOps・ネットワークスライシング・5G Core Network統合を扱う。",
 "5G Core・クラウドデータセンターのネットワーク自動化基盤として標準化。",
 "CS/情報工学","ネットワーク工学",2011,None,"system","ネットワークインフラ",
 "OpenFlowスイッチ・集中型コントローラ・APIベース管理","5Gネットワーク切断管理・データセンターネットワーク自動化時","SDNコントローラの単一障害点問題への耐障害設計は何か",
 "分散型ネットワーク管理","SDN,OpenFlow,P4,ONOS,ネットワークスライシング",
 "SDN,OpenFlow,P4,ONOS,network slicing",
 "active","secondary",83,9,
 "https://dl.acm.org/doi/10.1145/2043164.2018423","欧米",0.82,
 r"OpenFlowフロー優先度: $\text{match}(pkt, rule_i) \Rightarrow action_i$、優先度$p_i$の高い規則を優先適用。P4プログラム: $\text{header}+\text{parser}+\text{match-action table}$の組み合わせで転送動作定義。",
 "url_present"),

("cs_b3_039","バイオインフォマティクスパイプライン","Bioinformatics Pipeline Design","Computational Biology Pipeline",
 "ゲノム・トランスクリプトーム・プロテオーム解析のバイオインフォマティクスパイプライン設計手法。BWA・STAR・GATK・Snakemake・Nextflowによる再現可能ワークフローと統計解析を扱う。",
 "ヒトゲノム解析コストが2003年の30億ドルから現在200ドル以下へ低下。精密医療の計算基盤。",
 "CS/情報工学","バイオインフォマティクス工学",2001,None,"system","医療・生命科学",
 "ゲノムデータのストレージ・計算リソース・データプライバシー管理","ゲノム変異解析・トランスクリプトーム・創薬標的探索時","バリアント呼び出しの偽陽性率をどのように管理するか",
 "実験室のみの生物学","BWA,GATK,Snakemake,ゲノム,バイオインフォマティクス",
 "BWA,GATK,Snakemake,genome,bioinformatics",
 "active","secondary",84,9,
 "https://www.nature.com/articles/nmeth.1923","欧米",0.83,
 r"Smith-Watermanアライメントスコア: $H(i,j) = \max[0, H(i-1,j-1)+s(a_i,b_j), H(i-1,j)-g, H(i,j-1)-g]$。GATKバリアント品質: $QUAL = -10\log_{10}P(variant\_false)$。",
 "url_present"),

("cs_b3_040","プロセッサアーキテクチャ最適化","Processor Architecture Optimization","Superscalar and Out-of-Order Execution",
 "スーパースカラ・アウトオブオーダー実行・分岐予測・メモリ階層最適化の現代プロセッサ設計手法。RISC-V・ARMv9・Apple Mシリーズのアーキテクチャ革新の分析と設計原則。",
 "Apple M2がx86設計に対し電力性能比で2倍を達成。RISC-Vがオープン標準として産業普及。",
 "CS/情報工学","コンピュータアーキテクチャ",1990,None,"architecture","プロセッサ設計",
 "IPC・クロック周波数・TDP・ISA選択の多目的最適化","高性能プロセッサ設計・省電力CPU開発時","分岐予測精度がIPCに与える影響の定量モデルは何か",
 "単純なパイプライン実行","スーパースカラ,OOO,分岐予測,RISC-V,Apple M",
 "superscalar,OOO,branch prediction,RISC-V,Apple M",
 "active","secondary",84,9,
 "https://dl.acm.org/doi/10.1145/3140659.3080246","東アジア",0.8,
 r"IPC解析: $IPC = 1/(CPI)$、パイプラインCPI $= 1 + \text{stall}/\text{instr}$。トマスーロアルゴリズム（ROB）: 最大$N_{ROB}$命令を同時発行、データ依存解決後フォワーディング。",
 "url_present"),

("cs_b3_041","コード解析・リファクタリング自動化","Automated Code Analysis and Refactoring","Automated Program Transformation",
 "ソースコード品質分析・技術的負債定量化・自動リファクタリングツールの設計手法。AST解析・LLMによるコード変換・SonarQube・Semgrep・OpenRewriteの適用戦略。",
 "大規模コードベースのメンテナンスコスト削減。Meta Safecodex・GoogleによるLLMリファクタリングが生産性向上。",
 "CS/情報工学","ソフトウェア工学",2010,None,"method","ソフトウェア保守",
 "AST/CFGアクセス・技術的負債の定量基準（複雑度・重複率）設定","レガシーコード近代化・コード品質向上・マイグレーション時","LLMによる自動リファクタリングの正確性をどう検証するか",
 "手動コードレビュー","リファクタリング,AST,技術的負債,SonarQube,LLM",
 "refactoring,AST,technical debt,SonarQube,LLM",
 "active","secondary",81,8,
 "https://dl.acm.org/doi/10.1145/3387904.3389273","欧米",0.8,
 r"循環複雑度: $CC = E - N + 2P$（$E$: エッジ数、$N$: ノード数、$P$: 連結成分数）。保守性指数: $MI = 171 - 5.2\ln(HV) - 0.23 CC - 16.2\ln(LOC)$（Microsoftの定義）。",
 "url_present"),

("cs_b3_042","自動音声認識・合成最先端手法","State-of-the-Art ASR and TTS Systems","End-to-End ASR TTS Engineering",
 "Whisper・wav2vec2.0・Conformerによる最先端ASRと、VITS・NaturalSpeech・VoiceBoxによるニューラルTTSの実装手法。CTC・RNN-T・Attention Encoder-Decoder・拡散TTSの比較設計。",
 "OpenAI Whisperが多言語ASRの精度上限を更新。NaturalSpeech2が人間の自然性スコアに到達。",
 "CS/情報工学","音声工学",2019,None,"algorithm","音声インターフェース・アシスタント",
 "大規模音声データ（1000時間以上）・ノイズ環境評価・多言語対応要件","音声アシスタント・会議文字起こし・多言語TTSシステム構築時","ノイズロバスト性と言語多様性の同時最大化戦略は何か",
 "HMMベースASR","Whisper,ASR,TTS,CTC,Conformer",
 "Whisper,ASR,TTS,CTC,Conformer",
 "active","secondary",84,9,
 "https://arxiv.org/abs/2212.04356","欧米",0.84,
 r"CTCアライメント確率: $P(y|x) = \sum_{\pi:\mathcal{B}(\pi)=y}\prod_t P(\pi_t|x_t)$、$\mathcal{B}$: CTC collapse。RNN-T: $P(y|x) = \sum_{\text{alignments}}\prod_{t,u}P(y_u|t,u)$。",
 "url_present"),

("cs_b3_043","プライバシー強化技術（PET）実装","Privacy Enhancing Technology Implementation","PET Engineering",
 "差分プライバシー・同型暗号・TEE（信頼実行環境）・データアノニマイゼーション・k-匿名性の実装手法。GDPR/CCPA対応AI・プライバシー保護データ分析システムの設計を扱う。",
 "GDPR施行後の規制適合システム設計の基盤。Appleがオンデバイス差分プライバシーをiOSに実装。",
 "CS/情報工学","プライバシー工学",2015,None,"method","プライバシー保護システム",
 "プライバシー予算$\varepsilon$の設定・感度分析・リスクモデリング","医療データ分析・センシティブ機械学習・コンプライアンス対応時","差分プライバシーの$\varepsilon$値の実用的な選択基準はどのように決めるか",
 "データ削除・匿名化のみ","差分プライバシー,同型暗号,TEE,k-匿名性,GDPR",
 "differential privacy,homomorphic encryption,TEE,k-anonymity,GDPR",
 "active","secondary",83,8,
 "https://arxiv.org/abs/1702.07476","欧米",0.83,
 r"差分プライバシー: $M$が$(\varepsilon,\delta)$-DPを満たす iff $\Pr[M(D)\in S] \leq e^\varepsilon\Pr[M(D')\in S]+\delta$（隣接DB $D,D'$）。Gaussianメカニズム: $\sigma \geq \frac{\Delta f\sqrt{2\ln(1.25/\delta)}}{\varepsilon}$。",
 "url_present"),

("cs_b3_044","計算幾何アルゴリズム応用","Computational Geometry Algorithm Applications","Computational Geometry Engineering",
 "凸包・Voronoi図・Delaunay三角形分割・最小スパニングツリー・ポリゴン交差判定の実装と、3Dメッシュ処理・CAD・GIS・ロボット経路計画への応用を扱う。",
 "自動運転の地図処理・GIS解析・3DプリントスライサーのCGアルゴリズム基盤。",
 "CS/情報工学","計算幾何工学",1980,None,"algorithm","CAD・GIS・ロボット",
 "点・線・多角形データの入力形式・精度（浮動小数点誤差）管理","地図解析・メッシュ生成・コリジョン検知設計時","浮動小数点演算の丸め誤差がロバストネスに与える影響をどう対処するか",
 "グリッドベース処理","Voronoi,Delaunay,凸包,計算幾何,ロボット経路",
 "Voronoi,Delaunay,convex hull,computational geometry,robot path",
 "active","primary",83,9,
 "https://link.springer.com/book/10.1007/978-3-540-77974-2","欧米",0.82,
 r"Fortuneアルゴリズム（Voronoi）: $O(n\log n)$時間・$O(n)$空間。Delaunay条件: 三角形の外接円内に他の点がない $\Leftrightarrow$ 最小角度最大化。凸包Graham scan: $O(n\log n)$。",
 "url_present"),

("cs_b3_045","ハードウェアアクセラレータ設計","Hardware Accelerator Design","ASIC and GPU Accelerator Engineering",
 "AI・暗号・ビデオコーデック・信号処理向けASICおよびGPUアクセラレータの設計手法。ルーフラインモデルによる性能分析・HBMメモリシステム・DFX（設計-製造-テスト統合）を扱う。",
 "NVIDIA H100・Google TPU・Apple Neural Engineがそれぞれの領域でASIC優位性を実証。",
 "CS/情報工学","コンピュータアーキテクチャ",2010,None,"device","AI・HPC・信号処理",
 "演算量・メモリアクセスパターン・電力制約の事前解析","AI推論・科学計算・リアルタイム信号処理高速化時","ルーフラインモデルでメモリ律速と演算律速の境界を定量的に見極めるか",
 "汎用CPUのみ","ASIC,GPU,TPU,ルーフラインモデル,HBM",
 "ASIC,GPU,TPU,roofline model,HBM",
 "active","secondary",85,9,
 "https://dl.acm.org/doi/10.1145/1816038.1816004","欧米",0.83,
 r"ルーフラインモデル: $P_{perf} = \min(P_{peak}, I \cdot BW_{mem})$、$I$: 演算強度[FLOP/byte]。演算律速条件: $I > P_{peak}/BW_{mem} = \text{Ridge Point}$。",
 "url_present"),

("cs_b3_046","インターネットof Behaviors（IoB）設計","Internet of Behaviors System Design","IoB Engineering",
 "IoTセンサ・ビッグデータ・行動分析AIを統合してユーザー行動を観測・影響するIoBシステムの設計。デジタル疫学・保険テレマティクス・スマートリテール・労働安全管理への応用を含む。",
 "COVID-19接触追跡から始まり保険・健康管理・マーケティングへ拡大。プライバシー・倫理的課題と隣り合わせ。",
 "CS/情報工学","IoTシステム工学",2021,None,"system","ヘルスケア・保険・リテール",
 "倫理的同意設計・プライバシー規制適合（GDPR）・行動データ品質管理","健康行動促進・個別化保険設計・安全管理モニタリング時","IoB収集データの倫理的利用と商業利用の境界をどのように設計するか",
 "人口レベルの行動調査","IoB,行動分析,テレマティクス,デジタル疫学,プライバシー",
 "IoB,behavior analytics,telematics,digital epidemiology,privacy",
 "active","secondary",77,5,
 "https://www.gartner.com/en/documents/3991837","欧米",0.75,
 r"行動スコアリング: $S_{behavior} = w_1 f_1 + w_2 f_2 + \cdots + w_n f_n$、$f_i$:行動特徴量。保険リスク予測: $P(claim|\text{behavior}) = \sigma(W^T\phi_{behavior})$。",
 "url_present"),

("cs_b3_047","データレイクハウスアーキテクチャ","Data Lakehouse Architecture","Lakehouse Engineering",
 "データレイク（Apache Parquet・Delta Lake）とデータウェアハウス（Snowflake・BigQuery）の利点を統合したレイクハウスアーキテクチャの設計。ACID保証・スキーマ進化・タイムトラベルクエリを統合する。",
 "DatabricksがDelta Lakeでレイクハウスを実用化。MLテーブルとBIクエリを単一基盤で処理。",
 "CS/情報工学","データ基盤工学",2020,None,"architecture","データ分析基盤",
 "データ量・クエリパターン（BI/ML混在）・レイテンシ要件の分析","大規模データ分析・MLデータパイプライン統合時","Delta Lake vs Icebergの選択基準は何か",
 "独立したDWH+データレイク","レイクハウス,Delta Lake,Iceberg,Parquet,Snowflake",
 "lakehouse,Delta Lake,Iceberg,Parquet,Snowflake",
 "active","secondary",83,8,
 "https://www.vldb.org/pvldb/vol14/p3535-armbrust.pdf","欧米",0.83,
 r"Delta LakeのACID: MVCC（多版型同時実行制御）でスナップショット分離。タイムトラベル: $SELECT * FROM table TIMESTAMP AS OF '2024-01-01'$。Z-Orderクラスタリング: $\min_{\text{file layout}}\sum_{q}scan\_size(q)$。",
 "url_present"),

("cs_b3_048","中国ソフトウェア工学教育・産業連携","China Software Engineering Education and Industry","China SE Education Industry",
 "清華大・北京大・浙江大・電子科技大が主導するソフトウェア工学教育と産業（阿里巴巴・華為・字節跳動）の人材育成連携モデル。中国ACM-ICPC勝利戦略・競技プログラミング文化の分析。",
 "ACM-ICPC世界大会で継続的に上位独占。中国Tech企業の高密度エンジニア採用体制を支える。",
 "CS/情報工学","ソフトウェア工学教育",2000,None,"method","人材育成・産学連携",
 "競技プログラミング訓練体制・産学コーオプ制度・国際標準カリキュラム","中国Tech人材競争力分析・産学連携モデル参照時","中国の競技プログラミング偏重教育が産業実践スキルに与える影響は何か",
 "欧米CS教育モデル","中国,ソフトウェア工学,ACM-ICPC,産学連携,清華大",
 "China,software engineering,ACM-ICPC,industry academia,Tsinghua",
 "active","secondary",78,9,
 "https://ieeexplore.ieee.org/document/9196359","東アジア",0.88,
 r"競技プログラミング複雑度分析: 二分探索 $O(\log n)$、ダイクストラ $O((V+E)\log V)$、FFT畳み込み $O(n\log n)$の組み合わせ最適解法選択がICPC金メダルの鍵。",
 "url_present"),

("cs_b3_049","自然言語生成品質評価","Natural Language Generation Quality Evaluation","NLG Evaluation Engineering",
 "LLMや機械翻訳の出力品質を自動評価する手法の設計。BLEU・ROUGE・BERTScore・G-EVAL・MT-Bench・人間評価との相関分析・ハルシネーション検出メトリクスを統合する。",
 "ChatGPT等のLLM評価の自動化に不可欠。人間評価との相関0.9を超えるメトリクスの開発競争。",
 "CS/情報工学","NLP工学",2002,None,"method","LLM品質管理",
 "参照テキストまたは評価基準（ルーブリック）・評価者の一致率測定","MT・LLM・要約システムの品質ゲート設計時","BLEUとBERTScoreの使い分け基準と限界は何か",
 "人間のみによる評価","BLEU,BERTScore,G-EVAL,MT-Bench,ハルシネーション検出",
 "BLEU,BERTScore,G-EVAL,MT-Bench,hallucination detection",
 "active","secondary",82,9,
 "https://arxiv.org/abs/2303.16634","欧米",0.83,
 r"BLEU: $BP \cdot \exp\left(\sum_{n=1}^N w_n\log p_n\right)$、$p_n$: n-gram精度、$BP$: 簡潔性ペナルティ。BERTScore: $F1 = 2\cdot\frac{P_{BERT}\cdot R_{BERT}}{P_{BERT}+R_{BERT}}$、コサイン類似度ベース。",
 "url_present"),

("cs_b3_050","ウェブアセンブリ高性能アプリケーション","WebAssembly High-Performance Applications","WebAssembly Engineering",
 "WebAssembly（WASM）を用いたブラウザ内高性能計算・ネイティブコード実行・WASM外アプリケーション（WASI・エッジコンピューティング）の設計手法。Emscripten・Wasmer・WasmtimeのランタイムABI設計。",
 "Figma・Google Earth・科学計算のブラウザ内実行で実用化。エッジコンピューティングの軽量サンドボックスとして標準化進む。",
 "CS/情報工学","Web工学",2017,None,"system","Webアプリケーション・エッジ",
 "C/C++/RustのWASMコンパイルチェーン・メモリ管理（線形メモリ）・ABI設計","ブラウザ内高性能計算・エッジサーバーレス・プラグインサンドボックス時","WASMのJIT最適化とAOTコンパイルの使い分けはどのような状況で行うか",
 "JavaScriptのみのWebアプリ","WebAssembly,WASM,WASI,Emscripten,エッジコンピューティング",
 "WebAssembly,WASM,WASI,Emscripten,edge computing",
 "active","secondary",82,8,
 "https://dl.acm.org/doi/10.1145/3062341.3062363","欧米",0.82,
 r"WASM線形メモリ: $mem[i]$は連続バイト配列、アドレス空間最大4GB（32bit WASM）。スタックマシン命令: $i32.add: [i32,i32]\to[i32]$。WASM計算複雑度: オーバーヘッド$<2\times$native。",
 "url_present"),
]

if __name__ == "__main__":
    ins, skp = insert_records(records)
    print(f"Inserted: {ins}, Skipped: {skp}")
    import sqlite3 as _s
    c = _s.connect(DB).cursor()
    c.execute("SELECT COUNT(*) FROM engineering_method")
    print(f"Total: {c.fetchone()[0]}")
