#!/usr/bin/env python3
"""CS/情報工学 Batch 2: cs_b2_001 - cs_b2_050"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

RECORDS = [
    ("cs_b2_001","コンテナオーケストレーション","Container Orchestration","Container Orchestration",
     "複数のコンテナ化されたアプリケーションの展開・スケーリング・管理を自動化する手法。Kubernetesが事実上の標準となっている。",
     "マイクロサービスアーキテクチャの実運用を可能にし、大規模分散システムの管理コストを大幅に削減した。",
     "情報工学・計算機科学","DevOps・クラウドネイティブ",2014,None,"実装技法","分散システム",
     "マイクロサービス・コンテナ化済み","スケーラブルな分散デプロイが必要な場合",
     "サービス間の依存関係は？ヘルスチェック戦略は？","仮想マシンベース展開",
     "コンテナ,オーケストレーション,Kubernetes,DevOps,マイクロサービス",
     "container,orchestration,kubernetes,devops,microservices",
     "active","secondary",85,8,
     "https://kubernetes.io/docs/concepts/overview/","グローバル",0.9,
     "$$\\text{Pod scheduling: } \\min \\sum_{i} c_i x_i \\text{ s.t. } \\sum_{i} r_{ij} x_i \\leq C_j$$",
     "url_present"),

    ("cs_b2_002","形式手法","Formal Methods","Formal Methods",
     "数学的論理に基づいてソフトウェア・ハードウェアシステムの仕様記述・検証・開発を行う技法。TLA+、Alloy、Coqなどが代表的。",
     "安全クリティカルシステムにおけるバグ・設計欠陥の早期発見を可能にし、NASAやIntelなどで実績を持つ。",
     "情報工学・計算機科学","形式検証・プログラム論理",1970,None,"設計・検証技法","安全クリティカルシステム",
     "高信頼性要件・安全クリティカル","仕様の正確な検証が必要な場合",
     "状態空間のサイズは？不変条件は何か？","アジャイル・非形式的手法",
     "形式手法,形式検証,TLA+,Coq,モデル検査",
     "formal methods,formal verification,TLA+,Coq,model checking",
     "active","primary",90,7,
     "https://lamport.azurewebsites.net/tla/tla.html","欧米",0.9,
     "$$\\Box P \\rightarrow \\Diamond Q \\text{ (CTL: Always P leads to Eventually Q)}$$",
     "url_present"),

    ("cs_b2_003","ストリーム処理","Stream Processing","Stream Processing",
     "連続的に到着するデータストリームをリアルタイムで処理するパラダイム。Apache Kafka+Flink、Apache Sparkなどが主要プラットフォーム。",
     "IoT・金融・ソーシャルメディア分野でリアルタイム意思決定を実現し、バッチ処理との差別化を図る。",
     "情報工学・計算機科学","分散・ストリーム処理",2010,None,"実装技法","リアルタイムシステム",
     "連続データストリーム・低レイテンシ要件","リアルタイム集計・異常検知が必要な場合",
     "ウィンドウサイズは？順序保証は必要か？","バッチ処理",
     "ストリーム処理,Kafka,Flink,リアルタイム,ウィンドウ処理",
     "stream processing,kafka,flink,real-time,windowing",
     "active","secondary",85,8,
     "https://nightlies.apache.org/flink/flink-docs-stable/","グローバル",0.9,
     "$$W(t) = \\{e \\in S : t - w \\leq \\text{time}(e) \\leq t\\} \\text{ (sliding window)}$$",
     "url_present"),

    ("cs_b2_004","型推論","Type Inference","Type Inference",
     "プログラムの型を明示的な注釈なしに自動的に推論するアルゴリズム。Hindley-Milner型推論が最も広く使われる。",
     "HaskellやMLなどの関数型言語の実用化を支え、型安全性と開発効率を両立させた。",
     "情報工学・計算機科学","プログラミング言語理論",1969,None,"理論・アルゴリズム","コンパイラ・型システム",
     "静的型付き言語・型注釈削減","型安全なコードを簡潔に書きたい場合",
     "多相型は必要か？型クラスは？","動的型付け",
     "型推論,Hindley-Milner,型システム,関数型プログラミング,多相型",
     "type inference,hindley-milner,type system,functional programming,polymorphism",
     "active","primary",90,9,
     "https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system","欧米",0.9,
     "$$\\frac{\\Gamma \\vdash e_1 : \\tau_1 \\rightarrow \\tau_2 \\quad \\Gamma \\vdash e_2 : \\tau_1}{\\Gamma \\vdash e_1 e_2 : \\tau_2} \\text{ (App rule)}$$",
     "url_present"),

    ("cs_b2_005","差分プライバシー実装","Differential Privacy Implementation","Differential Privacy",
     "個人のプライバシーを数学的に保証しながらデータ分析を行う技術。εパラメータでプライバシー損失を定量化する。",
     "AppleやGoogleが製品に採用し、統計的有用性を保ちながらプライバシー保護を実現する工学的標準となった。",
     "情報工学・計算機科学","プライバシー工学",2006,None,"設計原則","データ分析・機械学習",
     "個人データを含む統計分析・ML","プライバシー保証が法的・倫理的に必要な場合",
     "εの値をどう設定するか？感度はいくらか？","k-匿名化",
     "差分プライバシー,プライバシー保護,ラプラスノイズ,ε-差分プライバシー",
     "differential privacy,privacy-preserving,laplace noise,epsilon-DP",
     "active","primary",90,8,
     "https://arxiv.org/abs/1702.07476","欧米",0.9,
     "$$M(x) = f(x) + \\text{Lap}\\left(\\frac{\\Delta f}{\\varepsilon}\\right) \\text{ is } \\varepsilon\\text{-DP}$$",
     "url_present"),

    ("cs_b2_006","グラフニューラルネットワーク","Graph Neural Network","GNN",
     "グラフ構造データを直接処理するニューラルネットワーク。ノードの埋め込みをメッセージパッシングで計算する。",
     "分子設計・ソーシャルネットワーク分析・知識グラフ推論など非ユークリッドデータへのDL適用を実現した。",
     "情報工学・計算機科学","グラフ機械学習",2009,None,"理論・アルゴリズム","機械学習・グラフ分析",
     "グラフ構造データ・関係性学習","ノード/エッジ/グラフレベルの予測タスク",
     "ホモフィリーの仮定は成立するか？スケーラビリティは？","CNNやRNN",
     "GNN,グラフニューラルネットワーク,メッセージパッシング,グラフ学習",
     "GNN,graph neural network,message passing,graph learning",
     "active","primary",88,8,
     "https://arxiv.org/abs/1901.00596","グローバル",0.9,
     "$$h_v^{(k)} = \\sigma\\left(W^{(k)} \\cdot \\text{AGG}\\left(\\{h_u^{(k-1)} : u \\in \\mathcal{N}(v)\\}\\right)\\right)$$",
     "url_present"),

    ("cs_b2_007","プログラム合成","Program Synthesis","Program Synthesis",
     "仕様・例・自然言語記述から自動的にプログラムを生成する技術。SyGuS（Syntax-Guided Synthesis）が標準的フレームワーク。",
     "テスト駆動開発の自動化やEnd-to-Endプログラミングを可能にし、Copilotなどの先駆けとなった研究領域。",
     "情報工学・計算機科学","プログラム合成・自動化",2010,None,"理論・アルゴリズム","ソフトウェア工学",
     "形式仕様または入出力例が存在","繰り返し作業の自動化・ドメイン特化DSL生成",
     "探索空間の定義は？反例駆動か？","手動コーディング",
     "プログラム合成,SyGuS,自動プログラミング,仕様から合成",
     "program synthesis,SyGuS,auto-programming,spec-to-code",
     "active","primary",85,7,
     "https://arxiv.org/abs/1703.03033","欧米",0.9,
     "$$\\exists P \\in \\mathcal{L} : \\forall (x,y) \\in E, P(x) = y \\text{ (synthesis from examples)}$$",
     "url_present"),

    ("cs_b2_008","量子コンピューティングアルゴリズム","Quantum Computing Algorithms","Quantum Algorithms",
     "量子力学の重ね合わせ・もつれ・干渉を利用した計算アルゴリズム。Shorのアルゴリズム・Groverのアルゴリズムが代表的。",
     "暗号解読・最適化・化学シミュレーションで指数的高速化を実現し、古典的計算の限界を超える可能性を示した。",
     "情報工学・計算機科学","量子情報・量子計算",1994,None,"理論・アルゴリズム","量子コンピューティング",
     "量子ハードウェアまたはシミュレータ","因数分解・探索・量子化学",
     "量子ビット数と深さは？ノイズ耐性は？","古典アルゴリズム",
     "量子アルゴリズム,Shorアルゴリズム,Groverアルゴリズム,量子優位性",
     "quantum algorithms,Shor,Grover,quantum advantage",
     "active","primary",88,4,
     "https://arxiv.org/abs/quant-ph/9508027","グローバル",0.9,
     "$$|\\psi\\rangle = \\frac{1}{\\sqrt{N}}\\sum_{x=0}^{N-1}|x\\rangle \\xrightarrow{\\text{Grover}} |x^*\\rangle \\text{ in } O(\\sqrt{N})$$",
     "url_present"),

    ("cs_b2_009","ベクトルデータベース","Vector Database","Vector Database",
     "高次元ベクトル埋め込みの保存・類似度検索に特化したデータベースシステム。Faiss、Pinecone、Weaviateなどが代表的。",
     "LLMと組み合わせたRAG（検索拡張生成）の基盤技術として2023年以降急速に普及した。",
     "情報工学・計算機科学","データベース・情報検索",2020,None,"実装技法","AI・機械学習インフラ",
     "大規模ベクトル埋め込みが存在","セマンティック検索・RAG・レコメンデーション",
     "インデックス手法は（HNSW/IVF）？精度とパフォーマンスのトレードオフは？","全文検索エンジン",
     "ベクトルデータベース,近似最近傍探索,HNSW,RAG,埋め込み",
     "vector database,ANN search,HNSW,RAG,embeddings",
     "active","secondary",85,9,
     "https://arxiv.org/abs/1603.09320","グローバル",0.9,
     "$$\\text{HNSW: } \\text{recall@k} \\approx 1 - \\exp(-\\alpha k) \\text{ with } O(\\log N) \\text{ search}$$",
     "url_present"),

    ("cs_b2_010","分散トレーシング","Distributed Tracing","Distributed Tracing",
     "マイクロサービスにまたがるリクエストの追跡・可視化技術。OpenTelemetry、Jaeger、Zipkinが標準的ツール。",
     "分散システムのデバッグ・パフォーマンス最適化に不可欠で、SRE（サイト信頼性工学）の基盤となっている。",
     "情報工学・計算機科学","オブザーバビリティ・SRE",2010,None,"実装技法","分散システム",
     "マイクロサービス・複数サービス呼び出し","レイテンシの原因特定・依存グラフ可視化",
     "サンプリングレートは？コンテキスト伝播の方法は？","ログ集約のみ",
     "分散トレーシング,OpenTelemetry,スパン,トレース,オブザーバビリティ",
     "distributed tracing,OpenTelemetry,span,trace,observability",
     "active","secondary",85,9,
     "https://opentelemetry.io/docs/","グローバル",0.9,
     "$$\\text{Trace} = \\{\\text{Span}_1, ..., \\text{Span}_n\\}, \\text{Latency} = \\sum_{i} \\text{dur}(\\text{Span}_i^{\\text{critical}})$$",
     "url_present"),

    ("cs_b2_011","継続的インテグレーション・継続的デリバリー","CI/CD Pipeline","CI/CD",
     "コードの変更を自動的にビルド・テスト・デプロイするパイプライン。GitHub Actions、Jenkins、CircleCIなどが代表的。",
     "ソフトウェアリリースサイクルを大幅に短縮し、品質の継続的な検証を可能にする現代ソフトウェア開発の標準実践。",
     "情報工学・計算機科学","DevOps・自動化",2000,None,"プロセス・方法論","ソフトウェア開発",
     "バージョン管理・自動テストが存在","頻繁なリリース・品質保証の自動化",
     "テストカバレッジは十分か？デプロイ戦略（Blue-Green等）は？","手動デプロイ",
     "CI/CD,継続的インテグレーション,継続的デリバリー,パイプライン,自動化",
     "CI/CD,continuous integration,continuous delivery,pipeline,automation",
     "active","secondary",85,9,
     "https://docs.github.com/en/actions","グローバル",0.9,
     "$$\\text{DORA: Deployment Frequency} \\uparrow, \\text{Lead Time} \\downarrow, \\text{MTTR} \\downarrow, \\text{Change Failure Rate} \\downarrow$$",
     "url_present"),

    ("cs_b2_012","セキュアコーディング","Secure Coding","Secure Coding",
     "脆弱性を排除したソフトウェアを開発するための原則・実践・ツールの体系。OWASP Top 10がリファレンス標準。",
     "SQLインジェクション・バッファオーバーフロー・XSSなどの一般的な脆弱性を設計段階で防ぐ開発文化を確立した。",
     "情報工学・計算機科学","ソフトウェアセキュリティ",1990,None,"設計原則","セキュリティ工学",
     "外部入力を受け付けるすべてのシステム","セキュリティ要件がある開発全般",
     "入力検証はどこで行うか？最小権限の原則は適用されているか？","セキュリティ後付け",
     "セキュアコーディング,OWASP,入力検証,SQLインジェクション対策,XSS対策",
     "secure coding,OWASP,input validation,SQL injection prevention,XSS prevention",
     "active","secondary",88,9,
     "https://owasp.org/www-project-top-ten/","グローバル",0.9,
     "$$\\text{CVSS} = f(\\text{AV}, \\text{AC}, \\text{PR}, \\text{UI}, \\text{S}, \\text{C}, \\text{I}, \\text{A}) \\in [0, 10]$$",
     "url_present"),

    ("cs_b2_013","メモリ安全性プログラミング","Memory-Safe Programming","Memory Safety",
     "バッファオーバーフロー・use-after-free・メモリリークなどのメモリ関連脆弱性を防ぐプログラミング技法。Rustの所有権システムが最先端実装。",
     "NSSAが2023年にメモリ安全言語への移行を推奨し、Chrome・WindowsカーネルへのRust採用が進んでいる。",
     "情報工学・計算機科学","プログラミング言語・安全性",1990,None,"設計原則","システムソフトウェア",
     "システムソフトウェア・低レベルプログラミング","セキュリティと性能を両立したい場合",
     "GCのオーバーヘッドは許容できるか？ゼロコスト抽象化が必要か？","手動メモリ管理",
     "メモリ安全性,Rust所有権,借用チェッカー,ガベージコレクション,use-after-free",
     "memory safety,Rust ownership,borrow checker,garbage collection,use-after-free",
     "active","primary",90,9,
     "https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html","欧米",0.9,
     "$$\\text{Rust: } \\forall \\text{ ref } r, \\text{lifetime}(r) \\subseteq \\text{lifetime}(\\text{owner}) \\Rightarrow \\text{no dangling ptr}$$",
     "url_present"),

    ("cs_b2_014","分散ファイルシステム","Distributed File System","DFS",
     "複数のサーバにまたがってファイルを透過的に保存・アクセスするシステム。HDFS、Ceph、GFS（Google File System）が代表的。",
     "ビッグデータ処理とクラウドストレージの基盤となり、ペタバイト規模のデータ管理を実現した。",
     "情報工学・計算機科学","分散ストレージ",2003,None,"実装技法","分散システム",
     "大規模データ・複数ノード","ペタバイト規模のデータ保存・MapReduceと組み合わせ",
     "一貫性モデルは（強整合性/結果整合性）？レプリケーション係数は？","ローカルファイルシステム",
     "分散ファイルシステム,HDFS,Ceph,レプリケーション,NameNode",
     "distributed file system,HDFS,Ceph,replication,NameNode",
     "active","primary",88,8,
     "https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html","グローバル",0.9,
     "$$\\text{Availability} = 1 - (1-p)^r \\text{ where } p = \\text{node failure prob}, r = \\text{replication factor}$$",
     "url_present"),

    ("cs_b2_015","サービスメッシュ","Service Mesh","Service Mesh",
     "マイクロサービス間の通信を管理するインフラレイヤー。Istioが代表的で、観測性・セキュリティ・トラフィック制御を提供する。",
     "アプリケーションコードからネットワーク制御ロジックを分離し、分散システムの信頼性とセキュリティを向上させた。",
     "情報工学・計算機科学","クラウドネイティブ・ネットワーク",2017,None,"アーキテクチャ","分散システム",
     "マイクロサービス・Kubernetes環境","mTLS・サーキットブレーカー・トラフィックシェーピングが必要",
     "オーバーヘッドは許容できるか？サイドカーパターンで十分か？","APIゲートウェイのみ",
     "サービスメッシュ,Istio,Envoy,mTLS,サーキットブレーカー",
     "service mesh,Istio,Envoy,mTLS,circuit breaker",
     "active","secondary",85,8,
     "https://istio.io/latest/docs/concepts/what-is-istio/","グローバル",0.9,
     "$$\\text{Circuit Breaker: } \\text{State} = \\begin{cases} \\text{Open} & \\text{if failure rate} > \\theta \\\\ \\text{Closed} & \\text{otherwise} \\end{cases}$$",
     "url_present"),

    ("cs_b2_016","静的解析","Static Analysis","Static Analysis",
     "プログラムを実行せずにソースコードを解析して欠陥・脆弱性・品質問題を検出する技法。データフロー解析・抽象解釈が理論的基盤。",
     "Coverity・Infer・SonarQubeなどのツールがCI/CDに組み込まれ、大規模コードベースの品質管理を自動化した。",
     "情報工学・計算機科学","プログラム解析",1970,None,"検証技法","ソフトウェア品質",
     "ソースコードへのアクセスがある","コードレビュー補助・脆弱性検出・コード品質向上",
     "誤検知（偽陽性）の許容率は？解析の深さは？","動的テスト",
     "静的解析,データフロー解析,抽象解釈,Coverity,Infer",
     "static analysis,data flow analysis,abstract interpretation,Coverity,Infer",
     "active","primary",88,9,
     "https://research.fb.com/publications/infer-interprocedural-program-verification/","欧米",0.9,
     "$$\\text{Abstract Interpretation: } \\alpha(f(x)) \\sqsubseteq f^\\#(\\alpha(x)) \\text{ (soundness)}$$",
     "url_present"),

    ("cs_b2_017","ニューラルアーキテクチャ探索","Neural Architecture Search","NAS",
     "機械学習モデルのアーキテクチャを自動的に探索・最適化する技術。強化学習・進化的手法・勾配ベース手法が主なアプローチ。",
     "GoogleのNASNetがImageNetで人手設計を超え、EfficientNetシリーズなどの高効率モデルファミリーを生み出した。",
     "情報工学・計算機科学","自動機械学習",2017,None,"理論・アルゴリズム","機械学習・AutoML",
     "大規模計算リソースまたはプロキシタスク","最高性能モデルの自動設計が必要",
     "探索空間の定義は？評価プロキシの妥当性は？","手動アーキテクチャ設計",
     "NAS,ニューラルアーキテクチャ探索,AutoML,DARTS,EfficientNet",
     "NAS,neural architecture search,AutoML,DARTS,EfficientNet",
     "active","primary",87,7,
     "https://arxiv.org/abs/1802.03268","グローバル",0.9,
     "$$\\min_{\\alpha} \\mathcal{L}_{val}(w^*(\\alpha), \\alpha), \\text{ s.t. } w^*(\\alpha) = \\arg\\min_w \\mathcal{L}_{train}(w, \\alpha)$$",
     "url_present"),

    ("cs_b2_018","因果推論機械学習","Causal Machine Learning","Causal ML",
     "機械学習と因果推論を組み合わせ、観測データから因果効果を推定する手法。DoCalculus・PotentialOutcomes・DML（二重機械学習）が代表的。",
     "A/Bテストが不可能な場合の政策評価・医療効果推定・業務介入設計に応用され、相関から因果への転換を実現する。",
     "情報工学・計算機科学","因果推論・統計的学習",2000,None,"理論・アルゴリズム","データ科学",
     "観測データ・介入変数・結果変数が存在","因果効果推定・反実仮想分析",
     "交絡変数は制御されているか？識別可能性の仮定は成立するか？","相関分析のみ",
     "因果推論,双機械学習,操作変数,傾向スコア,DoCalculus",
     "causal inference,double machine learning,instrumental variable,propensity score,DoCalculus",
     "active","primary",88,7,
     "https://arxiv.org/abs/1608.00060","欧米",0.9,
     "$$\\hat{\\tau} = \\frac{1}{n}\\sum_i \\hat{m}(X_i)(Y_i - \\hat{\\ell}(X_i)) \\text{ (DML estimator)}$$",
     "url_present"),

    ("cs_b2_019","多腕バンディット","Multi-Armed Bandit","MAB",
     "탐索と活用のトレードオフを最適化する逐次意思決定アルゴリズム。UCB（Upper Confidence Bound）・Thompson Samplingが代表的手法。",
     "ウェブの推薦・A/Bテスト・広告配信・臨床試験適応設計で広く使われ、強化学習の基盤理論を形成する。",
     "情報工学・計算機科学","強化学習・意思決定",1952,None,"理論・アルゴリズム","最適化・推薦システム",
     "報酬フィードバックが順次得られる","A/Bテスト代替・オンライン最適化",
     "アームの数は？報酬分布の仮定は？","完全ランダム化実験",
     "多腕バンディット,UCB,Thompson Sampling,探索と活用,後悔最小化",
     "multi-armed bandit,UCB,Thompson sampling,exploration-exploitation,regret minimization",
     "active","primary",90,9,
     "https://arxiv.org/abs/1402.6028","欧米",0.9,
     "$$\\text{Regret}(T) = T\\mu^* - \\sum_{t=1}^{T} \\mu_{a_t} = O(\\sqrt{KT \\ln T})$$",
     "url_present"),

    ("cs_b2_020","プログラミング言語処理系","Language Runtime","Language Runtime",
     "プログラミング言語のコードを実行するためのソフトウェア基盤。JVM・.NET CLR・V8などが代表的なランタイム実装。",
     "仮想マシン上での実行・JIT最適化・GCを統合し、ポータブルで高性能なプログラム実行環境を実現した。",
     "情報工学・計算機科学","プログラミング言語処理系",1995,None,"実装技法","プログラミング言語",
     "高水準言語とハードウェアの橋渡し","クロスプラットフォーム実行・JIT最適化",
     "インタープリタ・JIT・AOTのトレードオフは？GCアルゴリズムは何が適切か？","ネイティブコンパイル",
     "ランタイム,JVM,JIT,ガベージコレクション,.NET CLR",
     "runtime,JVM,JIT compilation,garbage collection,.NET CLR",
     "active","primary",88,9,
     "https://docs.oracle.com/javase/specs/jvms/se17/html/index.html","グローバル",0.9,
     "$$\\text{JIT speedup} = \\frac{T_{\\text{interp}}}{T_{\\text{JIT}}} \\approx 10\\text{-}100\\times \\text{ for hot loops}$$",
     "url_present"),

    ("cs_b2_021","オペレーティングシステムスケジューリング","OS Scheduling","OS Scheduling",
     "複数のプロセス・スレッドへのCPUリソースを割り当てるアルゴリズム。CFS（Completely Fair Scheduler）・EDF・Rate-Monotonicが代表的。",
     "リアルタイムシステムから汎用OSまで、公平性・スループット・レイテンシのトレードオフを管理する核心技術。",
     "情報工学・計算機科学","オペレーティングシステム",1960,None,"理論・アルゴリズム","システムソフトウェア",
     "複数プロセス・リソース競合","CPU利用効率最大化・リアルタイム応答保証",
     "リアルタイム要件か汎用要件か？優先度の逆転をどう防ぐか？","コルーチン（ユーザースペーススケジューリング）",
     "スケジューリング,CFS,EDF,Rate-Monotonic,リアルタイムOS",
     "scheduling,CFS,EDF,rate-monotonic,real-time OS",
     "active","primary",90,9,
     "https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html","グローバル",0.9,
     "$$\\text{Rate-Monotonic: feasible iff } \\sum_{i=1}^n \\frac{C_i}{T_i} \\leq n(2^{1/n}-1)$$",
     "url_present"),

    ("cs_b2_022","ネットワークプロトコル設計","Network Protocol Design","Network Protocol",
     "異なるシステム間の通信規則を定義する設計技法。TCP/IP・QUIC・gRPCなどのプロトコル設計原則が体系化されている。",
     "QUICプロトコルがHTTP/3の基盤となり、レイテンシ削減と接続性向上で現代Webの高速化に貢献している。",
     "情報工学・計算機科学","ネットワーク工学",1970,None,"設計原則","通信システム",
     "異種システム間通信・信頼性要件","低レイテンシ・信頼性・セキュリティが必要な通信",
     "信頼性保証のレベルは？フロー制御は必要か？","独自バイナリプロトコル",
     "プロトコル設計,TCP,QUIC,gRPC,フロー制御",
     "protocol design,TCP,QUIC,gRPC,flow control",
     "active","primary",90,9,
     "https://datatracker.ietf.org/doc/html/rfc9000","グローバル",0.9,
     "$$\\text{TCP Reno: } W_{t+1} = \\begin{cases} W_t + 1 & \\text{(congestion avoidance)} \\\\ W_t/2 & \\text{(congestion)} \\end{cases}$$",
     "url_present"),

    ("cs_b2_023","知識グラフ","Knowledge Graph","Knowledge Graph",
     "エンティティと関係をグラフ構造で表現したデータ形式。Google Knowledge Graph・WikiData・DBpediaが代表的実装。",
     "検索エンジンの知識拡張・質問応答・推薦システムの意味的基盤として、WebスケールのAI応用を支えている。",
     "情報工学・計算機科学","知識表現・セマンティックWeb",2012,None,"データモデル","情報検索・AI",
     "エンティティと関係が豊富なドメイン","セマンティック検索・知識推論・LLMのグラウンディング",
     "スキーマはどう設計するか？補完（リンク予測）はどうするか？","リレーショナルDB",
     "知識グラフ,KG,エンティティ,関係,WikiData,リンク予測",
     "knowledge graph,KG,entity,relation,WikiData,link prediction",
     "active","secondary",88,9,
     "https://arxiv.org/abs/2003.02320","グローバル",0.9,
     "$$\\text{TransE: } h + r \\approx t \\Rightarrow \\text{score}(h,r,t) = -\\|h+r-t\\|$$",
     "url_present"),

    ("cs_b2_024","コンテナセキュリティ","Container Security","Container Security",
     "Dockerコンテナ・Kubernetesクラスターのセキュリティを確保する技術と実践。イメージスキャン・ランタイム保護・RBAC設定が主要要素。",
     "コンテナの普及に伴い表面化した新たな攻撃ベクトルへの対策として、DevSecOpsの重要な柱となっている。",
     "情報工学・計算機科学","クラウドセキュリティ",2017,None,"設計原則","セキュリティ工学",
     "コンテナ化されたシステム","コンテナ・オーケストレーター環境のセキュリティ強化",
     "特権コンテナは本当に必要か？イメージの出自は信頼できるか？","VMベースセキュリティ",
     "コンテナセキュリティ,イメージスキャン,RBAC,Pod Security,Falco",
     "container security,image scanning,RBAC,pod security,Falco",
     "active","secondary",85,9,
     "https://kubernetes.io/docs/concepts/security/","グローバル",0.9,
     "$$\\text{Threat surface} = \\text{Host} \\cup \\text{Orchestrator} \\cup \\text{Image} \\cup \\text{Registry} \\cup \\text{Network}$$",
     "url_present"),

    ("cs_b2_025","機械学習パイプライン","ML Pipeline","ML Pipeline",
     "データ収集・前処理・特徴量エンジニアリング・学習・評価・デプロイまでの一連のワークフローを自動化する仕組み。",
     "MLOpsの中核として、モデルの再現性・継続的改善・プロダクション品質の確保を実現する。",
     "情報工学・計算機科学","MLOps・機械学習工学",2019,None,"プロセス・方法論","機械学習・データ工学",
     "本番機械学習システム・継続的更新","モデルの継続的デプロイ・実験管理",
     "データドリフトをどう検知するか？モデルバージョン管理は？","Jupyterノートブックのみ",
     "MLパイプライン,MLOps,特徴量ストア,モデルレジストリ,Kubeflow",
     "ML pipeline,MLOps,feature store,model registry,Kubeflow",
     "active","secondary",85,8,
     "https://www.kubeflow.org/docs/","グローバル",0.9,
     "$$\\text{Data Drift: } D_{KL}(P_{train} \\| P_{serve}) > \\epsilon \\Rightarrow \\text{retrain trigger}$$",
     "url_present"),

    ("cs_b2_026","エッジコンピューティング","Edge Computing","Edge Computing",
     "データ処理をクラウドではなくデバイスに近いエッジノードで行うパラダイム。IoT・5G・自動運転に不可欠。",
     "クラウドへの通信レイテンシを排除し、リアルタイム処理・帯域節約・プライバシー保護を同時に実現する。",
     "情報工学・計算機科学","分散・エッジコンピューティング",2016,None,"アーキテクチャ","IoT・組み込みシステム",
     "低レイテンシ・帯域制約・プライバシー要件","自動運転・産業IoT・AR/VRリアルタイム処理",
     "エッジとクラウドの処理分担はどこで引くか？モデル圧縮は必要か？","クラウドのみ",
     "エッジコンピューティング,MEC,IoT,モデル推論,レイテンシ削減",
     "edge computing,MEC,IoT,model inference,latency reduction",
     "active","secondary",87,8,
     "https://arxiv.org/abs/1905.10031","グローバル",0.9,
     "$$\\text{Offloading gain} = T_{local} - (T_{edge\\_proc} + T_{comm}) > 0 \\Rightarrow \\text{offload}$$",
     "url_present"),

    ("cs_b2_027","ハードウェアアクセラレータ設計","Hardware Accelerator Design","Hardware Accelerator",
     "特定計算ワークロード（行列乗算・CNN・暗号化）を高速化するASIC/FPGAの設計手法。Google TPU・NVIDIA GPUが代表例。",
     "DNN学習・推論の計算ボトルネックを解消し、AIシステムの実用化速度と電力効率を劇的に改善した。",
     "情報工学・計算機科学","計算機アーキテクチャ",2016,None,"設計・検証技法","AI・高性能計算",
     "特定計算の繰り返し実行・消費電力制約","DNN加速・暗号処理・信号処理",
     "汎用性vs専用性のトレードオフは？メモリ帯域がボトルネックか？","汎用CPUのみ",
     "アクセラレータ,TPU,GPU,ASIC,FPGA,行列演算",
     "hardware accelerator,TPU,GPU,ASIC,FPGA,matrix computation",
     "active","primary",88,7,
     "https://arxiv.org/abs/1704.04760","グローバル",0.9,
     "$$\\text{Roofline: } \\text{Perf} = \\min(\\text{Peak FLOPS}, \\text{Mem BW} \\times I) \\text{ where } I = \\text{arithmetic intensity}$$",
     "url_present"),

    ("cs_b2_028","暗号プロトコル","Cryptographic Protocol","Cryptographic Protocol",
     "安全な通信を実現するための暗号技術の組み合わせ・手順・プロトコルの設計。TLS 1.3・Signal Protocol・Noise Frameworkが現代標準。",
     "インターネット通信の秘密性・完全性・認証性の保証の基盤となり、eコマース・金融・医療情報システムを支える。",
     "情報工学・計算機科学","暗号工学",1975,None,"設計原則","セキュリティ工学",
     "通信の秘密性・完全性が必要","安全な認証・鍵共有・機密通信",
     "前方秘匿性は必要か？量子耐性は考慮するか？","独自暗号実装",
     "暗号プロトコル,TLS,鍵交換,Diffie-Hellman,Signal Protocol",
     "cryptographic protocol,TLS,key exchange,Diffie-Hellman,Signal Protocol",
     "active","primary",92,9,
     "https://datatracker.ietf.org/doc/html/rfc8446","グローバル",0.9,
     "$$\\text{ECDH: } \\text{shared\_secret} = a \\cdot B = b \\cdot A = ab \\cdot G \\text{ on elliptic curve}$$",
     "url_present"),

    ("cs_b2_029","ソフトウェアアーキテクチャパターン","Software Architecture Patterns","Software Architecture Patterns",
     "再現可能なソフトウェア設計上の問題を解決する構造的パターン。レイヤードアーキテクチャ・ヘキサゴナル・CQRS・Sagaパターンが代表的。",
     "Martin Fowler・Eric Evansらが体系化したDDD・EAAなどのパターン言語が、大規模システム設計の共通言語となっている。",
     "情報工学・計算機科学","ソフトウェアアーキテクチャ",1994,None,"設計原則","ソフトウェア工学",
     "中規模以上のソフトウェアシステム","変更容易性・テスタビリティ・スケーラビリティの確保",
     "ドメインの複雑さは？変更が頻繁な境界はどこか？","アドホック設計",
     "ソフトウェアアーキテクチャ,DDD,ヘキサゴナル,CQRS,イベント駆動",
     "software architecture,DDD,hexagonal,CQRS,event-driven",
     "active","secondary",88,9,
     "https://www.martinfowler.com/architecture/","欧米",0.9,
     "$$\\text{Complexity: } C(S) = \\sum_{m} cc(m) \\text{ where } cc = \\text{cyclomatic complexity (McCabe)}$$",
     "url_present"),

    ("cs_b2_030","量子誤り訂正符号","Quantum Error Correction","Quantum Error Correction",
     "量子ビットのデコヒーレンスと操作誤りを訂正する符号理論。Shor符号・Steane符号・表面符号（Surface Code）が主要実装。",
     "実用的な量子コンピュータ実現の最大の技術的課題であり、フォールトトレラント量子計算の基盤理論を形成する。",
     "情報工学・計算機科学","量子情報理論",1995,None,"理論・アルゴリズム","量子コンピューティング",
     "量子ハードウェア・ノイズのある量子回路","フォールトトレラント量子計算",
     "物理量子ビット対論理量子ビットのオーバーヘッドは？閾値定理は満たされるか？","古典誤り訂正",
     "量子誤り訂正,表面符号,スタビライザー符号,Shor符号,閾値定理",
     "quantum error correction,surface code,stabilizer code,Shor code,threshold theorem",
     "active","primary",88,3,
     "https://arxiv.org/abs/quant-ph/9705052","欧米",0.9,
     "$$\\text{Threshold: } p_{phys} < p_{th} \\approx 1\\% \\Rightarrow \\text{arbitrarily low logical error rate}$$",
     "url_present"),

    ("cs_b2_031","中国AIチップ設計","Chinese AI Chip Design","Chinese AI Chip Design",
     "中国における国産AIアクセラレータの設計・製造エコシステム。寒武紀（Cambricon）・華為HiSilicon・百度Kunlunが代表企業。",
     "米中技術競争下でNVIDIA規制を受け、国産GPUクラスタ・推論チップの独自開発が国家戦略として加速している。",
     "情報工学・計算機科学","東アジア工学・AIハードウェア",2016,None,"実装技法","AIハードウェア",
     "中国国内AIシステム・輸出規制対応","エッジAI推論・LLM学習クラスタ",
     "PetaFLOPSあたりのコストは？ソフトウェアエコシステムの成熟度は？","NVIDIAチップ使用",
     "中国AIチップ,Cambricon,HiSilicon,国産半導体,AI加速器",
     "Chinese AI chip,Cambricon,HiSilicon,domestic semiconductor,AI accelerator",
     "active","secondary",80,5,
     "https://www.cambricon.com/","東アジア",0.9,
     "$$\\text{Compute density gap}: \\frac{\\text{FLOPS}_{domestic}}{\\text{FLOPS}_{H100}} \\approx 0.3\\text{-}0.6 \\text{ (2024 estimate)}$$",
     "url_present"),

    ("cs_b2_032","日本計算機科学教育","Japanese CS Education","Japanese CS Education",
     "日本における計算機科学・情報工学の教育体系。高校情報科の必修化（2022年）・大学入学共通テストへの情報科目追加が近年の変化点。",
     "デジタル人材育成の国家課題として、情報教育カリキュラムの大幅改訂とプログラミング教育の全校展開が進んでいる。",
     "情報工学・計算機科学","東アジア工学・教育政策",2022,None,"制度・政策","教育システム",
     "日本の学校教育・DX人材育成","日本のICT人材育成・情報リテラシー向上",
     "アルゴリズム教育とデータサイエンス教育のバランスは？","欧米型STEM教育",
     "情報教育,プログラミング教育,日本,高校情報,デジタル人材",
     "CS education,programming education,Japan,high school informatics,digital talent",
     "active","secondary",80,8,
     "https://www.mext.go.jp/a_menu/shotou/zyouhou/detail/mext_00742.html","東アジア",0.9,
     "$$\\text{情報科履修率: } \\frac{\\text{高校情報科履修者数}}{\\text{高校生総数}} \\rightarrow 100\\% \\text{ (2025目標)}$$",
     "url_present"),

    ("cs_b2_033","韓国ソフトウェア産業","Korean Software Industry","Korean Software Industry",
     "韓国における情報技術産業の構造・育成政策。カカオ・ネイバー・Samsung SDS・LG CNSなどが主要企業。",
     "モバイルゲーム・フィンテック・O2Oサービスなどで世界市場に進出し、独自のIT生態系を形成している。",
     "情報工学・計算機科学","東アジア工学・産業構造",2000,None,"産業・政策","ITサービス産業",
     "韓国のデジタル経済・IT人材市場","韓国市場参入・韓国IT企業との連携",
     "財閥系SIと独立系SWの競争構造は？モバイルファーストの程度は？","日本型SIer産業",
     "韓国IT,カカオ,ネイバー,K-ソフトウェア,フィンテック",
     "Korean IT,Kakao,Naver,K-software,fintech",
     "active","secondary",78,8,
     "https://www.nipa.kr/","東アジア",0.85,
     "$$\\text{Korea SW export: } \\$8.7B \\text{ (2022)}, \\text{CAGR} \\approx 12\\% \\text{ (2018-2022)}$$",
     "url_present"),

    ("cs_b2_034","台湾半導体エコシステム","Taiwan Semiconductor Ecosystem","Taiwan Semiconductor Ecosystem",
     "TSMC・UMC・ASMedia・Mediatek・ASUS等を中心とした台湾の半導体・ICT産業クラスター。新竹サイエンスパークが核心拠点。",
     "世界の先端ロジック半導体の約60%を製造するTSMCが中心となり、AI/HPC向け先端パッケージング（CoWoS）でも主導的地位を持つ。",
     "情報工学・計算機科学","東アジア工学・半導体産業",1987,None,"産業・エコシステム","半導体製造",
     "先端半導体調達・AIインフラ構築","AI加速器向けチップ調達・先端パッケージング",
     "地政学リスク（台湾海峡）をどう評価するか？代替ファウンドリは？","米欧半導体エコシステム",
     "台湾半導体,TSMC,CoWoS,先端パッケージング,ファウンドリ",
     "Taiwan semiconductor,TSMC,CoWoS,advanced packaging,foundry",
     "active","secondary",88,9,
     "https://www.tsmc.com/","東アジア",0.92,
     "$$\\text{TSMC market share (foundry): } \\approx 58\\% \\text{ (2024), N3/N2 node leadership}$$",
     "url_present"),

    ("cs_b2_035","データエンジニアリング","Data Engineering","Data Engineering",
     "大規模データを収集・変換・保存・提供するパイプラインを設計・実装する工学分野。ETL・ELT・データレイクハウスが主要概念。",
     "MLOpsとデータサイエンスの基盤として、Airflow・dbt・Delta Lakeなどのツールが標準スタックを形成している。",
     "情報工学・計算機科学","データ工学",2015,None,"実装技法","データ基盤",
     "大量データの定期的処理・変換","データウェアハウス構築・ML特徴量基盤",
     "バッチかストリームか？データ品質保証はどうするか？","アドホックSQL",
     "データエンジニアリング,ETL,dbt,データレイクハウス,Airflow",
     "data engineering,ETL,dbt,data lakehouse,Airflow",
     "active","secondary",85,9,
     "https://www.databricks.com/glossary/data-lakehouse","グローバル",0.9,
     "$$\\text{Data freshness SLA: } T_{available} - T_{produced} \\leq \\Delta t_{SLA}$$",
     "url_present"),

    ("cs_b2_036","大規模言語モデル推論最適化","LLM Inference Optimization","LLM Inference Optimization",
     "大規模言語モデルのサービング効率を最大化する技術。量子化・バッチング・KVキャッシュ・スペキュレイティブデコードが主要手法。",
     "GPT-4・Claude・Geminiなどの商用LLMの低コスト大規模展開を実現し、AI民主化に貢献する重要エンジニアリング領域。",
     "情報工学・計算機科学","LLMシステム工学",2023,None,"実装技法","AI推論システム",
     "大規模言語モデルの本番デプロイ","レイテンシ・スループット・コストの最適化",
     "INT4/INT8量子化の精度低下は許容できるか？連続バッチングのスケジューリングは？","素朴なサービング",
     "LLM推論,量子化,KVキャッシュ,スペキュレイティブデコード,vLLM",
     "LLM inference,quantization,KV cache,speculative decoding,vLLM",
     "active","secondary",87,9,
     "https://arxiv.org/abs/2309.06180","グローバル",0.9,
     "$$\\text{Speculative decoding speedup: } \\approx \\frac{\\gamma}{1 - \\alpha(1 - \\beta)} \\text{ where } \\beta = \\text{acceptance rate}$$",
     "url_present"),

    ("cs_b2_037","ソフトウェアテスト設計","Software Test Design","Software Testing",
     "ソフトウェアの欠陥を効率的に発見するためのテスト戦略・技法の体系。境界値分析・等価分割・変異テスト・ファジングが代表的。",
     "テスト駆動開発（TDD）・ビヘイビア駆動開発（BDD）などの実践と組み合わさり、継続的品質保証の基盤となっている。",
     "情報工学・計算機科学","ソフトウェアテスト工学",1979,None,"検証技法","ソフトウェア品質",
     "あらゆるソフトウェア開発","機能品質・セキュリティ・パフォーマンスの検証",
     "テストカバレッジの目標は？自動化の範囲は？","コードレビューのみ",
     "ソフトウェアテスト,TDD,ファジング,変異テスト,カバレッジ",
     "software testing,TDD,fuzzing,mutation testing,coverage",
     "active","primary",90,9,
     "https://arxiv.org/abs/2212.09271","グローバル",0.9,
     "$$\\text{Mutation score} = \\frac{\\text{killed mutants}}{\\text{total mutants}} \\times 100\\%$$",
     "url_present"),

    ("cs_b2_038","リアクティブプログラミング","Reactive Programming","Reactive Programming",
     "データストリームと変化の伝播を中心に据えたプログラミングパラダイム。RxJava・RxJS・Akka Streamsが代表的実装。",
     "非同期イベント処理・UIインタラクション・マイクロサービス連携において、コールバック地獄の解決策として広く採用されている。",
     "情報工学・計算機科学","プログラミングパラダイム",2010,None,"実装技法","ソフトウェア設計",
     "非同期イベント・ストリーム処理","UIイベント処理・非同期API呼び出し・リアルタイムデータ",
     "バックプレッシャー戦略は？エラーハンドリングは？","コールバック・Promise",
     "リアクティブ,RxJava,Observable,バックプレッシャー,Reactive Streams",
     "reactive programming,RxJava,Observable,backpressure,Reactive Streams",
     "active","secondary",85,9,
     "https://www.reactive-streams.org/","グローバル",0.9,
     "$$\\text{Marble diagram: } A ---1---2---3---|\\! \\rightarrow \\text{map}(x \\mapsto x^2) \\rightarrow ---1---4---9---|\\!$$",
     "url_present"),

    ("cs_b2_039","継続的プロファイリング","Continuous Profiling","Continuous Profiling",
     "本番環境でアプリケーションのCPU・メモリ・レイテンシを継続的に測定・最適化する技法。pprof・async-profiler・Pyroscopeが代表的。",
     "シリコンバレーのパフォーマンス文化から生まれ、Googleが先駆的実装を開発。コスト効率と性能の同時最適化に有効。",
     "情報工学・計算機科学","パフォーマンスエンジニアリング",2010,None,"実装技法","サイト信頼性工学",
     "本番サービス・コスト最適化","CPU使用率削減・レイテンシ改善・コスト削減",
     "サンプリングオーバーヘッドは許容できるか？フレームグラフの解釈は？","定期的な負荷テストのみ",
     "継続的プロファイリング,pprof,フレームグラフ,パフォーマンス最適化",
     "continuous profiling,pprof,flame graph,performance optimization",
     "active","secondary",83,8,
     "https://pyroscope.io/","グローバル",0.9,
     "$$\\text{Profiling overhead} < 1\\% \\text{ CPU (sampling at } 100Hz) \\text{ for production use}$$",
     "url_present"),

    ("cs_b2_040","ゼロトラストネットワーク","Zero Trust Network","Zero Trust Architecture",
     "「信頼しない、常に検証する」原則に基づくセキュリティアーキテクチャ。境界型防御の限界を超え、アイデンティティ中心の制御を実現する。",
     "SolarWinds・Log4Shell等の大規模侵害を受け、NIST SP 800-207でゼロトラストが標準フレームワークとして確立された。",
     "情報工学・計算機科学","ネットワークセキュリティ",2010,None,"設計原則","セキュリティアーキテクチャ",
     "リモートワーク環境・クラウド移行後","従来のVPN+境界防御の置き換え",
     "マイクロセグメンテーションの粒度は？IDプロバイダは何を使うか？","境界型ファイアウォール",
     "ゼロトラスト,ZTNA,マイクロセグメンテーション,ID中心セキュリティ",
     "zero trust,ZTNA,microsegmentation,identity-centric security",
     "active","secondary",85,8,
     "https://csrc.nist.gov/publications/detail/sp/800-207/final","欧米",0.9,
     "$$\\text{ZT policy: } \\text{Access} = f(\\text{Identity}, \\text{Device}, \\text{Context}, \\text{Behavior})$$",
     "url_present"),

    ("cs_b2_041","APIゲートウェイ設計","API Gateway Design","API Gateway",
     "マイクロサービスへのリクエストを一元管理するエントリポイントの設計。認証・レート制限・ルーティング・変換を提供する。",
     "モバイルアプリとバックエンドの分離、マイクロサービス集約に不可欠で、Kong・AWS API Gateway・Nginxが代表的実装。",
     "情報工学・計算機科学","APIアーキテクチャ",2015,None,"アーキテクチャ","Webサービス",
     "マイクロサービスへの外部アクセス","API統合・セキュリティ・レート制限",
     "GraphQLかRESTかgRPCか？レート制限の戦略は？","各サービスへの直接アクセス",
     "APIゲートウェイ,Kong,GraphQL,レート制限,BFF",
     "API gateway,Kong,GraphQL,rate limiting,BFF",
     "active","secondary",85,9,
     "https://konghq.com/","グローバル",0.9,
     "$$\\text{Token bucket rate limiting: } \\text{tokens}(t) = \\min(C, \\text{tokens}(t-1) + r \\cdot \\Delta t)$$",
     "url_present"),

    ("cs_b2_042","説明可能人工知能","Explainable AI","XAI",
     "機械学習モデルの予測根拠を人間が理解できる形で提示する技術。SHAP・LIME・Grad-CAM・Integrated Gradientsが代表的手法。",
     "EUのAI法・金融規制・医療診断など高リスク領域でのAI説明責任要件に対応する必須技術として需要が急増している。",
     "情報工学・計算機科学","説明可能AI・AI倫理",2016,None,"理論・アルゴリズム","AI・機械学習",
     "高リスク意思決定・規制対応が必要なML","ローン審査・医療診断・刑事司法AI",
     "局所的説明か大域的説明か？特徴量重要度の一貫性は保証されるか？","ブラックボックスモデルのみ",
     "説明可能AI,XAI,SHAP,LIME,Grad-CAM,AI倫理",
     "explainable AI,XAI,SHAP,LIME,Grad-CAM,AI ethics",
     "active","primary",88,8,
     "https://arxiv.org/abs/1705.07874","グローバル",0.9,
     "$$\\phi_i = \\sum_{S \\subseteq F \\setminus \\{i\\}} \\frac{|S|!(|F|-|S|-1)!}{|F|!}[f(S\\cup\\{i\\})-f(S)] \\text{ (SHAP)}$$",
     "url_present"),

    ("cs_b2_043","インメモリデータグリッド","In-Memory Data Grid","IMDG",
     "データをメモリ上に分散配置し超高速アクセスを実現するミドルウェア。Redis・Apache Ignite・Hazelcastが代表的実装。",
     "株式取引・ゲームリーダーボード・セッション管理など超低レイテンシが要求される場面でRDBの補完的基盤として機能する。",
     "情報工学・計算機科学","インメモリ・キャッシュシステム",2005,None,"実装技法","高性能データシステム",
     "マイクロ秒レベルのデータアクセス・セッション管理","金融取引・ゲーミング・リアルタイム分析",
     "永続化の必要性は？分散一貫性モデルは？","ディスクベースDB",
     "インメモリDB,Redis,キャッシュ,分散ハッシュテーブル,高速データアクセス",
     "in-memory DB,Redis,cache,distributed hash table,low-latency data",
     "active","secondary",85,9,
     "https://redis.io/docs/","グローバル",0.9,
     "$$\\text{Cache hit ratio} = \\frac{N_{hit}}{N_{hit}+N_{miss}} \\rightarrow \\text{latency} = p \\cdot L_{cache} + (1-p) \\cdot L_{DB}$$",
     "url_present"),

    ("cs_b2_044","マルチモーダル学習","Multimodal Learning","Multimodal Learning",
     "テキスト・画像・音声・動画など複数のモダリティを統合して学習するDL手法。CLIP・GPT-4V・Gemini Ultraが代表的。",
     "画像理解・音声認識・動画キャプションなど単一モダリティの壁を超え、人間に近い多感覚統合知能を実現しつつある。",
     "情報工学・計算機科学","マルチモーダルAI",2021,None,"理論・アルゴリズム","人工知能",
     "複数データソース・クロスモーダル理解","Visual Question Answering・画像生成・音声テキスト変換",
     "モダリティ間のアライメントをどう学習するか？データ不均衡の扱いは？","単一モダリティモデル",
     "マルチモーダル,CLIP,GPT-4V,クロスモーダル,Vision-Language Model",
     "multimodal,CLIP,GPT-4V,cross-modal,vision-language model",
     "active","primary",88,9,
     "https://arxiv.org/abs/2103.00020","グローバル",0.9,
     "$$\\text{CLIP: } L = -\\frac{1}{N}\\sum_i \\log \\frac{\\exp(\\text{sim}(I_i, T_i)/\\tau)}{\\sum_j \\exp(\\text{sim}(I_i, T_j)/\\tau)}$$",
     "url_present"),

    ("cs_b2_045","ソフトウェアリファクタリング","Software Refactoring","Refactoring",
     "外部動作を変えずにコードの内部構造を改善する技術。Martin Fowler『リファクタリング』が体系化し、IDEサポートで実践が浸透した。",
     "技術的負債の解消・コードの可読性向上・将来の変更コスト削減に直結し、継続的なソフトウェア品質改善の中核実践となっている。",
     "情報工学・計算機科学","ソフトウェア品質工学",1999,None,"プロセス・方法論","ソフトウェア開発",
     "テストカバレッジが存在するコードベース","技術的負債解消・コード品質向上・新機能追加前準備",
     "リファクタリングと機能開発をどう並行させるか？自動テストで安全を担保できるか？","リライト",
     "リファクタリング,技術的負債,コードスメル,Extract Method,設計改善",
     "refactoring,technical debt,code smell,Extract Method,design improvement",
     "active","primary",90,9,
     "https://refactoring.com/","欧米",0.9,
     "$$\\text{Complexity reduction: } CC_{after} < CC_{before}, \\text{ s.t. } \\forall t \\in T: result(t)_{before} = result(t)_{after}$$",
     "url_present"),

    ("cs_b2_046","強化学習環境設計","RL Environment Design","RL Environment Design",
     "強化学習エージェントの訓練に用いる環境の設計原則。報酬関数設計・観測空間・行動空間・シミュレータが核心要素。",
     "OpenAI Gym・MuJoCo・Isaac Gymが標準化した環境設計により、ロボティクス・ゲームAI・資源最適化でのRL適用が進んだ。",
     "情報工学・計算機科学","強化学習・シミュレーション",2016,None,"設計・検証技法","ロボティクス・AI",
     "シミュレータが存在・報酬信号が設計可能","ロボット制御・ゲームAI・スケジューリング最適化",
     "報酬ハッキングが起きないか？sim-to-realギャップをどう埋めるか？","教師あり学習",
     "強化学習,RL環境,報酬設計,OpenAI Gym,sim-to-real",
     "reinforcement learning,RL environment,reward design,OpenAI Gym,sim-to-real",
     "active","primary",88,8,
     "https://gymnasium.farama.org/","グローバル",0.9,
     "$$R_t = \\sum_{k=0}^{\\infty} \\gamma^k r_{t+k+1}, \\text{ reward shaping: } R' = R + F(s,a,s')$$",
     "url_present"),

    ("cs_b2_047","データベースインデックス設計","Database Index Design","DB Index Design",
     "クエリパフォーマンスを最大化するためのデータベースインデックス選択・設計技法。B木・LSMツリー・ハッシュ・全文・ベクトルインデックスが代表的。",
     "適切なインデックス設計はN+1問題・フルテーブルスキャンを排除し、クエリ速度を数桁改善することがある。",
     "情報工学・計算機科学","データベースシステム",1970,None,"実装技法","データベース最適化",
     "クエリ頻度・書き込み比率・データ分布","検索性能とストレージのトレードオフが必要",
     "カーディナリティは高いか？インデックスの選択性は？","インデックスなし",
     "インデックス設計,B木,LSMツリー,クエリ最適化,部分インデックス",
     "index design,B-tree,LSM tree,query optimization,partial index",
     "active","primary",90,9,
     "https://use-the-index-luke.com/","グローバル",0.9,
     "$$\\text{B-tree height} = \\lceil \\log_d N \\rceil, \\text{ I/O} = O(\\log_d N) \\text{ per lookup}$$",
     "url_present"),

    ("cs_b2_048","プライバシーエンジニアリング","Privacy Engineering","Privacy Engineering",
     "プライバシー保護をシステム設計の早期段階から組み込む工学的アプローチ。Privacy by Design・GDPR適合・PETsが体系化している。",
     "GDPRのデータ最小化・目的制限・消去権などの要件をエンジニアリングで実装するための方法論として確立されている。",
     "情報工学・計算機科学","プライバシー工学",2018,None,"設計原則","規制・コンプライアンス",
     "個人データを扱うシステム全般","GDPR・CCPA・個人情報保護法への適合",
     "データ最小化の実装方法は？同意管理をどう設計するか？","後付けコンプライアンス",
     "プライバシーエンジニアリング,Privacy by Design,GDPR,データ最小化,同意管理",
     "privacy engineering,Privacy by Design,GDPR,data minimization,consent management",
     "active","secondary",85,8,
     "https://www.nist.gov/privacy-framework","欧米",0.9,
     "$$\\text{Privacy risk} = P(\\text{harm}) \\times \\text{impact}(\\text{harm}) \\text{ over data lifecycle}$$",
     "url_present"),

    ("cs_b2_049","コード生成・大規模言語モデル","Code Generation with LLMs","LLM Code Generation",
     "大規模言語モデルによるプログラムコードの自動生成技術。GitHub Copilot・CodeLlama・GPT-4oが代表的製品・モデル。",
     "開発生産性を20-50%向上させるとMicrosoftの研究で示され、ソフトウェアエンジニアリングの根本的変革をもたらしつつある。",
     "情報工学・計算機科学","AI支援開発",2021,None,"実装技法","ソフトウェア開発",
     "自然言語要件・コードコンテキストが存在","ボイラープレート生成・コード補完・テスト自動生成",
     "生成コードの検証はどうするか？著作権・ライセンスリスクは？","手動コーディングのみ",
     "コード生成,GitHub Copilot,CodeLlama,AI支援開発,プログラム合成",
     "code generation,GitHub Copilot,CodeLlama,AI-assisted development,program synthesis",
     "active","secondary",87,9,
     "https://arxiv.org/abs/2107.03374","グローバル",0.9,
     "$$\\text{pass@k} = 1 - \\frac{\\binom{n-c}{k}}{\\binom{n}{k}} \\text{ (HumanEval metric)}$$",
     "url_present"),

    ("cs_b2_050","ソフトウェアサプライチェーンセキュリティ","Software Supply Chain Security","SW Supply Chain Security",
     "オープンソース依存関係・ビルドパイプライン・配布チャネルを通じた攻撃を防ぐセキュリティ実践。SBOM・SLSA・Sigstoreが中心ツール。",
     "SolarWinds・log4shell・XZ Utils等の大規模サプライチェーン攻撃を受け、CISA・NIST・EUが対策フレームワークを策定した。",
     "情報工学・計算機科学","ソフトウェアセキュリティ",2020,None,"設計原則","セキュリティ工学",
     "OSS依存関係を使用する全てのソフトウェア","CI/CDパイプラインのセキュリティ強化",
     "SBOM（依存関係リスト）は管理されているか？ビルドの再現性は？","ネットワーク境界防御のみ",
     "サプライチェーンセキュリティ,SBOM,SLSA,Sigstore,依存関係スキャン",
     "supply chain security,SBOM,SLSA,Sigstore,dependency scanning",
     "active","secondary",85,8,
     "https://slsa.dev/","グローバル",0.9,
     "$$\\text{SLSA levels: } 1 \\rightarrow 2 \\rightarrow 3 \\rightarrow 4 \\text{ (increasing tamper resistance)}$$",
     "url_present"),
]

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

if __name__ == "__main__":
    ins, sk = insert_records(RECORDS)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Inserted: {ins}, Skipped: {sk}")
    print(f"Total: {total}")
