#!/usr/bin/env python3
"""電気電子工学 Batch 3: ee_b3_001–050"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
    ("ee_b3_001","Δ-Σ変調ADC","Delta-Sigma Analog-to-Digital Converter","ΔΣ ADC",
     "過サンプリングとノイズシェーピングを組み合わせて高分解能A/D変換を実現するアーキテクチャ。オーディオ・計測・センサIF回路に広用。",
     "オーディオDAC/ADCで24bit/192kHzの高品質変換を民生品レベルで実現。",
     "電気電子工学","アナログ・混合信号回路",1954,None,"手法","音声・計測・センサ回路",
     "高分解能・低帯域のA/D変換が必要な場合","オーディオ機器・計測器・センサモジュール",
     "OSR(過サンプリング比)と次数のトレードオフは？安定性条件は？",
     "逐次比較型ADC","ΔΣ変調,過サンプリング,ノイズシェーピング,ADC","delta-sigma,noise shaping,oversampling,ADC,SNR",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/1083519",
     "欧米","high",
     r"SQNR(1次ΔΣ): $SQNR \approx 6.02N + 1.76 + 20\log_{10}(OSR^{3/2}/\pi)$ dB. ノイズ出力(1次): $P_{n} = \frac{\Delta^2}{3}\frac{\pi^2}{3 OSR^3}$. 有効ビット数: $ENOB = (SNDR-1.76)/6.02$.",
     "url_present"),

    ("ee_b3_002","GaN高電子移動度トランジスタ","GaN High Electron Mobility Transistor","GaN HEMT",
     "GaN/AlGaN界面の二次元電子ガス(2DEG)を利用した高周波・高電力パワートランジスタ。Si MOSFETより高耐圧・高効率。",
     "5G基地局の電力増幅器でGaN HEMTが電力効率を2倍以上向上させ電力消費を半減。",
     "電気電子工学","化合物半導体デバイス",1993,None,"手法","電力変換・高周波",
     "高周波・高電力・高温動作が必要なパワーデバイス設計","5G基地局・レーダー・EV急速充電器",
     "GaNのhEMT動作閾値電圧の安定化は？p-GaNゲート構造のトレードオフは？",
     "Si MOSFET","GaN HEMT,化合物半導体,高電子移動度,パワーデバイス","GaN HEMT,compound semiconductor,2DEG,power device,5G",
     "active","primary",85,8,
     "https://ieeexplore.ieee.org/document/6578073",
     "東アジア","high",
     r"2DEG密度: $n_s = \frac{\varepsilon_{AlGaN}}{ed_{AlGaN}}(V_{PZ} - \phi_b + \frac{E_F}{e} - V_{gs})$. 移動度: $\mu_n \sim 2000$ cm$^2$/Vs(GaN). $g_m = \frac{\partial I_D}{\partial V_{gs}}|_{V_{DS}}$. $R_{on} = R_{ch} + R_{contact}$.",
     "url_present"),

    ("ee_b3_003","位相同期ループ","Phase-Locked Loop","PLL",
     "基準クロックに対して出力信号の位相・周波数を同期させるフィードバック制御回路。クロック生成・FM復調・周波数シンセサイザに使用。",
     "通信・コンピュータの全分野でクロック同期の標準技術となり半世紀以上使用継続。",
     "電気電子工学","アナログ・混合信号回路",1932,None,"手法","通信・クロック・計測",
     "クロック生成・周波数逓倍・FM復調が必要な場合","CPU,RF通信,SDR,計測器",
     "ロックインレンジとループ帯域のトレードオフは？位相ノイズの支配要因は？",
     "オープンループ発振器","PLL,位相同期,周波数シンセサイザ,位相ノイズ","PLL,phase-locked loop,frequency synthesizer,jitter,VCO",
     "active","primary",88,9,
     "https://ieeexplore.ieee.org/document/995479",
     "欧米","high",
     r"PLL線形モデル: $\frac{\theta_{out}(s)}{\theta_{ref}(s)} = \frac{K_{PD}K_{VCO}F(s)/s}{1+K_{PD}K_{VCO}F(s)/s}$. 位相ノイズ: $\mathcal{L}(\Delta f) = 10\log_{10}[S_\phi(\Delta f)/2]$. ロック時間: $t_{lock} \approx \frac{8\pi}{BW_n}$.",
     "url_present"),

    ("ee_b3_004","シリコンフォトニクス","Silicon Photonics","SiPh",
     "標準CMOSプロセスを用いて光導波路・変調器・光検出器・レーザー結合器を集積する光電子技術。データセンター光通信に適用。",
     "400Gbps/800Gbpsトランシーバ実現でデータセンターの消費電力を従来電気通信比で大幅削減。",
     "電気電子工学","フォトニクス・光通信",1985,None,"手法","光通信・データセンター",
     "チップ内・チップ間の超高速・低電力光通信が必要な場合","データセンター光インターコネクト・LiDAR・量子通信",
     "Si上でのレーザー光源課題(間接遷移バンドギャップ)をどう解決するか？",
     "電気配線通信","シリコンフォトニクス,光導波路,Mach-Zehnder変調器,光通信","silicon photonics,optical interconnect,Mach-Zehnder,photodetector",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/6714559",
     "欧米","high",
     r"Mach-Zehnder変調器位相シフト: $\Delta\phi = \frac{2\pi}{\lambda}\Delta n_{eff} L$. 光損失: $\alpha_{WG} \sim 1$-$3$ dB/cm(Si wire). Grating coupler効率: $\eta = |E_{out}|^2/|E_{in}|^2 \sim 50$-$90\%$.",
     "url_present"),

    ("ee_b3_005","ワイヤレス電力伝送","Wireless Power Transfer","WPT",
     "電磁誘導・磁界共鳴・電波放射(マイクロ波)を用いて非接触で電力を伝送する技術。EV充電・スマートデバイスに適用。",
     "Qiワイヤレス充電規格がスマートフォン・ウェアラブル充電を標準化し接続ポート需要を減少。",
     "電気電子工学","電力工学・RF工学",1891,None,"手法","電力伝送・消費者電子",
     "非接触・移動体・水中・医療インプラント等の有線接続が困難な電力供給","EV無線充電・医療植込み機器・工場AGV",
     "伝送効率と距離の関係は？電磁気安全基準(SAR)への適合は？",
     "有線電力供給","ワイヤレス給電,WPT,Qi,磁界共鳴,電磁誘導","WPT,wireless charging,resonant coupling,Qi,inductive power",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/5628312",
     "欧米","high",
     r"磁界共鳴効率: $\eta = \frac{k^2 Q_1 Q_2}{(1+\sqrt{1+k^2 Q_1 Q_2})^2}$. カップリング係数: $k = M/\sqrt{L_1 L_2}$. 誘導電力: $P = I^2 R_{eff} = \frac{(\omega M I_1)^2}{R_2+R_L}$.",
     "url_present"),

    ("ee_b3_006","電力グリッドインバータ制御","Grid-Connected Inverter Control","",
     "太陽光・風力発電システムをAC系統に連系するインバータの電流制御・同期・アイランディング検出を実装する制御技術。",
     "グリッドパリティ達成後の再生可能エネルギー大量導入でインバータ系統制御が電力品質の要となった。",
     "電気電子工学","パワーエレクトロニクス",2000,None,"手法","再生可能エネルギー・系統制御",
     "太陽光・風力等の分散電源の系統連系設計","太陽光パネルシステム・風力発電変換器",
     "系統電圧・周波数変動への対応は？アイランディング検出の感度と誤動作のトレードオフは？",
     "直結系統連系","系統連系インバータ,PLL,アイランディング検出,グリッド制御","grid-connected inverter,PLL,islanding detection,current control,LVRT",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/4118329",
     "欧米","high",
     r"dq変換電流制御: $V_d^* = V_d + L\omega i_q - k_i\int(i_d^*-i_d)dt - k_p(i_d^*-i_d)$. PLL: $\theta_{pll} = \int(\omega_0 + k_p e_q + k_i\int e_q dt)dt$. 系統安定条件: $|Z_{grid}(j\omega)| < |Z_{inv}(j\omega)|$.",
     "url_present"),

    ("ee_b3_007","ニューロモルフィックチップ","Neuromorphic Chip","",
     "脳の神経回路を模倣したスパイキングニューラルネットワーク(SNN)を超低電力で実装するAIプロセッサ。Intel Loihi・IBM TrueNorthが代表例。",
     "エッジデバイスでの常時センシング・オンデバイス学習をミリワット以下の電力で実現。",
     "電気電子工学","AI専用ハードウェア",2014,None,"手法","エッジAI・超低電力",
     "超低電力・リアルタイム・イベント駆動のAI推論が必要な場合","センシング・ウェアラブル・ロボットの低電力AI",
     "SNN学習アルゴリズムの精度はDNNに対して競争力があるか？プログラミングモデルは？",
     "GPUベースDNN","ニューロモルフィック,SNN,スパイキングニューラルネット,Loihi","neuromorphic,SNN,spiking neural network,Loihi,TrueNorth",
     "active","primary",82,6,
     "https://ieeexplore.ieee.org/document/7229264",
     "欧米","high",
     r"LIF(Leaky Integrate-and-Fire): $\tau_m \frac{dV}{dt} = -(V-V_{rest}) + R \cdot I(t)$. Fire条件: $V \geq V_{th}$, then $V \to V_{reset}$. STDP: $\Delta w = A_+ e^{-\Delta t/\tau_+}$ ($\Delta t>0$), $-A_- e^{\Delta t/\tau_-}$ ($\Delta t<0$).",
     "url_present"),

    ("ee_b3_008","超広帯域通信","Ultra-Wideband","UWB",
     "500MHz以上の広帯域で低電力パルスを用いて精密位置測定・短距離高速通信を実現するRF技術。IEEE 802.15.4aで標準化。",
     "Apple U1チップのAirDrop高精度方向検出・スマートキーの位置認証で一般普及が加速。",
     "電気電子工学","RF通信・測位",1990,None,"手法","精密測位・IoT通信",
     "10cm以下の精密測位・高時間分解能レンジングが必要な場合","スマートキー・工場AGV測位・医療アセット追跡",
     "マルチパス環境での測位精度はどう確保するか？FCC電力規制との整合は？",
     "WiFi測位・BLE Beacon","UWB,精密測位,ToF,Two-Way Ranging","UWB,ultra-wideband,TWR,precision positioning,impulse radio",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/4287097",
     "欧米","high",
     r"ToF距離: $d = c \cdot \frac{T_{round} - T_{reply}}{2}$. TWRレンジング精度: $\sigma_d = c \sigma_{clock}/f_{sampling}$. UWBパス損失: $PL(d) = PL(d_0) + 10n\log_{10}(d/d_0)$ ($n \approx 2$).",
     "url_present"),

    ("ee_b3_009","量子通信・量子鍵配送","Quantum Communication and QKD","QKD",
     "量子力学の盗聴検知性質を利用して情報理論的安全な秘密鍵を共有するBB84等のプロトコル。光ファイバー・衛星で実証。",
     "中国の墨子衛星が7,600kmの衛星QKDを実証し量子インターネットの実現可能性を示した。",
     "電気電子工学","量子情報・セキュリティ",1984,None,"手法","セキュリティ・量子通信",
     "情報理論的に安全な鍵配送が必要な高セキュリティ通信","政府・金融・軍事の機密通信インフラ",
     "現実の光子損失・エラー率を加味した安全鍵レートをどう計算するか？",
     "RSA公開鍵暗号","量子鍵配送,BB84,量子通信,盗聴検知","QKD,BB84,quantum key distribution,photon,entanglement",
     "active","primary",82,6,
     "https://ieeexplore.ieee.org/document/5695130",
     "東アジア","high",
     r"BB84安全鍵レート: $R_{key} = 1 - H(e_{bit}) - H(e_{ph})$ ($H$:バイナリエントロピー,$e$:エラー率). QBER: $QBER = n_{error}/n_{total}$. 安全条件: $QBER < 11\%$(ノイズチャネル). Decoy state: 3段強度で $h(e_{1,ph})$ 推定.",
     "url_present"),

    ("ee_b3_010","ワイドバンドギャップパワーデバイス","Wide Bandgap Power Devices","WBG",
     "SiC・GaNのバンドギャップが大きい半導体を用いた高耐圧・高周波・高温動作パワーデバイス。Si限界を超えた電力変換効率を実現。",
     "SiC MOSFETがEV牽引インバータで採用されシステム体積を50%削減し効率99%を達成。",
     "電気電子工学","パワー半導体",1993,None,"手法","電力変換・EV・再生可能エネルギー",
     "高電圧・高周波・高温動作が必要な電力変換設計","EV牽引インバータ・太陽光PCS・電鉄変換器",
     "SiCゲート酸化膜信頼性とSi比高コストの課題解決は？GaNとの用途住み分けは？",
     "Si IGBT","SiC,GaN,ワイドバンドギャップ,パワーデバイス,電力変換","SiC,GaN,wide bandgap,power device,switching loss",
     "active","primary",85,8,
     "https://ieeexplore.ieee.org/document/8533595",
     "東アジア","high",
     r"スイッチング損失: $E_{sw} = \frac{1}{2}V_{DC}I_D(t_{rise}+t_{fall})$. 導通損失: $P_{cond} = I_D^2 R_{on}$. 比抵抗限界: $R_{on,sp} = 4V_{BR}^2/(\varepsilon_s \mu E_c^3)$. SiC $E_c = 2.5$ MV/cm (Si比10倍).",
     "url_present"),

    ("ee_b3_011","ディープラーニング推論最適化","Deep Learning Inference Optimization","",
     "量子化・プルーニング・知識蒸留・NAS(ニューラルアーキテクチャ探索)を組み合わせてDNNモデルを組み込みデバイスに実装する技術。",
     "GPT-4クラスのLLMをスマートフォン上でリアルタイム動作させるエッジ推論技術が急速進歩。",
     "電気電子工学","AI専用ハードウェア",2017,None,"手法","エッジAI・モデル圧縮",
     "計算・メモリリソース制約下でのDNN高速推論が必要な場合","スマートフォン・IoTエッジデバイス・車載AI",
     "精度とスループット/電力のトレードオフを定量評価する指標は？",
     "クラウド推論","量子化,プルーニング,知識蒸留,NAS,エッジAI","quantization,pruning,knowledge distillation,NAS,model compression",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/8114708",
     "欧米","high",
     r"INT8量子化: $w_q = \text{round}(w/\Delta)\cdot\Delta$ ($\Delta = (w_{max}-w_{min})/255$). 知識蒸留損失: $L_{KD} = \alpha L_{CE}(y, y_{hard}) + (1-\alpha)T^2 L_{KL}(p_{soft}/T, q_{soft}/T)$. TOPS/W指標.",
     "url_present"),

    ("ee_b3_012","アクティブノイズコントロール","Active Noise Control","ANC",
     "音響センサとスピーカーを用いてノイズの逆位相信号をリアルタイム生成し騒音を打ち消す電子的消音技術。",
     "ノイズキャンセリングヘッドフォンで航空機ノイズを30dB以上低減し長時間飛行の快適性を革新。",
     "電気電子工学","信号処理・音響",1936,None,"手法","音響・NVH・IoT",
     "電子的手段でノイズを低減するシステム設計","ヘッドフォン・自動車キャビン・産業空調ダクト",
     "適応フィルタ(LMSアルゴリズム)の収束安定性条件は？フィードバック経路補正は？",
     "受動防音","アクティブノイズコントロール,LMSアルゴリズム,適応フィルタ,消音","ANC,active noise cancellation,LMS,adaptive filter,feedforward",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/476380",
     "欧米","high",
     r"LMSアルゴリズム: $w(n+1) = w(n) + 2\mu e(n)x(n)$. 収束条件: $0 < \mu < 1/(\lambda_{max})$. Filtered-X LMS: $w(n+1) = w(n) + 2\mu e(n) x'(n)$ ($x'$:二次経路フィルタ後). 消音量: $\Delta L = 20\log_{10}(1-\cos\Delta\phi)$.",
     "url_present"),

    ("ee_b3_013","パワーマネジメント集積回路","Power Management Integrated Circuit","PMIC",
     "バッテリーチャージャー・DC-DCコンバータ・LDO・電源監視回路を1チップに集積したシステム電源管理IC。スマートフォン・IoTに不可欠。",
     "最先端PMICが14以上の電源レールを1チップで管理しスマートフォンの電池寿命を最大化。",
     "電気電子工学","アナログ・混合信号回路",1990,None,"手法","電源設計・IoT",
     "バッテリー駆動・多電源システムの電源管理IC設計","スマートフォン・ウェアラブル・IoTノード",
     "待機時リーク電流の最小化は？過電流・過熱保護回路設計は？",
     "ディスクリート電源回路","PMIC,DC-DCコンバータ,バッテリーチャージ,LDO","PMIC,DC-DC converter,battery charger,LDO,power management",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5638468",
     "東アジア","high",
     r"Buck変換器効率: $\eta = \frac{P_{out}}{P_{out}+P_{sw}+P_{cond}} = \frac{V_{out}I_{out}}{V_{out}I_{out}+\frac{1}{2}C_pV_{in}^2 f+I_{out}^2 R_{on}D}$. LDO最小ドロップ: $V_{DO} = I_{out}(R_{DS,on}+R_{ESR})$. バッテリー充電: $SoC(t) = SoC_0 + \int_0^t I_{chg}/C_{bat} dt$.",
     "url_present"),

    ("ee_b3_014","レーダー信号処理","Radar Signal Processing","",
     "パルス圧縮・CFAR・MUSIC・MIMO処理等のアルゴリズムでレーダー受信信号から目標の距離・速度・角度を抽出する技術体系。",
     "FMCW自動車レーダーが歩行者検出・ACCを実現しADAS安全性を革命的に向上。",
     "電気電子工学","レーダー・センサ工学",1940,None,"手法","センシング・自動運転・防衛",
     "目標の精密検出・追跡・クラッタ除去が必要なレーダーシステム設計","自動車ADAS・航空管制・防衛・気象レーダー",
     "低RCS目標の検出閾値をどう設定するか？多重反射クラッタ除去は？",
     "光学センサ","CFAR,FMCW,パルス圧縮,MIMO,MUSIC","radar,CFAR,FMCW,pulse compression,MIMO radar",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/1631983",
     "欧米","high",
     r"FMCW周波数差: $\Delta f = \frac{2R}{c}B/T_{chirp}$ ($R$:距離,$B$:帯域). ドップラー速度: $v = \frac{\lambda \Delta f_d}{2}$. レーダー方程式: $P_r = \frac{P_t G^2 \lambda^2 \sigma}{(4\pi)^3 R^4}$. 角度分解能: $\theta_{3dB} = \lambda/D_{array}$.",
     "url_present"),

    ("ee_b3_015","フレキシブルエレクトロニクス","Flexible Electronics","",
     "ポリイミドフィルム・ストレッチャブル基板上に有機半導体・金属ナノワイヤ・グラフェンを成膜した柔軟電子デバイス。",
     "電子皮膚センサが生体に密着して心拍・血糖・体温を連続測定し医療モニタリングを変革。",
     "電気電子工学","フレキシブルデバイス",2000,None,"手法","ウェアラブル・医療電子",
     "曲げ・伸縮・生体適合が必要なデバイス設計","皮膚貼付センサ・ロールアップディスプレイ・生体埋込電子",
     "繰返し変形による電気特性劣化をどう抑制するか？薄膜封止の信頼性は？",
     "剛性基板上の従来電子","フレキシブルエレクトロニクス,有機半導体,ウェアラブル,OLED","flexible electronics,organic semiconductor,stretchable,wearable,e-skin",
     "active","primary",82,6,
     "https://ieeexplore.ieee.org/document/8253482",
     "東アジア","high",
     r"薄膜トランジスタ移動度: $\mu_{FET} = g_m L/(C_{ox}WV_{DS})$. 変形ゲージファクター: $GF = (\Delta R/R)/\varepsilon$. 曲げ半径: $R_{min} = t_{film}/2\varepsilon_{max}$. 伸縮率: $s = (L-L_0)/L_0$.",
     "url_present"),

    ("ee_b3_016","高精度GPSと測位補強","High-Precision GNSS and Augmentation","",
     "RTK・PPP・SBAS等の差分補正・測位補強技術でGNSS測位精度をcm〜mm級に向上させる技術体系。",
     "農業自動化でRTK-GPS誘導トラクターが2cmの作業列精度を実現し農薬・肥料散布を最適化。",
     "電気電子工学","測位・衛星工学",1985,None,"手法","測位・自動運転・インフラ",
     "cm精度の衛星測位が必要な応用","精密農業・建設重機自動化・自動運転車",
     "RTKの初期化(整数バイアス決定)時間とその信頼性は？マルチパスの影響は？",
     "単独GPS測位","RTK,PPP,GNSS補強,整数バイアス,精密測位","RTK,PPP,GNSS augmentation,integer ambiguity,precise positioning",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5062929",
     "欧米","high",
     r"RTK観測方程式: $\phi = \rho/\lambda + N + \delta_{iono}/\lambda + \delta_{trop}/\lambda + \varepsilon$. 二重差分: $\nabla\Delta\phi = \nabla\Delta\rho/\lambda + \nabla\Delta N$. LAMBDA法整数解精度: $P(|\hat{N}-N|=0) > 99.9\%$.",
     "url_present"),

    ("ee_b3_017","エネルギーハーベスティング","Energy Harvesting","",
     "環境中の振動・熱・光・RF電磁波等の微小エネルギーを回収して電力に変換しバッテリレスIoTセンサを実現する技術。",
     "圧電体を用いた振動エネルギー回収で工場センサのバッテリー交換コストをゼロ化。",
     "電気電子工学","エネルギー変換・IoT",2000,None,"手法","IoT・ウェアラブル・センサ",
     "バッテリー交換困難な場所でのセンサ自立電源が必要な場合","構造健全性モニタリング・医療植込デバイス・スマートビルIoT",
     "回収電力と消費電力のエネルギーバランスをどう設計するか？間歇動作制御は？",
     "バッテリー電源","エネルギーハーベスト,圧電,熱電,振動発電","energy harvesting,piezoelectric,thermoelectric,ambient RF,vibration",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/6178528",
     "欧米","high",
     r"圧電ハーベスト最大電力: $P_{max} = \frac{k^2 Q_m \omega_n^3 m^2 A^2}{16\pi^2}$ ($k^2$:電気機械結合係数). 熱電効率: $\eta_{TE} = \sqrt{1+ZT}-1)/(\sqrt{1+ZT}+T_c/T_h)$. 出力電力密度目標: $>100$ $\mu$W/cm$^2$.",
     "url_present"),

    ("ee_b3_018","マルウェア検出と逆コンパイル","Malware Detection and Reverse Engineering","",
     "動的解析・静的解析・機械学習ベースの検出手法でEmbeddedシステム・PC・モバイルのマルウェアを識別・解析する技術。",
     "Android端末のAI駆動マルウェア検出でゼロデイ攻撃の検出率を従来シグネチャ比90%向上。",
     "電気電子工学","サイバーセキュリティ",1987,None,"手法","セキュリティ・組み込み",
     "悪意あるコード・通信パターンの検出・解析が必要な場合","スマートフォン・IoT機器・産業制御システムのセキュリティ",
     "難読化・回避技術に対してどう検出性能を維持するか？誤検知率管理は？",
     "シグネチャベース検出","マルウェア検出,逆コンパイル,動的解析,機械学習セキュリティ","malware detection,reverse engineering,dynamic analysis,ML security",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/7535503",
     "欧米","high",
     r"検出F1スコア: $F1 = 2PR/(P+R)$ ($P$:精度,$R$:再現率). ROC AUC目標: $>0.99$. Kullback-Leibler divergence(API callパターン): $D_{KL}(P||Q) = \sum_x P(x)\log(P(x)/Q(x))$. ゼロデイ検出精度: $\geq 90\%$.",
     "url_present"),

    ("ee_b3_019","電磁両立性設計","Electromagnetic Compatibility Design","EMC",
     "IEC/CISPR・FCC規格に準拠した放射・伝導エミッションの抑制と外部ノイズへの耐性(イミュニティ)設計を体系化した技術。",
     "自動車ECUの国際EMC規制(UNECE R10)対応でグローバル市場参入を可能にする重要設計工程。",
     "電気電子工学","電磁両立性工学",1970,None,"枠組","機器設計・規格適合",
     "電子機器の放射ノイズ規制適合・外部ノイズ耐性が必要な設計","自動車ECU・産業用インバータ・医療機器",
     "放射エミッションの主要ノイズ源をどう特定するか？フィルタ設計の最適化は？",
     "事後対策型ノイズ対処","EMC,放射エミッション,イミュニティ,フェライトコア,シールド","EMC,EMI,radiated emission,immunity,shielding,ferrite",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5165594",
     "欧米","high",
     r"放射界強度: $E = \frac{I \cdot l \cdot \omega}{4\pi \varepsilon_0 c^2 r}\sin\theta$ (電気双極子). シールド効果: $SE = 20\log_{10}(E_0/E_s)$ dB. コモンモードフィルタ: $Z_{CM} = j\omega L_{CM}$,$f_{res} = 1/(2\pi\sqrt{LC})$.",
     "url_present"),

    ("ee_b3_020","テラヘルツ波工学","Terahertz Engineering","THz",
     "0.1-10THzの電磁波を用いた非破壊検査・医療イメージング・6G通信・セキュリティスクリーニングの技術体系。",
     "THzイメージングで爆発物・薬物の非接触・非侵襲スクリーニングを空港セキュリティに実用化。",
     "電気電子工学","テラヘルツ・6G通信",2000,None,"手法","通信・非破壊検査・医療",
     "非破壊内部イメージング・超高速無線通信・分子分光が必要な場合","空港セキュリティ・製薬検査・6G無線通信",
     "大気減衰の大きいTHz帯をどう実用化するか？THz発生器・検出器のコスト低減は？",
     "X線・マイクロ波","テラヘルツ波,非破壊検査,6G通信,時間領域分光","THz,terahertz,THz imaging,6G,molecular spectroscopy",
     "active","primary",80,5,
     "https://ieeexplore.ieee.org/document/8951132",
     "欧米","high",
     r"THz TDS: $E(t) = E_0 \exp(-t^2/2\tau_p^2)\cos(2\pi f_0 t)$. 透過率: $T(\omega) = E_{sample}(\omega)/E_{ref}(\omega)$. 大気減衰: $\alpha \sim 10$-$100$ dB/km (@60GHz/$H_2O$). 分解能: $\delta d = c/(2nB)$.",
     "url_present"),

    ("ee_b3_021","SoC設計方法論","System-on-Chip Design Methodology","SoC",
     "IP再利用・プラットフォーム設計・ハードウェア/ソフトウェア協調設計によって多機能を1チップに統合するVLSI設計手法。",
     "Apple M1/M2のSoC設計でCPU・GPU・NPU・メモリを統合しPC市場のアーキテクチャを刷新。",
     "電気電子工学","VLSI設計",1995,None,"枠組","半導体・組み込みシステム",
     "多機能・高性能・低消費電力の1チップ集積が必要な設計","スマートフォンSoC・AIアクセラレータ・車載SoC",
     "IP検証とシステムレベルシミュレーションを効率化するUVM方法論は？タイミングクロージャは？",
     "個別チップ設計","SoC,IP再利用,HW/SW協調設計,UVM,タイミングクロージャ","SoC,IP reuse,HW/SW co-design,UVM,timing closure",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/6213232",
     "東アジア","high",
     r"電力密度: $P_{dyn} = \alpha C V_{dd}^2 f$. タイミングスラック: $slack = T_{period} - (t_{setup} + t_{cq} + t_{logic})$. 面積: $A_{SoC} \propto N_{transistors} \cdot A_{cell,min}$.",
     "url_present"),

    ("ee_b3_022","光ファイバー通信伝送技術","Optical Fiber Transmission Technology","",
     "WDM・コヒーレント変調・DSP・EDFA・ラマン増幅を組み合わせて単一ファイバーの通信容量を最大化する伝送技術。",
     "400G-ZR コヒーレント光伝送でデータセンター間リンクのコスト/bpsを10年で100倍改善。",
     "電気電子工学","光通信工学",1970,None,"枠組","光通信・データセンター",
     "長距離・超大容量の光ファイバー通信システム設計","海底ケーブル・長距離基幹伝送・データセンター間接続",
     "非線形光学効果(FWM・XPM)と分散のトレードオフ管理は？SDNとの統合は？",
     "銅線通信","コヒーレント光通信,WDM,EDFA,DSP,DP-QPSK","coherent optical,WDM,EDFA,digital signal processing,dispersion",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/6739295",
     "欧米","high",
     r"Shannon容量: $C = B\log_2(1+SNR)$. 非線形雑音: $P_{NLI} = \frac{8}{27}\gamma^2(P_0 L_{eff})^2/B^2$. EDFA利得: $G = \exp(g_0 L - \alpha L)$. シンボルレート: $R_s = B/\log_2 M$.",
     "url_present"),

    ("ee_b3_023","インダクタンス型変位センサ","Inductive Displacement Sensor","LVDT",
     "LVDT・リゾルバ・誘導型近接センサ等の電磁誘導原理を用いた非接触位置・変位測定センサ技術。",
     "航空機フライトコントロールでLVDTが極寒・高温・高振動環境での精密位置フィードバックを実現。",
     "電気電子工学","センサ工学",1940,None,"手法","精密計測・制御",
     "過酷環境での高精度非接触変位計測が必要な場合","航空機アクチュエータ位置・工作機械フィードバック・医療",
     "温度ドリフト補償とオフセットキャリブレーションは？信号処理回路設計は？",
     "光学変位センサ","LVDT,誘導型変位センサ,非接触計測,電磁誘導","LVDT,inductive sensor,displacement measurement,resolver",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/4337847",
     "欧米","high",
     r"LVDT出力: $V_{out} = K(x) \cdot V_{exc} \cdot \sin(\omega t)$. 線形範囲内: $V_{out} = G \cdot x$ ($G$:ゲイン). 分解能: $\delta x = V_{noise}/(G \cdot V_{exc})$. 温度係数: $TK_G \approx -0.01\%/^\circ$C.",
     "url_present"),

    ("ee_b3_024","フォトボルタイック高効率化","Photovoltaic Efficiency Enhancement","",
     "タンデム型・ペロブスカイト・バックコンタクト・光閉じ込め構造等の技術でPV変換効率の理論限界Shockley-Queisser limit超えを目指す研究群。",
     "ペロブスカイト-Si タンデムセルで変換効率29%を突破しコストパリティを加速。",
     "電気電子工学","太陽電池工学",1954,None,"手法","再生可能エネルギー",
     "高変換効率・低コスト太陽電池セル・モジュール設計","住宅・産業・宇宙用太陽光発電",
     "ペロブスカイトの耐久性・安定性課題をどう解決するか？大面積均一成膜は？",
     "標準単接合Si太陽電池","ペロブスカイト太陽電池,タンデム型,変換効率,シリコン光閉じ込め","perovskite,tandem solar cell,efficiency,Shockley-Queisser",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/9076462",
     "欧米","high",
     r"Shockley-Queisser限界: $\eta_{max} \approx 33\%$ (1.1eV Si). タンデム効率: $\eta_{tandem} = 1-(1-\eta_1)(1-\eta_2)$. AM1.5G電流密度: $J_{sc} = q\int_0^\infty \Phi(\lambda)(1-R(\lambda))d\lambda$.",
     "url_present"),

    ("ee_b3_025","ロボットビジョン","Robot Vision","",
     "ステレオカメラ・深度センサ・LiDAR・CNNを統合してロボットが3D環境を認識し操作・ナビゲーションする技術体系。",
     "TeslaのFSD(完全自動運転)でカメラのみの3D環境認識で大型LiDARを不要とするアーキテクチャを実証。",
     "電気電子工学","コンピュータビジョン・ロボット",1980,None,"枠組","ロボット・自動運転",
     "ロボットの自律操作・ナビゲーション・対象物認識が必要な場合","産業ロボット・自律走行・服薬支援ロボット",
     "リアルタイム処理の計算量とロバスト性のトレードオフは？sim-to-real transferは？",
     "2D画像認識","ロボットビジョン,深度推定,点群処理,6DoF姿勢推定","robot vision,stereo,depth estimation,point cloud,6DoF pose",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/6909807",
     "欧米","high",
     r"ステレオ視差: $d = f \cdot B / Z$ ($f$:焦点距離,$B$:ベースライン,$Z$:深度). 再投影誤差: $\min \sum_i \|p_i - \pi(K[R|t]P_i)\|^2$. ICP収束: $\|T^* - T_{GT}\| < \epsilon$.",
     "url_present"),

    ("ee_b3_026","マグネティックセンシング","Magnetic Sensing","",
     "Hall効果センサ・AMR・GMR・TMR・フラックスゲートを用いた磁場・電流・角度・回転の精密測定技術。",
     "GMR磁気抵抗素子によるHDDの記録密度向上でAlbert FertとPeter GrünbergがNobel物理学賞受賞(2007)。",
     "電気電子工学","センサ工学",1879,None,"手法","精密計測・産業・医療",
     "磁場・電流・回転角の非接触精密測定が必要な場合","EV電流センサ・MEMS磁気センサ・MRI補助システム",
     "温度変化・外部磁場干渉への補償方法は？微小磁場検出感度の向上は？",
     "光学角度センサ","磁気センサ,GMR,TMR,Hall効果,磁気抵抗","magnetic sensor,GMR,TMR,Hall effect,fluxgate",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5680559",
     "欧米","high",
     r"Hall電圧: $V_H = \frac{IB}{nqt}$ ($n$:キャリア密度). GMR比: $GMR = \frac{R_{AP}-R_P}{R_P}\times 100\%$. TMR: $TMR = \frac{2P^2}{1-P^2}$ (Jullière式,$P$:スピン偏極率). 感度: $S = dV/dB$ [V/T].",
     "url_present"),

    ("ee_b3_027","電力系統安定化制御","Power System Stability Control","",
     "PSS(電力系統安定化装置)・AVR・FACTS・HVDC等の制御技術で電力系統の小信号安定性・過渡安定性を確保する技術。",
     "FACTS技術(SVC・STATCOM)が長距離送電線の電力潮流制御と電圧安定性を革新。",
     "電気電子工学","電力系統工学",1965,None,"枠組","電力工学・系統設計",
     "大規模電力系統の安定性解析・制御装置設計が必要な場合","基幹送電系統・再生可能エネルギー統合系統",
     "再エネ大量導入による慣性低下への対応策は？デジタルツイン系統解析は？",
     "受動的系統運用","PSS,STATCOM,SVC,HVDC,電力系統安定性","power system stability,PSS,FACTS,STATCOM,HVDC",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/5680037",
     "欧米","high",
     r"小信号安定方程式: $\dot{x} = Ax + Bu$,$A = \partial f/\partial x$. 固有値解析: $\lambda_i = \sigma_i \pm j\omega_i$ ($\sigma < 0$で安定). PSS伝達関数: $G_{PSS}(s) = K \frac{1+sT_1}{1+sT_2}\frac{sT_w}{1+sT_w}$.",
     "url_present"),

    ("ee_b3_028","半導体製造プロセス","Semiconductor Fabrication Process","",
     "フォトリソグラフィー・CVD・ALD・ドライエッチング・CMP等の単位プロセスを組み合わせて半導体デバイスを製造する技術体系。",
     "EUVリソグラフィーの実用化でIntel・TSMC・Samsungが3nm/2nmノードへの微細化を実現。",
     "電気電子工学","半導体製造",1960,None,"枠組","半導体・製造工学",
     "最先端VLSI・MEMSデバイスの製造プロセス設計","CPU・メモリ・MEMS・パワーデバイス製造",
     "ショートチャネル効果・EUV確率的課題(stochastic defect)の抑制策は？",
     "従来マクロ加工","フォトリソグラフィー,EUV,ALD,ドライエッチング,CMP","photolithography,EUV,ALD,dry etching,CMP,semiconductor process",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/9369830",
     "東アジア","high",
     r"Rayleigh分解能: $R = k_1 \lambda/NA$. DoF: $DoF = k_2 \lambda/NA^2$. ALD成長率: 1 原子層/$cycle$ ($\sim 0.1$ nm). EUVパターン確率欠陥: $P_{stochastic} \propto \exp(-N_{photons}/N_{threshold})$.",
     "url_present"),

    ("ee_b3_029","コグニティブラジオ","Cognitive Radio","CR",
     "スペクトルセンシングで空き周波数帯を動的に検出し未使用スペクトルを機会的に利用するインテリジェント無線技術。",
     "テレビホワイトスペースを活用したCRネットワークでIEEE 802.22を標準化しブロードバンドへの rural access を実現。",
     "電気電子工学","無線通信",1999,None,"手法","無線・スペクトル管理",
     "スペクトルの動的利用・干渉回避が必要な無線システム設計","テレビホワイトスペース・軍用周波数共用",
     "プライマリユーザーへの干渉をどう確実に回避するか？センシング検出確率の確保は？",
     "固定周波数割り当て","コグニティブラジオ,スペクトルセンシング,動的スペクトルアクセス","cognitive radio,spectrum sensing,dynamic spectrum access,white space",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/1580937",
     "欧米","high",
     r"Neyman-Pearson検出: $P_D = Q(\frac{\lambda - \mu_1}{\sigma_1})$,$P_F = Q(\frac{\lambda - \mu_0}{\sigma_0})$. エネルギー検出閾値: $\lambda_{th} = (\sigma_n^2/M)Q^{-1}(P_{FA}) + \sigma_n^2$. スペクトル効率: $C_{CR} = B_{TV}\log_2(1+SNR_{WS})$.",
     "url_present"),

    ("ee_b3_030","ディスプレイ駆動回路","Display Driver IC","DDI",
     "LCDバックライト制御・OLED電流駆動・TFT走査ドライバを集積してディスプレイパネルを高速高画質で駆動するIC技術。",
     "Samsung・LGのAMOLEDスマートフォンディスプレイ120Hz/HDR駆動でモバイルビジュアル体験を刷新。",
     "電気電子工学","ディスプレイ工学",1980,None,"手法","ディスプレイ・民生電子",
     "高解像度・高輝度・低消費電力のディスプレイ駆動IC設計","スマートフォン・タブレット・テレビのディスプレイ駆動",
     "OLED経年劣化補償(ELVSS調整)アルゴリズムは？HDR変換の処理遅延管理は？",
     "直接電圧駆動LCD","OLED,AMOLED,TFT,ゲートドライバ,ソースドライバ","OLED,AMOLED,TFT LCD,gate driver,source driver,display driver IC",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/7835209",
     "東アジア","high",
     r"OLED輝度: $L = f(I_{OLED})$($電流制御$). 経年補償: $V_{elvss} = V_{elvss,0} + \Delta V_{aging}(t)$. TFT駆動: $I_D = \frac{\mu_n C_{ox} W}{2L}(V_{GS}-V_{th})^2$(飽和域).",
     "url_present"),

    ("ee_b3_031","グリーン通信設計","Green Communications Design","",
     "通信ネットワークの電力消費を最小化するエネルギー効率指標(bits/J)に基づく基地局・プロトコル・ハードウェア設計手法。",
     "5G基地局のMassive MIMO+スリープモードで4G比エネルギー消費量を70%削減する目標が設定。",
     "電気電子工学","グリーンICT",2008,None,"枠組","通信・持続可能性",
     "通信システムの消費電力最小化とQoS両立が必要な場合","データセンター・モバイルネットワーク・IoTゲートウェイ",
     "エネルギー効率とスループットのトレードオフをどう最適化するか？",
     "最大スループット設計","グリーン通信,エネルギー効率,5G省電力,基地局スリープ","green communications,energy efficiency,EE,5G,base station sleep",
     "active","primary",80,7,
     "https://ieeexplore.ieee.org/document/5638368",
     "欧米","high",
     r"エネルギー効率: $EE = \frac{R_{sum}}{P_{total}}$ [bits/J]. $\max EE = \max_p \frac{B\log_2(1+p g/\sigma^2)}{p + P_{circuit}}$. 最適電力: $p^* = \frac{1}{g}(\frac{\sigma^2}{g}\cdot\frac{EE^* - \mu}{EE^* \cdot \ln 2})^{-1} - \frac{\sigma^2}{g}$.",
     "url_present"),

    ("ee_b3_032","ハードウェアトロイの検出","Hardware Trojan Detection","",
     "半導体製造プロセスやIPコア中に悪意あるハードウェア回路(トロイ)が混入していないかを検証するセキュリティ解析手法。",
     "サプライチェーン攻撃脅威の増大で国防・重要インフラの半導体のハードウェアセキュリティ検証が必須に。",
     "電気電子工学","ハードウェアセキュリティ",2007,None,"手法","セキュリティ・半導体",
     "外部ファウンドリで製造した半導体の安全性検証が必要な場合","軍用・航空宇宙・インフラ機器の半導体",
     "稀にしか活性化しないトロイをどう検出するか？サイドチャネル解析の適用は？",
     "ソフトウェアセキュリティ","ハードウェアトロイ,サイドチャネル解析,RTL検証,ICセキュリティ","hardware Trojan,side-channel,IC security,supply chain,RTL verification",
     "active","primary",80,5,
     "https://ieeexplore.ieee.org/document/4484490",
     "欧米","high",
     r"活性化確率: $P_{trigger} = P(condition_1 \cap \cdots \cap condition_n)$. 電力サイドチャネル: $P_{meas}(t) = P_{data}(t) + P_{Trojan}(t) + P_{noise}(t)$. 正規化相互情報量: $NMI = I(X;Y)/\max(H(X),H(Y))$.",
     "url_present"),

    ("ee_b3_033","MEMS共振器","MEMS Resonator","",
     "微細加工技術で製造した機械共振構造に電気的励振・検出を組み合わせた高Q値・高周波・低消費電力共振器。時計・フィルタに使用。",
     "MEMS振動子が水晶振動子代替として小型・集積化を実現しIoTデバイスの小型時刻基準に採用。",
     "電気電子工学","MEMS",1990,None,"手法","センサ・タイミングデバイス",
     "高Q値・低消費電力・小型の周波数基準・フィルタが必要な場合","IoT時刻基準・RF MEMSフィルタ・加速度センサ",
     "温度依存周波数ドリフトの温度補償は？真空パッケージングコストは？",
     "水晶発振器","MEMS共振器,高Q値,電磁機械結合,温度補償","MEMS resonator,high-Q,TCXO,RF MEMS,piezoelectric",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/7348607",
     "欧米","high",
     r"共振周波数: $f_0 = \frac{1}{2\pi}\sqrt{k_{eff}/m_{eff}}$. Q値: $Q = \omega_0/\Delta\omega = f_0/(f_2-f_1)$. 等価回路: $R_m = \sqrt{k m}/(Q \eta^2)$,$C_m = \eta^2/k$,$L_m = m/\eta^2$.",
     "url_present"),

    ("ee_b3_034","エッジAIと分散推論","Edge AI and Distributed Inference","",
     "クラウドに依存せずエッジデバイス(スマートフォン・カメラ・MCU)で低遅延・プライバシー保護のAI推論を実現する技術体系。",
     "スマートファクトリーでの外観検査AIがオンデバイス処理でリアルタイム不良検出を実現。",
     "電気電子工学","AI専用ハードウェア",2017,None,"枠組","エッジAI・製造・医療",
     "低遅延・オフライン動作・データプライバシーが要求されるAI応用","製造検査・スマートカメラ・ウェアラブルヘルス",
     "クラウドとエッジの分割点(split inference)をどう最適化するか？モデル更新はOTA？",
     "クラウドAI","エッジAI,TinyML,オンデバイス推論,スプリットコンピューティング","edge AI,TinyML,on-device inference,split computing,federated learning",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/9099828",
     "東アジア","high",
     r"エッジ分割点最適化: $\min_{k} T_{total} = t_{local}(k) + t_{comm}(k) + t_{server}(k)$. TinyML要件: $RAM < 256KB$,$Flash < 1MB$. スプリット推論通信量: $|a_k| = C_k \times H_k \times W_k$ (中間活性化サイズ).",
     "url_present"),

    ("ee_b3_035","パワーグリッドデジタルツイン","Power Grid Digital Twin","",
     "現実の電力系統のリアルタイムデータを取り込んで仮想系統モデルを同期稼働させ系統監視・運用最適化・訓練に利用する技術。",
     "欧州TSO(系統運用者)のデジタルツイン系統で再エネ変動への対応シミュレーションが常時実行可能に。",
     "電気電子工学","電力系統工学",2015,None,"手法","スマートグリッド・系統運用",
     "再エネ大量導入系統のリアルタイム監視・What-if解析が必要な場合","基幹送電系統・配電系統・マイクログリッド運用",
     "現実とデジタルツインの同期レイテンシをどう管理するか？サイバー攻撃への脆弱性は？",
     "静的系統解析","デジタルツイン,スマートグリッド,SCADA連携,系統シミュレーション","digital twin,smart grid,SCADA,power system simulation,PMU",
     "active","primary",78,5,
     "https://ieeexplore.ieee.org/document/9078820",
     "欧米","high",
     r"潮流方程式: $P_i = \sum_j V_i V_j (G_{ij}\cos\theta_{ij}+B_{ij}\sin\theta_{ij})$. PMUサンプリング: $f_{PMU} = 50$-$120$ Hz. デジタルツイン同期誤差: $\|\Delta x\| = \|x_{real} - x_{twin}\|$.",
     "url_present"),

    ("ee_b3_036","再構成可能インテリジェントサーフェス","Reconfigurable Intelligent Surface","RIS",
     "制御可能な反射位相を持つ多数のアンテナ素子配列で電波の伝搬経路を能動的に操作し通信容量・カバレッジを向上させる技術。6G候補技術。",
     "RISが室内の電波デッドゾーンを解消し建物内6G通信の可用性を向上させる実証が複数報告。",
     "電気電子工学","6G通信・スマートアンテナ",2019,None,"手法","無線通信・6G",
     "マルチパス環境の電波伝搬を能動的に制御したい通信システム設計","建物内・都市環境の6G電波環境制御",
     "位相制御の量子化誤差とビームフォーミング精度のトレードオフは？RIS-aided MIMOの設計は？",
     "中継器・リピーター","RIS,再構成可能知性サーフェス,スマートアンテナ,6G,位相シフト","RIS,reconfigurable intelligent surface,6G,passive beamforming,IRS",
     "active","primary",78,4,
     "https://ieeexplore.ieee.org/document/9140329",
     "欧米","high",
     r"RIS受信SNR: $SNR = P_t|(\sum_{m=1}^M \beta_m e^{j\phi_m} h_m g_m)|^2/\sigma^2$. 最適位相: $\phi_m^* = -\angle(h_m g_m)$. $SNR_{max} = P_t M^2 \beta^2/\sigma^2$ ($M$:素子数). アレイ利得: $10\log_{10}M^2$.",
     "url_present"),

    ("ee_b3_037","アナログ機械学習ハードウェア","Analog Machine Learning Hardware","",
     "重みを静電容量・電流源・メモリスタで実装しアナログ領域でMVM(行列-ベクトル積)を超低電力実行するニューラルネット推論チップ。",
     "Mythic・Syntiant等のアナログ計算AIチップが音声認識をμW級電力で実現し補聴器・IoTに適用。",
     "電気電子工学","AI専用ハードウェア",2017,None,"手法","超低電力AI・エッジ",
     "μW以下の超低電力AI推論が必要なエッジデバイス設計","補聴器・医療植込デバイス・農業IoTセンサ",
     "アナログ計算の精度(ENOB)をどう確保するか？温度変動・製造ばらつき補償は？",
     "デジタルDNN推論","アナログ計算,メモリスタ,MVM,超低電力AI","analog computing,memristor,MVM,in-memory computing,ultra-low power AI",
     "active","primary",78,4,
     "https://ieeexplore.ieee.org/document/8703164",
     "欧米","high",
     r"アナログMVM: $I_{out,j} = \sum_i G_{ij} V_{in,i}$ (Ohm則). ENOB劣化: $ENOB = (SINAD-1.76)/6.02$. 消費電力: $P_{MVM} = \sum_{ij} G_{ij} V_{in,i}^2$ vs デジタル $P_{dig} \propto N^2 f C V^2$.",
     "url_present"),

    ("ee_b3_038","MIMO-OFDMシステム","MIMO-OFDM System","",
     "複数アンテナ(MIMO)と多搬送波変調(OFDM)を組み合わせた広帯域・高効率無線伝送方式。4G LTE・5G NR・WiFi 6の中核技術。",
     "4G LTE以降の移動通信でMIMO-OFDMが標準化されスマートフォン広帯域通信を実現。",
     "電気電子工学","無線通信",2000,None,"手法","移動通信・WiFi",
     "高速・高信頼の広帯域無線通信システム設計","4G/5G基地局・WiFi AP・固定無線アクセス",
     "チャネル推定精度と移動体ドップラーへの対応は？ピーク対平均電力比(PAPR)低減は？",
     "単アンテナ単搬送波","MIMO,OFDM,空間多重,ビームフォーミング,5G NR","MIMO,OFDM,spatial multiplexing,beamforming,5G NR",
     "active","primary",88,9,
     "https://ieeexplore.ieee.org/document/4656786",
     "欧米","high",
     r"MIMO容量: $C = \log_2\det(I + \frac{\rho}{N_t}H H^\dagger)$ [bits/s/Hz]. OFDM: $s(t) = \sum_{k=0}^{N-1} X_k e^{j2\pi kt/T_s}$. PAPR: $PAPR = \max|s(t)|^2/E[|s(t)|^2]$. ZF検出: $\hat{x} = (H^\dagger H)^{-1}H^\dagger y$.",
     "url_present"),

    ("ee_b3_039","産業用イーサネット","Industrial Ethernet","",
     "TT-Ethernet・PROFINET・EtherCAT・TSN(時刻敏感ネットワーク)等のリアルタイム制御に対応した産業用有線ネットワーク技術。",
     "EtherCATが産業用ロボットの1μs同期制御を実現し多軸協調動作の精度を飛躍的向上。",
     "電気電子工学","産業ネットワーク",2000,None,"手法","工場自動化・制御",
     "μs〜ms精度のリアルタイム制御が必要な工場ネットワーク設計","産業ロボット・CNC工作機械・PLC制御システム",
     "TSNのスケジューリング設定と帯域保証の設計は？セキュリティ対策は？",
     "従来フィールドバス","産業用イーサネット,EtherCAT,PROFINET,TSN,リアルタイム制御","industrial Ethernet,EtherCAT,PROFINET,TSN,real-time control",
     "active","primary",82,9,
     "https://ieeexplore.ieee.org/document/8756028",
     "東アジア","high",
     r"EtherCAT周期: $T_{cycle} \leq 100\mu s$($125\mu s基準$). 同期精度: $\sigma_{sync} < 1\mu s$. TSN帯域保証: $B_{reserved} = \frac{T_{frame}}{T_{cycle}} \times B_{link}$. パケット遅延: $D = \frac{L_{frame}}{B_{link}} + \Delta_{switch}$.",
     "url_present"),

    ("ee_b3_040","電子線リソグラフィ","Electron Beam Lithography","EBL",
     "電子線で感光膜(レジスト)を直描してサブ10nmの超微細パターンを形成するリソグラフィー手法。マスク製造・研究用途。",
     "EBLが光リソグラフィーマスク製造の標準ツールとなり半導体の微細化ロードマップを支えた。",
     "電気電子工学","半導体製造",1965,None,"手法","ナノ加工・研究",
     "光リソグラフィー解像度限界以下の超微細パターン形成が必要な場合","フォトマスク製造・量子デバイス・ナノ光学",
     "電子線後方散乱(近接効果)補正アルゴリズムは？スループット改善法は？",
     "光リソグラフィー","EBL,電子線描画,近接効果補正,マスク製造","EBL,electron beam lithography,proximity effect,nanofabrication,resist",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/6507491",
     "欧米","high",
     r"解像度: $R_{EBL} \approx \sqrt{2 D_{backscatter} l_{range}}$ ($D$:拡散係数,$l$:レンジ). エネルギー付着: $f(r) = A_f e^{-r^2/\beta_f^2} + A_b e^{-r^2/\beta_b^2}$. 近接効果補正: $\text{ghost shot} = \eta \cdot E_{original}$.",
     "url_present"),

    ("ee_b3_041","有機エレクトロニクス","Organic Electronics","",
     "π共役有機半導体・ポリマーを用いたOLED・OPV・OTFT・センサの設計・製造技術。印刷プロセスと生体適合性が特徴。",
     "OLEDディスプレイが有機エレクトロニクスの最大市場となりスマートフォン・テレビ産業を革新。",
     "電気電子工学","有機半導体デバイス",1987,None,"枠組","ディスプレイ・IoT・再生エネ",
     "軽量・フレキシブル・大面積印刷可能な電子デバイス設計","OLED照明・有機太陽電池・電子タグ",
     "有機半導体の移動度向上と大気安定性の両立は？印刷プロセス精度は？",
     "無機半導体デバイス","有機半導体,OLED,有機薄膜トランジスタ,π共役","organic semiconductor,OLED,OTFT,OPV,pi-conjugated",
     "active","primary",82,8,
     "https://ieeexplore.ieee.org/document/7812513",
     "東アジア","high",
     r"有機TFT移動度: $\mu = \frac{L}{W C_{ox} V_{DS}}g_m$. OLED外部量子効率: $EQE = \eta_{out} \cdot \eta_{rad} \cdot \phi_{PL} \cdot \chi$ ($\chi$:スピン因子1/4(蛍光)または1(燐光)). $V_{bi} = \phi_{anode} - \phi_{cathode}$.",
     "url_present"),

    ("ee_b3_042","電気自動車充電インフラ","EV Charging Infrastructure","EVSE",
     "Level 2(AC)・DC急速充電・双方向V2G対応のEV充電スタンドの電力変換・プロトコル(OCPP・ISO 15118)・系統連系設計。",
     "CHAdeMO・CCS・MCS規格の競合から統一規格への移行がEVエコシステムの成長を左右する。",
     "電気電子工学","EV・充電インフラ",2010,None,"枠組","EV・再生可能エネルギー",
     "EV向け高速充電ステーションの電力設計・系統連系が必要な場合","高速道路SAのEV充電拠点・商業施設・マンション",
     "V2G双方向制御時の系統安定性への影響は？プロトコル標準化の遅延リスクは？",
     "ガソリンスタンド","EV充電,DC急速充電,V2G,OCPP,CHAdeMO","EVSE,DC fast charging,V2G,OCPP,ISO 15118,charging standard",
     "active","secondary",82,8,
     "https://ieeexplore.ieee.org/document/9078747",
     "東アジア","high",
     r"充電効率: $\eta_{charge} = E_{battery}/E_{grid}$. V2G電力: $P_{V2G} = I_{bat} \cdot V_{bat}$. 充電時間: $t_{charge} = C_{bat}(SoC_{target}-SoC_0)/I_{charge}$. DC/DCコンバータ効率: $\eta = P_{out}/P_{in} \geq 96\%$.",
     "url_present"),

    ("ee_b3_043","量子ドットデバイス","Quantum Dot Device","QD",
     "サイズ依存の量子閉じ込め効果により波長可変の発光・吸収特性を示す半導体ナノ粒子を用いたディスプレイ・太陽電池・量子通信デバイス。",
     "QLED(量子ドットディスプレイ)がLCDの色域を大幅拡張しプロフェッショナル映像市場を刷新。",
     "電気電子工学","ナノフォトニクス",1980,None,"手法","ディスプレイ・太陽電池・量子通信",
     "波長精密制御・高色純度・量子発光が必要なデバイス設計","QLED・量子通信光源・バイオイメージング",
     "Cd使用規制への対応(InP等代替材料)は？大面積均一成膜は？",
     "蛍光体LED","量子ドット,QLED,ナノ粒子,量子閉じ込め効果","quantum dot,QLED,nanocrystal,quantum confinement,InP",
     "active","primary",82,7,
     "https://ieeexplore.ieee.org/document/6220778",
     "欧米","high",
     r"量子閉じ込めエネルギー: $E_n = E_{bulk} + \frac{\hbar^2 \pi^2}{2 m^* R^2}n^2$ ($R$:粒子半径). 発光波長制御: $\lambda_{em} = hc/E_{gap}(R)$. PLQY: $\eta_{PL} = k_r/(k_r + k_{nr})$.",
     "url_present"),

    ("ee_b3_044","ニューラルインターフェース","Neural Interface","BCI",
     "電極・光学系・超音波等で神経活動を計測・刺激しコンピュータと脳の双方向インタフェースを実現する技術。EEG・ECoG・Utah Array等を含む。",
     "Neuralink・BrainGateが脊髄損傷者の念動操作を実証し完全麻痺患者のコミュニケーション回路を開いた。",
     "電気電子工学","ニューロエンジニアリング",1973,None,"枠組","医療・神経工学",
     "脳からの神経信号の記録・刺激で医療・HCI応用が必要な場合","麻痺患者支援・てんかん制御・神経義肢制御",
     "長期埋込電極の生体適合性とインピーダンス上昇をどう管理するか？スパイクソーティングは？",
     "EEG非侵襲型","BCI,脳コンピュータインターフェース,ニューラル記録,スパイクソーティング","BCI,neural interface,spike sorting,ECoG,neural recording",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/8423528",
     "欧米","high",
     r"スパイクSNR: $SNR = V_{spike}^2/(2\sigma_{noise}^2)$. LFP帯域: $1$-$300$ Hz,スパイク帯域: $300$-$6000$ Hz. Hodgkin-Huxley: $C_m\frac{dV}{dt} = -g_{Na}m^3h(V-E_{Na}) - g_K n^4(V-E_K) - g_L(V-E_L) + I$.",
     "url_present"),

    ("ee_b3_045","モータ駆動ドライブシステム","Motor Drive System","",
     "インバータ・センサ・制御器を一体化してACモータ(誘導・PM同期)を高効率・高精度に駆動するシステム技術。VVVFが代表。",
     "高効率インバータ+PMSMがEV・工作機械・エレベータの電力消費を30-50%削減。",
     "電気電子工学","パワーエレクトロニクス",1970,None,"枠組","EV・産業・HVAC",
     "AC電動機の可変速駆動・高精度トルク制御が必要なシステム設計","EV牽引システム・工作機械主軸・エアコンコンプレッサ",
     "弱め界磁制御での効率低下補償は？センサレス制御の低速安定性は？",
     "直入れ起動電動機","VVVF,インバータ,ベクトル制御,PMSモータ,センサレス","VVVF,inverter,vector control,PMSM,sensorless",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/7565569",
     "東アジア","high",
     r"FOC: $T_e = \frac{3}{2}p \psi_f i_q$ (PMSM). d軸電流制御: $V_d = R_s i_d + L_d \dot{i}_d - \omega_e L_q i_q$. 弱め界磁: $i_d = -\psi_f/L_d + \sqrt{(I_{max}^2 - i_q^2)}$. 効率: $\eta = T\omega/(T\omega + P_{loss})$.",
     "url_present"),

    ("ee_b3_046","光無線通信","Free-Space Optical Communication","FSO",
     "大気中を伝搬するレーザー光を用いた高速無線通信。高帯域・秘匿性・周波数規制なしが特徴。建物間・衛星間通信に使用。",
     "Meta(旧Facebook)のTerraGraphプロジェクトがFSOで建物間のラストワンマイル高速通信を実証。",
     "電気電子工学","光通信・無線",1960,None,"手法","バックホール通信・衛星通信",
     "大容量・非規制・高秘匿の無線通信リンクが必要な場合","建物間バックホール・LEO衛星間・航空機通信",
     "大気揺らぎ(シンチレーション)による受信レベル変動をどう補償するか？ポインティング制御は？",
     "RF無線・マイクロ波","FSO,自由空間光通信,シンチレーション,ポインティング,大気乱流","FSO,free-space optical,atmospheric turbulence,pointing acquisition,Li-Fi",
     "active","primary",80,6,
     "https://ieeexplore.ieee.org/document/7480405",
     "欧米","high",
     r"Beer-Lambert減衰: $P_r = P_t \eta_t \eta_r (\frac{D_r}{2\theta z})^2 e^{-\sigma z}$. 大気シンチレーション強度: $\sigma_R^2 = 1.23 C_n^2 k^{7/6} z^{11/6}$. 容量: $C = B\log_2(1+SNR_{FSO})$.",
     "url_present"),

    ("ee_b3_047","通信暗号化とPQC","Communication Encryption and Post-Quantum Cryptography","PQC",
     "量子コンピュータによる既存RSA・ECCの解読脅威に対応するLWE・格子暗号・コードベース暗号等の耐量子暗号アルゴリズム。NIST PQC標準化。",
     "NIST 2024のPQC標準(CRYSTALS-Kyber等)が通信プロトコルの将来セキュリティ基盤を確立。",
     "電気電子工学","暗号・セキュリティ",2015,None,"手法","セキュリティ・通信",
     "長期機密性が必要な通信システムの量子耐性暗号への移行設計","政府通信・金融インフラ・医療記録",
     "RSAからPQCへの移行期のハイブリッド実装は？PQC実装の計算コストは？",
     "RSA・ECC暗号","耐量子暗号,格子暗号,LWE,NIST PQC標準","PQC,post-quantum cryptography,lattice cryptography,NIST,CRYSTALS-Kyber",
     "active","primary",80,5,
     "https://ieeexplore.ieee.org/document/9882218",
     "欧米","high",
     r"LWE問題: $b = As + e \pmod{q}$ ($s$:秘密,$e$:小誤差). Kyber鍵長: $\lambda=128$ bit安全→公開鍵1088B/秘密鍵2400B/暗号文1088B. Groverアルゴリズム: $O(\sqrt{2^n})$でAES128は安全余裕なし→AES256推奨.",
     "url_present"),

    ("ee_b3_048","アンテナアレー・ビームフォーミング","Antenna Array and Beamforming","",
     "複数アンテナの励振位相・振幅を制御して所望方向に電波ビームを集中させるフェーズドアレー技術。5G・レーダー・衛星通信に適用。",
     "5G mmWave基地局のMassive MIMOフェーズドアレーで64/128アンテナ素子を統合し空間多重10倍。",
     "電気電子工学","アンテナ工学",1940,None,"手法","5G・レーダー・衛星",
     "指向性・追尾・空間多重のアンテナビーム制御が必要な場合","5G基地局・自動車レーダー・VSAT端末",
     "グレーティングローブを抑制するアレー設計は？ハイブリッドビームフォーミングの精度は？",
     "単一アンテナ指向性アンテナ","フェーズドアレー,ビームフォーミング,Massive MIMO,mmWave","phased array,beamforming,Massive MIMO,mmWave,spatial multiplexing",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/8356294",
     "東アジア","high",
     r"アレーファクタ: $AF(\theta) = \sum_{n=0}^{N-1} w_n e^{jn kd\sin\theta}$. 最適重み(MRC): $w = h^*/\|h\|$. 3dBビーム幅: $\theta_{3dB} \approx 0.886\lambda/(Nd)$ rad. グレーティングローブ条件: $d > \lambda/2$.",
     "url_present"),

    ("ee_b3_049","DRAM・NAND Flash設計","DRAM and NAND Flash Design","",
     "DRAMの1T1C構造・NANDフラッシュの浮遊ゲート/CTF構造・3D V-NAND積層設計によるメモリの高密度・高性能・低コスト化技術。",
     "Samsung・SK HynixのHBM(高帯域幅メモリ)とTSMCのCoWoS技術がAIアクセラレータの帯域幅を飛躍的向上。",
     "電気電子工学","半導体メモリ",1970,None,"枠組","半導体・AI",
     "高密度・高速・低電力メモリ設計が必要な場合","AI学習/推論メモリ・スマートフォン・SSD",
     "DRAMリフレッシュ消費電力とRow Hammerセキュリティ問題の対応は？3D V-NANDの層間リーク対策は？",
     "SRAM","DRAM,NAND Flash,HBM,V-NAND,メモリ設計","DRAM,NAND Flash,HBM,3D NAND,memory design",
     "active","primary",85,9,
     "https://ieeexplore.ieee.org/document/9912039",
     "東アジア","high",
     r"DRAMキャパシタ: $C_{cell} \geq 25$ fF(必要). リフレッシュ: $t_{RAS} + t_{RP} + t_{REF,cycle} = t_{REFW}/n_{rows}$. NANDプログラム: Fowler-Nordheim: $J = A E^2 \exp(-B/E)$. HBM帯域幅: $BW = 2 \times f_{IO} \times bus\_width$.",
     "url_present"),

    ("ee_b3_050","韓国半導体産業の技術開発戦略","South Korea Semiconductor Technology Strategy","",
     "Samsung・SK HynixによるDRAM・NAND Flashの技術リーダーシップと韓国政府の半導体産業育成政策の技術経営的考察。",
     "韓国の半導体輸出は2023年に国家輸出の18%を占め、一国の技術戦略が世界のメモリ市場を主導した事例。",
     "電気電子工学","半導体産業政策",1983,None,"枠組","半導体産業・技術政策",
     "東アジア半導体産業政策・技術キャッチアップ事例研究","DRAM・NAND Flash産業の国際競争力分析",
     "技術ライセンスから自社開発へのキャッチアップはどう実現したか？後発企業の市場参入戦略は？",
     "欧米主導型半導体産業","韓国半導体,Samsung,SK Hynix,技術キャッチアップ,産業政策","Korean semiconductor,Samsung,DRAM strategy,technology catch-up,industrial policy",
     "active","secondary",78,8,
     "https://www.korea.kr/news/policyNewsView.do?newsId=156479789",
     "東アジア","high",
     r"技術キャッチアップ速度: $\Delta TG = TG_{leader} - TG_{follower} = f(R\&D\_intensity, licensing, talent)$. 市場シェア: $MS_{Korea DRAM} > 70\%$ (2023). R\&D集約度: $R\&D/Revenue > 10\%$.",
     "url_present"),
]

if __name__ == "__main__":
    ins, sk = insert_records(records)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Inserted: {ins}, Skipped: {sk}")
    print(f"Total: {total}")
