import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
("mat_b3_001","マグネシウム合金軽量化設計","Magnesium Alloy Lightweight Design","Mg AZ31 AZ91 twin induced plasticity",
 "Mg-Al-Zn系合金の双晶誘起塑性(TWIP)・集合組織制御・表面処理による強度-延性-耐食性の同時最適化設計手法。",
 "自動車・航空機の軽量化(Alより35%軽量)に有望。耐食性向上でEV部品への適用が拡大中。",
 "材料工学・ナノテク","軽量合金工学",1990,None,"method","自動車・航空宇宙",
 "集合組織制御・表面処理・合金組成最適化","超軽量構造材料が必要な場合",
 "室温成形性向上は?耐食コーティング長期安定性は?","アルミ合金","マグネシウム合金,軽量化,双晶,耐食","Mg alloy,lightweight,TWIP,corrosion resistance",
 "active","primary",85,7,"https://doi.org/10.1016/j.actamat.2010.10.020","欧米",0.9,
 r"密度 $\rho_{Mg}=1.74$ g/cm³。CRSS双晶: $\tau_{CRSS} \approx 2-10$ MPa。Pilling-Bedworth比: $R_{PB}=V_{oxide}/V_{metal}=0.81$ (Mg)","url_present"),

("mat_b3_002","亜鉛めっき鋼板防食設計","Zinc Coated Steel Corrosion Protection Design","galvanized EG hot-dip Zn-Fe alloy",
 "電気亜鉛めっき(EG)・溶融亜鉛めっき(GI)・合金化溶融亜鉛めっき(GA)の膜厚・相構成・付着量を制御し犠牲防食・バリア機能を最適化する設計手法。",
 "自動車・建材・家電の防食鋼板として年間生産量6000万トン超。電着塗装との組合せで20年以上の耐食性を実現。",
 "材料工学・ナノテク","表面処理工学",1836,None,"method","自動車・建材",
 "めっき厚・合金化温度・化成処理設計","長期耐食性が必要な場合",
 "Mg含有高耐食ZnMg合金めっきは?電着塗装との整合は?","ステンレス鋼","亜鉛めっき,防食,犠牲防食,溶融亜鉛","galvanized steel,Zn coating,corrosion protection,sacrificial",
 "active","primary",88,9,"https://doi.org/10.1016/j.corsci.2019.108145","欧米",0.9,
 r"腐食電流: $i_{corr} = \frac{b_a \cdot b_c}{2.303(b_a+b_c) \cdot R_p}$。Zn消耗速度: $v = i_{corr} M_{Zn}/(n F \rho)$","url_present"),

("mat_b3_003","窒化物セラミックスSi3N4設計","Silicon Nitride Ceramic Design","Si3N4 sintering SRBSN GPS fracture toughness",
 "α→β相変態焼結と添加剤(Y2O3・Al2O3)による液相焼結でSi3N4の破壊靭性・高温強度・熱伝導を同時最適化する設計手法。",
 "エンジン部品・ベアリング・切削工具の高温耐摩耗材料として実用化。熱伝導率の高い基板材料としても注目。",
 "材料工学・ナノテク","セラミックス工学",1960,None,"method","機械・電子",
 "焼結助剤配合・相変態促進・粒界ガラス相制御","高温強度・高靭性が必要な場合",
 "熱伝導率向上と強度の両立は?","アルミナ","窒化ケイ素,Si3N4,セラミックス,高温強度","Si3N4,silicon nitride,ceramic,fracture toughness",
 "active","primary",87,8,"https://doi.org/10.1016/j.jeurceramsoc.2018.06.042","欧米",0.9,
 r"破壊靭性: $K_{IC} = Y\sigma\sqrt{\pi c}$。Griffith亀裂臨界応力: $\sigma_c = \sqrt{2E\gamma/(\pi c)}$。Si3N4目標: $K_{IC} > 8$ MPa·m⁰·⁵","url_present"),

("mat_b3_004","銅合金リードフレーム設計","Copper Alloy Lead Frame Design","Cu-Cr-Zr Cu-Fe-P electrical conductivity strength",
 "Cu-Cr-Zr・Cu-Fe-P系析出強化型銅合金の時効処理による高電気伝導率(>80% IACS)と高強度(>600MPa)の同時実現設計手法。",
 "半導体パッケージリードフレームの主要材料。高速信号・放熱・スタンピング加工性の全要件を満たす。",
 "材料工学・ナノテク","電子材料工学",1970,None,"method","電子部品",
 "析出温度・時間・変形量最適化","高伝導率・高強度が同時に必要な場合",
 "電気伝導率-強度のPareto最前線改善は?","42合金(Fe-Ni)","銅合金,リードフレーム,析出強化,電気伝導率","Cu alloy,lead frame,precipitation hardening,IACS",
 "active","primary",86,9,"https://doi.org/10.1007/s10853-019-04044-7","欧米",0.9,
 r"電気抵抗率: $\rho = \rho_0 + \alpha\Delta T + \rho_{disl} + \rho_{imp}$。Matthiessen則。時効硬化: $\Delta\sigma = M\cdot 0.4Gb\sqrt{N_v r_{ppt}}$","url_present"),

("mat_b3_005","エレクトロスピニングナノファイバー設計","Electrospinning Nanofiber Design","nanofiber polymer membrane filtration biomedical",
 "高電圧印加によるポリマー溶液の電気的延伸でナノ~マイクロ径繊維不織布を製造するエレクトロスピニングプロセスの設計手法。",
 "フィルター・組織工学足場・エネルギー貯蔵用セパレーターの高性能化に貢献。",
 "材料工学・ナノテク","高分子材料工学",2001,None,"method","フィルター・医療",
 "溶液粘度・電圧・流量・収集距離制御","超細径繊維の不織布が必要な場合",
 "繊維径均一化は?大量生産性向上は?","メルトブローン","エレクトロスピニング,ナノファイバー,不織布","electrospinning,nanofiber,nonwoven,filtration",
 "active","primary",85,7,"https://doi.org/10.1016/j.progpolymsci.2008.10.001","欧米",0.85,
 r"Rayleigh-Taylor不安定性起源。ジェット速度: $v = Q/(π r^2)$。Taylor cone開角: $\theta = 49.3°$。径推定: $d \propto (Q\rho)^{0.5}\gamma^{0.5}/(E^{0.5}\sigma^{0.5})$","url_present"),

("mat_b3_006","粉末冶金焼結設計","Powder Metallurgy Sintering Design","P/M sintering compaction density",
 "金属・合金粉末の粒度分布・成形圧力・焼結雰囲気・温度プロファイルを最適化し、ニアネットシェイプ複雑形状部品の高密度化と特性向上を達成する設計手法。",
 "歯車・軸受・フィルターなど機械部品の大量低コスト製造に確立済。",
 "材料工学・ナノテク","製造プロセス工学",1900,None,"method","機械部品",
 "粉末形状・粒度分布・成形圧力・焼結温度設計","複雑形状金属部品を低コスト量産する場合",
 "相対密度向上限界は?異種材料接合は?","切削加工","粉末冶金,焼結,P/M,ニアネットシェイプ","powder metallurgy,sintering,P/M,near net shape",
 "active","primary",87,9,"https://doi.org/10.1007/s11661-019-05490-z","欧米",0.85,
 r"Coble焼結: $\dot{\rho}/\rho \propto D_{gb}\delta\Omega/(k_BT G^4)$。緻密化方程式: $1-\rho = (1-\rho_0)\exp(-kt^n)$","url_present"),

("mat_b3_007","日本ファインセラミックス技術","Japan Fine Ceramics Technology","fine ceramics alumina zirconia Japan Kyocera NGK",
 "京セラ・NGK・村田製作所等が確立した超高純度アルミナ・ジルコニア・窒化アルミニウム焼結体の精密成形・焼結・加工技術。",
 "電子基板・人工関節・歯科材料・自動車センサーの世界市場をリード。日本のファインセラミックス輸出は年間数千億円規模。",
 "材料工学・ナノテク","セラミックス工学",1970,None,"method","電子・医療・自動車",
 "原料粉末純度・成形精度・焼結雰囲気制御","高信頼性電子部品・生体材料が必要な場合",
 "さらなる微細化・大型化は?コスト削減は?","ガラス・金属","ファインセラミックス,アルミナ,ジルコニア,日本","fine ceramics,alumina,zirconia,Japan,Kyocera",
 "active","primary",90,9,"https://doi.org/10.1111/jace.13748","東アジア",0.95,
 r"アルミナ曲げ強度: $\sigma_f > 400$ MPa。Y-TZP破壊靭性: $K_{IC} > 10$ MPa·m⁰·⁵。変態強化: $\Delta K_{IC} = 2E\Omega\Delta V_f/(1-\nu)$","url_present"),

("mat_b3_008","高分子ブレンド相溶化設計","Polymer Blend Compatibilization Design","reactive blending block copolymer compatibilizer",
 "非相溶ポリマーブレンドに反応性相溶化剤・ブロック共重合体を添加し、モルフォロジー制御・界面接着強化により機械特性を向上させる設計手法。",
 "廃プラスチックのリサイクルブレンドや高性能エンジニアリングプラスチック合金の基盤技術。",
 "材料工学・ナノテク","高分子材料工学",1975,None,"method","プラスチック・リサイクル",
 "相溶化剤濃度・分散相サイズ・界面張力評価","異種ポリマー混合で新特性が必要な場合",
 "リサイクル材への適用は?多成分系への拡張は?","単一ポリマー","ポリマーブレンド,相溶化,モルフォロジー","polymer blend,compatibilizer,morphology,reactive blending",
 "active","primary",84,8,"https://doi.org/10.1016/j.progpolymsci.2004.02.004","欧米",0.85,
 r"Flory-Huggins: $\Delta G_m = nRT(x_1\ln\phi_1 + x_2\ln\phi_2 + \chi\phi_1\phi_2)$。相分離条件: $\partial^2\Delta G_m/\partial\phi^2 < 0$","url_present"),

("mat_b3_009","化学気相蒸着ダイヤモンド成長","CVD Diamond Film Growth","HFCVD MPCVD diamond synthesis hard coating",
 "熱フィラメント(HFCVD)またはマイクロ波プラズマ(MPCVD)によるダイヤモンド薄膜の核生成・成長・ドーピング制御設計手法。",
 "硬度45GPaの最硬コーティングとして切削工具・電子放熱・量子センサーに実用化。",
 "材料工学・ナノテク","薄膜プロセス工学",1982,None,"method","工具・電子",
 "CH4/H2比・基板温度・水素ラジカル密度制御","超高硬度・高熱伝導コーティングが必要な場合",
 "大面積均一性は?グラファイト混入低減は?","TiN・TiAlNコーティング","CVDダイヤモンド,硬質コーティング,MPCVD","CVD diamond,hard coating,MPCVD,HFCVD",
 "active","primary",88,7,"https://doi.org/10.1016/j.diamond.2016.04.006","欧米",0.9,
 r"ダイヤモンド熱伝導率: $\kappa \approx 2200$ W/(m·K)。硬度: $H \approx 100$ GPa。成長速度: $r \propto [CH_3]\cdot\exp(-E_a/k_BT)$","url_present"),

("mat_b3_010","電着成形・電鋳設計","Electroforming Design","electrodeposition mold replication Ni Cu",
 "Ni・Cu・Au等の電気めっきによりマンドレル表面に金属を析出させ、剥離後に高精度形状部品を製造する電鋳プロセスの設計手法。",
 "DVDスタンパー・マイクロモールド・光学部品複製の基盤技術として確立。",
 "材料工学・ナノテク","表面処理工学",1838,None,"method","精密部品・光学",
 "電流密度・浴組成・pH・温度・撹拌条件制御","高精度形状転写部品が必要な場合",
 "析出応力による変形防止は?析出速度向上は?","切削加工","電鋳,電着成形,Ni電鋳,光学部品","electroforming,electrodeposition,Ni,optical component",
 "active","primary",84,8,"https://doi.org/10.1016/j.jmatprotec.2017.01.026","欧米",0.85,
 r"ファラデー則: $m = \frac{M I t}{n F}$。析出速度: $v = i M/(n F \rho)$。電流効率: $\eta_{CE} = m_{actual}/m_{theoretical}$","url_present"),

("mat_b3_011","中国太陽電池多結晶シリコン","China Polysilicon Solar Cell Manufacturing","multicrystalline Si PERC China LONGi Tongwei",
 "LONGi・Tongwei等中国企業が主導するモノPERC・TOPCon太陽電池の大面積単結晶シリコンウェハー引上げ・表面パッシベーション・金属化プロセス最適化技術。",
 "世界太陽電池生産の80%超を中国が担い、モジュールコストを2010年比1/10以下に低減した。",
 "材料工学・ナノテク","エネルギー材料工学",2005,None,"method","エネルギー変換",
 "CZ引上げ速度・PERC/TOPCon パッシベーション膜・金属化設計","大量低コスト高効率太陽電池製造が必要な場合",
 "TOPCon vs HJT vs IBC 最適選択は?銅配線は?","多結晶Si太陽電池","太陽電池,PERC,TOPCon,中国,LONGi","solar cell,PERC,TOPCon,China,LONGi,polysilicon",
 "active","primary",90,9,"https://doi.org/10.1016/j.solmat.2020.110741","東アジア",0.95,
 r"PERC効率: $\eta > 23\%$。$J_{sc}$ 改善: $\Delta J_{sc} = \int_{\lambda} S(\lambda)(1-R(\lambda))EQE(\lambda)d\lambda$。SRH再結合: $U = np/(n/S_{n0}+p/S_{p0}+n_i^2/(S_{n0}S_{p0}))^{0.5}$","url_present"),

("mat_b3_012","レアメタル代替材料設計","Rare Metal Substitution Material Design","earth-abundant catalyst W-free Co-free",
 "コバルト・タングステン・白金族元素を地球資源豊富な鉄・ニッケル・銅系材料で代替するための分子設計・ドーピング・欠陥エンジニアリング設計手法。",
 "EV電池・触媒・超硬工具のサプライチェーンリスク低減に向けた世界的研究課題。",
 "材料工学・ナノテク","機能性材料工学",2010,None,"method","エネルギー・触媒",
 "代替材料の性能ギャップ評価・DFT計算支援","希少金属依存度低減が必要な場合",
 "性能と希少性のトレードオフ評価は?","希少金属","レアメタル代替,Co-free,Pt代替,地球豊富元素","rare metal substitution,earth-abundant,Co-free,Pt-free",
 "active","primary",84,5,"https://doi.org/10.1038/s41578-020-00254-3","欧米",0.9,
 r"吸着エネルギー: $\Delta G_{ads} = \Delta H_{ads} - T\Delta S_{ads}$。Sabatier火山型: 最適$\Delta G_{H*} \approx 0$ eV for HER","url_present"),

("mat_b3_013","ガラス強化設計","Glass Strengthening Design","chemically tempered ion exchange gorilla glass",
 "イオン交換(KNO3溶融塩)による圧縮応力層形成でガラス破壊靭性・落下強度を向上させるケミカルテンパリング設計手法。",
 "スマートフォン・タブレットのGorilla Glass等に採用。2mm以下の薄板で高い衝撃耐性を実現。",
 "材料工学・ナノテク","ガラス工学",1962,None,"method","電子・建材",
 "イオン交換温度・時間・K+/Na+交換量・応力分布評価","薄板ガラスの高強度化が必要な場合",
 "残留応力層深さ向上は?高温強化との組合せは?","熱強化ガラス","ガラス強化,イオン交換,Gorilla Glass,ケミカルテンパリング","glass strengthening,ion exchange,Gorilla Glass,compressive stress",
 "active","primary",87,9,"https://doi.org/10.1111/jace.15537","欧米",0.9,
 r"圧縮応力: $\sigma_C = E\Delta\varepsilon/(1-\nu)$。イオン交換 $K^+ \leftrightarrow Na^+$: $\Delta V/V \approx 0.67\%$。Weibull破壊: $P_f = 1-\exp(-(σ/σ_0)^m)$","url_present"),

("mat_b3_014","核燃料被覆管材料設計","Nuclear Fuel Cladding Material Design","Zircaloy UO2 PWR BWR ATF",
 "ジルコニウム合金(Zircaloy-4・M5・ZIRLO)被覆管の耐水素吸収・ジルコニア酸化・クリープ・放射線照射脆化を設計・評価する手法。",
 "原子力発電の安全性と経済性の基盤。福島後の事故耐性燃料(ATF)開発でSiC・Cr被覆が注目。",
 "材料工学・ナノテク","核材料工学",1955,None,"method","原子力",
 "水素吸収率・酸化速度・照射後特性評価","軽水炉での燃料健全性確保が必要な場合",
 "事故耐性燃料ATFへの移行は?40年超運転への対応は?","ステンレス鋼","Zircaloy,核燃料被覆管,ATF,照射脆化","Zircaloy,cladding,ATF,nuclear fuel,radiation",
 "active","primary",85,9,"https://doi.org/10.1016/j.jnucmat.2013.08.020","欧米",0.9,
 r"酸化速度: $\Delta w = (A t)^{1/3}$ (三次則)。水素吸収率: $f_H = \Delta[H]/(\Delta[H]+\Delta[O]\cdot M_H/(2M_O))$","url_present"),

("mat_b3_015","ナノ複合めっき設計","Nanocomposite Electroplating Design","composite plating SiC Al2O3 PTFE Ni matrix",
 "Ni・Cu・Crめっきマトリクス中にSiC・Al2O3・PTFEナノ粒子を共析させ、硬度・耐摩耗性・摺動特性を向上させるナノ複合めっき設計手法。",
 "金型・精密機械部品の耐摩耗コーティングとして産業利用が広がっている。",
 "材料工学・ナノテク","表面処理工学",1970,None,"method","機械部品",
 "粒子ゼータ電位・浴中分散・電流密度制御","耐摩耗・低摩擦コーティングが必要な場合",
 "粒子偏析防止は?多成分混合系は?","硬質クロムめっき","ナノ複合めっき,SiC共析,耐摩耗,Ni-SiC","composite plating,SiC,PTFE,Ni matrix,wear resistance",
 "active","primary",83,7,"https://doi.org/10.1016/j.surfcoat.2019.02.041","欧米",0.85,
 r"共析率: $W_{part} = \frac{C_{bath}N_e}{1+C_{bath}N_e}$(Guglielmi模型)。硬度向上: $\Delta H \propto V_f^{0.5}$","url_present"),

("mat_b3_016","韓国半導体メモリ材料設計","Korea Semiconductor Memory Material Innovation","DRAM NAND flash V-NAND Samsung SK Hynix",
 "サムスン・SKハイニックスが主導するV-NAND(垂直積層)・DDR5 DRAMの容量セル絶縁膜・電荷トラップ層・ゲート絶縁膜の材料革新。",
 "スマートフォン・データセンター・AI学習のメモリ市場を韓国2社が世界支配。2020年代に200層以上V-NANDを実現。",
 "材料工学・ナノテク","半導体材料工学",1987,None,"method","半導体",
 "トンネル酸化膜品質・電荷トラップ量・消去効率設計","超高密度メモリが必要な場合",
 "スケーリング限界突破は?新セル構造は?","DRAM conventional","V-NAND,DRAM,フラッシュメモリ,韓国,半導体","V-NAND,DRAM,flash memory,Korea,Samsung,SK Hynix",
 "active","primary",90,9,"https://doi.org/10.1109/IEDM.2013.6724560","東アジア",0.95,
 r"フラッシュ記憶: Fowler-Nordheim tunneling $J_{FN} = A E^2\exp(-B/E)$。DRAM: $C_{cell} = \epsilon_0\epsilon_r A/d > 10$ fF","url_present"),

("mat_b3_017","二酸化炭素還元触媒設計","CO2 Reduction Catalyst Design","CO2RR electrochemical Cu Ag formate methanol",
 "Cu・Ag・Bi・Sn系電極触媒の結晶面・配位環境・欠陥・表面改質を精密制御し、CO2の電気化学的還元でCO・ギ酸・メタノール・エチレンを高選択的に生成する設計手法。",
 "再エネ由来電力でCO2をケミカル原料に変換するカーボンニュートラルの基幹技術として注目。",
 "材料工学・ナノテク","エネルギー材料工学",1985,None,"method","エネルギー変換・環境",
 "過電圧・ファラデー効率・生成物選択性評価","CO2を燃料・化学品に電気化学変換する場合",
 "電流密度向上は?長期安定性は?","熱化学変換","CO2還元,電気化学,Cu触媒,カーボンニュートラル","CO2RR,electrochemical reduction,Cu catalyst,carbon neutral",
 "active","primary",86,5,"https://doi.org/10.1038/s41929-018-0143-z","欧米",0.9,
 r"ファラデー効率: $FE = \frac{n_e F n_{product}}{Q_{total}} \times 100\%$。Sabatier原理: 最適 $\Delta G_{CO*} \approx 0$ eV","url_present"),

("mat_b3_018","チタン表面生体適合性設計","Titanium Surface Biocompatibility Design","TiO2 anodizing SLA RBM osseointegration",
 "陽極酸化・サンドブラスト・酸エッチング(SLA)・タンパク質コーティングによりTiインプラント表面の濡れ性・ナノ構造・生体分子吸着を最適化し骨統合を促進する設計手法。",
 "歯科インプラント・人工関節の骨統合促進で信頼性と長期予後を飛躍的に改善。",
 "材料工学・ナノテク","バイオ材料工学",1950,None,"method","医療インプラント",
 "ラフネス・濡れ性・タンパク吸着評価","骨との生物学的結合が必要な場合",
 "抗菌機能の同時付与は?SLActiveの超親水化効果は?","ポリマーインプラント","チタン,骨統合,生体適合,インプラント表面","Ti implant,osseointegration,SLA,biocompatibility",
 "active","primary",88,9,"https://doi.org/10.1016/j.actbio.2019.01.002","欧米",0.9,
 r"Wenzel則: $\cos\theta_W = r\cos\theta_Y$。Cassie-Baxter: $\cos\theta_{CB} = f_1\cos\theta_1 - f_2$。骨統合強度: $\tau_{shear} > 50$ MPa","url_present"),

("mat_b3_019","イオン交換膜設計","Ion Exchange Membrane Design","Nafion PEM SOFC alkaline AEM",
 "スルホン酸基・四級アンモニウム基の固定電荷と親水性チャンネルの制御によりプロトン・アニオン伝導と化学安定性を両立する燃料電池・電解槽用膜の設計手法。",
 "水素燃料電池自動車・グリーン水素電解槽の心臓部。Nafion117が標準として広く使用。",
 "材料工学・ナノテク","電気化学材料工学",1968,None,"method","エネルギー変換",
 "当量重量・固定荷電密度・スウェリング率・化学安定性評価","高プロトン伝導・耐久性膜が必要な場合",
 "非フッ素系代替は?AEM長期安定性は?","多孔性セパレーター","イオン交換膜,Nafion,燃料電池,水素","ion exchange membrane,Nafion,PEM,fuel cell,hydrogen",
 "active","primary",88,8,"https://doi.org/10.1039/C2EE23170A","欧米",0.9,
 r"プロトン伝導率: $\sigma = \sigma_0\exp(-E_a/RT)$。Nernst-Planck: $J_i = -D_i\nabla C_i - \frac{z_i F D_i}{RT}C_i\nabla\phi$","url_present"),

("mat_b3_020","磁気共鳴造影剤材料設計","MRI Contrast Agent Material Design","Gd chelate SPION T1 T2 relaxivity",
 "ガドリニウムキレート(T1造影剤)・酸化鉄ナノ粒子(T2造影剤)のリラクシビティ・生体毒性・クリアランスを最適化するMRI造影剤設計手法。",
 "がんの早期診断・手術ナビゲーション・脳神経疾患画像診断の精度向上に直結。",
 "材料工学・ナノテク","バイオナノ材料工学",1984,None,"method","医療診断",
 "r1/r2リラクシビティ・粒径・表面コーティング設計","MRIシグナル増強が必要な場合",
 "Gd腎毒性回避は?Gd-free代替は?","ヨウ素CT造影剤","MRI造影剤,ガドリニウム,酸化鉄ナノ粒子","MRI contrast agent,Gd,SPION,relaxivity",
 "active","primary",86,8,"https://doi.org/10.1021/acs.chemrev.8b00464","欧米",0.9,
 r"Solomon-Bloembergen-Morgan: $1/T_1 = r_1[CA]$。内圏機構: $1/T_1^{IS} = \frac{q/[H_2O]}{T_{1M}+\tau_M}$","url_present"),

("mat_b3_021","難燃高分子材料設計","Flame Retardant Polymer Design","halogen-free intumescent phosphorus nitrogen FR",
 "リン・窒素系膨張型難燃剤・金属水酸化物・ポリシロキサンによるハロゲンフリー難燃高分子の分解機構制御と残炭形成設計手法。",
 "電子機器・建材・航空機内装材のRoHS/EU規制対応で水酸化アルミニウム・リン系難燃剤が主流に。",
 "材料工学・ナノテク","高分子材料工学",1975,None,"method","電子・建材",
 "難燃等級UL94・限界酸素指数(LOI)・熱分解温度評価","ハロゲンフリー難燃化が必要な場合",
 "難燃性と機械特性の両立は?ナノフィラー相乗効果は?","ハロゲン系難燃剤","難燃,ハロゲンフリー,膨張型,リン系難燃剤","flame retardant,halogen-free,intumescent,phosphorus",
 "active","primary",85,8,"https://doi.org/10.1016/j.polymdegradstab.2017.12.004","欧米",0.85,
 r"LOI = (O2/(O2+N2)) × 100\%。目標LOI > 28\%。炭化速度: $\delta_{char}/\delta_t \propto \exp(-E_a^{char}/RT)$","url_present"),

("mat_b3_022","電子パッケージ熱伝導材料設計","Electronic Package Thermal Interface Material Design","TIM phase change metal graphite diamond",
 "シリコーングリース・相変化材料・金属インジウム・グラファイトシート・ダイヤモンドコンポジットのバルク熱抵抗と接触熱抵抗を同時低減するTIM設計手法。",
 "CPUダイとヒートスプレッダー間の熱管理の最重要部材。AIチップの消費電力急増で需要が爆発的に拡大。",
 "材料工学・ナノテク","電子材料工学",1990,None,"method","電子冷却",
 "接触抵抵抗・ポンプアウト耐性・長期信頼性評価","半導体デバイスの放熱が最重要な場合",
 "グラフェン複合TIMの実用化は?インジウム代替は?","シリコーングリース","TIM,熱伝導材料,放熱,CPUパッケージ","TIM,thermal interface material,heat dissipation,CPU",
 "active","primary",87,8,"https://doi.org/10.1007/s11664-015-3745-y","欧米",0.9,
 r"総熱抵抗: $R_{total} = R_{contact,1} + R_{bulk} + R_{contact,2} = 2r_c/k + t/k$。目標: $R_{total} < 0.1$ cm²·K/W","url_present"),

("mat_b3_023","日本超硬工具材料技術","Japan Cemented Carbide Tool Technology","WC-Co hardmetal cutting tool Japan Sumitomo Kyocera",
 "住友電工・京セラ・三菱マテリアルが確立したWC-Co超硬合金の硬度・靭性・コーティング(TiAlN・cvd-TiCN)最適化による高速切削工具設計技術。",
 "航空機・自動車のチタン・インコネル難削材高能率加工を実現。日本の切削工具世界シェアは約25%。",
 "材料工学・ナノテク","工具材料工学",1920,None,"method","製造・切削",
 "Co量・WC粒径・コーティング種・切削速度評価","高速切削・難削材加工が必要な場合",
 "CBN工具との競合は?Coフリー超硬開発は?","高速度鋼(HSS)","超硬合金,WC-Co,切削工具,コーティング,日本","WC-Co,cemented carbide,cutting tool,TiAlN,Japan",
 "active","primary",90,9,"https://doi.org/10.1016/j.ijmachtools.2012.03.004","東アジア",0.95,
 r"WC硬度: $H_v \approx 1500-2000$ kg/mm²。Taylor工具寿命: $VT^n = C$, $n \approx 0.2-0.4$(超硬)。摩耗: Archard式 $W = k F_n d/H$","url_present"),

("mat_b3_024","ポリイミド高耐熱フィルム設計","Polyimide High Heat Resistance Film Design","PI film imidization Kapton OLED substrate",
 "ジアミン・二無水物の選択とイミド化プロセスによるポリイミドフィルムのガラス転移温度(350°C超)・線膨張係数・誘電特性・透明性の最適化設計手法。",
 "フレキシブルOLED基板・宇宙用断熱膜・半導体プロセス用テープとして不可欠な高耐熱高分子材料。",
 "材料工学・ナノテク","高分子材料工学",1962,None,"method","電子・宇宙",
 "モノマー選択・イミド化温度・膜厚均一性制御","300°C超耐熱フレキシブル基板が必要な場合",
 "透明PI化は?低CTE化は?","PET","ポリイミド,高耐熱フィルム,Kapton,フレキシブル電子","polyimide,PI film,Kapton,flexible electronics,OLED",
 "active","primary",88,9,"https://doi.org/10.1016/j.progpolymsci.2012.09.003","欧米",0.9,
 r"$T_g > 350°C$。CTE $\approx 3-50$ ppm/K (設計で制御)。誘電率: $\epsilon_r \approx 3.0-3.5$。引張強度: $> 100$ MPa","url_present"),

("mat_b3_025","中国希土類永久磁石内製化","China Rare Earth Permanent Magnet Indigenization","NdFeB samarium cobalt SmCo China",
 "中国が確立したNdFeB・SmCo磁石の粉末製造・プレス配向・焼結・防錆コーティングの一貫生産技術と希土類資源の垂直統合戦略。",
 "世界の高性能永久磁石生産の90%超を中国が担い、EV・風力発電・ロボットサプライチェーンを制御。",
 "材料工学・ナノテク","磁性材料工学",1990,None,"method","電磁・エネルギー",
 "粉末粒径・磁場配向・焼結雰囲気・表面処理設計","高保磁力磁石の大量低コスト生産が必要な場合",
 "Dy削減技術は?SmCo vs NdFeB選択基準は?","フェライト","希土類磁石,NdFeB,SmCo,中国,EV","rare earth magnet,NdFeB,SmCo,China,EV",
 "active","primary",88,9,"https://doi.org/10.1016/j.jmmm.2020.167325","東アジア",0.95,
 r"(BH)_{max}: NdFeB $\approx 400$ kJ/m³, SmCo $\approx 240$ kJ/m³。磁化: $M_s = n\mu_B/V$。保磁力: $H_{cJ} > 1000$ kA/m","url_present"),

("mat_b3_026","繊維強化熱可塑性複合材料設計","Fiber Reinforced Thermoplastic Composite Design","FRTP PEEK PA6 CF LFT thermoplastic CFRTP",
 "炭素繊維・ガラス繊維強化PEEK・PA6・PPの繊維体積率・繊維長・界面接着と射出成形・プレス成形プロセスを設計し、短サイクル成形と高強度を両立する手法。",
 "EV・ドローン・スポーツ用品の軽量化と成形性向上。熱可塑性による成形サイクル短縮でCFRTP量産の扉を開いた。",
 "材料工学・ナノテク","複合材料工学",1985,None,"method","自動車・航空宇宙",
 "繊維長・体積率・界面接着・溶融粘度制御","短サイクル成形かつ高強度が必要な場合",
 "ウェルドライン強度確保は?リサイクル性は?","熱硬化性CFRP","CFRTP,熱可塑性複合材料,PEEK,短サイクル成形","CFRTP,FRTP,thermoplastic composite,PEEK,carbon fiber",
 "active","primary",86,7,"https://doi.org/10.1016/j.compositesa.2020.106098","欧米",0.9,
 r"混合則: $E_c = V_f E_f + (1-V_f)E_m$。Halpin-Tsai: $\eta = (E_f/E_m - 1)/(E_f/E_m + 2l/d)$","url_present"),

("mat_b3_027","ガス分離膜材料設計","Gas Separation Membrane Material Design","CO2/CH4 H2/N2 polymeric membrane mixed matrix",
 "ポリイミド・PIMs・混合マトリクス膜(MMM)のFFV(自由体積分率)・選択性・透過性・可塑化耐性を制御するガス分離膜設計手法。",
 "天然ガス精製・水素精製・CO2回収の低エネルギー分離プロセスとして膜技術が急速に成熟。",
 "材料工学・ナノテク","機能性材料工学",1980,None,"method","エネルギー・環境",
 "Robeson上限線超越・FFV最大化・ガラス転移温度設計","CO2/CH4・H2/N2選択的分離が必要な場合",
 "可塑化問題解決は?MMMのシーブ粒子分散は?","精留蒸留","ガス分離膜,CO2分離,H2精製,混合マトリクス","gas separation membrane,CO2 capture,H2 purification,mixed matrix",
 "active","primary",85,7,"https://doi.org/10.1126/science.1247462","欧米",0.9,
 r"溶解拡散モデル: $P = D \cdot S$。選択性: $\alpha_{A/B} = P_A/P_B = (D_A/D_B)(S_A/S_B)$。Robeson上限: $\ln\alpha = n\ln P_A + \beta$","url_present"),

("mat_b3_028","マルエージング鋼設計","Maraging Steel Design","18Ni maraging ultrahigh strength aerospace",
 "18%Ni系マルエージング鋼の時効処理によるNi3Mo・Ni3Ti金属間化合物析出強化と低炭素マルテンサイト基地で超高強度(~2000MPa)と靭性を両立する設計手法。",
 "航空機着陸装置・ロケットケース・金型の超高強度構造材料として不可欠。",
 "材料工学・ナノテク","金属材料工学",1960,None,"method","航空宇宙・金型",
 "時効温度・時間・析出物サイズ・逆変態量制御","超高強度(2000MPa超)と靭性が必要な場合",
 "Ti4+ 析出と炭化物の相互作用は?溶接性は?","高強度調質鋼","マルエージング鋼,超高強度,18Ni,航空宇宙","maraging steel,18Ni,ultrahigh strength,aerospace",
 "active","primary",85,8,"https://doi.org/10.1016/j.actamat.2014.01.049","欧米",0.9,
 r"強度予測: $\sigma_y = \sigma_{solid solution} + \Delta\sigma_{ppt}$。Orowan: $\Delta\sigma_{ppt} = 0.4M\mu b/(\pi\sqrt{1-\nu})\cdot\ln(2r/b)/\lambda$","url_present"),

("mat_b3_029","電磁波吸収材料設計","Electromagnetic Wave Absorber Design","radar absorber impedance matching ferrite composite",
 "フェライト・カーボン系複合材料の複素誘電率・複素透磁率の周波数依存特性を最適化し、インピーダンス整合条件で広帯域電磁波吸収を達成する設計手法。",
 "レーダーステルス・EMI対策・5G通信機器の電波吸収体として産業・防衛両用途で重要。",
 "材料工学・ナノテク","電磁材料工学",1940,None,"method","防衛・通信",
 "複素誘電率・透磁率・厚さ最適化","特定周波数帯の電磁波吸収が必要な場合",
 "広帯域化は?薄型化は?","金属シールド","電磁波吸収,フェライト,ステルス,EMI","EM absorber,ferrite,stealth,EMC,radar",
 "active","primary",84,8,"https://doi.org/10.1039/C6NR00728G","欧米",0.85,
 r"反射損失: $RL = 20\log|(\eta_{in}-1)/(\eta_{in}+1)|$ (dB)。インピーダンス: $\eta_{in} = \sqrt{\mu_r/\epsilon_r}\tanh(j2\pi f d\sqrt{\mu_r\epsilon_r}/c)$","url_present"),

("mat_b3_030","セルロースナノファイバー複合材料設計","Cellulose Nanofiber Composite Design","CNF CNC bacterial cellulose nanocrystal biopolymer",
 "TEMPO酸化・機械解繊・酸加水分解によりセルロースナノファイバー(CNF)・ナノクリスタル(CNC)を製造し、ポリマー複合材料・バリアフィルム・光学フィルムに応用する設計手法。",
 "植物由来の超軽量・高強度バイオベース材料として包装・電子・医療に応用。日本が世界トップの研究実績。",
 "材料工学・ナノテク","バイオ材料工学",2000,None,"method","包装・電子・医療",
 "解繊度・表面改質・分散条件・乾燥プロセス制御","バイオベース軽量高強度材料が必要な場合",
 "大量生産コスト削減は?疎水化による耐水性付与は?","ガラス繊維","セルロースナノファイバー,CNF,CNC,バイオ材料","cellulose nanofiber,CNF,CNC,biopolymer,nanocomposite",
 "active","primary",86,6,"https://doi.org/10.1021/acs.chemrev.8b00627","東アジア",0.85,
 r"弾性率: $E_{CNF} \approx 100-150$ GPa。引張強度: $\sigma > 2$ GPa。MFC懸濁粘度: $\eta \propto C^{1.5} d^{-4}$ (Doi-Edwards)","url_present"),

("mat_b3_031","アモルファス金属設計","Amorphous Metal Design","metallic glass BMG bulk amorphous Zr Cu Fe",
 "急冷凝固・スパッタリング・機械合金化によりZr・Cu・Fe・Al基バルクメタリックガラス(BMG)の臨界冷却速度・過冷却液体領域・強度・靭性を制御する設計手法。",
 "ゴルフヘッド・医療器具・電磁シールド材料として実用化。トポロジー制御で高靭性BMGが実現。",
 "材料工学・ナノテク","非晶質材料工学",1960,None,"method","精密部品・医療",
 "ガラス形成能・過冷却液体域ΔTx・粘性流動温度制御","超高強度非晶質金属が必要な場合",
 "スケールアップは?再現性確保は?","結晶合金","バルクメタリックガラス,BMG,アモルファス金属","BMG,metallic glass,amorphous,bulk",
 "active","primary",84,6,"https://doi.org/10.1126/science.267.5202.1476","欧米",0.9,
 r"Turnbull基準: $T_{rg} = T_g/T_l > 2/3$。粘度: $\eta = \eta_0\exp(D T_0/(T-T_0))$ (Vogel-Fulcher-Tammann)","url_present"),

("mat_b3_032","TiO2光触媒表面設計","TiO2 Photocatalyst Surface Design","anatase rutile heterojunction dye sensitization",
 "アナターゼ/ルチル混晶比・電子-正孔再結合抑制・貴金属助触媒・色素増感によりTiO2光触媒の可視光活性と量子効率を向上させる表面設計手法。",
 "防汚・抗菌・空気浄化タイルから水素生成まで幅広い応用。デグッサP25が標準参照光触媒として確立。",
 "材料工学・ナノテク","機能性材料工学",1972,None,"method","環境・エネルギー",
 "バンドギャップ・表面積・電子-正孔分離効率評価","可視光での有機物分解・H2生成が必要な場合",
 "可視光応答化の限界は?ドーピング安定性は?","活性炭吸着","TiO2,光触媒,アナターゼ,色素増感","TiO2,photocatalyst,anatase,dye sensitization",
 "active","primary",85,8,"https://doi.org/10.1021/cr00033a004","欧米",0.9,
 r"光触媒反応速度: $r = k\Phi I_0^{0.5}[reactant]^n$。価電子帯電位: $+2.9$ V vs NHE (anatase)。バンドギャップ: 3.0-3.2 eV","url_present"),

("mat_b3_033","ポリマー電解質燃料電池MEA設計","PEM Fuel Cell MEA Design","MEA catalyst layer GDL Nafion electrode",
 "白金触媒・カーボン担体・Nafionイオノマーの膜電極接合体(MEA)における触媒層多孔質構造・三相界面形成・水管理を最適化するPEMFC設計手法。",
 "水素自動車・定置型発電の心臓部。白金使用量低減(0.1g/kW以下)と耐久性向上が商業化の鍵。",
 "材料工学・ナノテク","電気化学材料工学",1960,None,"method","エネルギー変換",
 "ECA・ECSA・水管理・デグラデーション評価","水素燃料電池の高効率化が必要な場合",
 "白金代替触媒実用化は?耐久性80,000時間化は?","内燃機関","燃料電池,MEA,白金触媒,PEM,水素","PEMFC,MEA,platinum catalyst,hydrogen,fuel cell",
 "active","primary",88,8,"https://doi.org/10.1038/s41560-018-0221-x","欧米",0.9,
 r"Butler-Volmer ORR: $i = i_0\exp(-\alpha_c F\eta/RT)$。Tafel: $\eta = -b\log(i/i_0)$, $b = RT/(\alpha_c F) \approx 60-120$ mV/dec","url_present"),

("mat_b3_034","液晶ポリマー材料設計","Liquid Crystal Polymer Design","LCP TLCP self-reinforcing high-frequency PCB",
 "全芳香族ポリエステル液晶高分子の異方性・低誘電率(Dk<3)・低誘電正接(Df<0.002)・低吸水率を制御し、5G高周波PCB基板・ファインピッチコネクタに応用する設計手法。",
 "5G通信基地局・スマートフォンの高周波信号伝送基板として採用急拡大。日本・韓国・台湾が主要生産国。",
 "材料工学・ナノテク","高分子材料工学",1972,None,"method","通信・電子",
 "分子配向・誘電特性・低吸水率・加工温度設計","高周波低損失基板が必要な場合",
 "さらなる低誘電化は?PTFE・LCP選択基準は?","従来ガラスエポキシ(FR4)","液晶ポリマー,LCP,5G基板,低誘電","LCP,liquid crystal polymer,5G PCB,low dielectric",
 "active","primary",88,8,"https://doi.org/10.1016/j.polymer.2017.11.006","欧米",0.9,
 r"誘電率温度依存: $\epsilon_r(T) = \epsilon_r(T_0)(1 + \alpha_\epsilon(T-T_0))$。Dk $< 3.0$, Df $< 0.002$ at 10 GHz","url_present"),

("mat_b3_035","台湾フォトマスク材料設計","Taiwan Photomask Material Design","EUV mask blank TaN absorber HOYA Photronics Taiwan",
 "HOYA・台湾Photronics等が製造するEUV/ArF用フォトマスクブランクスのTaN吸収体・Ru保護膜・低熱膨張ガラス基板の欠陥・反射率・位相差を精密制御する技術。",
 "TSMC・Samsung等の最先端半導体製造には不可欠。EUVマスクブランクス市場は数社寡占。",
 "材料工学・ナノテク","半導体材料工学",1975,None,"method","半導体リソグラフィー",
 "欠陥密度<0.01/cm²・反射率均一性±0.5%・Rz≤0.15nm","EUV/ArFリソグラフィー露光が必要な場合",
 "EUV欠陥ゼロ達成は?次世代High-NA EUVは?","電子線マスク","フォトマスク,EUV,TaN,マスクブランクス,台湾","photomask,EUV mask,TaN absorber,HOYA,Taiwan",
 "active","primary",88,8,"https://doi.org/10.1117/12.2545690","東アジア",0.95,
 r"EUV反射率: $R = |r|^2 \approx 64-67\%$ (Mo/Si多層膜40周期)。位相差: $\Delta\phi = 4\pi n_{coat}d_{coat}/\lambda$","url_present"),

("mat_b3_036","ダイヤモンドライクカーボンDLC設計","Diamond-Like Carbon DLC Coating Design","ta-C a-C:H PVD PECVD hardness tribology",
 "スパッタリング・フィルタードアーク・ECRプラズマCVDによりsp3炭素比率・水素含量・内部応力を制御した超硬DLCコーティングを設計する手法。",
 "自動車エンジン摺動部品・金型・医療器具の耐摩耗コーティングとして広く実用化。",
 "材料工学・ナノテク","表面・コーティング工学",1971,None,"method","摺動・工具",
 "sp3/sp2比・H含量・内部応力・密着強度評価","超低摩擦・高硬度コーティングが必要な場合",
 "剥離防止は?厚膜化は?","TiN","DLC,ダイヤモンドライクカーボン,超硬コーティング,摺動","DLC,diamond-like carbon,hard coating,tribology",
 "active","primary",87,8,"https://doi.org/10.1016/j.diamond.2008.12.008","欧米",0.9,
 r"硬度: ta-C $H \approx 40-80$ GPa。摩擦係数: $\mu < 0.05$ (DLC対鋼,乾燥)。Hertz接触: $p_0 = \sqrt{6FE^{*2}/(\pi^3 R^2)}$","url_present"),

("mat_b3_037","固体酸化物燃料電池材料設計","Solid Oxide Fuel Cell Material Design","SOFC LSM LSCF YSZ GDC electrolyte anode",
 "La(Sr)MnO3カソード・Ni-YSZアノード・YSZ/GDC電解質の混合伝導体設計・焼結共存性・熱膨張整合によりSOFCの発電性能と長期安定性を実現する設計手法。",
 "天然ガス・水素・バイオガスの高効率発電(60%超)と熱電供給を実現。700-1000°C動作の大型定置電源として実用化。",
 "材料工学・ナノテク","電気化学材料工学",1937,None,"method","エネルギー変換",
 "イオン-電子混合伝導率・熱膨張整合・界面デグラデーション評価","高温固体電解質燃料電池が必要な場合",
 "低温化(500-700°C)は?Cr被毒防止は?","PEMFC","SOFC,固体酸化物燃料電池,YSZ,LSM,発電","SOFC,solid oxide fuel cell,YSZ,LSM,high temperature",
 "active","primary",87,8,"https://doi.org/10.1038/s41578-019-0121-6","欧米",0.9,
 r"Nernst EMF: $E = E^0 + \frac{RT}{4F}\ln\frac{p_{O_2,cathode}}{p_{O_2,anode}}$。ASR目標: $< 0.15\ \Omega\cdot\text{cm}^2$ at 800°C","url_present"),

("mat_b3_038","機能性表面テクスチャリング","Functional Surface Texturing Design","laser texturing biomimetic lotus shark skin hydrophobic",
 "フェムト秒レーザー・エッチング・コーティングによりマイクロ-ナノ階層構造を形成し、超疎水性・摩擦低減・光学機能を表面に付与するテクスチャリング設計手法。",
 "自動車塗装防汚・熱交換器伝熱促進・バイオセンサーの表面機能化に応用。",
 "材料工学・ナノテク","表面工学",2000,None,"method","表面機能化",
 "テクスチャパターン・深さ・空間周波数と機能の相関設計","表面濡れ性・摩擦の精密制御が必要な場合",
 "スケールアップ製造は?ロバスト性確保は?","平滑面","超疎水,テクスチャリング,バイオミメティクス,レーザー加工","superhydrophobic,texturing,biomimetic,lotus effect",
 "active","primary",85,7,"https://doi.org/10.1126/science.aaf8645","欧米",0.9,
 r"Wenzel疎水性: $\cos\theta_W = r\cos\theta_Y$。Cassie-Baxter: $\cos\theta_{CB} = f(1+\cos\theta_Y)-1$。超疎水: $\theta > 150°$","url_present"),

("mat_b3_039","セラミック/金属傾斜機能材料","Functionally Graded Material Design","FGM composition gradient thermal stress Japan",
 "日本の新野正之が1987年に提唱した傾斜機能材料(FGM)の組成・気孔率の連続変化設計により熱応力集中を緩和しながら金属/セラミックス界面接合を実現する手法。",
 "宇宙機・原子炉・高温構造部品の熱遮蔽と機械的結合の同時実現に貢献。概念提案から30年で国際標準技術へ。",
 "材料工学・ナノテク","複合材料工学",1987,None,"method","宇宙・原子炉",
 "組成勾配プロファイル・熱応力分布・製造プロセス設計","金属-セラミックス間の熱応力緩和が必要な場合",
 "多成分FGMへの拡張は?AM法との組合せは?","従来均質接合","傾斜機能材料,FGM,熱応力,日本","FGM,functionally graded material,thermal stress,Japan",
 "active","primary",86,5,"https://doi.org/10.1016/0263-8223(93)90188-7","東アジア",0.95,
 r"熱応力緩和: $\sigma(x) = E(x)[\alpha(x)-\bar{\alpha}]\Delta T$。分布則: $V_c(x) = (x/h)^n$, n: 勾配指数","url_present"),

("mat_b3_040","コークス製造設計","Coke Manufacturing Design","coking coal blend charge density metallurgical coke",
 "配合炭の膨張性・反射率・最高流動度・ヴィトリニット量を組み合わせ、高強度・高反応性冶金コークスを製造するコークス炉装入設計手法。",
 "高炉製鉄の基礎。CSR(コークス強度after Reaction)>65・CRI<25を満たすコークス製造が高炉効率の鍵。",
 "材料工学・ナノテク","鉄鋼材料工学",1850,None,"method","製鉄",
 "配合炭反射率・流動度分布・コークス炉温度設計","高炉用冶金コークス製造が必要な場合",
 "配合炭不均質性対応は?非微粘結炭比率拡大は?","電炉電力製鉄","コークス,製鉄,高炉,配合炭","metallurgical coke,coking coal,blast furnace,CSR",
 "active","primary",85,9,"https://doi.org/10.1016/j.fuel.2016.02.059","欧米",0.85,
 r"Micum試験: M10 $<$ 10\%, M40 $>$ 78\%。CSR-CRI相関: $CSR = -0.77 CRI + 97$","url_present"),

("mat_b3_041","高純度アルミニウム電解製錬設計","High-Purity Aluminum Electrolytic Smelting Design","Hall-Heroult Al electrolysis China aluminum",
 "氷晶石(Na3AlF6)融液中Al2O3の電解によるホール-エルー法の電流効率・エネルギー消費・陰極寿命を中国が大規模最適化した製錬プロセス設計。",
 "中国が世界のアルミ生産量の約60%を担う。電力コスト最小化と電流効率95%超が競争力の鍵。",
 "材料工学・ナノテク","冶金工学",1886,None,"method","基礎素材",
 "陽極電流密度・浴温・AlF3過剰率・浴組成制御","低コスト高品質アルミ生産が必要な場合",
 "惰性陽極への移行は?GHG排出削減は?","鉄鋼製造","アルミニウム電解,ホール-エルー法,中国,電流効率","Hall-Heroult,aluminum electrolysis,current efficiency,China",
 "active","primary",87,9,"https://doi.org/10.1007/978-3-030-02137-8","東アジア",0.9,
 r"Faraday効率: $\eta_{CE} = m_{Al}/m_{theor} \approx 93-95\%$。エネルギー消費: $E = U \cdot I/(\eta_{CE} \cdot m_{Al}) \approx 13-14$ kWh/kg","url_present"),

("mat_b3_042","プラズマ溶射コーティング設計","Plasma Spray Coating Design","APS VPS HVOF thermal spray ceramic metallic",
 "大気・真空プラズマ溶射(APS/VPS)・高速フレーム溶射(HVOF)により金属・セラミックス粉末を基材に高速堆積し、気孔率・ラメラ構造・密着強度を制御する設計手法。",
 "TBCガスタービン・生体適合HAコーティング・耐摩耗コーティングとして広く実用化。",
 "材料工学・ナノテク","表面・コーティング工学",1956,None,"method","航空宇宙・医療",
 "粒子温度・速度・基材前処理・後熱処理設計","高温・耐摩耗コーティングが必要な場合",
 "コールドスプレーとの比較は?残留応力緩和は?","電着めっき","プラズマ溶射,HVOF,TBC,溶射コーティング","plasma spray,HVOF,thermal spray,TBC",
 "active","primary",87,8,"https://doi.org/10.1007/s11666-016-0441-3","欧米",0.85,
 r"粒子速度: $v_p = \sqrt{2 C_{D,max} \rho_{gas} v_{gas}^2 A_p / (m_p C_D)}$。密着強度: ASTM C633 $> 50$ MPa (最高品質)","url_present"),

("mat_b3_043","バリア機能フィルム設計","Barrier Film Design","WVTR OTR flexible packaging OLED encapsulation",
 "SiOx・Al2O3・有機/無機多層のPVD/CVD積層により水蒸気透過率(WVTR<10⁻⁶g/m²/day)・酸素透過率を最小化するフレキシブルバリアフィルム設計手法。",
 "フレキシブルOLED封止・医薬品包装・食品鮮度保持の超高バリア膜として実用化が進んでいる。",
 "材料工学・ナノテク","薄膜プロセス工学",2000,None,"method","パッケージング・ディスプレイ",
 "欠陥密度・ピンホール数・膜応力・温度安定性評価","超低透湿・酸素バリアが必要な場合",
 "フレキシブル変形への耐性は?コスト削減は?","ガラス封止","バリアフィルム,WVTR,OLED封止,フレキシブル","barrier film,WVTR,OTR,OLED encapsulation,flexible",
 "active","primary",86,6,"https://doi.org/10.1063/1.4818308","欧米",0.9,
 r"WVTR目標(OLED): $< 10^{-6}$ g/m²/day。欠陥確率: $P_{defect} = 1-\exp(-\lambda A)$。多層緩和: $WVTR_{multilayer} \propto (WVTR_{single})^n$","url_present"),

("mat_b3_044","超伝導量子ビット材料設計","Superconducting Qubit Material Design","transmon Josephson junction Al Nb Qubit coherence",
 "Al/AlOx/Al・Nb/AlOx/Nbジョセフソン接合の酸化膜厚・欠陥密度・表面損失を制御し量子コヒーレンス時間(T2>100μs)を延ばす量子コンピュータ用材料設計手法。",
 "IBMQuantum・Google・中国の量子コンピュータ開発の基幹材料技術。超伝導量子ビットの実用化に不可欠。",
 "材料工学・ナノテク","量子材料工学",1999,None,"method","量子コンピュータ",
 "接合均一性・表面TLS欠陥・クエンチング制御","量子コヒーレンス時間最大化が必要な場合",
 "TLS欠陥の根本除去は?新材料(TiN・Ta)への移行は?","半導体量子ビット","量子ビット,ジョセフソン接合,超伝導,コヒーレンス","superconducting qubit,Josephson junction,coherence,quantum computing",
 "active","primary",86,5,"https://doi.org/10.1103/PhysRevLett.95.210503","欧米",0.9,
 r"transmon周波数: $f_{01} \approx \sqrt{8E_JE_C}/h$。コヒーレンス: $T_2 = 2T_1$ (純粋退位相がない場合)。Josephson: $I = I_c\sin\phi$","url_present"),

("mat_b3_045","強誘電体ドメイン制御","Ferroelectric Domain Engineering","PZT BaTiO3 domain wall MEMS piezo actuator",
 "PZT・BaTiO3強誘電体のドメイン構造・分極反転電界・電場-ひずみ曲線を電極形状・分極処理・クランプ条件で制御し、アクチュエータ・超音波センサー特性を最大化する設計手法。",
 "医療超音波プローブ・インクジェットヘッド・MEMSアクチュエータの基幹技術として確立。",
 "材料工学・ナノテク","電子セラミックス工学",1920,None,"method","医療・MEMSセンサー",
 "矯頑電界Ec・残留分極Pr・圧電定数d33評価","高精度変位制御アクチュエータが必要な場合",
 "Pb-free化対応は?超高圧駆動は?","電磁アクチュエータ","強誘電体,ドメイン制御,PZT,圧電アクチュエータ","ferroelectric,domain engineering,PZT,piezo actuator",
 "active","primary",87,8,"https://doi.org/10.1038/nmat3756","欧米",0.9,
 r"ランダウ-デボンシール自由エネルギー: $F = \alpha P^2 + \beta P^4 + \gamma P^6 - EP$。$d_{33} = 2\epsilon_0\epsilon_r Q_{11}P_s$","url_present"),

("mat_b3_046","ポリマー太陽電池非フラーレン受容体設計","Non-Fullerene Acceptor Polymer Solar Cell Design","NFA Y6 IT-4F ITIC PBDB-T morphology",
 "ITIC・Y6等の非フラーレン受容体とドナーポリマーのLUMO-HOMO差・形態的相分離・モルフォロジー制御によりOPV効率18%超を達成する分子設計手法。",
 "太陽電池の有機薄膜技術でフラーレン系を凌駕し、効率記録を更新中。中国研究者がY6発見で主導。",
 "材料工学・ナノテク","有機材料工学",2015,None,"method","エネルギー変換",
 "HOMO/LUMO整合・モルフォロジー・相純度評価","高効率有機太陽電池が必要な場合",
 "長期安定性向上は?大面積印刷は?","フラーレン系OPV","非フラーレン受容体,OPV,Y6,有機太陽電池","NFA,Y6,non-fullerene acceptor,OPV,organic solar",
 "active","primary",86,5,"https://doi.org/10.1016/j.joule.2019.01.004","東アジア",0.85,
 r"VOC予測: $V_{OC} = (1/e)(E_{LUMO,A} - E_{HOMO,D}) - 0.6$ V (経験則)。FF $= \frac{J_{mp}V_{mp}}{J_{sc}V_{oc}}$","url_present"),

("mat_b3_047","センサー用薄膜材料設計","Thin Film Sensor Material Design","MEMS piezoresistive piezoelectric IR pyroelectric",
 "圧抵抗(Si・ポリSi)・圧電(ZnO・AlN・PZT)・焦電(LiTaO3)・抵抗型(VO2・GST)薄膜のMEMSプロセスと感度・応答速度・安定性を最適化する設計手法。",
 "スマートフォン・IoT・医療診断用マイクロセンサーの基盤技術として産業的重要性が高い。",
 "材料工学・ナノテク","センサー材料工学",1960,None,"method","センサー・IoT",
 "ゲージ率・温度係数・1/fノイズ・クロスセンシティビティ評価","高感度・低ノイズマイクロセンサーが必要な場合",
 "CMOS集積化は?多軸センシングは?","バルク機械式センサー","MEMSセンサー,圧電薄膜,IoT,センサー材料","MEMS sensor,piezoelectric,piezoresistive,IoT,thin film",
 "active","primary",87,9,"https://doi.org/10.1016/j.sna.2016.04.052","欧米",0.9,
 r"圧抵抗感度: $\Pi_l = (1/\rho_0)\partial\rho/\partial\sigma_l$。Siゲージ率: $GF = 1 + 2\nu + \pi_l E \approx 100-150$","url_present"),

("mat_b3_048","鉄鋼焼入れ焼戻し熱処理設計","Steel Quenching and Tempering Design","Q&T martensite hardness toughness CCT diagram",
 "鉄鋼のオーステナイト化温度・焼入れ媒体・焼戻し温度を制御し、マルテンサイト変態量・焼入れひずみ・焼戻し軟化特性を最適化する熱処理設計手法。",
 "機械構造用鋼・工具鋼・ばね鋼・軸受鋼の強度・靭性・疲労特性向上の最も基本的かつ重要な製造技術。",
 "材料工学・ナノテク","鉄鋼材料工学",1800,None,"method","機械・工具",
 "Ac3温度・Ms温度・焼入れ硬度・焼戻し温度設計","強靭鋼部品の製造が必要な場合",
 "焼入れひずみ・割れ防止は?高温焼戻し軟化耐性は?","浸炭焼入れ","焼入れ焼戻し,マルテンサイト,硬度,靭性","quenching tempering,martensite,hardness,toughness,steel",
 "active","primary",90,9,"https://doi.org/10.1016/j.matchar.2018.06.016","欧米",0.9,
 r"マルテンサイト硬度: $H_{RC} \approx 64 - 6.5\sqrt{C_M}$。焼戻し軟化: $H = H_0\exp(-k t^n)$。Ms($°C$) $= 539 - 423C - 30.4Mn - 17.7Ni - 12.1Cr - 7.5Mo$","url_present"),

("mat_b3_049","中国Si IGBT・車載パワー設計","China Si IGBT Automotive Power Design","IGBT EV traction inverter CRRC BYD SAIC",
 "CRRC・BYD・士兰微等中国企業が開発する600-1700V SiIGBTの電流集中・ゲート駆動・温度サイクル耐久性の車載インバーター向け最適化設計技術。",
 "中国のEV急拡大に伴いIGBT国産化が国家戦略課題に。外国依存からの脱却を進める国産IGBT開発が加速。",
 "材料工学・ナノテク","半導体材料工学",1990,None,"method","電力電子",
 "ゲート酸化膜信頼性・熱抵抗・短絡耐量・EMC設計","高圧大電流スイッチングが必要な場合",
 "GaN/SiC代替タイムラインは?国産化率目標は?","外国製IGBT","IGBT,パワー半導体,EV,中国,インバーター","IGBT,power semiconductor,EV,China,inverter,traction",
 "active","primary",86,8,"https://doi.org/10.1109/TPEL.2019.2920424","東アジア",0.95,
 r"スイッチング損失: $E_{sw} = \frac{1}{2}V_{DC}I_C(t_{ri}+t_{fi})$。熱抵抗: $\theta_{jc} < 0.1$ K/W。短絡耐量: $I_{SC}/I_N > 6 \times$, $t_{SC} > 10\mu$s","url_present"),

("mat_b3_050","ナノ多孔質炭素材料設計","Nanoporous Carbon Material Design","activated carbon supercapacitor EDLC templating",
 "テンプレート法・活性化法・KOH活性化・CO2賦活によりナノ多孔質炭素の細孔径分布・比表面積(3000m²/g超)・導電率を制御し、スーパーキャパシタ・ガス吸着・触媒担体に応用する設計手法。",
 "電気二重層キャパシタ(EDLC)のエネルギー密度向上と急速充電の基盤材料技術。",
 "材料工学・ナノテク","炭素材料工学",1950,None,"method","エネルギー貯蔵",
 "細孔径分布・BET表面積・電気化学ウィンドウ評価","超高比表面積炭素が必要な場合",
 "エネルギー密度と出力密度の両立は?ドーピング効果は?","電解コンデンサ","ナノ多孔質炭素,スーパーキャパシタ,活性炭,EDLC","nanoporous carbon,supercapacitor,EDLC,activated carbon",
 "active","primary",86,7,"https://doi.org/10.1039/C0EE00716A","欧米",0.9,
 r"二重層容量: $C = \epsilon_0\epsilon_r A/d$。比エネルギー: $E = \frac{1}{2}CV^2$。Ragone関係: $P = V^2/(4R_{ESR})$","url_present"),
]

if __name__ == "__main__":
    inserted, skipped = insert_records(records)
    print(f"Inserted: {inserted}, Skipped: {skipped}")
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Total: {total}")
