#!/usr/bin/env python3
"""機械工学 Batch 3: mech_b3_001–050"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
    ("mech_b3_001","アイソゲオメトリック解析","Isogeometric Analysis","IGA",
     "CADのNURBSジオメトリを直接有限要素解析の基底関数として利用する手法。メッシュ生成コストを削減し幾何形状の精度を保持する。",
     "CAD-CAE統合を実現し形状最適化の精度向上に貢献。",
     "機械工学","計算力学",2005,None,"手法","構造解析・流体解析",
     "CADモデルが存在し曲面精度が重要な問題","形状最適化・シェル構造解析",
     "NURBSパッチをどう有限要素分割するか？境界条件の適用方法は？",
     "標準FEM","等幾何解析,NURBS,CAD-CAE統合,境界要素法","IGA,NURBS,CAD-CAE,shell analysis",
     "active","primary",90,7,
     "https://www.sciencedirect.com/science/article/pii/S0045782505000831",
     "欧米","high",
     r"IGA基底関数: $N_{i,p}(t)$ (B-spline). 剛性行列: $K = \int_\Omega B^T D B \, d\Omega$ (NURBSマッピング). 収束率: $h$-細分化で $O(h^{p+1})$.",
     "url_present"),

    ("mech_b3_002","格子ボルツマン法","Lattice Boltzmann Method","LBM",
     "流体を粒子集団の統計分布として扱いメッシュ格子上で輸送・衝突を計算するCFD手法。複雑境界や多相流に強い。",
     "多孔質媒体流動・気泡流のシミュレーションで従来CFDより効率的。",
     "機械工学","計算流体力学",1988,None,"手法","流体解析・熱流体",
     "複雑形状・多相流・LBMの並列計算資源がある場合","マイクロ流路・多孔質媒体流れ解析",
     "緩和時間τをどう設定するか？境界条件(no-slip)の実装は？",
     "従来Navier-Stokes有限差分法","格子ボルツマン,多相流,並列CFD,流体シミュレーション","LBM,lattice Boltzmann,multiphase flow,mesoscale CFD",
     "active","primary",85,8,
     "https://www.sciencedirect.com/science/article/pii/S0021999196901459",
     "欧米","high",
     r"LBM方程式: $f_i(\mathbf{x}+\mathbf{e}_i\Delta t, t+\Delta t) = f_i(\mathbf{x},t) - \frac{1}{\tau}[f_i - f_i^{eq}]$. 平衡分布: $f_i^{eq} = \rho w_i [1 + \frac{\mathbf{e}_i \cdot \mathbf{u}}{c_s^2} + \frac{(\mathbf{e}_i \cdot \mathbf{u})^2}{2c_s^4} - \frac{u^2}{2c_s^2}]$.",
     "url_present"),

    ("mech_b3_003","確率有限要素法","Stochastic Finite Element Method","SFEM",
     "材料特性・境界条件の不確実性を確率変数として扱い応答の統計量を算出するFEM拡張手法。",
     "構造信頼性評価において決定論的FEMの限界を超えた不確実性定量化を可能にする。",
     "機械工学","計算力学",1990,None,"手法","構造解析",
     "材料特性にばらつきがある設計問題","信頼性設計・ロバスト構造設計",
     "確率変数の相関構造をどう表現するか？計算コスト削減法は？",
     "決定論的FEM","確率FEM,不確実性定量化,モンテカルロ法,信頼性工学","SFEM,uncertainty quantification,reliability analysis,Monte Carlo",
     "active","primary",80,7,
     "https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.1620300207",
     "欧米","high",
     r"確率剛性: $K(θ) = K_0 + \sum_i θ_i K_i$. 応答分散: $\text{Var}[u] \approx \sum_{i,j} \frac{\partial u}{\partial θ_i}\frac{\partial u}{\partial θ_j}\text{Cov}[θ_i,θ_j]$. PCE展開: $u = \sum_α u_α Ψ_α(θ)$.",
     "url_present"),

    ("mech_b3_004","マルチスケール力学","Multiscale Mechanics","",
     "ナノ・マイクロ・マクロの異なるスケールを連携させて材料・構造の力学応答を解析するアプローチ。均質化理論やQC法を含む。",
     "新材料の巨視的特性を微視的構造から予測し材料設計を加速。",
     "機械工学","計算力学",1995,None,"枠組","材料力学・複合材料",
     "材料の微視的構造が巨視的特性に支配的影響を与える場合","複合材料・クリープ・破壊解析",
     "スケール間の情報をどう受け渡すか？RVEのサイズをどう決定するか？",
     "単スケール連続体力学","マルチスケール解析,均質化理論,RVE,複合材料","multiscale mechanics,homogenization,RVE,concurrent multiscale",
     "active","primary",85,7,
     "https://www.sciencedirect.com/science/article/pii/S0045782598003476",
     "欧米","high",
     r"均質化: $\langle \sigma \rangle = C^{eff} \langle \varepsilon \rangle$. FE2法: マクロ点にRVE境界値問題を埋め込む. Cauchy-Born則: $\mathbf{F}_{atom} = \mathbf{F}_{macro}$.",
     "url_present"),

    ("mech_b3_005","溶接変形・残留応力解析","Welding Distortion and Residual Stress Analysis","",
     "溶接による熱・構造連成問題を有限要素法で解析し,溶接後の変形量および残留応力分布を予測する手法。",
     "溶接構造物の品質保証と溶接シーケンス最適化に不可欠。",
     "機械工学","製造プロセス工学",2000,None,"手法","製造・溶接工学",
     "溶接プロセス設計・品質保証が必要な場合","構造用鋼・アルミ溶接構造物",
     "熱源モデル(Goldak二重楕円体)の妥当性検証は？相変態の影響は？",
     "実験的測定のみ","溶接シミュレーション,残留応力,熱-構造連成,変形予測","welding simulation,residual stress,thermo-structural coupling,distortion prediction",
     "active","secondary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0924013605002529",
     "欧米","high",
     r"Goldak熱源: $q(x,y,z) = \frac{6\sqrt{3}Q}{abc\pi\sqrt{\pi}}\exp(-\frac{3x^2}{a^2}-\frac{3y^2}{b^2}-\frac{3z^2}{c^2})$. 熱弾塑性構成則: $d\varepsilon = d\varepsilon^e + d\varepsilon^p + d\varepsilon^{th}$.",
     "url_present"),

    ("mech_b3_006","機械インピーダンス法","Mechanical Impedance Method","",
     "機械系の入力と出力の比(インピーダンス)を周波数領域で評価し動的特性を解析する手法。振動絶縁・NVH解析に用いる。",
     "自動車・航空機のNVH設計においてサブシステム結合解析を効率化。",
     "機械工学","振動・音響工学",1950,None,"手法","振動解析・NVH",
     "結合システムの振動特性を評価する場合","自動車ボディ・航空機フレーム振動解析",
     "サブシステム間の結合条件をどう処理するか？測定点をどう選ぶか？",
     "伝達関数法","インピーダンス,NVH,振動絶縁,サブシステム結合","mechanical impedance,NVH,vibration isolation,subsystem coupling",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0022460X83800461",
     "欧米","high",
     r"インピーダンス: $Z(\omega) = \frac{F(\omega)}{v(\omega)}$. 結合系: $Z_{total} = Z_A + Z_B$ (直列). 振動絶縁率: $TL = 20\log_{10}|Z_{isolator}/Z_{receiver}|$.",
     "url_present"),

    ("mech_b3_007","超音波加工","Ultrasonic Machining","USM",
     "超音波振動を付与した工具でアブレシブスラリーを介して脆性材料を加工する非切削的手法。セラミックス・ガラスの精密加工に使用。",
     "脆性材料の高精度3次元加工を可能にし光学部品・医療デバイスに貢献。",
     "機械工学","精密加工技術",1950,None,"手法","特殊加工・精密工学",
     "脆性材料・難削材の精密成形が必要な場合","セラミックス・石英・半導体加工",
     "振動周波数・振幅・スラリー粒径の最適化は？工具摩耗管理は？",
     "ダイヤモンド砥石研削","超音波加工,脆性材料,アブレシブ加工,精密工学","USM,ultrasonic machining,brittle material,abrasive machining",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0007850697801175",
     "欧米","medium",
     r"材料除去率(MRR): $MRR = K \cdot f \cdot A^2 \cdot \sqrt{\frac{H_w}{H_t}} \cdot d_g^{1/2}$ ($f$:周波数,$A$:振幅,$H$:硬さ,$d_g$:砥粒径). 接触力: $F = F_0 \sin(2\pi f t)$.",
     "url_present"),

    ("mech_b3_008","熱弾性不安定性","Thermoelastic Instability","TEI",
     "ブレーキ・クラッチ等の摩擦接触面で摩擦熱による熱変形がコンタクト圧力を局所集中させ不安定振動を引き起こす現象。",
     "自動車ブレーキのジャダー現象の理解と対策設計に直結する工学知識。",
     "機械工学","摩擦・トライボロジー",1969,None,"理論","摩擦・熱設計",
     "ブレーキ・クラッチ等の高速摩擦接触面設計","自動車ブレーキジャダー抑制",
     "臨界速度をどう予測するか？材料特性の影響は？",
     "静的熱解析","熱弾性不安定性,ブレーキジャダー,摩擦接触,不安定振動","TEI,thermoelastic instability,brake judder,frictional contact",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/0043164869900128",
     "欧米","high",
     r"TEI臨界速度: $V_c = \frac{2k\pi}{l f(m)}$ ($k$:熱拡散率,$l$:ウェーブ長,$f$:摩擦係数). 増幅率: $b = \mu q_0 \alpha V_c$ ($\alpha$:熱膨張係数).",
     "url_present"),

    ("mech_b3_009","流体構造連成最適化","Fluid-Structure Interaction Optimization","FSI-OPT",
     "FSI解析をベースに形状・位相最適化を組み合わせ,流れと構造の両方の性能を同時に最適化する手法。",
     "航空機翼・タービンブレード形状設計における空力-構造トレードオフを自動化。",
     "機械工学","設計最適化",2010,None,"手法","設計最適化・空力構造",
     "流れと構造の相互作用が支配的な設計最適化問題","翼形状・風車ブレード・血管ステント設計",
     "FSI感度解析の計算コストをどう削減するか？局所最適解への収束対策は？",
     "個別最適化","FSI最適化,形状最適化,空力弾性,連成最適化","FSI optimization,aeroelastic optimization,coupled design,adjoint method",
     "active","primary",75,6,
     "https://www.sciencedirect.com/science/article/pii/S0045782519304517",
     "欧米","high",
     r"随伴法感度: $\frac{dJ}{d\phi} = \frac{\partial J}{\partial \phi} + \lambda^T \frac{\partial R}{\partial \phi}$ ($R$:連成残差,$\lambda$:ラグランジュ乗数). FSI: $M_s \ddot{u} + C_s \dot{u} + K_s u = f_{fluid}$.",
     "url_present"),

    ("mech_b3_010","逆問題解析","Inverse Problem Analysis","",
     "観測結果から逆算して材料特性・境界条件・荷重を同定する手法。ノイズに対するIll-posedness処理が重要。",
     "非破壊検査・医療イメージングでの材料特性同定に広く応用。",
     "機械工学","計算力学",1975,None,"手法","非破壊検査・材料同定",
     "観測データから未知の材料・荷重情報を推定する必要がある場合","超音波NDT・熱拡散率同定",
     "Tikhonov正則化パラメータをどう選ぶか？測定ノイズの影響は？",
     "直接解析","逆問題,正則化,材料同定,非破壊検査","inverse problem,Tikhonov regularization,material identification,NDT",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/0045782588900244",
     "欧米","high",
     r"Tikhonov正則化: $\min_x \|Ax - b\|^2 + \alpha\|Lx\|^2$. 最適正則化: $\alpha^* = \arg\min GCV(\alpha) = \frac{\|A x_\alpha - b\|^2}{[tr(I - A A^\dagger)]^2}$. 感度行列: $S_{ij} = \frac{\partial u_i}{\partial p_j}$.",
     "url_present"),

    ("mech_b3_011","表面テクスチャリング","Surface Texturing","",
     "表面に微細な幾何学的パターン(溝・窪み・ピラー)を形成してトライボロジー特性・濡れ性・光学特性を改善する技術。",
     "摩擦低減・流体潤滑強化で内燃機関シリンダーライナーの摩耗を大幅削減。",
     "機械工学","表面工学",2000,None,"手法","トライボロジー・精密工学",
     "摩擦低減・濡れ性制御・光学機能付与が必要な表面設計","エンジン部品・医療インプラント・光学素子",
     "テクスチャ形状・密度をどう最適化するか？製造方法(レーザー・MEMS)の選択は？",
     "平滑面処理","表面テクスチャリング,レーザー加工,摩擦低減,マイクロ構造","surface texturing,laser surface processing,tribology,wettability",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0301679X01000634",
     "欧米","high",
     r"テクスチャ密度: $S_p = N_d A_d / A_{total}$. レイノルズ方程式(テクスチャ付き): $\frac{\partial}{\partial x}(h^3 \frac{\partial p}{\partial x}) + \frac{\partial}{\partial y}(h^3 \frac{\partial p}{\partial y}) = 6\mu U \frac{\partial h}{\partial x}$. 摩擦係数低減: $\Delta\mu / \mu_0 \approx 0.3 S_p$.",
     "url_present"),

    ("mech_b3_012","射出成形最適化","Injection Molding Optimization","",
     "射出成形プロセスのCAE解析(Moldflow等)を用いてゲート位置・冷却回路・成形条件を最適化する手法。",
     "成形品のソリ・ヒケ・ウェルドライン欠陥を削減し量産品質を確保。",
     "機械工学","高分子加工技術",1980,None,"手法","プラスチック成形・製造工学",
     "プラスチック射出成形金型設計・成形条件設定","家電・自動車内装・医療機器部品",
     "冷却チャンネル設計をどう最適化するか？残留応力起因のソリをどう抑制するか？",
     "試作・試行錯誤","射出成形,CAE,ソリ変形,冷却設計,ゲート位置","injection molding,Moldflow,warpage,cooling channel optimization",
     "active","secondary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0032386108007234",
     "欧米","high",
     r"充填圧力: $P_{fill} = \frac{6\mu L Q}{\pi R^4}$ (円形断面流路). ソリ支配: $\delta_{warp} \propto \Delta\alpha \Delta T \cdot L^2 / t$ ($\Delta\alpha$:収縮差). 冷却時間: $t_c = \frac{s^2}{\pi^2 a}\ln(\frac{4}{\pi}\frac{T_m - T_w}{T_e - T_w})$.",
     "url_present"),

    ("mech_b3_013","磁気軸受","Magnetic Bearing","",
     "電磁石の吸引力でロータを非接触支持する軸受。摩耗なし・高速回転・真空環境対応が特徴で能動的位置制御を伴う。",
     "超高速スピンドル・フライホイールエネルギー貯蔵・宇宙機構への適用で機械損失を革命的に削減。",
     "機械工学","精密機械・制御",1978,None,"手法","精密機械・エネルギー",
     "高速回転・無潤滑・高温環境が必要なロータ支持系","ターボ分子ポンプ・MRI・フライホイール蓄電",
     "ギャップ不安定性(オープンループ不安定)をどう安定化するか？電力損失最小化は？",
     "玉軸受・流体軸受","磁気軸受,能動制御,非接触回転,AMB","magnetic bearing,AMB,active magnetic bearing,non-contact rotation",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0888327014003355",
     "欧米","high",
     r"電磁力: $F = \frac{\mu_0 A N^2 i^2}{4 x^2}$ ($x$:ギャップ,$i$:電流,$N$:巻数). 線形化: $F \approx k_s x + k_i i$ ($k_s$:位置剛性(正),負剛性を補償するPID必要). 臨界回転数: $\Omega_c = \sqrt{k_{bearing}/m}$.",
     "url_present"),

    ("mech_b3_014","金属3Dプリンティング欠陥制御","Defect Control in Metal Additive Manufacturing","",
     "SLM/EBM等の金属積層造形における気孔・残留応力・ミクロ組織不均一性を解析し制御する工学的アプローチ。",
     "航空機エンジン部品の積層造形品質保証で量産適用への道を開いた。",
     "機械工学","積層造形工学",2010,None,"手法","製造・品質工学",
     "金属3Dプリント部品の品質検証・プロセス最適化","チタン合金・インコネル製航空宇宙部品",
     "プロセスパラメータ-品質関係をどうモデル化するか？インプロセス監視手法は？",
     "従来鋳造・鍛造","積層造形欠陥,SLM,気孔制御,残留応力","additive manufacturing defects,SLM,porosity,residual stress control",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S2214860418301520",
     "欧米","high",
     r"エネルギー密度: $E_v = \frac{P}{v \cdot h \cdot t}$ ($P$:出力,$v$:走査速度,$h$:ハッチ間隔,$t$:層厚). 気孔率予測: $\phi_{pore} = f(E_v, T_{preheat})$. 残留応力: $\sigma_{res} = E\alpha\Delta T/(1-\nu)$.",
     "url_present"),

    ("mech_b3_015","機械学習による疲労寿命予測","Machine Learning for Fatigue Life Prediction","",
     "材料組成・微細構造・応力状態の特徴量を機械学習モデルに入力して疲労き裂発生寿命を予測する手法。",
     "従来の経験式(S-N曲線)を超えた多変数疲労予測モデルを構築し実験コストを削減。",
     "機械工学","材料強度学",2015,None,"手法","材料評価・疲労設計",
     "大量の疲労試験データが存在し多パラメータ予測が必要な場合","航空機構造・プレッシャーベッセル疲労設計",
     "どの特徴量が重要か？少数サンプルでの汎化性確保は？",
     "経験的S-N曲線","機械学習,疲労寿命,S-N曲線,材料強度予測","ML fatigue prediction,S-N curve,feature engineering,fatigue life",
     "active","secondary",78,6,
     "https://www.sciencedirect.com/science/article/pii/S0142112320303017",
     "欧米","high",
     r"ガウス過程回帰: $f(x) \sim \mathcal{GP}(\mu(x), k(x,x'))$. 予測分布: $\hat{f}(x^*) \sim \mathcal{N}(\mu^*, \sigma^{*2})$. S-N曲線フィッティング: $\log N = a - b \log \Delta\sigma$.",
     "url_present"),

    ("mech_b3_016","熱音響冷凍","Thermoacoustic Refrigeration","",
     "音波(音響振動)による圧力・変位の位相差を利用してスターリングサイクル類似の冷凍・ヒートポンプを実現する装置。",
     "可動部を持たない冷凍機として宇宙・低温工学・液化天然ガス分野で注目される。",
     "機械工学","熱工学",1975,None,"手法","冷凍・低温工学",
     "可動部不要・極低温冷却・振動環境下の冷凍設計","宇宙極低温冷却・LNG液化・クライオクーラー",
     "レゾネータ設計と作動流体の選択は？音響-熱変換効率最大化は？",
     "蒸気圧縮冷凍機","熱音響,スターリング冷凍機,音響冷凍,低温工学","thermoacoustic,Stirling refrigeration,acoustic cooling,cryocooler",
     "active","primary",78,5,
     "https://www.sciencedirect.com/science/article/pii/S0011227502000188",
     "欧米","high",
     r"Swift方程式(熱音響): $\dot{W}_2 = \frac{1}{2}\text{Re}[\tilde{p}_1 \tilde{U}_1^*]$ ($\tilde{p}_1$:圧力振幅,$\tilde{U}_1$:体積流量). COP: $COP = \dot{Q}_c / \dot{W} \leq COP_{Carnot} = T_c/(T_h - T_c)$.",
     "url_present"),

    ("mech_b3_017","高エントロピー合金設計","High-Entropy Alloy Design","HEA",
     "5種類以上の主要元素をほぼ等モル比で混合した多主元素合金(HEA)の組成・構造設計手法。優れた機械的特性・耐食性を発現。",
     "従来の二元・三元系合金の枠を超えた組成空間探索で高強度高延性材料の発見を加速。",
     "機械工学","材料設計",2004,None,"枠組","先端材料・材料工学",
     "特殊な機械的・熱的・化学的特性の組み合わせが必要な場合","航空宇宙耐熱材・核融合材料・クライオジェニック部品",
     "どの元素組み合わせが単相固溶体を形成するか？予測モデルは？",
     "従来合金設計","高エントロピー合金,多主元素合金,固溶体強化,材料設計","HEA,multi-principal element alloy,solid solution,entropy stabilization",
     "active","primary",82,6,
     "https://www.sciencedirect.com/science/article/pii/S1359645404001570",
     "東アジア","high",
     r"配置エントロピー: $\Delta S_{mix} = -R\sum_{i=1}^n x_i \ln x_i$ (等モル $n$元系: $\Delta S_{mix} = R\ln n$). HEA基準: $\Delta S_{mix} \geq 1.5R$. 原子サイズ差: $\delta = \sqrt{\sum x_i(1-r_i/\bar{r})^2} < 6.5\%$.",
     "url_present"),

    ("mech_b3_018","機能性流体アクチュエータ","Functional Fluid Actuator","",
     "磁気粘性流体(MR流体)や電気粘性流体(ER流体)を用いた可変粘性・可変剛性アクチュエータ。外場で瞬時に特性変化。",
     "自動車サスペンション・ロボット関節・地震制振ダンパーでのスマートアクチュエータ応用。",
     "機械工学","スマートシステム",1990,None,"手法","制御・アクチュエータ",
     "可変剛性・可変ダンピングが必要な適応的機械系設計","MRダンパー・ロボットアシスト装具",
     "MR流体の沈降安定性とヒステリシスをどう管理するか？応答速度は？",
     "油圧アクチュエータ","MR流体,磁気粘性,スマートアクチュエータ,ダンパー","MR fluid,magnetorheological,ER fluid,smart actuator",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0924424799000862",
     "欧米","high",
     r"MR流体降伏応力: $\tau_y = f(\phi, B) \approx C \phi^{1.5} B^{0.7}$ ($\phi$:粒子体積分率,$B$:磁束密度). Bingham塑性: $\tau = \tau_y \text{sgn}(\dot\gamma) + \mu_{off}\dot\gamma$. 力: $F = k_1 \tau_y L w$.",
     "url_present"),

    ("mech_b3_019","量子機械工学","Quantum Mechanical Engineering","",
     "量子力学効果(量子トンネリング・量子重ね合わせ)が顕在化するナノ・サブナノスケールの機械系設計。NEMSの理論基盤。",
     "NEMS共振器の質量センシング感度をアトグラムオーダーまで高め生体分子検出に応用。",
     "機械工学","MEMS/NEMS",2005,None,"理論","ナノ機械・量子デバイス",
     "熱揺らぎ・量子揺らぎが機械特性に影響するナノ機械設計","ナノ共振器・量子センサ・カーボンナノチューブMEMS",
     "量子限界計測をどう実現するか？室温での量子効果発現条件は？",
     "古典連続体力学","NEMS,量子機械,カシミール力,量子揺らぎ","NEMS,quantum mechanics,Casimir force,nanomechanical resonator",
     "active","primary",78,5,
     "https://www.sciencedirect.com/science/article/pii/S0370157308002105",
     "欧米","high",
     r"量子ゼロ点揺らぎ: $x_{zpf} = \sqrt{\hbar/(2m\omega_0)}$. カシミール力: $F_C = \frac{\pi^2 \hbar c}{240 d^4} A$ ($d$:隙間). SQL(標準量子限界): $\Delta x \Delta p \geq \hbar/2$.",
     "url_present"),

    ("mech_b3_020","機械構造物の信頼性加速試験","Accelerated Life Testing for Mechanical Structures","ALT",
     "通常よりも高いストレス(温度・荷重・振動)を付加して短時間で疲労・破壊寿命を推定する試験手法。加速係数を理論的に算出。",
     "製品開発サイクル短縮と品質保証の両立を可能にし自動車・電子機器で標準化。",
     "機械工学","信頼性工学",1960,None,"手法","信頼性・品質工学",
     "実寿命試験が時間的・費用的に実施困難な耐久性評価","自動車部品・電子部品の信頼性保証",
     "加速係数をどう設定するか？高温低温でのモード変化をどう考慮するか？",
     "実稼働寿命試験","加速寿命試験,ALT,疲労試験,信頼性工学","ALT,accelerated life testing,Arrhenius model,fatigue,reliability",
     "active","primary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0951832011001123",
     "欧米","high",
     r"Arrheniusモデル: $AF = \exp\left[\frac{E_a}{k}(\frac{1}{T_U} - \frac{1}{T_A})\right]$. Coffin-Manson: $N_f = C (\Delta\varepsilon_p)^{-c}$. Miner則: $\sum D_i = \sum n_i/N_{fi} = 1$.",
     "url_present"),

    ("mech_b3_021","自動車軽量化設計","Automotive Lightweighting Design","",
     "マルチマテリアル設計・トポロジー最適化・高強度鋼・アルミ・CFRP適用により自動車の重量を削減する総合的設計手法。",
     "車両重量100kg削減でCO2排出量8-10g/km削減効果があり燃費規制対応の中核技術。",
     "機械工学","車両工学",2000,None,"枠組","自動車工学・設計",
     "燃費規制・EV航続距離延伸のための車体軽量化設計","車体骨格・サスペンション・シャシー設計",
     "強度・衝突安全性・コストのトレードオフをどう解くか？異材接合は？",
     "従来スチール一体設計","軽量化,マルチマテリアル,CFRP,高強度鋼,トポロジー最適化","lightweighting,multi-material,CFRP,ultra high strength steel,topology optimization",
     "active","secondary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0261306913009400",
     "欧米","high",
     r"比強度: $\sigma/\rho$ (MPa·cm$^3$/g). 軽量化指数: $LI = (\sigma_{ult}/\rho)^{2/3}/E^{1/3}$. 衝突吸収エネルギー: $E_{abs} = \int_0^{\delta} F d\delta$.",
     "url_present"),

    ("mech_b3_022","腐食防食工学","Corrosion and Corrosion Protection Engineering","",
     "金属の腐食機構(電気化学腐食・応力腐食割れ)を理解し被覆・犠牲陽極・電気防食等で腐食を抑制する技術体系。",
     "インフラ・海洋構造物の維持管理費削減とコスト対効果の高い防食設計を実現。",
     "機械工学","材料工学・防食",1960,None,"枠組","材料評価・インフラ管理",
     "金属構造物が腐食性環境(塩水・酸・高温)に曝露される設計","橋梁・パイプライン・船体・化学プラント",
     "環境・材料・応力の三角形腐食条件をどう評価するか？SCC感受性材料の選定は？",
     "定期塗装","腐食,防食,電気化学,SCC,カソード防食","corrosion,corrosion protection,SCC,cathodic protection,electrochemistry",
     "active","primary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0010938X14000067",
     "欧米","high",
     r"Butler-Volmer式: $i = i_0[\exp(\frac{\alpha_a F \eta}{RT}) - \exp(-\frac{\alpha_c F \eta}{RT})]$. 腐食速度: $CR = \frac{K M i_{corr}}{n \rho A}$ (mm/yr). タフェル勾配: $b = 2.303RT/(\alpha F)$.",
     "url_present"),

    ("mech_b3_023","制振鋼板","Damping Steel","",
     "鋼板の積層間に粘弾性樹脂を挟み込み振動エネルギーを熱に変換する制振材料。自動車・家電の騒音低減に利用。",
     "自動車エンジンカバー・オイルパンの制振化でNVHを5-10dB改善。",
     "機械工学","材料工学・制振",1980,None,"手法","NVH・音響設計",
     "鋼板部品の振動・騒音低減が必要な場合","自動車・家電・建築の制振パネル",
     "使用温度・周波数域での制振性能最適化は？成形性との両立は？",
     "制振塗料・リブ補剛","制振鋼板,拘束型制振,粘弾性材料,NVH","damping steel,constrained layer damping,viscoelastic,NVH",
     "active","secondary",80,8,
     "https://www.sciencedirect.com/science/article/pii/0022460X8690061X",
     "東アジア","high",
     r"複素弾性率: $E^* = E'(1 + i\eta)$ ($\eta$:損失係数). 制振効果: $\Delta_{dB} = 20\log_{10}\frac{1}{\eta_{bare}/\eta_{damped}}$. RKU法: $\eta_{sys} = \frac{E_c h_c^3 \eta_c + E_v h_v^3 \eta_v}{E_c h_c^3 + E_v h_v^3}$.",
     "url_present"),

    ("mech_b3_024","マイクロ波加熱加工","Microwave Processing","",
     "マイクロ波の誘電加熱を利用してセラミックス焼結・食品乾燥・化学反応を行う非従来加熱手法。内部加熱と選択加熱が特徴。",
     "セラミックス焼結エネルギーを従来比50-80%削減し製造コストを大幅低減。",
     "機械工学","熱処理・焼結工学",1975,None,"手法","特殊加熱・材料処理",
     "均一な内部加熱・選択加熱・短時間処理が必要な材料処理","セラミックス焼結・食品乾燥・廃棄物処理",
     "電磁場分布の均一化をどう確保するか？熱暴走のリスク管理は？",
     "従来電気炉加熱","マイクロ波加熱,セラミックス焼結,誘電加熱,選択加熱","microwave processing,microwave sintering,dielectric heating,selective heating",
     "active","primary",78,6,
     "https://www.sciencedirect.com/science/article/pii/S0955221911000550",
     "欧米","medium",
     r"吸収電力: $P_{abs} = \frac{1}{2}\omega\varepsilon_0 \varepsilon'' |E|^2$. 穿透深さ: $D = \frac{\lambda_0}{2\pi\sqrt{2\varepsilon'}}[\sqrt{1+(\varepsilon''/\varepsilon')^2}-1]^{-1/2}$. 反射係数: $\Gamma = (Z_s - Z_0)/(Z_s + Z_0)$.",
     "url_present"),

    ("mech_b3_025","医療用ロボット設計","Medical Robot Design","",
     "手術支援ロボット(da Vinci等)・リハビリロボット・カプセル内視鏡の力学設計・制御・安全認証の技術体系。",
     "ロボット支援手術で外科医の手ぶれを排除し微細縫合精度を向上,低侵襲手術を普及。",
     "機械工学","医療工学・ロボティクス",1995,None,"枠組","医療工学・ロボット",
     "手術支援・リハビリ・診断のための医療ロボット設計","腹腔鏡手術支援・脳神経外科ロボット",
     "インビボ環境での生体適合性・滅菌性をどう確保するか？FDA認証プロセスは？",
     "手術用器具","医療ロボット,手術支援,da Vinci,生体適合性,力制御","medical robot,surgical robot,da Vinci,haptic feedback,biocompatibility",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0736584506001688",
     "欧米","high",
     r"スケーリング比: $SR = \Delta x_{slave}/\Delta x_{master}$ (通常0.2-0.5倍). 力変換: $F_{haptic} = SR \cdot F_{tissue}$. 安全制約: $\|F_{tip}\| \leq F_{max,tissue}$.",
     "url_present"),

    ("mech_b3_026","炭素繊維強化ポリマー成形技術","CFRP Manufacturing Technology","",
     "プリプレグオートクレーブ・RTM・フィラメントワインディング等の製造工法でCFRP複合材部品を製造する技術体系。",
     "航空機機体重量の50%をCFRP化したBoeing 787で燃費20%改善を実現。",
     "機械工学","複合材製造",1970,None,"枠組","複合材料・航空宇宙製造",
     "高比強度・高比剛性が要求される軽量構造部品製造","航空機・宇宙機・風車ブレード・スポーツ用品",
     "積層構成(積層角・枚数)の最適化は？プリプレグの保管・使用期限管理は？",
     "金属板金製造","CFRP,プリプレグ,RTM,積層設計,オートクレーブ","CFRP,prepreg,RTM,autoclave,filament winding,composite manufacturing",
     "active","primary",85,8,
     "https://www.sciencedirect.com/science/article/pii/S1359835X12000619",
     "欧米","high",
     r"積層則: $[Q]_{ij} = Q_{ij}(\theta)$. ABD行列: $\begin{bmatrix}N\\M\end{bmatrix}=\begin{bmatrix}A&B\\B&D\end{bmatrix}\begin{bmatrix}\varepsilon^0\\\kappa\end{bmatrix}$. $A_{ij}=\sum_k Q_{ij}^{(k)}(z_k-z_{k-1})$.",
     "url_present"),

    ("mech_b3_027","有限体積法による熱流体解析","Finite Volume Method for Thermal-Fluid Analysis","FVM",
     "支配方程式を積分形で制御体積に適用しエネルギー・運動量・質量保存を数値的に解くCFDの標準手法。OpenFOAM等で実装。",
     "OpenFOAMの普及でCFD解析の民主化が進み中小企業での熱流体設計が可能に。",
     "機械工学","計算流体力学",1971,None,"手法","CFD・熱流体解析",
     "複雑形状の熱流体問題を数値解析する場合","熱交換器・冷却システム・燃焼器設計",
     "対流項の離散化スキームをどう選ぶか？圧力-速度カップリングの扱いは？",
     "有限要素法CFD","有限体積法,OpenFOAM,CFD,熱流体解析,離散化","FVM,finite volume method,OpenFOAM,CFD,pressure-velocity coupling",
     "active","primary",88,9,
     "https://www.sciencedirect.com/science/article/pii/0045793073900106",
     "欧米","high",
     r"FVM離散化: $\frac{\partial}{\partial t}\int_V \phi dV + \oint_S \phi \mathbf{u} \cdot d\mathbf{S} = \oint_S \Gamma \nabla\phi \cdot d\mathbf{S} + \int_V S_\phi dV$. SIMPLE法: $p' = p^* + p''$,$\mathbf{u}' = \mathbf{u}^* - \Delta t/\rho \nabla p''$.",
     "url_present"),

    ("mech_b3_028","ポリマーアクチュエータ","Polymer Actuator","EAP",
     "電場・光・熱・pH変化に応じて変形するポリマー材料(EAP: Electroactive Polymer)を用いた柔軟アクチュエータ技術。",
     "筋肉様の柔軟駆動で生体医療ロボット・ソフトロボティクスに新機能を付与。",
     "機械工学","ソフトロボティクス",1990,None,"手法","アクチュエータ・ロボット",
     "生体模倣・柔軟変形・軽量駆動が必要なロボット設計","人工筋肉・グリッパー・植込型医療デバイス",
     "出力密度と応答速度の向上は？水中動作での耐久性は？",
     "空圧アクチュエータ","ポリマーアクチュエータ,EAP,人工筋肉,ソフトロボティクス","EAP,polymer actuator,artificial muscle,soft robotics",
     "active","primary",78,5,
     "https://www.sciencedirect.com/science/article/pii/S0924424700004052",
     "欧米","high",
     r"誘電エラストマー変形: $\varepsilon_z = -p/Y_0 = -\varepsilon_0\varepsilon_r E^2/Y_0$ ($Y_0$:ヤング率). IPMC: $\kappa = \alpha V/d$ ($\alpha$:感度係数,$V$:印加電圧,$d$:膜厚). 力密度: $F/m \sim 0.1$-$1$ N/g.",
     "url_present"),

    ("mech_b3_029","ナノインデンテーション","Nanoindentation","",
     "ダイヤモンド圧子を材料表面にナノスケールで押し込み荷重-変位曲線から硬さ・弾性率を測定する微小機械試験法。",
     "薄膜・コーティング・微細組織の局所機械特性評価を可能にし材料開発を加速。",
     "機械工学","材料試験法",1992,None,"手法","材料試験・表面工学",
     "薄膜・バルク材の局所弾塑性特性を非破壊で評価する場合","コーティング膜・半導体・生体組織の力学評価",
     "Oliver-Pharr法の適用限界は？クリープ・ピラーダウンの補正は？",
     "引張試験・硬さ試験","ナノインデンテーション,硬さ測定,弾性率,Oliver-Pharr法","nanoindentation,hardness,elastic modulus,Oliver-Pharr method",
     "active","primary",85,9,
     "https://www.sciencedirect.com/science/article/pii/0022509692900263",
     "欧米","high",
     r"Oliver-Pharr: $E_r = \frac{\sqrt{\pi}}{2} \frac{S}{\sqrt{A_c}}$ ($S=dP/dh|_{unload}$:接触剛性,$A_c$:接触投影面積). $H = P_{max}/A_c$. $\frac{1}{E_r} = \frac{1-\nu^2}{E} + \frac{1-\nu_i^2}{E_i}$.",
     "url_present"),

    ("mech_b3_030","圧力容器設計","Pressure Vessel Design","",
     "ASME Sec.VIII・PD 5500等の規格に基づき内圧・外圧・熱応力・地震荷重に対する圧力容器の設計・検査を行う技術体系。",
     "石油化学・原子力プラントの安全設計を標準化し重大事故リスクを系統的に管理。",
     "機械工学","プラント機器設計",1914,None,"枠組","プラント・圧力装置",
     "化学・石油・原子力プラントの圧力保有機器設計","反応器・熱交換器・高圧配管・タンク設計",
     "設計圧力のマージンをどう設定するか？疲労解析による寿命は？",
     "経験的設計","圧力容器設計,ASME,疲労設計,腐食代","pressure vessel design,ASME,fatigue analysis,corrosion allowance",
     "active","primary",85,9,
     "https://www.asme.org/codes-standards/find-codes-standards/bpvc-viii-1",
     "欧米","high",
     r"内圧膜応力(薄肉球): $\sigma = pR/2t$. 厚肉(Lamé): $\sigma_\theta = \frac{p_i r_i^2}{r_o^2 - r_i^2}(1 + \frac{r_o^2}{r^2})$. 疲労設計S-N曲線: $S_m = \min(UTS/3.5, 2\sigma_y/3)$ (ASME).",
     "url_present"),

    ("mech_b3_031","弾塑性破壊力学","Elastic-Plastic Fracture Mechanics","EPFM",
     "大規模塑性変形域の破壊を扱うJ積分・CTOD基準に基づく破壊力学。高靭性材料・小型試験片の破壊評価に使用。",
     "圧力容器・パイプラインの欠陥許容評価(BS7910等)を可能にしインフラ安全管理を高度化。",
     "機械工学","破壊力学",1968,None,"理論","構造完全性評価",
     "降伏応力に近い応力条件での破壊評価・欠陥許容量評価","原子力圧力容器・石油パイプライン・橋梁鋼構造",
     "J積分とCTODの適用条件の違いは？ポップイン挙動の解釈は？",
     "線形弾性破壊力学(LEFM)","弾塑性破壊力学,J積分,CTOD,欠陥許容","EPFM,J-integral,CTOD,ductile fracture,flaw tolerance",
     "active","primary",85,8,
     "https://www.sciencedirect.com/science/article/pii/0013794468900014",
     "欧米","high",
     r"J積分: $J = \int_\Gamma (W n_1 - T_i \frac{\partial u_i}{\partial x_1}) d\Gamma$ (経路非依存). 破壊条件: $J \geq J_{Ic}$. J-M曲線: $J = J_0 + m_0 \sigma_0 \Delta a$ ($m_0 \approx 2$).",
     "url_present"),

    ("mech_b3_032","超精密位置決め","Ultra-Precision Positioning","",
     "ピエゾアクチュエータ・レーザー干渉計・アクティブ除振を組み合わせてサブナノメートル精度の位置決めを実現する技術。",
     "半導体露光装置(EUV)のウェーハステージにおける0.1nm級位置決め精度を実現。",
     "機械工学","精密工学",1980,None,"手法","精密機械・半導体製造",
     "nm以下の位置決め精度が必要な製造・計測システム","半導体露光装置・原子間力顕微鏡・精密工作機械",
     "熱変形・床振動・空気乱流の影響をどう遮断するか？ヒステリシス補償は？",
     "ボールねじ位置決め","超精密位置決め,ピエゾ,レーザー干渉計,除振","ultra-precision,piezo actuator,laser interferometry,vibration isolation",
     "active","primary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0141635900000301",
     "東アジア","high",
     r"ピエゾ変位: $\delta = d_{33} V$ ($d_{33}$:圧電定数 pm/V). ヒステリシス補償: $u_{inv} = h^{-1}(r)$ (Prandtl-Ishlinskii逆モデル). 分解能: $\delta_{min} = \sqrt{4k_BT R \Delta f} / G_{actuator}$.",
     "url_present"),

    ("mech_b3_033","燃料電池スタック設計","Fuel Cell Stack Design","",
     "MEA(膜電極接合体)・セパレータ・冷却プレートの集積設計とスタック内流量・温度分布均一化を実現する技術。",
     "FCEVの2050年普及に向けた高出力密度スタック設計の基盤技術。",
     "機械工学","エネルギー変換工学",1990,None,"枠組","エネルギー・自動車工学",
     "高出力密度・長寿命の燃料電池システム設計","FCV・定置型燃料電池・ドローン電源",
     "水管理(フラッディング・ドライアウト)と熱管理のバランスは？MEA耐久性は？",
     "バッテリー電源","燃料電池スタック,MEA,水管理,PEM","fuel cell stack,MEA,water management,PEMFC,thermal management",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0378775320312501",
     "東アジア","high",
     r"Butler-Volmer(FC): $i = i_0[\exp(\alpha_a F\eta/RT) - \exp(-\alpha_c F\eta/RT)]$. セル電圧: $V = E_{rev} - \eta_{act} - \eta_{ohm} - \eta_{conc}$. Nernst: $E = E^0 + \frac{RT}{2F}\ln\frac{p_{H_2}\sqrt{p_{O_2}}}{a_{H_2O}}$.",
     "url_present"),

    ("mech_b3_034","ロールフォーミング","Roll Forming","",
     "板材を複数対のロールで段階的に曲げ加工して長尺断面形状を高速連続製造するプロセス。鋼構造部材・自動車フレームに使用。",
     "建設用軽量形鋼の高速連続成形で従来プレス成形比3-5倍の生産性を実現。",
     "機械工学","塑性加工技術",1950,None,"手法","成形加工",
     "長尺一定断面形状の連続高速成形が必要な場合","建設用形鋼・自動車フレーム・屋根材",
     "フラワーパターン設計(段数・ロール形状)の最適化は？スプリングバック管理は？",
     "プレス曲げ加工","ロールフォーミング,冷間成形,形鋼製造,連続成形","roll forming,cold roll forming,section steel,continuous forming",
     "active","primary",80,8,
     "https://www.sciencedirect.com/science/article/pii/S0924013605009744",
     "欧米","high",
     r"スプリングバック角度: $\Delta\theta = \theta_{before} - \theta_{after} = \frac{M}{EI}\frac{L_{bend}}{3}$. 板厚変化: $t_{out} = t_{in}\sqrt{1 - (\varepsilon_l)^2}$. 成形力/ロール: $F \approx 2\sigma_y t w \varepsilon_{pl}$.",
     "url_present"),

    ("mech_b3_035","液体ロケットエンジン設計","Liquid Rocket Engine Design","LRE",
     "推進剤(液体酸素+液体水素等)の噴射・燃焼・冷却・ターボポンプ設計を一体化したロケットエンジン設計技術。",
     "SpaceX Raptonエンジン(FFSC方式)が比推力向上と再使用を同時実現し宇宙アクセスコストを激変。",
     "機械工学","推進工学",1940,None,"枠組","宇宙工学・推進",
     "宇宙打ち上げロケットの推進系設計","運搬ロケット主推進・月惑星探査機推進",
     "燃焼不安定性(高周波・低周波)の抑制手法は？再生冷却設計の熱計算は？",
     "固体ロケット","液体ロケットエンジン,燃焼不安定性,ターボポンプ,比推力","liquid rocket engine,combustion instability,turbopump,specific impulse",
     "active","primary",85,7,
     "https://www.sciencedirect.com/science/article/pii/S1270963813002009",
     "欧米","high",
     r"比推力: $I_{sp} = F/(\dot{m}g_0) = v_e/g_0$. ロケット推力: $F = \dot{m}v_e + (p_e - p_a)A_e$. 理想比推力: $I_{sp} = \frac{1}{g_0}\sqrt{\frac{2\gamma}{\gamma-1}RT_c[1-(p_e/p_c)^{(\gamma-1)/\gamma}]}$.",
     "url_present"),

    ("mech_b3_036","中国製造業2025とスマートファクトリー","China Manufacturing 2025 and Smart Factory Engineering","",
     "中国国務院が2015年に発布した製造業高度化戦略に基づくCPS(サイバーフィジカルシステム)型スマート工場の実装技術体系。",
     "中国製造業のデジタル化が10年で進展し世界の製造DX競争を加速。",
     "機械工学","製造システム工学",2015,None,"枠組","製造システム・産業政策",
     "大規模製造拠点のデジタル化・IoT化推進","電子機器・自動車・鉄鋼製造のスマート化",
     "中国版インダストリー4.0固有の実装課題は？地場OEMとの連携は？",
     "従来量産工場","中国製造2025,スマートファクトリー,CPS,製造DX","China Manufacturing 2025,smart factory,CPS,Industry 4.0,digital manufacturing",
     "active","secondary",80,7,
     "http://www.gov.cn/zhengce/content/2015-05/19/content_9784.htm",
     "東アジア","high",
     r"生産効率指標: $OEE = Availability \times Performance \times Quality$. デジタルツイン精度: $\epsilon = \|x_{real} - x_{twin}\|/\|x_{real}\|$. スマート工場KPI: $\text{Defect rate} < 100ppm$, $\text{OEE} > 85\%$.",
     "url_present"),

    ("mech_b3_037","流体包含構造物の連成振動","Fluid-Filled Structure Vibration","",
     "タンク・パイプライン・血管等の内部流体と外殻構造が連成して振動するFSI問題の解析手法。スロッシングを含む。",
     "液体燃料ロケットタンクのスロッシング制御が軌道投入精度に直結するため宇宙開発で重要。",
     "機械工学","構造動力学",1960,None,"手法","流体構造連成",
     "内部流体を持つ容器・管路・生体管の動的解析","燃料タンクスロッシング・水道管振動・動脈壁",
     "スロッシング固有モードをどう計算するか？TMD(同調質量ダンパー)設計は？",
     "空の容器解析","スロッシング,流体構造連成,タンク振動,FSI","sloshing,fluid-structure coupling,tank vibration,FSI",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0889974602001175",
     "欧米","high",
     r"スロッシング固有振動数: $\omega_n = \sqrt{g k_n \tanh(k_n h)}$ ($k_n = n\pi/L$,$h$:液深). TMD最適同調: $f_{TMD}/f_{primary} = 1/(1+\mu)$ ($\mu$:質量比). 渦流れ: $f = St \cdot U/D$.",
     "url_present"),

    ("mech_b3_038","バイオニックデザイン","Bionic Design","",
     "自然界の生物構造(ハチの巣・骨格・葉脈・貝殻)から着想を得て軽量・高強度・高機能の機械構造を設計するアプローチ。",
     "シロアリの巣の換気システムを模倣した建物HVAC設計でエネルギー消費を大幅削減。",
     "機械工学","設計工学",1960,None,"枠組","デザイン工学・バイオミメティクス",
     "自然界の最適化事例を工学設計に応用する場合","軽量構造設計・熱交換器・表面機能化",
     "生物の最適化と工学要件のスケール差をどう扱うか？製造可能性の確保は？",
     "慣用的形状設計","バイオニックデザイン,バイオミメティクス,生体模倣,自然インスパイア設計","bionic design,biomimetics,nature-inspired,bio-inspired engineering",
     "active","secondary",80,6,
     "https://www.sciencedirect.com/science/article/pii/S0264127521011242",
     "欧米","high",
     r"比強度最大化目標: $\max \sigma_{ult}/\rho$ s.t. $\rho < \rho_{max}$. トポロジー最適化の生物模倣: $\rho(x) = [E(x)/E_0]^{1/p}$ (SIMP法). ハニカム平均密度: $\rho^*/\rho_s = 2/\sqrt{3}(t/l)$.",
     "url_present"),

    ("mech_b3_039","高温超伝導応用機器","High-Temperature Superconductor Applications in Machines","HTS",
     "YBCO等のHTSコイルを電動機・発電機・送電ケーブルに適用して電気抵抗ゼロの超高効率電気機器を実現する技術。",
     "HTS発電機で従来比50%の小型軽量化と損失低減を実現し洋上風力・航空電動化を促進。",
     "機械工学","電気機械工学",2000,None,"手法","エネルギー変換・電動機械",
     "極めて高い電流密度・低損失が必要な電気機械設計","HTS電動機・磁気軸受・送電ケーブル",
     "77K冷却システムのコストと信頼性をどう確保するか？HTS線材の機械的制約は？",
     "銅線電動機","高温超伝導,HTS電動機,YBCO,液体窒素冷却","HTS motor,high-temperature superconductor,YBCO,cryogenic motor",
     "active","primary",78,5,
     "https://www.sciencedirect.com/science/article/pii/S0921453413001233",
     "欧米","high",
     r"HTS臨界電流密度: $J_c(B,T) = J_{c0}(1-T/T_c)^m (1-B/B_{c2})^n$. 電動機トルク: $T = k_T I_{sc}$. Bean臨界状態モデル: $\nabla \times B = \mu_0 J_c$.",
     "url_present"),

    ("mech_b3_040","プロセス強化","Process Intensification","PI",
     "反応・分離・熱移動等を統合・小型化することで単位操作を飛躍的に高効率化する化学工学・機械工学の設計哲学。マイクロリアクターを含む。",
     "マイクロリアクターで危険反応を連続安全処理し医薬中間体製造の安全性と生産性を同時向上。",
     "機械工学","プロセス工学",1983,None,"枠組","化学工学・製造プロセス",
     "反応・熱・物質移動の統合高効率化が必要なプロセス設計","マイクロ化学・医薬製造・石油精製",
     "スケールアップ時の熱・流体均一性をどう確保するか？マイクロリアクター目詰まり対策は？",
     "従来バッチ式プロセス","プロセス強化,マイクロリアクター,反応工学,分離統合","process intensification,microreactor,chemical engineering,continuous flow",
     "active","primary",80,6,
     "https://www.sciencedirect.com/science/article/pii/S0255270197001528",
     "欧米","high",
     r"Damköhler数: $Da = k\tau$($k$:速度定数,$\tau$:滞在時間). Bodenstein数: $Bo = uL/D_{ax}$ (プラグ流: $Bo \to \infty$). 体積比表面積: $a_v = 6/d$ (球充填). 伝熱強化比: $Nu_{micro}/Nu_{macro} = (D_{h,macro}/D_{h,micro})^{0.4}$.",
     "url_present"),

    ("mech_b3_041","宇宙機熱制御","Spacecraft Thermal Control","",
     "宇宙空間(-270℃〜+150℃の極端環境)で機器を動作温度範囲に保つ受動型・能動型熱制御技術の設計体系。",
     "James Webb宇宙望遠鏡の多層断熱材(MLI)とサンシールドで鏡を6Kに冷却し赤外線天文観測を実現。",
     "機械工学","宇宙機工学",1960,None,"枠組","宇宙工学・熱設計",
     "宇宙空間・惑星環境での機器温度管理","人工衛星・探査機・宇宙ステーションの熱設計",
     "電源変動・軌道変化による熱負荷変動をどう吸収するか？ヒートパイプの能力上限は？",
     "地上熱設計","宇宙機熱制御,ヒートパイプ,MLI,放熱","spacecraft thermal control,heat pipe,MLI,radiator,cryogenic",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0094576510001706",
     "欧米","high",
     r"放射熱: $Q_{rad} = \varepsilon \sigma A T^4$. 宇宙環境平衡温度: $T_{eq} = [(\alpha/\varepsilon)(1-A_g)S/4\sigma]^{1/4}$ ($A_g$:アルベド,$S$:太陽定数). MLI有効放射率: $\varepsilon_{eff} = 1/[(n+1)(2/\varepsilon_s - 1)]$.",
     "url_present"),

    ("mech_b3_042","弾道衝撃設計","Ballistic Impact Design","",
     "高速飛翔体との衝突時のエネルギー吸収・貫通防止を目的とした防護構造の設計技術。セラミック・複合材・金属の多層設計。",
     "ボディアーマー・装甲車両の軽量高性能防弾設計で人員保護と車両機動性を両立。",
     "機械工学","衝撃・爆発工学",1970,None,"手法","防護工学",
     "弾道・爆破・高速衝撃への耐性が必要な構造設計","防弾ベスト・装甲車・宇宙機微小隕石防護",
     "陶磁器/繊維/金属の最適積層順をどう決定するか？試験標準化は？",
     "均一金属板防護","弾道衝撃,防護構造,セラミック装甲,エネルギー吸収","ballistic impact,armor design,ceramic composite,energy absorption",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S0734743X09000906",
     "欧米","high",
     r"貫通速度(Kerry): $V_{50} = \sqrt{2E_{abs}/(m_{projectile})}$. 変形仕事: $W = \int F dx$. 比エネルギー吸収: $SEA = E_{abs}/m_{armor}$ (J/kg). ダメージ伝播: Hugoniot: $U_s = c_0 + s u_p$.",
     "url_present"),

    ("mech_b3_043","エンジン燃焼診断","Engine Combustion Diagnostics","",
     "光学エンジン・筒内圧センサ・エミッション分析を用いてエンジン内の燃焼過程をリアルタイムで診断・制御する技術。",
     "筒内圧センサベースの燃焼制御で気筒間ばらつきを排除しエンジン効率・排気を最適化。",
     "機械工学","内燃機関工学",1970,None,"手法","エンジン・燃焼制御",
     "エンジン燃焼最適化・異常燃焼検知・エミッション低減","ガソリン・ディーゼルエンジン開発・制御",
     "筒内圧センサのコスト・耐久性は量産に適用可能か？AIベース診断の精度は？",
     "従来キャブレター経験調整","燃焼診断,筒内圧,IMEP,ノッキング検出","combustion diagnostics,in-cylinder pressure,IMEP,knock detection",
     "active","primary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0376042106000194",
     "欧米","high",
     r"IMEP: $IMEP = \frac{1}{V_d}\oint p \, dV$. 熱発生率(HRR): $\frac{dQ_b}{d\theta} = \frac{\gamma}{\gamma-1}p\frac{dV}{d\theta} + \frac{1}{\gamma-1}V\frac{dp}{d\theta}$. ノック指数: $KI = \int_{SOC}^{EKW} |d^2p/d\theta^2| d\theta$.",
     "url_present"),

    ("mech_b3_044","ウィンドエンジニアリング","Wind Engineering","",
     "建物・橋梁・風力発電機への風荷重・風圧・空力弾性の解析と風洞試験による設計検証を行う工学分野。",
     "タコマナローズ橋崩壊(1940)教訓から空力弾性設計が義務化され大規模吊橋の安全確保に寄与。",
     "機械工学","風工学・構造工学",1950,None,"枠組","構造工学・空力設計",
     "風荷重を受ける建物・橋梁・風力発電機の設計","超高層建物・長大橋・沿岸構造物の風設計",
     "フラッターの臨界風速をどう予測するか？複雑地形での乱流特性評価は？",
     "静的風圧設計","風工学,フラッター,空力弾性,风洞試験","wind engineering,flutter,aeroelastic,wind tunnel,galloping",
     "active","primary",82,8,
     "https://www.sciencedirect.com/science/article/pii/S0167610506001547",
     "欧米","high",
     r"空力係数: $C_D = F_D/(\frac{1}{2}\rho U^2 A)$. フラッター方程式(2-DOF): $[M]\ddot{q}+[C]\dot{q}+[K]q = \{F_{aero}(q,\dot{q})\}$. Scruton数: $Sc = m/(2\rho D^2)$ (渦励振感受性指標).",
     "url_present"),

    ("mech_b3_045","光弾性法","Photoelasticity","",
     "光学的に複屈折する透明材料に荷重をかけ偏光の干渉縞パターンから応力分布を可視化する実験応力解析法。",
     "FEM普及以前に機械部品の応力集中をビジュアルに可視化し設計改善に貢献した先駆的手法。",
     "機械工学","実験応力解析",1850,None,"手法","応力解析・実験力学",
     "複雑形状部品の応力集中・主応力方向の可視化","ギア・フック・タービンブレードの応力分布確認",
     "三次元体の応力分析をどう実施するか？FEMとの比較検証は？",
     "FEM数値解析","光弾性,等色線,等傾線,応力可視化","photoelasticity,isochromatic,isoclinic,stress visualization",
     "active","primary",80,8,
     "https://www.sciencedirect.com/science/article/pii/S0143816607000759",
     "欧米","high",
     r"縞次数: $N = \frac{(\sigma_1-\sigma_2)t}{f_\sigma}$ ($f_\sigma$:材料縞感度). 主応力差: $\sigma_1-\sigma_2 = Nf_\sigma/t$. 縞感度: $f_\sigma = \lambda/(2C)$ ($C$:光弾性定数).",
     "url_present"),

    ("mech_b3_046","コンプライアントメカニズム","Compliant Mechanism","",
     "ヒンジ・ピン等の剛性継手を用いず弾性変形によって力・変位・運動を伝達する柔軟構造機構の設計手法。",
     "MEMS・医療デバイス・精密メカニズムで組立工程削減と高再現性の運動伝達を実現。",
     "機械工学","機構設計",1990,None,"枠組","機構学・精密工学",
     "ヒンジ不要の一体成形機構設計が必要な場合","MEMSスイッチ・手術用器具・光学調整機構",
     "疲労寿命(繰返し弾性変形)をどう確保するか？位置決め精度の限界は？",
     "剛体リンク機構","コンプライアントメカニズム,柔軟構造,トポロジー最適化,弾性変形","compliant mechanism,flexible structure,MEMS,topology optimization",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/S0094114X97000044",
     "欧米","high",
     r"疑似剛体モデル: $K_{eff} = K_\theta \cdot \gamma$ ($\gamma$:PRBM係数$\approx 0.85$). 変形エネルギー: $U = \int_0^l \frac{M^2}{2EI}ds$. トポロジー最適化目標: $\min |\mathbf{u}_{out}^T \mathbf{k}_{out} \mathbf{u}_{out}|$.",
     "url_present"),

    ("mech_b3_047","摩擦撹拌点接合","Friction Stir Spot Welding","FSSW",
     "回転工具を重ね合わせた板材に打ち込み,摩擦熱と塑性流動で固相接合する点接合手法。アルミ×異材接合に対応。",
     "アルミ車体パネルのスポット溶接代替としてFSSWが採用され異種材接合の強度・外観を両立。",
     "機械工学","接合技術",2000,None,"手法","接合・製造工学",
     "アルミや異種金属の高品質点接合が必要な場合","自動車アルミパネル・航空機外板・電池パック",
     "ツール引き抜きキーホールを除去するスリップリフロー対策は？接合強度の再現性管理は？",
     "抵抗スポット溶接","FSSW,摩擦撹拌点接合,アルミ接合,固相接合","FSSW,friction stir spot welding,aluminum joining,solid state welding",
     "active","primary",80,7,
     "https://www.sciencedirect.com/science/article/pii/S1359646204000247",
     "東アジア","high",
     r"接合条件: $Q_{friction} = \mu P \omega r$. せん断強度: $\tau_{FSS} = F_{lap}/A_{bond}$. ナゲット半径: $r_n = f(\omega, P, t_{dwell})$. 材料流動: $Pe = v \cdot l / D_{thermal}$.",
     "url_present"),

    ("mech_b3_048","産業用メタバース応用","Industrial Metaverse Applications","",
     "XR(AR/VR/MR)・デジタルツイン・AIを統合したバーチャル製造・訓練・遠隔協業の工学プラットフォーム。",
     "Siemens・PTC等のIndustrial Metaverseが工場設計・保守訓練の効率を大幅向上。",
     "機械工学","製造DX",2020,None,"枠組","製造システム・デジタル化",
     "製造プロセスの仮想化・遠隔協業・技能訓練が必要な場合","工場レイアウト設計・設備保守・技能伝承",
     "デジタルと物理の同期精度をどう確保するか？サイバーセキュリティ対策は？",
     "物理現地訓練","産業メタバース,デジタルツイン,XR,遠隔保守","industrial metaverse,digital twin,XR,remote maintenance,immersive manufacturing",
     "active","secondary",78,4,
     "https://www.siemens.com/global/en/home/company/fairs-events/hannover-messe.html",
     "欧米","medium",
     r"フレームレート: $FPS \geq 90$ (VR酔い防止). ポーズ予測: $\hat{q}(t+\Delta t) = q(t) + \dot{q}(t)\Delta t + \frac{1}{2}\ddot{q}(t)\Delta t^2$. デジタルツイン同期: $\epsilon = \|x_{real}(t)-x_{twin}(t)\| < 0.1mm$.",
     "url_present"),

    ("mech_b3_049","複合材料の非線形解析","Nonlinear Analysis of Composite Materials","",
     "FRP複合材の繊維破断・マトリックスき裂・層間はく離の進展を連続損傷力学(CDM)や有限要素法で解析する手法。",
     "複合材翼構造の鳥衝突衝撃後の残留強度を予測し設計の安全余裕を定量評価。",
     "機械工学","複合材料力学",1985,None,"手法","複合材料・破壊力学",
     "積層複合材の損傷・破壊進展を詳細に評価する必要がある場合","航空機翼・風車ブレード・圧力容器",
     "損傷変数の進展則とCZM(コヒーシブゾーン)パラメータの同定は？",
     "均質材料の非線形解析","複合材損傷,CDM,層間はく離,コヒーシブゾーン","composite damage,CDM,delamination,cohesive zone model",
     "active","primary",82,7,
     "https://www.sciencedirect.com/science/article/pii/0266353885900042",
     "欧米","high",
     r"CDM損傷変数: $\bar{\sigma} = \sigma/(1-D)$ ($D$:損傷変数). Hashin基準: $F_f^T = (\sigma_{11}/X_T)^2 + (\tau_{12}/S_L)^2 \geq 1$. CZMトラクション: $T = K \cdot \delta \cdot (1-D)$.",
     "url_present"),

    ("mech_b3_050","リープフロッグ型生産革新","Leapfrog Manufacturing Innovation","",
     "後発工業国が既存技術段階を飛び越えデジタル・ロボット化で一気に先端製造水準に到達する工業化戦略。バングラデシュ・インドネシア等に適用。",
     "モバイル決済でATMを飛び越えた金融インクルージョンと同様に製造分野での後発優位を実証。",
     "機械工学","製造戦略・産業政策",2015,None,"枠組","製造戦略・開発途上国工業化",
     "新興国における製造能力の急速構築と産業基盤形成","バングラデシュ縫製業・ベトナム電子製造・インドネシア自動車",
     "技術移転と国内産業育成のバランスをどう取るか？GVC(グローバルバリューチェーン)統合は？",
     "従来的段階的工業化","リープフロッグ,後発優位,製造革新,新興国工業化","leapfrog,manufacturing innovation,emerging market,GVC,technology transfer",
     "active","secondary",75,5,
     "https://www.unido.org/sites/default/files/2015-09/IDR2016_FULL_REPORT_0.pdf",
     "グローバルサウス","medium",
     r"後発優位指数: $LLA = (MFP_{gap} \times Absorptive\_capacity) / Entry\_barriers$. GVC参加度: $IV_{share} = \text{Foreign VA in exports}/\text{Total exports}$. 産業高度化速度: $dQ/dt = \beta \cdot Tech\_transfer - \gamma \cdot Barriers$.",
     "url_present"),
]

if __name__ == "__main__":
    ins, sk = insert_records(records)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Inserted: {ins}, Skipped: {sk}")
    print(f"Total: {total}")
