#!/usr/bin/env python3
"""CS/情報工学 Batch 1: +50件 (アルゴリズム・データ構造・分散システム)"""
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
("cs_b1_001","二分探索木","Binary Search Tree","BST",
 "各ノードの左子が親より小さく右子が親より大きい性質を持つ木構造。平均O(log n)の検索・挿入・削除を実現し、データベースインデックスや優先度管理に使用される。",
 "データベースインデックス・辞書・集合の実装基盤。整列済みデータへの効率的アクセスを実現。","アルゴリズム・データ構造","古典データ構造",1960,None,
 "データ構造","データベース・コンパイラ・OS","動的データで頻繁な検索・挿入・削除","順序付き集合の管理",
 "平均と最悪計算量の差はなぜ生じるか","ハッシュテーブル（無順序・O(1)平均）",
 "二分探索木,BST,木構造,データ構造,アルゴリズム","binary search tree,BST,tree,data structure,algorithm",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Binary_search_tree","Western_Europe",90,
 "search: T(n)=O(log n) avg, O(n) worst; height-balanced: T=O(log n)","url_present"),

("cs_b1_002","AVL木","AVL Tree","AVL Tree",
 "左右部分木の高さ差を1以下に保つ自己平衡二分探索木。挿入・削除後に回転操作でバランスを回復し、最悪O(log n)の操作を保証する。",
 "データベースエンジン・コンパイラシンボルテーブルで使用。最悪ケースの高速検索を保証する最初の平衡木。","アルゴリズム・データ構造","古典データ構造",1962,None,
 "データ構造","データベース・コンパイラ","頻繁な検索・稀な挿入削除","最悪O(log n)保証が必要な場合",
 "回転操作でどのように平衡を回復するか","赤黒木（挿入削除に有利）",
 "AVL木,平衡二分木,自己平衡,回転,データ構造","AVL tree,balanced BST,self-balancing,rotation,data structure",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/AVL_tree","Soviet_Union",90,
 "balance factor = h(left) - h(right) ∈ {-1,0,1}; rotation restores invariant","url_present"),

("cs_b1_003","赤黒木","Red-Black Tree","Red-Black Tree",
 "各ノードに赤か黒の色を割り当て、5つの色制約により高さをO(log n)に保つ自己平衡二分探索木。Linux カーネルのスケジューラやJavaのTreeMapで使用。",
 "実用的な平衡木の標準実装。C++ STL map/set・Java TreeMap・Linux CFSスケジューラの内部実装。","アルゴリズム・データ構造","古典データ構造",1972,None,
 "データ構造","OS・標準ライブラリ・データベース","挿入削除が頻繁な順序付き辞書","挿入削除と検索のバランスが必要な場合",
 "AVL木と比べて挿入削除の定数倍はどう違うか","AVL木・B木",
 "赤黒木,自己平衡木,Linux,データ構造,STL","red-black tree,balanced BST,Linux,data structure,STL",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Red%E2%80%93black_tree","Germany",90,
 "Black-height property: all paths root→leaf have equal black nodes; h ≤ 2log₂(n+1)","url_present"),

("cs_b1_004","ヒープ","Heap Data Structure","Binary Heap",
 "完全二分木の形を持ち、親が子以上（最大ヒープ）または以下（最小ヒープ）の半順序関係を満たすデータ構造。優先度付きキューの標準実装で挿入・最大値取得がO(log n)。",
 "ダイクストラ法・プリム法・ヒープソートの基盤。OS タスクスケジューラ・イベントシミュレーションの優先度管理に使用。","アルゴリズム・データ構造","古典データ構造",1964,None,
 "データ構造","グラフアルゴリズム・OS・シミュレーション","動的な最大・最小値アクセスが必要","優先度付きキューの実装",
 "配列で木を表現することでキャッシュ効率をどう高めるか","順序付き配列（O(log n)挿入O(1)最大）",
 "ヒープ,優先度キュー,ヒープソート,データ構造","heap,priority queue,heapsort,data structure",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Heap_(data_structure)","North_America",90,
 "parent(i)=⌊i/2⌋; insert/delete O(log n); heapify O(n); heapsort O(n log n)","url_present"),

("cs_b1_005","ハッシュテーブル","Hash Table","Hash Table",
 "キーをハッシュ関数で配列インデックスに変換し、平均O(1)の検索・挿入・削除を実現するデータ構造。衝突解決にチェイン法またはオープンアドレス法を使用。",
 "プログラミング言語の辞書・データベースのバッファプール・コンパイラのシンボルテーブルで普遍的に使用。","アルゴリズム・データ構造","古典データ構造",1953,None,
 "データ構造","データベース・言語処理系・OS","キーによる高速アクセス","順序不要で平均O(1)アクセスが必要な場合",
 "負荷率が増加するとどの時点でパフォーマンスが劣化するか","二分探索木（有序・O(log n)）",
 "ハッシュテーブル,ハッシュ関数,衝突解決,辞書","hash table,hash function,collision,dictionary",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Hash_table","North_America",90,
 "load factor α=n/m; chain: E[search]=1+α/2; open address: 1/(1-α)","url_present"),

("cs_b1_006","グラフアルゴリズム — 幅優先探索","Breadth-First Search","BFS",
 "グラフをキューを用いて始点から近い頂点順に探索するアルゴリズム。最短ホップ経路・連結成分・二部グラフ判定などに使用。時間計算量O(V+E)。",
 "ソーシャルネットワーク解析・ルーティングプロトコル・迷路探索・パズルAIの基盤アルゴリズム。","アルゴリズム・データ構造","グラフアルゴリズム",1959,None,
 "探索アルゴリズム","グラフ問題・ネットワーク経路・AI","重み無しグラフの最短経路","層ごとに最短距離を求める場合",
 "DFSとBFSはどのような問題でそれぞれ優位か","深さ優先探索（DFS）・ダイクストラ法",
 "幅優先探索,BFS,グラフ,最短経路,アルゴリズム","breadth-first search,BFS,graph,shortest path,algorithm",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Breadth-first_search","North_America",90,
 "T=O(V+E); space O(V); shortest hop distance d(s,v) correctly computed","url_present"),

("cs_b1_007","ダイクストラ法","Dijkstra's Algorithm","Dijkstra's Shortest Path",
 "非負重み付きグラフの単一始点最短経路を優先度付きキューを用いて効率的に求めるアルゴリズム。ナビゲーション・ネットワークルーティング・GISに使用される。",
 "カーナビ・OSPFルーティングプロトコル・ゲームAIのパス探索に使用。最短経路問題の実用的標準解法。","アルゴリズム・データ構造","グラフアルゴリズム",1956,None,
 "最短経路アルゴリズム","ネットワーク・地図・ゲームAI","非負重み付きグラフ","単一始点全点最短経路が必要な場合",
 "負重みがある場合なぜダイクストラ法は失敗するか","ベルマン-フォード法・A*アルゴリズム",
 "ダイクストラ法,最短経路,グラフ,ナビゲーション","Dijkstra,shortest path,graph,navigation",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm","Netherlands",90,
 "T=O((V+E)log V) with min-heap; d[v] = min over all paths from s to v","url_present"),

("cs_b1_008","動的計画法","Dynamic Programming","Dynamic Programming",
 "問題を重複する部分問題に分解し、メモ化または表形式で計算結果を再利用して全体を効率的に解く手法。最適部分構造と重複部分問題の二性質を持つ問題に適用できる。",
 "生物情報学のDNAアラインメント・自然言語処理・資源配分最適化・強化学習の価値関数計算の基盤手法。","アルゴリズム・データ構造","アルゴリズム設計パラダイム",1953,None,
 "アルゴリズム設計","最適化・文字列・グラフ問題","最適部分構造・重複部分問題","再帰的な最適化問題を多項式時間で解く場合",
 "メモ化（トップダウン）とボトムアップDPはどう使い分けるか","貪欲法・分割統治法",
 "動的計画法,DP,最適化,メモ化,アルゴリズム","dynamic programming,DP,optimization,memoization,algorithm",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Dynamic_programming","North_America",90,
 "Bellman equation: V*(s)=max_a[R(s,a)+γΣP(s'|s,a)V*(s')]; DP recurrence","url_present"),

("cs_b1_009","クイックソート","Quicksort","Quicksort",
 "ピボット要素を選び配列を小・大に分割して再帰的に整列する比較ベースの整列アルゴリズム。平均O(n log n)・最悪O(n²)。乱択ピボットで実用的に最速クラス。",
 "実用上最速クラスの汎用ソート。C標準ライブラリqsort・Java Arrays.sort（基本型）の実装ベース。","アルゴリズム・データ構造","アルゴリズム設計パラダイム",1959,None,
 "整列アルゴリズム","汎用ソート・データ前処理","インプレースソートが必要","大規模データの汎用ソート",
 "なぜ最悪ケースがO(n²)でも実用上最速なのか","マージソート（最悪O(n log n)・安定）",
 "クイックソート,ソート,分割統治,アルゴリズム","quicksort,sort,divide and conquer,algorithm",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Quicksort","United_Kingdom",90,
 "avg T=O(n log n); worst T=O(n²); randomized pivot achieves O(n log n) w.h.p.","url_present"),

("cs_b1_010","マージソート","Merge Sort","Merge Sort",
 "配列を半分に分割して再帰的にソートし、ソート済み配列をマージする安定ソートアルゴリズム。最悪O(n log n)・安定・外部ソートに適する。",
 "外部ソート・並列ソート・リンクリストソートの標準手法。Java Arrays.sort（オブジェクト型）の実装ベース。","アルゴリズム・データ構造","アルゴリズム設計パラダイム",1945,None,
 "整列アルゴリズム","外部ソート・並列処理","安定ソートが必要・リンクリスト","最悪O(n log n)保証が必要な場合",
 "なぜマージソートは外部ソートに適しているか","クイックソート（インプレース・不安定）",
 "マージソート,安定ソート,分割統治,外部ソート","merge sort,stable sort,divide and conquer,external sort",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Merge_sort","North_America",90,
 "T(n)=2T(n/2)+O(n) → T(n)=O(n log n); space O(n)","url_present"),

("cs_b1_011","B木・B+木","B-Tree / B+ Tree","B-Tree",
 "ディスクI/Oを最小化するために設計された多分岐平衡探索木。ノードが複数のキーを持ち、ページサイズに整合した設計でデータベースインデックスの標準実装となっている。",
 "MySQL InnoDB・PostgreSQL・Oracle全主要RDBMSのインデックスエンジン。ファイルシステム（ext4・NTFS）のディレクトリ管理にも使用。","アルゴリズム・データ構造","データベース構造",1970,None,
 "データ構造","データベースインデックス・ファイルシステム","ディスクブロック単位のI/Oが支配的","大規模データの範囲検索が必要な場合",
 "ページサイズに合わせた分岐数はどう決定するか","ハッシュインデックス（範囲検索不可）",
 "B木,B+木,データベース,インデックス,ディスクI/O","B-tree,B+ tree,database,index,disk I/O",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/B-tree","North_America",90,
 "height h=O(log_t n) where t=min degree; search O(log n); all leaves linked in B+","url_present"),

("cs_b1_012","トライ木","Trie","Prefix Tree",
 "文字列を文字単位で共有プレフィックスによって木に格納するデータ構造。キーワード検索・オートコンプリート・IP アドレスルーティングテーブルに使用される。",
 "検索エンジンの自動補完・DNSルーティング・形態素解析辞書の実装。文字列集合のO(m)検索（m=文字列長）。","アルゴリズム・データ構造","文字列データ構造",1959,None,
 "データ構造","テキスト検索・ルーティング・辞書","プレフィックス共有が多い文字列集合","高速プレフィックス検索が必要な場合",
 "Patricia木やDAWGはTrieをどのように圧縮するか","ハッシュマップによる辞書（プレフィックス検索が非効率）",
 "トライ木,プレフィックス木,文字列,辞書,オートコンプリート","trie,prefix tree,string,dictionary,autocomplete",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Trie","North_America",90,
 "search/insert O(m) where m=key length; space O(ALPHABET_SIZE × m × n)","url_present"),

("cs_b1_013","Union-Find (素集合データ構造)","Union-Find / Disjoint Set Union","DSU",
 "複数の素集合を管理し、集合の合併（Union）と要素が属する集合の検索（Find）を効率的に行うデータ構造。経路圧縮とランク結合でほぼO(α(n))（逆アッカーマン関数）を達成。",
 "クラスカル法の最小全域木・ネットワーク接続性判定・画像の連結成分ラベリングに使用。","アルゴリズム・データ構造","古典データ構造",1964,None,
 "データ構造","グラフアルゴリズム・ネットワーク","動的連結性問題","連結性を高速に管理する場合",
 "経路圧縮とランク結合を組み合わせるとなぜほぼO(1)になるか","隣接リストによる連結性判定（O(n+m)）",
 "Union-Find,素集合,経路圧縮,グラフ,連結性","union-find,disjoint set,path compression,graph,connectivity",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Disjoint-set_data_structure","North_America",90,
 "amortized O(α(n)) per operation with path compression + union by rank","url_present"),

("cs_b1_014","最小全域木 — クラスカル法","Minimum Spanning Tree — Kruskal's Algorithm","Kruskal's MST",
 "辺を重み昇順にソートしてUnion-Findで閉路を避けながら辺を追加する最小全域木アルゴリズム。疎なグラフに有利でO(E log E)。",
 "電力網設計・通信ネットワーク配線・クラスタリングアルゴリズムの基盤。","アルゴリズム・データ構造","グラフアルゴリズム",1956,None,
 "グラフアルゴリズム","ネットワーク設計・クラスタリング","無向重み付きグラフのMST","疎なグラフの最小全域木",
 "プリム法とクラスカル法はどちらが密なグラフに有利か","プリム法（密なグラフに有利）",
 "最小全域木,クラスカル,グラフアルゴリズム,ネットワーク","minimum spanning tree,Kruskal,graph algorithm,network",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Kruskal%27s_algorithm","North_America",90,
 "T=O(E log E); greedy: add min-weight edge not forming cycle using DSU","url_present"),

("cs_b1_015","フローアルゴリズム — Ford-Fulkerson法","Maximum Flow — Ford-Fulkerson Method","Max Flow",
 "増加路を反復的に見つけて最大流を計算するアルゴリズムの枠組み。Edmonds-Karpは幅優先探索による増加路選択でO(VE²)を保証する。最小カット最大流定理と直結。",
 "交通・物流ネットワーク設計・二部マッチング・画像セグメンテーション・コンパイラのデータフロー解析に使用。","アルゴリズム・データ構造","グラフアルゴリズム",1956,None,
 "グラフアルゴリズム","ネットワーク流・マッチング・排除問題","容量付きフローネットワーク","ネットワークの最大輸送量を求める場合",
 "最小カット最大流定理はなぜ成立するか","線形計画法による最大流",
 "最大流,Ford-Fulkerson,最小カット,ネットワーク流","maximum flow,Ford-Fulkerson,min cut,network flow",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Ford%E2%80%93Fulkerson_algorithm","North_America",90,
 "max-flow=min-cut (max-flow min-cut theorem); Edmonds-Karp: O(VE²)","url_present"),

("cs_b1_016","Paxosアルゴリズム","Paxos Consensus Algorithm","Paxos",
 "分散システムにおいてネットワーク障害やサーバ障害の存在下でも合意（コンセンサス）を達成するプロトコル。Proposer・Acceptor・Learnerの三役割からなる2フェーズ方式。",
 "Google Chubby・Apache Zookeeper・分散データベースのコンセンサス基盤。分散合意の理論的礎。","計算機科学","分散システム",1989,None,
 "分散アルゴリズム","分散ストレージ・ロック管理・データベース複製","障害許容分散合意が必要","非同期ネットワークで合意が必要な場合",
 "FLPの不可能性定理とどう折り合いをつけるか","Raftアルゴリズム（理解容易）",
 "Paxos,分散合意,フォールトトレランス,分散システム","Paxos,distributed consensus,fault tolerance,distributed systems",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Paxos_(computer_science)","North_America",90,
 "2-phase: Prepare(n)→Promise; Accept(n,v)→Accepted; quorum ⌈(N+1)/2⌉","url_present"),

("cs_b1_017","Raftコンセンサスアルゴリズム","Raft Consensus Algorithm","Raft",
 "Paxosより理解しやすいように設計された分散合意アルゴリズム。リーダー選出・ログ複製・安全性の3部から成り、強いリーダー一元管理で実装の明快さを実現。",
 "etcd（Kubernetes）・CockroachDB・TiKVなどクラウドネイティブインフラの合意エンジン。Paxosを実用的に置き換える標準。","計算機科学","分散システム",2013,None,
 "分散アルゴリズム","分散ストレージ・コンテナオーケストレーション","障害許容合意・可理解性重視","Paxosの複雑さを避けたい場合",
 "Paxosと比較してRaftはどの点で実装が容易か","Paxos・Multi-Paxos",
 "Raft,分散合意,リーダー選出,ログ複製,Kubernetes","Raft,distributed consensus,leader election,log replication,Kubernetes",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Raft_(algorithm)","North_America",90,
 "leader elected by majority; log entry committed when replicated on majority; term number","url_present"),

("cs_b1_018","CAP定理","CAP Theorem","CAP Theorem",
 "分散システムは一貫性・可用性・分断耐性の3特性を同時に全て満たすことはできず、分断発生時はCとAのどちらかを犠牲にしなければならないというブルワーの定理。",
 "NoSQLデータベース設計（CP系:HBase・MongoDB / AP系:Cassandra・DynamoDB）の理論的根拠。システム設計の基本トレードオフを整理。","計算機科学","分散システム",2000,None,
 "理論","分散データベース設計・マイクロサービス","ネットワーク分断が発生しうる分散システム","一貫性と可用性のトレードオフを設計判断する場合",
 "PACELC定理はCAP定理をどのように拡張するか","ACID特性・BASE特性・PACELC定理",
 "CAP定理,分散システム,一貫性,可用性,分断耐性","CAP theorem,distributed systems,consistency,availability,partition tolerance",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/CAP_theorem","North_America",90,
 "CAP: ∀ distributed system, only 2 of {C,A,P} simultaneously achievable","url_present"),

("cs_b1_019","MapReduceパラダイム","MapReduce Programming Model","MapReduce",
 "大規模データを並列処理するプログラミングモデル。Map関数でキー値ペアに変換し、Reduceで集約する。Googleが提案し、Hadoopで広く実装された分散バッチ処理の基盤。",
 "Web規模のデータ処理（ログ解析・インデックス構築・PageRank計算）の標準パラダイム。Hadoop MapReduceとして産業界に普及。","計算機科学","分散システム",2004,None,
 "プログラミングモデル","大規模バッチ処理・ログ解析","大規模構造化・半構造化データ処理","テラバイト規模のバッチ処理",
 "なぜMapReduceはStormやSparkに置き換えられつつあるか","Apache Spark（インメモリ・ストリーム）",
 "MapReduce,Hadoop,分散処理,大規模データ,並列計算","MapReduce,Hadoop,distributed computing,big data,parallel processing",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/MapReduce","North_America",90,
 "Map: (k1,v1)→list(k2,v2); Reduce: (k2,list(v2))→list(v3); shuffle+sort between","url_present"),

("cs_b1_020","LSMツリー","Log-Structured Merge Tree","LSM-Tree",
 "書き込みを一旦インメモリバッファ（MemTable）に集積してSSTファイルに順次フラッシュし、バックグラウンドでコンパクションするストレージエンジン構造。書き込み集約的ワークロードに優れる。",
 "RocksDB・LevelDB・Cassandra・HBaseのストレージエンジン。ランダム書き込みをシーケンシャル書き込みに変換して書き込みスループットを最大化。","計算機科学","データベースシステム",1996,None,
 "ストレージエンジン","NoSQLデータベース・時系列DB・ログDB","書き込み集約的ワークロード","高スループット書き込みが必要な場合",
 "読み取り増幅と書き込み増幅のトレードオフをどう調整するか","B+木ストレージエンジン（読み取り有利）",
 "LSMツリー,RocksDB,NoSQL,ストレージエンジン,書き込み最適化","LSM-tree,RocksDB,NoSQL,storage engine,write optimization",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Log-structured_merge-tree","North_America",90,
 "write amp ∝ levels L; read amp ∝ L; space amp ∝ size ratio r between levels","url_present"),

("cs_b1_021","仮想記憶とページング","Virtual Memory and Paging","Virtual Memory",
 "プロセスに連続した仮想アドレス空間を提供し、ページング（固定サイズブロック単位の管理）とページテーブルによってハードウェアで物理メモリとマッピングする機構。",
 "現代OSの基盤技術。プロセス間分離・メモリ保護・スワッピングを実現し、複数プロセスの安全な同時実行を可能にする。","計算機科学","オペレーティングシステム",1962,None,
 "OS機構","OS・ランタイム・ハイパーバイザ","マルチプロセス環境","プロセス間メモリ分離・物理メモリ超えのアドレス空間が必要な場合",
 "TLBミスはどのように性能に影響するか","セグメンテーション（可変長・歴史的）",
 "仮想記憶,ページング,TLB,OS,メモリ管理","virtual memory,paging,TLB,OS,memory management",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Virtual_memory","United_Kingdom",90,
 "VA→PA via page table: PA = page_base + offset; TLB caches recent translations","url_present"),

("cs_b1_022","プロセス間通信 — パイプ・ソケット","Inter-Process Communication — Pipes and Sockets","IPC",
 "異なるプロセス間でデータを交換する機構。Unixパイプはプロセス連鎖を実現し、ソケットはTCP/IPスタックを通じてネットワーク越しの通信を提供する。",
 "シェルパイプライン・マイクロサービス間通信・分散システムのデータ交換の基盤。UNIXの「一つのことをうまくやれ」哲学の実装。","計算機科学","オペレーティングシステム",1964,None,
 "OS機構","シェル・マイクロサービス・ネットワーク","異なるプロセス間データ交換","プロセス境界を越えたデータ交換",
 "共有メモリとメッセージパッシングはどう使い分けるか","共有メモリ・メッセージキュー",
 "IPC,パイプ,ソケット,プロセス間通信,Unix","IPC,pipe,socket,inter-process communication,Unix",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Inter-process_communication","North_America",90,
 "pipe: kernel buffer; socket: full-duplex, AF_UNIX (local) or AF_INET (network)","url_present"),

("cs_b1_023","ガベージコレクション","Garbage Collection","Garbage Collection",
 "プログラムが動的に確保したメモリのうち到達不能になった領域を自動的に回収する機構。参照カウント・マーク&スイープ・コピーGC・世代別GCなど多様な手法が存在する。",
 "Java・Python・Go・JavaScript・C#など主要言語のメモリ安全性の基盤。手動メモリ管理のバグ（解放忘れ・二重解放）を防止。","計算機科学","プログラミング言語・コンパイラ",1959,None,
 "ランタイム機構","マネージド言語・仮想マシン","安全で自動的なメモリ管理が必要","メモリ安全性が優先されGCポーズが許容できる場合",
 "世代別GCはなぜ短命オブジェクトが多い仮定で効率的か","手動メモリ管理（Rust所有権・C malloc/free）",
 "ガベージコレクション,GC,メモリ管理,Java,世代別GC","garbage collection,GC,memory management,Java,generational GC",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)","North_America",90,
 "mark-sweep: T=O(heap); generational: minor GC on young gen, major on old gen","url_present"),

("cs_b1_024","型システムとラムダ計算","Type Systems and Lambda Calculus","Type Theory",
 "プログラムの正確性を型によって静的に保証する理論体系。単純型付きラムダ計算・システムF（多相型）・依存型がプログラミング言語理論の基礎を形成する。",
 "Haskell・Rust・ML・Scalaの型システム設計の理論的基盤。型検査器は大規模ソフトウェアの安全性保証ツール。","計算機科学","プログラミング言語・コンパイラ",1936,None,
 "理論","プログラミング言語設計・定理証明","静的型付け言語","型安全性を形式的に証明したい場合",
 "Curry-Howard同型対応は型と証明をどう統一するか","動的型付け・コントラクト型",
 "型システム,ラムダ計算,多相型,依存型,プログラミング言語理論","type system,lambda calculus,polymorphism,dependent types,programming language theory",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Lambda_calculus","United_Kingdom",90,
 "β-reduction: (λx.t)s → t[x:=s]; System F: ΛX.t (type abstraction); Curry-Howard","url_present"),

("cs_b1_025","コンパイラ設計 — 字句解析・構文解析","Compiler Design — Lexing and Parsing","Compiler Frontend",
 "ソースコードをトークン列に変換する字句解析（レクサ）と文脈自由文法で構文木を構築する構文解析（パーサ）。LR・LL・GLR・PEGなど多様な解析法が存在する。",
 "GCC・LLVM・Clangのフロントエンド・JVM bytecode生成・DSL実装の基盤技術。言語処理系の第一工程。","計算機科学","プログラミング言語・コンパイラ",1956,None,
 "コンパイラ","言語処理系・DSL・テキスト解析","形式文法で記述可能な言語","プログラミング言語のフロントエンド実装",
 "LRパーサはLL(*) パーサと比べてどの文法クラスを扱えるか","インタプリタ・JITコンパイラ",
 "コンパイラ,字句解析,構文解析,LR,AST","compiler,lexer,parser,LR parsing,AST",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Compiler","North_America",90,
 "lex: DFA from regex; parse: LR(k) uses GOTO/ACTION table; AST construction","url_present"),

("cs_b1_026","コンパイラ最適化 — SSA形式","Compiler Optimization — Static Single Assignment","SSA Form",
 "各変数が一度だけ定義される中間表現。定義-使用連鎖の明確化によりデッドコード除去・定数畳み込み・ループ不変コード移動などの最適化を効率的に実施できる。",
 "LLVM IRのSSA形式はGCC・Clang・Rustcの最適化エンジンの基盤。ほぼ全ての現代コンパイラが採用する標準中間表現。","計算機科学","プログラミング言語・コンパイラ",1988,None,
 "コンパイラ最適化","最適化コンパイラ・JIT","定義-使用連鎖の明確化が必要","高度な最適化を適用する中間表現",
 "φ関数はSSA変換においてどのような役割を果たすか","CPS変換・継続渡しスタイル",
 "SSA形式,コンパイラ最適化,LLVM,中間表現,デッドコード除去","SSA form,compiler optimization,LLVM,IR,dead code elimination",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Static_single-assignment_form","North_America",90,
 "φ-function merges values at join points; enables O(V+E) dataflow analyses","url_present"),

("cs_b1_027","トランザクション処理とACID特性","Database Transaction and ACID","ACID Transactions",
 "データベーストランザクションの原子性・一貫性・独立性・永続性を保証する特性群。二相コミットプロトコル・ログ先行書き込み（WAL）・MVCC（多版同時実行制御）によって実装される。",
 "PostgreSQL・Oracle・MySQLなどRDBMSの信頼性の基盤。金融取引・在庫管理など整合性が最重要なシステムで必須。","計算機科学","データベースシステム",1970,None,
 "データベース特性","RDBMS・金融・在庫管理","データ整合性と耐障害性が必要","完全な整合性が必要なデータ操作",
 "直列化可能性はどのように並行トランザクションの正確性を定義するか","BASE特性・結果整合性（NoSQL）",
 "ACID,トランザクション,データベース,WAL,MVCC","ACID,transaction,database,WAL,MVCC",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/ACID","North_America",90,
 "2PL serializable; MVCC: read sees snapshot; WAL: log before data write (force+steal)","url_present"),

("cs_b1_028","クエリ最適化","Query Optimization","Query Optimization",
 "SQL クエリを受け取り、結合順序・インデックス選択・実行プラン生成をコストベースで最適化するデータベースエンジンの中心コンポーネント。ダイナミックプログラミングで最適結合順序を探索。",
 "PostgreSQL・MySQL・Oracle Optimizerの中心機能。適切な実行計画選択によって同一クエリの実行時間が100倍以上変わりうる。","計算機科学","データベースシステム",1979,None,
 "データベース","RDBMS・データウェアハウス","複雑な結合・集約クエリ","クエリの実行計画を自動的に最適化する場合",
 "ヒストグラム統計はどうコストモデルに組み込まれるか","物理レイヤ（インデックス設計・パーティショニング）",
 "クエリ最適化,SQL,実行計画,コストベース,データベース","query optimization,SQL,execution plan,cost-based,database",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Query_optimization","North_America",90,
 "Selinger algorithm: DP over subsets of relations; cost = I/O + CPU + network","url_present"),

("cs_b1_029","形式検証 — モデル検査","Formal Verification — Model Checking","Model Checking",
 "有限状態システムの仕様（LTL・CTL論理式）に対する充足性を網羅的に検査する自動検証技術。状態爆発問題をBDD・SAT・抽象化で対処する。",
 "Intel CPUの浮動小数点バグ発見・プロトコル検証（スピン）・組み込みシステム安全検証に使用。ハードウェア設計の必須検証手法。","計算機科学","形式手法",1981,None,
 "形式検証","ハードウェア設計・プロトコル・安全クリティカルシステム","有限状態の系で仕様を網羅検証","組み込み・ハードウェアの安全性保証",
 "状態爆発問題に対するCBMCやBMCはどのようにアプローチするか","定理証明（Coq・Isabelle）",
 "モデル検査,形式検証,LTL,BDD,状態爆発","model checking,formal verification,LTL,BDD,state explosion",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Model_checking","North_America",90,
 "Kripke structure M=(S,S₀,R,L); CTL: M,s⊨EFp iff ∃path s→…→s' with L(s')∋p","url_present"),

("cs_b1_030","P vs NP問題","P vs NP Problem","P versus NP",
 "多項式時間で解ける問題クラスP（決定性）とNP（非決定性）が等しいかという計算理論の中心未解決問題。NP完全問題へのKarp還元・クック-レビンの定理が理論的礎を形成。",
 "暗号理論（NP困難性の仮定）・最適化アルゴリズム設計・AIの推論理論への影響。ミレニアム懸賞問題の一つ。","計算機科学","計算複雑性理論",1971,None,
 "理論","計算理論・暗号・最適化","問題の計算複雑性分析","アルゴリズムの本質的困難さを理解する場合",
 "NP完全問題は現実にどのような近似アルゴリズムで対処されるか","近似アルゴリズム・量子計算（BQP）",
 "P vs NP,計算複雑性,NP完全,クック-レビン,アルゴリズム","P vs NP,computational complexity,NP-complete,Cook-Levin,algorithm",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/P_versus_NP_problem","North_America",90,
 "Cook-Levin: SAT is NP-complete; Karp: 21 NP-complete problems via poly reduction","url_present"),

("cs_b1_031","ランダム化アルゴリズム","Randomized Algorithms","Randomized Algorithms",
 "アルゴリズムの実行中に乱数を使用して意思決定を行う手法群。Las Vegas型（常に正解・ランダムな実行時間）とMonte Carlo型（ランダムな正確性・固定時間）に分類される。",
 "クイックソートの乱択ピボット・暗号（RSA素数検査）・ハッシュ関数・グラフアルゴリズム（最小カット）で広く使用。","計算機科学","アルゴリズム設計パラダイム",1970,None,
 "アルゴリズム設計","暗号・サンプリング・近似","最悪ケース回避・期待値最適化","決定性では困難な問題に期待値で高速解を求める場合",
 "derandomization（確率的アルゴリズムの決定性化）はどのように行われるか","決定性アルゴリズム・近似アルゴリズム",
 "ランダム化アルゴリズム,確率的,Monte Carlo,Las Vegas,乱択","randomized algorithm,probabilistic,Monte Carlo,Las Vegas,randomization",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Randomized_algorithm","North_America",90,
 "Miller-Rabin primality: prob(false positive) ≤ 1/4^k; Karger min-cut: O(n² log n)","url_present"),

("cs_b1_032","近似アルゴリズム","Approximation Algorithms","Approximation Algorithms",
 "NP困難問題に対して多項式時間で最適解の保証された比率（近似率）内の解を求める手法。貪欲法・LP緩和・プライマルデュアル法などが代表的設計技法。",
 "巡回セールスマン問題（Christofides法 1.5近似）・頂点被覆・スケジューリングなど実世界最適化問題への実用解法。","計算機科学","アルゴリズム設計パラダイム",1973,None,
 "アルゴリズム設計","組み合わせ最適化・スケジューリング・ネットワーク","NP困難問題を実用的に解く","最適保証付きで多項式時間解が必要な場合",
 "APX困難性はどのような近似率の限界を示すか","厳密アルゴリズム（指数時間）・ヒューリスティック",
 "近似アルゴリズム,NP困難,貪欲法,LP緩和,近似比","approximation algorithm,NP-hard,greedy,LP relaxation,approximation ratio",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Approximation_algorithm","North_America",90,
 "ρ-approximation: ALG ≤ ρ·OPT; vertex cover: greedy achieves 2-approx","url_present"),

("cs_b1_033","文字列照合 — KMPアルゴリズム","String Matching — Knuth-Morris-Pratt","KMP Algorithm",
 "パターンの失敗関数（部分一致表）を事前計算し、不一致時に比較位置を効率的に戻してO(n+m)でパターン照合するアルゴリズム。Boyer-Moore・Rabin-Karpと並ぶ基本文字列照合法。",
 "テキストエディタの検索・ゲノム配列マッチング・侵入検知システムのパターン照合に使用。","アルゴリズム・データ構造","文字列アルゴリズム",1977,None,
 "文字列アルゴリズム","テキスト検索・バイオインフォマティクス","単一パターン検索","線形時間でのパターン検索",
 "Aho-Corasickアルゴリズムはどのように複数パターンに拡張するか","Boyer-Moore（大きいアルファベットに有利）・Rabin-Karp（ハッシュベース）",
 "KMP,文字列照合,パターンマッチング,テキスト検索","KMP,string matching,pattern matching,text search",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm","North_America",90,
 "failure function π[q]=max{k<q: P[1..k] suffix of P[1..q]}; total T=O(n+m)","url_present"),

("cs_b1_034","公開鍵暗号 — RSA","Public Key Cryptography — RSA","RSA Cryptosystem",
 "大きな合成数の素因数分解困難性を安全性の根拠とする公開鍵暗号方式。公開鍵（n,e）で暗号化し秘密鍵dで復号する。デジタル署名・鍵交換の基盤として使用。",
 "TLS/SSLによるHTTPS通信・PGPメール暗号・電子署名の世界標準。インターネットセキュリティインフラの礎。","暗号・セキュリティ","公開鍵暗号",1977,None,
 "暗号アルゴリズム","TLS・電子署名・鍵交換","素因数分解が困難な大合成数の利用","非対称暗号が必要な場面",
 "量子コンピュータはShorのアルゴリズムでRSAをどう破るか","楕円曲線暗号（ECC）・ポスト量子暗号（格子暗号）",
 "RSA,公開鍵暗号,電子署名,TLS,素因数分解","RSA,public key cryptography,digital signature,TLS,prime factorization",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/RSA_(cryptosystem)","North_America",90,
 "c=m^e mod n; m=c^d mod n; ed≡1 (mod φ(n)); security: factor n=pq is hard","url_present"),

("cs_b1_035","楕円曲線暗号","Elliptic Curve Cryptography","ECC",
 "有限体上の楕円曲線の群演算を利用する公開鍵暗号。RSAより短い鍵長で同等安全性を達成し、TLS 1.3・Bitcoinの署名・モバイル通信の暗号化で使用される。",
 "現代TLS・Bitcoin/Ethereum（secp256k1）・SSH鍵（Ed25519）の暗号基盤。RSAより効率的でモバイル・IoT向け。","暗号・セキュリティ","公開鍵暗号",1985,None,
 "暗号アルゴリズム","TLS 1.3・ブロックチェーン・IoT","短い鍵長で高いセキュリティが必要","計算資源が制限された環境での公開鍵暗号",
 "ECDHとECDSAはそれぞれ何を提供するか","RSA（大きな鍵長）・ポスト量子暗号",
 "楕円曲線暗号,ECC,TLS,ブロックチェーン,Bitcoin","ECC,elliptic curve cryptography,TLS,blockchain,Bitcoin",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Elliptic-curve_cryptography","North_America",90,
 "y²=x³+ax+b over F_p; ECDLP: kP→Q easy, Q→k hard; 256-bit ECC ≈ 3072-bit RSA","url_present"),

("cs_b1_036","ゼロ知識証明","Zero-Knowledge Proof","Zero-Knowledge Proof",
 "証明者が検証者に対して、秘密の情報を明かすことなくその知識の保有を証明できる暗号プロトコル。完全性・健全性・ゼロ知識性の3性質を持つ。zk-SNARKsがブロックチェーンに応用。",
 "プライバシー保護ブロックチェーン（Zcash・StarkNet）・身元認証・投票システムの秘密性保証に使用。","暗号・セキュリティ","現代暗号理論",1985,None,
 "暗号プロトコル","プライバシー保護・ブロックチェーン・認証","秘密を明かさずに知識を証明","プライバシーと検証可能性を両立する場合",
 "zk-SNARKsとzk-STARKsの違いはトラスト前提でどう表れるか","コミットメントスキーム・秘密分散",
 "ゼロ知識証明,ZKP,zk-SNARK,ブロックチェーン,暗号","zero-knowledge proof,ZKP,zk-SNARK,blockchain,cryptography",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Zero-knowledge_proof","North_America",90,
 "completeness: honest prover convinces; soundness: cheater fails w.h.p.; ZK: no info leaked","url_present"),

("cs_b1_037","コンテナ化とDocker","Containerization and Docker","Docker Containers",
 "アプリケーションとその依存関係をコンテナイメージに隔離・パッケージし、ホストOSのカーネルを共有して軽量に実行する技術。Linuxの名前空間とcgroupsを基盤とする。",
 "マイクロサービス・CI/CD・クラウドネイティブ開発の標準インフラ。DockerはGitHubと並んでDevOpsの二大ツールに位置する。","計算機科学","クラウド・分散インフラ",2013,None,
 "インフラ技術","CI/CD・マイクロサービス・クラウド","環境依存を排除した一貫したデプロイ","開発・ステージング・本番の環境差異を排除する場合",
 "VMとコンテナはカーネル共有においてどう異なるか","仮想マシン（VM）・Kubernetes（オーケストレーション）",
 "Docker,コンテナ,名前空間,cgroup,マイクロサービス","Docker,container,namespace,cgroup,microservices",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Docker_(software)","North_America",90,
 "container = process with own namespace(pid,net,mnt,uts) + cgroup resource limits","url_present"),

("cs_b1_038","Kubernetesコンテナオーケストレーション","Kubernetes Container Orchestration","Kubernetes",
 "複数ホストにわたるコンテナのデプロイ・スケーリング・管理・ロードバランシングを自動化するオープンソースオーケストレーションシステム。Googleのボルグシステムを起源とする。",
 "クラウドネイティブアーキテクチャの事実上の標準。AWS EKS・GKE・AKSなど全主要クラウドが対応。CNCF エコシステムの中核。","計算機科学","クラウド・分散インフラ",2014,None,
 "インフラ技術","クラウドネイティブ・SRE・DevOps","大規模コンテナのオーケストレーション","マイクロサービスの自動デプロイ・スケーリング",
 "Kubernetes のコントロールプレーンはどのようにDesired Stateを維持するか","Docker Swarm・HashiCorp Nomad",
 "Kubernetes,コンテナオーケストレーション,クラウドネイティブ,Pod,CNCF","Kubernetes,container orchestration,cloud-native,Pod,CNCF",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Kubernetes","North_America",90,
 "control loop: observe→diff desired vs actual state→act; Pod=smallest schedulable unit","url_present"),

("cs_b1_039","サービスメッシュとIstio","Service Mesh and Istio","Service Mesh",
 "マイクロサービス間の通信を透過的に管理するインフラ層。サイドカープロキシ（Envoy）によってトラフィック管理・mTLS認証・可観測性・回路遮断を実現する。",
 "Netflix・Uber・Googleなど大規模マイクロサービスアーキテクチャのネットワーク管理層。アプリコードを変えずにセキュリティと可観測性を提供。","計算機科学","クラウド・分散インフラ",2017,None,
 "インフラ技術","大規模マイクロサービス・SRE","サービス間通信の統一管理","mTLS・サーキットブレーカ・トレースを横断的に適用する場合",
 "サイドカーパターンはデータプレーンとコントロールプレーンをどう分離するか","API Gateway・Nginx・HAProxy",
 "サービスメッシュ,Istio,Envoy,マイクロサービス,mTLS","service mesh,Istio,Envoy,microservices,mTLS",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Service_mesh","North_America",90,
 "sidecar intercepts all in/outbound traffic; control plane pushes xDS config to Envoy","url_present"),

("cs_b1_040","サーバレスコンピューティング","Serverless Computing","Serverless / FaaS",
 "サーバ管理なしにコードをイベント駆動で実行する実行モデル。AWS Lambda・Google Cloud Functions・Azure Functionsが代表例。使用した実行時間・メモリにのみ課金される。",
 "バックエンドAPI・イベント処理・バッチワークロードの迅速な実装を可能にし、運用コストを削減。マイクロサービスの軽量代替。","計算機科学","クラウド・分散インフラ",2014,None,
 "クラウドアーキテクチャ","イベント処理・API・バッチ","スケーラブルで管理不要な実行が必要","コールドスタートが許容でき短命なワークロード",
 "コールドスタートレイテンシはどのようなワークロードで問題になるか","コンテナ（常時稼働・長命）・Kubernetes",
 "サーバレス,FaaS,Lambda,イベント駆動,クラウド","serverless,FaaS,Lambda,event-driven,cloud",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Serverless_computing","North_America",90,
 "billing: per invocation + GB-sec; cold start: init container+runtime+handler","url_present"),

("cs_b1_041","イベントソーシングとCQRS","Event Sourcing and CQRS","Event Sourcing / CQRS",
 "アプリの状態変化を不変のイベントログとして保存するアーキテクチャパターン（Event Sourcing）と、読み書きのデータモデルを分離するCQRS（コマンドクエリ責務分離）の組み合わせ。",
 "金融システム・監査証跡・イベント駆動マイクロサービスの標準設計パターン。Apache Kafka との組み合わせで大規模なイベント処理基盤を構成。","計算機科学","ソフトウェアアーキテクチャ",2005,None,
 "アーキテクチャパターン","金融・監査・マイクロサービス","完全な変更履歴と読み書き最適化が必要","時系列変化の追跡と高スループット読み取りを両立する場合",
 "イベントストアのイベント再生による状態再構築はどのようにスケールするか","CRUD型アーキテクチャ・RDB",
 "イベントソーシング,CQRS,Kafka,マイクロサービス,イベント駆動","event sourcing,CQRS,Kafka,microservices,event-driven",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Event-driven_architecture","United_Kingdom",90,
 "state = fold(initial, events); CQRS: command side writes events, read side projects","url_present"),

("cs_b1_042","機械学習パイプライン — 特徴エンジニアリング","ML Pipeline — Feature Engineering","Feature Engineering",
 "生データから予測に有用な特徴量を設計・変換・選択する工程。スケーリング・エンコーディング・次元削減・交差特徴・時系列特徴の作成が含まれ、モデル性能への影響が最大。",
 "Kaggleコンペ優勝解法の多くが特徴エンジニアリングで差別化。AutoMLが自動化を試みるが、ドメイン知識に基づく手動特徴がいまも優位。","計算機科学","機械学習・データサイエンス",1990,None,
 "機械学習手法","予測モデル構築・データ分析","構造化データの機械学習","モデル性能をデータ変換で改善する場合",
 "特徴選択と特徴抽出はどのように過学習を防ぐか","表現学習（深層学習による自動特徴抽出）",
 "特徴エンジニアリング,機械学習,前処理,次元削減,AutoML","feature engineering,machine learning,preprocessing,dimensionality reduction,AutoML",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Feature_engineering","North_America",90,
 "mutual info: I(X;Y)=H(Y)-H(Y|X); PCA: cov eigendecomp; one-hot: |cat| binary cols","url_present"),

("cs_b1_043","勾配ブースティング","Gradient Boosting","Gradient Boosted Trees",
 "弱学習器（主に決定木）を順次加算し、各ステップで損失関数の負の勾配を目的変数として残差を学習する集成学習手法。XGBoost・LightGBM・CatBoostが実用的に最強クラスの実装。",
 "構造化データの機械学習コンペで最も実績が高い手法。金融スコアリング・クリック率予測・医療診断で広く使用。","計算機科学","機械学習・データサイエンス",1999,None,
 "機械学習手法","構造化データの分類・回帰","勾配計算可能な損失関数","表形式データで最高精度を求める場合",
 "XGBoostとLightGBMの分岐アルゴリズム（depth-first vs leaf-wise）はどう違うか","ランダムフォレスト（並列・低分散）",
 "勾配ブースティング,XGBoost,LightGBM,アンサンブル学習,決定木","gradient boosting,XGBoost,LightGBM,ensemble,decision tree",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Gradient_boosting","North_America",90,
 "F_m(x)=F_{m-1}(x)+γ_m·h_m(x); h_m fits -∂L/∂F_{m-1}; regularization via shrinkage","url_present"),

("cs_b1_044","注意機構とTransformer","Attention Mechanism and Transformer","Transformer Architecture",
 "クエリ・キー・バリューの内積に基づくスケール付き点積注意（Scaled Dot-Product Attention）とマルチヘッド注意機構を中心とするニューラルネットワークアーキテクチャ。長距離依存関係をO(1)で捕捉。",
 "BERT・GPT・T5・LLaMA等の大規模言語モデルの基盤。自然言語処理を超えて画像（ViT）・タンパク質構造予測（AlphaFold2）・音声認識にも波及。","AI・機械学習","深層学習アーキテクチャ",2017,None,
 "ニューラルネットワーク","自然言語処理・コンピュータビジョン・科学計算","系列データや高次元特徴の長距離依存モデリング","RNNを超える並列化と長距離依存が必要な場合",
 "注意機構の計算コストO(n²)をどう削減するか（Linformer・Flashattention）","RNN・LSTM（逐次処理）",
 "Transformer,注意機構,BERT,GPT,自然言語処理","Transformer,attention mechanism,BERT,GPT,NLP",
 "active","primary",95,1,"https://en.wikipedia.org/wiki/Transformer_(machine_learning_model)","Google Brain",90,
 "Attention(Q,K,V)=softmax(QK^T/√d_k)V; multi-head: concat h heads; pos encoding","url_present"),

("cs_b1_045","強化学習 — Q学習","Reinforcement Learning — Q-Learning","Q-Learning",
 "エージェントが環境との相互作用を通じて行動価値関数Q(s,a)をベルマン方程式を用いて反復的に学習する無モデル強化学習手法。ε-greedy探索で探索-利用トレードオフを管理。",
 "ゲームAI（Atari・囲碁）・ロボット制御・自動売買システムの学習の基盤。DeepMindのDQNはCNNと組み合わせてAtari人間超えを実現。","AI・機械学習","強化学習",1989,None,
 "強化学習","ゲームAI・ロボット・推薦システム","Markov決定過程・報酬信号がある環境","試行錯誤から最適方策を学習する場合",
 "Q学習とSARSAはオフ方策とオン方策でどう異なるか","方策勾配法・アクタークリティック法",
 "Q学習,強化学習,ベルマン方程式,DQN,探索","Q-learning,reinforcement learning,Bellman equation,DQN,exploration",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Q-learning","North_America",90,
 "Q(s,a)←Q(s,a)+α[r+γmax_a'Q(s',a')-Q(s,a)]; converges if all (s,a) visited ∞","url_present"),

("cs_b1_046","グラフニューラルネットワーク","Graph Neural Networks","GNN",
 "グラフ構造データに対してノード特徴量を近傍ノードからの集約（メッセージパッシング）によって更新するニューラルネットワーク。分子特性予測・ソーシャルネットワーク解析・推薦に使用。",
 "AlphaFold2のタンパク質構造予測・知識グラフ補完・交通流予測・薬物-標的相互作用予測の中核技術。","AI・機械学習","グラフ機械学習",2017,None,
 "ニューラルネットワーク","分子設計・ネットワーク分析・推薦","グラフ構造のデータ","グラフ上の予測・分類・生成",
 "GCNとGraphSAGEはどのように大規模グラフへのスケーリングを実現するか","グラフカーネル・スペクトルグラフ理論",
 "グラフニューラルネットワーク,GNN,メッセージパッシング,分子,知識グラフ","GNN,graph neural network,message passing,molecules,knowledge graph",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Graph_neural_network","North_America",90,
 "h_v^(l)=σ(W·AGG({h_u^(l-1): u∈N(v)∪{v}})); READOUT for graph-level task","url_present"),

("cs_b1_047","拡散モデル","Diffusion Models","Denoising Diffusion Probabilistic Models",
 "データにノイズを段階的に加える前向き過程と、学習したニューラルネットで逆向きにノイズ除去して生成する確率的生成モデル。画像・音声・動画・タンパク質生成で最先端の品質を達成。",
 "Stable Diffusion・DALL-E 3・Sora・RFdiffusion（タンパク質設計）の基盤。GANを超える安定かつ高品質な生成を実現し2020年代の生成AIを定義。","AI・機械学習","生成モデル",2020,None,
 "生成モデル","画像・音声・動画・タンパク質生成","高品質で多様な生成が必要","GAN的なモード崩壊なしに安定した生成",
 "DDPM・DDIM・スコアマッチングのサンプリング速度の違いはどこにあるか","GAN（敵対的生成）・VAE（変分オートエンコーダ）",
 "拡散モデル,DDPM,Stable Diffusion,生成AI,画像生成","diffusion model,DDPM,Stable Diffusion,generative AI,image generation",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Diffusion_model","North_America",90,
 "q(x_t|x_0)=N(√ᾱ_t x_0,(1-ᾱ_t)I); L=E[||ε-ε_θ(x_t,t)||²]; reverse: p_θ(x_{t-1}|x_t)","url_present"),

("cs_b1_048","量子エラー訂正","Quantum Error Correction","Quantum Error Correction",
 "量子ビットのデコヒーレンスと操作エラーを、複数の物理量子ビットで1つの論理量子ビットを符号化して訂正する手法。表面符号・スタビライザーコードが実用的標準。",
 "Google・IBMの量子コンピュータで量子アドバンテージ実現の前提。Surface code 1000:1物理-論理比が目標で2020年代の量子コンピューティング研究の中心課題。","計算機科学","量子計算",1995,None,
 "量子情報理論","量子コンピュータ","大規模量子回路の誤り耐性が必要","フォールトトレラント量子計算の実現",
 "表面符号の閾値定理はどのような誤り率条件を定義するか","量子アニーリング（誤り訂正不要）",
 "量子エラー訂正,量子コンピュータ,表面符号,スタビライザー","quantum error correction,quantum computing,surface code,stabilizer",
 "active","primary",88,1,"https://en.wikipedia.org/wiki/Quantum_error_correction","North_America",90,
 "logical qubit encoded in O(d²) physical qubits; threshold theorem: p<p_th→scalable","url_present"),

("cs_b1_049","連合学習","Federated Learning","Federated Learning",
 "生データをサーバに送らず、各デバイスでローカルに学習してモデル更新（勾配または重み差分）のみを集約するプライバシー保護機械学習手法。FedAvgが標準集約アルゴリズム。",
 "Google Gboardのキーボード予測・医療機関連合AI・スマートフォンの個人化に使用。GDPRに整合したプライバシー保護AI学習の標準手法。","計算機科学","機械学習・データサイエンス",2016,None,
 "機械学習","プライバシー保護AI・スマートデバイス・医療","データを集中化できないプライバシー制約環境","デバイス上のデータでプライバシーを保ちながら学習",
 "勾配漏洩攻撃はFederated Learningのプライバシーをどう脅かすか","中央集権的学習・差分プライバシー",
 "連合学習,Federated Learning,プライバシー,FedAvg,エッジAI","federated learning,privacy,FedAvg,edge AI,differential privacy",
 "active","primary",90,1,"https://en.wikipedia.org/wiki/Federated_learning","North_America",90,
 "FedAvg: w←Σ(n_k/n)w_k; E local steps; C fraction of clients per round","url_present"),

("cs_b1_050","差分プライバシー","Differential Privacy","Differential Privacy",
 "データベースへの任意のクエリに対してランダムノイズ（ラプラスノイズまたはガウスノイズ）を加えることで、個人の存在が出力に与える影響をεで制限するプライバシー保護技術。",
 "Apple・Google・Microsoftが製品統計収集に採用。US Censusでε-差分プライバシーを2020年から正式採用。プライバシー保護データ解析の数学的標準。","暗号・セキュリティ","プライバシー技術",2006,None,
 "プライバシー技術","統計公開・機械学習・センサデータ","個人を識別できないデータ公開・分析","個人プライバシーを数学的に保証した統計分析",
 "ε-差分プライバシーとδ-(ε,δ)-差分プライバシーはどう使い分けるか","k-匿名性・仮名化",
 "差分プライバシー,プライバシー保護,ラプラスノイズ,機械学習","differential privacy,privacy,Laplace noise,machine learning",
 "active","primary",92,1,"https://en.wikipedia.org/wiki/Differential_privacy","North_America",90,
 "Pr[M(D)∈S]≤e^ε·Pr[M(D')∈S]+δ for adjacent D,D'; Lap mech: sens/ε noise","url_present"),
]

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

ins, sk = insert_records(records)
print(f"Inserted: {ins}, Skipped: {sk}")

import sqlite3 as sq
c2 = sq.connect(DB)
total = c2.execute("SELECT COUNT(*) FROM engineering_method WHERE status='active'").fetchone()[0]
print(f"Total active: {total}")
c2.close()
