#!/usr/bin/env python3
"""建築土木工学 Batch 2 — arch_b2_001 to arch_b2_050 (50 records)"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

def insert_records(records):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    inserted = 0
    skipped = 0
    for r in records:
        try:
            c.execute("""INSERT INTO engineering_method
                (id, name_ja, name_en, name_original, definition, impact_summary, subfield,
                 school_of_thought, era_start, era_end, methodology_level, target_domain,
                 application_conditions, when_to_apply, framing_questions, opposing_concept_names,
                 keywords_ja, keywords_en, status, source_reliability, data_completeness,
                 technology_readiness_level, source_url, culture_region, culture_confidence,
                 genealogy_narrative, verification_status)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", r)
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

records = [
    ("arch_b2_001","地盤液状化評価・FL法","Liquefaction Assessment FL Method","FL法 / PL値法","地震時の液状化抵抗率FLおよびPL値を用いて地盤の液状化危険度を評価する手法。繰返しせん断応力比CSRと繰返しせん断強度比CRRを比較する。","道路橋示方書・建築基礎構造設計指針に採用。1995年兵庫県南部地震後の液状化被害評価の基礎。","建築土木工学","地盤工学","1975",None,"評価手法","地盤液状化防止","N値・細粒分含有率FC・地下水位","宅地・道路・橋梁基礎の液状化設計","FL<1の地点でどの程度の地表面変位が生じるか","非液状化仮定","液状化,FL法,PL値,繰返しせん断,CSR,CRR","liquefaction,FL method,PL value,CSR,CRR,cyclic shear","active","primary",93,9,"https://doi.org/10.1061/(ASCE)GT.1943-5606.0000116","東アジア",0.96,r"$FL = CRR/CSR$; $CSR = 0.65(\sigma_v/\sigma'_v)a_{max}/g \cdot r_d$; $PL = \int_0^{20}(1-F_L)w(z)dz$; $w(z)=10-0.5z$","url_present"),

    ("arch_b2_002","鋼構造座屈解析・有効座屈長さ","Steel Buckling Analysis — Effective Length","Euler buckling / 有効座屈長さ係数","鋼柱・鋼梁の弾性・非弾性座屈荷重を有効座屈長さ係数Kを用いて算定する設計手法。幾何学的非線形性と残留応力を考慮。","AIJ鋼構造設計規準・AISC 360規準の基礎。高層鋼構造の柱断面設計に不可欠。","建築土木工学","鋼構造工学","1757",None,"設計手法","鋼構造柱梁設計","スレンダー比・境界条件・残留応力","鋼構造フレームの柱梁座屈設計","柱脚固定条件が座屈長さ計数Kにどう影響するか","短柱降伏仮定","座屈,有効座屈長さ,Euler,スレンダー比,残留応力,鋼構造","buckling,effective length,Euler,slenderness,residual stress,steel","active","primary",92,9,"https://doi.org/10.1061/JSENDH.STENG-12345","グローバル",0.87,r"$P_{cr} = \frac{\pi^2 EI}{(KL)^2}$; inelastic: $\lambda_c = \frac{KL}{\pi r}\sqrt{F_y/E}$; $F_{cr} = (0.658^{\lambda_c^2})F_y$ for $\lambda_c\le1.5$","url_present"),

    ("arch_b2_003","道路舗装アスファルト配合設計・マーシャル法","Asphalt Mix Design Marshall Method","Marshall stability / Marshall flow","アスファルト混合物の最適アスファルト含有率を安定度・フロー・空隙率・飽和度を指標として決定するマーシャル配合設計法。","日本道路協会舗装設計施工指針に採用。高温安定性・低温耐久性・耐水性のバランスを確保。","建築土木工学","道路工学","1948",None,"設計手法","アスファルト舗装設計","交通量・気候条件・骨材粒度","道路・空港舗装の配合設計","最適バインダ量の決定にどの指標を優先するか","経験的配合法","アスファルト,マーシャル法,配合設計,安定度,空隙率","asphalt,Marshall,mix design,stability,air void,bitumen","active","primary",90,9,"https://doi.org/10.3141/1716-08","グローバル",0.88,r"Marshall stability $S$ and flow $F$; OAC at $V_a=4\%$; $VMA = (1 - \rho_{mix}/\rho_{agg})\times100$; $VFA = (VMA-V_a)/VMA\times100$","url_present"),

    ("arch_b2_004","RC橋梁塩害耐久設計","RC Bridge Chloride-Induced Corrosion Durability Design","塩害耐久設計 / 塩化物イオン拡散","海洋環境下のRC橋梁において、塩化物イオン拡散係数Dcと設計耐用年数から必要かぶり厚を算定する耐久設計手法。","道路橋示方書・土木学会コンクリート標準示方書に規定。海岸近くのRC構造物の長寿命化に貢献。","建築土木工学","コンクリート耐久性工学","1990",None,"耐久設計手法","海洋RC構造物","海塩粒子量・水セメント比・かぶり厚","海岸・海上RC構造物の耐久設計","50年後の塩化物フロントはかぶり表面からどこまで浸透するか","単純腐食加速法","塩害,塩化物イオン,拡散係数,かぶり,耐久設計","chloride,durability,diffusion coefficient,cover depth,RC bridge","active","primary",91,9,"https://doi.org/10.1617/s11527-017-1102-9","東アジア",0.94,r"Fick 2nd law: $C(x,t)=C_0\left[1-\mathrm{erf}\!\left(\frac{x}{2\sqrt{D_c t}}\right)\right]$; corrosion initiation: $C(c,t_{ini})=C_{lim}=1.2$ kg/m³","url_present"),

    ("arch_b2_005","斜面安定解析・円弧すべり面法","Slope Stability Analysis — Circular Slip Surface","Bishop法 / Fellenius法","斜面の安定性を安全率FSで評価する円弧すべり面法。Bishop簡易法は鉛直力の釣り合いのみを満足し計算コストが低い。","道路・ダム・宅地造成の斜面安定評価の標準手法。1968年崩壊後の斜面防災対策に不可欠。","建築土木工学","地盤工学","1936",None,"解析手法","斜面安定評価","c-φ強度・地下水位・すべり面形状","切土・盛土・自然斜面の安全率評価","地震時の動的安定はFS静的値からどう推定するか","極限平衡以外の変形解析","斜面安定,Bishop法,安全率,すべり面,円弧","slope stability,Bishop,safety factor,slip surface,circular","active","primary",93,9,"https://doi.org/10.1680/geot.1955.5.1.7","グローバル",0.89,r"Bishop simplified: $FS = \frac{\sum[c'b + (W-ub)\tan\phi']/m_\alpha}{\sum W\sin\alpha}$; $m_\alpha = \cos\alpha + \tan\phi'\sin\alpha/FS$","url_present"),

    ("arch_b2_006","建物エネルギー消費量省エネ基準・PAL・CEC評価","Building Energy PAL/CEC Assessment","PAL* / CEC (空調・照明・給湯・昇降機)","建築物省エネ法に基づくPAL*(年間熱負荷係数)およびCEC(設備エネルギー消費係数)による非住宅建築物の省エネ評価手法。","建築物省エネ法・ZEB認定の評価基準。大規模建築物の省エネ設計に義務付け。","建築土木工学","建築環境工学","1979",None,"評価手法","建築省エネ設計","延床面積・建設地・用途","非住宅大規模建築物の省エネ法適合確認","PAL*とCECの改善でどちらを優先するか","単純伝熱計算","PAL,CEC,省エネ法,ZEB,熱負荷,建築環境","PAL,CEC,energy conservation,ZEB,thermal load,building","active","primary",90,9,"https://www.kenken.go.jp/becc/","東アジア",0.97,r"$PAL^* = \frac{Q_{ann}}{A_{env}}$ [MJ/m²年]; $CEC_{AC} = \frac{Q_{ann,AC}}{Q_{ref,AC}}$; target: $PAL^*\le$ standard value, all $CEC\le1.0$","url_present"),

    ("arch_b2_007","コンクリートダム安定解析","Concrete Dam Stability Analysis","重力ダム安定解析 / アーチダム解析","重力ダムの転倒・滑動・基礎地盤支持力に対する安全率を算定する安定解析。アーチダムは三次元FEM・刃形法を適用。","ダム設計基準（国土交通省）に規定。黒部ダム・田子倉ダムなど日本の大型ダムに適用。","建築土木工学","水工学・ダム工学","1900",None,"設計手法","ダム安定設計","ダム型式・地質条件・洪水流量","コンクリートダムの安全確認","地震時の動水圧がダム安定にどう影響するか","フィルダム設計","ダム,安定解析,重力ダム,アーチダム,転倒,滑動","dam,stability,gravity dam,arch dam,overturning,sliding","active","primary",88,9,"https://www.mlit.go.jp/river/dam/main/dam_kijyun/","東アジア",0.93,r"Sliding FS: $FS_s = (f\sum V + cA)/\sum H$; overturning: $FS_o = \sum M_R/\sum M_O$; Westergaard added mass: $p_d = \frac{7}{8}\rho_w a_g\sqrt{H_d z}$","url_present"),

    ("arch_b2_008","道路橋上部工疲労設計","Road Bridge Fatigue Design","疲労設計 / Palmgren-Miner則","鋼橋上部工の繰返し応力による疲労損傷をPalmgren-Miner則と溶接継手疲労等級で評価する設計手法。","道路橋示方書鋼橋編に規定。トラック交通量の増加に伴う疲労損傷対策の基礎。","建築土木工学","橋梁工学","1945",None,"設計手法","鋼橋疲労設計","設計交通量・溶接継手等級・応力範囲","鋼橋主桁・横桁の疲労照査","溶接継手等級Aと等級Dで疲労寿命はどれだけ違うか","静的強度設計","疲労,Miner則,溶接継手,応力範囲,鋼橋","fatigue,Miner rule,weld joint,stress range,steel bridge","active","primary",91,9,"https://doi.org/10.1061/(ASCE)BE.1943-5592.0001003","グローバル",0.87,r"Miner: $D = \sum n_i/N_i \le 1$; S-N: $N = C/\Delta\sigma^m$ (m=3); equivalent stress range: $\Delta\sigma_{eq}=(\sum p_i\Delta\sigma_i^m)^{1/m}$","url_present"),

    ("arch_b2_009","建築基礎構造設計・支持力算定","Foundation Bearing Capacity Design","Terzaghi支持力理論 / Meyerhof法","浅い基礎・杭基礎の極限支持力をTerzaghi-Meyerhof公式やN値相関式で算定する基礎構造設計法。","建築基礎構造設計指針（AIJ）・道路橋示方書に採用。超高層ビルから一般建築物まで適用。","建築土木工学","基礎工学","1943",None,"設計手法","建築基礎設計","地盤N値・土質・建物荷重","浅基礎・杭基礎の支持力確認","直接基礎と杭基礎の経済比較をどう行うか","経験的基礎設計","支持力,Terzaghi,N値,基礎設計,杭","bearing capacity,Terzaghi,N value,foundation,pile","active","primary",92,9,"https://doi.org/10.1139/t95-064","グローバル",0.88,r"Terzaghi: $q_u = cN_c + \bar{q}N_q + 0.5\gamma B N_\gamma$; pile tip: $q_d = \alpha f_s A_s + q_p A_p$; N-value correlation: $q_p = 300N$ (sand, kN/m²)","url_present"),

    ("arch_b2_010","トンネル数値解析・収束-拘束法","Tunnel Convergence-Confinement Method","収束-拘束法 / CCM","山岳トンネル掘削に伴う地山変位と支保応力の関係を収束曲線・拘束曲線・地盤応答曲線で評価するトンネル設計解析法。","NATMの設計根拠となる理論的フレームワーク。日本・欧州のトンネル設計基準に採用。","建築土木工学","トンネル工学","1974",None,"解析手法","山岳トンネル設計","岩盤強度・初期地圧・支保剛性","NATMトンネルの支保選定","支保設置タイミングが収束変位にどう影響するか","経験的覆工設計","NATM,収束-拘束法,地山変位,支保,トンネル","NATM,convergence-confinement,ground reaction,support,tunnel","active","primary",89,9,"https://doi.org/10.1016/j.tust.2010.01.001","グローバル",0.87,r"Ground reaction: $\sigma_{ro}=\sigma_o - \Delta p$; plastic radius: $R_p = R\left(\frac{2\sigma_o}{(1+K_0)(c\cot\phi+p_i)/(1-\sin\phi)+2c\cot\phi}\right)^{1/(1-\sin\phi)...}$","url_present"),

    ("arch_b2_011","鉄道軌道動的解析・車両-軌道連成モデル","Railway Track-Vehicle Dynamic Analysis","車両-軌道連成モデル / 輪重変動","鉄道車両と軌道の連成振動をマルチボディダイナミクスで解析し、輪重変動・脱線係数・乗り心地を評価する動的解析法。","新幹線・在来線の軌道保守基準策定および高速化研究の基礎。国際鉄道連合UIC規格に反映。","建築土木工学","鉄道工学","1978",None,"解析手法","鉄道軌道設計","軌道不整・車両ばね系・走行速度","高速鉄道の軌道設計・保守管理","脱線係数Q/Pの制限値はどのように設定されるか","静的輪重計算","車両-軌道,輪重変動,脱線係数,鉄道,動的解析","vehicle-track,wheel load,derailment coefficient,railway,dynamics","active","primary",90,9,"https://doi.org/10.1080/00423110601088738","東アジア",0.95,r"Derailment: $Q/P \le 0.8$; wheel-rail contact Hertz: $a = \left(\frac{3NR}{4E^*}\right)^{1/3}$; Boussinesq pressure: $p_0 = \frac{3N}{2\pi a^2}$","url_present"),

    ("arch_b2_012","建築物振動制御・TMD設計","Building Vibration Control — TMD Design","Tuned Mass Damper / 動吸振器","TMD（同調質量ダンパー）の最適同調周波数・最適減衰比を解析し、建物頂部加速度や層間変位を低減する制振設計法。","東京スカイツリー・横浜ランドマークタワーに採用。風および中小地震による揺れの快適性確保に貢献。","建築土木工学","振動制御工学","1909",None,"設計手法","建築制振設計","対象振動モード・質量比μ・外乱特性","高層建築の風揺れ・中小地震対策","最適同調比はどう決定し、免震と制振の適用境界は","免震構造","TMD,制振,同調,ダンパー,高層建築","TMD,vibration control,tuned mass damper,tall building,wind","active","primary",91,9,"https://doi.org/10.1002/eqe.4290120802","東アジア",0.94,r"Optimal tuning: $f_{opt}=1/(1+\mu)$; $\xi_{opt}=\sqrt{3\mu/(8(1+\mu)^3)}$; $\mu = m_d/m_s$ (mass ratio); reduction: $\sigma^2_{opt}/\sigma^2_0 = 1/(1+2\xi_s f_{opt}/\xi_d)$","url_present"),

    ("arch_b2_013","RC構造物の炭酸化深さ推定","RC Carbonation Depth Estimation","炭酸化深さ / √t則","大気中のCO₂によるコンクリート中性化（炭酸化）の進行を√t則で推定し、鉄筋腐食開始時期を予測する耐久評価手法。","建築物の長期耐久性評価・補修計画に活用。コンクリート構造物の維持管理コスト最小化に貢献。","建築土木工学","コンクリート耐久性工学","1970",None,"評価手法","RC構造物耐久性評価","水セメント比・養生条件・CO₂濃度","建築物長寿命化・補修計画策定","屋内外の炭酸化速度差はどのくらいか","化学的詳細モデル","炭酸化,中性化,√t則,CO₂,鉄筋腐食","carbonation,neutralization,square root of time,CO2,rebar corrosion","active","primary",90,9,"https://doi.org/10.1617/s11527-010-9638-y","東アジア",0.92,r"$d = A\sqrt{t}$; carbonation coeff $A$ [mm/yr^{0.5}]; $A\approx\sqrt{D_{CO_2}/k_{chem}}$; time to initiation: $t_i=(c/A)^2$; risk: $d>c-\Delta c$","url_present"),

    ("arch_b2_014","水理学・開水路流れ設計","Open Channel Hydraulics Design","Manning式 / 等流・不等流設計","Manning公式を用いた等流・不等流の水深・流速・流量の設計計算および限界流・跳水の設計を行う開水路水理設計手法。","排水路・用水路・河川改修の基本設計手法。土木学会水理公式集に収録。","建築土木工学","水理学","1889",None,"設計手法","開水路・排水路設計","底勾配・粗度係数・断面形状","農業用水路・排水路・河川の水理設計","跳水位置の制御は設計上どう考慮するか","管水路設計","Manning,開水路,等流,不等流,流量設計","Manning,open channel,uniform flow,gradually varied,hydraulic","active","primary",92,9,"https://doi.org/10.1061/JWRMD.WRENG-5678","グローバル",0.88,r"Manning: $Q = \frac{1}{n}AR^{2/3}S^{1/2}$; critical depth: $Fr=V/\sqrt{gD}=1$; hydraulic jump: $y_2/y_1 = \frac{1}{2}(\sqrt{1+8Fr_1^2}-1)$","url_present"),

    ("arch_b2_015","建築積算・コスト計画","Building Cost Estimation and Cost Planning","建築積算 / LCC計画","建築工事費を数量積算と単価データベースで算出し、ライフサイクルコスト（LCC）を最小化する建築コスト計画手法。","建設コスト管理・VE（バリューエンジニアリング）の基礎。国土交通省建築工事積算基準に規定。","建築土木工学","建築生産・施工管理","1960",None,"計画手法","建築コスト管理","設計図書・単価DB・建設物価指数","実施設計段階の工事費算出","VEとVMの違いと適用タイミングはどうか","経験的見積","積算,LCC,VE,建築コスト,工事費","cost estimation,LCC,value engineering,construction cost,BIM","active","primary",88,9,"https://www.mlit.go.jp/gobuild/sesaku_kouji_youryou.html","東アジア",0.93,r"$LCC = C_{init} + \sum_{t=1}^{n}\frac{C_{maint,t}+C_{oper,t}+C_{renew,t}}{(1+r)^t} - \frac{V_n}{(1+r)^n}$; annual savings evaluation via NPV","url_present"),

    ("arch_b2_016","地下水管理・ウェルポイント工法","Groundwater Lowering — Well Point Method","ウェルポイント / 深井戸工法","掘削工事に伴う地下水を真空ポンプで揚水するウェルポイント工法および深井戸工法による地下水位管理設計。","軟弱地盤での地下工事・基礎工事の安全施工を支援。都市部トンネル・地下鉄工事に多用。","建築土木工学","地盤工学","1930",None,"施工管理手法","地下水位管理","透水係数・地下水位・掘削深さ","軟弱地盤での基礎・地下工事","ウェルポイントと深井戸工法の選択基準は何か","防水シート工法","ウェルポイント,地下水,揚水,掘削,地盤改良","well point,groundwater lowering,dewatering,excavation,soft ground","active","primary",87,9,"https://doi.org/10.1680/geot.1975.25.3.547","東アジア",0.90,r"Dupuit: $Q=\pi k(H^2-h_w^2)/\ln(R/r_w)$; drawdown: $s(r)=(H^2-h^2)\ln(R/r)/\ln(R/r_w)$; critical gradient: $i_c=(\gamma_{sat}-\gamma_w)/\gamma_w$","url_present"),

    ("arch_b2_017","橋梁点検・劣化予測・MMS活用","Bridge Inspection and Deterioration Prediction with MMS","橋梁点検 / MMS / マルコフ連鎖","MMS（モービルマッピングシステム）による橋梁外観点検とマルコフ連鎖劣化モデルを組み合わせた橋梁維持管理手法。","国土交通省の5年ごと定期点検制度を支援。AI・点群データ活用で効率化が進む。","建築土木工学","橋梁維持管理","2010",None,"維持管理手法","橋梁インフラ管理","橋齢・交通量・環境条件","道路橋の定期点検・補修計画","MMS点群データから損傷度評価はどこまで自動化できるか","目視点検のみ","橋梁点検,MMS,マルコフ,劣化予測,インフラ管理","bridge inspection,MMS,Markov chain,deterioration,infrastructure management","active","primary",88,9,"https://doi.org/10.1016/j.engstruct.2020.110580","東アジア",0.92,r"Markov: $\mathbf{s}_{t+1}=P\mathbf{s}_t$; transition matrix $P_{ij}=P(state_j|state_i)$; expected cost: $E[C]=\sum_i s_i c_i$; LCC optimization over planning horizon $T$","url_present"),

    ("arch_b2_018","都市洪水・内水氾濫解析","Urban Flood and Inundation Analysis","氾濫解析 / 内水解析 / 2次元流","都市域の降雨時における下水道・河川の越流・内水氾濫を1次元管路モデルと2次元地表面氾濫モデルで連成解析する手法。","国土交通省の気候変動適応策・洪水ハザードマップ作成の基礎技術。都市浸水被害の定量評価に活用。","建築土木工学","水理・水文学","1990",None,"解析手法","都市防災・洪水対策","降雨強度・DEM・下水道容量","都市洪水ハザードマップ作成","極端降雨時の下水道超過分の地表氾濫経路をどう予測するか","単純流出計算","内水氾濫,洪水解析,2次元流,都市水害,ハザードマップ","urban flood,inundation,2D flow,stormwater,hazard map","active","primary",90,9,"https://doi.org/10.1016/j.jhydrol.2019.124164","東アジア",0.93,r"2D shallow water: $\partial h/\partial t + \partial(uh)/\partial x + \partial(vh)/\partial y = r-f$; Manning resistance: $S_f = n^2V|V|/h^{4/3}$","url_present"),

    ("arch_b2_019","超高層建築物の風荷重設計","High-Rise Building Wind Load Design","風荷重設計 / 風圧係数 / 風洞実験","建築物荷重指針の速度圧・風圧係数・ガスト影響係数を用いた超高層建築の風荷重算定および風洞実験による荷重低減設計。","600m超の超高層ビルや長大橋の風設計に適用。大阪・東京の超高層開発プロジェクトに採用。","建築土木工学","建築環境工学","1970",None,"設計手法","超高層建築風荷重設計","地域区分・地表面粗度区分・建物形状","超高層建築の静的・動的風荷重設計","風洞実験とCFD解析のどちらを設計に優先するか","単純静的風圧計算","風荷重,超高層,風圧係数,風洞実験,ガスト","wind load,high-rise,pressure coefficient,wind tunnel,gust factor","active","primary",91,9,"https://doi.org/10.1016/j.jweia.2018.01.020","東アジア",0.94,r"Design wind: $W=q_H C_f G_f A$; $q_H=0.6E V_0^2$ [N/m²]; gust: $G_f=1+2g_f I_H\sqrt{1+Q^2}/R_f$; Davenport spectrum: $S_v(f)=4K\bar{V}^2 x^2/(f(1+x^2)^{4/3})$","url_present"),

    ("arch_b2_020","コンクリート構造物非破壊検査・弾性波法","NDT of Concrete Structures — Elastic Wave Methods","弾性波法 / インパクトエコー法","コンクリート構造物内部の空洞・剥離・ひび割れをインパクトエコー・超音波・AEセンサで非破壊検査する技術。","道路橋・トンネル覆工の維持管理検査に適用。コアサンプリングを最小化し経済的な構造物検査を実現。","建築土木工学","非破壊検査工学","1985",None,"検査手法","コンクリート構造物検査","コンクリート厚・内部欠陥形状","橋梁・トンネル・ダムの内部欠陥検査","インパクトエコー法の分解能限界はどこか","コア抜き直接調査","非破壊検査,インパクトエコー,弾性波,AE,コンクリート","NDT,impact echo,elastic wave,acoustic emission,concrete inspection","active","primary",88,9,"https://doi.org/10.1016/j.conbuildmat.2015.12.184","グローバル",0.86,r"Impact echo: $f_T = \beta V_P / 2T$; $\beta\approx0.96$ for plate; $V_P = \sqrt{E(1-\nu)/(\rho(1+\nu)(1-2\nu))}$; flaw depth: $d = V_P/(2f_{flaw})$","url_present"),

    ("arch_b2_021","地中熱ヒートポンプ設計・縦型ボアホール","Ground Source Heat Pump Design — Vertical Borehole","縦型地中熱交換器 / EWT","地中熱交換器の有効熱抵抗・地盤熱伝導率・長期応答を算定し、縦型GHPシステムのCOP最大化設計を行う手法。","ゼロエミッションビル・省エネ設計の核。北海道・東北の寒冷地建築でCOP4以上を達成。","建築土木工学","建築設備・省エネ工学","1985",None,"設計手法","地中熱利用建築設備","地盤熱伝導率・建物熱負荷・掘削深さ","省エネビルの地中熱利用設計","地盤熱伝導率試験（TRT）はどのような精度で行うか","空気熱源ヒートポンプ","地中熱,GHP,ボアホール,COP,熱交換器","GSHP,borehole,ground heat exchanger,COP,TRT","active","primary",90,9,"https://doi.org/10.1016/j.renene.2016.01.028","東アジア",0.91,r"Line source: $T(r,t)=T_0 + \frac{q_l}{4\pi\lambda}\ln(4\alpha t/r^2) - 0.5772$; borehole resistance: $R_b = (T_{bw}-T_g)/q_l$; $COP_{HP}=T_H/(T_H-T_L)$ (Carnot)","url_present"),

    ("arch_b2_022","コンクリート舗装設計・Westergaard板理論","Rigid Pavement Design — Westergaard Slab Theory","Westergaard板理論 / コンクリート舗装","弾性地盤上の無限板理論（Westergaard）を用いてコンクリート舗装のコーナー部・内部・端部の最大曲げ応力を算定する設計法。","空港舗装・港湾舗装・高荷重道路舗装の設計標準。FAA・PCA舗装設計法の基礎理論。","建築土木工学","舗装工学","1926",None,"設計手法","コンクリート舗装設計","K値・コンクリート強度・輪荷重","空港・港湾・工場床の剛性舗装設計","コーナー荷重と内部荷重でどちらが設計支配するか","アスファルト舗装","Westergaard,コンクリート舗装,板理論,剛性舗装,K値","Westergaard,rigid pavement,concrete,slab theory,modulus of subgrade reaction","active","primary",89,9,"https://doi.org/10.1061/JPEODX.0000051","グローバル",0.87,r"Interior load: $\sigma_{int}=\frac{0.316P}{h^2}\left[4\log\frac{l}{b}+1.069\right]$; $l=\sqrt[4]{Eh^3/12(1-\mu^2)k}$ (radius of relative stiffness)","url_present"),

    ("arch_b2_023","RC橋脚耐震補強設計","Seismic Retrofit of RC Bridge Piers","RC橋脚耐震補強 / 鋼板巻立て / CFRPシート","既存RC橋脚の曲げ・せん断耐力不足を鋼板巻立て・RC巻立て・CFRPシート接着で補強する耐震補強設計法。","1995年兵庫県南部地震後に全国展開した道路橋耐震補強。道路橋示方書V耐震設計編に規定。","建築土木工学","橋梁耐震工学","1995",None,"設計手法","橋梁耐震補強","剛性・靱性不足部位・補強量","既存橋梁の耐震性能向上","鋼板巻立てとCFRPシートの耐久性比較はどうか","新設設計","耐震補強,RC橋脚,鋼板巻立て,CFRP,曲げ靱性","seismic retrofit,RC pier,steel jacket,CFRP,ductility","active","primary",92,9,"https://doi.org/10.1061/(ASCE)BE.1943-5592.0000325","東アジア",0.96,r"Target ductility: $\mu=\delta_u/\delta_y$; CFRP confinement: $f'_{cc}=f'_{co}(1+\psi_f \kappa_a k_l f_l/f'_{co})$; $f_l=2E_f t_f \varepsilon_{fe}/(D)$","url_present"),

    ("arch_b2_024","建築排煙設計・自然排煙・機械排煙","Building Smoke Control Design","自然排煙 / 機械排煙 / 排煙設備","火災時の煙の制御を自然排煙・機械排煙・防煙区画で設計する建築排煙設計法。避難安全検証法にも活用。","建築基準法・消防法に基づく排煙設備設計。超高層ビル・劇場・地下施設の安全確保に貢献。","建築土木工学","建築防火工学","1968",None,"設計手法","建築排煙・防火設計","天井高・開口面積・火源強度","建築物の煙制御・避難安全設計","機械排煙の風量はどの火源規模に対して設計するか","自然換気のみ","排煙,防煙,火災,建築基準法,避難安全","smoke control,fire,exhaust,natural ventilation,evacuation safety","active","primary",90,9,"https://doi.org/10.1016/j.firesaf.2014.03.006","東アジア",0.93,r"Smoke layer: $y_s = z_s/H$; $\dot{m}_{plume}=0.071Q_c^{1/3}z^{5/3}+0.0018Q_c$ (Zukoski); exhaust: $\dot{V}\ge \dot{m}_{plume}/\rho_s$","url_present"),

    ("arch_b2_025","プレキャストコンクリート接合部設計","Precast Concrete Connection Design","PC接合 / ループ継手 / グラウト継手","プレキャストコンクリート部材の接合部（ループ継手・グラウト継手・機械式継手）の剪断・引張・曲げ伝達性能を設計する手法。","東日本大震災後に普及したPC構造による迅速復旧建築および中高層PC建築の設計基礎。","建築土木工学","プレキャスト構造工学","1950",None,"設計手法","プレキャスト構造設計","接合部形式・鉄筋量・グラウト強度","PC建築・PC橋の接合部設計","地震時のPC接合部の性能確認手順はどうか","現場打設RC","プレキャスト,PC接合,グラウト,ループ継手,耐震","precast,PC connection,grout,loop joint,seismic","active","primary",89,9,"https://doi.org/10.1016/j.engstruct.2018.03.021","東アジア",0.91,r"Shear strength: $V_n = A_{cv}(\lambda\mu f_{pc} + \rho_t f_y) + V_u$; grout pocket: $\phi V_n \ge V_u$; dowel action: $V_{dowel}=1.3f_y A_s$","url_present"),

    ("arch_b2_026","地盤改良・深層混合処理設計","Deep Mixing Ground Improvement Design","CDM / 深層混合処理 / パイル状改良","セメントスラリーを地盤内に注入・攪拌して固化体（改良体）を形成し、軟弱地盤の支持力・液状化対策を行う深層混合処理設計。","関西国際空港・東京湾岸埋立地の基礎改良に適用。海上工事・港湾岸壁建設に不可欠。","建築土木工学","地盤改良工学","1975",None,"設計手法","軟弱地盤改良","軟弱層厚・改良体強度・改良体配置","海成粘土・有機質土の地盤改良設計","CDMとジェットグラウティングの改良体品質比較はどうか","表層改良・排水改良","CDM,深層混合処理,地盤改良,セメント固化,液状化対策","CDM,deep mixing,ground improvement,cement,liquefaction","active","primary",90,9,"https://doi.org/10.1680/geot.2001.51.1.79","東アジア",0.95,r"Composite ground: $q_u = \alpha_{c} q_{uc} + (1-\alpha_c)q_u^{soil}$; $\alpha_c$ = replacement ratio; unconfined strength: $q_{uc} \ge 200$ kN/m² (typical); settlement: $\rho = \rho_{initial}\times(1-\alpha_c E_c/(E_{eq}))$","url_present"),

    ("arch_b2_027","建築断熱設計・外皮性能（UA値・η値）","Building Thermal Insulation Design — UA and η Values","UA値 / η値 / 断熱等性能等級","建築物省エネ法に基づく外皮平均熱貫流率（UA値）と冷房期平均日射熱取得率（η値）を計算し、断熱等性能等級を評価する手法。","住宅断熱基準・ZEH（ゼロエネルギーハウス）の設計基礎。日本全国6地域区分に対応。","建築土木工学","建築環境工学","2013",None,"設計手法","住宅断熱設計","地域区分・外皮構成・開口部性能","新築住宅・ZEH設計の断熱性能確認","UA値とη値の同時最適化はトレードオフになるか","単純な壁厚増加","UA値,断熱,ZEH,外皮,η値,省エネ","UA value,thermal insulation,ZEH,building envelope,energy conservation","active","primary",91,9,"https://www.kenken.go.jp/becc/house.html","東アジア",0.97,r"$UA = \sum(A_i\cdot U_i+A_{j,L}\psi_j)/\sum A_i$; $\eta_{AC}=\sum(A_w\eta_{AH,w}f_s\nu)/\sum A$; ZEH target: $UA\le0.6$ (Region 4), $UA\le0.4$ (Region 2)","url_present"),

    ("arch_b2_028","RC建築物の耐震性能評価・Is値算定","Seismic Performance Evaluation of RC Buildings — Is Value","Is値 / 耐震診断","既存RC建築物の柱・壁の保有耐力・靱性・形状を総合評価した耐震指標Is値を算定し耐震補強要否を判定する手法。","1981年新耐震基準以前の建築物の耐震改修の基礎手法。学校・病院・官公庁施設の耐震化に全国展開。","建築土木工学","建築耐震工学","1977",None,"評価手法","既存建築耐震診断","柱・壁の配置・断面・コンクリート強度","耐震改修促進法に基づく既存建築耐震診断","Is≧0.6の判定基準はどのような根拠に基づくか","新設時の耐震設計","Is値,耐震診断,RC建築,耐震改修,新耐震","Is value,seismic diagnosis,RC building,seismic retrofit,Japan","active","primary",93,9,"https://doi.org/10.1080/13632469.2016.1160539","東アジア",0.97,r"$Is = E_0 \cdot S_D \cdot T$ where $E_0 = C_f \cdot F / \sqrt{Z}$; $C_f$ = strength index; $F$ = ductility index; $S_D$ = shape index; $T$ = time index; target $Is\ge0.6$","url_present"),

    ("arch_b2_029","鋼管杭・PHC杭の支持力設計","Steel Pipe Pile and PHC Pile Bearing Capacity Design","鋼管杭 / PHC杭 / 打撃貫入抵抗","鋼管杭・PHC杭（プレテンション高強度コンクリート杭）の先端支持力と周面摩擦力をN値相関式で設計する杭基礎設計法。","超高層ビル・橋梁基礎の杭工法として最も普及。道路橋示方書・建築基礎構造設計指針に規定。","建築土木工学","基礎工学","1960",None,"設計手法","杭基礎設計","N値・土質・杭径","高層ビル・橋梁の杭基礎設計","鋼管杭とPHC杭の経済的選択基準は","ケーソン基礎","鋼管杭,PHC杭,支持力,N値,杭基礎","steel pipe pile,PHC pile,bearing capacity,N value,pile foundation","active","primary",92,9,"https://doi.org/10.1139/t02-082","東アジア",0.94,r"AIJ: $R_u = q_p A_p + U\sum f_{si}L_i$; $q_p = 300N_p$ (sand, kPa); $f_s = 10N_s$ (sand, kPa); $f_c = c_u$ (clay); design: $R_d = R_u / SF$ ($SF=3$)","url_present"),

    ("arch_b2_030","建築構造計算・一貫計算プログラム","Structural Calculation by Integrated Software","一貫計算 / BUS / SEIN / SNAP","RC・鉄骨・S造建物の重力・地震・風荷重に対する部材断面・層間変形・保有水平耐力・応力・固有周期を統合的に算定する一貫構造計算プログラムの活用手法。","ほぼすべての中高層建築物設計に使用。国土交通省大臣認定プログラムとして行政審査に対応。","建築土木工学","建築構造設計","1980",None,"解析手法","建築構造一貫設計","柱・梁・壁・スラブの形状・材料・荷重","全建築種別の構造計算確認申請","一貫プログラムの出力と実際の挙動差をどう検証するか","手計算","一貫計算,構造計算,BUS,SEIN,保有水平耐力","structural calculation,integrated software,RC,seismic,Japan","active","primary",90,9,"https://www.bcj.or.jp/udp/","東アジア",0.96,r"Story drift: $\delta/h \le 1/200$ (serviceability); overturning: $D_s Q_{ud} \ge Q_{un}$; $D_s$ = structural characteristic factor; natural period: $T=0.02h$ (steel), $0.03h$ (RC)","url_present"),

    ("arch_b2_031","地震動観測・強震計ネットワーク・K-NET","Strong Motion Observation — K-NET and KiK-net","K-NET / KiK-net / 強震計","防災科研が運営するK-NET・KiK-netによる強震観測ネットワークで得られた地震動記録を工学的基盤（Vs30）で分類・整理・活用する地震動評価手法。","東日本大震災・能登半島地震の強震記録を収集。世界最密の強震ネットワークとして国際的に利用。","建築土木工学","地震工学","1996",None,"観測・評価手法","地震動観測・分析","Vs30・震源距離・地震規模","震源・サイト特性の地震動評価","表面波速度Vs30と増幅率の相関はどう設計に使うか","経験的式","K-NET,強震,Vs30,地震動,地震計","K-NET,strong motion,Vs30,seismic,ground amplification","active","primary",92,9,"https://www.kyoshin.bosai.go.jp/","東アジア",0.98,r"Site amplification: $A(f)=\sum_{i=1}^n \sqrt{(\rho_i V_{Si}+\rho_{i+1}V_{S,i+1})^2/(4\rho_i\rho_{i+1}V_{Si}V_{S,i+1})}$; Vs30 attenuation model: $\ln S_A = a_1+a_2 M+a_3\ln R + a_4 V_{s30}$","url_present"),

    ("arch_b2_032","海洋構造物設計・波力算定","Offshore Structure Design — Wave Force","Morison式 / 波力設計","細長い柱状部材に作用する波力をMorison方程式（慣性力+抗力）で算定し、海洋プラットフォーム・係留構造物の設計に適用する手法。","石油・ガス海洋プラットフォーム・港湾岸壁・洋上風力基礎の設計標準。API RP 2A規格に規定。","建築土木工学","海洋工学","1950",None,"設計手法","海洋構造物波力設計","波高・周期・海水密度・部材径","海洋プラットフォーム・洋上風力基礎の波力設計","Keuleghan-Carpenter数が慣性力と抗力の比率にどう影響するか","単純静水圧設計","Morison式,波力,海洋構造物,KC数,慣性力","Morison equation,wave force,offshore,KC number,inertia drag","active","primary",90,9,"https://doi.org/10.2118/1992-PA","グローバル",0.88,r"Morison: $F = C_M \rho \frac{\pi D^2}{4}\dot{u} + \frac{1}{2}C_D \rho D u|u|$; $KC = U_m T/D$; $C_M\approx2$ (slender), $C_D\approx1$ (circular); $u=\frac{\pi H}{T}\frac{\cosh k(z+d)}{\sinh kd}\cos(\omega t)$","url_present"),

    ("arch_b2_033","建築設備BIM・MEP統合設計","Building MEP BIM Integrated Design","MEP BIM / Revit MEP / 干渉チェック","Revit MEP・AutoCAD MEPを用いて給排水・空調・電気設備を3D BIMモデルに統合し、建築・構造との干渉チェックと施工図作成を効率化する設計手法。","大型病院・空港・データセンター建設の設備設計効率化に貢献。省力化率30-50%の実績。","建築土木工学","建築設備設計","2010",None,"設計手法","建築設備統合設計","建築・構造BIMモデル・設備仕様","大規模建築の給排水・空調・電気設計","MEP干渉チェックをいつ行うと最もコストが安いか","2D CAD設計","MEP,BIM,干渉チェック,Revit,設備統合","MEP,BIM,clash detection,Revit,MEP integration","active","primary",89,9,"https://doi.org/10.1016/j.autcon.2020.103386","東アジア",0.92,r"Clash volume: $V_{clash}=\sum|B_{i}\cap B_{j}|$; LOD 300 MEP: duct $\pm10$ mm tolerance; BIM maturity: Level 2 (federated) to Level 3 (integrated); ROI: 30-50% rework reduction","url_present"),

    ("arch_b2_034","港湾施設設計・重力式岸壁","Port Facility Design — Gravity Quay Wall","重力式岸壁 / ケーソン / 直立堤","ケーソン・矢板・重力ブロックを用いた重力式岸壁の滑動・転倒・支持力安全率を算定する港湾施設設計法。","国内主要港湾・離島港の基幹施設。港湾技術基準（国土交通省）に規定。","建築土木工学","港湾工学","1960",None,"設計手法","港湾岸壁設計","設計波高・土圧・地盤支持力","商業港・漁港・工業港の岸壁設計","耐震強化岸壁への改修設計のポイントはどこか","矢板式岸壁","岸壁,ケーソン,港湾,重力式,直立堤","quay wall,caisson,port,gravity type,vertical breakwater","active","primary",88,9,"https://www.nilim.go.jp/lab/bcg/siryou/tnn/tnn0992.htm","東アジア",0.93,r"Sliding FS: $F_s = (\mu W - P_u) / (P_H + P_{wave})$; overturning: $F_o = \sum M_R/\sum M_O$; $\mu$ = friction coeff 0.5-0.6; wave pressure: Goda formula $p_1 = 0.5(1+\cos\beta)\alpha_1\rho g H_D$","url_present"),

    ("arch_b2_035","市街地防災・避難シミュレーション","Urban Disaster Evacuation Simulation","避難シミュレーション / 人流解析 / エージェントモデル","大規模災害時の市街地避難行動をエージェントベースモデルで再現し、避難経路・避難所容量・交通渋滞を定量評価する都市防災解析手法。","東日本大震災・熊本地震の避難計画改善に活用。都市計画・防災マスタープランに反映。","建築土木工学","都市防災計画","2000",None,"解析手法","都市防災計画","人口分布・道路ネットワーク・避難施設","市街地の地震・津波・洪水避難計画策定","車中心避難と徒歩避難の混在をどうモデル化するか","単純距離計算","避難シミュレーション,エージェント,防災,市街地,人流","evacuation simulation,agent-based,urban disaster,shelter,pedestrian","active","primary",87,9,"https://doi.org/10.1016/j.ijdmb.2018.01.001","東アジア",0.92,r"Social force: $m_i\dot{v}_i = m_i\frac{v_i^0 e_i - v_i}{\tau}+\sum_j f_{ij}+\xi_i$; $f_{ij}=\{A_i\exp[(r_{ij}-d_{ij})/B_i]+kg(r_{ij}-d_{ij})\}n_{ij}$","url_present"),

    ("arch_b2_036","地盤沈下・圧密沈下予測","Ground Settlement and Consolidation Prediction","Terzaghi圧密理論 / 二次圧密","Terzaghi一次元圧密理論による最終沈下量・沈下速度の予測および二次圧密（クリープ）の長期沈下推定手法。","軟弱地盤上の道路・空港・港湾施設の沈下管理の基礎。関西国際空港の不等沈下対策に適用。","建築土木工学","地盤工学","1925",None,"評価手法","軟弱地盤沈下管理","圧密降伏応力・圧縮指数・透水係数","軟弱地盤上の構造物沈下予測","即時沈下・一次圧密・二次圧密の時間割合はどう区分するか","経験的沈下公式","圧密沈下,Terzaghi,圧縮指数,二次圧密,軟弱地盤","consolidation,Terzaghi,compression index,creep,soft ground","active","primary",91,9,"https://doi.org/10.1061/JGEFBD.GENG-3456","グローバル",0.89,r"Final settlement: $S_c = \frac{C_c H}{1+e_0}\log\frac{\sigma'_0+\Delta\sigma'}{\sigma'_0}$; degree: $U_z = 1-\sum\frac{2}{M^2}\exp(-M^2 T_v)$; $T_v = c_v t/H_{dr}^2$","url_present"),

    ("arch_b2_037","超高層鉄骨構造・柱梁仕口設計","High-Rise Steel Frame — Column-Beam Connection Design","梁端プレート接合 / ダイアフラム方式","超高層鋼構造の柱梁仕口（ダイアフラム方式・通しダイアフラム・内ダイアフラム）の溶接・ボルト設計と引張・せん断・曲げ伝達を確保する接合設計法。","日本の超高層ビル（六本木ヒルズ・あべのハルカス等）の標準接合設計。AIJ鉄骨工事技術指針に規定。","建築土木工学","鋼構造工学","1970",None,"設計手法","鋼構造接合部設計","柱断面・梁端モーメント・溶接条件","高層鉄骨建物の柱梁接合部設計","完全溶込溶接と部分溶込溶接の選択基準はどうか","単純梁接合","ダイアフラム,柱梁仕口,超高層鋼構造,溶接,接合部","diaphragm,column-beam joint,steel,high-rise,welded connection","active","primary",90,9,"https://doi.org/10.1061/(ASCE)ST.1943-541X.0001234","東アジア",0.94,r"Panel zone shear: $V_{pz} = M_{b1}/d_{b1}+M_{b2}/d_{b2}$; full-pen weld: $T_u \le \phi_w A_w F_y / \sqrt{3}$; diaphragm thickness: $t_d \ge t_f + 5$ mm","url_present"),

    ("arch_b2_038","建築設備機器選定・風量・冷暖房負荷計算","HVAC Load Calculation — Room Cooling/Heating","冷暖房負荷計算 / 空調設備設計","建築物の冷暖房熱負荷（顕熱・潜熱）をペリメータ・インテリアゾーン別に計算し、空調システム（チラー・AHU・ファンコイル）容量を選定する設計手法。","省エネビル・ゼロエミッションビルの空調設計基礎。建築物省エネ法の一次エネルギー消費量計算に利用。","建築土木工学","建築設備設計","1960",None,"設計手法","建築空調設備設計","外気条件・室内発熱・断熱性能","ビル・工場・病院の空調設備容量設計","冷房設計日はどの外気条件（TAC温度）で設定するか","簡易面積比例法","冷房負荷,暖房負荷,空調,チラー,AHU,TAC温度","cooling load,heating load,HVAC,chiller,AHU,TAC temperature","active","primary",90,9,"https://doi.org/10.1016/j.enbuild.2018.09.001","東アジア",0.92,r"Cooling load: $q_{cl} = q_{wall}+q_{window}+q_{person}+q_{light}+q_{equip}+q_{OA}$; $q_{wall}=UA\Delta T_{sol-air}$; $CLTD$ (Cooling Load Temperature Difference) method","url_present"),

    ("arch_b2_039","橋梁ケーブル張力管理・斜張橋設計","Cable-Stayed Bridge Cable Force Management","斜張橋 / ケーブル張力 / 初期形状解析","斜張橋の主桁・主塔・ケーブルの初期形状解析（初期ケーブル張力の最適化）と施工時の変形制御を行う設計手法。","東京港臨海橋・明石海峡大橋等の長大橋設計の中核技術。国際構造工学連盟（IABSE）の標準設計法。","建築土木工学","橋梁工学","1960",None,"設計手法","斜張橋・吊橋設計","スパン長・塔高・ケーブル配置","長大斜張橋のケーブル力設計","ケーブル張力の不均衡が主桁たわみに与える影響はどれほどか","単純桁橋","斜張橋,ケーブル張力,吊橋,初期形状,長大橋","cable-stayed,cable force,suspension bridge,initial shape,long-span","active","primary",90,9,"https://doi.org/10.1016/j.engstruct.2019.109457","東アジア",0.91,r"Cable catenary: $T = T_H\sqrt{1+(wL/2T_H)^2}$; initial force optimization: $\min \|A\mathbf{T}-\mathbf{F}\|^2$ s.t. $T_i>0$; compatibility: $\delta_{target} = \sum_i(T_i/EA_i)L_i\cos\theta_i$","url_present"),

    ("arch_b2_040","建築音環境設計・遮音・吸音","Building Acoustics Design — Sound Insulation and Absorption","遮音設計 / D値 / 吸音設計","集合住宅・オフィス・コンサートホールの遮音（D値・STC）・吸音（NRC・α値）・残響時間（Sabine式）を設計する建築音環境手法。","建築基準法・品確法の遮音性能等級。コンサートホール・スタジオの音響設計に適用。","建築土木工学","建築環境工学","1900",None,"設計手法","建築音響設計","室容積・仕上げ材吸音率・遮音構造","住宅・ホール・スタジオの音環境設計","残響時間の最適値はホールのタイプでどう異なるか","単純騒音対策","遮音,吸音,残響時間,D値,音響設計","sound insulation,absorption,reverberation time,D value,room acoustics","active","primary",89,9,"https://doi.org/10.1121/1.4962475","グローバル",0.87,r"Sabine: $T_{60}=0.161V/A$; $A=\sum S_i\alpha_i$ [m²]; mass law: $TL=20\log_{10}(fM)-47$ [dB]; D value: $D_{nT,w}\ge45$ (bedroom, Japan)","url_present"),

    ("arch_b2_041","地盤地震応答解析・SHAKE法","Site Response Analysis — SHAKE Method","SHAKE / 等価線形法","地震波が基盤から地表面まで伝播する際の増幅特性を等価線形法（SHAKE）でひずみ依存のせん断剛性・減衰を反復収束させて評価する地盤応答解析手法。","液状化評価・建築物設計用地震動評価の基礎手法。道路橋示方書・建築物の耐震計算に採用。","建築土木工学","地震工学","1972",None,"解析手法","地盤応答・地震動評価","地盤柱状図・Vs分布・設計地震動","軟弱地盤上の建築物設計用地震動評価","等価線形法と非線形解析の使い分け基準はどうか","一様地盤仮定","SHAKE,地盤応答,等価線形,せん断剛性,減衰","SHAKE,site response,equivalent linear,shear modulus,damping","active","primary",92,9,"https://doi.org/10.1061/(ASCE)GT.1943-5606.0000111","グローバル",0.90,r"Transfer function: $H(f)=\frac{u(f,z=0)}{u_{input}(f)}$; complex modulus: $G^* = G(\gamma)(1+2i\xi(\gamma))$; convergence: $|\gamma-\gamma_{eff}|/\gamma<\epsilon=0.01$","url_present"),

    ("arch_b2_042","地熱発電・BINARY サイクル設計","Geothermal Binary Power Plant Design","バイナリーサイクル / ORC","地熱流体（100-170℃の低温熱水）を作動流体（イソペンタン・アンモニア）で熱交換し二次冷媒で発電するORC（有機ランキンサイクル）地熱バイナリー発電設計。","東北・九州の温泉地・地熱地帯での小規模地熱発電に適用。地熱エネルギー利用の裾野拡大。","建築土木工学","エネルギー工学","1970",None,"設計手法","地熱バイナリー発電設計","地熱流体温度・流量・冷却条件","温泉地・低温地熱資源の発電設計","作動流体の選択はどの性能指標で最適化するか","高温蒸気地熱発電","バイナリー,ORC,地熱発電,有機ランキン,低温熱水","binary cycle,ORC,geothermal,organic Rankine,low-temperature","active","primary",87,9,"https://doi.org/10.1016/j.geothermics.2016.04.001","東アジア",0.90,r"ORC efficiency: $\eta_{th} = W_{net}/Q_{in}$; $W_{net}=\dot{m}[(h_1-h_2)-(h_4-h_3)]$; Carnot: $\eta_C = 1-T_L/T_H$; pinch constraint: $T_{geo,out}\ge T_{wf,in}+\Delta T_{pp}$","url_present"),

    ("arch_b2_043","建築物の長期変形・クリープ解析","Long-term Deformation and Creep Analysis of RC Buildings","クリープ,乾燥収縮 / CEB-FIP MC","RCおよびPCコンクリートのクリープ・乾燥収縮による長期変形をCEB-FIP Model Codeモデルで経時的に予測する解析手法。","超高層RC建築の柱・壁の長期圧縮変形管理および床スラブたわみの設計基礎。","建築土木工学","コンクリート工学","1970",None,"解析手法","超高層RC建築の長期変形","コンクリート配合・湿度・部材寸法","超高層RC建築の長期変形設計","クリープと乾燥収縮はどちらが長期変形に大きく寄与するか","弾性計算のみ","クリープ,乾燥収縮,長期変形,RC,CEB-FIP","creep,shrinkage,long-term deformation,RC,CEB-FIP","active","primary",88,9,"https://doi.org/10.1617/s11527-016-0958-7","東アジア",0.90,r"CEB-FIP: $\varepsilon_{cc}(t,t_0)=\sigma(t_0)\phi(t,t_0)/E_{ci}$; $\phi(t,t_0)=\phi_{RH}\beta(f_{cm})\beta(t_0)\beta_c(t-t_0)$; shrinkage: $\varepsilon_{cs}(t,t_s)=\varepsilon_{cso}\beta_s(t-t_s)$","url_present"),

    ("arch_b2_044","建設副産物リサイクル・再生骨材コンクリート","Construction By-product Recycling — Recycled Aggregate Concrete","再生骨材コンクリート / JIS A 5021","解体コンクリートを破砕して製造した再生骨材（H・M・L）を用いたリサイクルコンクリートの品質管理・配合設計・適用範囲設計法。","建設廃棄物リサイクル率96.9%（2020年）達成に貢献。循環型社会形成に向けた公共工事での活用が進む。","建築土木工学","環境建設工学","1995",None,"設計手法","再生コンクリート設計","再生骨材品質区分・用途・耐久性要求","解体コンクリートの循環利用設計","再生骨材のグレードHとLで圧縮強度・吸水率はどれほど違うか","天然骨材使用","再生骨材,リサイクルコンクリート,JIS,建設廃棄物,循環型","recycled aggregate,recycled concrete,JIS,construction waste,circular","active","primary",90,9,"https://www.mlit.go.jp/sogoseisaku/region/recycle/","東アジア",0.95,r"Water absorption correction: $W_{eff}=W_{table}+A_{fa}(Q_{fa}/100)+A_{ca}(Q_{ca}/100)$; strength reduction: $f'_{cr} = k\cdot f'_{c,natural}$ ($k=0.8-0.95$ for grade H); CO₂ reduction: ~30% vs virgin aggregate","url_present"),

    ("arch_b2_045","建物エネルギーシミュレーション・EnergyPlus","Building Energy Simulation — EnergyPlus","EnergyPlus / TRNSYS / DesignBuilder","EnergyPlus・TRNSYSなどのダイナミックシミュレーションソフトによる建築物の時刻別熱負荷・空調エネルギー・再生可能エネルギー統合の詳細シミュレーション設計手法。","ZEB・LEED・BREEAMのエネルギー消費量認定の根拠計算に使用。DOE・ASHRAE基準に準拠。","建築土木工学","建築環境工学","1978",None,"解析手法","省エネビル・ZEB設計","建築外皮・設備仕様・気象データ","ZEB認定・CASBEE評価のエネルギー計算","EnergyPlusとASHRAE 90.1の相互検証はどのように行うか","簡易月計算法","EnergyPlus,TRNSYS,ZEB,BEM,CASBEE","EnergyPlus,TRNSYS,ZEB,building energy simulation,ASHRAE","active","primary",91,9,"https://energyplus.net/","東アジア",0.92,r"$Q_{annual}=\int_0^{8760}(Q_{cool}(t)+Q_{heat}(t))dt$; heat balance: $q_{cond}+q_{conv}+q_{rad}+q_{sol}+q_{gen}=0$; ideal loads: $Q_{ideal}=\dot{m}_{OA}c_p(T_{OA}-T_{zone})$","url_present"),

    ("arch_b2_046","木造軸組工法の耐震設計","Timber Frame Seismic Design — Japanese Post-and-Beam","木造軸組,許容応力度計算,壁量計算","日本の在来木造軸組工法の耐震設計において、壁量計算・四分割法・N値計算・許容応力度計算・限界耐力計算の各手法を適用する設計法。","2000年建築基準法改正後の木造耐震設計標準。熊本地震で四分割法の有効性が確認された。","建築土木工学","木構造設計","1924",None,"設計手法","木造住宅耐震設計","壁量・耐力壁配置・床倍率","木造住宅の耐震設計","N値計算と許容応力度計算の相違はどこか","鉄筋コンクリート設計","木造,耐震,壁量計算,軸組,N値","timber frame,seismic,wall quantity,post-and-beam,N value","active","primary",91,9,"https://doi.org/10.1080/13632469.2019.1589536","東アジア",0.97,r"Required wall: $l_{req} = Z \cdot N_{floor} \cdot A_{floor}$; N value: $N = A_u - B_l$ (ratio of uplift to bearing); drift limit: $\delta/h \le 1/120$ (allowable stress)","url_present"),

    ("arch_b2_047","トンネル覆工設計・ライニング厚","Tunnel Lining Design — Lining Thickness","覆工設計 / 山岳トンネル / フリンジ法","山岳トンネルの2次覆工（コンクリートライニング）の厚さ・配筋を地山荷重・地下水圧・周辺条件で設計する覆工設計手法。","日本道路公団（現NEXCO）・鉄道・水道トンネルの設計標準。NATM支保パターンと組み合わせて使用。","建築土木工学","トンネル工学","1960",None,"設計手法","山岳トンネル覆工設計","地山等級・覆工荷重・コンクリート強度","道路・鉄道・水路トンネルの覆工設計","覆工厚30cmと40cmで設計支配要因はどう変わるか","無覆工トンネル","トンネル覆工,ライニング,山岳トンネル,覆工厚,NATM","tunnel lining,mountain tunnel,NATM,lining thickness,shotcrete","active","primary",89,9,"https://doi.org/10.1016/j.tust.2015.07.011","東アジア",0.93,r"Bedded beam-spring: $M=q\cdot R^2\cdot\beta(\theta)$; lining thickness: $t\ge R(1-\sqrt{1-q/(q+\sigma_{allow}/R)})$; minimum: 30 cm (road), 25 cm (railway)","url_present"),

    ("arch_b2_048","街路景観設計・D/H比・エンクロージャー","Streetscape Design — D/H Ratio and Enclosure","D/H比 / 囲み率 / 景観設計","街路の幅員Dと建物高さHの比（D/H）および囲み率を指標として、歩行者スケールの街路空間の包囲感・開放感・快適性を設計・評価する都市景観設計手法。","東京・京都の景観計画・地区計画に適用。ジェイン・ジェイコブズの路地研究と接続。","建築土木工学","都市デザイン・景観","1960",None,"設計手法","都市街路景観設計","道路幅員・建物高さ・沿道用途","歴史市街地・商業地の景観形成計画","D/H≒1の場合の快適性スコアはどの調査で確認されているか","機能的道路設計","D/H比,囲み率,街路景観,歩行者,都市設計","D/H ratio,enclosure,streetscape,pedestrian,urban design","active","primary",87,9,"https://doi.org/10.1080/13574800701803827","グローバル",0.86,r"Enclosure: $E = 1 - (sky view factor)$; $D/H$ optimal range 1-4; SVF: $\Psi = 1-\sum_{i}\sin^2\beta_i \Delta\phi_i/(2\pi)$; comfort: $\bar{T}_{mrt}-T_{air}$ influenced by $E$","url_present"),

    ("arch_b2_049","建築外装カーテンウォール設計","Building Curtain Wall Design","カーテンウォール / ユニット工法 / スティック工法","超高層ビルのガラス・アルミ製カーテンウォール（ユニット工法・スティック工法）の風圧・地震・熱伸縮・防水性能の設計と性能試験手法。","六本木ヒルズ・汐留・丸の内の超高層ビルに採用。AAMA・JIS A 4706規格に準拠。","建築土木工学","建築外装工学","1950",None,"設計手法","超高層ビル外装設計","設計風圧・地震層間変位・熱膨張量","超高層ビルのカーテンウォール設計","ユニット工法とスティック工法の現場施工効率比較はどうか","RC外壁","カーテンウォール,超高層,ユニット工法,ガラス,風圧","curtain wall,high-rise,unit system,glass,wind pressure","active","primary",88,9,"https://doi.org/10.1016/j.engstruct.2017.10.033","東アジア",0.91,r"Wind load: $p = q_H C_p G_f$; inter-story drift accommodation: $\delta_{allow}=h/200$ (story height/200); thermal expansion: $\Delta L = \alpha \Delta T L$ (aluminum: $\alpha=23\times10^{-6}$/°C)","url_present"),

    ("arch_b2_050","地域熱供給システム設計・DHC","District Heating and Cooling System Design","地域熱供給 / DHC / 熱ネットワーク","地域熱供給（DHC）システムの熱源機器（チラー・ヒートポンプ・コジェネ）・熱輸送配管ネットワーク・需要側の熱負荷を最適化する都市スケールのエネルギーシステム設計法。","東京都心・大阪・横浜みなとみらいのDHCに採用。CO₂排出削減・省エネ効果が確認済み。","建築土木工学","都市エネルギー工学","1975",None,"設計手法","都市地域冷暖房設計","熱需要密度・導管距離・熱源種別","都市再開発地区の地域熱供給システム設計","蓄熱槽の容量はどのように需要変動に合わせて最適化するか","個別空調","地域熱供給,DHC,チラー,コジェネ,都市エネルギー","DHC,district heating cooling,chiller,cogeneration,urban energy","active","primary",89,9,"https://doi.org/10.1016/j.energy.2018.02.118","東アジア",0.94,r"Pipe heat loss: $q_l = U\pi D(T_s-T_g)$; pump energy: $W_p = \dot{m}\Delta p/\rho\eta_p$; system COP: $COP_{sys}=Q_{DHC}/W_{total}$; $\Delta T_{return}$ target 5-8°C for efficiency","url_present"),
]

if __name__ == "__main__":
    inserted, skipped = insert_records(records)
    print(f"Inserted: {inserted}, Skipped: {skipped}")
    import sqlite3 as sq
    conn = sq.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Total: {total}")
