"""Phase 2 Part 2: 残り 9 subfield × 10 entries = 90 entries"""
import json
import sys
sys.path.insert(0, '/tmp/academic-build/team-4')
from gen_lib import row

ALL = []

def add(items):
    ALL.extend(items)

# 6. market_entry (BDBM_051-060)
add([
    dict(id="BDBM_051", name_ja="アンゾフ・マトリクス", name_en="Ansoff Matrix",
         definition="製品 (既存/新規) × 市場 (既存/新規) の 2×2 で成長戦略を 4 類型 (市場浸透・市場開発・製品開発・多角化) に分類する古典的枠組み。",
         impact_summary="戦略論の基礎フレーム、教育的影響大",
         subfield="market_entry", school_of_thought="Growth Matrix", era_start=1957,
         keywords_ja="成長戦略, 多角化", keywords_en="growth strategy, diversification",
         key_researchers=["Ansoff, H.I."],
         key_works=[{"title":"Strategies for Diversification","year":1957,"venue":"Harvard Business Review"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=2,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_052", name_ja="ポーター 5 forces", name_en="Porter's Five Forces (Entry Barriers)",
         definition="新規参入の脅威・買い手交渉力・供給者交渉力・代替品脅威・競合度の 5 力で産業構造を分析。参入障壁の概念を体系化。",
         impact_summary="戦略分析の標準フレーム、引用数 10万超",
         subfield="market_entry", school_of_thought="Industry Analysis", era_start=1980,
         keywords_ja="5フォース, 参入障壁", keywords_en="five forces, entry barriers",
         key_researchers=["Porter, M.E."],
         key_works=[{"title":"Competitive Strategy","year":1980,"venue":"Free Press"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_053", name_ja="新興市場での勝ち筋 (Khanna-Palepu)", name_en="Winning in Emerging Markets",
         definition="新興市場の制度的空隙 (institutional voids) を分析し、現地適応・グローバル統合のバランスで参入戦略を設計する枠組み。",
         impact_summary="新興市場戦略論の代表的書籍",
         subfield="market_entry", school_of_thought="Emerging Markets", era_start=2010,
         keywords_ja="新興市場, 制度的空隙", keywords_en="emerging markets, institutional voids",
         key_researchers=["Khanna, T.","Palepu, K."],
         key_works=[{"title":"Winning in Emerging Markets","year":2010,"venue":"HBS Press"}],
         industry_applicability=["B2C","B2B"], case_companies=["Tata","Reliance"], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_054", name_ja="BoP (ピラミッドの底辺) 戦略 (批判)", name_en="Bottom of the Pyramid Strategy",
         definition="世界の貧困層 40 億人を市場として捉え、低価格・高量・現地適応で価値を創造する戦略。従来の市場参入論への批判的代替案。",
         impact_summary="新興国・低所得層戦略論として影響大",
         subfield="market_entry", school_of_thought="BoP", era_start=2005,
         keywords_ja="BoP, ピラミッドの底辺", keywords_en="BoP, bottom of pyramid",
         key_researchers=["Prahalad, C.K."],
         key_works=[{"title":"The Fortune at the Bottom of the Pyramid","year":2004,"venue":"Wharton School"}],
         industry_applicability=["B2C"], case_companies=["Hindustan Unilever","Grameen Bank"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_055", name_ja="参入モード選択", name_en="Market Entry Mode Choice",
         definition="輸出・ライセンス・JV・買収・グリーンフィールドのいずれを選ぶかを内部化理論・取引コスト論で説明する研究領域。",
         impact_summary="国際経営論の中核トピック",
         subfield="market_entry", school_of_thought="Internationalization", era_start=1986,
         keywords_ja="参入モード, 内部化", keywords_en="entry mode, internalization",
         key_researchers=["Anderson, E.","Gatignon, H."],
         key_works=[{"title":"Modes of Foreign Entry: A Transaction Cost Analysis","year":1986,"venue":"Journal of International Business Studies"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_056", name_ja="ボーン・グローバル", name_en="Born Globals",
         definition="創業初期から国際展開する小規模・若年企業を対象とする研究分野。インターネット・グローバル化が促進。",
         impact_summary="国際起業論の主要研究領域",
         subfield="market_entry", school_of_thought="International Entrepreneurship", era_start=2004,
         keywords_ja="ボーングローバル, 国際起業", keywords_en="born global, international entrepreneurship",
         key_researchers=["Knight, G.A.","Cavusgil, S.T."],
         key_works=[{"title":"Innovation, Organizational Capabilities, and the Born-Global Firm","year":2004,"venue":"Journal of International Business Studies"}],
         industry_applicability=["All"], case_companies=["Skype","Spotify"], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_057", name_ja="Beachhead 戦略", name_en="Beachhead Strategy",
         definition="新市場参入時に小さな足場 (beachhead) 市場を確立し、隣接市場へ拡張していく段階的戦略。Crossing the Chasm 系で発展。",
         impact_summary="スタートアップの市場参入実務として広く利用",
         subfield="market_entry", school_of_thought="Sequenced Entry", era_start=1991,
         keywords_ja="ビーチヘッド, 段階拡張", keywords_en="beachhead, sequenced",
         key_researchers=["Moore, G.A."],
         key_works=[{"title":"Crossing the Chasm","year":1991,"venue":"HarperBusiness"}],
         industry_applicability=["B2B","B2C"], case_companies=["Salesforce","Tesla"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_058", name_ja="Land-and-Expand", name_en="Land-and-Expand Strategy",
         definition="まず小規模で顧客に入り込み (land)、その後アカウント内で拡張する (expand) B2B SaaS の典型成長戦略。",
         impact_summary="エンタープライズ SaaS 成長の標準モデル",
         subfield="market_entry", school_of_thought="SaaS GTM", era_start=2014,
         keywords_ja="land-expand, アカウント拡張", keywords_en="land-and-expand",
         key_researchers=["Skok, D."],
         key_works=[{"title":"The SaaS Guide","year":2014,"venue":"For Entrepreneurs (blog)"}],
         industry_applicability=["B2B"], case_companies=["Slack","Zoom","Atlassian"], implementation_complexity=3,
         source_reliability="tertiary", data_completeness=80),

    dict(id="BDBM_059", name_ja="アジャシエンシー戦略", name_en="Adjacency Strategy",
         definition="中核事業から地理・顧客・製品・チャネルなどの隣接領域 (adjacency) に系統的に拡張する成長戦略。Bain の Zook フレーム。",
         impact_summary="多角化戦略の実証的・体系的研究",
         subfield="market_entry", school_of_thought="Adjacency", era_start=2004,
         keywords_ja="隣接拡張, アジャシェンシー", keywords_en="adjacency expansion",
         key_researchers=["Zook, C."],
         key_works=[{"title":"Beyond the Core","year":2004,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["Nike","Apple"], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_060", name_ja="マーケットセグメンテーション", name_en="Market Segmentation",
         definition="市場を顧客ニーズ・行動・特性で分割し、各セグメントに最適化された価値提案を設計するマーケティング基本概念。",
         impact_summary="マーケティング論の出発点、教育的影響大",
         subfield="market_entry", school_of_thought="Marketing", era_start=1978,
         keywords_ja="セグメンテーション, ターゲティング", keywords_en="segmentation, targeting",
         key_researchers=["Wind, Y."],
         key_works=[{"title":"Issues and Advances in Segmentation Research","year":1978,"venue":"Journal of Marketing Research"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),
])

# 7. open_innov (BDBM_061-070)
add([
    dict(id="BDBM_061", name_ja="オープンイノベーション", name_en="Open Innovation",
         definition="企業がアイデア・技術を内外双方向に流通させ、価値創造・獲得を加速するイノベーションパラダイム。Closed innovation との対比。",
         impact_summary="イノベーション・マネジメントの中心パラダイム",
         subfield="open_innov", school_of_thought="Open Innovation Theory", era_start=2003,
         keywords_ja="オープンイノベ, 内外流通", keywords_en="open innovation, inflows outflows",
         key_researchers=["Chesbrough, H."],
         key_works=[{"title":"Open Innovation: The New Imperative for Creating and Profiting from Technology","year":2003,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["P&G","Lego","NASA"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_062", name_ja="オープンイノベーション研究パラダイム", name_en="Open Innovation: Researching a New Paradigm",
         definition="OI 研究の理論基盤・方法論・将来課題を整理した編著。研究領域としての OI を学術的に確立。",
         impact_summary="OI 研究の出発点として最も引用される編著",
         subfield="open_innov", school_of_thought="Research Paradigm", era_start=2006,
         keywords_ja="OIパラダイム, 編著", keywords_en="OI paradigm, edited volume",
         key_researchers=["Chesbrough, H.","Vanhaverbeke, W.","West, J."],
         key_works=[{"title":"Open Innovation: Researching a New Paradigm","year":2006,"venue":"Oxford University Press"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_063", name_ja="OI 研究ランドスケープ (Bogers et al.)", name_en="The Open Innovation Research Landscape",
         definition="OI 研究の 7 領域 (個人/グループ/組織/産業/領域/政策/方法論) を統合的に整理した代表的レビュー論文。",
         impact_summary="OI 研究の現代的整理として標準参照",
         subfield="open_innov", school_of_thought="Meta-research", era_start=2017,
         keywords_ja="OIレビュー, 7領域", keywords_en="OI review, seven domains",
         key_researchers=["Bogers, M.","Chesbrough, H.","Moedas, C."],
         key_works=[{"title":"Open Innovation: Research, Practices, and Policies","year":2018,"venue":"California Management Review"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_064", name_ja="「OI は古い酒の新しい瓶」批判", name_en="Old Wine in New Bottles Critique",
         definition="OI が言うほど新しい現象ではなく、過去の研究 (R&D outsourcing, technology transfer) で既に分析されてきたと主張する批判論文。",
         impact_summary="OI 概念の独自性に疑問を投じた重要批判",
         subfield="open_innov", school_of_thought="Critical Open Innovation", era_start=2009,
         keywords_ja="OI批判, 概念新規性", keywords_en="OI critique, novelty",
         key_researchers=["Trott, P.","Hartmann, D."],
         key_works=[{"title":"Why 'Open Innovation' is old wine in new bottles","year":2009,"venue":"International Journal of Innovation Management"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_065", name_ja="Outside-In プロセス", name_en="Outside-In Process",
         definition="外部知識・技術を企業内に取り込み、自社のイノベーションを加速するプロセス。OI の主要 2 流のうちの 1 つ。",
         impact_summary="OI 実装の主流形態、buy-in scouting・licensing 等",
         subfield="open_innov", school_of_thought="OI Direction", era_start=2003,
         keywords_ja="アウトサイドイン, 取り込み", keywords_en="outside-in, inbound",
         key_researchers=["Chesbrough, H."],
         key_works=[{"title":"Open Innovation","year":2003,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["P&G Connect+Develop"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_066", name_ja="Inside-Out プロセス", name_en="Inside-Out Process",
         definition="社内に眠るアイデア・技術を外部に開放し、ライセンス・スピンオフ・コンソーシアム経由で価値化するプロセス。",
         impact_summary="使われない IP の収益化として広く実装",
         subfield="open_innov", school_of_thought="OI Direction", era_start=2003,
         keywords_ja="インサイドアウト, 外部化", keywords_en="inside-out, outbound",
         key_researchers=["Chesbrough, H."],
         key_works=[{"title":"Open Innovation","year":2003,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["Xerox PARC spinoffs","IBM patent licensing"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_067", name_ja="クラウドソーシング", name_en="Crowdsourcing",
         definition="不特定多数のオンラインコミュニティに業務・アイデア生成を委託する手法。Howe による造語。OI のチャネルの 1 つ。",
         impact_summary="OI 実装の主要メカニズムとして普及",
         subfield="open_innov", school_of_thought="Crowd Innovation", era_start=2006,
         keywords_ja="クラウドソーシング, 群衆知", keywords_en="crowdsourcing, wisdom of crowds",
         key_researchers=["Howe, J."],
         key_works=[{"title":"The Rise of Crowdsourcing","year":2006,"venue":"Wired"}],
         industry_applicability=["All"], case_companies=["InnoCentive","Wikipedia","Threadless"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_068", name_ja="イノベーション仲介者", name_en="Innovation Intermediaries",
         definition="技術探索者と技術保有者を結ぶ第三者プラットフォーム (NineSigma, InnoCentive 等)。OI の市場メカニズムを担う。",
         impact_summary="OI エコシステムのインフラとして実証研究多数",
         subfield="open_innov", school_of_thought="Intermediation", era_start=2006,
         keywords_ja="仲介者, 技術市場", keywords_en="intermediary, technology market",
         key_researchers=["Howells, J."],
         key_works=[{"title":"Intermediation and the role of intermediaries in innovation","year":2006,"venue":"Research Policy"}],
         industry_applicability=["B2B"], case_companies=["NineSigma","InnoCentive","yet2.com"], implementation_complexity=3,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_069", name_ja="ユーザーイノベーション", name_en="User Innovation (von Hippel)",
         definition="製品ユーザー自身がイノベーションを生み出す現象。リード・ユーザー法・toolkits-for-users などの方法論を含む。",
         impact_summary="OI に先行する重要理論流れ、引用数巨大",
         subfield="open_innov", school_of_thought="User Innovation", era_start=1988,
         keywords_ja="ユーザーイノベ, リードユーザー", keywords_en="user innovation, lead user",
         key_researchers=["von Hippel, E."],
         key_works=[{"title":"The Sources of Innovation","year":1988,"venue":"Oxford University Press"}],
         industry_applicability=["All"], case_companies=["3M","Mountain bike industry"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_070", name_ja="オープンビジネスモデル", name_en="Open Business Model",
         definition="OI を BM レベルで体系化し、価値創造・獲得の両方を外部協創で行う BM。Chesbrough の OI 第 2 弾の中心概念。",
         impact_summary="OI と BM の統合、研究・実務両面で参照",
         subfield="open_innov", school_of_thought="Open BM", era_start=2006,
         keywords_ja="オープンBM, 価値協創", keywords_en="open business model",
         key_researchers=["Chesbrough, H."],
         key_works=[{"title":"Open Business Models","year":2006,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["IBM","Lilly"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),
])

# 8. lean_startup (BDBM_071-080)
add([
    dict(id="BDBM_071", name_ja="顧客開発", name_en="Customer Development",
         definition="顧客開発 (発見・検証・創造・構築) の 4 段階で仮説検証を進めるスタートアップ方法論。技術開発と並行する。",
         impact_summary="リーンスタートアップ運動の理論基盤",
         subfield="lean_startup", school_of_thought="Customer Development", era_start=2005,
         keywords_ja="顧客開発, 4段階", keywords_en="customer development, four steps",
         key_researchers=["Blank, S."],
         key_works=[{"title":"The Four Steps to the Epiphany","year":2005,"venue":"K&S Ranch"}],
         industry_applicability=["All"], case_companies=["IMVU"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_072", name_ja="リーンスタートアップ", name_en="The Lean Startup",
         definition="Build-Measure-Learn ループで仮説検証を最速化し、validated learning に基づく Pivot or Persevere 判断でスタートアップを運営するアプローチ。",
         impact_summary="スタートアップ実務の標準パラダイム、書籍 100万部超",
         subfield="lean_startup", school_of_thought="Lean Startup", era_start=2011,
         keywords_ja="リーンスタートアップ, BML", keywords_en="lean startup, build-measure-learn",
         key_researchers=["Ries, E."],
         key_works=[{"title":"The Lean Startup","year":2011,"venue":"Crown Business"}],
         industry_applicability=["All"], case_companies=["IMVU","Dropbox","Zappos"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_073", name_ja="スケーリング・リーン", name_en="Scaling Lean",
         definition="リーン手法をスケールアップ段階に適用するための指標 (traction roadmap・10x growth) と意思決定枠組み。",
         impact_summary="リーン運動のスケール期論",
         subfield="lean_startup", school_of_thought="Scaling Lean", era_start=2016,
         keywords_ja="スケーリング, トラクション", keywords_en="scaling, traction",
         key_researchers=["Maurya, A."],
         key_works=[{"title":"Scaling Lean","year":2016,"venue":"Portfolio"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=3,
         source_reliability="secondary", data_completeness=85),

    dict(id="BDBM_074", name_ja="リーンスタートアップ批判 (Felin et al.)", name_en="Lean Startup and the Business Model (Critique)",
         definition="リーンスタートアップの理論的根拠を批判し、市場発見の前提・実証性・偶然要素を問い直した学術論文。",
         impact_summary="実務優位の lean startup に対する学術的懐疑",
         subfield="lean_startup", school_of_thought="Critical Lean", era_start=2020,
         keywords_ja="リーン批判, 市場発見", keywords_en="lean critique, market discovery",
         key_researchers=["Felin, T.","Gambardella, A.","Stern, S.","Zenger, T."],
         key_works=[{"title":"Lean Startup and the Business Model","year":2020,"venue":"California Management Review"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_075", name_ja="MVP (Minimum Viable Product)", name_en="Minimum Viable Product",
         definition="顧客の検証に必要な最小機能セット。validated learning を最速で得るための投資最小化アプローチ。",
         impact_summary="プロダクト開発実務の標準概念",
         subfield="lean_startup", school_of_thought="Lean Methods", era_start=2009,
         keywords_ja="MVP, 最小実用製品", keywords_en="MVP, minimum viable product",
         key_researchers=["Ries, E."],
         key_works=[{"title":"The Lean Startup blog posts","year":2009,"venue":"Startup Lessons Learned"}],
         industry_applicability=["All"], case_companies=["Dropbox","Airbnb"], implementation_complexity=2,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_076", name_ja="Pivot 類型", name_en="Pivot Typology",
         definition="検証結果に基づき仮説を変更する 10 種の pivot 類型 (zoom-in/zoom-out/customer segment/customer need/platform/business architecture/value capture/engine of growth/channel/technology)。",
         impact_summary="リーンスタートアップ実務の戦略的選択肢",
         subfield="lean_startup", school_of_thought="Lean Methods", era_start=2011,
         keywords_ja="ピボット, 10類型", keywords_en="pivot, ten types",
         key_researchers=["Ries, E."],
         key_works=[{"title":"The Lean Startup","year":2011,"venue":"Crown Business"}],
         industry_applicability=["All"], case_companies=["Slack (gaming pivot)","Twitter (Odeo pivot)"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_077", name_ja="Lean Canvas", name_en="Lean Canvas",
         definition="BM Canvas をスタートアップ向けに改変したフレーム。問題・解決策・指標・ unfair advantage を強調。",
         impact_summary="スタートアップの BM 検証実務で広く利用",
         subfield="lean_startup", school_of_thought="Canvas Variant", era_start=2010,
         keywords_ja="リーンキャンバス, 問題解決", keywords_en="lean canvas, problem-solution",
         key_researchers=["Maurya, A."],
         key_works=[{"title":"Running Lean","year":2012,"venue":"O'Reilly"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=2,
         source_reliability="secondary", data_completeness=85),

    dict(id="BDBM_078", name_ja="Validated Learning", name_en="Validated Learning",
         definition="顧客行動データに基づく実証的学習。Vanity metrics ではなく actionable metrics で進捗を測定する原則。",
         impact_summary="リーンスタートアップ運動の認識論的基盤",
         subfield="lean_startup", school_of_thought="Lean Methods", era_start=2011,
         keywords_ja="実証的学習, 仮説検証", keywords_en="validated learning, hypothesis testing",
         key_researchers=["Ries, E."],
         key_works=[{"title":"The Lean Startup","year":2011,"venue":"Crown Business"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_079", name_ja="イノベーションアカウンティング", name_en="Innovation Accounting",
         definition="従来の財務会計ではなく、学習進捗を測る新しい指標体系 (cohort analysis, conversion rates) で起業の進捗を可視化する。",
         impact_summary="新規事業の業績評価の新パラダイム",
         subfield="lean_startup", school_of_thought="Innovation Metrics", era_start=2011,
         keywords_ja="イノベーション会計, 学習指標", keywords_en="innovation accounting, learning metrics",
         key_researchers=["Ries, E."],
         key_works=[{"title":"The Lean Startup","year":2011,"venue":"Crown Business"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_080", name_ja="Concierge MVP / Wizard of Oz MVP", name_en="Concierge / Wizard of Oz MVP",
         definition="製品自動化前に手作業で価値提供を検証する MVP 手法 (Concierge: 個別サービス, Wizard of Oz: 自動化偽装)。",
         impact_summary="MVP 設計の代表的具体パターン",
         subfield="lean_startup", school_of_thought="MVP Patterns", era_start=2012,
         keywords_ja="コンシェルジュMVP, 手作業検証", keywords_en="concierge MVP, manual",
         key_researchers=["Ries, E.","Maurya, A."],
         key_works=[{"title":"Running Lean","year":2012,"venue":"O'Reilly"}],
         industry_applicability=["All"], case_companies=["Food on the Table","Aardvark"], implementation_complexity=2,
         source_reliability="secondary", data_completeness=80),
])

# 9. disruptive (BDBM_081-090)
add([
    dict(id="BDBM_081", name_ja="イノベーターのジレンマ", name_en="The Innovator's Dilemma",
         definition="優良企業が顧客の声に応えて持続的イノベーションを追求する結果、低性能・低価格の破壊的イノベーションに敗北する逆説。",
         impact_summary="戦略論で最も影響力のある書籍の 1 つ、引用数 5万超",
         subfield="disruptive", school_of_thought="Disruption Theory", era_start=1997,
         keywords_ja="イノベーターのジレンマ, 持続的vs破壊的", keywords_en="disruption theory",
         key_researchers=["Christensen, C.M."],
         key_works=[{"title":"The Innovator's Dilemma","year":1997,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["Disk drive industry","Sears"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_082", name_ja="イノベーターの解", name_en="The Innovator's Solution",
         definition="破壊的イノベーションを既存企業内で実行するための組織・戦略の処方箋。Disruption 理論の応用編。",
         impact_summary="Disruption 理論の実装フレーム",
         subfield="disruptive", school_of_thought="Disruption Theory", era_start=2003,
         keywords_ja="イノベーターの解, 実装", keywords_en="innovator's solution",
         key_researchers=["Christensen, C.M.","Raynor, M.E."],
         key_works=[{"title":"The Innovator's Solution","year":2003,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["IBM PC","HP printers"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_083", name_ja="What Is Disruptive Innovation?", name_en="What Is Disruptive Innovation? (HBR clarification)",
         definition="Disruption の定義を再確認し、Uber・Tesla のような事例が「真の disruption ではない」と論じた HBR 論文。概念の厳密化。",
         impact_summary="Disruption 概念の理論的整理として影響大",
         subfield="disruptive", school_of_thought="Disruption Theory", era_start=2015,
         keywords_ja="ディスラプション定義, Uber批判", keywords_en="disruption definition",
         key_researchers=["Christensen, C.M.","Raynor, M.","McDonald, R."],
         key_works=[{"title":"What Is Disruptive Innovation?","year":2015,"venue":"Harvard Business Review"}],
         industry_applicability=["All"], case_companies=["Uber (NOT disruption)","Tesla (NOT disruption)"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_084", name_ja="The Disruption Machine 批判", name_en="The Disruption Machine Critique (Lepore)",
         definition="Christensen の disruption 理論の歴史的事例選定・予測力を批判し、概念の流行性を問題視した New Yorker 論考。",
         impact_summary="Disruption 概念への代表的批判",
         subfield="disruptive", school_of_thought="Critical Disruption", era_start=2014,
         keywords_ja="ディスラプション批判, Lepore", keywords_en="disruption critique",
         key_researchers=["Lepore, J."],
         key_works=[{"title":"The Disruption Machine","year":2014,"venue":"The New Yorker"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=2,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_085", name_ja="ローエンド破壊", name_en="Low-End Disruption",
         definition="既存市場のローエンドの過剰スペック顧客に向けて、性能は劣るが価格・利便性で勝る製品で参入する破壊パターン。",
         impact_summary="Disruption の主要 2 類型のうちの 1 つ",
         subfield="disruptive", school_of_thought="Disruption Type", era_start=1997,
         keywords_ja="ローエンド破壊, 過剰スペック", keywords_en="low-end disruption",
         key_researchers=["Christensen, C.M."],
         key_works=[{"title":"The Innovator's Dilemma","year":1997,"venue":"HBS Press"}],
         industry_applicability=["B2B","B2C"], case_companies=["Hyundai","Toyota Lexus"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_086", name_ja="新市場破壊", name_en="New-Market Disruption",
         definition="従来の非顧客 (non-consumers) に新市場を作る破壊。ローエンド破壊と並ぶ disruption の主類型。",
         impact_summary="Disruption の主要 2 類型のうちの 1 つ",
         subfield="disruptive", school_of_thought="Disruption Type", era_start=2003,
         keywords_ja="新市場破壊, 非消費者", keywords_en="new-market disruption, non-consumption",
         key_researchers=["Christensen, C.M.","Raynor, M.E."],
         key_works=[{"title":"The Innovator's Solution","year":2003,"venue":"HBS Press"}],
         industry_applicability=["All"], case_companies=["Sony Walkman","Personal Computer"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_087", name_ja="Job-to-be-Done", name_en="Jobs-to-be-Done Theory",
         definition="顧客は「製品」を買うのではなく「片付けたい仕事 (job)」を雇う、と捉える顧客理解フレーム。Christensen と Ulwick が発展。",
         impact_summary="製品開発・マーケティング実務に深く浸透",
         subfield="disruptive", school_of_thought="Jobs Theory", era_start=2003,
         keywords_ja="ジョブ理論, 雇う", keywords_en="jobs to be done, hire",
         key_researchers=["Christensen, C.M.","Ulwick, A.","Hall, T.","Dillon, K."],
         key_works=[{"title":"Competing Against Luck","year":2016,"venue":"HarperBusiness"}],
         industry_applicability=["All"], case_companies=["McDonald's milkshake","IKEA"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_088", name_ja="モジュラリティ理論", name_en="Modularity Theory (Baldwin-Clark)",
         definition="製品アーキテクチャがモジュラー化すると、産業構造が水平分業に再編される。Disruption の構造的駆動因。",
         impact_summary="産業進化論の主要理論",
         subfield="disruptive", school_of_thought="Modularity", era_start=2000,
         keywords_ja="モジュラリティ, 水平分業", keywords_en="modularity, vertical disintegration",
         key_researchers=["Baldwin, C.Y.","Clark, K.B."],
         key_works=[{"title":"Design Rules: The Power of Modularity","year":2000,"venue":"MIT Press"}],
         industry_applicability=["B2B","All"], case_companies=["PC industry","Auto industry"], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_089", name_ja="S-カーブ", name_en="S-Curve of Innovation",
         definition="技術性能の累積的向上は S 字曲線を描く。新技術の S-curve への乗り換えが disruption のメカニズム。",
         impact_summary="技術進化分析の標準フレーム",
         subfield="disruptive", school_of_thought="Technology Trajectory", era_start=1989,
         keywords_ja="Sカーブ, 技術進化", keywords_en="S-curve, technology trajectory",
         key_researchers=["Foster, R.N."],
         key_works=[{"title":"Innovation: The Attacker's Advantage","year":1986,"venue":"Summit Books"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_090", name_ja="Big Bang Disruption", name_en="Big Bang Disruption",
         definition="性能・価格・customization 全てで瞬時に既存品を凌駕するデジタル時代の急速 disruption 形態。Christensen 型のジワジワとは対照的。",
         impact_summary="デジタル時代の新 disruption 類型",
         subfield="disruptive", school_of_thought="Modern Disruption", era_start=2014,
         keywords_ja="ビッグバン破壊, 急速破壊", keywords_en="big bang disruption",
         key_researchers=["Downes, L.","Nunes, P."],
         key_works=[{"title":"Big Bang Disruption","year":2014,"venue":"Portfolio"}],
         industry_applicability=["All"], case_companies=["Smartphone","GPS apps","Netflix streaming"], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),
])

# 10. subscription_saas (BDBM_091-100)
add([
    dict(id="BDBM_091", name_ja="サブスクリプション経済", name_en="Subscription Economy",
         definition="所有から利用へのシフトを背景に、定期収益型 BM が急成長する経済現象。Zuora の Tzuo が概念化。",
         impact_summary="2010年代以降の支配的 BM パラダイム",
         subfield="subscription_saas", school_of_thought="Subscription Economy", era_start=2018,
         keywords_ja="サブスク経済, 定期収益", keywords_en="subscription economy, recurring",
         key_researchers=["Tzuo, T.","Weisert, G."],
         key_works=[{"title":"Subscribed","year":2018,"venue":"Portfolio"}],
         industry_applicability=["All"], case_companies=["Netflix","Spotify","Adobe"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_092", name_ja="マルチサイドプラットフォーム戦略決定 (Hagiu)", name_en="Strategic Decisions for Multisided Platforms",
         definition="プラットフォーム/サブスク BM の戦略決定 (誰を含めるか・収益化・統治) を整理した MIT SMR 論文。",
         impact_summary="サブスク・プラットフォーム BM の戦略論",
         subfield="subscription_saas", school_of_thought="Platform/Subscription", era_start=2014,
         keywords_ja="MSP, 戦略決定", keywords_en="MSP, strategic decisions",
         key_researchers=["Hagiu, A."],
         key_works=[{"title":"Strategic Decisions for Multisided Platforms","year":2014,"venue":"MIT Sloan Management Review"}],
         industry_applicability=["Platform"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_093", name_ja="カスタマーサクセス", name_en="Customer Success",
         definition="顧客の成果実現を継続的に支援することで、解約防止と LTV 拡大を同時実現する SaaS 専用機能・哲学。",
         impact_summary="SaaS 業界で全社的に標準化された機能",
         subfield="subscription_saas", school_of_thought="Customer Success", era_start=2016,
         keywords_ja="カスタマーサクセス, 継続支援", keywords_en="customer success",
         key_researchers=["Mehta, N.","Steinman, D.","Murphy, L."],
         key_works=[{"title":"Customer Success","year":2016,"venue":"Wiley"}],
         industry_applicability=["B2B"], case_companies=["Salesforce","HubSpot","Gainsight"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_094", name_ja="ハブエコノミー批判", name_en="Hub Economy Critique",
         definition="プラットフォーム・サブスク BM の独占傾向と社会的影響 (lock-in・規制必要性) を提示する HBR 論文。",
         impact_summary="サブスク・プラットフォーム経済の社会学的視点",
         subfield="subscription_saas", school_of_thought="Critical Platform", era_start=2017,
         keywords_ja="ハブ経済, ロックイン批判", keywords_en="hub economy, lock-in",
         key_researchers=["Iansiti, M.","Lakhani, K.R."],
         key_works=[{"title":"Managing Our Hub Economy","year":2017,"venue":"Harvard Business Review"}],
         industry_applicability=["Platform"], case_companies=["Apple","Google","Amazon"], implementation_complexity=3,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_095", name_ja="顧客生涯価値 (LTV)", name_en="Customer Lifetime Value",
         definition="顧客 1 人が生涯にもたらす純利益の現在価値。サブスク BM の根幹指標。",
         impact_summary="サブスク・SaaS の経済性評価の中心指標",
         subfield="subscription_saas", school_of_thought="Customer Economics", era_start=1985,
         keywords_ja="LTV, 顧客生涯価値", keywords_en="LTV, lifetime value",
         key_researchers=["Reichheld, F.","Sasser, W.E."],
         key_works=[{"title":"Zero Defections: Quality Comes to Services","year":1990,"venue":"Harvard Business Review"}],
         industry_applicability=["B2C","B2B"], case_companies=[], implementation_complexity=2,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_096", name_ja="顧客獲得コスト (CAC)", name_en="Customer Acquisition Cost",
         definition="新規顧客 1 人を獲得するための総コスト。LTV/CAC 比率はサブスク BM の経済性を判断する標準指標。",
         impact_summary="サブスク・SaaS で最も用いられる経営指標",
         subfield="subscription_saas", school_of_thought="Customer Economics", era_start=2009,
         keywords_ja="CAC, 顧客獲得コスト", keywords_en="CAC, customer acquisition",
         key_researchers=["Skok, D."],
         key_works=[{"title":"SaaS Metrics","year":2009,"venue":"For Entrepreneurs (blog)"}],
         industry_applicability=["B2B","B2C"], case_companies=[], implementation_complexity=2,
         source_reliability="tertiary", data_completeness=85),

    dict(id="BDBM_097", name_ja="チャーン (解約)", name_en="Churn (Logo / Revenue)",
         definition="解約による顧客・収益の喪失。logo churn (顧客数) と revenue churn (収益額) を区別する。サブスク BM の最大リスク。",
         impact_summary="サブスク健全性評価の必須指標",
         subfield="subscription_saas", school_of_thought="Subscription Metrics", era_start=2010,
         keywords_ja="チャーン, 解約", keywords_en="churn, attrition",
         key_researchers=["Skok, D.","Mehta, N."],
         key_works=[{"title":"Customer Success","year":2016,"venue":"Wiley"}],
         industry_applicability=["B2B","B2C"], case_companies=[], implementation_complexity=2,
         source_reliability="tertiary", data_completeness=85),

    dict(id="BDBM_098", name_ja="ネット・レベニュー・リテンション (NRR)", name_en="Net Revenue Retention",
         definition="既存顧客の収益が、解約を差し引いてもアップセル・拡張で増えているかを測る指標。120%超で健全と評価される。",
         impact_summary="SaaS 投資家の標準評価指標",
         subfield="subscription_saas", school_of_thought="Subscription Metrics", era_start=2018,
         keywords_ja="NRR, 純収益保持率", keywords_en="NRR, net revenue retention",
         key_researchers=["Kellogg, B."],
         key_works=[{"title":"SaaS Benchmarks","year":2020,"venue":"Bessemer"}],
         industry_applicability=["B2B"], case_companies=["Snowflake (160%+)","Datadog"], implementation_complexity=3,
         source_reliability="tertiary", data_completeness=80),

    dict(id="BDBM_099", name_ja="プロダクトレッドグロース (PLG)", name_en="Product-Led Growth",
         definition="営業ではなく製品自体が顧客獲得・拡張・保持の主要ドライバーになる成長戦略。Slack・Zoom・Figma の典型。",
         impact_summary="SaaS 成長戦略の主要パラダイム",
         subfield="subscription_saas", school_of_thought="PLG", era_start=2019,
         keywords_ja="PLG, プロダクト主導成長", keywords_en="PLG, product-led growth",
         key_researchers=["Bush, W.","Cagan, M."],
         key_works=[{"title":"Product-Led Growth","year":2019,"venue":"OpenView"}],
         industry_applicability=["B2B"], case_companies=["Slack","Zoom","Figma","Notion"], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=85),

    dict(id="BDBM_100", name_ja="使用量ベース価格 (Usage-Based Pricing)", name_en="Usage-Based Pricing",
         definition="顧客の利用量に応じて課金するサブスク変種。Snowflake・Twilio・AWS の主流モデル。Predictability より価値整合性を優先。",
         impact_summary="2020年代のサブスク BM の主流変種",
         subfield="subscription_saas", school_of_thought="Pricing Model", era_start=2020,
         keywords_ja="従量課金, UBP", keywords_en="usage-based pricing",
         key_researchers=["Bornstein, M."],
         key_works=[{"title":"The State of Usage-Based Pricing","year":2020,"venue":"OpenView"}],
         industry_applicability=["B2B"], case_companies=["Snowflake","Twilio","AWS","Stripe"], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=85),
])

# 11. sustainable_bm (BDBM_101-110)
add([
    dict(id="BDBM_101", name_ja="サステナビリティ BM 概念化", name_en="Conceptualizing a Sustainability Business Model",
         definition="経済・環境・社会の 3 軸で価値を創造する BM の構造的特徴を理論化した先駆的論文。",
         impact_summary="サステナブル BM 研究の起点",
         subfield="sustainable_bm", school_of_thought="Sustainable BM Foundation", era_start=2008,
         keywords_ja="サステナビリティBM, トリプルボトムライン", keywords_en="sustainability BM",
         key_researchers=["Stubbs, W.","Cocklin, C."],
         key_works=[{"title":"Conceptualizing a 'Sustainability Business Model'","year":2008,"venue":"Organization & Environment"}],
         industry_applicability=["All"], case_companies=["Interface","Patagonia"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_102", name_ja="サステナブル BM アーキタイプ", name_en="Sustainable Business Model Archetypes",
         definition="サステナブル BM を 8 つの archetype (技術・社会・組織) に分類した文献・実務レビューの統合フレーム。",
         impact_summary="サステナブル BM 研究の標準分類",
         subfield="sustainable_bm", school_of_thought="Archetype Classification", era_start=2014,
         keywords_ja="アーキタイプ, 8類型", keywords_en="archetypes, eight types",
         key_researchers=["Bocken, N.","Short, S.W.","Rana, P.","Evans, S."],
         key_works=[{"title":"A literature and practice review to develop sustainable business model archetypes","year":2014,"venue":"Journal of Cleaner Production"}],
         industry_applicability=["All"], case_companies=["Interface","Riversimple"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_103", name_ja="サステナブル BMI レビュー (Geissdoerfer)", name_en="Sustainable BMI Review",
         definition="サステナブル BMI 研究の体系的レビュー。経済性・環境性・社会性の統合的価値創造プロセスを 5 段階で整理。",
         impact_summary="現代サステナブル BMI 研究の代表的レビュー",
         subfield="sustainable_bm", school_of_thought="Meta-research", era_start=2018,
         keywords_ja="サステナブルBMI, レビュー", keywords_en="sustainable BMI review",
         key_researchers=["Geissdoerfer, M.","Vladimirova, D.","Evans, S."],
         key_works=[{"title":"Sustainable business model innovation: A review","year":2018,"venue":"Journal of Cleaner Production"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_104", name_ja="企業サステナビリティの緊張", name_en="Tensions in Corporate Sustainability (Critique)",
         definition="経済・環境・社会の 3 軸間にトレードオフ・緊張があることを論理的に整理し、楽観的なサステナビリティ言説を批判した論文。",
         impact_summary="サステナビリティ研究のトレードオフ視点",
         subfield="sustainable_bm", school_of_thought="Critical Sustainability", era_start=2015,
         keywords_ja="トレードオフ, 緊張", keywords_en="tensions, tradeoffs",
         key_researchers=["Hahn, T.","Pinkse, J.","Preuss, L.","Figge, F."],
         key_works=[{"title":"Tensions in Corporate Sustainability","year":2015,"venue":"Journal of Business Ethics"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_105", name_ja="トリプルボトムライン", name_en="Triple Bottom Line",
         definition="People・Planet・Profit の 3 軸で企業業績を測る評価フレーム。サステナビリティ会計の基礎概念。Elkington の造語。",
         impact_summary="サステナビリティ報告基準の概念基盤",
         subfield="sustainable_bm", school_of_thought="3BL", era_start=1994,
         keywords_ja="トリプルボトムライン, 3軸評価", keywords_en="triple bottom line",
         key_researchers=["Elkington, J."],
         key_works=[{"title":"Cannibals with Forks","year":1997,"venue":"Capstone"}],
         industry_applicability=["All"], case_companies=["Patagonia","Ben & Jerry's"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_106", name_ja="サーキュラーエコノミー", name_en="Circular Economy",
         definition="廃棄物を資源として再利用し続ける閉ループ型の経済システム。Ellen MacArthur Foundation が普及。",
         impact_summary="EU・日本の政策に組み込まれる主要パラダイム",
         subfield="sustainable_bm", school_of_thought="Circular Economy", era_start=2013,
         keywords_ja="サーキュラーエコノミー, 循環", keywords_en="circular economy, closed loop",
         key_researchers=["Ellen MacArthur Foundation","Stahel, W.R."],
         key_works=[{"title":"Towards the Circular Economy","year":2013,"venue":"Ellen MacArthur Foundation"}],
         industry_applicability=["All"], case_companies=["Renault","Philips Lighting"], implementation_complexity=5,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_107", name_ja="共有価値創造 (CSV)", name_en="Creating Shared Value",
         definition="社会課題を解決しつつ経済的価値を生み出す戦略。CSR を超えた戦略的サステナビリティの中心概念。Porter-Kramer 提唱。",
         impact_summary="戦略論におけるサステナビリティ統合の代表",
         subfield="sustainable_bm", school_of_thought="Shared Value", era_start=2011,
         keywords_ja="共有価値, CSV", keywords_en="shared value, CSV",
         key_researchers=["Porter, M.E.","Kramer, M.R."],
         key_works=[{"title":"Creating Shared Value","year":2011,"venue":"Harvard Business Review"}],
         industry_applicability=["All"], case_companies=["Nestlé","GE"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_108", name_ja="再生型ビジネス", name_en="Regenerative Business",
         definition="環境を「劣化させない」を超えて「再生・改善」する事業設計。Doughnut Economics や生態系視点と整合。",
         impact_summary="2020年代の新たな BM パラダイム",
         subfield="sustainable_bm", school_of_thought="Regenerative", era_start=2017,
         keywords_ja="再生型, リジェネレーティブ", keywords_en="regenerative",
         key_researchers=["Hutchins, G.","Storm, L."],
         key_works=[{"title":"Regenerative Leadership","year":2019,"venue":"Wordzworth"}],
         industry_applicability=["All"], case_companies=["Patagonia","Interface"], implementation_complexity=5,
         source_reliability="secondary", data_completeness=80),

    dict(id="BDBM_109", name_ja="ドーナツ経済学", name_en="Doughnut Economics",
         definition="社会的下限と環境的上限の間で繁栄する「安全で公正な空間」を経済目標とする新パラダイム。Raworth 提唱。",
         impact_summary="アムステルダム市等が政策採用、2020年代の急成長思想",
         subfield="sustainable_bm", school_of_thought="Heterodox Economics", era_start=2017,
         keywords_ja="ドーナツ経済, 限界内繁栄", keywords_en="doughnut economics",
         key_researchers=["Raworth, K."],
         key_works=[{"title":"Doughnut Economics","year":2017,"venue":"Random House"}],
         industry_applicability=["All"], case_companies=["Amsterdam city","C40 cities"], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_110", name_ja="ステークホルダー理論", name_en="Stakeholder Theory",
         definition="株主だけでなく従業員・顧客・コミュニティ・環境など全 stakeholder への価値提供を企業目的とする理論。Freeman 提唱。",
         impact_summary="Friedman 流の株主至上主義への代替パラダイム",
         subfield="sustainable_bm", school_of_thought="Stakeholder Theory", era_start=1984,
         keywords_ja="ステークホルダー, 利害関係者", keywords_en="stakeholder theory",
         key_researchers=["Freeman, R.E."],
         key_works=[{"title":"Strategic Management: A Stakeholder Approach","year":1984,"venue":"Pitman"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),
])

# 12. channel_gtm (BDBM_111-120)
add([
    dict(id="BDBM_111", name_ja="チャネル行動次元", name_en="Distribution Channels: Behavioral Dimensions",
         definition="流通チャネルを単なる経済的取引でなく、社会的・行動的システムとして捉える理論的視点。チャネル研究の起点。",
         impact_summary="チャネル研究の出発点",
         subfield="channel_gtm", school_of_thought="Channel Behavior", era_start=1969,
         keywords_ja="チャネル行動, 社会システム", keywords_en="channel behavior, social system",
         key_researchers=["Stern, L.W."],
         key_works=[{"title":"Distribution Channels: Behavioral Dimensions","year":1969,"venue":"Houghton Mifflin"}],
         industry_applicability=["B2B","B2C"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_112", name_ja="国際参入と直接 vs 間接チャネル", name_en="International Entry: Direct vs Integrated Channels",
         definition="国際市場参入時のチャネル選択 (代理店・流通業者 vs 自社販売子会社) を取引コスト論で分析した古典的論文。",
         impact_summary="チャネル選択論の理論基盤",
         subfield="channel_gtm", school_of_thought="Transaction Cost", era_start=1987,
         keywords_ja="国際参入, チャネル選択", keywords_en="international entry, channel choice",
         key_researchers=["Anderson, E.","Coughlan, A.T."],
         key_works=[{"title":"International Market Entry and Expansion via Independent or Integrated Channels of Distribution","year":1987,"venue":"Journal of Marketing"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_113", name_ja="マルチ・オムニチャネル管理", name_en="Managing Multi- and Omni-Channel Distribution",
         definition="物理店舗・EC・モバイル等の複数チャネルを統合的にマネージする現代的アプローチ。Showrooming・Webrooming への対応。",
         impact_summary="リテール戦略の標準的フレーム",
         subfield="channel_gtm", school_of_thought="Omnichannel", era_start=2017,
         keywords_ja="オムニチャネル, 統合管理", keywords_en="omnichannel",
         key_researchers=["Ailawadi, K.L.","Farris, P.W."],
         key_works=[{"title":"Managing Multi- and Omni-Channel Distribution","year":2017,"venue":"Journal of Retailing"}],
         industry_applicability=["B2C"], case_companies=["Walmart","Target","Best Buy"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_114", name_ja="EC 時代のチャネル摩擦 (批判)", name_en="Channel Conflict in E-Commerce Era",
         definition="EC 直販チャネル導入が既存の代理店・流通網と摩擦を生む構造的問題を分析。チャネル管理の困難性を実証。",
         impact_summary="現代チャネル摩擦の主要研究",
         subfield="channel_gtm", school_of_thought="Critical Channel", era_start=2002,
         keywords_ja="チャネル摩擦, EC", keywords_en="channel conflict, e-commerce",
         key_researchers=["Webb, K.L."],
         key_works=[{"title":"Managing Channels of Distribution in the Age of Electronic Commerce","year":2002,"venue":"Industrial Marketing Management"}],
         industry_applicability=["B2B","B2C"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_115", name_ja="流通強度", name_en="Distribution Intensity",
         definition="流通網の密度を「集中・選択・専属」の 3 段階で設計する原則。製品特性・ブランド戦略に応じた選択が必要。",
         impact_summary="マーケティング教科書の標準概念",
         subfield="channel_gtm", school_of_thought="Channel Design", era_start=1996,
         keywords_ja="流通強度, 集中選択専属", keywords_en="distribution intensity",
         key_researchers=["Stern, L.W.","El-Ansary, A.I.","Coughlan, A.T."],
         key_works=[{"title":"Marketing Channels","year":1996,"venue":"Prentice Hall"}],
         industry_applicability=["B2C"], case_companies=["Rolex (専属)","Coca-Cola (集中)"], implementation_complexity=3,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_116", name_ja="ディスインターメディエーション", name_en="Disintermediation",
         definition="従来の中間業者を飛ばし、メーカーが直接エンドユーザーに販売する流通革新。EC・デジタル化が促進。",
         impact_summary="リテール革命の中心概念",
         subfield="channel_gtm", school_of_thought="Channel Restructuring", era_start=1998,
         keywords_ja="中抜き, 直販", keywords_en="disintermediation, direct",
         key_researchers=["Sarkar, M.B.","Butler, B.","Steinfield, C."],
         key_works=[{"title":"Intermediaries and cybermediaries: A continuing role for mediating players","year":1995,"venue":"Journal of Computer-Mediated Communication"}],
         industry_applicability=["B2C","B2B"], case_companies=["Dell","Tesla"], implementation_complexity=4,
         source_reliability="secondary", data_completeness=85),

    dict(id="BDBM_117", name_ja="リインターメディエーション", name_en="Reintermediation",
         definition="ディスインターメディエーション後に、新たな価値を提供する中間プレイヤー (Amazon・Booking.com 等) が再登場する現象。",
         impact_summary="プラットフォーム経済の流通論的説明",
         subfield="channel_gtm", school_of_thought="Channel Restructuring", era_start=2000,
         keywords_ja="再仲介, 新中間業者", keywords_en="reintermediation",
         key_researchers=["Chircu, A.M.","Kauffman, R.J."],
         key_works=[{"title":"Reintermediation strategies in business-to-business electronic commerce","year":2000,"venue":"International Journal of Electronic Commerce"}],
         industry_applicability=["B2B","B2C"], case_companies=["Amazon","Expedia","Airbnb"], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_118", name_ja="チャネルパートナープログラム", name_en="Channel Partner Program",
         definition="販売パートナー (リセラー・SI・MSP) を体系的に育成・管理するプログラム。tier 制・認定・インセンティブが構成要素。",
         impact_summary="B2B 流通実務の標準",
         subfield="channel_gtm", school_of_thought="Partner Management", era_start=2010,
         keywords_ja="パートナープログラム, リセラー", keywords_en="partner program, reseller",
         key_researchers=["Forrester","SiriusDecisions"],
         key_works=[{"title":"State of the Partner Ecosystem","year":2020,"venue":"Forrester"}],
         industry_applicability=["B2B"], case_companies=["Microsoft","Cisco","Salesforce"], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=80),

    dict(id="BDBM_119", name_ja="チャネルカニバリゼーション", name_en="Channel Cannibalization",
         definition="新チャネル導入が既存チャネルの売上を奪う現象。直販導入の主要リスクとして分析される。",
         impact_summary="チャネル戦略策定の中心リスク",
         subfield="channel_gtm", school_of_thought="Channel Strategy", era_start=2003,
         keywords_ja="カニバリ, 自食化", keywords_en="cannibalization",
         key_researchers=["Geyskens, I.","Gielens, K.","Dekimpe, M.G."],
         key_works=[{"title":"The Market Valuation of Internet Channel Additions","year":2002,"venue":"Journal of Marketing"}],
         industry_applicability=["B2B","B2C"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_120", name_ja="GTM デザインピラミッド", name_en="Go-to-Market Design Pyramid",
         definition="顧客 → セグメント → メッセージ → チャネル → セールス組織の階層で GTM を体系的に設計するフレーム。",
         impact_summary="B2B GTM 実務の標準フレーム",
         subfield="channel_gtm", school_of_thought="GTM Design", era_start=2014,
         keywords_ja="GTMピラミッド, 階層設計", keywords_en="GTM pyramid",
         key_researchers=["Pisano, G.P."],
         key_works=[{"title":"Creating an R&D Strategy","year":2012,"venue":"Harvard Business School"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=75),
])

# 13. b2b_enterprise (BDBM_121-130)
add([
    dict(id="BDBM_121", name_ja="組織購買行動モデル", name_en="Organizational Buying Behavior Model",
         definition="組織購買を「購買センター」が複数アクターで意思決定するプロセスとして捉えるモデル。Webster-Wind の古典的枠組み。",
         impact_summary="B2B マーケティングの理論基盤",
         subfield="b2b_enterprise", school_of_thought="Organizational Buying", era_start=1972,
         keywords_ja="組織購買, バイイングセンター", keywords_en="organizational buying",
         key_researchers=["Webster, F.E.","Wind, Y."],
         key_works=[{"title":"A General Model for Understanding Organizational Buying Behavior","year":1972,"venue":"Journal of Marketing"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_122", name_ja="SPIN セリング", name_en="SPIN Selling",
         definition="Situation・Problem・Implication・Need-payoff の 4 種の質問で大型 B2B 商談を進める営業手法。Rackham による実証研究ベース。",
         impact_summary="B2B 営業実務の標準教科書、世界 100万部超",
         subfield="b2b_enterprise", school_of_thought="Consultative Selling", era_start=1988,
         keywords_ja="SPINセリング, 質問法", keywords_en="SPIN selling, questioning",
         key_researchers=["Rackham, N."],
         key_works=[{"title":"SPIN Selling","year":1988,"venue":"McGraw-Hill"}],
         industry_applicability=["B2B"], case_companies=["Xerox (源流)","IBM"], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_123", name_ja="チャレンジャーセール", name_en="The Challenger Sale",
         definition="優秀営業の 5 類型 (Hard Worker・Relationship Builder・Lone Wolf・Reactive Problem Solver・Challenger) で Challenger が最も成果高いことを実証。",
         impact_summary="2010年代以降の B2B 営業実務の主流",
         subfield="b2b_enterprise", school_of_thought="Challenger Sale", era_start=2011,
         keywords_ja="チャレンジャー営業, 5類型", keywords_en="challenger sale, five types",
         key_researchers=["Adamson, B.","Dixon, M.","Toman, N."],
         key_works=[{"title":"The Challenger Sale","year":2011,"venue":"Portfolio"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=3,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_124", name_ja="関係性営業の限界批判", name_en="Critique of Relationship Selling",
         definition="従来の関係性営業 (relationship building) が複雑な購買意思決定では効果薄であることを実証し、より能動的なアプローチを提唱。",
         impact_summary="関係性営業から Challenger 型への移行を示す論考",
         subfield="b2b_enterprise", school_of_thought="Critical Sales", era_start=2008,
         keywords_ja="関係性営業批判, アクティブ営業", keywords_en="relationship selling critique",
         key_researchers=["Sheth, J.N.","Sharma, A."],
         key_works=[{"title":"The impact of the product to service shift in industrial markets","year":2008,"venue":"Industrial Marketing Management"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_125", name_ja="アカウントベースマーケティング (ABM)", name_en="Account-Based Marketing",
         definition="特定のターゲットアカウントに営業・マーケティングを集中させる B2B アプローチ。スプレー&プレイ型と対照的。",
         impact_summary="2020年代 B2B マーケの主流アプローチ",
         subfield="b2b_enterprise", school_of_thought="ABM", era_start=2014,
         keywords_ja="ABM, アカウント集中", keywords_en="ABM, account-based",
         key_researchers=["Robitaille, B."],
         key_works=[{"title":"The Clear and Complete Guide to Account-Based Marketing","year":2017,"venue":"ITSMA"}],
         industry_applicability=["B2B"], case_companies=["LinkedIn","Demandbase"], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=80),

    dict(id="BDBM_126", name_ja="ソリューション営業", name_en="Solution Selling",
         definition="製品ではなく顧客の問題解決を売る営業アプローチ。SPIN や Consultative Selling と並ぶ古典的手法。",
         impact_summary="B2B 営業教育の標準",
         subfield="b2b_enterprise", school_of_thought="Solution Selling", era_start=1995,
         keywords_ja="ソリューション営業, 問題解決", keywords_en="solution selling",
         key_researchers=["Bosworth, M.T."],
         key_works=[{"title":"Solution Selling","year":1995,"venue":"McGraw-Hill"}],
         industry_applicability=["B2B"], case_companies=["IBM Global Services"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_127", name_ja="MEDDIC / MEDDPICC", name_en="MEDDIC / MEDDPICC",
         definition="Metrics・Economic Buyer・Decision Criteria・Decision Process・Identify Pain・Champion (+ Paper process・Competition) の頭字語で資格判定する B2B 営業フレーム。",
         impact_summary="エンタープライズ営業の qualification 標準",
         subfield="b2b_enterprise", school_of_thought="Sales Qualification", era_start=1996,
         keywords_ja="MEDDIC, 資格判定", keywords_en="MEDDIC, qualification",
         key_researchers=["Roberge, M.","Napoli, J."],
         key_works=[{"title":"MEDDIC framework (PTC origin)","year":1996,"venue":"Practitioner / PTC"}],
         industry_applicability=["B2B"], case_companies=["PTC","Oracle"], implementation_complexity=3,
         source_reliability="tertiary", data_completeness=80),

    dict(id="BDBM_128", name_ja="バリューセリング", name_en="Value-Based Selling",
         definition="顧客が得る経済的・戦略的価値を定量化して提示し、その価値の一部として価格を正当化する営業手法。",
         impact_summary="価格議論を価値議論に転換する実務",
         subfield="b2b_enterprise", school_of_thought="Value Selling", era_start=2004,
         keywords_ja="バリューセリング, 価値定量化", keywords_en="value selling",
         key_researchers=["Liozu, S.M."],
         key_works=[{"title":"The Pricing Journey","year":2014,"venue":"Stanford University Press"}],
         industry_applicability=["B2B"], case_companies=[], implementation_complexity=4,
         source_reliability="secondary", data_completeness=80),

    dict(id="BDBM_129", name_ja="セールスイネーブルメント", name_en="Sales Enablement",
         definition="営業の効率・成果を高めるための教育・コンテンツ・プロセス・ツールを統合的に提供する機能・職能。",
         impact_summary="現代 B2B 営業組織の標準機能",
         subfield="b2b_enterprise", school_of_thought="Sales Enablement", era_start=2014,
         keywords_ja="セールスイネーブルメント, 営業支援", keywords_en="sales enablement",
         key_researchers=["Forrester","Gartner"],
         key_works=[{"title":"Sales Enablement: The Engine of Sales Productivity","year":2014,"venue":"Forrester"}],
         industry_applicability=["B2B"], case_companies=["HubSpot","Highspot","Seismic"], implementation_complexity=3,
         source_reliability="tertiary", data_completeness=75),

    dict(id="BDBM_130", name_ja="レベニューオペレーションズ (RevOps)", name_en="Revenue Operations",
         definition="マーケティング・セールス・カスタマーサクセスのオペレーションを統合し、収益サイクル全体を一元最適化する組織機能。",
         impact_summary="2020年代 SaaS 企業の標準組織形態",
         subfield="b2b_enterprise", school_of_thought="RevOps", era_start=2018,
         keywords_ja="RevOps, 収益オペ統合", keywords_en="RevOps, revenue operations",
         key_researchers=["Forrester"],
         key_works=[{"title":"The State of Revenue Operations","year":2020,"venue":"Forrester"}],
         industry_applicability=["B2B"], case_companies=["Snowflake","Datadog","HubSpot"], implementation_complexity=4,
         source_reliability="tertiary", data_completeness=75),
])

# 14. ma_corp_dev (BDBM_131-140)
add([
    dict(id="BDBM_131", name_ja="買収統合の管理 (Haspeslagh-Jemison)", name_en="Managing Acquisitions: Haspeslagh-Jemison Framework",
         definition="買収後統合 (PMI) を 4 類型 (Preservation・Symbiosis・Absorption・Holding) で分類し、それぞれの戦略的アプローチを定義した古典的フレーム。",
         impact_summary="M&A 研究の理論基盤",
         subfield="ma_corp_dev", school_of_thought="Integration Typology", era_start=1991,
         keywords_ja="統合4類型, PMI", keywords_en="integration typology, PMI",
         key_researchers=["Haspeslagh, P.C.","Jemison, D.B."],
         key_works=[{"title":"Managing Acquisitions","year":1991,"venue":"Free Press"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=5,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_132", name_ja="水平的買収の長期業績", name_en="Long-Term Performance of Horizontal Acquisitions",
         definition="水平的 (同業) 買収のシナジー実現と長期業績の関係を実証分析した代表的研究。コスト/収益シナジーを区別。",
         impact_summary="M&A シナジー研究の中心論文",
         subfield="ma_corp_dev", school_of_thought="Synergy Empirical", era_start=1999,
         keywords_ja="水平買収, シナジー", keywords_en="horizontal acquisition, synergy",
         key_researchers=["Capron, L."],
         key_works=[{"title":"The long-term performance of horizontal acquisitions","year":1999,"venue":"Strategic Management Journal"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_133", name_ja="M&A 研究レビュー (King-Bauer-Schriber)", name_en="M&A Research Overview",
         definition="M&A 研究 30 年を体系的にレビューし、戦略的・組織的・統合プロセス的視点を統合した最新書籍。",
         impact_summary="現代 M&A 研究の標準レビュー",
         subfield="ma_corp_dev", school_of_thought="Meta-research", era_start=2018,
         keywords_ja="M&Aレビュー, 統合視点", keywords_en="M&A review",
         key_researchers=["King, D.R.","Bauer, F.","Schriber, S."],
         key_works=[{"title":"Mergers and Acquisitions: A Research Overview","year":2018,"venue":"Routledge"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_134", name_ja="M&A 失敗率レビュー (批判)", name_en="M&A Failure Rate Critique",
         definition="M&A の 50%以上が業績期待を下回ることを 30 年の研究で実証し、M&A の戦略的論理を批判的に再検討した代表的レビュー。",
         impact_summary="M&A 楽観論への決定的批判",
         subfield="ma_corp_dev", school_of_thought="Critical M&A", era_start=2006,
         keywords_ja="M&A失敗, 50%超", keywords_en="M&A failure rate",
         key_researchers=["Cartwright, S.","Schoenberg, R."],
         key_works=[{"title":"Thirty Years of Mergers and Acquisitions Research","year":2006,"venue":"British Journal of Management"}],
         industry_applicability=["All"], case_companies=["AOL-Time Warner","Daimler-Chrysler"], implementation_complexity=4,
         source_reliability="primary", data_completeness=95),

    dict(id="BDBM_135", name_ja="戦略的フィット vs 文化的フィット", name_en="Strategic Fit vs Cultural Fit",
         definition="買収成功の 2 軸:事業戦略の整合性と組織文化の親和性。文化的不整合が PMI 失敗の主要因と実証される。",
         impact_summary="M&A 実務の中心評価軸",
         subfield="ma_corp_dev", school_of_thought="Fit Analysis", era_start=1989,
         keywords_ja="戦略的フィット, 文化的フィット", keywords_en="strategic fit, cultural fit",
         key_researchers=["Datta, D.K."],
         key_works=[{"title":"Organizational fit and acquisition performance","year":1991,"venue":"Strategic Management Journal"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_136", name_ja="アクハイヤー (Acquihire)", name_en="Acquihire",
         definition="主に人材獲得を目的とした小規模スタートアップ買収。テック大企業の典型的タレント獲得手段。",
         impact_summary="2010年代以降のテック M&A の主要パターン",
         subfield="ma_corp_dev", school_of_thought="Modern M&A", era_start=2010,
         keywords_ja="アクハイヤー, 人材買収", keywords_en="acquihire, talent acquisition",
         key_researchers=["Coyle, J.F.","Polsky, G.D."],
         key_works=[{"title":"Acqui-hiring","year":2013,"venue":"Duke Law Journal"}],
         industry_applicability=["B2B","All"], case_companies=["Google","Facebook","Yahoo"], implementation_complexity=3,
         source_reliability="primary", data_completeness=85),

    dict(id="BDBM_137", name_ja="スピンオフ・ダイベスチメント", name_en="Spin-offs and Divestments",
         definition="既存事業を分離・売却して企業価値を高める戦略。集中・コングロマリットディスカウント解消の主要手段。",
         impact_summary="ポートフォリオ管理論の中心トピック",
         subfield="ma_corp_dev", school_of_thought="Portfolio Restructuring", era_start=1993,
         keywords_ja="スピンオフ, 売却", keywords_en="spin-off, divestment",
         key_researchers=["Hoskisson, R.E.","Johnson, R.A.","Moesel, D.D."],
         key_works=[{"title":"Corporate Divestiture Intensity","year":1994,"venue":"Academy of Management Journal"}],
         industry_applicability=["All"], case_companies=["GE Healthcare","HP Enterprise"], implementation_complexity=5,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_138", name_ja="コーポレートベンチャーキャピタル (CVC)", name_en="Corporate Venture Capital",
         definition="既存企業がスタートアップに少数出資する仕組み。財務リターンと戦略的学習の二重目的。",
         impact_summary="2010年代以降のオープンイノベーション主要手段",
         subfield="ma_corp_dev", school_of_thought="CVC", era_start=2002,
         keywords_ja="CVC, スタートアップ出資", keywords_en="CVC, startup investment",
         key_researchers=["Dushnitsky, G.","Lenox, M.J."],
         key_works=[{"title":"When does corporate venture capital investment create firm value?","year":2006,"venue":"Journal of Business Venturing"}],
         industry_applicability=["All"], case_companies=["Intel Capital","Salesforce Ventures","Google Ventures"], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_139", name_ja="買収プレミアム", name_en="Acquisition Premium",
         definition="買収企業が market price 以上に支払う金額。プレミアムが過大だとシナジー回収困難という winner's curse 問題。",
         impact_summary="M&A 経済性の中心論点",
         subfield="ma_corp_dev", school_of_thought="Deal Economics", era_start=1986,
         keywords_ja="買収プレミアム, ウィナーズカース", keywords_en="acquisition premium, winner's curse",
         key_researchers=["Roll, R."],
         key_works=[{"title":"The Hubris Hypothesis of Corporate Takeovers","year":1986,"venue":"Journal of Business"}],
         industry_applicability=["All"], case_companies=[], implementation_complexity=4,
         source_reliability="primary", data_completeness=90),

    dict(id="BDBM_140", name_ja="SPAC (特別買収目的会社)", name_en="Special Purpose Acquisition Company",
         definition="上場済みの空箱企業を通じてターゲット企業を買収・公開する仕組み。2020-2021 にブーム、その後規制強化。",
         impact_summary="2020年代の M&A の特殊形態",
         subfield="ma_corp_dev", school_of_thought="Modern Deal Structure", era_start=2020,
         keywords_ja="SPAC, 空箱買収", keywords_en="SPAC, blank check",
         key_researchers=["Klausner, M.D.","Ohlrogge, M.","Ruan, E."],
         key_works=[{"title":"A Sober Look at SPACs","year":2021,"venue":"Yale Journal on Regulation"}],
         industry_applicability=["All"], case_companies=["Virgin Galactic","DraftKings","SoFi"], implementation_complexity=4,
         source_reliability="primary", data_completeness=85),
])

# Print SQL
import sys
print("BEGIN;")
for r in ALL:
    print(row(**r), end="")
print("COMMIT;")
print(f"-- {len(ALL)} entries (part 2)", file=sys.stderr)
