#!/usr/bin/env python3
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
    ("inno_digi_351","デジタルツインと製品ライフサイクル管理","Digital Twin and Product Lifecycle Management","製品のデジタルツインはCAD・シミュレーション・製造・保守データを一体化したPLMを実現する。Siemens Xcelerator・PTC Windchill・Dassault ENOVIA が主要PLMプラットフォーム。航空機エンジン(GEAviation)・自動車(BoeingDigitalTwin)が先行事例として研究される。製品設計の物理試作削減・欠陥コスト削減・保守最適化が定量的効果として示される。","platform_digital_innovation","デジタルトランスフォーメーション",2016,None,"meso","製造・航空","PLM設計","製品開発のデジタル化を推進する際","PLMデジタルツインは製品開発コストをどう削減するか","物理プロトタイプ","デジタルツイン,PLM,Siemens,製品開発","digital twin,PLM,Siemens,product development","active","secondary",76,'["Siemens PLM Team"]','["Siemens Xcelerator Case 2022"]',"試作削減率・開発期間"),
    ("inno_digi_352","プラットフォームと消費者保護法の進化","Platform and Evolution of Consumer Protection Law","デジタルプラットフォームへの消費者保護規制はEUデジタルサービス法・消費者権利指令の改訂・国内法整備を通じて進化している。暗いパターン(Dark Patterns)はNielsen Norman Groupが定義した欺瞞的UI設計で欧州GDPR・FTC対応が強化された。自動更新・解約困難・価格表示の不透明性が主要規制対象となっている。","platform_digital_innovation","プラットフォーム規制",2022,None,"macro","消費者・EC","消費者保護デザイン","デジタルサービスの消費者保護を設計する際","プラットフォームの消費者保護規制はどのような課題に対処するか","伝統的消費者保護","ダークパターン,消費者保護,EU DSA,FTC","dark patterns,consumer protection,EU DSA,FTC","active","secondary",76,'["Harry Brignull","FTC Staff"]','["FTC Dark Patterns Report 2022","EU DSA 2022"]',"消費者苦情件数・規制対応率"),
    ("inno_digi_353","次世代バッテリーとエネルギー貯蔵イノベーション","Next-Generation Battery and Energy Storage Innovation","リチウムイオン電池を超える次世代電池(全固体電池・リチウム硫黄・ナトリウムイオン)はEV・グリッド貯蔵を変革する可能性を持つ。Tesla・CATL・Panasonicがギガファクトリー展開で規模の経済を実現している。Nykvist & Nilsson(2015)はEVバッテリーコストの急速低下を実証しS字曲線を確認した。全固体電池は2027-2030年の商業化が目標とされている。","platform_digital_innovation","エネルギー・環境DX",2020,None,"macro","エネルギー・EV","バッテリー技術・政策評価","EV・蓄電池投資を判断する際","次世代バッテリーはEV普及とグリッド安定化をどう加速するか","ガソリン車","全固体電池,リチウムイオン,EV,CATL","solid-state battery,lithium-ion,EV,CATL","active","secondary",76,'["Bjorn Nykvist","Mans Nilsson"]','["Nykvist Nilsson 2015 Nature Energy"]',"バッテリーコスト・エネルギー密度"),
    ("inno_digi_354","クリプト決済とステーブルコイン","Crypto Payment and Stablecoins","ステーブルコイン(USDC・Tether・DAI)は価格変動を抑えたデジタル通貨で国際送金・DeFi・コマースに応用される。Gorton & Zhang(2021)はステーブルコインを銀行取付リスクを持つ私的貨幣として分析しCBDCとの比較を論じた。Terra/LUNAの崩壊(2022)がアルゴリズム型ステーブルコインの脆弱性を露呈した。FSBはクロスボーダーステーブルコインの規制フレームを2023年に策定した。","platform_digital_innovation","デジタル金融",2020,None,"macro","金融・暗号資産","ステーブルコイン規制評価","決済のデジタル化・国際化を検討する際","ステーブルコインはどのような決済課題に対応するか","法定通貨決済","ステーブルコイン,USDC,DeFi,FSB","stablecoin,USDC,DeFi,FSB","active","secondary",76,'["Gary Gorton","Arwin Zhang"]','["Gorton Zhang 2021","FSB Stablecoin 2023"]',"取引量・価格安定性"),
    ("inno_digi_355","モバイルゲームとアジア型課金モデル","Mobile Gaming and Asian Monetization Models","アジア発のスマホゲームはガチャ(確率課金)・バトルパス・コンテンツ定期更新の課金モデルを世界に広めた。Hamari(2015)はゲームアイテム課金の経済的メカニズムを分析した。TencentのHoK・miHoYoの原神が世界市場で10億ドル超の月収を記録した。規制(ベルギー・オランダのガチャ禁止)がビジネスモデルの変容を迫っている。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2015,None,"meso","ゲーム産業","モバイルゲーム収益化","スマホゲームの収益モデルを設計する際","アジア型課金モデルは西洋ゲームと何が異なるか","パッケージ販売型","モバイルゲーム,ガチャ,バトルパス,Tencent","mobile gaming,gacha,battle pass,Tencent","active","secondary",74,'["Juho Hamari"]','["Hamari 2015","miHoYo Annual Report"]',"ARPU・課金率"),
    ("inno_digi_356","AIアシスタントとコパイロット経済","AI Assistant and Copilot Economy","Microsoft Copilot(Word・Excel・Teams統合)・GitHub Copilot・Google Workspace AIがオフィス生産性ツールにLLMを統合する。Noy & Zhang(2023)はChatGPTによるライティング支援が生産性を37%向上させたと実験的に示した。コパイロット経済は専門知識の民主化と職種横断的なAI補助を実現する。Softwareエンジニア・ライター・分析者・弁護士等の知識労働がAIパートナーシップへ移行する。","platform_digital_innovation","生成AI応用",2023,None,"meso","知識産業","AI生産性ツール導入","知識労働の生産性向上","コパイロットAIは知識労働の何を変えるか","単独作業","コパイロット,LLM,Microsoft Copilot,生産性","copilot,LLM,Microsoft Copilot,productivity","active","primary",82,'["Shakked Noy","Whitney Zhang"]','["Noy Zhang 2023","Microsoft Copilot Launch 2023"]',"生産性向上率・採用率"),
    ("inno_digi_357","プラットフォームの標準化競争とインターオペラビリティ","Platform Standardization Competition and Interoperability","プラットフォーム間の相互運用性(Interoperability)はロックイン低減・競争促進・消費者便益の鍵となる。EU DMA(2022)はゲートキーパーにメッセージング相互運用を義務付ける。Matter規格(スマートホームIoT)・GSMA RCS(メッセージング)・W3C標準が業界主導標準化の事例。Katz & Shapiro(1985)のネットワーク外部性論が標準化競争の経済学的基礎となる。","platform_digital_innovation","プラットフォーム規制",2022,None,"macro","デジタルプラットフォーム","相互運用性政策設計","プラットフォーム間の技術連携を実現する際","相互運用性義務はプラットフォーム競争にどう影響するか","独自標準プラットフォーム","相互運用性,Matter,EU DMA,標準化","interoperability,Matter,EU DMA,standardization","active","secondary",78,'["Michael Katz","Carl Shapiro"]','["Katz Shapiro 1985","EU DMA 2022"]',"スイッチングコスト・競争指標"),
    ("inno_digi_358","オンラインプラットフォームと医療情報エコシステム","Online Platform and Medical Information Ecosystem","WebMD・PubMed・UpToDate・NIH MedlinePlusが医療情報の主要プラットフォームとして患者・医師の情報探索を変えた。Eysenbach(2008)はHealth 2.0の到来を論じ患者が能動的健康情報生産者になることを示した。HealthUnlocked・PatientsLikeMe等のSNS型医療コミュニティが患者主導の集合知を生む。医療情報の質保証・偽情報・プライバシー(HIPAA)が主要課題となっている。","platform_digital_innovation","デジタルトランスフォーメーション",2008,None,"meso","医療","医療情報プラットフォーム設計","医療情報の信頼性と普及を高める際","医療プラットフォームは患者行動をどう変えるか","医師のみの情報提供","Health 2.0,医療情報,WebMD,患者主体","Health 2.0,medical information,WebMD,patient empowerment","active","secondary",74,'["Gunther Eysenbach"]','["Eysenbach 2008","WHO Digital Health Strategy 2020"]',"情報利用率・患者エンゲージメント"),
    ("inno_digi_359","プラットフォームとデータ独占","Platform and Data Monopoly","データが競争の主要資源になるとともにデータ独占が新形態の市場支配力をもたらす。Stucke & Grunes(2016)はデータ優位性が競争政策の新フロンティアであると論じた。強制的データアクセス・データポータビリティ(GDPR第20条)・データシェアリング義務がデータ独占解消の政策ツール。Google・Facebookの第一者データ優位が広告市場での競争障壁を形成する。","platform_digital_innovation","プラットフォーム規制",2016,None,"macro","デジタルプラットフォーム","データ独占・競争政策","データ独占の競争影響を評価する際","データ独占はどのような競争制限効果をもたらすか","製品・サービス独占","データ独占,データポータビリティ,GDPR,競争政策","data monopoly,data portability,GDPR,competition policy","active","secondary",78,'["Maurice Stucke","Allen Grunes"]','["Stucke Grunes 2016","GDPR Art.20 2018"]',"市場集中度・データアクセス率"),
    ("inno_digi_360","自律型AIエージェントとオーケストレーション","Autonomous AI Agent and Orchestration","LLMを利用した自律型AIエージェント(AutoGPT・LangChain・CrewAI)は複数ステップの複雑タスクを人間の監督なしに遂行する。Weng(2023)がLLMエージェントのアーキテクチャ(Planning・Memory・Tools)を体系化した。Microsoft AutoGen・Anthropic Claude Tool UseがAIエージェントシステムの産業標準となりつつある。マルチエージェントオーケストレーションがSoftwareEngineeringの自動化の次段階として注目される。","platform_digital_innovation","AI・機械学習",2023,None,"micro","AI開発・知識産業","AIエージェントシステム設計","自律的タスク実行をAIで実現する際","AIエージェントはどのような複雑タスクを自律実行できるか","ルールベース自動化","AIエージェント,LangChain,AutoGPT,オーケストレーション","AI agent,LangChain,AutoGPT,orchestration","active","primary",80,'["Lilian Weng","Harrison Chase"]','["Weng 2023 LLM Agent Survey","AutoGPT 2023"]',"タスク完了率・エラー率"),
    ("inno_digi_361","デジタル監視技術と社会的含意","Digital Surveillance Technology and Social Implications","CCTV・顔認識・スマートフォン追跡・ソーシャルメディア監視等のデジタル監視技術は安全保障と自由のバランス問題を提起する。Lyon(2001)の監視社会論がデジタル時代に再評価されている。中国の社会信用システムが国家監視技術の極端な事例として国際比較研究の対象となる。プライバシー・表現の自由・差別への影響が人権・倫理の論点となっている。","platform_digital_innovation","AI規制・ガバナンス",2020,None,"macro","政府・安全保障","監視技術の倫理・規制","デジタル監視技術の社会的影響を評価する際","デジタル監視技術はどのような社会的トレードオフを持つか","非監視型社会","デジタル監視,顔認識,社会信用,プライバシー","digital surveillance,facial recognition,social credit,privacy","active","secondary",76,'["David Lyon","Shoshana Zuboff"]','["Lyon 2001 Surveillance Society","China Social Credit Analysis 2021"]',"監視技術普及率・自由度指標"),
    ("inno_digi_362","EコマースとオムニチャネルCX革命","E-commerce and Omnichannel CX Revolution","オムニチャネルは店舗・オンライン・モバイル・ソーシャルを一貫した顧客体験に統合する。Verhoef et al.(2015)がオムニチャネル小売を体系的にレビューした。Zara・Nike・Starbucksのオムニチャネル実践が顧客生涯価値向上の事例として研究される。コロナ以降のBOPIS(Buy Online Pickup In Store)・ライブコマース・メタバース小売が新次元を加えた。","platform_digital_innovation","デジタルプラットフォーム経済",2015,None,"meso","小売","オムニチャネル戦略","顧客体験の統合化を実現する際","オムニチャネルはどのような顧客行動変容をもたらすか","チャネル別サイロ","オムニチャネル,BOPIS,CX,Nike","omnichannel,BOPIS,CX,Nike","active","secondary",76,'["Peter Verhoef"]','["Verhoef et al. 2015 JR"]',"顧客転換率・LTV"),
    ("inno_digi_363","AI推論コストの低下と民主化","Declining AI Inference Cost and Democratization","AI推論コストはGPUの世代交代・量子化・蒸留・効率的アーキテクチャにより急速に低下している。Thompson et al.(2020)はAIモデルの性能向上速度が計算資源の増加を超える傾向を示した。Mistral・Llama等の軽量オープンソースLLMが中小企業・個人開発者のAIアクセスを民主化した。エッジ推論(スマートフォン上のLLM)が次世代プライバシー保護AI応用の基盤となる。","platform_digital_innovation","AI・機械学習",2023,None,"macro","AI産業全般","AI民主化戦略","低コストAI導入を計画する際","AI推論コスト低下は産業のAI採用をどう加速するか","大企業専用AI","AI推論コスト,民主化,Mistral,Llama,量子化","AI inference cost,democratization,Mistral,Llama,quantization","active","primary",80,'["Neil Thompson","Arvind Nair"]','["Thompson et al. 2020","Mistral AI 2023"]',"推論コスト・採用企業数"),
    ("inno_digi_364","オープンバンキングとAPIエコシステム","Open Banking and API Ecosystem","オープンバンキングはPSD2(EU)・UK Open Banking・日本API公開要件に基づき銀行がAPIで第三者にデータ・サービスアクセスを提供する枠組み。Plaid・TrueLayerがデータ集約・API標準化を商業展開する。Consumers International(2020)はオープンバンキングが金融競争・包摂を改善すると評価した。Open Finance(銀行以外の金融データ開放)への拡張が政策議論として進行中。","platform_digital_innovation","デジタル金融",2018,None,"meso","金融・フィンテック","オープンバンキング設計","銀行APIを活用したサービスを開発する際","オープンバンキングは金融競争をどう促進するか","閉鎖型銀行","オープンバンキング,PSD2,API,Plaid","open banking,PSD2,API,Plaid","active","secondary",78,'["Consumers International","FCA Open Banking"]','["UK Open Banking 2022","PSD2 Review 2023"]',"API利用数・新サービス数"),
    ("inno_digi_365","インターネット経済の勝者総取りと独占","Winner-Take-All in Internet Economy and Monopoly","デジタルプラットフォームのネットワーク効果・規模の経済・スイッチングコストが少数企業への「勝者総取り(Winner-Take-All)」を生む。Frank & Cook(1995)が勝者総取り経済の一般理論を提示した。Amazon・Google・Facebook・Microsoft等の寡占形成が各国競争当局の介入を促した。Monopoly Contestability(市場参入可能性)がデジタル市場の主要政策議論となっている。","platform_digital_innovation","プラットフォーム経済学",1995,None,"macro","デジタルプラットフォーム","デジタル独占分析","デジタル市場の競争構造を評価する際","勝者総取りは市場効率と消費者厚生にどう影響するか","完全競争市場","勝者総取り,独占,GAFAM,ネットワーク効果","winner-take-all,monopoly,GAFAM,network effects","active","primary",82,'["Robert Frank","Philip Cook"]','["Frank Cook 1995","Khan 2017 Amazon Antitrust"]',"市場集中度・競争指標"),
    ("inno_digi_366","デジタルインフラと国家安全保障","Digital Infrastructure and National Security","5G・海底ケーブル・クラウドデータセンター・衛星通信が国家の重要インフラとして安全保障政策の対象となった。Huawei 5G排除問題(2018-)が技術安全保障の国際議論を触発した。EU NIS2指令(2022)・米国サイバーセキュリティ大統領令(2021)が重要インフラ保護を強化する。Renn(2008)のリスクガバナンス論がデジタルインフラ保護の制度設計に援用される。","platform_digital_innovation","サイバーセキュリティ",2018,None,"macro","安全保障・通信","デジタルインフラ保護設計","重要インフラのサイバーセキュリティを確保する際","デジタルインフラはどのような国家安全保障リスクを持つか","アナログインフラ","デジタルインフラ,国家安全保障,5G,Huawei,NIS2","digital infrastructure,national security,5G,Huawei,NIS2","active","secondary",78,'["Renn Ortwin","CISA Staff"]','["EU NIS2 2022","White House EO 14028 2021"]',"インシデント件数・回復力指標"),
    ("inno_digi_367","SNSと精神健康の関係","Social Media and Mental Health","ソーシャルメディアの使用と特に若者の精神健康(うつ・不安・自尊心低下)の関係が実証研究の焦点となっている。Twenge et al.(2018)はスマートフォン普及と青年うつの増加の時系列相関を示した。Haidt & Allen(2020)はSNSが向社会行動に負の影響を持つと主張するが因果関係の実証は論争中。プラットフォームの設計変更(ライクボタン廃止・スクリーンタイム制限)が対策として試みられている。","platform_digital_innovation","プラットフォーム規制",2018,None,"macro","消費者・公衆衛生","SNS健康影響評価","SNSの精神健康への影響を政策として対処する際","SNSは若者の精神健康にどのような影響を与えるか","ソーシャル不関与","SNS,精神健康,若者,スマートフォン,Haidt","social media,mental health,youth,smartphone,Haidt","active","primary",78,'["Jean Twenge","Jonathan Haidt"]','["Twenge et al. 2018","Haidt Allen 2020"]',"精神健康指標・SNS利用時間"),
    ("inno_digi_368","量子インターネットと次世代通信","Quantum Internet and Next-Generation Communication","量子インターネットは量子もつれを利用した盗聴不可能な通信ネットワークを構築する。Wehner et al.(2018)がQuantum Internet発展段階(Trusted Node→Entanglement-based)を定義した。EU Quantum Flagship・米国国家量子推進(NQI)・中国量子科学衛星が技術開発を競争する。量子鍵配送ネットワーク(東京・ジュネーブ・北京)の実証実験が先行している。","platform_digital_innovation","量子コンピューティング",2018,None,"macro","通信・安全保障","量子通信インフラ評価","量子通信基盤の実現可能性を評価する際","量子インターネットは古典インターネットのどのセキュリティ課題を解決するか","古典暗号通信","量子インターネット,量子もつれ,QKD,EU Quantum","quantum internet,quantum entanglement,QKD,EU Quantum","active","secondary",72,'["Stephanie Wehner","Anton Zeilinger"]','["Wehner et al. 2018 Science","EU Quantum Flagship 2022"]',"量子鍵配送距離・ノード数"),
    ("inno_digi_369","生成AIの産業応用：法律・コンプライアンス","Generative AI Industrial Application Legal Compliance","LLMは契約書ドラフト・デューデリジェンス・規制コンプライアンス調査・訴訟支援を変革しつつある。HarveyAI・Lexis+AI・ContractPodAiが法務部門向けLLMを展開する。大型法律事務所でLLM使用ポリシーが整備され弁護士の活用と監督のバランスが実務課題となる。","platform_digital_innovation","生成AI応用",2023,None,"meso","法律・コンプライアンス","法務AI導入","法務業務の生産性向上を検討する際","生成AIは法律業務のどのプロセスを効率化するか","人手法務","法務AI,ContractPodAi,HarveyAI,コンプライアンス","legal AI,ContractPodAi,HarveyAI,compliance","active","secondary",76,'["Richard Susskind","HarveyAI Team"]','["Susskind 2023","HarveyAI Launch 2022"]',"契約書処理時間・コスト削減"),
    ("inno_digi_370","デジタルピアッサ：地域コミュニティとプラットフォーム","Digital Piazza: Local Community and Platform","Nextdoor・Facebook Groups・地域LINE・マチマチ等の地域コミュニティプラットフォームは物理的地域社会のデジタル拡張として機能する。Gerbaudo(2012)はソーシャルメディアが集合行動の「振り付け」に使われることを示した。地域防災・子育て情報共有・シェアリング経済への接続が主要用途。孤独・排除・偽情報が課題として残る。","platform_digital_innovation","デジタルプラットフォーム経済",2012,None,"meso","地域コミュニティ","地域プラットフォーム設計","地域社会のデジタル化を推進する際","地域コミュニティプラットフォームはどのような社会資本を生むか","物理的地縁","地域コミュニティ,Nextdoor,防災,ソーシャルメディア","local community,Nextdoor,disaster prevention,social media","active","secondary",72,'["Paolo Gerbaudo"]','["Gerbaudo 2012","Nextdoor Case Studies 2022"]',"参加率・コミュニティ課題解決率"),
    ("inno_digi_371","プラットフォームと情報格差：デジタルデバイドの深層","Platform and Information Inequality: Depth of Digital Divide","インターネットへのアクセス格差を超えた「スキル格差・利用質格差・アウトカム格差」がデジタルデバイドの第2・第3段階として研究される。van Dijk(2020)は「デジタル格差(Digital Divide)」を多次元的に定義し単純なアクセス論を批判した。教育・労働・医療のデジタル化が格差を拡大するリスクをIMFが警告している。","platform_digital_innovation","デジタル包摂",2020,None,"macro","社会政策","デジタル格差対策","デジタル包摂政策を設計する際","デジタル格差はどのような多次元的不平等を生むか","単純なアクセス格差","デジタルデバイド,情報格差,スキル格差,van Dijk","digital divide,information inequality,skill gap,van Dijk","active","primary",80,'["Jan van Dijk"]','["van Dijk 2020","IMF Digital Inclusion Report 2022"]',"格差指標・政策効果"),
    ("inno_digi_372","AIと教育の個別最適化","AI and Personalized Learning in Education","AI支援の個別最適化学習はKhan Academy Khanmigo・DuolingoMax・Carnegie Learningが実装し学習パスを個人のペース・スタイルに動的調整する。Bloom(1984)の「2-sigma問題」(1対1チュータリングの大きな効果)をAIが解決する可能性を示した。学習分析(LA)と適応型評価がリアルタイムの理解度把握と指導最適化を実現する。","platform_digital_innovation","生成AI応用",2023,None,"meso","教育","AI教育システム設計","個別最適化学習を実現する際","AI個別学習はどのような教育成果改善をもたらすか","一斉授業","AI教育,個別最適化,Khanmigo,適応学習","AI education,personalized learning,Khanmigo,adaptive learning","active","primary",80,'["Sal Khan","Benjamin Bloom"]','["Bloom 1984","Khan Academy Khanmigo 2023"]',"学習成果・エンゲージメント"),
    ("inno_digi_373","デジタルプラットフォームのエコシステムと共創価値","Digital Platform Ecosystem and Co-creation Value","プラットフォームエコシステムの価値はプラットフォーム企業単独でなく全参加者の共創で生まれる。Adner(2012)のエコシステム論はパートナー間の依存関係と整合性管理を分析した。Apple・Amazon・Salesforceのエコシステムが独自の価値共創メカニズムを持つことが比較研究されている。","platform_digital_innovation","プラットフォーム競争戦略",2012,None,"meso","プラットフォーム産業","エコシステム価値設計","プラットフォームエコシステムの価値最大化","エコシステムはどのような共創価値を生むか","単一企業","エコシステム,共創,Adner,Apple,Salesforce","ecosystem,co-creation,Adner,Apple,Salesforce","active","secondary",78,'["Ron Adner"]','["Adner 2012 Wide Lens","Adner 2017 JMgt"]',"エコシステム参加者数・GMV"),
    ("inno_digi_374","ソーシャルネットワーク分析とイノベーション拡散","Social Network Analysis and Innovation Diffusion","SNA(Social Network Analysis)はノード・エッジ・中心性・クラスタリングでイノベーション情報の伝播経路と普及速度を分析する。Granovetter(1973)の「弱い紐帯の強さ」がイノベーション情報拡散の鍵となることを示した。Twitter・LinkedInでの新技術普及パターン分析が従来の普及論(Rogers 1962)を検証・更新する。","platform_digital_innovation","データ経済",1973,None,"meso","社会科学・マーケティング","SNAによるイノベーション拡散分析","技術普及の社会的メカニズムを分析する際","ソーシャルネットワークはイノベーション普及にどう影響するか","マスメディア拡散","SNA,弱い紐帯,イノベーション拡散,クラスタリング","SNA,weak ties,innovation diffusion,clustering","active","primary",80,'["Mark Granovetter","Everett Rogers"]','["Granovetter 1973 AJS","Rogers 1962 Diffusion"]',"普及速度・ネットワーク構造指標"),
    ("inno_digi_375","プラットフォームとサステナビリティレポーティング","Platform and Sustainability Reporting","デジタルプラットフォームは企業ESGデータ収集・検証・報告を自動化しESGエコシステムを変革する。BloombergESG・MSCI ESG・Refinitiv等のデータプロバイダーがAIで非財務情報を構造化する。EU CSRD(企業サステナビリティ報告指令,2023)はデジタルESGタクソノミー適用を義務付けた。GHG排出量の自動計算・Scope3サプライチェーン追跡がデジタルESGの主要課題。","platform_digital_innovation","エネルギー・環境DX",2023,None,"macro","金融・ESG","ESGデータ自動化","ESGレポーティングのデジタル化を推進する際","デジタルESGプラットフォームはレポーティングコストをどう削減するか","人手ESG集計","ESG,CSRD,GHG,Scope3,デジタルレポーティング","ESG,CSRD,GHG,Scope3,digital reporting","active","secondary",76,'["EU Commission Sustainability","Bloomberg ESG Team"]','["EU CSRD 2023","TCFD Digital Report 2022"]',"ESG報告精度・コスト削減"),
    ("inno_digi_376","AIロボティクスと製造フレキシビリティ","AI Robotics and Manufacturing Flexibility","AIと協働ロボット(Cobot)の統合は製造工程の柔軟な自動化を実現し少量多品種生産を可能にする。Universal Robots・Fanuc・ABBがCobotプラットフォームを展開。Wisskirchen et al.(2017)はロボット・AIの雇用影響の産業別差異を分析した。適応型グリッパー・ロボット視覚・強化学習がロボットの万能化を推進している。","platform_digital_innovation","ロボティクス",2020,None,"meso","製造・物流","製造自動化設計","柔軟な生産自動化を実現する際","AI Cobotはどのような製造柔軟性をもたらすか","固定自動化","AIロボット,Cobot,Universal Robots,協働","AI robot,cobot,Universal Robots,collaboration","active","secondary",76,'["Universal Robots","ABB Robotics"]','["Wisskirchen et al. 2017","Universal Robots Case 2022"]',"生産性・導入コスト"),
    ("inno_digi_377","インシュアテックと保険業DX","Insurtech and Insurance Industry DX","インシュアテックはAI・テレマティクス・IoTで保険リスク評価・保険料設定・クレーム処理を変革する。Lemonade・Root Insurance・ZhongAn(中国)が新形態保険モデルを展開した。行動経済学ベースのnudge保険(健康行動報酬型)・Pay-As-You-Drive(走行距離連動保険)が伝統的アクチュアリー計算を補完する。","platform_digital_innovation","デジタルトランスフォーメーション",2015,None,"meso","保険業","インシュアテック戦略","保険業DXを分析する際","インシュアテックはどのような保険バリューチェーンを変革するか","従来型保険モデル","インシュアテック,AI保険,テレマティクス,Lemonade","insurtech,AI insurance,telematics,Lemonade","active","secondary",74,'["Lemonade Team","ZhongAn Research"]','["Lemonade S-1 2020","ZhongAn Annual Report 2022"]',"損害率・顧客獲得コスト"),
    ("inno_digi_378","デジタルプロパガンダと情報戦","Digital Propaganda and Information Warfare","国家・非国家主体がSNS・ボット・ディープフェイクを利用した情報操作(Influence Operation)を展開する。Bradshaw & Howard(2019)のOxford Internet Instituteはサイバートループ(Computational Propaganda)の実態を78カ国で記録した。2016年米大統領選・Brexit・COVID偽情報が情報戦の主要事例として分析される。","platform_digital_innovation","プラットフォーム規制",2019,None,"macro","安全保障・メディア","情報操作対策","デジタル情報操作のリスクを評価する際","デジタルプロパガンダはどのような社会的害悪をもたらすか","通常言論","デジタルプロパガンダ,ボット,Computational Propaganda,情報戦","digital propaganda,bot,Computational Propaganda,information warfare","active","secondary",78,'["Samantha Bradshaw","Philip Howard"]','["Bradshaw Howard 2019 OII"]',"偽情報拡散速度・ボット検出率"),
    ("inno_digi_379","AIと法の支配(Rule of Law)","AI and the Rule of Law","AIシステムが司法・法執行・行政裁量に介入する際の法の支配との整合性が論じられる。COMPAS(再犯リスク算出AI)のPropublica報告(2016)が刑事司法AIの人種バイアスを告発した。AlgorithmicAccountability(アルゴリズム説明責任)とDue Process(適正手続)の両立が法律学者の主要課題となる。","platform_digital_innovation","AI規制・ガバナンス",2016,None,"macro","法・司法","AI法的リスク管理","AI意思決定の法的正当性を確保する際","AIは法の支配にどのような課題をもたらすか","人間による法的判断","AI法律,COMPAS,アルゴリズム説明責任,Due Process","AI law,COMPAS,algorithmic accountability,due process","active","secondary",78,'["Julia Angwin","Solon Barocas"]','["Propublica COMPAS 2016","Barocas Selbst 2016"]',"バイアス指標・訴訟件数"),
    ("inno_digi_380","マイクロペイメントとデジタルコンテンツ収益化","Micropayment and Digital Content Monetization","マイクロペイメントは従来の広告・サブスクより低コストで単発コンテンツ課金を実現する仕組み。Coil・Web Monetization API・Lightning Network(ビットコイン)が実装を試みた。Shirky(2000)はマイクロペイメントの心理的摩擦コストが商業化の障壁となることを論じた。AI自動マイクロ課金が普及すれば広告依存モデルの代替として情報の質向上が期待される。","platform_digital_innovation","デジタル金融",2020,None,"meso","コンテンツ・メディア","マイクロペイメント設計","デジタルコンテンツの新収益化モデル","マイクロペイメントはコンテンツ経済をどう変えるか","広告モデル","マイクロペイメント,Lightning Network,Web Monetization,コンテンツ課金","micropayment,Lightning Network,Web Monetization,content payment","active","secondary",72,'["Clay Shirky","Stefan Thomas"]','["Shirky 2000","Coil Micropayment 2020"]',"取引数・コンテンツ収益"),
    ("inno_digi_381","プラットフォームと農業市場統合","Platform and Agricultural Market Integration","農業デジタルプラットフォームはBuyer-Seller情報非対称を解消し農家の収益を向上させる。DigiFarm(Safaricom)・AgroCenta(Ghana)・Ninjacart(India)が途上国農業DXを推進する。Aker(2008)はニジェール携帯電話普及が穀物市場の価格統合を改善することを実証した。精密農業・気象AI・金融包摂(農業信用)との統合が価値連鎖全体を変革する。","platform_digital_innovation","デジタルプラットフォーム経済",2015,None,"meso","農業・途上国","農業プラットフォーム戦略","農業市場の情報格差を解消する際","農業デジタルプラットフォームはどのような農業価値連鎖を変えるか","伝統的農業市場","農業プラットフォーム,DigiFarm,Ninjacart,情報非対称","agricultural platform,DigiFarm,Ninjacart,information asymmetry","active","secondary",74,'["Jenny Aker","CGA Staff"]','["Aker 2008 CEB","DigiFarm Case 2021"]',"農家収益・市場統合指標"),
    ("inno_digi_382","デジタルシングルマーケットとEU戦略","Digital Single Market and EU Strategy","EU Digital Single Market(DSM)戦略(2015-)はデジタル商品・サービス・データの域内自由流通障壁除去を目標とした。EU e-commerce Directive・VAT改正・地理的ブロッキング廃止・データポータビリティがDSMの柱。Crafts & Venables(2016)はDSMのGDP押上効果を推計した。DSAとDMAがDSMのコンプライアンス側面を強化している。","platform_digital_innovation","デジタルプラットフォーム経済",2015,None,"macro","EU政策","EU DSM政策評価","欧州デジタル市場政策を分析する際","EU DSMはデジタル経済のどのような障壁を除去するか","分断された国内市場","EU DSM,デジタル単一市場,eCommerce,データポータビリティ","EU DSM,Digital Single Market,eCommerce,data portability","active","secondary",76,'["EU Commission Digital Economy"]','["EU DSM Midterm Review 2017","Crafts Venables 2016"]',"DSM経済効果・EC取引量"),
    ("inno_digi_383","AIによる材料科学発見","AI-Driven Materials Science Discovery","DeepMindのGNoME(2023)は2.2百万種の安定結晶構造を発見しNature掲載で材料AI発見の転換点となった。AIは高温超電導体・太陽電池材料・触媒・バッテリー材料の探索空間を大幅に圧縮する。Pymatgen・Materials Project・AFLOW等のオープン材料データベースがAI訓練の基盤を提供する。","platform_digital_innovation","SpaceTech・DeepTech",2023,None,"macro","材料科学・エネルギー","AI材料発見研究設計","材料発見プロセスをAIで加速する際","AIは材料科学のどのような探索課題を解決するか","試行錯誤実験","AI材料発見,GNoME,Materials Project,高温超電導","AI materials discovery,GNoME,Materials Project,superconductor","active","primary",80,'["Deepmind GNoME Team"]','["Merchant et al. 2023 Nature GNoME","Materials Project 2023"]',"発見速度・材料性能向上"),
    ("inno_digi_384","サイバーフィジカルシステムとIndustrie 4.0","Cyber-Physical Systems and Industrie 4.0","CPS(Cyber-Physical Systems)は物理プロセスとデジタル制御を統合し製造・インフラの知能化を実現する。Lee(2008)がCPSの概念を定式化した。Industrie4.0はCPS・IoT・ビッグデータ・クラウドを統合したドイツ製造業変革戦略(Kagermann 2013)。スマート工場・自動倉庫・スマートグリッドがCPS応用事例として研究される。","platform_digital_innovation","IoT・エッジコンピューティング",2013,None,"meso","製造・インフラ","CPS設計","製造のサイバーフィジカル統合を実現する際","CPSはどのような製造効率と柔軟性を実現するか","物理ベース制御","CPS,Industrie4.0,IoT,スマート工場","CPS,Industrie4.0,IoT,smart factory","active","secondary",80,'["Edward Lee","Henning Kagermann"]','["Lee 2008","Kagermann et al. 2013"]',"製造効率・生産柔軟性"),
    ("inno_digi_385","医療AIの公平性と偏向","Fairness and Bias in Medical AI","医療AIは訓練データの偏りによりマイノリティ集団への診断精度低下リスクを持つ。Obermeyer et al.(2019)は米国医療のアルゴリズムが黒人患者に体系的に低いヘルスケア割り当てを行うことを実証した。FDA・EMAのAI偏向評価要件が商業承認の条件となりつつある。多様な訓練データ収集・偏向テスト・継続的モニタリングが設計要件として確立している。","platform_digital_innovation","AI規制・ガバナンス",2019,None,"meso","医療AI","医療AI公平性設計","医療AIのバイアスリスクを管理する際","医療AIはどのような人種・性別バイアスを内包するか","アルゴリズムなし","医療AI,公平性,バイアス,Obermeyer","medical AI,fairness,bias,Obermeyer","active","primary",82,'["Ziad Obermeyer","Sendhil Mullainathan"]','["Obermeyer et al. 2019 Science"]',"診断精度・人口グループ差"),
    ("inno_digi_386","プラットフォームと農村デジタル化","Platform and Rural Digitalization","中国のタオバオビレッジ・インドのeSamudaay・ケニアのDigiFarm等のプラットフォームが農村経済をデジタル化する。Jack & Suri(2011)はM-Pesaが農村消費平滑化と食料安全保障を改善することを実証した。農村EC・農業ファイナンス・農業保険・精密農業の統合が農村デジタルエコシステムを形成する。","platform_digital_innovation","デジタル包摂",2015,None,"meso","農村・途上国","農村DX設計","農村のデジタル化を推進する際","農村デジタルプラットフォームはどのような農村経済課題を解決するか","都市集中型デジタル経済","農村デジタル化,タオバオビレッジ,M-Pesa,農業EC","rural digitalization,Taobao Village,M-Pesa,agricultural EC","active","secondary",74,'["William Jack","Tavneet Suri"]','["Jack Suri 2011 AER","Taobao Village Case 2020"]',"農村EC売上・農家収益"),
    ("inno_digi_387","デジタルヘルスケアのビジネスモデル革新","Digital Healthcare Business Model Innovation","遠隔医療・デジタル治療・健康データ活用が医療のビジネスモデルを出来高払い(Fee-for-Service)から成果払い(Value-Based Care)へ転換する。Teladoc・Hims & Hers・Noom等がD2C医療モデルを展開した。Apple Health Records・Google Health・Amazon Clinicが大型テック企業の医療参入を示す。","platform_digital_innovation","デジタルトランスフォーメーション",2018,None,"meso","医療","デジタルヘルスビジネスモデル","医療DXのビジネス設計","デジタルヘルスはどのように医療報酬モデルを変えるか","出来高医療","デジタルヘルス,Value-Based Care,Teladoc,Amazon Clinic","digital health,value-based care,Teladoc,Amazon Clinic","active","secondary",76,'["Eric Topol","Jeff Nadler"]','["Topol 2019","CMS VBC Strategy 2023"]',"成果指標・コスト削減"),
    ("inno_digi_388","APIファーストと組み合わせ可能性経済","API-First and Composability Economy","APIファーストアーキテクチャはソフトウェア機能を細粒度のAPIとして設計しサービス組み合わせによる新ビジネス創出を可能にする。Stripe・Twilio・SendGrid・Algoliaが「インフラAPI」として開発者に機能を提供する。Composition(組み合わせ可能性)がDeFi(各プロトコルの組み合わせ)・No-code(APIブロック組み合わせ)の基盤となる。","platform_digital_innovation","クラウドコンピューティング",2010,None,"meso","ソフトウェア産業","APIファースト設計","ソフトウェアコンポーネントの再利用を最大化する際","APIファーストはどのようにビジネスイノベーション速度を高めるか","モノリシック","APIファースト,組み合わせ可能性,Stripe,Twilio","API-first,composability,Stripe,Twilio","active","secondary",76,'["Patrick Collison","Jeff Lawson"]','["Twilio IPO Prospectus 2016","Stripe Developer Docs"]',"API呼び出し数・新サービス創出"),
    ("inno_digi_389","ゲームエンジンとリアルタイム3D産業応用","Game Engine and Real-Time 3D Industrial Application","Unity・Unreal Engine等のゲームエンジンが建築・映画・製造・医療研修の3Dビジュアライゼーション・シミュレーション基盤として産業転用された。Epic GamesのUnrealのMetaHuman・BMW工場シミュレーション・SiemensのNX統合が事例。リアルタイムレンダリングの高度化がデジタルツイン・XR・メタバースの視覚品質を向上させる。","platform_digital_innovation","AR・VR・空間コンピューティング",2018,None,"meso","製造・エンタメ・医療","ゲームエンジン産業応用","リアルタイム3D可視化を産業に展開する際","ゲームエンジンはどのような産業シミュレーション価値を持つか","業界特化3D","ゲームエンジン,Unity,Unreal,産業3D,デジタルツイン","game engine,Unity,Unreal,industrial 3D,digital twin","active","secondary",76,'["Tim Sweeney","John Riccitiello"]','["Epic Unreal Industrial 2022","Unity Industrial Report 2022"]',"レンダリング品質・産業採用率"),
    ("inno_digi_390","AIと創薬の倫理：データ・多様性・アクセス","Ethics of AI in Drug Discovery: Data Diversity and Access","AI創薬は訓練データの偏り(西洋集団過剰代表)・知的財産障壁・アクセス格差という倫理課題を持つ。Global Alliance for Genomics and Health(GA4GH)は多様なゲノムデータ共有標準を促進する。Medicines for Malaria Venture等のPDPがAI創薬ツールをNTD(顧みられない熱帯病)に応用する試みを展開する。","platform_digital_innovation","AI規制・ガバナンス",2022,None,"macro","製薬・公衆衛生","AI創薬倫理設計","AI創薬の公平性を確保する際","AI創薬の倫理課題はどのように解決されるか","特許保護創薬","AI創薬,倫理,多様性,NTD,GA4GH","AI drug discovery,ethics,diversity,NTD,GA4GH","active","secondary",74,'["GA4GH Staff","MMV Staff"]','["GA4GH Strategic Plan 2021","MMV Annual Report 2022"]',"多様性指標・アクセシブル薬品数"),
    ("inno_digi_391","デジタルツールと非公式経済の形式化","Digital Tools and Formalization of Informal Economy","途上国の非公式経済は労働力の50-80%を占め課税・保護・信用から排除されている。M-Pesa・mVisa等のデジタル決済が非公式取引を追跡可能にし形式化の入口となる。ILO(2021)は非公式経済のデジタル化が社会保護拡大の重要経路であると報告した。","platform_digital_innovation","デジタル包摂",2021,None,"macro","途上国・労働","非公式経済デジタル化","非公式経済の形式化を支援する際","デジタルツールは非公式経済をどのように形式化するか","現金のみ経済","非公式経済,デジタル決済,M-Pesa,形式化","informal economy,digital payment,M-Pesa,formalization","active","secondary",74,'["ILO Staff","CGD Staff"]','["ILO Informal Economy 2021","CGD Digitalization 2020"]',"非公式労働比率・デジタル決済普及率"),
    ("inno_digi_392","クラウドゲーミングとXaaS経済","Cloud Gaming and XaaS Economy","XaaS(Everything as a Service)経済はハードウェア・ソフトウェア・インフラをサービスとして提供するサブスクリプション経済の究極形態。Hirt & Willmott(2014)はデジタル戦略における「リンカーン効果(素早い模倣速度)」を分析した。SaaS ARR(Annual Recurring Revenue)が企業評価の主要指標となりサービス資産価値が製品資産価値を超える。","platform_digital_innovation","クラウドコンピューティング",2018,None,"meso","IT産業","XaaS事業設計","サービス型ビジネスモデルを設計する際","XaaS経済はどのように企業の収益構造を変えるか","製品販売","XaaS,SaaS,ARR,サブスクリプション,サービス化","XaaS,SaaS,ARR,subscription,servitization","active","secondary",76,'["Martyn Hirt","Paul Willmott"]','["Hirt Willmott 2014 McKinsey QR","Bessemer SaaS Atlas 2022"]',"ARR・顧客解約率"),
    ("inno_digi_393","生成AIの産業応用：人材採用と評価","Generative AI Industrial Application Recruitment and Assessment","LLMはJD作成・候補者スクリーニング・面接設計・能力評価に応用され採用プロセスを効率化する。HireVue・Pymetrics(Harver)・Workday AI Recruitingが商業展開する。リクルーティングAIのバイアス問題(Amazon 2018年事例)・EEOC指針が人事AIの倫理的使用基準を形成する。","platform_digital_innovation","AI・機械学習",2020,None,"meso","人事・採用","採用AIシステム設計","採用プロセスのAI化を検討する際","採用AIはどのような採用課題を解決しどのようなリスクを持つか","人手面接","採用AI,HireVue,スクリーニング,バイアス","recruitment AI,HireVue,screening,bias","active","secondary",76,'["HireVue Research","EEOC Staff"]','["EEOC AI Hiring 2023","Amazon AI Hiring Failure 2018"]',"採用時間・バイアス指標"),
    ("inno_digi_394","LiDARと自律センシングプラットフォーム","LiDAR and Autonomous Sensing Platform","LiDAR(Light Detection And Ranging)はレーザー光で3D点群データを生成し自動運転・ドローン・ロボットの空間認識基盤となる。Velodyne・Luminar・Aeye・Ousterが車載LiDARを展開する。ソリッドステートLiDARのコスト低下(1000ドル以下)が自動運転商業化の条件の一つとなる。","platform_digital_innovation","AI・機械学習",2018,None,"meso","モビリティ・ロボティクス","自律センシングシステム設計","自律移動システムの知覚センシングを設計する際","LiDARはどのような3D認識能力を実現するか","カメラのみ自律","LiDAR,点群,自動運転,ドローン","LiDAR,point cloud,autonomous driving,drone","active","secondary",76,'["Austin Russell","David Hall"]','["Luminar IPO 2020","Velodyne Technical Papers"]',"検知距離・コスト"),
    ("inno_digi_395","AIサプライチェーン最適化","AI Supply Chain Optimization","AIはサプライチェーンの需要予測・在庫最適化・ルート計画・サプライヤーリスク管理を同時に最適化する。Gartner(2023)はAI SCM投資が生産性20-30%向上をもたらすと推計した。コロナ後のサプライチェーン混乱がAI活用の緊急性を高め導入を加速した。ElasticityModelingとMulti-Echelon在庫最適化がAI SCMの中核手法となる。","platform_digital_innovation","AI・機械学習",2020,None,"meso","製造・小売","AI SCM導入","サプライチェーンの効率化をAIで実現する際","AIはサプライチェーンのどのコスト・リスクを削減するか","ルールベースSCM","AI SCM,需要予測,在庫最適化,Multi-Echelon","AI SCM,demand forecasting,inventory optimization,multi-echelon","active","secondary",78,'["Gartner SCM Research"]','["Gartner SCM AI Report 2023"]',"在庫削減率・サービスレベル"),
    ("inno_digi_396","デジタルイノベーションと所得分配","Digital Innovation and Income Distribution","デジタルイノベーションは高スキル・高所得層を優遇し低スキル雇用を代替することで所得格差を拡大するリスクを持つ。Autor et al.(2003)の「仕事の二極化」仮説がコンピュータ化とルーティン業務代替の関係を示した。デジタル経済の勝者がテクノロジー保有者と高スキル労働者に偏ることをPiketty(2014)の資本論が補完的に示す。","platform_digital_innovation","データ経済",2003,None,"macro","労働・経済政策","デジタル格差と分配政策","デジタルイノベーションの分配効果を評価する際","デジタル化は所得分配にどのような影響を与えるか","技術中立的成長","所得格差,仕事の二極化,Autor,デジタル化","income inequality,job polarization,Autor,digitalization","active","primary",82,'["David Autor","Daron Acemoglu"]','["Autor et al. 2003 QJE","Piketty 2014"]',"ジニ係数・賃金分布"),
    ("inno_digi_397","プラットフォームのロイヤルティプログラムと行動経済学","Platform Loyalty Program and Behavioral Economics","ポイントプログラム・ゲーミフィケーション・ゼロ価格効果を活用してユーザーの繰り返し利用・スイッチングコストを形成する。Thaler & Sunstein(2008)のナッジ理論がプラットフォームUI設計に応用される。AmazonPrime・Starbucks Rewards・航空会社マイレージが高LTVモデルの事例として分析される。","platform_digital_innovation","アルゴリズム経済",2008,None,"micro","EC・小売","ロイヤルティプログラム設計","顧客維持率とLTVを高める際","ロイヤルティプログラムはどのような行動変容をもたらすか","価格競争","ロイヤルティ,ポイント,Amazon Prime,ナッジ","loyalty,points,Amazon Prime,nudge","active","secondary",78,'["Richard Thaler","Cass Sunstein"]','["Thaler Sunstein 2008","Amazon Prime Economics 2022"]',"顧客維持率・LTV"),
    ("inno_digi_398","AIによる自然言語生成と報告書自動化","AI Natural Language Generation and Report Automation","NLG(自然言語生成)技術はデータから自動的にテキストレポートを生成する。Automated InsightsのWordsmithが財務報告・スポーツ記事・気象報告を自動生成する先行サービスとなった。LLMの台頭でNLGは記事生成・投資メモ・ESGレポートの自動化に広く応用されている。Associated Press・Reuters・NHKが自動ニュース生成を導入した実績がある。","platform_digital_innovation","AI・機械学習",2014,None,"meso","メディア・金融","NLG報告自動化","定型レポート作成を自動化する際","NLGはどのような報告業務を自動化するか","人手レポート","NLG,自然言語生成,Wordsmith,報告自動化","NLG,natural language generation,Wordsmith,report automation","active","secondary",76,'["Automated Insights"]','["Associated Press NLG Case 2014","Automated Insights Wordsmith"]',"生成時間・品質スコア"),
    ("inno_digi_399","プラットフォームとアントレプレナーシップ・エコシステム","Platform and Entrepreneurship Ecosystem","スタートアップエコシステムはVC・アクセラレータ・大学・大企業・メンター・コワーキングのプラットフォーム的ネットワークで構成される。Isenberg(2010)はアントレプレナーシップエコシステムの六要素(政策・金融・文化・支援・人材・市場)を定義した。Y Combinator・Techstars・500 Startupsがプラットフォームとしてスタートアップ成功率を向上させる。","platform_digital_innovation","デジタルプラットフォーム経済",2010,None,"macro","スタートアップ・政策","エコシステム設計","スタートアップ支援体制を設計する際","プラットフォームはアントレプレナーシップエコシステムをどう強化するか","孤立した起業家","スタートアップ,エコシステム,YC,Techstars","startup,ecosystem,YC,Techstars","active","secondary",78,'["Daniel Isenberg","Paul Graham"]','["Isenberg 2010 HBR","YC Company Stats 2023"]',"スタートアップ成功率・IPO数"),
    ("inno_digi_400","AIによる気候変動コミュニケーション","AI for Climate Change Communication","AI自然言語処理は気候変動コミュニケーション(ファクトチェック・感情分析・ターゲット最適化メッセージ)を支援する。ClimateBert(Webersinke et al. 2022)は気候関連テキスト分類の専用LLMとして研究・政策分析に活用される。気候否定論・グリーンウォッシング検出にNLPが有効なツールとして機能する。","platform_digital_innovation","エネルギー・環境DX",2022,None,"macro","気候コミュニケーション","AI気候コミュニケーション設計","気候変動情報の効果的伝達を設計する際","AIは気候変動コミュニケーションをどう改善するか","従来のマスコミュニケーション","AI気候,ClimateBert,グリーンウォッシング,ファクトチェック","AI climate,ClimateBert,greenwashing,fact-check","active","secondary",72,'["Nicolas Webersinke"]','["Webersinke et al. 2022 ClimateBert","IPCC Communication Report"]',"偽情報検出精度・コミュニケーション効果"),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()
insert_sql = """INSERT OR IGNORE INTO innovation_theory
(id, name_ja, name_en, definition, subfield, school_of_thought, era_start, era_end,
 methodology_level, target_domain, application_conditions, when_to_apply, framing_questions,
 opposing_concept_names, keywords_ja, keywords_en, status, source_reliability, data_completeness,
 key_researchers, key_works, measurement_approach)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
conn.executemany(insert_sql, records)
conn.commit()
print(f"Inserted: {conn.total_changes}")
cur.execute("SELECT COUNT(*) FROM innovation_theory WHERE subfield='platform_digital_innovation'")
print(f"Total: {cur.fetchone()[0]}")
conn.close()
