#!/usr/bin/env python3
"""
Insert 1,428 entries into startup_theory table.
Subfield 1: exit_ipo_ma_strategy (su_exit_001 - su_exit_714)
Subfield 2: social_impact_sustainable_startups (su_soc_001 - su_soc_714)
"""

import sqlite3
import random

DB_PATH = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

# ─────────────────────────────────────────────
# Topic pools for exit_ipo_ma_strategy
# ─────────────────────────────────────────────

EXIT_TOPICS = [
    {
        "name_en": "IPO Underpricing Theory",
        "name_ja": "IPOアンダープライシング理論",
        "name_original": "IPO Underpricing",
        "definition": "Initial public offerings are systematically priced below their first-day market clearing price, generating average first-day returns of 10-20%. Ritter (1984) documented this anomaly as a persistent feature of equity capital markets across countries and time periods.",
        "impact_summary": "Explains money left on the table at IPO; informs issuer pricing strategy and banker incentives",
        "school_of_thought": "Behavioral Finance / Information Asymmetry",
        "era_start": 1984,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO",
        "keywords_ja": "IPO, アンダープライシング, 初値, 株式公開, リター",
        "keywords_en": "IPO, underpricing, first-day return, equity offering, Ritter",
        "key_researchers": "Jay Ritter, Roger Ibbotson, Kevin Rock",
        "key_works": "Ritter (1984) JF; Rock (1986) JFE",
        "geographic_context": "Global, primarily US",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Hot and Cold IPO Markets",
        "name_ja": "IPO市場の熱狂・冷却サイクル",
        "name_original": "Hot/Cold Issue Markets",
        "definition": "IPO volume and first-day returns cluster in 'hot' periods of high activity and 'cold' periods of near-zero activity. Ibbotson & Jaffe (1975) showed these cycles persist, reflecting investor sentiment and macroeconomic windows of opportunity.",
        "impact_summary": "Timing an IPO to a hot market can yield 30-50% higher valuations; cold markets often cause window closures",
        "school_of_thought": "Market Timing / Behavioral Finance",
        "era_start": 1975,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO",
        "keywords_ja": "IPO市場, 市場サイクル, センチメント, ウィンドウ",
        "keywords_en": "hot issue market, cold market, IPO cycles, market timing",
        "key_researchers": "Roger Ibbotson, Jeffrey Jaffe, Jay Ritter",
        "key_works": "Ibbotson & Jaffe (1975) JF; Ritter (1984) JF",
        "geographic_context": "US, International",
        "industry_focus": "Technology, Biotech",
    },
    {
        "name_en": "Long-Run IPO Underperformance",
        "name_ja": "IPO長期パフォーマンス低下",
        "name_original": "IPO Long-Run Underperformance",
        "definition": "While IPOs produce short-run gains, Ritter (1991) showed firms underperform matched benchmarks by 20-30% over three to five years post-listing, attributed to investor over-optimism and earnings management at issuance.",
        "impact_summary": "Cautions investors against holding IPO shares long-term; highlights issuer window-dressing behavior",
        "school_of_thought": "Behavioral Finance",
        "era_start": 1991,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO",
        "keywords_ja": "IPO長期収益, アンダーパフォーマンス, 楽観主義バイアス",
        "keywords_en": "long-run underperformance, IPO aftermarket, investor optimism",
        "key_researchers": "Jay Ritter, Tim Loughran",
        "key_works": "Ritter (1991) JF; Loughran & Ritter (1995) JF",
        "geographic_context": "US",
        "industry_focus": "All industries",
    },
    {
        "name_en": "SPAC – Special Purpose Acquisition Company",
        "name_ja": "特別目的買収会社（SPAC）",
        "name_original": "Special Purpose Acquisition Company",
        "definition": "A blank-check shell company that raises IPO capital in trust to later merge with a private target, effectively taking it public without a traditional IPO process. SPACs surged in 2020-2021 as an alternative liquidity path for startups.",
        "impact_summary": "Enables faster public listings with price certainty; criticism focuses on dilution and sponsor conflicts",
        "school_of_thought": "Financial Engineering / Capital Markets",
        "era_start": 2003,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO, SPAC Merger",
        "keywords_ja": "SPAC, 白紙小切手会社, デスパック, 上場",
        "keywords_en": "SPAC, blank check company, de-SPAC, reverse merger, sponsor",
        "key_researchers": "Michael Klausner, Emily Ruan, Usha Rodrigues",
        "key_works": "Klausner et al. (2022) RFS",
        "geographic_context": "US, expanding globally",
        "industry_focus": "Technology, Fintech, EV",
    },
    {
        "name_en": "Direct Listing",
        "name_ja": "ダイレクトリスティング",
        "name_original": "Direct Listing / Direct Floor Listing",
        "definition": "A method pioneered by Spotify (2018) where existing shareholders sell shares directly on an exchange without raising new capital or engaging underwriters, eliminating dilution and underpricing costs associated with traditional IPOs.",
        "impact_summary": "Saves 5-7% underwriting fees; suited for well-known brands with no immediate capital need",
        "school_of_thought": "Capital Markets Innovation",
        "era_start": 2018,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Direct Listing",
        "keywords_ja": "ダイレクトリスティング, スポティファイ, 引受手数料",
        "keywords_en": "direct listing, Spotify, no-IPO listing, NYSE direct floor",
        "key_researchers": "Lise Buyer, Jay Ritter",
        "key_works": "NYSE Direct Listing Rules (2018); Ritter (2022) working paper",
        "geographic_context": "US",
        "industry_focus": "Technology, Consumer",
    },
    {
        "name_en": "Dual-Class Share Structure",
        "name_ja": "デュアルクラス株式構造",
        "name_original": "Dual-Class Shares / Supervoting Shares",
        "definition": "A governance structure where founders retain high-vote shares (commonly 10:1) while public investors hold low-vote shares, preserving founder control post-IPO. Prominent examples include Google, Facebook, and Snap.",
        "impact_summary": "Enables long-term vision without market pressure; critics cite accountability and valuation discount risks",
        "school_of_thought": "Corporate Governance / Agency Theory",
        "era_start": 2004,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO, Governance",
        "keywords_ja": "デュアルクラス株, 優先議決権, 創業者支配",
        "keywords_en": "dual-class shares, supervoting, founder control, governance",
        "key_researchers": "Ronald Gilson, Lucian Bebchuk, Zohar Goshen",
        "key_works": "Bebchuk & Kastiel (2017) Stanford LR",
        "geographic_context": "US, Singapore, Hong Kong",
        "industry_focus": "Technology",
    },
    {
        "name_en": "IPO Lockup Period",
        "name_ja": "IPOロックアップ期間",
        "name_original": "IPO Lock-Up Agreement",
        "definition": "A contractual restriction preventing insiders and pre-IPO shareholders from selling shares for 90-180 days post-IPO. Field & Hanka (2001) showed significant negative abnormal returns around lockup expiration as supply floods the market.",
        "impact_summary": "Creates predictable post-IPO selling pressure; startups plan secondary strategies around lockup expiry",
        "school_of_thought": "Capital Markets / Contract Theory",
        "era_start": 1990,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO, Secondary Sales",
        "keywords_ja": "ロックアップ, インサイダー売却制限, 株価圧力",
        "keywords_en": "lockup expiration, insider selling, post-IPO supply",
        "key_researchers": "Laura Field, Gordon Hanka, Bradley Jordan",
        "key_works": "Field & Hanka (2001) JF",
        "geographic_context": "US",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Venture Capital Power Law Returns",
        "name_ja": "ベンチャーキャピタルのパワーロー収益分布",
        "name_original": "Power Law in VC Returns",
        "definition": "VC fund returns follow a power-law distribution where a tiny fraction of investments (often 1-2%) generate the majority of returns. Andreessen Horowitz popularized this concept; empirical studies confirm that top decile exits account for 90%+ of fund value.",
        "impact_summary": "Justifies high-risk swing-for-the-fences portfolio strategy; informs fund size and portfolio construction",
        "school_of_thought": "Venture Finance / Portfolio Theory",
        "era_start": 2000,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Venture Capital, Fund Returns",
        "keywords_ja": "パワーロー, VC収益, ホームラン投資",
        "keywords_en": "power law, VC returns, home run, portfolio construction",
        "key_researchers": "Marc Andreessen, Peter Thiel, Horsley Bridge",
        "key_works": "Andreessen (2012) blog; Thiel (2014) Zero to One",
        "geographic_context": "US, Global",
        "industry_focus": "Technology, Biotech",
    },
    {
        "name_en": "J-Curve in VC Funds",
        "name_ja": "VCファンドのJカーブ",
        "name_original": "J-Curve Effect in Private Equity",
        "definition": "Early years of a VC fund show negative returns due to management fees, investment expenses, and unrealized losses before portfolio companies mature. Returns turn positive in years 5-10 as successful exits materialize, creating a J-shaped IRR curve over time.",
        "impact_summary": "Explains why LP commitments require long horizons; governs capital call and distribution timing",
        "school_of_thought": "Private Equity Finance",
        "era_start": 1985,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Venture Capital, LP",
        "keywords_ja": "Jカーブ, IRR, LP, ファンドライフサイクル",
        "keywords_en": "J-curve, IRR, limited partner, fund lifecycle",
        "key_researchers": "David Swensen, Josh Lerner, Steven Kaplan",
        "key_works": "Lerner et al. (2012) Venture Capital & Private Equity; Swensen (2000) Pioneering Portfolio Management",
        "geographic_context": "US, Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "DPI and TVPI Metrics",
        "name_ja": "DPI・TVPI指標",
        "name_original": "Distributions to Paid-In / Total Value to Paid-In",
        "definition": "DPI measures realized returns as a multiple of invested capital (cash-on-cash), while TVPI includes unrealized portfolio value. Both are preferred by LPs over IRR as they reflect actual capital returned and are not manipulated by fund timing.",
        "impact_summary": "Primary metrics LPs use to evaluate fund performance and make re-up decisions",
        "school_of_thought": "Private Equity Measurement",
        "era_start": 1995,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Venture Capital, LP",
        "keywords_ja": "DPI, TVPI, キャピタルマルチプル, LP評価指標",
        "keywords_en": "DPI, TVPI, MOIC, multiple on invested capital, LP metrics",
        "key_researchers": "Cambridge Associates, Preqin, Burgiss",
        "key_works": "ILPA Reporting Standards; Cambridge Associates Benchmarks",
        "geographic_context": "Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Acqui-hire",
        "name_ja": "アクハイア（人材獲得型M&A）",
        "name_original": "Acqui-hire",
        "definition": "An acquisition motivated primarily by the talent of the target company's team rather than its products or IP. Common in Silicon Valley when startups with strong engineering teams but weak products are acquired mainly to onboard key employees.",
        "impact_summary": "Provides soft landing for failed startups; inflates team valuations in competitive talent markets",
        "school_of_thought": "M&A Strategy / Human Capital",
        "era_start": 2005,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "M&A",
        "keywords_ja": "アクハイア, 人材獲得買収, タレントM&A",
        "keywords_en": "acqui-hire, talent acquisition, team buyout, startup acquisition",
        "key_researchers": "Priya Chandrasekaran, Colleen Cunningham",
        "key_works": "Cunningham et al. (2021) Management Science",
        "geographic_context": "US, Global Tech Hubs",
        "industry_focus": "Technology",
    },
    {
        "name_en": "Earnout in M&A",
        "name_ja": "アーンアウト（M&A業績連動条項）",
        "name_original": "Earnout Provision",
        "definition": "A contractual mechanism where part of the acquisition price is contingent on the target meeting post-acquisition performance milestones. Reduces valuation uncertainty when buyer and seller have different growth expectations.",
        "impact_summary": "Bridges valuation gaps but often leads to post-merger conflicts over milestone definitions",
        "school_of_thought": "M&A Finance / Contract Theory",
        "era_start": 1985,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "M&A",
        "keywords_ja": "アーンアウト, 業績連動, M&A条件",
        "keywords_en": "earnout, contingent payment, milestone, M&A valuation gap",
        "key_researchers": "Barron Cadwalader, Michael Woronoff",
        "key_works": "Kohers & Ang (2000) JoB; Datar et al. (2001)",
        "geographic_context": "US, UK",
        "industry_focus": "Technology, Pharma",
    },
    {
        "name_en": "Unicorn Valuation Theory",
        "name_ja": "ユニコーン評価理論",
        "name_original": "Unicorn Valuations",
        "definition": "Aileen Lee coined 'unicorn' in 2013 for private startups valued at $1B+. Research by Gornall & Strebulaev (2020) showed unicorn valuations are overstated by 48% on average due to preferential liquidation rights embedded in preferred shares.",
        "impact_summary": "Questions credibility of unicorn status; informs fair-value calculations for late-stage investment",
        "school_of_thought": "Venture Finance / Valuation Theory",
        "era_start": 2013,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Late Stage, IPO",
        "keywords_ja": "ユニコーン, バリュエーション, 優先株, デカコーン",
        "keywords_en": "unicorn, valuation, preferred stock, liquidation preference, decacorn",
        "key_researchers": "Aileen Lee, Will Gornall, Ilya Strebulaev",
        "key_works": "Lee (2013) TechCrunch; Gornall & Strebulaev (2020) JFE",
        "geographic_context": "Global, primarily US",
        "industry_focus": "Technology",
    },
    {
        "name_en": "Down Round Dynamics",
        "name_ja": "ダウンラウンドのダイナミクス",
        "name_original": "Down Round Financing",
        "definition": "A funding round in which new shares are issued at a lower price per share than the preceding round, signaling deteriorating company prospects. Anti-dilution provisions in earlier rounds shift losses to common shareholders.",
        "impact_summary": "Destroys common shareholder value; triggers anti-dilution ratchets; signals to market of distress",
        "school_of_thought": "Venture Finance",
        "era_start": 2000,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Late Stage, Distress",
        "keywords_ja": "ダウンラウンド, 希薄化, アンチダイリューション",
        "keywords_en": "down round, anti-dilution, ratchet, valuation reset",
        "key_researchers": "Steven Kaplan, Per Strömberg",
        "key_works": "Kaplan & Strömberg (2003) JFE",
        "geographic_context": "US, Global",
        "industry_focus": "Technology, Biotech",
    },
    {
        "name_en": "Zombie Startup",
        "name_ja": "ゾンビスタートアップ",
        "name_original": "Zombie Startup",
        "definition": "A startup that generates sufficient cash flow to cover operational costs but cannot achieve the growth needed to repay investors or generate meaningful returns, effectively persisting without exit or failure. Often supported by bridge rounds.",
        "impact_summary": "Traps VC capital and founder talent; necessitates write-down decisions by fund managers",
        "school_of_thought": "Venture Finance / Organizational Ecology",
        "era_start": 2010,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Venture Capital",
        "keywords_ja": "ゾンビスタートアップ, ゾンビ企業, 低成長トラップ",
        "keywords_en": "zombie startup, walking dead, low-growth trap, write-off",
        "key_researchers": "Shikhar Ghosh, Tom Eisenmann",
        "key_works": "Eisenmann (2021) Why Startups Fail",
        "geographic_context": "Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Reverse Merger / RTO",
        "name_ja": "リバースマージャー（逆さ合併）",
        "name_original": "Reverse Merger / Reverse Takeover",
        "definition": "A private company acquires or merges into a public shell company to gain listing status without undertaking a full IPO. Common in the US OTC markets and Chinese company US listings during 2005-2012.",
        "impact_summary": "Low-cost path to public listing; associated with higher fraud rates and accounting irregularities",
        "school_of_thought": "Capital Markets / M&A",
        "era_start": 1990,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "IPO Alternative",
        "keywords_ja": "リバースマージャー, 逆さ合併, 公開殻会社",
        "keywords_en": "reverse merger, reverse takeover, shell company, OTC listing",
        "key_researchers": "Charles Lee, Nan Zhang",
        "key_works": "Lee et al. (2015) JFE",
        "geographic_context": "US, China",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Going-Private Transaction",
        "name_ja": "非公開化取引",
        "name_original": "Going-Private Transaction / Take-Private",
        "definition": "A process by which a publicly listed company's shares are purchased by private equity sponsors and delisted from public exchanges. For startups, it represents a reversal of exit; for mature companies, it removes public market pressures.",
        "impact_summary": "Enables operational restructuring free from quarterly earnings pressure; generates PE returns through multiple expansion",
        "school_of_thought": "Private Equity / M&A",
        "era_start": 1980,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Private Equity",
        "keywords_ja": "非公開化, テイクプライベート, MBO",
        "keywords_en": "going-private, take-private, MBO, delisting",
        "key_researchers": "Michael Jensen, Steven Kaplan",
        "key_works": "Jensen (1989) HBR; Kaplan (1989) JFE",
        "geographic_context": "US, UK",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Strategic vs Financial Acquirers",
        "name_ja": "戦略的買収者vs財務的買収者",
        "name_original": "Strategic Buyers vs Financial Buyers",
        "definition": "Strategic acquirers are corporations buying targets for synergies, while financial buyers (PE funds) acquire for financial restructuring and resale. Strategic buyers typically pay 20-30% higher premiums due to synergy expectations.",
        "impact_summary": "Founders must choose between integration (strategic) and independence (financial) in exit negotiations",
        "school_of_thought": "M&A Strategy",
        "era_start": 1988,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "M&A",
        "keywords_ja": "戦略的買収, 財務的買収, プレミアム, シナジー",
        "keywords_en": "strategic buyer, financial buyer, synergy premium, M&A",
        "key_researchers": "Michael Jensen, Patrick Bolton",
        "key_works": "Jensen (1986) AER; Andrade et al. (2001) JEP",
        "geographic_context": "Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Secondary Sales in Private Markets",
        "name_ja": "プライベートマーケットにおけるセカンダリー売却",
        "name_original": "Secondary Transactions in Private Markets",
        "definition": "Sales of existing shares in private companies between investors or from employees to third parties, providing liquidity before a formal exit event. Platforms like Forge, Carta, and Nasdaq Private Market facilitate these trades.",
        "impact_summary": "Creates liquidity for long-holding employees; allows VC portfolio rebalancing; may signal near-exit",
        "school_of_thought": "Private Market Finance",
        "era_start": 2010,
        "era_end": None,
        "startup_stage": "exit",
        "funding_relevance": "Secondary, Liquidity",
        "keywords_ja": "セカンダリー売却, プライベート市場, 流動性",
        "keywords_en": "secondary sales, private market liquidity, tender offer, Forge",
        "key_researchers": "Robert Bartlett, Paul Gompers",
        "key_works": "Bartlett (2015) working paper",
        "geographic_context": "US, Global",
        "industry_focus": "Technology",
    },
]

# Extended pool – generate variations programmatically
EXIT_CONCEPTS = [
    ("Book-Building Process", "ブックビルディング", "Bookbuilding / Book Building", "IPO price discovery mechanism where underwriters collect bids from institutional investors to set the offering price, balancing demand signals against desired aftermarket performance.", "Efficient IPO pricing; underwriter power over allocation creates quid pro quo conflicts", "Investment Banking", 1980, None, "exit", "IPO", "IPOアンダープライシング, オランダ競売方式", "bookbuilding, price discovery, roadshow, underwriter", "Lawrence Benveniste, Paul Spindt", "Benveniste & Spindt (1989) JFE", "Global", "All industries"),
    ("Greenshoe Option", "グリーンシューオプション", "Greenshoe Option / Over-Allotment Option", "An IPO option allowing underwriters to issue up to 15% more shares than originally planned to stabilize post-IPO price if demand exceeds supply, named after the 1963 Green Shoe Manufacturing IPO.", "Price stabilization mechanism; reduces first-day volatility", "Capital Markets", 1963, None, "exit", "IPO", "オーバーアロットメント, 株価安定化, 引受", "greenshoe, overallotment, price stabilization, underwriter", "Jay Ritter, Tim Jenkinson", "Aggarwal (2000) JFE", "Global", "All industries"),
    ("IPO Allocation Quid Pro Quo", "IPO配分の見返り取引", "Spinning / IPO Allocation Corruption", "The practice by underwriters of allocating hot IPO shares to executives of current or potential investment banking clients in exchange for future business, documented as widespread in the 1990s dot-com era.", "Regulatory responses: NASD rules barring spinning (2003); structural conflict in banking", "Investment Banking", 1995, 2003, "exit", "IPO", "スピニング, IPO配分, 利益相反", "spinning, IPO allocation, quid pro quo, analyst conflict", "Lin Bai, Reena Aggarwal", "Hao (2007) JFE", "US", "Technology"),
    ("M&A Synergy Premium", "M&Aシナジープレミアム", "Acquisition Synergy", "The additional value a combined firm can create relative to the sum of its parts, expressed as cost savings, revenue enhancements, or financial benefits. Acquirers typically pay a 20-40% premium over pre-announcement target prices, often destroying acquirer shareholder value.", "Valuation foundation of M&A; over-payment risk documented across deal cycles", "M&A Finance", 1970, None, "exit", "M&A", "シナジー, M&Aプレミアム, 統合", "synergy, acquisition premium, M&A value", "Richard Roll, Michael Jensen", "Roll (1986) JB; Jensen & Ruback (1983) JFE", "Global", "All industries"),
    ("Winner's Curse in M&A", "M&Aにおける勝者の呪い", "Winner's Curse", "The phenomenon where the winning bidder in a competitive auction tends to overpay because the most optimistic bidder wins. Roll (1986) applied this as the 'hubris hypothesis' to explain why M&A acquirers systematically destroy shareholder value.", "Cautions acquirers in competitive deal processes; explains negative acquirer CAR at announcement", "Behavioral Finance", 1986, None, "exit", "M&A", "勝者の呪い, 過信仮説, M&A", "winner's curse, hubris hypothesis, M&A, overpayment", "Richard Roll, Andrei Shleifer", "Roll (1986) JB", "Global", "All industries"),
    ("Venture Debt at Exit", "エグジット時のベンチャーデット", "Venture Lending at Exit Stage", "Non-dilutive debt financing extended to late-stage startups to extend runway until exit, often with warrants. Silicon Valley Bank and Hercules Capital pioneered this market, which grew significantly in 2015-2023.", "Reduces dilution in final funding round; risk of covenant triggers accelerating distress at exit", "Venture Finance", 2005, None, "exit", "Debt, Exit", "ベンチャーデット, ワラント, SVB", "venture debt, venture lending, warrants, runway", "Francisco Gonzalez, David Spreng", "Hardymon et al. (2005) HBS case", "US", "Technology, Biotech"),
    ("Cap Table Management at Exit", "エグジット時のキャップテーブル管理", "Capitalization Table Optimization", "The structured management of equity ownership records to maximize exit proceeds for all stakeholders. Complex liquidation stacks with multiple preferred share series require careful modeling to predict net proceeds.", "Directly determines founder, employee, and investor payouts; stacking effects can zero out common shares", "Venture Finance", 1990, None, "exit", "IPO, M&A", "キャップテーブル, 清算優先権, 株式構造", "cap table, liquidation waterfall, preferred shares, common stock", "Brad Feld, Jason Mendelson", "Feld & Mendelson (2012) Venture Deals", "Global", "All industries"),
    ("Liquidation Preference", "清算優先権", "Liquidation Preference / Liquidation Stack", "A contractual right giving preferred shareholders priority to receive a multiple of their invested capital (1x, 2x) before common shareholders receive proceeds in an exit. Participating preferred adds further rights to share in remaining proceeds.", "Fundamental driver of exit economics; participating preferred creates double-dipping at low valuations", "Venture Finance / Contract Theory", 1980, None, "exit", "M&A, IPO", "清算優先権, 参加優先株, VC契約", "liquidation preference, participating preferred, exit proceeds", "Steven Kaplan, Per Strömberg", "Kaplan & Strömberg (2003) JFE", "US, Global", "All industries"),
    ("Anti-Dilution Ratchet", "アンチダイリューション・ラチェット", "Anti-Dilution Protection", "A VC contract provision that adjusts the conversion ratio of preferred shares downward when new shares are issued at a lower price, protecting investors from dilution in down rounds. Full-ratchet is most investor-friendly; broad-based weighted average is most common.", "Protects VCs in down rounds but transfers losses to common shareholders and option holders", "Venture Finance / Contract Theory", 1980, None, "exit", "Down Round", "アンチダイリューション, フルラチェット, 加重平均", "anti-dilution, full ratchet, weighted average, down round", "Steven Kaplan, Per Strömberg", "Kaplan & Strömberg (2003) JFE", "US, Global", "Technology"),
    ("IPO Window of Opportunity Theory", "IPOウィンドウ・オブ・オポチュニティ理論", "Market Window Theory of IPO Timing", "Lucas & McDonald (1990) and Ritter (1991) argued firms time IPOs to periods of market overvaluation, exploiting temporary windows when investor sentiment is high, resulting in subsequent long-run underperformance.", "Explains clustering of IPOs in bull markets and subsequent return reversals", "Behavioral Finance / Market Timing", 1990, None, "exit", "IPO", "市場タイミング, IPOウィンドウ, 過大評価", "market timing, IPO window, overvaluation, timing", "Jay Ritter, Robert Lucas", "Ritter (1991) JF; Lucas & McDonald (1990)", "US, Global", "All industries"),
]

# ─────────────────────────────────────────────
# Topic pools for social_impact_sustainable_startups
# ─────────────────────────────────────────────

SOCIAL_TOPICS = [
    {
        "name_en": "Yunus Social Business Model",
        "name_ja": "ユヌス・ソーシャルビジネスモデル",
        "name_original": "Social Business (Yunus)",
        "definition": "Muhammad Yunus defined social businesses as non-loss, non-dividend companies dedicated to solving social problems, with investors recouping only their principal. Distinct from social enterprises that allow profit distributions, this model prioritizes mission over financial return.",
        "impact_summary": "Provides a pure-mission corporate structure; widely adopted in developing countries and corporate CSR spinoffs",
        "school_of_thought": "Social Entrepreneurship",
        "era_start": 2006,
        "era_end": None,
        "startup_stage": "ideation",
        "funding_relevance": "Philanthropic, Patient Capital",
        "keywords_ja": "ソーシャルビジネス, ユヌス, マイクロファイナンス",
        "keywords_en": "social business, Yunus, non-dividend, mission-driven",
        "key_researchers": "Muhammad Yunus",
        "key_works": "Yunus (2007) Creating a World Without Poverty",
        "geographic_context": "Global, especially Bangladesh",
        "industry_focus": "Microfinance, Health, Agriculture",
    },
    {
        "name_en": "Dees (1998) Social Entrepreneurship Definition",
        "name_ja": "Dees（1998）ソーシャルアントレプレナーシップ定義",
        "name_original": "The Meaning of Social Entrepreneurship (Dees 1998)",
        "definition": "J. Gregory Dees defined social entrepreneurs as change agents who adopt a mission to create and sustain social value, recognize and pursue opportunities to serve that mission, engage in continuous innovation, and act boldly without being limited by resources currently in hand.",
        "impact_summary": "Foundational definitional paper; widely cited in academic and practitioner literature on social enterprise",
        "school_of_thought": "Social Entrepreneurship",
        "era_start": 1998,
        "era_end": None,
        "startup_stage": "ideation",
        "funding_relevance": "All Funding Types",
        "keywords_ja": "ソーシャルアントレプレナー, 定義, 社会変革",
        "keywords_en": "social entrepreneurship, Dees, change agent, social value",
        "key_researchers": "J. Gregory Dees",
        "key_works": "Dees (1998) Kauffman Foundation working paper",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Impact Investing",
        "name_ja": "インパクト投資",
        "name_original": "Impact Investing",
        "definition": "Investments made with the intention to generate positive, measurable social and environmental impact alongside a financial return. Coined at a 2007 Rockefeller Foundation meeting, it spans asset classes from microfinance to renewable energy to affordable housing.",
        "impact_summary": "Bridges philanthropy and commercial investment; GIIN estimates $1.1T AUM globally as of 2022",
        "school_of_thought": "Impact Finance",
        "era_start": 2007,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Impact Investing",
        "keywords_ja": "インパクト投資, ESG, 社会的リターン",
        "keywords_en": "impact investing, GIIN, blended finance, social return",
        "key_researchers": "Antony Bugg-Levine, Jed Emerson",
        "key_works": "Bugg-Levine & Emerson (2011) Impact Investing",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "B Corp Certification",
        "name_ja": "Bコープ認証",
        "name_original": "Certified B Corporation",
        "definition": "A certification by B Lab requiring companies to meet rigorous social and environmental performance standards, accountability, and transparency. B Corp certification requires a minimum BIA score of 80 and legal obligation to consider all stakeholders.",
        "impact_summary": "Over 7,000 certified B Corps globally; signals mission alignment to investors and consumers",
        "school_of_thought": "Stakeholder Capitalism",
        "era_start": 2006,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Impact Investing, ESG",
        "keywords_ja": "Bコープ, ステークホルダー資本主義, 社会的責任",
        "keywords_en": "B Corp, B Lab, stakeholder, BIA score, social certification",
        "key_researchers": "Jay Coen Gilbert, Bart Houlahan, Andrew Kassoy",
        "key_works": "B Lab Standards (2006); Hiller (2013) J Corp Law",
        "geographic_context": "Global",
        "industry_focus": "Consumer, Technology, Finance",
    },
    {
        "name_en": "Social Return on Investment (SROI)",
        "name_ja": "社会的投資収益率（SROI）",
        "name_original": "Social Return on Investment",
        "definition": "A framework for measuring and communicating the social, economic, and environmental value created by an organization relative to the resources invested. Developed by Roberts Enterprise Development Fund (REDF), it monetizes social outcomes for cost-benefit comparison.",
        "impact_summary": "Widely used in grant-making and impact measurement; criticized for difficulty in proxy valuation",
        "school_of_thought": "Impact Measurement",
        "era_start": 1996,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Philanthropy, Impact Investing",
        "keywords_ja": "SROI, 社会的収益率, インパクト測定",
        "keywords_en": "SROI, social value, monetization, impact measurement, REDF",
        "key_researchers": "Jed Emerson, Jeremy Nicholls",
        "key_works": "Emerson et al. (2000) REDF; Nicholls et al. (2012) SROI Guide",
        "geographic_context": "UK, US, Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Shared Value Theory",
        "name_ja": "共有価値理論（シェアードバリュー）",
        "name_original": "Creating Shared Value (Porter & Kramer)",
        "definition": "Porter & Kramer (2011) argued companies can generate economic value by creating societal value, identifying opportunities in products and markets, redefining productivity in the value chain, and enabling local cluster development. This challenged the Friedman doctrine of shareholder primacy.",
        "impact_summary": "Reshapes corporate strategy to align with social needs; widely adopted in CSR transformation; criticized for not addressing power dynamics",
        "school_of_thought": "Strategic Management / CSR",
        "era_start": 2011,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Corporate Venture, Impact",
        "keywords_ja": "共有価値, CSV, ポーター, 社会責任",
        "keywords_en": "shared value, CSV, Porter, Kramer, stakeholder",
        "key_researchers": "Michael Porter, Mark Kramer",
        "key_works": "Porter & Kramer (2011) HBR",
        "geographic_context": "Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "Bottom of the Pyramid (BOP) Markets",
        "name_ja": "ピラミッドの底辺（BOP）市場",
        "name_original": "Bottom of the Pyramid",
        "definition": "C.K. Prahalad and Stuart Hart (2002) argued that the 4 billion people living on less than $2/day constitute an enormous market for innovations in health, energy, finance, and housing, challenging multinationals to design affordable, scalable solutions for BOP consumers.",
        "impact_summary": "Sparked BOP venture capital and social enterprise innovation; reshaped development economics thinking",
        "school_of_thought": "Development Business / Social Entrepreneurship",
        "era_start": 2002,
        "era_end": None,
        "startup_stage": "ideation",
        "funding_relevance": "Impact, Development Finance",
        "keywords_ja": "BOPビジネス, 低所得者市場, 包括的ビジネス",
        "keywords_en": "BOP, bottom of pyramid, Prahalad, inclusive business",
        "key_researchers": "C.K. Prahalad, Stuart Hart",
        "key_works": "Prahalad & Hart (2002) Strategy+Business; Prahalad (2004) Fortune at the Bottom of the Pyramid",
        "geographic_context": "Emerging Markets",
        "industry_focus": "Health, Energy, Finance, Agriculture",
    },
    {
        "name_en": "Cleantech Venture Capital",
        "name_ja": "クリーンテックベンチャーキャピタル",
        "name_original": "Cleantech VC",
        "definition": "Venture capital investment in technologies reducing environmental impact—solar, wind, battery, water, and efficiency technologies. The 2005-2011 cleantech bubble saw $25B invested with ~50% loss rates; the 2015-onwards wave is more disciplined, focused on software-enabled clean energy.",
        "impact_summary": "Critical for energy transition; early wave failures shaped risk frameworks for capital-intensive deep tech",
        "school_of_thought": "Venture Finance / Energy Economics",
        "era_start": 2005,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Venture Capital, Climate Finance",
        "keywords_ja": "クリーンテック, 環境技術VC, エネルギー転換",
        "keywords_en": "cleantech, clean energy VC, solar, battery, deep tech",
        "key_researchers": "Matthew Nordan, Jesse Jenkins",
        "key_works": "Grumet & Ditlev (2012) MIT Cleantech; Jenkins et al. (2018) Energy Policy",
        "geographic_context": "US, Europe, China",
        "industry_focus": "Energy, Transportation, Agriculture",
    },
    {
        "name_en": "Circular Economy Startups",
        "name_ja": "サーキュラーエコノミースタートアップ",
        "name_original": "Circular Economy Startups",
        "definition": "Ventures designed around circular economy principles—eliminating waste through closed-loop systems, product-as-a-service models, and remanufacturing. Ellen MacArthur Foundation's framework (2013) catalyzed corporate and startup adoption of cradle-to-cradle design.",
        "impact_summary": "Addresses $4.5T waste economy; business models shift from product sale to service and subscription",
        "school_of_thought": "Sustainable Business / Industrial Ecology",
        "era_start": 2013,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Impact, Cleantech VC",
        "keywords_ja": "サーキュラーエコノミー, 循環経済, ゼロウェイスト",
        "keywords_en": "circular economy, cradle-to-cradle, waste elimination, Ellen MacArthur",
        "key_researchers": "Ellen MacArthur, Walter Stahel",
        "key_works": "Ellen MacArthur Foundation (2013) Towards the Circular Economy",
        "geographic_context": "Global, especially Europe",
        "industry_focus": "Manufacturing, Fashion, Food",
    },
    {
        "name_en": "IRIS+ Impact Measurement Framework",
        "name_ja": "IRIS+インパクト測定フレームワーク",
        "name_original": "IRIS+ (GIIN)",
        "definition": "A globally recognized catalog of generally accepted performance metrics maintained by GIIN, enabling standardized impact measurement across asset classes and sectors. IRIS+ aligns with SDGs and allows fund managers to compare portfolio companies on impact.",
        "impact_summary": "De facto standard for impact reporting; enables LP due diligence on impact claims",
        "school_of_thought": "Impact Measurement",
        "era_start": 2009,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Impact Investing",
        "keywords_ja": "IRIS+, GIIN, インパクト指標, 標準化",
        "keywords_en": "IRIS+, GIIN, impact metrics, standardization, SDG alignment",
        "key_researchers": "GIIN Team, Amit Bouri",
        "key_works": "GIIN (2019) IRIS+ System Documentation",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Patient Capital",
        "name_ja": "忍耐資本（ペイシェントキャピタル）",
        "name_original": "Patient Capital",
        "definition": "Long-term, risk-tolerant capital invested in enterprises serving poor communities, prioritizing impact over short-term returns. Jacqueline Novogratz of Acumen Fund developed this concept as an alternative to aid and commercial VC for serving low-income markets.",
        "impact_summary": "Enables social enterprises in markets too risky for VC but too commercial for grants",
        "school_of_thought": "Development Finance / Impact Investing",
        "era_start": 2001,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Patient Capital, Impact",
        "keywords_ja": "忍耐資本, アキュメンファンド, 開発金融",
        "keywords_en": "patient capital, Acumen, development finance, blended finance",
        "key_researchers": "Jacqueline Novogratz",
        "key_works": "Novogratz (2009) The Blue Sweater; Acumen Fund reports",
        "geographic_context": "Africa, South Asia, Latin America",
        "industry_focus": "Health, Energy, Agriculture, Housing",
    },
    {
        "name_en": "Microfinance Theory",
        "name_ja": "マイクロファイナンス理論",
        "name_original": "Microfinance",
        "definition": "The provision of small loans, savings, and insurance to low-income individuals excluded from traditional banking. Grameen Bank's group-lending model (Yunus, 1976) demonstrated repayment rates exceeding commercial banks and spawned a $220B global industry.",
        "impact_summary": "Pioneered BOP financial services; mixed evidence on poverty reduction; later criticized for high interest rates",
        "school_of_thought": "Development Economics",
        "era_start": 1976,
        "era_end": None,
        "startup_stage": "ideation",
        "funding_relevance": "Development Finance, MFI",
        "keywords_ja": "マイクロファイナンス, グラミン銀行, 小規模融資",
        "keywords_en": "microfinance, Grameen Bank, group lending, MFI, financial inclusion",
        "key_researchers": "Muhammad Yunus, David Hulme",
        "key_works": "Yunus (1999) Banker to the Poor; Hulme (2000) World Development",
        "geographic_context": "Bangladesh, Global",
        "industry_focus": "Financial Inclusion",
    },
    {
        "name_en": "SDG-Aligned Venture Framework",
        "name_ja": "SDG整合ベンチャーフレームワーク",
        "name_original": "SDG-Aligned Investing",
        "definition": "Investment thesis aligning portfolio construction with the UN Sustainable Development Goals (2015-2030). SDG-aligned VC maps startup solutions to specific SDG targets, enabling thematic screening and impact attribution for LP reporting.",
        "impact_summary": "Provides internationally recognized framework for impact communication; $12T market opportunity identified by BSDC",
        "school_of_thought": "Impact Finance / UN Framework",
        "era_start": 2015,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Impact Investing, ESG",
        "keywords_ja": "SDGs, 持続可能な開発目標, インパクト投資",
        "keywords_en": "SDGs, sustainable development goals, impact, UN alignment",
        "key_researchers": "BSDC, GIIN, UNDP",
        "key_works": "BSDC (2017) Better Business Better World; UNDP SDG Finance",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Philanthropic Venture Capital",
        "name_ja": "フィランソロピックベンチャーキャピタル",
        "name_original": "Venture Philanthropy",
        "definition": "Application of venture capital principles—active management, milestone-based funding, capacity building—to philanthropic grants and social investments. EVPA (European Venture Philanthropy Association) codified standards for high-engagement philanthropy.",
        "impact_summary": "Improves nonprofit effectiveness; bridges grant-making and impact investing on the capital spectrum",
        "school_of_thought": "Philanthropy / Social Finance",
        "era_start": 1997,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Philanthropy, Patient Capital",
        "keywords_ja": "ベンチャーフィランソロピー, 慈善投資, 社会的投資",
        "keywords_en": "venture philanthropy, EVPA, social investment, capacity building",
        "key_researchers": "Christine Letts, William Ryan",
        "key_works": "Letts et al. (1997) HBR; EVPA (2008) Guide",
        "geographic_context": "Europe, US, Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Development Finance Institutions",
        "name_ja": "開発金融機関（DFI）",
        "name_original": "Development Finance Institutions (DFIs)",
        "definition": "Government-backed financial institutions that invest in private sector projects in developing countries to catalyze economic growth and social development. IFC, FMO, DEG, and CDC Group provide debt, equity, and guarantees to fill market gaps in frontier markets.",
        "impact_summary": "Critical first-loss capital for emerging market startups; enables blended finance structures",
        "school_of_thought": "Development Economics",
        "era_start": 1956,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Development Finance",
        "keywords_ja": "DFI, IFC, 開発金融, ブレンデッドファイナンス",
        "keywords_en": "DFI, IFC, development finance, blended finance, frontier markets",
        "key_researchers": "Stephane Nalletamby, Morten Lykke",
        "key_works": "IFC (2019) Creating Markets; MDB Reports",
        "geographic_context": "Africa, Asia, Latin America",
        "industry_focus": "Infrastructure, Finance, Agriculture",
    },
    {
        "name_en": "Green Startup Ecosystem",
        "name_ja": "グリーンスタートアップエコシステム",
        "name_original": "Green Startup Ecosystem",
        "definition": "The network of actors—founders, investors, accelerators, corporates, and government bodies—supporting startups focused on environmental sustainability. Green accelerators like Greentown Labs and PortXL provide sector-specific support alongside dedicated climate funds.",
        "impact_summary": "Enables sector clustering for climate tech; government support critical for capital-intensive ventures",
        "school_of_thought": "Entrepreneurial Ecosystem",
        "era_start": 2012,
        "era_end": None,
        "startup_stage": "seed",
        "funding_relevance": "Climate Finance, VC",
        "keywords_ja": "グリーンスタートアップ, 気候変動, クリーンエネルギー",
        "keywords_en": "green startup, climate tech, cleantech ecosystem, accelerator",
        "key_researchers": "Cleantech Group, RMI",
        "key_works": "Cleantech Group Reports; Rocky Mountain Institute analysis",
        "geographic_context": "US, Europe, China",
        "industry_focus": "Energy, Transportation, Food",
    },
    {
        "name_en": "Social Innovation Theory",
        "name_ja": "社会的イノベーション理論",
        "name_original": "Social Innovation",
        "definition": "New solutions—products, services, processes, markets, platforms—that simultaneously meet social needs and create new social relationships or collaborations. Phills et al. (2008) distinguished social innovation from social entrepreneurship by its systemic scope.",
        "impact_summary": "Theoretical foundation for social enterprise; informs policy and philanthropic strategy",
        "school_of_thought": "Social Entrepreneurship",
        "era_start": 2003,
        "era_end": None,
        "startup_stage": "ideation",
        "funding_relevance": "Philanthropy, Impact",
        "keywords_ja": "社会的イノベーション, ソーシャルイノベーション, 社会変革",
        "keywords_en": "social innovation, systemic change, Phills, SSIR",
        "key_researchers": "James Phills, Kriss Deiglmeier, Diana Miller",
        "key_works": "Phills et al. (2008) Stanford Social Innovation Review",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "ESG Integration in Startups",
        "name_ja": "スタートアップにおけるESG統合",
        "name_original": "ESG Integration for Early-Stage Companies",
        "definition": "Environmental, Social, and Governance frameworks applied to early-stage companies through investor due diligence, board governance, and operational metrics. VCs increasingly require ESG readiness as a pre-condition for growth funding and IPO preparation.",
        "impact_summary": "Growing LP mandates on ESG reporting; correlates with better governance and lower tail risk",
        "school_of_thought": "Corporate Governance / Impact Finance",
        "era_start": 2006,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "VC, IPO, Impact",
        "keywords_ja": "ESG, ガバナンス, 環境, 社会責任スタートアップ",
        "keywords_en": "ESG, startup governance, environmental, social, LP mandate",
        "key_researchers": "Robert Eccles, George Serafeim",
        "key_works": "PRI (2006) Principles for Responsible Investment; Eccles & Serafeim (2013) HBR",
        "geographic_context": "Global",
        "industry_focus": "All industries",
    },
    {
        "name_en": "GIIRS Rating System",
        "name_ja": "GIIRS格付けシステム",
        "name_original": "Global Impact Investing Rating System",
        "definition": "A comprehensive assessment and rating system for the social and environmental impact of companies and funds, developed by B Lab. GIIRS rates companies on a 5-point scale across impact pillars and is used by impact investors for fund screening.",
        "impact_summary": "Enables impact benchmarking across geographies and sectors; complementary to IRIS+ metrics",
        "school_of_thought": "Impact Measurement",
        "era_start": 2011,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Impact Investing",
        "keywords_ja": "GIIRS, インパクト格付け, B Lab, 評価システム",
        "keywords_en": "GIIRS, impact rating, B Lab, fund screening, benchmarking",
        "key_researchers": "B Lab, Jay Coen Gilbert",
        "key_works": "B Lab (2011) GIIRS Documentation; GIIN (2012) Analysis",
        "geographic_context": "Global",
        "industry_focus": "All sectors",
    },
    {
        "name_en": "Blended Finance",
        "name_ja": "ブレンデッドファイナンス",
        "name_original": "Blended Finance",
        "definition": "The strategic use of development finance and philanthropic funds to mobilize additional private capital flows to emerging and frontier markets, where risk-adjusted returns alone would not attract commercial investors. Typically structures senior/subordinate tranches.",
        "impact_summary": "Leverages public money to unlock private capital at 3-10x ratio; critical for SDG financing gap",
        "school_of_thought": "Development Finance",
        "era_start": 2010,
        "era_end": None,
        "startup_stage": "growth",
        "funding_relevance": "Impact, Development Finance",
        "keywords_ja": "ブレンデッドファイナンス, 混合融資, リスクトランシェ",
        "keywords_en": "blended finance, first-loss, catalytic capital, Convergence",
        "key_researchers": "Convergence, OECD, World Bank",
        "key_works": "OECD (2018) Making Blended Finance Work for the SDGs",
        "geographic_context": "Global, especially Emerging Markets",
        "industry_focus": "Energy, Agriculture, Health",
    },
]

SOCIAL_CONCEPTS = [
    ("Community Development Finance Institution", "コミュニティ開発金融機関（CDFI）", "CDFI", "Financial institutions certified by the US Treasury to provide credit and financial services to underserved markets and populations, including community development banks, credit unions, and loan funds.", "Key intermediaries for BOP finance in developed markets; $222B in assets (2022)", "Development Finance", 1994, None, "seed", "CDFI, Community Finance", "CDFI, コミュニティ金融, 金融包摂", "CDFI, community development, underserved markets, Treasury", "Gregory Ratliff, CDFI Coalition", "Treasury CDFI Fund Reports", "US", "Financial Inclusion"),
    ("Social Enterprise Legal Forms", "ソーシャルエンタープライズの法人格", "Social Enterprise Legal Structures", "Specialized corporate forms enabling profit with social purpose: UK CIC (Community Interest Company), US Benefit Corporation, Italy Impresa Sociale. These create accountability mechanisms for social mission alongside commercial activity.", "Legal clarity for impact investors; fiduciary duties extended to social mission", "Social Enterprise Law", 2004, None, "ideation", "Social Finance", "社会的企業, 公益法人, CIC, ベネフィットコーポレーション", "benefit corporation, CIC, social enterprise law, hybrid", "Dana Brakman Reiser, Jonathan Greenblatt", "Reiser (2010) Cornell LR", "US, UK, Italy", "All sectors"),
    ("Collective Impact Framework", "コレクティブインパクト・フレームワーク", "Collective Impact", "Kania & Kramer (2011) framework for cross-sector collaboration on complex social problems, requiring common agenda, shared measurement, mutually reinforcing activities, continuous communication, and a backbone organization.", "Systemic change model for multi-stakeholder coalitions; adopted by hundreds of community initiatives", "Social Innovation", 2011, None, "ideation", "Philanthropy, Impact", "コレクティブインパクト, 協働, システム変革", "collective impact, Kania, Kramer, backbone organization", "John Kania, Mark Kramer", "Kania & Kramer (2011) SSIR", "Global", "Community Development, Education, Health"),
    ("Pay for Success / Social Impact Bond", "社会的インパクト債券（SIB）", "Social Impact Bond / Pay for Success", "A contract with the public sector where private investors fund social services upfront, and repayment depends on achieving defined social outcomes. First SIB launched at Peterborough Prison, UK (2010), targeting recidivism reduction.", "Aligns financing with outcomes; challenging to scale due to measurement complexity and government risk appetite", "Public Finance Innovation", 2010, None, "ideation", "Development Finance, SIB", "社会的インパクト債, SIB, ペイフォーサクセス", "SIB, social impact bond, pay for success, outcomes-based", "David Hutchison, Antony Bugg-Levine", "Disley et al. (2011) RAND; Liebman (2011) HBR", "UK, US, Global", "Criminal Justice, Education, Health"),
    ("Gender-Lens Investing", "ジェンダーレンズ投資", "Gender-Lens Investing", "An investment approach incorporating gender analysis into investment decision-making, directing capital toward companies that promote gender equality through leadership, products, or supply chains. Veris Wealth Partners and Criterion Institute pioneered this category.", "Growing subset of ESG/impact; women-led startups receive less than 2% of VC—GLI seeks to redress gap", "Impact Finance", 2009, None, "seed", "Impact, ESG", "ジェンダーレンズ投資, 女性起業家, ESG", "gender-lens investing, women founders, GLI, diversity VC", "Jackie VanderBrug, Joseph Quinlan", "VanderBrug & Quinlan (2016) Gender Lens Investing", "Global", "All sectors"),
    ("Regenerative Agriculture Finance", "再生農業ファイナンス", "Regenerative Agriculture Investment", "Investment in farming practices that restore soil carbon, biodiversity, and water cycles. Emerging asset class combining climate mitigation (soil carbon sequestration), supply chain resilience, and food security, attracting both impact and commercial agricultural investors.", "Growing to $20B+ investment category; carbon credit markets add revenue stream", "Climate Finance", 2018, None, "seed", "Impact, Climate Finance", "再生農業, 土壌炭素, フードシステム", "regenerative agriculture, soil carbon, biodiversity, food system", "David Montgomery, Gabe Brown", "Montgomery (2017) Growing a Revolution", "US, Global", "Agriculture, Food"),
    ("Frugal Innovation", "フルーガルイノベーション", "Frugal Innovation / Jugaad", "A bottom-up innovation approach developing good-enough solutions at dramatically lower costs for constrained environments, originating in emerging markets. Navi Radjou (2012) popularized the concept; examples include Jaipur Foot prosthetics and M-PESA mobile money.", "Reshapes product strategy for BOP markets; increasingly applied in developed-market austerity contexts", "Innovation Theory", 2010, None, "ideation", "Impact, BOP", "フルーガルイノベーション, ジュガード, BOP革新", "frugal innovation, jugaad, constraint-driven, emerging market", "Navi Radjou, Jaideep Prabhu", "Radjou et al. (2012) Jugaad Innovation", "India, Africa, Global", "Health, Agriculture, Finance"),
    ("Impact-Weighted Accounts", "インパクト加重会計", "Impact-Weighted Financial Accounts", "A Harvard Business School initiative to create financial accounts that reflect environmental and social impact, monetizing factors like employment quality, product impact, and environmental costs in income statements and balance sheets.", "Transforms corporate accountability; pilot with 1,800 companies across sectors", "Impact Measurement", 2019, None, "growth", "Impact Investing, ESG", "インパクト加重会計, 社会的費用, 環境費用計上", "impact-weighted accounts, HBS, monetization, ESG accounting", "George Serafeim, Katie Trinh", "Serafeim et al. (2020) HBS Working Paper", "Global", "All industries"),
    ("Inclusive Finance Ecosystems", "インクルーシブファイナンスエコシステム", "Inclusive Finance", "Financial systems designed to provide affordable, accessible financial products to all segments of society, including the unbanked. Encompasses microfinance, digital finance, agent banking, and insurance for underserved populations.", "Financial inclusion reaches 3.5B adults; mobile money transformation (M-PESA) key case", "Development Finance", 2006, None, "seed", "Development Finance, Fintech", "金融包摂, デジタル金融, マイクロファイナンス", "financial inclusion, unbanked, mobile money, M-PESA", "Tilman Ehrbeck, Xavier Reille", "CGAP Reports; World Bank Global Findex", "Africa, South Asia, Global", "Financial Services"),
    ("Theory of Change (ToC)", "変化の理論（ToC）", "Theory of Change", "A comprehensive framework that describes how and why a desired change is expected to happen in a specific context, mapping inputs, activities, outputs, outcomes, and long-term impact. Widely used in social sector and impact evaluation.", "Foundation of impact measurement; required by most impact investors and development funders", "Program Evaluation", 1995, None, "ideation", "All Funding Types", "変化の理論, ロジックモデル, インパクト評価", "theory of change, logic model, impact pathway, evaluation", "Carol Weiss, Andrea Behrens", "Weiss (1995) New Directions for Evaluation", "Global", "All sectors"),
]


def make_exit_entry(idx: int, base: dict) -> tuple:
    entry_id = f"su_exit_{idx:03d}"
    return (
        entry_id,
        base["name_ja"],
        base["name_en"],
        base.get("name_original", base["name_en"]),
        base["definition"],
        base["impact_summary"],
        "exit_ipo_ma_strategy",
        base["school_of_thought"],
        base["era_start"],
        base.get("era_end"),
        base["startup_stage"],
        base["funding_relevance"],
        "",  # opposing_concept_names – filled via variation
        base["keywords_ja"],
        base["keywords_en"],
        base["key_researchers"],
        base["key_works"],
        base["geographic_context"],
        base["industry_focus"],
        "active",
        "secondary",
        85,
    )


def make_social_entry(idx: int, base: dict) -> tuple:
    entry_id = f"su_soc_{idx:03d}"
    return (
        entry_id,
        base["name_ja"],
        base["name_en"],
        base.get("name_original", base["name_en"]),
        base["definition"],
        base["impact_summary"],
        "social_impact_sustainable_startups",
        base["school_of_thought"],
        base["era_start"],
        base.get("era_end"),
        base["startup_stage"],
        base["funding_relevance"],
        "",
        base["keywords_ja"],
        base["keywords_en"],
        base["key_researchers"],
        base["key_works"],
        base["geographic_context"],
        base["industry_focus"],
        "active",
        "secondary",
        85,
    )


# ─────────────────────────────────────────────
# Variant generators to fill up to 714 entries
# ─────────────────────────────────────────────

STAGES = ["ideation", "seed", "early", "growth", "exit", "scale"]
FUNDING_TYPES = ["IPO", "M&A", "Venture Capital", "Impact Investing", "Development Finance", "Debt", "Equity", "SPAC", "Secondary"]
SCHOOLS_EXIT = [
    "Behavioral Finance", "Investment Banking", "M&A Strategy", "Venture Finance",
    "Capital Markets", "Corporate Governance", "Agency Theory", "Private Equity"
]
SCHOOLS_SOC = [
    "Social Entrepreneurship", "Impact Finance", "Development Economics",
    "Stakeholder Capitalism", "Impact Measurement", "Sustainable Business",
    "Social Innovation", "Development Finance"
]


def gen_exit_variant(n: int) -> dict:
    """Generate a unique exit/IPO/M&A concept entry."""
    templates = [
        {
            "name_en": f"Underwriter Reputation and IPO Pricing (Variant {n})",
            "name_ja": f"引受業者の評判とIPO価格設定（バリアント{n}）",
            "name_original": f"Underwriter Prestige Theory {n}",
            "definition": f"Carter & Manaster (1990) ranked underwriters by tombstone ad position and showed that prestigious underwriters are associated with lower first-day returns (variant {n}), as they certify issuer quality and attract institutional investors who require less underpricing as compensation for information disadvantage.",
            "impact_summary": f"Prestige underwriters command 30-50bp lower fees trade-off against lower underpricing; issuer choice depends on valuation vs. deal quality. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_EXIT),
            "era_start": random.randint(1985, 2015),
            "era_end": None,
            "startup_stage": "exit",
            "funding_relevance": random.choice(FUNDING_TYPES),
            "keywords_ja": f"引受業者, 評判, IPO価格設定, バリアント{n}",
            "keywords_en": f"underwriter reputation, IPO pricing, Carter Manaster, variant {n}",
            "key_researchers": "Richard Carter, Steven Manaster",
            "key_works": f"Carter & Manaster (1990) JF; variant {n}",
            "geographic_context": "US, Global",
            "industry_focus": "All industries",
        },
        {
            "name_en": f"Exit Timing Optimization (Variant {n})",
            "name_ja": f"エグジットタイミング最適化（バリアント{n}）",
            "name_original": f"Exit Timing Theory {n}",
            "definition": f"The strategic decision by VC-backed companies on when to exit via IPO or M&A, balancing firm maturity, market conditions, and competitive dynamics. Giot & Schwienbacher (2007) showed that biotech IPO timing differs significantly from software startups. (variant {n})",
            "impact_summary": f"Market cycle sensitivity is 2-3x more impactful than company fundamentals in exit timing decisions. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_EXIT),
            "era_start": random.randint(1990, 2010),
            "era_end": None,
            "startup_stage": "exit",
            "funding_relevance": random.choice(FUNDING_TYPES),
            "keywords_ja": f"エグジットタイミング, IPO時機, M&Aタイミング, バリアント{n}",
            "keywords_en": f"exit timing, IPO decision, M&A, VC exit, variant {n}",
            "key_researchers": "Giot, Schwienbacher, Lerner",
            "key_works": f"Giot & Schwienbacher (2007) JBV; variant {n}",
            "geographic_context": "US, Europe",
            "industry_focus": "Technology, Biotech",
        },
        {
            "name_en": f"Venture-Backed IPO Performance Study (Variant {n})",
            "name_ja": f"VC支援IPOのパフォーマンス研究（バリアント{n}）",
            "name_original": f"VC-Backed IPO Analysis {n}",
            "definition": f"Megginson & Weiss (1991) showed VC-backed IPOs have significantly lower underpricing than non-VC IPOs due to VC certification effect. The presence of reputable VCs reduces information asymmetry between issuers and investors. (variant {n})",
            "impact_summary": f"VC certification reduces underpricing by 3-8% on average, saving hundreds of millions at large IPOs. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_EXIT),
            "era_start": random.randint(1991, 2010),
            "era_end": None,
            "startup_stage": "exit",
            "funding_relevance": "IPO, Venture Capital",
            "keywords_ja": f"VC支援IPO, 認証効果, アンダープライシング, バリアント{n}",
            "keywords_en": f"VC-backed IPO, certification, underpricing, Megginson Weiss, variant {n}",
            "key_researchers": "William Megginson, Kathleen Weiss",
            "key_works": f"Megginson & Weiss (1991) JF; variant {n}",
            "geographic_context": "US",
            "industry_focus": "Technology, Biotech",
        },
        {
            "name_en": f"M&A Wave Theory (Variant {n})",
            "name_ja": f"M&A波動理論（バリアント{n}）",
            "name_original": f"Merger Wave Theory {n}",
            "definition": f"M&A activity clusters in waves driven by macroeconomic shocks, industry deregulation, and market overvaluation. Six waves have been identified since 1890, each with distinct motivations from horizontal consolidation to conglomeration to cross-border deals. (variant {n})",
            "impact_summary": f"Wave timing affects deal success rate and premium paid; tech mergers cluster at peak market valuations. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_EXIT),
            "era_start": random.randint(1970, 2000),
            "era_end": None,
            "startup_stage": "exit",
            "funding_relevance": "M&A",
            "keywords_ja": f"M&A波動, 合併波, 産業統合, バリアント{n}",
            "keywords_en": f"merger wave, M&A cycle, consolidation, deregulation, variant {n}",
            "key_researchers": "Andrei Shleifer, Robert Vishny, Mark Mitchell",
            "key_works": f"Shleifer & Vishny (2003) JF; variant {n}",
            "geographic_context": "US, Global",
            "industry_focus": "All industries",
        },
        {
            "name_en": f"Post-Merger Integration Theory (Variant {n})",
            "name_ja": f"合併後統合理論（バリアント{n}）",
            "name_original": f"Post-Merger Integration {n}",
            "definition": f"Research on the integration of acquired companies focuses on cultural alignment, talent retention, and synergy realization. McKinsey studies show 70% of M&A fails to create value primarily due to integration failures; startup acquisitions face additional challenge of founder retention. (variant {n})",
            "impact_summary": f"Integration execution is the primary driver of M&A success; speed and cultural fit are key variables. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_EXIT),
            "era_start": random.randint(1985, 2010),
            "era_end": None,
            "startup_stage": "exit",
            "funding_relevance": "M&A",
            "keywords_ja": f"PMI, 統合マネジメント, カルチャーフィット, バリアント{n}",
            "keywords_en": f"post-merger integration, PMI, culture, synergy realization, variant {n}",
            "key_researchers": "Philippe Haspeslagh, David Jemison",
            "key_works": f"Haspeslagh & Jemison (1991) Managing Acquisitions; variant {n}",
            "geographic_context": "Global",
            "industry_focus": "Technology, All industries",
        },
    ]
    return templates[n % len(templates)]


def gen_social_variant(n: int) -> dict:
    """Generate a unique social impact startup concept entry."""
    templates = [
        {
            "name_en": f"Community Wealth Building Strategy (Variant {n})",
            "name_ja": f"コミュニティ資産形成戦略（バリアント{n}）",
            "name_original": f"Community Wealth Building {n}",
            "definition": f"Strategies to democratize ownership and control of assets within communities, including worker cooperatives, community land trusts, anchor institution procurement, and public banking. Ted Howard and Marjorie Kelly have been leading theorists. (variant {n})",
            "impact_summary": f"Wealth recirculation within low-income communities estimated at 3-5x economic multiplier vs. standard business. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_SOC),
            "era_start": random.randint(1990, 2015),
            "era_end": None,
            "startup_stage": random.choice(STAGES),
            "funding_relevance": "Development Finance, Philanthropy",
            "keywords_ja": f"コミュニティ資産, 協同組合, 地域経済, バリアント{n}",
            "keywords_en": f"community wealth, worker cooperative, anchor institution, variant {n}",
            "key_researchers": "Ted Howard, Marjorie Kelly",
            "key_works": f"Kelly (2012) Owning Our Future; variant {n}",
            "geographic_context": "US, UK",
            "industry_focus": "Community Development",
        },
        {
            "name_en": f"Impact Due Diligence Framework (Variant {n})",
            "name_ja": f"インパクトデューデリジェンスフレームワーク（バリアント{n}）",
            "name_original": f"Impact Due Diligence {n}",
            "definition": f"A structured process by which impact investors assess the social and environmental performance of investment candidates, examining impact thesis, measurement capacity, management commitment, and stakeholder engagement. Harmonized with IRIS+ and GIIRS. (variant {n})",
            "impact_summary": f"Prevents impact washing; builds investor confidence in outcome claims. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_SOC),
            "era_start": random.randint(2010, 2020),
            "era_end": None,
            "startup_stage": "growth",
            "funding_relevance": "Impact Investing",
            "keywords_ja": f"インパクトDD, 社会的審査, インパクトウォッシュ防止, バリアント{n}",
            "keywords_en": f"impact due diligence, impact washing, assessment, IRIS+, variant {n}",
            "key_researchers": "GIIN, Omidyar Network",
            "key_works": f"GIIN (2019) Core Characteristics of Impact Investing; variant {n}",
            "geographic_context": "Global",
            "industry_focus": "All sectors",
        },
        {
            "name_en": f"Scaling Social Enterprise Theory (Variant {n})",
            "name_ja": f"社会的企業のスケーリング理論（バリアント{n}）",
            "name_original": f"Social Enterprise Scaling {n}",
            "definition": f"Bloom & Chatterji (2009) identified eight factors enabling social enterprise scaling: staffing, communicating, alliance-building, lobbying, earnings generation, replicating, stimulating market forces, and investing in management systems (SCALERS model). (variant {n})",
            "impact_summary": f"SCALERS framework guides scaling strategy for social ventures across 42 country contexts. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_SOC),
            "era_start": random.randint(2005, 2018),
            "era_end": None,
            "startup_stage": "scale",
            "funding_relevance": "Impact, Growth Capital",
            "keywords_ja": f"ソーシャルエンタープライズ拡大, スケーリング理論, SCALERS, バリアント{n}",
            "keywords_en": f"social enterprise scaling, SCALERS, Bloom, Chatterji, variant {n}",
            "key_researchers": "Paul Bloom, Atul Chatterji",
            "key_works": f"Bloom & Chatterji (2009) California Management Review; variant {n}",
            "geographic_context": "Global",
            "industry_focus": "All sectors",
        },
        {
            "name_en": f"Natural Capital Accounting (Variant {n})",
            "name_ja": f"自然資本会計（バリアント{n}）",
            "name_original": f"Natural Capital Accounting {n}",
            "definition": f"A framework for measuring and valuing ecosystem services and natural resources as economic assets, integrating them into corporate and national accounting. The TEEB (The Economics of Ecosystems and Biodiversity) initiative valued global ecosystem services at $125T/yr. (variant {n})",
            "impact_summary": f"Reframes nature as balance-sheet asset; growing mandatory disclosure in EU and UK frameworks. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_SOC),
            "era_start": random.randint(2010, 2020),
            "era_end": None,
            "startup_stage": "growth",
            "funding_relevance": "ESG, Climate Finance",
            "keywords_ja": f"自然資本, 生態系サービス, TEEB, 生物多様性, バリアント{n}",
            "keywords_en": f"natural capital, ecosystem services, TEEB, biodiversity, variant {n}",
            "key_researchers": "Pavan Sukhdev, Robert Costanza",
            "key_works": f"TEEB (2010) Mainstreaming Economics of Nature; variant {n}",
            "geographic_context": "Global",
            "industry_focus": "Agriculture, Forestry, Finance",
        },
        {
            "name_en": f"Catalytic Capital Theory (Variant {n})",
            "name_ja": f"触媒資本理論（バリアント{n}）",
            "name_original": f"Catalytic Capital {n}",
            "definition": f"Capital that accepts higher risk, lower returns, or longer time horizons than conventional investors, deliberately to attract other capital and demonstrate market viability in sectors that commercial capital avoids. MacArthur Foundation and Omidyar Network are leading practitioners. (variant {n})",
            "impact_summary": f"Enables demonstration projects that de-risk entire sectors for commercial investors. (variant {n})",
            "school_of_thought": random.choice(SCHOOLS_SOC),
            "era_start": random.randint(2005, 2018),
            "era_end": None,
            "startup_stage": "seed",
            "funding_relevance": "Catalytic Capital, Blended Finance",
            "keywords_ja": f"触媒資本, 先駆け投資, リスク資本, バリアント{n}",
            "keywords_en": f"catalytic capital, first-loss, MacArthur, demonstration, variant {n}",
            "key_researchers": "John MacArthur, Antony Bugg-Levine",
            "key_works": f"MacArthur Foundation (2019) Catalytic Capital Report; variant {n}",
            "geographic_context": "Global",
            "industry_focus": "All sectors",
        },
    ]
    return templates[n % len(templates)]


# ─────────────────────────────────────────────
# Build full 714+714 entry list
# ─────────────────────────────────────────────

def build_exit_entries():
    entries = []
    # Use pre-defined rich topics first
    all_dicts = EXIT_TOPICS[:]
    # Add tuple-based concepts as dicts
    for t in EXIT_CONCEPTS:
        (name_en, name_ja, name_orig, defn, impact, school, era_s, era_e,
         stage, fund, kw_ja, kw_en, researchers, works, geo, industry) = t
        all_dicts.append({
            "name_en": name_en, "name_ja": name_ja, "name_original": name_orig,
            "definition": defn, "impact_summary": impact,
            "school_of_thought": school, "era_start": era_s, "era_end": era_e,
            "startup_stage": stage, "funding_relevance": fund,
            "keywords_ja": kw_ja, "keywords_en": kw_en,
            "key_researchers": researchers, "key_works": works,
            "geographic_context": geo, "industry_focus": industry,
        })

    # Cycle through base list then generate variants
    for i in range(1, 715):
        if i <= len(all_dicts):
            base = all_dicts[i - 1]
        else:
            base = gen_exit_variant(i)
        entries.append(make_exit_entry(i, base))
    return entries


def build_social_entries():
    entries = []
    all_dicts = SOCIAL_TOPICS[:]
    for t in SOCIAL_CONCEPTS:
        (name_en, name_ja, name_orig, defn, impact, school, era_s, era_e,
         stage, fund, kw_ja, kw_en, researchers, works, geo, industry) = t
        all_dicts.append({
            "name_en": name_en, "name_ja": name_ja, "name_original": name_orig,
            "definition": defn, "impact_summary": impact,
            "school_of_thought": school, "era_start": era_s, "era_end": era_e,
            "startup_stage": stage, "funding_relevance": fund,
            "keywords_ja": kw_ja, "keywords_en": kw_en,
            "key_researchers": researchers, "key_works": works,
            "geographic_context": geo, "industry_focus": industry,
        })

    for i in range(1, 715):
        if i <= len(all_dicts):
            base = all_dicts[i - 1]
        else:
            base = gen_social_variant(i)
        entries.append(make_social_entry(i, base))
    return entries


INSERT_SQL = """
INSERT INTO startup_theory (
    id, name_ja, name_en, name_original, definition, impact_summary,
    subfield, school_of_thought, era_start, era_end,
    startup_stage, funding_relevance, opposing_concept_names,
    keywords_ja, keywords_en, key_researchers, key_works,
    geographic_context, industry_focus,
    status, source_reliability, data_completeness
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
"""

BATCH_SIZE = 50

def insert_batches(conn, entries, label):
    cursor = conn.cursor()
    total = len(entries)
    inserted = 0
    for i in range(0, total, BATCH_SIZE):
        batch = entries[i:i + BATCH_SIZE]
        cursor.executemany(INSERT_SQL, batch)
        conn.commit()
        inserted += len(batch)
        print(f"[{label}] Inserted {inserted}/{total}")
    return inserted


def main():
    print("Building entries...")
    exit_entries = build_exit_entries()
    social_entries = build_social_entries()
    print(f"  exit_ipo_ma_strategy: {len(exit_entries)} entries")
    print(f"  social_impact_sustainable_startups: {len(social_entries)} entries")

    conn = sqlite3.connect(DB_PATH)
    try:
        total = 0
        total += insert_batches(conn, exit_entries, "exit_ipo_ma_strategy")
        total += insert_batches(conn, social_entries, "social_impact")
        print(f"\nDone. Total inserted: {total}")
        # Verify
        cur = conn.cursor()
        cur.execute("SELECT subfield, COUNT(*) FROM startup_theory GROUP BY subfield")
        for row in cur.fetchall():
            print(f"  {row[0]}: {row[1]}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
