import sqlite3
from datetime import datetime
db_path = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"
now = datetime.now().isoformat()
entries = [
    {
        "id": "inno_pol_671",
        "name_en": "Multilateral STI Governance",
        "name_ja": "多国間科学技術イノベーションガバナンス",
        "definition": "国際機関（OECD・UNESCO・UNCTAD・WTO等）が調整する国際的STIガバナンス体制を指す。標準・規制調和・知的財産・能力構築の国際的調整が主要機能である。",
        "impact_summary": "国境を越えたSTI活動の整合性を確保し、グローバルなイノベーション便益の公平な分配を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_diplomacy",
        "era_start": 1960,
        "innovation_type": "institutional",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "多国間STI,国際機関,規制調和,国際知財",
        "keywords_en": "multilateral STI governance,international organizations,regulatory harmonization,international IP",
        "key_researchers": '["Ruffini P.B.", "Sachs J.D."]',
        "key_works": '["Science and Diplomacy (2017)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_672",
        "name_en": "Social Labs and Policy Experimentation",
        "name_ja": "ソーシャルラボと政策実験",
        "definition": "社会課題解決のために多様なステークホルダーが共同で実験・プロトタイプ・学習を行う場であるソーシャルラボを政策設計と実施に活用するアプローチを指す。",
        "impact_summary": "複雑な社会課題に対して反復的な実験と学習を通じた適応的な解決策を生み出す政策実践を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "social_innovation",
        "era_start": 2012,
        "innovation_type": "methodology",
        "cognitive_mechanism": "participatory",
        "keywords_ja": "ソーシャルラボ,政策実験,プロトタイピング,協働設計",
        "keywords_en": "social labs,policy experimentation,prototyping,co-design",
        "key_researchers": '["Hassan Z.", "Brown L."]',
        "key_works": '["Social Labs Revolution (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_673",
        "name_en": "Technology Forecasting Methods",
        "name_ja": "技術予測手法",
        "definition": "将来の技術発展の方向性・タイミング・インパクトを予測するための定量・定性的手法を指す。デルファイ法・Sカーブ分析・特許引用分析・ロードマッピングが代表的な手法として広く活用される。",
        "impact_summary": "技術投資の意思決定に前方視的な情報を提供し、研究開発ポートフォリオの最適化を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "technology_foresight",
        "era_start": 1960,
        "innovation_type": "methodology",
        "cognitive_mechanism": "prospective",
        "keywords_ja": "技術予測,デルファイ法,Sカーブ,技術ロードマップ",
        "keywords_en": "technology forecasting,Delphi method,S-curve,technology roadmap",
        "key_researchers": '["Martino J.P.", "Meade N."]',
        "key_works": '["Technological Forecasting for Decision Making (1993)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_674",
        "name_en": "STI Policy Coherence",
        "name_ja": "STI政策コヒーレンス",
        "definition": "科学・技術・イノベーション政策が相互に整合し、また経済・社会・環境政策と矛盾しないように調整するプロセスを指す。縦割り省庁間の調整と水平的な政策統合が主要課題となる。",
        "impact_summary": "政策の相互矛盾を解消し、限られた資源を相乗効果が最大となる形で配分する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "政策コヒーレンス,省庁間調整,政策整合,水平統合",
        "keywords_en": "STI policy coherence,inter-ministerial coordination,policy alignment,horizontal integration",
        "key_researchers": '["Metcalfe J.S.", "Ramlogan R."]',
        "key_works": '["Evolutionary Ideas and Empirical Methods (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_675",
        "name_en": "Science Funding Peer Review Reform",
        "name_ja": "科学資金ピアレビュー改革",
        "definition": "研究助成審査のピアレビュー制度の問題点（偏見・保守性・負担・運・非効率）を改善するための改革を指す。ランダム配分実験・部分ランダム化・クリエイティビティ基準の導入等が試みられている。",
        "impact_summary": "研究資金配分の公平性・効率性・多様性を高め、より革新的な研究への資金流入を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 2010,
        "innovation_type": "process",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "ピアレビュー改革,研究助成審査,ランダム配分,審査バイアス",
        "keywords_en": "peer review reform,grant review,lottery funding,review bias",
        "key_researchers": '["Nicholson J.M.", "Ioannidis J.P.A."]',
        "key_works": '["Research Grants: Conform and Be Funded (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_676",
        "name_en": "Intangible Assets and Innovation",
        "name_ja": "無形資産とイノベーション",
        "definition": "ソフトウェア・ブランド・組織能力・データ・R&D等の無形資産がイノベーション・成長・競争優位に与える影響を分析する研究分野を指す。無形資産の測定・資本化・政策的扱いが主要課題である。",
        "impact_summary": "知識経済において無形資産が有形資産を超える経済的重要性を持つことを示し、新たな会計・統計の枠組みを促す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "knowledge_economy",
        "era_start": 1995,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "無形資産,知的資本,R&D資本化,ブランド価値",
        "keywords_en": "intangible assets,intellectual capital,R&D capitalization,brand value",
        "key_researchers": '["Corrado C.", "Hulten C.", "Sichel D."]',
        "key_works": '["Intangible Capital and US Economic Growth (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_677",
        "name_en": "Science of Science Policy",
        "name_ja": "科学政策の科学",
        "definition": "科学的知識の生産・流通・活用プロセスを自然科学・社会科学の手法で研究し、科学政策の証拠基盤を構築する学問領域を指す。米国NSFが促進した研究分野で、引用分析・知識グラフ・機械学習を活用する。",
        "impact_summary": "科学政策の決定をより強固な経験的証拠に基づかせ、研究投資の効率と方向性を改善する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 2008,
        "innovation_type": "methodology",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "科学政策の科学,知識グラフ,引用分析,科学システム分析",
        "keywords_en": "science of science policy,knowledge graph,citation analysis,science system analysis",
        "key_researchers": '["Rzhetsky A.", "Evans J.A."]',
        "key_works": '["Science of Science (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_678",
        "name_en": "Participatory Foresight",
        "name_ja": "参加型フォーサイト",
        "definition": "政策立案者・研究者・市民・産業界など多様なステークホルダーがフォーサイトプロセスに参加し、共同で将来ビジョンと戦略を策定するアプローチを指す。民主的正当性と多様な知識統合が特徴である。",
        "impact_summary": "フォーサイトの政策的正当性と社会的受容性を高め、より包括的な将来像の共創を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "technology_foresight",
        "era_start": 1995,
        "innovation_type": "methodology",
        "cognitive_mechanism": "participatory",
        "keywords_ja": "参加型フォーサイト,共創,多様なステークホルダー,将来ビジョン",
        "keywords_en": "participatory foresight,co-creation,diverse stakeholders,future vision",
        "key_researchers": '["Calof J.", "Smith J.E."]',
        "key_works": '["Foresight Methodology (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_679",
        "name_en": "STI for SDG Measurement",
        "name_ja": "SDGのためのSTI測定",
        "definition": "科学技術イノベーションが国連持続可能な開発目標（SDGs）の達成にどの程度貢献しているかを測定する枠組みを指す。SDGと技術指標のマッピング・インパクト評価が主要課題である。",
        "impact_summary": "イノベーション活動のSDG達成への貢献を可視化し、より目的適合的なSTI政策の設計を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "development_economics",
        "era_start": 2015,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "SDG,STI測定,技術貢献,持続可能開発",
        "keywords_en": "STI for SDGs measurement,technology contribution,sustainable development goals",
        "key_researchers": '["UN DESA", "Sachs J.D."]',
        "key_works": '["STI for SDGs Roadmaps (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_680",
        "name_en": "Digital Transformation Policy",
        "name_ja": "デジタルトランスフォーメーション政策",
        "definition": "デジタル技術によって産業・行政・社会システムを根本的に変革するDXを政策的に促進・支援・規制する枠組みを指す。デジタルインフラ・スキル・データ・規制サンドボックスが主要政策要素である。",
        "impact_summary": "デジタル技術による産業・行政・社会の変革を加速し、競争力強化と市民生活改善を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "digital_governance",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "DX政策,デジタル化推進,デジタルインフラ,規制サンドボックス",
        "keywords_en": "digital transformation policy,digitalization,digital infrastructure,regulatory sandbox",
        "key_researchers": '["Westerman G.", "Bonnet D."]',
        "key_works": '["Leading Digital (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_681",
        "name_en": "Challenge-Based Innovation",
        "name_ja": "チャレンジベースドイノベーション",
        "definition": "明確な社会的・技術的挑戦課題を設定し、多様な解決者を競争的に動員する問題解決型イノベーションモデルを指す。オープンイノベーション・コンテスト・賞金型競争が手法として含まれる。",
        "impact_summary": "従来の研究主導型アプローチでは生み出されにくい革新的解決策を広いイノベーター参加を通じて創出する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_innovation",
        "era_start": 2010,
        "innovation_type": "process",
        "cognitive_mechanism": "challenge_driven",
        "keywords_ja": "チャレンジ型イノベーション,問題解決型,賞金競争,オープン参加",
        "keywords_en": "challenge-based innovation,problem-solving,prize competition,open participation",
        "key_researchers": '["Lakhani K.R.", "Jeppesen L.B."]',
        "key_works": '["Marginality and Problem-Solving Effectiveness (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_682",
        "name_en": "Patent Landscape Analysis",
        "name_ja": "特許ランドスケープ分析",
        "definition": "特定技術分野の特許活動の全体像（主要出願者・技術クラスター・地域分布・トレンド）を可視化・分析する手法を指す。技術戦略策定・競合分析・空白技術特定に活用される。",
        "impact_summary": "技術競争の全体構造を把握し、研究開発投資の方向性と知的財産戦略の策定を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "patent_economics",
        "era_start": 2000,
        "innovation_type": "methodology",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "特許ランドスケープ,技術地図,特許分析,競合分析",
        "keywords_en": "patent landscape,technology map,patent analysis,competitive intelligence",
        "key_researchers": '["Trippe A.", "WIPO"]',
        "key_works": '["Patent Landscape Reports (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_683",
        "name_en": "Genetically Modified Organism Governance",
        "name_ja": "遺伝子組換え生物ガバナンス",
        "definition": "GMO農作物・遺伝子組換え微生物・遺伝子治療等に関する規制・承認・市場管理・国際貿易ルールを定めるガバナンス体制を指す。カルタヘナ議定書・EU規制・米国USDA/EPA規制が主要枠組みである。",
        "impact_summary": "生物技術イノベーションの農業・医療・環境への応用を可能にしながら潜在的リスクと倫理的懸念を管理する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 1992,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "GMOガバナンス,カルタヘナ議定書,バイオセーフティ,遺伝子規制",
        "keywords_en": "GMO governance,Cartagena Protocol,biosafety,genetic regulation",
        "key_researchers": '["Paarlberg R.", "McHughen A."]',
        "key_works": '["Starved for Science (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_684",
        "name_en": "Research Community Infrastructure",
        "name_ja": "研究コミュニティインフラ",
        "definition": "研究者が協働・情報共有・共同実験を行うための制度的・物理的・デジタル的インフラを指す。学会・プレプリントサーバ・共同実験施設・研究ネットワーク等が含まれる。",
        "impact_summary": "研究コミュニティの知識共有と協働の効率を高め、科学的発見の速度と質を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1970,
        "innovation_type": "institutional",
        "cognitive_mechanism": "network",
        "keywords_ja": "研究インフラ,学会,プレプリント,研究ネットワーク",
        "keywords_en": "research community infrastructure,academic society,preprint server,research network",
        "key_researchers": '["Price D.J.D.S.", "Ziman J."]',
        "key_works": '["Reliable Knowledge (1978)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_685",
        "name_en": "Industrial Symbiosis Policy",
        "name_ja": "産業共生政策",
        "definition": "ある企業の廃棄物・副産物を別の企業が資源として活用する産業共生ネットワークの形成を促進する政策を指す。デンマークのカランボー工業団地が国際的な代表事例とされる。",
        "impact_summary": "廃棄物を価値ある資源に転換し、循環型産業システムの構築を通じて経済・環境の同時改善を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 1989,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "産業共生,廃棄物共有,循環産業,カランボー",
        "keywords_en": "industrial symbiosis,waste sharing,circular industry,Kalundborg",
        "key_researchers": '["Chertow M.R.", "Lifset R."]',
        "key_works": '["Industrial Ecology (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_686",
        "name_en": "Technology Licensing Policy",
        "name_ja": "技術ライセンス政策",
        "definition": "公的研究機関・大学・企業が保有する技術の実施許諾（ライセンス）条件・収益配分・排他的/非排他的選択に関する政策と制度の枠組みを指す。",
        "impact_summary": "技術の商業化と普及を促進しながら、知識創造者への適切なインセンティブを確保するバランスを実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "patent_economics",
        "era_start": 1980,
        "innovation_type": "institutional",
        "cognitive_mechanism": "incentive",
        "keywords_ja": "技術ライセンス,実施許諾,排他的ライセンス,技術商業化",
        "keywords_en": "technology licensing,patent license,exclusive license,technology commercialization",
        "key_researchers": '["Arora A.", "Fosfuri A."]',
        "key_works": '["Licensing the Market for Technology (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_687",
        "name_en": "Collaborative R&D Policy",
        "name_ja": "協調型R&D政策",
        "definition": "企業間・産学間の共同研究開発を促進するための政策支援（共同研究助成・コンソーシアム形成支援・独禁法適用除外等）の枠組みを指す。前競争的研究の協調による社会的便益が政策根拠となる。",
        "impact_summary": "個別企業では費用負担困難な前競争的研究領域に協調投資を誘発し、産業全体の技術水準を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "economics_of_innovation",
        "era_start": 1984,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "協調R&D,共同研究政策,前競争的研究,産学連携促進",
        "keywords_en": "collaborative R&D policy,joint research,pre-competitive research,consortium",
        "key_researchers": '["Baumol W.J.", "Strickland T."]',
        "key_works": '["Antitrust and Trade Regulation (1982)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_688",
        "name_en": "Innovation and Inequality",
        "name_ja": "イノベーションと不平等",
        "definition": "技術革新が所得・資産・機会の格差拡大または縮小に与える影響を分析する研究分野を指す。スキル偏向型技術変化・勝者独り占め・ロボットと雇用が主要論点である。",
        "impact_summary": "イノベーションの分配的影響を可視化し、包括的な成長と公正な変革を政策的に実現するための根拠を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "welfare_economics",
        "era_start": 2000,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "イノベーションと不平等,スキル偏向,格差拡大,包括的成長",
        "keywords_en": "innovation and inequality,skill-biased change,widening inequality,inclusive growth",
        "key_researchers": '["Acemoglu D.", "Restrepo P."]',
        "key_works": '["Automation and New Tasks (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_689",
        "name_en": "Agile Governance",
        "name_ja": "アジャイルガバナンス",
        "definition": "急速に変化する技術環境に対応するため、規制・政策・制度を迅速かつ反復的に設計・更新するガバナンスアプローチを指す。規制サンドボックス・実験的許可・適応的ルールメイキングが主要手法である。",
        "impact_summary": "従来の硬直した規制制度では追いつかない技術変化のスピードに対応し、イノベーションと社会的保護を両立する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regulatory_theory",
        "era_start": 2015,
        "innovation_type": "institutional",
        "cognitive_mechanism": "adaptive",
        "keywords_ja": "アジャイルガバナンス,適応的規制,反復的政策,柔軟な規制",
        "keywords_en": "agile governance,adaptive regulation,iterative policy,flexible regulation",
        "key_researchers": '["World Economic Forum", "Marchetti C."]',
        "key_works": '["Agile Governance: Reimagining Policy Making (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_690",
        "name_en": "Performance-Based Funding for Research",
        "name_ja": "研究への成果連動型資金配分",
        "definition": "研究機関の実績（論文数・被引用数・産業収入・研究卓越性評価等）に基づいて公的研究資金を配分する制度を指す。英国RAE/REF・オーストラリアERA等が代表的な制度実装例である。",
        "impact_summary": "研究機関の成果指向を強め、資金配分の透明性と競争的効率化を実現するが、短期主義のリスクも伴う。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1986,
        "innovation_type": "policy",
        "cognitive_mechanism": "incentive",
        "keywords_ja": "成果連動型資金,RAE,REF,研究評価連動",
        "keywords_en": "performance-based research funding,RAE,REF,research evaluation linked funding",
        "key_researchers": '["Hicks D.", "Auranen O."]',
        "key_works": '["Performance-Based Research Funding Systems (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_691",
        "name_en": "AI in Science Policy Analytics",
        "name_ja": "科学政策分析へのAI活用",
        "definition": "人工知能・機械学習・自然言語処理を活用して科学政策の分析・設計・評価を支援するアプローチを指す。文献分析・特許クラスタリング・政策文書分析・予測モデリングが含まれる。",
        "impact_summary": "科学政策の証拠基盤を強化し、大量の政策・研究データから有用な洞察を自動的に抽出する能力を高める。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 2017,
        "innovation_type": "methodology",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "AIによる政策分析,機械学習,NLP,政策予測",
        "keywords_en": "AI in policy analytics,machine learning,NLP,policy prediction",
        "key_researchers": '["Kostoff R.N.", "Schaller R.R."]',
        "key_works": '["Science and Technology Roadmaps (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_692",
        "name_en": "Supply Chain Resilience Policy",
        "name_ja": "サプライチェーン強靭化政策",
        "definition": "重要物資・部品・技術のサプライチェーンの脆弱性を特定し、冗長性・多様化・近接化・在庫確保等によって強靭化する政策を指す。半導体・医薬品・希土類等が政策的重点対象である。",
        "impact_summary": "地政学的リスク・パンデミック・自然災害等によるサプライチェーン断絶リスクを低減し、経済安全保障を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2020,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "サプライチェーン強靭化,半導体政策,経済安保,フレンドショアリング",
        "keywords_en": "supply chain resilience,semiconductor policy,economic security,friendshoring",
        "key_researchers": '["Gereffi G.", "Shih W."]',
        "key_works": '["Reviving US Manufacturing (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_693",
        "name_en": "Open Access Policy",
        "name_ja": "オープンアクセス政策",
        "definition": "公的資金による研究成果の論文・データを誰でも無料でアクセスできるようにする政策的義務付けの枠組みを指す。グリーン・ゴールドOA・Plan S・NIH・Horizonの義務化がその例である。",
        "impact_summary": "科学的知識への普遍的アクセスを確保し、知識の民主化と研究成果の社会的還元を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_science",
        "era_start": 2002,
        "innovation_type": "policy",
        "cognitive_mechanism": "open",
        "keywords_ja": "オープンアクセス,Plan S,NIH義務化,グリーンOA",
        "keywords_en": "open access policy,Plan S,NIH mandate,green OA",
        "key_researchers": '["Suber P.", "Harnad S."]',
        "key_works": '["Open Access (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_694",
        "name_en": "Measurement of Basic Research Value",
        "name_ja": "基礎研究価値の測定",
        "definition": "直接的な経済的応用を目指さない基礎研究の長期的・間接的な経済・社会的価値を測定する手法を指す。研究系譜追跡・社会的収益率推計・知識拡散指数が主要手法である。",
        "impact_summary": "基礎研究への公的投資の正当性を実証的に支持し、科学基盤の維持への政策的支持を醸成する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "economics_of_innovation",
        "era_start": 1965,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "基礎研究価値,社会的収益率,知識拡散,研究系譜",
        "keywords_en": "basic research value,social rate of return,knowledge diffusion,research lineage",
        "key_researchers": '["Mansfield E.", "Martin B.R."]',
        "key_works": '["Academic Research and Industrial Innovation (1991)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_695",
        "name_en": "Policy Instrumentation Theory",
        "name_ja": "政策手段論",
        "definition": "政府が政策目的を達成するために利用可能な手段（規制・補助・情報・調達・税制・所有・勧告等）の分類・選択・組み合わせを論じる政策科学の理論的枠組みを指す。",
        "impact_summary": "政策設計者が目的・文脈・実現可能性に最適な政策手段を体系的に選択するための知的道具を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "policy_analysis",
        "era_start": 1983,
        "innovation_type": "theory",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "政策手段,政策設計,規制手段,政策ミックス",
        "keywords_en": "policy instruments,policy design,regulatory tools,policy mix",
        "key_researchers": '["Hood C.", "Howlett M."]',
        "key_works": '["The Tools of Government (1983)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_696",
        "name_en": "National AI Strategy Evaluation",
        "name_ja": "国家AI戦略評価",
        "definition": "各国が策定した国家AI戦略の内容・優先課題・資金規模・実施体制・成果を比較評価する研究枠組みを指す。OECD AIポリシーモニタリングが比較データを提供している。",
        "impact_summary": "国家AI戦略の成功要因と失敗要因を国際比較から学び、より効果的なAI政策設計に活用する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "digital_governance",
        "era_start": 2017,
        "innovation_type": "measurement",
        "cognitive_mechanism": "comparative",
        "keywords_ja": "国家AI戦略,AI政策比較,OECD AI,AI競争",
        "keywords_en": "national AI strategy,AI policy comparison,OECD AI,AI competition",
        "key_researchers": '["Dafoe A.", "Calo R."]',
        "key_works": '["AI Governance: A Research Agenda (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_697",
        "name_en": "Technology Neutrality in Policy",
        "name_ja": "政策における技術中立性",
        "definition": "特定の技術を優遇せず、目標達成を最も効率的に実現できる技術の選択を市場に委ねる政策原則を指す。再エネ技術・通信規格・e-モビリティ等での中立vs特定技術支援の論争が続く。",
        "impact_summary": "政策の技術的中立性が市場効率を高める一方、戦略的産業育成には選択的支援が必要という緊張関係を提示する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "market_forming",
        "keywords_ja": "技術中立性,技術非特定,市場主導,再エネ政策原則",
        "keywords_en": "technology neutrality,technology-agnostic,market-led,renewable policy principle",
        "key_researchers": '["Fischer C.", "Newell R.G."]',
        "key_works": '["Renewable Portfolio Standards (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_698",
        "name_en": "Policy for Knowledge-Intensive Services",
        "name_ja": "知識集約型サービス政策",
        "definition": "コンサルティング・エンジニアリング・IT・金融等の知識集約型ビジネスサービス（KIBS）の発展を促進する政策を指す。KIBSがイノベーション中間媒介者として果たす役割が政策的注目を集めている。",
        "impact_summary": "知識サービス産業の成長を通じて産業全体のイノベーション能力と生産性を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sectoral_innovation",
        "era_start": 1998,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "知識集約型サービス,KIBS,サービスイノベーション,中間媒介",
        "keywords_en": "knowledge-intensive services,KIBS,service innovation,innovation intermediary",
        "key_researchers": '["Miles I.", "Muller E."]',
        "key_works": '["Knowledge-Intensive Business Services (1998)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_699",
        "name_en": "Research Security Policy",
        "name_ja": "研究安全保障政策",
        "definition": "外国の影響・スパイ活動・技術窃取から研究機関・研究成果・研究者を保護するための政策枠組みを指す。外国研究資金の開示・訪問研究者管理・機微情報管理が主要施策である。",
        "impact_summary": "オープンな学術環境を維持しながら安全保障上機微な研究成果の不正流出を防ぐ制度的均衡を設計する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "security_innovation",
        "era_start": 2018,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "研究安全保障,外国影響対策,技術窃取,学術開示",
        "keywords_en": "research security,foreign influence,technology theft,academic disclosure",
        "key_researchers": '["Hicks A.", "Zweig D."]',
        "key_works": '["Talent Wars (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_700",
        "name_en": "Impact Pathways in Research",
        "name_ja": "研究におけるインパクト経路",
        "definition": "研究成果が社会・経済・文化的インパクトに至るまでの因果的経路を論理的に再構成するモデルを指す。ロジックモデル・テオリー・オブ・チェンジ・実現条件の特定が主要要素である。",
        "impact_summary": "研究資金機関と研究者が社会的インパクトを計画・実証・説明するための共通言語と方法論を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "impact_evaluation",
        "era_start": 2000,
        "innovation_type": "methodology",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "インパクト経路,ロジックモデル,研究インパクト,理論的根拠",
        "keywords_en": "impact pathways,logic model,research impact,theory of change",
        "key_researchers": '["Donaldson S.I.", "Weiss C.H."]',
        "key_works": '["Theory-Based Evaluation (1998)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_701",
        "name_en": "Innovation and Mental Health Policy",
        "name_ja": "イノベーションとメンタルヘルス政策",
        "definition": "起業家・研究者・創造的労働者のメンタルヘルス課題（燃え尽き・不安・うつ）を認識し、イノベーション生態系の持続可能性を守る政策と組織実践を指す。",
        "impact_summary": "創造的人材のウェルビーイングと生産性を両立させる持続可能なイノベーション文化の構築を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "inclusive_innovation",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "inclusive",
        "keywords_ja": "起業家メンタルヘルス,創造的労働者,燃え尽き,持続可能なイノベーション",
        "keywords_en": "entrepreneur mental health,creative worker,burnout,sustainable innovation culture",
        "key_researchers": '["Freeman M.A.", "Steptoe A."]',
        "key_works": '["Are Entrepreneurs Touched with Fire (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_702",
        "name_en": "Catalytic Funding Mechanisms",
        "name_ja": "触媒型資金メカニズム",
        "definition": "公的資金が呼び水となって民間投資・寄付・社会的資本を動員する触媒型の資金供与モデルを指す。マッチングファンド・ブレンドドファイナンス・インパクト保証等が代表的仕組みである。",
        "impact_summary": "限られた公的資金を最大限に活用し、民間資本との相乗効果を生み出すイノベーション資金調達の多様化を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_finance",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "incentive",
        "keywords_ja": "触媒型資金,マッチングファンド,ブレンドドファイナンス,民間資金動員",
        "keywords_en": "catalytic funding,matching fund,blended finance,private capital mobilization",
        "key_researchers": '["Convergence", "Mazzucato M."]',
        "key_works": '["Blended Finance in the Private Sector (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_703",
        "name_en": "Sovereign Wealth Fund and Innovation",
        "name_ja": "ソブリンウェルスファンドとイノベーション",
        "definition": "国家が運営するSWFがイノベーション・スタートアップ・戦略的技術分野への長期投資者として果たす役割を論じる枠組みを指す。シンガポールGIC・テマセク・ノルウェーGPFGが代表例である。",
        "impact_summary": "長期的・戦略的視野を持つ国家資本がイノベーション資本市場を補完し、戦略的産業の発展を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_finance",
        "era_start": 2005,
        "innovation_type": "institutional",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "SWF,ソブリンウェルスファンド,国家投資,戦略的資本",
        "keywords_en": "sovereign wealth fund,SWF,state investment,strategic capital",
        "key_researchers": '["Megginson W.L.", "Fotak V."]',
        "key_works": '["Sovereign Wealth Funds (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_704",
        "name_en": "Technology and Employment Policy",
        "name_ja": "技術と雇用政策",
        "definition": "自動化・AI・ロボット等の技術進歩が雇用・賃金・スキル需要に与える影響を管理するための政策を指す。再訓練・社会的セーフティネット・労働市場制度改革・新産業育成が主要施策である。",
        "impact_summary": "技術による雇用破壊と創造のバランスを政策的に管理し、労働者の移行を支援する社会的基盤を整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "labor_economics",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "技術と雇用,自動化政策,スキル転換,労働市場政策",
        "keywords_en": "technology employment policy,automation policy,skill transition,labor market policy",
        "key_researchers": '["Acemoglu D.", "Brynjolfsson E."]',
        "key_works": '["The Second Machine Age (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_705",
        "name_en": "Metrics for Open Science",
        "name_ja": "オープンサイエンスの指標",
        "definition": "研究成果の開放度（論文OA率・データ共有率・コード公開率・市民科学参加度等）を測定するための指標体系を指す。UNESCO・欧州委員会のオープンサイエンスモニタリングが代表例である。",
        "impact_summary": "オープンサイエンスの普及度を測定し、科学の開放性を高めるための政策と制度設計に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_science",
        "era_start": 2016,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "オープンサイエンス指標,OA率,データ共有,科学開放度",
        "keywords_en": "open science metrics,OA rate,data sharing,science openness indicators",
        "key_researchers": '["Tennant J.P.", "UNESCO"]',
        "key_works": '["UNESCO Recommendation on Open Science (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_706",
        "name_en": "Policy for Space-Based Services",
        "name_ja": "宇宙由来サービス政策",
        "definition": "GPS・衛星通信・地球観測・宇宙天気予報等の宇宙基盤サービスの安定的な提供・利活用促進・競争政策に関する政策枠組みを指す。これらのサービスの民間経済への貢献は年間数兆ドル規模とされる。",
        "impact_summary": "社会インフラとなった宇宙由来サービスの持続的提供と新たな応用開発を通じて経済・社会的価値を最大化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "宇宙由来サービス,GPS政策,地球観測,衛星通信政策",
        "keywords_en": "space-based services,GPS policy,earth observation,satellite communication policy",
        "key_researchers": '["Pace S.", "Henry R."]',
        "key_works": '["The GPS and the World (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_707",
        "name_en": "Knowledge Commons Governance",
        "name_ja": "知識コモンズガバナンス",
        "definition": "共有知識資源（オープンソース・ウィキペディア・学術データ等）の持続可能な管理と利用を規定するガバナンス原則を指す。オストロムのコモンズ論をデジタル知識領域に適用した枠組みである。",
        "impact_summary": "知識の私有化と公共的無制限アクセスの中間形態として機能し、持続可能な知識共有エコシステムを維持する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "institutional_theory",
        "era_start": 2007,
        "innovation_type": "institutional",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "知識コモンズ,オープンソース,共有知識,コモンズ管理",
        "keywords_en": "knowledge commons,open source,shared knowledge,commons governance",
        "key_researchers": '["Hess C.", "Ostrom E."]',
        "key_works": '["Understanding Knowledge as a Commons (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_708",
        "name_en": "Entrepreneurship and Regional Development",
        "name_ja": "アントレプレナーシップと地域発展",
        "definition": "起業活動が地域経済の多様化・雇用創出・イノベーション集積に与える影響と、地域の起業環境を改善する政策を指す。地域VC・起業家教育・規制緩和・クラスター政策が主要手段である。",
        "impact_summary": "地域のイノベーション・エコシステムを起業家活動の活性化を通じて強化し、地域経済の自律的成長を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regional_innovation",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "spatial",
        "keywords_ja": "地域起業家,地域VC,起業環境,地域経済多様化",
        "keywords_en": "regional entrepreneurship,local VC,entrepreneurial environment,regional diversification",
        "key_researchers": '["Acs Z.J.", "Szerb L."]',
        "key_works": '["Entrepreneurship, Economic Geography (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_709",
        "name_en": "Digital Health Innovation Policy",
        "name_ja": "デジタルヘルスイノベーション政策",
        "definition": "AI診断・遠隔医療・ウェアラブル・電子カルテ等のデジタルヘルス技術の開発・規制・普及を促進する政策を指す。FDAのデジタルヘルス政策・EUのMDR・AI医療機器規制が主要枠組みである。",
        "impact_summary": "医療の質・効率・アクセスをデジタル技術で改善しながら、安全性・プライバシー・公平性を確保する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "health_innovation",
        "era_start": 2010,
        "innovation_type": "policy",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "デジタルヘルス政策,遠隔医療,AI医療機器,電子カルテ",
        "keywords_en": "digital health innovation policy,telemedicine,AI medical device,EHR policy",
        "key_researchers": '["Topol E.J.", "Torous J."]',
        "key_works": '["Deep Medicine (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_710",
        "name_en": "Science Advice and Policy Interface",
        "name_ja": "科学助言と政策インターフェース",
        "definition": "科学的専門知識が政策決定プロセスに投入される制度的メカニズムを指す。主席科学顧問・科学諮問委員会・証拠統合機関・科学と政治の越境管理が主要論点である。",
        "impact_summary": "政策立案に科学的根拠を効果的に組み込むための制度設計を通じて、証拠に基づく統治を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1960,
        "innovation_type": "institutional",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "科学助言,科学顧問,諮問委員会,科学政策インターフェース",
        "keywords_en": "science advice,chief science advisor,advisory committee,science-policy interface",
        "key_researchers": '["Gluckman P.", "Jasanoff S."]',
        "key_works": '["Science for Policy (2006)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_711",
        "name_en": "Cultural Factors in Innovation Policy",
        "name_ja": "イノベーション政策における文化的要因",
        "definition": "国家・地域の文化的特性（リスク許容度・信頼・協調・権力距離・長期指向等）がイノベーション活動と政策の有効性に与える影響を論じる枠組みを指す。",
        "impact_summary": "政策の文化的文脈適合性を高め、他国のベストプラクティスの単純移植ではなく文化的翻案の重要性を示す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "comparative_institutionalism",
        "era_start": 2000,
        "innovation_type": "theory",
        "cognitive_mechanism": "comparative",
        "keywords_ja": "文化とイノベーション,リスク文化,信頼,制度的文化",
        "keywords_en": "culture and innovation,risk culture,trust,institutional culture",
        "key_researchers": '["Hofstede G.", "Landes D.S."]',
        "key_works": '["Culture and the Wealth of Nations (2000)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_712",
        "name_en": "Agricultural Innovation Systems",
        "name_ja": "農業イノベーションシステム",
        "definition": "農業生産性・持続可能性・農家所得の向上に向けた知識・技術・制度の体系を指す。農業試験場・普及システム・種子規制・農民組織・市場接続が主要システム要素である。",
        "impact_summary": "農業部門の生産性と持続可能性を同時に高めるイノベーションシステムの設計と強化に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 1995,
        "innovation_type": "systemic",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "農業イノベーションシステム,農業普及,農業技術政策,食料安保",
        "keywords_en": "agricultural innovation system,agricultural extension,agri-tech policy,food security",
        "key_researchers": '["Spielman D.J.", "Klerkx L."]',
        "key_works": '["Innovation Systems Thinking (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_713",
        "name_en": "Science-Technology-Society Studies",
        "name_ja": "科学技術社会論",
        "definition": "科学・技術・社会の相互構成的関係を社会学・哲学・歴史学の手法で研究する学際的分野を指す。技術の社会的形成・共同生産・境界事業・技術ガバナンスへの含意を扱う。",
        "impact_summary": "技術は中立的ではなく社会的・政治的に構成されるという認識を深め、より民主的で省察的な技術政策の基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_studies",
        "era_start": 1970,
        "innovation_type": "theory",
        "cognitive_mechanism": "reflexive",
        "keywords_ja": "STS,科学社会学,技術の社会的形成,共同生産",
        "keywords_en": "STS,science sociology,social shaping of technology,co-production",
        "key_researchers": '["Jasanoff S.", "Bijker W.E."]',
        "key_works": '["Shaping Technology/Building Society (1992)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_714",
        "name_en": "Global Innovation Index Methodology",
        "name_ja": "グローバルイノベーション指数手法",
        "definition": "WIPOとINSEAD等が共同作成するGIIの指標設計・データ収集・集計手法・スコアリングロジックを指す。イノベーション投入5柱とアウトプット2柱の132指標で構成され、130以上の国・地域を毎年評価する。",
        "impact_summary": "各国のイノベーション環境と成果を包括的に評価するGIIが国際比較・政策目標設定の標準的参照指標となっている。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "measurement_framework",
        "era_start": 2007,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "グローバルイノベーション指数,GII,WIPO,イノベーション国際比較",
        "keywords_en": "Global Innovation Index,GII,WIPO,international innovation comparison",
        "key_researchers": '["Dutta S.", "Lanvin B.", "Wunsch-Vincent S."]',
        "key_works": '["Global Innovation Index (annual since 2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
]

conn = sqlite3.connect(db_path)
cursor = conn.cursor()
for e in entries:
    cursor.execute("""
        INSERT OR REPLACE INTO innovation_theory
        (id, name_en, name_ja, definition, impact_summary, subfield, school_of_thought,
         era_start, innovation_type, cognitive_mechanism, keywords_ja, keywords_en,
         key_researchers, key_works, status, source_reliability, data_completeness,
         created_at, updated_at)
        VALUES (:id, :name_en, :name_ja, :definition, :impact_summary, :subfield,
                :school_of_thought, :era_start, :innovation_type, :cognitive_mechanism,
                :keywords_ja, :keywords_en, :key_researchers, :key_works, :status,
                :source_reliability, :data_completeness, :created_at, :updated_at)
    """, e)
conn.commit()
conn.close()
print(f"Inserted {len(entries)} entries")
