import sqlite3
from datetime import datetime

db_path = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"
now = datetime.now().isoformat()

entries = [
    {
        "id": "inno_pol_501",
        "name_en": "Innovation Observatory Networks",
        "name_ja": "イノベーション観測所ネットワーク",
        "definition": "国・地域のイノベーション活動を継続的に監視・データ収集・分析する機関ネットワークであり、欧州イノベーション観測所（EIO）・Joint Research Centre（JRC）・各国のイノベーション政策研究機関が構成する。リアルタイムのイノベーション指標モニタリング・政策効果の早期検出・グローバルな比較分析が主な機能として設計されており、政策のアジャイル的調整を支える情報基盤を提供している。AIとビッグデータの活用により観測の範囲・速度・精度が大幅に向上しつつある。",
        "impact_summary": "イノベーション政策の実施状況をリアルタイムで把握する継続的なモニタリング基盤を整備し、適時の政策修正と証拠蓄積のサイクルを実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2005,
        "innovation_type": "measurement,governance",
        "cognitive_mechanism": "monitoring,data-collection",
        "keywords_ja": "イノベーション観測所,JRC,モニタリング,政策追跡",
        "keywords_en": "innovation observatory,JRC,monitoring,policy tracking",
        "key_researchers": '["European Commission JRC","Hugo Hollanders","Stefan Kuhlmann"]',
        "key_works": '["Eco-Innovation Observatory (2010)","Innovation Policy Monitoring (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_502",
        "name_en": "National Innovation System Performance",
        "name_ja": "国家イノベーション・システムのパフォーマンス",
        "definition": "国家イノベーション・システム（NIS）が知識の創出・普及・活用をどの程度効率的・効果的に実現しているかを多次元的に評価する枠組みであり、R&D強度・特許・企業イノベーション率・生産性成長・グローバル市場シェアなどのアウトカム指標を統合した評価が標準的手法として確立されている。Edquist（2005）のシステム機能アプローチ（10の機能）が体系的な評価フレームワークを提供しており、機能的弱点の特定が政策的対応の起点となる。",
        "impact_summary": "NIS全体のパフォーマンスを包括的に診断し、システムの機能的強みと弱みを特定してターゲットを絞った政策改善の根拠を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2000,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "systems-thinking,evaluation",
        "keywords_ja": "NISパフォーマンス,システム機能,Edquist,イノベーション評価",
        "keywords_en": "NIS performance,system functions,Edquist,innovation evaluation",
        "key_researchers": '["Charles Edquist","Bengt-Ake Lundvall","Richard Nelson"]',
        "key_works": '["Systems of Innovation (2005)","National Innovation Systems (1993)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_503",
        "name_en": "Intellectual Property Rights Reform",
        "name_ja": "知的財産権制度改革",
        "definition": "デジタル経済・AI・合成生物学などの新興技術への対応と、イノベーション促進と知識アクセスのバランス改善を目的とした知的財産権制度の体系的改革を分析する研究領域であり、特許保護期間の見直し・AI生成物の権利帰属・伝統的知識の保護・コンピュータ実施発明の特許適格性が現代的な改革課題として浮上している。WIPO開発アジェンダ（2007）・欧州特許制度統合（UP/UPC）・日本の不正競争防止法改正が代表的な最近の改革として知られる。",
        "impact_summary": "新興技術・新興産業に対応した知財制度の現代化を実現し、イノベーション投資の適切な保護と知識の社会的活用の最適バランスを更新している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2004,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "IP-reform,institutional-design",
        "keywords_ja": "知財改革,WIPO,UP/UPC,AI著作権",
        "keywords_en": "IP reform,WIPO,UP/UPC,AI copyright",
        "key_researchers": '["Jerome Reichman","Peter Drahos","Susy Frankel"]',
        "key_works": '["International Intellectual Property (2009)","Intellectual Property Reform (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_504",
        "name_en": "Catalytic Innovation Policy",
        "name_ja": "触媒的イノベーション政策",
        "definition": "政府が直接的な資金供給・規制・調達に加えて、市場形成・行動基準設定・情報提供・調整機能提供などの「触媒的」役割を通じて民間イノベーション活動を誘発する政策アプローチであり、政府の直接的コントロールではなく間接的なエコシステム形成が特徴である。Ezell & Atkinson（2011）・欧州委員会のCatalytic Role of the Stateが概念的枠組みを提供しており、イノベーション・ハブ設立・データ共有標準の策定・市場情報の普及が触媒的政策手段の代表例として研究されている。",
        "impact_summary": "政府が直接の投資者ではなく触媒・協調者として機能することで、民間エコシステムの自律的活力を最大化しながら公共目標の実現を効率的に達成している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2011,
        "innovation_type": "policy",
        "cognitive_mechanism": "catalytic,ecosystem",
        "keywords_ja": "触媒的政策,市場形成,情報提供,エコシステム触媒",
        "keywords_en": "catalytic policy,market formation,information provision,ecosystem catalyst",
        "key_researchers": '["Robert Atkinson","Stephen Ezell","Mariana Mazzucato"]',
        "key_works": '["Innovation Economics (2011)","The Entrepreneurial State (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_505",
        "name_en": "Science Policy Institutions",
        "name_ja": "科学政策機関",
        "definition": "科学・技術・イノベーション政策の立案・調整・評価を専門的に担う政府機関・研究評議会・政策研究機関の役割と設計を分析する研究領域であり、NSF（米国）・UKRI（英国）・ANR（フランス）・JST（日本）などの研究資金配分機関と、BMBF（ドイツ）・METI（日本）などのSTI省庁が分析対象の中心となる。機関の設計（独立性・任務・権限・評価システム）がイノベーション政策の有効性を規定する重要な制度的要因として研究されている。",
        "impact_summary": "科学技術政策の実施主体の制度的設計を最適化し、政策の効率的・一貫的な実施と科学コミュニティへの信頼性確保を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 1945,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "institutional-design,governance",
        "keywords_ja": "科学政策機関,NSF,UKRI,JST,研究評議会",
        "keywords_en": "science policy institutions,NSF,UKRI,JST,research councils",
        "key_researchers": '["David Guston","Daniel Kevles","Roger Geiger"]',
        "key_works": '["Between Politics and Science (2000)","The Physicist (1987)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_506",
        "name_en": "Macroeconomic Framework for Innovation",
        "name_ja": "イノベーションのためのマクロ経済枠組み",
        "definition": "財政・金融・為替・労働・貿易政策などのマクロ経済政策がイノベーション活動の量と質に与える影響を分析し、イノベーション促進に適したマクロ経済環境の設計を論じる研究領域であり、低金利環境・為替安定・財政収支・労働市場柔軟性がイノベーション投資に与える相関が実証的に研究されている。国際競争力論（Porter 1990）からの派生として、有利なマクロ経済枠組みがイノベーション・エコシステムの前提条件となることが強調されている。",
        "impact_summary": "マクロ経済政策とイノベーション政策の相互作用を明示化し、イノベーション促進に資する安定的で競争的なマクロ経済環境の条件整備を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1986,
        "innovation_type": "policy",
        "cognitive_mechanism": "macro-economic,policy-design",
        "keywords_ja": "マクロ経済,金融政策,財政政策,競争力",
        "keywords_en": "macroeconomics,monetary policy,fiscal policy,competitiveness",
        "key_researchers": '["Michael Porter","Dani Rodrik","Barry Eichengreen"]',
        "key_works": '["The Competitive Advantage of Nations (1990)","One Economics, Many Recipes (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_507",
        "name_en": "Foreign Direct Investment and Innovation",
        "name_ja": "外国直接投資とイノベーション",
        "definition": "外国企業による直接投資（FDI）が受け入れ国のイノベーション能力・生産性・技術移転に与える影響と、FDIを通じたイノベーション波及を最大化するための政策設計を分析する研究領域であり、技術・知識の垂直スピルオーバーと水平スピルオーバーの条件特定が中心的な実証課題となっている。受け入れ国の吸収能力・人的資本・制度的環境がFDIからの技術スピルオーバーを規定する主要変数として分析されており、投資環境整備政策・産業連関構築・技術移転インセンティブが政策的含意として導出されている。",
        "impact_summary": "FDIを通じた技術・知識のスピルオーバーを国内イノベーション能力の向上に活用するための政策条件を特定し、グローバルな技術拡散と産業高度化を促進している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "spillover,investment",
        "keywords_ja": "FDI,技術スピルオーバー,吸収能力,投資環境",
        "keywords_en": "FDI,technology spillover,absorptive capacity,investment environment",
        "key_researchers": '["Bruce Kogut","Udo Zander","Magnus Blomstrom"]',
        "key_works": '["Knowledge and the Speed of Transfer (1993)","FDI and Technology Spillovers (1999)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_508",
        "name_en": "Innovation System Resilience",
        "name_ja": "イノベーション・システムのレジリエンス",
        "definition": "外部ショック（パンデミック・金融危機・自然災害・地政学的変動等）に対してイノベーション・システムが機能を維持・回復・進化させる能力（レジリエンス）の測定と強化を論じる研究領域であり、COVID-19パンデミックが国家イノベーション・システムのレジリエンスの比較研究に豊富な自然実験を提供した。冗長性・多様性・モジュール性・適応性がレジリエントなイノベーション・システムの設計原則として特定されており、政策的対応としてのポートフォリオ多様化・国際連携・デジタル基盤強化が研究されている。",
        "impact_summary": "予測不可能な外部ショックに対するイノベーション・システムの耐性と回復力を高め、危機時においてもイノベーション活動の継続と加速を確保している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2012,
        "innovation_type": "policy,governance",
        "cognitive_mechanism": "resilience,systems-thinking",
        "keywords_ja": "レジリエンス,イノベーションシステム,COVID-19,危機対応",
        "keywords_en": "resilience,innovation system,COVID-19,crisis response",
        "key_researchers": '["Johan Schot","Caetano Penna","Fred Gault"]',
        "key_works": '["Innovation System Resilience (2015)","COVID-19 and Innovation Policy (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_509",
        "name_en": "Research Culture and Incentive Systems",
        "name_ja": "研究文化とインセンティブ・システム",
        "definition": "研究者・研究機関の行動・優先事項・倫理を形成する研究文化と、それを規定するインセンティブ構造（業績評価・昇進基準・資金獲得・出版プレッシャー等）の相互作用を分析する研究領域であり、「パブリッシュ・オア・ペリッシュ」文化・研究不正・再現性危機・オープンサイエンスへの抵抗が現代的な研究文化問題として認識されている。研究文化改革への政策介入（評価基準見直し・CoARA宣言・DORA宣言）が国際的に推進されている。",
        "impact_summary": "歪んだ研究インセンティブが引き起こす研究不正・再現性低下・科学的誠実性の毀損を政策的に改善し、長期的な科学の健全性と社会的信頼を維持している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2012,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "incentive-design,culture",
        "keywords_ja": "研究文化,DORA宣言,再現性危機,評価改革",
        "keywords_en": "research culture,DORA declaration,replication crisis,evaluation reform",
        "key_researchers": '["Michèle Lamont","Marcus Munafo","Dorothy Bishop"]',
        "key_works": '["DORA Declaration (2013)","CoARA Agreement (2022)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_510",
        "name_en": "Bioinformatics and Computational Biology Policy",
        "name_ja": "バイオインフォマティクスと計算生物学政策",
        "definition": "ゲノム・プロテオーム・メタボロームなどの大規模生命科学データを計算機科学・統計学・AIで解析するバイオインフォマティクスと計算生物学の研究インフラ・データ共有・人材育成に関する政策を分析する領域であり、NIH拠点プログラム・欧州ライフサイエンスインフラ（ELIXIR）・日本のNBDC（国立生命科学データベースセンター）が代表的な政策実施基盤として機能している。ゲノムデータの国境を越えた共有とプライバシー保護の均衡が国際的な政策課題として浮上している。",
        "impact_summary": "生命科学のデジタル変革を支えるデータ・計算インフラと人材を整備し、個別化医療・農業・バイオ産業のイノベーション加速に不可欠な基盤を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2003,
        "innovation_type": "policy,governance",
        "cognitive_mechanism": "data-infrastructure,computation",
        "keywords_ja": "バイオインフォマティクス,ELIXIR,ゲノムデータ,計算生物学",
        "keywords_en": "bioinformatics,ELIXIR,genomic data,computational biology",
        "key_researchers": '["Ewan Birney","Steven Salzberg","Søren Brunak"]',
        "key_works": '["ELIXIR Infrastructure Plan (2014)","Bioinformatics Policy (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_511",
        "name_en": "Regulatory Burden and Innovation",
        "name_ja": "規制負担とイノベーション",
        "definition": "行政規制・コンプライアンス要件・申請手続きなどの規制負担が企業のイノベーション活動（R&D投資・新製品開発・市場参入）に与える抑制効果と、その軽減のための政策設計を分析する研究領域であり、中小企業・スタートアップが規制負担を相対的に重く受ける「規制の逆進性」が特に政策的関心を集めている。規制の累積的効果・コンプライアンスコスト計測・ワン・イン・ワン・アウト規制改革が主要な研究・政策テーマとして知られる。",
        "impact_summary": "不必要な規制コストがイノベーションを阻害する実態を計量化し、規制改革による創業・革新の障壁低減と競争的な市場環境の整備に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 1995,
        "innovation_type": "policy,measurement",
        "cognitive_mechanism": "regulatory-cost,measurement",
        "keywords_ja": "規制負担,コンプライアンスコスト,ワンインワンアウト,規制改革",
        "keywords_en": "regulatory burden,compliance cost,one-in-one-out,regulatory reform",
        "key_researchers": '["Jaffe Adam","Palmer Karen","Stavins Robert"]',
        "key_works": '["Environmental Regulation and Innovation (1995)","Regulatory Burden (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_512",
        "name_en": "Knowledge Transfer Networks",
        "name_ja": "知識移転ネットワーク",
        "definition": "産業界・大学・研究機関・政府間の知識・技術・人材の移転を促進するために政策的に構築されたネットワーク組織であり、英国のKTN（Knowledge Transfer Networks）・欧州のKICs（Knowledge and Innovation Communities）・日本の産業技術連携推進会議が代表的な制度として知られる。ネットワーク仲介機関・コンソーシアム・テクノロジー・ゲートウェイが具体的な組織形態として機能しており、知識の「粘着性」（stickiness）克服が主要な政策課題として認識されている。",
        "impact_summary": "産学官間の知識移転の制度的障壁を低減し、研究知識の商業化・産業応用・政策への統合を体系的に促進するネットワーク基盤を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2004,
        "innovation_type": "policy",
        "cognitive_mechanism": "knowledge-transfer,networks",
        "keywords_ja": "知識移転ネットワーク,KTN,KICs,産学官連携",
        "keywords_en": "knowledge transfer networks,KTN,KICs,industry-academia-government",
        "key_researchers": '["Eric von Hippel","Eric Bartelsman","Luc Soete"]',
        "key_works": '["Democratizing Innovation (2005)","Knowledge Transfer in Networks (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_513",
        "name_en": "Risk-based Regulation Framework",
        "name_ja": "リスクベース規制枠組み",
        "definition": "規制対象のリスクの大きさ・発生確率・影響範囲に基づいて規制の強度・頻度・手段を比例的に設計するリスクベース規制アプローチであり、全規制対象に一律の規制を課す従来のルールベース規制とは対照的な柔軟性を持つ。英国HSE（健康安全局）・金融サービス庁・医薬品規制機関がリスクベース規制の先行実施機関として知られており、新興技術分野での適用拡大が重要な政策課題として浮上している。AI・医療機器・金融革新製品でのリスク比例規制の具体的設計が研究されている。",
        "impact_summary": "規制リソースをリスクが高い領域に集中させることで規制の効率性と比例性を確保し、低リスクの革新的活動への規制障壁を最小化している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 1998,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "risk-proportionality,regulatory-design",
        "keywords_ja": "リスクベース規制,比例規制,HSE,AI規制リスク分類",
        "keywords_en": "risk-based regulation,proportionate regulation,HSE,AI risk classification",
        "key_researchers": '["Chris Hood","Henry Rothstein","Robert Baldwin"]',
        "key_works": '["Avoiding Regulatory Failure (1997)","Risk-Based Regulation (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_514",
        "name_en": "S&T Governance Compared Asia",
        "name_ja": "アジアの科学技術ガバナンス比較",
        "definition": "日本・韓国・中国・シンガポール・台湾などアジア主要国の科学技術政策体制の特徴と成果を比較分析する研究領域であり、発展国家モデル・産業政策とイノベーション政策の統合・政府主導の研究開発体制がアジアの共通的な文脈として分析されている。各国の国家イノベーション・システムの強みと課題・キャッチアップから技術フロンティアへの移行・少子化・高齢化への政策的対応が比較研究の主要テーマとして蓄積されている。",
        "impact_summary": "アジア主要国のSTIガバナンスの比較分析を通じて各国固有の成功要因と課題を特定し、アジア的文脈でのイノベーション政策改善に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1997,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "comparative-policy,governance",
        "keywords_ja": "アジア科学技術,発展国家,比較政策,韓国日本中国",
        "keywords_en": "Asian S&T,developmental state,comparative policy,Korea Japan China",
        "key_researchers": '["Linsu Kim","Alice Amsden","Dieter Ernst"]',
        "key_works": '["The Developmental State (1999)","Asian Innovation Systems (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_515",
        "name_en": "Clean Technology Financing",
        "name_ja": "クリーンテクノロジー・ファイナンス",
        "definition": "再生可能エネルギー・エネルギー効率・クリーンモビリティ・グリーン水素などのクリーンテクノロジーへの投資を促進・拡大するための公的・民間金融メカニズムの設計と評価を分析する研究領域であり、グリーンボンド・サステナブルファイナンス・公的開発銀行の役割・炭素市場連動ファイナンスが主要な政策・市場手段として研究されている。GFANZ（Glasgow Financial Alliance for Net Zero）・国際開発金融クラブ（IDFC）がグローバルなクリーンファイナンスの枠組みを提供している。",
        "impact_summary": "脱炭素化に必要な大規模技術転換への投資資金を公私連携で動員し、気候変動対策とグリーン産業発展への資金の流れを政策的に形成している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2015,
        "innovation_type": "policy,fiscal",
        "cognitive_mechanism": "green-finance,market-formation",
        "keywords_ja": "クリーンファイナンス,グリーンボンド,GFANZ,脱炭素投資",
        "keywords_en": "clean finance,green bonds,GFANZ,decarbonization investment",
        "key_researchers": '["Nick Robins","Stephane Hallegatte","Harro van Asselt"]',
        "key_works": '["Financing the Transition (2017)","GFANZ Framework (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_516",
        "name_en": "Space Innovation Policy Metrics",
        "name_ja": "宇宙イノベーション政策指標",
        "definition": "宇宙産業のイノベーション活動（衛星製造・打上サービス・宇宙データ応用・宇宙観光・深宇宙探査等）を測定・評価するための指標体系であり、OECD宇宙フォーラム・欧州宇宙庁（ESA）・日本宇宙航空研究開発機構（JAXA）が測定枠組みの開発を進めている。打上実績・衛星ミッション成功率・宇宙セクターGDP寄与・宇宙関連特許・雇用統計が代表的な指標として提案されており、民間宇宙産業（New Space）の急成長に伴い測定手法の更新が急務となっている。",
        "impact_summary": "宇宙経済のイノベーション活動を可視化・定量化し、宇宙産業政策の立案と国際比較のための証拠基盤を構築している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 2010,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "quantification,space-economy",
        "keywords_ja": "宇宙経済指標,ESA,JAXA,New Space測定",
        "keywords_en": "space economy metrics,ESA,JAXA,New Space measurement",
        "key_researchers": '["OECD Space Forum","European Space Policy Institute","RAND Corp"]',
        "key_works": '["OECD Space Economy (2020)","New Space Economy Report (2022)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_517",
        "name_en": "Science Technology Society Studies",
        "name_ja": "科学技術社会論",
        "definition": "科学・技術と社会の相互形成（co-production）を批判的・社会学的・哲学的に分析するSTS（Science and Technology Studies）の研究領域であり、ラトゥール・ウールガーの実験室研究・コリンズの知識社会学・ジャサノフの市民認識論が理論的基盤を提供している。技術の社会的形成（SCOT）・アクターネットワーク理論（ANT）・想像の共同体（Imagined Communities of Science）などの枠組みが政策研究への応用において特に重要な理論ツールを提供している。",
        "impact_summary": "科学技術が社会に中立的な事実を提供するのではなく社会的に構成されることを明らかにし、STI政策の民主的設計と社会的文脈への感受性向上に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1979,
        "innovation_type": "governance",
        "cognitive_mechanism": "social-construction,critique",
        "keywords_ja": "STS,科学技術社会論,SCOT,ANT",
        "keywords_en": "STS,science technology society,SCOT,ANT",
        "key_researchers": '["Sheila Jasanoff","Bruno Latour","Wiebe Bijker"]',
        "key_works": '["The Social Construction of Technological Systems (1987)","The Pasteurization of France (1988)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_518",
        "name_en": "Macro-level Innovation Indicators",
        "name_ja": "マクロレベルのイノベーション指標",
        "definition": "国家・産業・地域レベルでのイノベーション実績を集計的に評価するマクロ指標の設計と活用を研究する領域であり、特許数・R&D支出GDP比・新産業創出率・生産性成長率・ハイテク製品輸出比率などが代表的なマクロ指標として広く活用されている。マクロ指標の限界（イノベーションの質を反映しない・国際比較上の制度的差異・時間的ラグ等）への対処として複合指標・パネルデータ分析・時系列比較が標準的分析手法として採用されている。",
        "impact_summary": "国家・産業のイノベーション活動全体を俯瞰的に評価し、政策の優先課題設定と国際的な競争力ポジションの把握に不可欠な集計情報を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "aggregate-indicators,benchmarking",
        "keywords_ja": "マクロ指標,R&D対GDP,生産性,ハイテク輸出",
        "keywords_en": "macro indicators,R&D to GDP,productivity,high-tech exports",
        "key_researchers": '["OECD DSTI","Eurostat","UNESCO Institute for Statistics"]',
        "key_works": '["OECD Science Technology and Innovation Outlook (annual)","World Development Indicators (annual)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_519",
        "name_en": "Skills Taxonomy for Innovation",
        "name_ja": "イノベーションのためのスキル分類体系",
        "definition": "イノベーション活動に必要な技術的・認知的・対人的スキルの体系的分類と需給分析に関する研究領域であり、O*NET・欧州スキル・コンピテンス・資格・職業フレームワーク（ESCO）・世界経済フォーラムの「仕事の未来」レポートが代表的なスキル分類基盤を提供している。AIによるスキル陳腐化とリスキリング需要の急増・STEM人材の国際的希少性・デジタルスキル格差がイノベーション・スキル政策の主要課題として認識されている。",
        "impact_summary": "イノベーション経済に必要なスキルの体系的把握と需給分析を可能にし、教育・訓練・移民政策の証拠基盤としてのスキル政策設計を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2005,
        "innovation_type": "policy,measurement",
        "cognitive_mechanism": "human-capital,taxonomy",
        "keywords_ja": "スキル分類,ESCO,STEM人材,リスキリング",
        "keywords_en": "skills taxonomy,ESCO,STEM talent,reskilling",
        "key_researchers": '["David Autor","Frank Levy","Richard Murnane"]',
        "key_works": '["Skill Biased Technology Change (2003)","The Future of Jobs (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_520",
        "name_en": "Nature-Based Solutions Policy",
        "name_ja": "自然に基づく解決策政策",
        "definition": "生態系サービス・生物多様性・自然インフラを活用して社会課題（気候変動・防災・食料安全保障・都市環境）を解決する「自然に基づく解決策（NbS）」を政策的に推進するための枠組みであり、EU生物多様性戦略・UN SDGs目標15・パリ協定NDCsとの整合が重要な政策課題となっている。NbSの効果測定・スケーリング条件・生態系サービス価値評価・ネイチャーポジティブ経済への移行が研究の主要テーマとして浮上している。",
        "impact_summary": "自然生態系の機能を社会課題解決のイノベーションに活用し、グレーインフラに代わる費用対効果の高い持続可能な解決策の政策的普及を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "sustainability,systems-thinking",
        "keywords_ja": "NbS,生態系サービス,生物多様性,ネイチャーポジティブ",
        "keywords_en": "NbS,ecosystem services,biodiversity,nature positive",
        "key_researchers": '["Nathalie Pettorelli","Albert Cohen","Laure Ledoux"]',
        "key_works": '["Nature-Based Solutions (2018)","EU NbS Mission (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_521",
        "name_en": "Policy Design Theory",
        "name_ja": "政策設計論",
        "definition": "公共政策の問題定義・目標設定・手段選択・実施設計・評価計画の体系的プロセスを研究する理論領域であり、政策設計の成功と失敗を規定する変数として、政策問題の構造・政策ツールの特性・制度的文脈・政治的実現可能性が分析されている。Howlett・Ramesh・Perl（2009）の政策設計論・Linder・Peters（1990）のポリシーインストルメント論が理論的基盤を提供しており、複雑な社会課題に対する「適合的（fit-for-purpose）」な政策設計原則の体系化が研究課題として継続している。",
        "impact_summary": "公共政策の設計品質を向上させる理論的原則と実践的知見を提供し、複雑な社会課題への的確な政策対応と意図せぬ失敗の予防を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "policy-design,rational-design",
        "keywords_ja": "政策設計,手段選択,問題構造,政策理論",
        "keywords_en": "policy design,instrument choice,problem structure,policy theory",
        "key_researchers": '["Michael Howlett","M. Ramesh","Bryan Jones"]',
        "key_works": '["Designing Public Policies (2009)","Policy Design and Non-Design (1990)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_522",
        "name_en": "Knowledge-based Economy Policy",
        "name_ja": "知識基盤経済政策",
        "definition": "知識・情報・スキルが主要な生産要素となる「知識基盤経済」への移行を政策的に促進・支援するための枠組みであり、高等教育拡充・R&D投資促進・ICTインフラ整備・知識移転支援・起業家エコシステム形成が主要な政策柱として設定されている。OECDの「知識経済」報告書（1996）が国際的な政策議論の起点となっており、各国の知識経済政策の比較評価と知識指標の開発が進んでいる。デジタル経済への移行とともに「データ経済政策」への概念的進化も見られる。",
        "impact_summary": "経済発展の中心を物的資本から知識資本に転換し、持続的な生産性向上と高付加価値産業の育成を通じた長期的な経済成長を政策的に支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1996,
        "innovation_type": "policy",
        "cognitive_mechanism": "knowledge-economy,human-capital",
        "keywords_ja": "知識経済政策,高等教育,ICTインフラ,知識移転",
        "keywords_en": "knowledge economy policy,higher education,ICT infrastructure,knowledge transfer",
        "key_researchers": '["OECD","Dominique Foray","Paul Romer"]',
        "key_works": '["The Knowledge-Based Economy (1996)","The Endogenous Technological Change (1990)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_523",
        "name_en": "STEM Education Policy",
        "name_ja": "STEM教育政策",
        "definition": "理科・技術・工学・数学（STEM）分野の教育を強化・普及させることで科学技術人材を育成するための教育政策であり、PISA・TIMSS等の国際学力調査によるベンチマーキング・STEM教員の質向上・女性STEM参加促進・STEM教育へのICT統合が主要な政策テーマとして世界的に展開されている。米国のEvery Student Succeeds Act・EU STEM Coalition・日本のSTEAM教育推進政策が代表的な国家政策として知られており、21世紀型スキルとの統合（STEAM）も重要なトレンドとして浮上している。",
        "impact_summary": "科学技術イノベーションの人的基盤を教育段階から整備し、将来のイノベーター・技術者・科学者の安定的供給を政策的に確保している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2001,
        "innovation_type": "policy",
        "cognitive_mechanism": "human-capital,education",
        "keywords_ja": "STEM教育,STEAM,理工系人材,PISA",
        "keywords_en": "STEM education,STEAM,science engineering talent,PISA",
        "key_researchers": '["Andreas Schleicher","Yvonne Kao","National Academies"]',
        "key_works": '["STEM Education Framework (2011)","PISA 2022 Results (2023)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_524",
        "name_en": "Health Technology Assessment",
        "name_ja": "医療技術評価",
        "definition": "新しい医薬品・医療機器・診断技術・治療手技の臨床的有効性・安全性・費用対効果・社会的影響を体系的に評価するHTA（Health Technology Assessment）の方法論と制度的枠組みであり、NICE（英国）・G-BA（ドイツ）・HAS（フランス）・厚生労働省（日本）が代表的な国家HTA機関として機能している。QALYを用いた費用効用分析・証拠合成・多基準意思決定分析（MCDA）が標準的な評価手法として確立されており、価値に基づく医薬品価格設定（VBP）の実践的基盤を提供している。",
        "impact_summary": "医療技術の社会的価値を体系的に評価し、公的医療資源の最適配分と医療イノベーションへの適切なインセンティブの両立を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "エビデンスベース政策論",
        "era_start": 1975,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "evaluation,cost-effectiveness",
        "keywords_ja": "HTA,QALY,費用効用分析,NICE",
        "keywords_en": "HTA,QALY,cost-utility analysis,NICE",
        "key_researchers": '["Michael Drummond","Mark Sculpher","George Torrance"]',
        "key_works": '["Methods for Economic Evaluation (2005)","NICE Methods Guide (2022)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_525",
        "name_en": "Procurement Data as Innovation Evidence",
        "name_ja": "調達データによるイノベーション証拠",
        "definition": "政府・機関の購買・調達データを体系的に分析することでイノベーション製品・サービスの普及・浸透・市場形成を定量的に把握する方法論であり、オープンコントラクティング・スタンダード（OCS）・公的調達データベース（TED・USASPending）が主要なデータソースとして活用されている。調達データの機械学習による分析を通じて、新技術採用率・新規参入者の市場アクセス・革新的サプライヤーの特定が可能となっている。EUのデータ主導イノベーション調達評価が先行事例として注目されている。",
        "impact_summary": "公共調達データから政策効果と技術普及の実態を証拠として抽出し、需要側イノベーション政策の評価と改善のための新たな証拠経路を開拓している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "エビデンスベース政策論",
        "era_start": 2015,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "data-driven,evidence",
        "keywords_ja": "調達データ,OCS,TED,イノベーション証拠",
        "keywords_en": "procurement data,OCS,TED,innovation evidence",
        "key_researchers": '["Gavin Hayman","Open Contracting Partnership","European Commission"]',
        "key_works": '["Open Contracting Standard (2014)","Procurement Data for Innovation (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_526",
        "name_en": "Venture Capital Market Analysis",
        "name_ja": "ベンチャーキャピタル市場分析",
        "definition": "ベンチャーキャピタル市場の規模・構造・投資パターン・成果を定量的に分析し、VC市場のイノベーション経済への貢献を評価する研究領域であり、PitchBook・Crunchbase・Preqin・NVCA（全米ベンチャーキャピタル協会）データが主要な分析ソースとして用いられている。投資ラウンドサイズ・セクター別配分・地域集中・成功率・IPO/M&Aによる出口実績が標準的な分析指標として確立されている。VC市場のデータ分析はイノベーション政策設計とスタートアップ・エコシステム評価において重要な証拠基盤を提供している。",
        "impact_summary": "ベンチャーキャピタル市場の実態を定量的に把握し、スタートアップ・エコシステムへの資金フローと政策介入の最適化に向けた証拠基盤を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "market-analysis,quantification",
        "keywords_ja": "VC市場分析,PitchBook,投資ラウンド,スタートアップ資金",
        "keywords_en": "VC market analysis,PitchBook,investment rounds,startup funding",
        "key_researchers": '["Josh Lerner","Paul Gompers","Anna Kovner"]',
        "key_works": '["The Venture Capital Cycle (1999)","Venture Capital and the Finance of Innovation (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_527",
        "name_en": "Participatory Budgeting for Innovation",
        "name_ja": "イノベーションのための参加型予算",
        "definition": "市民が公共予算の一部をどの革新的事業・プロジェクトに使うかを直接決定する参加型予算制度のSTI政策への適用であり、科学技術予算への市民優先事項の反映・市民科学プロジェクトへの資金配分・地域イノベーション課題の特定が参加型予算のSTI文脈での主要テーマとして研究されている。ポルトアレグレ（1989）を起源とする参加型予算の世界的普及とデジタル化（d-democracy・vTaiwan等）がSTI政策参加の新たな可能性を開いている。",
        "impact_summary": "市民の価値観と優先事項を公共イノベーション投資に反映させ、STI政策の民主的正統性と社会的受容性を向上させるための直接的な参加メカニズムを提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2010,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "participation,democratic",
        "keywords_ja": "参加型予算,市民参加,d-democracy,STI民主主義",
        "keywords_en": "participatory budgeting,citizen participation,d-democracy,STI democracy",
        "key_researchers": '["Archon Fung","Erik Wright","Gianpaolo Baiocchi"]',
        "key_works": '["Empowered Participation (2003)","Democratic Accountability in Participatory Budgeting (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_528",
        "name_en": "Technology Concentration and Monopoly",
        "name_ja": "技術集中と独占",
        "definition": "特定の技術・市場において少数企業が圧倒的な市場支配力を持つ技術独占の経済的・社会的影響を分析し、競争政策的対応を論じる研究領域であり、GAFA（Google・Apple・Facebook・Amazon）のプラットフォーム独占・半導体・医薬品・AI分野でのトップ企業への技術・特許集中が現代的な政策課題として浮上している。特許集積・M&Aによる競合の買収・ネットワーク効果によるロックインがデジタル独占形成の主要メカニズムとして分析されている。",
        "impact_summary": "技術集中と独占がイノベーションの多様性・競争・アクセスに与える悪影響を特定し、技術市場の競争環境維持のための競争政策と規制設計に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2010,
        "innovation_type": "policy,governance",
        "cognitive_mechanism": "market-concentration,regulation",
        "keywords_ja": "技術独占,GAFA,プラットフォーム独占,競争政策",
        "keywords_en": "technology monopoly,GAFA,platform monopoly,competition policy",
        "key_researchers": '["Jason Furman","Lina Khan","Tim Wu"]',
        "key_works": '["Unlocking Digital Competition (2019)","The Curse of Bigness (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_529",
        "name_en": "Evaluation of Basic Research",
        "name_ja": "基礎研究の評価",
        "definition": "直接的な応用目的を持たない基礎・純粋研究の価値と貢献を評価する方法論の研究領域であり、長期的・不確実・非線形な基礎研究の成果は既存の評価指標では捕捉困難であるという根本的な方法論的課題が継続的に議論されている。パストゥールの象限（Stokes 1997）・科学的重要度評価・基礎研究から応用への経路分析・時系列スピルオーバー分析が評価の枠組みとして提案されており、高リスク・高リターン研究の公的支援の根拠づけに直接活用されている。",
        "impact_summary": "基礎研究投資の長期的社会価値を評価するための方法論を発展させ、公的研究費の基礎研究への適切な配分と長期的イノベーション基盤の維持に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "エビデンスベース政策論",
        "era_start": 1997,
        "innovation_type": "measurement,evaluation",
        "cognitive_mechanism": "evaluation,basic-research",
        "keywords_ja": "基礎研究評価,パストゥール象限,高リスク研究,長期スピルオーバー",
        "keywords_en": "basic research evaluation,Pasteurs quadrant,high-risk research,long-term spillover",
        "key_researchers": '["Donald Stokes","Nathan Rosenberg","John Irvine"]',
        "key_works": '["Pasteurs Quadrant (1997)","The Evaluation of Basic Research (2000)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_530",
        "name_en": "STI Foresight Governance",
        "name_ja": "STIフォーサイト・ガバナンス",
        "definition": "科学技術イノベーション政策のフォーサイト活動を制度化・統合するための組織設計と政策決定プロセスへの接続方法を分析する研究領域であり、フィンランドの議会フォーサイト（FOPEN）・シンガポールのCentre for Strategic Futures・英国のGovernment Office for Scienceのフォーサイト活動が代表的な制度化事例として知られる。フォーサイト結果の政策実装・フォーサイト・ガバナンスの評価指標・政治的サイクルとの整合が制度化の核心的課題として研究されている。",
        "impact_summary": "長期的なSTIの未来を見通す能力を政府に制度的に組み込み、短期的政治サイクルを超えた持続的・先見的な科学技術政策の実現を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1993,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "foresight,institutional-design",
        "keywords_ja": "フォーサイトガバナンス,議会フォーサイト,CSF,政策統合",
        "keywords_en": "foresight governance,parliamentary foresight,CSF,policy integration",
        "key_researchers": '["Ozcan Saritas","Ian Miles","Sari Helminen"]',
        "key_works": '["Governance of Foresight (2012)","Institutionalising Foresight (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_531",
        "name_en": "Innovation Finance Ecosystems",
        "name_ja": "イノベーション・ファイナンス・エコシステム",
        "definition": "スタートアップ・中小企業・研究機関へのイノベーション資金供給を担う多様なアクター（VC・CVC・公的ファンド・エンジェル・グラント・債務・クラウドファンディング等）のエコシステムとしての相互作用を分析する研究領域であり、各資金ソースの役割分担・資金の連鎖（funding continuum）・エコシステムの地域差がイノベーション・パフォーマンスに与える影響が研究されている。日本・欧州のVC市場の相対的未発達と米国との比較を通じた政策的含意が導出されている。",
        "impact_summary": "イノベーション資金エコシステムの構造的特性と機能を可視化し、公的・民間資本が相互補完的に機能するイノベーション・ファイナンスの生態系設計を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2000,
        "innovation_type": "policy,measurement",
        "cognitive_mechanism": "ecosystem,financing",
        "keywords_ja": "ファイナンス・エコシステム,VC,CVC,資金連鎖",
        "keywords_en": "finance ecosystem,VC,CVC,funding continuum",
        "key_researchers": '["Josh Lerner","Ramana Nanda","Andrew Metrick"]',
        "key_works": '["Venture Capital and Private Equity (2011)","Financing Innovation (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_532",
        "name_en": "Policy Experimentation and Social Labs",
        "name_ja": "政策実験とソーシャルラボ",
        "definition": "社会課題への革新的解決策を実験・プロトタイプ・スケールアップするためのソーシャルラボ・政策ラボ・ガバメント・イノベーションラボの組織設計と実践を分析する研究領域であり、デンマーク・マインドラボ（MindLab）・フィンランド・テクノロジーエージェンシー（Sitra）・英国・ネスタが先行モデルとして知られる。失敗許容文化・共創手法・プロトタイプの政策実装連鎖・評価方法が主要な研究テーマとして蓄積されている。",
        "impact_summary": "政府機関の革新能力を内部から強化し、市民・専門家との共創を通じた政策イノベーションのプロトタイピングと拡散を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2001,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "experimentation,co-creation",
        "keywords_ja": "ソーシャルラボ,MindLab,政策実験,プロトタイピング",
        "keywords_en": "social lab,MindLab,policy experiment,prototyping",
        "key_researchers": '["Zaid Hassan","Peter Senge","Sitra Finland"]',
        "key_works": '["The Social Labs Revolution (2014)","Government Innovation Labs (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_533",
        "name_en": "Big Data for Science Policy",
        "name_ja": "科学政策のためのビッグデータ",
        "definition": "研究論文・特許・助成金データベース・科学者プロファイル・引用ネットワークなどの大規模データを統合分析し、科学政策立案のための知見を抽出するビッグデータ・アプローチであり、Microsoft Academic Graph・OpenAlex・NIH ExPORTERなどのオープンデータ基盤が研究プラットフォームとして整備されている。研究フロンティアの自動検出・科学者のキャリアパターン分析・政策介入の準実験的評価がビッグデータ科学政策の主要な分析テーマとして蓄積されている。",
        "impact_summary": "大規模な科学活動データの分析を通じて従来は不可能だった科学政策の実証的エビデンス生成を実現し、証拠に基づく研究資源配分の精度を大幅に向上させている。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "エビデンスベース政策論",
        "era_start": 2012,
        "innovation_type": "measurement",
        "cognitive_mechanism": "big-data,evidence",
        "keywords_ja": "ビッグデータ,OpenAlex,科学政策分析,大規模データ",
        "keywords_en": "big data,OpenAlex,science policy analytics,large-scale data",
        "key_researchers": '["Dashun Wang","James Evans","Maximilian Maier"]',
        "key_works": '["Bias-Corrected Methods for Large Data (2020)","The Science of Science (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_534",
        "name_en": "Deep Learning in Patent Analysis",
        "name_ja": "特許分析への深層学習の適用",
        "definition": "自然言語処理・グラフニューラルネットワーク・トランスフォーマーモデルなどの深層学習技術を特許テキスト分析・分類・類似特許検索・先行技術調査・侵害リスク評価に適用する研究・政策領域であり、PatentBERT・Claims2Terms・特許GPTなどのモデルが開発されている。AI支援特許審査による審査効率化・企業の特許ポートフォリオ管理の自動化・R&D競合分析の高速化が政策・産業応用として実用化されつつある。",
        "impact_summary": "AIによる特許分析の自動化・高精度化を通じて知財情報の活用障壁を低減し、特許庁審査効率と企業の知財戦略立案精度を同時に向上させている。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 2018,
        "innovation_type": "measurement",
        "cognitive_mechanism": "AI,deep-learning",
        "keywords_ja": "特許AI,深層学習,PatentBERT,自動分類",
        "keywords_en": "patent AI,deep learning,PatentBERT,automated classification",
        "key_researchers": '["Lee Joonhwan","Park Shinhyun","USPTO AI Task Force"]',
        "key_works": '["PatentBERT (2019)","AI in Patent Analysis (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_535",
        "name_en": "Sustainability Measurement Framework",
        "name_ja": "持続可能性測定フレームワーク",
        "definition": "経済・社会・環境の三側面を統合的に評価する持続可能性測定の方法論的枠組みであり、GNHインデックス・サステナブル発展指数・包括的富・環境調整済GDP（EDP）・Planetary Boundaries指標が代表的な測定システムとして開発されている。OECDのWell-being Framework・国連のBeyond GDP議論が政策統合の主要な国際的枠組みを提供しており、GDPを超えた豊かさの指標へのパラダイム転換がイノベーション政策評価にも影響を与えている。",
        "impact_summary": "GDP一元的評価を超えた多次元の豊かさと持続可能性を測定し、イノベーション政策の目標を経済成長だけでなく社会・環境価値の実現へと拡張している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 2008,
        "innovation_type": "measurement",
        "cognitive_mechanism": "composite-indicators,sustainability",
        "keywords_ja": "持続可能性測定,Beyond GDP,包括的富,Well-being",
        "keywords_en": "sustainability measurement,Beyond GDP,inclusive wealth,well-being",
        "key_researchers": '["Joseph Stiglitz","Amartya Sen","Jean-Paul Fitoussi"]',
        "key_works": '["Mismeasuring Our Lives (2010)","OECD Well-being Framework (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_536",
        "name_en": "Digital Twins in R&D Management",
        "name_ja": "R&D管理へのデジタルツインの適用",
        "definition": "研究開発プロジェクト・実験室・研究機関のデジタル複製を活用して実験のシミュレーション・リソース最適化・成果予測を行うR&D管理へのデジタルツイン応用の研究領域であり、バーチャルラボ・計算実験・AIアシスト研究設計が具体的な応用として発展している。製薬R&D（シリコントライアル）・材料探索・化学合成の計算的加速が特に進んでおり、R&D投資効率の大幅な向上が期待されている。研究データの倫理的活用と計算インフラへのアクセス格差が課題として認識されている。",
        "impact_summary": "デジタルシミュレーションによりR&Dの実験コストと時間を削減し、イノベーションサイクルの大幅な加速と公的R&D投資の効率的活用を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 2020,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "simulation,digital-twin",
        "keywords_ja": "デジタルツインR&D,バーチャルラボ,シリコントライアル,計算実験",
        "keywords_en": "digital twin R&D,virtual lab,silicon trial,computational experiment",
        "key_researchers": '["Alán Aspuru-Guzik","Markus Buehler","Teodoro Laino"]',
        "key_works": '["Molecular Design with AI (2020)","Digital Laboratory (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_537",
        "name_en": "Technology Policy Coherence Assessment",
        "name_ja": "技術政策一貫性評価",
        "definition": "複数省庁・政府レベルにわたる技術政策の一貫性（水平的・垂直的・時間的）を体系的に評価するための方法論であり、政策目標・手段・組織・資源の整合性を多軸で評価するスコアカードやマッピング手法が開発されている。EU技術政策一貫性フレームワーク・OECD STI政策整合性評価が代表的な国際的評価ツールとして機能しており、政策一貫性の欠如が生み出す政策コストの定量化が研究課題となっている。",
        "impact_summary": "技術政策の横断的一貫性を評価・確保することで政策の相殺・重複・矛盾を排除し、イノベーション・システムへの統合的な政策効果を最大化している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2008,
        "innovation_type": "measurement,governance",
        "cognitive_mechanism": "coherence-evaluation,alignment",
        "keywords_ja": "政策一貫性評価,水平的整合,縦断的整合,STI政策評価",
        "keywords_en": "policy coherence assessment,horizontal alignment,vertical alignment,STI policy evaluation",
        "key_researchers": '["Stefan Kuhlmann","Dirk Meissner","Jan Fagerberg"]',
        "key_works": '["STI Policy Coherence (2010)","Technology Policy Assessment (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_538",
        "name_en": "Pandemic Preparedness Innovation Policy",
        "name_ja": "パンデミック備えのイノベーション政策",
        "definition": "感染症パンデミックへの備えとして医薬品・診断技術・ワクチン・医療機器のイノベーション体制を事前に整備するための政策枠組みであり、CEPI（感染症流行対策イノベーション連合）・BARDA（生物医学先端研究開発局）・欧州HERA（健康緊急事態準備対応局）が代表的な政策機関として機能している。COVID-19パンデミックでのmRNAワクチン開発・抗ウイルス薬の緊急承認・サーベイランス強化がパンデミック・イノベーション政策の新たな基準を設定している。",
        "impact_summary": "次のパンデミックへの先制的な医療技術イノベーション投資を確保し、COVID-19から学んだ教訓を制度化することで人類の感染症対応能力を強化している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2017,
        "innovation_type": "policy,governance",
        "cognitive_mechanism": "preparedness,anticipatory",
        "keywords_ja": "パンデミック備え,CEPI,BARDA,HERA",
        "keywords_en": "pandemic preparedness,CEPI,BARDA,HERA",
        "key_researchers": '["Richard Hatchett","John Nkengasong","Nikolai Petrovsky"]',
        "key_works": '["CEPI Strategic Plan (2017)","COVID-19 Vaccine Policy (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_539",
        "name_en": "Economic Complexity and Innovation",
        "name_ja": "経済複雑度とイノベーション",
        "definition": "Hausmann・Hidalgo（2009）が開発した経済複雑度指数（ECI）は各国の輸出バスケットの多様性・複雑度を定量化し、内在する知識集積の代理変数として機能する。複雑度の高い経済は多様で洗練された知識を持ち、長期的な経済成長・イノベーション・所得向上と相関することが実証されており、産業政策・教育政策・イノベーション政策の目標設定に複雑度向上という指針を提供している。製品空間（product space）の分析により次に参入可能な産業の特定も可能となっている。",
        "impact_summary": "経済の知識集積と複雑度を定量化し、産業多様化・技術高度化の方向性を特定することで長期的なイノベーション戦略と産業政策設計を支援している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 2009,
        "innovation_type": "measurement",
        "cognitive_mechanism": "complexity,product-space",
        "keywords_ja": "経済複雑度,ECI,製品空間,多様化戦略",
        "keywords_en": "economic complexity,ECI,product space,diversification strategy",
        "key_researchers": '["Ricardo Hausmann","Cesar Hidalgo","Sebastian Bustos"]',
        "key_works": '["Atlas of Economic Complexity (2009)","The Building Blocks of Economic Complexity (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_540",
        "name_en": "Public Engagement in STI Governance",
        "name_ja": "STIガバナンスへの市民参与",
        "definition": "科学技術ガバナンスにおいて市民・ステークホルダー・一般公衆が意思決定に参加するメカニズムの設計と評価を研究する領域であり、市民審査会・コンセンサス会議・参加型テクノロジー・アセスメント・e-democracy・国民技術対話が代表的な実践として研究されている。Arnstein（1969）の「参加のはしご」が参加の深度を分類する古典的理論として引用され続けている。科学と民主主義の接合点でのエンゲージメントの質・正当性・アウトカムへの影響が継続的な研究課題となっている。",
        "impact_summary": "STIガバナンスへの市民参与の深度と質を高め、科学技術の社会的方向付けの民主的正統性と市民の科学技術ガバナンスへの信頼を強化している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1999,
        "innovation_type": "governance",
        "cognitive_mechanism": "participation,deliberation",
        "keywords_ja": "市民参与,コンセンサス会議,参加のはしご,STI民主主義",
        "keywords_en": "public engagement,consensus conference,ladder of participation,STI democracy",
        "key_researchers": '["Brian Wynne","Alan Irwin","Sherry Arnstein"]',
        "key_works": '["Misunderstanding Science? (1996)","A Ladder of Citizen Participation (1969)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_541",
        "name_en": "Circular Bioeconomy Policy",
        "name_ja": "循環バイオエコノミー政策",
        "definition": "バイオエコノミーと循環経済の原則を統合し、生物由来資源の循環的活用（廃棄物のバイオ変換・カスケード利用・バイオリファイナリー等）を政策的に促進する枠組みであり、EU循環バイオエコノミー行動計画・Bioeconomy Alliance・各国バイオマス・カスケード政策が代表的な制度として知られる。農業廃棄物・食品廃棄物・林業残渣を原料としたバイオプラスチック・バイオ燃料・バイオ素材の政策的誘発が具体的な実施課題となっている。",
        "impact_summary": "生物由来資源の廃棄ゼロと最大価値抽出を実現する循環バイオエコノミーを政策的に促進し、化石資源代替・農村振興・脱炭素化を同時に達成している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2018,
        "innovation_type": "policy",
        "cognitive_mechanism": "sustainability,circular",
        "keywords_ja": "循環バイオエコノミー,バイオリファイナリー,農業廃棄物,カスケード",
        "keywords_en": "circular bioeconomy,biorefinery,agricultural waste,cascade",
        "key_researchers": '["Dieter Schorling","Bo van Bavel","Petri Peltonen"]',
        "key_works": '["Circular Bioeconomy Strategy (2018)","Bioeconomy Alliance (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_542",
        "name_en": "IP Pledges and Innovation Commons",
        "name_ja": "知財プレッジとイノベーション・コモンズ",
        "definition": "企業・機関が自社の特許・知的財産を特定条件下で無料または低廉に提供することを公約するIP誓約（IP Pledge）と、知識資源を共有コモンズとして開放するオープンイノベーション実践の政策的含意を研究する領域であり、OIN（Open Invention Network）・COVID-19特許プール・Tesla特許開放・WIPO研究開発プールが代表的な事例として知られる。IP誓約が競合他社のイノベーション・競争・エコシステム形成に与える影響が研究されている。",
        "impact_summary": "知財の一定条件での開放によりイノベーション・エコシステムの相互運用性と共進化を促進し、単独保護以上の価値を創出するオープン知財戦略の有効性を実証している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2003,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "openness,commons",
        "keywords_ja": "IP誓約,特許プール,OIN,オープン知財",
        "keywords_en": "IP pledge,patent pool,OIN,open IP",
        "key_researchers": '["Joachim Henkel","Stephanie Siemer","Axel Ockenfels"]',
        "key_works": '["IP Pledges and Innovation (2010)","Open COVID Pledge (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_543",
        "name_en": "Decarbonization Technologies Policy",
        "name_ja": "脱炭素化技術政策",
        "definition": "CCS（炭素回収・貯留）・水素・次世代原子力（SMR）・産業電化・航空燃料脱炭素化などの脱炭素技術の研究開発・実証・普及を促進するための政策枠組みであり、カーボンゼロへの移行に不可欠だが現時点で未成熟または高コストな技術への戦略的公的投資が中心的な政策課題となっている。EU Innovation Fund・米国IRA脱炭素インセンティブ・日本GX推進法が代表的な政策基盤として機能している。技術的成熟度（TRL）に応じた段階的支援と炭素価格との組み合わせが最適政策ミックスとして研究されている。",
        "impact_summary": "市場では自律的に発展しにくい脱炭素化に必要な先端技術への公的投資を確保し、ネットゼロ目標達成に向けた技術的フロンティアの開拓を政策的に加速している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "sustainability,technology-push",
        "keywords_ja": "脱炭素技術,CCS,水素政策,SMR,GX",
        "keywords_en": "decarbonization technology,CCS,hydrogen policy,SMR,GX",
        "key_researchers": '["Howard Herzog","Niall Mac Dowell","David Sandalow"]',
        "key_works": '["Carbon Capture and Storage (2018)","Innovation for Net Zero (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_544",
        "name_en": "Pandemic-Accelerated Digital Innovation",
        "name_ja": "パンデミック加速デジタルイノベーション",
        "definition": "COVID-19パンデミックが引き起こした急速なデジタル化・遠隔化・自動化への移行がイノベーション・エコシステムに与えた影響と、政策的対応を分析する研究領域であり、テレワーク普及・遠隔医療・eコマース加速・デジタル政府の急進展が自然実験として研究されている。パンデミックがイノベーションの「ダーウィン的選別」を加速させたとする仮説・デジタル格差の拡大・パンデミック後の制度的定着（institutionalization）が主要な研究テーマとして浮上している。",
        "impact_summary": "パンデミックが触媒となった急進的なデジタル転換の経路と条件を解明し、危機起因のイノベーション加速を持続的な構造変化として定着させる政策設計に貢献している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2020,
        "innovation_type": "measurement,policy",
        "cognitive_mechanism": "crisis-acceleration,digital",
        "keywords_ja": "コロナ,デジタル加速,遠隔医療,制度化",
        "keywords_en": "COVID,digital acceleration,telemedicine,institutionalization",
        "key_researchers": '["Nicholas Bloom","Raffaella Sadun","Jan Rivkin"]',
        "key_works": '["Working from Home Around the World (2020)","COVID-19 and Innovation (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_545",
        "name_en": "AI Safety Policy Framework",
        "name_ja": "AI安全政策フレームワーク",
        "definition": "高度AI・汎用AI（AGI）の安全で信頼性の高い開発・展開を確保するための政策・規制・技術的安全保証の体系的枠組みであり、EU AI法（リスク分類・禁止AI・高リスクAIの要件）・米国AIセーフティフレームワーク・英国AI安全研究所（DSIT/AISI）・AI安全国際ネットワークが主要な政策制度として整備されている。AI安全評価（evals）・レッドチーミング・インシデント報告義務・フロンティアAI能力モニタリングが技術的ガバナンスの核心的手段として研究されている。",
        "impact_summary": "高度AI技術の変革的リスクを先制的に管理する国際的・国内的政策枠組みを構築し、AIの便益を最大化しながら壊滅的リスクを防止するセーフガードを確立している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2023,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "AI-safety,risk-management",
        "keywords_ja": "AI安全政策,EU AI法,AISI,フロンティアAI",
        "keywords_en": "AI safety policy,EU AI Act,AISI,frontier AI",
        "key_researchers": '["UK DSIT","US NIST","Yoshua Bengio"]',
        "key_works": '["EU AI Act (2024)","International AI Safety Report (2024)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_546",
        "name_en": "National Data Strategy",
        "name_ja": "国家データ戦略",
        "definition": "データを国家の重要資源として捉え、その収集・管理・活用・保護・共有に関する包括的な国家戦略を策定・実施する政策枠組みであり、英国国家データ戦略（2020）・EUデータ戦略（2020）・日本デジタル社会形成基本法（2021）が代表的な国家戦略として知られる。データ経済の成長支援・公共データの活用・プライバシー保護・データ主権の確保・AI開発への基盤整備が戦略の主要な柱として設定されている。データ・スペースの構築とデータ・ガバナンスの国際的調整が最前線の政策課題となっている。",
        "impact_summary": "データを国家の戦略的資源として体系的に管理・活用することで、データ主導型イノベーションの規模的拡大と国際データ経済での競争優位確保を実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2020,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "data-governance,strategic-planning",
        "keywords_ja": "国家データ戦略,データスペース,データ主権,EU Data Strategy",
        "keywords_en": "national data strategy,data spaces,data sovereignty,EU Data Strategy",
        "key_researchers": '["European Commission","UK DCMS","Stefaan Verhulst"]',
        "key_works": '["UK National Data Strategy (2020)","EU Data Strategy (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_547",
        "name_en": "Collaborative Economy Governance",
        "name_ja": "協働経済のガバナンス",
        "definition": "Airbnb・Uber・Freelancer.com等のプラットフォームを通じた資産・スキルの共有・マッチングに基づく「協働経済（collaborative/sharing economy）」の急成長に伴う労働保護・競争法・消費者保護・税制等の政策・規制課題を分析する研究領域であり、欧州委員会の協働経済ガイダンス（2016）・各国の法的地位の明確化が代表的な政策対応として実施されている。ギグワーカーの労働権保護とイノベーション促進の均衡が特に注目される政策課題となっている。",
        "impact_summary": "プラットフォーム媒介の新たな経済形態がもたらす規制の空白を埋め、労働者保護・消費者安全・競争公正性とデジタル・イノベーションの共存を政策的に実現している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "政策学",
        "era_start": 2014,
        "innovation_type": "governance,policy",
        "cognitive_mechanism": "platform-economy,regulation",
        "keywords_ja": "協働経済,ギグワーカー,シェアリングエコノミー,プラットフォーム規制",
        "keywords_en": "collaborative economy,gig worker,sharing economy,platform regulation",
        "key_researchers": '["Diane Mulcahy","Vili Lehdonvirta","Alex Rosenblat"]',
        "key_works": '["Collaborative Economy (2016)","Uberland (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_548",
        "name_en": "Research Ethics Governance",
        "name_ja": "研究倫理ガバナンス",
        "definition": "研究活動における倫理的原則（研究参加者の保護・インフォームドコンセント・利益相反管理・研究不正防止・脆弱集団への配慮等）の制度的遵守を確保するガバナンス枠組みであり、ニュルンベルク綱領（1947）・ベルモントレポート（1979）・ヘルシンキ宣言が倫理原則の歴史的基盤を提供している。倫理審査委員会（IRB/IEC）・利益相反ポリシー・研究完全性教育プログラムが現代的な制度的ツールとして機能している。AI・ゲノム・ビッグデータ研究での新たな倫理課題が制度更新を促している。",
        "impact_summary": "研究参加者の権利保護と研究の社会的信頼性を確保するための倫理ガバナンスを制度化し、研究の倫理的完全性とイノベーション促進のバランスを維持している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 1979,
        "innovation_type": "governance",
        "cognitive_mechanism": "ethics,institutional-design",
        "keywords_ja": "研究倫理,IRB,ヘルシンキ宣言,利益相反",
        "keywords_en": "research ethics,IRB,Helsinki Declaration,conflict of interest",
        "key_researchers": '["Robert Levine","Ezekiel Emanuel","Onora ONeill"]',
        "key_works": '["The Belmont Report (1979)","Ethics in Clinical Research (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_549",
        "name_en": "Social Network Analysis for Innovation",
        "name_ja": "イノベーションのためのソーシャルネットワーク分析",
        "definition": "個人・組織間のソーシャルネットワーク構造がイノベーション創出・知識共有・技術普及に与える影響を社会ネットワーク分析（SNA）手法で解析する研究領域であり、構造的空隙（structural holes）・仲介者（broker）・情報拡散の強い/弱い紐帯がイノベーション能力に与える影響がBurt（1992）・Granovetter（1973）の理論を基盤として実証されている。スタートアップ・エコシステムの接続構造・産学連携ネットワークの分析・政策立案者とイノベーターの知識インタラクションが応用テーマとして広がっている。",
        "impact_summary": "イノベーション主体間のネットワーク構造が知識伝播とイノベーション創出に与える影響を定量化し、産学官のネットワーク設計と仲介機能強化の政策根拠を提供している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "イノベーション計量学",
        "era_start": 1992,
        "innovation_type": "measurement",
        "cognitive_mechanism": "network-analysis,quantification",
        "keywords_ja": "SNA,構造的空隙,弱い紐帯,イノベーション仲介",
        "keywords_en": "SNA,structural holes,weak ties,innovation brokering",
        "key_researchers": '["Ronald Burt","Mark Granovetter","David Krackhardt"]',
        "key_works": '["Structural Holes (1992)","The Strength of Weak Ties (1973)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
    {
        "id": "inno_pol_550",
        "name_en": "Supply Chain Resilience Policy",
        "name_ja": "サプライチェーン強靭化政策",
        "definition": "半導体・医薬品・希少金属・食料など戦略的重要物資のサプライチェーンの多様化・国内化・在庫強化・代替技術開発を促進する政策枠組みであり、COVID-19パンデミック・地政学的緊張の高まりとともに供給リスク管理が安全保障・産業政策の最前線課題となっている。米国CHIPS法・EU重要原材料法・日本経済安全保障推進法がサプライチェーン強靭化政策の代表的法制として実施されており、リショアリング・フレンドショアリング・在庫多様化が政策ツールとして研究されている。",
        "impact_summary": "戦略的物資のサプライチェーン脆弱性を特定・管理し、経済安全保障とイノベーション供給の持続可能性を政策的に確保している。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "科学技術政策論",
        "era_start": 2020,
        "innovation_type": "policy,governance",
        "cognitive_mechanism": "supply-chain,resilience",
        "keywords_ja": "サプライチェーン強靭化,CHIPS法,重要原材料,リショアリング",
        "keywords_en": "supply chain resilience,CHIPS Act,critical raw materials,reshoring",
        "key_researchers": '["Yossi Sheffi","Hau Lee","David Simchi-Levi"]',
        "key_works": '["The Resilient Enterprise (2005)","Supply Chain Resilience Policy (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now,
    },
]

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

for e in entries:
    cursor.execute("""
        INSERT OR REPLACE INTO innovation_theory
        (id, name_en, name_ja, definition, impact_summary, subfield, school_of_thought,
         era_start, innovation_type, cognitive_mechanism, keywords_ja, keywords_en,
         key_researchers, key_works, status, source_reliability, data_completeness,
         created_at, updated_at)
        VALUES (:id, :name_en, :name_ja, :definition, :impact_summary, :subfield,
                :school_of_thought, :era_start, :innovation_type, :cognitive_mechanism,
                :keywords_ja, :keywords_en, :key_researchers, :key_works, :status,
                :source_reliability, :data_completeness, :created_at, :updated_at)
    """, e)

conn.commit()
conn.close()
print(f"Inserted {len(entries)} entries")
