#!/usr/bin/env python3
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
    ("inno_digi_201","Appleプラットフォーム戦略とエコシステム支配","Apple Platform Strategy and Ecosystem Control","AppleはiOS/macOSを中核とした垂直統合型エコシステムを構築し、ハードウェア・OS・アプリストア・決済・コンテンツを一体管理する。App Store手数料（30%）・プライバシー規制（ATT）・独自チップ（Apple Silicon）の三本柱が競合参入障壁を形成。Porter（1985）の垂直統合論とEisenmann（2011）のプラットフォームエンベロープメント理論が分析枠組みとなる。","platform_digital_innovation","プラットフォーム競争戦略",2007,None,"meso","ICT産業","独自エコシステム管理","競合プラットフォームに対抗する際","Appleのエコシステム支配力はどのような参入障壁を生み出すか","オープンプラットフォーム戦略","Apple,iOS,App Store,垂直統合,エコシステム","Apple,iOS,App Store,vertical integration,ecosystem","active","secondary",80,'["Tim Cook", "Steve Jobs"]','["Porter 1985", "Eisenmann 2011"]',"市場シェア・App Store収益・開発者数"),
    ("inno_digi_202","Google検索広告ビジネスモデルの経済学","Economics of Google Search Advertising","Googleの検索広告はキーワードオークションに基づく二面市場であり、広告主はClicked-Per-Click(CPC)モデルで入札する。Varian（2007）がVickrey-Clarke-Groves(VCG)メカニズムに近いGSPオークションを分析し、この仕組みがAdWordsの収益最大化と広告主余剰確保を同時達成することを示した。検索エンジン市場の90%超シェアがネットワーク効果と切り替えコストによって維持される構造を欧州委員会が問題視し反トラスト調査が進行している。","platform_digital_innovation","デジタル広告経済",2000,None,"meso","デジタル広告","キーワードオークション分析","デジタル広告収益モデルを設計する際","Googleの広告オークションはどのような経済メカニズムで機能するか","伝統的広告モデル","Google,検索広告,オークション,CPC,AdWords","Google,search advertising,auction,CPC,AdWords","active","secondary",80,'["Hal Varian", "Eric Schmidt"]','["Varian 2007 AdWords"]',"広告単価・収益・市場シェア"),
    ("inno_digi_203","Amazon AWSクラウドサービスとプラットフォーム転換","Amazon AWS Cloud Services and Platform Shift","AmazonはECのインフラ内部化過程でAWSを開発し、2006年に外部提供を開始した。IaaS(インフラ)→PaaS(プラットフォーム)→SaaS(ソフトウェア)の三層構造でクラウド市場を形成。Brynjolfsson & McAfee（2014）はAWSが中小企業のIT投資コストを劇的に削減し技術民主化をもたらしたと評価する。2024年時点でAWS世界市場シェア32%を維持し、MicrosoftAzure・GCPとの三極寡占が続く。","platform_digital_innovation","クラウドコンピューティング",2006,None,"meso","クラウド産業","クラウド移行・スケーリング","ITインフラをクラウド化する際","AWSはどのようにしてクラウド市場を創造したか","オンプレミスIT","AWS,クラウド,IaaS,PaaS,Amazon","AWS,cloud,IaaS,PaaS,Amazon","active","secondary",85,'["Andy Jassy", "Werner Vogels"]','["Brynjolfsson McAfee 2014"]',"市場シェア・収益・顧客数"),
    ("inno_digi_204","Metaソーシャルグラフとネットワーク効果","Meta Social Graph and Network Effects","Facebookが構築したソーシャルグラフ（実名・関係性データ）はMetaプラットフォーム群（Instagram、WhatsApp）の競争優位の源泉。Metcalfe則（価値∝n²）がソーシャルネットワークの規模優位を説明し、Zuckerberg（2004以降）の成長戦略は接続性最大化を軸とした。プライバシー・偽情報・民主主義への影響をめぐる規制議論が各国で進行し、Haugen内部告発（2021）がアルゴリズム設計の倫理問題を顕在化させた。","platform_digital_innovation","ソーシャルメディア経済",2004,None,"meso","ソーシャルメディア","ソーシャルネットワーク分析","ソーシャルプラットフォームの戦略を分析する際","Metaのソーシャルグラフはどのような競争障壁を生むか","分散型SNS","Meta,Facebook,ソーシャルグラフ,ネットワーク効果","Meta,Facebook,social graph,network effects","active","secondary",80,'["Mark Zuckerberg", "Sheryl Sandberg"]','["Metcalfe Law", "Haugen 2021"]',"月間アクティブユーザー・広告収益"),
    ("inno_digi_205","Alibabaプラットフォームエコシステムと中国デジタル経済","Alibaba Platform Ecosystem and Chinese Digital Economy","Alibabaはタオバオ・天猫・アリペイ・アリクラウドを統合したスーパープラットフォームを形成し、中国EC取引の約60%を媒介する。Yoffie & Cusumano（2015）のプラットフォーム競争論が分析枠組みを提供。独自決済（アリペイ）・物流（菜鳥）・クラウド（阿里雲）のフルスタック統合が差別化要因。中国政府の規制強化（2020年以降）がプラットフォーム支配力を制約した事例として各国規制論議に影響を与えている。","platform_digital_innovation","デジタルプラットフォーム経済",2003,None,"meso","EC・デジタル金融","中国市場デジタル化分析","中国デジタル経済を分析する際","Alibabaはどのようにスーパープラットフォームを構築したか","西側EC モデル","Alibaba,アリペイ,タオバオ,天猫,中国EC","Alibaba,Alipay,Taobao,Tmall,China EC","active","secondary",80,'["Jack Ma", "Daniel Zhang"]','["Yoffie Cusumano 2015"]',"GMV・市場シェア・ユーザー数"),
    ("inno_digi_206","ByteDanceアルゴリズムレコメンデーションとコンテンツ経済","ByteDance Algorithm Recommendation and Content Economy","TikTok親会社ByteDanceはFor You Page(FYP)アルゴリズムで個人化コンテンツ推薦を実現し、従来のソーシャルグラフではなく行動データに基づくレコメンデーションを中核とする。Zhang Yiming（2012）設立以来、AI-first戦略で急成長。10億MAUを超えるTikTokは若年層の時間シェアをめぐりYouTube・Instagramと競合。米国・EUの安全保障・プライバシー懸念に基づく規制リスクが事業継続に影響している。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2012,None,"meso","コンテンツ・エンタメ","ショート動画プラットフォーム分析","アルゴリズム推薦型プラットフォームを分析する際","ByteDanceのアルゴリズムはどのようにエンゲージメントを最大化するか","ソーシャルグラフ型SNS","ByteDance,TikTok,アルゴリズム,レコメンデーション","ByteDance,TikTok,algorithm,recommendation","active","secondary",78,'["Zhang Yiming"]','["FYP algorithm analysis 2022"]',"MAU・滞在時間・コンテンツ視聴数"),
    ("inno_digi_207","クラウドコンピューティングの経済学と規模の経済","Economics of Cloud Computing and Economies of Scale","クラウドコンピューティングはサーバー・ストレージ・ネットワークのリソースを仮想化・共有することで固定費を変動費に転換する。Armbrust et al.（2010）はクラウドの10大利点として弾力的スケーリング・コスト削減・地理的分散等を挙げた。規模の経済と密度の経済（economies of density）が大手CSPの競争優位を支え、スイッチングコストとデータ移行障壁が顧客ロックインを生む。","platform_digital_innovation","クラウドコンピューティング",2009,None,"meso","IT産業全般","クラウド移行の経済性評価","クラウド投資判断を行う際","クラウドの経済的優位性はどのような条件で実現されるか","オンプレミス","クラウド,規模の経済,弾力性,仮想化","cloud,economies of scale,elasticity,virtualization","active","primary",82,'["Michael Armbrust", "Matei Zaharia"]','["Armbrust et al. 2010 EECS"]',"コスト削減率・TCO・利用率"),
    ("inno_digi_208","AIプラットフォーム競争とGPUエコノミクス","AI Platform Competition and GPU Economics","生成AI時代の競争軸はGPUクラスターの計算資源優位性にある。NvidiaのCUDAエコシステム（2006年以降）が事実上のAIインフラ標準となり、H100/B100等の需要急増（2022年以降）が半導体サプライチェーンを変容させた。Klinger et al.（2023）はAI能力とモデル規模の対数線形関係（スケーリング則）がGPU需要を牽引することを示した。ハイパースケーラー（Google TPU・Amazon Trainium・Microsoft・Meta）の独自AI チップ開発がNvidia依存からの脱却を図る。","platform_digital_innovation","AI半導体・計算資源",2020,None,"macro","AI産業","AI競争力の計算資源分析","AIプラットフォーム戦略を分析する際","GPUエコシステムはAI競争にどのような影響を与えるか","CPU汎用計算","GPU,AI,CUDA,Nvidia,スケーリング則","GPU,AI,CUDA,Nvidia,scaling laws","active","secondary",80,'["Jensen Huang", "Jared Kaplan"]','["Klinger et al. 2023", "Kaplan et al. 2020 scaling laws"]',"GPU出荷数・AI市場規模"),
    ("inno_digi_209","IoTプラットフォームとエッジコンピューティング","IoT Platform and Edge Computing","IoT(Internet of Things)は数十億のセンサー・デバイスをネットワーク化し、製造・農業・医療・インフラ等のデータ収集基盤を形成する。Shi et al.（2016）はエッジコンピューティング（デバイス近傍での処理）がクラウド集中処理の遅延・帯域問題を解決すると論じた。PTC・Siemens・GEのIndustrialIoTプラットフォームが製造業のデジタルツインを実現し、スマートシティ・コネクテッドカー等の基盤となる。","platform_digital_innovation","IoT・エッジコンピューティング",2015,None,"meso","製造・インフラ","IoTシステム設計","産業IoT導入を検討する際","IoTプラットフォームとエッジ処理はどのように役割分担するか","クラウド集中型","IoT,エッジコンピューティング,センサー,デジタルツイン","IoT,edge computing,sensor,digital twin","active","secondary",78,'["Weisong Shi", "Flavio Bonomi"]','["Shi et al. 2016 edge computing"]',"接続デバイス数・処理遅延"),
    ("inno_digi_210","5Gネットワーク経済学と産業変革","5G Network Economics and Industrial Transformation","5G(第5世代移動通信)は高速・低遅延・大規模接続の三特性により自動運転・遠隔医療・スマート製造等の実現基盤となる。Oughton et al.（2019）は5Gの経済効果を産業×地域ごとに定量化する枠組みを提案。周波数帯（ミリ波vs.サブ6GHz）・基地局密度・国際標準化(3GPP)・安全保障リスク（Huawei問題）が政策議論の焦点となっている。","platform_digital_innovation","モバイル通信・5G",2019,None,"macro","通信・製造","5G導入の経済影響分析","5G政策・投資判断を行う際","5Gはどの産業に最大の変革をもたらすか","4G LTE","5G,モバイル通信,低遅延,スマート製造","5G,mobile communication,low latency,smart manufacturing","active","secondary",76,'["Edward Oughton", "Matti Latva-aho"]','["Oughton et al. 2019"]',"5Gカバレッジ・経済効果額"),
    ("inno_digi_211","AR/VRプラットフォームと空間コンピューティング","AR/VR Platform and Spatial Computing","拡張現実(AR)・仮想現実(VR)は物理空間とデジタル情報を融合する空間コンピューティングを実現する。Milgram & Kishino（1994）のリアリティ-バーチャリティ連続体が概念的基礎。Meta Quest・Apple Vision Pro・Microsoft HoloLensがプラットフォーム競争を展開。Dincelli & Yayla（2022）はARがサプライチェーン・医療・教育へのインパクトを系統的にレビューし、没入型インターフェースが生産性・学習効果を向上させることを示した。","platform_digital_innovation","AR・VR・空間コンピューティング",2016,None,"meso","エンタメ・製造・医療","没入型インターフェース設計","AR/VRプラットフォーム戦略を分析する際","空間コンピューティングはどのような産業変革をもたらすか","平面スクリーン","AR,VR,空間コンピューティング,没入型","AR,VR,spatial computing,immersive","active","secondary",75,'["Paul Milgram", "Mark Zuckerberg"]','["Milgram Kishino 1994", "Dincelli Yayla 2022"]',"デバイス出荷数・コンテンツ市場規模"),
    ("inno_digi_212","ブロックチェーン技術の制度経済学","Institutional Economics of Blockchain Technology","ブロックチェーンは分散台帳技術（DLT）により信頼の第三者介在を不要にし、スマートコントラクトで契約自動執行を実現する。Davidson et al.（2018）はブロックチェーンを「制度技術（institutional technology）」として位置付け、Williamsonの取引コスト理論を拡張した。ビットコイン・イーサリアム・エンタープライズブロックチェーン（Hyperledger）の分類が実装目的・ガバナンス設計と対応する。","platform_digital_innovation","ブロックチェーン・分散技術",2008,None,"meso","金融・サプライチェーン","ブロックチェーン導入の制度的分析","信頼機構のデジタル化を検討する際","ブロックチェーンはどのような取引コストを削減するか","中央集権型台帳","ブロックチェーン,DLT,スマートコントラクト,信頼","blockchain,DLT,smart contract,trust","active","primary",78,'["Simon Davidson", "Sinclair Davidson"]','["Davidson et al. 2018 JPE"]',"トランザクション数・採用企業数"),
    ("inno_digi_213","量子コンピューティングとイノベーション潜在力","Quantum Computing and Innovation Potential","量子コンピュータは量子ビット（qubit）の重ね合わせと量子もつれを利用し、古典コンピュータが指数時間要する問題を多項式時間で解く潜在力を持つ。Preskill（2018）が「量子超越性（quantum supremacy）」概念を提唱し、Google Sycamoreが2019年に実証した。創薬・材料科学・最適化・暗号解読への応用が期待され、IBM・Google・IonQ・Quantinuumが競争する。誤り訂正実用化が量子優位の商業化の主要障壁となっている。","platform_digital_innovation","量子コンピューティング",2019,None,"macro","創薬・材料・金融","量子技術の応用可能性評価","量子技術の産業影響を分析する際","量子コンピュータはどの分野で古典計算に対する優位性を発揮するか","古典コンピュータ","量子コンピュータ,量子超越性,qubit,創薬","quantum computing,quantum supremacy,qubit,drug discovery","active","secondary",75,'["John Preskill", "Hartmut Neven"]','["Preskill 2018", "Arute et al. 2019 Nature"]',"量子ビット数・エラー率"),
    ("inno_digi_214","生成AIの産業応用：コード生成","Generative AI Industrial Application: Code Generation","GitHub Copilot（2021）に代表される生成AIコード生成ツールはLLMを活用して開発者の生産性を向上させる。Peng et al.（2023）はCopilot使用によりタスク完了速度が55%向上したと実験的に示した。コードの品質・セキュリティリスク・知的財産権問題が主要な課題であり、Pearce et al.（2022）は生成AIコードのセキュリティ脆弱性を系統的に分析した。ソフトウェア開発職の変容とAI-human協働モデルへの移行が進行している。","platform_digital_innovation","生成AI応用",2021,None,"meso","ソフトウェア開発","AI支援コーディング導入","ソフトウェア開発生産性を改善する際","生成AIはソフトウェア開発プロセスをどう変容させるか","人手コーディング","生成AI,コード生成,Copilot,LLM,開発者生産性","generative AI,code generation,Copilot,LLM,developer productivity","active","primary",82,'["Albert Ziegler", "Sida Peng"]','["Peng et al. 2023", "Pearce et al. 2022"]',"生産性向上率・採用企業数"),
    ("inno_digi_215","生成AIの産業応用：クリエイティブ産業","Generative AI Industrial Application: Creative Industries","画像生成AI（Midjourney・DALL-E・Stable Diffusion）・音楽生成AI（Suno・Udio）・映像生成AI（Sora）はクリエイティブ産業のコスト構造と創造プロセスを変容させる。Epstein et al.（2023）はAI生成コンテンツが著作権・帰属・真正性の規範的問いを提起すると論じた。広告・ゲーム・映画・音楽業界での採用が加速し、クリエイターの役割がプロンプトエンジニアリングへシフトしている。","platform_digital_innovation","生成AI応用",2022,None,"meso","クリエイティブ産業","生成AIクリエイティブ活用","クリエイティブワークフローにAIを導入する際","生成AIはクリエイティブ産業の価値連鎖をどう再編するか","人手制作","生成AI,画像生成,音楽生成,クリエイティブ,著作権","generative AI,image generation,creative industries,copyright","active","primary",80,'["Robert Epstein", "Reid Southen"]','["Epstein et al. 2023"]',"市場規模・採用率・著作権訴訟件数"),
    ("inno_digi_216","生成AIの産業応用：医療・ライフサイエンス","Generative AI Industrial Application: Healthcare and Life Sciences","大規模言語モデル（LLM）は医療記録要約・診断支援・創薬候補生成に応用される。Singhal et al.（2023）のMed-PaLMはUSMLE医師国家試験で専門医レベルのスコアを達成した。AlphaFold2（Jumper et al. 2021）はタンパク質構造予測精度を飛躍的に向上させ、2億以上の構造データベースを公開した。FDA・欧州EMAのAI医療機器規制フレームワークの整備が産業化の条件となっている。","platform_digital_innovation","生成AI応用",2021,None,"meso","医療・製薬","AI医療診断・創薬支援","医療AIの導入可能性を評価する際","生成AIは医療価値連鎖のどの部分を変革するか","従来の診断アルゴリズム","生成AI,医療,LLM,AlphaFold,創薬","generative AI,healthcare,LLM,AlphaFold,drug discovery","active","primary",83,'["Karan Singhal", "John Jumper"]','["Singhal et al. 2023 Nature", "Jumper et al. 2021 Nature"]',"診断精度・創薬コスト削減"),
    ("inno_digi_217","生成AIの産業応用：教育・ナレッジワーク","Generative AI Industrial Application: Education and Knowledge Work","ChatGPT（2022年11月）の公開は教育・知識労働の実践を急速に変容させた。Mollick & Mollick（2023）はLLMを「billion-parameter tutor」として教育効果を検証し、一対一チュータリングのBlooms 2-sigma効果をAIが再現できる可能性を示した。学術不正・評価方法の変革・教師の役割再定義が政策・教育機関の主要課題となっている。","platform_digital_innovation","生成AI応用",2022,None,"meso","教育・知識産業","AI教育ツール導入","教育イノベーション戦略を検討する際","生成AIは知識習得・評価プロセスをどう変容させるか","従来型講義・テスト","生成AI,教育,LLM,ChatGPT,ナレッジワーク","generative AI,education,LLM,ChatGPT,knowledge work","active","primary",80,'["Ethan Mollick", "Lilach Mollick"]','["Mollick & Mollick 2023"]',"学習成果・採用機関数"),
    ("inno_digi_218","デジタルトランスフォーメーション(DX)の定義と測定","Definition and Measurement of Digital Transformation (DX)","DXはデジタル技術の組織全体への統合により事業モデル・プロセス・顧客体験を根本的に変革するプロセス。Vial（2019）は文献レビューから「デジタル変革の構造」を提示し、DX定義の多様性を整理した。McKinsey Global Institute（2021）はDX成熟度を5段階（デジタル対応→デジタル競争力→デジタルリーダー）で評価する。DX失敗率70%（MIT調査）の要因として変革マネジメント・人材・文化的障壁が指摘される。","platform_digital_innovation","デジタルトランスフォーメーション",2017,None,"meso","全産業","DX戦略・成熟度評価","DX推進計画を策定する際","DXはどのような条件で成功するか","漸進的デジタル化","DX,デジタル変革,成熟度,ビジネスモデル","DX,digital transformation,maturity,business model","active","secondary",80,'["Gregory Vial", "George Westerman"]','["Vial 2019 JSIS", "Westerman et al. 2014"]',"DX投資額・成熟度スコア"),
    ("inno_digi_219","DXの産業別適用：製造業のスマート工場","DX Industry Application: Smart Factory in Manufacturing","製造業のDXはサイバーフィジカルシステム（CPS）・デジタルツイン・ロボティクスを統合したスマート工場を実現する。Kagermann et al.（2013）はIndustrie4.0コンセプトを提唱し、ドイツ製造業の競争力維持のためのデジタル化戦略を示した。予知保全・品質管理AI・自律搬送ロボット（AMR）・デジタルスレッドが価値連鎖全体を変革する。日本の「Connected Industries」政策、中国「製造2025」との政策競争も分析される。","platform_digital_innovation","デジタルトランスフォーメーション",2013,None,"meso","製造業","スマート工場設計","製造DX戦略を立案する際","スマート工場はどのような生産性向上をもたらすか","従来型生産管理","DX,スマート工場,Industrie4.0,デジタルツイン","DX,smart factory,Industry 4.0,digital twin","active","secondary",82,'["Henning Kagermann", "Siegfried Russwurm"]','["Kagermann et al. 2013 acatech"]',"生産性・OEE・コスト削減"),
    ("inno_digi_220","DXの産業別適用：金融サービスのフィンテック","DX Industry Application: Fintech in Financial Services","金融サービスのDXはモバイル決済・ロボアドバイザー・オープンバンキング・BNPLを通じて伝統的銀行業を再構築する。Philippon（2016）は金融仲介コストが100年間変化せず、フィンテックが初めてそのコスト削減を実現すると論じた。Stripe・Revolut・Ant Financial等のフィンテックユニコーンが規制の隙間から急成長し、既存金融機関のイノベーション対応を迫る。PSD2（欧州）・金融庁API公開要件（日本）がオープンバンキングを推進している。","platform_digital_innovation","デジタルトランスフォーメーション",2015,None,"meso","金融サービス","フィンテック戦略分析","金融サービスDXを評価する際","フィンテックは金融仲介のどのコストを削減するか","伝統的銀行モデル","フィンテック,DX,モバイル決済,オープンバンキング","fintech,DX,mobile payment,open banking","active","secondary",80,'["Thomas Philippon", "Chris Skinner"]','["Philippon 2016 AEA", "Skinner 2019"]',"フィンテック投資額・採用率"),
    ("inno_digi_221","データ市場の経済学","Economics of Data Markets","データは非競合財（同時使用可能）かつ非排除性が低い（コピー容易）という特性から、伝統的財の経済学とは異なるルールに従う。Varian（2014）は「データ所有権は分析能力と分離できない」と論じ、Jones & Tonetti（2020）はデータの経済学的性質を非競合性・スピルオーバー・規模の経済から分析した。データ市場形成には品質評価・価格メカニズム・プライバシー保護の同時設計が必要であり、Databroker産業の出現がその実態を示す。","platform_digital_innovation","データ経済",2014,None,"macro","全産業","データ価値化戦略","データビジネスモデルを設計する際","データはどのような経済的性質を持つか","物財市場","データ市場,非競合財,データ価値,データブローカー","data market,non-rival good,data value,data broker","active","primary",80,'["Hal Varian", "Charles Jones"]','["Jones Tonetti 2020 AER", "Varian 2014"]',"データ取引量・市場規模"),
    ("inno_digi_222","データガバナンスフレームワーク","Data Governance Framework","データガバナンスはデータ品質・プライバシー・セキュリティ・コンプライアンスを組織横断的に管理する仕組み。DAMA-DMBOK（2017）がデータ管理の包括的枠組みを提供。GDPR（EU、2018）・CCPA（カリフォルニア、2020）・日本個人情報保護法改正（2022）が規制環境を形成する。データメッシュ（Dehghani 2019）はデータ所有権を中央集権型から各ドメインに分散する新アーキテクチャとして注目を集める。","platform_digital_innovation","データ経済",2017,None,"meso","全産業","データガバナンス体制構築","データ管理・コンプライアンスを整備する際","データガバナンスは組織のデータ活用能力をどう高めるか","非構造的データ管理","データガバナンス,GDPR,プライバシー,DAMA","data governance,GDPR,privacy,DAMA","active","secondary",80,'["Zhamak Dehghani", "DAMA International"]','["DAMA-DMBOK 2017", "GDPR 2018"]',"コンプライアンス達成率・データ品質スコア"),
    ("inno_digi_223","データ主権とデジタル地政学","Data Sovereignty and Digital Geopolitics","データ主権（data sovereignty）は国家・企業・個人がデータに対して持つ管轄権・コントロール権を指す。欧州のGAIA-Xプロジェクト（2020）はEUのデータ主権確立を目指す産業クラウド基盤。中国のデータセキュリティ法（2021）・国家安全法は国内データの越境移転を制限する。Floridi（2020）は「データ地政学」として国家間のデータ覇権争いを分析し、デジタル植民地主義のリスクを論じた。","platform_digital_innovation","データ経済",2020,None,"macro","政府・多国籍企業","デジタル地政学分析","データ政策の地政学的影響を分析する際","データ主権はデジタル経済の国際秩序をどう変えるか","グローバルデータ自由流通","データ主権,GAIA-X,デジタル地政学,越境データ","data sovereignty,GAIA-X,digital geopolitics,cross-border data","active","secondary",76,'["Luciano Floridi", "Ulrich Ahle"]','["Floridi 2020", "GAIA-X Technical Committee 2021"]',"データローカライゼーション法令数・越境データ量"),
    ("inno_digi_224","サイバーセキュリティとイノベーション投資","Cybersecurity and Innovation Investment","サイバーセキュリティへの投資は組織のデジタルイノベーション継続の前提条件となっている。Anderson et al.（2019）はセキュリティ侵害の経済コストをサプライチェーン全体で評価する枠組みを提案。ゼロトラストアーキテクチャ（NIST SP800-207、2020）はパラメータ防御からアイデンティティベース認証へのパラダイム転換を示す。ランサムウェア・サプライチェーン攻撃（SolarWinds、Log4j）がサイバーリスクの現実的脅威を顕在化させた。","platform_digital_innovation","サイバーセキュリティ",2019,None,"meso","全産業","サイバーリスク管理","デジタル基盤のセキュリティを確保する際","サイバーセキュリティ投資はどのようにイノベーションを支えるか","境界型セキュリティ","サイバーセキュリティ,ゼロトラスト,ランサムウェア,NIST","cybersecurity,zero trust,ransomware,NIST","active","secondary",78,'["Ross Anderson", "John Kindervag"]','["Anderson et al. 2019", "NIST SP800-207 2020"]',"セキュリティ侵害コスト・インシデント件数"),
    ("inno_digi_225","プライバシー強化技術（PET）とイノベーション","Privacy Enhancing Technologies (PET) and Innovation","プライバシー強化技術（PET）は個人データを保護しながらデータ活用を可能にする技術群。差分プライバシー（Dwork 2006）・連合学習（McMahan et al. 2017）・秘密計算（Multi-Party Computation）・準同型暗号がPETの主要カテゴリ。Googleのプライバシーサンドボックス・Appleの差分プライバシー適用が実用事例。プライバシーとデータ有用性のトレードオフを最小化する研究が活発化している。","platform_digital_innovation","プライバシー技術",2017,None,"meso","医療・金融・広告","プライバシー保護データ活用設計","プライバシーを保護しながらデータを活用する際","PETはプライバシーとデータ有用性のトレードオフをどう解決するか","中央集権型データ収集","PET,差分プライバシー,連合学習,プライバシー","PET,differential privacy,federated learning,privacy","active","primary",80,'["Cynthia Dwork", "Brendan McMahan"]','["Dwork 2006", "McMahan et al. 2017 AISTATS"]',"プライバシー侵害件数・データ活用精度"),
    ("inno_digi_226","アルゴリズム経済と自動化価格設定","Algorithmic Economy and Automated Pricing","アルゴリズム経済はAI・機械学習が価格設定・在庫管理・マーケティングを自動化する経済システム。Calvano et al.（2020）はアルゴリズム同士が相互作用により人間の指示なく協調的価格設定（暗黙的談合）を学習することを実験的に示した。Amazon・Uber等のダイナミックプライシングが消費者福祉と競争政策に与える影響が規制論議の焦点となっている。","platform_digital_innovation","アルゴリズム経済",2020,None,"macro","EC・金融・交通","アルゴリズム競争分析","アルゴリズムが市場価格形成に関与する際","アルゴリズム価格設定は競争にどのような影響を与えるか","人間による価格設定","アルゴリズム価格設定,ダイナミックプライシング,談合,AI","algorithmic pricing,dynamic pricing,collusion,AI","active","primary",80,'["Emilio Calvano", "Giacomo Calzolari"]','["Calvano et al. 2020 AER"]',"価格分散・消費者余剰"),
    ("inno_digi_227","プラットフォーム労働市場とギグエコノミー","Platform Labor Markets and Gig Economy","Uber・Airbnb・TaskRabbit等のプラットフォームが仲介する仕事（ギグ）は雇用関係の法的曖昧性・所得不安定性・社会保障の欠如を特徴とする。Katz & Krueger（2016）は米国代替的就労形態の拡大を実証し、Hall & Krueger（2018）はUberドライバーの柔軟性選好を示した。EU指令（2024年プラットフォーム労働者指令）・カリフォルニアAB5法などが労働者分類の規制基準を設定しようとしている。","platform_digital_innovation","プラットフォーム労働",2016,None,"macro","労働市場","ギグ経済の政策評価","プラットフォーム労働の規制政策を立案する際","ギグエコノミーは労働市場にどのような影響を与えるか","標準雇用関係","ギグエコノミー,プラットフォーム労働,Uber,雇用分類","gig economy,platform labor,Uber,employment classification","active","primary",82,'["Lawrence Katz", "Alan Krueger"]','["Katz Krueger 2016 NBER", "Hall Krueger 2018"]',"ギグワーカー数・所得格差"),
    ("inno_digi_228","ロボティクスイノベーションと労働市場影響","Robotics Innovation and Labor Market Impact","産業用ロボット・協働ロボット（cobot）・自律移動ロボット（AMR）は製造・物流・農業・サービス業での自動化を推進する。Acemoglu & Restrepo（2020）はロボット導入が雇用と賃金に負の影響を与えることを実証し、「置換効果（displacement effect）」対「生産性効果（productivity effect）」の論争を展開した。日本・韓国・ドイツは高ロボット密度（1万人当たりロボット台数）上位国として比較研究の対象となる。","platform_digital_innovation","ロボティクス",2020,None,"macro","製造・物流","ロボット化の経済影響評価","自動化投資判断と雇用政策を検討する際","ロボティクスは雇用・賃金・生産性にどう影響するか","人手作業","ロボット,協働ロボット,自動化,労働市場","robot,cobot,automation,labor market","active","primary",84,'["Daron Acemoglu", "Pascual Restrepo"]','["Acemoglu Restrepo 2020 AER"]',"ロボット密度・雇用変化率"),
    ("inno_digi_229","SpaceTechイノベーションの民間化","SpaceTech Innovation and Privatization","宇宙産業の民間化（New Space）はSpaceX・Blue Origin・Rocket Labが既存の政府主導宇宙開発コストを劇的に低下させた。SpaceXのFalcon9再使用ロケット（2015年着陸成功）は打上コストをkg当たり60,000ドルから2,700ドル以下に削減した。Bryce Space and Technology（2023）は民間宇宙投資が累計2900億ドルに達したと報告。衛星通信（Starlink）・宇宙観光・月探査・小惑星資源採掘が新事業領域として浮上している。","platform_digital_innovation","SpaceTech・DeepTech",2015,None,"macro","宇宙産業","民間宇宙産業分析","宇宙関連投資・政策を評価する際","SpaceTechの民間化はどのようなイノベーションエコシステムを形成するか","政府独占型宇宙開発","SpaceTech,SpaceX,New Space,再使用ロケット","SpaceTech,SpaceX,New Space,reusable rocket","active","secondary",78,'["Elon Musk", "Jeff Bezos"]','["Bryce Tech 2023", "SpaceX Technical Reports"]',"打上コスト・民間投資額"),
    ("inno_digi_230","DeepTechスタートアップの資金調達構造","DeepTech Startup Financing Structure","DeepTech（先端技術ベンチャー）は長期R&D・高資本要件・技術リスクから従来のVCモデルと適合しにくい。Dealroom（2022）のDeepTechレポートは欧州DeepTech投資が2021年に過去最高の490億ユーロを記録したと報告。EIB・EIC（欧州イノベーション評議会）が公的融資でデスバレーを補完する政策設計が進む。量子・バイオ・核融合・先端材料の各分野でDeepTechクラスターが形成されている。","platform_digital_innovation","SpaceTech・DeepTech",2020,None,"macro","VC・スタートアップ","DeepTech投資分析","DeepTech投資戦略を設計する際","DeepTechスタートアップはどのような資金調達の課題を持つか","ソフトウェアスタートアップ","DeepTech,VC,EIC,資金調達,技術リスク","DeepTech,VC,EIC,financing,technology risk","active","secondary",76,'["Dealroom Research Team", "EIC Staff"]','["Dealroom DeepTech Report 2022", "EIB DeepTech Report 2021"]',"DeepTech投資額・ユニコーン数"),
    ("inno_digi_231","Web3の経済学とトークンエコノミクス","Web3 Economics and Tokenomics","Web3はブロックチェーン基盤の分散型ウェブを指し、DeFi（分散型金融）・NFT・DAO（分散型自律組織）が主要コンセプト。Catalini & Gans（2018）はトークンセール（ICO）の経済学を分析し、情報非対称性の解消メカニズムとして機能すると論じた。DeFiはAave・Uniswap等のスマートコントラクトで金融仲介を非中央集権化し、2021年ピーク時TVL（総預け入れ価値）は1800億ドルに達した。","platform_digital_innovation","Web3・分散型経済",2018,None,"macro","金融・コンテンツ","Web3エコシステム分析","分散型ビジネスモデルを評価する際","Web3はどのような経済的価値を創出するか","中央集権型Web2","Web3,DeFi,NFT,DAO,トークン","Web3,DeFi,NFT,DAO,tokenomics","active","secondary",74,'["Christian Catalini", "Joshua Gans"]','["Catalini Gans 2018 NBER"]',"TVL・NFT取引量・DAOメンバー数"),
    ("inno_digi_232","メタバース経済と仮想空間プラットフォーム","Metaverse Economy and Virtual Space Platform","メタバースは永続的・相互運用的な仮想空間において経済活動・社会活動が行われるコンセプト。Ball（2022）はメタバースの7要件（持続性・同期性・無制限参加者・経済機能・相互運用性等）を定義した。Roblox・Fortnite・Decentralandの異なる実装モデルが競合し、Meta社のHorizon Worlds失敗がエンタープライズメタバースの課題を露呈した。空間コンピューティング・触覚インターフェース・AIアバターがメタバース実現の技術的条件となる。","platform_digital_innovation","Web3・分散型経済",2021,None,"meso","エンタメ・教育・不動産","メタバース事業評価","メタバース参入戦略を検討する際","メタバースはどのような産業に変革をもたらすか","物理空間ビジネス","メタバース,仮想空間,Roblox,Meta,経済","metaverse,virtual space,Roblox,Meta,economy","active","secondary",72,'["Matthew Ball", "Mark Zuckerberg"]','["Ball 2022 Metaverse Book"]',"メタバース市場規模・ユーザー数"),
    ("inno_digi_233","デジタルツインの産業適用","Industrial Application of Digital Twins","デジタルツインは物理システムのリアルタイム仮想複製であり、製造・インフラ・都市管理の最適化に用いられる。Grieves（2014）が「デジタルツイン」概念を製品ライフサイクル管理（PLM）で定式化し、NASA・GEが航空宇宙・発電で実用化した。Siemens NX・Ansys Twin Builder・Azure Digital Twinsがプラットフォームを提供。스マートシティ（シンガポールVirtual Singapore・バルセロナ）でのデジタルツイン適用が都市管理コストを削減している。","platform_digital_innovation","デジタルトランスフォーメーション",2014,None,"meso","製造・インフラ・都市","デジタルツイン設計","物理システムの予知管理を実現する際","デジタルツインはどのような産業での価値を持つか","物理試験","デジタルツイン,PLM,スマートシティ,IoT","digital twin,PLM,smart city,IoT","active","secondary",78,'["Michael Grieves", "John Vickers"]','["Grieves 2014 Product Lifecycle Management"]',"予知保全コスト削減率"),
    ("inno_digi_234","APIエコノミーとプログラマブルビジネス","API Economy and Programmable Business","API（Application Programming Interface）エコノミーはソフトウェア機能をサービスとして公開・流通させる経済モデル。Stripe・Twilio・Plaidが「APIファースト企業」の典型として急成長した。Kin Lane（2012）の「API Economy」概念が普及し、ProgrammableWebが記録するAPI数は2020年に24,000件超に達した。SquareやPayPalのような決済APIが新規事業立ち上げコストを劇的に削減し、ソフトウェアの構成可能性（composability）がビジネスモデルイノベーションを加速する。","platform_digital_innovation","デジタルプラットフォーム経済",2012,None,"meso","IT・金融・通信","APIビジネスモデル設計","ソフトウェア機能を外部公開する際","APIエコノミーはどのようにビジネスモデルを変革するか","垂直統合型ソフトウェア","API,APIエコノミー,Stripe,Twilio,プログラマブル","API,API economy,Stripe,Twilio,programmable","active","secondary",78,'["Kin Lane", "Patrick Collison"]','["Kin Lane 2012", "ProgrammableWeb Reports"]',"API公開数・API収益"),
    ("inno_digi_235","マイクロサービスアーキテクチャとイノベーション速度","Microservices Architecture and Innovation Speed","マイクロサービスアーキテクチャはモノリシックアプリケーションを独立デプロイ可能な小サービスに分割し、開発速度・スケーラビリティ・耐障害性を向上させる。Newman（2015）が実践的枠組みを整理し、Amazon・Netflix・Spotifyが先行事例として機能した。コンテナ（Docker）・オーケストレーション（Kubernetes）・サービスメッシュ（Istio）との組み合わせがDevOps実践の基盤となる。Forsgren et al.（2018）のDORA指標はデプロイ頻度・変更失敗率でデリバリーパフォーマンスを測定する。","platform_digital_innovation","クラウドコンピューティング",2015,None,"micro","ソフトウェア産業","マイクロサービス設計・移行","開発速度とデプロイ頻度を向上させる際","マイクロサービスはイノベーション速度をどう高めるか","モノリシックアーキテクチャ","マイクロサービス,Docker,Kubernetes,DevOps","microservices,Docker,Kubernetes,DevOps","active","secondary",80,'["Sam Newman", "Nicole Forsgren"]','["Newman 2015", "Forsgren et al. 2018 Accelerate"]',"デプロイ頻度・変更失敗率"),
    ("inno_digi_236","ネットワーク効果の種類と測定","Types and Measurement of Network Effects","ネットワーク効果は直接（同一サイドユーザー増加による価値向上）・間接（補完的サイドの増加による価値向上）・データネットワーク効果に分類される。Shapiro & Varian（1999）の「情報ルール」がネットワーク効果の経済学的基礎を提供。Eisenmann（2006）はプラットフォームのネットワーク効果測定に「採用曲線傾き」と「離脱率」を使用した。Tucker（2019）はデータネットワーク効果の実証研究で、ビッグデータが予測精度を向上させる効果を定量化した。","platform_digital_innovation","プラットフォーム経済学",1999,None,"meso","プラットフォーム産業","ネットワーク効果分析","プラットフォームの競争優位を評価する際","ネットワーク効果の強さはどのように測定できるか","単独製品の価値","ネットワーク効果,直接,間接,データ,プラットフォーム","network effects,direct,indirect,data,platform","active","primary",85,'["Carl Shapiro", "Hal Varian"]','["Shapiro Varian 1999 Information Rules", "Tucker 2019"]',"ユーザー増加率・スイッチングコスト"),
    ("inno_digi_237","プラットフォームガバナンスと規制設計","Platform Governance and Regulatory Design","プラットフォームガバナンスは市場支配力・コンテンツモデレーション・競争政策・データ保護を統合的に管理する枠組み。EU DSA（デジタルサービス法、2022）・DMA（デジタル市場法、2022）は大規模プラットフォームに「ゲートキーパー」義務を課す。Balkin（2018）は「プラットフォームが情報中間者として新たな言論規制主体になる」と論じ、Zittrain（2008）のGenerativity理論が革新性と制御のバランスを分析した。","platform_digital_innovation","プラットフォーム規制",2018,None,"macro","デジタルプラットフォーム","プラットフォーム規制・自主規制設計","デジタル市場の公正競争を確保する際","プラットフォームガバナンスはどのような課題を抱えるか","従来産業規制","プラットフォームガバナンス,DSA,DMA,コンテンツモデレーション","platform governance,DSA,DMA,content moderation","active","secondary",80,'["Jack Balkin", "Jonathan Zittrain"]','["Balkin 2018", "EU DSA 2022", "EU DMA 2022"]',"規制コスト・競争状況"),
    ("inno_digi_238","人工知能規制とイノベーション政策","AI Regulation and Innovation Policy","AI規制はリスクベースアプローチ（EU AI Act、2024）・セクター別規制（FDA医療AI・金融AI）・自主規制（業界コード）の三類型で展開される。EU AI Act（2024年施行）は高リスクAIに適合評価・透明性要件を課し、世界初の包括的AI規制法となった。Dafoe（2018）のAIガバナンス論は技術ガバナンスと地政学的競争の緊張関係を分析した。イノベーション速度と安全規制のバランスをどう取るかが政策設計の核心となっている。","platform_digital_innovation","AI規制・ガバナンス",2024,None,"macro","AI産業全般","AI規制の影響分析","AI開発・展開の規制対応を検討する際","AI規制はイノベーション速度にどう影響するか","事後規制","AI規制,EU AI Act,リスクベース,ガバナンス","AI regulation,EU AI Act,risk-based,governance","active","secondary",80,'["Allan Dafoe", "Marietje Schaake"]','["EU AI Act 2024", "Dafoe 2018 AI Governance"]',"AI規制コスト・採用障壁"),
    ("inno_digi_239","プラットフォーム競争とM&A戦略","Platform Competition and M&A Strategy","デジタルプラットフォームはKillzone戦略（有望スタートアップの先行買収）でエコシステムを拡張する。Cunningham et al.（2019）はFacebook・Google・Amazonの買収673件を分析し、競合可能性のある企業の「予防的買収（killer acquisition）」を実証した。欧州委員会・FTCは大型プラットフォームM&Aに対する精査を強化し、Microsoft-Activision（2023）・Meta-Giphy等の事例が規制論議を深めた。","platform_digital_innovation","プラットフォーム競争戦略",2019,None,"macro","デジタルプラットフォーム","M&A競争戦略分析","プラットフォームの買収戦略を評価する際","プラットフォームのM&Aは競争を阻害するか促進するか","有機的成長","プラットフォーム,M&A,killzone,買収,競争","platform,M&A,killzone,acquisition,competition","active","primary",82,'["Colleen Cunningham", "Florian Ederer"]','["Cunningham et al. 2019 QJE"]',"M&A件数・市場集中度"),
    ("inno_digi_240","マルチホーミングとプラットフォームスイッチング","Multi-Homing and Platform Switching","マルチホーミングはユーザーが複数の競合プラットフォームを並行利用することで、シングルホーミングより競争を促進する。Rochet & Tirole（2003）がマルチホーミングを二面市場競争の鍵変数として定式化した。配車（UberとLyft並行利用）・フードデリバリー（複数アプリ利用）・フリーランス（複数プラットフォーム登録）が典型事例。マルチホーミングコストの低下がプラットフォームの価格競争を激化させる動態が実証されている。","platform_digital_innovation","プラットフォーム経済学",2003,None,"meso","プラットフォーム産業","プラットフォーム競争分析","プラットフォーム競争戦略を設計する際","マルチホーミングはプラットフォームの競争力をどう変えるか","ロックイン型プラットフォーム","マルチホーミング,スイッチング,競争,プラットフォーム","multi-homing,switching,competition,platform","active","primary",80,'["Jean Tirole", "Jean-Charles Rochet"]','["Rochet Tirole 2003"]',"マルチホーミング率・価格弾力性"),
    ("inno_digi_241","自然言語処理の発展とテキスト分析産業応用","NLP Development and Text Analytics Industrial Application","BERT（Devlin et al. 2018）・GPT系列（OpenAI）・T5（Raffel et al. 2019）等のTransformerベースモデルがNLPの精度を飛躍的に向上させた。感情分析・情報抽出・要約・機械翻訳・対話システムへの産業応用が拡大する。Manning et al.（2020）はNLP技術の進歩が社会科学・法律・医療での文書分析を変革すると論じた。HuggingFaceのモデルハブが事前学習済みモデルの民主的アクセスを実現している。","platform_digital_innovation","AI・機械学習",2018,None,"meso","全産業","NLPシステム設計","テキストデータからの価値創出を検討する際","NLPはどのような業務プロセスを自動化するか","規則ベース文書処理","NLP,BERT,GPT,Transformer,テキスト分析","NLP,BERT,GPT,Transformer,text analytics","active","primary",82,'["Jacob Devlin", "Colin Raffel"]','["Devlin et al. 2018 BERT", "Raffel et al. 2019 T5"]',"タスク精度・採用企業数"),
    ("inno_digi_242","コンピュータビジョンと製造品質管理","Computer Vision and Manufacturing Quality Control","ディープラーニングベースのコンピュータビジョン（ResNet・YOLO等）は製品外観検査・欠陥検出・OCRの精度で人間を超え産業自動化を推進する。LeCun et al.（2015）のディープラーニング論文が現代CVの基礎を整理した。BMW・Toyota・Samsung等の製造ラインへの自動外観検査導入が不良率削減と検査コスト低下をもたらした。医療画像診断（放射線科AI）・自動運転センシング・農業ドローン管理にも広く適用される。","platform_digital_innovation","AI・機械学習",2015,None,"meso","製造・医療","CV品質管理システム設計","製造品質管理をAI化する際","コンピュータビジョンはどのような品質管理タスクを改善するか","人手目視検査","コンピュータビジョン,深層学習,品質管理,製造AI","computer vision,deep learning,quality control,manufacturing AI","active","secondary",80,'["Yann LeCun", "Yoshua Bengio"]','["LeCun et al. 2015 Nature"]',"欠陥検出精度・検査コスト"),
    ("inno_digi_243","予測分析とビジネス意思決定","Predictive Analytics and Business Decision Making","予測分析は過去データから機械学習モデルを構築し、将来の顧客行動・需要・リスクを予測する。Davenport & Harris（2007）の「Competing on Analytics」は分析競争力を組織能力として位置付けた。Churn予測・需要予測・信用スコアリング・サプライチェーン最適化が主要適用領域。モデルの解釈可能性（XAI：説明可能AI）が規制・倫理の観点から重要性を増している。","platform_digital_innovation","AI・機械学習",2007,None,"micro","全産業","予測モデル導入","データドリブン意思決定を実現する際","予測分析は組織の意思決定品質をどう向上させるか","直感・経験則","予測分析,機械学習,XAI,需要予測,意思決定","predictive analytics,machine learning,XAI,demand forecast","active","secondary",80,'["Thomas Davenport", "Jeanne Harris"]','["Davenport Harris 2007"]',"予測精度・意思決定速度"),
    ("inno_digi_244","推薦システムの経済学とフィルターバブル","Economics of Recommendation Systems and Filter Bubbles","推薦システム（Collaborative Filtering・Content-based・ハイブリッド）はNetflix・Spotify・AmazonでUX向上と収益最大化を実現する。Resnick & Varian（1997）が協調フィルタリングの基礎を定式化した。Pariser（2011）の「フィルターバブル」概念は推薦アルゴリズムによる情報偏向・分極化リスクを論じた。Spotify Discoverの音楽消費拡大・Netflixレコメンドのエンゲージメント改善が実証事例として頻繁に引用される。","platform_digital_innovation","アルゴリズム経済",1997,None,"meso","EC・メディア","推薦システム設計","パーソナライゼーション戦略を実施する際","推薦システムはどのような経済的価値を生むか","編集・キュレーション","推薦システム,フィルターバブル,協調フィルタリング,Netflix","recommendation system,filter bubble,collaborative filtering,Netflix","active","secondary",82,'["Paul Resnick", "Hal Varian"]','["Resnick Varian 1997", "Pariser 2011"]',"エンゲージメント率・多様性指標"),
    ("inno_digi_245","デジタルプラットフォームの市場支配力と反トラスト","Digital Platform Market Power and Antitrust","GAFAM等のデジタルプラットフォームはネットワーク効果・データ優位性・スイッチングコストにより寡占的市場支配力を持つ。Stigler Committee（2019）・Competition & Digital Markets（UK, 2020）・Furman Review（UK, 2019）が各国競争政策レビューを提供した。市場画定（関連市場）・支配的地位の濫用・合併規制の三軸で競争政策が展開される。デジタル市場の競争分析にはマルチサイド市場・ゼロ価格・データ資産の概念的再定義が必要とされている。","platform_digital_innovation","プラットフォーム規制",2019,None,"macro","デジタルプラットフォーム","デジタル市場競争政策分析","デジタル市場の競争政策を設計する際","デジタルプラットフォームの市場支配力はどのように評価されるか","伝統産業競争法","市場支配力,GAFAM,反トラスト,競争政策","market power,GAFAM,antitrust,competition policy","active","secondary",82,'["Jason Furman", "Lina Khan"]','["Furman Review 2019", "Stigler Committee 2019", "Khan 2017 Yale LJ"]',"市場集中度・規制件数"),
    ("inno_digi_246","スーパーアプリの戦略と新興国デジタル経済","Super App Strategy and Emerging Market Digital Economy","スーパーアプリ（WeChat・Grab・Gojek・Paytm）は一つのアプリ内でメッセージ・決済・フード・モビリティ等を統合し、新興国のデジタル金融包摂を推進する。Laffont & Tirole（2000）のバンドリング理論がスーパーアプリの経済学的基礎を提供。インドのUPI（Unified Payments Interface）・インドネシアのGojekが金融包摂モデルの事例として研究される。欧米型アンバンドリング規制との対比で政策議論が展開している。","platform_digital_innovation","デジタルプラットフォーム経済",2013,None,"meso","新興国デジタル経済","スーパーアプリ戦略分析","新興国向けデジタルサービスを設計する際","スーパーアプリはどのような市場で競争優位を生むか","シングルユース型アプリ","スーパーアプリ,WeChat,Grab,金融包摂,新興国","super app,WeChat,Grab,financial inclusion,emerging market","active","secondary",78,'["Jean Tirole", "Anthony Tan"]','["Laffont Tirole 2000", "CGAP Super App Report 2021"]',"MAU・取引額・金融包摂率"),
    ("inno_digi_247","プラットフォームエンベロープメントとエコシステム拡張","Platform Envelopment and Ecosystem Expansion","プラットフォームエンベロープメントはEisenmann et al.（2011）が提唱した概念で、既存プラットフォームが隣接市場に参入し競合プラットフォームを取り込む戦略。Microsoft Office→Teams、Amazon EC→AWS→Advertising→Prime Videoの拡張がその典型。補完品市場への参入（Complementor Conflict）が開発者エコシステムとの信頼に摩擦を生む。Parker et al.（2016）の「プラットフォームレボリューション」が体系化した。","platform_digital_innovation","プラットフォーム競争戦略",2011,None,"meso","プラットフォーム産業","エコシステム拡張戦略","プラットフォームの隣接市場参入を評価する際","プラットフォームエンベロープメントはどのような条件で成功するか","垂直統合","エンベロープメント,エコシステム,プラットフォーム拡張,補完","envelopment,ecosystem,platform expansion,complement","active","primary",80,'["Thomas Eisenmann", "Geoffrey Parker"]','["Eisenmann et al. 2011 HBR", "Parker et al. 2016"]',"市場シェア拡大・開発者数"),
    ("inno_digi_248","AIと自動化の倫理フレームワーク","Ethics Framework for AI and Automation","AI倫理は公平性（Fairness）・説明可能性（Explainability）・プライバシー・安全性・アカウンタビリティの五原則で構成される。IEEE Ethically Aligned Design（2019）・EU信頼できるAI倫理ガイドライン（2019）・OECD AI原則（2019）が国際標準を形成。Barocas & Hardt（2023）の公平機械学習教科書がアルゴリズムバイアスの技術的対処を整理した。採用・融資・刑事司法でのAI差別リスクが具体的訴訟事例として議論されている。","platform_digital_innovation","AI規制・ガバナンス",2019,None,"macro","AI開発全般","AI倫理審査・設計","AI製品の倫理審査プロセスを設計する際","AI倫理フレームワークはどのような実装上の課題を持つか","性能最大化型AI設計","AI倫理,公平性,説明可能性,アルゴリズムバイアス","AI ethics,fairness,explainability,algorithmic bias","active","secondary",80,'["Solon Barocas", "Moritz Hardt"]','["IEEE EAD 2019", "EU HLEG 2019", "Barocas Hardt 2023"]',"バイアス事例数・コンプライアンス率"),
    ("inno_digi_249","デジタルインクルージョンとアクセシビリティ","Digital Inclusion and Accessibility","デジタルインクルージョンは年齢・障害・地域・経済力による技術アクセス格差を解消し、デジタル経済の恩恵を全員に届ける政策概念。ITU（2023）はグローバルインターネット普及率67%と未接続33億人の実態を報告。WAI-ARIA・WCAG2.1（Web Content Accessibility Guidelines）がアクセシビリティ標準を提供。日本の障害者差別解消法改正（2024）・EU EAA（欧州アクセシビリティ法）が法的義務化を進める。","platform_digital_innovation","デジタル包摂",2019,None,"macro","公共サービス・教育","デジタル格差対策","デジタルインクルージョン政策を設計する際","デジタル格差はどのような経済的不平等を生むか","デジタルエリート主義","デジタルインクルージョン,アクセシビリティ,デジタル格差,ITU","digital inclusion,accessibility,digital divide,ITU","active","secondary",76,'["International Telecommunication Union", "Judy Brewer"]','["ITU Digital Development Report 2023", "WCAG 2.1 2018"]',"インターネット普及率・格差指標"),
    ("inno_digi_250","スマートシティとデジタルアーバニズム","Smart City and Digital Urbanism","スマートシティはIoT・AI・ビッグデータで都市インフラを最適化し市民サービスを向上させる。Caragliu et al.（2011）がスマートシティの学術的定義を提示し、Singapore・Barcelona・Amsterdam・東京等の事例研究が蓄積された。Sidewalk Toronto（Alphabet子会社）プロジェクトの中止がプライバシー・データ主権の問題を顕在化させた。国連SDGs目標11（持続可能な都市）との接続でスマートシティ政策が位置付けられる。","platform_digital_innovation","IoT・エッジコンピューティング",2011,None,"macro","都市・公共","スマートシティ政策設計","都市デジタル化戦略を立案する際","スマートシティはどのような都市課題を解決するか","従来都市管理","スマートシティ,IoT,都市データ,Singapore","smart city,IoT,urban data,Singapore","active","secondary",78,'["Andrea Caragliu", "Carlo Bo"]','["Caragliu et al. 2011", "ITU Smart City Framework"]',"都市効率指標・住民満足度"),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()

insert_sql = """
INSERT OR IGNORE INTO innovation_theory
(id, name_ja, name_en, definition, subfield, school_of_thought, era_start, era_end,
 methodology_level, target_domain, application_conditions, when_to_apply, framing_questions,
 opposing_concept_names, keywords_ja, keywords_en, status, source_reliability, data_completeness,
 key_researchers, key_works, measurement_approach)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
"""

conn.executemany(insert_sql, records)
conn.commit()
print(f"Inserted: {conn.total_changes} records")

cur.execute("SELECT COUNT(*) FROM innovation_theory WHERE subfield='platform_digital_innovation'")
print(f"Total platform_digital_innovation: {cur.fetchone()[0]}")
conn.close()
