import sqlite3
from datetime import datetime
db_path = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"
now = datetime.now().isoformat()
entries = [
    {
        "id": "inno_pol_551",
        "name_en": "Technology Intelligence Systems",
        "name_ja": "技術インテリジェンスシステム",
        "definition": "競争企業・政府・研究機関が技術動向・競合状況・脅威を系統的に収集・分析する組織的能力を指す。特許・論文・ニュースデータを統合し、戦略的意思決定を支援する。",
        "impact_summary": "技術情報の戦略的活用を通じて企業や国家の競争優位を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "strategic_management",
        "era_start": 1980,
        "innovation_type": "process",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "技術インテリジェンス,競合分析,特許情報,戦略的情報収集",
        "keywords_en": "technology intelligence,competitive intelligence,patent analysis,strategic scanning",
        "key_researchers": '["Ashton W.B.", "Klavans R."]',
        "key_works": '["Technology Intelligence and Corporate Strategy (1985)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_552",
        "name_en": "Research Evaluation Frameworks",
        "name_ja": "研究評価フレームワーク",
        "definition": "公的研究の成果・効率・影響を体系的に評価するための方法論的枠組みを指す。英国REF、オーストラリアERE、欧州科学技術指標等が代表例である。",
        "impact_summary": "研究資金配分の透明性と効率性を高め、研究の説明責任を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1986,
        "innovation_type": "process",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "研究評価,REF,研究卓越性,研究業績評価",
        "keywords_en": "research evaluation,REF,research excellence framework,performance-based funding",
        "key_researchers": '["Butler L.", "Hicks D."]',
        "key_works": '["Bibliometrics in Research Evaluation (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_553",
        "name_en": "Innovation in Public Services",
        "name_ja": "公共サービスにおけるイノベーション",
        "definition": "政府・自治体・公共機関が提供するサービスの改善・変革を指し、プロセス改革・デジタル化・市民参加型共創などを含む。民間イノベーションとは異なる動機・障壁・評価基準を持つ。",
        "impact_summary": "公共価値の創造と行政効率の改善を通じて市民生活の質を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "public_administration",
        "era_start": 2000,
        "innovation_type": "service",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "公共サービス革新,行政イノベーション,デジタル行政,公共価値",
        "keywords_en": "public service innovation,government innovation,digital government,public value",
        "key_researchers": '["Bason C.", "Hartley J."]',
        "key_works": '["Leading Public Sector Innovation (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_554",
        "name_en": "Technology Diffusion Policy",
        "name_ja": "技術普及政策",
        "definition": "新技術の社会的・経済的普及を促進するために政府が実施する政策介入を指す。補助金・税制・規制・情報普及・公共調達などの手段を組み合わせる。",
        "impact_summary": "技術の社会的便益を最大化し、普及の格差や遅延を縮小する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 1985,
        "innovation_type": "diffusion",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "技術普及,普及政策,採用促進,技術移転政策",
        "keywords_en": "technology diffusion,diffusion policy,adoption policy,technology deployment",
        "key_researchers": '["Rogers E.M.", "Geroski P."]',
        "key_works": '["Diffusion of Innovations (1962)", "Markets for Technology (1990)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_555",
        "name_en": "National Research Priorities",
        "name_ja": "国家研究優先課題",
        "definition": "政府が国家的観点から重要とみなす研究分野・課題を特定し、資源配分を方向付けるプロセスを指す。科学諮問委員会・省庁協議・フォーサイト等を通じて策定される。",
        "impact_summary": "限られた公的研究資源を戦略的に配分し、国家課題の解決を加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1970,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "研究優先課題,国家戦略,研究資金配分,科学政策",
        "keywords_en": "research priorities,national strategy,research funding allocation,science policy",
        "key_researchers": '["Salter A.", "Martin B.R."]',
        "key_works": '["The Measurement of Scientific and Technical Activities (1993)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_556",
        "name_en": "Science and Technology Parks Policy",
        "name_ja": "科学技術パーク政策",
        "definition": "大学・研究機関の近隣に設置されたサイエンスパークや技術パークの設立・運営・評価に関する政策的枠組みを指す。スピンオフ育成・産学連携・地域経済振興を目的とする。",
        "impact_summary": "知識集約型産業クラスターの形成を促進し、地域イノベーション生態系を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "cluster_theory",
        "era_start": 1972,
        "innovation_type": "ecosystem",
        "cognitive_mechanism": "spatial",
        "keywords_ja": "サイエンスパーク,テクノポリス,産学連携,クラスター政策",
        "keywords_en": "science park,technology park,research park,university-industry linkage",
        "key_researchers": '["Link A.N.", "Scott J.T."]',
        "key_works": '["Public Science and Public Technology (1998)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_557",
        "name_en": "Venture Capital Policy Evaluation",
        "name_ja": "ベンチャーキャピタル政策評価",
        "definition": "政府によるVC市場への介入（公的VC・税制優遇・共同投資等）の効果を評価する研究分野を指す。民間VC誘発効果・スタートアップ成長・市場失敗是正の観点から分析される。",
        "impact_summary": "VC政策の費用対効果を明らかにし、より効率的なスタートアップエコシステム支援を設計する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_finance",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "VC政策,公的ベンチャー,スタートアップ支援評価,市場失敗",
        "keywords_en": "venture capital policy,public VC,startup ecosystem policy,market failure",
        "key_researchers": '["Leleux B.", "Lerner J."]',
        "key_works": '["The Money of Invention (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_558",
        "name_en": "Open Innovation Metrics",
        "name_ja": "オープンイノベーション測定指標",
        "definition": "企業が外部知識・技術を活用するオープンイノベーション活動の範囲・深度・成果を測定する指標体系を指す。外部R&D比率・協力協定数・ライセンス収入・共同特許等が含まれる。",
        "impact_summary": "企業のオープンイノベーション戦略の実態把握と政策立案の基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_innovation",
        "era_start": 2003,
        "innovation_type": "process",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "オープンイノベーション測定,外部R&D,知識獲得,協力指標",
        "keywords_en": "open innovation metrics,external R&D,knowledge sourcing,collaboration indicators",
        "key_researchers": '["Chesbrough H.", "Dahlander L.", "Gann D."]',
        "key_works": '["Open Innovation (2003)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_559",
        "name_en": "STI Policy for Aging Societies",
        "name_ja": "高齢化社会に向けた科学技術イノベーション政策",
        "definition": "急速な高齢化に対応するため、医療・介護・生活支援技術の開発・普及を促進する政策を指す。シルバーテック・AAL・ロボット介護等が政策的関心を集めている。",
        "impact_summary": "高齢社会の課題解決と産業機会の創出を同時に追求する政策の枠組みを提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 2000,
        "innovation_type": "social",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "高齢化対応技術,AAL,シルバーテック,介護ロボット政策",
        "keywords_en": "aging society innovation,AAL,silver technology,care robot policy",
        "key_researchers": '["Christensen K.", "Fagerberg J."]',
        "key_works": '["Innovation and Welfare State (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_560",
        "name_en": "Science Budget Analysis",
        "name_ja": "科学予算分析",
        "definition": "国家・地域・国際レベルでの科学技術予算の規模・構造・推移を分析する手法を指す。GERD/GDP比・公民比率・分野別配分・目的別分類等が主要指標として用いられる。",
        "impact_summary": "科学技術投資の国際比較と政策効果の評価基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1960,
        "innovation_type": "policy",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "科学予算,GERD,R&D集約度,科学技術費",
        "keywords_en": "science budget,GERD,R&D intensity,public R&D expenditure",
        "key_researchers": '["OECD Directorate", "Hicks D."]',
        "key_works": '["Main Science and Technology Indicators (annual)", "Frascati Manual (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_561",
        "name_en": "Knowledge-Based Economy Indicators",
        "name_ja": "知識基盤経済指標",
        "definition": "知識・技術・人的資本が経済成長の主要ドライバーとなる知識基盤経済の実態を測定する指標体系を指す。教育水準・R&D支出・情報化度・イノベーション活動等を総合的に評価する。",
        "impact_summary": "知識経済への移行度合いを国際比較し、政策優先課題の特定を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "knowledge_economy",
        "era_start": 1996,
        "innovation_type": "systemic",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "知識基盤経済,知識指標,人的資本,情報化経済",
        "keywords_en": "knowledge-based economy,knowledge indicators,human capital,information economy",
        "key_researchers": '["David P.A.", "Foray D."]',
        "key_works": '["Economic Fundamentals of the Knowledge Society (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_562",
        "name_en": "Evaluation of Technology Transfer Offices",
        "name_ja": "技術移転機関評価",
        "definition": "大学・公的研究機関の技術移転活動（特許出願・ライセンス・スピンオフ・受託研究等）の成果と効率を評価する方法論を指す。AUTM調査・UNICO等が国際比較データを提供する。",
        "impact_summary": "大学発イノベーションの商業化効率を測定し、TTO運営改善の根拠を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "triple_helix",
        "era_start": 1990,
        "innovation_type": "process",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "技術移転機関,TTO評価,ライセンス収入,大学スピンオフ",
        "keywords_en": "technology transfer office,TTO evaluation,licensing,university spinoff",
        "key_researchers": '["Siegel D.S.", "Thursby M."]',
        "key_works": '["Assessing the Impact of College Spinoffs (2003)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_563",
        "name_en": "Digital Economy Policy",
        "name_ja": "デジタル経済政策",
        "definition": "デジタル技術・プラットフォーム・データ経済の発展を促進または規制する政策の総称を指す。デジタルインフラ整備・データ流通ルール・AI規制・プラットフォーム競争政策等が含まれる。",
        "impact_summary": "デジタル経済の成長と公正な競争環境の確保を同時に実現する政策設計の基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "platform_economics",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "デジタル経済,プラットフォーム規制,データ政策,AI規制",
        "keywords_en": "digital economy policy,platform regulation,data policy,AI governance",
        "key_researchers": '["Tirole J.", "van Dijck J."]',
        "key_works": '["The Culture of Connectivity (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_564",
        "name_en": "Innovation System Indicators",
        "name_ja": "イノベーションシステム指標",
        "definition": "国家・地域・セクター別イノベーションシステムの構造・機能・パフォーマンスを測定する指標を指す。システム要素（企業・大学・政府・中間機関）間の相互作用と知識フローを把握する。",
        "impact_summary": "イノベーションシステムの強みと弱点を診断し、的確な政策介入を設計する基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 1992,
        "innovation_type": "systemic",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "イノベーションシステム指標,NIS測定,システム機能,知識フロー",
        "keywords_en": "innovation system indicators,NIS measurement,system functions,knowledge flows",
        "key_researchers": '["Lundvall B.A.", "Edquist C."]',
        "key_works": '["National Systems of Innovation (1992)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_565",
        "name_en": "Entrepreneurship Policy",
        "name_ja": "アントレプレナーシップ政策",
        "definition": "新規企業設立・成長・起業家人材育成を促進する政策の総称を指す。規制緩和・教育プログラム・資金支援・ネットワーク構築等の手段が含まれる。",
        "impact_summary": "新産業の創出と雇用創出を通じて経済活性化と社会変革を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "entrepreneurship",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "起業政策,スタートアップ支援,規制緩和,起業家教育",
        "keywords_en": "entrepreneurship policy,startup policy,regulatory reform,entrepreneurship education",
        "key_researchers": '["Audretsch D.B.", "Thurik A.R."]',
        "key_works": '["Capitalism and Democracy in the 21st Century (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_566",
        "name_en": "Innovation Policy Mix",
        "name_ja": "イノベーション政策ミックス",
        "definition": "供給側（R&D支援）・需要側（調達・規制）・媒介（中間機関）などの多様な政策手段を組み合わせ、イノベーションシステム全体を強化する総合的アプローチを指す。",
        "impact_summary": "単一の政策手段では対処できない複合的な市場失敗・システム失敗に対処する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "政策ミックス,需要側政策,供給側政策,政策設計",
        "keywords_en": "policy mix,demand-side policy,supply-side policy,policy design",
        "key_researchers": '["Flanagan K.", "Uyarra E.", "Laranja M."]',
        "key_works": '["Reconceptualising the Policy Mix (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_567",
        "name_en": "Research Infrastructure Governance",
        "name_ja": "研究インフラガバナンス",
        "definition": "大型研究施設（粒子加速器・望遠鏡・バイオバンク等）の構築・運営・アクセス管理に関するガバナンス枠組みを指す。費用分担・優先順位設定・国際協力が主要課題である。",
        "impact_summary": "科学的生産性を最大化しつつ、研究インフラへの公平なアクセスを確保する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "研究インフラ,大型施設,ESFRI,インフラガバナンス",
        "keywords_en": "research infrastructure,large-scale facility,ESFRI,infrastructure governance",
        "key_researchers": '["Hallonsten O.", "Heinze T."]',
        "key_works": '["Big Science Transformed (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_568",
        "name_en": "Social Enterprise Policy",
        "name_ja": "ソーシャルエンタープライズ政策",
        "definition": "社会的目的を優先しながら市場原理を活用する社会的企業の設立・成長・持続可能性を支援する政策を指す。ハイブリッド組織・B Corp・社会的インパクト投資と密接に関連する。",
        "impact_summary": "市場と公共セクターの境界を越えた社会的課題解決の新たな制度的基盤を構築する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "social_innovation",
        "era_start": 2000,
        "innovation_type": "institutional",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "ソーシャルエンタープライズ,社会的企業,社会的投資,ハイブリッド組織",
        "keywords_en": "social enterprise,social investment,hybrid organizations,social economy",
        "key_researchers": '["Defourny J.", "Nyssens M."]',
        "key_works": '["Social Enterprise in Europe (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_569",
        "name_en": "Technology Sovereignty",
        "name_ja": "技術主権",
        "definition": "国家・地域（特にEU）が重要技術の開発・生産・調達において外部依存を最小化し、自律的能力を確保しようとする戦略的概念を指す。半導体・AI・量子・バイオ等が対象分野とされる。",
        "impact_summary": "地政学的リスクへの対応として戦略的技術自律性を確保し、経済安全保障を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "strategic_management",
        "era_start": 2019,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "技術主権,経済安全保障,戦略的自律性,技術依存リスク",
        "keywords_en": "technology sovereignty,economic security,strategic autonomy,tech dependence",
        "key_researchers": '["Edler J.", "Carlson E."]',
        "key_works": '["The Political Economy of Technology Sovereignty (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_570",
        "name_en": "Patent Quality Measurement",
        "name_ja": "特許品質測定",
        "definition": "特許の技術的価値・経済的価値・法的強度を定量的に評価する手法を指す。被引用数・請求範囲の広さ・審査過程・無効化率等が指標として用いられる。",
        "impact_summary": "特許システムの効率性改善と知的財産政策の評価に不可欠な情報基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "patent_economics",
        "era_start": 1990,
        "innovation_type": "process",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "特許品質,特許価値,被引用数,特許審査",
        "keywords_en": "patent quality,patent value,citation analysis,patent examination",
        "key_researchers": '["Lanjouw J.", "Schankerman M."]',
        "key_works": '["Patent Quality and Research Productivity (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_571",
        "name_en": "Critical Technology Assessment",
        "name_ja": "重要技術評価",
        "definition": "国家安全保障・経済競争力・社会基盤に不可欠な重要技術を特定・評価するプロセスを指す。米国CHIPS法・EU重要技術リスト・日本経済安保法等における技術特定作業がその例である。",
        "impact_summary": "重要技術への集中投資と保護措置を通じて国家競争力と安全保障を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "strategic_management",
        "era_start": 2020,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "重要技術,経済安保,技術特定,CHIPS法",
        "keywords_en": "critical technology,economic security,technology identification,CHIPS Act",
        "key_researchers": '["Bonvillian W.B.", "Weiss C."]',
        "key_works": '["Technological Innovation in Legacy Sectors (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_572",
        "name_en": "Net Promoter Score for Innovation",
        "name_ja": "イノベーション向けネットプロモータースコア",
        "definition": "顧客推奨意向を測定するNPSをイノベーション活動の成果評価に応用した手法を指す。新製品・サービスの顧客価値・浸透度を定量的に把握するために活用される。",
        "impact_summary": "イノベーション成果を顧客視点から迅速に評価し、製品開発サイクルの改善に活用する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_management",
        "era_start": 2003,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "NPS,顧客推奨,サービス評価,イノベーション成果",
        "keywords_en": "NPS,customer advocacy,service evaluation,innovation outcome",
        "key_researchers": '["Reichheld F.", "Markey R."]',
        "key_works": '["The Ultimate Question 2.0 (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_573",
        "name_en": "Science Communication Policy",
        "name_ja": "科学コミュニケーション政策",
        "definition": "科学的知見・研究成果・リスク情報を一般市民・政策立案者・メディアに効果的に伝達するための政策・制度・資金支援の枠組みを指す。",
        "impact_summary": "科学リテラシーの向上と証拠に基づく意思決定文化の普及を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_communication",
        "era_start": 1985,
        "innovation_type": "policy",
        "cognitive_mechanism": "communicative",
        "keywords_ja": "科学コミュニケーション,科学リテラシー,パブリックエンゲージメント,リスクコミュニケーション",
        "keywords_en": "science communication,science literacy,public engagement,risk communication",
        "key_researchers": '["Wynne B.", "Bauer M.W."]',
        "key_works": '["Public Understanding of Science (1992)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_574",
        "name_en": "Technology Governance Frameworks",
        "name_ja": "技術ガバナンスフレームワーク",
        "definition": "新興技術の開発・展開・利用を規制・誘導する多層的なガバナンス構造を指す。法規制・自主規制・標準・倫理ガイドライン・国際条約等の組み合わせが含まれる。",
        "impact_summary": "技術イノベーションの便益を最大化しつつ、リスク・副作用・格差を管理する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "technology_governance",
        "era_start": 2000,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "技術ガバナンス,規制フレームワーク,自主規制,倫理ガイドライン",
        "keywords_en": "technology governance,regulatory framework,self-regulation,ethics guidelines",
        "key_researchers": '["Rip A.", "Jasanoff S."]',
        "key_works": '["States of Knowledge (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_575",
        "name_en": "Public Research Funding Optimization",
        "name_ja": "公的研究資金最適化",
        "definition": "限られた公的研究資金を最大効果が期待される研究に配分するための意思決定手法を指す。ポートフォリオ分析・実績評価・優先課題との整合・ピアレビュー改革等が含まれる。",
        "impact_summary": "研究資金の費用対効果を高め、科学的・社会的インパクトを最大化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "研究資金配分,ポートフォリオ,ピアレビュー,研究費最適化",
        "keywords_en": "research funding optimization,portfolio,peer review reform,funding allocation",
        "key_researchers": '["Braun D.", "Guston D.H."]',
        "key_works": '["The Politics of Scientists (1998)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_576",
        "name_en": "Regional STI Policy Evaluation",
        "name_ja": "地域科学技術イノベーション政策評価",
        "definition": "地域・州・都市レベルのSTI政策（クラスター・テクノポリス・スマート専門化等）の成果を評価する手法を指す。経済成長・雇用・知識集積・ネットワーク密度等が指標として用いられる。",
        "impact_summary": "地域イノベーション政策の有効性を測定し、リソース配分の改善と政策学習を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regional_innovation",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "地域STI政策,スマート専門化評価,クラスター効果,地域成長",
        "keywords_en": "regional STI policy,smart specialization evaluation,cluster effect,regional growth",
        "key_researchers": '["Cooke P.", "Asheim B."]',
        "key_works": '["Regional Innovation Systems (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_577",
        "name_en": "Science Policy History",
        "name_ja": "科学政策史",
        "definition": "科学・技術・イノベーション政策の歴史的発展を追跡する学術分野を指す。バネバー・ブッシュ報告（1945年）以降の政策パラダイムの変遷、制度変化、国際比較が主要テーマである。",
        "impact_summary": "科学政策の歴史的文脈を理解することで、現代の政策課題をより深く分析する視座を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1945,
        "innovation_type": "institutional",
        "cognitive_mechanism": "historical",
        "keywords_ja": "科学政策史,バネバー・ブッシュ,政策パラダイム,STI史",
        "keywords_en": "science policy history,Vannevar Bush,policy paradigm,STI history",
        "key_researchers": '["Kevles D.J.", "Stokes D.E."]',
        "key_works": '["Pasteurs Quadrant (1997)", "The Physicists (1978)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_578",
        "name_en": "Platform-Based Innovation Governance",
        "name_ja": "プラットフォーム型イノベーションガバナンス",
        "definition": "デジタルプラットフォームが主導するエコシステム型イノベーションを規制・促進するための制度的枠組みを指す。競争法・データ共有義務・アルゴリズム透明性等が主要論点である。",
        "impact_summary": "プラットフォーム経済における公正競争と持続的イノベーションを両立する制度設計を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "platform_economics",
        "era_start": 2015,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "プラットフォーム規制,DMA,デジタル市場,エコシステムガバナンス",
        "keywords_en": "platform regulation,DMA,digital markets,ecosystem governance",
        "key_researchers": '["Parker G.", "van Alstyne M."]',
        "key_works": '["Platform Revolution (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_579",
        "name_en": "Comparative Innovation Policy",
        "name_ja": "比較イノベーション政策",
        "definition": "異なる国・地域のイノベーション政策の設計・実施・成果を体系的に比較分析する研究アプローチを指す。制度的多様性・収束・政策移転の可能性と限界を明らかにする。",
        "impact_summary": "他国の成功事例や失敗から学び、自国に適した政策設計を行うための知識基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "comparative_institutionalism",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "comparative",
        "keywords_ja": "比較政策,制度多様性,政策移転,国際比較",
        "keywords_en": "comparative policy,institutional diversity,policy transfer,cross-national comparison",
        "key_researchers": '["Hall P.A.", "Soskice D."]',
        "key_works": '["Varieties of Capitalism (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_580",
        "name_en": "AI Ethics Governance",
        "name_ja": "AI倫理ガバナンス",
        "definition": "人工知能システムの開発・展開における倫理的課題（偏見・透明性・説明可能性・プライバシー）を管理するための政策・基準・制度の総称を指す。EUのAI Act等が代表的な法制化の試みである。",
        "impact_summary": "AI技術の社会的便益を最大化しながら差別・不透明性・プライバシー侵害リスクを管理する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 2016,
        "innovation_type": "institutional",
        "cognitive_mechanism": "ethical",
        "keywords_ja": "AI倫理,AI Act,アルゴリズム偏見,説明可能AI",
        "keywords_en": "AI ethics,AI Act,algorithmic bias,explainable AI",
        "key_researchers": '["Mittelstadt B.", "Floridi L."]',
        "key_works": '["The Ethics of Artificial Intelligence (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_581",
        "name_en": "Responsible Scaling Policies",
        "name_ja": "責任ある拡張政策",
        "definition": "AI・バイオ・ナノ等の急速に進歩する技術を段階的に展開し、リスク評価と安全対策を先行させながら普及を進める政策アプローチを指す。チェックポイント評価・能力基準等が含まれる。",
        "impact_summary": "技術の急速な普及がもたらすリスクを事前評価し、安全性と革新性を両立させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 2022,
        "innovation_type": "policy",
        "cognitive_mechanism": "precautionary",
        "keywords_ja": "責任ある拡張,AIリスク管理,チェックポイント評価,安全優先",
        "keywords_en": "responsible scaling,AI risk management,capability evaluations,safety-first",
        "key_researchers": '["Askell A.", "Hendrycks D."]',
        "key_works": '["Constitutional AI (2022)", "X-Risk Analysis for AI Research (2022)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_582",
        "name_en": "Societal Impact Assessment",
        "name_ja": "社会的インパクト評価",
        "definition": "研究・イノベーション・政策が社会全体に及ぼす広範な影響（経済・環境・文化・社会的公正等）を評価する手法の総称を指す。SROIや社会的費用便益分析等が代表的手法である。",
        "impact_summary": "経済価値に還元されない社会的・環境的価値を可視化し、より包括的な政策評価を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "impact_evaluation",
        "era_start": 1995,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "社会的インパクト,SROI,社会的費用便益,包括的評価",
        "keywords_en": "societal impact,SROI,social cost-benefit,comprehensive evaluation",
        "key_researchers": '["Mazzucato M.", "Brest P."]',
        "key_works": '["Manifesto for an Entrepreneurial State (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_583",
        "name_en": "Smart Regulation",
        "name_ja": "スマート規制",
        "definition": "規制の設計において費用対効果・比例原則・柔軟性・代替手段の活用を重視し、過剰規制と規制不足を回避する原則的アプローチを指す。Better Regulation・RIAと密接に関連する。",
        "impact_summary": "規制の質を高め、企業負担を削減しながら社会的目標を効率的に達成する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regulatory_theory",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "スマート規制,Better Regulation,比例原則,規制品質",
        "keywords_en": "smart regulation,better regulation,proportionality,regulatory quality",
        "key_researchers": '["Coglianese C.", "Baldwin R."]',
        "key_works": '["Understanding Regulation (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_584",
        "name_en": "University Research Commercialization Policy",
        "name_ja": "大学研究商業化政策",
        "definition": "大学が生み出す基礎研究の成果を商業製品・サービス・産業に転換するプロセスを促進する政策を指す。特許制度改革（バイ・ドール法）・TTO・産学協定等が主要手段である。",
        "impact_summary": "公的研究投資の経済的リターンを高め、大学発イノベーションの商業化を加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "triple_helix",
        "era_start": 1980,
        "innovation_type": "policy",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "大学商業化,バイ・ドール法,産学連携政策,技術移転促進",
        "keywords_en": "university commercialization,Bayh-Dole Act,industry-academia policy,tech transfer",
        "key_researchers": '["Nelson R.R.", "Mowery D.C."]',
        "key_works": '["Ivory Tower and Industrial Innovation (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_585",
        "name_en": "Circular Economy Policy",
        "name_ja": "循環経済政策",
        "definition": "廃棄物をなくし資源の循環利用を最大化する循環経済への移行を促進する政策の総称を指す。製品設計規制・拡大生産者責任・リサイクルインフラ整備等の手段が含まれる。",
        "impact_summary": "資源効率を高め環境負荷を削減しながら、新たなビジネスモデルとイノベーションを促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "循環経済,CE政策,廃棄物削減,資源循環",
        "keywords_en": "circular economy policy,CE policy,waste reduction,resource circularity",
        "key_researchers": '["Ellen MacArthur Foundation", "Stahel W."]',
        "key_works": '["Towards the Circular Economy (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_586",
        "name_en": "National Bioeconomy Strategy",
        "name_ja": "国家バイオエコノミー戦略",
        "definition": "バイオテクノロジー・生物資源・生物プロセスを活用した持続可能な経済活動を促進する国家戦略を指す。農業・医療・エネルギー・材料等の分野横断的なバイオイノベーションを対象とする。",
        "impact_summary": "生物系資源の持続可能な利用と高付加価値化を通じてグリーン経済への移行を加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 2012,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "バイオエコノミー戦略,バイオテクノロジー政策,生物資源,持続可能な経済",
        "keywords_en": "bioeconomy strategy,biotech policy,biological resources,sustainable economy",
        "key_researchers": '["McCormick K.", "Kautto N."]',
        "key_works": '["Bioeconomy in Europe (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_587",
        "name_en": "Transformative Innovation Policy",
        "name_ja": "変革的イノベーション政策",
        "definition": "既存システムを漸進的に改善するのではなく、エネルギー・食料・交通等の社会技術システム全体を根本的に変革するための方向性を持った政策アプローチを指す。",
        "impact_summary": "持続可能な発展目標の達成に必要な社会技術転換を政策的に加速・誘導する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "transitions_theory",
        "era_start": 2016,
        "innovation_type": "systemic",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "変革的政策,システム転換,社会技術移行,持続可能転換",
        "keywords_en": "transformative innovation policy,system transformation,sustainability transition,TIP",
        "key_researchers": '["Schot J.", "Steinmueller W.E."]',
        "key_works": '["Three Frames for Innovation Policy (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_588",
        "name_en": "Technology Assessment Methods",
        "name_ja": "テクノロジーアセスメント手法",
        "definition": "新興技術の社会的影響・リスク・倫理的課題を先行的または事後的に評価する方法論の総称を指す。議会TAから構成的TA・参加型TA・リアルタイムTAへと進化してきた。",
        "impact_summary": "技術の社会実装前後における影響を体系的に把握し、社会的受容と政策立案を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 1972,
        "innovation_type": "process",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "テクノロジーアセスメント,構成的TA,参加型評価,リアルタイムTA",
        "keywords_en": "technology assessment,constructive TA,participatory evaluation,real-time TA",
        "key_researchers": '["Rip A.", "Schot J."]',
        "key_works": '["Constructive Technology Assessment (1995)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_589",
        "name_en": "Science Diplomacy Practice",
        "name_ja": "科学外交実践",
        "definition": "科学・技術協力を外交手段として活用し、国際関係の構築・維持・改善を図る実践を指す。科学顧問外交・研究協定・多国間枠組みへの参加等が含まれる。",
        "impact_summary": "科学協力を通じた信頼構築と知識の国際流通を促進し、グローバルな科学的課題への対処を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_diplomacy",
        "era_start": 2010,
        "innovation_type": "policy",
        "cognitive_mechanism": "diplomatic",
        "keywords_ja": "科学外交,国際科学協力,外交政策,科学顧問",
        "keywords_en": "science diplomacy,international science cooperation,foreign policy,science advisor",
        "key_researchers": '["Ruffini P.B.", "AAAS Science Diplomacy"]',
        "key_works": '["Science and Diplomacy (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_590",
        "name_en": "Deep Technology Investment Policy",
        "name_ja": "ディープテクノロジー投資政策",
        "definition": "量子・AI・合成生物学・先進素材など長期的R&Dを要する革新的技術への投資を促進する政策を指す。長期的資本・専門人材・実証環境の整備が政策的課題とされる。",
        "impact_summary": "既存産業を根本的に変革する可能性を持つ深層技術への投資を通じて次世代産業競争力を形成する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "ディープテック投資,量子政策,合成生物学政策,先進素材",
        "keywords_en": "deep tech investment,quantum policy,synthetic biology policy,advanced materials",
        "key_researchers": '["Bonvillian W.B.", "Swamidass P.M."]',
        "key_works": '["Transforming US Energy Innovation (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_591",
        "name_en": "Citizen Science Policy",
        "name_ja": "市民科学政策",
        "definition": "市民が科学研究プロセス（データ収集・分析・問いの設定等）に参加する市民科学を振興・統合するための政策枠組みを指す。オープンデータ・参加型研究の推進が含まれる。",
        "impact_summary": "科学の民主化と広域データ収集能力の強化を通じて研究の質と社会的関与を高める。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_science",
        "era_start": 2010,
        "innovation_type": "process",
        "cognitive_mechanism": "participatory",
        "keywords_ja": "市民科学,参加型研究,オープンデータ,科学民主化",
        "keywords_en": "citizen science,participatory research,open data,democratization of science",
        "key_researchers": '["Bonney R.", "Irwin A."]',
        "key_works": '["Citizen Science (1995)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_592",
        "name_en": "Innovation Measurement for SMEs",
        "name_ja": "中小企業向けイノベーション測定",
        "definition": "中小企業のイノベーション活動（製品・プロセス・組織・マーケティング）を適切に把握するための指標と調査手法を指す。大企業向けR&D指標が中小企業には適合しにくいという課題への対処を扱う。",
        "impact_summary": "中小企業のイノベーション実態を正確に把握し、効果的な支援政策の設計に役立てる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "measurement_framework",
        "era_start": 2005,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "中小企業イノベーション,SME指標,中小企業調査,イノベーション測定",
        "keywords_en": "SME innovation measurement,SME indicators,small firm survey,innovation metrics",
        "key_researchers": '["Wolter K.", "Bhattacharya M."]',
        "key_works": '["Innovation in Small Firms (2000)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_593",
        "name_en": "Grand Challenge Programs",
        "name_ja": "グランドチャレンジプログラム",
        "definition": "社会的な難題（癌・貧困・気候変動等）の解決に向けて公的資金と民間資本を集中的に投入し、競争的問題解決を促進するミッション型プログラムを指す。X Prizeやゲイツ財団のGCHが典型例である。",
        "impact_summary": "特定の社会的課題への解決策開発を賞金・評判・使命感を通じて民間イノベーターに促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "challenge_driven",
        "keywords_ja": "グランドチャレンジ,賞金競争,ミッション型研究,社会的課題解決",
        "keywords_en": "grand challenge,prize competition,mission-driven research,social problem solving",
        "key_researchers": '["Mowery D.C.", "Murray F."]',
        "key_works": '["Prizes and the Challenge of Innovation (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_594",
        "name_en": "Innovation Policy Narratives",
        "name_ja": "イノベーション政策ナラティブ",
        "definition": "政策立案者・産業界・メディアがイノベーションについて語る言語的枠組みや物語を分析する研究分野を指す。ナラティブが政策アジェンダ設定・資源配分・制度設計に与える影響を検討する。",
        "impact_summary": "イノベーション政策の言語的構築過程を明らかにし、政策形成の権力関係や偏見を批判的に分析する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "critical_innovation_studies",
        "era_start": 2005,
        "innovation_type": "policy",
        "cognitive_mechanism": "discursive",
        "keywords_ja": "政策ナラティブ,言語分析,政策言説,イノベーション物語",
        "keywords_en": "policy narrative,discourse analysis,policy framing,innovation storyline",
        "key_researchers": '["Mazzucato M.", "Romer P."]',
        "key_works": '["The Entrepreneurial State (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_595",
        "name_en": "Industry 5.0 Policy",
        "name_ja": "インダストリー5.0政策",
        "definition": "人間中心・持続可能・レジリエントな産業を目指すIndustry 5.0の概念を政策設計に組み込む枠組みを指す。EUのIndustry 5.0戦略が先行事例であり、自動化と人間の協働を強調する。",
        "impact_summary": "技術中心のIndustry 4.0を超えて人間的価値と持続可能性を産業政策の核心に位置づける。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2021,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "インダストリー5.0,人間中心産業,持続可能製造,EU産業政策",
        "keywords_en": "Industry 5.0,human-centric industry,sustainable manufacturing,EU industrial policy",
        "key_researchers": '["European Commission", "Floridi L."]',
        "key_works": '["Industry 5.0: Towards a Sustainable, Human-Centric (2021)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_596",
        "name_en": "STI Policy for Climate Mitigation",
        "name_ja": "気候変動緩和のためのSTI政策",
        "definition": "温室効果ガス排出削減に向けたクリーンエネルギー・低炭素技術・炭素回収等の開発・普及を促進するSTI政策を指す。炭素税・排出権取引・再エネ補助・技術ロードマップが主要手段である。",
        "impact_summary": "エネルギーシステムの脱炭素化を技術革新と政策的誘因の組み合わせによって加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 1992,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "気候変動STI,再エネ政策,クリーンテック,低炭素イノベーション",
        "keywords_en": "climate STI policy,renewable energy policy,clean tech,low-carbon innovation",
        "key_researchers": '["Fischer C.", "Newell R.G."]',
        "key_works": '["Environmental and Technology Policies for Climate Mitigation (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_597",
        "name_en": "Digital Twin Policy Framework",
        "name_ja": "デジタルツイン政策フレームワーク",
        "definition": "物理システムのデジタル複製（デジタルツイン）の構築・標準化・データ共有・ガバナンスに関する政策枠組みを指す。スマートシティ・製造・インフラ管理等での活用が政策的関心を集めている。",
        "impact_summary": "デジタルツイン技術の社会的展開を促進しつつ、データ主権・プライバシー・相互運用性の課題に対処する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "digital_governance",
        "era_start": 2018,
        "innovation_type": "policy",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "デジタルツイン,政策フレームワーク,データ共有,スマートシティ",
        "keywords_en": "digital twin policy,data sharing,smart city,interoperability",
        "key_researchers": '["Grieves M.", "Bolton A."]',
        "key_works": '["Digital Twin: Manufacturing Excellence (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_598",
        "name_en": "Post-COVID Innovation Policy",
        "name_ja": "ポストコロナイノベーション政策",
        "definition": "COVID-19パンデミックからの経済・社会回復を契機として設計される新たなイノベーション政策を指す。デジタル転換加速・グリーン回復・保健イノベーション・レジリエンス強化が主要テーマとなる。",
        "impact_summary": "危機からの回復を単なる復旧に留めず、より持続可能で強靭な社会への転換の機会として活用する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 2020,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "ポストコロナ政策,グリーン回復,デジタル転換,レジリエンス",
        "keywords_en": "post-COVID policy,green recovery,digital transformation,resilience",
        "key_researchers": '["Mazzucato M.", "Bloom N."]',
        "key_works": '["Rethinking Value in Health Innovation (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_599",
        "name_en": "Research Integrity Policy",
        "name_ja": "研究誠実性政策",
        "definition": "研究の倫理・誠実性・再現可能性を確保するための制度的枠組みを指す。不正行為防止・データ管理・利益相反開示・査読改革等が主要政策課題である。",
        "impact_summary": "科学的知識の信頼性を確保し、研究資金の無駄遣いと社会的信頼の損失を防ぐ。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 1990,
        "innovation_type": "institutional",
        "cognitive_mechanism": "ethical",
        "keywords_ja": "研究誠実性,再現可能性,研究不正,研究倫理政策",
        "keywords_en": "research integrity,reproducibility,research misconduct,research ethics policy",
        "key_researchers": '["Steneck N.H.", "Macrina F.L."]',
        "key_works": '["Introduction to the Responsible Conduct of Research (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_600",
        "name_en": "Innovation Accounting",
        "name_ja": "イノベーション会計",
        "definition": "イノベーション活動への投資と成果を財務・非財務の両面から体系的に測定・報告する手法を指す。無形資産会計・R&D資本化・イノベーションROI等が含まれ、企業と政策立案の意思決定を支援する。",
        "impact_summary": "イノベーション投資の価値創造メカニズムを定量化し、より合理的な資源配分を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "measurement_framework",
        "era_start": 2000,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "イノベーション会計,無形資産,R&D資本化,イノベーションROI",
        "keywords_en": "innovation accounting,intangible assets,R&D capitalization,innovation ROI",
        "key_researchers": '["Lev B.", "Zhen W."]',
        "key_works": '["Intangibles (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_601",
        "name_en": "Platform Governance for Innovation",
        "name_ja": "イノベーションのためのプラットフォームガバナンス",
        "definition": "デジタルプラットフォームを通じたイノベーション創出を促進するガバナンス枠組みを指す。API開示・データポータビリティ・エコシステム規則・参加者保護が主要課題である。",
        "impact_summary": "プラットフォーム型イノベーションエコシステムの公正性と生産性を同時に高める制度基盤を整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "platform_economics",
        "era_start": 2010,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "プラットフォームガバナンス,API開示,データポータビリティ,エコシステム規制",
        "keywords_en": "platform governance,API disclosure,data portability,ecosystem rules",
        "key_researchers": '["Rochet J.C.", "Tirole J."]',
        "key_works": '["Two-Sided Markets (2003)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_602",
        "name_en": "Standards Setting Organizations Policy",
        "name_ja": "標準化機関政策",
        "definition": "技術標準を策定する機関（ISO・IEC・ITU・ETSI等）の運営・参加・ガバナンスに関する政策課題を指す。標準必須特許・参加バランス・スピード・開放性が主要争点である。",
        "impact_summary": "技術標準を通じて相互運用性・安全性・市場形成に影響し、イノベーション競争の枠組みを規定する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regulatory_theory",
        "era_start": 1990,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "標準化機関,ISO,標準必須特許,技術標準ガバナンス",
        "keywords_en": "standards setting organizations,ISO,SEP,technical standards governance",
        "key_researchers": '["Blind K.", "Galetovic A."]',
        "key_works": '["The Economics of Standard Essential Patents (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_603",
        "name_en": "Defense Technology Spinoff Policy",
        "name_ja": "防衛技術スピンオフ政策",
        "definition": "軍事・防衛目的で開発された技術を民間産業・社会に転用（スピンオフ）するプロセスを促進する政策を指す。インターネット・GPS・ドローン等が歴史的な軍民転用の代表例である。",
        "impact_summary": "防衛R&D投資の民間経済的恩恵を最大化し、デュアルユース技術の社会実装を加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 1970,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "防衛スピンオフ,軍民転用,デュアルユース,DARPA",
        "keywords_en": "defense spinoff,military-civilian transfer,dual use,DARPA",
        "key_researchers": '["Mowery D.C.", "Rosenberg N."]',
        "key_works": '["The Oxford Handbook of Innovation (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_604",
        "name_en": "Gender and Innovation Policy",
        "name_ja": "ジェンダーとイノベーション政策",
        "definition": "研究・イノベーション活動におけるジェンダー不平等を是正し、多様性を促進するための政策を指す。STEM分野への女性参入促進・研究コンテンツへのジェンダー分析統合・調達基準等が含まれる。",
        "impact_summary": "イノベーション人材の多様性を高め、より包括的で公正な研究成果と市場応用を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "inclusive_innovation",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "inclusive",
        "keywords_ja": "ジェンダーイノベーション,女性STEM,多様性政策,包括的研究",
        "keywords_en": "gender innovation,women in STEM,diversity policy,gendered innovation",
        "key_researchers": '["Schiebinger L.", "Schraudner M."]',
        "key_works": '["Gendered Innovations (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_605",
        "name_en": "Space Economy Policy",
        "name_ja": "宇宙経済政策",
        "definition": "宇宙産業の商業化・競争力強化・国際協力・安全保障を促進する政策の総称を指す。ロケット規制緩和・衛星軌道管理・月面資源利用・宇宙交通管理等が主要課題である。",
        "impact_summary": "新宇宙時代の産業競争力確保と持続可能な宇宙利用のための制度基盤を整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "宇宙経済,ニュースペース,宇宙政策,軌道管理",
        "keywords_en": "space economy,new space,space policy,orbital management",
        "key_researchers": '["Hertzfeld H.R.", "Johnson-Freese J."]',
        "key_works": '["Space as a Strategic Asset (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_606",
        "name_en": "Innovation Finance Measurement",
        "name_ja": "イノベーション金融測定",
        "definition": "ベンチャーキャピタル・エンジェル投資・クラウドファンディング・公的融資等のイノベーション向け金融の規模・構造・効果を測定する手法を指す。資金ギャップ分析や生態系評価に活用される。",
        "impact_summary": "イノベーション資金調達の実態を把握し、金融政策と産業政策の連携を強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_finance",
        "era_start": 2000,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "VC測定,エンジェル投資,スタートアップ金融,資金ギャップ",
        "keywords_en": "VC measurement,angel investment,startup finance,funding gap analysis",
        "key_researchers": '["Cumming D.", "Block J."]',
        "key_works": '["Venture Capital and the Finance of Innovation (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_607",
        "name_en": "Public-Private Partnership in STI",
        "name_ja": "STIにおける官民連携",
        "definition": "政府と民間が共同でR&D・イノベーションインフラ・技術実証に投資する連携形態を指す。共同研究センター・産学官コンソーシアム・ベンチャーファンドへの公的出資等が含まれる。",
        "impact_summary": "公的資金と民間資本の相乗効果を最大化し、リスク分担を通じてイノベーション投資を拡大する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "triple_helix",
        "era_start": 1990,
        "innovation_type": "institutional",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "官民連携,PPP,共同研究,産学官コンソーシアム",
        "keywords_en": "public-private partnership,PPP,joint research,university-industry-government",
        "key_researchers": '["Buse K.", "Mays N."]',
        "key_works": '["Making Sense of Global Health Governance (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_608",
        "name_en": "Technology Horizon Scanning",
        "name_ja": "テクノロジーホライゾンスキャニング",
        "definition": "政策・戦略・研究目的で新興技術・破壊的変化・潜在的リスクと機会を系統的に探索する手法を指す。英国政府科学庁・EU JRCなどが制度化しており、フォーサイトの前段階として機能する。",
        "impact_summary": "政策立案者が未来の技術変化を早期に認識し、先手の政策対応を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "technology_foresight",
        "era_start": 1990,
        "innovation_type": "process",
        "cognitive_mechanism": "prospective",
        "keywords_ja": "ホライゾンスキャニング,新興技術探索,政策先読み,技術トレンド",
        "keywords_en": "horizon scanning,emerging technology,policy foresight,tech trends",
        "key_researchers": '["Miles I.", "Keenan M."]',
        "key_works": '["Practical Guide to Regional Foresight (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_609",
        "name_en": "Sectoral Innovation Systems Policy",
        "name_ja": "セクター別イノベーションシステム政策",
        "definition": "製薬・自動車・ICT等のセクター別に特化したイノベーションシステムの特性（知識基盤・行為者・制度）を考慮した政策設計の枠組みを指す。",
        "impact_summary": "セクター固有の技術機会・課題・制度条件に適合した的確な政策介入を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sectoral_innovation",
        "era_start": 1998,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "セクター別システム,産業政策,セクター固有,イノベーションシステム",
        "keywords_en": "sectoral innovation system,industry policy,sector-specific,innovation system",
        "key_researchers": '["Malerba F.", "Breschi S."]',
        "key_works": '["Sectoral Systems of Innovation (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_610",
        "name_en": "Demand-Side Innovation Policy",
        "name_ja": "需要側イノベーション政策",
        "definition": "イノベーションの需要（顧客・市場・公共調達）を刺激することで革新的製品・サービスの開発と普及を促進する政策アプローチを指す。鉛客市場・先進的公共調達・Need Statement等が手法として含まれる。",
        "impact_summary": "供給側支援（R&D補助）を補完する需要誘発型政策として新たな市場と産業競争力を形成する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 2005,
        "innovation_type": "policy",
        "cognitive_mechanism": "market_forming",
        "keywords_ja": "需要側政策,公共調達イノベーション,鉛客市場,市場形成",
        "keywords_en": "demand-side policy,innovative procurement,lead market,market formation",
        "key_researchers": '["Edler J.", "Georghiou L."]',
        "key_works": '["Public Procurement and Innovation (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_611",
        "name_en": "Technology Readiness Level Policy Application",
        "name_ja": "技術成熟度レベルの政策応用",
        "definition": "NASA由来のTRL（技術成熟度レベル）スケールを研究開発プログラム管理・ポートフォリオ評価・官民連携設計に応用する政策枠組みを指す。EU Horizon EuropeでもTRLが主要管理指標として採用されている。",
        "impact_summary": "R&Dポートフォリオ全体を可視化し、死の谷克服と技術移転効率を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "measurement_framework",
        "era_start": 1989,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "TRL,技術成熟度,死の谷,R&D管理",
        "keywords_en": "TRL,technology readiness level,valley of death,R&D portfolio management",
        "key_researchers": '["Mankins J.C.", "Héder M."]',
        "key_works": '["Technology Readiness Levels (1995)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_612",
        "name_en": "Inclusive Innovation Metrics",
        "name_ja": "包括的イノベーション指標",
        "definition": "イノベーションの恩恵が社会の広範な層に届いているかを測定する指標体系を指す。低所得者向け技術普及・地域格差・ジェンダーギャップ・デジタルデバイド等を含む。",
        "impact_summary": "イノベーションの包摂性と公平性を可視化し、格差縮小に向けた政策設計に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "inclusive_innovation",
        "era_start": 2010,
        "innovation_type": "measurement",
        "cognitive_mechanism": "inclusive",
        "keywords_ja": "包括的イノベーション,格差測定,デジタルデバイド,公平性指標",
        "keywords_en": "inclusive innovation metrics,inequality measurement,digital divide,equity indicators",
        "key_researchers": '["George G.", "Howard-Grenville J."]',
        "key_works": '["Understanding and Tackling Societal Grand Challenges (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_613",
        "name_en": "Food System Innovation Policy",
        "name_ja": "食料システムイノベーション政策",
        "definition": "食料の生産・加工・流通・消費システム全体の持続可能性・栄養・環境影響を改善するイノベーションを促進する政策を指す。AgTech・精密農業・代替タンパク・食品廃棄削減等が対象である。",
        "impact_summary": "食料安全保障と持続可能な農業システムへの転換を技術イノベーションと政策支援の組み合わせで加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "食料イノベーション,AgTech,精密農業,フードシステム政策",
        "keywords_en": "food system innovation,AgTech,precision agriculture,sustainable food policy",
        "key_researchers": '["Klerkx L.", "Gliessman S."]',
        "key_works": '["Transforming Food Systems for a Rising Billion (2017)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_614",
        "name_en": "Network Analysis of Innovation Systems",
        "name_ja": "イノベーションシステムのネットワーク分析",
        "definition": "特許共同出願・共著論文・共同研究協定・知識フローを社会ネットワーク分析の手法で測定し、イノベーションシステムの構造と動態を可視化するアプローチを指す。",
        "impact_summary": "イノベーション行為者間の知識ネットワークを定量化し、ブローカー・ハブ・構造的空隙を特定する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "network_theory",
        "era_start": 2000,
        "innovation_type": "measurement",
        "cognitive_mechanism": "network",
        "keywords_ja": "ネットワーク分析,知識フロー,共著分析,イノベーションネットワーク",
        "keywords_en": "network analysis,knowledge flow,co-authorship analysis,innovation network",
        "key_researchers": '["Callon M.", "Newman M.E.J."]',
        "key_works": '["The Structure and Dynamics of Scientific Networks (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_615",
        "name_en": "Science Park Performance Indicators",
        "name_ja": "サイエンスパーク成果指標",
        "definition": "サイエンスパーク・テクノポリス・イノベーションセンターの成果（入居企業成長・スピンオフ・雇用創出・特許等）を測定する指標体系を指す。投資対効果と立地選択効果の識別が方法論的課題である。",
        "impact_summary": "サイエンスパーク政策の費用対効果を測定し、公共投資の正当化と運営改善に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "cluster_theory",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "サイエンスパーク評価,スピンオフ測定,雇用創出,投資対効果",
        "keywords_en": "science park evaluation,spinoff measurement,job creation,investment return",
        "key_researchers": '["Colombo M.", "Delmastro M."]',
        "key_works": '["How Effective are Technology Incubators (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_616",
        "name_en": "Economic Complexity and Innovation",
        "name_ja": "経済複雑性とイノベーション",
        "definition": "ハウスマン・ヒダルゴらが開発した経済複雑性指数（ECI）をイノベーション能力の代理指標として活用する分析枠組みを指す。産業多様性・関連知識・能力蓄積がイノベーション基盤を形成するとみる。",
        "impact_summary": "国の産業構造の複雑性が長期的なイノベーション能力・経済成長と強い相関を持つことを示す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "complexity_economics",
        "era_start": 2009,
        "innovation_type": "measurement",
        "cognitive_mechanism": "complexity",
        "keywords_ja": "経済複雑性,ECI,産業多様化,関連多様化",
        "keywords_en": "economic complexity,ECI,industrial diversification,related variety",
        "key_researchers": '["Hidalgo C.A.", "Hausmann R."]',
        "key_works": '["The Building Blocks of Economic Complexity (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_617",
        "name_en": "Pharmaceutical Innovation Policy",
        "name_ja": "製薬イノベーション政策",
        "definition": "新薬・ワクチン・医療機器の開発促進・承認迅速化・アクセス確保を目指す政策の総称を指す。希少疾患法・優先審査・プッシュ/プル型インセンティブ・知財とアクセスのバランスが主要課題である。",
        "impact_summary": "医薬品イノベーションの社会的便益を最大化しながら費用と公平なアクセスの問題に対処する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "health_innovation",
        "era_start": 1983,
        "innovation_type": "policy",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "製薬政策,希少疾患薬,ワクチン政策,医薬品アクセス",
        "keywords_en": "pharmaceutical policy,orphan drug,vaccine policy,drug access",
        "key_researchers": '["DiMasi J.A.", "Grabowski H.G."]',
        "key_works": '["The Price of Innovation (2003)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_618",
        "name_en": "Intellectual Property Rights and Innovation",
        "name_ja": "知的財産権とイノベーション",
        "definition": "特許・著作権・商標・企業秘密等の知的財産制度がイノベーションインセンティブ・知識拡散・競争に与える影響を分析する研究分野を指す。強い保護と弱い保護のトレードオフが中心的論点である。",
        "impact_summary": "知的財産制度の設計がイノベーションの動機・速度・方向性に根本的影響を与えることを明らかにする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "economics_of_innovation",
        "era_start": 1960,
        "innovation_type": "institutional",
        "cognitive_mechanism": "incentive",
        "keywords_ja": "知的財産,特許制度,イノベーションインセンティブ,知識拡散",
        "keywords_en": "intellectual property rights,patent system,innovation incentive,knowledge diffusion",
        "key_researchers": '["Arrow K.J.", "Scotchmer S."]',
        "key_works": '["Innovation and Incentives (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_619",
        "name_en": "Evidence Synthesis for Policy",
        "name_ja": "政策のためのエビデンス統合",
        "definition": "政策決定に活用するため、複数の研究知見を体系的にまとめるメタ分析・系統的レビュー・ラピッドレビュー等の手法を指す。コクラン・キャンベル共同計画が代表的な制度的枠組みである。",
        "impact_summary": "単一研究の限界を超えた強固な証拠基盤を政策立案者に提供し、エビデンスに基づく意思決定を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "evidence_based_policy",
        "era_start": 1993,
        "innovation_type": "methodology",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "メタ分析,系統的レビュー,コクラン,エビデンス統合",
        "keywords_en": "meta-analysis,systematic review,Cochrane,evidence synthesis",
        "key_researchers": '["Higgins J.P.T.", "Green S."]',
        "key_works": '["Cochrane Handbook for Systematic Reviews (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_620",
        "name_en": "Open Government Data for Innovation",
        "name_ja": "イノベーションのためのオープン政府データ",
        "definition": "政府が保有するデータを開放し、民間企業・研究者・市民が二次利用することで新たなサービス・知識・政策改善を生み出す取り組みを指す。オープンデータ標準・ライセンス・品質が主要課題である。",
        "impact_summary": "公的データの商業・社会的価値を開放し、データ駆動型イノベーションエコシステムを育成する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_government",
        "era_start": 2009,
        "innovation_type": "policy",
        "cognitive_mechanism": "open",
        "keywords_ja": "オープンデータ,政府データ,データ利活用,データ駆動イノベーション",
        "keywords_en": "open government data,data reuse,data-driven innovation,open data standard",
        "key_researchers": '["Davies T.", "Bates J."]',
        "key_works": '["The Promise of Open Data (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
]

conn = sqlite3.connect(db_path)
cursor = conn.cursor()
for e in entries:
    cursor.execute("""
        INSERT OR REPLACE INTO innovation_theory
        (id, name_en, name_ja, definition, impact_summary, subfield, school_of_thought,
         era_start, innovation_type, cognitive_mechanism, keywords_ja, keywords_en,
         key_researchers, key_works, status, source_reliability, data_completeness,
         created_at, updated_at)
        VALUES (:id, :name_en, :name_ja, :definition, :impact_summary, :subfield,
                :school_of_thought, :era_start, :innovation_type, :cognitive_mechanism,
                :keywords_ja, :keywords_en, :key_researchers, :key_works, :status,
                :source_reliability, :data_completeness, :created_at, :updated_at)
    """, e)
conn.commit()
conn.close()
print(f"Inserted {len(entries)} entries")
