#!/usr/bin/env python3
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
    ("inno_digi_401","テクノロジーとフェアネス：アルゴリズム監査","Technology and Fairness: Algorithm Audit","アルゴリズム監査は採用・融資・医療・刑事司法等のAI意思決定システムの公平性・説明可能性を独立機関が検証する。Raji & Buolamwini(2019)はGenderShadesでGAFA顔認識の人種・性別精度差を暴露した。EU AI Act(2024)はHigh-Risk AIに第三者適合評価を義務付ける。MozillaAI Observatory・AlgorithmWatchが市民社会監視機能を担う。","platform_digital_innovation","AI規制・ガバナンス",2019,None,"macro","AI全般","AI監査設計","AIシステムの公平性を独立評価する際","アルゴリズム監査はどのようなAI差別リスクを特定するか","内部評価のみ","アルゴリズム監査,公平性,GenderShades,EU AI Act","algorithm audit,fairness,GenderShades,EU AI Act","active","primary",82,'["Joy Buolamwini","Inioluwa Raji"]','["Raji Buolamwini 2019","EU AI Act 2024"]',"バイアス検出率・コンプライアンス"),
    ("inno_digi_402","マシンラーニングエンジニアリングとMLOps","Machine Learning Engineering and MLOps","MLOpsはモデル開発から本番展開・監視まで機械学習ライフサイクルを管理するDevOpsの拡張。Sculley et al.(2015)の「Hidden Technical Debt in ML Systems」が本番ML特有の課題を整理した。Kubeflow・MLflow・SageMaker・Vertexが主要プラットフォーム。Feature Store・モデルレジストリ・ドリフト検知がMLOpsの核心コンポーネント。","platform_digital_innovation","AI・機械学習",2019,None,"micro","AI開発","MLOpsシステム設計","本番AIシステムを信頼性高く運用する際","MLOpsはMLシステムの信頼性をどう担保するか","実験専用ML","MLOps,Feature Store,Kubeflow,MLflow","MLOps,Feature Store,Kubeflow,MLflow","active","secondary",78,'["Sculley et al.","Mark Treveil"]','["Sculley et al. 2015 NIPS","MLflow Docs 2023"]',"デプロイ頻度・モデル精度維持率"),
    ("inno_digi_403","デジタル社会インフラとレジリエンス","Digital Social Infrastructure and Resilience","デジタル社会インフラ(電子政府・デジタルID・公共クラウド・決済基盤)のレジリエンス設計は国家機能継続の条件となる。COVID-19パンデミックで各国の給付金デジタル配布能力の差が顕在化した。Dunleavy et al.(2006)の「デジタル時代のガバナンス」が公共デジタルインフラの設計原理を論じた。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"macro","公共・政府","デジタル公共インフラ設計","公共デジタルサービスのレジリエンスを確保する際","デジタル社会インフラはどのような危機対応能力を支えるか","アナログ行政","デジタル社会インフラ,レジリエンス,電子政府,COVID","digital social infrastructure,resilience,e-government,COVID","active","secondary",76,'["Patrick Dunleavy"]','["Dunleavy et al. 2006","OECD Digital Government 2022"]',"サービス継続率・復旧時間"),
    ("inno_digi_404","5Gスライシングとバーティカル産業","5G Network Slicing and Vertical Industries","5Gネットワークスライシングは単一物理インフラ上に仮想的に独立したネットワークを多重構成し製造・医療・自動運転等の垂直産業に最適化された通信を提供する。NGMN Alliance(2015)がスライシング概念を5Gアーキテクチャの核心として定式化した。Industry4.0ユースケースでのプライベート5G展開がボッシュ・BMW・BMWライプツィヒ工場で実証された。","platform_digital_innovation","モバイル通信・5G",2020,None,"meso","製造・医療・交通","5G産業垂直適用","5Gを産業DXに活用する際","5Gスライシングはどのような産業特化通信を実現するか","共用帯域型通信","5Gスライシング,プライベート5G,Industry4.0","5G slicing,private 5G,Industry4.0","active","secondary",76,'["NGMN Alliance","Ericsson Research"]','["NGMN 2015","Ericsson Private 5G Report 2022"]',"遅延・信頼性・スループット"),
    ("inno_digi_405","ヘルステックとウェアラブルデータ産業化","HealthTech and Wearable Data Industrialization","スマートウォッチ・連続血糖計・スマート血圧計のデータが保険・治験・公衆衛生の産業利用に転換されつつある。Fitbit(Google)・Apple HealthKit・Samsung Health等がデータプラットフォームを構築する。デジタルバイオマーカーの規制承認(FDA 2022)がウェアラブルデータの医療的価値を公式化した。","platform_digital_innovation","デジタルトランスフォーメーション",2022,None,"meso","医療・保険","ウェアラブル産業化設計","ウェアラブルデータを事業化する際","ウェアラブルデータはどのような医療産業価値を持つか","単発診断","ウェアラブル,デジタルバイオマーカー,Apple Health,保険","wearable,digital biomarker,Apple Health,insurance","active","secondary",76,'["Eric Topol","FDA Digital Health"]','["FDA Digital Biomarker 2022","Apple Health Study 2022"]',"バイオマーカー精度・採用数"),
    ("inno_digi_406","デジタル教科書と学習コンテンツ産業","Digital Textbook and Learning Content Industry","電子教科書・OER(Open Educational Resources)・学習管理システムが教育出版産業を変革する。Pearson・McGraw-Hill・Wileyのデジタル転換が伝統的教科書ビジネスを再定義した。OER Commons・MIT OpenCourseWareが高等教育コンテンツの開放的共有を推進する。AIによる教科書コンテンツの個別最適化・インタラクティブ化が次世代学習材料を形成している。","platform_digital_innovation","デジタルトランスフォーメーション",2010,None,"meso","教育","デジタル教育コンテンツ戦略","教育コンテンツのデジタル化を設計する際","デジタル教科書はどのような教育体験を改善するか","物理教科書","デジタル教科書,OER,MIT OCW,Pearson","digital textbook,OER,MIT OCW,Pearson","active","secondary",74,'["Pearson Digital"]','["MIT OCW 2002","OER Commons 2022"]',"採用率・学習成果"),
    ("inno_digi_407","クリーンエネルギーデジタルシフト","Clean Energy Digital Shift","再生可能エネルギーのコスト低下(太陽光ラーニングカーブ)とデジタル管理の組み合わせがエネルギートランジションを加速する。BloombergNEF(2023)はオンショア風力・太陽光が最安の発電源となったことを確認した。AIによる発電量予測・需要予測・市場入札最適化がグリッド統合を実現する。","platform_digital_innovation","エネルギー・環境DX",2020,None,"macro","エネルギー","クリーンエネルギーDX","再エネのデジタル管理を実現する際","デジタル技術は再エネの系統統合をどう改善するか","化石燃料発電","クリーンエネルギー,太陽光,AI予測,BloombergNEF","clean energy,solar,AI forecast,BloombergNEF","active","secondary",78,'["BloombergNEF"]','["BloombergNEF BNEF 2023 Energy Outlook"]',"発電コスト・系統統合率"),
    ("inno_digi_408","デジタルツールと市民科学","Digital Tools and Citizen Science","iNaturalist・Galaxy Zoo・Foldit等の市民科学プラットフォームは一般市民をデータ収集・仮説検証に参加させて科学研究を加速する。Bonney et al.(2009)が市民科学の定義・類型・科学的価値を体系化した。CovidScan・Air Quality Egg等がコロナ・環境モニタリングで市民参加型データ収集を実現した。","platform_digital_innovation","データ経済",2009,None,"macro","科学研究","市民科学プラットフォーム設計","大規模データ収集を低コストで実現する際","市民科学は科学研究のどの課題を解決するか","専門研究者のみ","市民科学,iNaturalist,クラウドソーシング,Galaxy Zoo","citizen science,iNaturalist,crowdsourcing,Galaxy Zoo","active","secondary",76,'["Rick Bonney","Cornell Lab"]','["Bonney et al. 2009 Science","iNaturalist Platform Stats 2023"]',"データ収集量・論文数"),
    ("inno_digi_409","デジタル経済の環境コスト","Environmental Cost of Digital Economy","デジタル経済のCO2排出(データセンター・ネットワーク・端末製造・電子廃棄物)は全世界の2-4%を占める。Freitag et al.(2021)は2010-2020年のICTエネルギー消費が予測に反し横ばいを維持したことを示した。電子廃棄物(E-Waste)は年間5700万トンに達しリサイクル率は20%未満(UN 2021)。AI推論の急増がデータセンター電力需要を再び急上昇させるリスクがある。","platform_digital_innovation","エネルギー・環境DX",2021,None,"macro","環境・ICT","デジタル環境コスト評価","デジタルサービスの環境影響を評価する際","デジタル経済はどのような環境コストを持つか","物理産業","デジタル環境コスト,E-Waste,データセンターCO2","digital environmental cost,e-waste,data center CO2","active","primary",78,'["Charlotte Freitag","UN E-Waste Monitor"]','["Freitag et al. 2021","UN E-Waste Monitor 2020"]',"CO2排出量・E-Waste量"),
    ("inno_digi_410","ナレッジグラフと企業知識管理","Knowledge Graph and Enterprise Knowledge Management","ナレッジグラフはエンティティ・関係・属性を構造化したグラフデータベースで検索精度・推薦精度・AIコンテキスト理解を向上させる。Google Knowledge Graph(2012)・WikiData・LinkedInEconomicGraph・Amazon Productグラフが産業事例。RAG(Retrieval-Augmented Generation)アーキテクチャがナレッジグラフとLLMを統合したAIシステムの標準となりつつある。","platform_digital_innovation","AI・機械学習",2012,None,"meso","検索・企業IT","ナレッジグラフ構築","構造化知識をAIシステムに統合する際","ナレッジグラフはどのようなAI性能向上をもたらすか","非構造化テキストのみ","ナレッジグラフ,Knowledge Graph,RAG,Wikidata","knowledge graph,Knowledge Graph,RAG,Wikidata","active","secondary",78,'["Tom Mitchell","Google Research"]','["Google Knowledge Graph Launch 2012","RAG Survey 2023"]',"検索精度・回答精度"),
    ("inno_digi_411","マーテックとカスタマーデータプラットフォーム","MarTech and Customer Data Platform","マーテック(MarTech)は顧客データ収集・統合・活用のデジタルマーケティング技術スタック。CDP(Customer Data Platform)は複数ソースの顧客データをリアルタイム統合しパーソナライゼーションを実現する。Salesforce Marketing Cloud・Adobe Experience Platform・Segment(Twilio)が主要CDPを提供する。Cookieless転換(2024)でファーストパーティデータの重要性が急騰した。","platform_digital_innovation","デジタル広告経済",2018,None,"meso","マーケティング","CDP設計","顧客データの一元管理と活用","CDPはマーケティング精度をどう向上させるか","サイロ型顧客データ","マーテック,CDP,ファーストパーティ,Salesforce","MarTech,CDP,first-party data,Salesforce","active","secondary",76,'["Gartner MarTech"]','["Gartner MarTech 2022","Twilio CDP Report 2022"]',"マーケティングROI・CDP統合率"),
    ("inno_digi_412","AIと福祉政策の最適化","AI and Welfare Policy Optimization","AIは貧困ターゲティング・社会保護給付最適化・フードスタンプ詐欺検知に応用される。Kasy & Sautmann(2021)はAIによる援助配分の最適化が格差是正に貢献する理論的根拠を示した。インドジャムプラ・ケニアGDPdictデータを用いた貧困マッピングがAI貧困推定の先行研究となった。プライバシー・スティグマ・デジタル排除が福祉AIの倫理課題となる。","platform_digital_innovation","AI・機械学習",2021,None,"macro","社会政策","AI福祉政策設計","社会保護の効率化にAIを活用する際","AIは福祉政策配分をどう改善するか","人手審査","AI福祉,貧困マッピング,社会保護,スティグマ","AI welfare,poverty mapping,social protection,stigma","active","secondary",74,'["Maximilian Kasy","Anja Sautmann"]','["Kasy Sautmann 2021","World Bank AI Poverty Mapping 2022"]',"ターゲティング精度・給付到達率"),
    ("inno_digi_413","量子機械学習の可能性と限界","Quantum Machine Learning: Potential and Limitations","QML(Quantum Machine Learning)は量子コンピュータを機械学習に適用し指数的な高速化の可能性を探る。Biamonte et al.(2017)がQMLの理論的基礎と限界を体系化した。量子カーネル法・変分量子回路(VQC)が近期量子コンピュータ(NISQ)向け手法として研究される。Dequantization(量子優位の古典代替)が示すように量子機械学習の実際の利点は限定的との指摘もある。","platform_digital_innovation","量子コンピューティング",2017,None,"macro","AI・量子","量子ML可能性評価","量子コンピュータのML適用を評価する際","QMLはどのようなML課題で古典MLに優位するか","古典ML","量子機械学習,QML,NISQ,変分量子回路","quantum machine learning,QML,NISQ,variational quantum circuit","active","secondary",72,'["Jacob Biamonte","Maria Schuld"]','["Biamonte et al. 2017 Nature","Schuld et al. 2021"]',"量子優位達成条件"),
    ("inno_digi_414","デジタルプラットフォームとデータ経済の次段階","Digital Platform and Next Stage of Data Economy","データエコノミーの次段階は個人データの主権化・合成データ・フェデレーテッドデータの三方向で展開される。個人情報保護法・GDPRの執行強化でデータ仲介ビジネスモデルが変容する。Synthea・Gretel.ai等の合成データプラットフォームがプライバシー保護データ活用を実現する。","platform_digital_innovation","データ経済",2022,None,"macro","データ産業","次世代データ戦略","データ活用の新モデルを設計する際","次世代データ経済はどのような新ビジネスモデルを生むか","個人データ収集","合成データ,フェデレーテッドデータ,Gretel,データ主権","synthetic data,federated data,Gretel,data sovereignty","active","secondary",74,'["Gretel.ai Team"]','["Gretel Synthetic Data Report 2022","GDPR Enforcement 2023"]',"合成データ品質・プライバシー保護率"),
    ("inno_digi_415","デジタルヘルスケアのインターオペラビリティ","Digital Healthcare Interoperability","医療データの相互運用性はFHIR(Fast Healthcare Interoperability Resources・HL7)が国際標準として確立し電子カルテ間連携を実現する。米国CMS最終規則(2020)はFHIRベースのAPI実装を病院に義務付けた。Apple Health Records・CommonHealthがFHIRでEHRデータを患者管理下に置く。医療データサイロが患者安全・研究効率を阻害する問題の解消が目標となっている。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"meso","医療","医療データ相互運用設計","電子カルテ連携システムを設計する際","医療データ相互運用性はどのような患者安全改善をもたらすか","サイロ型EHR","FHIR,HL7,EHR,医療相互運用性","FHIR,HL7,EHR,healthcare interoperability","active","secondary",76,'["HL7 International","CMS Staff"]','["CMS Final Rule 2020","FHIR R4 2019"]',"データ連携率・患者安全指標"),
    ("inno_digi_416","プラットフォームのピボット戦略","Platform Pivot Strategy","プラットフォーム企業のピボット(事業転換)はコアコンピタンスを維持しながら市場機会に応じて事業領域を転換する戦略。Ries(2011)のLeanStartupがピボットを方法論として定式化した。YouTubeのゲームツールからビデオプラットフォームへの転換・Slackのゲームからメッセージングへの転換が典型事例。Andreessen(2011)の「Software is Eating the World」がソフトウェアピボットの一般化を示した。","platform_digital_innovation","プラットフォーム競争戦略",2011,None,"micro","スタートアップ","ピボット戦略設計","事業方向を転換する際","ピボットはどのような条件で成功するか","硬直した戦略","ピボット,LeanStartup,Slack,YouTube","pivot,LeanStartup,Slack,YouTube","active","secondary",76,'["Eric Ries","Marc Andreessen"]','["Ries 2011 Lean Startup","Andreessen 2011 WSJ"]',"ピボット成功率・成長率"),
    ("inno_digi_417","AIとサステナビリティ戦略の統合","AI and Sustainability Strategy Integration","AI・機械学習はEnergy Management System・GHG排出量計算・循環経済最適化・農業資源管理の持続可能性を向上させる。Vinuesa et al.(2020)はAIが17つのSDGsの達成に与える影響を体系的に分析しポジティブ・ネガティブ両面を示した。企業のAI for Sustainabilityプログラムが戦略的優先課題として確立している。","platform_digital_innovation","エネルギー・環境DX",2020,None,"macro","企業サステナビリティ","AI持続可能性統合","AI戦略とサステナビリティを統合する際","AIはSDGs達成にどのような貢献とリスクをもたらすか","非統合サステナビリティ","AI,SDGs,サステナビリティ,Vinuesa","AI,SDGs,sustainability,Vinuesa","active","primary",80,'["Ricardo Vinuesa","Yoshua Bengio"]','["Vinuesa et al. 2020 Nature Communications"]',"SDGs達成度・AI環境コスト"),
    ("inno_digi_418","デジタル文化遺産保存と3Dデジタイゼーション","Digital Cultural Heritage Preservation and 3D Digitization","Cyark・Google Arts & Culture・スミソニアン博物館の3Dデジタイゼーションプロジェクトが文化遺産を高精度3Dデータとして保存する。Corona Pandemic期間にバーチャルミュージアム訪問が急増しデジタルアクセスの価値を示した。UNESCO・ICOMOS がデジタル文化遺産保存の倫理的指針を整備している。","platform_digital_innovation","AR・VR・空間コンピューティング",2018,None,"meso","文化遺産","デジタル文化遺産設計","文化遺産をデジタル保存する際","デジタル化は文化遺産へのアクセスをどう拡大するか","物理展示のみ","デジタル文化遺産,3D,バーチャルミュージアム,Cyark","digital cultural heritage,3D,virtual museum,Cyark","active","secondary",72,'["UNESCO Heritage","Google Arts & Culture"]','["UNESCO Digital Heritage 2021","Google Arts & Culture Stats 2023"]',"アクセス数・保存品質"),
    ("inno_digi_419","プラットフォームとフリーランス経済の学習・スキル","Platform and Freelance Economy Learning and Skills","Upwork・Fiverr・Toptal等のフリーランスプラットフォームは仕事のスキル要件と報酬をリアルタイムで市場価格化する。Autor & Salomons(2018)は自動化時代のスキル需要転換として「新しい職業の出現」メカニズムを分析した。Coursera・LinkedIn Learningとフリーランスプラットフォームの統合が「スキル獲得→市場価格化」パイプラインを形成する。","platform_digital_innovation","プラットフォーム労働",2018,None,"meso","フリーランス・教育","フリーランスプラットフォーム設計","スキル市場価格を最適化する際","フリーランスプラットフォームはスキル獲得・評価をどう変えるか","企業内雇用","フリーランス,Upwork,スキル市場,Coursera","freelance,Upwork,skill market,Coursera","active","secondary",74,'["David Autor","Anna Salomons"]','["Autor Salomons 2018","Upwork Freelance Forward 2022"]',"フリーランス収益・スキル採用率"),
    ("inno_digi_420","デジタルヘルスの患者主体モデル","Patient-Centered Model in Digital Health","PHR(Personal Health Record)・患者ポータル・Apple Health等が患者を医療データの能動的管理者に転換する。Ferguson & Frydman(2004)が「患者主体の医療」パラダイムを提唱した。PatientsLikeMe・CureTogether が患者コミュニティの集合知で研究を加速する事例となった。デジタルヘルスのデータポータビリティ(TEFCA,米国)が患者主体モデルの制度基盤を提供する。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"meso","医療","患者主体デジタルヘルス設計","患者中心の医療データ管理を実現する際","患者主体モデルはどのような医療品質改善をもたらすか","医師中心モデル","患者主体,PHR,PatientsLikeMe,TEFCA","patient-centered,PHR,PatientsLikeMe,TEFCA","active","secondary",74,'["Tom Ferguson","Gilles Frydman"]','["Ferguson Frydman 2004","TEFCA 2022 ONC"]',"患者エンゲージメント・医療品質"),
    ("inno_digi_421","デジタルゲームと認知訓練","Digital Games and Cognitive Training","NeuroRacer・BrainHQ等のゲームベース認知訓練ツールが注意力・作業記憶・処理速度の改善効果を実証しようとしている。Anguera et al.(2013)のNatureStudyはNeuroRacerが高齢者の多重課題能力を改善することを示した。Lumosity・Posit Scienceの効果に関する論争(FTC罰金2015)がエビデンス基準を厳格化した。VRゲームとリハビリの統合が神経リハビリテーション新手法として研究される。","platform_digital_innovation","デジタルトランスフォーメーション",2013,None,"meso","医療・教育","ゲーム認知訓練設計","ゲームで認知能力を向上させる際","ゲームベース認知訓練はどのような認知効果を持つか","座学訓練","ゲーム認知訓練,NeuroRacer,VRリハビリ,Lumosity","game cognitive training,NeuroRacer,VR rehabilitation,Lumosity","active","secondary",72,'["Adam Gazzaley","Posit Science"]','["Anguera et al. 2013 Nature","FTC Lumosity 2015"]',"認知改善効果量"),
    ("inno_digi_422","インターネット企業のグローバル展開と地域化","Internet Company Global Expansion and Localization","デジタルプラットフォームのグローバル展開はネットワーク効果と地域参入障壁のトレードオフを伴う。Rugman & Verbeke(2004)の「FSA-CSA」フレームが多国籍企業優位論をデジタル時代に拡張した。Uberの各国撤退・Airbnbの規制対応・TikTokの米国リスクが地域化の複雑性を示す。プラットフォームの「Think Global Act Local」戦略が市場参入の鍵となる。","platform_digital_innovation","デジタルプラットフォーム経済",2016,None,"macro","多国籍デジタル企業","グローバル展開戦略","デジタルプラットフォームの国際化を設計する際","デジタルプラットフォームはどのような地域化課題に直面するか","単一グローバルモデル","グローバル展開,地域化,Uber,TikTok,FSA","global expansion,localization,Uber,TikTok,FSA","active","secondary",76,'["Alan Rugman","Mark Zuckerberg"]','["Rugman Verbeke 2004","Uber Retreat Analysis 2017"]',"市場参入成功率・地域シェア"),
    ("inno_digi_423","AIと人間協調：コグニティブオートメーション","AI and Human Collaboration: Cognitive Automation","コグニティブオートメーションはAIが認知タスクの一部を担い人間の判断・創造性・倫理を補完する協働モデル。Wilson & Daugherty(2018)はAIと人間の協働が単純代替より高い生産性を生む「スーパーマインド」を論じた。Augmentation vs Automation論争が組織設計の核心となっている。","platform_digital_innovation","AI・機械学習",2018,None,"meso","知識産業","コグニティブオートメーション設計","AIと人間の協働を最適化する際","コグニティブオートメーションはどのような人間能力を増幅するか","完全自動化","コグニティブオートメーション,AI協働,スーパーマインド","cognitive automation,AI collaboration,supermind","active","secondary",76,'["H. James Wilson","Paul Daugherty"]','["Wilson Daugherty 2018 HBR"]',"生産性向上・判断品質"),
    ("inno_digi_424","プラットフォームと観光産業変革","Platform and Tourism Industry Transformation","Airbnb・Booking.com・Expedia・Trivago がホテル・フライト・観光体験を一元検索・予約プラットフォーム化した。Airbnb上場(2020)はパンデミック中の需要激減後の急速回復を示し分散型宿泊の強靭性を証明した。観光プラットフォームはDestination Management Organizationの機能を代替し旅行者体験設計の主体となった。","platform_digital_innovation","デジタルプラットフォーム経済",2008,None,"meso","観光・旅行","観光プラットフォーム戦略","観光業のデジタル化を分析する際","観光プラットフォームはどのような観光産業を変革するか","伝統的旅行代理店","観光,Airbnb,Booking.com,Expedia,プラットフォーム","tourism,Airbnb,Booking.com,Expedia,platform","active","secondary",76,'["Airbnb Research"]','["Airbnb S-1 2020","UNWTO Digital Tourism 2022"]',"GMV・旅行者数"),
    ("inno_digi_425","デジタル医療イメージングとAI診断","Digital Medical Imaging and AI Diagnosis","AI医療画像診断(放射線・病理・眼底・皮膚科)はCNNによって専門医レベルの精度を達成した。Gulshan et al.(2016)はGoogleの眼科AIがGoogleレベルの精度で糖尿病網膜症を検出することをNatureに示した。FDA承認AI医療機器は2024年に500件を超えた。医師との協働・説明可能性・保険適用・偽陽性管理が臨床導入の課題となっている。","platform_digital_innovation","AI・機械学習",2016,None,"meso","医療・診断","AI医療画像診断設計","医療診断にAIを導入する際","AIは医療画像診断のどの課題を解決するか","人手診断","AI医療診断,放射線AI,眼底AI,CNN","AI medical imaging,radiology AI,retinal AI,CNN","active","primary",82,'["Vinod Gulshan","Pranav Rajpurkar"]','["Gulshan et al. 2016 JAMA","FDA AI Device List 2024"]',"診断精度・FDA承認数"),
    ("inno_digi_426","プラットフォームと食料廃棄削減","Platform and Food Waste Reduction","TooGoodToGo・OLIO・Flashfood等のフードシェアリングプラットフォームが閉店前余剰食品をマッチングし食料廃棄を削減する。FAO(2019)は世界食料生産の3分の1(13億トン)が廃棄されることを報告した。AIベース在庫予測・ダイナミックプライシング・消費期限最適化が小売・外食の廃棄削減ツールとなる。","platform_digital_innovation","エネルギー・環境DX",2018,None,"meso","食品・流通","フードウェイスト削減プラットフォーム","食料廃棄削減を実現する際","フードシェアリングプラットフォームはどのような食料廃棄を削減するか","廃棄前提","TooGoodToGo,OLIO,フードシェア,食料廃棄","TooGoodToGo,OLIO,food sharing,food waste","active","secondary",74,'["TooGoodToGo Team","FAO Staff"]','["FAO Food Loss 2019","TooGoodToGo Impact Report 2022"]',"廃棄削減量・CO2削減"),
    ("inno_digi_427","プラットフォームとスポーツ産業デジタル化","Platform and Sports Industry Digitalization","スポーツアナリティクス・ファンエンゲージメントプラットフォーム・NFTスポーツコレクタブルがスポーツ産業を変革する。NBAのSports Reference・StatMuseがスポーツデータ民主化をリードした。Sorare・NBA Top Shotのスポーツ系NFTが2021年に急成長した。DAZN・ESPN+・Amazon Prime Videoが放映権の分散化とコード切りを加速している。","platform_digital_innovation","デジタルプラットフォーム経済",2015,None,"meso","スポーツ","スポーツデジタル戦略","スポーツビジネスのデジタル化を分析する際","デジタル化はスポーツ産業のどの収益構造を変えるか","放送独占モデル","スポーツアナリティクス,DAZN,Sorare,NFTスポーツ","sports analytics,DAZN,Sorare,sports NFT","active","secondary",72,'["Billy Beane","DAZN Research"]','["NBA Top Shot 2021","DAZN Streaming Strategy"]',"ファンエンゲージメント・放映収益"),
    ("inno_digi_428","AIによる財務分析と株式市場予測","AI for Financial Analysis and Stock Market Prediction","機械学習・NLP・代替データ(衛星画像・ESGスコア・SNS感情)が定量的投資戦略(クオンツ)と組み合わさる。Two Sigma・D.E.Shaw・Renaissanceが先行するAI運用を牽引する。Cont & Bouchaud(2000)のエージェントモデルが市場の内生的バブル形成を示した。Flash Crash(2010)がアルゴリズムトレーディングの市場リスクを顕在化させた。","platform_digital_innovation","デジタル金融",2016,None,"meso","金融・投資","AIクオンツ戦略","AI駆動の投資分析を設計する際","AIは金融予測のどの精度を向上させるか","人手アナリスト","AI投資,クオンツ,Two Sigma,代替データ","AI investment,quant,Two Sigma,alternative data","active","secondary",76,'["Robert Mercer","David Siegel"]','["Cont Bouchaud 2000","Two Sigma AI Report"]',"予測精度・アルファ"),
    ("inno_digi_429","デジタルイノベーションとジェンダー格差","Digital Innovation and Gender Gap","デジタル産業のジェンダー格差はSTEM教育・採用・昇進・起業の各段階で存在する。McKinsey(2020)は女性のデジタルスキル格差が2030年経済損失1.5兆ドルになると試算した。Girls Who Code・Technovation等が格差是正プログラムを展開する。AI開発のジェンダー偏向(音声認識・医療AI等の精度差)が倫理・安全課題として研究される。","platform_digital_innovation","デジタル包摂",2020,None,"macro","ジェンダー・STEM","ジェンダー格差解消設計","デジタルのジェンダー格差を是正する際","デジタルジェンダー格差はどのような社会経済コストを生むか","ジェンダー非考慮","デジタルジェンダー格差,Girls Who Code,STEM,AI偏向","digital gender gap,Girls Who Code,STEM,AI bias","active","secondary",76,'["McKinsey Women"]','["McKinsey Women Digital 2020","UNESCO STEM Girls 2019"]',"ジェンダー格差指標・STEM女性比率"),
    ("inno_digi_430","クラウドセキュリティとゼロトラスト実装","Cloud Security and Zero Trust Implementation","クラウド環境のセキュリティはVPN境界モデルから「決して信頼せず常に検証する」ゼロトラスト(NIST SP800-207)へ移行する。BeyondCorp(Google 2014)が企業ゼロトラストの先行事例となった。Gartner(2022)は2025年までに大企業の60%がゼロトラストを主要セキュリティ戦略として採用すると予測した。","platform_digital_innovation","サイバーセキュリティ",2020,None,"meso","企業IT","ゼロトラスト設計","クラウド環境のセキュリティアーキテクチャを設計する際","ゼロトラストは従来型セキュリティのどの脆弱性を解消するか","境界防御","ゼロトラスト,NIST,BeyondCorp,クラウドセキュリティ","zero trust,NIST,BeyondCorp,cloud security","active","secondary",78,'["John Kindervag","Google BeyondCorp Team"]','["NIST SP800-207 2020","Google BeyondCorp 2014"]',"侵害件数・認証コスト"),
    ("inno_digi_431","デジタルプラットフォームと自動車産業変革","Digital Platform and Automotive Industry Transformation","自動車産業はEV・自動運転・コネクテッドカー・MaaSの四つの変革軸(CASE)に直面する。Tesla・BMW・Volkswagen・トヨタが「ソフトウェアデファインドビークル(SDV)」への転換を進める。GoogleAndroid Automotive・Apple CarPlayが車載インフォテインメントのプラットフォーム化を推進する。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"macro","自動車産業","自動車デジタル変革","自動車産業のDXを評価する際","デジタル化は自動車産業バリューチェーンをどう再編するか","従来型ガソリン車製造","CASE,SDV,Tesla,Android Automotive","CASE,SDV,Tesla,Android Automotive","active","secondary",78,'["Elon Musk","Oliver Zipse"]','["McKinsey CASE 2021","Google Android Automotive 2020"]',"EV市場シェア・SDV採用率"),
    ("inno_digi_432","ミームとデジタル文化の伝播","Meme and Digital Culture Propagation","インターネットミームはDawkinsの文化的遺伝子単位(1976)がデジタル空間での急速複製・変形・拡散を通じて社会的コミュニケーションの新形態となった。Know Your Meme・Reddit・4chanがミーム文化のハブとして機能する。政治的ミーム工学・ブランドミーム活用・ミーム金融(GameStop事件2021)が社会・経済への影響を示した。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2016,None,"micro","SNS・文化","デジタル文化伝播分析","デジタル文化の拡散メカニズムを分析する際","ミームはデジタル文化コミュニケーションをどう変えるか","従来メディア","ミーム,デジタル文化,GameStop,Reddit","meme,digital culture,GameStop,Reddit","active","secondary",70,'["Richard Dawkins","Limor Shifman"]','["Dawkins 1976 Selfish Gene","Shifman 2014 Memes in Digital Culture"]',"拡散速度・影響指標"),
    ("inno_digi_433","ブロードバンドインフラとデジタル経済格差","Broadband Infrastructure and Digital Economy Inequality","高速インターネット接続の地域格差が都市農村・先進途上国間のデジタル経済格差を固定化する。Koutroumpis(2009)はOECDデータでブロードバンド普及が経済成長に貢献することを実証した。米国BEAD法(2021)・EU DigitalCompass 2030が農村・低収入地域の接続義務化を推進する。SpaceX Starlink衛星ブロードバンドが地理的制約を突破する新インフラとして注目される。","platform_digital_innovation","デジタル包摂",2021,None,"macro","インフラ政策","ブロードバンド普及政策","デジタルインフラの地域格差を解消する際","ブロードバンド格差はどのような経済格差をもたらすか","高速通信普及地域","ブロードバンド格差,Starlink,BEAD法,デジタル経済","broadband gap,Starlink,BEAD Act,digital economy","active","secondary",76,'["Pantelis Koutroumpis"]','["Koutroumpis 2009 TE","BEAD Act 2021"]',"ブロードバンド普及率・経済格差"),
    ("inno_digi_434","クリエイティブAIツールとデザイン産業","Creative AI Tools and Design Industry","Figma AI・Adobe Firefly・Canva AIがデザインワークフローにAIを統合しデザイナーの生産性と創造の幅を拡大する。Adobe(2023)のAI機能はPhotoshop・Illustratorにジェネレーティブ塗りつぶし等を追加し月間ユーザーが急増した。非デザイナーのセルフサービスデザイン化がデザイン民主化をもたらす一方プロデザイナーの価値再定義が求められる。","platform_digital_innovation","生成AI応用",2023,None,"meso","デザイン産業","AIデザインツール導入","デザイン業務のAI化を推進する際","AIデザインツールはデザイン産業をどう変えるか","人手デザイン","AI デザイン,Adobe Firefly,Figma AI,Canva AI","AI design,Adobe Firefly,Figma AI,Canva AI","active","secondary",76,'["Adobe Research","Figma Team"]','["Adobe Firefly Launch 2023","Figma AI 2023"]',"デザイン作成時間・採用率"),
    ("inno_digi_435","プラットフォームとライフサイエンス研究","Platform and Life Sciences Research","Life Science Platformは創薬・臨床試験・生物医学研究のデジタル基盤を提供する。Benchling・Veeva Systems・Medidata(Dassault)が試験管理・規制文書・臨床データを統合管理する。分散型臨床試験(DCT)はデジタルツールで患者をリモート参加させ試験コストと期間を削減する。","platform_digital_innovation","デジタルトランスフォーメーション",2018,None,"meso","ライフサイエンス","ライフサイエンスプラットフォーム設計","創薬・臨床試験のデジタル化を検討する際","ライフサイエンスプラットフォームはどのようなR&D効率化をもたらすか","紙ベース研究管理","ライフサイエンス,Benchling,臨床試験,DCT","life sciences,Benchling,clinical trial,DCT","active","secondary",74,'["Benchling Team","Medidata Solutions"]','["Benchling Case 2022","FDA DCT Guidance 2023"]',"試験コスト・期間削減"),
    ("inno_digi_436","デジタル選挙とデモクラシーインフラ","Digital Election and Democracy Infrastructure","電子投票・デジタル選挙人登録・SNS選挙広告規制・AIファクトチェックが民主的選挙プロセスに影響する。エストニアはインターネット投票(i-Voting,2005-)で投票率・コスト改善を実証した。Cambridge Analytica事件(2016)がMicrotargeting広告の民主主義への脅威を顕在化させた。Verified Voting・選挙安全保障(CISA)が選挙インフラ保護の政策基盤を整備する。","platform_digital_innovation","プラットフォーム規制",2016,None,"macro","民主主義・選挙","デジタル選挙インフラ設計","選挙のデジタル化を安全に進める際","デジタル化は選挙の信頼性・参加率にどう影響するか","紙ベース投票","デジタル選挙,e-Voting,Cambridge Analytica,Microtargeting","digital election,e-voting,Cambridge Analytica,microtargeting","active","secondary",76,'["CISA Staff","Estonian National Electoral Committee"]','["Estonian i-Voting 2019","Cambridge Analytica Report 2018"]',"投票率・選挙セキュリティ"),
    ("inno_digi_437","デジタルインフラの標準化と技術主権","Digitalization of Infrastructure and Technology Sovereignty","EU・中国・インドが国産デジタル技術スタック(クラウド・AI・チップ)の育成で技術主権を追求する。EU「Tech Sovereignty」概念はTechAccelerator・EUCS(EU Cloud Scheme)・Gaia-Xで具体化された。Edler & Boon(2021)は技術主権の経済・安全保障・産業政策の三側面を整理した。","platform_digital_innovation","AI半導体・計算資源",2021,None,"macro","政策・産業","技術主権戦略","デジタル技術の自律性を確保する際","技術主権はどのような政策手段で実現されるか","技術的依存","技術主権,EU,Gaia-X,EUCS","technology sovereignty,EU,Gaia-X,EUCS","active","secondary",76,'["Jakob Edler","Wouter Boon"]','["Edler Boon 2021","EU Tech Sovereignty 2021"]',"技術自給率・投資額"),
    ("inno_digi_438","プラットフォームとメンタルヘルスサービス","Platform and Mental Health Services","BetterHelp・Talkspace・Woebot等のデジタルメンタルヘルスプラットフォームが遠隔カウンセリング・AIチャットボット療法を提供する。COVID-19で精神健康需要が急増しデジタル療法の重要性が高まった。Woebot(CBTベースチャットボット)の効果を検証したFossati et al.(2022)が限定的有効性を示した。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"meso","メンタルヘルス","デジタルメンタルヘルス設計","精神健康ケアのデジタル化を推進する際","デジタルプラットフォームはメンタルヘルスアクセスをどう改善するか","対面カウンセリング","デジタルメンタルヘルス,BetterHelp,Woebot,CBT","digital mental health,BetterHelp,Woebot,CBT","active","secondary",74,'["Alison Darcy","Adam Miner"]','["Woebot RCT 2022","BetterHelp Scale 2022"]',"サービス利用率・症状改善率"),
    ("inno_digi_439","コンテンツ経済と知識課金プラットフォーム","Content Economy and Knowledge Monetization Platform","知識課金プラットフォーム(Substack・Ghost・Patreon・note)はライター・研究者・コンサルタントが直接サブスクリプション収入を得るモデルを普及させた。The Atlantic・NYTのデジタル課金成功事例がバンドル課金の価値を示した。AIによる要約・翻訳・個別推薦が知識コンテンツの消費効率を向上させる一方知識労働者の収益機会を複雑化させる。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2020,None,"meso","メディア・知識産業","知識課金戦略","知識コンテンツの収益化モデルを設計する際","知識課金プラットフォームはどのようなコンテンツ経済を作るか","広告依存メディア","知識課金,Substack,Ghost,Patreon,note","knowledge monetization,Substack,Ghost,Patreon,note","active","secondary",74,'["Hamish McKenzie","Li Jin"]','["Substack Growth 2022","Li Jin 2021 Passion Economy"]',"サブスクリプション収益・クリエイター数"),
    ("inno_digi_440","デジタルツールとセーフガーディング(児童保護)","Digital Tools and Child Safeguarding","オンライン児童性搾取防止にAI画像検知(PhotoDNA・CSAM検出)が広く使われている。NCMEC・IWF(Internet Watch Foundation)が報告機関として機能する。Apple's CSAM Hash-Matching計画(2021)がプライバシー vs 児童保護の논争を引き起こした。EU Child Sexual Abuse Regulation(2022)が暗号化通信のスキャン義務を巡り議論中。","platform_digital_innovation","プラットフォーム規制",2021,None,"macro","子ども・公共","オンライン児童保護設計","オンライン上の児童保護を強化する際","デジタルツールはオンライン児童性搾取をどう検知するか","未規制インターネット","CSAM,PhotoDNA,児童保護,EU CSA規則","CSAM,PhotoDNA,child protection,EU CSA Regulation","active","secondary",76,'["NCMEC Staff","IWF Staff"]','["IWF Annual Report 2022","EU CSA Regulation 2022"]',"CSAM検出率・報告件数"),
    ("inno_digi_441","デジタルノマドと働き方のグローバル化","Digital Nomad and Globalization of Work","高速インターネットと非同期協働ツールが「どこでも働ける」デジタルノマドライフスタイルを可能にした。MBO Partners(2021)は米国だけで1500万人のデジタルノマドがいると推計した。バルビザ・バルセロナ・バリ・クロアチア・エストニアがデジタルノマドビザを導入し人材獲得競争を展開する。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"macro","労働・移住","デジタルノマド政策","リモートワークのグローバル化を分析する際","デジタルノマドは労働市場と都市経済をどう変えるか","固定オフィス勤務","デジタルノマド,リモートワーク,ノマドビザ","digital nomad,remote work,nomad visa","active","secondary",72,'["MBO Partners"]','["MBO Partners Digital Nomad Report 2021","Estonia Digital Nomad Visa"]',"ノマド人口・地域経済効果"),
    ("inno_digi_442","プラットフォームと不動産テック","Platform and Real Estate Tech","Zillow・Redfin・OpendoorがAI査定・即時買取(iBuying)・デジタル内覧で不動産取引を変革しようとした。Zillow Offers失敗(2021年損失5億ドル)がAI不動産価格予測の限界を示した。PropTechは物件管理・スマートビル・リモート内覧・デジタル登記・不動産クラウドファンディングを包含する。","platform_digital_innovation","デジタルプラットフォーム経済",2018,None,"meso","不動産","PropTech戦略","不動産業のデジタル化を分析する際","PropTechは不動産取引のどの摩擦を削減するか","伝統的不動産仲介","PropTech,Zillow,iBuying,スマートビル","PropTech,Zillow,iBuying,smart building","active","secondary",74,'["Spencer Rascoff","Eric Wu"]','["Zillow Offers Failure 2021","Andreessen Horowitz PropTech 2022"]',"取引コスト・所要時間"),
    ("inno_digi_443","量子エラー訂正と誤り耐性量子コンピュータ","Quantum Error Correction and Fault-Tolerant Quantum Computing","量子計算機の誤り訂正は量子コンピュータの実用化の最大技術障壁。Surface Code・Color Code・Concatenated Codeが誤り訂正手法として研究される。Google Sycamore(2019)の量子超越達成後Googleは Surface Code実証(2023年の距離3・5・7比較)に成功した。Fault-Tolerant QCの実現には現在の物理量子ビット数の1000倍規模の量子ビットが必要と見積もられる。","platform_digital_innovation","量子コンピューティング",2023,None,"macro","量子コンピュータ","量子誤り訂正実装","量子コンピュータの実用化ロードマップを評価する際","量子誤り訂正はどのような技術的課題を持つか","古典コンピュータ","量子誤り訂正,Surface Code,Fault-Tolerant,Sycamore","quantum error correction,Surface Code,fault-tolerant,Sycamore","active","secondary",74,'["John Preskill","Craig Gidney"]','["Google Quantum 2023 Nature","Gidney Ekera 2021"]',"誤り率・論理量子ビット数"),
    ("inno_digi_444","デジタルツールと社会起業家支援","Digital Tools and Social Entrepreneurship Support","Ashoka・Echoing Green・Acumen等の社会的起業家支援組織がデジタルプラットフォームで資金・ネットワーク・ナレッジを提供する。Kickstarter・ImpactInvestmentマーケットプレイスがソーシャルビジネスへのクラウドファンディングを可能にした。Yunus Social Business・B Labが社会的インパクト測定(SROI)の標準化を進める。","platform_digital_innovation","デジタルプラットフォーム経済",2012,None,"meso","社会起業家","ソーシャルイノベーション支援設計","社会起業家をデジタルで支援する際","デジタルプラットフォームは社会起業家エコシステムをどう強化するか","資金不足環境","社会起業家,SROI,Kickstarter,B Lab","social entrepreneurship,SROI,Kickstarter,B Lab","active","secondary",72,'["Muhammad Yunus","Bill Drayton"]','["B Lab Impact Report 2022","SROI Network Guide 2012"]',"インパクト指標・資金調達額"),
    ("inno_digi_445","生成AIと著作権法の再構成","Generative AI and Reconstruction of Copyright Law","LLMは著作権保護コンテンツで訓練され生成物が元著作物を変容させるため著作権の新解釈が必要となった。Anderson v. Stability AI・NYT v. OpenAIが著作権AIケースとして進行中。EUのAI Act付属書とUSCOのAIガイダンスが生成物の著作権帰属を暫定的に整理した。Fair Use vs 著作権保護の境界線が生成AI産業の法的基盤を左右する。","platform_digital_innovation","AI規制・ガバナンス",2023,None,"macro","法律・著作権","生成AI著作権対応","AI生成コンテンツの著作権リスクを管理する際","生成AIは著作権法のどの原則に挑戦するか","人手制作著作物","生成AI,著作権,Fair Use,NYT v OpenAI","generative AI,copyright,fair use,NYT v OpenAI","active","primary",82,'["US Copyright Office","EU IPO Staff"]','["USCO AI Copyright Guidance 2023","NYT v OpenAI 2023"]',"訴訟件数・ライセンス合意数"),
    ("inno_digi_446","デジタルツールと刑事司法改革","Digital Tools and Criminal Justice Reform","AI予測警察(PredPol)・エレクトロニックモニタリング・デジタル証拠管理がCriminal Justiceに応用される。PredPolの地理的偏向がマイノリティ地域への過剰警察を助長することが研究で示された。ビデオ証拠・ボディカメラ映像のAI解析が刑事手続に影響する。Pretrial Risk Assessment ToolのValidityと公平性が訴訟論点となっている。","platform_digital_innovation","AI規制・ガバナンス",2019,None,"macro","刑事司法","刑事AI評価","刑事司法にAIを適用する際","予測警察AIはどのような正義・公平性問題を持つか","人手警察","予測警察,PredPol,アルゴリズム刑事司法,ボディカメラ","predictive policing,PredPol,algorithmic criminal justice,body camera","active","secondary",76,'["Julia Angwin","Bernard Harcourt"]','["Propublica 2016","Lum Isaac 2016 Sig Computing"]',"バイアス指標・再犯率"),
    ("inno_digi_447","デジタルプラットフォームと著作権収益化","Digital Platform and Copyright Monetization","YouTube ContentID・Spotify Loud&Clear・Apple Music Analyticsが著作権保護者のデジタル収益化インフラを提供する。ContentIDは年間1億時間のコンテンツをマッチングし権利者に収益を分配する。MMA(Music Modernization Act,2018,米国)がデジタル時代のライセンス制度を整備した。IFPI(2023)は全球音楽収益のうちストリーミングが67%を占めると報告した。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2018,None,"meso","音楽・コンテンツ産業","デジタル著作権収益化","デジタルコンテンツの収益化システムを設計する際","デジタルプラットフォームは著作権収益をどう変えるか","物理メディア","ContentID,MMA,著作権,音楽ストリーミング収益","ContentID,MMA,copyright,music streaming revenue","active","secondary",76,'["IFPI Staff","YouTube ContentID Team"]','["IFPI Global Music Report 2023","MMA 2018"]',"著作権収益・分配精度"),
    ("inno_digi_448","AIと高齢社会：介護ロボット・認知症支援","AI and Aging Society: Care Robots and Dementia Support","高齢化社会の介護ニーズにAIロボット(Pepper・Paro・LOVOT)・ AI認知症スクリーニング・転倒検知センサーが対応する。日本厚労省のロボット介護機器開発・普及プロジェクト(2013-)が産業エコシステムを形成した。Conversational AIが認知症患者の孤独感軽減・認知訓練に有効なことを複数RCTが示している。","platform_digital_innovation","ロボティクス",2020,None,"meso","介護・医療","AI介護システム設計","高齢者ケアのAI化を検討する際","AIロボットは介護の質と効率をどう改善するか","人手介護のみ","介護ロボット,Paro,認知症AI,Pepper","care robot,Paro,dementia AI,Pepper","active","secondary",74,'["厚労省AI介護"]','["Wada et al. PARO Study","Japan MHLW Robot Care 2013"]',"介護負担・認知スコア"),
    ("inno_digi_449","プラットフォームとライブエンタテインメント融合","Platform and Live Entertainment Fusion","ライブネーション・AXS・SeatGeekがチケット販売・ファン体験・二次市場を統合するライブエンタプラットフォームを構築する。TicketmasterとLiveNationの合併(2010)が反トラスト問題として議論が続く。NFTチケット・AR体験・ライブストリーミングのハイブリッドイベントが「フィジカル+デジタル」エンタを形成する。","platform_digital_innovation","デジタルプラットフォーム経済",2010,None,"meso","エンタテインメント","ライブエンタプラットフォーム設計","ライブエンタビジネスのデジタル化","ライブエンタプラットフォームはどのような価値を創出するか","フィジカルのみ","ライブエンタ,Ticketmaster,NFTチケット,ハイブリッド","live entertainment,Ticketmaster,NFT ticket,hybrid","active","secondary",72,'["Michael Rapino","DOJ Antitrust"]','["Ticketmaster LN Antitrust 2022","NFT Ticket Case Studies 2021"]',"チケット収益・二次市場規模"),
    ("inno_digi_450","デジタル地図と位置情報エコノミー","Digital Map and Location Information Economy","Google Maps・Apple Maps・OpenStreetMap・HERE Technologiesが位置情報サービスのインフラを提供する。位置情報データ(ジオデータ)は小売立地・物流・都市計画・広告ターゲティングの基盤となる。Uber・Airbnb・配達プラットフォームは精密地図なしには機能しない。位置情報プライバシー(Carpenter v. United States,2018)が令状なしGPSデータ取得の違憲性を示した。","platform_digital_innovation","データ経済",2005,None,"meso","地図・位置情報","位置情報サービス設計","位置情報を活用したサービスを設計する際","位置情報データはどのような経済的価値を持つか","印刷地図","位置情報,Google Maps,ジオデータ,プライバシー","location data,Google Maps,geodata,privacy","active","secondary",76,'["Google Maps Team","HERE Technologies"]','["Carpenter v US 2018","Google Maps Ecosystem Report 2022"]',"API利用数・ジオデータ市場規模"),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()
insert_sql = """INSERT OR IGNORE INTO innovation_theory
(id, name_ja, name_en, definition, subfield, school_of_thought, era_start, era_end,
 methodology_level, target_domain, application_conditions, when_to_apply, framing_questions,
 opposing_concept_names, keywords_ja, keywords_en, status, source_reliability, data_completeness,
 key_researchers, key_works, measurement_approach)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
conn.executemany(insert_sql, records)
conn.commit()
print(f"Inserted: {conn.total_changes}")
cur.execute("SELECT COUNT(*) FROM innovation_theory WHERE subfield='platform_digital_innovation'")
print(f"Total: {cur.fetchone()[0]}")
conn.close()
