import sqlite3
from datetime import datetime
db_path = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"
now = datetime.now().isoformat()
entries = [
    {
        "id": "inno_pol_621",
        "name_en": "Regulatory Impact Assessment",
        "name_ja": "規制影響評価",
        "definition": "新規・改正規制の実施前に経済・社会・環境への影響を体系的に評価するプロセスを指す。費用便益分析・利害関係者協議・代替案検討が標準的要素であり、OECD各国で制度化されている。",
        "impact_summary": "規制の質を事前に検証し、不必要な規制負担の発生と政策失敗を防止する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regulatory_theory",
        "era_start": 1980,
        "innovation_type": "policy",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "規制影響評価,RIA,費用便益分析,規制改革",
        "keywords_en": "regulatory impact assessment,RIA,cost-benefit analysis,regulatory reform",
        "key_researchers": '["Radaelli C.M.", "de Francesco F."]',
        "key_works": '["Regulatory Quality in Europe (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_622",
        "name_en": "Research Reproducibility Policy",
        "name_ja": "研究再現可能性政策",
        "definition": "科学研究の再現可能性危機に対応するため、事前登録・オープンデータ・透明な報告・複製研究への資金提供等を促進する政策枠組みを指す。",
        "impact_summary": "科学的知識の信頼性を回復し、研究資源の無駄遣いと政策立案における誤った証拠依存を防ぐ。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "science_policy",
        "era_start": 2013,
        "innovation_type": "institutional",
        "cognitive_mechanism": "ethical",
        "keywords_ja": "再現可能性,オープンサイエンス,事前登録,研究透明性",
        "keywords_en": "reproducibility,open science,preregistration,research transparency",
        "key_researchers": '["Ioannidis J.P.A.", "Nosek B.A."]',
        "key_works": '["Why Most Published Research Findings Are False (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_623",
        "name_en": "Responsible AI Governance Frameworks",
        "name_ja": "責任あるAIガバナンスフレームワーク",
        "definition": "AIシステムの設計・開発・展開における安全性・公平性・透明性・説明可能性を確保するための組織的・制度的枠組みを指す。NIST AI RMF・EU AI Act・ISO/IEC 42001等が代表例である。",
        "impact_summary": "AIシステムへの社会的信頼を構築し、高リスク用途における害を予防する制度基盤を整える。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 2019,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "AIガバナンス,NIST RMF,EU AI Act,責任あるAI",
        "keywords_en": "responsible AI governance,NIST AI RMF,EU AI Act,trustworthy AI",
        "key_researchers": '["Jobin A.", "Ienca M.", "Vayena E."]',
        "key_works": '["The Global Landscape of AI Ethics Guidelines (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_624",
        "name_en": "Institutional Logics in Innovation",
        "name_ja": "イノベーションにおける制度的論理",
        "definition": "企業・大学・政府・市場・専門家集団など異なる制度圏が持つ固有の価値・規範・実践が、イノベーション活動の方向性と成果を規定するという分析枠組みを指す。",
        "impact_summary": "イノベーション行為者間の制度的摩擦と協力の動態を解明し、多元的ガバナンスの設計に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "institutional_theory",
        "era_start": 1991,
        "innovation_type": "institutional",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "制度的論理,制度理論,価値多元性,ガバナンス複数性",
        "keywords_en": "institutional logics,institutional theory,value plurality,governance multiplicity",
        "key_researchers": '["Friedland R.", "Alford R.R.", "Thornton P.H."]',
        "key_works": '["Institutional Logics Perspective (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_625",
        "name_en": "Quantum Technology Policy",
        "name_ja": "量子技術政策",
        "definition": "量子コンピューティング・量子通信・量子センシング等の量子技術の開発・実証・標準化・安全保障応用を促進する国家・国際政策を指す。各国が大型量子フラッグシッププログラムを競い合っている。",
        "impact_summary": "次世代の安全保障・通信・計算能力を左右する量子技術における競争優位を確保する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_policy",
        "era_start": 2016,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "量子政策,量子コンピューティング,量子通信,量子安全保障",
        "keywords_en": "quantum policy,quantum computing,quantum communication,quantum security",
        "key_researchers": '["Preskill J.", "Wehner S."]',
        "key_works": '["Quantum Computing in the NISQ Era and Beyond (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_626",
        "name_en": "Technology Transfer Measurement",
        "name_ja": "技術移転測定",
        "definition": "大学・研究機関から産業への技術移転（特許ライセンス・スピンオフ・受託研究・人材移動等）の量・質・経済的影響を測定する手法を指す。",
        "impact_summary": "公的研究の商業化効率を定量的に評価し、技術移転政策の改善と成功要因の特定を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "triple_helix",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "技術移転測定,ライセンス収入,スピンオフ,産学連携評価",
        "keywords_en": "technology transfer measurement,licensing revenue,spinoff,industry-academia evaluation",
        "key_researchers": '["Bercovitz J.", "Feldman M."]',
        "key_works": '["Academic Entrepreneurs: Organizational Change (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_627",
        "name_en": "Biodiversity and Innovation",
        "name_ja": "生物多様性とイノベーション",
        "definition": "生物多様性資源（遺伝資源・伝統知識・生態系サービス）を活用したイノベーション（医薬・農業・バイオ素材等）のガバナンスを指す。名古屋議定書・ABS（利益配分）が主要制度枠組みである。",
        "impact_summary": "生物多様性の保護と持続可能な利用を両立しつつ、バイオイノベーションの公正な利益配分を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 2010,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "生物多様性,名古屋議定書,ABS,遺伝資源",
        "keywords_en": "biodiversity,Nagoya Protocol,ABS,genetic resources",
        "key_researchers": '["Laird S.", "Wynberg R."]',
        "key_works": '["Access and Benefit Sharing (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_628",
        "name_en": "Urban Innovation Policy",
        "name_ja": "都市イノベーション政策",
        "definition": "都市を舞台にしたイノベーション（スマートシティ・リビングラボ・都市実証・モビリティ転換等）を促進する政策の総称を指す。都市のテストベッド機能と市民参加が重要要素である。",
        "impact_summary": "都市空間を実証環境として活用し、社会課題解決型イノベーションの実装を加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regional_innovation",
        "era_start": 2005,
        "innovation_type": "policy",
        "cognitive_mechanism": "spatial",
        "keywords_ja": "都市イノベーション,スマートシティ,リビングラボ,都市実証",
        "keywords_en": "urban innovation policy,smart city,living lab,urban testbed",
        "key_researchers": '["Hollands R.G.", "Komninos N."]',
        "key_works": '["Intelligent Cities (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_629",
        "name_en": "Competition Policy and Innovation",
        "name_ja": "競争政策とイノベーション",
        "definition": "市場競争の維持・促進を目的とする競争政策（独占禁止法・合併審査・競争促進）がイノベーション活動に与える影響を分析・設計する枠組みを指す。",
        "impact_summary": "競争圧力がイノベーションインセンティブに与える複雑な影響を解明し、最適な競争政策設計に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "industrial_organization",
        "era_start": 1970,
        "innovation_type": "policy",
        "cognitive_mechanism": "market_forming",
        "keywords_ja": "競争政策,独占禁止法,市場競争,イノベーション促進",
        "keywords_en": "competition policy,antitrust,market competition,innovation promotion",
        "key_researchers": '["Aghion P.", "Gilbert R."]',
        "key_works": '["Competition and Innovation: An Inverted U Relationship (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_630",
        "name_en": "Research Data Management Policy",
        "name_ja": "研究データ管理政策",
        "definition": "研究データの収集・保管・共有・再利用を適切に管理するための政策・基準・インフラを指す。FAIR原則（発見可能・アクセス可能・相互運用・再利用可能）が国際的な規範として普及している。",
        "impact_summary": "研究データの長期保存と再利用を促進し、研究効率と科学的透明性を高める。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_science",
        "era_start": 2016,
        "innovation_type": "institutional",
        "cognitive_mechanism": "open",
        "keywords_ja": "研究データ管理,FAIR原則,データ共有,オープンデータ",
        "keywords_en": "research data management,FAIR principles,data sharing,open data",
        "key_researchers": '["Wilkinson M.D.", "Mons B."]',
        "key_works": '["The FAIR Guiding Principles (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_631",
        "name_en": "Anticipatory Regulation",
        "name_ja": "先行的規制",
        "definition": "技術が市場に出る前に潜在的リスクを評価し、予防的・適応的な規制フレームワークをあらかじめ設計するアプローチを指す。ナノテク・AI・合成生物学等の新興技術に適用が試みられている。",
        "impact_summary": "規制の後追いを回避し、技術普及と安全確保を同時に実現する先手の制度整備を可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "anticipatory_governance",
        "era_start": 2010,
        "innovation_type": "institutional",
        "cognitive_mechanism": "precautionary",
        "keywords_ja": "先行規制,予防的規制,適応的規制,新興技術ガバナンス",
        "keywords_en": "anticipatory regulation,precautionary regulation,adaptive regulation,emerging tech governance",
        "key_researchers": '["Marchant G.E.", "Sylvester D.J."]',
        "key_works": '["Transnational Models for Regulation of Nanotechnology (2006)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_632",
        "name_en": "Behavioral Insights for Innovation Policy",
        "name_ja": "イノベーション政策への行動インサイト応用",
        "definition": "行動経済学・行動科学の知見（ナッジ・デフォルト設定・フレーミング等）をイノベーション政策の設計・実施に応用する手法を指す。英国BITが先駆的モデルを提供した。",
        "impact_summary": "行動バイアスを考慮した政策設計により、介入の費用対効果を高め政策目標の達成を改善する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "behavioral_economics",
        "era_start": 2010,
        "innovation_type": "policy",
        "cognitive_mechanism": "behavioral",
        "keywords_ja": "行動インサイト,ナッジ,政策設計,行動経済学応用",
        "keywords_en": "behavioral insights,nudge,policy design,behavioral economics application",
        "key_researchers": '["Thaler R.H.", "Sunstein C.R."]',
        "key_works": '["Nudge (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_633",
        "name_en": "R&D Tax Credit Evaluation Methods",
        "name_ja": "R&D税額控除評価手法",
        "definition": "R&D活動に対する税額控除の経済的効果を識別・測定するための計量経済学的手法を指す。差分の差分法・回帰不連続設計・操作変数法等が活用され、追加性と投資誘発効果が主要評価指標である。",
        "impact_summary": "R&D税制の費用対効果を厳密に評価し、政策設計の改善とエビデンスに基づく政策判断を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "economics_of_innovation",
        "era_start": 1995,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "R&D税額控除評価,追加性,差分の差分法,準実験",
        "keywords_en": "R&D tax credit evaluation,additionality,difference-in-differences,quasi-experiment",
        "key_researchers": '["Hall B.H.", "Reenen J.V."]',
        "key_works": '["Do R&D Tax Credits Work (2000)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_634",
        "name_en": "Synthetic Biology Governance",
        "name_ja": "合成生物学ガバナンス",
        "definition": "生物システムの設計・構築・再プログラミングを行う合成生物学の研究・商業利用・安全管理に関するガバナンス枠組みを指す。デュアルユースリスク・生態系影響・倫理的境界が主要論点である。",
        "impact_summary": "革新的な生物工学の恩恵を実現しながら生物安全・生物保安・倫理的懸念に対処するバランスを図る。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "responsible_innovation",
        "era_start": 2004,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "合成生物学ガバナンス,バイオセキュリティ,デュアルユース,生物安全",
        "keywords_en": "synthetic biology governance,biosecurity,dual use,biosafety",
        "key_researchers": '["Endy D.", "Schmidt M."]',
        "key_works": '["Synthetic Biology (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_635",
        "name_en": "Mission-Oriented Research Programs",
        "name_ja": "ミッション指向型研究プログラム",
        "definition": "月面着陸・がん撲滅・気候中立等の明確な社会的使命を設定し、その達成に向けて研究投資を集中するプログラム型の政策手法を指す。マリアナ・マッツカートの研究がこの概念を再評価した。",
        "impact_summary": "市場では解決困難な大規模社会的課題を公的ミッション設定によって研究・イノベーションの方向性を定めて対処する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 1960,
        "innovation_type": "policy",
        "cognitive_mechanism": "mission_driven",
        "keywords_ja": "ミッション型研究,使命指向,社会的挑戦,ムーンショット",
        "keywords_en": "mission-oriented research,mission-directed,societal challenges,moonshot",
        "key_researchers": '["Mazzucato M.", "Hicks D."]',
        "key_works": '["Mission-Oriented Research and Innovation in the European Union (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_636",
        "name_en": "National Cybersecurity Innovation Policy",
        "name_ja": "国家サイバーセキュリティイノベーション政策",
        "definition": "サイバー脅威への対応能力を向上させる技術・人材・組織の育成を支援する政策を指す。NIST CSF・国家サイバー戦略・官民連携セキュリティR&Dが主要要素である。",
        "impact_summary": "デジタル社会の根幹となるサイバー空間の安全性を技術イノベーションと制度整備の両面から強化する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "security_innovation",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "サイバーセキュリティ政策,NIST CSF,官民連携,サイバー戦略",
        "keywords_en": "cybersecurity innovation policy,NIST CSF,public-private partnership,cyber strategy",
        "key_researchers": '["Schneier B.", "Anderson R."]',
        "key_works": '["Security Engineering (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_637",
        "name_en": "STI Governance in Developing Countries",
        "name_ja": "途上国における科学技術イノベーションガバナンス",
        "definition": "低・中所得国がSTIシステムの構築・強化・ガバナンス改革を行うための政策枠組みを指す。能力構築・南南協力・技術移転・ローカル知識の統合が主要課題である。",
        "impact_summary": "途上国が自国の発展課題に対応したイノベーション能力を構築し、持続可能な発展を実現する基盤を整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "development_economics",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "途上国STI,能力構築,技術移転,南南協力",
        "keywords_en": "developing country STI,capacity building,technology transfer,South-South cooperation",
        "key_researchers": '["Lall S.", "Pietrobelli C."]',
        "key_works": '["Technological Learning and Economic Development (2003)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_638",
        "name_en": "Pandemic Preparedness Innovation",
        "name_ja": "パンデミック対応イノベーション",
        "definition": "感染症パンデミックへの備えと対応を強化するための技術開発・ガバナンス・国際協力の枠組みを指す。mRNAワクチン基盤・診断技術・サーベイランスシステム・CEPI等が代表的要素である。",
        "impact_summary": "将来のパンデミックに対して迅速・効果的に対応できる技術・制度・供給チェーンの事前構築を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "health_innovation",
        "era_start": 2005,
        "innovation_type": "policy",
        "cognitive_mechanism": "precautionary",
        "keywords_ja": "パンデミック対応,mRNAワクチン,CEPI,感染症対策イノベーション",
        "keywords_en": "pandemic preparedness,mRNA vaccine,CEPI,infectious disease innovation",
        "key_researchers": '["Fauci A.S.", "Hatchett R."]',
        "key_works": '["CEPI: New Vaccines for a Safer World (2017)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_639",
        "name_en": "Knowledge Governance in Firms",
        "name_ja": "企業における知識ガバナンス",
        "definition": "企業内外での知識の創造・共有・保護・活用を統制するガバナンス構造を指す。知識移転の促進と知的財産保護のバランス、コミュニティ・オブ・プラクティスの制度化等が主要課題である。",
        "impact_summary": "企業の知識資産を効果的に管理し、組織学習とイノベーション能力の持続的強化を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "knowledge_management",
        "era_start": 1995,
        "innovation_type": "process",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "知識ガバナンス,知識管理,組織学習,知的財産管理",
        "keywords_en": "knowledge governance,knowledge management,organizational learning,IP management",
        "key_researchers": '["Foss N.J.", "Michailova S."]',
        "key_works": '["Governing Knowledge Processes (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_640",
        "name_en": "Breakthrough Innovation Policy",
        "name_ja": "突破型イノベーション政策",
        "definition": "既存技術軌跡を根本的に変革し、新産業・新市場を創出する突破型イノベーションを特別に支援する政策の総称を指す。ARPA型機関・ムーンショットプログラム・破壊的技術投資が含まれる。",
        "impact_summary": "漸進的革新だけでは到達できない技術飛躍を公的介入によって実現し、産業・社会の根本変革を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "mission_oriented",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "突破型イノベーション,ARPA型,破壊的技術,ムーンショット",
        "keywords_en": "breakthrough innovation policy,ARPA-type agency,disruptive technology,moonshot program",
        "key_researchers": '["Fuchs E.R.H.", "Bonvillian W.B."]',
        "key_works": '["ARPA-E and the Challenge (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_641",
        "name_en": "Natural Capital and Innovation",
        "name_ja": "自然資本とイノベーション",
        "definition": "生態系サービス・自然資源・生物多様性等の自然資本を経済・政策分析の枠組みに組み込み、自然資本保全と活用に向けたイノベーションを促進する政策を指す。",
        "impact_summary": "自然資本の経済的価値を可視化することで、より持続可能な生産・消費パターンへの転換を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "ecological_economics",
        "era_start": 2012,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "自然資本,生態系サービス,TEEB,自然資本会計",
        "keywords_en": "natural capital,ecosystem services,TEEB,natural capital accounting",
        "key_researchers": '["Costanza R.", "Sukhdev P."]',
        "key_works": '["The Economics of Ecosystems and Biodiversity (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_642",
        "name_en": "Social Network Analysis for Policy",
        "name_ja": "政策のための社会ネットワーク分析",
        "definition": "政策コミュニティ・アドボカシー連合・政策ネットワーク内の行為者関係を社会ネットワーク分析で測定・可視化する手法を指す。知識ブローカー・影響力のある行為者・ネットワークの空隙を特定する。",
        "impact_summary": "政策形成ネットワークの構造を明らかにし、効果的な政策コミュニケーションと連携戦略の設計を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "network_theory",
        "era_start": 1990,
        "innovation_type": "methodology",
        "cognitive_mechanism": "network",
        "keywords_ja": "政策ネットワーク分析,アドボカシー連合,知識ブローカー,政策コミュニティ",
        "keywords_en": "policy network analysis,advocacy coalition,knowledge broker,policy community",
        "key_researchers": '["Sabatier P.A.", "Weible C.M."]',
        "key_works": '["Theories of the Policy Process (2007)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_643",
        "name_en": "Health Data Governance",
        "name_ja": "医療データガバナンス",
        "definition": "医療・健康データの収集・共有・利活用を支配するルール・標準・制度の枠組みを指す。EHR相互運用性・GDPR適用・患者同意・医薬品開発への二次利用が主要政策課題である。",
        "impact_summary": "医療データの適切な活用を通じて医学研究と個人化医療を加速しつつ、プライバシーと安全を確保する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "digital_governance",
        "era_start": 2015,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "医療データガバナンス,EHR,患者同意,ヘルスデータ利活用",
        "keywords_en": "health data governance,EHR,patient consent,health data utilization",
        "key_researchers": '["Topol E.J.", "Bhavnani S.P."]',
        "key_works": '["Deep Medicine (2019)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_644",
        "name_en": "Technology and Trade Policy",
        "name_ja": "技術と貿易政策",
        "definition": "技術貿易（知識・ライセンス・ハイテク財・サービス）の促進・制限・規制に関する政策を指す。輸出管理・技術覇権競争・TRIPS・WTO技術規制が主要制度的枠組みとなる。",
        "impact_summary": "技術の国際移転と貿易ルールのバランスを通じて競争力と安全保障を同時に追求する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "international_economics",
        "era_start": 1980,
        "innovation_type": "policy",
        "cognitive_mechanism": "strategic",
        "keywords_ja": "技術貿易,輸出規制,TRIPS,技術覇権",
        "keywords_en": "technology trade policy,export control,TRIPS,tech hegemony",
        "key_researchers": '["Helpman E.", "Grossman G.M."]',
        "key_works": '["Innovation and Growth in the Global Economy (1991)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_645",
        "name_en": "Innovation Ecosystems Governance",
        "name_ja": "イノベーション生態系ガバナンス",
        "definition": "企業・大学・投資家・中間機関・政府が形成する複雑なイノベーション生態系の調整・育成・方向付けを行うガバナンスの枠組みを指す。生態系のオーケストレーション・コンポーネント間の相互依存管理が課題である。",
        "impact_summary": "多様な行為者が協調してイノベーションを生み出す生態系全体の健全性と生産性を維持する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 2010,
        "innovation_type": "institutional",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "イノベーション生態系,エコシステムガバナンス,オーケストレーション,多行為者調整",
        "keywords_en": "innovation ecosystem governance,ecosystem orchestration,multi-actor coordination,keystone actor",
        "key_researchers": '["Adner R.", "Kapoor R."]',
        "key_works": '["Value Creation in Innovation Ecosystems (2010)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_646",
        "name_en": "Industry-Science Linkages Measurement",
        "name_ja": "産業-科学連携測定",
        "definition": "産業界と公的研究機関の連携（共同特許・共著・人材移動・共同研究資金等）を定量的に測定する手法を指す。知識移転チャネルと産業R&Dへの大学知識の貢献を把握するために使われる。",
        "impact_summary": "産学連携の実態を測定し、知識移転の経路と効果を分析することで政策設計に貢献する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "triple_helix",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "産学連携測定,共同特許,知識移転,産学接続",
        "keywords_en": "industry-science linkages,co-patent,knowledge transfer,university-industry connection",
        "key_researchers": '["Cohen W.M.", "Nelson R.R.", "Walsh J.P."]',
        "key_works": '["Links and Impacts: Surveys on University-Industry Research (2002)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_647",
        "name_en": "Policy Evaluation for Innovation Programs",
        "name_ja": "イノベーションプログラムの政策評価",
        "definition": "公的イノベーション支援プログラム（補助金・税制・インキュベーション等）の実施効果を因果推論の手法で評価する研究分野を指す。反事実分析・マッチング・RCT等が活用される。",
        "impact_summary": "イノベーション政策の実際の追加効果を厳密に測定し、資源配分の改善と政策学習を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "evidence_based_policy",
        "era_start": 1995,
        "innovation_type": "methodology",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "政策評価,因果推論,追加性,プログラム評価",
        "keywords_en": "policy evaluation,causal inference,additionality,program evaluation",
        "key_researchers": '["Klette T.J.", "Moen J.", "Griliches Z."]',
        "key_works": '["Do Subsidies to Commercial R&D Reduce Market Failures (2000)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_648",
        "name_en": "Territorial Cohesion and Innovation",
        "name_ja": "領域的結束とイノベーション",
        "definition": "EU結束政策の枠組みにおいて、地域間格差の是正とイノベーション能力の均等化を同時に目指す政策を指す。スマート専門化戦略がこの目的を具体化する主要手段として採用されている。",
        "impact_summary": "イノベーション能力の地域格差を縮小し、より均衡のとれた地域発展と経済統合を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regional_innovation",
        "era_start": 2007,
        "innovation_type": "policy",
        "cognitive_mechanism": "spatial",
        "keywords_ja": "結束政策,地域格差,スマート専門化,EU構造基金",
        "keywords_en": "cohesion policy,regional disparity,smart specialization,EU structural funds",
        "key_researchers": '["Barca F.", "McCann P."]',
        "key_works": '["Smart Specialisation (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_649",
        "name_en": "Global Value Chains and Innovation Policy",
        "name_ja": "グローバルバリューチェーンとイノベーション政策",
        "definition": "製品・サービスの開発・製造・流通・消費が世界に分散したGVC構造がイノベーション政策に与える影響を分析する枠組みを指す。知識集約活動の誘致・育成、GVC高度化支援が政策課題となる。",
        "impact_summary": "GVC内の知識・技術移転メカニズムを解明し、国の産業高度化とイノベーション能力向上を政策的に支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "international_economics",
        "era_start": 2000,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "グローバルバリューチェーン,GVC,産業高度化,知識集約活動",
        "keywords_en": "global value chains,GVC,industrial upgrading,knowledge-intensive activities",
        "key_researchers": '["Gereffi G.", "Humphrey J.", "Sturgeon T."]',
        "key_works": '["The Governance of Global Value Chains (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_650",
        "name_en": "Living Standards and Innovation",
        "name_ja": "生活水準とイノベーション",
        "definition": "イノベーションが経済成長を通じて生活水準・福祉・生活の質に与える長期的影響を分析する枠組みを指す。Jカーブ・分配効果・非市場的便益・消費者余剰の測定が主要課題となる。",
        "impact_summary": "イノベーションのGDPへの貢献を超えた生活の質への影響を包括的に評価する視点を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "welfare_economics",
        "era_start": 1990,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "生活水準,消費者余剰,福祉効果,イノベーション分配",
        "keywords_en": "living standards,consumer surplus,welfare effects,innovation distribution",
        "key_researchers": '["Nordhaus W.D.", "Jones C.I."]',
        "key_works": '["The Facts of Economic Growth (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_651",
        "name_en": "Public Value and Innovation",
        "name_ja": "公共価値とイノベーション",
        "definition": "政府のイノベーション活動が創出すべき「公共価値」の概念と測定を論じる枠組みを指す。マーク・ムーアの戦略的三角形モデル等を参照し、政治的正当性・運営能力・公共的目標の達成を総合評価する。",
        "impact_summary": "公共部門のイノベーションを純粋な効率性指標を超えた多元的価値で評価する規範的基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "public_administration",
        "era_start": 1995,
        "innovation_type": "measurement",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "公共価値,行政評価,戦略的三角形,公益性",
        "keywords_en": "public value,government evaluation,strategic triangle,public interest",
        "key_researchers": '["Moore M.H.", "Benington J."]',
        "key_works": '["Creating Public Value (1995)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_652",
        "name_en": "Academic Publishing Policy",
        "name_ja": "学術出版政策",
        "definition": "学術論文の出版・アクセス・引用文化・ジャーナル評価に関する政策を指す。オープンアクセス義務化・プレプリント普及・Plan S・APC（論文処理費）の公平性が主要政策課題である。",
        "impact_summary": "科学的知識の公開と普及を促進し、出版プロセスの透明性とアクセス公平性を向上させる。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "open_science",
        "era_start": 2003,
        "innovation_type": "institutional",
        "cognitive_mechanism": "open",
        "keywords_ja": "学術出版,オープンアクセス,Plan S,APC",
        "keywords_en": "academic publishing policy,open access,Plan S,APC",
        "key_researchers": '["Suber P.", "Lariviere V."]',
        "key_works": '["Open Access (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_653",
        "name_en": "Export Control and Technology Governance",
        "name_ja": "輸出管理と技術ガバナンス",
        "definition": "安全保障上機微な技術・製品・ソフトウェアの輸出を制限・管理する国際・国内ガバナンス体制を指す。WassenaarアレンジメントECCN分類・エンドユーザー確認が主要仕組みである。",
        "impact_summary": "技術の安全保障リスクを管理しながら、正当な技術・知識の国際流通を最大限確保するバランスを維持する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "security_innovation",
        "era_start": 1995,
        "innovation_type": "institutional",
        "cognitive_mechanism": "regulatory",
        "keywords_ja": "輸出管理,Wassenaar,デュアルユース技術,安全保障管理",
        "keywords_en": "export control,Wassenaar Arrangement,dual-use technology,security governance",
        "key_researchers": '["Grillot S.R.", "Jones R.S."]',
        "key_works": '["Controlling the Atom in the 21st Century (2001)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_654",
        "name_en": "Entrepreneurial Ecosystem Indicators",
        "name_ja": "アントレプレナーシップ生態系指標",
        "definition": "スタートアップ生態系の強さ・多様性・ダイナミクスを定量的に評価する指標体系を指す。ユニコーン数・VC投資額・設立容易性・人材流動性・失敗文化等の多面的指標が含まれる。",
        "impact_summary": "起業家生態系の国際比較と弱点特定を通じて、より効果的なスタートアップ政策設計を支援する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "entrepreneurship",
        "era_start": 2010,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "スタートアップ生態系,ユニコーン,VC投資,起業家指標",
        "keywords_en": "startup ecosystem indicators,unicorn,VC investment,entrepreneurship metrics",
        "key_researchers": '["Isenberg D.", "Spigel B."]',
        "key_works": '["The Entrepreneurship Ecosystem Strategy (2011)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_655",
        "name_en": "Foresight for Public Policy",
        "name_ja": "公共政策のためのフォーサイト",
        "definition": "政府機関が将来の変化・リスク・機会を探索し、より長期的視野で政策を設計するためのフォーサイト手法の応用を指す。シナリオ・デルファイ・ロードマッピングが代表的手法である。",
        "impact_summary": "政府の政策視野を拡張し、短期的課題対応を超えた長期的社会変革への備えを可能にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "technology_foresight",
        "era_start": 1990,
        "innovation_type": "methodology",
        "cognitive_mechanism": "prospective",
        "keywords_ja": "政策フォーサイト,シナリオ,デルファイ,長期政策",
        "keywords_en": "foresight for public policy,scenario,Delphi,long-term policy",
        "key_researchers": '["Georghiou L.", "Haegeman K."]',
        "key_works": '["Evaluating Foresight and Lessons for Its Future (2008)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_656",
        "name_en": "Circular Bioeconomy Policy",
        "name_ja": "循環型バイオエコノミー政策",
        "definition": "バイオマス・生物プロセスを活用した循環経済を推進する政策を指す。廃棄物から価値創出・生物由来素材のカスケード利用・バイオリファイナリーが主要技術対象である。",
        "impact_summary": "化石資源依存を減少させつつ生物系資源の最大価値活用を通じて持続可能な産業を実現する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 2018,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "循環バイオエコノミー,バイオリファイナリー,カスケード利用,廃棄物価値化",
        "keywords_en": "circular bioeconomy,biorefinery,cascade use,waste valorization",
        "key_researchers": '["Stegmann P.", "Londo M.", "Junginger M."]',
        "key_works": '["The Circular Bioeconomy (2020)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_657",
        "name_en": "Talent Mobility and Innovation",
        "name_ja": "人材流動性とイノベーション",
        "definition": "研究者・エンジニア・起業家の国際・組織間移動がイノベーション活動と知識拡散に与える影響を分析し、人材流動性を政策的に促進・管理する枠組みを指す。",
        "impact_summary": "人材の移動を通じた知識移転と多様性の促進がイノベーション生態系の活性化に貢献することを示す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "human_capital",
        "era_start": 1995,
        "innovation_type": "policy",
        "cognitive_mechanism": "network",
        "keywords_ja": "人材流動性,研究者移動,知識移転,頭脳循環",
        "keywords_en": "talent mobility,researcher mobility,knowledge transfer,brain circulation",
        "key_researchers": '["Saxenian A.L.", "Kerr W.R."]',
        "key_works": '["The Immigrant Exodus (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_658",
        "name_en": "Accelerator and Incubator Policy",
        "name_ja": "アクセラレーターとインキュベーター政策",
        "definition": "スタートアップの成長を支援するアクセラレーターとインキュベーターの設立・運営・評価に関する政策枠組みを指す。公的vs民間運営・卒業生実績・エコシステムへの貢献が評価指標である。",
        "impact_summary": "新興企業の生存率と成長速度を高め、地域イノベーション生態系の厚みを増すインフラを整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "entrepreneurship",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "アクセラレーター,インキュベーター,スタートアップ支援,起業支援インフラ",
        "keywords_en": "accelerator,incubator,startup support,entrepreneurship infrastructure",
        "key_researchers": '["Hackett S.M.", "Dilts D.M."]',
        "key_works": '["A Systematic Review of Business Incubation Research (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_659",
        "name_en": "Crisis Innovation Policy",
        "name_ja": "危機対応イノベーション政策",
        "definition": "経済危機・パンデミック・自然災害等の急性的ショックに対応するために設計・実施される緊急イノベーション政策を指す。迅速な資金展開・規制緩和・官民連携の加速が特徴である。",
        "impact_summary": "危機時の技術的・社会的課題に迅速に対応し、復旧から変革への転換を可能にする政策基盤を整える。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "crisis_management",
        "era_start": 2008,
        "innovation_type": "policy",
        "cognitive_mechanism": "adaptive",
        "keywords_ja": "危機イノベーション,緊急政策,迅速資金展開,規制緩和",
        "keywords_en": "crisis innovation policy,emergency policy,rapid funding,regulatory waiver",
        "key_researchers": '["Mazzucato M.", "Cimoli M."]',
        "key_works": '["Innovation and Economic Crisis (2009)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_660",
        "name_en": "Institutional Capacity for Innovation Policy",
        "name_ja": "イノベーション政策の制度的能力",
        "definition": "政府機関がイノベーション政策を設計・実施・評価する組織的能力の総称を指す。政策コミュニティの専門性・省庁間調整・証拠活用・学習能力が主要要素である。",
        "impact_summary": "イノベーション政策の質と一貫性は政策立案機関の制度的能力に決定的に依存することを示す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "institutional_theory",
        "era_start": 2000,
        "innovation_type": "institutional",
        "cognitive_mechanism": "institutional",
        "keywords_ja": "政策能力,制度的能力,省庁間調整,政策学習",
        "keywords_en": "policy capacity,institutional capacity,inter-ministerial coordination,policy learning",
        "key_researchers": '["Wu X.", "Howlett M.", "Ramesh M."]',
        "key_works": '["Policy Capacity and Governance (2018)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_661",
        "name_en": "Green Innovation Indicators",
        "name_ja": "グリーンイノベーション指標",
        "definition": "環境改善に貢献するイノベーション（再エネ・省エネ・廃棄物削減・循環素材等）の規模・方向・成果を測定する指標体系を指す。環境特許・グリーンR&D投資・低炭素投資が代表的指標である。",
        "impact_summary": "グリーン転換の進捗を測定し、低炭素社会への移行を加速するための政策的証拠基盤を提供する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 2010,
        "innovation_type": "measurement",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "グリーンイノベーション,環境特許,低炭素投資,グリーンR&D",
        "keywords_en": "green innovation indicators,environmental patents,low-carbon investment,green R&D",
        "key_researchers": '["Popp D.", "Calel R."]',
        "key_works": '["Environmental Policy and Innovation (2012)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_662",
        "name_en": "Responsible Investment in STI",
        "name_ja": "STIにおける責任投資",
        "definition": "環境・社会・ガバナンス（ESG）基準をSTI投資に組み込み、長期的・持続可能な価値創造を目指す投資戦略と政策を指す。PRI・ESG基準・サステナブルファイナンスが関連枠組みである。",
        "impact_summary": "STI投資の環境・社会への外部性を内部化し、持続可能で公正なイノベーションに資本を誘導する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainable_finance",
        "era_start": 2015,
        "innovation_type": "policy",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "責任投資,ESG,PRI,サステナブルファイナンス",
        "keywords_en": "responsible investment,ESG,PRI,sustainable finance",
        "key_researchers": '["Eccles R.G.", "Ioannou I."]',
        "key_works": '["The Impact of Corporate Sustainability (2014)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_663",
        "name_en": "Workforce Development for Innovation",
        "name_ja": "イノベーションのための労働力開発",
        "definition": "イノベーション経済が必要とする技術・能力・知識を持つ労働力を育成するための教育・訓練・生涯学習政策を指す。STEM教育・リスキリング・高度技術人材政策が含まれる。",
        "impact_summary": "人的資本の量と質を高め、イノベーション活動の担い手を安定的に供給する基盤を整備する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "human_capital",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "労働力開発,スキル育成,リスキリング,STEM人材",
        "keywords_en": "workforce development,skills development,reskilling,STEM talent",
        "key_researchers": '["Autor D.H.", "Dorn D."]',
        "key_works": '["The Growth of Low-Skill Service Jobs (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_664",
        "name_en": "Systemic Innovation Failure Framework",
        "name_ja": "システム的イノベーション失敗フレームワーク",
        "definition": "市場失敗・能力失敗・ネットワーク失敗・制度失敗・方向性失敗という5種のシステム失敗を体系的に診断し、それぞれに適合した政策介入を設計するための枠組みを指す。",
        "impact_summary": "単純な市場失敗論では捉えられないイノベーションシステムの構造的問題を多面的に診断し対処する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 1997,
        "innovation_type": "policy",
        "cognitive_mechanism": "systemic",
        "keywords_ja": "システム失敗,能力失敗,ネットワーク失敗,制度失敗",
        "keywords_en": "systemic failure,capability failure,network failure,institutional failure",
        "key_researchers": '["Klein Woolthuis R.", "Lankhuizen M.", "Gilsing V."]',
        "key_works": '["A System Failure Framework for Innovation Policy Design (2005)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_665",
        "name_en": "Science-Based Regulation",
        "name_ja": "科学に基づく規制",
        "definition": "規制設計・改廃において科学的証拠を中心的根拠とするアプローチを指す。リスク評価・毒性試験・疫学証拠が規制基準設定の基礎となる。科学と政策の境界管理が重要課題である。",
        "impact_summary": "規制の科学的正当性を強化し、恣意的・政治的規制からの保護と社会的信頼の構築を促進する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "regulatory_theory",
        "era_start": 1970,
        "innovation_type": "institutional",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "科学的規制,リスク評価,証拠に基づく規制,規制科学",
        "keywords_en": "science-based regulation,risk assessment,evidence-based regulation,regulatory science",
        "key_researchers": '["Jasanoff S.", "Sheila J."]',
        "key_works": '["The Fifth Branch: Science Advisers as Policymakers (1990)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_666",
        "name_en": "Entrepreneurial State Theory",
        "name_ja": "起業家国家論",
        "definition": "国家がリスクを取り、産業・技術変革を積極的に主導する「起業家国家」としての役割を論じる理論を指す。マリアナ・マッツカートが体系化し、インターネット・mRNAワクチン等が事例として挙げられる。",
        "impact_summary": "国家が単なる市場失敗の修正者を超えてイノベーションのリスク負担者・方向性設定者として機能することを示す。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "innovation_systems",
        "era_start": 2011,
        "innovation_type": "theory",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "起業家国家,国家イノベーション,公的リスク,マッツカート",
        "keywords_en": "entrepreneurial state,state innovation,public risk,Mazzucato",
        "key_researchers": '["Mazzucato M."]',
        "key_works": '["The Entrepreneurial State (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_667",
        "name_en": "Clean Energy Innovation Policy",
        "name_ja": "クリーンエネルギーイノベーション政策",
        "definition": "再生可能エネルギー・省エネ・蓄電・水素・CCS等のクリーンエネルギー技術の開発・実証・普及を促進する政策の総称を指す。炭素価格・再エネ目標・技術ロードマップが主要手段である。",
        "impact_summary": "エネルギーシステムの急速な脱炭素化に必要な技術革新を政策的投資と市場形成の組み合わせで加速する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "sustainability_transition",
        "era_start": 1990,
        "innovation_type": "policy",
        "cognitive_mechanism": "transformative",
        "keywords_ja": "クリーンエネルギー政策,脱炭素,再エネ,蓄電技術政策",
        "keywords_en": "clean energy innovation policy,decarbonization,renewable energy,storage technology policy",
        "key_researchers": '["Jacobsson S.", "Bergek A."]',
        "key_works": '["Innovation System Analysis (2004)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_668",
        "name_en": "Data-Driven Innovation",
        "name_ja": "データ駆動型イノベーション",
        "definition": "大量データ・AI・機械学習を活用してイノベーションを加速するビジネスモデル・研究手法・政策アプローチを指す。データ共有・データ市場・プライバシー保護・データポータビリティが政策課題となる。",
        "impact_summary": "データの経済的・科学的価値を最大化するために必要なデータガバナンスとイノベーション政策を設計する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "digital_governance",
        "era_start": 2012,
        "innovation_type": "policy",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "データ駆動イノベーション,データ市場,データガバナンス,AI活用",
        "keywords_en": "data-driven innovation,data market,data governance,AI application",
        "key_researchers": '["OECD", "Mayer-Schonberger V."]',
        "key_works": '["Data-Driven Innovation (2015)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_669",
        "name_en": "Evaluation of National Innovation Policies",
        "name_ja": "国家イノベーション政策の評価",
        "definition": "国全体のイノベーション政策の総体的効果を評価するマクロレベルの枠組みを指す。イノベーションシステムの全体的な機能・成果・効率を総合的に判断するためのフレームワークである。",
        "impact_summary": "イノベーション政策全体の整合性と実効性を点検し、政策改革の方向性と優先順位を明確にする。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "evidence_based_policy",
        "era_start": 2000,
        "innovation_type": "methodology",
        "cognitive_mechanism": "evaluative",
        "keywords_ja": "政策評価,国家イノベーション,政策整合性,政策審査",
        "keywords_en": "national innovation policy evaluation,policy coherence,policy review,system performance",
        "key_researchers": '["Borras S.", "Edquist C."]',
        "key_works": '["The Choice of Innovation Policy Instruments (2013)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
    {
        "id": "inno_pol_670",
        "name_en": "Process Tracing in Policy Research",
        "name_ja": "政策研究におけるプロセストレーシング",
        "definition": "政策の因果メカニズムを文書・証言・観察等の証拠を系統的にたどることで解明する質的研究手法を指す。政策の「なぜうまくいったか」「なぜ失敗したか」を詳細に分析する。",
        "impact_summary": "計量的手法では捉えにくい政策の因果経路と文脈依存性を明らかにし、政策の「なぜ」を解明する。",
        "subfield": "measurement_policy_governance",
        "school_of_thought": "policy_analysis",
        "era_start": 2000,
        "innovation_type": "methodology",
        "cognitive_mechanism": "analytical",
        "keywords_ja": "プロセストレーシング,因果メカニズム,質的研究,政策分析",
        "keywords_en": "process tracing,causal mechanism,qualitative research,policy analysis",
        "key_researchers": '["Beach D.", "Pedersen R.B."]',
        "key_works": '["Causal Case Study Methods (2016)"]',
        "status": "active",
        "source_reliability": "secondary",
        "data_completeness": 80,
        "created_at": now,
        "updated_at": now
    },
]

conn = sqlite3.connect(db_path)
cursor = conn.cursor()
for e in entries:
    cursor.execute("""
        INSERT OR REPLACE INTO innovation_theory
        (id, name_en, name_ja, definition, impact_summary, subfield, school_of_thought,
         era_start, innovation_type, cognitive_mechanism, keywords_ja, keywords_en,
         key_researchers, key_works, status, source_reliability, data_completeness,
         created_at, updated_at)
        VALUES (:id, :name_en, :name_ja, :definition, :impact_summary, :subfield,
                :school_of_thought, :era_start, :innovation_type, :cognitive_mechanism,
                :keywords_ja, :keywords_en, :key_researchers, :key_works, :status,
                :source_reliability, :data_completeness, :created_at, :updated_at)
    """, e)
conn.commit()
conn.close()
print(f"Inserted {len(entries)} entries")
