#!/usr/bin/env python3
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
    ("inno_digi_251","クラウドネイティブ開発とサーバーレスアーキテクチャ","Cloud-Native Development and Serverless Architecture","クラウドネイティブはコンテナ・マイクロサービス・DevOps・継続的デリバリーを統合する開発哲学。CNCF（Cloud Native Computing Foundation）がKubernetes中心のエコシステムを標準化した。サーバーレス（AWS Lambda・Google Cloud Functions）はインフラ管理を完全抽象化しイベント駆動型開発を実現する。Richardson（2018）のマイクロサービスパターン集が実装知識を体系化した。","platform_digital_innovation","クラウドコンピューティング",2015,None,"meso","ソフトウェア産業","クラウドネイティブ移行","開発速度を最大化するアーキテクチャを選択する際","サーバーレスはどのような開発・運用コストを削減するか","オンプレミス","クラウドネイティブ,サーバーレス,Kubernetes,CNCF","cloud-native,serverless,Kubernetes,CNCF","active","secondary",78,'["Chris Richardson", "Kelsey Hightower"]','["Richardson 2018", "CNCF Annual Survey 2023"]',"デプロイ頻度・インフラコスト"),
    ("inno_digi_252","デジタルヘルス・テレメディシンの拡大","Digital Health and Telemedicine Expansion","COVID-19パンデミックはテレヘルス利用を10-30倍に拡大させ、遠隔診療・RPM（遠隔患者モニタリング）・デジタル治療（DTx）が新標準となった。Dorsey & Topol（2016）はスマートフォンが医療のプラットフォームになる「Smartphone Medicine」を予言した。FDA DTx承認プロセス・CMS遠隔診療保険適用規則が制度的基盤を形成。健康データのプライバシー（HIPAA）・医師-患者関係の変容が倫理・規制課題となる。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"meso","医療","デジタルヘルス戦略","医療DXを推進する際","デジタルヘルス技術はどのように医療アクセスを改善するか","対面医療","テレヘルス,デジタル治療,DTx,遠隔医療","telehealth,digital therapeutics,DTx,remote care","active","secondary",78,'["Eric Topol", "E. Ray Dorsey"]','["Dorsey Topol 2016 Lancet", "FDA DTx 2017"]',"テレヘルス利用率・医療コスト削減"),
    ("inno_digi_253","EdTechプラットフォームと学習分析","EdTech Platforms and Learning Analytics","EdTechはMOOC（Coursera・edX・Udemy）・LMS（Moodle・Canvas）・アダプティブラーニング（Khan Academy）・VR学習を包含する教育技術産業。Siemens & Long（2011）が学習分析（Learning Analytics）の基礎を定義し、学習データから個別指導を最適化する枠組みを提示した。UNESCO EdTech報告（2023）はEdTech投資ブームの後退と「EdTech失望（EdTech disillusionment）」を記録し、効果測定の厳密化を求めた。","platform_digital_innovation","デジタルトランスフォーメーション",2011,None,"meso","教育","EdTech導入・評価","教育デジタル化を検討する際","EdTechはどのような学習成果改善をもたらすか","対面集合教育","EdTech,MOOC,学習分析,アダプティブラーニング","EdTech,MOOC,learning analytics,adaptive learning","active","secondary",76,'["George Siemens", "Phil Long"]','["Siemens Long 2011", "UNESCO EdTech 2023"]',"学習成果・完了率・コスト効率"),
    ("inno_digi_254","サプライチェーンデジタル化とトレーサビリティ","Supply Chain Digitalization and Traceability","サプライチェーンのデジタル化はERP・SCM・ブロックチェーン・IoTを統合してリアルタイム可視性を実現する。COVID-19のサプライチェーン混乱（2020-2022）がデジタルレジリエンスの重要性を顕在化させた。Walmart・Maerskのブロックチェーントレーサビリティ導入が食品安全・物流効率に成果を示した。Sheffi（2020）の「ニュー（AB）ノーマル」はサプライチェーン戦略の多元化を論じた。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"meso","サプライチェーン","SC デジタル化戦略","サプライチェーンリスクを管理する際","サプライチェーンのデジタル化はどのようなレジリエンスをもたらすか","線形サプライチェーン","サプライチェーン,デジタル化,トレーサビリティ,ブロックチェーン","supply chain,digitalization,traceability,blockchain","active","secondary",78,'["Yossi Sheffi", "Hau Lee"]','["Sheffi 2020", "IBM Food Trust Case 2018"]',"在庫精度・納期遵守率"),
    ("inno_digi_255","RegTechと金融規制テクノロジー","RegTech and Financial Regulatory Technology","RegTech（Regulatory Technology）はAI・自然言語処理・ブロックチェーンを活用してAML・KYC・リスク管理・規制報告の自動化を実現する。FCA（英国金融行動監視機構）がRegTech用語を2015年に定式化した。Institute of International Finance（2016）はRegTechを規制コストの60-70%削減ポテンシャルがあると評価した。マネーロンダリング監視のAI化・リアルタイム取引監視・規制変更への自動適応が主要適用領域。","platform_digital_innovation","デジタルトランスフォーメーション",2015,None,"meso","金融規制","RegTech導入評価","金融規制コンプライアンスを効率化する際","RegTechは規制コンプライアンスコストをどう削減するか","人手規制対応","RegTech,AML,KYC,規制技術,金融","RegTech,AML,KYC,regulatory technology,financial","active","secondary",76,'["FCA", "Chris Skinner"]','["FCA RegTech Report 2015", "IIF RegTech Study 2016"]',"コンプライアンスコスト・誤検知率"),
    ("inno_digi_256","デジタルヘルスとウェアラブルデータ活用","Digital Health and Wearable Data Utilization","Apple Watch・Fitbit・Garminなどのウェアラブルデバイスが心拍・血糖・睡眠・活動量のリアルタイムデータを収集し医療研究・予防医療に活用される。Topol（2019）の「Deep Medicine」はウェアラブルデータとAIが個別化医療を実現すると論じた。Apple Heart StudyはApple Watch不整脈検知の精度をMayoClinicとの共同研究で実証した。FDA承認デジタルバイオマーカーの開発が臨床試験コスト削減と薬事承認加速に寄与している。","platform_digital_innovation","デジタルトランスフォーメーション",2019,None,"meso","医療・ウェルネス","ウェアラブルヘルスデータ活用","予防医療・個別化医療を設計する際","ウェアラブルデータは医療意思決定をどう改善するか","定期検診モデル","ウェアラブル,デジタルヘルス,バイオマーカー,予防医療","wearable,digital health,biomarker,preventive care","active","secondary",78,'["Eric Topol", "Calum MacRae"]','["Topol 2019 Deep Medicine", "Apple Heart Study 2019"]',"バイオマーカー精度・予防効果"),
    ("inno_digi_257","ヴァーチャルパワープラントとエネルギーデジタル化","Virtual Power Plant and Energy Digitalization","ヴァーチャルパワープラント（VPP）は分散電源（太陽光・蓄電池・EV）をクラウドで束ねて仮想的な発電所として運用するデジタルエネルギー技術。Pudjianto et al.（2007）がVPP概念の経済的・技術的フレームを提示した。Tesla Powerwall・Sonnen・AGL等がVPP商用化を展開。日本でのVPP実証事業（経済産業省）が需給調整市場への参入モデルを検証している。","platform_digital_innovation","エネルギー・環境DX",2007,None,"meso","エネルギー","VPP事業設計","分散型エネルギー資源を活用する際","VPPはどのようにエネルギー系統を最適化するか","集中型発電所","VPP,分散電源,太陽光,蓄電池,EV","VPP,distributed energy,solar,battery,EV","active","secondary",76,'["Danny Pudjianto", "Goran Strbac"]','["Pudjianto et al. 2007", "Tesla VPP Case 2022"]',"需給調整量・コスト削減"),
    ("inno_digi_258","デジタル農業とプレシジョンファーミング","Digital Agriculture and Precision Farming","プレシジョンファーミングは衛星測位・IoTセンサー・ドローン・AIを組み合わせて農業投入物（肥料・農薬・水）を最適化し、収量増加と環境負荷低減を同時達成する。Paustian & Theuvsen（2017）は精密農業の採用決定要因を実証した。John Deere Operations Center・Trimble Agriculture・Climate Corporation（Monsanto）がプラットフォームを展開。衛星データを活用した作物保険・土壌炭素クレジットが新規事業として台頭している。","platform_digital_innovation","デジタルトランスフォーメーション",2015,None,"meso","農業","デジタル農業導入","農業生産性向上を追求する際","精密農業はどのような投入最適化をもたらすか","慣行農業","精密農業,IoT,ドローン,AI,農業DX","precision farming,IoT,drone,AI,agriculture DX","active","secondary",76,'["Matthias Paustian", "Leo Theuvsen"]','["Paustian Theuvsen 2017", "John Deere Connected Farm"]',"収量・投入コスト・CO2排出"),
    ("inno_digi_259","デジタル文化産業とコンテンツプラットフォーム","Digital Cultural Industries and Content Platforms","Spotify・Netflix・YouTube等のデジタルコンテンツプラットフォームは録音・映像・出版産業の流通構造を根本変革した。Elberse（2013）の「ブロックバスター」研究はデジタル化がコンテンツ消費のロングテール化よりスーパースターへの集中を強化することを示した。音楽ストリーミングはCDからの収益移転でレーベルと独立アーティストのパワー関係を変容させた。ユーザー生成コンテンツ（UGC）プラットフォーム（YouTube・TikTok）がプロとアマの境界を曖昧にした。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2013,None,"meso","文化産業","デジタルコンテンツ戦略","デジタル時代の文化産業ビジネスモデルを分析する際","デジタル化は文化産業の収益構造をどう変えるか","物理メディア","デジタルコンテンツ,Spotify,Netflix,ロングテール,UGC","digital content,Spotify,Netflix,long tail,UGC","active","secondary",78,'["Anita Elberse", "Will Page"]','["Elberse 2013 Blockbusters", "Will Page Tarzan Economics 2021"]',"ストリーミング収益・アーティスト収益"),
    ("inno_digi_260","デジタル通貨とCBDC","Digital Currency and CBDC","中央銀行デジタル通貨（CBDC）は政府発行の法定デジタル通貨で、金融包摂・支払い効率化・通貨政策の新ツールとなる。BIS（2021）の調査では中央銀行の86%がCBDC研究を行っていると報告。中国デジタル人民元（e-CNY）が先行実証実験を展開し、バハマ「Sand Dollar」・ナイジェリア「eNaira」が本格導入した。民間暗号資産（Bitcoin・Ether）との競合・金融安定リスク・プライバシーが主要政策論点。","platform_digital_innovation","デジタル金融",2021,None,"macro","金融・中央銀行","CBDC設計・政策評価","中央銀行デジタル通貨政策を検討する際","CBDCは金融システムにどのような変化をもたらすか","現金・銀行預金","CBDC,デジタル通貨,e-CNY,金融包摂","CBDC,digital currency,e-CNY,financial inclusion","active","secondary",78,'["BIS Research Staff", "Agustin Carstens"]','["BIS CBDC Report 2021", "IMF CBDC Staff Discussion Note"]',"CBDC導入国数・取引量"),
    ("inno_digi_261","自動運転技術の段階的発展とビジネスモデル","Autonomous Driving Technology Development and Business Model","SAEレベル0-5の自動化段階でADAS（先進運転支援）からフル自動運転への技術ロードマップが描かれる。Waymo・Tesla・Mobileye・Cruise等が競争し、ロボタクシー（RoboTaxi）サービスが商用化フェーズに入っている。Litman（2020）は自動運転の社会的便益（安全・渋滞・エネルギー）を総合評価した。保険・法的責任・インフラ整備・倫理（トロッコ問題）が産業化の制度的課題となっている。","platform_digital_innovation","AI・機械学習",2016,None,"macro","モビリティ","自動運転戦略・規制","自動運転技術の産業化を評価する際","自動運転はどのようなビジネスモデルで収益化するか","人間ドライバー","自動運転,SAEレベル,Waymo,Tesla,ロボタクシー","autonomous driving,SAE level,Waymo,Tesla,robotaxi","active","secondary",78,'["Todd Litman", "Chris Urmson"]','["Litman 2020 VTPI", "SAE J3016 2021"]',"自動運転走行距離・事故率"),
    ("inno_digi_262","電子政府とGovTechイノベーション","E-Government and GovTech Innovation","GovTech（Government Technology）はデジタル技術で公共サービス・政策立案・規制執行を改革する。エストニアの電子政府（x-Road基盤、1996-）が先進モデルとして世界に参照され、デジタルIDから行政手続全面電子化を実現した。UN E-Government Development Index（EGDI）で各国のデジタル行政成熟度が評価される。シンガポールGovTech・英国GDS（Government Digital Service）・米国USDS（US Digital Service）が組織モデルを提供する。","platform_digital_innovation","デジタルトランスフォーメーション",1996,None,"macro","公共・行政","電子政府設計・評価","行政デジタル化を推進する際","電子政府はどのような行政効率化と市民サービス向上をもたらすか","紙ベース行政","電子政府,GovTech,エストニア,デジタルID,行政DX","e-government,GovTech,Estonia,digital ID,public administration","active","secondary",78,'["Tarmo Kalvet", "Tom Loosemore"]','["UN EGDI 2022", "Estonian e-Gov Case Studies"]',"行政効率・市民満足度"),
    ("inno_digi_263","インフルエンサーエコノミーとクリエイターエコノミー","Influencer Economy and Creator Economy","クリエイターエコノミーはソーシャルメディア・サブスクリプションプラットフォーム（Substack・Patreon）・NFTでコンテンツクリエイターが直接収益化する経済モデル。Signorini（2022）はクリエイターエコノミー市場規模を1040億ドルと推定した。インフルエンサーマーケティングは企業広告の一部を代替し、信頼性・エンゲージメント率でTV広告を超える効果が実証されている。AI生成コンテンツとの競合がクリエイターの差別化戦略に影響する。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2016,None,"meso","メディア・広告","クリエイターエコノミー戦略","コンテンツマーケティング戦略を設計する際","クリエイターエコノミーはどのような収益モデルを生み出したか","従来型メディア","クリエイターエコノミー,インフルエンサー,Patreon,Substack","creator economy,influencer,Patreon,Substack","active","secondary",74,'["Li Jin", "Chris Dixon"]','["Signorini 2022", "Li Jin 2020 a16z"]',"クリエイター収益・エンゲージメント率"),
    ("inno_digi_264","オープンソースとコモンズベース同等生産","Open Source and Commons-Based Peer Production","オープンソースソフトウェア（Linux・Apache・Git）はBenkler（2006）が「コモンズベース同等生産」と呼ぶ非市場的協調生産モデルで開発される。OSS経済への民間企業貢献（Red Hat・IBM・Google）がビジネスモデルとして確立した。GitHub（2008-）はOSS協働基盤を商業化し、2023年に1億開発者が登録した。OSS依存のサプライチェーンリスク（Log4j脆弱性）が信頼性・セキュリティ管理の問題を提起している。","platform_digital_innovation","デジタルプラットフォーム経済",2006,None,"meso","ソフトウェア産業","OSS戦略・ガバナンス","ソフトウェア開発の協調モデルを設計する際","オープンソースはどのようなイノベーション加速メカニズムを持つか","独自開発","オープンソース,Linux,GitHub,コモンズ生産","open source,Linux,GitHub,commons production","active","primary",82,'["Yochai Benkler", "Eric Raymond"]','["Benkler 2006 Wealth of Networks", "Raymond 1999 Cathedral Bazaar"]',"コントリビュータ数・Fork数"),
    ("inno_digi_265","プラットフォームエコシステムとデベロッパーリレーション","Platform Ecosystem and Developer Relations","プラットフォームの価値はサードパーティ開発者が構築する補完財・アプリの厚みに依存する。Parker & Van Alstyne（2018）は開発者エコシステムへの投資（API・SDK・デベロッパープログラム）がプラットフォーム価値創造の核心と論じた。Apple WWDC・Google I/O・AWS re:Inventがデベロッパーコミュニティの信頼形成に機能する。プラットフォーム手数料交渉（Epic vs Apple裁判）がデベロッパーパワーの限界を示した。","platform_digital_innovation","プラットフォーム競争戦略",2018,None,"meso","プラットフォーム産業","デベロッパーエコシステム構築","プラットフォームの開発者戦略を立案する際","デベロッパーエコシステムはどのようにプラットフォーム価値を高めるか","垂直統合","デベロッパー,エコシステム,API,SDK,App Store","developer,ecosystem,API,SDK,App Store","active","secondary",78,'["Geoffrey Parker", "Marshall Van Alstyne"]','["Parker Van Alstyne 2018", "Epic v Apple 2021"]',"App数・開発者数・エコシステム収益"),
    ("inno_digi_266","デジタルマーケットプレイスと流通革命","Digital Marketplace and Distribution Revolution","デジタルマーケットプレイスはAmazon・eBay・Airbnb・Upworkが財・サービス・資産・労働の多様な市場を電子化した。Sundararajan（2016）の「共有経済」はピアツーピア取引が従来の価値連鎖を迂回する仕組みを分析した。Bresnahan & Trajtenberg（1995）の汎用技術論がインターネットの流通変革を説明する枠組みとして援用される。取引安全（レーティング・エスクロー・保証）が信頼メカニズムとして機能する。","platform_digital_innovation","デジタルプラットフォーム経済",2016,None,"meso","流通・小売","デジタル流通戦略","流通のデジタル化を評価する際","デジタルマーケットプレイスはどのような仲介コストを削減するか","物理流通チャネル","デジタルマーケット,共有経済,Airbnb,eBay,P2P","digital marketplace,sharing economy,Airbnb,eBay,P2P","active","primary",80,'["Arun Sundararajan", "Tim Bresnahan"]','["Sundararajan 2016", "Bresnahan Trajtenberg 1995"]',"GMV・取引コスト削減"),
    ("inno_digi_267","ゼロサイドプラットフォームとオープン標準","Zero-Side Platforms and Open Standards","ゼロサイドプラットフォームはLinux・WWW・SMTP・TCP/IPのように無料で誰でも使える開放型基盤標準で、プラットフォーム競争が生じない公共財的性格を持つ。Berners-Lee（1989）のWebのオープン性原則がその典型思想。W3C・IETF・ISOが標準化プロセスを管理し、特許制約のないオープン標準がイノベーションのコモンズを提供する。FRAND（公正・合理的・非差別的）ライセンスが標準必須特許の管理原則として機能する。","platform_digital_innovation","デジタルプラットフォーム経済",1989,None,"macro","IT産業全般","オープン標準政策","デジタルインフラの標準化を検討する際","オープン標準はイノベーションにどのような正の外部性をもたらすか","独自標準","オープン標準,WWW,IETF,FRAND,公共財","open standards,WWW,IETF,FRAND,public goods","active","secondary",80,'["Tim Berners-Lee", "Carl Cargill"]','["Berners-Lee 1989", "IETF RFC History"]',"標準採用率・イノベーション貢献度"),
    ("inno_digi_268","デジタルID・自己主権型アイデンティティ","Digital ID and Self-Sovereign Identity","デジタルIDはオンラインサービスの認証基盤であり、中央集権型（Facebook Login・Google OAuth）から分散型（自己主権型SSI）への転換が議論されている。W3C DID仕様（2022）がSSIの技術標準を定め、EU European Digital Identity（eIDAS2）が公的デジタルID基盤を整備する。インドAadhaar（14億人登録）とブラジルPIXの成功が発展途上国のデジタルID普及モデルを示した。プライバシー・排除リスク・生体認証の倫理が論点となっている。","platform_digital_innovation","データ経済",2019,None,"macro","公共・金融","デジタルID基盤設計","デジタルアイデンティティシステムを構築する際","自己主権型IDは中央集権型IDのどの問題を解決するか","中央集権型ID","デジタルID,SSI,Aadhaar,eIDAS,生体認証","digital ID,SSI,Aadhaar,eIDAS,biometrics","active","secondary",76,'["Drummond Reed", "Christopher Allen"]','["W3C DID 2022", "eIDAS2 2024"]',"ID登録数・認証コスト"),
    ("inno_digi_269","合成メディアとディープフェイク技術の倫理","Synthetic Media and Deepfake Ethics","GANやDiffusionモデルによる合成メディアは顔・音声・映像のリアルな偽造を可能にし、フェイクニュース・詐欺・政治操作のリスクを高める。Chesney & Citron（2019）は「ディープフェイク」が証拠・信頼・民主主義へもたらす「情報真正性の危機」を論じた。C2PA（Content Credentials・メディアアセンティケーション仕様）がAIコンテンツの来歴標準化を推進。合成メディアの創造的応用（映画・VTuber・音楽）との規制バランスが課題。","platform_digital_innovation","AI規制・ガバナンス",2019,None,"macro","メディア・セキュリティ","ディープフェイク対策","合成メディアのリスク管理を設計する際","ディープフェイクはどのような社会的信頼コストを生むか","実写・実声","ディープフェイク,合成メディア,C2PA,フェイクニュース","deepfake,synthetic media,C2PA,fake news","active","secondary",78,'["Robert Chesney", "Danielle Citron"]','["Chesney Citron 2019 Foreign Affairs", "C2PA Spec 2022"]',"ディープフェイク検知精度・インシデント件数"),
    ("inno_digi_270","モバイルファーストイノベーションと新興国跳び越し","Mobile-First Innovation and Leapfrogging in Emerging Markets","新興国では固定インターネット・PCインフラを跳び越してスマートフォンがデジタル経済の主要アクセス手段となった。M-Pesa（ケニア、2007）はモバイル送金で銀行口座なし人口の金融包摂を実現した先行事例。Aker & Mbiti（2010）はアフリカにおける携帯電話普及が農業市場価格情報・労働市場効率を改善することを実証した。インドJio（2016年低価格データ普及）・インドネシアGojekが後発優位の跳び越し事例を提供する。","platform_digital_innovation","デジタルプラットフォーム経済",2007,None,"meso","新興国市場","モバイルファースト戦略","新興国デジタル市場参入を検討する際","モバイルファーストイノベーションはどのような市場を創出するか","固定通信インフラ","モバイルファースト,M-Pesa,跳び越し,新興国,金融包摂","mobile-first,M-Pesa,leapfrogging,emerging market,financial inclusion","active","primary",80,'["Jenny Aker", "Isaac Mbiti"]','["Aker Mbiti 2010 JEP", "Safaricom M-Pesa Case"]',"モバイル普及率・金融包摂指標"),
    ("inno_digi_271","AIによる科学的発見の加速","AI-Accelerated Scientific Discovery","AlphaFold2（タンパク質構造）・AlphaMold（数学定理）・GNoME（材料発見）に代表されるAIは科学的発見プロセスを加速する。Wang et al.（2023）はAIが生命科学論文の質と速度を向上させることを実証した。「AI for Science」ムーブメントがNIH・DARPA・欧州Horizon等の研究投資プログラムを再設計しつつある。AIが仮説生成・実験設計・データ解析を支援する「第四の科学パラダイム」（Hey 2009）の深化が進む。","platform_digital_innovation","AI・機械学習",2021,None,"macro","科学研究","AI活用研究設計","科学研究にAIを活用する際","AIはどのような科学分野で最大の発見加速をもたらすか","人手実験","AI for Science,AlphaFold,材料発見,科学加速","AI for Science,AlphaFold,materials discovery,scientific acceleration","active","primary",82,'["Demis Hassabis", "Tony Hey"]','["Jumper et al. 2021 AlphaFold2", "Hey 2009 4th Paradigm"]',"発見速度・論文質スコア"),
    ("inno_digi_272","デジタルツールとリモートワーク生産性","Digital Tools and Remote Work Productivity","COVID-19以降のリモートワーク定着はZoom・Slack・Microsoft Teams・Notionなどの非同期・同期コラボレーションツールへの依存を急拡大させた。Barrero et al.（2021）はリモートワーカーの生産性は業種・職種によって異なり、一部で+13%向上を示した。ハイブリッドワークモデルが定着するなか、デジタルオフィス環境の設計（非同期ドキュメント文化・バーチャルウォーターク―ラー）が組織生産性の鍵となった。","platform_digital_innovation","デジタルトランスフォーメーション",2020,None,"micro","知識産業","リモートワーク生産性管理","ハイブリッドワーク環境を設計する際","デジタルツールはリモートワーク生産性をどう変えるか","対面オフィス","リモートワーク,生産性,Zoom,Microsoft Teams,ハイブリッド","remote work,productivity,Zoom,Microsoft Teams,hybrid","active","secondary",80,'["Jose Maria Barrero", "Nicholas Bloom"]','["Barrero et al. 2021 NBER", "Bloom 2021 WFH Research"]',"生産性変化率・出社率"),
    ("inno_digi_273","量子通信と次世代セキュリティ","Quantum Communication and Next-Generation Security","量子通信（量子鍵配送・量子テレポーテーション）は量子力学の原理を利用して盗聴不可能な通信を実現する。中国が2016年に打ち上げた量子衛星「墨子」が宇宙量子通信の概念実証を成功させた。Post-Quantum Cryptography（PQC）はNISTが2022年に4方式を標準化し、現行暗号（RSA・楕円曲線）を量子コンピュータ攻撃から保護する移行計画が進む。ハーヴェスト・ナウ・デクリプト・レーター攻撃への対応が緊急課題となっている。","platform_digital_innovation","サイバーセキュリティ",2016,None,"macro","通信・安全保障","量子セキュリティ移行","量子コンピュータ時代のセキュリティを設計する際","量子通信はどのようなセキュリティ課題を解決するか","古典暗号","量子通信,PQC,量子鍵配送,NIST","quantum communication,PQC,QKD,NIST","active","secondary",76,'["Charles Bennett", "Artur Ekert"]','["NIST PQC 2022", "Pan Jianwei 2016 Micius"]',"量子鍵配送距離・PQC移行率"),
    ("inno_digi_274","デジタルプラットフォームと民主主義","Digital Platforms and Democracy","ソーシャルメディアプラットフォームは選挙・政治的言説・民主的討議に多面的影響を与える。Tucker et al.（2018）は「ソーシャルメディアと民主主義」の総合レビューで偽情報・分極化・監視資本主義のリスクを整理した。Brexit・米大統領選2016でのCambridge Analytica事件がプラットフォーム政治介入の実態を顕在化させた。コンテンツモデレーション・マイクロターゲット広告規制・アルゴリズム透明性が民主主義保護の政策ツールとして議論される。","platform_digital_innovation","プラットフォーム規制",2018,None,"macro","政治・メディア","プラットフォーム民主主義影響分析","デジタルプラットフォームの政治的影響を評価する際","プラットフォームは民主主義プロセスにどう介入するか","従来型マスメディア","プラットフォーム,民主主義,偽情報,分極化,選挙","platform,democracy,disinformation,polarization,election","active","secondary",80,'["Joshua Tucker", "Eli Pariser"]','["Tucker et al. 2018 SSRC", "Pariser 2011 Filter Bubble"]',"偽情報拡散率・政治的分極化指標"),
    ("inno_digi_275","AI医薬品発見と創薬革命","AI Drug Discovery and Pharmaceutical Revolution","AIは創薬の標的同定・リード最適化・毒性予測・臨床試験設計を加速し、10-15年・数十億ドルの開発コスト構造を変革しつつある。Zhavoronkov et al.（2019）はGANを用いた創薬候補生成を世界初の臨床試験入り化合物として報告した。Insilico Medicine・Exscientia・Recursion Pharmaceuticalsが主要プレイヤー。AlphaFold2の構造データベース公開がAI創薬の基盤データを飛躍的に拡充した。","platform_digital_innovation","生成AI応用",2019,None,"meso","製薬・バイオテック","AI創薬戦略","創薬プロセスへのAI導入を検討する際","AIはどの創薬フェーズで最大の効率化をもたらすか","実験ベース創薬","AI創薬,AlphaFold,Insilico,GAN,製薬","AI drug discovery,AlphaFold,Insilico,GAN,pharmaceutical","active","primary",80,'["Alex Zhavoronkov", "Mike Bax"]','["Zhavoronkov et al. 2019 Nature Biotechnology", "AlphaFold2 2021"]',"臨床入り速度・開発コスト削減"),
    ("inno_digi_276","ソーシャルコマースとライブコマース","Social Commerce and Live Commerce","ソーシャルコマースはSNS上での購買を直接実現し、ライブコマース（TikTok Shop・淘宝直播）は配信者が実演しながら販売するフォーマット。中国ライブコマース市場は2023年に4.9兆元（65兆円）に達した。Kim & Johnson（2016）がソーシャルコマースの購買意図に影響する「社会的支援・共有・推薦」を分析した。Instagram Shopping・Pinterest・YouTube Shoppingが西側市場でのソーシャルコマース拡大を牽引している。","platform_digital_innovation","デジタルプラットフォーム経済",2016,None,"meso","小売・EC","ソーシャルコマース戦略","SNSを収益化する際","ライブコマースはどのような購買行動変容をもたらすか","伝統的EC","ソーシャルコマース,ライブコマース,TikTok Shop,淘宝","social commerce,live commerce,TikTok Shop,Taobao Live","active","secondary",76,'["Shu-Chuan Chu", "Kim Johnson"]','["Kim Johnson 2016", "iResearch Live Commerce Report 2023"]',"ライブコマース市場規模・コンバージョン率"),
    ("inno_digi_277","クリーンテックとデジタルの交差点","Cleantech and Digital Intersection","クリーンテックイノベーションはAI・IoT・ビッグデータと融合し、エネルギー・交通・廃棄物管理の脱炭素化を加速する。Google DeepMindのAIによるデータセンター冷却最適化（40%エネルギー削減）が産業応用事例として引用される。Climate TechベンチャーへのVC投資は2022年に700億ドルを超え、Cleantech 2.0ブームが進行中。デジタルカーボントラッカー・グリーン電力証書（REC）のブロックチェーン管理が新規サービスとして台頭している。","platform_digital_innovation","エネルギー・環境DX",2020,None,"macro","エネルギー・クリーンテック","CleanTech×デジタル戦略","GHG削減にデジタル技術を活用する際","デジタル技術はクリーンテックのスケールアップをどう支援するか","アナログエネルギー管理","クリーンテック,AI,カーボントラッカー,デジタル脱炭素","cleantech,AI,carbon tracker,digital decarbonization","active","secondary",76,'["James Arbib", "Tony Seba"]','["Google DeepMind Cooling 2016", "Climate Tech VC Report 2022"]',"CO2削減量・投資額"),
    ("inno_digi_278","ゲーミフィケーションとエンゲージメント設計","Gamification and Engagement Design","ゲーミフィケーションはゲーム要素（ポイント・バッジ・ランキング・クエスト）を非ゲーム文脈に適用してエンゲージメント・行動変容・学習を促進する。Deterding et al.（2011）が学術概念として定式化し、Duolingo・Starbucks Rewards・Nike Runが成功事例を提供した。Hamari et al.（2014）のシステマティックレビューはゲーミフィケーションの有効性証拠を整理し、コンテキスト依存性を示した。過度なゲーミフィケーションによる「内発的動機づけ阻害」リスクも指摘される。","platform_digital_innovation","デジタルプラットフォーム経済",2011,None,"micro","教育・小売・健康","ゲーミフィケーション設計","ユーザーエンゲージメントを高める際","ゲーミフィケーションはどのような行動変容に有効か","伝統的インセンティブ","ゲーミフィケーション,エンゲージメント,Duolingo,ポイント","gamification,engagement,Duolingo,points","active","primary",80,'["Sebastian Deterding", "Juho Hamari"]','["Deterding et al. 2011 CHI", "Hamari et al. 2014 HICSS"]',"エンゲージメント率・行動変容率"),
    ("inno_digi_279","デジタル経済の計測と国民経済計算","Measurement of Digital Economy and National Accounts","デジタル経済の無形資産・プラットフォーム・無料サービスはGDPで捕捉困難で経済統計の課題となっている。Brynjolfsson et al.（2019）は消費者余剰調査でFacebook・Googleの無料サービスの経済的価値を推計した。OECDの「デジタル経済見通し（DEON）」・世界銀行のデジタル指標が国際比較基準を提供。Coyle（2014）の「GDP: その短くも奇妙な歴史」がデジタル時代のGDP限界を論じた。","platform_digital_innovation","データ経済",2019,None,"macro","経済統計","デジタル経済の計測","デジタル産業の経済規模を評価する際","デジタル経済はどのようにGDP統計に反映されているか","伝統的GDP","デジタル経済,GDP,消費者余剰,無形資産,計測","digital economy,GDP,consumer surplus,intangible assets,measurement","active","primary",80,'["Erik Brynjolfsson", "Diane Coyle"]','["Brynjolfsson et al. 2019 AEA", "Coyle 2014"]',"デジタル経済規模・消費者余剰"),
    ("inno_digi_280","自然語インターフェースと会話型AI","Natural Language Interface and Conversational AI","LLMによる自然語インターフェースは人とコンピュータのインタラクションパラダイムを「コマンド型」から「対話型」に転換しつつある。Amazon Alexa・Google Assistant・Apple Siriがスマートスピーカー市場を形成し、ChatGPTが「Chat as Interface」を一般化した。Shum et al.（2018）は社会的会話AI（XiaoIce）の評価フレームを提示した。音声・テキスト・マルチモーダルの統合が次世代UIの基盤となる。","platform_digital_innovation","AI・機械学習",2018,None,"meso","全産業","会話型AIシステム設計","自然言語インターフェースを実装する際","会話型AIはどのような業務インターフェースを変革するか","メニュー型GUI","会話型AI,LLM,ChatGPT,Alexa,マルチモーダル","conversational AI,LLM,ChatGPT,Alexa,multimodal","active","secondary",80,'["Hsiao-Wuen Hon", "Heung-Yeung Shum"]','["Shum et al. 2018 AI Magazine", "OpenAI ChatGPT 2022"]',"ユーザー数・タスク完了率"),
    ("inno_digi_281","ハイブリッドクラウドとマルチクラウド戦略","Hybrid Cloud and Multi-Cloud Strategy","ハイブリッドクラウドはオンプレミスとパブリッククラウドを統合し、マルチクラウドは複数のクラウドプロバイダーを並行活用する戦略。IDC（2022）はエンタープライズの82%がハイブリッド/マルチクラウド環境を採用していると報告した。ベンダーロックイン回避・コスト最適化・コンプライアンス対応がマルチクラウド採用の主要動機。Gartner（2022）はマルチクラウド管理の複雑性が企業の主要ITリスクとなることを予測した。","platform_digital_innovation","クラウドコンピューティング",2018,None,"meso","大企業IT","クラウド戦略設計","クラウド環境の最適化を検討する際","ハイブリッド/マルチクラウドはどのようなビジネス価値を提供するか","シングルクラウド","ハイブリッドクラウド,マルチクラウド,ベンダーロックイン","hybrid cloud,multi-cloud,vendor lock-in","active","secondary",78,'["IDC Research", "Gartner Research"]','["IDC CloudPulse 2022", "Gartner Magic Quadrant 2022"]',"クラウド採用率・コスト最適化"),
    ("inno_digi_282","デジタルウォレットと決済エコシステム","Digital Wallet and Payment Ecosystem","デジタルウォレット（Apple Pay・Google Pay・PayPal・WeChat Pay）は支払いの摩擦を取り除き、非接触・QRコード・P2P送金を普及させた。BIS（2022）のデジタル決済レポートは非現金決済比率の国際比較を行い、スウェーデン・中国・韓国が先進事例として示された。BNPL（Buy Now Pay Later：Klarna・Afterpay）が若年層の信用商品として急成長し、FSB（金融安定理事会）が規制論点を整理した。","platform_digital_innovation","デジタル金融",2014,None,"meso","金融・小売","デジタル決済戦略","決済体験を改善する際","デジタルウォレットはどのような決済摩擦を除去するか","現金・カード決済","デジタルウォレット,Apple Pay,BNPL,Klarna,非接触","digital wallet,Apple Pay,BNPL,Klarna,contactless","active","secondary",78,'["BIS Research", "FSB Staff"]','["BIS Digital Payment Report 2022", "FSB BNPL 2022"]',"非現金決済率・取引量"),
    ("inno_digi_283","プラットフォームイノベーションと開発途上国経済","Platform Innovation and Developing Country Economics","デジタルプラットフォームは開発途上国において市場失敗（情報非対称・取引コスト）を克服し、農業・金融・医療・教育アクセスを改善する。Manyika et al.（2016）のMGIレポートはデジタルプラットフォームが2025年までに途上国GDP6.9兆ドルを創出すると予測した。M-Kopa（太陽光装置分割払い）・Jumia（アフリカEC）・mHealth等が実用事例を提供。中国BRIのデジタルインフラ展開が「デジタルシルクロード」として地政学的論点となっている。","platform_digital_innovation","デジタルプラットフォーム経済",2016,None,"macro","開発途上国","途上国デジタル経済戦略","途上国市場のデジタル化を評価する際","プラットフォームは途上国経済にどのような包摂効果をもたらすか","伝統的市場","途上国,プラットフォーム,M-Kopa,デジタル包摂,BRI","developing country,platform,M-Kopa,digital inclusion,BRI","active","secondary",76,'["James Manyika", "McKinsey Global Institute"]','["MGI Digital Globalization 2016"]',"経済効果額・包摂指標"),
    ("inno_digi_284","ウェブ3.0とセマンティックウェブの再構成","Web 3.0 and Semantic Web Reconstitution","ウェブ3.0はBerners-Lee（2001）のセマンティックウェブ（機械可読データ）概念と、ブロックチェーン技術による分散型ウェブ（Web3）の二つの文脈で使われる。前者はOntologyデータモデル・RDF・SPARQL・Knowledge Graphとして発展し、Googleナレッジグラフ・Wikidata・DBpediaに実装された。後者は非中央集権・トークンエコノミクス・スマートコントラクトの文脈で急拡大した。両者の概念的接続がLinked DataとDIDの統合で進行中。","platform_digital_innovation","Web3・分散型経済",2001,None,"meso","IT産業","セマンティック/分散型ウェブ設計","データの機械可読性と分散化を同時追求する際","Web3.0はウェブの情報基盤をどう変えるか","集中型ウェブ","セマンティックウェブ,Web3,知識グラフ,RDF,分散型","semantic web,Web3,knowledge graph,RDF,decentralized","active","secondary",76,'["Tim Berners-Lee", "Gavin Wood"]','["Berners-Lee et al. 2001 Scientific American", "Gavin Wood Web3 2014"]',"知識グラフサイズ・Web3取引量"),
    ("inno_digi_285","グリーンIT・持続可能なデータセンター","Green IT and Sustainable Data Centers","データセンターの電力消費は世界電力の1-2%（IEA 2022）を占め、AI普及で急増が予測されている。PUE（Power Usage Effectiveness）指標が効率基準として使用され、Google・Meta等のハイパースケーラーはPUE1.1以下を達成した。再生可能エネルギーPPA・水冷システム・廃熱利用が持続可能データセンターの技術要素。欧州GDPR電力効率要求・日本グリーン成長戦略が政策的後押しとなる。","platform_digital_innovation","エネルギー・環境DX",2020,None,"meso","IT産業・エネルギー","グリーンデータセンター設計","デジタルインフラのGHG削減を実現する際","グリーンITはデータセンター運営コストと環境負荷をどう削減するか","従来型データセンター","グリーンIT,PUE,データセンター,再エネ,AI電力","green IT,PUE,data center,renewable energy,AI power","active","secondary",76,'["Evan Mills", "IEA Research"]','["IEA Data Centres 2022", "Google Environmental Report 2023"]',"PUE・再エネ率・電力消費"),
    ("inno_digi_286","デジタルツインシティと都市データプラットフォーム","Digital Twin City and Urban Data Platform","都市規模のデジタルツインは都市全体のインフラ・交通・エネルギー・人口流動をリアルタイム仮想空間で再現する。シンガポールVirtual Singapore・フィンランドHelsinki 3D City Model・国交省の3D都市モデル（PLATEAU）が先行事例。Urban Data Platform（UDP）はオープンデータとプライベートデータを統合した都市の共有データ基盤として機能する。市民参加型都市設計・緊急時シミュレーション・不動産評価の高精度化に活用される。","platform_digital_innovation","IoT・エッジコンピューティング",2017,None,"macro","都市・公共","デジタルツイン都市設計","都市計画・管理のデジタル化を推進する際","デジタルツイン都市はどのような都市管理を実現するか","GIS","デジタルツイン都市,Urban Data Platform,PLATEAU,シンガポール","digital twin city,Urban Data Platform,PLATEAU,Singapore","active","secondary",76,'["Kees Kamphuis", "National Land Infrastructure Ministry Japan"]','["Virtual Singapore 2018", "PLATEAU 2020"]',"都市管理コスト・シミュレーション精度"),
    ("inno_digi_287","バイオテクノロジーとデジタルバイオの融合","Biotechnology and Digital Biology Convergence","デジタルバイオロジーは遺伝子編集（CRISPR）・合成生物学・タンパク質工学にAI・計算科学を統合する。CRISPR-Cas9のAlgorithm（Doench Score等）でガイドRNA設計を最適化し、創薬・農業・材料の革新を加速する。Twist Bioscience・Ginkgo Bioworks・Zymergen（Ginkgo傘下）が合成生物学プラットフォームを商業展開。Leroy Hood（2011）の「P4医療（予測・予防・個別化・参加型）」がデジタルバイオの医療応用の指針となっている。","platform_digital_innovation","SpaceTech・DeepTech",2020,None,"macro","バイオテック・製薬","デジタルバイオ戦略","バイオテックとデジタルの融合を分析する際","デジタルバイオはどのような産業革新をもたらすか","伝統的バイオテック","デジタルバイオ,CRISPR,合成生物学,P4医療","digital biology,CRISPR,synthetic biology,P4 medicine","active","secondary",76,'["Leroy Hood", "Jason Kelly"]','["Hood 2011 P4 Medicine", "Ginkgo Bioworks Case 2022"]',"遺伝子回路設計速度・研究コスト"),
    ("inno_digi_288","コンピューテーショナルソーシャルサイエンスの成立","Emergence of Computational Social Science","大規模デジタルデータ（ソーシャルメディア・検索・行動ログ）を用いた社会現象分析が「計算社会科学」として台頭した。Lazer et al.（2009）がCSS創設論文として位置付けられ、Google Flu Trends・Twitter Political Analysis等が先行事例となった。ネットワーク分析・機械学習・ABM（エージェントベースモデリング）が主要手法。プライバシー・代表性バイアス・再現性の課題が方法論的論点となっている。","platform_digital_innovation","データ経済",2009,None,"macro","社会科学全般","計算社会科学研究設計","デジタルデータで社会現象を分析する際","計算社会科学は伝統的社会科学をどう変えるか","質問紙調査","計算社会科学,ビッグデータ,ソーシャルメディア分析,CSS","computational social science,big data,social media analysis,CSS","active","primary",80,'["David Lazer", "Duncan Watts"]','["Lazer et al. 2009 Science", "Salganik 2018 Bit by Bit"]',"研究数・再現性率"),
    ("inno_digi_289","デジタル競争力国際比較：IMD・WEF指標","International Comparison of Digital Competitiveness: IMD and WEF Indices","IMD世界デジタル競争力ランキング（WDCR）とWEFグローバル競争力指数（GCI）の技術柱はデジタルインフラ・スキル・規制・R&Dで各国を評価する。Singapore・Denmark・Switzerland・USA・Swedenが常連上位国。日本は2023年WDCR32位と先進国内での相対的低下が議論された。国家デジタル戦略（EU Digital Compass 2030・米国National Digital Strategy・日本デジタル田園都市国家構想）の比較分析に活用される。","platform_digital_innovation","デジタルプラットフォーム経済",2019,None,"macro","国家デジタル政策","デジタル競争力評価","国家デジタル政策を立案・評価する際","IMD/WEF指標は何を測定しどのような政策示唆を持つか","GDPのみの評価","IMD,WEF,デジタル競争力,国際比較,Digital Compass","IMD,WEF,digital competitiveness,international comparison,Digital Compass","active","secondary",78,'["IMD World Competitiveness Center", "WEF Staff"]','["IMD WDCR 2023", "WEF GCI 2020"]',"デジタル競争力スコア・順位変動"),
    ("inno_digi_290","ソフトウェア定義ネットワークとネットワーク仮想化","Software-Defined Networking and Network Virtualization","SDN（Software-Defined Networking）とNFV（Network Functions Virtualization）はハードウェア依存のネットワーク機能をソフトウェアに移行し、プログラマブルなネットワーク制御を実現する。McKeown et al.（2008）がOpenFlowプロトコルを提案しSDN研究を開拓した。5Gコアネットワークの仮想化・スライシングがSDN/NFVの主要適用領域。Stallings（2015）のSDN教科書がアーキテクチャを体系化した。","platform_digital_innovation","クラウドコンピューティング",2008,None,"meso","通信・クラウド","SDN/NFVアーキテクチャ設計","ネットワークの柔軟性とコスト効率を高める際","SDNはネットワーク管理の複雑性をどう軽減するか","ハードウェアネットワーク","SDN,NFV,OpenFlow,5Gコア,ネットワーク仮想化","SDN,NFV,OpenFlow,5G core,network virtualization","active","secondary",76,'["Nick McKeown", "Scott Shenker"]','["McKeown et al. 2008 SIGCOMM", "ONF SDN 2012"]',"ネットワーク管理コスト・展開速度"),
    ("inno_digi_291","AIチップ競争と半導体産業地政学","AI Chip Competition and Semiconductor Geopolitics","生成AIの普及がNvidia H100・A100への需要を急増させ、半導体サプライチェーンの地政学的重要性が高まった。米国CHIPS Act（2022）・EU Chips Act（2023）・日本半導体戦略がTSMC・Samsung・Intel誘致を競う。Mayer-Schönberger & Cukier（2013）のビッグデータ論がAI時代のデータ=処理能力=知識のトライアングルを示した。EUV露光装置のASML独占とTSMCのファウンドリ支配が技術デカップリングの焦点となっている。","platform_digital_innovation","AI半導体・計算資源",2022,None,"macro","半導体・AI","半導体地政学分析","AI競争力の基盤となる半導体戦略を評価する際","AIチップ競争はどのような地政学的リスクを生むか","ソフトウェア競争","AIチップ,半導体,地政学,TSMC,CHIPS Act","AI chip,semiconductor,geopolitics,TSMC,CHIPS Act","active","secondary",80,'["Chris Miller", "TSMC Executive"]','["Miller 2022 Chip War", "CHIPS Act 2022"]',"AI半導体市場シェア・製造能力"),
    ("inno_digi_292","プロセスマイニングとデジタルプロセス変革","Process Mining and Digital Process Transformation","プロセスマイニングはITシステムのイベントログを分析し、実際のビジネスプロセスを可視化・改善する技術。van der Aalst（2016）が方法論の基礎を確立し、Celonis・Process Goldが商業プラットフォームを展開する。ERP（SAP・Oracle）のログデータから非効率・ボトルネックを自動発見し、RPA・AI自動化の優先順位決定に活用される。Gartner（2022）はプロセスマイニング市場が2026年に24億ドルに達すると予測した。","platform_digital_innovation","デジタルトランスフォーメーション",2016,None,"meso","製造・金融・サービス","プロセス改善・DX","業務プロセスの非効率を可視化・改善する際","プロセスマイニングはどのような業務改善価値をもたらすか","人手プロセス分析","プロセスマイニング,ERP,RPA,Celonis,業務改善","process mining,ERP,RPA,Celonis,process improvement","active","secondary",78,'["Wil van der Aalst", "Alexander Rinke"]','["van der Aalst 2016 Process Mining", "Gartner PM Market 2022"]',"プロセス改善率・ROI"),
    ("inno_digi_293","ローコード・ノーコードプラットフォームと市民開発者","Low-Code/No-Code Platform and Citizen Developer","ローコード・ノーコードプラットフォーム（Salesforce・Microsoft Power Platform・OutSystems・Bubble）はプログラミングスキルなしでもアプリ開発を可能にし「市民開発者」を生み出す。Forrester（2021）はローコード市場が2028年に210億ドルに達すると予測。Richardson & Rymer（2014）がForrester でローコード概念を定義した。Shadow ITリスク・セキュリティ・ガバナンスが企業導入の課題となる。","platform_digital_innovation","デジタルトランスフォーメーション",2014,None,"meso","企業IT","市民開発者プログラム設計","IT開発を民主化する際","ローコードはアプリ開発コストとスピードをどう改善するか","専門開発者依存","ローコード,ノーコード,市民開発者,Power Platform","low-code,no-code,citizen developer,Power Platform","active","secondary",76,'["Clay Richardson", "John Rymer"]','["Forrester Low-Code 2021", "Richardson Rymer 2014 Forrester"]',"開発速度・市民開発者数"),
    ("inno_digi_294","インターネット経済の地理的分布と集積","Geographic Distribution and Agglomeration of Internet Economy","インターネット経済はSilicon Valley・Seattle・New York・Beijing・Shenzhenへの地理的集積が顕著で、Storper（2013）の知識経済の集積理論が適用される。Zook（2005）は.comドメイン分布を用いてインターネット産業の地理的集中を実証した。デジタルノマド・分散チーム・コワーキング空間の普及がアクセシブルな「第二ティア都市」の台頭を促している。COVID後のリモートワーク定着が経済地理の再配置を生んでいる。","platform_digital_innovation","デジタルプラットフォーム経済",2005,None,"macro","経済地理・都市","デジタル産業クラスター政策","デジタルイノベーションの地理的分布を分析する際","インターネット経済はなぜ特定地域に集積するか","物理産業クラスター","インターネット経済,Silicon Valley,集積,デジタルノマド","internet economy,Silicon Valley,agglomeration,digital nomad","active","secondary",76,'["Matthew Zook", "Michael Storper"]','["Zook 2005", "Storper 2013"]',"デジタル産業集中度・地域格差"),
    ("inno_digi_295","AIと雇用：スキルプレミアムと技術偏向的変化","AI and Employment: Skill Premium and Skill-Biased Technical Change","Acemoglu（2023）はAIが以前の自動化と異なり「中間スキル」に加え「高スキル」仕事を代替するリスクを論じ、従来のSBTC（技術偏向的変化）理論の修正を主張した。World Economic Forum「仕事の未来報告書（2023）」は2027年までに6900万の新規雇用創出と8300万の消失を予測した。再スキリング（Reskilling）・アップスキリング政策の設計がAI移行期の労働市場政策の核心となる。","platform_digital_innovation","AI・機械学習",2023,None,"macro","労働市場・政策","AI雇用影響評価","AI導入の雇用影響を分析する際","AIはどのような雇用に最大の代替リスクをもたらすか","肉体労働のみの自動化","AI,雇用,スキルプレミアム,SBTC,リスキリング","AI,employment,skill premium,SBTC,reskilling","active","primary",82,'["Daron Acemoglu", "WEF Research"]','["Acemoglu 2023 AEA", "WEF FoW 2023"]',"雇用変化数・スキルプレミアム"),
    ("inno_digi_296","デジタルエコノミーの税制と国際課税競争","Digital Economy Taxation and International Tax Competition","デジタル企業は物理的拠点なく多国間で収益を得るため、伝統的国際課税（PE原則）が機能しない。OECD/G20 BEPSプロジェクトの「Pillar One（利益配分）・Pillar Two（最低税率15%）」が2023年に大枠合意した。DST（デジタルサービス税）を先行導入したフランス・UK・インドに対し米国が報復関税措置を検討。デジタル経済課税はオープンエコノミーにおける政府収入とプラットフォーム競争力のトレードオフを生む。","platform_digital_innovation","プラットフォーム規制",2021,None,"macro","国際税務・政策","デジタル課税設計","デジタル企業の国際課税問題を分析する際","OECD Pillar One/Twoはデジタル経済の課税課題をどう解決するか","PE原則","デジタル課税,BEPS,Pillar One,Pillar Two,DST","digital tax,BEPS,Pillar One,Pillar Two,DST","active","secondary",78,'["Pascal Saint-Amans", "OECD Tax Policy Division"]','["OECD BEPS 2021", "Pillar Two Model Rules 2021"]',"税収変化・競争力影響"),
    ("inno_digi_297","レコメンダーシステムの多様性・偶発性設計","Diversity and Serendipity Design in Recommender Systems","従来の推薦システムは予測精度（RMSE・MAE）最大化に注力したが、多様性（diversity）・新規性（novelty）・偶発性（serendipity）の欠如がフィルターバブル・エコーチェンバーを生む。Kaminskas & Bridge（2016）が多様性・偶発性の評価指標を体系化した。Spotify's「Discover Weekly」・Netflix「New Releases」が多様性向上設計の事例。個人的関連性と意外性のバランスを最適化する「Beyond Accuracy」研究が活発化している。","platform_digital_innovation","アルゴリズム経済",2016,None,"micro","メディア・EC","推薦システム設計","ユーザー満足度と多様性を両立する際","多様性設計は推薦システムの長期ユーザー価値をどう改善するか","精度最大化型推薦","推薦システム,多様性,偶発性,フィルターバブル","recommender system,diversity,serendipity,filter bubble","active","primary",80,'["Marius Kaminskas", "Derek Bridge"]','["Kaminskas Bridge 2016 TIST"]',"多様性指標・長期エンゲージメント"),
    ("inno_digi_298","デジタルプラットフォームと都市型小売変革","Digital Platform and Urban Retail Transformation","Eコマースの成長と都市型O2O（Online-to-Offline）サービスが都市商業の空間構成・消費行動を変容させる。Hristova et al.（2016）はデジタルフットプリントを使って都市小売の商業集積パターンを分析した。Amazon Goの無人店舗・Alibabaの「新小売（New Retail）」が物理×デジタル融合の事例として研究される。空き店舗問題・都市商業の空洞化がEC拡大の負の外部性として都市政策課題となっている。","platform_digital_innovation","デジタルプラットフォーム経済",2018,None,"meso","小売・都市","デジタル小売戦略","都市小売のデジタル化を分析する際","デジタルプラットフォームは都市商業地区をどう変えるか","物理小売","O2O,新小売,Amazon Go,都市小売,EC","O2O,new retail,Amazon Go,urban retail,EC","active","secondary",76,'["Jack Ma", "Amazon Go Team"]','["Alibaba New Retail White Paper 2018", "Amazon Go Case 2018"]',"EC率・都市空き店舗率"),
    ("inno_digi_299","フィジカルインターネットと物流革命","Physical Internet and Logistics Revolution","フィジカルインターネットはBenjaafar et al.（2013）が提唱した概念で、情報インターネットのプロトコルを物流（モジュール化コンテナ・標準化HUB・動的ルーティング）に応用して効率化する。物流効率70%向上・GHG削減が理論的ポテンシャルとして示された。Europeログイスティクス協会がPI実現ロードマップを2050年目標として策定。Amazon・JD物流・フェデックスのデジタル物流プラットフォームが先行実装を展開する。","platform_digital_innovation","デジタルトランスフォーメーション",2013,None,"macro","物流・サプライチェーン","物流DX設計","物流効率を根本から改善する際","フィジカルインターネットはどのような物流コストを削減するか","独自物流ネットワーク","フィジカルインターネット,物流,PI,サプライチェーン","physical internet,logistics,PI,supply chain","active","secondary",74,'["Shengyong Chen", "Benoit Montreuil"]','["Benjaafar et al. 2013", "Montreuil 2011 Physical Internet"]',"物流コスト・GHG削減"),
    ("inno_digi_300","プラットフォームの失敗：Chicken-and-Egg問題","Platform Failure: Chicken-and-Egg Problem","プラットフォームは両サイドのユーザーを同時に獲得しなければ価値が生まれないChicken-and-Egg問題（卵が先か鶏が先か）に直面する。Evans & Schmalensee（2016）はプラットフォーム立ち上げ戦略として「シーディング・戦略的補助・単一サイド先行・制限付き公開」を分類した。OpenTable（レストラン予約）・Etsy（ハンドメイドEC）が段階的サイド獲得の成功事例として分析される。失敗事例（多くのGoogle+・Amazon Dash Button等）との比較から成功要因が抽出されている。","platform_digital_innovation","プラットフォーム経済学",2016,None,"meso","プラットフォーム産業","プラットフォーム立ち上げ戦略","プラットフォームの初期成長戦略を設計する際","Chicken-and-Egg問題を克服するどのような戦略が有効か","単一製品市場","Chicken-and-Egg,プラットフォーム立ち上げ,シーディング","chicken-and-egg,platform launch,seeding","active","primary",80,'["David Evans", "Richard Schmalensee"]','["Evans Schmalensee 2016 Matchmakers"]',"立ち上げ期ユーザー獲得率"),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()
insert_sql = """INSERT OR IGNORE INTO innovation_theory
(id, name_ja, name_en, definition, subfield, school_of_thought, era_start, era_end,
 methodology_level, target_domain, application_conditions, when_to_apply, framing_questions,
 opposing_concept_names, keywords_ja, keywords_en, status, source_reliability, data_completeness,
 key_researchers, key_works, measurement_approach)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
conn.executemany(insert_sql, records)
conn.commit()
print(f"Inserted: {conn.total_changes}")
cur.execute("SELECT COUNT(*) FROM innovation_theory WHERE subfield='platform_digital_innovation'")
print(f"Total: {cur.fetchone()[0]}")
conn.close()
