import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

entries = [
("su_vc_001","VCサイクル理論","VC Cycle Theory","Venture Capital Cycle","ベンチャーキャピタル産業が景気循環・イノベーション波と連動して資金調達・投資・回収のサイクルを繰り返すという理論","Gompers & Lerner(1998)がVCの資金調達・投資行動の周期性を実証し、過熱期の割高投資と冷却期の機会損失を説明","venture_capital_financing","institutional_finance",1998,None,"growth","high","市場効率仮説","ベンチャーキャピタル,資金循環,投資波,資本市場","venture capital cycle,fund raising,investment waves","Paul Gompers, Josh Lerner","The Venture Capital Cycle (Gompers & Lerner 1998)","USA","tech,biotech","active","primary",90),
("su_vc_002","VCの金融契約理論","VC Financial Contracting","Venture Capital Financial Contracting","VCが起業家との情報非対称性・エージェンシー問題を解消するため転換優先株・段階的出資・取締役会権利等の複雑な契約を設計するという理論","Kaplan & Strömberg(2003)が600件超のVC契約を分析し、財務・統治・清算優先権の設計パターンを体系化","venture_capital_financing","institutional_finance",2003,None,"seed,early","high","シンプル普通株モデル","転換優先株,エージェンシー問題,金融契約,情報非対称性","convertible preferred,financial contracting,agency problem,information asymmetry","Steven Kaplan, Per Strömberg","Financial Contracting Theory Meets the Real World (Kaplan & Strömberg 2003)","USA,Europe","all","active","primary",92),
("su_vc_003","Sahlman VCファンド構造論","Sahlman VC Structure","VC Fund Structure","LP-GP二層構造、10年ファンド期間、キャリーインタレスト報酬設計などVC産業の基本制度設計を分析した先駆的研究","Sahlman(1990)がHBRおよびJFEでVC産業の制度設計を包括的に記述し、以降の研究の基礎となった","venture_capital_financing","institutional_finance",1990,None,"all","high","銀行融資モデル","LP-GP構造,キャリー,ファンド期間,VCパートナーシップ","LP-GP structure,carried interest,fund life,VC partnership","William Sahlman","The Structure and Governance of Venture-Capital Organizations (Sahlman 1990)","USA","all","active","primary",90),
("su_vc_004","段階的融資理論","Staged Financing Theory","Staged Capital Infusion","VCが起業家の進捗に応じて複数ラウンドに分けて投資することでモラルハザードを抑制し情報を逐次更新する仕組み","Gompers(1995)が段階投資の規律効果を実証し、各ラウンドにおける企業価値評価と継続投資判断のダイナミクスを解明","venture_capital_financing","institutional_finance",1995,None,"seed,early,growth","high","一括融資","段階投資,マイルストーン,モラルハザード抑制,VC規律","staged financing,milestone,moral hazard,VC discipline","Paul Gompers","Optimal Investment, Monitoring, and the Staging of Venture Capital (Gompers 1995)","USA","all","active","primary",88),
("su_vc_005","シンジケーション理論","Syndication Theory","VC Syndication","複数のVCが同一ディールに共同投資することでリスク分散・情報共有・ネットワーク拡大を実現する戦略","Lerner(1994)がシンジケーションの選択的パターンを分析し、質の低いVCが良質VCに追随するフリーライダー問題を指摘","venture_capital_financing","network_theory",1994,None,"early,growth","high","単独投資","シンジケーション,共同投資,VCネットワーク,リスク分散","syndication,co-investment,VC network,risk sharing","Josh Lerner","The Syndication of Venture Capital Investments (Lerner 1994)","USA","all","active","primary",86),
("su_vc_006","デューデリジェンス理論","Due Diligence Framework","Venture Capital Due Diligence","VCが投資前に実施する財務・法務・技術・市場・チームの包括的調査プロセスの体系","Harvey & Lush(2002)らがデューデリジェンスの多次元評価フレームワークを整理し、失敗案件との関係を実証","venture_capital_financing","institutional_finance",2002,None,"seed,early","high","直感的投資判断","デューデリジェンス,事前調査,リスク評価,投資審査","due diligence,pre-investment screening,risk assessment","Harvey, Lush","VC Due Diligence Practices (Harvey & Lush 2002)","UK,USA","all","active","secondary",80),
("su_vc_007","タームシート設計論","Term Sheet Design","Term Sheet Negotiation","VCと起業家間の主要条件(バリュエーション・ガバナンス・清算優先・希薄化防止)を規定する非拘束契約書の設計理論","Feld & Mendelson(2011)がタームシートの各条項の経済的意味を解説し、交渉ダイナミクスを体系化","venture_capital_financing","institutional_finance",2011,None,"seed,early","high","契約省略","タームシート,優先清算権,希薄化防止,バリュエーション上限","term sheet,liquidation preference,anti-dilution,valuation cap","Brad Feld, Jason Mendelson","Venture Deals (Feld & Mendelson 2011)","USA","all","active","secondary",85),
("su_vc_008","転換社債理論","Convertible Note Theory","Convertible Note Financing","シードラウンドでバリュエーション確定を先送りしながら資金提供できる負債+転換権付き金融商品の理論","2000年代後半のシード投資実務から発展し、ディスカウントレート・バリュエーションキャップ設計が標準化された","venture_capital_financing","institutional_finance",2008,None,"seed","high","普通株直接発行","転換社債,ディスカウント,バリュエーションキャップ,シード資金","convertible note,discount rate,valuation cap,seed financing","Various practitioners","Y Combinator convertible note templates (2008-)","USA","all","active","secondary",82),
("su_vc_009","SAFE契約理論","SAFE Agreement Theory","Simple Agreement for Future Equity","Y Combinatorが2013年に設計した負債性なし・利息なしのシード資金調達手段で、将来ラウンドで株式に転換","Postman(2013)が標準化されたSAFEテンプレートを公開し、世界中のシードエコシステムに普及","venture_capital_financing","institutional_finance",2013,None,"seed","high","転換社債","SAFE,シンプル合意,株式転換,バリュエーションキャップ","SAFE,simple agreement for future equity,post-money SAFE","Y Combinator","Y Combinator SAFE template (2013)","USA","all","active","secondary",84),
("su_vc_010","DCFバリュエーション理論","DCF Valuation for Startups","Discounted Cash Flow Valuation","将来キャッシュフローをリスク調整割引率で現在価値に換算してスタートアップを評価する手法","Damodaran(2000s)がスタートアップ特有の負のCF期間・高サバイバルリスクを考慮したDCF適用法を体系化","venture_capital_financing","valuation_methods",2000,None,"growth,late","medium","マーケット法","DCF,将来キャッシュフロー,割引率,ターミナルバリュー","DCF,discounted cash flow,terminal value,WACC","Aswath Damodaran","The Dark Side of Valuation (Damodaran 2001)","USA","all","active","primary",85),
("su_vc_011","類似取引比較法","Comparable Transactions Method","Comparable Company Valuation","同業種・同ステージの比較企業や類似M&A取引のマルチプル(EV/Revenue等)を用いてスタートアップを評価する手法","投資銀行実務から発展し、市場実勢を反映した客観的な評価ベンチマークとして広く使用される","venture_capital_financing","valuation_methods",1990,None,"growth,late","medium","内在価値法","類似企業比較,マルチプル,EV/Revenue,市場評価","comparable companies,multiples,EV/Revenue,market valuation","Investment banking practitioners","Standard IB valuation methodology","USA,Europe","all","active","secondary",78),
("su_vc_012","VCメソッドバリュエーション","VC Method Valuation","Venture Capital Method","投資時の目標リターン倍率(MOIC)から逆算して現在のプレマネーバリュエーションを決定するVC固有の評価手法","Sahlman & Stevenson(1986)がHBSケースで体系化し、VC実務の標準的評価手法として定着","venture_capital_financing","valuation_methods",1986,None,"seed,early","high","DCF法","VCメソッド,リターン倍率,ポストマネー,MOIC","VC method,return multiple,post-money valuation,MOIC","William Sahlman, Howard Stevenson","A Method for Valuing High-Risk, Long-Term Investments (HBS 1986)","USA","all","active","primary",87),
("su_vc_013","エンジェル投資理論","Angel Investing Theory","Angel Investment","個人富裕投資家が初期スタートアップに資金・知識・ネットワークを提供する非公式初期資本市場の理論","Wetzel(1983)がエンジェル投資家の存在を初めて体系的に記述し、資本ギャップ問題の解決者として位置付け","venture_capital_financing","early_stage_finance",1983,None,"seed","high","VC投資","エンジェル投資,個人投資家,資本ギャップ,非公式市場","angel investing,informal capital,capital gap,HNW individuals","William Wetzel","Angels and Informal Risk Capital (Wetzel 1983)","USA","all","active","primary",82),
("su_vc_014","クラウドファンディング(報酬型)理論","Reward Crowdfunding Theory","Reward-Based Crowdfunding","製品・サービスのプロトタイプを見込み客に事前販売することで資金調達と市場検証を同時に行う手法","Kickstarterの登場(2009)以降、Mollickら(2014)が成功要因・詐欺リスク・社会的証明効果を実証","venture_capital_financing","alternative_finance",2009,None,"seed","medium","VC投資","クラウドファンディング,事前予約,市場検証,ネットワーク効果","reward crowdfunding,pre-sales,market validation,social proof","Ethan Mollick","The Dynamics of Crowdfunding (Mollick 2014)","USA","consumer,hardware","active","primary",83),
("su_vc_015","株式型クラウドファンディング理論","Equity Crowdfunding Theory","Equity Crowdfunding","JOBs Act(2012)後に制度化された一般投資家による株式取得型クラウドファンディングの理論","Ahlers et al.(2015)が欧州エクイティCF市場を分析し、シグナリング・情報開示・投資家保護の重要性を実証","venture_capital_financing","alternative_finance",2012,None,"seed","high","エンジェル投資","株式型CF,JOBS法,小口投資家,証券規制","equity crowdfunding,JOBS Act,retail investors,securities regulation","Ahlers, Cumming","Signaling in Equity Crowdfunding (Ahlers et al. 2015)","USA,Europe","all","active","primary",84),
("su_vc_016","コーポレートVC理論","Corporate Venture Capital Theory","Corporate Venture Capital","大企業が戦略的目的(技術・市場・人材の獲得)のために設立するVC部門の理論","Chesbrough(2002)がCVCの投資目的を財務的リターン×戦略的価値の2軸で類型化し、制度設計指針を提示","venture_capital_financing","corporate_finance",2002,None,"early,growth","high","独立VC","CVC,コーポレートVC,オープンイノベーション,戦略的投資","CVC,corporate venture capital,strategic investment,open innovation","Henry Chesbrough","Making Sense of Corporate Venture Capital (Chesbrough 2002)","USA,Japan","tech,pharma","active","primary",85),
("su_vc_017","LP-GPダイナミクス理論","LP-GP Dynamics","Limited Partner - General Partner Dynamics","年金基金・財団等のLPとVCファンドマネジャー(GP)間のエージェンシー関係、コミットメント構造、情報開示の非対称性を扱う理論","Lerner & Schoar(2004)がLP属性とパフォーマンスの関係を分析し、洗練度の差異がリターンに影響することを実証","venture_capital_financing","institutional_finance",2004,None,"all","high","直接投資","LP,GP,エージェンシー問題,ファンドガバナンス","LP,GP,agency problem,fund governance,commitment","Josh Lerner, Antoinette Schoar","The Illiquidity Puzzle (Lerner & Schoar 2004)","USA","all","active","primary",86),
("su_vc_018","キャリーと報酬設計論","Carried Interest Design","Carried Interest and Fee Structure","GPが獲得する成功報酬(通常20%)と管理報酬(通常2%)の設計が投資行動・LP利益との整合性に与える影響の理論","Metrick & Yasuda(2010)がVC報酬構造を分析し、管理報酬の固定性がリスク回避行動を招く可能性を示した","venture_capital_financing","institutional_finance",2010,None,"all","high","固定報酬制","キャリーインタレスト,管理報酬,インセンティブ設計,GP報酬","carried interest,management fee,incentive alignment,GP compensation","Andrew Metrick, Ayako Yasuda","The Economics of Private Equity Funds (Metrick & Yasuda 2010)","USA","all","active","primary",87),
("su_vc_019","ベンチャーデット理論","Venture Debt Theory","Venture Debt Financing","エクイティ希薄化を最小化しながら成長資本を調達できる有担保・ワラント付き負債型資金調達の理論","Hardymon et al.(2005)がベンチャーデットの利点・リスク・タイミングを整理し、VC投資との補完関係を論じた","venture_capital_financing","debt_finance",2005,None,"growth","medium","株式型VC","ベンチャーデット,ワラント,希薄化防止,負債調達","venture debt,warrant,dilution prevention,debt financing","Hardymon, Leamon","Venture Lending and Leasing (Hardymon et al. 2005)","USA","tech,biotech","active","secondary",78),
("su_vc_020","収益連動型融資理論","Revenue-Based Financing Theory","Revenue-Based Financing","月次収益の一定割合を返済に充てることでエクイティを発行せずに成長資金を調達する代替金融手法","Lighter Capital等が2010年代に普及させ、Capchase・Clearco等のプラットフォームが理論と実務を発展させた","venture_capital_financing","alternative_finance",2010,None,"growth","medium","エクイティVC","収益連動融資,RBF,希薄化ゼロ,SaaS資金調達","revenue-based financing,RBF,non-dilutive,recurring revenue","Lighter Capital founders","Revenue-Based Financing model (2010s)","USA","SaaS,D2C","active","secondary",76),
("su_vc_021","ICOトークン資金調達理論","ICO Token Fundraising Theory","Initial Coin Offering","ブロックチェーントークンを用いてプロジェクトへの参加権・効用権を販売し資金調達する手法の理論","Catalini & Gans(2018)がICOの情報経済学的分析を行い、トークン設計・証券規制回避・詐欺リスクを論じた","venture_capital_financing","alternative_finance",2017,2020,"seed","high","従来VC","ICO,トークン,ブロックチェーン,暗号資産資金調達","ICO,token,blockchain fundraising,crypto","Christian Catalini, Joshua Gans","Initial Coin Offerings and the Value of Crypto Tokens (Catalini & Gans 2018)","Global","crypto,fintech","active","primary",84),
("su_vc_022","ファンドオブファンズ理論","Fund of Funds Theory","Fund of Funds","複数のVCファンドに分散投資するメタファンドの構造・パフォーマンス・流動性特性の理論","Lerner et al.(2007)がFoFのリターン分布と直接投資との比較を分析し、二重コスト問題と分散効果を論じた","venture_capital_financing","institutional_finance",2007,None,"all","medium","直接投資","ファンドオブファンズ,分散投資,二重コスト,機関投資","fund of funds,diversification,double layer fees,institutional VC","Josh Lerner","Smart Money? The Effect of Education on Financial Outcomes (Lerner et al. 2007)","USA,Europe","all","active","primary",80),
("su_vc_023","新興GPプログラム理論","Emerging Manager Programs","Emerging VC Manager Programs","実績の少ない新興VCマネジャーを支援する機関投資家のプログラム設計と、多様性・地域分散効果の理論","ILPA等が2010年代に新興GPプログラムを体系化し、ダイバーシティ投資とアルファ探索の両立を論じた","venture_capital_financing","institutional_finance",2015,None,"all","medium","確立GP優先","新興GP,多様性投資,機関投資家,エマージングマネジャー","emerging manager,diverse GP,institutional LP,new fund","ILPA, Diverse Asset Managers Initiative","ILPA Emerging Manager Guidelines (2015-)","USA","all","active","secondary",74),
("su_vc_024","セカンダリーマーケット理論","Secondary Market Theory","VC Secondary Market","VCファンド持分・未公開株を流通させるセカンダリー市場の価格形成・流動性供給・LP出口機能の理論","Jeffries et al.(2012)がセカンダリー市場の急成長を分析し、流動性ディスカウントの縮小トレンドを記述","venture_capital_financing","market_structure",2012,None,"all","medium","IPO/M&A","セカンダリー市場,LP持分,流動性,未公開株流通","secondary market,LP interests,liquidity,private equity secondary","Setter Capital","Secondary Market Report (Setter Capital 2012)","USA,Europe","all","active","secondary",76),
("su_vc_025","SPV構造理論","SPV Structure Theory","Special Purpose Vehicle","特定ディールへの集中投資を可能にするSPV(特別目的会社)の設計・税務・投資家向け透明性の理論","AngelList(2013)がSPVをプラットフォーム化したことで小口投資家のディールアクセスが民主化された","venture_capital_financing","institutional_finance",2013,None,"seed,early","high","ファンド投資","SPV,特別目的会社,シンジケート,AngelList","SPV,special purpose vehicle,syndicate,rolling fund","Naval Ravikant, AngelList","AngelList Syndicates (2013)","USA","all","active","secondary",80),
("su_vc_026","VC投資判断プロセス論","VC Investment Decision Process","VC Decision Making Process","VCがソーシング・スクリーニング・デューデリジェンス・投資委員会承認・クロージングを経て意思決定する組織プロセスの理論","Zacharakis & Meyer(1998)がVCの判断バイアスをプロトコル分析で検証し、ヒューリスティックの影響を実証","venture_capital_financing","behavioral_finance",1998,None,"seed,early","high","定量モデル","投資判断,VC意思決定,認知バイアス,投資委員会","VC decision making,cognitive bias,investment committee,heuristics","Zacharakis, Meyer","A Lack of Insight: Do Venture Capitalists Really Understand Their Own Decision Process? (1998)","USA","all","active","primary",82),
("su_vc_027","VC付加価値サービス論","VC Value-Added Services","VC Value-Added","VCが資金提供に加えて経営助言・採用支援・顧客紹介・M&Aアドバイスなどの非金融支援を提供する価値の理論","Gorman & Sahlman(1989)がVCのハンズオン関与度とポートフォリオパフォーマンスの関係を実証","venture_capital_financing","institutional_finance",1989,None,"early,growth","high","パッシブ投資","VC付加価値,ハンズオン,経営支援,採用支援","VC value-add,hands-on,board involvement,portfolio support","Gorman, Sahlman","What Do Venture Capitalists Do? (Gorman & Sahlman 1989)","USA","all","active","primary",83),
("su_vc_028","VC選択シグナリング理論","VC Selection Signaling","VC Signaling Theory","高評価VCからの投資が外部投資家に対して起業家の質を証明するシグナルとして機能するという理論","Megginson & Weiss(1991)がVC支援IPOの方がアンダープライシングが低いことを実証し、VC評判の情報シグナル価値を論証","venture_capital_financing","information_economics",1991,None,"seed,early","high","市場均衡仮説","シグナリング,VC評判,IPOアンダープライシング,情報非対称","signaling,VC reputation,IPO underpricing,certification","Megginson, Weiss","Venture Capitalist Certification in Initial Public Offerings (Megginson & Weiss 1991)","USA","all","active","primary",86),
("su_vc_029","VC地理的集中理論","VC Geographic Concentration","VC Geographic Clustering","VCが物理的近接性・現地情報優位・ネットワーク密度を理由として特定地域(シリコンバレー等)に集積する現象の理論","Sorenson & Stuart(2001)がVC投資の地理的パターンを分析し、距離減衰効果とネットワーク仲介効果を実証","venture_capital_financing","economic_geography",2001,None,"all","medium","分散投資","VC集積,地理的制約,ネットワーク仲介,物理的近接","VC clustering,geographic concentration,distance,network intermediation","Sorenson, Stuart","Syndication Networks and the Spatial Distribution of Venture Capital Investments (2001)","USA","all","active","primary",85),
("su_vc_030","VC評価基準理論","VC Evaluation Criteria","VC Investment Criteria","VCが起業家チーム・市場規模・技術・ビジネスモデル・競合優位性を多次元で評価する基準の体系","MacMillan et al.(1985)が投資基準サーベイを実施し、チームの質が最重要評価軸であることを実証","venture_capital_financing","decision_theory",1985,None,"seed,early","high","財務指標重視","投資評価基準,チーム重視,市場規模,競合優位","investment criteria,team quality,market size,competitive advantage","MacMillan, Siegel, SubbaNarasimha","Criteria Used by Venture Capitalists to Evaluate New Venture Proposals (MacMillan et al. 1985)","USA","all","active","primary",84),
("su_vc_031","マイクロVC理論","Micro VC Theory","Micro VC","運用資産1億ドル未満のシード特化小型VCファンドの投資戦略・リターン特性・エコシステム役割の理論","500 Startups・First Round Capital等が2010年代に台頭し、Pre-Seed/Seedの専門化を推進","venture_capital_financing","institutional_finance",2010,None,"seed","high","大型VC","マイクロVC,シード特化,小型ファンド,個人起業家","micro VC,seed fund,pre-seed,small fund","Dave McClure","500 Startups thesis (2010)","USA","all","active","secondary",78),
("su_vc_032","メガファンド理論","Mega Fund Theory","VC Mega Fund","10億ドル以上の大型VCファンドが後期ステージ・海外展開・クロスオーバー投資を行う戦略の理論","SoftBank Vision Fund(2017)やTiger Global等が非上場市場での巨大投資を実行し、従来VCモデルへの挑戦を体現","venture_capital_financing","institutional_finance",2017,None,"late,growth","high","早期段階VC","メガファンド,後期投資,SoftBank,クロスオーバー","mega fund,late-stage VC,crossover,SoftBank Vision Fund","Masayoshi Son","SoftBank Vision Fund thesis (2017)","Global","tech","active","secondary",80),
("su_vc_033","VC女性起業家バイアス理論","VC Gender Bias Theory","Gender Bias in VC","VC投資判断における女性起業家への構造的バイアスとその原因・対策を扱う理論","Gompers & Wang(2017)がVC業界の女性比率の低さとパフォーマンスへの影響を分析し、多様性の投資リターン向上効果を示唆","venture_capital_financing","behavioral_finance",2017,None,"seed,early","medium","メリトクラシー仮説","ジェンダーバイアス,女性起業家,VC多様性,投資格差","gender bias,female founders,VC diversity,investment gap","Paul Gompers, Sophie Wang","Diversity in Innovation (Gompers & Wang 2017)","USA","all","active","primary",82),
("su_vc_034","VC出口戦略理論","VC Exit Strategy Theory","VC Exit Strategy","IPO・M&A・セカンダリー売却を通じたVC投資回収のタイミング・手法・バリュエーションの最適化理論","Gompers(1996)がグランドスタンディング仮説を提唱し、若手VCが評判構築のため早期IPOを急ぐ傾向を実証","venture_capital_financing","institutional_finance",1996,None,"late","high","長期保有","出口戦略,IPO,M&A,グランドスタンディング","exit strategy,IPO,M&A,grandstanding hypothesis","Paul Gompers","Grandstanding in the Venture Capital Industry (Gompers 1996)","USA","all","active","primary",85),
("su_vc_035","VC業績持続性理論","VC Performance Persistence","VC Performance Persistence","優れたVCファンドのリターンが後続ファンドでも持続する傾向(スキル vs 運)を検証する理論","Kaplan & Schoar(2005)がPEファンドの成績持続性を実証し、VCでも初期ファンドの成功が次ファンドに持続することを示した","venture_capital_financing","institutional_finance",2005,None,"all","high","ランダムウォーク仮説","成績持続性,VC実力,ファンドパフォーマンス,スキル","performance persistence,VC skill,fund returns,track record","Kaplan, Schoar","Private Equity Performance: Returns, Persistence, and Capital Flows (Kaplan & Schoar 2005)","USA","all","active","primary",87),
("su_vc_036","VCネットワーク資本論","VC Network Capital","VC Network Capital Theory","VCのネットワーク中心性・紹介能力・業界コネクションがポートフォリオへの価値付加と資金調達成功に与える影響の理論","Hochberg et al.(2007)がVCネットワーク構造とファンドパフォーマンスの正の相関を実証","venture_capital_financing","network_theory",2007,None,"all","high","財務資本優先","ネットワーク資本,VC紹介,業界コネクション,ソーシャルキャピタル","network capital,VC connections,social capital,referral network","Hochberg, Ljungqvist, Lu","Whom You Know Matters: Venture Capital Networks and Investment Performance (Hochberg et al. 2007)","USA","all","active","primary",86),
("su_vc_037","クリーンテックVC理論","Cleantech VC Theory","Cleantech Venture Capital","再生可能エネルギー・環境技術への特化VC投資の特性・長期資本要求・政策依存性の理論","Hargadon & Kenney(2012)がクリーンテックVCの資本構造とリターンの問題を論じ、政策支援の必要性を強調","venture_capital_financing","sector_finance",2012,None,"early,growth","medium","ICT VC","クリーンテック,環境投資,グリーンVC,長期資本","cleantech VC,green investment,renewable energy,long-horizon capital","Hargadon, Kenney","Misguided Policy? Following Venture Capital into Clean Technology (Hargadon & Kenney 2012)","USA","cleantech,energy","active","primary",80),
("su_vc_038","バイオテックVC理論","Biotech VC Theory","Biotech Venture Capital","創薬・医療機器への特化VC投資の長期開発期間・規制リスク・臨床試験コストの特性の理論","Pisano(2006)がバイオテックVC投資の高失敗率と学習障壁を分析し、科学・ビジネスモデルの乖離を論じた","venture_capital_financing","sector_finance",2006,None,"seed,early,growth","medium","ICT VC","バイオテック,創薬投資,規制リスク,臨床試験","biotech VC,drug development,regulatory risk,clinical trials","Gary Pisano","Science Business (Pisano 2006)","USA","biotech,pharma","active","primary",82),
("su_vc_039","インパクト投資理論","Impact Investing Theory","Impact Investing","財務リターンと社会・環境インパクトの両立を目指す投資戦略の理論","Bugg-Levine & Emerson(2011)がインパクト投資の概念を体系化し、GIIN・IMP等の評価フレームワークが発展","venture_capital_financing","alternative_finance",2011,None,"all","medium","純粋リターン投資","インパクト投資,ESG,社会的リターン,GIIN","impact investing,ESG,social return,blended value","Bugg-Levine, Emerson","Impact Investing (Bugg-Levine & Emerson 2011)","Global","social enterprise,fintech","active","primary",82),
("su_vc_040","VC契約条件最適化理論","VC Contract Optimization","Optimal VC Contracting","情報非対称・多段階投資・努力モラルハザードを同時に扱うVCと起業家間の最適契約設計の理論","Bergemann & Hege(1998)が動的学習モデルでVCの段階投資と起業家努力の最適化条件を導出","venture_capital_financing","contract_theory",1998,None,"seed,early","high","固定契約","最適契約,動的契約,段階投資最適化,起業家努力","optimal contracting,dynamic contracting,staged investment,entrepreneur effort","Bergemann, Hege","Venture Capital Financing, Moral Hazard, and Learning (Bergemann & Hege 1998)","Europe","all","active","primary",83),
("su_vc_041","VC市場サイクル理論","VC Market Cycle","Venture Capital Market Cycle","経済環境・金利・株式市場・技術革新が絡み合いVCへの資金流入と投資活動に波をもたらすマクロサイクルの理論","Gompers et al.(2008)がVC投資の景気循環感応度を定量化し、株式市場との連動メカニズムを解明","venture_capital_financing","macroeconomics",2008,None,"all","medium","非循環性","VCサイクル,景気連動,資金フロー,投資波","VC market cycle,economic cycle,capital flows,investment waves","Gompers, Kovner, Lerner","Venture Capital Investment Cycles (Gompers et al. 2008)","USA","all","active","primary",83),
("su_vc_042","VC地政学リスク理論","VC Geopolitical Risk","Geopolitical Risk in VC","政策規制・国際緊張・輸出規制・国家安全保障がクロスボーダーVC投資に与える影響の理論","CFIUS強化(2018)やChina-US tech decoupling以降、地政学リスクの投資意思決定への組み込みが論点化","venture_capital_financing","political_economy",2018,None,"all","medium","自由市場仮説","地政学リスク,CFIUS,クロスボーダー投資,技術規制","geopolitical risk,CFIUS,cross-border VC,tech regulation","Various policy researchers","CFIUS Reform Act (2018) analysis","USA,China","deep tech,defense","active","secondary",78),
("su_vc_043","VC ESG統合理論","VC ESG Integration","ESG Integration in VC","環境・社会・ガバナンス基準をVC投資判断・ポートフォリオ管理・EXIT戦略に組み込む理論","UNPRI(2006)のPE向けガイドラインを起点にILPA ESGガイドライン(2021)が実務基準として普及","venture_capital_financing","alternative_finance",2021,None,"all","medium","純財務投資","ESG投資,環境基準,ガバナンス評価,UNPRI","ESG integration,responsible investing,UNPRI,ILPA ESG","ILPA, UNPRI","ILPA ESG Data Convergence Project (2021)","Global","all","active","secondary",79),
("su_vc_044","ダウンラウンド理論","Down Round Theory","Down Round Financing","前回ラウンドより低いバリュエーションでの追加調達が既存株主・創業者・従業員に与える希薄化と心理的影響の理論","2000年代ITバブル崩壊・2022年金利上昇局面でダウンラウンドの実態と法的保護メカニズムが再検討された","venture_capital_financing","institutional_finance",2001,None,"growth,late","high","常時バリュエーション上昇","ダウンラウンド,バリュエーション下落,希薄化,アンチダイリューション","down round,valuation decline,dilution,anti-dilution ratchet","Various practitioners","Post-dot-com crash analysis (2001-)","USA","all","active","secondary",80),
("su_vc_045","VC評判資本理論","VC Reputation Capital","VC Reputation Capital","VCの評判(実績・人脈・ブランド)がポートフォリオ企業の採用・提携・次回調達に与えるシグナル価値の理論","Hsu(2004)が有名VCの投資オファーが低バリュエーションでも受け入れられる事実を示し、評判の非金融価値を定量化","venture_capital_financing","information_economics",2004,None,"seed,early","high","財務条件優先","VC評判,シグナル価値,スタートアップ選択,ブランドVC","VC reputation,signaling value,startup preference,brand VC","David Hsu","What Do Entrepreneurs Pay for Venture Capital Affiliation? (Hsu 2004)","USA","all","active","primary",85),
("su_vc_046","VC多様性リターン研究","VC Diversity Returns","Diversity and VC Returns","VCパートナーの多様性(ジェンダー・人種・学歴)が投資先の多様化とファンドリターン向上につながるという研究","BCG(2018)・Gompers & Wang(2017)がパートナー多様性とリターン向上の相関を実証し、多様性のビジネスケースを構築","venture_capital_financing","behavioral_finance",2017,None,"all","medium","ホモフィリー","多様性,VC パートナー,リターン向上,包摂的投資","diversity,VC partners,returns,inclusion","Gompers, Wang, BCG","Diversity in Innovation (Gompers & Wang 2017)","USA","all","active","primary",81),
("su_vc_047","転換優先株設計論","Convertible Preferred Stock Design","Convertible Preferred Stock","清算優先権・参加型条項・希薄化防止条項を組み込んだ転換優先株の契約設計と起業家との利益相反の理論","Kaplan & Strömberg(2003)が転換優先株条件が起業家の行動インセンティブに与える影響を詳細分析","venture_capital_financing","contract_theory",2003,None,"seed,early","high","普通株","転換優先株,清算優先権,参加型条項,希薄化防止","convertible preferred,liquidation preference,participation,anti-dilution","Kaplan, Strömberg","Financial Contracting Theory Meets the Real World (2003)","USA","all","active","primary",87),
("su_vc_048","プロラタ権利理論","Pro-Rata Rights Theory","Pro-Rata Investment Rights","VCが次回ラウンドで保有株式比率を維持するためにプロラタ(按分)投資する権利の理論","Hornik(2010s)らが初期VCのプロラタ権利行使がポートフォリオリターン最大化に直結することを実務で確立","venture_capital_financing","institutional_finance",2010,None,"early,growth","high","希薄化許容","プロラタ権,按分投資,持分維持,VC権利","pro-rata rights,follow-on investment,ownership maintenance,VC rights","David Hornik","VC Pro-Rata Rights analysis (2010s)","USA","all","active","secondary",77),
("su_vc_049","VC情報生産理論","VC Information Production","VC Information Production","VCが投資前後に企業・技術・市場に関する高度な情報を生産・蓄積し、金融市場の情報効率化に貢献する理論","Admati & Pfleiderer(1994)がVCの内部者情報優位を分析し、証券市場における情報非対称の緩和機能を論じた","venture_capital_financing","information_economics",1994,None,"all","high","情報効率市場","情報生産,VC モニタリング,内部情報,市場効率","information production,VC monitoring,insider information,market efficiency","Admati, Pfleiderer","Robust Financial Contracting and the Role of Venture Capitalists (Admati & Pfleiderer 1994)","USA","all","active","primary",82),
("su_vc_050","VC産業発展史","VC Industry History","History of Venture Capital","ARD設立(1946)からシリコンバレー形成・Limited Partnership法制化(1958)・ERISA改正(1979)を経た米国VC産業の制度的発展史","Gompers & Lerner(2001)がVCの歴史的発展と制度変化の相互作用を体系的に記述","venture_capital_financing","institutional_finance",1946,None,"all","low","銀行融資歴史","VC歴史,ARD,ERISA,シリコンバレー形成","VC history,ARD,ERISA,Limited Partnership Act","Gompers, Lerner","The Money of Invention (Gompers & Lerner 2001)","USA","all","active","primary",84),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()
cur.executemany("""
INSERT OR IGNORE INTO startup_theory
(id,name_ja,name_en,name_original,definition,impact_summary,subfield,school_of_thought,
era_start,era_end,startup_stage,funding_relevance,opposing_concept_names,keywords_ja,
keywords_en,key_researchers,key_works,geographic_context,industry_focus,status,
source_reliability,data_completeness)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
""", entries)
conn.commit()
print(f"Inserted: {cur.rowcount} rows, Total: {conn.execute('SELECT COUNT(*) FROM startup_theory').fetchone()[0]}")
conn.close()
