#!/usr/bin/env python3
import sqlite3
DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

records = [
    ("inno_digi_301","クラウドゲームとゲーム産業プラットフォーム化","Cloud Gaming and Platformization of Game Industry","クラウドゲーミング（NVIDIA GeForce NOW・Xbox Cloud Gaming・PlayStation Now）はゲームをストリーミングサービス化し、高性能ハードウェアを不要にする。IDG（2022）はゲーム市場全体の2030年3000億ドルを予測し、そのうちクラウド比率が拡大する。Valve SteamのPC市場支配・Apple Arcadeのサブスクモデルがプラットフォーム収益構造を変えた。モバイルゲームの5億ドルの合成バイオマーカー市場とメタバースゲームとの統合が次段階として示される。","platform_digital_innovation","コンテンツ推薦アルゴリズム",2019,None,"meso","ゲーム産業","クラウドゲーム戦略","ゲームのサービス化（GaaS）を分析する際","クラウドゲーミングはゲーム市場の参入障壁をどう下げるか","コンソールハードウェア","クラウドゲーム,GaaS,Xbox Cloud,ストリーミング","cloud gaming,GaaS,Xbox Cloud,streaming","active","secondary",74,'["Phil Spencer", "Jensen Huang"]','["IDG 2022", "Microsoft Gaming Strategy 2022"]',"クラウドゲーム加入者数・市場シェア"),
    ("inno_digi_302","デジタルツインと予知保全","Digital Twin and Predictive Maintenance","工業用デジタルツインはリアルタイムセンサーデータと物理モデルを組み合わせて設備状態を監視し、故障発生前のメンテナンスを可能にする。GEの風力タービンデジタルツイン・Siemensの工場デジタルツインが先行事例。Grieves & Vickers（2017）がデジタルツインの概念的枠組みを再整理した。McKinsey（2022）は予知保全のROIを予防保全比10-20%コスト削減と示した。","platform_digital_innovation","IoT・エッジコンピューティング",2017,None,"meso","製造・エネルギー","予知保全設計","設備故障コストを最小化する際","デジタルツイン予知保全はどのようなROIをもたらすか","定期保全","デジタルツイン,予知保全,GE,センサー","digital twin,predictive maintenance,GE,sensor","active","secondary",78,'["Michael Grieves", "John Vickers"]','["Grieves Vickers 2017", "McKinsey PM Report 2022"]',"保全コスト削減率・設備停止時間"),
    ("inno_digi_303","AIによる法律サービスの変革","AI Transformation of Legal Services","LegalTechはNLP・機械学習を契約書レビュー・法律調査・訴訟予測・コンプライアンス管理に適用する。Katz et al.（2017）は機械学習で米国最高裁判決を70%超の精度で予測した。Harvey AI・Lexis+AI・Thomson Reuters AI が大手法律事務所に導入され、文書レビュー業務の自動化が進む。法律専門家の役割変容と法曹倫理規則（弁護士AI使用ルール）の整備が課題となっている。","platform_digital_innovation","AI・機械学習",2017,None,"meso","法律サービス","LegalTechシステム設計","法律業務効率化を検討する際","AIは法律サービスのどの業務を変革するか","人手法律業務","LegalTech,契約書AI,法律AI,Harvey","LegalTech,contract AI,legal AI,Harvey","active","secondary",76,'["Daniel Katz", "Richard Susskind"]','["Katz et al. 2017 PLOS One", "Susskind 2023 Tomorrow's Lawyers"]',"法律業務自動化率・コスト削減"),
    ("inno_digi_304","フードテックと食料システムデジタル化","FoodTech and Food System Digitalization","フードテックは代替タンパク質（植物性肉・培養肉）・精密発酵・フードロスAI・スマート農場・フードデリバリーを包括するイノベーション領域。Good Food Institute（2022）は代替タンパク質投資が2021年に32億ドルを記録したと報告。Impossible Foods・Beyond Meat・Eat Justがプラントベース・細胞培養肉の商業展開を牽引。フードデリバリープラットフォーム（Uber Eats・Deliveroo・Grab Food）がQSR（クイックサービス飲食）の流通を変革している。","platform_digital_innovation","デジタルトランスフォーメーション",2015,None,"meso","食品・農業","フードテック戦略","食料システムのデジタル化・持続可能化","フードテックはどのような食料システム課題を解決するか","伝統的農業・食品","フードテック,代替タンパク質,精密発酵,フードデリバリー","FoodTech,alternative protein,precision fermentation,food delivery","active","secondary",76,'["Pat Brown", "Uma Valeti"]','["GFI 2022 State of Alternative Protein", "McKinsey FoodTech 2021"]',"市場規模・フードロス削減"),
    ("inno_digi_305","ナノテクノロジーとデジタル製造の収束","Nanotechnology and Digital Manufacturing Convergence","ナノテクノロジーはナノスケール材料・デバイスの設計・製造を可能にし、半導体微細化・薬物送達・エネルギー材料に応用される。Drexler（1986）の「創造エンジン」が分子製造の概念を提唱した。TSMC 3nmプロセスがAIチップ性能向上の物理的基盤。カーボンナノチューブ・グラフェン・量子ドットの産業応用が材料イノベーションを牽引する。NSF NNI（国家ナノテク推進）予算が米国の戦略投資を示す。","platform_digital_innovation","SpaceTech・DeepTech",2000,None,"macro","半導体・材料","ナノ技術産業応用評価","ナノテクのイノベーション潜在力を評価する際","ナノテクは半導体・材料産業をどう変革するか","マクロスケール製造","ナノテクノロジー,半導体,カーボンナノチューブ,グラフェン","nanotechnology,semiconductor,carbon nanotube,graphene","active","secondary",74,'["Eric Drexler", "Richard Feynman"]','["Drexler 1986", "NNI Strategic Plan 2021"]',"ナノ材料市場規模・チップ性能"),
    ("inno_digi_306","デジタルコンテンツモデレーションと言論規制","Digital Content Moderation and Speech Regulation","プラットフォームのコンテンツモデレーションは違法コンテンツ・ヘイトスピーチ・誤情報の審査・削除を担い、表現の自由と安全のバランスを追求する。Roberts（2019）はモデレーター労働（幽霊労働）の実態を調査した。EU DSA（2022）はVLOP（超大規模オンラインプラットフォーム）にリスク評価・透明性報告義務を課す。AIモデレーションツールと人間審査員の組み合わせが現実的アプローチとして普及している。","platform_digital_innovation","プラットフォーム規制",2019,None,"macro","ソーシャルメディア","コンテンツモデレーション設計","プラットフォームの言論管理を設計する際","コンテンツモデレーションは表現の自由とどう両立するか","無審査型言論空間","コンテンツモデレーション,DSA,ヘイトスピーチ,表現の自由","content moderation,DSA,hate speech,freedom of speech","active","secondary",78,'["Sarah Roberts", "Kate Klonick"]','["Roberts 2019 Behind the Screen", "EU DSA 2022"]',"違法コンテンツ削除率・上訴率"),
    ("inno_digi_307","ドローン配送とラストマイルイノベーション","Drone Delivery and Last-Mile Innovation","ラストマイル物流はeコマース急増で最コスト集約的段階となり、ドローン・自律ロボット・電動バイクが代替技術として展開される。Wing（Google X）・Amazon Prime Air・UPS Flightが商用ドローン配送の先行事例を提供した。FAA BVLOS（目視外飛行）規制・日本改正航空法（2022年レベル4）が商用化の法的条件を整備。McKinsey（2022）はラストマイルのドローン化が配送コストを最大80%削減すると推計した。","platform_digital_innovation","デジタルトランスフォーメーション",2016,None,"meso","物流・EC","ドローン物流戦略","最終配送コストを削減する際","ドローン配送はどのような物流条件で経済的に優位か","人手配送","ドローン配送,ラストマイル,Wing,Amazon Prime Air","drone delivery,last-mile,Wing,Amazon Prime Air","active","secondary",76,'["McKinsey Logistics", "FAA Research"]','["McKinsey Last Mile 2022", "FAA BVLOS Rule 2022"]',"配送コスト・配達時間"),
    ("inno_digi_308","エッジAIと分散型機械学習","Edge AI and Distributed Machine Learning","エッジAIはクラウド送信なしにデバイス上でAIモデルを実行し、遅延削減・プライバシー保護・帯域節約を実現する。連合学習（McMahan et al. 2017）はデータをローカルに保ちながらモデル更新を共有する分散学習パラダイム。スマートフォンのOn-Device AI（Apple Neural Engine・Qualcomm AI Engine）・産業IoTエッジ推論が主要適用。Lin et al.（2022）はエッジAIの効率的モデル圧縮手法（TinyML）を体系化した。","platform_digital_innovation","IoT・エッジコンピューティング",2020,None,"meso","IoT・モバイル","エッジAIシステム設計","リアルタイムAI推論を低遅延で実現する際","エッジAIはクラウドAIのどの制約を克服するか","クラウド集中AI","エッジAI,連合学習,TinyML,On-Device","Edge AI,federated learning,TinyML,on-device","active","primary",80,'["Brendan McMahan", "Song Han"]','["McMahan et al. 2017", "Lin et al. 2022 TinyML"]',"推論遅延・バッテリー効率"),
    ("inno_digi_309","スマートコントラクトとDAOガバナンス","Smart Contract and DAO Governance","スマートコントラクトはブロックチェーン上で自動執行される契約で、DAOは投票・提案・報酬分配を自動化する分散型組織体。Buterin（2014）がEthereumを提案しスマートコントラクトを実装可能にした。MakerDAO・Compound・Uniswapが代表的DAOとして運営される。Faqir-Rhazoui et al.（2021）がDAO参加・意思決定の実態を分析し、参加者の集中・投票率の低さを指摘した。","platform_digital_innovation","Web3・分散型経済",2014,None,"meso","金融・組織","DAO設計","分散型組織・自律的契約執行を実現する際","スマートコントラクトはどのような組織コストを削減するか","中央集権型組織","スマートコントラクト,DAO,Ethereum,DeFi","smart contract,DAO,Ethereum,DeFi","active","secondary",76,'["Vitalik Buterin", "Primavera De Filippi"]','["Buterin 2014 Ethereum White Paper", "Faqir-Rhazoui 2021"]',"DAO参加者数・TVL"),
    ("inno_digi_310","AI倫理の国際標準化と多様性","International Standardization and Diversity in AI Ethics","AI倫理の国際標準はUNESCO AI倫理勧告（2021）・OECD AI原則（2019）・G20 AI原則・ISO/IEC JTC 1/SC 42が競合・補完関係にある。Hagendorff（2020）はAI倫理ガイドラインの実施率の低さを実証し「倫理洗浄（ethics washing）」を批判した。文化的価値観（集団主義vs.個人主義・プライバシー規範）がAI倫理の実装に与える差異をCross-Cultural AI研究が分析する。","platform_digital_innovation","AI規制・ガバナンス",2021,None,"macro","AI開発全般","AI倫理政策設計","AI倫理フレームワークを国際的に評価する際","AI倫理の国際標準はどのような多様性を持つか","単一規制モデル","AI倫理,UNESCO,OECD,国際標準,倫理洗浄","AI ethics,UNESCO,OECD,international standards,ethics washing","active","secondary",78,'["Thilo Hagendorff", "UNESCO Ethics Division"]','["UNESCO AI Ethics 2021", "Hagendorff 2020 Minds & Machines"]',"採用率・実施率"),
    ("inno_digi_311","デジタルマーケティングとプログラマティック広告","Digital Marketing and Programmatic Advertising","プログラマティック広告はRTB（リアルタイム入札）により広告配信をミリ秒単位で自動最適化し、ターゲティング精度を向上させる。Goldfarb & Tucker（2011）はオンライン広告のターゲティングと邪魔さのトレードオフを実証した。サードパーティCookieの廃止（2024-2025年移行）がデジタル広告のプライバシー保護と効果測定に構造的変化をもたらしつつある。","platform_digital_innovation","デジタル広告経済",2011,None,"meso","広告・マーケティング","プログラマティック広告戦略","デジタル広告の効果最大化","デジタル広告はどのようにターゲティング精度を向上させるか","マスメディア広告","プログラマティック広告,RTB,ターゲティング,Cookie廃止","programmatic advertising,RTB,targeting,cookie deprecation","active","secondary",78,'["Avner Goldfarb", "Catherine Tucker"]','["Goldfarb Tucker 2011 Marketing Science", "IAB Programmatic Report 2022"]',"広告ROI・CTR・CPM"),
    ("inno_digi_312","シェアリングエコノミーの経済学と社会影響","Economics and Social Impact of Sharing Economy","シェアリングエコノミー（Airbnb・Uber・Zipcar）はアイドル資産（空き部屋・車・工具）の効率的利用を実現する。Zervas et al.（2017）はAirbnbがホテル収益を年8-10%低下させることを実証した。プラットフォームが取引信頼を評価システム（評価・レビュー）で担保するメカニズムをHall & Wooders（2010）が分析した。住宅コスト上昇・労働保護・脱税が規制論議の主要焦点となっている。","platform_digital_innovation","プラットフォーム経済学",2017,None,"meso","消費者経済","シェアリング経済の社会影響分析","シェアリングビジネスモデルの影響を評価する際","シェアリングエコノミーはどのような市場を変革するか","所有型経済","シェアリングエコノミー,Airbnb,Uber,ピアツーピア","sharing economy,Airbnb,Uber,peer-to-peer","active","primary",82,'["Georgios Zervas", "Arun Sundararajan"]','["Zervas et al. 2017 JMR", "Sundararajan 2016"]',"経済効果・雇用変化・住宅コスト"),
    ("inno_digi_313","生体認証技術と身元確認","Biometric Technology and Identity Verification","顔認証・指紋・虹彩・声紋認証は行政・金融・セキュリティでの身元確認精度を向上させ、パスワードを代替しつつある。NIST FRVT（顔認識技術評価）がアルゴリズム精度を公開ベンチマークで測定する。Clearview AI事件はプライバシーを侵害する大規模顔認識使用の論争を引き起こした。EU AI Act（2024）は公共空間リアルタイム顔認識を原則禁止とし、例外適用の厳格化を求める。","platform_digital_innovation","サイバーセキュリティ",2020,None,"meso","公共・金融・セキュリティ","生体認証システム設計","セキュアな認証システムを導入する際","生体認証はどのようなセキュリティ・プライバシートレードオフを持つか","パスワード認証","生体認証,顔認識,NIST,プライバシー,Clearview","biometrics,facial recognition,NIST,privacy,Clearview","active","secondary",78,'["NIST Research", "Timnit Gebru"]','["NIST FRVT 2022", "EU AI Act 2024 Biometrics"]',"認証精度・誤検知率・プライバシー苦情"),
    ("inno_digi_314","インフルエンサーマーケティングのROI測定","ROI Measurement of Influencer Marketing","インフルエンサーマーケティングはブランドがSNSフォロワーを持つ個人を通じて商品・サービスを宣伝する手法で、2022年市場規模は164億ドル（Influencer Marketing Hub）に達した。Hwang & Zhang（2018）はマイクロインフルエンサー（フォロワー1-10万）がマクロインフルエンサーより高エンゲージメント率を示すことを実証した。EMV（Earned Media Value）・LTV（顧客生涯価値）・ブランドリフト調査がROI測定指標として使用される。","platform_digital_innovation","デジタル広告経済",2018,None,"micro","消費財・ファッション","インフルエンサー戦略","SNSマーケティングROIを最大化する際","インフルエンサーマーケティングはどのような消費者行動を変えるか","従来型セレブリティ広告","インフルエンサー,マイクロインフルエンサー,ROI,エンゲージメント","influencer,micro-influencer,ROI,engagement","active","secondary",74,'["Yadong Hwang", "Commey Zhang"]','["IMH Influencer Marketing Report 2022"]',"エンゲージメント率・EMV"),
    ("inno_digi_315","AIの解釈可能性・説明可能性（XAI）","AI Interpretability and Explainability (XAI)","ブラックボックスAIモデルの判断根拠を説明する技術がXAI（Explainable AI）として体系化されている。LIME（Ribeiro et al. 2016）・SHAP（Lundberg & Lee 2017）がモデル非依存の局所説明手法を提供した。EU GDPR第22条の「説明を受ける権利」・EU AI ActのHigh-Risk AI透明性要件がXAI義務化を推進する。医療・信用・刑事司法でのAI説明責任が法的・倫理的要件として確立しつつある。","platform_digital_innovation","AI・機械学習",2016,None,"micro","AI開発・高リスクドメイン","AI説明可能性設計","規制に準拠したAIシステムを設計する際","XAIはどのようなAI意思決定の信頼性を高めるか","ブラックボックスAI","XAI,LIME,SHAP,説明可能AI,透明性","XAI,LIME,SHAP,explainable AI,transparency","active","primary",82,'["Marco Ribeiro", "Scott Lundberg"]','["Ribeiro et al. 2016 KDD", "Lundberg Lee 2017 NIPS"]',"説明精度・ユーザー信頼度"),
    ("inno_digi_316","デジタル資産と知的財産権の変容","Digital Assets and Transformation of Intellectual Property","デジタルコンテンツ（音楽・映像・ソフトウェア・デザイン）の複製容易性が著作権保護の技術的・制度的課題を生む。Lessig（2001）の「コモンズの未来」はデジタル著作権の過剰保護を批判し、Creative Commonsライセンスの創設を主導した。NFTはデジタル資産の希少性・所有権をブロックチェーンで保証しようとする技術実験。TRIPS協定・ベルヌ条約のデジタル時代への適応が国際的論議となっている。","platform_digital_innovation","デジタルプラットフォーム経済",2001,None,"macro","コンテンツ・IT産業","デジタル知財戦略","デジタルコンテンツの保護・利用戦略を設計する際","デジタル時代に知的財産権はどう再設計されるべきか","物理的著作権","知的財産権,Creative Commons,NFT,著作権,デジタル","intellectual property,Creative Commons,NFT,copyright,digital","active","secondary",78,'["Lawrence Lessig", "Aaron Swartz"]','["Lessig 2001 Future of Ideas", "Creative Commons"]',"CC採用率・著作権訴訟件数"),
    ("inno_digi_317","ロボットプロセス自動化（RPA）と業務革新","Robotic Process Automation (RPA) and Business Process Innovation","RPAはソフトウェアロボットが規則ベースのデジタル業務（データ入力・帳票処理・システム間連携）を自動化する技術。UIPath・Automation Anywhere・Blue Prismが主要ベンダー。Forrester（2021）はRPA市場が2025年に220億ドルに達すると予測した。コグニティブRPA（AI+RPA）がより複雑な判断を伴う業務自動化に拡張される。銀行・保険・行政での導入が最も進み、Gartnerが「ハイパーオートメーション」へのロードマップを提示した。","platform_digital_innovation","デジタルトランスフォーメーション",2012,None,"meso","金融・行政","RPA導入設計","繰り返し業務を自動化する際","RPAはどのような業務プロセスに最も有効か","人手データ入力","RPA,ハイパーオートメーション,UIPath,業務自動化","RPA,hyperautomation,UIPath,process automation","active","secondary",78,'["Leslie Willcocks", "Mary Lacity"]','["Willcocks Lacity 2016", "Gartner Hyperautomation 2022"]',"処理時間削減・コスト削減率"),
    ("inno_digi_318","AIと音楽・芸術の共創","AI and Music/Art Co-Creation","AI音楽生成（Suno・Udio・Google MusicLM）・AI絵画（Midjourney・DALL-E・Stable Diffusion）が創造的産業の生産プロセスに入り込みつつある。Agres et al.（2016）はコンピュータ創造性の評価フレームを整理した。著作権帰属（AI生成物の著作者は誰か）・ヒューマンアーティストの経済的影響・アート市場での価値形成が法的・経済的論点。EU・米国著作権庁の行政指針が事例ごとに形成されつつある。","platform_digital_innovation","生成AI応用",2022,None,"meso","音楽・芸術産業","AI創作共創設計","AIと人間の共同創作ワークフローを設計する際","AI創作ツールは芸術創造プロセスをどう変えるか","人手創作","AI音楽,AI絵画,共創,著作権,Midjourney","AI music,AI art,co-creation,copyright,Midjourney","active","secondary",76,'["Kat Agres", "Holly Herndon"]','["Agres et al. 2016", "US Copyright Office AI Guidance 2023"]',"AI生成物市場規模・著作権判例"),
    ("inno_digi_319","インターネット普及の経済成長効果","Economic Growth Effects of Internet Diffusion","インターネット普及は情報コスト削減・市場統合・生産性向上を通じて経済成長を促進する。Czernich et al.（2011）はOECD25カ国パネルデータでブロードバンド普及率10%増加がGDP成長率0.9-1.5%向上と相関することを示した。発展途上国でのモバイルインターネット普及効果（農業価格情報・金融包摂）が実証された。デジタルインフラへの公的投資の費用便益分析が政策判断の基礎となる。","platform_digital_innovation","デジタルプラットフォーム経済",2011,None,"macro","経済政策","ICTの経済成長効果分析","デジタルインフラ投資を正当化する際","インターネット普及はGDPにどのような効果をもたらすか","インターネット普及なし","インターネット普及,GDP,ブロードバンド,デジタル配当","internet diffusion,GDP,broadband,digital dividend","active","primary",80,'["Nicole Czernich", "Tobias Kretschmer"]','["Czernich et al. 2011 EJ"]',"GDP成長率・ブロードバンド普及率"),
    ("inno_digi_320","オープンAIと大規模言語モデルのガバナンス","Open AI and Governance of Large Language Models","ChatGPT・GPT-4・Gemini・Claude・Llama等のLLMは2022年以降急速に普及し、AIガバナンスの焦点となった。Bommasani et al.（2021）のStanford CRFMが「基盤モデル（Foundation Models）」概念を提唱し、その社会的影響の包括的評価枠組みを提示した。OpenAIの「Responsible Scaling Policy」・Anthropicの「Constitutional AI」・Metaのオープンソース戦略（Llama）がガバナンスアプローチの多様性を示す。","platform_digital_innovation","AI規制・ガバナンス",2022,None,"macro","AI産業全般","LLMガバナンス設計","大規模AIモデルのリスク管理","LLMガバナンスはどのような安全性目標を追求するか","規制なしAI展開","LLM,基盤モデル,ChatGPT,Anthropic,Constitutional AI","LLM,foundation model,ChatGPT,Anthropic,Constitutional AI","active","primary",82,'["Rishi Bommasani", "Dario Amodei"]','["Bommasani et al. 2021 Stanford CRFM", "Anthropic RSP 2023"]',"モデル安全性指標・有害出力率"),
    ("inno_digi_321","NFTとデジタル所有権の実験","NFT and Digital Ownership Experiment","NFT（Non-Fungible Token）はブロックチェーン上で唯一無二性を証明するデジタルトークンで、アート・音楽・ゲームアイテム・不動産の所有権証明に応用された。2021年のNFTブーム（Beeple作品69百万ドル落札）が市場関心を最大化し、2022年以降急速に縮小した。Nadini et al.（2021）はNFT市場のバブル構造とエリートコレクター集中を実証した。Web3所有権とプラットフォーム継続性（ガス代・ネットワーク消滅リスク）が実用課題として残る。","platform_digital_innovation","Web3・分散型経済",2021,None,"meso","アート・ゲーム","NFTビジネスモデル評価","デジタル所有権とトークン化を検討する際","NFTはどのようなデジタル所有権課題に答えるか","中央集権型デジタルコンテンツ","NFT,デジタル所有権,ブロックチェーン,Beeple","NFT,digital ownership,blockchain,Beeple","active","secondary",74,'["Matthieu Nadini", "Mike Winkelmann"]','["Nadini et al. 2021 Scientific Reports", "Christie's Beeple 2021"]',"NFT取引量・市場時価総額"),
    ("inno_digi_322","プラットフォーム透明性と説明責任報告","Platform Transparency and Accountability Reporting","主要プラットフォームは透明性レポート（コンテンツ削除件数・政府情報要求・広告ライブラリ）を公開し始めている。EU DSA（2022）はVLOPに年次リスク評価・独立監査を義務付けた。Stanford Internet Observatory・NYUオンライン透明性研究所が学術的監視機能を担う。アルゴリズム監査（Algorithm Audit）が新産業として台頭し、プラットフォームの意思決定プロセスを外部検証する。","platform_digital_innovation","プラットフォーム規制",2022,None,"macro","デジタルプラットフォーム","透明性・監査体制設計","プラットフォームのアカウンタビリティを確保する際","透明性報告はプラットフォームガバナンスにどう貢献するか","非公開アルゴリズム","透明性レポート,EU DSA,アルゴリズム監査,プラットフォーム","transparency report,EU DSA,algorithm audit,platform","active","secondary",78,'["Stanford Internet Observatory", "Renee DiResta"]','["EU DSA Transparency Obligations 2022", "Stanford IO Report 2023"]',"透明性指標・コンプライアンス率"),
    ("inno_digi_323","デジタルバンクと銀行業のアンバンドリング","Digital Bank and Banking Unbundling","デジタルバンク（Monzo・N26・Revolut・WeBank）は規制ライセンスを取得しフルスタック銀行機能をアプリで提供する。Philippon（2020）は「グレートリバーサル」としてデジタル化が金融集中度を高めるリスクを指摘した。オープンバンキング（PSD2・UK Open Banking）は既存銀行のAPIを開放してフィンテックとの連携を促進する。BaaS（Banking as a Service）モデルが銀行インフラの非銀行企業への提供を可能にした。","platform_digital_innovation","デジタル金融",2016,None,"meso","金融・銀行","デジタルバンク戦略","銀行業のデジタル変革を分析する際","デジタルバンクはどのような銀行機能を変革するか","伝統的支店銀行","デジタルバンク,Monzo,N26,オープンバンキング,BaaS","digital bank,Monzo,N26,open banking,BaaS","active","secondary",78,'["Thomas Philippon", "Anne Boden"]','["Philippon 2020", "UK Open Banking Report 2022"]',"デジタルバンク顧客数・コスト比較"),
    ("inno_digi_324","コンピュテーショナルクリエイティビティとAI創造性","Computational Creativity and AI Creativity","コンピュータによる創造性（CC）は人間の創造プロセスをモデル化・実装する研究領域。Boden（2004）は創造性を「組み合わせ型・探索型・変換型」の三タイプに分類した。GAN・LLMによる芸術・音楽・詩・設計の生成がCCの実装として評価される。「AIは本当に創造的か」の哲学的論争（中国語の部屋論争の延長）と、生成AI産業の急拡大が並行して進行している。","platform_digital_innovation","AI・機械学習",2022,None,"meso","AI研究・創造産業","AI創造性評価","AIの創造的能力を評価する際","AIの創造性は人間の創造性とどのように異なるか","人間創造性","計算創造性,GAN,AI芸術,創造性評価","computational creativity,GAN,AI art,creativity evaluation","active","secondary",76,'["Margaret Boden", "Tony Veale"]','["Boden 2004 Creative Mind", "ICCC Proceedings 2023"]',"Turing Test通過率・作品評価スコア"),
    ("inno_digi_325","デジタルアイデンティティとオンライン信頼構築","Digital Identity and Online Trust Building","オンラインプラットフォームでの信頼は評価システム・検証バッジ・ブロックチェーン証明等で構築される。Resnick et al.（2000）はeBayの評価システムが取引信頼を形成するメカニズムを分析した。Airbnbのホストレビューシステム・Linkedinの資格証明が産業事例。セルフIDの偽造・ボット・フィッシングが信頼システムへの脅威として持続する。デジタルIDと評判の携帯性（Portable Reputation）が分散型Web3の課題として論じられる。","platform_digital_innovation","データ経済",2000,None,"meso","EC・SNS","オンライン信頼システム設計","デジタル取引の信頼基盤を構築する際","デジタル信頼メカニズムはどのようにオンライン取引を可能にするか","オフライン対面信頼","デジタル信頼,評価システム,eBay,Airbnb,ブロックチェーン","digital trust,rating system,eBay,Airbnb,blockchain","active","primary",80,'["Paul Resnick", "Chris Dellarocas"]','["Resnick et al. 2000 CACM", "Dellarocas 2003"]',"評価精度・詐欺率"),
    ("inno_digi_326","スマートコントラクトのセキュリティ脆弱性","Security Vulnerabilities in Smart Contracts","スマートコントラクトのコードバグは不可逆的損害をもたらす。The DAO事件（2016年、6000万ドル盗難）・Poly Network（2021年、6億ドル）・Wormhole（3.2億ドル）が主要ハック事例。Atzei et al.（2017）はSolidityスマートコントラクトの脆弱性分類（再入攻撃・整数オーバーフロー等）を体系化した。形式検証（Formal Verification）・スマートコントラクト監査産業（Certik・Trail of Bits）が対策手段として確立しつつある。","platform_digital_innovation","サイバーセキュリティ",2017,None,"meso","ブロックチェーン・金融","スマートコントラクトセキュリティ","DeFiプロトコルのリスクを管理する際","スマートコントラクトの主要脆弱性はどのように分類されるか","従来型ソフトウェアセキュリティ","スマートコントラクト,セキュリティ,The DAO,Solidity","smart contract,security,The DAO,Solidity","active","secondary",76,'["Nicola Atzei", "Massimo Bartoletti"]','["Atzei et al. 2017", "The DAO Hack Analysis 2016"]',"脆弱性検出率・損害額"),
    ("inno_digi_327","デジタルプラットフォームの競争政策：垂直統合と自己優遇","Digital Platform Competition Policy: Vertical Integration and Self-Preferencing","自己優遇（Self-Preferencing）はプラットフォームが検索結果・推薦で自社製品を有利に扱う行為で、Google Shopping事件（EU、2017年）が先駆的規制事例となった。Kades & Morton（2021）はゲートキーパープラットフォームの自己優遇を競争政策の新フロンティアとして分析した。EU DMA（2022）はゲートキーパーに自己優遇禁止・データアクセス・相互運用性義務を課す。Amazon Marketplace問題・Apple App Storeの独禁審査が同様の問題として展開されている。","platform_digital_innovation","プラットフォーム規制",2021,None,"macro","デジタルプラットフォーム","自己優遇問題の規制分析","プラットフォームの競争行為を規制する際","自己優遇はどのような競争害悪をもたらすか","中立的プラットフォーム","自己優遇,EU DMA,Google Shopping,ゲートキーパー","self-preferencing,EU DMA,Google Shopping,gatekeeper","active","secondary",80,'["Michael Kades", "Fiona Morton"]','["Kades Morton 2021", "EU DMA 2022", "EU Google Shopping 2017"]',"競争指標・規制件数"),
    ("inno_digi_328","量子センシングと新世代計測","Quantum Sensing and Next-Generation Measurement","量子センシングは原子干渉計・NV中心・超電導量子干渉素子（SQUID）を用いた極高感度計測で、重力・磁場・時間の精度を革新する。Degen et al.（2017）が量子センシングの技術的可能性と応用領域を体系的にレビューした。地下資源探索・医療診断（MEGバイオマーカー）・GPS代替（量子慣性航法）・基礎物理探索がアプリケーション領域。防衛・インフラ・医療での利用が量子技術の近中期商業化の主軸と見なされている。","platform_digital_innovation","SpaceTech・DeepTech",2017,None,"macro","医療・防衛・エネルギー","量子センシング応用評価","量子センシングの産業応用を評価する際","量子センシングは何を古典センサーより精密に測定できるか","古典センサー","量子センシング,NV中心,SQUID,慣性航法","quantum sensing,NV center,SQUID,inertial navigation","active","secondary",74,'["Christian Degen", "Jian Li"]','["Degen et al. 2017 Reviews of Modern Physics"]',"感度・精度・商業化ロードマップ"),
    ("inno_digi_329","アドテック産業と監視資本主義","AdTech Industry and Surveillance Capitalism","デジタル広告技術（AdTech）はクッキー・デバイスフィンガープリント・クロスサイトトラッキングで個人の行動データを収集し、標的広告に活用する。Zuboff（2019）の「監視資本主義の時代」はGoogleのビジネスモデルを「予測製品（人間行動の未来）」の売買として定義した。GDPR・ePrivacy指令・CCPA・AppleのATTがトラッキング制限を強化し、AdTech産業の構造変化を迫る。","platform_digital_innovation","デジタル広告経済",2019,None,"macro","デジタル広告","プライバシー保護広告設計","デジタル広告のプライバシーリスクを評価する際","監視資本主義はどのような社会的害悪をもたらすか","インターネット無料モデル","監視資本主義,AdTech,トラッキング,GDPR,Zuboff","surveillance capitalism,AdTech,tracking,GDPR,Zuboff","active","secondary",80,'["Shoshana Zuboff", "Tim Hwang"]','["Zuboff 2019 Surveillance Capitalism", "Hwang 2020 Subprime Attention Crisis"]',"広告収益・プライバシー苦情"),
    ("inno_digi_330","デジタルトランジションと組織学習","Digital Transition and Organizational Learning","デジタル変革は技術採用だけでなく組織の学習・文化・リーダーシップの変容を伴う。Senge（1990）の「学習する組織」がデジタル組織変革の理論的基盤として援用される。Westerman et al.（2014）はデジタル成熟度を技術的能力×リーダーシップ能力のマトリクスで評価した。DXに成功した組織はアジャイル・失敗許容・データドリブン文化を共通特性として持つことが事例研究で示されている。","platform_digital_innovation","デジタルトランスフォーメーション",2014,None,"meso","全産業","DX組織設計","組織のデジタル変革能力を高める際","デジタル変革に必要な組織文化はどのように形成されるか","テクノロジー中心DX","組織学習,DX文化,アジャイル,学習する組織","organizational learning,DX culture,agile,learning organization","active","secondary",78,'["George Westerman", "Peter Senge"]','["Westerman et al. 2014", "Senge 1990 Fifth Discipline"]',"DX成熟度スコア・変革達成率"),
    ("inno_digi_331","マイクロモビリティとMaaSプラットフォーム","Micromobility and MaaS Platform","マイクロモビリティ（電動キックボード・シェアサイクル・e-バイク）は都市の最初/最後の1マイル問題を解決し、MaaS（Mobility as a Service）プラットフォームは複数交通モードを一元管理する。Lime・Bird・Voi・Helixが電動キックボード市場を展開した。Kamargianni & Matyas（2017）がMaaSの概念・ビジネスモデル・政策含意を体系化した。フィンランドWhim（MaaSGlobal）が月額定額プランで多様な交通を統合する実証を先行した。","platform_digital_innovation","デジタルトランスフォーメーション",2017,None,"meso","都市交通","マイクロモビリティ・MaaS設計","都市交通のデジタル統合","マイクロモビリティはどのような都市移動問題を解決するか","自家用車","マイクロモビリティ,MaaS,電動キックボード,Lime","micromobility,MaaS,e-scooter,Lime","active","secondary",74,'["Maria Kamargianni", "Melinda Matyas"]','["Kamargianni Matyas 2017 TRR", "MaaS Global Whim Case"]',"移動コスト・CO2削減"),
    ("inno_digi_332","AIの地政学：米中技術覇権競争","Geopolitics of AI: US-China Technology Hegemony Competition","AI技術覇権をめぐる米中競争は半導体・データ・人材・標準化の多次元で展開される。Allen & Chan（2017）は中国AIの軍事的応用可能性を分析した。中国「次世代AI発展計画（2017）」・米国CHIPS Act・Executive Order on AI（2023）が対抗政策として展開する。Schmidt & Work（2021）のNSC AI報告がAIと国家安全保障の包括的フレームを提示した。テクノロジーデカップリング（技術分断）が半導体・AI・通信の国際分業に影響する。","platform_digital_innovation","AI半導体・計算資源",2017,None,"macro","地政学・安全保障","AI地政学分析","国際AI競争戦略を評価する際","米中AI競争はどのような技術・産業・安全保障リスクをもたらすか","協調的国際技術開発","AI地政学,米中競争,CHIPS Act,技術覇権","AI geopolitics,US-China competition,CHIPS Act,tech hegemony","active","secondary",80,'["Eric Schmidt", "Elsa Kania"]','["NSC AI Final Report 2021", "Allen Chan 2017 Harvard Belfer"]',"AI投資額・特許比較・輸出規制件数"),
    ("inno_digi_333","グリーンボンドとサステナブルファイナンスデジタル化","Green Bonds and Sustainable Finance Digitalization","グリーンボンドは環境プロジェクト資金調達のために設計された債券で、GBP（Green Bond Principles）がICSMA（国際資本市場協会）により管理される。ClimateFinance分野でのAIとブロックチェーン活用がESGデータ検証・レポーティング自動化・グリーンウォッシング検出に応用される。Flammer（2021）はグリーンボンド発行が企業の環境パフォーマンスを改善することを実証した。日本グリーンボンドガイドライン・EU グリーンボンド基準規制（2023）が制度化を促進する。","platform_digital_innovation","デジタル金融",2021,None,"macro","金融・ESG","グリーンファイナンス戦略","ESG投資のデジタル化を推進する際","デジタル化はグリーンボンド市場の透明性をどう高めるか","従来の社債","グリーンボンド,ESG,ブロックチェーン,グリーンウォッシング","green bond,ESG,blockchain,greenwashing","active","secondary",74,'["Caroline Flammer", "ICMA GBWP"]','["Flammer 2021 Strategic Management Journal", "EU GBS 2023"]',"グリーンボンド発行額・ESGスコア"),
    ("inno_digi_334","AmazonのEC生態系とロジスティクス革命","Amazon EC Ecosystem and Logistics Revolution","AmazonはFBA（Fulfillment by Amazon）・Prime・Alexa・Kindle・AWS・Advertising・Healthcareを統合したスーパーエコシステムを形成した。Eisenmann（2021）はAmazonの「フライホイール効果」（選択肢増→顧客増→出品者増→選択肢増のループ）を競争戦略として分析した。Amazon物流ネットワーク（航空・配送・倉庫自動化）が世界最大の民間配送インフラとなりつつある。Marketplace出品者との関係（競合・利用の二律背反）が規制審査の対象。","platform_digital_innovation","デジタルプラットフォーム経済",2005,None,"macro","EC・物流","Amazonエコシステム分析","EC物流戦略を立案する際","Amazonのフライホイール効果はどのように競争優位を形成するか","伝統的小売","Amazon,FBA,フライホイール,EC,物流","Amazon,FBA,flywheel,EC,logistics","active","secondary",80,'["Jeff Bezos", "Thomas Eisenmann"]','["Eisenmann 2021 Why Startups Fail", "Amazon Annual Report 2023"]',"市場シェア・物流コスト・顧客数"),
    ("inno_digi_335","デジタルキャパシティビルディングと途上国DX","Digital Capacity Building and Developing Country DX","途上国のデジタル変革は技術導入だけでなくデジタルスキル・制度・インフラの総合的能力構築（Capacity Building）を要する。世界銀行「Digital Economy for Africa（DE4A）」プログラムが包括的DXフレームを提供する。Ghana Digital Financial Services Policy（2020）・Kenya Big4 Digital Agenda等が国家DX計画として展開。ITU Academy・GSMA Digital Economy Foundationが途上国向けデジタルスキル訓練を支援する。","platform_digital_innovation","デジタル包摂",2020,None,"macro","途上国政策","途上国DX政策設計","途上国のデジタル能力を構築する際","デジタル能力構築はどのような開発成果をもたらすか","技術のみの移転","デジタル能力構築,途上国DX,World Bank,Africa","digital capacity building,developing country DX,World Bank,Africa","active","secondary",74,'["World Bank Digital Development", "Tim Unwin"]','["World Bank DE4A 2021", "ITU Digital Skills 2022"]',"デジタルスキル習得率・経済効果"),
    ("inno_digi_336","ポスト量子暗号と暗号移行計画","Post-Quantum Cryptography and Cryptography Migration","量子コンピュータによるShor's アルゴリズムはRSA・楕円曲線暗号を多項式時間で破る。NIST PQC標準化（2022：CRYSTALS-Kyber・CRYSTALS-Dilithium・FALCON・SPHINCS+）が移行の国際基準となった。企業・政府はCryptographic Inventory（使用中暗号の全棚卸し）→優先順位設定→PQC移行計画のフェーズで対応を進める。NSA/CSS「商用国家安全保障アルゴリズム（CNSA）2.0スイート（2022）」が米国政府機関のロードマップを示す。","platform_digital_innovation","サイバーセキュリティ",2022,None,"macro","政府・金融・通信","PQC移行計画","量子コンピュータ脅威への対策を設計する際","PQCはどのような既存暗号の脆弱性を解決するか","古典公開鍵暗号","PQC,量子暗号移行,NIST,Kyber,Dilithium","PQC,quantum cryptography migration,NIST,Kyber,Dilithium","active","secondary",76,'["NIST PQC Team", "Michele Mosca"]','["NIST PQC Standard 2022", "CNSA 2.0 2022"]',"PQC移行率・サイバー攻撃成功率"),
    ("inno_digi_337","スマートホームとコネクテッドホームエコノミー","Smart Home and Connected Home Economy","スマートホーム（Amazon Echo・Google Nest・Apple HomeKit）はIoT機器の家庭統合プラットフォームで、音声AI・センサー・自動化を通じて家庭体験を変革する。Berg Insight（2023）は世界スマートホームデバイス市場が2027年に8.5億台に達すると予測した。エネルギー管理（スマートサーモスタット）・セキュリティ・高齢者ケアが価値提供の主要用途。プラットフォーム競争（Matter標準採用）がスマートホームエコシステムの相互運用性を改善しつつある。","platform_digital_innovation","IoT・エッジコンピューティング",2014,None,"meso","消費者・住宅","スマートホーム戦略","家庭IoT展開戦略を設計する際","スマートホームはどのような家庭エネルギー・セキュリティ価値を提供するか","アナログ家電","スマートホーム,IoT,Amazon Echo,Matter,音声AI","smart home,IoT,Amazon Echo,Matter,voice AI","active","secondary",76,'["Amazon Alexa Team", "Google Nest Team"]','["Berg Insight 2023", "Connectivity Standards Alliance Matter 2022"]',"スマートホーム普及率・エネルギー節約"),
    ("inno_digi_338","デジタルプラットフォームと中小企業","Digital Platforms and Small and Medium Enterprises","デジタルプラットフォームはSMEに大市場へのアクセスを提供する一方、依存度の高さが交渉力の非対称を生む。Goldfarb & Tucker（2019）はデジタル技術がSMEの固定費を削減しグローバル市場参入を可能にすることを実証した。Amazon・Etsy・Shopifyがそれぞれ異なるSME支援モデルを提供する。手数料・アルゴリズム変更・競合参入が交渉力の不均衡として問題視される。EUのデジタル市場法（DMA）はプラットフォームのビジネスユーザーへの公正アクセス義務を規定する。","platform_digital_innovation","デジタルプラットフォーム経済",2019,None,"meso","中小企業","SMEのデジタルプラットフォーム活用","中小企業のデジタル化戦略を設計する際","デジタルプラットフォームはSMEにとって機会か脅威か","大企業優位の市場","デジタルプラットフォーム,SME,Amazon,Shopify,公平性","digital platform,SME,Amazon,Shopify,fairness","active","secondary",76,'["Avner Goldfarb", "Catherine Tucker"]','["Goldfarb Tucker 2019 JEP", "EU P2B Regulation 2020"]',"SMEの売上成長・プラットフォーム依存度"),
    ("inno_digi_339","リアルタイムデータ処理と意思決定","Real-Time Data Processing and Decision Making","ストリーミングデータ処理（Apache Kafka・Flink・Spark Streaming）はセンサー・トランザクション・SNSデータをリアルタイムに処理し、即時意思決定を可能にする。事不正検知（Stripe・PayPal）・広告入札・IoTアラートが主要応用。Marz & Warren（2015）のLambdaアーキテクチャがバッチ+ストリーミング処理の統合設計を提示した。Confluent（Kafka商業化）・Databricks（Flink商業化）が市場を牽引している。","platform_digital_innovation","AI・機械学習",2015,None,"micro","金融・製造・広告","リアルタイムデータ基盤設計","ミリ秒単位の意思決定が必要な場合","リアルタイム処理はどのような業務価値を生むか","バッチ処理","リアルタイム処理,Kafka,Flink,ストリーミング","real-time processing,Kafka,Flink,streaming","active","secondary",78,'["Jay Kreps", "Nathan Marz"]','["Marz Warren 2015 Big Data", "Confluent Reports 2022"]',"遅延時間・スループット"),
    ("inno_digi_340","バイオインフォマティクスとゲノムデジタル経済","Bioinformatics and Genomic Digital Economy","ゲノミクスのデジタル化（次世代シーケンシング・CRISPR・ゲノムデータベース）は個別化医療・農業品種改良・バイオセキュリティを変革する。Illumina・PacBio・Oxford Nanoporeがシーケンシングプラットフォームを競争。NIH All of Us・UK Biobank・ゲノムイングランドが大規模ゲノムデータベースを構築し研究基盤を提供する。DNAデータストレージ（ゲノム配列への情報記録）が次世代ストレージ技術として注目される。","platform_digital_innovation","SpaceTech・DeepTech",2015,None,"macro","医療・農業","バイオインフォマティクス応用","ゲノムデータを活用した医療・農業革新","ゲノミクスのデジタル化はどのような産業変革をもたらすか","集団遺伝学","バイオインフォマティクス,ゲノム,個別化医療,Illumina","bioinformatics,genome,personalized medicine,Illumina","active","secondary",76,'["Francis Collins", "Jay Flatley"]','["NIH All of Us 2018", "UK Biobank 2022"]',"シーケンシングコスト・ゲノム解析精度"),
    ("inno_digi_341","AIによる気候変動予測と適応","AI for Climate Change Prediction and Adaptation","AI・機械学習は気候モデリング・極端気象予測・CO2排出最適化・エネルギー系統管理で気候変動対応を加速する。Rolnick et al.（2022）の「Tackling Climate Change with Machine Learning」が機野応用の包括的マップを提示した。DeepMind WeatherBenchとNVIDIA Earth-2が高精度気候シミュレーションを実現しつつある。IPCC AR6はAIを気候予測の精度向上ツールとして注目し、適応策立案への活用を勧告した。","platform_digital_innovation","エネルギー・環境DX",2022,None,"macro","気候・エネルギー","AI気候応用設計","気候変動対策にAIを活用する際","AIは気候変動予測と適応政策をどう改善するか","伝統的気候モデル","AI,気候変動,WeatherBench,IPCC,予測","AI,climate change,WeatherBench,IPCC,prediction","active","secondary",78,'["David Rolnick", "Yoshua Bengio"]','["Rolnick et al. 2022 CACM", "IPCC AR6 WG3 2022"]',"予測精度・エネルギー削減量"),
    ("inno_digi_342","プラットフォームビジネスのユニットエコノミクス","Unit Economics of Platform Business","プラットフォームのユニットエコノミクスはLTV（顧客生涯価値）/CAC（顧客獲得コスト）比・Cohort分析・GMV take-rateで評価される。Damodaran（2020）はプラットフォームバリュエーションにおける従来DCF法の限界を論じ、ネットワーク効果を組み込む修正モデルを提案した。UberやAirbnbのIPO申請書がユニットエコノミクスの実態を開示し、投資家の評価手法の改善をもたらした。","platform_digital_innovation","プラットフォーム経済学",2020,None,"micro","VC・スタートアップ","プラットフォーム財務評価","プラットフォームビジネスの価値を評価する際","ユニットエコノミクスはプラットフォームの持続可能性をどう示すか","売上高評価","LTV,CAC,GMV,ユニットエコノミクス,プラットフォーム","LTV,CAC,GMV,unit economics,platform","active","secondary",78,'["Aswath Damodaran", "Brad Stone"]','["Damodaran 2020 Little Book of Valuation", "Uber S-1 2019"]',"LTV/CAC比・take-rate"),
    ("inno_digi_343","オープンイノベーションプラットフォームとデジタル協働","Open Innovation Platform and Digital Collaboration","デジタルプラットフォームはオープンイノベーション（Chesbrough 2003）を加速し、企業外部の知識・技術・アイデアを組織的に取り込む。InnoCentive・Kaggle・HeroX がクラウドソーシング型イノベーションプラットフォームとして機能した。企業のイノベーションハブ・アクセラレータ・コーポレートVCがデジタル連携基盤を整備。Lakhani & Panetta（2007）は外部問題解決者（知識の「周縁」）が内部専門家より有効な場合を実証した。","platform_digital_innovation","デジタルプラットフォーム経済",2007,None,"meso","R&D・製造","オープンイノベーション設計","外部知識をデジタルで取り込む際","デジタルOIプラットフォームはどのようなイノベーション成果を生むか","社内R&D","オープンイノベーション,クラウドソーシング,Kaggle,InnoCentive","open innovation,crowdsourcing,Kaggle,InnoCentive","active","secondary",76,'["Karim Lakhani", "Lars Jeppesen"]','["Chesbrough 2003", "Lakhani Panetta 2007 MIT SMR"]',"問題解決率・外部提案採用率"),
    ("inno_digi_344","デジタルコモンズとデータ共有基盤","Digital Commons and Data Sharing Infrastructure","デジタルコモンズはWikipedia・OpenStreetMap・Wikidata等の公共データ基盤で、非市場的協調生産により共有知識インフラを提供する。Elinor Ostrom（2009ノーベル経済学賞）のコモンズ管理理論がデジタルコモンズの制度設計に応用される。FAIR原則（Findable・Accessible・Interoperable・Reusable）がデータ共有基盤の設計基準となっている。研究データ公開義務（EU Horizon Europe・NIH DMS Policy）がオープンサイエンスを推進する。","platform_digital_innovation","データ経済",2016,None,"macro","学術・公共","データ共有基盤設計","研究データの公開・共有を推進する際","デジタルコモンズはどのような知識生産を可能にするか","民間データ独占","デジタルコモンズ,Wikipedia,FAIR,オープンデータ","digital commons,Wikipedia,FAIR,open data","active","secondary",78,'["Elinor Ostrom", "Mark Wilkinson"]','["Ostrom 2009", "Wilkinson et al. 2016 FAIR"]',"データ共有量・再利用率"),
    ("inno_digi_345","デジタルリテラシーと批判的技術教育","Digital Literacy and Critical Technology Education","デジタルリテラシーは情報評価・プログラミング・データ理解・AI理解を含む現代的基礎能力。UNESCO ICTコンピテンシーフレームワーク・EU DigComp2.2（2022）が国際基準を提供する。フィンランドの全国AI倫理教育・UK Computerコンピューティングカリキュラムが先進事例として研究される。批判的技術教育（Critical Technology Literacy）はアルゴリズム・プラットフォーム・AIへの市民的批判能力を育成する。","platform_digital_innovation","デジタル包摂",2020,None,"macro","教育","デジタルリテラシー教育設計","AI時代の教育カリキュラムを設計する際","デジタルリテラシーはどのような社会的能力を育成するか","従来型リテラシー","デジタルリテラシー,DigComp,AI教育,プログラミング教育","digital literacy,DigComp,AI education,coding education","active","secondary",76,'["UNESCO EdTech Division", "EU DigComp Team"]','["EU DigComp 2.2 2022", "UNESCO ICT CFT 2022"]',"デジタルリテラシー指標・教育普及率"),
    ("inno_digi_346","AIと創薬の規制科学","AI and Regulatory Science in Drug Development","FDAのAI/ML-based Software as a Medical Device（SaMD）フレームワーク（2021）はAI医療機器の監視承認基準を定める。欧州EMAも同様の規制ガイダンスを整備中。Klebe（2019）は創薬AIのバリデーション課題を整理した。「説明不可能なAI診断」への患者の同意問題・承認後AI更新（Continuous Learning）の規制困難が制度設計の課題となっている。医薬品承認期間の短縮（FDA Breakthrough Therapy指定）とAIの組み合わせが業界標準となりつつある。","platform_digital_innovation","AI規制・ガバナンス",2021,None,"meso","製薬・医療機器","AI医療機器規制","AI創薬製品の規制対応を設計する際","AIの医療承認プロセスはどのような課題を持つか","従来医療機器承認","AI創薬,FDA SaMD,規制科学,バリデーション","AI drug discovery,FDA SaMD,regulatory science,validation","active","secondary",76,'["FDA CDER", "EMA Digital Transformation"]','["FDA AI SaMD 2021", "EMA AI Strategy 2023"]',"承認期間・開発コスト"),
    ("inno_digi_347","データスペースとEuropean Data Economy","Data Space and European Data Economy","EU主導のデータスペース（GAIA-X・Health Data Space・Industrial Data Space）は欧州内でのデータ共有基盤を競争主権的に構築する試み。EU Data Act（2023）・EU Data Governance Act（2022）が法的フレームを提供する。Iansiti & Lakhani（2022）の「Competing in the Age of AI」が欧州の戦略的文脈を分析する枠組みを提供。非個人データの共有義務・公共データの再利用・データ仲介者の規制が政策の三本柱。","platform_digital_innovation","データ経済",2022,None,"macro","EU政策・産業","データ主権政策設計","欧州データ経済政策を評価する際","EUデータスペースはどのような市場失敗を補正するか","GAFAMによるデータ独占","データスペース,GAIA-X,EU Data Act,データ主権","data space,GAIA-X,EU Data Act,data sovereignty","active","secondary",76,'["EU Commission Digital Policy", "Hubert Tardieu"]','["EU Data Act 2023", "EU Data Governance Act 2022"]',"データ共有量・欧州データ市場規模"),
    ("inno_digi_348","マルチモーダルAIと次世代インターフェース","Multimodal AI and Next-Generation Interface","マルチモーダルAIはテキスト・画像・音声・動画・センサーデータを統合処理する。GPT-4V・Gemini Ultra・Claude 3がマルチモーダル能力を実装した。Reed et al.（2022）のGATOは単一モデルで604種のタスクをこなす「ジェネラリストエージェント」を実証した。医療診断（テキスト×画像）・自動運転（映像×センサー）・教育（音声×テキスト×映像）への応用が拡大している。","platform_digital_innovation","AI・機械学習",2023,None,"micro","AI開発全般","マルチモーダルシステム設計","複数データモダリティを統合したAIを構築する際","マルチモーダルAIはどのような人間的認知能力に近づくか","単一モダリティAI","マルチモーダルAI,GPT-4V,Gemini,GATO","multimodal AI,GPT-4V,Gemini,GATO","active","primary",80,'["Aakanksha Chowdhery", "Scott Reed"]','["Reed et al. 2022 GATO", "OpenAI GPT-4V 2023"]',"マルチタスク精度・応用採用率"),
    ("inno_digi_349","デジタルプラットフォームと民主的公論空間","Digital Platforms and Democratic Public Sphere","ハーバーマスの公共圏（Public Sphere）概念をソーシャルメディアに適用した分析が活発化している。Papacharissi（2010）は「仮想的公共圏」として参加・可視性・議論の可能性を評価した。Twitter/X・Facebook・YouTubeの政治言説への影響が言論分析として研究される。アルゴリズムフィード・広告ターゲティング・プラットフォーム所有者の判断が公論空間の非中立性を生む。","platform_digital_innovation","プラットフォーム規制",2010,None,"macro","メディア・政治","デジタル公論空間設計","デジタルメディアの民主主義への影響を分析する際","デジタルプラットフォームは公論空間を強化するか弱化するか","伝統的マスメディア","公共圏,ソーシャルメディア,民主主義,アルゴリズム","public sphere,social media,democracy,algorithm","active","secondary",76,'["Jürgen Habermas", "Zizi Papacharissi"]','["Papacharissi 2010", "Habermas 2022 On Public Sphere"]',"政治的参加率・議論質指標"),
    ("inno_digi_350","スマートエネルギーグリッドとデジタルユーティリティ","Smart Energy Grid and Digital Utility","スマートグリッドはIoTセンサー・AI・通信技術で電力系統をリアルタイム制御し、再エネの変動性・需要側応答・EVとの統合を実現する。IEA（2023）はグリッドデジタル化投資が2030年に年間6000億ドルが必要と推計した。PG&E・Enel・東京電力の先進事例が系統安定化・コスト削減を示す。サイバーセキュリティ（電力系統攻撃）・規制設計（電力市場改革）がスマートグリッド展開の制度的課題。","platform_digital_innovation","エネルギー・環境DX",2020,None,"macro","エネルギー","スマートグリッド設計","再エネ統合と電力系統管理を最適化する際","スマートグリッドはどのような電力系統課題を解決するか","集中型発電・送電","スマートグリッド,電力系統,IoT,再エネ統合","smart grid,power grid,IoT,renewable integration","active","secondary",78,'["IEA Energy", "Massoud Amin"]','["IEA Grid Report 2023", "Amin 2008 IEEE"]',"系統安定性・再エネ統合率"),
]

conn = sqlite3.connect(DB)
cur = conn.cursor()
insert_sql = """INSERT OR IGNORE INTO innovation_theory
(id, name_ja, name_en, definition, subfield, school_of_thought, era_start, era_end,
 methodology_level, target_domain, application_conditions, when_to_apply, framing_questions,
 opposing_concept_names, keywords_ja, keywords_en, status, source_reliability, data_completeness,
 key_researchers, key_works, measurement_approach)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
conn.executemany(insert_sql, records)
conn.commit()
print(f"Inserted: {conn.total_changes}")
cur.execute("SELECT COUNT(*) FROM innovation_theory WHERE subfield='platform_digital_innovation'")
print(f"Total: {cur.fetchone()[0]}")
conn.close()
