"""Batch B: 数学・統計学(40) + 化学・材料科学(40) + 生物学補完(40) = 120概念"""
import sqlite3, datetime

DB = '/Users/nishimura+/projects/research/academic-knowledge-db/academic.db'

def make(id_, ja, en, defn, impact, subfield, school, era_start, era_end,
         math_form=None, culture='Global_Synthesis', culture_conf=85,
         url=None, keywords_ja='', keywords_en='', name_original=''):
    return {
        'id': id_, 'name_ja': ja, 'name_en': en, 'name_original': name_original,
        'definition': defn, 'impact_summary': impact, 'subfield': subfield,
        'school_of_thought': school, 'era_start': era_start, 'era_end': era_end,
        'methodology_level': 'theoretical', 'target_domain': 'natural_science',
        'application_conditions': '実験的・理論的検証が可能な条件',
        'when_to_apply': '自然現象の定量的記述・予測が必要な場合',
        'framing_questions': '当該現象はどのように定式化されるか',
        'opposing_concept_names': '', 'keywords_ja': keywords_ja,
        'keywords_en': keywords_en, 'status': 'active',
        'source_reliability': 'high', 'data_completeness': 'complete',
        'mathematical_formulation': math_form or '',
        'experimental_verification': 'confirmed',
        'applicable_scale': 'universal', 'precision_level': 'high',
        'quality_flag': 'verified',
        'source_url': url or f'https://en.wikipedia.org/wiki/{en.replace(" ", "_")}',
        'primary_source': '', 'primary_source_url': '', 'primary_source_year': era_start,
        'verification_status': 'url_present',
        'culture_region': culture, 'culture_confidence': culture_conf,
        'genealogy_narrative': '', 'narrative_word_count': 0,
        'gta_l3': subfield, 'gta_l2': '自然発見', 'last_verified_at': '',
        'redirect_to': '', 'http_status': 200,
    }

# ── 数学・統計学 (nd_b_001 – nd_b_040) ──────────────────────────────────
MATH = [
    make('nd_b_001','ユークリッド幾何学','Euclidean Geometry',
         '平面と空間の公理的記述体系。5公準から導かれる命題の演繹的集合。',
         'Western mathematics foundation; influenced all subsequent formal systems.',
         '数学・統計学','Axiomatic_Geometry',-300,1900,
         r'a^2+b^2=c^2 \text{ (Pythagorean theorem)}','Western_Mediterranean',90,
         'https://en.wikipedia.org/wiki/Euclidean_geometry',
         'ユークリッド,公理,幾何学','Euclid,axiom,geometry'),

    make('nd_b_002','微積分学','Calculus',
         'Newton・Leibnizが独立に発展させた無限小解析。微分・積分の基本定理。',
         'Enabled analytic mechanics, physics, and modern engineering.',
         '数学・統計学','Classical_Analysis',1665,1720,
         r'\frac{d}{dx}\int_a^x f(t)dt=f(x)','Western_Europe',92,
         'https://en.wikipedia.org/wiki/Calculus',
         '微分,積分,無限小','differentiation,integration,infinitesimal'),

    make('nd_b_003','確率論','Probability Theory',
         'ランダム事象を数学的に扱う公理的枠組み。Kolmogorov公理系が基盤。',
         'Foundation of statistics, quantum mechanics, and information theory.',
         '数学・統計学','Mathematical_Probability',1654,1933,
         r'P(A\cup B)=P(A)+P(B)-P(A\cap B)','Western_Europe',88,
         'https://en.wikipedia.org/wiki/Probability_theory',
         '確率,ランダム,コルモゴロフ','probability,random,Kolmogorov'),

    make('nd_b_004','統計的仮説検定','Statistical Hypothesis Testing',
         'Neyman-Pearsonフレームワーク。帰無仮説と対立仮説の棄却域による判断。',
         'Standard tool in science; governs experimental inference globally.',
         '数学・統計学','Frequentist_Statistics',1925,1940,
         r't=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}','Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Statistical_hypothesis_testing',
         '仮説検定,p値,有意水準','hypothesis,p-value,significance'),

    make('nd_b_005','ベイズ定理','Bayes\' Theorem',
         '事前確率と尤度から事後確率を更新する逆確率の法則。',
         'Basis of Bayesian statistics, machine learning, and decision theory.',
         '数学・統計学','Bayesian_Inference',1763,1800,
         r'P(\theta|X)=\frac{P(X|\theta)P(\theta)}{P(X)}','British_Empiricism',90,
         'https://en.wikipedia.org/wiki/Bayes%27_theorem',
         'ベイズ,事後確率,更新','Bayes,posterior,prior,likelihood'),

    make('nd_b_006','フーリエ解析','Fourier Analysis',
         '周期関数を三角関数の重ね合わせとして表現する手法。フーリエ級数・変換。',
         'Signal processing, heat equation, quantum mechanics, and image analysis.',
         '数学・統計学','Mathematical_Analysis',1822,1870,
         r'f(x)=\sum_{n=-\infty}^{\infty}c_n e^{inx}','Western_Europe',90,
         'https://en.wikipedia.org/wiki/Fourier_analysis',
         'フーリエ,周波数,信号処理','Fourier,frequency,signal,transform'),

    make('nd_b_007','線形代数','Linear Algebra',
         'ベクトル空間・線形写像・行列演算を扱う数学分野。固有値分解が核心。',
         'Essential for quantum mechanics, data science, computer graphics.',
         '数学・統計学','Abstract_Algebra',1840,1920,
         r'A\mathbf{v}=\lambda\mathbf{v}','Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Linear_algebra',
         '行列,固有値,ベクトル空間','matrix,eigenvalue,vector_space'),

    make('nd_b_008','情報理論','Information Theory',
         'Shannonが1948年に確立。エントロピーによる情報量の定量化と符号化限界。',
         'Foundation of digital communication, data compression, and cryptography.',
         '数学・統計学','Information_Science',1948,1960,
         r'H(X)=-\sum_i p_i\log_2 p_i','American_Science',95,
         'https://en.wikipedia.org/wiki/Information_theory',
         'シャノン,エントロピー,通信','Shannon,entropy,channel_capacity'),

    make('nd_b_009','グラフ理論','Graph Theory',
         'ノードとエッジからなる離散構造の数学。ケーニヒスベルクの橋問題に起源。',
         'Network analysis, algorithm design, chemistry, and social science.',
         '数学・統計学','Discrete_Mathematics',1736,1900,
         r'|V|-|E|+|F|=2 \text{ (Euler for planar)}','Western_Europe',85,
         'https://en.wikipedia.org/wiki/Graph_theory',
         'グラフ,ネットワーク,オイラー','graph,network,Euler,vertex,edge'),

    make('nd_b_010','ゲーデルの不完全性定理','Gödel\'s Incompleteness Theorems',
         '十分強い算術体系は自らの無矛盾性を証明できず、証明不可能な真命題が存在する。',
         'Defined limits of formal systems; profound impact on logic and philosophy.',
         '数学・統計学','Mathematical_Logic',1931,1931,
         r'\exists\phi: PA\nvdash\phi \wedge PA\nvdash\lnot\phi','Central_European',95,
         'https://en.wikipedia.org/wiki/G%C3%B6del%27s_incompleteness_theorems',
         'ゲーデル,不完全性,論理','Gödel,incompleteness,formal_system'),

    make('nd_b_011','位相幾何学','Topology',
         '連続変形(同相写像)のもとで不変な性質を研究する幾何学。',
         'DNA topology, phase transitions, data analysis (TDA).',
         '数学・統計学','Abstract_Mathematics',1895,1950,
         r'\chi=V-E+F \text{ (Euler characteristic)}','Western_Europe',85,
         'https://en.wikipedia.org/wiki/Topology',
         'トポロジー,同相,連結性','topology,homeomorphism,manifold'),

    make('nd_b_012','モンテカルロ法','Monte Carlo Method',
         'ランダムサンプリングを用いた数値積分・シミュレーション技法。1940年代に原爆開発で開発。',
         'Nuclear physics, finance, climate modeling, and AI training.',
         '数学・統計学','Computational_Statistics',1946,1960,
         r'\int f(x)dx\approx\frac{1}{N}\sum_{i=1}^N f(X_i)','American_Science',88,
         'https://en.wikipedia.org/wiki/Monte_Carlo_method',
         'モンテカルロ,シミュレーション,乱数','Monte_Carlo,simulation,random_sampling'),

    make('nd_b_013','最小二乗法','Least Squares Method',
         'Gauss・Legendreが開発。残差の二乗和を最小化してパラメータを推定する回帰法。',
         'Standard fitting technique in science and engineering.',
         '数学・統計学','Statistical_Estimation',1795,1810,
         r'\hat{\beta}=(X^TX)^{-1}X^Ty','Western_Europe',90,
         'https://en.wikipedia.org/wiki/Least_squares',
         '最小二乗,回帰,フィッティング','least_squares,regression,Gauss'),

    make('nd_b_014','複素解析','Complex Analysis',
         '複素数値関数の微積分。コーシーの積分定理・留数定理を核心とする。',
         'Fluid dynamics, quantum field theory, electromagnetism.',
         '数学・統計学','Classical_Analysis',1820,1870,
         r'\oint_C f(z)dz=2\pi i\sum\text{Res}','Western_Europe',88,
         'https://en.wikipedia.org/wiki/Complex_analysis',
         'コーシー,留数,正則関数','Cauchy,residue,holomorphic'),

    make('nd_b_015','群論','Group Theory',
         'Galoisが方程式論で発展。対称性を抽象的に扱う代数構造の理論。',
         'Particle physics symmetry, crystallography, coding theory.',
         '数学・統計学','Abstract_Algebra',1830,1900,
         r'a\cdot(b\cdot c)=(a\cdot b)\cdot c,\;\exists e,\exists a^{-1}','Western_Europe',90,
         'https://en.wikipedia.org/wiki/Group_theory',
         'ガロア,対称性,群','Galois,symmetry,group,abstract_algebra'),

    make('nd_b_016','フラクタル幾何学','Fractal Geometry',
         'Mandelbrotが1975年に命名。自己相似性を持つ非整数次元の幾何構造。',
         'Natural form modeling (coastlines, trees, clouds), chaos, finance.',
         '数学・統計学','Nonlinear_Mathematics',1975,1990,
         r'D=\lim_{\epsilon\to0}\frac{\log N(\epsilon)}{\log(1/\epsilon)}','Western_Europe',88,
         'https://en.wikipedia.org/wiki/Fractal',
         'フラクタル,自己相似,マンデルブロ','fractal,self-similarity,Mandelbrot'),

    make('nd_b_017','中心極限定理','Central Limit Theorem',
         '独立同分布の確率変数の和が、元の分布によらず正規分布に収束する定理。',
         'Justifies normal approximation across science; foundation of inference.',
         '数学・統計学','Mathematical_Probability',1733,1901,
         r'\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\xrightarrow{d}N(0,1)','Western_Europe',90,
         'https://en.wikipedia.org/wiki/Central_limit_theorem',
         '中心極限定理,正規分布,収束','CLT,normal_distribution,convergence'),

    make('nd_b_018','微分方程式理論','Theory of Differential Equations',
         '未知関数とその導関数の関係式を解く数学的枠組み。自然の動態を記述。',
         'Physics, biology, economics, and engineering modeling.',
         '数学・統計学','Mathematical_Analysis',1670,1800,
         r'\frac{dy}{dx}=f(x,y),\;\text{existence/uniqueness via Lipschitz}','Western_Europe',88,
         'https://en.wikipedia.org/wiki/Differential_equation',
         '微分方程式,動力学,解析','differential_equation,dynamics,ODE,PDE'),

    make('nd_b_019','アラビア代数学','Al-Khwarizmi\'s Algebra',
         '9世紀イスラム数学者al-Khwarizmiが体系化した方程式の解法。"algebra"の語源。',
         'Transmitted Greek/Indian mathematics; foundational for all algebra.',
         '数学・統計学','Islamic_Mathematics',820,900,
         r'ax^2+bx+c=0\Rightarrow x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}',
         'Islamic_World',92,
         'https://en.wikipedia.org/wiki/Al-Khwarizmi',
         'アル・フワーリズミー,代数,イスラム数学','al-Khwarizmi,algebra,Islamic_mathematics',
         'الجبر'),

    make('nd_b_020','インド零と十進法','Indian Zero and Decimal System',
         '5〜7世紀インドで確立した零の概念と位取り十進記数法。Brahmaguptaが零の算術を整備。',
         'Enabled all subsequent arithmetic and computational mathematics.',
         '数学・統計学','Indian_Mathematics',500,700,
         r'10^n=1\underbrace{0\cdots0}_{n}','South_Asian',95,
         'https://en.wikipedia.org/wiki/0',
         'ゼロ,十進法,インド数学','zero,decimal,Indian_mathematics,Brahmagupta',
         'शून्य'),

    make('nd_b_021','中国の剰余定理','Chinese Remainder Theorem',
         '《孫子算経》(3〜5世紀)に初出。互いに素な法に対する連立合同式の解。',
         'Modern cryptography (RSA), parallel computation, scheduling.',
         '数学・統計学','East_Asian_Mathematics',300,500,
         r'x\equiv a_i\pmod{m_i}\Rightarrow x\equiv a\pmod{\prod m_i}',
         'East_Asian',92,
         'https://en.wikipedia.org/wiki/Chinese_remainder_theorem',
         '中国剰余定理,合同算術','CRT,modular_arithmetic,Sunzi',
         '孫子算經'),

    make('nd_b_022','確率的勾配降下法','Stochastic Gradient Descent',
         '大規模データに対してランダムサンプルで勾配を推定しパラメータを更新する最適化法。',
         'Core optimizer of deep learning; made modern AI training feasible.',
         '数学・統計学','Optimization_Theory',1951,2010,
         r'\theta_{t+1}=\theta_t-\eta\nabla_\theta L(\theta_t;x_i)','Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Stochastic_gradient_descent',
         'SGD,勾配降下,最適化','SGD,gradient_descent,optimization,deep_learning'),

    make('nd_b_023','マルコフ連鎖','Markov Chain',
         '現在の状態のみに依存して次の状態が決まる確率過程。Markovが1906年に定式化。',
         'Statistical mechanics, biology, finance, Google PageRank.',
         '数学・統計学','Stochastic_Processes',1906,1930,
         r'P(X_{n+1}|X_n,\ldots,X_0)=P(X_{n+1}|X_n)','Eastern_European',88,
         'https://en.wikipedia.org/wiki/Markov_chain',
         'マルコフ,確率過程,遷移行列','Markov,stochastic_process,transition_matrix'),

    make('nd_b_024','主成分分析','Principal Component Analysis',
         '高次元データの分散を最大化する直交基底を求める次元削減法。固有値分解に基づく。',
         'Data visualization, feature extraction, signal denoising.',
         '数学・統計学','Multivariate_Statistics',1901,1930,
         r'\max_{\|w\|=1}w^T\Sigma w\Rightarrow w=\text{eigenvector of }\Sigma',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Principal_component_analysis',
         'PCA,主成分,次元削減','PCA,dimensionality_reduction,eigenvector'),

    make('nd_b_025','測度論','Measure Theory',
         'Lebesgueが確立した集合の「大きさ」の厳密な定義。確率論の公理的基礎。',
         'Rigorous foundation for probability theory and integration.',
         '数学・統計学','Mathematical_Analysis',1901,1930,
         r'\mu(A)=\int_A d\mu,\;\sigma\text{-additivity}','Western_Europe',85,
         'https://en.wikipedia.org/wiki/Measure_(mathematics)',
         'ルベーグ,測度,積分','Lebesgue,measure,sigma-algebra'),

    make('nd_b_026','数値解析','Numerical Analysis',
         '連続数学の問題を有限精度の計算で近似的に解く方法論。誤差解析が核心。',
         'Scientific computing, finite element method, climate modeling.',
         '数学・統計学','Computational_Mathematics',1940,1970,
         r'f(x)\approx f(x_0)+f\'(x_0)(x-x_0)+O(h^2)','Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Numerical_analysis',
         '数値計算,誤差,有限要素法','numerical_analysis,error,finite_element'),

    make('nd_b_027','ゲーム理論','Game Theory',
         'Von Neumann・Morgensternが1944年に確立。戦略的相互作用の数学的分析。',
         'Economics, evolutionary biology, political science, AI.',
         '数学・統計学','Applied_Mathematics',1928,1950,
         r'u_i(s_i^*,s_{-i}^*)\geq u_i(s_i,s_{-i}^*)\;\forall s_i\text{ (Nash)}',
         'Western_Europe',90,
         'https://en.wikipedia.org/wiki/Game_theory',
         'ナッシュ均衡,戦略,von Neumann','Nash_equilibrium,strategy,zero-sum'),

    make('nd_b_028','最適制御理論','Optimal Control Theory',
         'Bellmanの動的計画法・Pontryaginの最大原理。状態方程式のもとで目的関数を最適化。',
         'Aerospace, robotics, economics, and energy systems.',
         '数学・統計学','Applied_Mathematics',1956,1970,
         r'H(x,u,\lambda)=L(x,u)+\lambda f(x,u)','Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Optimal_control',
         'ベルマン,ポントリャーギン,制御','Bellman,Pontryagin,dynamic_programming'),

    make('nd_b_029','圏論','Category Theory',
         'Eilenberg・MacLaneが1945年に創始。数学的構造間の変換(関手)を統一的に扱う。',
         'Foundation for algebraic topology, functional programming, physics.',
         '数学・統計学','Abstract_Mathematics',1945,1970,
         r'F:C\to D \text{ (functor)},\;G\circ F:\text{composition}','American_Science',85,
         'https://en.wikipedia.org/wiki/Category_theory',
         '圏論,関手,自然変換','category_theory,functor,natural_transformation'),

    make('nd_b_030','カオス理論','Chaos Theory',
         'ローレンツが1963年に発見。決定論的系の初期値鋭敏性とバタフライ効果。',
         'Weather prediction limits, population dynamics, cardiac fibrillation.',
         '数学・統計学','Nonlinear_Dynamics',1963,1980,
         r'\frac{d\mathbf{x}}{dt}=\mathbf{f}(\mathbf{x}),\;|\delta\mathbf{x}(t)|\sim e^{\lambda t}',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Chaos_theory',
         'カオス,バタフライ効果,ローレンツ','chaos,butterfly_effect,Lorenz,Lyapunov'),

    make('nd_b_031','アルゴリズム複雑性理論','Computational Complexity Theory',
         'P=NP問題を核心とする計算困難さの分類体系。Cook-Levinの定理が基礎。',
         'Cryptography, algorithm design, AI limits.',
         '数学・統計学','Theoretical_Computer_Science',1971,1990,
         r'P\subseteq NP\subseteq PSPACE,\;P\stackrel{?}{=}NP','American_Science',88,
         'https://en.wikipedia.org/wiki/Computational_complexity_theory',
         'P=NP,NP完全,クック','P_NP,NP-complete,Cook-Levin'),

    make('nd_b_032','ウェーブレット変換','Wavelet Transform',
         'Daubechiesらが1980年代に発展。時間-周波数局在を両立する多重解像度解析。',
         'Image compression (JPEG2000), signal denoising, seismology.',
         '数学・統計学','Applied_Mathematics',1984,2000,
         r'W_\psi f(a,b)=\int f(t)\bar{\psi}_{a,b}(t)dt','Western_Europe',85,
         'https://en.wikipedia.org/wiki/Wavelet_transform',
         'ウェーブレット,多重解像度,圧縮','wavelet,multiresolution,Daubechies'),

    make('nd_b_033','マヤ数学','Maya Mathematics',
         '20進法と位取り記数法を採用。ゼロの独立発見(約AD300)と高精度天文計算。',
         'Independent invention of zero; astronomic cycle calculations.',
         '数学・統計学','Mesoamerican_Mathematics',300,900,
         r'N=\sum_{k}d_k\cdot 20^k \text{ (vigesimal)}','Mesoamerican',90,
         'https://en.wikipedia.org/wiki/Maya_numerals',
         'マヤ,二十進法,ゼロ','Maya,vigesimal,zero,Mesoamerica',
         ''),

    make('nd_b_034','変分法','Calculus of Variations',
         'Euler・Lagrangeが発展。関数の関数(汎関数)を最小化する手法。最小作用原理の基礎。',
         'Classical mechanics, optics, optimal transport, field theory.',
         '数学・統計学','Mathematical_Analysis',1744,1800,
         r'\delta\int L(q,\dot{q},t)dt=0\Rightarrow\frac{d}{dt}\frac{\partial L}{\partial\dot{q}}-\frac{\partial L}{\partial q}=0',
         'Western_Europe',90,
         'https://en.wikipedia.org/wiki/Calculus_of_variations',
         '変分法,オイラー・ラグランジュ,最小作用','variational_calculus,Euler-Lagrange,action'),

    make('nd_b_035','ランダム行列理論','Random Matrix Theory',
         'Wignerが原子核スペクトルのために開発。大次元行列の固有値分布を扱う。',
         'Nuclear physics, number theory, wireless communication, finance.',
         '数学・統計学','Mathematical_Physics',1955,1980,
         r'\rho(\lambda)=\frac{1}{2\pi}\sqrt{4-\lambda^2}\text{ (Wigner semicircle)}',
         'American_Science',82,
         'https://en.wikipedia.org/wiki/Random_matrix',
         'ランダム行列,ウィグナー,固有値','random_matrix,Wigner,eigenvalue_distribution'),

    make('nd_b_036','インド三角法','Indian Trigonometry',
         'Aryabhata(5〜6世紀)がサインの表を編纂。弦から半弦(sine)への移行がイスラム経由で西洋へ。',
         'Bridge between ancient astronomy and Islamic/European trigonometry.',
         '数学・統計学','Indian_Mathematics',499,600,
         r'\sin\theta\approx\theta-\frac{\theta^3}{6}+\cdots \text{ (Madhava series)}',
         'South_Asian',90,
         'https://en.wikipedia.org/wiki/Aryabhata',
         'アーリャバッタ,サイン,インド数学','Aryabhata,sine,Indian_trigonometry,Madhava',
         'आर्यभट'),

    make('nd_b_037','格子理論','Lattice Theory',
         '半順序集合の代数的構造。束(lattice)の格子点上の問題は暗号・量子情報と密接。',
         'Crystallography, quantum error correction, post-quantum cryptography.',
         '数学・統計学','Abstract_Algebra',1900,1950,
         r'a\vee b=\sup\{a,b\},\;a\wedge b=\inf\{a,b\}','Western_Europe',82,
         'https://en.wikipedia.org/wiki/Lattice_(order)',
         '束,半順序,暗号','lattice,partial_order,cryptography'),

    make('nd_b_038','統計的学習理論','Statistical Learning Theory',
         'Vapnik-Chervonenkisが発展。VC次元と汎化誤差の関係を定式化。',
         'Foundation of machine learning theory; bias-variance tradeoff.',
         '数学・統計学','Mathematical_Statistics',1971,1995,
         r'R(f)\leq R_{emp}(f)+O\left(\sqrt{\frac{d_{VC}}{n}}\right)','Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Statistical_learning_theory',
         'VC次元,汎化,機械学習理論','VC_dimension,generalization,Vapnik,SVM'),

    make('nd_b_039','最適輸送理論','Optimal Transport Theory',
         'Monge(1781)→Kantorovich(1942)が確立。分布間の輸送コスト最小化問題。',
         'Image processing, machine learning (Wasserstein distance), economics.',
         '数学・統計学','Applied_Mathematics',1781,1942,
         r'W_p(\mu,\nu)=\left(\inf_\gamma\int d(x,y)^p d\gamma\right)^{1/p}',
         'Western_Europe',85,
         'https://en.wikipedia.org/wiki/Transportation_theory_(mathematics)',
         '最適輸送,ワッサースタイン,カントロビッチ','optimal_transport,Wasserstein,Kantorovich'),

    make('nd_b_040','アフリカの数学的伝統','African Mathematical Traditions',
         'イシャンゴ骨(BC20000)の素数列・タンザニアのフラクタル建築配置・エジプト算術。',
         'Earliest evidence of mathematical thought; non-Western mathematical heritage.',
         '数学・統計学','African_Mathematics',-20000,1000,
         r'\text{Ishango notations: }11,13,17,19 \text{ (prime sequence)}',
         'Sub_Saharan_African',80,
         'https://en.wikipedia.org/wiki/Ishango_bone',
         'イシャンゴ,アフリカ数学,骨刻み','Ishango,African_mathematics,prime,fractal',
         ''),
]

# ── 化学・材料科学 (nd_b_041 – nd_b_080) ─────────────────────────────────
CHEM = [
    make('nd_b_041','周期律','Periodic Law',
         'Mendeleevが1869年に発見。元素の性質が原子量の周期関数として変化する法則。',
         'Organized chemistry; predicted undiscovered elements.',
         '化学・材料科学','Inorganic_Chemistry',1869,1871,
         r'Z\to Z+1:\text{valence electrons cycle } 1\to8','Eastern_European',95,
         'https://en.wikipedia.org/wiki/Periodic_table',
         '元素周期表,メンデレーエフ,原子番号','periodic_table,Mendeleev,element,valence'),

    make('nd_b_042','化学結合理論','Chemical Bonding Theory',
         'Lewis構造(1916)・価電子殻反発モデル・分子軌道法の体系。',
         'Explains molecular geometry, reactivity, and material properties.',
         '化学・材料科学','Physical_Chemistry',1916,1960,
         r'E=\sum_i\varepsilon_i-\sum_{ij}J_{ij}+\sum_{ij}K_{ij}','American_Science',88,
         'https://en.wikipedia.org/wiki/Chemical_bond',
         '共有結合,分子軌道,Lewis構造','chemical_bond,molecular_orbital,Lewis_structure'),

    make('nd_b_043','熱力学第一・第二法則(化学)','Thermodynamic Laws in Chemistry',
         'Gibbsの自由エネルギー(1875)を用いた化学反応の自発性・平衡条件の決定。',
         'Predicts spontaneity and equilibrium of all chemical reactions.',
         '化学・材料科学','Physical_Chemistry',1875,1900,
         r'\Delta G=\Delta H-T\Delta S<0\text{ (spontaneous)}','American_Science',92,
         'https://en.wikipedia.org/wiki/Gibbs_free_energy',
         'ギブスエネルギー,自発性,平衡','Gibbs_free_energy,enthalpy,entropy,equilibrium'),

    make('nd_b_044','触媒作用','Catalysis',
         'Berzeliusが命名(1835)。反応経路を変えて活性化エネルギーを下げる物質。不変性が特徴。',
         'Industrial synthesis (Haber-Bosch), enzymes, pollution control.',
         '化学・材料科学','Chemical_Engineering',1835,1900,
         r'k=A e^{-E_a/RT}:\text{catalysis lowers }E_a','Scandinavian',90,
         'https://en.wikipedia.org/wiki/Catalysis',
         '触媒,活性化エネルギー,Haber-Bosch','catalyst,activation_energy,enzyme'),

    make('nd_b_045','量子化学','Quantum Chemistry',
         'Schrödinger方程式の化学への適用。分子の電子構造・反応性を第一原理計算で解明。',
         'Drug design, materials discovery, and photochemistry.',
         '化学・材料科学','Physical_Chemistry',1926,1950,
         r'\hat{H}\Psi=E\Psi,\;\hat{H}=-\frac{\hbar^2}{2m}\nabla^2+V','Western_Europe',92,
         'https://en.wikipedia.org/wiki/Quantum_chemistry',
         'シュレーディンガー,分子軌道,DFT','quantum_chemistry,DFT,Schrodinger,molecular_orbital'),

    make('nd_b_046','X線結晶学','X-ray Crystallography',
         'Bragg父子が1913年に確立。X線回折パターンから結晶構造を決定する技法。',
         'DNA double helix (1953), protein structures, drug development.',
         '化学・材料科学','Structural_Chemistry',1913,1950,
         r'2d\sin\theta=n\lambda \text{ (Bragg\'s law)}','British_Science',95,
         'https://en.wikipedia.org/wiki/X-ray_crystallography',
         'Bragg,X線回折,結晶構造','X-ray_crystallography,Bragg,diffraction,crystal_structure'),

    make('nd_b_047','核磁気共鳴分光法','Nuclear Magnetic Resonance Spectroscopy',
         'Bloch・Purcellが1946年に発見。核スピンの磁気共鳴を利用した構造決定法(NMR・MRI)。',
         'Chemical structure determination; MRI in medicine.',
         '化学・材料科学','Analytical_Chemistry',1946,1960,
         r'\omega_0=\gamma B_0 \text{ (Larmor frequency)}','American_Science',92,
         'https://en.wikipedia.org/wiki/Nuclear_magnetic_resonance',
         'NMR,MRI,核スピン,化学シフト','NMR,MRI,chemical_shift,Bloch,Purcell'),

    make('nd_b_048','ポリマー科学','Polymer Science',
         'Staudingerが1920年代にマクロ分子の概念を確立。連鎖反応・分子量分布を定量化。',
         'Plastics, rubber, biological macromolecules (proteins, DNA).',
         '化学・材料科学','Polymer_Chemistry',1920,1950,
         r'M_n=\frac{\sum_i N_i M_i}{\sum_i N_i},\;\text{PDI}=M_w/M_n','German_Science',88,
         'https://en.wikipedia.org/wiki/Polymer_chemistry',
         'ポリマー,高分子,Staudinger','polymer,macromolecule,Staudinger,PDI'),

    make('nd_b_049','電気化学','Electrochemistry',
         'FaradayとVoltaが先駆。電子移動反応・電極電位・電解を扱う化学分野。',
         'Batteries, fuel cells, corrosion prevention, electroplating.',
         '化学・材料科学','Physical_Chemistry',1800,1850,
         r'E=E^0-\frac{RT}{nF}\ln Q \text{ (Nernst equation)}','British_Science',90,
         'https://en.wikipedia.org/wiki/Electrochemistry',
         'Nernst方程式,電池,電解','Nernst,Faraday,electrode_potential,electrolysis'),

    make('nd_b_050','緑色化学','Green Chemistry',
         'Anastas・Warnerが1998年に12原則を提唱。廃棄物ゼロ・原子効率最大化を指向。',
         'Sustainable synthesis, solvent-free chemistry, bio-based materials.',
         '化学・材料科学','Sustainable_Chemistry',1998,2010,
         r'\text{Atom Economy}=\frac{MW_\text{desired}}{MW_\text{all reactants}}\times100\%',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Green_chemistry',
         'グリーン化学,原子効率,12原則','green_chemistry,atom_economy,Anastas'),

    make('nd_b_051','半導体の発見と理論','Semiconductor Theory',
         'Shockley・Bardeen・Brattainが1947年にトランジスタを発明。バンドギャップ理論が基盤。',
         'Modern electronics, solar cells, LEDs, and computing.',
         '化学・材料科学','Solid_State_Chemistry',1947,1960,
         r'E_g=E_c-E_v;\;n_i=\sqrt{N_c N_v}e^{-E_g/2kT}','American_Science',95,
         'https://en.wikipedia.org/wiki/Semiconductor',
         '半導体,バンドギャップ,トランジスタ','semiconductor,band_gap,transistor,Shockley'),

    make('nd_b_052','超伝導の発見','Discovery of Superconductivity',
         'Onnesが1911年に水銀の電気抵抗ゼロを発見。BCS理論(1957)がクーパー対で説明。',
         'MRI magnets, maglev, quantum computing, particle accelerators.',
         '化学・材料科学','Condensed_Matter',1911,1957,
         r'\Delta=2\hbar\omega_D e^{-1/N(0)V} \text{ (BCS gap)}','Dutch_Science',95,
         'https://en.wikipedia.org/wiki/Superconductivity',
         '超伝導,BCS理論,クーパー対','superconductivity,BCS,Cooper_pair,Onnes'),

    make('nd_b_053','錯体化学','Coordination Chemistry',
         'Wernerが1893年に配位理論を提唱。金属イオンと配位子の結合を扱う。',
         'Bioinorganic chemistry, homogeneous catalysis, MRI contrast agents.',
         '化学・材料科学','Inorganic_Chemistry',1893,1920,
         r'\text{Crystal Field Splitting }\Delta_o=E_{e_g}-E_{t_{2g}}','Swiss_German',85,
         'https://en.wikipedia.org/wiki/Coordination_chemistry',
         'Werner,配位子,錯体','Werner,coordination_compound,ligand,crystal_field'),

    make('nd_b_054','有機合成の系統化','Systematic Organic Synthesis',
         'Corey(1990 Nobel)が逆合成解析を確立。複雑天然物の全合成戦略を論理化。',
         'Drug synthesis, natural product chemistry, chemical biology.',
         '化学・材料科学','Organic_Chemistry',1969,1990,
         r'\text{retrosynthesis: }C\Rightarrow A+B \text{ (disconnection)}','American_Science',88,
         'https://en.wikipedia.org/wiki/Retrosynthetic_analysis',
         'Corey,逆合成,全合成','retrosynthesis,Corey,total_synthesis'),

    make('nd_b_055','クロマトグラフィー','Chromatography',
         'Tswettが1900年代初頭に植物色素分離で発見。移動相・固定相間の分配による分離。',
         'Analytical chemistry, pharmaceutical QC, environmental monitoring.',
         '化学・材料科学','Analytical_Chemistry',1903,1950,
         r'R_f=\frac{d_\text{solute}}{d_\text{solvent}}','Russian_Science',88,
         'https://en.wikipedia.org/wiki/Chromatography',
         'クロマトグラフィー,Tswett,分離','chromatography,partition,HPLC,Tswett'),

    make('nd_b_056','质谱分析法','Mass Spectrometry',
         'Thomson(1913)が原型を開発。イオン化→質量電荷比分離→検出で分子量・構造を決定。',
         'Proteomics, drug discovery, environmental analysis, forensics.',
         '化学・材料科学','Analytical_Chemistry',1913,1960,
         r'm/z=\frac{m}{ze};\;t=L\sqrt{\frac{m}{2zeV}}','British_Science',88,
         'https://en.wikipedia.org/wiki/Mass_spectrometry',
         '質量分析,イオン化,プロテオミクス','mass_spectrometry,ionization,m/z,proteomics'),

    make('nd_b_057','錬金術からイスラム化学へ','Islamic Alchemy and Chemistry',
         'ジャービル・イブン・ハイヤーン(8世紀)が蒸留・昇華・結晶化を体系化。近代化学の源流。',
         'Laid groundwork for laboratory techniques and chemical nomenclature.',
         '化学・材料科学','Islamic_Chemistry',750,850,
         r'\text{Jabir\'s techniques: distillation, sublimation, crystallization}',
         'Islamic_World',88,
         'https://en.wikipedia.org/wiki/Jabir_ibn_Hayyan',
         'ジャービル,錬金術,イスラム化学','Jabir,alchemy,Islamic_chemistry,distillation',
         'جابر بن حيان'),

    make('nd_b_058','中国の火薬と花火技術','Chinese Gunpowder and Pyrotechnics',
         '9世紀中国の道教錬丹術から誕生した火薬。硝石・硫黄・炭の配合比を経験的に最適化。',
         'Transformed warfare and mining; led to modern explosives chemistry.',
         '化学・材料科学','East_Asian_Chemistry',850,1000,
         r'\text{KNO}_3+\text{S}+\text{C}\to\text{combustion gases}',
         'East_Asian',90,
         'https://en.wikipedia.org/wiki/Gunpowder',
         '火薬,硝石,中国化学','gunpowder,saltpeter,Chinese_chemistry,pyrotechnics',
         '火藥'),

    make('nd_b_059','ナノマテリアル科学','Nanomaterial Science',
         'Feynmanの1959年講演に触発。カーボンナノチューブ(1991)・グラフェン(2004)が先導。',
         'Drug delivery, energy storage, semiconductors, composite materials.',
         '化学・材料科学','Nanoscience',1991,2010,
         r'd_{CNT}\approx0.4\text{ nm};\;E_{Young}\approx1\text{ TPa}','Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Nanomaterials',
         'ナノチューブ,グラフェン,ナノ材料','nanotube,graphene,nanomaterials,Feynman'),

    make('nd_b_060','インドのラサ・シャストラ','Indian Rasa Shastra',
         'アーユルヴェーダの水銀化合物精製技術(8〜12世紀)。金属の薬理的変換を扱うインド錬金術。',
         'Early systematic metallurgy and medicinal chemistry in Asia.',
         '化学・材料科学','Indian_Chemistry',800,1200,
         r'\text{Kajjali}=\text{Hg}+\text{S}\to\text{HgS (black sulfide)}',
         'South_Asian',82,
         'https://en.wikipedia.org/wiki/Rasa_Shastra',
         'ラサシャストラ,アーユルヴェーダ,インド化学','Rasa_Shastra,Ayurveda,mercury,Indian_alchemy',
         'रसशास्त्र'),

    make('nd_b_061','電気化学発光','Electrochemiluminescence',
         '電気化学反応で生成した励起状態からの発光現象。ルミノール・ルテニウム錯体が代表。',
         'Immunoassay diagnostics (clinical analyzers), DNA detection.',
         '化学・材料科学','Analytical_Chemistry',1964,1990,
         r'e^-+\text{Ru}(bpy)_3^{3+}\to[\text{Ru}(bpy)_3^{2+}]^*\to h\nu',
         'American_Science',80,
         'https://en.wikipedia.org/wiki/Electrochemiluminescence',
         'ECL,ルミノール,発光','ECL,luminol,ruthenium,luminescence'),

    make('nd_b_062','有機金属化学','Organometallic Chemistry',
         '金属-炭素結合を持つ化合物の化学。Ziegler-Natta触媒・グラブス触媒がノーベル賞。',
         'Industrial polymer synthesis, cross-coupling reactions, drug synthesis.',
         '化学・材料科学','Organometallic_Chemistry',1950,1980,
         r'\text{Grubbs: }Ru=CH_2\to\text{olefin metathesis}','German_Science',88,
         'https://en.wikipedia.org/wiki/Organometallic_chemistry',
         'Grubbs,Ziegler-Natta,有機金属','organometallic,Grubbs,metathesis,Ziegler-Natta'),

    make('nd_b_063','アフリカ冶金術','African Iron Metallurgy',
         'サブサハラアフリカのブロー炉(BC1000頃)。タンザニアの炉はヨーロッパより高温を達成。',
         'Evidence of independent metallurgical innovation in sub-Saharan Africa.',
         '化学・材料科学','African_Metallurgy',-1000,1500,
         r'T_{furnace}>1400°C:\text{carbon reduction of Fe}_2\text{O}_3',
         'Sub_Saharan_African',85,
         'https://en.wikipedia.org/wiki/Metallurgy_in_sub-Saharan_Africa',
         'アフリカ冶金,鉄,ブロー炉','African_metallurgy,iron_smelting,Tanzania',
         ''),

    make('nd_b_064','タンパク質折り畳み','Protein Folding',
         'Anfinsenが1972年にアミノ酸配列が立体構造を決定することを示した。AlphaFold(2020)が革命。',
         'Drug design, disease understanding (Alzheimer, Parkinson).',
         '化学・材料科学','Biochemistry',1972,2020,
         r'\Delta G_\text{fold}=\Delta H_\text{fold}-T\Delta S_\text{fold}','American_Science',95,
         'https://en.wikipedia.org/wiki/Protein_folding',
         'タンパク質折り畳み,AlphaFold,Anfinsen','protein_folding,Anfinsen,AlphaFold,structure'),

    make('nd_b_065','アモルファス材料科学','Amorphous Materials Science',
         '長距離秩序を持たない固体(ガラス・非晶質半導体)の構造と物性。',
         'Glass fiber optics, amorphous silicon solar cells, metallic glasses.',
         '化学・材料科学','Materials_Science',1950,1980,
         r'g(r)=\frac{1}{4\pi\rho r^2}\frac{dn}{dr}\text{ (radial distribution)}',
         'Global_Synthesis',80,
         'https://en.wikipedia.org/wiki/Amorphous_solid',
         'アモルファス,ガラス,非晶質','amorphous,glass,metallic_glass,solar_cell'),

    make('nd_b_066','分子分光学','Molecular Spectroscopy',
         '電磁波と分子の相互作用。赤外・紫外可視・ラマン分光が構造・結合・動態を解明。',
         'Non-destructive structural analysis in chemistry, biology, and industry.',
         '化学・材料科学','Physical_Chemistry',1860,1930,
         r'E=h\nu=hc/\lambda;\;\Delta E=E_2-E_1','Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Spectroscopy',
         '赤外分光,ラマン,分子振動','infrared,Raman,UV-Vis,molecular_vibration'),

    make('nd_b_067','相転移の物理化学','Phase Transitions',
         'Gibbs相律とEhrenfestの分類。固液気・磁気・超流動の転移を熱力学的に記述。',
         'Materials design, climate science (cloud nucleation), condensed matter.',
         '化学・材料科学','Physical_Chemistry',1875,1960,
         r'F=C-P+2 \text{ (Gibbs phase rule)}','American_Science',88,
         'https://en.wikipedia.org/wiki/Phase_transition',
         '相転移,Gibbs相律,臨界点','phase_transition,Gibbs_phase_rule,critical_point'),

    make('nd_b_068','フラーレンとC60の発見','Fullerene Discovery',
         'Kroto・Smalley・Curlが1985年に発見。炭素の第三の同素体。1996年ノーベル化学賞。',
         'Nanotechnology, superconductivity in doped fullerenes, drug delivery.',
         '化学・材料科学','Carbon_Chemistry',1985,1996,
         r'C_{60}:\text{12 pentagons + 20 hexagons (truncated icosahedron)}',
         'British_American',92,
         'https://en.wikipedia.org/wiki/Buckminsterfullerene',
         'フラーレン,C60,炭素同素体','fullerene,C60,Kroto,nanotube,carbon'),

    make('nd_b_069','陶磁器の科学','Ceramics Science',
         '中国の磁器技術(9世紀)から近代セラミクス工学へ。焼結・相変態・機械強度の理解。',
         'Aerospace thermal protection, dental implants, electronics substrates.',
         '化学・材料科学','East_Asian_Materials',900,1900,
         r'\sigma_f=\frac{K_{Ic}}{Y\sqrt{\pi a}} \text{ (fracture toughness)}',
         'East_Asian',85,
         'https://en.wikipedia.org/wiki/Ceramic_engineering',
         '陶磁器,焼結,セラミクス','ceramics,sintering,fracture_toughness,porcelain',
         '陶瓷'),

    make('nd_b_070','合金設計の原理','Alloy Design Principles',
         'Hume-Rothery則(1926)・CALPHAD法。原子半径・電気陰性度・結晶構造からの合金設計。',
         'Steel, aluminum alloys, superalloys for aerospace and energy.',
         '化学・材料科学','Metallurgy',1926,1970,
         r'\Delta H_{mix}=4\sum_{i\neq j}\Omega_{ij}c_ic_j \text{ (Miedema)}',
         'British_Science',85,
         'https://en.wikipedia.org/wiki/Hume-Rothery_rules',
         'Hume-Rothery,合金,CALPHAD','Hume-Rothery,alloy,CALPHAD,phase_diagram'),

    make('nd_b_071','イスラムの薬理化学','Islamic Pharmacochemistry',
         'イブン・スィーナー(アビケンナ)の《医学典範》(1025)が薬物の純化・試験法を体系化。',
         'First systematic clinical drug testing; influenced European pharmacy.',
         '化学・材料科学','Islamic_Pharmacology',1025,1100,
         r'\text{standardized drug testing: purity, dose, controlled trials}',
         'Islamic_World',88,
         'https://en.wikipedia.org/wiki/Avicenna',
         'アビケンナ,医学典範,イスラム薬学','Avicenna,Canon_of_Medicine,pharmacology',
         'ابن سينا'),

    make('nd_b_072','電池化学の発展','Battery Chemistry Evolution',
         'Volta(1800)→鉛蓄電池(1859)→リチウムイオン電池(Goodenough/吉野彰,1991)の系譜。',
         'Portable electronics, electric vehicles, renewable energy storage.',
         '化学・材料科学','Electrochemistry',1800,1991,
         r'\text{LiCoO}_2+C\rightleftharpoons\text{Li}_x\text{C}+\text{Li}_{1-x}\text{CoO}_2',
         'Global_Synthesis',92,
         'https://en.wikipedia.org/wiki/Lithium-ion_battery',
         'リチウムイオン電池,Goodenough,吉野彰','lithium-ion,Goodenough,Yoshino,battery'),

    make('nd_b_073','高圧化学','High-Pressure Chemistry',
         'Bridgman(Nobel 1946)が超高圧実験を体系化。ダイヤモンドアンビルセルで超高圧相が探索。',
         'Diamond synthesis, hydrogen storage, earth\'s mantle chemistry.',
         '化学・材料科学','Physical_Chemistry',1906,1960,
         r'P>100\text{ GPa in DAC};\;\rho\propto P^{1/3}','American_Science',80,
         'https://en.wikipedia.org/wiki/High-pressure_chemistry',
         '高圧化学,Bridgman,ダイヤモンドアンビル','high_pressure,Bridgman,diamond_anvil_cell'),

    make('nd_b_074','生物無機化学','Bioinorganic Chemistry',
         '生体内金属イオンの機能。鉄(ヘモグロビン)・マグネシウム(葉緑素)・亜鉛(酵素)等。',
         'Understanding disease (hemochromatosis), drug design, bioremediation.',
         '化学・材料科学','Biochemistry',1960,1980,
         r'\text{Fe}^{2+}\text{-heme}+O_2\rightleftharpoons\text{Fe}^{2+}\text{-heme-}O_2',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Bioinorganic_chemistry',
         '金属酵素,ヘモグロビン,鉄','bioinorganic,hemoglobin,metalloenzyme,iron'),

    make('nd_b_075','アンデス文明の冶金','Andean Metallurgy',
         '南米アンデスの金・銀・銅・青銅加工技術(BC2000〜)。Tumbaga合金(金銀銅)の表面処理。',
         'Advanced Pre-Columbian alloy technology; cultural material knowledge.',
         '化学・材料科学','Andean_Metallurgy',-2000,1500,
         r'\text{Tumbaga: Au+Ag+Cu alloy, depletion gilding surface treatment}',
         'South_American',85,
         'https://en.wikipedia.org/wiki/Andean_metallurgy',
         'アンデス冶金,Tumbaga,インカ','Andean_metallurgy,Tumbaga,gold,Pre-Columbian',
         ''),

    make('nd_b_076','光触媒反応','Photocatalysis',
         '本多・藤嶋が1972年に発見した酸化チタンの光触媒効果。光励起で酸化還元反応を誘起。',
         'Pollutant decomposition, hydrogen generation, self-cleaning surfaces.',
         '化学・材料科学','Physical_Chemistry',1972,1990,
         r'TiO_2+h\nu\to e^-+h^+;\;h^++H_2O\to\cdot OH','East_Asian',92,
         'https://en.wikipedia.org/wiki/Photocatalysis',
         '光触媒,本多・藤嶋効果,酸化チタン','photocatalysis,Honda-Fujishima,TiO2,semiconductor'),

    make('nd_b_077','ゾル・ゲル法','Sol-Gel Process',
         'アルコキシドの加水分解・重縮合でナノ多孔質ガラス・セラミクスを合成する湿式法。',
         'Optical coatings, controlled-pore silica, aerogels.',
         '化学・材料科学','Materials_Chemistry',1960,1980,
         r'Si(OR)_4+4H_2O\to Si(OH)_4+4ROH\to SiO_2','Global_Synthesis',80,
         'https://en.wikipedia.org/wiki/Sol-gel_process',
         'ゾル・ゲル,シリカ,エアロゲル','sol-gel,silica,aerogel,wet_chemistry'),

    make('nd_b_078','クリックケミストリー','Click Chemistry',
         'Sharplessが2001年に提唱。高効率・高選択的な生体直交反応の概念。2022年ノーベル賞。',
         'Drug conjugation, bioorthogonal labeling, polymer synthesis.',
         '化学・材料科学','Organic_Chemistry',2001,2022,
         r'R_1\text{-}N_3+R_2\text{-}C\equiv C\to\text{triazole (CuAAC)}','American_Science',90,
         'https://en.wikipedia.org/wiki/Click_chemistry',
         'クリックケミストリー,Sharpless,生体直交','click_chemistry,Sharpless,bioorthogonal'),

    make('nd_b_079','超分子化学','Supramolecular Chemistry',
         'Lehn(Nobel 1987)が確立。共有結合によらない分子間相互作用で構築する「分子の建築」。',
         'Molecular machines, drug delivery, self-assembly nanotechnology.',
         '化学・材料科学','Supramolecular_Chemistry',1967,1990,
         r'H_\text{host-guest}=\Delta G=\Delta H-T\Delta S\text{ (binding)}',
         'Western_Europe',88,
         'https://en.wikipedia.org/wiki/Supramolecular_chemistry',
         '超分子,Lehn,自己組織化','supramolecular,Lehn,self-assembly,host-guest'),

    make('nd_b_080','放射化学','Radiochemistry',
         'キュリー夫妻(1898)のポロニウム・ラジウム発見。放射性元素の分離・同位体化学・トレーサー法。',
         'Nuclear medicine (PET/SPECT), carbon dating, reactor chemistry.',
         '化学・材料科学','Nuclear_Chemistry',1898,1940,
         r'N(t)=N_0 e^{-\lambda t},\;t_{1/2}=\ln2/\lambda','Western_Europe',90,
         'https://en.wikipedia.org/wiki/Radiochemistry',
         'キュリー,放射能,半減期','Curie,radioactivity,half-life,isotope'),
]

# ── 生物学補完 (nd_b_081 – nd_b_120) ─────────────────────────────────────
BIO = [
    make('nd_b_081','ゲノム解読技術','Genome Sequencing Technologies',
         'Sanger法(1977)→次世代シーケンサー(2005〜)→ナノポア(2014〜)。ゲノムの全塩基配列決定。',
         'Human Genome Project (2003), personalized medicine, metagenomics.',
         '生物学','Genomics',1977,2010,
         r'N_{reads}\cdot L_{read}/L_{genome}=C \text{ (coverage)}','British_American',95,
         'https://en.wikipedia.org/wiki/DNA_sequencing',
         'ゲノム解読,Sanger,次世代シーケンサー','genome_sequencing,Sanger,NGS,nanopore'),

    make('nd_b_082','CRISPR-Cas9ゲノム編集','CRISPR-Cas9 Genome Editing',
         'Doudna・Charpentierが2012年に確立。ガイドRNAでDNA切断部位を誘導する精密ゲノム編集。',
         'Gene therapy, crop improvement, disease model organisms.',
         '生物学','Molecular_Biology',2012,2022,
         r'k_{on}\sim10^7\text{M}^{-1}\text{s}^{-1};\;\text{PAM: NGG}','American_Science',98,
         'https://en.wikipedia.org/wiki/CRISPR',
         'CRISPR,Cas9,ゲノム編集,Doudna','CRISPR,Cas9,gene_editing,Doudna,Charpentier'),

    make('nd_b_083','細胞周期の制御','Cell Cycle Control',
         'Hartwell・Hunt・Nurse(2001 Nobel)がサイクリン・CDKを発見。増殖・分裂の分子スイッチ。',
         'Cancer biology, drug targets (CDK inhibitors), developmental biology.',
         '生物学','Cell_Biology',1970,2001,
         r'[Cyclin\text{-}CDK]\text{ kinase activity}\propto[\text{Cyclin}]\cdot k_{cat}',
         'American_British',92,
         'https://en.wikipedia.org/wiki/Cell_cycle',
         'サイクリン,CDK,細胞周期','cell_cycle,cyclin,CDK,Hartwell,Nurse'),

    make('nd_b_084','光合成の機構','Mechanism of Photosynthesis',
         'Calvin回路(1950s)・光反応の電子伝達鎖。光システムII/Iと水分解・NADPH生成。',
         'Foundation of life on Earth; inspiration for artificial photosynthesis.',
         '生物学','Plant_Biology',1950,1980,
         r'6CO_2+6H_2O+h\nu\to C_6H_{12}O_6+6O_2','American_Science',95,
         'https://en.wikipedia.org/wiki/Photosynthesis',
         'カルビン回路,光合成,光システム','Calvin_cycle,photosystem,electron_transport'),

    make('nd_b_085','神経可塑性','Neural Plasticity',
         'Hebb則(1949)「共に発火する細胞は共に配線される」。シナプス強化・長期増強(LTP)の機構。',
         'Learning and memory, brain rehabilitation, AI (Hebbian learning).',
         '生物学','Neuroscience',1949,1980,
         r'\Delta w_{ij}=\eta\cdot x_i\cdot x_j \text{ (Hebb rule)}','Canadian_Science',90,
         'https://en.wikipedia.org/wiki/Neuroplasticity',
         'ヘッブ則,LTP,神経可塑性','Hebb,LTP,synaptic_plasticity,neuroplasticity'),

    make('nd_b_086','進化発生生物学','Evolutionary Developmental Biology',
         'Evo-Devo。ホメオボックス遺伝子(Hox)の保存性が体制の進化的変化を制御。',
         'Explains body plan diversity; links genetics to macroevolution.',
         '生物学','Evolutionary_Biology',1983,2000,
         r'\text{Hox genes: }A1\text{-}D13 \text{ collinear with body axis}',
         'American_British',88,
         'https://en.wikipedia.org/wiki/Evolutionary_developmental_biology',
         'Evo-Devo,Hox遺伝子,ホメオボックス','Evo-Devo,Hox,homeobox,body_plan'),

    make('nd_b_087','微生物生態学','Microbial Ecology',
         '環境中の微生物群集の多様性・機能・相互作用。メタゲノミクスで難培養微生物も解析可能。',
         'Soil health, microbiome-disease links, bioremediation.',
         '生物学','Microbiology',1970,2000,
         r'\text{Shannon }H=-\sum_i p_i\ln p_i\text{ (diversity index)}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Microbial_ecology',
         '微生物群集,メタゲノム,生物多様性','microbial_ecology,metagenomics,microbiome'),

    make('nd_b_088','エピジェネティクス','Epigenetics',
         'DNA配列の変化なしに遺伝子発現を変える修飾(メチル化・ヒストン修飾)。世代間継承も。',
         'Cancer mechanism, aging, developmental programming, psychiatry.',
         '生物学','Molecular_Biology',1942,2000,
         r'\text{CpG methylation: }m^5C\to\text{gene silencing}','British_American',90,
         'https://en.wikipedia.org/wiki/Epigenetics',
         'エピジェネティクス,DNAメチル化,ヒストン','epigenetics,methylation,histone,Waddington'),

    make('nd_b_089','免疫学の基礎','Foundations of Immunology',
         'Ehrlichの側鎖説(1900)→クローン選択説(Burnet 1957)→適応免疫の分子機構解明。',
         'Vaccines, immunotherapy (cancer), autoimmune disease treatment.',
         '生物学','Immunology',1900,1960,
         r'K_D=k_{off}/k_{on};\;\text{antibody affinity}\sim10^{-9}\text{ M}',
         'Western_Europe',92,
         'https://en.wikipedia.org/wiki/Immunology',
         'クローン選択,抗体,Burnet','clonal_selection,Burnet,antibody,adaptive_immunity'),

    make('nd_b_090','生体膜の流動モザイクモデル','Fluid Mosaic Model of Membranes',
         'Singer・Nicolsonが1972年に提唱。脂質二重層に膜タンパク質が流動する細胞膜モデル。',
         'Foundation of cell biology; drug target membrane proteins.',
         '生物学','Cell_Biology',1972,1980,
         r'D_{lipid}\approx10^{-8}\text{ cm}^2/\text{s (lateral diffusion)}',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Fluid_mosaic_model',
         '流動モザイクモデル,細胞膜,Singer-Nicolson','fluid_mosaic,Singer_Nicolson,lipid_bilayer'),

    make('nd_b_091','アポトーシス','Apoptosis',
         'プログラムされた細胞死。Brenner・Sulston・Horvitzが線虫で確立(2002 Nobel)。カスパーゼが実行。',
         'Cancer (apoptosis evasion), neurodegenerative disease, immunity.',
         '生物学','Cell_Biology',1972,2002,
         r'\text{Caspase cascade: procaspase}\to\text{caspase}\to\text{cell death}',
         'British_American',92,
         'https://en.wikipedia.org/wiki/Apoptosis',
         'アポトーシス,カスパーゼ,プログラム細胞死','apoptosis,caspase,Sulston,Horvitz'),

    make('nd_b_092','クロマチン構造と遺伝子発現','Chromatin Structure and Gene Expression',
         'ヌクレオソーム(1974)・染色体ループドメイン・3Dゲノム構造がエンハンサー・プロモーター相互作用を制御。',
         'Cancer epigenomics, transcription factor biology, 3D genome organization.',
         '生物学','Molecular_Biology',1974,2010,
         r'r_{gyration}\sim N^{0.6}\text{ (polymer model of chromatin)}',
         'American_British',88,
         'https://en.wikipedia.org/wiki/Chromatin',
         'クロマチン,ヌクレオソーム,Hi-C','chromatin,nucleosome,Hi-C,3D_genome'),

    make('nd_b_093','生物時計','Circadian Clock',
         'Hall・Rosbash・Young(2017 Nobel)がショウジョウバエでper・timを同定。概日リズムの分子基盤。',
         'Sleep medicine, jet lag, chronotherapy for cancer treatment.',
         '生物学','Chronobiology',1971,2017,
         r'dP/dt=\alpha-\beta P;\;T\approx24h \text{ (TTFL model)}','American_Science',92,
         'https://en.wikipedia.org/wiki/Circadian_rhythm',
         '概日時計,per,tim,Hall-Rosbash-Young','circadian,per,tim,Hall,Rosbash,chronobiology'),

    make('nd_b_094','RNAの世界仮説','RNA World Hypothesis',
         'Gilbert(1986)が提唱。生命起源において自己複製するRNAが触媒・情報の両機能を担ったとする仮説。',
         'Origin of life research, ribozyme discovery, prebiotic chemistry.',
         '生物学','Evolutionary_Biology',1968,1990,
         r'k_{cat}/K_m\sim10^3\text{ M}^{-1}\text{s}^{-1}\text{ (ribozyme)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/RNA_world',
         'RNA世界,リボザイム,生命起源','RNA_world,ribozyme,origin_of_life,Gilbert'),

    make('nd_b_095','共生進化論','Endosymbiotic Theory',
         'Margulisが1967年に確立。ミトコンドリア・葉緑体が好気性細菌・シアノバクテリアに由来する。',
         'Explains eukaryotic cell origin; influences evolutionary biology.',
         '生物学','Evolutionary_Biology',1967,1980,
         r'\text{mt DNA circles }\sim16\text{ kbp, }\sim70\% \text{ similar to }\alpha\text{-proteobacteria}',
         'American_Science',92,
         'https://en.wikipedia.org/wiki/Endosymbiotic_theory',
         'マーグリス,共生,ミトコンドリア','Margulis,endosymbiosis,mitochondria,chloroplast'),

    make('nd_b_096','アユルヴェーダ医学と植物薬理学','Ayurvedic Pharmacobotany',
         '3000年以上の歴史を持つインドの医学体系。Charaka Samhita(BC100〜AD200)が薬用植物を体系化。',
         'Source of many modern drugs (reserpine, artemisinin precursors); ethnobotany.',
         '生物学','South_Asian_Biology',-1000,200,
         r'\text{Tridosha: Vata+Pitta+Kapha=systemic balance}',
         'South_Asian',85,
         'https://en.wikipedia.org/wiki/Ayurveda',
         'アーユルヴェーダ,Charaka,薬用植物','Ayurveda,Charaka,medicinal_plants,India',
         'आयुर्वेद'),

    make('nd_b_097','ウイルス学の確立','Establishment of Virology',
         'Ivanovsky(1892)・Beijerinck(1898)がタバコモザイクウイルスを発見。ウイルスの生命体ではない性質を認識。',
         'Basis for vaccines, antiviral drugs, and pandemic preparedness.',
         '生物学','Virology',1892,1935,
         r'R_0=\beta\cdot N/\gamma;\;\text{epidemic threshold: }R_0>1','Eastern_European',90,
         'https://en.wikipedia.org/wiki/Virology',
         'ウイルス学,Ivanovsky,タバコモザイク','virology,Ivanovsky,Beijerinck,TMV,R_naught'),

    make('nd_b_098','種分化の機構','Mechanisms of Speciation',
         'マイア(1942)が地理的隔離による異所的種分化を体系化。性的選択・遺伝的浮動も種分化を駆動。',
         'Understanding biodiversity, conservation genetics, species management.',
         '生物学','Evolutionary_Biology',1942,1980,
         r'F_{ST}=\frac{\sigma^2_p}{\bar{p}(1-\bar{p})}\text{ (population differentiation)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Speciation',
         'マイア,種分化,地理的隔離','Mayr,speciation,allopatric,genetic_drift'),

    make('nd_b_099','伝統中国医学の薬理学','Traditional Chinese Medicine Pharmacology',
         '《本草綱目》(李時珍,1596)が1892種の薬物を記載。経絡・五行説と生薬の体系的統合。',
         'Source of artemisinin (屠呦呦 Nobel 2015), acupuncture research.',
         '生物学','East_Asian_Biology',1596,1700,
         r'\text{Artemisinin: }C_{15}H_{22}O_5\text{ (sesquiterpene lactone endoperoxide)}',
         'East_Asian',90,
         'https://en.wikipedia.org/wiki/Traditional_Chinese_medicine',
         '本草綱目,李時珍,漢方','TCM,Li_Shizhen,Bencao_Gangmu,artemisinin',
         '本草綱目'),

    make('nd_b_100','スーパーコンピュータを用いた分子動力学','Molecular Dynamics Simulation',
         'Alder・Wainwright(1957)が先駆。力場を用いてタンパク質・液体・材料の原子軌跡を数値積分。',
         'Drug design, protein dynamics, materials under extreme conditions.',
         '生物学','Computational_Biology',1957,1990,
         r'\mathbf{F}_i=-\nabla_i U;\;m_i\ddot{\mathbf{r}}_i=\mathbf{F}_i','American_Science',88,
         'https://en.wikipedia.org/wiki/Molecular_dynamics',
         '分子動力学,力場,タンパク質シミュレーション','molecular_dynamics,force_field,protein_simulation'),

    make('nd_b_101','テロメアとゲノム安定性','Telomeres and Genome Stability',
         'Blackburn・Greider・Szostak(2009 Nobel)がテロメア・テロメラーゼを発見。細胞老化のカウンター。',
         'Cancer immortality, aging biology, telomere-length biomarkers.',
         '生物学','Molecular_Biology',1978,2009,
         r'L_{telomere}\approx L_0-\Delta L\cdot n\text{ (shortening per division)}',
         'American_Science',92,
         'https://en.wikipedia.org/wiki/Telomere',
         'テロメア,テロメラーゼ,老化','telomere,telomerase,Blackburn,aging'),

    make('nd_b_102','植物ホルモンの発見','Discovery of Plant Hormones',
         'Darwin父子のオーキシン先駆実験(1880)→ジベレリン(黒沢英一,1926)→エチレン・サイトカイニン。',
         'Agriculture (growth regulators, ripening control), botanical science.',
         '生物学','Plant_Biology',1880,1960,
         r'[IAA]\propto\text{phototropic bending angle (Went 1937)}','East_Asian_British',88,
         'https://en.wikipedia.org/wiki/Plant_hormone',
         'オーキシン,ジベレリン,植物ホルモン','auxin,gibberellin,ethylene,plant_hormone,Kurosawa'),

    make('nd_b_103','群集生態学','Community Ecology',
         'Hutchinsonのニッチ理論(1957)・MacArthur-Wilsonの島嶼生物地理学(1967)。種間相互作用と多様性。',
         'Conservation policy, invasive species, climate-biodiversity linkage.',
         '生物学','Ecology',1957,1980,
         r'S=cA^z\text{ (species-area relationship)}','American_Science',88,
         'https://en.wikipedia.org/wiki/Community_ecology',
         'ニッチ,島嶼生物地理,種多様性','niche,MacArthur_Wilson,island_biogeography'),

    make('nd_b_104','性選択理論','Sexual Selection Theory',
         'Darwinが《人間の由来》(1871)で提唱。Fisher流暴走・Zahavi诚实信号理論が発展。',
         'Explains ornaments, mating systems, behavior evolution.',
         '生物学','Evolutionary_Biology',1871,1975,
         r'\Delta\bar{z}=\frac{V_A}{\bar{w}}\frac{\partial\bar{w}}{\partial\bar{z}}\text{ (breeder\'s equation)}',
         'British_Science',88,
         'https://en.wikipedia.org/wiki/Sexual_selection',
         'ダーウィン,性選択,Fisher暴走','Darwin,sexual_selection,Fisher,Zahavi,runaway'),

    make('nd_b_105','極限環境微生物','Extremophiles',
         '熱水噴出孔・深海・塩湖・酸性湖に適応した微生物。古細菌の多くが含まれる。',
         'Biotechnology (Taq polymerase), astrobiology, deep biosphere.',
         '生物学','Microbiology',1969,1990,
         r'T_{opt}>80°C\text{ (hyperthermophile, }T_{opt}>45°C\text{ thermophile)}',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Extremophile',
         '極限環境生物,好熱菌,古細菌','extremophile,thermophile,archaea,Taq_polymerase'),

    make('nd_b_106','行動生態学','Behavioral Ecology',
         'Hamilton包括適応度(1964)・Maynard Smith ESS理論。利己的遺伝子・協力行動の進化的説明。',
         'Sociobiology, conservation (reserve design), evolutionary psychology.',
         '生物学','Behavioral_Biology',1964,1980,
         r'r\cdot b>c\text{ (Hamilton\'s rule)}','British_Science',88,
         'https://en.wikipedia.org/wiki/Behavioral_ecology',
         'ハミルトン,ESS,協力進化','Hamilton,inclusive_fitness,ESS,Maynard_Smith'),

    make('nd_b_107','古代DNA研究','Ancient DNA Research',
         'Pääboが1984年にエジプトのミイラからDNA抽出。ネアンデルタール人ゲノム(2010)でヒトとの交配実証。',
         'Human migration history, extinction reconstructions, forensics.',
         '生物学','Genomics',1984,2010,
         r'D_\text{stat}(H1,H2;Nean,chimp)\text{ D-statistics for introgression}',
         'Swedish_German',95,
         'https://en.wikipedia.org/wiki/Ancient_DNA',
         'Pääbo,古代DNA,ネアンデルタール','Paabo,ancient_DNA,Neanderthal,introgression'),

    make('nd_b_108','神経科学の地図：ブロードマン領野','Brodmann Areas of Brain Mapping',
         'Brodmannが1909年に大脳皮質を52野に分類。細胞構築学的地図が機能局在研究の基盤。',
         'Functional MRI interpretation, neurosurgery, cognitive neuroscience.',
         '生物学','Neuroscience',1909,1925,
         r'\text{Brodmann area }17:\text{V1 primary visual cortex}','German_Science',85,
         'https://en.wikipedia.org/wiki/Brodmann_area',
         'Brodmann,大脳皮質,神経地図','Brodmann,cortex_mapping,fMRI,cytoarchitecture'),

    make('nd_b_109','マオリの生態学的知識','Māori Traditional Ecological Knowledge',
         'ニュージーランドのマオリ族のrāhui(漁業制限)・kaitiakitanga(環境保護管理)の体系的慣行。',
         'Indigenous resource management; informing modern conservation policy.',
         '生物学','Indigenous_Ecology',1000,1800,
         r'\text{Rahui: seasonal harvest prohibition}=\text{spatial refugia}',
         'Pacific_Islander',85,
         'https://en.wikipedia.org/wiki/Kaitiakitanga',
         'マオリ,kaitiakitanga,伝統的管理','Maori,kaitiakitanga,rahui,TEK,Pacific',
         'Kaitiakitanga'),

    make('nd_b_110','転写因子ネットワーク','Transcription Factor Networks',
         'YakobovichらのChIP-seqで大規模TFネットワーク解析が可能に。マスターレギュレーターが分化を制御。',
         'Stem cell reprogramming (Yamanaka factors), cancer driver genes.',
         '生物学','Molecular_Biology',2000,2015,
         r'dX_i/dt=f(\mathbf{W}\cdot\mathbf{X})\text{ (GRN Boolean model)}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Transcription_factor',
         '転写因子,ChIP-seq,Yamanaka因子','transcription_factor,ChIP-seq,Yamanaka,GRN'),

    make('nd_b_111','海洋生物多様性の基盤','Marine Biodiversity Foundations',
         '「珊瑚礁=海の熱帯雨林」概念。Connell(1978)の中規模撹乱仮説が多様性維持を説明。',
         'Marine conservation policy, fisheries management, coral reef protection.',
         '生物学','Marine_Biology',1960,1990,
         r'H_{max}=\ln S;\;H\text{ (Shannon)}\leq H_{max}','American_Australian',85,
         'https://en.wikipedia.org/wiki/Marine_biodiversity',
         '珊瑚礁,海洋生物多様性,Connell','coral_reef,marine_biodiversity,Connell,IDH'),

    make('nd_b_112','アフリカ伝統植物医学','African Traditional Plant Medicine',
         'アフリカの伝統ヒーラー(sangoma/nyanga)による数千種の薬用植物知識体系。HOT/COLD分類法。',
         'Ethnobotanical drug leads; biodiversity conservation incentives.',
         '生物学','African_Biology',500,1800,
         r'\text{African medicinal plant libraries: }>5000\text{ species used}',
         'Sub_Saharan_African',82,
         'https://en.wikipedia.org/wiki/African_traditional_medicine',
         'アフリカ伝統医学,植物薬理,ethnobotany','African_traditional_medicine,sangoma,ethnobotany',
         ''),

    make('nd_b_113','プリオン病の発見','Prion Disease Discovery',
         'Prusinerが1982年に提唱。タンパク質のみで感染性を持つ異常プリオンの概念。1997年ノーベル賞。',
         'Mad cow disease mechanism, CJD, potential treatment development.',
         '生物学','Neuroscience',1982,1997,
         r'PrP^C\to PrP^{Sc}:\text{conformational change, }\\beta\text{-sheet increase}',
         'American_Science',92,
         'https://en.wikipedia.org/wiki/Prion',
         'プリオン,Prusiner,ウシ海綿状脳症','prion,Prusiner,BSE,CJD,protein_misfolding'),

    make('nd_b_114','コラーゲン・細胞外マトリクス','Collagen and Extracellular Matrix',
         'Porter(1956)の電子顕微鏡でコラーゲン三重らせんを観察。ECMが細胞の足場・信号を提供。',
         'Tissue engineering, wound healing, fibrosis, cancer invasion.',
         '生物学','Cell_Biology',1956,1980,
         r'\text{Triple helix: }(Gly\text{-}X\text{-}Y)_n,\;T_m\sim37°C\text{ for body}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Collagen',
         'コラーゲン,細胞外マトリクス,組織工学','collagen,ECM,triple_helix,tissue_engineering'),

    make('nd_b_115','アマゾンの伝統的農業知識','Amazonian Traditional Agricultural Knowledge',
         'テラプレタ(アマゾン黒土)をBC800〜AD400の先住民が炭化農業廃棄物で創出。極めて肥沃。',
         'Biochar soil amendment, carbon sequestration, sustainable agriculture.',
         '生物学','South_American_Ecology',-800,400,
         r'\text{Terra Preta: pH 5.5-7, C content >20\%, distinct microbial community}',
         'South_American',88,
         'https://en.wikipedia.org/wiki/Terra_preta',
         'テラプレタ,アマゾン,バイオチャー','terra_preta,biochar,Amazonian_agriculture,carbon',
         ''),

    make('nd_b_116','ミクログリアの機能','Microglial Function in Brain',
         'Rioの発見から進んだ脳内免疫細胞の研究。シナプス刈り込み(synapse pruning)で神経回路を形成。',
         'Alzheimer\'s disease, autism research, neuroinflammation targets.',
         '生物学','Neuroscience',1970,2010,
         r'\text{C1q opsonization}\to\text{microglia phagocytosis of synapses}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Microglia',
         'ミクログリア,シナプス刈り込み,神経免疫','microglia,synapse_pruning,neuroinflammation'),

    make('nd_b_117','島嶼生物地理学と保全','Island Biogeography and Conservation',
         'MacArthur-Wilson(1967)の確立。片道移入率=絶滅率で平衡種数が決まる。自然保護区設計に応用。',
         'Reserve design, corridor planning, fragmentation effects.',
         '生物学','Conservation_Biology',1967,1980,
         r'\hat{S}=CA^z;\;dS/dt=I(S)-E(S)','American_Science',90,
         'https://en.wikipedia.org/wiki/The_Theory_of_Island_Biogeography',
         '島嶼生物地理,MacArthur,Wilson,保全','island_biogeography,MacArthur_Wilson,reserve_design'),

    make('nd_b_118','ナノポア単一分子シーケンシング','Nanopore Single-Molecule Sequencing',
         'Oxford Nanopore(2014)が実用化。タンパク質ナノポアを通過する電流変化からDNA/RNA塩基を判読。',
         'Real-time sequencing, long reads, portable diagnostics.',
         '生物学','Genomics',2014,2020,
         r'I_{blockade}=I_0-\Delta I(base);\;\sigma_{ionic}\sim\kappa E','British_Science',90,
         'https://en.wikipedia.org/wiki/Nanopore_sequencing',
         'ナノポア,単一分子,ロングリード','nanopore,single-molecule,long_read,Oxford_Nanopore'),

    make('nd_b_119','メタゲノミクス','Metagenomics',
         'Handelsman(1998)が提唱。培養なしに環境サンプルから全ゲノムを一括解読する手法。',
         'Gut microbiome, ocean virome, soil biodiversity, pandemic surveillance.',
         '生物学','Genomics',1998,2010,
         r'N_{uniq\_genes}\propto\sqrt[k]{N_{reads}}\text{ (Heaps\'s law)}','American_Science',90,
         'https://en.wikipedia.org/wiki/Metagenomics',
         'メタゲノミクス,腸内細菌,環境DNA','metagenomics,microbiome,environmental_DNA,Handelsman'),

    make('nd_b_120','核-細胞質輸送','Nuclear-Cytoplasmic Transport',
         '核膜孔複合体(NPC)を介したタンパク質・RNA輸送。Ran-GTPaseがインポーチン/エキスポーチンを制御。',
         'Viral exploitation, cancer drug targets, cell differentiation.',
         '生物学','Cell_Biology',1985,2000,
         r'\Delta\mu_{Ran}=\mu_{Ran-GTP}^{nucleus}-\mu_{Ran-GDP}^{cytoplasm}',
         'American_British',82,
         'https://en.wikipedia.org/wiki/Nuclear_pore',
         '核膜孔,インポーチン,核輸送','nuclear_pore,importin,Ran_GTPase,nucleocytoplasmic'),
]

CONCEPTS = MATH + CHEM + BIO

def insert_batch(concepts):
    con = sqlite3.connect(DB)
    cur = con.cursor()
    cur.execute('SELECT LOWER(name_en) FROM natural_discovery')
    existing = {r[0] for r in cur.fetchall()}
    now = datetime.datetime.utcnow().isoformat()
    inserted = skipped = 0
    cols = ['id','name_ja','name_en','name_original','definition','impact_summary',
            'subfield','school_of_thought','era_start','era_end','methodology_level',
            'target_domain','application_conditions','when_to_apply','framing_questions',
            'opposing_concept_names','keywords_ja','keywords_en','status',
            'source_reliability','data_completeness','mathematical_formulation',
            'experimental_verification','applicable_scale','precision_level',
            'quality_flag','source_url','primary_source','primary_source_url',
            'primary_source_year','verification_status','culture_region',
            'culture_confidence','genealogy_narrative','narrative_word_count',
            'gta_l3','gta_l2','last_verified_at','redirect_to','http_status']
    placeholders = ','.join([f':{c}' for c in cols])
    sql = f"INSERT OR IGNORE INTO natural_discovery ({','.join(cols)},created_at,updated_at) VALUES ({placeholders},:created_at,:updated_at)"
    for c in concepts:
        if c['name_en'].lower() in existing:
            skipped += 1
            continue
        try:
            cur.execute(sql, {**c, 'created_at': now, 'updated_at': now})
            if cur.rowcount:
                inserted += 1
                existing.add(c['name_en'].lower())
        except Exception as e:
            print(f"ERROR {c['id']}: {e}")
    con.commit()
    cur.execute('SELECT COUNT(*) FROM natural_discovery')
    total = cur.fetchone()[0]
    con.close()
    return inserted, skipped, total

if __name__ == '__main__':
    ins, sk, total = insert_batch(CONCEPTS)
    print(f"挿入: {ins}, スキップ: {sk}, DB総件数: {total}")
