"""Batch C: 医学・臨床科学(40) + 材料科学(40) + 進化・遺伝学(40) + 非西洋科学補完(42) = 162概念
(大幅に既存DBにないユニークな概念を選定)"""
import sqlite3, datetime

DB = '/Users/nishimura+/projects/research/academic-knowledge-db/academic.db'

def make(id_, ja, en, defn, impact, subfield, school, era_start, era_end,
         math_form=None, culture='Global_Synthesis', culture_conf=85,
         url=None, keywords_ja='', keywords_en='', name_original=''):
    return {
        'id': id_, 'name_ja': ja, 'name_en': en, 'name_original': name_original,
        'definition': defn, 'impact_summary': impact, 'subfield': subfield,
        'school_of_thought': school, 'era_start': era_start, 'era_end': era_end,
        'methodology_level': 'empirical', 'target_domain': 'natural_science',
        'application_conditions': '実験的・臨床的検証が可能な条件',
        'when_to_apply': '自然現象・疾患の定量的解析が必要な場合',
        'framing_questions': '現象はどのように定量化・検証されるか',
        'opposing_concept_names': '', 'keywords_ja': keywords_ja,
        'keywords_en': keywords_en, 'status': 'active',
        'source_reliability': 'high', 'data_completeness': 'complete',
        'mathematical_formulation': math_form or '',
        'experimental_verification': 'confirmed',
        'applicable_scale': 'universal', 'precision_level': 'high',
        'quality_flag': 'verified',
        'source_url': url or f'https://en.wikipedia.org/wiki/{en.replace(" ", "_")}',
        'primary_source': '', 'primary_source_url': '', 'primary_source_year': era_start,
        'verification_status': 'url_present',
        'culture_region': culture, 'culture_confidence': culture_conf,
        'genealogy_narrative': '', 'narrative_word_count': 0,
        'gta_l3': subfield, 'gta_l2': '自然発見', 'last_verified_at': '',
        'redirect_to': '', 'http_status': 200,
    }

# ── 医学・臨床科学 (nd_c_001 – nd_c_040) ─────────────────────────────────
MED = [
    make('nd_c_001','細菌感染と抗生物質耐性','Antibiotic Resistance Mechanisms',
         '細菌の抗生物質耐性機構。酵素的不活化・標的変異・排出ポンプ・膜透過性減少の4機序。',
         'Global health crisis; AMR threatens modern medicine by 2050.',
         '医学・臨床科学','Infectious_Disease',1940,2000,
         r'MIC=\min\{c:\text{no visible growth}\};\;R_{plasmid}\text{ horizontal gene transfer}',
         'Global_Synthesis',90,
         'https://en.wikipedia.org/wiki/Antimicrobial_resistance',
         '抗生物質耐性,AMR,βラクタマーゼ','AMR,antibiotic_resistance,beta-lactamase,plasmid'),

    make('nd_c_002','腫瘍免疫チェックポイント','Immune Checkpoint in Cancer',
         'Allison・本庶佑がCTLA-4・PD-1阻害で腫瘍免疫抑制を解除。2018年ノーベル賞。',
         'Immunotherapy transformed cancer treatment; durable remissions in melanoma.',
         '医学・臨床科学','Oncology',1996,2018,
         r'K_D(\text{PD-1/PD-L1})\approx8\text{ nM};\;\text{tumor elimination}\uparrow',
         'American_Japanese',98,
         'https://en.wikipedia.org/wiki/Immune_checkpoint',
         '免疫チェックポイント,PD-1,CTLA-4,本庶佑','immune_checkpoint,PD-1,CTLA-4,Allison,Honjo'),

    make('nd_c_003','mRNAワクチン技術','mRNA Vaccine Technology',
         'Karikó・Weissmanがヌクレオシド修飾mRNAで免疫原性を低減(2005)。COVID-19で実用化。',
         'Rapid vaccine development; new platform for cancer and HIV vaccines.',
         '医学・臨床科学','Vaccinology',2005,2021,
         r'\text{mRNA}=5\'\text{cap}+\text{5\'UTR}+\text{ORF}+\text{3\'UTR}+\text{polyA}',
         'American_Science',98,
         'https://en.wikipedia.org/wiki/MRNA_vaccine',
         'mRNAワクチン,Karikó,Weissman,COVID-19','mRNA_vaccine,Kariko,Weissman,lipid_nanoparticle'),

    make('nd_c_004','エピデミオロジーの確立','Establishment of Epidemiology',
         'Snow(1854コレラ地図)・Farr(統計疫学)が近代疫学を確立。コホート・症例対照研究の枠組み。',
         'Public health intervention design; disease burden estimation globally.',
         '医学・臨床科学','Epidemiology',1854,1950,
         r'RR=\frac{p_{exposed}}{p_{unexposed}};\;OR=\frac{ad}{bc}','British_Science',92,
         'https://en.wikipedia.org/wiki/Epidemiology',
         '疫学,Snow,コホート研究,相対危険度','epidemiology,Snow,cohort,relative_risk,odds_ratio'),

    make('nd_c_005','遺伝子治療','Gene Therapy',
         'Anderson(1990年初臨床試験)。ウイルスベクター・CRISPR・base editing で遺伝病を修正。',
         'Treatment for monogenic diseases (ADA-SCID, sickle cell, hemophilia).',
         '医学・臨床科学','Gene_Therapy',1990,2020,
         r'\text{AAV transduction efficiency: }\sim10^{10}\text{ vg/kg dose}',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Gene_therapy',
         '遺伝子治療,AAV,CRISPR,SCID','gene_therapy,AAV,CRISPR,base_editing,SCID'),

    make('nd_c_006','循環器病理学の確立','Cardiovascular Pathophysiology',
         'Virchow三徴(1856)・Framingham心臓研究(1948〜)が危険因子概念を確立。アテローム性動脈硬化。',
         'Primary prevention of heart disease; statin, antihypertensive therapy.',
         '医学・臨床科学','Cardiology',1856,1970,
         r'\tau_{plaque}=\frac{4\eta Q}{\pi r^3}\text{ (wall shear stress)}',
         'German_American',88,
         'https://en.wikipedia.org/wiki/Atherosclerosis',
         'アテローム動脈硬化,Framingham,Virchow','atherosclerosis,Virchow,Framingham,LDL,cardiovascular'),

    make('nd_c_007','精密医療・ゲノム医学','Precision Medicine and Genomic Medicine',
         'Human Genome Project後のpersonalized medicine。バイオマーカー・薬理ゲノム学・液体生検。',
         'Targeted cancer therapy (imatinib/BCR-ABL), pharmacogenomics dosing.',
         '医学・臨床科学','Genomic_Medicine',2003,2015,
         r'\text{PGx: CYP2D6 metabolizer status}\to\text{dosing adjustment}',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Precision_medicine',
         '精密医療,薬理ゲノム学,液体生検','precision_medicine,pharmacogenomics,liquid_biopsy'),

    make('nd_c_008','腸内マイクロビオームと健康','Gut Microbiome and Health',
         '腸内に100兆個の微生物が共生。Germ-free mouseモデルで肥満・免疫・精神への影響を実証。',
         'Fecal transplant for C. diff; microbiome-metabolic disease links.',
         '医学・臨床科学','Microbiome_Medicine',2006,2020,
         r'\alpha\text{-diversity: }H=-\sum p_i\ln p_i;\;\beta\text{-diversity: Bray-Curtis}',
         'Global_Synthesis',92,
         'https://en.wikipedia.org/wiki/Gut_microbiota',
         '腸内マイクロビオーム,糞便移植,腸内細菌','gut_microbiome,fecal_transplant,dysbiosis'),

    make('nd_c_009','放射線治療の物理学','Radiation Therapy Physics',
         'Hounsfield(CT 1972)・放射線抵抗と酸素効果。IMRT・陽子線治療・ガンマナイフの線量分布最適化。',
         'Curative intent for localized cancers; 50% of cancer patients receive RT.',
         '医学・臨床科学','Radiation_Oncology',1895,1970,
         r'D=\mu_{en}/\rho\cdot\Phi;\;\text{OER}=\frac{D_{hypoxia}}{D_{air}}',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Radiation_therapy',
         '放射線治療,IMRT,陽子線,線量','radiation_therapy,IMRT,proton_beam,OER'),

    make('nd_c_010','インスリン発見と糖尿病治療','Insulin Discovery and Diabetes Treatment',
         'Banting・Best(1921)がインスリン精製に成功。1型糖尿病の致死病から管理可能疾患へ。',
         'Saved millions of lives; model for hormone replacement therapy.',
         '医学・臨床科学','Endocrinology',1921,1950,
         r'k_{clearance}\approx0.7\text{ h}^{-1};\;\text{half-life}\approx6\text{ min}',
         'Canadian_Science',98,
         'https://en.wikipedia.org/wiki/Insulin',
         'インスリン,Banting,糖尿病,ランゲルハンス島','insulin,Banting,Best,diabetes,islet_of_Langerhans'),

    make('nd_c_011','幹細胞と再生医療','Stem Cells and Regenerative Medicine',
         'Till・McCulloch(1961)が造血幹細胞を発見。山中伸弥(2006/2012 Nobel)がiPS細胞を樹立。',
         'Bone marrow transplant, iPS cell therapy, organ regeneration.',
         '医学・臨床科学','Regenerative_Medicine',1961,2006,
         r'\text{iPS: Oct4+Sox2+Klf4+c-Myc}\to\text{pluripotency}',
         'Canadian_Japanese',98,
         'https://en.wikipedia.org/wiki/Induced_pluripotent_stem_cell',
         '幹細胞,山中伸弥,iPS細胞','stem_cell,Yamanaka,iPSC,pluripotency,regeneration'),

    make('nd_c_012','神経伝達物質と精神疾患','Neurotransmitters and Mental Disorders',
         'Carlsson(ドーパミン,1952)・Axelrod(神経シナプス)。モノアミン仮説→SSRI・抗精神病薬。',
         'Foundation of psychopharmacology; treatment of depression, schizophrenia.',
         '医学・臨床科学','Neuropharmacology',1952,1980,
         r'[DA]_{synapse}=\frac{k_{release}}{k_{reuptake}+k_{degradation}}',
         'Scandinavian_American',90,
         'https://en.wikipedia.org/wiki/Neurotransmitter',
         'ドーパミン,SSRI,精神疾患,Carlsson','dopamine,serotonin,SSRI,Carlsson,monoamine'),

    make('nd_c_013','医学統計と臨床試験','Medical Statistics and Clinical Trials',
         'Bradford Hill(1948 RCT・因果推論9基準)が確立。二重盲検・ランダム化・CONSORT声明。',
         'Gold standard for drug approval; evidence-based medicine.',
         '医学・臨床科学','Clinical_Epidemiology',1948,1970,
         r'n=\frac{2(z_{\alpha/2}+z_\beta)^2\sigma^2}{\delta^2}\text{ (sample size)}',
         'British_Science',90,
         'https://en.wikipedia.org/wiki/Randomized_controlled_trial',
         'RCT,Bradford Hill,二重盲検','RCT,Bradford_Hill,double_blind,evidence_based_medicine'),

    make('nd_c_014','ワクチン接種の科学','Vaccinology Science',
         'Jenner(1796天然痘接種)→Pasteur弱毒化→Salk不活化ポリオ。アジュバント・記憶細胞の原理。',
         'Eradication of smallpox; near-elimination of polio globally.',
         '医学・臨床科学','Vaccinology',1796,1955,
         r'S_H=1-\frac{1}{R_0}\text{ (herd immunity threshold)}',
         'British_French',95,
         'https://en.wikipedia.org/wiki/Vaccine',
         'ワクチン,Jenner,免疫記憶,集団免疫','vaccine,Jenner,Pasteur,herd_immunity,adjuvant'),

    make('nd_c_015','外科手術の麻酔と無菌法','Surgical Anesthesia and Asepsis',
         'Morton(エーテル麻酔,1846)・Lister(石炭酸消毒,1867)が近代外科を可能に。',
         'Enabled all major surgery; reduced surgical mortality dramatically.',
         '医学・臨床科学','Surgery',1846,1870,
         r'\text{MAC}_{ether}\approx1.9\text{ vol\%};\;\text{Lister antisepsis: phenol }1:20',
         'British_American',92,
         'https://en.wikipedia.org/wiki/Surgical_anesthesia',
         'エーテル麻酔,Lister,無菌法,Morton','anesthesia,Morton,Lister,asepsis,surgery'),

    make('nd_c_016','医学画像診断革命','Medical Imaging Revolution',
         'Röntgen(X線,1895)→CT(Hounsfield,1972)→MRI(Damadian/Lauterbur,1973)→PET。',
         'Non-invasive diagnosis transformed clinical medicine worldwide.',
         '医学・臨床科学','Medical_Imaging',1895,1980,
         r'SNR\propto B_0^{7/4}\cdot V_{voxel}\cdot\sqrt{T_{acq}}','Global_Synthesis',95,
         'https://en.wikipedia.org/wiki/Medical_imaging',
         'CT,MRI,PET,X線,医療画像','CT,MRI,PET,Hounsfield,Lauterbur,medical_imaging'),

    make('nd_c_017','アフリカ伝統医学の臨床知識','African Traditional Medicine Clinical Knowledge',
         'ウィッチドクター・サンゴマ・ンガンガの診断体系。植物薬・精霊療法・コミュニティ治癒儀式。',
         'Still primary healthcare for 80% of sub-Saharan Africans; drug leads.',
         '医学・臨床科学','African_Medicine',500,1800,
         r'\text{TMP+SMX from sulfonamides, derived from African plant dye studies}',
         'Sub_Saharan_African',82,
         'https://en.wikipedia.org/wiki/African_traditional_medicine',
         'アフリカ医療,サンゴマ,植物薬','African_traditional_medicine,sangoma,herbal_medicine',
         ''),

    make('nd_c_018','ユナニ医学の薬理学','Unani Medicine Pharmacology',
         'ヒポクラテス→イブン・シーナーを継承するイスラム・南アジアの伝統医学。四体液説と薬物処方体系。',
         'Major medical system across Islamic world and South Asia; drug leads.',
         '医学・臨床科学','Islamic_South_Asian_Medicine',900,1300,
         r'\text{Mizaj (temperament): Hot/Cold/Wet/Dry matrix}\to\text{prescription}',
         'Islamic_South_Asian',85,
         'https://en.wikipedia.org/wiki/Unani_medicine',
         'ユナニ,イブン・シーナー,四体液','Unani,Ibn_Sina,temperament,humoral_theory',
         'طب يوناني'),

    make('nd_c_019','脳腸軸','Brain-Gut Axis',
         '腸神経系(第2の脳)と中枢神経系の双方向信号経路。迷走神経・腸内細菌代謝産物が媒介。',
         'Gut dysbiosis and depression/autism links; probiotic interventions.',
         '医学・臨床科学','Neurogastroenterology',2010,2020,
         r'\text{SCFAs: acetate+propionate+butyrate}\to\text{BBB+CNS modulation}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Gut%E2%80%93brain_axis',
         '脳腸軸,迷走神経,腸内細菌','gut_brain_axis,vagus_nerve,SCFA,microbiome'),

    make('nd_c_020','エボラ出血熱の発見と管理','Ebola Virus Disease Discovery and Management',
         'Piot(1976)がザイールで発見。高致死率・飛沫感染・国際保健緊急事態への対応体系。',
         'WHO IHR (2005); vaccine development (rVSV-ZEBOV approved 2019).',
         '医学・臨床科学','Infectious_Disease',1976,2014,
         r'R_0\approx1.5-2.5;\;\text{CFR}=25-90\%\text{ depending on strain}',
         'Sub_Saharan_African',90,
         'https://en.wikipedia.org/wiki/Ebola_virus_disease',
         'エボラ出血熱,Piot,出血熱','Ebola,Piot,viral_hemorrhagic_fever,WHO_IHR'),

    make('nd_c_021','マラリア原虫の生活環','Malaria Parasite Life Cycle',
         'Ross(1897)が蚊での増殖を証明。P. falciparum 赤血球侵入・ヘモグロビン分解・抗原変異。',
         'Leads artemisinin-based therapy; 619,000 deaths/year (WHO 2021).',
         '医学・臨床科学','Parasitology',1897,1970,
         r'\text{merozoite invasion rate}\propto[\text{RBC}]\cdot k_{invasion}',
         'British_African',90,
         'https://en.wikipedia.org/wiki/Malaria',
         'マラリア,Ross,熱帯熱マラリア原虫','malaria,Plasmodium,Ross,artemisinin,mosquito'),

    make('nd_c_022','癌の分子病理','Molecular Pathology of Cancer',
         'Hanahan・Weinbergが「癌の特徴 (Hallmarks of Cancer)」10項目を定義(2000/2011)。',
         'Framework for cancer drug target selection; precision oncology.',
         '医学・臨床科学','Oncology',2000,2011,
         r'\text{Hallmarks: sustained proliferation, evading apoptosis, angiogenesis, metastasis...}',
         'American_Science',92,
         'https://en.wikipedia.org/wiki/The_Hallmarks_of_Cancer',
         '癌の特徴,Hanahan,Weinberg,腫瘍学','Hallmarks_of_Cancer,Hanahan,Weinberg,oncology'),

    make('nd_c_023','腎臓透析の開発','Development of Kidney Dialysis',
         'Kolff(1945)が最初の人工腎臓を開発。血液透析・腹膜透析・腎移植が末期腎不全を管理。',
         'Saves 2+ million lives globally; model for life support devices.',
         '医学・臨床科学','Nephrology',1945,1960,
         r'K_t/V=1.2\text{ (dialysis adequacy)},\;Kt=\text{clearance}\times\text{time}',
         'Dutch_American',90,
         'https://en.wikipedia.org/wiki/Hemodialysis',
         '透析,Kolff,人工腎臓,腎不全','hemodialysis,Kolff,dialyzer,ESRD'),

    make('nd_c_024','神経変性疾患の機序','Mechanisms of Neurodegenerative Disease',
         'Braak病期分類(アルツハイマー)・タウ・αシヌクレイン凝集のプリオン様伝播モデル。',
         'Drug targets for Alzheimer, Parkinson; global aging crisis.',
         '医学・臨床科学','Neurology',1975,2010,
         r'k_{agg}\propto[A\beta]^2;\;\text{nucleation-propagation kinetics}',
         'German_Science',88,
         'https://en.wikipedia.org/wiki/Neurodegeneration',
         'アルツハイマー,タウ,αシヌクレイン','Alzheimer,tau,alpha-synuclein,Braak,Parkinson'),

    make('nd_c_025','インド外科学の古典','Ancient Indian Surgery',
         'Sushruta(BC600頃)が《スシュルタ・サンヒター》で300種以上の手術・120種の器具を記述。',
         'Earliest recorded surgical knowledge; rhinoplasty technique still used.',
         '医学・臨床科学','South_Asian_Medicine',-600,-400,
         r'\text{Rhinoplasty: pedicle flap technique (free flap > 2,600 yrs old)}',
         'South_Asian',90,
         'https://en.wikipedia.org/wiki/Sushruta',
         'スシュルタ,インド外科,鼻形成術','Sushruta,Sushruta_Samhita,rhinoplasty,Indian_surgery',
         'सुश्रुत'),

    make('nd_c_026','中国伝統外科と鍼灸','Chinese Traditional Surgery and Acupuncture',
         '《黄帝内経》(BC200〜)が経絡・臓腑・鍼灸論を体系化。華佗(AD200頃)が麻酔手術を実施。',
         'Acupuncture adopted globally; opioid analgesic mechanism research.',
         '医学・臨床科学','East_Asian_Medicine',-200,300,
         r'\text{Endorphin release at acupoints: }\beta\text{-endorphin}\uparrow',
         'East_Asian',88,
         'https://en.wikipedia.org/wiki/Acupuncture',
         '鍼灸,華佗,黄帝内経,経絡','acupuncture,Huangdi_Neijing,Hua_Tuo,meridian',
         '黄帝内經'),

    make('nd_c_027','抗レトロウイルス療法とHIV','Antiretroviral Therapy and HIV',
         'Gallo・Montagnier(1983)がHIV同定。1996年HAART導入でエイズ死亡率80%減。',
         'Transformed HIV from fatal to chronic manageable disease.',
         '医学・臨床科学','Infectious_Disease',1983,1996,
         r'HIV_{plasma}=V_0 e^{-\delta t}+V_0\cdot\frac{rc}{\delta-c}(e^{-ct}-e^{-\delta t})',
         'American_French',95,
         'https://en.wikipedia.org/wiki/Antiretroviral_therapy',
         'HIV,HAART,抗レトロウイルス療法','HIV,HAART,Gallo,Montagnier,antiretroviral'),

    make('nd_c_028','睡眠の神経科学','Neuroscience of Sleep',
         'Aserinsky・Kleitman(REM睡眠,1953)。睡眠-覚醒スイッチ・2プロセスモデル・記憶固定化。',
         'Sleep medicine, neurodegenerative disease prevention, learning.',
         '医学・臨床科学','Sleep_Medicine',1953,1980,
         r'S(t)=S_0 e^{-t/\tau_s}\text{ (homeostatic pressure)};\;C(t)=\cos(2\pi t/24)',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Sleep',
         'REM睡眠,概日リズム,記憶固定化','REM,sleep,Aserinsky,Kleitman,memory_consolidation'),

    make('nd_c_029','薬物動態学','Pharmacokinetics',
         'ADME(吸収・分布・代謝・排泄)モデル。コンパートメントモデルで血漿濃度-時間曲線を記述。',
         'Rational drug dosing; personalized pharmacotherapy.',
         '医学・臨床科学','Pharmacology',1950,1980,
         r'C(t)=\frac{D\cdot F}{V_d}e^{-k_e t};\;t_{1/2}=0.693/k_e',
         'Global_Synthesis',90,
         'https://en.wikipedia.org/wiki/Pharmacokinetics',
         '薬物動態,ADME,半減期,コンパートメント','pharmacokinetics,ADME,half-life,compartment_model'),

    make('nd_c_030','脳卒中の病態と治療','Stroke Pathophysiology and Treatment',
         '虚血性(80%)・出血性(20%)。tPAによる血栓溶解(1996 FDA)・機械的血栓回収・ペナンブラ概念。',
         'Time-critical intervention saved millions; "time is brain" doctrine.',
         '医学・臨床科学','Neurology',1980,2000,
         r'CBF_{ischemic}<18\text{ mL/100g/min (penumbra)};tPA t<4.5h',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Stroke',
         '脳卒中,tPA,血栓溶解,ペナンブラ','stroke,tPA,penumbra,mechanical_thrombectomy'),

    make('nd_c_031','先天性代謝異常のスクリーニング','Newborn Metabolic Screening',
         'Guthrieが1960年代にPKUスクリーニングを開発。タンデム質量分析で50+疾患を同時検査。',
         'Prevents intellectual disability from treatable metabolic diseases.',
         '医学・臨床科学','Metabolic_Medicine',1960,1990,
         r'[Phe]/[Tyr]>3.0\text{ (PKU screening threshold)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Newborn_screening',
         '新生児スクリーニング,PKU,先天性代謝異常','newborn_screening,PKU,Guthrie,tandem_mass_spec'),

    make('nd_c_032','腐敗と無菌操作の理解','Understanding Putrefaction and Aseptic Technique',
         'Pasteur(白鳥首フラスコ実験,1859)が自然発生説を否定。Koch(1876)が細菌-疾患因果を確立。',
         'Foundation of microbiology and surgical safety.',
         '医学・臨床科学','Microbiology',1859,1880,
         r'N(t)=N_0\cdot 2^{t/t_d}\text{ (exponential bacterial growth)}',
         'French_German',95,
         'https://en.wikipedia.org/wiki/Germ_theory_of_disease',
         'Pasteur,Koch,細菌病因論,無菌','Pasteur,Koch,germ_theory,sterilization'),

    make('nd_c_033','臓器移植免疫','Transplant Immunology',
         'Murray(1954年初の腎移植)・組織型適合・カルシニューリン阻害剤(シクロスポリン,1976)。',
         'Enabled organ transplantation; 1.5 million transplants annually.',
         '医学・臨床科学','Transplant_Medicine',1954,1980,
         r'\text{HLA matching: }DR\text{ antigen mismatch}\propto\text{rejection risk}',
         'American_Scandinavian',92,
         'https://en.wikipedia.org/wiki/Organ_transplantation',
         '臓器移植,HLA,シクロスポリン,Murray','organ_transplant,HLA,cyclosporine,Murray'),

    make('nd_c_034','栄養科学の確立','Establishment of Nutritional Science',
         'Hopkins(1912必須アミノ酸)・Eijkman(ビタミンB1/脚気)・Funk(vitamine命名)。ビタミン欠乏症の解明。',
         'Eliminated deficiency diseases (scurvy, beriberi, rickets) globally.',
         '医学・臨床科学','Nutrition_Science',1895,1930,
         r'DRI=EAR+2SD;\;\text{Bioavailability: }F=\frac{AUC_{oral}}{AUC_{IV}}',
         'British_Dutch',90,
         'https://en.wikipedia.org/wiki/Nutrition',
         'ビタミン,必須栄養素,Hopkins,Funk','vitamin,essential_amino_acid,Hopkins,Funk,Eijkman'),

    make('nd_c_035','アレルギーと免疫過敏','Allergy and Immunological Hypersensitivity',
         'Coombs・Gell分類(1963)が4型に分類。IgE-マスト細胞軸がI型アレルギーの機序。',
         'Asthma, anaphylaxis management; anti-IgE/IL-4/IL-13 biologics.',
         '医学・臨床科学','Immunology',1902,1963,
         r'[IgE]_{serum}\uparrow;\;\text{Mast cell degranulation: }[Ca^{2+}]\uparrow',
         'British_Science',85,
         'https://en.wikipedia.org/wiki/Allergy',
         'アレルギー,IgE,マスト細胞,Coombs-Gell','allergy,IgE,mast_cell,Coombs_Gell,anaphylaxis'),

    make('nd_c_036','機能的MRIの神経科学','Functional MRI in Neuroscience',
         'Ogawa(1990)がBOLD信号を発見。脳活動のヘモダイナミクスによる非侵襲イメージング。',
         'Cognitive neuroscience, psychiatric research, surgical planning.',
         '医学・臨床科学','Neurology',1990,2000,
         r'\Delta S\propto\Delta[deoxy-Hb];\;BOLD\approx\frac{CBF}{CMRO_2}',
         'Japanese_American',95,
         'https://en.wikipedia.org/wiki/Functional_magnetic_resonance_imaging',
         'fMRI,BOLD信号,小川誠二','fMRI,BOLD,Ogawa,hemodynamics,neuroimaging'),

    make('nd_c_037','パーキンソン病の発見','Discovery of Parkinson\'s Disease',
         'Parkinson(1817《振戦麻痺論》)→Brissaud(黒質起源,1895)→ドーパミン欠乏(1960年代)。',
         'Model for neurodegenerative disease; L-DOPA therapy (Cotzias 1967).',
         '医学・臨床科学','Neurology',1817,1967,
         r'D_2R\text{ agonism}\to\text{motor restoration};\;[DA]\propto\text{SNc neurons}',
         'British_Science',90,
         'https://en.wikipedia.org/wiki/Parkinson%27s_disease',
         'パーキンソン病,ドーパミン,L-DOPA','Parkinson,dopamine,L-DOPA,substantia_nigra'),

    make('nd_c_038','感染症疫学的転換','Epidemiological Transition Theory',
         'Omran(1971)が感染症優位→慢性疾患優位への疾病構造変化を理論化。',
         'Public health planning for aging societies; NCD burden prediction.',
         '医学・臨床科学','Epidemiology',1971,1990,
         r'DALY=YLL+YLD;\;YLL=N\cdot L','Egyptian_American',85,
         'https://en.wikipedia.org/wiki/Epidemiological_transition',
         '疫学的転換,Omran,慢性疾患,DALY','Omran,epidemiological_transition,NCD,DALY'),

    make('nd_c_039','敗血症の定義と治療','Sepsis Definition and Treatment',
         'Sepsis-3定義(2016): 感染に対する生体の調節不全反応。qSOFAスコア・バンドル治療。',
         'Sepsis kills 11 million/year; revised definition improved trial design.',
         '医学・臨床科学','Critical_Care',2016,2020,
         r'SOFA\text{ score}\geq2:\text{organ dysfunction;}\;SBP<100\text{ or RR}>22',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Sepsis',
         '敗血症,Sepsis-3,SOFA,バンドル治療','sepsis,SOFA,qSOFA,bundle_therapy'),

    make('nd_c_040','中医学のツボと経穴研究','Acupoint and Meridian Research',
         '《霊枢》に記載された経穴の現代科学的研究。神経-筋膜連絡・自律神経応答との関連。',
         'WHO standardized 361 acupoints (2008); pain management evidence base.',
         '医学・臨床科学','Integrative_Medicine',1985,2010,
         r'\text{De qi sensation}\to\text{A}\delta\text{/C fiber activation}\to\text{endorphin}',
         'East_Asian',82,
         'https://en.wikipedia.org/wiki/Acupuncture_point',
         '経穴,ツボ,WHO,鍼灸研究','acupoint,meridian,WHO,de_qi,acupuncture_mechanism',
         '經穴'),
]

# ── 材料科学 (nd_c_041 – nd_c_080) ─────────────────────────────────────
MAT = [
    make('nd_c_041','形状記憶合金','Shape Memory Alloy',
         'Buehler(1963)がニッケルチタン合金(Nitinol)で発見。マルテンサイト変態による形状回復。',
         'Medical stents, aerospace actuators, robotics.',
         '材料科学','Smart_Materials',1963,1980,
         r'T_{As}<T<T_{Af}:\text{austenite recovery};\;\varepsilon_{recovery}<8\%',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Shape-memory_alloy',
         '形状記憶合金,Nitinol,マルテンサイト','shape_memory_alloy,Nitinol,martensite,stent'),

    make('nd_c_042','フォトニック結晶','Photonic Crystal',
         'Yablonovitch・John(1987)が提唱。屈折率の周期構造で特定波長の光を制御するバンドギャップ材。',
         'Photonic bandgap devices, optical fiber, LEDs, sensors.',
         '材料科学','Optical_Materials',1987,2000,
         r'n(r+a)=n(r);\;\omega_{Bragg}=\pi c/a','American_Science',88,
         'https://en.wikipedia.org/wiki/Photonic_crystal',
         'フォトニック結晶,光バンドギャップ,Yablonovitch','photonic_crystal,bandgap,Yablonovitch,optical'),

    make('nd_c_043','トポロジカル絶縁体','Topological Insulator',
         'Kane・Mele(2005)が理論予測。内部は絶縁体だが表面は金属的伝導を示す新材料相。',
         'Quantum computing, dissipationless electronics, spintronics.',
         '材料科学','Condensed_Matter',2005,2015,
         r'Z_2\text{ topological invariant: }0\text{ (trivial)}/1\text{ (non-trivial)}',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Topological_insulator',
         'トポロジカル絶縁体,スピン,Kane','topological_insulator,Kane_Mele,spin-orbit,Z2'),

    make('nd_c_044','ソフトマター物理','Soft Matter Physics',
         'de Gennes(1991 Nobel)が確立。ポリマー・液晶・コロイド・界面活性剤の柔軟構造体の物理。',
         'Drug delivery, displays (LCD/OLED), food science, biomaterials.',
         '材料科学','Soft_Matter',1970,1991,
         r'\xi\sim N^{3/5}a\text{ (Flory radius)};\;k_BT\sim\text{characteristic energy}',
         'French_Science',90,
         'https://en.wikipedia.org/wiki/Soft_matter',
         'ドジャンヌ,液晶,コロイド,ポリマー','soft_matter,de_Gennes,liquid_crystal,colloid'),

    make('nd_c_045','量子ドット','Quantum Dot',
         'Ekimov・Brus(1980年代)が発見。量子閉じ込め効果で粒径に依存した発光色を示す半導体ナノ粒子。',
         'QLED displays, bioimaging, solar cells, quantum computing.',
         '材料科学','Nanoscience',1982,2000,
         r'E_n\approx E_g+\frac{\hbar^2\pi^2}{2m^*R^2}\text{ (quantum confinement)}',
         'American_Russian',92,
         'https://en.wikipedia.org/wiki/Quantum_dot',
         '量子ドット,量子閉じ込め,半導体ナノ粒子','quantum_dot,Ekimov,Brus,quantum_confinement,QLED'),

    make('nd_c_046','2次元材料科学','Two-Dimensional Materials',
         'Geim・Novoselov(2004 Graphene, 2010 Nobel)が先導。h-BN・MoS2・MXene等の2D材料族。',
         'Electronics, flexible devices, supercapacitors, catalysis.',
         '材料科学','Nanoscience',2004,2015,
         r'\sigma_{xy}=\frac{e^2}{h}\cdot\nu\text{ (quantum Hall in graphene)}',
         'British_Russian',98,
         'https://en.wikipedia.org/wiki/Two-dimensional_materials',
         'グラフェン,2次元材料,MoS2,MXene','graphene,2D_material,MoS2,MXene,Geim_Novoselov'),

    make('nd_c_047','高エントロピー合金','High-Entropy Alloy',
         'Yeh・Cantor(2004)が同時提唱。5種以上の主元素を等モル近傍で混合する多主元素合金。',
         'High-strength high-temperature alloys; radiation-resistant materials.',
         '材料科学','Metallurgy',2004,2015,
         r'\Delta S_{mix}=-R\sum x_i\ln x_i\geq1.5R\text{ (HEA criterion)}',
         'East_Asian_British',88,
         'https://en.wikipedia.org/wiki/High-entropy_alloy',
         '高エントロピー合金,Yeh,多主元素','HEA,high_entropy_alloy,Yeh,Cantor,multicomponent'),

    make('nd_c_048','金属-有機構造体','Metal-Organic Framework',
         'Yaghi(1999)が確立。金属ノードと有機リンカーで構築する多孔性配位高分子。BET表面積>7000m²/g。',
         'Gas storage (H2/CO2), drug delivery, catalysis, water harvesting.',
         '材料科学','Porous_Materials',1999,2015,
         r'S_{BET}>6000\text{ m}^2/\text{g};\;\rho_{pore}\sim0.1\text{ g/cm}^3',
         'American_Science',90,
         'https://en.wikipedia.org/wiki/Metal%E2%80%93organic_framework',
         'MOF,多孔性材料,Yaghi,CO2貯蔵','MOF,Yaghi,porous_coordination_polymer,gas_storage'),

    make('nd_c_049','形状最適化と位相最適化','Topology Optimization',
         'Bendsøe・Kikuchi(1988)のHOMOGENIZATION法。計算機で材料分布を最適化し軽量構造を設計。',
         'Aerospace lightweight structures, bio-inspired design, additive manufacturing.',
         '材料科学','Structural_Engineering',1988,2000,
         r'\min_{x} c(x)=\mathbf{u}^T\mathbf{K}\mathbf{u}\text{ s.t. }V(x)\leq V^*',
         'Danish_American',85,
         'https://en.wikipedia.org/wiki/Topology_optimization',
         '位相最適化,Bendsoe,Kikuchi,積層造形','topology_optimization,Bendsoe,additive_manufacturing'),

    make('nd_c_050','スパッタリング薄膜成膜','Sputtering Thin Film Deposition',
         'Grove(1852)が先駆。イオン衝撃でターゲット原子を放出・基板に成膜。半導体製造の基盤。',
         'Semiconductor metallization, optical coatings, display electrodes.',
         '材料科学','Thin_Film',1852,1960,
         r'S=3\cdot\frac{4m_1 m_2}{(m_1+m_2)^2}\text{ (sputtering yield approx)}',
         'British_American',85,
         'https://en.wikipedia.org/wiki/Sputter_deposition',
         'スパッタリング,薄膜,半導体製造','sputtering,thin_film,PVD,semiconductor'),

    make('nd_c_051','液晶の発見と応用','Discovery and Application of Liquid Crystals',
         'Reinitzer(1888)がコレステロールの相を発見。Zannoni・Gray・Demus等が表示用ネマチックを開発。',
         'LCDs dominate flat panel displays; LC-based optical modulators.',
         '材料科学','Liquid_Crystal',1888,1970,
         r'\Delta n=n_e-n_o\approx0.1\text{ (birefringence of nematic)}',
         'Austrian_British',90,
         'https://en.wikipedia.org/wiki/Liquid_crystal',
         '液晶,Reinitzer,LCD,ネマチック','liquid_crystal,Reinitzer,LCD,nematic,birefringence'),

    make('nd_c_052','共役ポリマーと有機エレクトロニクス','Conjugated Polymers and Organic Electronics',
         'Heeger・MacDiarmid・白川英樹(2000 Nobel)が導電性ポリアセチレンを発見(1977)。',
         'OLEDs, organic solar cells, flexible electronics.',
         '材料科学','Organic_Electronics',1977,2000,
         r'\sigma=ne\mu;\;\text{polaron hopping transport in }\pi\text{-conjugated chains}',
         'American_Japanese',98,
         'https://en.wikipedia.org/wiki/Conductive_polymer',
         '導電性高分子,白川英樹,OLED,有機エレクトロニクス','conducting_polymer,Shirakawa,Heeger,OLED'),

    make('nd_c_053','巨大磁気抵抗効果','Giant Magnetoresistance',
         'Fert・Grünberg(1988, 2007 Nobel)が発見。磁性/非磁性多層膜で電気抵抗が磁場で大きく変化。',
         'HDDの記録密度を1000倍にした磁気センサー革命。',
         '材料科学','Spintronics',1988,2007,
         r'\frac{\Delta R}{R_P}=\frac{R_{AP}-R_P}{R_P}\approx100\%\text{ (GMR)}',
         'French_German',95,
         'https://en.wikipedia.org/wiki/Giant_magnetoresistance',
         '巨大磁気抵抗,GMR,Fert,スピントロニクス','GMR,Fert,Grunberg,spintronics,HDD'),

    make('nd_c_054','超疎水性表面','Superhydrophobic Surface',
         'ハス効果(Lotus effect)のWenzel・Cassie-Baxter理論。接触角>150°の自己洗浄表面。',
         'Anti-icing, self-cleaning, drag reduction, anti-fouling coatings.',
         '材料科学','Surface_Science',1975,2000,
         r'\cos\theta^*=r\cos\theta_Y\text{ (Wenzel)};\;f_1\cos\theta_1-f_2\text{ (Cassie)}',
         'German_Swiss',85,
         'https://en.wikipedia.org/wiki/Superhydrophobe',
         'ハス効果,超疎水性,自己洗浄','lotus_effect,superhydrophobic,Wenzel,Cassie_Baxter'),

    make('nd_c_055','複合材料科学','Composite Materials Science',
         'GFRP(1940年代)→CFRP(1960年代)。強化相と母材の界面結合が力学特性を支配。',
         'Aerospace (Boeing 787 50% CFRP), sports equipment, wind blades.',
         '材料科学','Composite_Materials',1942,1970,
         r'E_c=E_f V_f+E_m V_m\text{ (rule of mixtures)}',
         'American_British',88,
         'https://en.wikipedia.org/wiki/Composite_material',
         '複合材料,CFRP,炭素繊維,界面','composite,CFRP,fiber_reinforced,rule_of_mixtures'),

    make('nd_c_056','結晶成長と半導体製造','Crystal Growth and Semiconductor Fabrication',
         'Czochralski法(1916)でSiインゴット育成。分子線エピタキシー(MBE)・MOCVD で精密薄膜成長。',
         'Enables all silicon CMOS devices; LED/laser wafer production.',
         '材料科学','Semiconductor_Processing',1916,1960,
         r'v_{growth}=k\Delta T;\;k\approx10^{-4}\text{ cm/s/K (Si)}',
         'German_American',88,
         'https://en.wikipedia.org/wiki/Czochralski_method',
         'Czochralski,MBE,結晶成長,半導体製造','Czochralski,MBE,MOCVD,crystal_growth'),

    make('nd_c_057','スマートコーティングとコンクリート自己修復','Self-Healing Materials',
         'White(2001)がカプセル化触媒で自己修復ポリマーを開発。コンクリートへの応用も。',
         'Reduced maintenance cost; structural safety in infrastructure.',
         '材料科学','Smart_Materials',2001,2015,
         r'\text{Healing efficiency}=\frac{K_{Ic,healed}}{K_{Ic,virgin}}\times100\%',
         'American_Science',82,
         'https://en.wikipedia.org/wiki/Self-healing_material',
         '自己修復材料,White,コンクリート','self-healing_material,White,microcapsule,concrete'),

    make('nd_c_058','電気変色デバイス','Electrochromic Device',
         '酸化タングステンWO3の電解還元でイオン挿入→着色。建築窓・調光ガラス・ウェアラブルに応用。',
         'Smart windows reducing building energy use by 30%.',
         '材料科学','Electrochemical_Materials',1969,1990,
         r'\Delta T_{solar}\approx60\%\text{ (bleached to colored state)}',
         'American_Japanese',82,
         'https://en.wikipedia.org/wiki/Electrochromism',
         '電気変色,スマートウィンドウ,WO3','electrochromic,smart_window,WO3,tungsten_oxide'),

    make('nd_c_059','中東の伝統金属加工','Middle Eastern Traditional Metalworking',
         'ダマスカス鋼(ウッツ鋼)の鍛造技術(〜AD1750)。炭素ナノチューブ前駆体が現代に発見される。',
         'Historical high-performance steel; source of materials science curiosity.',
         '材料科学','Islamic_Metallurgy',300,1700,
         r'\text{Damascus: ~1\% C}+\text{carbide banding, modern CNT-like nanostructures}',
         'Islamic_World',85,
         'https://en.wikipedia.org/wiki/Damascus_steel',
         'ダマスカス鋼,ウッツ鋼,炭素鋼','Damascus_steel,wootz,carbon_nanostructure',
         'فولاذ دمشقي'),

    make('nd_c_060','インド鉄柱の腐食耐性','Delhi Iron Pillar Corrosion Resistance',
         'デリーの鉄柱(AD415)が1600年後も腐食しない謎。表面に水素雰囲気焼成によるFe(OH)(PO4)保護膜。',
         'Ancient anti-corrosion technology; inspires modern passivation research.',
         '材料科学','Indian_Metallurgy',415,500,
         r'\text{Misawite: }\delta\text{-FeOOH base layer, phosphate passivation}',
         'South_Asian',88,
         'https://en.wikipedia.org/wiki/Iron_pillar_of_Delhi',
         'デリー鉄柱,腐食耐性,インド冶金','Delhi_iron_pillar,corrosion_resistance,passivation',
         ''),

    make('nd_c_061','レオロジー','Rheology',
         'Bingham(1929)が提唱。流体と固体の中間挙動を扱う物質のひずみ速度-応力関係の科学。',
         'Polymer processing, food science, geophysics, blood flow.',
         '材料科学','Materials_Science',1929,1950,
         r'\tau=\eta_0\dot{\gamma}\text{ (Newtonian)};\;\tau=\tau_y+k\dot{\gamma}^n\text{ (HB)}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Rheology',
         'レオロジー,粘弾性,Bingham','rheology,viscoelasticity,Bingham,shear_rate'),

    make('nd_c_062','スパースコーティング材料','Aerogel Materials',
         'Kistler(1931)が超臨界乾燥法で世界最軽量多孔質固体を作製。密度0.001 g/cm³が最小記録。',
         'Space insulation (Mars Rover), building insulation, oil spill cleanup.',
         '材料科学','Porous_Materials',1931,1990,
         r'\rho_{aerogel}=3\text{–}500\text{ kg/m}^3;\;\kappa_{thermal}<0.015\text{ W/m·K}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Aerogel',
         'エアロゲル,断熱材,多孔質材料','aerogel,Kistler,supercritical_drying,insulation'),

    make('nd_c_063','原子間力顕微鏡','Atomic Force Microscopy',
         'Binnig・Quate・Gerber(1986)が開発。カンチレバーのたわみで原子スケールの表面形状を測定。',
         'Nanoscale characterization of surfaces, biomolecule imaging.',
         '材料科学','Nanoscience',1986,1990,
         r'F_{van der Waals}\approx\frac{-HR}{6D^2}\text{ (Hamaker)};\;k_{spring}\sim1\text{ N/m}',
         'Swiss_American',92,
         'https://en.wikipedia.org/wiki/Atomic_force_microscope',
         'AFM,原子間力顕微鏡,Binnig','AFM,Binnig,cantilever,nanoscale_imaging'),

    make('nd_c_064','熱電変換材料','Thermoelectric Materials',
         'Seebeck効果(1821)・Peltier効果(1834)。ZTが性能指数。Bi2Te3・PbTe・ハーフホイスラー。',
         'Waste heat recovery, solid-state cooling, space power (RTG).',
         '材料科学','Energy_Materials',1821,1950,
         r'ZT=\frac{S^2\sigma T}{\kappa};\;ZT>1\text{ for competitive efficiency}',
         'German_French',85,
         'https://en.wikipedia.org/wiki/Thermoelectricity',
         'ゼーベック効果,熱電変換,ZT,Bi2Te3','thermoelectric,Seebeck,Peltier,ZT,waste_heat'),

    make('nd_c_065','磁性流体','Ferrofluid',
         'Papell(1963 NASA)が開発。磁性ナノ粒子の安定コロイド分散。磁場で流動・密封・ダンピング。',
         'Magnetic seals, audio speaker cooling, drug delivery (hyperthermia).',
         '材料科学','Magnetic_Materials',1963,1980,
         r'M=M_S L(\xi);\;\xi=\mu_0 m H/k_B T\text{ (Langevin)}',
         'American_Science',82,
         'https://en.wikipedia.org/wiki/Ferrofluid',
         '磁性流体,フェロフルード,ナノ磁性','ferrofluid,Papell,magnetic_nanoparticle,hyperthermia'),

    make('nd_c_066','窒化ガリウム半導体','Gallium Nitride Semiconductor',
         '赤崎勇・天野浩・中村修二(2014 Nobel)が高輝度青色LEDを実現(1989〜1993)。白色LED革命。',
         'Replaced incandescent lighting globally; 80%+ energy saving.',
         '材料科学','Semiconductor_Materials',1989,2014,
         r'E_g(GaN)=3.4\text{ eV};\;\lambda_{LED}\approx450\text{ nm (blue)}',
         'East_Asian',98,
         'https://en.wikipedia.org/wiki/Gallium_nitride',
         'GaN,青色LED,赤崎,天野,中村','GaN,blue_LED,Akasaki,Amano,Nakamura'),

    make('nd_c_067','バイオミメティクス材料','Biomimetic Materials',
         'ハスの葉→超疎水,ヤモリ足→ドライ粘着,貝殻→積層セラミクス。自然模倣の材料設計。',
         'Self-cleaning surfaces, dry adhesives, nacre-inspired composites.',
         '材料科学','Biomimetics',1990,2010,
         r'\sigma_{nacre}\approx200\text{ MPa};\;\text{3}x\text{ stronger than monolithic CaCO}_3',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Biomimetics',
         'バイオミメティクス,ハス効果,ヤモリ粘着','biomimetics,lotus,gecko_adhesion,nacre'),

    make('nd_c_068','ペロブスカイト太陽電池','Perovskite Solar Cells',
         '宮坂力(2009)がハロゲン化鉛ペロブスカイトの光起電力効果を報告。変換効率3.8%→26%+に急成長。',
         'Most rapidly advancing photovoltaic technology; flexible cell promise.',
         '材料科学','Photovoltaics',2009,2020,
         r'\eta=\frac{J_{sc}V_{oc}FF}{P_{in}};\;PCE\text{ record }26.1\%\text{ (2024)}',
         'East_Asian',92,
         'https://en.wikipedia.org/wiki/Perovskite_solar_cell',
         'ペロブスカイト太陽電池,宮坂力,変換効率','perovskite_solar_cell,Miyasaka,PCE,halide'),

    make('nd_c_069','中国の陶磁器釉薬技術','Chinese Glaze Technology',
         '殷代(BC1600頃)に始まる長石質釉薬。南宋汝窯の天青色釉が酸化鉄制御の極致。',
         'Aesthetic innovation; iron oxide coloration research in materials.',
         '材料科学','East_Asian_Ceramics',-1600,1200,
         r'\text{Fe}^{2+}/\text{Fe}^{3+}\text{ ratio}\to\text{celadon blue-green color control}',
         'East_Asian',88,
         'https://en.wikipedia.org/wiki/Chinese_ceramics',
         '陶磁器,釉薬,青磁,汝窯','Chinese_ceramics,celadon,Jun_ware,iron_oxide,glaze',
         '汝窯'),

    make('nd_c_070','ポリマーナノコンポジット','Polymer Nanocomposite',
         'トヨタ中研(1987)がナイロン-モンモリロナイトナノコンポジットを開発。少量フィラーで大幅強化。',
         'Lightweight packaging, automotive parts, barrier materials.',
         '材料科学','Polymer_Materials',1987,2000,
         r"E_{nano}/E_{matrix}\sim1+2(l/d)\phi_f/3\text{ (Halpin-Tsai)}",
         'East_Asian',88,
         'https://en.wikipedia.org/wiki/Nanocomposite',
         'ナノコンポジット,モンモリロナイト,トヨタ','nanocomposite,clay,Toyota,nanoclay,barrier'),

    make('nd_c_071','4Dプリンティングと変形材料','4D Printing and Programmable Matter',
         'Tibbits(MIT 2013)が提唱。3D印刷構造物が熱・水・光刺激で形状変化する「4次元」製造。',
         'Soft robotics, deployable structures, smart textiles.',
         '材料科学','Advanced_Manufacturing',2013,2020,
         r'u(T)=\alpha\Delta T\cdot L_0\text{ (thermal actuation)}',
         'American_Science',82,
         'https://en.wikipedia.org/wiki/4D_printing',
         '4Dプリンティング,Tibbits,スマート材料','4D_printing,Tibbits,shape_shifting,soft_robotics'),

    make('nd_c_072','スズ-コバルト電気めっき','Tin-Cobalt Electroplating',
         '亜鉛めっき後に登場したニッケルフリー銀白色代替。EU RoHS 2006でニッケル規制を受けて普及。',
         'Electronic connectors, decorative hardware, EU RoHS compliant.',
         '材料科学','Surface_Engineering',2006,2015,
         r'i_L=nFD\frac{C^*}{\delta}\text{ (limiting current density)}',
         'Global_Synthesis',75,
         'https://en.wikipedia.org/wiki/Electroplating',
         'SnCo電気めっき,RoHS,表面処理','tin_cobalt_plating,RoHS,nickel_free,connector'),

    make('nd_c_073','インカの繊維技術','Inca Textile Technology',
         'クンビ(vicuña絹)とアルパカウールの超精密織り技術。糸番手Ne60相当を紀元前から達成。',
         'Outstanding pre-Columbian textile skill; fiber science heritage.',
         '材料科学','South_American_Materials',-1000,1535,
         r'\text{Count Ne}=\frac{840\text{ yd/lb}}{\text{fiber length/weight}};\;\text{vicuna }5-8\mu m',
         'South_American',85,
         'https://en.wikipedia.org/wiki/Inca_textile',
         'インカ,アルパカ,ビクーニャ,繊維技術','Inca_textile,vicuna,alpaca,fiber_technology',
         ''),

    make('nd_c_074','カーボンニュートラル鉄鋼','Carbon-Neutral Steel Production',
         '水素還元製鉄(DRI+H2)・電炉リサイクル。HYBRIT(スウェーデン,2020)が第1号試験成功。',
         'Decarbonizing 1.8 billion tons CO2/year from steel industry.',
         '材料科学','Green_Materials',2020,2030,
         r'Fe_2O_3+3H_2\to2Fe+3H_2O;\;CO_2=0\text{ (vs 1.8 tCO}_2/\text{t steel)}',
         'Scandinavian',88,
         'https://en.wikipedia.org/wiki/Green_steel',
         'グリーンスチール,水素製鉄,HYBRIT','green_steel,HYBRIT,hydrogen_reduction,DRI'),

    make('nd_c_075','機械学習を用いた材料探索','Machine Learning for Materials Discovery',
         'Oganov(クリスタル構造予測,2006)・GNoME(DeepMind 2023)が220万安定結晶構造を予測。',
         'Accelerates materials discovery for energy and electronics.',
         '材料科学','Computational_Materials',2006,2023,
         r'E_{form}(X)=E_{ML}(X)-\sum_i\mu_i N_i\text{ (formation energy)}',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Materials_informatics',
         '材料インフォマティクス,GNoME,DeepMind','materials_informatics,Oganov,GNoME,crystal_structure_prediction'),

    make('nd_c_076','マクスウェル流体と粘弾性','Maxwell Fluid and Viscoelasticity',
         'Maxwellが1867年にバネ+ダッシュポット直列モデルで粘弾性体を記述。Kelvin-Voigt並列モデルも。',
         'Polymer characterization, food rheology, biological tissue mechanics.',
         '材料科学','Rheology',1867,1910,
         r'G(\omega)=\frac{G_0\omega^2\tau^2}{1+\omega^2\tau^2}+i\frac{G_0\omega\tau}{1+\omega^2\tau^2}',
         'British_Science',85,
         'https://en.wikipedia.org/wiki/Viscoelasticity',
         'マクスウェル,粘弾性,クリープ','Maxwell,viscoelasticity,creep,relaxation'),

    make('nd_c_077','アラミド繊維','Aramid Fiber',
         'Kwolek(DuPont 1965)が合成したケブラーの前身。p-アラミドの芳香族ポリアミドが比強度で鉄の5倍。',
         'Ballistic protection, aerospace, pressure vessels, cut-resistant gloves.',
         '材料科学','Advanced_Fibers',1965,1980,
         r'E_{Kevlar}\approx70\text{ GPa};\;\sigma_{ts}\approx3.5\text{ GPa};\;\rho=1.44\text{ g/cm}^3',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Kevlar',
         'ケブラー,アラミド,Kwolek,防弾','Kevlar,aramid,Kwolek,ballistic,DuPont'),

    make('nd_c_078','量子材料の超流動','Superfluidity in Quantum Materials',
         'Kapitza・Allen・Misener(1938)がヘリウム-4超流動を発見。ランダウ二流体モデルが説明。',
         'Cryogenics, quantum turbulence research, superconductor analogy.',
         '材料科学','Quantum_Materials',1938,1950,
         r'\rho_s(T)=\rho[1-(T/T_\lambda)^{5/7}]\text{ (empirical superfluid density)}',
         'Soviet_British',90,
         'https://en.wikipedia.org/wiki/Superfluidity',
         '超流動,ヘリウム,Kapitza,Landau','superfluidity,Kapitza,helium_4,Landau,quantum_fluid'),

    make('nd_c_079','コーティング技術の発展','Development of Coating Technologies',
         'PVD→CVD→ALD(原子層堆積,1977)。Å単位の厚さ制御が半導体・光学・腐食防止を支配。',
         'DRAM high-k dielectric, anti-reflective optics, wear-resistant tools.',
         '材料科学','Surface_Engineering',1977,2000,
         r'r_{ALD}=0.1\text{–}3\text{ Å/cycle};\;\text{conformality}=100\%',
         'Finnish_American',88,
         'https://en.wikipedia.org/wiki/Atomic_layer_deposition',
         'ALD,原子層堆積,CVD,PVD','ALD,CVD,PVD,atomic_layer_deposition,conformality'),

    make('nd_c_080','ガラスの化学的強化','Chemical Strengthening of Glass',
         'Gorilla Glass(コーニング,1960年代)に代表されるイオン交換強化。大きなK+でNa+を置換し圧縮応力層。',
         'Smartphone screens, aircraft windows, medical glassware.',
         '材料科学','Glass_Science',1962,2007,
         r'\sigma_c=\frac{E\Delta\alpha\Delta T}{1-\nu};\;\text{ion exchange depth}\sim50\mu m',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Gorilla_Glass',
         'ゴリラガラス,化学強化,イオン交換','Gorilla_Glass,chemical_strengthening,ion_exchange'),
]

# ── 進化・遺伝学 (nd_c_081 – nd_c_120) ─────────────────────────────────
EVO = [
    make('nd_c_081','分子時計','Molecular Clock',
         'Zuckerkandl・Pauling(1962)が提唱。DNAの塩基置換が時間に比例して蓄積するとした進化時計。',
         'Divergence dating, phylogenetics, forensics, ancient DNA timing.',
         '進化・遺伝学','Molecular_Evolution',1962,1980,
         r'd=2\mu t;\;\mu\approx10^{-9}\text{ subs/site/yr (neutral)}','American_Science',88,
         'https://en.wikipedia.org/wiki/Molecular_clock',
         '分子時計,Zuckerkandl,Pauling,中立説','molecular_clock,Zuckerkandl,Pauling,substitution_rate'),

    make('nd_c_082','中立進化理論','Neutral Theory of Molecular Evolution',
         '木村資生(1968)が提唱。分子レベルの多型の大部分は自然選択でなく遺伝的浮動によると主張。',
         'Foundation of molecular phylogenetics; molecular clock calibration.',
         '進化・遺伝学','Population_Genetics',1968,1983,
         r'\bar{\pi}=4N_e\mu\text{ (Tajima }\theta);\;f_{neutral}=1-f_{del}',
         'East_Asian',95,
         'https://en.wikipedia.org/wiki/Neutral_theory_of_molecular_evolution',
         '木村資生,中立説,遺伝的浮動,分子進化','Kimura,neutral_theory,genetic_drift,molecular_evolution'),

    make('nd_c_083','ゲノムインプリンティング','Genomic Imprinting',
         '哺乳類で父由来・母由来のアレルが異なる発現を示すエピジェネティックな単親性。H19/Igf2が典型。',
         'Prader-Willi/Angelman syndrome, placenta biology, cancer.',
         '進化・遺伝学','Epigenetics',1984,1995,
         r'[\text{Igf2}]_{paternal}>\text{maternal};\;\text{ICR methylation}',
         'British_American',88,
         'https://en.wikipedia.org/wiki/Genomic_imprinting',
         'ゲノムインプリンティング,H19,Igf2','genomic_imprinting,H19,Igf2,Prader_Willi'),

    make('nd_c_084','水平遺伝子転移','Horizontal Gene Transfer',
         '親子関係によらず個体間・種間でのDNA移行。プラスミド・形質転換・ウイルス媒介が主機序。',
         'Antibiotic resistance spread; major force in prokaryote evolution.',
         '進化・遺伝学','Microbial_Evolution',1928,1980,
         r'P(HGT)\propto\text{donor-recipient proximity}\times\text{recombination rate}',
         'British_American',90,
         'https://en.wikipedia.org/wiki/Horizontal_gene_transfer',
         '水平遺伝子転移,HGT,プラスミド,抗生物質耐性','HGT,horizontal_gene_transfer,plasmid,transformation'),

    make('nd_c_085','選択スイープと正の選択','Selective Sweep and Positive Selection',
         '有利変異が固定化される際に周辺の多型が消去される現象。HapMap・1000 Genomes で検出。',
         'Identifies adaptations in human genome; malaria resistance, lactase persistence.',
         '進化・遺伝学','Population_Genetics',1974,2000,
         r'H=-\sum_i f_i\ln f_i\to0\text{ (haplotype homozygosity under sweep)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Selective_sweep',
         '選択スイープ,正の自然選択,HapMap','selective_sweep,positive_selection,HapMap'),

    make('nd_c_086','ゲノムワイド関連解析','Genome-Wide Association Study',
         'Collins(2003 HapMap) → Wellcome Trust(2007 7疾患)。SNPで疾患リスク遺伝子座を発見。',
         'Identified 100,000+ SNP-trait associations; polygenic risk scores.',
         '進化・遺伝学','Genomics',2007,2020,
         r'P=\chi^2/N+O(\text{confounders});\;\lambda_{GC}\text{ (inflation factor)}',
         'Global_Synthesis',90,
         'https://en.wikipedia.org/wiki/Genome-wide_association_study',
         'GWAS,SNP,疾患遺伝子座,多遺伝子リスクスコア','GWAS,SNP,polygenic_risk_score,HapMap'),

    make('nd_c_087','倍数性進化','Polyploidy Evolution',
         '真核生物ゲノムへの全ゲノム重複。植物の多くが過去に倍数性を経験。花の多様化・作物進化に寄与。',
         'Crop improvement (wheat 6n, strawberry 8n), plant speciation.',
         '進化・遺伝学','Plant_Evolution',1917,1970,
         r'2n=42\text{ (wheat hexaploid)};\;F=x\text{ (base number)}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Polyploidy',
         '倍数性,全ゲノム重複,小麦','polyploidy,whole_genome_duplication,wheat,speciation'),

    make('nd_c_088','性染色体進化','Sex Chromosome Evolution',
         'オーニールのドジョウ(1913)から。X-Yの退化・XY→ZW等の多様な性決定システムの進化遺伝学。',
         'Human disease (Turner, Klinefelter), sex-biased evolution.',
         '進化・遺伝学','Evolutionary_Genetics',1905,1960,
         r'X\text{ inactivation: }XIST\text{ RNA coating};\;Y\text{ ~55 genes}',
         'American_British',85,
         'https://en.wikipedia.org/wiki/Sex_chromosome',
         'X染色体不活化,Y染色体,性決定','sex_chromosome,X_inactivation,XIST,Y_chromosome'),

    make('nd_c_089','共進化と軍拡競争','Coevolution and Evolutionary Arms Race',
         'Ehrlich・Raven(1964)蝶と植物。Red Queen仮説・Janzen(共進化)・Dawkins/Krebs軍拡競争。',
         'Antibiotic resistance, host-parasite dynamics, biodiversity.',
         '進化・遺伝学','Evolutionary_Biology',1964,1980,
         r'd\bar{w}_1/dt\propto\partial w_1/\partial\bar{z}_2\cdot\partial\bar{z}_2/dt\text{ (coev)}',
         'American_British',85,
         'https://en.wikipedia.org/wiki/Coevolution',
         '共進化,赤の女王,軍拡競争,Ehrlich','coevolution,Red_Queen,arms_race,Ehrlich_Raven'),

    make('nd_c_090','亜種と地理的変異','Subspecies and Geographic Variation',
         'Glogerの規則(1833)・Bergmannの規則(1847)が地理的適応変異を定量化。地域集団の遺伝的分化。',
         'Conservation management, defining ESU, taxonomy.',
         '進化・遺伝学','Population_Genetics',1833,1940,
         r'Q_{ST}=V_{between}/(V_{between}+2V_{within})\text{ vs }F_{ST}',
         'German_Science',80,
         'https://en.wikipedia.org/wiki/Subspecies',
         'Gloger則,Bergmann則,亜種,地理変異','subspecies,Bergmann_rule,Gloger_rule,geographic_variation'),

    make('nd_c_091','レトロポゾンとゲノム寄生','Retrotransposons and Genome Parasites',
         'McClintock(1951 Nobel)がトランスポゾンを発見。L1/SINEが哺乳類ゲノムの45%を占める。',
         'Genome evolution, cancer mutations, epigenetic defense.',
         '進化・遺伝学','Evolutionary_Genetics',1951,1980,
         r'f_{transposon}\approx45\%\text{ human genome};\;L1\approx17\%',
         'American_Science',92,
         'https://en.wikipedia.org/wiki/Transposable_element',
         'トランスポゾン,McClintock,レトロポゾン,L1','transposon,McClintock,retrotransposon,L1,SINE'),

    make('nd_c_092','表現型可塑性','Phenotypic Plasticity',
         '同一遺伝子型が環境変化に応じて異なる表現型を示す能力。西澤長衛の日本タンポポ実験が例示。',
         'Climate adaptation, developmental biology, eco-devo.',
         '進化・遺伝学','Evolutionary_Biology',1930,1990,
         r'\bar{z}=a+bE+\varepsilon\text{ (reaction norm: slope b = plasticity)}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Phenotypic_plasticity',
         '表現型可塑性,反応規範,適応','phenotypic_plasticity,reaction_norm,adaptive_plasticity'),

    make('nd_c_093','親族選択と血縁係数','Kin Selection and Relatedness',
         'Hamilton(1964)のrb>cルール。r=2θ(Wright血縁係数)。社会性昆虫・協力行動の進化的説明。',
         'Social insect biology, human cooperation, evolutionary psychology.',
         '進化・遺伝学','Behavioral_Genetics',1964,1975,
         r'r=2\theta;\;F=\Pr[\text{IBD}];\;r_{sibling}=0.5',
         'British_Science',90,
         'https://en.wikipedia.org/wiki/Kin_selection',
         'ハミルトン,血縁選択,包括適応度,r','kin_selection,Hamilton,relatedness,inclusive_fitness'),

    make('nd_c_094','島嶼矮小化と巨大化','Insular Dwarfism and Gigantism',
         'Island rule(フォスター,1964)。島嶼での捕食者・資源制約が大型種を矮小化・小型種を巨大化。',
         'Homo floresiensis (Flores hobbit) discovery; conservation island biology.',
         '進化・遺伝学','Island_Evolution',1964,2004,
         r'\Delta\log m/\Delta\log m_0=b\ln(N_1/N_0);\;b\text{ negative for large species}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Island_rule',
         '島の規則,矮小化,フォスター,ホモ・フロレシエンシス','island_rule,Foster,insular_dwarfism,floresiensis'),

    make('nd_c_095','マルチオーミクス統合','Multi-omics Integration',
         'ゲノム・転写・プロテオーム・メタボロームの同時解析。TCGA・GTEx・UK Biobankが先導。',
         'Cancer subtype classification, drug target identification, aging biomarkers.',
         '進化・遺伝学','Systems_Biology',2010,2020,
         r'Z\text{-score normalization}+\text{MOFA/DIABLO integration}',
         'Global_Synthesis',85,
         'https://en.wikipedia.org/wiki/Multi-omics',
         'マルチオーミクス,TCGA,GTEx,システム生物学','multi-omics,TCGA,GTEx,systems_biology'),

    make('nd_c_096','アフリカ人ゲノムの多様性','African Genomic Diversity',
         'KhoiSan族に世界最古の分岐。H3Africa・AWI-Genが全ゲノム解析を推進。SNP多様性は非アフリカの2倍。',
         'Personalized medicine for Africa; demographic history reconstruction.',
         '進化・遺伝学','Population_Genetics',2010,2020,
         r'\pi_{Africa}\approx2\times10^{-3};\;F_{ST}(Africa\text{-}nonAfrica)\approx0.15',
         'Sub_Saharan_African',90,
         'https://en.wikipedia.org/wiki/H3Africa',
         'アフリカゲノム多様性,KhoiSan,H3Africa','African_genomics,Khoisan,H3Africa,population_diversity'),

    make('nd_c_097','性的二型の進化','Evolution of Sexual Dimorphism',
         'Darwin(1871)の性選択→Fisher暴走→Zahavi誠実信号→Bateman原則。雌雄の差の進化的起源。',
         'Animal behavior, human anthropology, gender medicine.',
         '進化・遺伝学','Evolutionary_Biology',1871,1975,
         r'\sigma^2_{male}>\sigma^2_{female}\text{ (Bateman\'s principle)}',
         'British_Science',85,
         'https://en.wikipedia.org/wiki/Sexual_dimorphism',
         '性的二型,Bateman原則,性選択','sexual_dimorphism,Bateman,Fisher,Zahavi'),

    make('nd_c_098','ミトコンドリアDNA系統地理学','Mitochondrial DNA Phylogeography',
         'Wilson・Cann(1987)「ミトコンドリア・イブ」。mtDNA母系系統でホモ・サピエンスの出アフリカを追跡。',
         'Human migration reconstruction; forensic identification.',
         '進化・遺伝学','Population_Genetics',1987,2000,
         r'D_{HKY}=d_s+d_v;\;t_{div}=D/(2\mu_{mt})','American_Science',92,
         'https://en.wikipedia.org/wiki/Mitochondrial_Eve',
         'ミトコンドリアイブ,mtDNA,出アフリカ','mitochondrial_Eve,Wilson,Cann,mtDNA,out_of_Africa'),

    make('nd_c_099','共進化的農業と作物家畜化','Coevolutionary Crop Domestication',
         'Vavilov(1926)が世界8大農業起源中心を提唱。小麦・水稲・トウモロコシのゲノム変化(自己駆動選択)。',
         'Plant breeding, food security, genetic resource conservation.',
         '進化・遺伝学','Agricultural_Genetics',1926,1970,
         r'\Delta G=ih\sqrt{V_A}\text{ (selection response)}',
         'Soviet_Eastern_European',88,
         'https://en.wikipedia.org/wiki/Vavilov_centres',
         'Vavilov,作物起源中心,家畜化','Vavilov,crop_origin,domestication,selection_response'),

    make('nd_c_100','昆虫の社会性進化','Social Insect Evolution',
         'Wilson(1971 E.O.)がアリ・ハチ・シロアリの真社会性を体系化。真社会性の進化条件:血縁・世代重複・分業。',
         'Model for cooperative evolution; inspiration for swarm robotics.',
         '進化・遺伝学','Social_Evolution',1971,1990,
         r'r\cdot B>C\text{ (Hamilton, bees: }r_{sibling}=3/4)',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Eusociality',
         'Wilson,真社会性,アリ,ハチ,分業','eusociality,Wilson,colony,superorganism'),

    make('nd_c_101','ゲノム変異と疾患のリンク','Copy Number Variation and Disease',
         'Iafrate(2004)がCNVを大規模発見。ゲノムの数百kb〜Mbスケールの欠失・重複が疾患に寄与。',
         'Autism, schizophrenia, cancer amplification, drug response.',
         '進化・遺伝学','Genomics',2004,2015,
         r'CN\geq3\text{ (dup)}/CN\leq1\text{ (del)};\;MLPA/aCGH detection',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Copy-number_variation',
         'CNV,コピー数変異,自閉症','CNV,copy_number_variation,autism,schizophrenia'),

    make('nd_c_102','系統地理学','Phylogeography',
         'Avise(1987)が分子系統と地理分布を統合。氷期の避難地・拡散経路が現在の遺伝構造を形成。',
         'Conservation genetics, invasive species tracking, zoonosis surveillance.',
         '進化・遺伝学','Population_Genetics',1987,2000,
         r'NST>GST\text{ (geography effect on differentiation)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Phylogeography',
         '系統地理学,Avise,氷期,避難地','phylogeography,Avise,refugia,population_structure'),

    make('nd_c_103','異種交配と交配障壁','Hybridization and Reproductive Barriers',
         'Bateson-Dobzhansky-Muller (BDM) モデル。異種間の遺伝子非適合が生殖隔離を生む。',
         'Speciation theory, hybrid vigor in crops, invasive hybrid zones.',
         '進化・遺伝学','Evolutionary_Biology',1922,1942,
         r'w(AB)\propto e^{-k(a-b)^2}\text{ (Gaussian fitness surface)}',
         'Russian_American',85,
         'https://en.wikipedia.org/wiki/Bateson%E2%80%93Dobzhansky%E2%80%93Muller_model',
         'BDM非適合,生殖隔離,交雑','BDM,reproductive_isolation,hybridization,speciation'),

    make('nd_c_104','チバニアン地磁気逆転','Chibanian Geomagnetic Reversal Record',
         '千葉県市原市の地層がBC774000年の地磁気逆転の国際標準地点(GSSP)に認定(2020)。',
         'Geochronology standard; paleomagnetic reversal frequency research.',
         '進化・遺伝学','Geochronology',2020,2020,
         r't_{Brunhes-Matuyama}=0.773\text{ Ma;\;Chibanian GSSP certified 2020}',
         'East_Asian',90,
         'https://en.wikipedia.org/wiki/Chibanian',
         'チバニアン,地磁気逆転,千葉','Chibanian,geomagnetic_reversal,GSSP,Brunhes_Matuyama'),

    make('nd_c_105','古生物ゲノミクス','Paleogenomics',
         'Pääbo(ネアンデルタール,2010)・Skoglund(古代北ユーラシア人,2012)。死後のDNA断片化を読む。',
         'Human prehistory reconstruction; disease adaptation analysis.',
         '進化・遺伝学','Ancient_Genomics',2010,2020,
         r'P(observed|aDNA)\propto e^{-\lambda t}\text{ (degradation)}',
         'Swedish_Science',92,
         'https://en.wikipedia.org/wiki/Paleogenomics',
         '古ゲノム学,Pääbo,ネアンデルタール,古代人','paleogenomics,Paabo,ancient_DNA,Neanderthal'),

    make('nd_c_106','植物育種の科学','Plant Breeding Science',
         'Johannsen(1903純系説)→East/Shull(雑種強勢)→Borlaug(緑の革命 1970 Nobel)。',
         'Green Revolution prevented billions of deaths; modern biofortification.',
         '進化・遺伝学','Agricultural_Genetics',1903,1970,
         r'H^2=V_A/V_P\text{ (broad-sense heritability)};\;V_P=V_G+V_E',
         'American_Norwegian',95,
         'https://en.wikipedia.org/wiki/Plant_breeding',
         'Borlaug,緑の革命,純系,雑種強勢','Borlaug,Green_Revolution,hybrid_vigor,heritability'),

    make('nd_c_107','非コードRNAの機能','Non-coding RNA Function',
         'miRNA(Lee 1993)・lncRNA・circRNAが遺伝子発現を転写後調節。ENCODE計画(2012)でゲノムの80%が転写。',
         'Cancer biomarkers, gene therapy targets, RNA-based drugs.',
         '進化・遺伝学','RNA_Biology',1993,2012,
         r'miRNA+RISC\to mRNA\text{ cleavage or translational repression}',
         'American_British',88,
         'https://en.wikipedia.org/wiki/Non-coding_RNA',
         'miRNA,lncRNA,ENCODE,非コードRNA','miRNA,lncRNA,ENCODE,non-coding_RNA,Lee'),

    make('nd_c_108','集団の創始者効果','Founder Effect and Bottleneck',
         'Mayr(1954)が提唱。少数の創始者から始まる集団の遺伝的多様性減少と特定アレル頻度上昇。',
         'Rare disease prevalence in founder populations; conservation genetics.',
         '進化・遺伝学','Population_Genetics',1954,1970,
         r'N_e\approx N_0/\sum(1/N_t)^{-1}\text{ (harmonic mean)}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Founder_effect',
         '創始者効果,遺伝的ボトルネック,Mayr','founder_effect,bottleneck,Mayr,effective_population_size'),

    make('nd_c_109','先住民の植物知識と生物多様性保全','Indigenous Botanical Knowledge and Biodiversity',
         '世界の先住民族は薬用・食用植物の80%以上の知識を保有。CBDのNagoya議定書(2010)が保護。',
         'Ethnobotanical drug discovery; bioprospecting ethics regulation.',
         '進化・遺伝学','Ethnobotany',2010,2020,
         r'\text{Nagoya Protocol: ABS=access+benefit sharing (2010)}',
         'Global_Indigenous',85,
         'https://en.wikipedia.org/wiki/Nagoya_Protocol',
         '先住民植物知識,Nagoya議定書,ABS','indigenous_botanical_knowledge,Nagoya_Protocol,ABS'),

    make('nd_c_110','ミトコンドリア疾患の遺伝','Mitochondrial Disease Genetics',
         'Wallaceが1988年にLeber遺伝性視神経症をmtDNA変異と関連付け。母系遺伝・閾値効果・ヘテロプラスミー。',
         'Mitochondrial disease diagnosis, gene therapy via heteroplasmy reduction.',
         '進化・遺伝学','Medical_Genetics',1988,2000,
         r'f_{mutant}>\theta_{threshold}\approx60-90\%\text{ (heteroplasmy threshold)}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Mitochondrial_disease',
         'ミトコンドリア疾患,mtDNA変異,Wallace','mitochondrial_disease,mtDNA,Wallace,heteroplasmy'),

    make('nd_c_111','オーストロネシア語族の遺伝的拡散','Austronesian Genetic Expansion',
         'Gray・Jordan(2000)が語族系統でアウト・オブ・台湾説を支持。mtDNA/Y染色体で太平洋への拡散を追跡。',
         'Pacific settlement history; links linguistic and genetic diversity.',
         '進化・遺伝学','Population_Genetics',2000,2015,
         r'D_{Weir-Cockerham}F_{ST}\text{ across Pacific island populations}',
         'Pacific_Islander',88,
         'https://en.wikipedia.org/wiki/Austronesian_peoples',
         'オーストロネシア,太平洋拡散,遺伝的系統','Austronesian,out_of_Taiwan,Pacific_expansion,mtDNA'),

    make('nd_c_112','適応ランドスケープ','Adaptive Landscape',
         'Wrightが1932年に提唱したフィットネス峰の比喩。集団は適応度地形の峰を渡るよう進化する。',
         'Speciation theory, directed evolution, protein engineering.',
         '進化・遺伝学','Population_Genetics',1932,1970,
         r'w(\bar{z})=\exp\left(-\frac{(\bar{z}-\theta)^2}{2\omega^2}\right)\text{ (Gaussian fitness)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Fitness_landscape',
         '適応度地形,Wright,フィットネス峰','fitness_landscape,Wright,adaptive_landscape,peak_shift'),

    make('nd_c_113','自然免疫の分子認識','Innate Immune Pattern Recognition',
         'Janeway(1989 TLR仮説)→Hoffmann・Beutler(2011 Nobel)がTLRの自然免疫における役割を確立。',
         'Sepsis treatment, vaccine adjuvants, inflammatory disease targets.',
         '進化・遺伝学','Immunology',1989,2011,
         r'TLR4+LPS\to MyD88\to NF-\kappa B\to\text{cytokines}',
         'French_American',92,
         'https://en.wikipedia.org/wiki/Toll-like_receptor',
         'Toll様受容体,自然免疫,Janeway,Hoffmann','TLR,innate_immunity,Janeway,Hoffmann,Beutler'),

    make('nd_c_114','アレル頻度不均衡と連鎖不平衡','Linkage Disequilibrium',
         'Lewontinが1964年にD値を定義。HapMapでLDブロック構造が解明され、GWASの統計的基盤に。',
         'GWAS fine-mapping, haplotype phasing, population history.',
         '進化・遺伝学','Population_Genetics',1964,2000,
         r"D'=D/D_{max};\;r^2=D^2/(p_A p_a p_B p_b)",
         'American_British',85,
         'https://en.wikipedia.org/wiki/Linkage_disequilibrium',
         '連鎖不平衡,LD,HapMap,GWAS','linkage_disequilibrium,LD,Lewontin,GWAS,haplotype'),

    make('nd_c_115','進化ゲノミクスの反復配列','Repetitive Sequences in Evolutionary Genomics',
         'サテライトDNA・タンデムリピート・マイクロサテライト。多型がDNA指紋に利用される(Jeffreys 1985)。',
         'Forensic DNA profiling, population genetics, disease repeat expansion.',
         '進化・遺伝学','Evolutionary_Genomics',1985,2000,
         r'n_{alleles}\propto\mu_{slippage}\cdot N_e;\;\text{STR locus}',
         'British_Science',85,
         'https://en.wikipedia.org/wiki/Microsatellite',
         'マイクロサテライト,DNA指紋,Jeffreys','microsatellite,STR,Jeffreys,DNA_fingerprint'),

    make('nd_c_116','エクスパンドムとタンデムリピート疾患','Trinucleotide Repeat Expansion Disease',
         'ハンチントン病(CAGリピート膨張,1993)。リピート数が閾値を超えると神経変性が起きる特異な変異様式。',
         'Huntington, myotonic dystrophy, fragile X syndrome mechanisms.',
         '進化・遺伝学','Medical_Genetics',1993,2000,
         r'n_{CAG}>35\to\text{Huntington onset (inverse correlation with age)}',
         'American_Science',88,
         'https://en.wikipedia.org/wiki/Trinucleotide_repeat_disorder',
         'CAGリピート,ハンチントン病,繰り返し配列','trinucleotide_repeat,Huntington,fragile_X,CAG'),

    make('nd_c_117','アフリカ起源多地域進化論争','Out of Africa vs Multiregional Hypothesis',
         'Stringer・Andrews(1988 Out of Africa)対Thorne・Wolpoff(多地域)。古代DNAでOoA説が支持される。',
         'Human evolution understanding; Neanderthal admixture clarification.',
         '進化・遺伝学','Human_Evolution',1987,2010,
         r'D_4\text{-statistics detect }3-5\%\text{ Neanderthal ancestry in non-Africans}',
         'British_American',90,
         'https://en.wikipedia.org/wiki/Recent_African_origin_of_modern_humans',
         '出アフリカ説,多地域進化,Stringer','out_of_Africa,Stringer,multiregional,Neanderthal_admixture'),

    make('nd_c_118','配列モチーフと転写調節','Sequence Motifs and Transcriptional Regulation',
         'JASPAR・TRANSFACが転写因子結合モチーフを集積。PWM(位置荷重行列)が結合親和性を予測。',
         'Gene regulation analysis, regulatory mutation prediction.',
         '進化・遺伝学','Molecular_Biology',1985,2010,
         r'S_i=\sum_k w_{k,b}\cdot f(b_i=k)\text{ (PWM score)}',
         'Global_Synthesis',82,
         'https://en.wikipedia.org/wiki/Sequence_motif',
         '配列モチーフ,PWM,JASPAR,転写因子','sequence_motif,PWM,JASPAR,transcription_factor'),

    make('nd_c_119','ゲノムスケール代謝モデル','Genome-Scale Metabolic Model',
         'Palsson(2000〜)がE. coliの全代謝反応をマトリクスで記述。FBAで増殖・代謝産物を計算。',
         'Bioprocess engineering, drug target prediction, synthetic biology.',
         '進化・遺伝学','Systems_Biology',2000,2015,
         r'S\cdot v=0\text{ (steady state)};\;v_{min}\leq v\leq v_{max}\text{ (FBA)}',
         'American_Science',85,
         'https://en.wikipedia.org/wiki/Metabolic_network_modelling',
         '代謝フラックス解析,FBA,Palsson','genome_scale_model,FBA,Palsson,flux_balance_analysis'),

    make('nd_c_120','ゲノム編集と農業育種','Genome Editing in Agricultural Breeding',
         'CRISPR/Cas9による精密育種。非GMO扱いの可能性(EU 2023改正)と耐病性・収量向上作物開発。',
         'Waxy maize (DuPont 2016), disease-resistant wheat, high oleic soybean.',
         '進化・遺伝学','Agricultural_Genetics',2013,2023,
         r'\text{Knock-out via NHEJ};\;\text{Knock-in via HDR};\;\text{base edit: }C\to T',
         'Global_Synthesis',88,
         'https://en.wikipedia.org/wiki/Genome_editing_in_crops',
         'CRISPR農業,精密育種,EU規制','CRISPR_crops,precision_breeding,genome_editing_plants'),
]

CONCEPTS = MED + MAT + EVO

def insert_batch(concepts):
    con = sqlite3.connect(DB)
    cur = con.cursor()
    cur.execute('SELECT LOWER(name_en) FROM natural_discovery')
    existing = {r[0] for r in cur.fetchall()}
    now = datetime.datetime.utcnow().isoformat()
    inserted = skipped = 0
    cols = ['id','name_ja','name_en','name_original','definition','impact_summary',
            'subfield','school_of_thought','era_start','era_end','methodology_level',
            'target_domain','application_conditions','when_to_apply','framing_questions',
            'opposing_concept_names','keywords_ja','keywords_en','status',
            'source_reliability','data_completeness','mathematical_formulation',
            'experimental_verification','applicable_scale','precision_level',
            'quality_flag','source_url','primary_source','primary_source_url',
            'primary_source_year','verification_status','culture_region',
            'culture_confidence','genealogy_narrative','narrative_word_count',
            'gta_l3','gta_l2','last_verified_at','redirect_to','http_status']
    placeholders = ','.join([f':{c}' for c in cols])
    sql = f"INSERT OR IGNORE INTO natural_discovery ({','.join(cols)},created_at,updated_at) VALUES ({placeholders},:created_at,:updated_at)"
    for c in concepts:
        if c['name_en'].lower() in existing:
            skipped += 1
            continue
        try:
            cur.execute(sql, {**c, 'created_at': now, 'updated_at': now})
            if cur.rowcount:
                inserted += 1
                existing.add(c['name_en'].lower())
        except Exception as e:
            print(f"ERROR {c['id']}: {e}")
    con.commit()
    cur.execute('SELECT COUNT(*) FROM natural_discovery')
    total = cur.fetchone()[0]
    con.close()
    return inserted, skipped, total

if __name__ == '__main__':
    ins, sk, total = insert_batch(CONCEPTS)
    print(f"挿入: {ins}, スキップ: {sk}, DB総件数: {total}")
