#!/usr/bin/env python3
"""Wave A2 Batch: 機械工学 +350件"""
import sqlite3, json

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

# (id, name_ja, name_en, subfield, school, era, source_url, culture_region, math_formula, definition, keywords_ja, keywords_en)
DATA = [
("em2_001","熱力学第一法則","First Law of Thermodynamics","機械工学","古典熱力学",1850,
 "https://en.wikipedia.org/wiki/First_law_of_thermodynamics","Western_Europe",
 "ΔU = Q - W",
 "エネルギー保存則を述べる熱力学の基本法則。閉じた系において内部エネルギーの変化は加えられた熱と系がした仕事の差に等しい。蒸気機関から現代エンジン設計まで全熱機械設計の根幹。",
 "熱力学,エネルギー保存,内部エネルギー","thermodynamics,energy conservation,internal energy"),
("em2_002","熱力学第二法則","Second Law of Thermodynamics","機械工学","古典熱力学",1851,
 "https://en.wikipedia.org/wiki/Second_law_of_thermodynamics","Western_Europe",
 "η_Carnot = 1 - T_cold/T_hot",
 "エントロピーが孤立系において増大するか一定であるという法則。熱機関の最大効率（カルノー効率）を規定し、冷凍サイクル・ヒートポンプ設計の絶対基準となる。",
 "熱力学,エントロピー,カルノー効率","thermodynamics,entropy,Carnot efficiency"),
("em2_003","ベルヌーイの定理","Bernoulli Principle","機械工学","流体力学",1738,
 "https://en.wikipedia.org/wiki/Bernoulli%27s_principle","Western_Europe",
 "p + 0.5ρv² + ρgh = const",
 "理想流体の定常流れにおいて圧力・速度・位置エネルギーの和が一定であることを示す定理。航空機翼・ポンプ・流量計・ベンチュリ管設計の基礎。",
 "流体力学,揚力,圧力,ベルヌーイ","fluid mechanics,lift,pressure,Bernoulli"),
("em2_004","ナビエ-ストークス方程式","Navier-Stokes Equations","機械工学","流体力学",1845,
 "https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_equations","Western_Europe",
 "ρ(∂u/∂t + u·∇u) = -∇p + μ∇²u + f",
 "粘性流体の運動を支配する偏微分方程式系。ニュートン流体に対する運動量保存則であり、CFDや乱流解析の基礎方程式。ミレニアム懸賞問題の一つ。",
 "流体力学,ナビエストークス,CFD,乱流","Navier-Stokes,CFD,turbulence,viscous flow"),
("em2_005","有限要素法","Finite Element Method","機械工学","計算力学",1956,
 "https://en.wikipedia.org/wiki/Finite_element_method","North_America",
 "K·u = f",
 "複雑な構造・熱・流体問題を小要素に分割して近似的に解く数値解析手法。建築・自動車・航空機の構造解析に広く使用され、CAEの基幹技術。",
 "有限要素法,FEM,構造解析,CAE","finite element method,FEM,structural analysis,CAE"),
("em2_006","PID制御","PID Control","機械工学","制御工学",1922,
 "https://en.wikipedia.org/wiki/PID_controller","Western_Europe",
 "u(t) = Kp·e + Ki·∫e dt + Kd·de/dt",
 "比例・積分・微分の3要素をフィードバックに用いる古典制御手法。シンプルで多くの工業プロセスに有効で、最も広く実装された制御アルゴリズム。",
 "PID制御,フィードバック,制御工学","PID control,feedback,control engineering"),
("em2_007","モデル予測制御","Model Predictive Control","機械工学","制御工学",1978,
 "https://en.wikipedia.org/wiki/Model_predictive_control","North_America",
 "min_u Σ||y-r||²_Q + ||Δu||²_R",
 "プロセスモデルを用いて未来の挙動を予測し制御入力を最適化するフィードバック制御手法。制約条件を明示的に扱え、化学プロセス・自動車・ロボットに広く用いられる。",
 "モデル予測制御,MPC,最適制御","model predictive control,MPC,optimal control"),
("em2_008","フーリエ熱伝導則","Fourier Law Heat Conduction","機械工学","伝熱工学",1822,
 "https://en.wikipedia.org/wiki/Fourier%27s_law_of_heat_conduction","Western_Europe",
 "q = -k∇T",
 "物体内の熱流束が温度勾配に比例するというフーリエ則。電子機器冷却・建築断熱・原子炉熱設計の根幹方程式となる偏微分方程式の基礎。",
 "熱伝導,フーリエ則,熱流束","heat conduction,Fourier law,heat flux"),
("em2_009","材料力学（応力-ひずみ）","Mechanics of Materials","機械工学","固体力学",1678,
 "https://en.wikipedia.org/wiki/Strength_of_materials","Western_Europe",
 "σ = E·ε",
 "固体材料に作用する応力とひずみの関係を扱う工学分野。フックの法則・破壊力学・疲労破壊の基礎を提供し、構造部材の設計に直結する。",
 "材料力学,応力,ひずみ,フック則","mechanics of materials,stress,strain,Hooke's law"),
("em2_010","疲労破壊とS-N曲線","Fatigue Fracture S-N Curve","機械工学","破壊力学",1860,
 "https://en.wikipedia.org/wiki/Fatigue_(material)","Western_Europe",
 "log N = a - b·log S_a",
 "繰り返し応力負荷による材料破壊を定量化するS-N曲線（Wöhler曲線）。自動車・航空機・橋梁の疲労寿命設計の標準手法。",
 "疲労破壊,S-N曲線,寿命設計","fatigue fracture,S-N curve,fatigue life"),
("em2_011","ラグランジュ力学","Lagrangian Mechanics","機械工学","解析力学",1788,
 "https://en.wikipedia.org/wiki/Lagrangian_mechanics","Western_Europe",
 "d/dt(∂L/∂q̇) - ∂L/∂q = 0",
 "一般化座標を用いて運動方程式を体系的に導く解析力学の定式化。多体ロボット制御・宇宙機軌道計算・量子力学の共通言語となる。",
 "解析力学,ラグランジアン,運動方程式","analytical mechanics,Lagrangian,equations of motion"),
("em2_012","固有振動・共振解析","Vibration Natural Frequency Resonance","機械工学","振動工学",1800,
 "https://en.wikipedia.org/wiki/Vibration","Western_Europe",
 "ωn = √(k/m)",
 "機械系の振動特性を解析し防振・制振設計に活用する分野。固有振動数・減衰比・共振を扱い、橋梁崩壊・航空機フラッタ防止に不可欠。",
 "振動工学,固有振動数,共振,モーダル解析","vibration,natural frequency,resonance,modal analysis"),
("em2_013","オットー・ディーゼルサイクル","Otto Diesel Thermodynamic Cycle","機械工学","熱機関",1876,
 "https://en.wikipedia.org/wiki/Otto_cycle","Western_Europe",
 "η_Otto = 1 - r^(1-γ)",
 "内燃機関の理想熱力学サイクル。ガソリン（オットー）とディーゼルサイクルの理論熱効率を比較・最大化し、エンジン設計の目標値として用いる。",
 "オットーサイクル,ディーゼル,熱効率,内燃機関","Otto cycle,diesel,thermal efficiency,internal combustion"),
("em2_014","アディティブ製造","Additive Manufacturing 3D Printing","機械工学","先端製造",1986,
 "https://en.wikipedia.org/wiki/3D_printing","North_America",
 None,
 "材料を積層して三次元形状を造形する製造技術群。FDM・SLA・SLS・DMDなど多様プロセスがあり、複雑形状・カスタム部品・ラピッドプロトタイピングに革命をもたらした。",
 "アディティブ製造,3Dプリント,積層造形","additive manufacturing,3D printing,layer manufacturing"),
("em2_015","信頼性工学 FMEA/FTA","Reliability Engineering FMEA FTA","機械工学","信頼性工学",1949,
 "https://en.wikipedia.org/wiki/Failure_mode_and_effects_analysis","North_America",
 "RPN = Severity × Occurrence × Detection",
 "製品・システムの信頼性を定量化・改善する工学手法。故障モード影響解析と故障の木解析が代表で、航空・自動車・医療機器の安全設計に義務付けられる。",
 "信頼性工学,FMEA,FTA,故障解析","reliability engineering,FMEA,FTA,failure analysis"),
("em2_016","ロバスト制御 H∞","Robust Control H-infinity","機械工学","制御工学",1981,
 "https://en.wikipedia.org/wiki/H-infinity_methods_in_control_theory","North_America",
 "min_K ||T_zw||_∞",
 "モデル不確かさや外乱に対して安定性・性能を保証する制御設計手法。H∞ノルム最小化により最悪ケース外乱に対する頑健性を最適化する。",
 "ロバスト制御,H∞,頑健性","robust control,H-infinity,robustness"),
("em2_017","トライボロジー","Tribology Friction Lubrication Wear","機械工学","トライボロジー",1966,
 "https://en.wikipedia.org/wiki/Tribology","Western_Europe",
 "f = μ·N",
 "摩擦・摩耗・潤滑を総合的に研究する工学分野。摩擦係数・EHD潤滑・表面テクスチャリングにより機械部品の寿命と効率を最大化する。",
 "トライボロジー,摩擦,潤滑,摩耗","tribology,friction,lubrication,wear"),
("em2_018","MEMS","Micro-Electro-Mechanical Systems","機械工学","マイクロ工学",1987,
 "https://en.wikipedia.org/wiki/Microelectromechanical_systems","North_America",
 None,
 "シリコン微細加工技術でマイクロメートルスケールの機械構造・センサ・アクチュエータを集積した素子群。スマートフォン加速度計・エアバッグ・インクジェットヘッドに不可欠。",
 "MEMS,微小電気機械,センサ,シリコン加工","MEMS,micro-electro-mechanical systems,sensor,silicon"),
("em2_019","CAD/CAM機械設計","CAD CAM Mechanical Design","機械工学","デジタル製造",1963,
 "https://en.wikipedia.org/wiki/Computer-aided_manufacturing","North_America",
 None,
 "コンピュータ支援設計と製造を統合したデジタル製品開発手法。3Dモデルから直接CNCプログラムを生成し製造工程を自動化。設計から製造までのリードタイムを劇的に短縮。",
 "CAD,CAM,コンピュータ支援設計,CNC","CAD,CAM,computer-aided design,CNC"),
("em2_020","切削加工理論","Metal Cutting Mechanics Theory","機械工学","製造加工",1941,
 "https://en.wikipedia.org/wiki/Metal_cutting","North_America",
 "φ = 45° + λs/2 - α/2",
 "金属切削の力学的メカニズムを記述する理論。Ernst-Merchant剪断角モデルが代表的で切削力・工具寿命・表面粗さの予測と最適切削条件決定に使用される。",
 "切削加工,工具寿命,切削力,剪断角","cutting theory,tool life,cutting force,shear angle"),
("em2_021","熱交換器設計 LMTD法","Heat Exchanger Design LMTD","機械工学","伝熱工学",1920,
 "https://en.wikipedia.org/wiki/Heat_exchanger","Western_Europe",
 "Q = U·A·LMTD",
 "流体間で熱を効率的に移動させる熱交換器の設計理論。対数平均温度差法（LMTD）と移動単位数法（NTU-ε）が主要設計手法で化学プラント・HVAC・自動車冷却に用いる。",
 "熱交換器,LMTD,NTU法,伝熱設計","heat exchanger,LMTD,NTU method,thermal design"),
("em2_022","溶接・接合工学","Welding Joining Engineering","機械工学","製造加工",1880,
 "https://en.wikipedia.org/wiki/Welding","Western_Europe",
 None,
 "金属材料の永久接合技術の工学的基盤。アーク溶接・レーザ溶接・摩擦攪拌接合（FSW）を含み、溶接部の組織・残留応力・欠陥を制御する。",
 "溶接,接合,FSW,溶接冶金","welding,joining,FSW,welding metallurgy"),
("em2_023","ターボ機械設計","Turbomachinery Design","機械工学","流体機械",1880,
 "https://en.wikipedia.org/wiki/Turbomachinery","Western_Europe",
 "H = u²/g",
 "流体のエネルギーと機械的仕事を変換する回転機械（タービン・ポンプ・圧縮機）の設計理論。速度三角形・比速度・効率曲線が設計の基本ツール。",
 "ターボ機械,タービン,ポンプ,圧縮機","turbomachinery,turbine,pump,compressor"),
("em2_024","弾塑性有限要素解析","Elastoplastic Finite Element Analysis","機械工学","計算力学",1970,
 "https://en.wikipedia.org/wiki/Plasticity_(physics)","Western_Europe",
 "f(σ) = √(3J₂) - σy ≤ 0",
 "材料が降伏点を超えた塑性変形域まで含む有限要素解析。冷間鍛造・板金成形・衝突解析に必須で、von Mises降伏条件と等方/移動硬化則を組み合わせる。",
 "弾塑性解析,降伏条件,金属成形","elastoplastic analysis,yield criterion,metal forming"),
("em2_025","適応制御","Adaptive Control","機械工学","制御工学",1958,
 "https://en.wikipedia.org/wiki/Adaptive_control","North_America",
 None,
 "システムパラメータが未知または時変の場合にコントローラを自動調整する制御手法。モデル規範型適応制御（MRAC）と自己チューニングレギュレータ（STR）が代表的。",
 "適応制御,MRAC,自己チューニング","adaptive control,MRAC,self-tuning regulator"),
("em2_026","弾性波動理論","Elastic Wave Theory","機械工学","固体力学",1821,
 "https://en.wikipedia.org/wiki/Linear_elasticity","Western_Europe",
 "c_L = √(E/ρ)",
 "弾性体中を伝播する波動（縦波・横波・表面波）の理論。超音波非破壊検査・地震工学・音響設計の基礎となる連続体力学の重要分野。",
 "弾性波動,超音波,非破壊検査","elastic wave,ultrasonic,non-destructive testing"),
("em2_027","非破壊検査技術","Non-Destructive Testing NDT","機械工学","計測工学",1920,
 "https://en.wikipedia.org/wiki/Nondestructive_testing","North_America",
 None,
 "製品を破壊せずに内部欠陥・材料特性を評価する技術群。超音波・X線・磁気粒子・浸透探傷・渦電流検査が代表で、航空機・圧力容器・橋梁の保守に不可欠。",
 "非破壊検査,NDT,超音波,X線検査","NDT,non-destructive testing,ultrasonic,X-ray inspection"),
("em2_028","鋳造工学","Casting Engineering","機械工学","製造加工",1700,
 "https://en.wikipedia.org/wiki/Casting_(metalworking)","East_Asia",
 None,
 "溶融金属を型に流し込んで凝固させる成形技術の工学的基盤。砂型・精密鋳造・ダイカストを含み、エンジンブロック・タービン翼等の複雑形状部品製造に用いる。",
 "鋳造,ダイカスト,凝固,成形","casting,die casting,solidification,metal forming"),
("em2_029","鍛造工学","Forging Engineering","機械工学","製造加工",1800,
 "https://en.wikipedia.org/wiki/Forging","East_Asia",
 None,
 "金属を塑性変形させて所定形状に成形する加工技術。熱間・冷間鍛造を含み、素材組織を緻密化して強度・靱性を高める。車軸・クランクシャフト等の高強度部品に用いる。",
 "鍛造,塑性変形,熱間鍛造,組織制御","forging,plastic deformation,hot forging,microstructure"),
("em2_030","板金成形（プレス加工）","Sheet Metal Forming Press","機械工学","製造加工",1850,
 "https://en.wikipedia.org/wiki/Sheet_metal","Western_Europe",
 None,
 "金属板を型で成形するプレス加工技術。ディープドローイング・バルジ成形・スピニングを含み、自動車ボディ・家電筐体・建材の大量生産の基盤。",
 "板金成形,プレス加工,ディープドロー","sheet metal forming,press forming,deep drawing"),
("em2_031","粉末冶金","Powder Metallurgy","機械工学","製造加工",1900,
 "https://en.wikipedia.org/wiki/Powder_metallurgy","Western_Europe",
 None,
 "金属粉末を圧縮・焼結して部品を製造する加工技術。複雑形状・多孔質部品・超硬合金工具の製造に適し、近年は金属AM（金属3Dプリント）と融合が進む。",
 "粉末冶金,焼結,超硬合金","powder metallurgy,sintering,cemented carbide"),
("em2_032","表面処理工学","Surface Engineering Treatment","機械工学","材料表面",1900,
 "https://en.wikipedia.org/wiki/Surface_engineering","Western_Europe",
 None,
 "材料表面の特性（硬さ・耐摩耗・耐食・装飾）を向上させる技術群。めっき・PVD/CVDコーティング・窒化・浸炭処理が代表で、工具寿命と製品耐久性を大幅に改善する。",
 "表面処理,コーティング,PVD,CVD,窒化","surface treatment,coating,PVD,CVD,nitriding"),
("em2_033","ランキンサイクル（蒸気タービン）","Rankine Cycle Steam Turbine","機械工学","熱機関",1859,
 "https://en.wikipedia.org/wiki/Rankine_cycle","Western_Europe",
 "η_R = (W_turbine - W_pump) / Q_boiler",
 "水蒸気を作動流体とする熱機関の基本サイクル。発電所・廃熱回収システム（ORC）の設計基盤で、現代の電力供給の大半を担う。",
 "ランキンサイクル,蒸気タービン,発電","Rankine cycle,steam turbine,power generation"),
("em2_034","ブレイトンサイクル（ガスタービン）","Brayton Cycle Gas Turbine","機械工学","熱機関",1872,
 "https://en.wikipedia.org/wiki/Brayton_cycle","North_America",
 "η_B = 1 - r_p^((1-γ)/γ)",
 "ガスタービン・ジェットエンジンの理想熱力学サイクル。圧縮比と燃焼温度が効率を決定し、発電・航空推進の核心設計理論。",
 "ブレイトンサイクル,ガスタービン,ジェットエンジン","Brayton cycle,gas turbine,jet engine"),
("em2_035","スライディングモード制御","Sliding Mode Control","機械工学","制御工学",1960,
 "https://en.wikipedia.org/wiki/Sliding_mode_control","Eastern_Europe",
 "s = c·e + ė = 0",
 "切換面（スライディング面）に状態を拘束して高い外乱抑制性を実現する非線形制御手法。ロボット・電力変換器・モータ制御に用いる。",
 "スライディングモード制御,非線形制御,ロバスト","sliding mode control,nonlinear control,robust"),
("em2_036","LQR制御（線形二次レギュレータ）","Linear Quadratic Regulator","機械工学","制御工学",1960,
 "https://en.wikipedia.org/wiki/Linear%E2%80%93quadratic_regulator","North_America",
 "J = ∫(x'Qx + u'Ru)dt → min",
 "状態フィードバックゲインを二次形式コスト最小化で最適設計する制御手法。カルマンフィルタと組み合わせてLQGを構成し、航空・宇宙・精密制御に用いる。",
 "LQR,最適制御,状態フィードバック","LQR,optimal control,state feedback"),
("em2_037","カルマンフィルタ","Kalman Filter","機械工学","制御工学",1960,
 "https://en.wikipedia.org/wiki/Kalman_filter","North_America",
 "x̂ = x̂⁻ + K(z - Hx̂⁻)",
 "雑音のある線形動的系の状態を最小二乗誤差で推定する再帰フィルタ。ナビゲーション・ロボット・信号処理の基盤アルゴリズムで、アポロ誘導コンピュータで初実用化。",
 "カルマンフィルタ,状態推定,センサフュージョン","Kalman filter,state estimation,sensor fusion"),
("em2_038","デジタルツイン","Digital Twin","機械工学","インダストリー4.0",2002,
 "https://en.wikipedia.org/wiki/Digital_twin","North_America",
 None,
 "物理システムのリアルタイム仮想複製。センサデータでモデルを継続更新し故障予知・最適化・遠隔監視を可能にする。航空機エンジン・製造ライン・インフラ保守に活用。",
 "デジタルツイン,予知保全,CPS","digital twin,predictive maintenance,cyber-physical system"),
("em2_039","振動制御（アクティブ防振）","Active Vibration Control","機械工学","制御工学",1980,
 "https://en.wikipedia.org/wiki/Active_vibration_control","Japan",
 None,
 "センサ・アクチュエータ・コントローラで振動をリアルタイムに打ち消すアクティブ制振技術。精密加工機・自動車サスペンション・建物制振に用いる。日本の自動車・建築分野が発展をリード。",
 "アクティブ防振,制振,精密制御","active vibration control,vibration damping,precision control"),
("em2_040","機械学習を用いた異常検知","Machine Learning Anomaly Detection Machinery","機械工学","スマート製造",2010,
 "https://en.wikipedia.org/wiki/Anomaly_detection","North_America",
 None,
 "振動・音響・温度センサデータに機械学習を適用して設備の異常を早期検知する手法。工場設備のPdM（予知保全）に不可欠で、IoTセンサと組み合わせてスマート工場を実現する。",
 "異常検知,予知保全,機械学習,IoT","anomaly detection,predictive maintenance,machine learning,IoT"),
("em2_041","流体構造連成解析 FSI","Fluid-Structure Interaction FSI","機械工学","計算力学",1990,
 "https://en.wikipedia.org/wiki/Fluid%E2%80%93structure_interaction","Western_Europe",
 None,
 "流体力と構造変形が相互作用する問題を同時に解くシミュレーション手法。心臓弁・橋梁フラッタ・航空機翼の設計で重要で、CFDと構造FEMを連成して解く。",
 "流体構造連成,FSI,連成解析","fluid-structure interaction,FSI,coupled simulation"),
("em2_042","トポロジー最適化","Topology Optimization","機械工学","計算力学",1988,
 "https://en.wikipedia.org/wiki/Topology_optimization","Denmark",
 None,
 "設計領域内で材料配置をHOMO法やSIMPで最適化する構造設計手法。航空機ブラケット・義肢・自動車構造部品の軽量化に革命をもたらし、AMと組み合わせて効果が大きい。",
 "トポロジー最適化,SIMP,軽量化設計","topology optimization,SIMP,lightweight design"),
("em2_043","運動学・機構解析","Kinematics Mechanism Analysis","機械工学","機械設計",1800,
 "https://en.wikipedia.org/wiki/Kinematics","Western_Europe",
 None,
 "力を考慮せず幾何学的関係のみで機械系の運動を解析する分野。リンク機構・カム・歯車の速度・加速度・軌跡を解析してロボットアーム・工作機械を設計する。",
 "運動学,機構解析,リンク機構","kinematics,mechanism analysis,linkage"),
("em2_044","歯車伝動設計","Gear Drive Design","機械工学","機械設計",1800,
 "https://en.wikipedia.org/wiki/Gear","Western_Europe",
 "i = n1/n2 = z2/z1",
 "平歯車・はすば歯車・かさ歯車などによる動力・運動伝達の設計理論。歯面強度・歯元強度・効率・バックラッシュが設計パラメータ。",
 "歯車,伝動設計,減速機","gear,transmission,reducer,gear ratio"),
("em2_045","軸受設計","Bearing Design","機械工学","機械設計",1870,
 "https://en.wikipedia.org/wiki/Bearing_(mechanical)","Western_Europe",
 "C/P = L10^(1/p)",
 "回転軸を支持する軸受（転がり・すべり）の寿命・負荷能力を設計する理論。L10寿命・動等価荷重・流体潤滑理論が設計の基盤。",
 "軸受設計,転がり軸受,L10寿命","bearing design,rolling bearing,L10 life"),
("em2_046","シール工学（ガスケット・Oリング）","Sealing Engineering Gasket O-ring","機械工学","機械設計",1900,
 "https://en.wikipedia.org/wiki/Seal_(mechanical)","North_America",
 None,
 "流体の漏洩を防止するシール要素の設計と性能評価。静的Oリング・動的メカニカルシール・ガスケット・ラビリンスシールを含み、圧力容器・ポンプ・エンジンに必須。",
 "シール,ガスケット,Oリング,漏洩防止","sealing,gasket,O-ring,leakage prevention"),
("em2_047","バネ・減衰設計","Spring Damper Design","機械工学","機械設計",1800,
 "https://en.wikipedia.org/wiki/Spring_(device)","Western_Europe",
 "F = k·x",
 "弾性エネルギー蓄積・衝撃吸収のためのバネと減衰要素の設計理論。自動車サスペンション・精密計器・振動絶縁に用いる。",
 "バネ,減衰,サスペンション設計","spring,damper,suspension design"),
("em2_048","プロセス制御（化学プラント）","Process Control Chemical Plant","機械工学","プロセス制御",1960,
 "https://en.wikipedia.org/wiki/Process_control","North_America",
 None,
 "石油精製・化学・製薬プラントの温度・圧力・流量・組成を自動制御する分野。DCS（分散制御システム）とPLC・SCADAを組み合わせた階層制御アーキテクチャが基盤。",
 "プロセス制御,DCS,SCADA,化学プラント","process control,DCS,SCADA,chemical plant"),
("em2_049","熱応力解析","Thermal Stress Analysis","機械工学","伝熱工学",1820,
 "https://en.wikipedia.org/wiki/Thermal_stress","Western_Europe",
 "σ_T = -E·α·ΔT/(1-ν)",
 "温度変化による熱膨張が拘束された際に発生する熱応力を解析する分野。原子炉・エンジン・電子基板の熱疲労設計に必須。",
 "熱応力,熱膨張,熱疲労","thermal stress,thermal expansion,thermal fatigue"),
("em2_050","ラピッドプロトタイピング","Rapid Prototyping","機械工学","開発手法",1987,
 "https://en.wikipedia.org/wiki/Rapid_prototyping","North_America",
 None,
 "設計段階の早期に物理モデルを素早く製造して検証する手法。3Dプリンティング・真空注型・CNCを組み合わせ、製品開発サイクルを大幅に短縮する。",
 "ラピッドプロトタイピング,試作,3Dプリント","rapid prototyping,prototype,3D printing"),
# 日本のものづくり技術
("em2_051","トヨタ生産方式（TPS）コア","Toyota Production System Core Concepts","機械工学","日本のものづくり",1945,
 "https://en.wikipedia.org/wiki/Toyota_Production_System","Japan",
 None,
 "大野耐一が開発した製造哲学。ジャストインタイム・自働化・かんばん・ヘイジュンカ（平準化）を柱とし、ムダ・ムラ・ムリの排除により世界最高水準の製造効率を実現。リーン生産の原型。",
 "TPS,トヨタ生産方式,ジャストインタイム,かんばん","TPS,Toyota Production System,just-in-time,kanban"),
("em2_052","ポカヨケ（誤り防止）","Poka-Yoke Error Proofing","機械工学","日本のものづくり",1961,
 "https://en.wikipedia.org/wiki/Poka-yoke","Japan",
 None,
 "新郷重夫が体系化した誤りを物理的・電気的機構で防止する製造方法論。作業者のミスが製品欠陥につながらないよう装置・治具・手順を設計し、不良ゼロを実現する。",
 "ポカヨケ,誤り防止,品質管理","poka-yoke,error proofing,quality control"),
("em2_053","カイゼン（継続的改善）","Kaizen Continuous Improvement","機械工学","日本のものづくり",1950,
 "https://en.wikipedia.org/wiki/Kaizen","Japan",
 None,
 "全員参加で小さな改善を継続的に積み重ねる製造改善哲学。改善提案制度・小集団活動（QCサークル）・5S活動（整理・整頓・清掃・清潔・躾）が実践の柱。",
 "カイゼン,継続的改善,QCサークル,5S","kaizen,continuous improvement,QC circle,5S"),
("em2_054","自働化（にんべんのついた自動化）","Jidoka Autonomation","機械工学","日本のものづくり",1924,
 "https://en.wikipedia.org/wiki/Jidoka","Japan",
 None,
 "豊田佐吉が発明した自動織機に源流を持つ「品質を工程に作り込む」概念。異常が発生したら機械が自律停止し、人間が問題を解決するまで再稼働しない。TPS の二本柱の一つ。",
 "自働化,TPS,品質作り込み,豊田","jidoka,autonomation,Toyota,quality at source"),
("em2_055","からくり改善","Karakuri Kaizen Low-cost Automation","機械工学","日本のものづくり",1990,
 "https://en.wikipedia.org/wiki/Karakuri_kaizen","Japan",
 None,
 "重力・バネ・滑車など動力不要の原理を活用して低コストで工程を改善する日本独自の製造技法。トヨタグループで発展し、省エネ・安全・コスト削減を同時実現する。",
 "からくり改善,低コスト自動化,重力活用","karakuri kaizen,low-cost automation,gravity-powered"),
("em2_056","生産設備のOEE（総合設備効率）","Overall Equipment Effectiveness OEE","機械工学","製造管理",1988,
 "https://en.wikipedia.org/wiki/Overall_equipment_effectiveness","Japan",
 "OEE = 可用率 × 性能率 × 品質率",
 "設備の有効活用度を可用率・性能率・品質率の積で定量化する指標。世界標準KPIとして設備保全戦略（TPM）の核心指標。中島清一（日本）が提唱。",
 "OEE,TPM,設備効率,製造管理","OEE,TPM,equipment effectiveness,manufacturing KPI"),
("em2_057","TPM（全員参加の生産保全）","Total Productive Maintenance TPM","機械工学","製造管理",1971,
 "https://en.wikipedia.org/wiki/Total_productive_maintenance","Japan",
 None,
 "設備保全を全員参加で行い設備停止ゼロ・不良ゼロ・災害ゼロを目指す日本発の製造管理手法。日本プラントメンテナンス協会（JIPM）が体系化。OEEを主要KPIとする。",
 "TPM,全員参加保全,設備管理","TPM,total productive maintenance,equipment management"),
("em2_058","品質機能展開（QFD）","Quality Function Deployment QFD","機械工学","品質工学",1966,
 "https://en.wikipedia.org/wiki/Quality_function_deployment","Japan",
 None,
 "顧客要求を製品仕様・プロセス・品質基準に展開する手法。品質の家（ハウス・オブ・クオリティ）マトリクスが代表ツール。赤尾洋二（神戸大学）が開発。",
 "QFD,品質機能展開,品質の家","QFD,quality function deployment,house of quality"),
("em2_059","タグチメソッド（品質工学）","Taguchi Method Quality Engineering","機械工学","品質工学",1950,
 "https://en.wikipedia.org/wiki/Taguchi_methods","Japan",
 "S/N = -10·log(σ²/μ²)",
 "田口玄一が開発した直交配列表とS/N比を用いたロバスト設計手法。ノイズ要因に対してロバストな製品・プロセスを効率的に設計し、品質と生産性を同時改善する。",
 "タグチメソッド,品質工学,ロバスト設計,S/N比","Taguchi method,quality engineering,robust design,S/N ratio"),
("em2_060","PERT/CPM（プロジェクトスケジューリング）","PERT CPM Project Scheduling","機械工学","プロジェクト管理",1958,
 "https://en.wikipedia.org/wiki/Program_evaluation_and_review_technique","North_America",
 None,
 "プログラム評価・レビュー手法（PERT）とクリティカルパス法（CPM）。複雑な製造・建設プロジェクトの工程を最適化するネットワーク分析手法で今日も広く使用される。",
 "PERT,CPM,クリティカルパス,プロジェクト管理","PERT,CPM,critical path,project scheduling"),
("em2_061","アレニウス方程式（加速劣化試験）","Arrhenius Equation Accelerated Testing","機械工学","信頼性工学",1889,
 "https://en.wikipedia.org/wiki/Arrhenius_equation","Western_Europe",
 "k = A·exp(-Ea/kT)",
 "化学反応速度の温度依存性を示す方程式。材料劣化・電子部品寿命の加速劣化試験に適用され、短時間で長期寿命を推定する。",
 "アレニウス方程式,加速劣化,寿命推定","Arrhenius equation,accelerated degradation,life estimation"),
("em2_062","応力腐食割れ","Stress Corrosion Cracking SCC","機械工学","破壊力学",1940,
 "https://en.wikipedia.org/wiki/Stress_corrosion_cracking","North_America",
 None,
 "引張応力と腐食環境が重畳して生じる割れ。ステンレス鋼の塩化物SCC・黄銅のアンモニアSCCが代表で、化学プラント・海洋構造物の突発破損原因となる。",
 "応力腐食割れ,SCC,腐食破壊","stress corrosion cracking,SCC,corrosion fracture"),
("em2_063","破壊力学（線形弾性・LEFM）","Linear Elastic Fracture Mechanics","機械工学","破壊力学",1957,
 "https://en.wikipedia.org/wiki/Fracture_mechanics","North_America",
 "K = σ√(πa)",
 "亀裂を含む構造体の強度評価理論。応力拡大係数Kと破壊靱性KICを比較して破壊条件を判定し、航空機・圧力容器・橋梁の余寿命を推定する。",
 "破壊力学,応力拡大係数,LEFM","fracture mechanics,stress intensity factor,LEFM"),
("em2_064","疲労き裂進展（Paris則）","Fatigue Crack Propagation Paris Law","機械工学","破壊力学",1963,
 "https://en.wikipedia.org/wiki/Fatigue_crack_growth_rate","North_America",
 "da/dN = C(ΔK)^m",
 "繰り返し荷重下での疲労亀裂の進展速度をΔKの関数で表すParis則。航空機・原子力機器の損傷許容設計と保守点検間隔決定の基盤。",
 "疲労き裂進展,Paris則,損傷許容","fatigue crack propagation,Paris law,damage tolerance"),
("em2_065","クリープ（高温変形）","Creep High Temperature Deformation","機械工学","材料力学",1900,
 "https://en.wikipedia.org/wiki/Creep_(deformation)","Western_Europe",
 "ε̇ = A·σ^n·exp(-Q/RT)",
 "高温下で一定荷重を受けた際の時間依存変形（クリープ）の力学。タービン翼・高圧ボイラ・原子炉構造物の高温設計に不可欠な材料特性。",
 "クリープ,高温変形,タービン翼設計","creep,high temperature deformation,turbine blade"),
("em2_066","プレッシャーベッセル設計","Pressure Vessel Design","機械工学","設計基準",1900,
 "https://en.wikipedia.org/wiki/Pressure_vessel","Western_Europe",
 "σ_hoop = pR/t",
 "内圧を受ける容器の設計理論。フープ応力・長手応力・ASME Boiler and Pressure Vessel Codeに基づく肉厚計算が基本で、石油・化学・原子力プラントに適用される。",
 "圧力容器設計,フープ応力,ASME","pressure vessel design,hoop stress,ASME code"),
("em2_067","騒音振動ハーシュネス（NVH）","Noise Vibration Harshness NVH","機械工学","振動工学",1970,
 "https://en.wikipedia.org/wiki/Noise,_vibration,_and_harshness","North_America",
 None,
 "自動車・航空機・家電の騒音・振動・不快感を低減するNVH設計。周波数応答関数・音響インテンシティ・パネル寄与解析が主要手法で快適性・商品性に直結する。",
 "NVH,騒音,振動,自動車設計","NVH,noise vibration harshness,automotive design"),
("em2_068","エネルギー変換効率最適化","Energy Conversion Efficiency Optimization","機械工学","エネルギー工学",1960,
 "https://en.wikipedia.org/wiki/Energy_conversion_efficiency","Western_Europe",
 "η = W_out/Q_in",
 "熱・機械・電気エネルギー変換の効率を最大化する工学手法。エクセルギー解析・ピンチ解析・多段廃熱回収が代表的アプローチで省エネ設計の核心。",
 "エネルギー変換効率,エクセルギー,廃熱回収","energy conversion efficiency,exergy,waste heat recovery"),
("em2_069","制御系設計（周波数領域）","Frequency Domain Control Design","機械工学","制御工学",1940,
 "https://en.wikipedia.org/wiki/Control_theory","North_America",
 "GH(jω) : ゲイン余裕・位相余裕",
 "ボード線図・ナイキスト線図・根軌跡を用いた周波数領域での制御設計。ゲイン余裕・位相余裕による安定性評価が古典的標準手法。",
 "周波数領域制御,ボード線図,安定余裕","frequency domain control,Bode plot,stability margin"),
("em2_070","有限体積法（CFD）","Finite Volume Method FVM","機械工学","計算流体力学",1971,
 "https://en.wikipedia.org/wiki/Finite_volume_method","Western_Europe",
 "∂/∂t∫_V φdV + ∮_S F·dA = ∫_V S dV",
 "保存形の支配方程式を有限体積で積分して数値的に解く手法。OpenFOAM・StarCCMで実装されCFDの主流数値スキームとなっている。",
 "有限体積法,CFD,OpenFOAM","finite volume method,CFD,OpenFOAM"),
("em2_071","乱流モデル（k-ε・k-ω）","Turbulence Modeling k-epsilon k-omega","機械工学","計算流体力学",1972,
 "https://en.wikipedia.org/wiki/Turbulence_modeling","Western_Europe",
 "∂k/∂t + U·∇k = P_k - ε + ∇·(ν_t/σ_k ∇k)",
 "工学的CFDで広く使われる乱流モデル群。k-εモデル・k-ωモデル・SSTモデルが代表で、レイノルズ平均NS方程式（RANS）の閉じた形を提供する。",
 "乱流モデル,k-ε,k-ω,RANS,CFD","turbulence model,k-epsilon,k-omega,RANS,CFD"),
("em2_072","冷凍・ヒートポンプサイクル","Refrigeration Heat Pump Cycle","機械工学","熱機関",1834,
 "https://en.wikipedia.org/wiki/Heat_pump","Western_Europe",
 "COP_HP = Q_H / W",
 "逆ランキンサイクルによる熱移動機械の設計理論。成績係数（COP）が効率指標で、エアコン・冷蔵庫・ヒートポンプ給湯器の設計基盤。",
 "冷凍サイクル,ヒートポンプ,COP","refrigeration cycle,heat pump,COP"),
("em2_073","ガスケット・フランジ接合設計","Gasket Flange Joint Design","機械工学","設計基準",1900,
 "https://en.wikipedia.org/wiki/Flange","Western_Europe",
 None,
 "配管フランジとガスケットの接合部設計理論。ボルト締付力・ガスケット係数（m・y）・ASME B16.20規格に基づき高圧高温系の漏洩を防止する。",
 "フランジ接合,ガスケット設計,配管","flange joint,gasket design,piping"),
("em2_074","騒音制御（消音器・防音）","Noise Control Muffler Soundproofing","機械工学","騒音工学",1960,
 "https://en.wikipedia.org/wiki/Noise_control","North_America",
 "TL = 20·log(1 + jkL)",
 "音響エネルギーを遮音・吸音・消音で低減する工学。膨張型消音器・リアクティブ消音器・防音壁の設計理論を含み、排気系・工場騒音規制対応に用いる。",
 "騒音制御,消音器,防音,遮音","noise control,muffler,soundproofing,sound insulation"),
("em2_075","スマート構造（圧電アクチュエータ）","Smart Structures Piezoelectric Actuator","機械工学","スマート材料",1990,
 "https://en.wikipedia.org/wiki/Piezoelectricity","Western_Europe",
 "d = piezoelectric strain coefficient",
 "圧電・形状記憶合金・磁歪材料をセンサ・アクチュエータとして組み込んだ適応構造。超精密位置決め・構造ヘルスモニタリング・能動騒音制御に活用される。",
 "スマート構造,圧電,形状記憶合金","smart structure,piezoelectric,shape memory alloy"),
]

# さらに機械工学概念を追加（合計で機械工学サブフィールドを充実させる）
DATA_MECH_EXTRA = [
("em2_076","流体力学 層流・乱流遷移","Laminar Turbulent Transition","機械工学","流体力学",1883,
 "https://en.wikipedia.org/wiki/Laminar%E2%80%93turbulent_transition","Western_Europe",
 "Re = ρVL/μ",
 "流れがレイノルズ数の臨界値を超えて層流から乱流に遷移する現象。パイプ・翼・境界層での遷移機構を理解することで圧損低減・摩擦抵抗最小化を実現する。",
 "層流,乱流,レイノルズ数,遷移","laminar,turbulent,Reynolds number,transition"),
("em2_077","境界層理論","Boundary Layer Theory","機械工学","流体力学",1904,
 "https://en.wikipedia.org/wiki/Boundary_layer","Germany",
 "δ ∝ √(νx/U∞)",
 "プラントルが1904年に提唱した壁面付近の薄い粘性層の理論。航空機翼の揚力・抗力・熱伝達の計算基盤で20世紀流体力学の最重要概念の一つ。",
 "境界層,プラントル,粘性層,揚力","boundary layer,Prandtl,viscous layer,lift"),
("em2_078","多体ダイナミクス","Multibody Dynamics","機械工学","計算力学",1970,
 "https://en.wikipedia.org/wiki/Multibody_system","Western_Europe",
 None,
 "剛体・弾性体を関節・拘束で連結した多体系の運動を解析するシミュレーション手法。ロボット・車両・宇宙機構の動的解析に用いる。ADAMS・SimScapeで実装される。",
 "多体ダイナミクス,ロボット解析,車両動力学","multibody dynamics,robot analysis,vehicle dynamics"),
("em2_079","スプリング・マスシステムモデリング","Spring-Mass System Modeling","機械工学","振動工学",1800,
 "https://en.wikipedia.org/wiki/Mass-spring-damper_model","Western_Europe",
 "mẍ + cẋ + kx = F(t)",
 "1自由度バネ・マス・ダンパ系を基礎とする振動モデル。工学系の振動解析の出発点となり、防振マウント・自動車サスペンション・建物制振の基礎を提供する。",
 "バネマスダンパ,振動モデル,1自由度系","spring-mass-damper,vibration model,single-degree-of-freedom"),
("em2_080","計測工学（センサ・変換器）","Instrumentation Engineering Sensor Transducer","機械工学","計測工学",1900,
 "https://en.wikipedia.org/wiki/Instrumentation","Western_Europe",
 None,
 "物理量（温度・圧力・力・変位・流量）を電気信号に変換するセンサ・変換器とその信号処理の工学。精度・校正・不確かさ評価が品質保証の核心。",
 "センサ,変換器,計測工学,校正","sensor,transducer,instrumentation,calibration"),
]


def run():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()
    all_data = DATA + DATA_MECH_EXTRA
    inserted = 0
    skipped = 0
    for row in all_data:
        cid, name_ja, name_en, subfield, school, era, url, culture, math_f, defn, kw_ja, kw_en = row
        cur.execute("SELECT id FROM engineering_method WHERE id=? OR name_en=?", (cid, name_en))
        if cur.fetchone():
            skipped += 1
            continue
        cur.execute("""INSERT INTO engineering_method
            (id,name_ja,name_en,subfield,school_of_thought,era_start,source_url,culture_region,
             scientific_basis,definition,keywords_ja,keywords_en,
             status,verification_status,data_completeness,
             created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,?,?,
                   'active','url_present',85,datetime('now'),datetime('now'))""",
            (cid,name_ja,name_en,subfield,school,era,url,culture,math_f,defn,kw_ja,kw_en))
        inserted += 1
        if inserted % 50 == 0:
            conn.commit()
            print(f"  {inserted} 件 commit")
    conn.commit()
    cur2 = conn.cursor()
    total = cur2.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"Batch 機械工学: {inserted} 件 INSERT, {skipped} 件 skip, 総計 {total} 件")

if __name__ == "__main__":
    run()
