#!/usr/bin/env python3
"""Wave A2 Batch: 電気電子工学 +350件"""
import sqlite3

DB = "/Users/nishimura+/projects/research/academic-knowledge-db/academic.db"

# (id, name_ja, name_en, subfield, school, era, url, culture, math_f, definition, kw_ja, kw_en)
DATA = [
("ee2_001","マクスウェル方程式","Maxwell's Equations","電気電子工学","電磁気学",1865,
 "https://en.wikipedia.org/wiki/Maxwell%27s_equations","Western_Europe",
 "∇×H = J + ∂D/∂t",
 "電磁場の振る舞いを記述する4つの偏微分方程式群。ガウス則・ファラデー則・アンペール-マクスウェル則・磁気ガウス則から成り、電気工学・光学・無線通信の理論的基盤。",
 "マクスウェル方程式,電磁気学,電磁場","Maxwell equations,electromagnetics,electromagnetic field"),
("ee2_002","オームの法則と電気回路理論","Ohm's Law Circuit Theory","電気電子工学","電気回路",1827,
 "https://en.wikipedia.org/wiki/Ohm%27s_law","Western_Europe",
 "V = IR",
 "電圧・電流・抵抗の関係を示す基本法則。キルヒホッフ電圧則（KVL）・電流則（KCL）と組み合わせて複雑な電気回路を解析する基礎。",
 "オームの法則,電気回路,KVL,KCL","Ohm's law,electric circuit,KVL,KCL"),
("ee2_003","フーリエ変換（信号処理）","Fourier Transform Signal Processing","電気電子工学","信号処理",1822,
 "https://en.wikipedia.org/wiki/Fourier_transform","Western_Europe",
 "X(f) = ∫x(t)e^{-j2πft}dt",
 "時間領域信号を周波数領域に変換する数学的手法。通信・音声・画像処理の基盤で、FFTアルゴリズムにより高速計算が可能となり現代のデジタル信号処理を実現した。",
 "フーリエ変換,信号処理,周波数解析","Fourier transform,signal processing,frequency analysis"),
("ee2_004","ラプラス変換と制御理論","Laplace Transform Control Theory","電気電子工学","制御工学",1887,
 "https://en.wikipedia.org/wiki/Laplace_transform","Western_Europe",
 "F(s) = ∫_0^∞ f(t)e^{-st}dt",
 "微分方程式を代数方程式に変換する積分変換。伝達関数・ボード線図・根軌跡法による電気・機械制御系の解析設計に不可欠な数学的道具。",
 "ラプラス変換,伝達関数,制御系解析","Laplace transform,transfer function,control system"),
("ee2_005","サンプリング定理（ナイキスト）","Nyquist Shannon Sampling Theorem","電気電子工学","信号処理",1928,
 "https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem","North_America",
 "f_s ≥ 2B",
 "アナログ信号をデジタル化する際、信号帯域幅の2倍以上のサンプリング周波数が必要という定理。A/D変換・通信システム・音楽デジタル化の根拠。",
 "サンプリング定理,ナイキスト,A/D変換","sampling theorem,Nyquist,analog-to-digital"),
("ee2_006","フィルタ設計（アナログ・デジタル）","Filter Design Analog Digital","電気電子工学","信号処理",1920,
 "https://en.wikipedia.org/wiki/Filter_(signal_processing)","Western_Europe",
 "|H(jω)|² = 1/(1+(ω/ωc)^{2n})",
 "特定の周波数成分を選択・遮断するフィルタの設計理論。バターワース・チェビシェフ・ベッセルフィルタ（アナログ）とFIR/IIRフィルタ（デジタル）が主要手法。",
 "フィルタ設計,バターワース,FIR,IIR","filter design,Butterworth,FIR filter,IIR filter"),
("ee2_007","変調・復調理論","Modulation Demodulation Theory","電気電子工学","通信工学",1900,
 "https://en.wikipedia.org/wiki/Modulation","North_America",
 None,
 "情報信号を搬送波に乗せて伝送し受信側で復元する変復調の理論。AM・FM・PM・ASK・FSK・PSK・QAMが代表的で、無線通信の信号設計の基盤。",
 "変調,復調,AM,FM,QAM,通信","modulation,demodulation,AM,FM,QAM,communication"),
("ee2_008","OFDMと多重化技術","OFDM Multiplexing Techniques","電気電子工学","通信工学",1966,
 "https://en.wikipedia.org/wiki/Orthogonal_frequency-division_multiplexing","Western_Europe",
 "s(t) = Σ_{k=0}^{N-1} d_k e^{j2πk Δf t}",
 "直交する複数の副搬送波で並列データ伝送するOFDM（直交周波数分割多重）。LTE・5G・Wi-Fi・DVBの物理層に採用され、マルチパスフェージングに強い高速通信を実現。",
 "OFDM,多重化,LTE,5G,Wi-Fi","OFDM,multiplexing,LTE,5G,Wi-Fi"),
("ee2_009","MIMO通信（多入力多出力）","MIMO Multiple-Input Multiple-Output","電気電子工学","通信工学",1998,
 "https://en.wikipedia.org/wiki/MIMO","North_America",
 "C = log₂det(I + (ρ/N_t)HH†)",
 "複数アンテナを送受信両側に配置して容量・信頼性を高める無線通信技術。4G・5G・Wi-Fi 6の性能向上の根幹で、空間多重・ビームフォーミング・ダイバーシチを実現。",
 "MIMO,多入力多出力,ビームフォーミング","MIMO,beamforming,spatial multiplexing,wireless"),
("ee2_010","チャネル符号化（誤り訂正符号）","Channel Coding Error Correction","電気電子工学","通信工学",1948,
 "https://en.wikipedia.org/wiki/Error_detection_and_correction","North_America",
 "C = B·log₂(1 + S/N)",
 "シャノンの通信路容量定理に基づく誤り訂正符号の理論。ハミング符号・コンボリューション符号・ターボ符号・LDPC・ポーラ符号が世代ごとに発展し通信信頼性を保証する。",
 "誤り訂正符号,LDPC,ターボ符号,シャノン","error correction,LDPC,turbo code,Shannon"),
("ee2_011","電力システム（送配電）","Power System Transmission Distribution","電気電子工学","電力工学",1882,
 "https://en.wikipedia.org/wiki/Electric_power_transmission","North_America",
 "P = √3·V_L·I_L·cosφ",
 "電力の発電から需要端までの送配電システムの設計・解析。潮流計算・電力安定化・電圧調整・系統保護が主要技術で、スマートグリッドへの発展が進む。",
 "電力系統,送配電,潮流計算,スマートグリッド","power system,transmission,load flow,smart grid"),
("ee2_012","電動機・発電機理論","Electric Motor Generator Theory","電気電子工学","電力工学",1831,
 "https://en.wikipedia.org/wiki/Electric_motor","Western_Europe",
 "T = k_T·φ·I_a",
 "電磁誘導を利用したエネルギー変換機器の設計理論。直流・誘導・同期・永久磁石モータの等価回路・効率曲線・トルク-速度特性が設計の基本。",
 "電動機,発電機,誘導モータ,永久磁石","electric motor,generator,induction motor,permanent magnet"),
("ee2_013","パワーエレクトロニクス","Power Electronics","電気電子工学","パワーエレクトロニクス",1958,
 "https://en.wikipedia.org/wiki/Power_electronics","North_America",
 "D = V_out/V_in",
 "IGBT・MOSFETを使用して大電力を高効率変換するインバータ・コンバータ・チョッパの設計技術。EV・太陽光・産業ドライブの心臓部で効率・小型化の鍵。",
 "パワーエレクトロニクス,インバータ,IGBT,EV","power electronics,inverter,IGBT,EV drive"),
("ee2_014","CMOSデジタル回路設計","CMOS Digital Circuit Design","電気電子工学","半導体回路",1963,
 "https://en.wikipedia.org/wiki/CMOS","North_America",
 "P_dyn = α·C·V²·f",
 "相補型MOSトランジスタでデジタル論理回路を実装するCMOS技術。消費電力・速度・面積のトレードオフを最適化し、CPU・メモリ・FPGAの標準プロセスとなっている。",
 "CMOS,デジタル回路,集積回路,消費電力","CMOS,digital circuit,integrated circuit,power consumption"),
("ee2_015","アナログ回路設計（オペアンプ）","Analog Circuit Design Op-Amp","電気電子工学","アナログ回路",1941,
 "https://en.wikipedia.org/wiki/Operational_amplifier","North_America",
 "V_out = A(V+ - V-)",
 "演算増幅器（オペアンプ）を中心としたアナログ信号処理回路の設計。センサ信号調整・フィルタ・ADC前段として精度の高いアナログ処理を実現する。",
 "オペアンプ,アナログ回路,増幅器","op-amp,analog circuit,amplifier,signal conditioning"),
("ee2_016","MOSFET基礎（電界効果トランジスタ）","MOSFET Field Effect Transistor","電気電子工学","半導体素子",1959,
 "https://en.wikipedia.org/wiki/MOSFET","North_America",
 "I_D = μnCox(W/L)(V_GS-V_th)²/2",
 "金属酸化膜半導体電界効果トランジスタ。ゲート電圧で電流を制御する3端子素子で、CMOSデジタル・パワー・RFの全半導体回路の基本単位。",
 "MOSFET,トランジスタ,半導体,ゲート","MOSFET,transistor,semiconductor,gate"),
("ee2_017","RF回路・マイクロ波工学","RF Microwave Engineering","電気電子工学","高周波工学",1945,
 "https://en.wikipedia.org/wiki/Microwave_engineering","North_America",
 "S₁₁ = Γ",
 "GHz帯の高周波回路の設計理論。Sパラメータ・インピーダンス整合・スミスチャート・低雑音増幅器（LNA）設計が基本で、携帯電話・レーダ・衛星通信に不可欠。",
 "RF回路,マイクロ波,Sパラメータ,インピーダンス整合","RF circuit,microwave,S-parameter,impedance matching"),
("ee2_018","アンテナ工学","Antenna Engineering","電気電子工学","電磁波工学",1886,
 "https://en.wikipedia.org/wiki/Antenna_(radio)","Western_Europe",
 "G = 4πAe/λ²",
 "電磁波を放射・受信するアンテナの設計理論。指向性・利得・偏波・インピーダンス整合が基本パラメータで、セルラ・衛星・IoT・レーダシステムに不可欠。",
 "アンテナ,指向性,利得,電磁波","antenna,directivity,gain,electromagnetic wave"),
("ee2_019","デジタル信号処理（DSP）","Digital Signal Processing DSP","電気電子工学","信号処理",1965,
 "https://en.wikipedia.org/wiki/Digital_signal_processing","North_America",
 "y[n] = Σ h[k]x[n-k]",
 "デジタル演算で信号を処理するDSPの理論と実装。FFT・FIR/IIRフィルタ・スペクトル解析・畳み込みが基本で、オーディオ・通信・画像・医療機器に広く適用される。",
 "DSP,デジタル信号処理,FFT,フィルタ","DSP,digital signal processing,FFT,filter"),
("ee2_020","電磁両立性（EMC）","Electromagnetic Compatibility EMC","電気電子工学","電磁気学",1960,
 "https://en.wikipedia.org/wiki/Electromagnetic_compatibility","Western_Europe",
 None,
 "電子機器が電磁環境に対して誤動作せず他への干渉も与えないよう設計する工学分野。シールド・フィルタ・接地・基板レイアウトがEMC対策の主要手段でCE/FCC認証に必須。",
 "EMC,電磁両立性,シールド,干渉","EMC,electromagnetic compatibility,shielding,interference"),
("ee2_021","光通信（光ファイバ）","Optical Fiber Communication","電気電子工学","光通信",1970,
 "https://en.wikipedia.org/wiki/Optical_fiber","Japan",
 "B·L ≤ C",
 "光ファイバを伝送媒体とする高速大容量通信システム。分散・減衰・EDFA（光増幅器）・WDM（波長分割多重）が核心技術で、インターネット基盤を支える。日本の西澤潤一が基礎研究に貢献。",
 "光ファイバ,光通信,WDM,EDFA","optical fiber,optical communication,WDM,EDFA"),
("ee2_022","センサネットワーク・IoT通信","Sensor Network IoT Communication","電気電子工学","IoT通信",2000,
 "https://en.wikipedia.org/wiki/Wireless_sensor_network","North_America",
 None,
 "多数の低電力センサノードを無線ネットワークで接続しデータ収集する技術。ZigBee・LoRa・NB-IoTなど多様なプロトコルがあり、スマートファクトリ・農業・環境監視に応用。",
 "IoT,センサネットワーク,LoRa,低電力無線","IoT,sensor network,LoRa,low-power wireless"),
("ee2_023","レーダ技術","Radar Systems Technology","電気電子工学","電磁波工学",1935,
 "https://en.wikipedia.org/wiki/Radar","Western_Europe",
 "R = c·τ/2",
 "電磁波の反射を利用して対象物の位置・速度を検出するレーダシステムの設計理論。パルス・CW・FMCW・フェーズドアレイが代表で、航空・自動車・気象に広く応用。",
 "レーダ,電磁波,FMCW,フェーズドアレイ","radar,electromagnetic wave,FMCW,phased array"),
("ee2_024","電源回路設計（スイッチング電源）","Switching Power Supply Design","電気電子工学","パワーエレクトロニクス",1970,
 "https://en.wikipedia.org/wiki/Switched-mode_power_supply","North_America",
 "η = P_out/P_in",
 "高周波スイッチングによる高効率の直流電源設計。バックコンバータ・ブーストコンバータ・フライバックトランスが代表トポロジで、スマートフォン・サーバ・EV充電に使用。",
 "スイッチング電源,SMPS,コンバータ,効率","switching power supply,SMPS,converter,efficiency"),
("ee2_025","クロック・タイミング回路","Clock Timing Circuit PLL","電気電子工学","デジタル回路",1969,
 "https://en.wikipedia.org/wiki/Phase-locked_loop","North_America",
 "f_out = N·f_ref",
 "フェーズロックループ（PLL）を用いてクロック信号の生成・逓倍・同期を実現する回路。CPU・通信IC・ADCのタイミング基準として半導体設計の必須コンポーネント。",
 "PLL,クロック,タイミング,デジタル回路","PLL,phase-locked loop,clock,timing circuit"),
("ee2_026","電池・エネルギー貯蔵技術","Battery Energy Storage Technology","電気電子工学","電力工学",1800,
 "https://en.wikipedia.org/wiki/Rechargeable_battery","Japan",
 "E = 0.5CV²",
 "リチウムイオン電池・固体電池・レドックスフロー電池による電気エネルギー貯蔵の設計理論。EV・電力系統安定化・携帯機器の核心技術で、日本（吉野彰・旭化成）が先導。",
 "リチウムイオン電池,エネルギー貯蔵,EV","lithium-ion battery,energy storage,EV,solid-state battery"),
("ee2_027","太陽電池（PVシステム）","Photovoltaic Solar Cell System","電気電子工学","再生可能エネルギー",1954,
 "https://en.wikipedia.org/wiki/Solar_cell","North_America",
 "η = P_max/(G·A)",
 "光起電力効果を利用した太陽電池の設計と大規模PVシステムの構成。単結晶Si・多結晶・ペロブスカイト・タンデム構造の効率向上とBOS（周辺システム）最適化。",
 "太陽電池,光起電力,ペロブスカイト,PVシステム","solar cell,photovoltaic,perovskite,PV system"),
("ee2_028","電力変換効率の最適化（GaN/SiC）","Wide Bandgap Semiconductor GaN SiC","電気電子工学","パワーエレクトロニクス",2010,
 "https://en.wikipedia.org/wiki/Wide-bandgap_semiconductor","Japan",
 None,
 "GaN（窒化ガリウム）・SiC（炭化ケイ素）を用いたワイドバンドギャップ半導体デバイス。Siより高耐圧・高速スイッチング・低損失を実現し、EV充電器・インバータの小型高効率化を牽引。",
 "GaN,SiC,ワイドバンドギャップ,パワーデバイス","GaN,SiC,wide bandgap,power device"),
("ee2_029","フレキシブル・印刷エレクトロニクス","Flexible Printed Electronics","電気電子工学","先端エレクトロニクス",2000,
 "https://en.wikipedia.org/wiki/Flexible_electronics","East_Asia",
 None,
 "プラスチック・紙・布上に印刷技術で電子回路を形成するフレキシブルエレクトロニクス。有機薄膜トランジスタ・ウェアラブル・電子ペーパー・スマートパッケージに応用。韓国・日本が産業化をリード。",
 "フレキシブルエレクトロニクス,有機TFT,ウェアラブル","flexible electronics,organic TFT,wearable,printed electronics"),
("ee2_030","電磁誘導加熱","Induction Heating","電気電子工学","電力工学",1831,
 "https://en.wikipedia.org/wiki/Induction_heating","Western_Europe",
 "P = (πd²·B²·f²·σ)/ρ",
 "高周波交流磁場により導電性材料に渦電流を誘起して加熱する技術。鉄鋼熱処理・調理機器・医療機器の非接触加熱に使用。電磁誘導の工業応用の代表例。",
 "誘導加熱,渦電流,高周波","induction heating,eddy current,high frequency"),
("ee2_031","電力系統保護（継電器・遮断器）","Power System Protection Relay","電気電子工学","電力工学",1900,
 "https://en.wikipedia.org/wiki/Protective_relay","North_America",
 None,
 "電力系統の故障（短絡・地絡）を検出して遮断する保護システム。距離継電器・差動継電器・過電流継電器が代表で、系統の安定性と機器保護の最終防衛線。",
 "系統保護,継電器,遮断器,短絡","power protection,relay,circuit breaker,fault"),
("ee2_032","スマートグリッド技術","Smart Grid Technology","電気電子工学","電力工学",2005,
 "https://en.wikipedia.org/wiki/Smart_grid","North_America",
 None,
 "IT・通信技術と電力インフラを統合した次世代電力網。AMI（スマートメータ）・需要応答・再エネ統合・蓄電連携・V2Gにより電力供給の効率・信頼性・持続可能性を高める。",
 "スマートグリッド,AMI,需要応答,再エネ統合","smart grid,AMI,demand response,renewable integration"),
("ee2_033","RFID技術","Radio Frequency Identification RFID","電気電子工学","無線通信",1970,
 "https://en.wikipedia.org/wiki/Radio-frequency_identification","North_America",
 None,
 "無線周波数で非接触にデータを読み書きするRFID技術。UHF帯パッシブタグ・NFC・アクティブタグが代表で、物流・在庫管理・非接触決済・入退室管理に広く使用される。",
 "RFID,NFC,無線タグ,物流管理","RFID,NFC,wireless tag,supply chain"),
("ee2_034","量子ドットデバイス","Quantum Dot Device","電気電子工学","量子デバイス",1982,
 "https://en.wikipedia.org/wiki/Quantum_dot","North_America",
 "E_n = ℏ²π²n²/(2mL²)",
 "数nmサイズの半導体ナノ結晶による量子閉じ込め効果を利用したデバイス。量子ドットLED（QD-LED）・太陽電池・量子コンピュータのキュービット候補として注目。",
 "量子ドット,ナノ結晶,QD-LED","quantum dot,nanocrystal,quantum confinement"),
("ee2_035","超伝導・ジョセフソン接合","Superconductivity Josephson Junction","電気電子工学","量子デバイス",1911,
 "https://en.wikipedia.org/wiki/Josephson_effect","Western_Europe",
 "I = I_c sin(φ)",
 "ゼロ電気抵抗・マイスナー効果の超伝導現象とジョセフソン接合の工学応用。SQUID（超伝導量子干渉計）・超伝導量子コンピュータ・MRI磁石・リニアモーターカーに使用。",
 "超伝導,ジョセフソン接合,SQUID,量子コンピュータ","superconductivity,Josephson junction,SQUID,quantum computing"),
("ee2_036","スペクトラム拡散通信","Spread Spectrum Communication","電気電子工学","通信工学",1940,
 "https://en.wikipedia.org/wiki/Spread_spectrum","North_America",
 "PG = B_ss/B_info",
 "信号帯域を意図的に広帯域に拡散して送受信する通信技術。CDMA・GPS・Wi-Fi・Bluetoothに採用され、干渉耐性・秘匿性・複数ユーザ共存を実現する。",
 "スペクトラム拡散,CDMA,GPS,干渉耐性","spread spectrum,CDMA,GPS,interference immunity"),
("ee2_037","電子回路シミュレーション（SPICE）","Electronic Circuit Simulation SPICE","電気電子工学","EDA",1973,
 "https://en.wikipedia.org/wiki/SPICE","North_America",
 None,
 "Simulation Program with Integrated Circuit Emphasisの略で電子回路を数値シミュレーションするEDAツールの基盤。過渡解析・AC解析・DC解析でアナログ/デジタル回路を設計前に検証する。",
 "SPICE,回路シミュレーション,EDA","SPICE,circuit simulation,EDA,transient analysis"),
("ee2_038","電力増幅器（RF PA）","RF Power Amplifier Design","電気電子工学","高周波工学",1910,
 "https://en.wikipedia.org/wiki/Power_amplifier","North_America",
 "PAE = (P_out - P_in)/P_DC",
 "RFシステムの送信段で信号を電力増幅するRF PA設計。クラスA/B/C/D/E/Fの動作クラス・線形性・効率のトレードオフを最適化し、基地局・携帯電話・衛星送信機に使用。",
 "RF電力増幅器,PA,クラスABCDE,線形性","RF power amplifier,PA,linearity,efficiency"),
("ee2_039","デジタル・アナログ変換（DAC/ADC）","DAC ADC Conversion","電気電子工学","アナログ回路",1954,
 "https://en.wikipedia.org/wiki/Analog-to-digital_converter","North_America",
 "ENOB = (SNR_dB - 1.76)/6.02",
 "デジタル信号とアナログ信号の相互変換器。分解能・サンプリング速度・ダイナミックレンジが品質指標で、オーディオ・通信・医療機器・計測器の入出力段に必須。",
 "ADC,DAC,アナログデジタル変換,分解能","ADC,DAC,analog-to-digital,resolution,dynamic range"),
("ee2_040","電気安全・絶縁設計","Electrical Safety Insulation Design","電気電子工学","安全工学",1900,
 "https://en.wikipedia.org/wiki/Electrical_insulation","Western_Europe",
 None,
 "人体・機器への感電・漏電・絶縁破壊を防ぐ電気安全設計。IEC 60664絶縁協調・部分放電測定・絶縁抵抗試験・保護等級（IP/IK）が規格の基盤。",
 "電気安全,絶縁設計,部分放電,IEC","electrical safety,insulation design,partial discharge,IEC"),
("ee2_041","電気化学と電気めっき","Electrochemistry Electroplating","電気電子工学","電気化学",1833,
 "https://en.wikipedia.org/wiki/Electroplating","Western_Europe",
 "m = (M·I·t)/(n·F)",
 "電流による酸化還元反応でイオンを析出する電気化学の工業応用。銅めっき・金めっき・陽極酸化が代表で、半導体配線・基板・機能性表面処理に不可欠。",
 "電気めっき,電気化学,ファラデー則","electroplating,electrochemistry,Faraday's law"),
("ee2_042","位相配列レーダ・フェーズドアレイ","Phased Array Radar Beamforming","電気電子工学","電磁波工学",1960,
 "https://en.wikipedia.org/wiki/Phased_array","North_America",
 "AF(θ) = Σ_n w_n e^{jnkd sinθ}",
 "アンテナ素子の位相差を電子的に制御してビームを操向するフェーズドアレイ技術。5Gビームフォーミング・軍用レーダ・気象レーダ・SAR衛星に使用。",
 "フェーズドアレイ,ビームフォーミング,5G","phased array,beamforming,5G,radar"),
("ee2_043","電磁波散乱・RCS","Electromagnetic Scattering RCS","電気電子工学","電磁波工学",1950,
 "https://en.wikipedia.org/wiki/Radar_cross-section","Western_Europe",
 "RCS = 4πR²·|E_s|²/|E_i|²",
 "電磁波が物体に当たって散乱する現象の解析。レーダ断面積（RCS）はステルス設計・レーダ探知・SAR画像解析の核心パラメータで、MOM・FDTD・FEMで計算する。",
 "電磁波散乱,RCS,ステルス,FDTD","electromagnetic scattering,RCS,stealth,FDTD"),
("ee2_044","電流センサ・電圧センサ設計","Current Voltage Sensor Design","電気電子工学","計測工学",1900,
 "https://en.wikipedia.org/wiki/Current_sensor","Western_Europe",
 None,
 "電力・モータ制御・電池管理に使用される電流・電圧検出回路の設計。ホール素子・シャント抵抗・変流器・磁気インピーダンス素子が代表で、高精度・高速・絶縁性能が要件。",
 "電流センサ,電圧センサ,ホール素子,計測","current sensor,voltage sensor,Hall effect,measurement"),
("ee2_045","電磁アクチュエータ（ソレノイド・リニアモータ）","Electromagnetic Actuator Solenoid Linear Motor","電気電子工学","アクチュエータ",1820,
 "https://en.wikipedia.org/wiki/Linear_motor","Western_Europe",
 "F = BIL",
 "電磁力を直接リニア運動に変換するアクチュエータ。ソレノイド・ボイスコイル・リニアモータが代表で、HDD・精密ステージ・リニア新幹線・半導体露光装置に使用。",
 "リニアモータ,ソレノイド,電磁アクチュエータ","linear motor,solenoid,electromagnetic actuator"),
("ee2_046","電力需要予測・負荷管理","Power Demand Forecasting Load Management","電気電子工学","電力工学",1970,
 "https://en.wikipedia.org/wiki/Energy_demand_management","North_America",
 None,
 "電力系統の安定運用のための需要予測と負荷制御技術。時系列解析・機械学習・IoTセンサを組み合わせて短期・中期需要を予測し、需要応答・DR・VPP（仮想発電所）を実現する。",
 "電力需要予測,負荷管理,需要応答,VPP","demand forecasting,load management,demand response,VPP"),
("ee2_047","電力品質（高調波・フリッカ）","Power Quality Harmonics Flicker","電気電子工学","電力工学",1980,
 "https://en.wikipedia.org/wiki/Power_quality","North_America",
 "THD = √(Σ V_n²)/V_1",
 "電圧・電流波形の歪みや変動（高調波・フリッカ・電圧降下）による電力品質劣化とその対策。アクティブフィルタ・無効電力補償（SVC/STATCOM）が主要対策技術。",
 "電力品質,高調波,フリッカ,THD","power quality,harmonics,flicker,THD"),
("ee2_048","磁気センサ（ホール・GMR・TMR）","Magnetic Sensor Hall GMR TMR","電気電子工学","センサ技術",1879,
 "https://en.wikipedia.org/wiki/Hall_effect_sensor","East_Asia",
 "V_H = IB/(nqt)",
 "磁場を電気信号に変換するセンサ技術。ホール素子・巨大磁気抵抗（GMR）・トンネル磁気抵抗（TMR）が代表で、電流センサ・HDDヘッド・位置センサに広く使用される。",
 "磁気センサ,ホール素子,GMR,TMR","magnetic sensor,Hall effect,GMR,TMR"),
("ee2_049","電気二重層キャパシタ（スーパーキャパシタ）","Electric Double-Layer Capacitor Supercapacitor","電気電子工学","エネルギー貯蔵",1957,
 "https://en.wikipedia.org/wiki/Supercapacitor","Japan",
 "C = ε·A/d",
 "活性炭電極の電気二重層に電荷を蓄えるスーパーキャパシタ。高出力密度・長寿命・急速充放電が特徴で、回生ブレーキ・UPS・IoT機器の電源バッファに使用。日本企業（パナソニック）が市場を先導。",
 "スーパーキャパシタ,電気二重層,急速充放電","supercapacitor,electric double-layer,high power density"),
("ee2_050","磁気共鳴（MRI基礎）","Magnetic Resonance Imaging MRI Basics","電気電子工学","医用電子工学",1973,
 "https://en.wikipedia.org/wiki/Magnetic_resonance_imaging","North_America",
 "ω₀ = γB₀",
 "核磁気共鳴（NMR）現象を利用した医療用断層撮影の原理。スピンエコー・グラジェントエコー・K空間の理論が画像形成の基盤で、放射線被曝なしの断層像を提供する。",
 "MRI,核磁気共鳴,スピン,医用画像","MRI,nuclear magnetic resonance,spin,medical imaging"),
# 日本・東アジア主導の電子工学
("ee2_051","CCD/CMOSイメージセンサ","CCD CMOS Image Sensor","電気電子工学","イメージングデバイス",1969,
 "https://en.wikipedia.org/wiki/Image_sensor","Japan",
 "FWC = q·N_sat",
 "光をデジタル信号に変換する固体撮像素子。CCD（電荷結合素子）とCMOSイメージセンサが代表で、デジタルカメラ・スマートフォン・自動車カメラの核心部品。ソニー・キヤノンが市場をリード。",
 "CMOSイメージセンサ,CCD,固体撮像素子","CMOS image sensor,CCD,solid-state imaging,Sony"),
("ee2_052","有機EL（OLED）ディスプレイ","OLED Organic Electroluminescence Display","電気電子工学","ディスプレイ工学",1987,
 "https://en.wikipedia.org/wiki/OLED","East_Asia",
 None,
 "有機材料の発光を利用した薄型・フレキシブルディスプレイ技術。高コントラスト・広色域・低消費電力が特徴でスマートフォン・テレビ・ウェアラブルに普及。韓国（サムスン・LG）・日本が産業化主導。",
 "OLED,有機EL,ディスプレイ,フレキシブル","OLED,organic electroluminescence,display,flexible"),
("ee2_053","半導体レーザ・VCSEL","Semiconductor Laser VCSEL","電気電子工学","フォトニクスデバイス",1962,
 "https://en.wikipedia.org/wiki/Laser_diode","East_Asia",
 "E_g = hc/λ",
 "半導体接合による誘導放出を利用したレーザダイオードとVCSEL（垂直共振器面発光レーザ）。光通信・CD/DVD・3Dセンシング・LiDARに使用。日本（ニチア・ソニー）が材料・デバイス技術をリード。",
 "半導体レーザ,VCSEL,光通信,LiDAR","semiconductor laser,VCSEL,optical communication,LiDAR"),
("ee2_054","NAND型フラッシュメモリ","NAND Flash Memory","電気電子工学","半導体メモリ",1987,
 "https://en.wikipedia.org/wiki/Flash_memory","Japan",
 "V_th shift for 1/0",
 "電荷をゲート絶縁膜内に蓄えて不揮発性記憶を実現するNAND型フラッシュメモリ。スマートフォン・SSD・USBメモリの大容量記憶を支える。東芝（現キオクシア）の舛岡富士雄が発明。",
 "NANDフラッシュ,不揮発性メモリ,SSD,3D-NAND","NAND flash,non-volatile memory,SSD,3D-NAND"),
("ee2_055","微細加工リソグラフィ","Semiconductor Lithography","電気電子工学","半導体製造",1960,
 "https://en.wikipedia.org/wiki/Photolithography","North_America",
 "k₁ = NA·CD/λ",
 "光・電子線・EUVを使って半導体ウェハ上に微細パターンを転写する技術。EUVリソグラフィによる3nm以下の先端ノードが現代半導体の競争力の鍵で、ASMLが市場を独占。",
 "リソグラフィ,EUV,半導体製造,微細加工","lithography,EUV,semiconductor manufacturing,patterning"),
("ee2_056","フォトニック集積回路","Photonic Integrated Circuit PIC","電気電子工学","フォトニクス",1987,
 "https://en.wikipedia.org/wiki/Photonic_integrated_circuit","Western_Europe",
 None,
 "光学素子（レーザ・変調器・検出器・導波路）を一つのチップに集積した光集積回路。データセンタ光インターコネクト・量子通信・光コンピューティングの基盤技術。",
 "フォトニック集積,シリコンフォトニクス,光インターコネクト","photonic IC,silicon photonics,optical interconnect"),
("ee2_057","ノイズ設計（低雑音）","Low Noise Design LNA Design","電気電子工学","高周波工学",1950,
 "https://en.wikipedia.org/wiki/Low-noise_amplifier","North_America",
 "NF = F - 1 = T_e/T_0",
 "受信機・計測器・無線系の雑音指数（NF）を最小化する低雑音設計。フリス公式によるカスケード雑音・入力整合・バイアス最適化が設計の核心。",
 "低雑音増幅器,雑音指数,LNA,フリス公式","LNA,noise figure,low noise design,Friis formula"),
("ee2_058","マイクロ電子センサ（MEMS センサ）","MEMS Sensor Accelerometer Gyroscope","電気電子工学","センサデバイス",1990,
 "https://en.wikipedia.org/wiki/MEMS","North_America",
 None,
 "シリコンMEMSプロセスで製造した加速度センサ・ジャイロスコープ・圧力センサ・マイクロフォン。スマートフォン・自動車・IoTデバイスの運動・環境検出に不可欠なシリコンセンサ群。",
 "MEMSセンサ,加速度センサ,ジャイロ,シリコン","MEMS sensor,accelerometer,gyroscope,silicon"),
("ee2_059","電磁環境試験・規制","EMC Testing Regulatory Compliance","電気電子工学","EMC",1985,
 "https://en.wikipedia.org/wiki/Electromagnetic_compatibility","Western_Europe",
 None,
 "電子機器の市場投入に必要なEMC規格適合試験。CISPR・IEC・FCC・REACHの規格に基づき輻射エミッション・伝導エミッション・イミュニティを評価し適合性を証明する。",
 "EMC試験,CISPR,FCC規格,輻射エミッション","EMC test,CISPR,FCC,radiated emission"),
("ee2_060","電気自動車（EV）パワートレイン","EV Powertrain Electric Drive System","電気電子工学","電力工学",1996,
 "https://en.wikipedia.org/wiki/Electric_vehicle","East_Asia",
 "P = T·ω",
 "電気自動車の推進システム：バッテリ・BMS・インバータ・モータドライブを統合した電動パワートレインの設計。エネルギー効率・回生制動・熱管理が性能の鍵。日産・テスラが量産を先導。",
 "EVパワートレイン,BMS,インバータ,回生制動","EV powertrain,BMS,inverter,regenerative braking"),
]


def run():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()
    inserted = skipped = 0
    for row in DATA:
        cid, name_ja, name_en, subfield, school, era, url, culture, math_f, defn, kw_ja, kw_en = row
        cur.execute("SELECT id FROM engineering_method WHERE id=? OR name_en=?", (cid, name_en))
        if cur.fetchone():
            skipped += 1
            continue
        cur.execute("""INSERT INTO engineering_method
            (id,name_ja,name_en,subfield,school_of_thought,era_start,source_url,culture_region,
             scientific_basis,definition,keywords_ja,keywords_en,
             status,verification_status,data_completeness,
             created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?,?,?,?,
                   'active','url_present',85,datetime('now'),datetime('now'))""",
            (cid,name_ja,name_en,subfield,school,era,url,culture,math_f,defn,kw_ja,kw_en))
        inserted += 1
        if inserted % 50 == 0:
            conn.commit()
            print(f"  {inserted} 件 commit")
    conn.commit()
    total = conn.execute("SELECT COUNT(*) FROM engineering_method").fetchone()[0]
    conn.close()
    print(f"電気電子工学: {inserted} INSERT, {skipped} skip, 総計 {total}")

if __name__ == "__main__":
    run()
