#!/usr/bin/env python3
"""Generate diffusion_adoption_user entries 633-714 (82 entries)."""
import json

entries = [
    {"id": f"inno_diff_{i}", "name_ja": t[0], "name_en": t[1], "definition": t[2], "impact_summary": t[3], "subfield": "diffusion_adoption_user", "school_of_thought": t[4], "era_start": t[5], "innovation_type": "diffusion", "schumpeter_layer": t[6], "cognitive_mechanism": t[7], "key_researchers": t[8], "key_works": t[9], "opposing_concept_names": t[10], "keywords_ja": t[11], "keywords_en": t[12], "category": "C_processes"}
    for i, t in enumerate([
        ("技術標準化と採用の臨界量", "Standardization and Critical Mass in Adoption", "技術標準の確立が採用の臨界量到達を加速するメカニズム。Farrell & Saloner（1985）は標準化の経済分析を提供し、互換性の価値がネットワーク効果を通じて採用を加速することを示した。標準化戦争（VHS vs Betamax、Blu-ray vs HD DVD）の歴史的分析が理論的基盤。David & Greenstein（1990）は標準の分類（デファクト、デジュール、委員会標準）を体系化した。", "技術標準政策とITU/ISO/IEC等の標準化機構の運営に理論的根拠を提供した。", "標準化経済学", 1985, "macro", "互換性とネットワーク効果の標準化加速", "Joseph Farrell; Garth Saloner; Paul David; Shane Greenstein", "Standardization, Compatibility, and Innovation (Farrell & Saloner, 1985)", "独自規格至上主義, 標準不要論", "技術標準, 互換性, 臨界量, 標準化戦争", "technology standards, compatibility, critical mass, standards war"),
        ("モバイルヘルス（mHealth）の患者採用", "Patient Adoption of Mobile Health (mHealth)", "スマートフォンベースの健康管理アプリ・遠隔モニタリングの患者採用を分析。Akter et al.（2013）はmHealthサービス品質モデルを構築し、信頼性・応答性・保証性が採用に与える影響を分析した。慢性疾患管理、服薬リマインダー、遠隔診察が主要ユースケース。", "デジタルヘルス戦略とmHealth規制の理論的根拠を提供した。", "mHealth採用論", 2013, "micro", "健康動機と技術利便性の統合", "Shahriar Akter; John D'Ambra; Pradeep Ray", "Continuance of mHealth Services at the Bottom of the Pyramid (Akter et al., 2013)", "対面診療至上主義, mHealthの信頼性疑念", "mHealth, モバイルヘルス, 患者採用, 遠隔モニタリング", "mHealth, mobile health, patient adoption, remote monitoring"),
        ("ドローン配送の消費者受容", "Consumer Acceptance of Drone Delivery", "商品配送用ドローンに対する消費者受容を分析。Yoo et al.（2018）はドローン配送の知覚リスク（プライバシー侵害、物理的危険、騒音）と知覚便益（速度、利便性）のトレードオフを分析した。Amazon Prime Air、Wing（Alphabet）が先駆的事例。", "ドローン配送規制と都市物流政策の理論的根拠を提供した。", "ドローン受容論", 2018, "micro", "利便性とリスクの空間的評価", "Wooseok Yoo; Eunil Park; Jinyoung Han", "Consumer acceptance of drone delivery (Yoo et al., 2018)", "従来型物流至上主義, ドローン万能論", "ドローン配送, 消費者受容, 安全性, プライバシー", "drone delivery, consumer acceptance, safety, privacy"),
        ("デジタルID・eKYCの消費者採用", "Consumer Adoption of Digital ID and eKYC", "デジタル本人確認（eKYC）と分散型デジタルID（DID）の消費者採用障壁を分析。Sullivan（2018）はデジタルIDの信頼フレームワークを構築し、プライバシー、利便性、セキュリティの三角関係を分析した。インドAadhaar、エストニアe-IDが制度的実装例。", "デジタルID政策と金融包摂の理論的根拠を提供した。", "デジタルID論", 2018, "macro", "アイデンティティ管理とプライバシー緊張", "Clare Sullivan; Eric Verheul; Bart Jacobs", "Digital Identity (Sullivan, 2018)", "紙ベース本人確認至上主義, 完全匿名性要求", "デジタルID, eKYC, 本人確認, 分散型ID", "digital ID, eKYC, identity verification, decentralized ID"),
        ("プラント由来肉代替品の消費者採用", "Consumer Adoption of Plant-Based Meat Alternatives", "Beyond Meat、Impossible Foods等のプラント由来肉代替品の消費者受容を分析。Bryant（2019）は培養肉と植物性肉の消費者受容の比較分析を提供し、味覚的満足、健康認知、環境意識が採用動機であることを示した。肉食文化への愛着と新食品恐怖が主要障壁。", "代替タンパク質政策と食品ラベリング規制の理論的根拠を提供した。", "食品テクノロジー受容論", 2019, "micro", "味覚的満足と倫理的動機の統合判断", "Christopher Bryant; Julie Barnett; Michael Siegrist", "A survey of consumer perceptions of plant-based and clean meat (Bryant, 2019)", "肉食至上主義, フードテクノロジー嫌悪", "プラント由来肉, 代替タンパク, 消費者受容, フードテック", "plant-based meat, alternative protein, consumer acceptance, food tech"),
        ("AIチャットボットの顧客サービス採用", "Customer Service Adoption of AI Chatbots", "カスタマーサービスにおけるAIチャットボットの消費者受容と利用体験を分析。Følstad & Brandtzæg（2017）はチャットボット利用の動機を分析し、生産性、娯楽、社会的関係、好奇心を主要動機として同定した。人間エージェントとの比較、感情的対応の限界、エスカレーション設計が研究焦点。", "顧客体験（CX）戦略とAI対話設計の理論的根拠を提供した。", "AI対話採用論", 2017, "micro", "自動化効率と人間的共感の葛藤", "Asbjørn Følstad; Petter Bae Brandtzæg; Adam Palanica", "Chatbots and the New World of HCI (Følstad & Brandtzæg, 2017)", "全自動化楽観論, 人間対応至上主義", "AIチャットボット, 顧客サービス, 対話AI, エスカレーション", "AI chatbot, customer service, conversational AI, escalation"),
        ("テクノロジー規制の二面性：採用促進と抑制", "Dual Effects of Technology Regulation on Adoption", "規制がテクノロジー採用に与える促進効果（信頼構築、品質保証）と抑制効果（コスト増、参入障壁）の二面性を分析。Blind（2012）は規制とイノベーションの関係の包括的レビューを提供し、規制の質（明確性、比例性、適応性）が二面性の方向を決定することを示した。", "バランスの取れたテクノロジー規制設計の理論的根拠を提供した。", "規制とイノベーション論", 2012, "macro", "規制品質と採用のバランス", "Knut Blind; André Jungmittag; Axel Mangelsdorf", "The Impact of Standards and Regulation on Innovation (Blind, 2012)", "規制不要論, 過剰規制万能論", "規制の二面性, 規制品質, 採用促進, 参入障壁", "regulation duality, regulatory quality, adoption promotion, entry barrier"),
        ("テクノロジーの非利用と権利としての拒否", "Technology Non-Use and Right to Refuse", "イノベーションを意識的に採用しない選択（非利用）を体系的に分析する理論。Wyatt（2003）は非利用者の四類型（抵抗者、拒絶者、排除者、追放者）を提示し、非採用が受動的な無知ではなく能動的な選択であることを理論化した。Baumer et al.（2013）はFacebook非利用の多様な動機を実証した。", "デジタル包摂政策における非利用者の権利尊重の理論的根拠を提供した。", "非採用研究", 2003, "micro", "能動的非採用と権利としての拒否", "Sally Wyatt; Eric Baumer; Phil Adams; Vera Khovanskaya", "Non-users also matter (Wyatt, 2003); Limiting, Leaving, and (Re)Lapsing (Baumer et al., 2013)", "採用至上主義, 非利用=未開発仮定", "非利用, 非採用, デジタル拒否, 能動的選択", "non-use, non-adoption, digital refusal, active choice"),
        ("テクノロジー・フォアキャスティングと採用予測", "Technology Forecasting and Adoption Prediction", "技術の普及速度と最終採用率を予測する方法論。Meade & Islam（2006）はSカーブモデルの拡張と比較分析を提供し、Bass、Gompertz、ロジスティック等の普及モデルの予測精度を比較した。ビッグデータとAIを活用した予測手法の発展が最近の研究焦点。", "テクノロジー投資計画とインフラ整備タイミングの理論的根拠を提供した。", "普及予測論", 2006, "macro", "数学的モデリングとパラメータ推定", "Nigel Meade; Towhidul Islam; Vijay Mahajan", "Modelling and forecasting the diffusion of innovation (Meade & Islam, 2006)", "定性的予測のみ, 過去データ外挿の限界無視", "普及予測, Sカーブ, Bassモデル, 技術フォアキャスト", "diffusion forecasting, S-curve, Bass model, technology forecast"),
        ("リバウンド効果とテクノロジー採用の環境影響", "Rebound Effects and Environmental Impact of Technology Adoption", "効率改善技術の採用が、利用増加を通じて意図せず資源消費を増大させるリバウンド効果を分析。Sorrell（2009）はエビデンスレビューを提供し、直接的リバウンド（同一サービスの消費増加）と間接的リバウンド（節約分の他消費への転用）を区分した。Jevons（1865）のパラドックスの現代的検証。", "エネルギー効率政策と持続可能消費政策の理論的根拠を提供した。", "リバウンド効果論", 2009, "macro", "効率改善と利用増加の逆説的関係", "Steve Sorrell; John Dimitropoulos; Matt Sommerville", "The rebound effect: an assessment of the evidence (Sorrell, 2009)", "効率改善=消費削減仮定, リバウンド否定論", "リバウンド効果, ジェヴォンズのパラドックス, エネルギー効率, 消費増加", "rebound effect, Jevons paradox, energy efficiency, consumption increase"),
        ("テクノロジー放棄とディスコンティニュアンス", "Technology Abandonment and Discontinuance", "一度採用したテクノロジーを意図的に放棄する行動のメカニズムを分析。Furneaux & Wade（2011）はIT放棄の決定要因モデルを構築し、不満足、レガシー問題、代替手段の利用可能性が放棄を決定することを実証した。SNSの放棄、ウェアラブルの放棄が代表的研究対象。", "テクノロジー製品のリテンション戦略の理論的根拠を提供した。", "技術放棄論", 2011, "micro", "不満足と代替判断による離脱", "Brent Furneaux; Michael Wade; Raghav Rao", "An Exploration of Organizational Level IS Discontinuance Intentions (Furneaux & Wade, 2011)", "採用=永続利用仮定, 放棄の非合理性前提", "テクノロジー放棄, ディスコンティニュアンス, 不満足, 代替手段", "technology abandonment, discontinuance, dissatisfaction, alternative"),
        ("社会的受容と公衆の技術評価", "Social Acceptance and Public Technology Assessment", "原子力、遺伝子組み換え、5G基地局等の技術に対する公衆の社会的受容と参加型技術評価（pTA）を分析。Wüstenhagen et al.（2007）は再生可能エネルギーの社会的受容の三次元（社会政治的、コミュニティ、市場）を提示した。NIMBY（Not In My Back Yard）問題の構造的分析を含む。", "テクノロジーアセスメント政策と公衆参加制度の理論的根拠を提供した。", "社会的受容論", 2007, "macro", "リスク認知と民主的参加の統合", "Rolf Wüstenhagen; Maarten Wolsink; Mary Jean Bürer", "Social acceptance of renewable energy innovation (Wüstenhagen et al., 2007)", "テクノロジー楽観論, 公衆の非合理性仮定", "社会的受容, NIMBY, 公衆参加, リスク認知", "social acceptance, NIMBY, public participation, risk perception"),
        ("ソーシャルロボットの子どもの採用と教育効果", "Children's Adoption of Social Robots and Educational Effects", "教育用ソーシャルロボット（NAO、Pepper、KIBO等）に対する子どもの受容と学習効果を分析。Belpaeme et al.（2018）は教育ロボットの効果のメタ分析を提供し、ロボットの物理的存在が画面上のエージェントよりも学習効果が高いことを示した。擬社会的愛着の形成と教育的利用の倫理的課題を含む。", "EdTechロボット政策と子ども向けAI倫理の理論的根拠を提供した。", "子ども-ロボット相互作用論", 2018, "micro", "擬社会的愛着と教育的効果", "Tony Belpaeme; James Kennedy; Aditi Ramachandran; Paul Baxter", "Social Robots for Education: A Review (Belpaeme et al., 2018)", "画面ベース教育至上主義, ロボットの非教育性仮定", "教育ロボット, 子ども, 社会的ロボット, 学習効果", "educational robot, children, social robot, learning effect"),
        ("デジタル遺産とテクノロジーの世代間移転", "Digital Legacy and Intergenerational Technology Transfer", "デジタル資産（SNSアカウント、暗号資産、デジタルコンテンツ等）の死後管理と世代間移転を分析。Massimi & Baecker（2010）はデジタル遺産の概念を先駆的に提起し、Brubaker et al.（2013）はFacebookの故人アカウント管理を分析した。デジタル遺産法制の未整備が主要課題。", "デジタル遺産法制と世代間デジタルリテラシー政策の理論的根拠を提供した。", "デジタル遺産論", 2010, "micro", "デジタルアイデンティティの永続性と継承", "Michael Massimi; Ronald Baecker; Jed Brubaker; Gillian Hayes", "Mortality and Immortality: The Design of Digital Legacy Systems (Massimi & Baecker, 2010)", "デジタルの一時性仮定, 死後のデジタル資産無視", "デジタル遺産, 故人アカウント, デジタル資産, 世代間移転", "digital legacy, deceased account, digital asset, intergenerational transfer"),
        ("量子暗号通信の組織採用", "Organizational Adoption of Quantum Cryptography", "量子鍵配送（QKD）等の量子暗号通信技術の組織的採用障壁を分析。Diamanti et al.（2016）はQKDの実用的課題（距離制限、インフラコスト、既存暗号との互換性）を体系化した。ポスト量子暗号への移行の組織的準備度も研究焦点。", "量子セキュリティ政策と暗号インフラ移行戦略の理論的根拠を提供した。", "量子技術採用論", 2016, "meso", "量子セキュリティと実装複雑性のトレードオフ", "Eleni Diamanti; Hoi-Kwong Lo; Bing Qi; Zhiliang Yuan", "Practical challenges in quantum key distribution (Diamanti et al., 2016)", "現行暗号の充分性仮定, 量子コンピュータ脅威の過小評価", "量子暗号, QKD, ポスト量子, 暗号移行", "quantum cryptography, QKD, post-quantum, cryptographic transition"),
        ("クラウドファンディングと新製品の事前採用", "Crowdfunding and Pre-Adoption of New Products", "Kickstarter、Indiegogo等のクラウドファンディングを通じた新製品の事前採用（バッキング）行動を分析。Mollick（2014）はクラウドファンディング成功の決定要因を実証し、プロジェクト品質のシグナル、ソーシャルキャピタル、目標設定が成功要因であることを示した。Belleflamme et al.（2014）は報酬型と投資型の経済分析を提示。", "クラウドファンディング規制と起業支援政策の理論的根拠を提供した。", "クラウドファンディング論", 2014, "micro", "事前コミットメントとコミュニティ形成", "Ethan Mollick; Paul Belleflamme; Thomas Lambert; Armin Schwienbacher", "The Dynamics of Crowdfunding (Mollick, 2014)", "従来型資金調達のみ, 消費者の受動性仮定", "クラウドファンディング, 事前採用, バッキング, コミュニティ支援", "crowdfunding, pre-adoption, backing, community support"),
        ("自動運転車の社会的受容", "Social Acceptance of Autonomous Vehicles", "レベル3-5の自動運転車に対する消費者・社会の受容分析。Bansal et al.（2016）は自動運転車採用のモデルを構築し、安全性認知、技術的信頼、法的責任、保険制度が主要決定要因であることを示した。MIT Moral Machineプロジェクトが自動運転の倫理的ジレンマの文化差を大規模に実証。", "自動運転規制政策とインフラ設計の理論的根拠を提供した。", "自動運転受容論", 2016, "macro", "安全性信頼と倫理的ジレンマ", "Prateek Bansal; Kara Kockelman; Iyad Rahwan; Jean-François Bonnefon; Azim Shariff", "Forecasting Americans' long-term adoption of connected and autonomous vehicle technologies (Bansal et al., 2016); The Moral Machine experiment (Awad et al., 2018)", "技術的安全性のみの評価, 社会的受容の自動達成仮定", "自動運転, 社会的受容, 安全性信頼, 倫理的ジレンマ, モラルマシン", "autonomous vehicle, social acceptance, safety trust, ethical dilemma, moral machine"),
        ("プラットフォーム労働の「採用」とギグエコノミー", "Platform Labor Adoption and Gig Economy", "Uber、DoorDash、Fiverr等のギグプラットフォームへの労働者としての参加を分析。Schor et al.（2020）はプラットフォーム労働の多様な動機を実証し、Wood et al.（2019）はプラットフォーム労働の自律性とプレカリティのパラドックスを分析した。アルゴリズム管理と労働者の主体性の緊張が核心的課題。", "ギグエコノミー労働規制と社会保障政策の理論的根拠を提供した。", "プラットフォーム労働論", 2019, "meso", "柔軟性とプレカリティのトレードオフ", "Juliet Schor; William Attwood-Charles; Alex Wood; Mark Graham", "After the gig (Schor et al., 2020); Good Gig, Bad Gig (Wood et al., 2019)", "従来型雇用モデル至上主義, プラットフォーム労働の単純化", "プラットフォーム労働, ギグエコノミー, アルゴリズム管理, 労働者保護", "platform labor, gig economy, algorithmic management, worker protection"),
        ("EdTechの学習者採用とMOOC完了率問題", "EdTech Learner Adoption and MOOC Completion Rate Problem", "MOOCs、LMS、適応型学習プラットフォームの学習者レベルでの採用と継続利用。Alraimi et al.（2015）はMOOC継続利用意図モデルを構築した。MOOC完了率の低さ（平均5-15%）が採用と継続利用のギャップを象徴する。マイクロクレデンシャルやナノディグリーが完了率改善策として注目される。", "オンライン学習政策と教育DXの理論的根拠を提供した。", "教育テクノロジー採用論", 2015, "micro", "学習動機の持続と離脱のダイナミクス", "Khaled Alraimi; Hangjung Zo; Andrew Ciganek; Justin Reich", "Understanding the MOOCs Continuance (Alraimi et al., 2015); Is the MOOC Pivot Point? (Reich, 2015)", "対面教育至上主義, 技術=学習効果仮定", "EdTech, MOOC, 完了率, マイクロクレデンシャル", "EdTech, MOOC, completion rate, micro-credential"),
        ("企業AI採用の組織的成熟度モデル", "Organizational AI Maturity Model for Enterprise Adoption", "企業レベルでのAI技術採用の成熟度を段階的に評価するフレームワーク。Ransbotham et al.（2019）のMIT-BCG調査はAI採用の成熟度ギャップを実証し、先行企業と遅延企業の差がデータ品質、人材、組織文化に起因することを示した。Davenport（2018）は分析成熟度モデルを提示。", "企業AI戦略と人材育成政策の理論的根拠を提供した。", "企業AI採用論", 2019, "meso", "組織的準備度とAI成熟度の段階的構築", "Sam Ransbotham; David Kiron; Philipp Gerbert; Thomas Davenport", "Winning With AI (Ransbotham et al., 2019); The AI Advantage (Davenport, 2018)", "AI導入=即座の成果仮定, 段階的成熟の無視", "企業AI, AI成熟度, データ品質, 組織的準備度", "enterprise AI, AI maturity, data quality, organizational readiness"),
        ("農業テクノロジーの途上国小規模農家採用", "Smallholder Adoption of Agricultural Technology in Developing Countries", "途上国の小規模農家による改良種子、灌漑、精密農業技術の採用を分析。Foster & Rosenzweig（1995）は社会的学習モデルで採用行動を説明し、隣人の成功体験が自身の採用確率を高めることを実証した。信用制約、土地の安全保障、拡張サービスへのアクセスが固有の障壁。", "農業開発政策と技術普及サービスの設計に理論的根拠を提供した。", "農業技術採用論", 1995, "micro", "社会的学習と経済的制約の相互作用", "Andrew Foster; Mark Rosenzweig; David Zilberman; Cheryl Doss", "Learning by Doing and Learning from Others (Foster & Rosenzweig, 1995)", "合理的即時採用仮定, 制約の無視", "農業技術, 途上国, 小規模農家, 社会的学習", "agricultural technology, developing country, smallholder, social learning"),
        ("デジタル農業（スマートファーミング）の採用障壁", "Adoption Barriers of Digital Agriculture (Smart Farming)", "精密農業、ドローン監視、IoTセンサー、AI作物管理等のデジタル農業技術の採用障壁。Kernecker et al.（2020）は欧州農家のスマート農業採用障壁を調査し、コスト、データセキュリティ、デジタルインフラ不備、デジタルスキル不足を主要障壁として同定した。", "農業DX政策と農村デジタルインフラの設計に理論的根拠を提供した。", "精密農業採用論", 2020, "meso", "デジタルスキル格差と投資回収不確実性", "Maria Kernecker; Andrea Knierim; Angelika Wurbs; Simone Kraus", "Experience versus expectation (Kernecker et al., 2020)", "ハイテク農業万能論, 小規模農家無視", "スマートファーミング, 精密農業, デジタル農業, IoT", "smart farming, precision agriculture, digital agriculture, IoT"),
        ("eガバメントサービスの市民採用と信頼", "Citizen Adoption of e-Government Services and Trust", "電子政府サービスの市民採用における制度的信頼と政府信頼の役割を分析。Venkatesh et al.（2016）はUTAUTをeガバメント文脈に適用し、制度的信頼と透明性が固有の決定要因であることを示した。デジタルデバイドによるeガバメントの不平等なアクセスも研究焦点。", "デジタルガバメント政策と行政DXの理論的根拠を提供した。", "eガバメント採用論", 2016, "macro", "政府信頼とサービス品質の相互作用", "Viswanath Venkatesh; John Thong; Frank Chan; Paul Hu", "Unified Theory of Acceptance and Use of E-Government (Venkatesh et al., 2016)", "行政サービスの窓口至上主義, デジタル化=効率化仮定", "eガバメント, デジタル行政, 市民採用, 政府信頼", "e-government, digital government, citizen adoption, government trust"),
        ("ペイウォールとデジタルニュースの支払い意思", "Paywall and Willingness to Pay for Digital News", "新聞のデジタル版有料化に対する消費者の支払い意思を分析。Chiou & Tucker（2013）はペイウォールがニュース消費パターンに与える影響を実証した。メーター型、フリーミアム型、ハード型ペイウォールの効果比較と、広告モデルからの移行の課題が研究焦点。", "デジタルジャーナリズムの持続可能なビジネスモデルの理論的根拠を提供した。", "デジタルメディア採用論", 2013, "micro", "情報への支払い意思と代替手段との競合", "Lesley Chiou; Catherine Tucker; Merja Myllylahti", "Paywalls and the Demand for News (Chiou & Tucker, 2013)", "情報無料仮定, 広告モデル至上主義", "ペイウォール, デジタルニュース, 支払い意思, サブスクリプション", "paywall, digital news, willingness to pay, subscription"),
        ("サイバーセキュリティ行動の保護動機理論", "Protection Motivation Theory in Cybersecurity Behavior", "Rogers（1975）の保護動機理論（PMT）をサイバーセキュリティ行動に適用し、脅威評価（脆弱性、深刻度）と対処評価（自己効力感、反応効力感）がセキュリティ対策の採用を決定するメカニズムを分析。Herath & Rao（2009）は組織における従業員のセキュリティ行動にPMTを適用した。", "サイバーセキュリティ教育と従業員トレーニングの理論的根拠を提供した。", "セキュリティ行動論", 2009, "micro", "脅威認知と自己効力感の相互作用", "Tejaswini Herath; H. Raghav Rao; Ronald Rogers", "Protection Motivation and Deterrence (Herath & Rao, 2009)", "技術的防御のみ, 人的要因の無視", "保護動機理論, サイバーセキュリティ, 脅威評価, 自己効力感", "protection motivation theory, cybersecurity, threat appraisal, self-efficacy"),
        ("RPA（ロボティック・プロセス・オートメーション）の組織採用", "Organizational Adoption of RPA", "定型的業務プロセスをソフトウェアロボットで自動化するRPAの組織的採用を分析。Willcocks et al.（2015）は成功要因として適切なプロセス選定、段階的導入、人材リスキリングを同定した。UiPath、Automation Anywhere、Blue Prismが主要ベンダー。RPA→インテリジェントオートメーション（IA）への進化が研究焦点。", "業務自動化戦略とRPA投資判断の理論的根拠を提供した。", "業務自動化採用論", 2015, "meso", "定型業務の自動化判断と人材転換", "Leslie Willcocks; Mary Lacity; Andrew Craig", "The IT Function and Robotic Process Automation (Willcocks et al., 2015)", "完全自動化幻想, 人的業務の不要化仮定", "RPA, ロボティック・プロセス, 業務自動化, インテリジェントオートメーション", "RPA, robotic process, business automation, intelligent automation"),
        ("量子コンピューティングの初期市場形成", "Early Market Formation of Quantum Computing", "量子コンピューティングの初期商業採用パターンを分析。金融（ポートフォリオ最適化）、製薬（分子シミュレーション）、物流（経路最適化）が先行領域。Gill et al.（2022）は量子コンピューティング採用の技術的・組織的課題を体系的にレビューした。量子優位性（quantum advantage）の実証が商業採用の鍵。", "量子コンピューティング政策と人材育成戦略の理論的根拠を提供した。", "量子技術採用論", 2022, "meso", "技術的不確実性下の戦略的ポジショニング", "Sukhpal Singh Gill; Adarsh Kumar; Minxian Xu", "Quantum Computing: A Taxonomy, Systematic Review and Future Directions (Gill et al., 2022)", "量子万能論, 短期的商業化楽観", "量子コンピューティング, 量子優位性, 初期採用, 商業化", "quantum computing, quantum advantage, early adoption, commercialization"),
        ("デジタルトランスフォーメーション採用の中小企業モデル", "SME Model of Digital Transformation Adoption", "中小企業（SME）のデジタルトランスフォーメーション採用の固有の課題（限定的資源、IT人材不足、経営者のデジタルリテラシー）を分析。Li et al.（2018）はSMEのDX採用段階モデルを構築し、デジタル化→デジタリゼーション→DXの三段階を提示した。政府支援プログラムの効果と限界も分析される。", "中小企業DX支援政策の理論的根拠を提供した。", "中小企業DX論", 2018, "meso", "資源制約下の段階的デジタル化", "Ling Li; Fang Su; Wei Zhang; Ji-Ye Mao", "Digital transformation by SME entrepreneurs (Li et al., 2018)", "大企業モデルの無条件適用, 資源制約の無視", "SME, デジタルトランスフォーメーション, 段階モデル, 資源制約", "SME, digital transformation, stage model, resource constraint"),
        ("ダークパターンと操作的UX設計", "Dark Patterns and Manipulative UX Design", "ユーザーインターフェースの意図的な欺瞞的設計（ダークパターン）による採用・課金・データ提供の操作を分析。Brignull（2010）が類型化し、Gray et al.（2018）は学術的に体系化した。Mathur et al.（2019）は11,000のeコマースサイトを分析しダークパターンの普及度を実証。EU Digital Services ActやFTCガイダンスが規制的対応。", "デジタル消費者保護規制の理論的根拠を提供した。", "デジタル倫理論", 2010, "micro", "認知バイアスの意図的利用と倫理的問題", "Harry Brignull; Colin Gray; Arunesh Mathur; Gunes Acar; Jonathan Mayer", "Dark Patterns at Scale (Mathur et al., 2019)", "ユーザー中心設計至上主義, 操作的設計の無認識", "ダークパターン, 欺瞞的UX, 消費者保護, 倫理的設計", "dark patterns, deceptive UX, consumer protection, ethical design"),
        ("アクセシビリティ法制とテクノロジーの包摂的採用", "Accessibility Legislation and Inclusive Technology Adoption", "障害者や高齢者のテクノロジー利用を保障するアクセシビリティ法制（ADA、EU Accessibility Act、WCAG）の採用促進効果を分析。Persson et al.（2015）はアクセシビリティの概念的枠組みを構築し、ユニバーサルデザイン原則の技術への適用を理論化した。", "デジタルアクセシビリティ政策と包摂的テクノロジー設計の理論的根拠を提供した。", "アクセシビリティ研究", 2015, "macro", "包摂的設計原則による利用障壁の除去", "Hans Persson; Henrik Åhman; Alexander Yngling; Jan Gulliksen", "Universal design, inclusive design, accessible design (Persson et al., 2015)", "健常者中心設計, アクセシビリティの事後的追加", "アクセシビリティ, ユニバーサルデザイン, WCAG, 包摂的設計", "accessibility, universal design, WCAG, inclusive design"),
        ("AIバイアスと差別的テクノロジー影響", "AI Bias and Discriminatory Technology Impact", "AI/機械学習システムのバイアスが特定グループの技術アクセスと利用を差別的に影響するメカニズム。Buolamwini & Gebru（2018）は顔認識AIのジェンダー・人種バイアスを実証し、Obermeyer et al.（2019）はヘルスケアAIの人種バイアスを暴露した。アルゴリズム的公平性（algorithmic fairness）の定量化と監査が研究焦点。", "AI倫理政策、公平性監査制度、AI規制の理論的根拠を提供した。", "AI倫理・公平性研究", 2018, "macro", "構造的不平等のアルゴリズム的再生産", "Joy Buolamwini; Timnit Gebru; Ziad Obermeyer; Safiya Noble", "Gender Shades (Buolamwini & Gebru, 2018); Dissecting racial bias (Obermeyer et al., 2019)", "アルゴリズム中立仮定, 技術の無偏性前提", "AIバイアス, 公平性, アルゴリズム監査, 差別的影響", "AI bias, fairness, algorithmic audit, discriminatory impact"),
        ("ソーシャルコマースとライブコマースの採用", "Adoption of Social Commerce and Live Commerce", "ソーシャルメディア上での商品発見・購買（ソーシャルコマース）とライブストリーミング販売の採用動態。Liang & Turban（2011）はソーシャルコマースの概念枠組みを構築し、Sun et al.（2019）は中国のライブコマース（淘宝直播等）の消費者行動を分析した。インフルエンサーの信頼性と購買衝動の関係が研究焦点。", "ソーシャルメディアの商業利用政策とインフルエンサー規制の理論的根拠を提供した。", "ソーシャルコマース論", 2019, "micro", "社会的影響と即時的購買衝動の融合", "Ting-Peng Liang; Efraim Turban; Yongqiang Sun; Nan Shang", "How live streaming influences purchase intentions (Sun et al., 2019)", "eコマースとSNSの分離, 合理的購買のみ仮定", "ソーシャルコマース, ライブコマース, インフルエンサー, 衝動買い", "social commerce, live commerce, influencer, impulse buying"),
        ("倫理的消費と態度-行動ギャップ", "Ethical Consumption and Attitude-Behavior Gap", "フェアトレード、オーガニック、クルエルティフリー等の倫理的イノベーションの消費者採用における「態度-行動ギャップ」を分析。Carrington et al.（2014）は倫理的消費の態度-行動ギャップの理論的説明を提供し、利便性、価格、入手可能性がギャップの主要原因であることを示した。", "サステナブル消費政策とCSR戦略の理論的根拠を提供した。", "倫理的消費論", 2014, "micro", "道徳的判断と実際の購買行動の乖離", "Michal Carrington; Benjamin Neville; Gregory Whitwell", "Lost in translation (Carrington et al., 2014)", "合理的消費者仮定, 倫理的プレミアムの自明性", "倫理的消費, 態度行動ギャップ, フェアトレード, サステナブル", "ethical consumption, attitude-behavior gap, fair trade, sustainable"),
        ("P2P経済の信頼メカニズムと採用", "Trust Mechanisms in P2P Economy and Adoption", "P2P取引プラットフォームの信頼構築メカニズム（レピュテーションシステム、エスクロー、保険等）が採用に与える影響。Sundararajan（2016）は信頼の「リープ・オブ・フェイス」概念を提唱し、デジタル信頼がP2P経済の基盤であることを理論化した。Zervas et al.（2021）はAirbnbのレビューバイアスを実証。", "P2P規制政策とプラットフォーム信頼設計の理論的根拠を提供した。", "信頼とプラットフォーム論", 2016, "meso", "デジタル信頼の構築と脆弱性", "Arun Sundararajan; Georgios Zervas; Davide Proserpio; John Byers", "The Sharing Economy (Sundararajan, 2016); A First Look at Online Reputation (Zervas et al., 2021)", "中央集権型市場至上主義, 対面信頼のみ", "P2P信頼, レピュテーション, デジタル信頼, プラットフォーム", "P2P trust, reputation, digital trust, platform"),
        ("低テクノロジーイノベーションの再評価とDUIモード", "Revaluation of Low-Tech Innovation and DUI Mode", "ハイテクではなくローテク産業（食品、繊維、建設等）のイノベーション重要性を再評価する研究。Hirsch-Kreinsen et al.（2005）はローテク産業のイノベーション・パラドックスを分析し、Jensen et al.（2007）はDUI（Doing, Using, Interacting）モードの学習がSTI（Science, Technology, Innovation）モードと同等に重要であることを実証した。", "イノベーション政策のハイテク偏重を是正し、全産業横断的イノベーション支援の理論的根拠を提供した。", "ローテクイノベーション論", 2005, "meso", "経験ベースの漸進的改善と組織学習", "Hartmut Hirsch-Kreinsen; Morten Berg Jensen; Björn Johnson; Edward Lorenz", "Low-tech innovation (Hirsch-Kreinsen et al., 2005); Forms of knowledge and modes of innovation (Jensen et al., 2007)", "ハイテク至上主義, R&D投資=イノベーション仮定", "ローテク, DUIモード, 漸進的イノベーション, 実践ベース学習", "low-tech, DUI mode, incremental innovation, practice-based learning"),
        ("デジタルサステナビリティとグリーンIT採用", "Digital Sustainability and Green IT Adoption", "デジタル技術の環境的コスト（e-waste、データセンターエネルギー）と環境的便益のバランスを分析。Stuermer et al.（2017）はデジタルサステナビリティの概念フレームワークを構築した。Murugesan（2008）はグリーンITの体系化を提供し、エネルギー効率的なIT運用の実践を理論化した。", "グリーンIT政策とデジタルサステナビリティ戦略の理論的根拠を提供した。", "デジタルサステナビリティ論", 2008, "meso", "デジタル化の環境コストと便益の両面評価", "Matthias Stuermer; San Murugesan; Gabriel Abu-Tayeh", "Harnessing Green IT (Murugesan, 2008); Digital sustainability (Stuermer et al., 2017)", "デジタル化=環境改善仮定, ICTの環境負荷無視", "グリーンIT, デジタルサステナビリティ, e-waste, データセンター効率", "green IT, digital sustainability, e-waste, data center efficiency"),
        ("テクノロジー採用のメタ分析的統合", "Meta-Analytic Integration of Technology Adoption", "TAM、UTAUT等の技術採用理論のメタ分析を通じた実証的統合。King & He（2006）はTAMのメタ分析で知覚有用性と知覚容易性の効果量を統合推定した。Dwivedi et al.（2019）はUTAUT研究の包括的メタ分析を提供し、理論の境界条件を同定した。", "技術採用研究の方法論的洗練と理論的統合に貢献した。", "メタ分析的統合論", 2006, "micro", "効果量の統合推定と境界条件の同定", "William King; Jun He; Yogesh Dwivedi; Nripendra Rana; Michael Williams", "A meta-analysis of the technology acceptance model (King & He, 2006); Re-examining the UTAUT (Dwivedi et al., 2019)", "単一研究の一般化, サンプル固有の結論", "メタ分析, TAM, UTAUT, 効果量統合", "meta-analysis, TAM, UTAUT, effect size integration"),
        ("サーキュラーエコノミー製品の消費者受容", "Consumer Acceptance of Circular Economy Products", "リファービッシュ品、リサイクル素材製品、製品サービスシステム（PSS）等の循環型製品の消費者受容。Camacho-Otero et al.（2018）は循環型消費の決定要因レビューを提供し、品質認知、価格メリット、環境意識が採用動機であることを示した。「新品信仰」と「中古品スティグマ」が主要障壁。", "サーキュラーエコノミー政策と持続可能消費促進の理論的根拠を提供した。", "持続可能消費論", 2018, "micro", "新品信仰と循環的価値の再評価", "Juana Camacho-Otero; Casper Boks; Ida Nilstad Pettersen", "Consumption in the Circular Economy (Camacho-Otero et al., 2018)", "新品至上主義, 線形消費モデル", "サーキュラーエコノミー, リファービッシュ, PSS, 持続可能消費", "circular economy, refurbished, PSS, sustainable consumption"),
        ("5G技術の消費者採用と期待-体験ギャップ", "Consumer Adoption of 5G and Expectation-Experience Gap", "5G通信技術の消費者採用における過剰期待と実際のユースケースの乖離を分析。通信速度の改善は知覚されにくく、キラーアプリの不在が採用動機を弱める。Oughton et al.（2021）は5G展開のコスト便益分析を提供した。", "5G政策と次世代通信インフラ投資の理論的根拠を提供した。", "通信技術採用論", 2021, "micro", "期待管理と知覚価値の限界", "Edward Oughton; Zoraida Frias; Tom van der Gaast", "The costs, coverage and rollout implications of 5G infrastructure (Oughton et al., 2021)", "技術的仕様至上主義, 消費者ニーズ無視", "5G, 期待-体験ギャップ, キラーアプリ, 消費者採用", "5G, expectation-experience gap, killer app, consumer adoption"),
        ("IoTセキュリティとプライバシーの消費者認知", "Consumer Perception of IoT Security and Privacy", "IoTデバイスのセキュリティ脆弱性とプライバシーリスクに対する消費者認知が採用に与える影響。Zheng et al.（2018）はIoT採用におけるプライバシー懸念の多層構造を分析し、デバイスレベル、ネットワークレベル、クラウドレベルのリスクを同定した。Mirai botnet事件等がIoTセキュリティ意識を高めた。", "IoTセキュリティ規制とプライバシー・バイ・デザインの理論的根拠を提供した。", "IoTセキュリティ論", 2018, "micro", "多層的セキュリティリスク認知", "Shanqing Zheng; Noel Apthorpe; Marshini Chetty; Nick Feamster", "User Perceptions of Smart Home IoT Privacy (Zheng et al., 2018)", "IoTセキュリティの無視, 利便性至上主義", "IoTセキュリティ, プライバシー, 消費者認知, スマートホーム", "IoT security, privacy, consumer perception, smart home"),
        ("デジタルヘルスリテラシーとmHealth採用", "Digital Health Literacy and mHealth Adoption", "デジタルヘルスリテラシー（オンラインの健康情報を検索、評価、利用する能力）がmHealth技術の採用に与える影響。Norman & Skinner（2006）はeHealth Literacyの概念を提唱し、van der Vaart & Drossaert（2017）はデジタルヘルスリテラシーの測定尺度を開発した。", "デジタルヘルスリテラシー教育と健康格差是正の理論的根拠を提供した。", "デジタルヘルスリテラシー論", 2006, "micro", "健康情報リテラシーとデジタルスキルの統合", "Cameron Norman; Harvey Skinner; Rosalie van der Vaart; Constance Drossaert", "eHealth Literacy (Norman & Skinner, 2006)", "デジタルヘルスの普遍的アクセス仮定, リテラシー格差の無視", "デジタルヘルスリテラシー, eHealth, 健康情報, mHealth", "digital health literacy, eHealth, health information, mHealth"),
        ("XR（拡張現実）の産業採用", "Industrial Adoption of Extended Reality (XR)", "AR/VR/MRの製造業（遠隔支援、トレーニング、設計レビュー）における組織的採用を分析。Berg & Vance（2017）は設計レビューにおけるVR利用の効果を実証し、de Belen et al.（2019）は産業XRのレビューを提供した。ハードウェアコスト、コンテンツ制作、組織変革管理が主要障壁。", "産業DX政策とXR技術投資の理論的根拠を提供した。", "XR産業採用論", 2017, "meso", "没入型インターフェースの産業的価値実現", "L.P. Berg; J.M. Vance; R.A. de Belen; H. Nguyen", "Industry use of virtual reality in product design (Berg & Vance, 2017)", "2Dインターフェース至上主義, XRの消費者用途限定", "産業XR, ARトレーニング, VR設計, 没入型作業支援", "industrial XR, AR training, VR design, immersive work support"),
        ("産業メタバースと組織間デジタルツイン", "Industrial Metaverse and Inter-Organizational Digital Twins", "製造、サプライチェーン、都市計画における産業メタバース（デジタルツイン+VR+AI+IoT統合）の組織的採用。Nvidiaのオムニバースが先駆的プラットフォーム。Lee et al.（2021）はメタバース発展ロードマップを提示した。組織間データ共有と相互運用性が最大の課題。", "産業DX政策とメタバースインフラ投資の理論的根拠を提供した。", "産業メタバース論", 2021, "meso", "物理-デジタル融合のシステム間統合", "Lik-Hang Lee; Tristan Braud; Pengyuan Zhou; Pan Hui", "All One Needs to Know about Metaverse (Lee et al., 2021)", "メタバースのエンタメ限定視点, 産業適用無視", "産業メタバース, 組織間デジタルツイン, オムニバース, 相互運用性", "industrial metaverse, inter-organizational digital twin, omniverse, interoperability"),
        ("音声ソーシャルメディアの急速採用と減衰", "Rapid Adoption and Decay of Voice Social Media", "Clubhouse、Twitter Spaces等の音声ベースソーシャルメディアの急速な採用と減衰パターンを分析。2021年のClubhouseブームとその後の急速な利用者減少が「新奇性効果」による一時的採用と持続的価値の欠如を示す事例として研究された。普及のSカーブからの逸脱パターンの一類型。", "新興プラットフォームの成長と持続可能性の評価に理論的根拠を提供した。", "プラットフォーム動態論", 2021, "micro", "新奇性効果の減衰と持続的価値の不足", "Various researchers on Clubhouse phenomenon", "Studies on Clubhouse adoption patterns (2021-2022)", "新興プラットフォームの永続的成長仮定, ブームの無批判的評価", "音声ソーシャル, 採用と減衰, 新奇性効果, プラットフォーム持続性", "voice social, adoption and decay, novelty effect, platform sustainability"),
        ("技術的負債とレガシーシステムの組織的ロックイン", "Technical Debt and Legacy System Organizational Lock-in", "レガシーシステムの技術的負債が新技術採用を阻害するメカニズムの組織論的分析。Tom et al.（2013）は技術的負債の包括的分類を提供し、設計負債、コード負債、テスト負債、アーキテクチャ負債を同定した。金融機関のCOBOLレガシー、政府システムの更新遅延が代表的事例。", "IT近代化政策とレガシーシステム移行戦略の理論的根拠を提供した。", "技術的負債論", 2013, "meso", "蓄積的制約と移行の組織的困難", "Edith Tom; Aybüke Aurum; Richard Vidgen; Ward Cunningham", "An exploration of technical debt (Tom et al., 2013)", "完全リプレース仮定, 段階的移行の無視", "技術的負債, レガシーシステム, 移行障壁, IT近代化", "technical debt, legacy system, migration barrier, IT modernization"),
        ("暗黙知のデジタル化とAI支援技能伝承", "Digitization of Tacit Knowledge and AI-Assisted Skill Transfer", "暗黙知（言語化困難な経験的知識）のAI・VR・センサー技術による形式知化と技能伝承を分析。製造業の熟練工の技能、医療の暗黙的診断能力等がデジタル化対象。Nonaka & Takeuchi（1995）のSECIモデルのデジタル拡張として位置づけられ、AIによる暗黙知の部分的抽出・再現が研究焦点。", "技能伝承政策と高齢化社会の知識管理戦略の理論的根拠を提供した。", "知識経営論・AI応用", 2020, "meso", "暗黙知のデジタル変換の可能性と限界", "Ikujiro Nonaka; Hirotaka Takeuchi; Georg von Krogh", "The Knowledge-Creating Company (Nonaka & Takeuchi, 1995) + AI extensions", "暗黙知の完全デジタル化仮定, 形式知至上主義", "暗黙知, デジタル化, AI技能伝承, SECIモデル", "tacit knowledge, digitization, AI skill transfer, SECI model"),
        ("生成AI採用の組織文化的障壁", "Organizational Cultural Barriers to Generative AI Adoption", "ChatGPT、Copilot等の生成AIツールの組織的採用における文化的・心理的障壁を分析。Dell'Acqua et al.（2023）はBCGコンサルタントの生成AI利用実験で、タスク依存的な生産性効果を実証した。組織の信頼文化、リスク回避性、従業員の自律性と監視のバランスが採用速度を規定。品質管理とハルシネーション対策が実務的課題。", "組織のAI利用方針と従業員ガイドラインの設計に理論的根拠を提供した。", "生成AI組織採用論", 2023, "meso", "組織的信頼とAIの品質管理", "Fabrizio Dell'Acqua; Edward McFowland; Ethan Mollick; Hila Lifshitz-Assaf", "Navigating the Jagged Technological Frontier (Dell'Acqua et al., 2023)", "生成AI万能仮定, 組織文化の無視", "生成AI組織採用, 文化的障壁, ハルシネーション, 品質管理", "generative AI organizational adoption, cultural barriers, hallucination, quality control"),
        ("テクノロジー採用の行動経済学的統合モデル", "Behavioral Economics Integrated Model of Technology Adoption", "行動経済学の知見（損失回避、現状維持バイアス、フレーミング効果、時間割引等）を技術採用理論に統合するアプローチ。Kahneman & Tversky（1979）のプロスペクト理論とTAM/UTAUTの統合が進み、採用の「非合理的」側面をフォーマルに分析する。Gourville（2006）はイノベーションの損失回避効果（endowment effect for the status quo）を理論化した。", "テクノロジーマーケティングと政策的介入のナッジ設計に理論的根拠を提供した。", "行動経済学的採用論", 2006, "micro", "認知バイアスによる合理性からの逸脱", "John Gourville; Daniel Kahneman; Amos Tversky; Richard Thaler", "Eager Sellers and Stony Buyers (Gourville, 2006)", "完全合理的採用者仮定, バイアスの無視", "行動経済学, 損失回避, フレーミング, 現状維持バイアス", "behavioral economics, loss aversion, framing, status quo bias"),
        ("テクノロジー採用における信頼の修復", "Trust Repair in Technology Adoption", "テクノロジーの信頼喪失事件（データ漏洩、AI判断ミス、システム障害等）後の信頼修復メカニズムを分析。Kim et al.（2009）はオンライン信頼の違反と修復の理論を構築し、否定（denial）、謝罪（apology）、約束（promise）の効果を実証した。Bansal & Zahedi（2015）はプライバシー侵害後の信頼修復戦略を分析。", "テクノロジー企業の危機管理とインシデント対応の理論的根拠を提供した。", "信頼修復論", 2009, "micro", "信頼違反のタイプに応じた修復戦略", "Peter Kim; Donald Ferrin; Cecily Cooper; Gaurav Bansal; Fatemeh Zahedi", "Repairing Trust in Organizations (Kim et al., 2009)", "信頼の永続性仮定, 信頼喪失の不可逆性前提", "信頼修復, データ漏洩, 謝罪戦略, インシデント対応", "trust repair, data breach, apology strategy, incident response"),
    ], start=633)
]

print(f"Generated {len(entries)} entries")
print(f"ID range: {entries[0]['id']} - {entries[-1]['id']}")

# Write to JSON
output_path = "/Users/nishimura+/projects/research/academic-knowledge-db/collected/innovation/inno_diff_633_714.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(entries, f, ensure_ascii=False, indent=2)

print(f"Written to {output_path}")
