#!/usr/bin/env python3
"""Generate knowledge_learning_capabilities entries (inno_know_301 to inno_know_719)."""
import json, os
entries = []
idx = 301
def add(n_en, n_ja, defn, imp, sch, era, innov, cog, res, wrk, opp, kj, ke):
    global idx
    entries.append({"id":f"inno_know_{idx}","name_en":n_en,"name_ja":n_ja,"definition":defn,"impact_summary":imp,"subfield":"knowledge_learning_capabilities","school_of_thought":sch,"era_start":era,"era_end":None,"innovation_type":innov,"cognitive_mechanism":cog,"key_researchers":json.dumps(res,ensure_ascii=False),"key_works":json.dumps(wrk,ensure_ascii=False),"opposing_concept_names":opp,"keywords_ja":kj,"keywords_en":ke,"schumpeter_layer":"micro","status":"active","source_reliability":"secondary","data_completeness":75})
    idx += 1

# === ABSORPTIVE CAPACITY EXTENSIONS (301-330) ===
add("Potential Absorptive Capacity","潜在的吸収能力","外部知識を認識（acquisition）し理解（assimilation）する組織能力。Zahra & George（2002）がCohen & Levinthalの吸収能力概念を潜在的能力と実現的能力に再分類した拡張モデルの前半要素。","吸収能力概念の精緻化と操作化。","知識マネジメント",2002,"organizational","外部知識の認識と理解",["Shaker Zahra","Gerard George"],["Zahra & George (2002) Absorptive Capacity: A Review"],"realized absorptive capacity","潜在的吸収能力,知識認識,知識同化","potential absorptive capacity, knowledge acquisition, assimilation")
add("Realized Absorptive Capacity","実現的吸収能力","外部知識を変換（transformation）し活用（exploitation）する組織能力。潜在的吸収能力で獲得した知識を実際のイノベーション成果に結びつける能力であり、組織の社会的統合メカニズムが両者を媒介する。","吸収能力の実践的活用面の理論化。","知識マネジメント",2002,"organizational","知識変換と実践的活用",["Shaker Zahra","Gerard George"],["Zahra & George (2002) Absorptive Capacity: A Review"],"potential absorptive capacity","実現的吸収能力,知識変換,知識活用","realized absorptive capacity, knowledge transformation, exploitation")
add("Relative Absorptive Capacity","相対的吸収能力","特定の外部知識源（パートナー企業、大学等）との知識基盤の類似性に依存する吸収能力。Lane & Lubatkin（1998年）がダイアド（二者間関係）レベルで概念化し、知識移転の効果がパートナー間の知識的近接性に依存することを示した。","パートナー間の知識的近接性が吸収能力を規定する。","知識マネジメント",1998,"organizational","パートナー固有の知識吸収",["Peter Lane","Michael Lubatkin"],["Lane & Lubatkin (1998) Relative Absorptive Capacity"],"","相対的吸収能力,ダイアド,知識的近接性","relative absorptive capacity, dyadic, knowledge proximity")
add("Absorptive Capacity as Dynamic Capability","動的能力としての吸収能力","吸収能力をTeece et al.の動的能力フレームワークに位置付け、外部知識の獲得・統合・再構成を通じて競争優位を持続的に更新する能力として再概念化するアプローチ。","吸収能力と動的能力の理論的統合。","知識マネジメント",2002,"organizational","知識ベースの動態的更新",["Shaker Zahra","Gerard George","David Teece"],["Zahra & George (2002)","Teece (2007) Explicating Dynamic Capabilities"],"","動的吸収能力,能力更新,競争優位","dynamic absorptive capacity, capability renewal, competitive advantage")
add("Individual-Level Absorptive Capacity","個人レベルの吸収能力","組織レベルの吸収能力の基盤となる個人の知識獲得・理解・活用能力。先行知識（prior knowledge）、認知スキル、モチベーション、社会的ネットワーク位置等の個人的要因が組織的吸収能力の構成要素として機能する。","吸収能力のミクロ的基盤の分析。","知識マネジメント",2005,"organizational","個人の知識処理能力",["Volberda","Foss","Lyles"],["Volberda, Foss & Lyles (2010) Absorptive Capacity: Taking Stock"],"","個人レベル吸収能力,先行知識,認知スキル","individual absorptive capacity, prior knowledge, cognitive skills")
add("Absorptive Capacity and R&D Investment","吸収能力とR&D投資","Cohen & Levinthal（1989年）の原義的命題：R&D投資はイノベーション生産だけでなく外部知識の吸収能力構築にも寄与する「二面的な顔」を持つ。R&D投資の吸収能力構築効果の実証的検証。","R&D投資の吸収能力構築効果の理論と実証。","知識マネジメント",1989,"organizational","R&Dの学習効果",["Wesley Cohen","Daniel Levinthal"],["Cohen & Levinthal (1989) Innovation and Learning"],"","R&D投資,二面性,学習効果","R&D investment, two faces, learning effect, absorptive capacity")
add("Network Absorptive Capacity","ネットワーク吸収能力","個別企業の吸収能力ではなく、アライアンス・ネットワーク全体としての知識吸収・統合能力。ネットワーク構造（密度、多様性、中心性）が集合的な吸収能力を形成する。","ネットワークレベルの吸収能力概念の理論化。","知識マネジメント",2008,"organizational","ネットワークを通じた集合的学習",["Dyer & Singh","Reagans & McEvily"],["Dyer & Singh (1998) The Relational View"],"","ネットワーク吸収能力,集合的学習,ネットワーク構造","network absorptive capacity, collective learning, network structure")
add("Absorptive Capacity and Knowledge Breadth","吸収能力と知識の幅","組織の知識基盤の幅（breadth）と深さ（depth）が吸収能力に与える差異的影響の分析。幅広い知識基盤は多様な外部知識の認識を促進し、深い知識基盤は特定領域の知識の活用を促進する。","知識基盤の構造が吸収能力に与える影響の分析。","知識マネジメント",2010,"organizational","知識構造の認知的効果",["Laursen & Salter"],["Laursen & Salter (2006) Open for Innovation"],"","知識の幅,知識の深さ,探索vs活用","knowledge breadth, knowledge depth, exploration vs exploitation")

# === KNOWLEDGE MANAGEMENT SYSTEMS (309-340) ===
add("Knowledge Management System (KMS)","知識管理システム","組織の知識資産の創造、蓄積、共有、活用を支援する情報技術基盤のシステム。データベース、文書管理、検索エンジン、コラボレーションツール等を統合し、暗黙知の形式知化と知識の組織的活用を促進する。","組織の知識資産管理の技術的基盤。","知識マネジメント",1995,"organizational","知識の体系的管理と活用",["Thomas Davenport","Larry Prusak"],["Davenport & Prusak (1998) Working Knowledge"],"","KMS,知識管理,知識活用","KMS, knowledge management, knowledge utilization, IT-based")
add("Knowledge Repository","知識リポジトリ","組織の明示的知識（文書、手順書、ベストプラクティス、教訓等）を体系的に蓄積し検索可能にするデータベース。知識の再利用と組織的記憶の維持を目的とし、ナレッジベース、Wikiシステム等として実装される。","明示的知識の体系的蓄積と再利用基盤。","知識マネジメント",1995,"organizational","知識の蓄積と検索",["Thomas Davenport"],["Davenport & Prusak (1998) Working Knowledge"],"","知識リポジトリ,ナレッジベース,知識再利用","knowledge repository, knowledge base, knowledge reuse, organizational memory")
add("Expert Locator System","専門家検索システム","組織内の専門知識の所在（誰が何を知っているか）を可視化し、知識保有者への迅速なアクセスを可能にするシステム。知識そのものではなく「知識の知識」（meta-knowledge）を管理する。","組織内の専門知識所在の可視化とアクセス促進。","知識マネジメント",2000,"organizational","メタ知識の管理",["Andrea Kö","Rob Cross"],["Cross & Prusak (2002) The People Who Make Organizations Go"],"","専門家検索,メタ知識,Who knows what","expert locator, meta-knowledge, who knows what, expertise finding")
add("Knowledge Audit","知識監査","組織の知識資産、知識フロー、知識ギャップを体系的に評価するプロセス。どの知識が存在し、どこに蓄積され、どのように流通し、何が不足しているかを明らかにして知識マネジメント戦略の基盤データを提供する。","組織の知識資産と知識フローの体系的評価。","知識マネジメント",2000,"organizational","知識の棚卸しと評価",["Jay Liebowitz"],["Liebowitz (2000) Building Organizational Intelligence"],"","知識監査,知識マッピング,知識ギャップ","knowledge audit, knowledge mapping, knowledge gap, knowledge inventory")
add("After Action Review (AAR)","事後検証","プロジェクトや活動の完了後に、「何が起こったか」「なぜ起こったか」「何を学んだか」「次にどうするか」を体系的に振り返る学習プロセス。米陸軍が開発し、組織学習の実践的手法として広く採用されている。","経験からの体系的学習の実践的手法。","組織学習",1980,"organizational","経験的学習の構造化",["US Army","David Garvin"],["US Army AAR Handbook"],"","事後検証,AAR,振り返り,教訓抽出","after action review, AAR, reflection, lesson learned")
add("Lessons Learned System","教訓管理システム","プロジェクトや業務から得られた教訓（成功要因・失敗要因）を体系的に収集、整理、蓄積、検索可能にし、将来の意思決定に活用するナレッジマネジメントの仕組み。NASAやWorld Bankが先駆的に実装。","組織的教訓の体系的管理と活用。","知識マネジメント",1990,"organizational","教訓の蓄積と再利用",["NASA","World Bank"],["NASA Lessons Learned Information System"],"","教訓管理,失敗学習,知識再利用","lessons learned, failure learning, knowledge reuse, organizational learning")
add("Knowledge Governance Approach","知識ガバナンス・アプローチ","組織の知識プロセス（創造、共有、統合、活用）を管理するガバナンス・メカニズム（権限構造、インセンティブ設計、調整メカニズム等）の設計原理。Foss（2007年）が組織経済学の知見を知識マネジメントに統合して理論化。","知識プロセスのガバナンス・メカニズム設計の理論。","知識マネジメント",2007,"organizational","組織設計による知識管理",["Nicolai Foss"],["Foss (2007) The Emerging Knowledge Governance Approach"],"","知識ガバナンス,権限構造,インセンティブ","knowledge governance, authority structure, incentive design")
add("Knowledge Integration Capability","知識統合能力","分散した専門知識を統合して問題解決やイノベーションに活用する組織能力。Grant（1996年）の知識ベース論に基づき、ルール・手順、シーケンシング、ルーティン、グループ問題解決等の統合メカニズムを通じて実現される。","分散的専門知識の効果的統合メカニズム。","知識ベース論",1996,"organizational","多様な知識の統合",["Robert Grant"],["Grant (1996) Toward a Knowledge-Based Theory of the Firm"],"","知識統合,専門知識統合,統合メカニズム","knowledge integration, expertise integration, integration mechanism")
add("Knowledge Sharing Barriers","知識共有の障壁","個人・組織・技術レベルで知識共有を阻害する要因の分析。個人レベル（信頼不足、知識権力の保持）、組織レベル（部門間サイロ、インセンティブ不整合）、技術レベル（ツール不足、互換性）の多層的障壁を特定する。","知識共有阻害要因の多層的分析。","知識マネジメント",2000,"organizational","知識共有の心理的・制度的障壁",["Morten Hansen"],["Hansen (1999) The Search-Transfer Problem"],"","知識共有障壁,サイロ,信頼不足","knowledge sharing barriers, silos, trust deficit, incentive misalignment")
add("Knowledge Creation Theory (SECI Model)","知識創造理論（SECIモデル）","野中郁次郎が提唱した、暗黙知と形式知の変換プロセスを通じて組織的に新知識が創造されるモデル。共同化（Socialization）→表出化（Externalization）→連結化（Combination）→内面化（Internalization）の4モード。","組織的知識創造の最も影響力のあるモデル。","知識創造論",1995,"organizational","暗黙知-形式知変換による知識創造",["野中郁次郎","竹内弘高"],["Nonaka & Takeuchi (1995) The Knowledge-Creating Company"],"","SECIモデル,知識創造,暗黙知,形式知","SECI model, knowledge creation, tacit knowledge, explicit knowledge")
add("Ba (Knowledge Creation Space)","場（知識創造の空間）","知識創造が生じる共有された物理的・仮想的・精神的空間。野中が西田哲学の「場」概念をナレッジマネジメントに導入し、SECIモデルの各フェーズに対応する4種の「場」を定義した。","知識創造の文脈としての「場」の概念化。","知識創造論",1998,"organizational","知識創造の文脈的条件",["野中郁次郎","Konno"],["Nonaka & Konno (1998) The Concept of Ba"],"","場,知識空間,創造的文脈","Ba, knowledge space, creative context, shared space")
add("Knowledge Vision","知識ビジョン","組織の知識創造活動の方向性を示す戦略的指針。何を知るべきか、どのような知識を創造すべきかを示す上位概念として、知識創造プロセス全体を方向付ける。","知識創造活動の戦略的方向付け。","知識創造論",2000,"organizational","知識戦略の方向性",["野中郁次郎","Georg von Krogh"],["von Krogh, Ichijo & Nonaka (2000) Enabling Knowledge Creation"],"","知識ビジョン,知識戦略,方向性","knowledge vision, knowledge strategy, directionality")
add("Knowledge Asset Taxonomy","知識資産の分類体系","組織が保有する知識資産を体系的に分類する枠組み。経験的知識資産（暗黙的スキル）、概念的知識資産（言語化された概念）、体系的知識資産（マニュアル等）、定型的知識資産（データベース等）の4類型。","組織の知識資産の体系的分類と管理。","知識創造論",2000,"organizational","知識資産の類型化",["野中郁次郎","Toyama","Konno"],["Nonaka, Toyama & Konno (2000) SECI, Ba and Leadership"],"","知識資産分類,4類型,知識ポートフォリオ","knowledge asset taxonomy, four types, knowledge portfolio")

# === COMMUNITIES OF PRACTICE EXTENSIONS (322-345) ===
add("Community of Practice Design Principles","実践コミュニティの設計原則","CoP（実践コミュニティ）を組織的に育成・支援するための設計原則。Wenger, McDermott & Snyder（2002年）が7つの設計原則を提示し、自発性と制度的支援のバランスを重視した。","CoPの意図的育成のための実践的設計ガイドライン。","社会的学習理論",2002,"organizational","制度化された社会的学習",["Etienne Wenger","Richard McDermott","William Snyder"],["Wenger, McDermott & Snyder (2002) Cultivating Communities of Practice"],"","CoP設計,7原則,自発性と支援","CoP design, seven principles, voluntariness and support")
add("Network of Practice (NoP)","実践のネットワーク","CoP（対面的な実践コミュニティ）をより広範な、地理的に分散した弱い紐帯のネットワークに拡張した概念。John Seely BrownとPaul Duguidが概念化し、ICT技術がNoP形成を促進する。","地理的に分散した実践者の弱い紐帯ネットワーク。","社会的学習理論",2001,"organizational","分散的な実践者間の弱い紐帯",["John Seely Brown","Paul Duguid"],["Brown & Duguid (2001) Knowledge and Organization"],"","実践ネットワーク,弱い紐帯,分散型","network of practice, weak ties, distributed, ICT-enabled")
add("Virtual Community of Practice","仮想実践コミュニティ","ICT（Web、SNS、Wiki等）を基盤として形成される地理的に分散した実践コミュニティ。対面的な相互作用の欠如を補うバーチャルな知識共有・協働メカニズムの設計が課題。","デジタル技術を基盤とした分散型CoP。","社会的学習理論",2005,"organizational","バーチャルな知識共有",["Kimball & Rheingold"],["Kimball & Ladd (2004) Facilitator's Toolkit for Virtual Communities"],"","仮想CoP,オンラインコミュニティ,遠隔協働","virtual CoP, online community, remote collaboration")
add("Boundary Practice","境界実践","異なるCoPの境界で生じる実践。境界オブジェクト（boundary objects）やブローカー（brokers）を通じて、異なる知識領域・専門分野間の翻訳と知識移転を促進する実践的活動。","異なる実践領域間の知識橋渡しの実践。","社会的学習理論",2000,"organizational","境界を超える知識移転",["Etienne Wenger","Susan Leigh Star"],["Star & Griesemer (1989) Institutional Ecology, Translations"],"","境界実践,境界オブジェクト,ブローカー","boundary practice, boundary object, broker, knowledge translation")
add("Identity and Learning in Communities of Practice","実践コミュニティにおけるアイデンティティと学習","CoP内での学習が参加者のアイデンティティ形成と不可分に結びついているプロセスの分析。「何を学ぶか」だけでなく「誰になるか」が学習の本質的要素であるという社会的学習観。","学習とアイデンティティ形成の不可分性の理論化。","社会的学習理論",1998,"organizational","アイデンティティによる学習動機付け",["Etienne Wenger"],["Wenger (1998) Communities of Practice"],"","アイデンティティ,学習,参加,帰属","identity, learning, participation, belonging")

# === ORGANIZATIONAL MEMORY (327-350) ===
add("Organizational Memory","組織記憶","組織が過去の経験から蓄積した知識、ルーティン、手順、文化的規範等の総体。個人の記憶、文書・データベース、組織構造、ルーティン、文化に分散的に保持され、現在の意思決定に影響する。","組織における過去の知識と経験の保持メカニズム。","組織学習",1991,"organizational","集合的な知識保持と想起",["James Walsh","Gerardo Ungson"],["Walsh & Ungson (1991) Organizational Memory"],"","組織記憶,知識保持,ルーティン,文化","organizational memory, knowledge retention, routine, culture")
add("Transactive Memory System (TMS)","交差記憶システム","グループ内で「誰が何を知っているか」の共有認識に基づく分散的な知識保持・検索システム。Wegner（1987年）が概念化し、チームの専門化・調整・信頼性の3次元で測定される。","集合的知識の分散的保持と効率的検索のメカニズム。","組織学習",1987,"organizational","メタ知識による効率的知識アクセス",["Daniel Wegner","Kyle Lewis"],["Wegner (1987) TMS","Lewis (2003) Measuring TMS"],"","交差記憶,TMS,誰が何を知っているか","transactive memory system, TMS, who knows what, shared cognition")
add("Organizational Forgetting","組織的忘却","組織が蓄積した知識・能力を時間経過とともに喪失するプロセス。人材の離職、ルーティンの途絶、知識の陳腐化、意図的な忘却（unlearning）等の多様な形態がある。","知識・能力の喪失プロセスとその管理。","組織学習",2000,"organizational","知識の喪失と更新",["Pablo Martin de Holan","Nelson Phillips"],["de Holan & Phillips (2004) Organizational Forgetting"],"organizational memory","組織的忘却,知識喪失,アンラーニング","organizational forgetting, knowledge loss, unlearning, knowledge decay")
add("Organizational Unlearning","組織的アンラーニング","既存の知識・ルーティン・信念を意図的に放棄し、新しい知識への転換を可能にするプロセス。Hedberg（1981年）が概念化し、イノベーションと組織変革の前提条件として位置付けられる。","既存知識の意図的放棄による新知識への転換。","組織学習",1981,"organizational","既存フレームの解体と再構築",["Bo Hedberg"],["Hedberg (1981) How Organizations Learn and Unlearn"],"organizational learning","組織的アンラーニング,既存知識放棄,変革","organizational unlearning, knowledge discarding, transformation")
add("Declarative Organizational Memory","宣言的組織記憶","事実・概念・原理等の「何であるか」に関する明示的知識として組織に保持される記憶。データベース、マニュアル、レポート、公式手順等の形式で保存され、検索・参照が比較的容易。","事実知識としての組織記憶の形態。","組織学習",1991,"organizational","形式知の保持と検索",["Walsh & Ungson"],["Walsh & Ungson (1991) Organizational Memory"],"procedural organizational memory","宣言的記憶,形式知,データベース","declarative memory, explicit knowledge, database, documents")
add("Procedural Organizational Memory","手続き的組織記憶","「どのようにするか」に関する暗黙的知識として組織のルーティン・手順・スキルに埋め込まれた記憶。個人のスキルと組織のルーティンの両方に分散保持され、実践を通じて伝達される。","手続き知識としての組織記憶の形態。","組織学習",1991,"organizational","暗黙知のルーティンへの埋め込み",["Walsh & Ungson","Nelson & Winter"],["Nelson & Winter (1982) An Evolutionary Theory"],"declarative organizational memory","手続き的記憶,暗黙知,ルーティン","procedural memory, tacit knowledge, routine, embodied knowledge")
add("Knowledge Retention Strategy","知識保持戦略","退職・異動等による重要知識の流出を防止し、組織的知識基盤を維持するための戦略的アプローチ。メンタリング、知識移転セッション、文書化、知識監査、後継者計画等の手段を統合的に活用する。","組織的知識基盤の維持と流出防止の戦略。","知識マネジメント",2005,"organizational","知識流出の戦略的防止",["David DeLong"],["DeLong (2004) Lost Knowledge"],"","知識保持,知識流出防止,後継者計画","knowledge retention, brain drain prevention, succession planning")

# === KNOWLEDGE SPILLOVERS (334-360) ===
add("Knowledge Spillover Theory of Entrepreneurship","知識スピルオーバーの起業理論","大学・企業で生産された知識が組織内で十分に活用されず、起業家がスピルオーバーした知識を新事業として商業化するメカニズムの理論。Acs, Braunerhjelm等が知識フィルター概念と併せて理論化。","知識スピルオーバーが起業の源泉となるメカニズム。","知識スピルオーバー論",2009,"organizational","未活用知識の起業的商業化",["Zoltan Acs","David Audretsch","Pontus Braunerhjelm"],["Acs et al. (2009) KSTE: The Role of Entrepreneurship"],"","知識スピルオーバー起業,知識フィルター","knowledge spillover entrepreneurship, knowledge filter, commercialization")
add("Localized Knowledge Spillovers","地理的に限定された知識スピルオーバー","知識スピルオーバーが地理的に近接した範囲で強く、距離とともに急速に減衰するという実証的知見。Jaffe, Trajtenberg & Henderson（1993年）の特許引用分析が先駆的で、クラスター政策の理論的基盤。","知識スピルオーバーの地理的限定性の実証。","知識スピルオーバー論",1993,"organizational","地理的近接による暗黙知の伝達",["Adam Jaffe","Manuel Trajtenberg"],["Jaffe et al. (1993) Geographic Localization of Knowledge Spillovers"],"","地理的スピルオーバー,距離減衰,クラスター","localized spillovers, distance decay, cluster, proximity")
add("Inter-Industry Knowledge Spillovers","産業間知識スピルオーバー","異なる産業セクター間で生じる知識の外部性。Jacobs外部性（多様性からのスピルオーバー）として知られ、都市の産業多様性がイノベーションを促進するメカニズムの理論的基盤。","産業多様性からのイノベーション促進メカニズム。","知識スピルオーバー論",1969,"organizational","多様性による創造的組み合わせ",["Jane Jacobs","Glaeser et al."],["Jacobs (1969) The Economy of Cities"],"MAR externalities","産業間スピルオーバー,Jacobs外部性,多様性","inter-industry spillovers, Jacobs externalities, diversity")
add("MAR Externalities","MAR外部性","Marshall-Arrow-Romer外部性。同一産業内の企業集積から生じる知識スピルオーバー。専門化と産業内知識共有がイノベーションを促進するが、Jacobs外部性（多様性）との相対的重要性が論争テーマ。","産業内専門化からの知識スピルオーバー。","知識スピルオーバー論",1890,"organizational","専門化による深い知識共有",["Alfred Marshall","Kenneth Arrow","Paul Romer"],["Marshall (1890) Principles of Economics"],"Jacobs externalities","MAR外部性,専門化,産業集積","MAR externalities, specialization, industrial agglomeration")
add("Technology Spillover Measurement","技術スピルオーバーの測定","R&D活動から生じる技術的知識の外部性を定量的に測定する方法論。技術的距離マトリクス、特許引用フロー、生産性への間接効果推計（R&Dストック法）等の手法群。","技術的知識の外部性の定量化手法。","知識スピルオーバー論",1992,"measurement","知識の外部効果の計量",["Zvi Griliches","Adam Jaffe"],["Griliches (1992) The Search for R&D Spillovers"],"","技術スピルオーバー測定,外部性計量","technology spillover measurement, externality quantification")
add("FDI Knowledge Spillovers","FDIを通じた知識スピルオーバー","外国直接投資（FDI）を通じて多国籍企業から現地企業に技術・経営知識が波及するメカニズム。垂直的（サプライチェーン内）と水平的（同業種内）のスピルオーバー経路があり、現地企業の吸収能力が波及効果を左右する。","FDIを通じた知識・技術の現地波及メカニズム。","知識スピルオーバー論",2000,"organizational","多国籍企業からの知識移転",["Smarzynska Javorcik"],["Javorcik (2004) Does FDI Increase the Productivity of Domestic Firms?"],"","FDIスピルオーバー,多国籍企業,技術波及","FDI spillovers, multinational, technology diffusion, absorptive capacity")
add("University Knowledge Spillovers","大学からの知識スピルオーバー","大学の研究活動から地域の企業・産業に波及する知識の外部性。特許ライセンシング、スピンオフ、人材輩出、共同研究、非公式な接触等の多様なチャネルを通じて実現される。","大学研究から産業への多チャネル知識波及。","知識スピルオーバー論",1989,"organizational","大学-産業間知識フロー",["Adam Jaffe","Maryann Feldman"],["Jaffe (1989) Real Effects of Academic Research"],"","大学スピルオーバー,産学連携,地域効果","university spillovers, university-industry, regional effect")
add("Knowledge Spillover and Human Capital Mobility","知識スピルオーバーと人的資本の流動性","労働者の企業間移動を通じて暗黙知が伝播するメカニズム。特にシリコンバレーの高い人材流動性がイノベーション・スピルオーバーを促進するという実証的知見。","人材流動を通じた暗黙知伝播のメカニズム。","知識スピルオーバー論",2002,"organizational","人的移動による知識伝播",["Matt Marx","Toby Stuart"],["Almeida & Kogut (1999) Localization of Knowledge and the Mobility of Engineers"],"","人的資本流動,知識伝播,労働市場","human capital mobility, knowledge diffusion, labor market")

# === LEARNING CURVES & ORGANIZATIONAL LEARNING (342-380) ===
add("Learning Curve (Experience Curve)","学習曲線（経験曲線）","累積生産量の増加に伴って単位コストが低下する経験的法則。Wright（1936年）が航空機製造で発見し、BCGが戦略ツールとして普及させた。生産プロセスの暗黙的改善（learning-by-doing）が主因。","累積経験による生産効率の系統的改善の法則。","組織学習",1936,"process","生産経験の暗黙的蓄積",["Theodore Wright","BCG"],["Wright (1936) Factors Affecting the Cost of Airplanes"],"","学習曲線,経験曲線,コスト低下","learning curve, experience curve, cost reduction, learning-by-doing")
add("Learning by Doing","実行による学習","Arrow（1962年）が理論化した、生産活動の実行を通じて技術的知識が蓄積されるプロセス。意図的なR&Dではなく日常的な生産活動の副産物として知識が生成され、生産性を向上させる。","生産活動の副産物としての知識蓄積。","組織学習",1962,"process","実践を通じた暗黙的学習",["Kenneth Arrow"],["Arrow (1962) The Economic Implications of Learning by Doing"],"learning by research","実行学習,生産学習,Arrow","learning by doing, production learning, Arrow")
add("Learning by Using","使用による学習","Rosenberg（1982年）が概念化した、製品やシステムの使用経験を通じて性能改善のための知識が蓄積されるプロセス。ユーザーのフィードバックが製品改良の情報源となり、生産者の学習を補完する。","使用経験を通じた製品改良知識の蓄積。","組織学習",1982,"process","使用経験からのフィードバック",["Nathan Rosenberg"],["Rosenberg (1982) Inside the Black Box"],"","使用学習,ユーザーフィードバック,製品改良","learning by using, user feedback, product improvement")
add("Learning by Searching","探索による学習","意図的なR&D活動を通じて新しい科学的・技術的知識を体系的に追求するプロセス。learning-by-doingの副産物的学習と対比される、目的志向的な知識創造活動。","R&D活動を通じた目的志向的知識創造。","組織学習",1985,"organizational","意図的な知識探索",["Keith Pavitt","Giovanni Dosi"],["Dosi (1988) Sources, Procedures and Microeconomic Effects of Innovation"],"learning by doing","探索学習,R&D,目的志向的","learning by searching, R&D, purposive, systematic")
add("Learning by Interacting","相互作用による学習","サプライヤー、顧客、大学等の外部アクターとの相互作用を通じて知識を獲得するプロセス。Lundvall（1988年）がuser-producer相互作用として概念化し、イノベーションシステム論の基盤概念となった。","外部アクターとの相互作用を通じた知識獲得。","組織学習",1988,"organizational","対外的相互作用からの学習",["Bengt-Åke Lundvall"],["Lundvall (1988) Innovation as an Interactive Process"],"","相互作用学習,ユーザー-生産者,NIS","learning by interacting, user-producer, NIS, interactive learning")
add("Learning by Monitoring","監視による学習","Sabel（1994年）が概念化した、協力パートナーの活動を監視する過程で互いの能力と信頼性を学習するプロセス。取引コスト理論の機会主義的監視とは異なる、相互学習としての監視の肯定的側面を強調。","協力関係における相互監視からの学習。","組織学習",1994,"organizational","協力的監視からの相互学習",["Charles Sabel"],["Sabel (1994) Learning by Monitoring"],"","監視学習,協力的学習,相互監視","learning by monitoring, cooperative learning, mutual surveillance")
add("Learning Race","学習競争","アライアンス・パートナー間でパートナーの知識を先に吸収し自らの交渉力を高めようとする競争的学習行動。Hamel（1991年）が分析し、アライアンスにおける学習の競争的側面と協力的側面の緊張を明らかにした。","アライアンスにおける競争的学習のダイナミクス。","組織学習",1991,"organizational","競争的知識吸収",["Gary Hamel"],["Hamel (1991) Competition for Competence and Inter-Partner Learning"],"","学習競争,アライアンス,競争的吸収","learning race, alliance, competitive absorption, partner learning")
add("Experiential Learning Theory","経験学習理論","Kolb（1984年）が提唱した、具体的経験→内省的観察→抽象的概念化→能動的実験の4段階サイクルによる学習モデル。Deweyの経験主義教育哲学を組織的学習の文脈に体系化した。","経験を通じた4段階サイクル学習モデル。","組織学習",1984,"organizational","4段階の経験学習サイクル",["David Kolb"],["Kolb (1984) Experiential Learning"],"","経験学習,Kolbサイクル,内省","experiential learning, Kolb cycle, reflection, abstract conceptualization")
add("Single-Loop Learning","シングルループ学習","既存の目標・価値観・規範の枠内で行動の修正を行う学習。Argyris & Schön（1978年）が概念化し、「与えられた枠組みの中での問題解決」として、ダブルループ学習と対比される。","既存枠組み内での行動修正型学習。","組織学習",1978,"organizational","既存フレーム内の修正",["Chris Argyris","Donald Schön"],["Argyris & Schön (1978) Organizational Learning"],"double-loop learning","シングルループ,行動修正,既存枠組み","single-loop learning, behavior correction, existing framework")
add("Double-Loop Learning","ダブルループ学習","既存の目標・価値観・規範自体を問い直し、前提の変更を通じて根本的な問題解決を図る学習。Argyris & Schön（1978年）の概念で、組織変革とイノベーションの基盤的学習形態。","前提自体を問い直す根本的学習。","組織学習",1978,"organizational","前提の再検討と変革",["Chris Argyris","Donald Schön"],["Argyris & Schön (1978) Organizational Learning"],"single-loop learning","ダブルループ,前提変更,組織変革","double-loop learning, assumption change, organizational change")
add("Deutero-Learning","第二次学習","学習のプロセス自体について学ぶメタレベルの学習。Argyris & Schönが3番目の学習レベルとして概念化し、組織が自らの学習能力を改善する「学習の仕方を学ぶ」能力を指す。","学習プロセス自体の改善（メタ学習）。","組織学習",1978,"organizational","学習能力自体の改善",["Chris Argyris","Donald Schön","Gregory Bateson"],["Bateson (1972) Steps to an Ecology of Mind"],"","第二次学習,メタ学習,学習能力改善","deutero-learning, meta-learning, learning to learn")
add("Learning Organization","学習する組織","継続的に学習し変容する能力を制度化した組織。Senge（1990年）のシステム思考、自己マスタリー、メンタルモデル、共有ビジョン、チーム学習の5つのディシプリンが代表的な枠組み。","継続的学習能力を制度化した組織概念。","組織学習",1990,"organizational","5つのディシプリンの統合",["Peter Senge"],["Senge (1990) The Fifth Discipline"],"","学習する組織,5つのディシプリン,Senge","learning organization, five disciplines, Senge, systems thinking")

# === DYNAMIC CAPABILITIES (354-380) ===
add("Dynamic Capabilities Framework","動的能力フレームワーク","急速に変化する環境に対応するため、組織の資源・能力を統合・構築・再構成する高次の組織能力。Teece, Pisano & Shuen（1997年）が提唱し、感知（sensing）→捕捉（seizing）→変革（transforming）の3能力に体系化。","組織の持続的競争優位を動態的に説明する枠組み。","動的能力論",1997,"organizational","環境適応のための能力再構成",["David Teece","Gary Pisano","Amy Shuen"],["Teece, Pisano & Shuen (1997) Dynamic Capabilities"],"","動的能力,感知,捕捉,変革","dynamic capabilities, sensing, seizing, transforming")
add("Sensing Capability","感知能力","環境中の機会と脅威を探索・フィルタリング・解釈する能力。Teece（2007年）の動的能力フレームワークの第1柱。R&D活動、顧客インサイト、技術スカウティング、シナリオ分析等のプロセスを通じて実現。","環境中の機会・脅威の組織的探索能力。","動的能力論",2007,"organizational","機会の組織的探索と解釈",["David Teece"],["Teece (2007) Explicating Dynamic Capabilities"],"","感知能力,機会探索,環境スキャン","sensing capability, opportunity search, environmental scan")
add("Seizing Capability","捕捉能力","感知した機会を活用するために、ビジネスモデルの設計、資源の動員・配分、組織的コミットメントの形成を行う能力。Teece（2007年）の動的能力フレームワークの第2柱。","機会の実践的活用のための組織的動員能力。","動的能力論",2007,"organizational","機会への組織的資源動員",["David Teece"],["Teece (2007) Explicating Dynamic Capabilities"],"","捕捉能力,資源動員,ビジネスモデル","seizing capability, resource mobilization, business model design")
add("Transforming Capability","変革能力","既存の資源・能力・組織構造を再構成し、新しい機会に対応する能力。Teece（2007年）の動的能力フレームワークの第3柱。組織変革、知識管理、ガバナンス構造の適応等を含む。","組織的資源・構造の根本的再構成能力。","動的能力論",2007,"organizational","組織構造の適応的再構成",["David Teece"],["Teece (2007) Explicating Dynamic Capabilities"],"","変革能力,再構成,組織変革","transforming capability, reconfiguration, organizational change")
add("Micro-Foundations of Dynamic Capabilities","動的能力のミクロ基盤","動的能力の基盤となる個人レベルの認知・行動・スキルの分析。経営者の認知フレーム、アテンション配分、意思決定ヒューリスティクス等がマクロレベルの動的能力を構成するメカニズム。","動的能力の個人レベルの認知的・行動的基盤。","動的能力論",2010,"organizational","経営者認知の動的能力への影響",["Constance Helfat","Sidney Winter","Teppo Felin"],["Felin & Foss (2005) Strategic Organization and the Knowledge Economy"],"","ミクロ基盤,経営者認知,アテンション","micro-foundations, managerial cognition, attention allocation")
add("Ordinary Capabilities vs Dynamic Capabilities","通常能力と動的能力","日常的な業務遂行を支える通常能力（operational capabilities）と、その通常能力を変更・拡張する高次の動的能力の区別。Winter（2003年）が能力の階層構造を明確化し、ゼロ次能力（通常）と一次能力（動的）を区分。","能力の階層構造と動的能力の位置付け。","動的能力論",2003,"organizational","能力の階層的構造化",["Sidney Winter"],["Winter (2003) Understanding Dynamic Capabilities"],"","通常能力,能力階層,ゼロ次能力","ordinary capabilities, capability hierarchy, zero-level capability")
add("Ambidextrous Organization","両利きの経営","既存事業の活用（exploitation）と新規事業の探索（exploration）を同時に追求する組織能力。March（1991年）の探索-活用概念をO'Reilly & Tushman（2004年）が組織設計の観点から発展させた。","探索と活用の同時追求の組織設計。","動的能力論",2004,"organizational","探索と活用の構造的分離と統合",["James March","Charles O'Reilly III","Michael Tushman"],["O'Reilly & Tushman (2004) The Ambidextrous Organization"],"","両利きの経営,探索と活用,構造的分離","ambidextrous organization, exploration-exploitation, structural separation")
add("Exploration vs Exploitation Trade-off","探索と活用のトレードオフ","March（1991年）が定式化した、新しい可能性の探索（exploration）と既知の確実性の活用（exploitation）の間の組織的資源配分のトレードオフ。近視眼的な活用偏重がイノベーション能力を侵食する。","探索と活用の資源配分トレードオフ。","組織学習",1991,"organizational","組織的資源配分のジレンマ",["James March"],["March (1991) Exploration and Exploitation in Organizational Learning"],"","探索vs活用,トレードオフ,March","exploration vs exploitation, trade-off, March, resource allocation")

# === INTELLECTUAL CAPITAL (362-390) ===
add("Intellectual Capital Measurement","知的資本の測定","組織の知的資本（人的資本、構造資本、関係資本）を体系的に測定・報告する方法論。Skandia Navigator、Balanced Scorecard、VAIC（Value Added Intellectual Coefficient）等の測定フレームワーク。","組織の知的資本の体系的測定・報告方法論。","知的資本論",1997,"organizational","無形資産の定量化",["Leif Edvinsson","Thomas Stewart"],["Edvinsson & Malone (1997) Intellectual Capital"],"","知的資本測定,Skandia,無形資産","intellectual capital measurement, Skandia, intangible assets")
add("Human Capital in Innovation","イノベーションにおける人的資本","従業員の知識、スキル、経験、創造性がイノベーション能力に与える影響の分析。STEM人材、T型人材、起業家的人材等の人的資本の質と構成がイノベーション・パフォーマンスを規定する。","人的資本がイノベーション能力を規定するメカニズム。","知的資本論",1960,"organizational","人材の質がイノベーションに与える影響",["Gary Becker","Theodore Schultz"],["Becker (1964) Human Capital"],"","人的資本,STEM人材,T型人材","human capital, STEM talent, T-shaped talent, innovation workforce")
add("Structural Capital","構造資本","組織の知識インフラ（データベース、プロセス、知的財産、組織文化等）として人的資本が退出しても組織に残る知的資本の要素。組織の「夜に帰宅しない」知識として、人的資本の効果を増幅する基盤。","組織に残存する知識インフラとしての知的資本。","知的資本論",1997,"organizational","組織的知識インフラ",["Leif Edvinsson"],["Edvinsson & Malone (1997) Intellectual Capital"],"","構造資本,知識インフラ,組織プロセス","structural capital, knowledge infrastructure, organizational processes")
add("Relational Capital","関係資本","組織が外部のステークホルダー（顧客、サプライヤー、パートナー、コミュニティ等）との関係を通じて保有する知的資本。信頼、ブランド、評判、顧客ロイヤルティ、ネットワーク関係等が含まれる。","外部関係から生じる知的資本の要素。","知的資本論",1997,"organizational","外部関係の知識的価値",["Leif Edvinsson","Johan Roos"],["Roos et al. (1997) Intellectual Capital"],"","関係資本,顧客関係,信頼,ネットワーク","relational capital, customer relationships, trust, network value")
add("Knowledge-Based View of the Firm","企業の知識ベース論","企業の競争優位の源泉を知識（特に暗黙知の統合と活用）に求める理論。Grant（1996年）が体系化し、企業の存在理由を「市場では達成できない知識統合メカニズムの提供」と位置付けた。","知識を企業の競争優位の中核的源泉とする理論。","知識ベース論",1996,"organizational","知識統合メカニズムとしての企業",["Robert Grant","J.C. Spender"],["Grant (1996) Toward a Knowledge-Based Theory of the Firm"],"","知識ベース論,知識統合,暗黙知","knowledge-based view, knowledge integration, tacit knowledge")
add("Knowledge Worker Productivity","知識労働者の生産性","Drucker（1999年）が提起した、知識労働者の生産性をどのように定義・測定・向上させるかという課題。肉体労働の生産性（テイラー主義）とは根本的に異なるアプローチが必要であり、21世紀のマネジメント最大の課題。","知識労働の生産性の定義・測定・向上の課題。","知識マネジメント",1999,"organizational","知識労働の成果測定",["Peter Drucker"],["Drucker (1999) Management Challenges for the 21st Century"],"","知識労働者,生産性,Drucker","knowledge worker, productivity, Drucker, knowledge work")
add("Knowledge Intensive Firm (KIF)","知識集約型企業","知的資本が最も重要な生産要素であり、高度な専門知識を持つ従業員が価値創造の中核を担う企業類型。コンサルティング、法律、IT、研究開発等の専門サービス企業が典型的。Alvesson（2004年）が特徴を体系化。","知識が最重要生産要素である企業の特性分析。","知識マネジメント",2004,"organizational","知識集約型の組織運営",["Mats Alvesson"],["Alvesson (2004) Knowledge Work and Knowledge-Intensive Firms"],"","知識集約型企業,専門サービス,知的資本","KIF, professional services, intellectual capital, knowledge work")
add("Intellectual Capital Reporting","知的資本報告","組織の知的資本の状態と変化を外部ステークホルダーに報告する開示制度。欧州のIC報告ガイドライン（MERITUM等）やGRI基準が枠組みを提供し、財務報告を補完する非財務情報開示。","知的資本の外部ステークホルダーへの報告制度。","知的資本論",2002,"organizational","無形資産の開示",["European Commission","MERITUM Project"],["MERITUM Guidelines (2002)"],"","知的資本報告,非財務開示,IR","intellectual capital reporting, non-financial disclosure, integrated reporting")

# === KNOWLEDGE NETWORKS & FLOWS (370-400) ===
add("Knowledge Network Analysis","知識ネットワーク分析","組織内外の知識フローの構造をネットワーク分析手法で可視化・分析する方法論。知識の送り手-受け手の関係、仲介者の役割、ネットワークの密度・集中度等を定量的に把握し、知識共有の障害と促進要因を特定する。","知識フロー構造のネットワーク的分析手法。","知識マネジメント",2002,"organizational","知識フローの構造的分析",["Rob Cross","Andrew Parker"],["Cross & Parker (2004) The Hidden Power of Social Networks"],"","知識ネットワーク,フロー分析,社会ネットワーク","knowledge network, flow analysis, social network, knowledge broker")
add("Knowledge Broker","知識ブローカー","異なる知識領域やコミュニティ間を橋渡しし、知識の翻訳・移転・結合を促進する個人・組織。Hargadon（2003年）がテクノロジーブローカリングとして概念化し、知識仲介が革新的組み合わせを生み出すメカニズムを解明。","異なる知識領域間の橋渡しと革新的結合。","知識マネジメント",2003,"organizational","知識の仲介と創造的結合",["Andrew Hargadon"],["Hargadon (2003) How Breakthroughs Happen"],"","知識ブローカー,橋渡し,テクノロジーブローカリング","knowledge broker, bridging, technology brokering, recombination")
add("Knowledge Flows in Multinational Corporations","多国籍企業における知識フロー","本社と子会社間、子会社間の知識移転パターンを分析する研究領域。知識の方向性（本社→子会社、子会社→本社、子会社間）、知識の特性（暗黙度、複雑性）、組織的メカニズムが移転効果を規定する。","多国籍企業内部の知識移転パターンの分析。","知識マネジメント",2000,"organizational","国際的な組織内知識移転",["Ulf Andersson","Mats Forsgren","Torben Pedersen"],["Gupta & Govindarajan (2000) Knowledge Flows Within MNCs"],"","MNC知識フロー,子会社間移転,知識方向性","MNC knowledge flow, subsidiary transfer, knowledge directionality")
add("Knowledge Stickiness","知識の粘着性","知識がその生成文脈に「粘着」し、他の文脈への移転が困難である性質。von Hippel（1994年）が概念化し、暗黙性、文脈依存性、因果曖昧性等の知識特性が粘着性の源泉となる。","知識の文脈依存的な移転困難性。","知識マネジメント",1994,"organizational","知識の文脈依存的固着",["Eric von Hippel"],["von Hippel (1994) Sticky Information and the Locus of Problem Solving"],"","知識粘着性,移転困難,文脈依存","knowledge stickiness, transfer difficulty, context dependency")
add("Knowledge Transfer in Strategic Alliances","戦略的アライアンスにおける知識移転","企業間アライアンスを通じた知識移転のメカニズム、促進要因、阻害要因の分析。信頼の役割、知識の暗黙性、パートナー間の吸収能力格差、ガバナンス構造が移転効果を規定する。","アライアンスを通じた知識移転のダイナミクス。","知識マネジメント",1998,"organizational","組織間の知識移転と吸収",["Marjorie Lyles","Jane Salk"],["Mowery, Oxley & Silverman (1996) Strategic Alliances and Interfirm Knowledge Transfer"],"","アライアンス知識移転,信頼,ガバナンス","alliance knowledge transfer, trust, governance, inter-firm learning")
add("Reverse Knowledge Transfer","逆知識移転","多国籍企業において、子会社（特に新興国子会社）から本社に向かう知識移転。新興国市場での独自の知識・イノベーションが先進国の親会社の能力を強化するメカニズム。","子会社から親会社への知識の逆流。","知識マネジメント",2005,"organizational","子会社起点の知識フロー",["Ulf Andersson","Dana Minbaeva"],["Ambos, Ambos & Schlegelmilch (2006) Learning from Foreign Subsidiaries"],"","逆知識移転,子会社発イノベーション","reverse knowledge transfer, subsidiary-driven innovation, knowledge flow")
add("Knowledge Commons","知識コモンズ","共有資源として管理される知識資産。オープンソース・ソフトウェア、Creative Commons、学術論文のオープンアクセス等が代表的で、Hess & Ostrom（2007年）が知識のコモンズ管理の理論的枠組みを提供。","共有資源としての知識管理の理論と実践。","知識マネジメント",2007,"organizational","知識の集合的管理",["Charlotte Hess","Elinor Ostrom"],["Hess & Ostrom (2007) Understanding Knowledge as a Commons"],"proprietary knowledge","知識コモンズ,オープンアクセス,共有管理","knowledge commons, open access, collective management, Ostrom")
add("Knowledge Ecology","知識生態学","知識の創造・進化・選択・保持のプロセスを生態学的アナロジーで分析する概念的枠組み。知識の多様性、競争、共生、ニッチ形成等の生態学的概念を知識ダイナミクスに適用する。","知識ダイナミクスの生態学的分析枠組み。","知識マネジメント",2000,"organizational","知識の進化と淘汰",["George Pór"],["Pór (2000) Nurturing Systemic Wisdom Through Knowledge Ecology"],"","知識生態学,進化,多様性","knowledge ecology, evolution, diversity, knowledge niche")

# === KNOWLEDGE GOVERNANCE & STRATEGY (378-410) ===
add("Knowledge Strategy","知識戦略","組織が競争優位を構築・維持するために、どのような知識を開発・獲得・保護・活用するかに関する戦略的意思決定。知識の内部開発vs外部獲得（make vs buy）、知識保護戦略（特許vs営業秘密）等を含む。","知識資源の戦略的管理の枠組み。","知識マネジメント",1998,"organizational","知識の戦略的選択と管理",["Ikujiro Nonaka","Max Boisot"],["Zack (1999) Developing a Knowledge Strategy"],"","知識戦略,Make vs Buy,知識保護","knowledge strategy, make vs buy, knowledge protection, strategic choice")
add("Knowledge Protection Mechanism","知識保護メカニズム","組織の競争優位の源泉である知識資産を模倣・流出から保護するメカニズム群。法的保護（特許、著作権、営業秘密法）、組織的保護（アクセス制限、暗黙知化）、人的保護（非競争条項、知識分散化）を含む。","知識資産の模倣・流出からの多層的保護。","知識マネジメント",2000,"organizational","知識流出の防止策",["James Liebeskind"],["Liebeskind (1996) Knowledge, Strategy, and the Theory of the Firm"],"knowledge sharing","知識保護,流出防止,営業秘密","knowledge protection, leakage prevention, trade secret, IP protection")
add("Causal Ambiguity","因果曖昧性","競争優位の源泉となる資源・能力と成果の間の因果関係が不明確であること。Lippman & Rumelt（1982年）が概念化し、因果曖昧性が模倣障壁として機能する一方、知識の内部移転も困難にするパラドックスを生む。","因果曖昧性が模倣障壁と内部移転障壁の両面で機能。","知識ベース論",1982,"organizational","知識の不透明性による保護と障壁",["Steven Lippman","Richard Rumelt"],["Lippman & Rumelt (1982) Uncertain Imitability"],"","因果曖昧性,模倣障壁,知識移転障壁","causal ambiguity, imitation barrier, knowledge transfer barrier")
add("Knowledge Sharing Incentive Design","知識共有インセンティブ設計","組織内の知識共有を促進するためのインセンティブ・メカニズムの設計。金銭的報酬、評価制度への統合、キャリア昇進との連動、互恵的規範の構築、ゲーミフィケーション等の手段を用いて「知識の買い占め」を克服する。","知識共有を促進するインセンティブ・メカニズム設計。","知識マネジメント",2005,"organizational","知識共有の動機付け設計",["Morten Hansen"],["Hansen, Nohria & Tierney (1999) What's Your Strategy for Managing Knowledge?"],"","知識共有インセンティブ,報酬設計,動機付け","knowledge sharing incentive, reward design, motivation, gamification")
add("Tacit Knowledge Transfer Methods","暗黙知移転手法","形式化・言語化が困難な暗黙知を組織内で効果的に移転するための手法群。メンタリング、師弟関係、ジョブローテーション、ストーリーテリング、シャドーイング、共同実践等の実践的アプローチ。","暗黙知の効果的な組織内移転手法。","知識マネジメント",2000,"organizational","暗黙知の社会的伝達",["Nonaka","Szulanski"],["Szulanski (1996) Exploring Internal Stickiness"],"","暗黙知移転,メンタリング,師弟関係","tacit knowledge transfer, mentoring, apprenticeship, storytelling")
add("Knowledge-Based Dynamic Capabilities","知識ベースの動的能力","動的能力の基盤を知識プロセス（知識創造、知識統合、知識再構成）に求めるアプローチ。組織の知識基盤の拡張と再構成が環境適応のための動的能力を構成するという理論的統合。","知識プロセスを基盤とする動的能力の理論化。","動的能力論",2005,"organizational","知識の動態的再構成",["Teece","Nonaka","Zollo"],["Zollo & Winter (2002) Deliberate Learning and the Evolution of Dynamic Capabilities"],"","知識ベース動的能力,知識再構成,能力進化","knowledge-based DC, knowledge reconfiguration, capability evolution")
add("Knowledge Ambidexterity","知識の両利き","既存知識の活用（exploitation）と新知識の探索（exploration）を知識レベルで同時追求する組織能力。知識の深化と知識の多角化のバランスが組織のイノベーション能力を規定する。","知識の深化と多角化の同時追求能力。","知識マネジメント",2010,"organizational","知識の深化と多角化のバランス",["Mom, van den Bosch & Volberda"],["Mom et al. (2007) Investigating Managers' Exploration and Exploitation Activities"],"","知識両利き,知識深化,知識多角化","knowledge ambidexterity, knowledge deepening, knowledge diversification")
add("Social Capital and Knowledge Sharing","社会関係資本と知識共有","組織内外の社会的ネットワーク、信頼関係、共有規範（社会関係資本）が知識共有を促進するメカニズムの分析。Nahapiet & Ghoshal（1998年）が知的資本の創出における社会関係資本の役割を理論化。","社会関係資本が知識共有を促進するメカニズム。","知識マネジメント",1998,"organizational","社会的紐帯による知識フロー促進",["Janine Nahapiet","Sumantra Ghoshal"],["Nahapiet & Ghoshal (1998) Social Capital, Intellectual Capital"],"","社会関係資本,知識共有,信頼,ネットワーク","social capital, knowledge sharing, trust, network, intellectual capital")
add("Knowledge-Based Alliance Management","知識ベースのアライアンス管理","戦略的アライアンスの目的を知識獲得・学習に焦点化し、パートナー選択、ガバナンス設計、学習プロセス管理を知識フロー最適化の観点から行うマネジメント・アプローチ。","知識獲得を目的とするアライアンスの管理手法。","知識マネジメント",2000,"organizational","知識目的のパートナーシップ管理",["Anoop Madhok","Stephen Tallman"],["Tallman & Chacar (2011) Knowledge, Capability, and Competition"],"","知識アライアンス,パートナー選択,学習管理","knowledge alliance, partner selection, learning management")
add("Knowledge Codification Strategy","知識コード化戦略","暗黙知をマニュアル、データベース、ソフトウェア等の形式知に変換し、組織的な再利用とスケールを可能にする知識マネジメント戦略。Hansen, Nohria & Tierney（1999年）がPersonalization戦略と対比してCodification戦略を類型化。","暗黙知の形式知化による組織的スケーリング。","知識マネジメント",1999,"organizational","知識のコード化と再利用",["Morten Hansen","Nitin Nohria","Thomas Tierney"],["Hansen, Nohria & Tierney (1999) What's Your Strategy?"],"personalization strategy","知識コード化,形式知化,再利用","knowledge codification, formalization, reuse, scalability")
add("Knowledge Personalization Strategy","知識パーソナリゼーション戦略","知識をコード化するのではなく、人と人の直接的な対話・相互作用を通じて暗黙知を共有する知識マネジメント戦略。メンター制度、ワークショップ、ナラティブ手法等を重視し、コンサルティング企業等で採用。","人的相互作用を通じた暗黙知共有戦略。","知識マネジメント",1999,"organizational","対話を通じた暗黙知共有",["Morten Hansen","Nitin Nohria","Thomas Tierney"],["Hansen, Nohria & Tierney (1999) What's Your Strategy?"],"codification strategy","パーソナリゼーション,対話,暗黙知共有","personalization, dialogue, tacit knowledge sharing, mentor")

# === COGNITIVE FOUNDATIONS OF LEARNING (388-420) ===
add("Absorptive Capacity and Cognitive Frames","吸収能力と認知フレーム","組織の認知フレーム（注意配分のパターン、解釈スキーマ、因果的信念）が吸収能力の方向性と限界を規定するメカニズム。既存の認知フレームは関連知識の認識を促進する一方、フレーム外の知識を見逃す「能力の罠」を生む。","認知フレームが吸収能力を方向付け制約するメカニズム。","知識マネジメント",2005,"organizational","認知的フィルターとしてのフレーム",["Volberda, Foss & Lyles"],["Volberda et al. (2010) Absorptive Capacity: Taking Stock"],"","認知フレーム,注意配分,能力の罠","cognitive frames, attention allocation, competency trap")
add("Dominant Logic","支配的論理","経営陣が事業を概念化し重要な資源配分の意思決定を行う際の思考パターン。Prahalad & Bettis（1986年）が概念化し、支配的論理が環境変化に対する組織の適応を妨げるメカニズムを分析。","経営陣の思考パターンが組織適応を規定・制約する。","組織学習",1986,"organizational","経営者の認知的制約",["C.K. Prahalad","Richard Bettis"],["Prahalad & Bettis (1986) The Dominant Logic"],"","支配的論理,認知的制約,経営者マインドセット","dominant logic, cognitive constraint, managerial mindset")
add("Competency Trap","能力の罠","既存の能力への過度の依存（活用偏重）が新しい能力の開発（探索）を阻害し、環境変化への適応能力を損なう現象。Levitt & March（1988年）が組織学習の「罠」として概念化。","既存能力への過度依存がイノベーションを阻害。","組織学習",1988,"organizational","活用偏重による探索の抑制",["Barbara Levitt","James March"],["Levitt & March (1988) Organizational Learning"],"","能力の罠,活用偏重,適応失敗","competency trap, exploitation bias, adaptation failure")
add("Cognitive Search in Problem Solving","問題解決における認知的探索","組織が問題解決のために知識空間を探索するプロセスの認知的モデル。ローカルサーチ（近接的探索）とディスタントサーチ（遠隔的探索）のバランスが解の新規性と質を規定する。NKランドスケープモデルが分析ツール。","知識空間の認知的探索と解の新規性。","組織学習",2000,"organizational","知識空間の探索バランス",["Jan Rivkin","Daniel Levinthal"],["Rivkin & Siggelkow (2003) Balancing Search and Stability"],"","認知的探索,ローカルサーチ,NKモデル","cognitive search, local search, NK model, problem-solving landscape")
add("Organizational Attention","組織的注意","組織が環境中のどの情報・問題・機会に注意を配分するかの構造的パターン。Ocasio（1997年）の注意ベース観点（Attention-Based View）が、注意配分が組織行動とイノベーションの方向性を規定するメカニズムを理論化。","組織の注意配分がイノベーション方向性を規定する。","組織学習",1997,"organizational","注意配分による意思決定の方向付け",["William Ocasio"],["Ocasio (1997) Towards an Attention-Based View of the Firm"],"","組織的注意,ABV,注意配分","organizational attention, ABV, attention allocation, issue salience")
add("Sensemaking in Organizations","組織におけるセンスメイキング","組織メンバーが曖昧な状況に意味を付与し、理解可能な枠組みを構築するプロセス。Weick（1995年）が理論化し、危機対応、戦略形成、イノベーション・プロセスにおける集合的意味構築の重要性を強調。","組織における集合的な意味構築プロセス。","組織学習",1995,"organizational","集合的な意味構築と解釈",["Karl Weick"],["Weick (1995) Sensemaking in Organizations"],"","センスメイキング,意味構築,解釈","sensemaking, meaning construction, interpretation, enactment")
add("Absorptive Capacity and Open Innovation","吸収能力とオープンイノベーション","オープンイノベーション戦略の効果が企業の吸収能力に依存するメカニズムの分析。外部知識源の多様性と吸収能力の相互作用がイノベーション・パフォーマンスを規定し、「最適な開放度」が存在する。","オープンイノベーションにおける吸収能力の調整効果。","知識マネジメント",2006,"organizational","開放度と吸収能力の相互作用",["Keld Laursen","Ammon Salter"],["Laursen & Salter (2006) Open for Innovation"],"","吸収能力とOI,開放度,外部知識活用","absorptive capacity and OI, openness, external knowledge utilization")
add("Knowledge Search Breadth and Depth","知識探索の幅と深さ","企業が外部知識を探索する際の幅（異なる知識源の数）と深さ（各知識源からの知識吸収の程度）のバランスがイノベーション・パフォーマンスに与える影響の分析。逆U字関係の実証。","知識探索の幅と深さのイノベーションへの影響。","知識マネジメント",2006,"organizational","探索パターンの最適化",["Keld Laursen","Ammon Salter"],["Laursen & Salter (2006) Open for Innovation"],"","探索の幅,探索の深さ,逆U字","search breadth, search depth, inverted-U, optimal openness")

# === KNOWLEDGE TECHNOLOGY & AI (396-430) ===
add("Knowledge Graph for Innovation","イノベーションのための知識グラフ","概念、研究者、技術、特許、企業等のエンティティとその関係をグラフ構造で表現し、イノベーション機会の発見や技術動向の分析を支援するデータ構造と分析手法。","知識関係のグラフ構造化によるイノベーション分析。","知識マネジメント",2012,"organizational","構造化された知識の関係分析",["Google","Various researchers"],["Google Knowledge Graph","Ehrlinger & Wöß (2016)"],"","知識グラフ,関係分析,イノベーション発見","knowledge graph, relationship analysis, innovation discovery")
add("AI-Augmented Knowledge Management","AI支援型知識管理","自然言語処理、機械学習、推薦システム等のAI技術を活用して、知識の発見、分類、推薦、要約、翻訳等の知識管理プロセスを自動化・高度化するアプローチ。","AI技術による知識管理プロセスの高度化。","知識マネジメント",2018,"organizational","AIによる知識プロセスの自動化",["IBM Watson","Various"],["Davenport & Ronanki (2018) Artificial Intelligence for the Real World"],"","AI知識管理,NLP,自動化","AI knowledge management, NLP, automation, smart KM")
add("Large Language Models and Organizational Knowledge","大規模言語モデルと組織知識","ChatGPT等の大規模言語モデル（LLM）が組織の知識管理、学習、創造性に与える変革的影響の分析。知識のアクセシビリティ、暗黙知の部分的形式知化、組織記憶のAI拡張等の可能性と課題。","LLMが組織知識に与える変革的影響の分析。","知識マネジメント",2023,"organizational","LLMによる知識プロセスの変革",["OpenAI","Various researchers"],["Dell'Acqua et al. (2023) Navigating the Jagged Technological Frontier"],"","LLM,組織知識,AI拡張","LLM, organizational knowledge, AI augmentation, knowledge access")
add("Digital Knowledge Platform","デジタル知識プラットフォーム","組織の知識の創造、蓄積、共有、活用を統合的に支援するデジタルプラットフォーム。Slack、Teams、Notion、Confluence等のツールが実質的な知識プラットフォームとして機能し、知識マネジメントのインフラを形成。","知識管理の統合的デジタルプラットフォーム。","知識マネジメント",2015,"organizational","デジタル環境での知識管理",["Various technology companies"],["McAfee & Brynjolfsson (2017) Machine, Platform, Crowd"],"","知識プラットフォーム,デジタルツール,Slack","digital knowledge platform, digital tools, collaboration, knowledge sharing")
add("Knowledge Automation","知識の自動化","定型的な知識労働（データ分析、報告書作成、パターン認識等）をAI・RPA等の技術で自動化するプロセス。人間の知識労働者はより創造的・判断的な知識活動に集中可能になる。","定型的知識労働のAI自動化。","知識マネジメント",2015,"organizational","知識労働の機械化",["Thomas Davenport"],["Davenport & Kirby (2016) Only Humans Need Apply"],"","知識自動化,RPA,AI,定型知識労働","knowledge automation, RPA, AI, routine knowledge work")

# === REMAINING ENTRIES TO 719 (401-419) ===
add("Cognitive Diversity and Innovation","認知的多様性とイノベーション","チーム・組織メンバーの思考スタイル、問題解決アプローチ、知識基盤の多様性がイノベーション・パフォーマンスに与える影響の分析。認知的多様性は問題解決の解空間を拡大するが、調整コストも増大させる。","認知的多様性のイノベーション促進メカニズム。","組織学習",2004,"organizational","認知的多様性による創造的問題解決",["Scott Page"],["Page (2007) The Difference"],"","認知的多様性,創造的問題解決,チーム構成","cognitive diversity, creative problem solving, team composition")
add("Knowledge Integration in Cross-Functional Teams","機能横断チームにおける知識統合","マーケティング、エンジニアリング、製造等の異なる機能部門の専門知識を新製品開発チーム内で統合するメカニズム。共有言語の開発、境界オブジェクト、T型スキル人材等が統合を促進する。","機能横断的な専門知識の統合メカニズム。","知識マネジメント",1997,"organizational","異領域知識の統合プロセス",["Kathleen Eisenhardt","Behnam Tabrizi"],["Eisenhardt & Tabrizi (1995) Accelerating Adaptive Processes"],"","機能横断チーム,知識統合,共有言語","cross-functional team, knowledge integration, shared language")
add("Organizational Learning from Failure","失敗からの組織学習","プロジェクトの失敗、事故、ミス等の否定的経験から組織が体系的に学習するメカニズム。心理的安全性（Edmondson）が失敗からの学習を促進する組織条件として重要。","失敗経験からの組織的学習のメカニズムと条件。","組織学習",1999,"organizational","失敗からの教訓抽出と適用",["Amy Edmondson"],["Edmondson (1999) Psychological Safety and Learning Behavior"],"","失敗学習,心理的安全性,教訓","learning from failure, psychological safety, lessons, error management")
add("Psychological Safety","心理的安全性","対人関係のリスクを取っても安全だというチームの共有信念。Edmondson（1999年）が概念化し、心理的安全性が高いチームでは失敗の報告、質問、アイデア提案等の学習行動が促進される。","チーム学習を促進する心理的条件。","組織学習",1999,"organizational","安全な環境での学習行動促進",["Amy Edmondson"],["Edmondson (1999) Psychological Safety and Learning Behavior"],"","心理的安全性,チーム学習,リスクテイキング","psychological safety, team learning, risk-taking, speaking up")
add("Knowledge-Creating Crew","知識創造クルー","プロジェクトベースで集まり、知識創造活動を行う小規模チーム。野中の「自己組織化チーム」概念を発展させ、多様な専門性を持つメンバーが自律的に知識創造プロセスを推進する組織単位。","プロジェクトベースの知識創造チーム。","知識創造論",2008,"organizational","自律的知識創造の組織単位",["野中郁次郎","竹内弘高"],["Nonaka & Takeuchi (1995)"],"","知識創造チーム,自己組織化,プロジェクト","knowledge-creating crew, self-organizing, project-based")
add("Contextual Ambidexterity","文脈的両利き","構造的分離ではなく、個人が自らの判断で探索と活用のバランスを取る能力を組織文化・制度設計によって促進するアプローチ。Gibson & Birkinshaw（2004年）がストレッチ、規律、サポート、信頼の4要素で概念化。","個人レベルの探索-活用バランスを文脈で促進。","動的能力論",2004,"organizational","組織文脈による個人的両利きの促進",["Cristina Gibson","Julian Birkinshaw"],["Gibson & Birkinshaw (2004) The Antecedents, Consequences, and Mediating Role of Organizational Ambidexterity"],"structural ambidexterity","文脈的両利き,個人的バランス,組織文化","contextual ambidexterity, individual balance, organizational culture")
add("Knowledge Recombination","知識の再結合","既存の知識要素を新しい方法で組み合わせることによって新知識・イノベーションが生まれるメカニズム。Schumpeterの「新結合」概念を知識レベルに適用し、知識の多様性と結合能力がイノベーションを規定する。","既存知識の新結合によるイノベーション創出。","知識マネジメント",2003,"organizational","既存知識の創造的組み合わせ",["Lee Fleming","Andrew Hargadon"],["Fleming (2001) Recombinant Uncertainty in Technological Search"],"","知識再結合,新結合,創造的組み合わせ","knowledge recombination, new combination, creative recombination")
add("Organizational Learning Curve","組織学習曲線","組織全体の学習プロセスを累積経験と成果の関係として定量化したもの。個人の学習曲線を超えた組織レベルの学習ダイナミクス（ルーティン化、知識の制度化、人員変動の影響等）を分析する。","組織レベルの累積的学習の定量的分析。","組織学習",1990,"organizational","組織全体の累積的学習",["Linda Argote"],["Argote (1999) Organizational Learning: Creating, Retaining and Transferring Knowledge"],"","組織学習曲線,累積学習,ルーティン化","organizational learning curve, cumulative learning, routinization")
add("Vicarious Learning","代理学習","他組織の経験（成功・失敗）を間接的に観察して学習するプロセス。直接経験のコストとリスクを回避しつつ、他者の経験から教訓を抽出する効率的な学習形態。","他組織の経験からの間接的学習。","組織学習",1988,"organizational","他者の経験の間接的活用",["Huber","Kim & Miner"],["Huber (1991) Organizational Learning"],"","代理学習,間接学習,他者経験","vicarious learning, indirect learning, other's experience, observation")
add("Superstitious Learning","迷信的学習","組織が因果関係を誤認して「間違った教訓」を学習するプロセス。成功の原因を誤帰属し、効果のない行動を強化したり、偶然の成功を能力と誤認する学習の病理。","因果関係の誤認による誤った学習。","組織学習",1988,"organizational","因果関係の誤認と強化",["James March","Daniel Levinthal"],["Levinthal & March (1993) The Myopia of Learning"],"","迷信的学習,誤帰属,学習の病理","superstitious learning, misattribution, learning pathology")
add("Interorganizational Learning","組織間学習","アライアンス、サプライチェーン、コンソーシアム等の組織間関係を通じた相互的な学習プロセス。知識の相互移転、共同知識創造、制度的学習等の多様な形態がある。","組織間関係を通じた相互的な学習プロセス。","組織学習",1998,"organizational","組織間の相互的知識交換",["Andrew Inkpen","Anoop Madhok"],["Inkpen & Tsang (2005) Social Capital, Networks, and Knowledge Transfer"],"","組織間学習,相互学習,アライアンス学習","interorganizational learning, mutual learning, alliance learning")
add("Mindful Learning in Organizations","組織におけるマインドフル学習","Langer（1989年）のマインドフルネス概念を組織学習に適用し、ルーティン化された無意識的行動（マインドレス）から脱却して、環境の変化に注意深く対応する学習形態。Weick & Sutcliffe（2001年）がHRO（高信頼性組織）の文脈で発展。","注意深い状況認識に基づく適応的学習。","組織学習",2001,"organizational","注意深い状況認識と適応",["Karl Weick","Kathleen Sutcliffe"],["Weick & Sutcliffe (2001) Managing the Unexpected"],"","マインドフル学習,高信頼性組織,注意深さ","mindful learning, HRO, mindfulness, situational awareness")
add("Knowledge Management Maturity Model","知識管理成熟度モデル","組織の知識管理能力を段階的に評価するフレームワーク。初期段階（ad hoc）→反復段階→定義段階→管理段階→最適化段階の5段階で、KM実践の制度化と高度化の現状を診断する。","知識管理能力の段階的評価と改善ガイド。","知識マネジメント",2003,"organizational","KM能力の段階的評価",["Karl Wiig","APQC"],["APQC KM Maturity Model"],"","KM成熟度,段階的評価,能力改善","KM maturity, staged assessment, capability improvement")
add("Knowledge Visualization","知識の可視化","抽象的な知識・概念・関係を視覚的表現（マインドマップ、コンセプトマップ、知識マップ、インフォグラフィック等）を通じてコミュニケーション可能にする手法群。知識移転と理解の促進を目的とする。","知識の視覚的表現による理解とコミュニケーションの促進。","知識マネジメント",2004,"organizational","視覚的表現による知識伝達",["Martin Eppler","Remo Burkhard"],["Eppler & Burkhard (2007) Visual Representations in Knowledge Management"],"","知識可視化,マインドマップ,コンセプトマップ","knowledge visualization, mind map, concept map, visual representation")
add("Distributed Cognition","分散認知","認知プロセスが個人の頭脳内だけでなく、他者、ツール、環境に分散して存在するという認知科学の枠組み。Hutchins（1995年）が航空操縦室を例に概念化し、チームの知識活動をシステムレベルで分析する基盤を提供。","認知プロセスの人間-環境-ツール間の分散。","組織学習",1995,"organizational","認知の社会的・物質的分散",["Edwin Hutchins"],["Hutchins (1995) Cognition in the Wild"],"","分散認知,認知の分散,チーム認知","distributed cognition, cognitive distribution, team cognition")
add("Knowledge Worker Autonomy","知識労働者の自律性","知識労働者が仕事の内容、方法、時間、場所について裁量を持つ程度。自律性が知識創造、創造的問題解決、モチベーションを促進するメカニズムと、組織的調整との緊張の分析。","知識労働者の自律性がイノベーションを促進するメカニズム。","知識マネジメント",2000,"organizational","自律性による創造的活動の促進",["Teresa Amabile"],["Amabile (1998) How to Kill Creativity"],"","知識労働者自律性,裁量,創造性","knowledge worker autonomy, discretion, creativity, motivation")
add("Knowledge Entropy","知識エントロピー","組織の知識基盤が時間経過・人員変動・環境変化等により劣化・散逸する傾向。熱力学のエントロピー概念を知識管理に適用し、知識の秩序維持に必要なエネルギー投入（知識管理活動）の必要性を理論化。","知識基盤の自然な劣化傾向とその管理。","知識マネジメント",2005,"organizational","知識の自然劣化と維持コスト",["Max Boisot"],["Boisot (1998) Knowledge Assets"],"","知識エントロピー,知識劣化,維持コスト","knowledge entropy, knowledge degradation, maintenance cost")
add("Knowledge Supply Chain","知識サプライチェーン","知識の生成（大学・研究機関）→加工（コンサルティング・仲介機関）→配達（トレーニング・メディア）→消費（企業・実務者）の一連のフローをサプライチェーン・アナロジーで分析する枠組み。","知識の生成から消費までのフロー分析。","知識マネジメント",2003,"organizational","知識フローのバリューチェーン分析",["Andrew Hargadon"],["Holsapple & Singh (2001) The Knowledge Chain Model"],"","知識サプライチェーン,知識フロー,バリューチェーン","knowledge supply chain, knowledge flow, value chain")
add("Situated Learning Theory","状況的学習理論","学習が特定の社会的・物理的文脈に埋め込まれて生じるという理論。Lave & Wenger（1991年）が正統的周辺参加として定式化し、学習を個人の認知的活動ではなく社会的参加のプロセスとして再定義した。","学習を社会的文脈に埋め込まれた参加プロセスとして理論化。","社会的学習理論",1991,"organizational","社会的文脈への参加としての学習",["Jean Lave","Etienne Wenger"],["Lave & Wenger (1991) Situated Learning"],"","状況的学習,正統的周辺参加,社会的参加","situated learning, legitimate peripheral participation, social participation")

output_dir = os.path.dirname(os.path.abspath(__file__))
total = len(entries)
print(f"Total know entries generated: {total}")
for batch_idx in range(0, total, 50):
    batch = entries[batch_idx:batch_idx+50]
    batch_num = batch_idx // 50 + 1
    filepath = os.path.join(output_dir, f"know_batch_{batch_num}.json")
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    print(f"Written {len(batch)} to {filepath} (IDs: {batch[0]['id']} - {batch[-1]['id']})")
