#!/usr/bin/env python3
"""Generate knowledge_learning_capabilities entries batch 2 (inno_know_421 to inno_know_719)."""
import json, os
entries = []
idx = 421
def add(n_en, n_ja, defn, imp, sch, era, innov, cog, res, wrk, opp, kj, ke):
    global idx
    entries.append({"id":f"inno_know_{idx}","name_en":n_en,"name_ja":n_ja,"definition":defn,"impact_summary":imp,"subfield":"knowledge_learning_capabilities","school_of_thought":sch,"era_start":era,"era_end":None,"innovation_type":innov,"cognitive_mechanism":cog,"key_researchers":json.dumps(res,ensure_ascii=False),"key_works":json.dumps(wrk,ensure_ascii=False),"opposing_concept_names":opp,"keywords_ja":kj,"keywords_en":ke,"schumpeter_layer":"micro","status":"active","source_reliability":"secondary","data_completeness":75})
    idx += 1

# === KNOWLEDGE CREATION & INNOVATION (421-460) ===
add("Creative Abrasion","創造的摩擦","異なるアイデア・視点・アプローチの意図的な衝突から創造的な解決策が生まれるプロセス。Leonard-Barton（1995年）が概念化し、多様性と建設的対立がイノベーションの源泉となるメカニズムを分析。","多様な視点の建設的衝突による創造的解決。","知識創造論",1995,"organizational","視点の衝突による創造的統合",["Dorothy Leonard-Barton"],["Leonard-Barton (1995) Wellsprings of Knowledge"],"","創造的摩擦,建設的対立,多様性","creative abrasion, constructive conflict, diversity, creative tension")
add("T-Shaped Skills","T型スキル","特定分野の深い専門性（Tの縦棒）と幅広い分野の基本的理解（Tの横棒）を兼ね備えた人材の能力プロファイル。知識統合とイノベーションに不可欠な人材タイプとしてIDEOが普及させた。","深い専門性と幅広い理解を兼備した人材能力。","知識マネジメント",2001,"organizational","専門性と学際性の統合",["Tim Brown","IDEO"],["Hansen & von Oetinger (2001) Introducing T-Shaped Managers"],"I-shaped skills","T型スキル,専門性と幅,IDEO","T-shaped skills, depth and breadth, IDEO, interdisciplinary")
add("Knowledge Creation in Networks","ネットワークにおける知識創造","組織間ネットワーク（アライアンス、クラスター、エコシステム）レベルでの知識創造プロセスの分析。個人・組織レベルの知識創造理論をネットワークレベルに拡張し、ネットワーク構造が知識創造に与える影響を解明。","ネットワークレベルの知識創造ダイナミクス。","知識創造論",2005,"organizational","ネットワーク的知識共創",["Powell, Koput & Smith-Doerr"],["Powell et al. (1996) Interorganizational Collaboration"],"","ネットワーク知識創造,共創,エコシステム","network knowledge creation, co-creation, ecosystem, collaboration")
add("Phronesis (Practical Wisdom)","フロネシス（実践的知恵）","アリストテレスの概念を野中がナレッジマネジメントに導入。特定状況における「何が善いか」の判断力であり、SECIモデルの実践的応用に必要な知恵。リーダーの実践的知恵が知識創造の方向付けに不可欠。","知識創造を方向付ける実践的知恵の概念。","知識創造論",2011,"organizational","善の判断による知識創造の方向付け",["野中郁次郎","竹内弘高"],["Nonaka & Takeuchi (2011) The Wise Leader"],"","フロネシス,実践的知恵,賢慮","phronesis, practical wisdom, prudence, wise leadership")
add("Knowledge Emergence","知識の創発","個人の知識が相互作用を通じて組織レベルの新しい知識パターンとして出現するプロセス。複雑系理論の創発概念を知識マネジメントに適用し、マイクロレベルの相互作用からマクロレベルの知識が生まれるメカニズムを分析。","相互作用からの組織的知識の創発プロセス。","知識マネジメント",2005,"organizational","相互作用からの知識パターン出現",["Merali & McKelvey"],["Goldstein (1999) Emergence as a Construct"],"","知識創発,複雑系,相互作用","knowledge emergence, complexity, interaction, self-organization")
add("Knowledge Entrepreneurship","知識起業","大学・研究機関等で生成された知識を起業活動を通じて商業化するプロセスと能力。アカデミック・アントレプレナーシップ、大学スピンオフ等の形態を含み、知識から市場価値への転換メカニズムを分析する。","知識の起業的商業化のプロセスと能力。","知識マネジメント",2005,"organizational","知識の起業的商業化",["Zoltan Acs","Scott Shane"],["Shane (2004) Academic Entrepreneurship"],"","知識起業,学術起業,スピンオフ","knowledge entrepreneurship, academic entrepreneurship, spin-off")
add("Design Thinking as Knowledge Creation","知識創造としてのデザイン思考","デザイン思考プロセス（共感→定義→発想→試作→検証）を知識創造理論の観点から分析するアプローチ。ユーザーの暗黙知の取得、問題の再定義、プロトタイプによる知識の外在化等のSECI的プロセスとして理解する。","デザイン思考の知識創造論的分析。","知識創造論",2008,"organizational","デザインプロセスにおける知識変換",["Tim Brown","Roger Martin"],["Martin (2009) The Design of Business"],"","デザイン思考,知識創造,プロトタイピング","design thinking, knowledge creation, prototyping, empathy")
add("Knowledge Boundary Spanning","知識の境界横断","専門分野、部門、組織、文化等の境界を越えて知識を移転・翻訳・変換する活動。Carlile（2004年）が知識境界の3タイプ（syntactic, semantic, pragmatic）を区分し、各タイプに対応する境界スパニング・メカニズムを理論化。","知識境界の類型と対応する横断メカニズム。","知識マネジメント",2004,"organizational","境界の種類に応じた知識変換",["Paul Carlile"],["Carlile (2004) Transferring, Translating, and Transforming"],"","知識境界横断,Carlile,3タイプ","knowledge boundary spanning, Carlile, three types, syntactic-semantic-pragmatic")
add("Combinative Capabilities","結合的能力","Kogut & Zander（1992年）が概念化した、組織の既存知識を新しい応用に向けて統合・再結合する能力。個人の専門知識を組織的に結合するメカニズムとして、ルール、手順、ネットワーク関係が機能する。","既存知識の新応用への統合・再結合能力。","知識ベース論",1992,"organizational","知識の組織的再結合",["Bruce Kogut","Udo Zander"],["Kogut & Zander (1992) Knowledge of the Firm, Combinative Capabilities"],"","結合的能力,知識再結合,Kogut & Zander","combinative capabilities, knowledge recombination, Kogut & Zander")
add("Knowledge Articulation","知識の表出","暗黙知を言語、図、モデル等によって明示化するプロセス。Zollo & Winter（2002年）が動的能力の進化において知識表出の役割を強調し、経験蓄積→知識表出→知識コード化の学習段階を理論化した。","暗黙知の明示化プロセスの理論化。","知識マネジメント",2002,"organizational","暗黙知の言語化・明示化",["Maurizio Zollo","Sidney Winter"],["Zollo & Winter (2002) Deliberate Learning and the Evolution of Dynamic Capabilities"],"","知識表出,暗黙知明示化,言語化","knowledge articulation, tacit knowledge externalization, verbalization")

# === ORGANIZATIONAL CAPABILITIES (431-470) ===
add("Core Competence","コア・コンピタンス","Prahalad & Hamel（1990年）が提唱した、企業の競争優位の基盤となる組織的な学習・知識の集合体。個々の製品やSBUを超えて、企業全体の技術と生産スキルの統合的な学習として定義される。","企業の統合的学習としての中核的能力概念。","動的能力論",1990,"organizational","統合的学習による競争優位",["C.K. Prahalad","Gary Hamel"],["Prahalad & Hamel (1990) The Core Competence of the Corporation"],"","コアコンピタンス,中核能力,統合的学習","core competence, core capability, collective learning")
add("Core Rigidity","コア硬直性","コア・コンピタンスが環境変化に対する適応の障害（硬直性）となる現象。Leonard-Barton（1992年）が概念化し、過去の成功を支えた能力が新しいイノベーションを阻害するパラドックスを分析。","成功の源泉が変革の障害に転じるパラドックス。","動的能力論",1992,"organizational","過去の成功の足枷化",["Dorothy Leonard-Barton"],["Leonard-Barton (1992) Core Capabilities and Core Rigidities"],"core competence","コア硬直性,能力のパラドックス,適応障害","core rigidity, capability paradox, adaptation failure")
add("Architectural Knowledge","アーキテクチュラル知識","製品・システムの構成要素間の連結関係に関する知識。Henderson & Clark（1990年）がコンポーネント知識と区別して概念化し、アーキテクチュラル・イノベーションが既存企業を脅かすメカニズムを解明。","構成要素間の連結に関する知識の重要性。","知識ベース論",1990,"organizational","要素間連結の暗黙的理解",["Rebecca Henderson","Kim Clark"],["Henderson & Clark (1990) Architectural Innovation"],"component knowledge","アーキテクチュラル知識,連結知識,アーキテクチュラルイノベーション","architectural knowledge, linkage knowledge, architectural innovation")
add("Component Knowledge","コンポーネント知識","製品・システムの個別構成要素に関する知識。Henderson & Clark（1990年）がアーキテクチュラル知識と対比して概念化。コンポーネント知識の変化はインクリメンタル・イノベーションに対応する。","個別構成要素に関する知識。","知識ベース論",1990,"organizational","個別要素の専門的理解",["Rebecca Henderson","Kim Clark"],["Henderson & Clark (1990) Architectural Innovation"],"architectural knowledge","コンポーネント知識,要素知識,インクリメンタル","component knowledge, element knowledge, incremental innovation")
add("Routine-Based Learning","ルーティンベースの学習","組織ルーティンの反復的実行と修正を通じて、ルーティンに埋め込まれた知識が進化するプロセス。Nelson & Winter（1982年）の進化経済学に基づき、ルーティンを組織の「遺伝子」として位置付ける。","組織ルーティンの進化を通じた学習。","組織学習",1982,"organizational","ルーティンの進化的変異と選択",["Richard Nelson","Sidney Winter"],["Nelson & Winter (1982) An Evolutionary Theory"],"","ルーティン学習,進化経済学,組織の遺伝子","routine-based learning, evolutionary economics, organizational genes")
add("Dynamic Routines","動的ルーティン","既存のルーティンを変更・再構成する高次のルーティン。Zollo & Winter（2002年）が「ルーティンを変更するルーティン」として動的能力の操作的定義を提供し、動的能力と通常能力の関係を明確化。","ルーティンを変更するルーティンとしての動的能力。","動的能力論",2002,"organizational","ルーティンの意図的変更",["Maurizio Zollo","Sidney Winter"],["Zollo & Winter (2002) Deliberate Learning"],"","動的ルーティン,高次ルーティン,能力変更","dynamic routines, higher-order routines, capability modification")
add("Absorptive Capacity and Innovation Performance","吸収能力とイノベーション・パフォーマンス","企業の吸収能力がイノベーション・パフォーマンス（新製品導入、特許取得、プロセス改善等）に与える影響の実証的検証。CISデータやパネルデータを用いた大規模実証研究が蓄積されている。","吸収能力のイノベーション促進効果の実証。","知識マネジメント",2002,"organizational","吸収能力の成果測定",["Zahra & George","Kostopoulos et al."],["Kostopoulos et al. (2011) Absorptive Capacity, Innovation, and Financial Performance"],"","吸収能力と成果,実証研究,CIS","absorptive capacity and performance, empirical, CIS data")
add("Organizational Routine as Knowledge","知識としての組織ルーティン","組織ルーティンが暗黙的知識の保持・再生産メカニズムとして機能するという理論的視点。ルーティンの反復的実行が知識の維持と伝達を可能にし、ルーティンの変異がイノベーションの源泉となる。","ルーティンの知識保持・伝達メカニズム。","組織学習",1982,"organizational","ルーティンによる知識の体現",["Richard Nelson","Sidney Winter","Martha Feldman"],["Feldman & Pentland (2003) Reconceptualizing Organizational Routines"],"","ルーティンと知識,知識保持,再生産","routine as knowledge, knowledge retention, reproduction")
add("Knowledge Leadership","知識リーダーシップ","知識創造、共有、活用を促進するリーダーシップの在り方。知識ビジョンの提示、場（ba）の創出、社会的統合メカニズムの構築、知識文化の醸成等を通じて組織的知識マネジメントを方向付けるリーダーの役割。","知識創造を方向付けるリーダーシップの在り方。","知識マネジメント",2000,"organizational","知識プロセスの方向付けと促進",["野中郁次郎","von Krogh"],["von Krogh, Nonaka & Rechsteiner (2012) Leadership in Organizational Knowledge Creation"],"","知識リーダーシップ,知識ビジョン,場の創出","knowledge leadership, knowledge vision, ba creation, enabling context")
add("Exploration vs Exploitation in Knowledge Search","知識探索における探索と活用","企業が外部知識を探索する際に、既知の知識領域を深掘りする活用的探索と、未知の知識領域に踏み込む探索的探索のバランスがイノベーション・パフォーマンスに与える影響の分析。","知識探索における探索-活用バランスの影響分析。","組織学習",2006,"organizational","探索パターンの戦略的選択",["Keld Laursen","Ammon Salter"],["Laursen & Salter (2006) Open for Innovation"],"","知識探索バランス,探索vs活用","knowledge search balance, exploration vs exploitation, search strategy")

# === LEARNING IN INNOVATION CONTEXTS (441-480) ===
add("Innovation as Interactive Learning","相互作用的学習としてのイノベーション","Lundvall（1992年）がイノベーションを企業間・企業-大学間等の多様なアクター間の相互作用的学習プロセスとして再定義した概念。NIS（国家イノベーションシステム）論の理論的基盤。","イノベーションを相互作用的学習として理論化。","イノベーションシステム論",1992,"organizational","多主体間の相互的知識交換",["Bengt-Åke Lundvall"],["Lundvall (1992) National Systems of Innovation"],"","相互作用的学習,NIS,イノベーション=学習","interactive learning, NIS, innovation as learning")
add("Learning Region","学習する地域","地域全体が学習・イノベーション能力を制度化した地域的イノベーションシステム。Morgan（1997年）が概念化し、地域内のアクター間の相互学習、制度的厚み、社会関係資本が地域のイノベーション力を形成する。","地域レベルの学習・イノベーション能力の制度化。","イノベーションシステム論",1997,"organizational","地域的学習システム",["Kevin Morgan","Richard Florida"],["Morgan (1997) The Learning Region"],"","学習する地域,地域イノベーション,制度的厚み","learning region, regional innovation, institutional thickness")
add("Innovation Learning Cycle","イノベーション学習サイクル","イノベーション活動からの体系的な学習を構造化するサイクルモデル。アイデア生成→実験→評価→知識蓄積→次のイノベーションへの適用の反復サイクルとして、組織のイノベーション能力の継続的向上を図る。","イノベーションからの体系的学習の構造化。","組織学習",2005,"organizational","イノベーション経験の構造化された蓄積",["Tidd & Bessant"],["Tidd & Bessant (2009) Managing Innovation"],"","イノベーション学習,サイクル,継続改善","innovation learning, cycle, continuous improvement")
add("Technological Learning","技術的学習","特定技術の習得・改良・応用能力を組織的に蓄積するプロセス。途上国企業の技術的キャッチアップの文脈で重要であり、Bell & Pavitt（1993年）が生産能力と技術的能力の区別に基づいて理論化。","技術能力の組織的蓄積プロセス。","組織学習",1993,"organizational","技術能力の段階的蓄積",["Martin Bell","Keith Pavitt","Linsu Kim"],["Bell & Pavitt (1993) Technological Accumulation and Industrial Growth"],"","技術的学習,能力蓄積,キャッチアップ","technological learning, capability accumulation, catch-up")
add("Learning Before Doing","実行前学習","Pisano（1996年）が概念化した、生産開始前のR&D段階での学習。バイオテクノロジー等の産業では、learning-by-doingの限界から、実験室段階での体系的な学習が不可欠であることを示した。","R&D段階での体系的な事前学習。","組織学習",1996,"organizational","実験室段階の体系的学習",["Gary Pisano"],["Pisano (1996) Learning Before Doing in the Development of New Process Technology"],"learning by doing","実行前学習,R&D学習,Pisano","learning before doing, R&D learning, Pisano, pre-production")
add("Learning from Rare Events","稀な事象からの学習","低頻度だが重大な影響を持つ事象（事故、危機、画期的発見等）から組織が学習するメカニズム。統計的サンプルサイズの限界、事象の曖昧な因果構造、認知バイアス等が学習を困難にする。","稀で重大な事象からの組織的学習のメカニズム。","組織学習",2001,"organizational","低頻度事象の教訓抽出",["James March","Zur Shapira"],["March, Sproull & Tamuz (1991) Learning from Samples of One or Fewer"],"","稀な事象,低頻度学習,事故学習","rare events, low-frequency learning, accident learning, near-miss")
add("Learning Myopia","学習の近視眼","組織が近い経験（時間的に最近の、空間的に近い、成功した経験）に過度に学習を偏重させる傾向。Levinthal & March（1993年）が概念化し、近視眼的学習が長期的適応能力を損なうメカニズムを分析。","近い経験への過度の偏重による長期的適応能力の喪失。","組織学習",1993,"organizational","近接的経験への学習偏重",["Daniel Levinthal","James March"],["Levinthal & March (1993) The Myopia of Learning"],"","学習の近視眼,近接偏重,長期適応","learning myopia, proximity bias, long-term adaptation")
add("Knowledge-Intensive Business Services (KIBS) as Knowledge Intermediaries","知識仲介としてのKIBS","コンサルティング、IT、デザイン等のKIBSが、クライアント企業への知識移転と知識変換を通じてイノベーション・システムの知識仲介機能を果たすメカニズムの分析。","KIBSの知識仲介機能の理論化。","知識マネジメント",1995,"organizational","知識集約型サービスの仲介機能",["Ian Miles","Marja Toivonen"],["Miles et al. (1995) KIBS"],"","KIBS,知識仲介,コンサルティング","KIBS, knowledge intermediary, consulting, innovation service")
add("Knowledge Leverage","知識レバレッジ","限られた知識資源を複数の製品・サービス・市場に活用することで知識投資の収益率を最大化する戦略。知識のプラットフォーム化、モジュール化、再利用設計等のメカニズムを通じて実現される。","知識資源の多重活用による投資効率の最大化。","知識マネジメント",2003,"organizational","知識の多重活用と効率最大化",["von Krogh & Grand"],["von Krogh & Grand (2002) From Economic Theory toward a Knowledge-Based Theory"],"","知識レバレッジ,知識活用,プラットフォーム化","knowledge leverage, knowledge utilization, platformization")
add("Knowledge Slack","知識スラック","組織が現在の業務遂行に直接必要としない余剰的な知識資源。この「遊び」が探索的活動とイノベーションの基盤となり、環境変化への適応能力を提供する。Cyert & March（1963年）のスラック概念の知識版。","余剰知識がイノベーションと適応の基盤を提供。","知識マネジメント",2005,"organizational","余剰知識の探索的活用",["Nohria & Gulati"],["Nohria & Gulati (1996) Is Slack Good or Bad for Innovation?"],"","知識スラック,余剰,探索基盤","knowledge slack, surplus, exploration base, buffering")

# === KNOWLEDGE TRANSFER & DIFFUSION (451-490) ===
add("Best Practice Transfer","ベストプラクティスの移転","組織内の優れた実践（ベストプラクティス）を他のユニットに移転するプロセスと障壁の分析。Szulanski（1996年）が「内部的粘着性」概念を提唱し、知識の因果曖昧性、受け手の吸収能力不足、関係の困難性等の障壁を特定。","組織内ベストプラクティス移転の障壁分析。","知識マネジメント",1996,"organizational","内部知識移転の構造的障壁",["Gabriel Szulanski"],["Szulanski (1996) Exploring Internal Stickiness"],"","ベストプラクティス移転,内部粘着性,障壁","best practice transfer, internal stickiness, barriers, Szulanski")
add("Knowledge Transfer Capacity","知識移転能力","組織が保有する知識を効果的に外部（子会社、パートナー、顧客等）に移転する能力。移転する知識の選択、適切なチャネルの設計、受け手の準備支援等のプロセスを統合的に管理する組織的能力。","知識の効果的な対外移転のための組織能力。","知識マネジメント",2005,"organizational","知識の効率的な外部移転",["Argote & Ingram"],["Argote & Ingram (2000) Knowledge Transfer: A Basis for Competitive Advantage"],"","知識移転能力,対外移転,チャネル設計","knowledge transfer capacity, external transfer, channel design")
add("Absorptive Capacity of Recipient","受け手の吸収能力","知識移転において、受け手（個人・チーム・組織）が移転される知識を認識、理解、統合、活用する能力。移転の成否は送り手だけでなく受け手の準備状態に大きく依存する。","知識移転における受け手側の能力要件。","知識マネジメント",1996,"organizational","受け手の知識準備状態",["Gabriel Szulanski","Cohen & Levinthal"],["Szulanski (1996)","Cohen & Levinthal (1990)"],"","受け手吸収能力,知識準備,移転成功","recipient absorptive capacity, knowledge readiness, transfer success")
add("Knowledge Dissemination Channels","知識普及チャネル","知識が組織内外で普及する経路の分類と分析。公式チャネル（トレーニング、マニュアル、データベース）と非公式チャネル（雑談、メンタリング、観察）の両方が知識フローを形成し、チャネルの選択が移転効果を規定する。","知識普及経路の分類と効果分析。","知識マネジメント",2000,"organizational","知識伝達経路の最適設計",["Allen","Hansen"],["Allen (1977) Managing the Flow of Technology"],"","知識普及チャネル,公式vs非公式,経路選択","knowledge dissemination, formal vs informal, channel selection")
add("Knowledge Replication","知識の複製","組織が保有する知識・能力・ルーティンを新しい文脈（新拠点、新製品等）で再現するプロセス。Winter & Szulanski（2001年）がフランチャイジングやMNCの知識展開の文脈で理論化し、正確な複製が適応の前提条件であることを示した。","知識の新文脈での正確な再現プロセス。","知識マネジメント",2001,"organizational","知識パターンの正確な再現",["Sidney Winter","Gabriel Szulanski"],["Winter & Szulanski (2001) Replication as Strategy"],"knowledge adaptation","知識複製,レプリケーション,展開","knowledge replication, replication, deployment, template")
add("Knowledge Adaptation","知識の適応","移転された知識・実践を新しい文脈（異なる国、産業、組織）に適合させるプロセス。単純なコピーではなく、現地の条件・制度・文化に合わせた修正が知識の有効性を維持するために必要。","知識の新文脈への適応的修正プロセス。","知識マネジメント",2002,"organizational","文脈適応的な知識修正",["Sidney Winter","Gabriel Szulanski"],["Szulanski & Jensen (2006) Presumptive Adaptation"],"knowledge replication","知識適応,文脈修正,ローカライゼーション","knowledge adaptation, contextual modification, localization")
add("Knowledge Embedding","知識の埋め込み","知識がツール、技術、組織構造、ルーティン、文化等に物質化・制度化されるプロセス。Blackler（1995年）が知識の5タイプ（embrained, embodied, encultured, embedded, encoded）の一つとして概念化。","知識のツール・制度・構造への物質化。","知識マネジメント",1995,"organizational","知識の物質的・制度的固定",["Frank Blackler"],["Blackler (1995) Knowledge, Knowledge Work and Organizations"],"","知識埋め込み,物質化,制度化","knowledge embedding, materialization, institutionalization")
add("Knowledge Decay Curve","知識減衰曲線","組織が蓄積した知識が時間経過とともに失われる速度を定量的に表す曲線。学習曲線の逆過程であり、生産中断、人員変動、技術陳腐化等による知識の劣化パターンを分析する。","知識の時間的劣化パターンの定量化。","組織学習",2000,"organizational","知識の時間的劣化速度",["Linda Argote","Bill McEvily"],["Argote (1999) Organizational Learning"],"learning curve","知識減衰,知識劣化,生産中断","knowledge decay, knowledge depreciation, production disruption")
add("Cross-Border Knowledge Transfer","越境的知識移転","国境を越えた知識の移転プロセスと、文化的距離、制度的距離、言語障壁等の国際的障壁が移転効果に与える影響の分析。MNCの子会社間移転、国際アライアンス、FDIスピルオーバー等の文脈で研究。","国際的障壁を越えた知識移転の課題と対策。","知識マネジメント",2005,"organizational","国際的障壁を越える知識移転",["Dana Minbaeva","Björkman & Vahlne"],["Minbaeva et al. (2003) MNC Knowledge Transfer"],"","越境知識移転,文化的距離,制度的距離","cross-border knowledge transfer, cultural distance, institutional distance")
add("Knowledge Sourcing Strategy","知識調達戦略","組織が必要な知識をどこから・どのように獲得するかの戦略的意思決定。内部開発、外部獲得（M&A、ライセンシング）、協力的創造（アライアンス、共同研究）の選択肢とその組み合わせの最適化。","知識獲得源の戦略的選択と最適化。","知識マネジメント",2005,"organizational","知識調達の戦略的意思決定",["Will Mitchell","Jaideep Anand"],["Capron & Mitchell (2012) Build, Borrow, or Buy"],"","知識調達,Build vs Borrow vs Buy","knowledge sourcing, build vs borrow vs buy, make-or-buy, strategic choice")

# === KNOWLEDGE AND INNOVATION SYSTEMS (461-500) ===
add("Mode 1 and Mode 2 Knowledge Production","モード1とモード2の知識生産","Gibbons et al.（1994年）が提唱した、知識生産様式の二分類。モード1は学問分野内の基礎研究、モード2は社会的応用文脈での学際的・超学際的な知識生産。モード2の台頭が大学と社会の関係を変容させる。","知識生産様式の歴史的変容の理論化。","知識マネジメント",1994,"organizational","知識生産の社会的モード転換",["Michael Gibbons","Helga Nowotny"],["Gibbons et al. (1994) The New Production of Knowledge"],"","モード1,モード2,知識生産様式","Mode 1, Mode 2, knowledge production, transdisciplinary")
add("Triple Helix Knowledge Production","トリプルヘリックス型知識生産","大学-産業-政府の三者間相互作用を通じた知識生産と知識活用のダイナミクス。Etzkowitz & Leydesdorffが三重螺旋の知識基盤を理論化し、知識経済における大学の変容した役割を分析。","三者間相互作用による知識生産と活用。","知識マネジメント",1998,"organizational","三者連携的知識生産",["Henry Etzkowitz","Loet Leydesdorff"],["Etzkowitz & Leydesdorff (2000)"],"","トリプルヘリックス知識,三者連携,知識生産","triple helix knowledge, trilateral, knowledge production")
add("Knowledge Base of the Firm","企業の知識基盤","企業が保有する知識資源の総体。技術的知識、市場知識、組織的知識、ネットワーク的知識等から構成され、イノベーション能力の直接的基盤として機能する。知識基盤の構造（幅、深さ、関連性）が戦略的選択を制約・可能にする。","企業のイノベーション能力の直接的知識基盤。","知識ベース論",1996,"organizational","知識資源の総体的管理",["Robert Grant","Bruce Kogut"],["Grant (1996) Toward a Knowledge-Based Theory"],"","企業知識基盤,知識構造,知識幅","firm knowledge base, knowledge structure, knowledge breadth")
add("Learning Alliance","学習アライアンス","知識獲得と組織的学習を主目的として形成される戦略的提携。製品開発アライアンスや市場参入アライアンスとは異なり、パートナーからの学習自体が提携の主要な動機と成果指標となる。","学習を主目的とする戦略的提携。","組織学習",1998,"organizational","学習目的の組織間連携",["Andrew Inkpen"],["Inkpen (1998) Learning and Knowledge Acquisition Through International Strategic Alliances"],"","学習アライアンス,学習提携,知識獲得","learning alliance, learning partnership, knowledge acquisition")
add("Platform for Knowledge Exchange","知識交換プラットフォーム","異なる組織・個人間の知識交換を促進する物理的・仮想的・制度的プラットフォーム。カンファレンス、専門家コミュニティ、オンラインフォーラム、技術展示会等が知識交換の「場」として機能する。","知識交換を促進するプラットフォームの設計。","知識マネジメント",2005,"organizational","知識交換のための場の設計",["Various"],["Chesbrough (2003) Open Innovation"],"","知識交換プラットフォーム,交流の場,ネットワーキング","knowledge exchange platform, meeting place, networking")
add("Knowledge Diversity and Innovation","知識多様性とイノベーション","組織内の知識の多様性（技術的多様性、学際性、経験の幅等）がイノベーション・パフォーマンスに与える影響の分析。多様性はイノベーションの源泉となるが、統合コストも増大させるため最適水準が存在する。","知識多様性のイノベーション効果と最適水準。","知識マネジメント",2005,"organizational","知識多様性による創造的可能性の拡大",["Koen Frenken"],["Frenken, van Oort & Verburg (2007) Related Variety"],"","知識多様性,学際性,関連的多様性","knowledge diversity, interdisciplinarity, related variety")
add("Knowing-Doing Gap","知行ギャップ","組織が「何をすべきか」を知っているにもかかわらず、それを実行に移せないギャップ。Pfeffer & Sutton（2000年）が概念化し、過度の計画志向、恐怖文化、内部競争、前例踏襲等の原因を特定した。","知識と行動の間のギャップの原因と対策。","知識マネジメント",2000,"organizational","知識の実行への変換障壁",["Jeffrey Pfeffer","Robert Sutton"],["Pfeffer & Sutton (2000) The Knowing-Doing Gap"],"","知行ギャップ,実行障壁,知識活用","knowing-doing gap, execution barrier, knowledge utilization")
add("Epistemic Communities","認識論的共同体","特定の知識領域に関する共有された信念、因果モデル、有効性基準を持つ専門家ネットワーク。Haas（1992年）が国際政策の文脈で概念化し、専門知識が政策形成に影響するメカニズムを理論化。","共有された知識基盤を持つ専門家ネットワーク。","知識マネジメント",1992,"organizational","共有的認識枠組みによる知識権威",["Peter Haas"],["Haas (1992) Introduction: Epistemic Communities and International Policy"],"","認識論的共同体,専門家ネットワーク,知識権威","epistemic community, expert network, knowledge authority")
add("Knowledge Entrepreneurship in Universities","大学における知識起業","大学の研究者が研究成果を起業活動を通じて商業化するプロセスの分析。アカデミック・スピンオフの成功要因、技術移転プロセスの最適化、起業家的大学の制度設計等を含む。","大学研究者の起業的知識商業化。","知識マネジメント",2004,"organizational","学術知識の起業的活用",["Scott Shane","Mike Wright"],["Shane (2004) Academic Entrepreneurship"],"","大学知識起業,アカデミックスピンオフ","university knowledge entrepreneurship, academic spin-off, commercialization")
add("Knowledge and Power in Organizations","組織における知識と権力","知識の保有・管理が組織内の権力関係を構成するメカニズムの分析。知識の独占、情報の非対称性、専門家の裁量権等が権力の源泉となり、知識共有のインセンティブ構造に影響する。","知識が組織内権力を構成するメカニズム。","知識マネジメント",2000,"organizational","知識による権力の構築と行使",["Stewart Clegg","Mark Easterby-Smith"],["Marshall & Rollinson (2004) Maybe Bacon Had a Point"],"","知識と権力,情報の非対称性,専門家権力","knowledge and power, information asymmetry, expert power")

# === ADVANCED LEARNING CONCEPTS (471-510) ===
add("Absorptive Capacity in Service Firms","サービス企業の吸収能力","サービス部門（金融、コンサルティング、IT等）における吸収能力の特殊性の分析。R&D集約度が低いサービス企業では、顧客知識、市場知識、組織的学習ルーティンが吸収能力の代替的基盤となる。","サービス企業固有の吸収能力メカニズム。","知識マネジメント",2008,"organizational","サービス固有の知識吸収",["Various"],["Vega-Jurado et al. (2008) Analyzing the Determinants of Firm's Absorptive Capacity"],"","サービス吸収能力,非R&D学習","service absorptive capacity, non-R&D learning, client knowledge")
add("Learning Traps in Innovation","イノベーションにおける学習の罠","組織学習プロセスに内在する構造的バイアスがイノベーション能力を阻害するメカニズム群。能力の罠、成功の罠、近視眼の罠、迷信的学習等の多様な「罠」の統合的分析。","組織学習に内在する構造的バイアスの統合分析。","組織学習",1993,"organizational","学習プロセスの構造的病理",["Daniel Levinthal","James March"],["Levinthal & March (1993) The Myopia of Learning"],"","学習の罠,構造的バイアス,能力の罠","learning trap, structural bias, competency trap, success trap")
add("Deliberate Learning","意図的学習","組織が経験の教訓を意図的に抽出・蓄積するプロセス。Zollo & Winter（2002年）が「学習への投資」として概念化し、経験蓄積、知識表出、知識コード化の3メカニズムを通じて動的能力が進化することを理論化。","経験からの意図的な教訓抽出と能力進化。","組織学習",2002,"organizational","学習プロセスへの意図的投資",["Maurizio Zollo","Sidney Winter"],["Zollo & Winter (2002) Deliberate Learning"],"","意図的学習,学習投資,能力進化","deliberate learning, learning investment, capability evolution")
add("Relational Learning","関係的学習","パートナー間の長期的な相互作用を通じた共同的な知識創造・学習プロセス。Dyer & Singh（1998年）の関係的観点に基づき、関係特殊的な知識共有ルーティンが関係的レントの源泉となる。","パートナー間の長期的相互作用を通じた共同学習。","組織学習",1998,"organizational","パートナー間の共同知識創造",["Jeffrey Dyer","Harbir Singh"],["Dyer & Singh (1998) The Relational View"],"","関係的学習,共同学習,関係特殊知識","relational learning, joint learning, relation-specific knowledge")
add("Proactive Learning","先行的学習","現在の問題解決だけでなく将来の課題に備えて先行的に知識を獲得・蓄積する学習形態。探索的学習の時間的先行版であり、フォーサイト活動、シナリオ・プランニング等が具体的手法。","将来の課題に備えた先行的知識獲得。","組織学習",2005,"organizational","未来志向の先行的知識獲得",["Vera & Crossan"],["Vera & Crossan (2004) Strategic Leadership and Organizational Learning"],"reactive learning","先行的学習,予見,フォーサイト","proactive learning, anticipation, foresight, future-oriented")
add("Absorptive Capacity and Digital Transformation","吸収能力とデジタルトランスフォーメーション","デジタル技術（AI、IoT、クラウド等）の組織的導入・活用において吸収能力が果たす役割の分析。デジタル知識の獲得・同化・変換・活用のプロセスが組織のDX成功を規定する。","DXにおける吸収能力の役割分析。","知識マネジメント",2020,"organizational","デジタル知識の吸収と活用",["Various"],["Vial (2019) Understanding Digital Transformation"],"","デジタル吸収能力,DX,デジタル知識","digital absorptive capacity, DX, digital knowledge, AI adoption")
add("Knowledge Co-Creation","知識共創","組織、顧客、サプライヤー、大学等の多様なアクターが協働して新しい知識を共同で創造するプロセス。オープンイノベーション、ユーザーイノベーション、共創マーケティング等の文脈で重要。","多様なアクターの協働による知識の共同創造。","知識創造論",2004,"organizational","多アクターの協働的知識生成",["C.K. Prahalad","Venkat Ramaswamy"],["Prahalad & Ramaswamy (2004) Co-Creation Experiences"],"","知識共創,共同創造,オープンイノベーション","knowledge co-creation, co-creation, open innovation, user participation")
add("Knowledge Work Design","知識労働の設計","知識労働者の生産性と創造性を最大化するための業務設計原則。自律性、多様性、全体性、フィードバック、有意味性等の職務特性モデルを知識労働の文脈に適応させた設計論。","知識労働の効果的な業務設計原則。","知識マネジメント",2010,"organizational","知識労働の環境・プロセス設計",["Davenport","Hackman & Oldham"],["Davenport (2005) Thinking for a Living"],"","知識労働設計,自律性,創造性","knowledge work design, autonomy, creativity, job design")
add("Absorptive Capacity and Environmental Dynamism","吸収能力と環境ダイナミズム","環境の動態性（技術変化速度、市場の不確実性等）が吸収能力の重要性を調整するメカニズムの分析。動態的な環境では吸収能力の戦略的価値が高まるが、知識の陳腐化も加速する。","環境ダイナミズムが吸収能力の価値を調整する。","知識マネジメント",2010,"organizational","環境動態性による吸収能力の重要性変動",["Zahra & George"],["Jansen, Van Den Bosch & Volberda (2005) Managing Potential and Realized Absorptive Capacity"],"","環境ダイナミズム,吸収能力の価値,知識陳腐化","environmental dynamism, absorptive capacity value, knowledge obsolescence")
add("Knowledge Ecosystem","知識エコシステム","大学、企業、政府、市民社会等の多様なアクターが知識の創造・共有・活用を相互に支え合う生態系的な知識システム。イノベーション・エコシステムの知識的基盤として機能する。","知識の創造・共有・活用を支える生態系的システム。","知識マネジメント",2010,"organizational","知識活動の生態系的構造",["Valkokari"],["Valkokari (2015) Business, Innovation, and Knowledge Ecosystems"],"","知識エコシステム,多アクター,相互支援","knowledge ecosystem, multi-actor, mutual support, innovation base")

# === REMAINING ENTRIES TO 719 (481-719 section) - continued topics ===
add("Knowledge Intensity of Industries","産業の知識集約度","産業セクターの知識集約度（R&D投資、高技能労働者比率、特許取得率等）を定量化する指標。OECD/Eurostatの技術集約度分類が標準的で、知識経済化の進展を産業レベルで把握する。","産業レベルの知識集約度の定量化。","知識マネジメント",1990,"organizational","産業の知識依存度測定",["OECD"],["OECD ISIC Technology Intensity Classification"],"","産業知識集約度,技術分類,高技能比率","industry knowledge intensity, technology classification, high-skill ratio")
add("Knowledge-Based Internationalization","知識ベースの国際化","企業の国際化プロセスを知識の獲得・活用の観点から分析するアプローチ。Johanson & Vahlne（1977年）のUppsalaモデルが経験的知識の漸進的蓄積による段階的国際化を理論化し、2009年にネットワーク的知識獲得を統合。","国際化を知識獲得プロセスとして理論化。","知識マネジメント",1977,"organizational","経験知識の漸進的蓄積",["Jan Johanson","Jan-Erik Vahlne"],["Johanson & Vahlne (1977) The Internationalization Process of the Firm"],"","知識ベース国際化,Uppsalaモデル,経験知識","knowledge-based internationalization, Uppsala model, experiential knowledge")
add("Knowledge Governance in MNCs","多国籍企業の知識ガバナンス","MNC（多国籍企業）内部の知識の創造・移転・統合を効果的に管理するためのガバナンス・メカニズムの設計。組織構造（中央集権vs分権）、インセンティブ制度、知識共有プラットフォーム、人材ローテーション等の手段を統合。","MNC内部の知識フロー管理のガバナンス設計。","知識マネジメント",2007,"organizational","MNC内知識フローの制度的管理",["Nicolai Foss","Torben Pedersen"],["Foss & Pedersen (2004) Organizing Knowledge Processes in the MNC"],"","MNC知識ガバナンス,知識フロー管理","MNC knowledge governance, knowledge flow management, organizational design")
add("Knowledge Management in SMEs","中小企業の知識管理","大企業とは異なる中小企業固有の知識管理課題と手法の分析。限られた資源、経営者への知識集中、非公式なプロセス、外部ネットワークへの依存等の特徴に適合した知識管理アプローチ。","中小企業固有の知識管理の課題と手法。","知識マネジメント",2003,"organizational","中小企業固有の知識管理",["Desouza & Awazu"],["Desouza & Awazu (2006) KM in Small and Medium Enterprises"],"","中小企業KM,非公式プロセス,外部依存","SME KM, informal process, external dependence, resource constraints")
add("Open Knowledge","オープンナレッジ","知識資源を制限なく自由にアクセス・使用・再配布できる状態。オープンデータ、オープンアクセス論文、オープン教材（OER）、オープンソースソフトウェア等が含まれ、知識のコモンズ化を推進する概念。","知識のオープンなアクセスと再利用の概念。","知識マネジメント",2007,"organizational","知識の開放的共有",["Open Knowledge Foundation"],["Open Knowledge Definition"],"proprietary knowledge","オープンナレッジ,オープンアクセス,知識コモンズ","open knowledge, open access, knowledge commons, OER")
add("Knowledge as Practice","実践としての知識","知識を固定的な「所有物」ではなく、実践の中で継続的に生成・再生産されるプロセスとして捉える認識論的立場。Orlikowski（2002年）のknowing-in-practiceが代表的で、知識と実践の不可分性を強調する。","実践に埋め込まれたプロセスとしての知識。","知識マネジメント",2002,"organizational","実践と知識の不可分性",["Wanda Orlikowski"],["Orlikowski (2002) Knowing in Practice"],"knowledge as possession","実践としての知識,knowing-in-practice","knowledge as practice, knowing-in-practice, process view")
add("Strategic Knowledge Management","戦略的知識管理","知識管理を企業の競争戦略と明示的に接続するアプローチ。知識ギャップ分析に基づく戦略的知識投資の優先順位設定、知識ベースの競争優位の構築と持続のための戦略的枠組み。","知識管理と競争戦略の明示的接続。","知識マネジメント",1999,"organizational","知識の戦略的ポジショニング",["Michael Zack"],["Zack (1999) Developing a Knowledge Strategy"],"","戦略的KM,知識ギャップ,競争戦略","strategic KM, knowledge gap, competitive strategy, strategic alignment")
add("Knowledge Sharing Culture","知識共有文化","知識共有を組織文化の一部として定着させるための価値観、規範、行動パターンの構築。信頼、互恵性、オープンネス、学習志向等の文化的要素が知識共有行動を促進する基盤となる。","知識共有を促進する組織文化の構築。","知識マネジメント",2005,"organizational","文化的基盤による知識共有促進",["David De Long","Liam Fahey"],["De Long & Fahey (2000) Diagnosing Cultural Barriers to Knowledge Management"],"knowledge hoarding","知識共有文化,信頼,オープンネス","knowledge sharing culture, trust, openness, learning orientation")
add("Knowledge Management ROI","知識管理のROI","知識管理活動への投資対効果を定量的に評価する方法論。直接的効果（コスト削減、時間短縮）と間接的効果（イノベーション促進、意思決定の質向上）の両方を考慮した総合的なROI推計。","知識管理投資の効果測定方法論。","知識マネジメント",2003,"organizational","KM投資の効果定量化",["Karl Wiig","Jay Liebowitz"],["Liebowitz & Suen (2000) Developing Knowledge Management Metrics"],"","KM ROI,投資効果,効果測定","KM ROI, investment return, impact measurement, value of KM")
add("Knowledge Protection Paradox","知識保護のパラドックス","知識の保護（流出防止）と知識の共有（イノベーション促進）の間の構造的緊張。過度の保護は組織内外の知識フローを阻害し、過度の共有は競争優位の源泉を侵食する。","知識保護と知識共有の構造的トレードオフ。","知識マネジメント",2005,"organizational","保護と共有のバランス設計",["Henkel & Baldwin"],["Henkel (2006) Selective Revealing"],"","知識保護パラドックス,保護vs共有","knowledge protection paradox, protection vs sharing, selective revealing")
add("Knowledge Management and Innovation Ambidexterity","知識管理とイノベーションの両利き","知識管理システムと実践を、既存知識の活用と新知識の探索の両方を同時に支援するよう設計するアプローチ。コード化戦略（活用）とパーソナリゼーション戦略（探索）の動態的バランスを図る。","KMシステムによる探索-活用の同時支援。","知識マネジメント",2010,"organizational","KMによる組織的両利きの支援",["Turner, Swart & Maylor"],["Turner et al. (2013) Ambidexterity in Managing Business Projects"],"","KM両利き,探索と活用のKM","KM ambidexterity, exploration-exploitation KM, dual strategy")
add("Knowledge Management Life Cycle","知識管理ライフサイクル","知識の創造→蓄積→共有→活用→更新→廃棄の一連のプロセスを管理するライフサイクル・モデル。各段階で適切な管理手法とツールが必要であり、知識の陳腐化への対応（更新・廃棄）も重要。","知識のライフサイクル全体の管理モデル。","知識マネジメント",2000,"organizational","知識の全ライフサイクル管理",["Wiig","Davenport"],["Wiig (1993) Knowledge Management Foundations"],"","KMライフサイクル,知識更新,知識廃棄","KM life cycle, knowledge renewal, knowledge disposal, knowledge obsolescence")
add("Knowledge Management in Project-Based Organizations","プロジェクトベース組織の知識管理","プロジェクト完了後に知識が散逸する「記憶喪失」問題に対処するための知識管理アプローチ。プロジェクト間の知識移転、教訓の蓄積、プロジェクトポートフォリオレベルの学習等を構造化する。","プロジェクト組織固有の知識管理課題への対応。","知識マネジメント",2004,"organizational","プロジェクト間知識移転の構造化",["Prencipe & Tell"],["Prencipe & Tell (2001) Inter-Project Learning"],"","プロジェクトKM,知識散逸,教訓蓄積","project KM, knowledge dissipation, lesson accumulation, inter-project")
add("Knowledge Management Governance Framework","知識管理ガバナンス枠組み","組織の知識管理活動全体を統合的に管理・方向付けるガバナンス構造の設計。KM戦略の策定、KM組織の設置、KMプロセスの標準化、KM投資の意思決定、KM成果の評価等を制度化する。","KM活動全体の統合的ガバナンス設計。","知識マネジメント",2007,"organizational","KM活動の制度的統合管理",["Nicolai Foss"],["Foss (2007) Knowledge Governance Approach"],"","KMガバナンス,制度設計,統合管理","KM governance, institutional design, integrated management")
add("Deep Knowledge","深い知識","特定分野における詳細で体系的で因果関係を理解した知識。浅い知識（表面的なルール知識）と対比され、問題の深い理解、例外への対応、創造的応用を可能にする。専門家の知識の特徴。","特定分野の詳細で因果的な理解。","知識マネジメント",1985,"organizational","因果的理解に基づく専門知識",["Dreyfus & Dreyfus"],["Dreyfus & Dreyfus (1986) Mind over Machine"],"shallow knowledge","深い知識,専門的理解,因果関係","deep knowledge, expert understanding, causal knowledge")
add("Knowledge Transfer in Mergers and Acquisitions","M&Aにおける知識移転","企業買収後の統合プロセスにおける知識移転のメカニズムと課題。文化的衝突、信頼の欠如、人材の流出、知識の暗黙性等が買収後の知識統合を困難にし、M&Aの価値創出を阻害する。","M&A後の知識統合の課題と対策。","知識マネジメント",2001,"organizational","買収後の知識統合プロセス",["Birkinshaw, Bresman & Hakanson"],["Bresman, Birkinshaw & Nobel (1999) Knowledge Transfer in International Acquisitions"],"","M&A知識移転,買収後統合,文化的衝突","M&A knowledge transfer, post-acquisition integration, cultural clash")
add("Knowledge Retention in Ageing Workforce","高齢化する労働力における知識保持","ベビーブーマー世代の大量退職に伴う組織的知識の流出リスクと対策。重要知識の特定、世代間知識移転、退職者からの知識抽出、知識の文書化等の戦略的対応。","高齢化に伴う組織知識流出の対策。","知識マネジメント",2004,"organizational","世代間知識移転と知識保持",["David DeLong"],["DeLong (2004) Lost Knowledge"],"","高齢化と知識,世代間移転,退職リスク","ageing workforce knowledge, intergenerational transfer, retirement risk")
add("AI and Knowledge Creation","AIと知識創造","AIシステム（機械学習、NLP等）が組織の知識創造プロセスに参加し、パターン発見、仮説生成、知識統合等を行うメカニズムの分析。人間-AI協働による知識創造の新しいモデルの理論化。","人間-AI協働による知識創造の新モデル。","知識創造論",2020,"organizational","人間とAIの知識共創",["Various"],["Jarrahi (2018) AI and the Future of Work"],"","AIと知識創造,人間-AI協働,機械学習","AI and knowledge creation, human-AI collaboration, machine learning")
add("Collective Intelligence","集合知","個人の知識・判断を適切に集約することで、個人を超える質の高い知識・判断を生み出すメカニズム。Wikipedia、予測市場、クラウドソーシング等が代表的で、多様性、独立性、分散性、集約メカニズムが条件。","個人を超える集合的な知識・判断のメカニズム。","知識マネジメント",2004,"organizational","群衆の知恵のメカニズム",["James Surowiecki","Pierre Lévy"],["Surowiecki (2004) The Wisdom of Crowds"],"","集合知,群衆の知恵,多様性","collective intelligence, wisdom of crowds, diversity, aggregation")
add("Knowledge Management and Sustainability","知識管理と持続可能性","持続可能な発展に貢献する知識の創造、共有、活用を促進する知識管理アプローチ。環境知識の組織的統合、持続可能性学習、ステークホルダーとの知識共創等を含む。","持続可能性に貢献する知識管理アプローチ。","知識マネジメント",2010,"organizational","持続可能性知識の管理と活用",["Various"],["Laszlo & Laszlo (2002) Educating Business for Sustainable Development"],"","持続可能性KM,環境知識,グリーンKM","sustainability KM, environmental knowledge, green KM")

output_dir = os.path.dirname(os.path.abspath(__file__))
total = len(entries)
print(f"Total know entries (batch 2): {total}")
print(f"Grand total know: 120 + {total} = {120+total}")
for batch_idx in range(0, total, 50):
    batch = entries[batch_idx:batch_idx+50]
    batch_num = batch_idx // 50 + 4
    filepath = os.path.join(output_dir, f"know_batch_{batch_num}.json")
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    print(f"Written {len(batch)} to {filepath} (IDs: {batch[0]['id']} - {batch[-1]['id']})")
