#!/usr/bin/env python3
"""Generate final measurement_policy_governance entries (inno_pol_679 to inno_pol_714)."""
import json, os
entries = []
idx = 679
def add(n_en, n_ja, defn, imp, sch, era, innov, cog, res, wrk, opp, kj, ke):
    global idx
    entries.append({"id":f"inno_pol_{idx}","name_en":n_en,"name_ja":n_ja,"definition":defn,"impact_summary":imp,"subfield":"measurement_policy_governance","school_of_thought":sch,"era_start":era,"era_end":None,"innovation_type":innov,"cognitive_mechanism":cog,"key_researchers":json.dumps(res,ensure_ascii=False),"key_works":json.dumps(wrk,ensure_ascii=False),"opposing_concept_names":opp,"keywords_ja":kj,"keywords_en":ke,"schumpeter_layer":"macro","status":"active","source_reliability":"secondary","data_completeness":75})
    idx += 1

add("Innovation Demand Measurement","イノベーション需要測定","消費者・企業・公共部門のイノベーティブな製品・サービスへの需要の大きさとパターンを定量化する方法論。需要サイドの条件がイノベーション活動に与える影響を実証的に分析する。","イノベーション需要の供給サイドへの影響の定量分析。","イノベーション計量学",2005,"measurement","policy,learning",["OECD","European Commission"],["OECD Demand-Side Innovation Policy Studies"],"","需要測定,需要サイド,市場条件","innovation demand measurement, demand-side, market conditions")
add("Innovation Policy for SME Digital Transformation","中小企業DXのためのイノベーション政策","中小企業のデジタルトランスフォーメーションを促進する政策体系。デジタルスキル支援、IT投資補助、デジタルプラットフォーム活用支援、サイバーセキュリティ対策等を含む包括的な中小企業DX支援。","中小企業のデジタル化によるイノベーション能力強化。","イノベーション政策",2018,"policy","policy,learning",["European Commission","SME Envoy Network"],["EU Digital SME Alliance Reports"],"","中小企業DX,デジタル化支援,IT投資","SME digital transformation, digitalization support, IT investment")
add("National AI Strategy as Innovation Policy","国家AI戦略としてのイノベーション政策","AIの研究開発・人材育成・社会実装・倫理的ガバナンスを包括的に推進する国家戦略。カナダ（2017年、世界初）、中国、EU、米国、日本等が策定し、AIイノベーション・エコシステムの構築を目指す。","AI分野の国際競争力強化のための包括的国家戦略。","イノベーション政策",2017,"policy,institutional","policy",["Various national governments"],["OECD AI Policy Observatory"],"","国家AI戦略,AI人材,AI倫理","national AI strategy, AI talent, AI ethics, innovation ecosystem")
add("Innovation Assessment of Regulatory Proposals","規制提案のイノベーション影響評価","新規規制の提案段階でイノベーション活動への潜在的影響を体系的に評価するプロセス。EU規制影響評価（RIA）にイノベーション次元を統合し、規制がイノベーション・インセンティブに与える効果を事前に検討する。","規制提案段階でのイノベーション影響の事前評価。","イノベーション政策評価",2015,"measurement,policy","policy",["European Commission"],["EU Better Regulation Toolbox - Innovation Tool"],"","規制影響評価,イノベーションテスト","regulatory impact assessment, innovation test, better regulation")
add("Open Source Innovation Policy","オープンソース・イノベーション政策","オープンソース・ソフトウェア、ハードウェア、データの開発・利用を制度的に促進する政策。EUのOpen Source Strategy、各国のデジタル政府におけるOSS優先調達方針等を含む。","オープンソース・イノベーションの制度的促進。","イノベーション政策",2010,"policy,institutional","policy,learning",["European Commission","OSI"],["EU Open Source Strategy 2020-2023"],"","オープンソース政策,OSS,デジタル政府","open source policy, OSS, digital government, collaborative innovation")
add("Innovation Ecosystem Mapping Methodology","イノベーション・エコシステム・マッピング方法論","地域のイノベーション・エコシステムの構成要素（アクター、ネットワーク、制度、資源）を体系的に可視化する方法論。ネットワーク分析、GISマッピング、ステークホルダー分析等を統合する。","エコシステム構成要素の体系的な可視化手法。","イノベーション計量学",2012,"measurement,systemic","learning",["Startup Genome","OECD"],["OECD Entrepreneurship Indicators Programme"],"","エコシステムマッピング,可視化,ネットワーク分析","ecosystem mapping, visualization, network analysis, stakeholder analysis")
add("Collaborative Patent Classification (CPC)","共同特許分類","EPOとUSPTOが共同開発した特許分類体系。IPCを大幅に細分化（約25万サブグループ）し、先行技術調査と特許分析の精度を向上させた。2013年から本格運用され、Y02（気候変動緩和）等の横断分類も含む。","特許分析の精度を大幅に向上させた詳細分類体系。","特許分析",2013,"measurement","learning",["EPO","USPTO"],["CPC Classification Scheme"],"","CPC,特許分類,詳細分類","CPC, patent classification, detailed classification, Y02")
add("Innovation Policy Learning from Failure","失敗からのイノベーション政策学習","イノベーション政策の失敗事例（ソリンドラ、Quango削減等）から体系的に教訓を抽出し、政策設計の改善に活かすプロセス。失敗の分類（設計の失敗、実施の失敗、環境変化）と組織的学習メカニズムを体系化する。","政策失敗からの体系的学習メカニズム。","イノベーション政策評価",2012,"policy","policy,learning",["OECD","Nesta"],["OECD Innovation Policy Learning Studies"],"","政策失敗,学習,教訓抽出","policy failure, learning, lesson extraction, adaptive policy")
add("Innovation Collaboration Index","イノベーション協力指標","企業間、産学間、国際間のイノベーション協力活動の頻度・深度・範囲を測定する複合指標。CISの協力変数、共同特許率、共著論文率、共同R&Dプロジェクト参加率等を統合して協力の全体像を把握する。","イノベーション協力の多面的測定。","イノベーション計量学",2005,"measurement","learning",["Eurostat","OECD"],["CIS Collaboration Variables"],"","協力指標,共同研究,産学連携率","collaboration index, joint research, university-industry rate, cooperation")
add("IPR Enforcement and Innovation","知財権執行とイノベーション","特許侵害訴訟、模倣品取締り、営業秘密保護等の知的財産権の執行体制がイノベーション・インセンティブに与える影響の分析。執行の強度と効率がR&D投資、FDI、技術ライセンシングに及ぼす効果を検証する。","知財権執行体制のイノベーション促進効果の分析。","イノベーション政策",2000,"institutional,policy","policy",["WIPO","USPTO"],["WIPO IP Enforcement Studies"],"","知財執行,特許侵害,模倣品対策","IPR enforcement, patent infringement, anti-counterfeiting, innovation incentive")
add("Innovation Scoreboard for Cities","都市イノベーション・スコアボード","都市レベルのイノベーション能力を多次元的に評価する指標体系。スタートアップ密度、特許出願、R&D支出、VC投資、人材集積、デジタルインフラ等から構成され、都市間のイノベーション・ベンチマーキングを支援。","都市レベルのイノベーション能力の多次元的評価。","イノベーション計量学",2015,"measurement","policy,learning",["European Commission","OECD"],["EU Urban Innovation Scoreboard"],"","都市スコアボード,都市イノベーション","city innovation scoreboard, urban innovation, municipal benchmarking")
add("Innovation Policy Narrative Analysis","イノベーション政策ナラティブ分析","政策文書、政治的言説、メディア報道等に含まれるイノベーション政策のナラティブ（物語的枠組み）を分析する質的手法。政策の正当化論理、因果ストーリー、未来像の構築パターンを解明する。","イノベーション政策の言説的構築パターンの分析。","イノベーション政策評価",2010,"measurement","learning",["Deborah Stone","Dvora Yanow"],["Fischer & Forester (1993) The Argumentative Turn in Policy Analysis"],"","ナラティブ分析,言説,政策正当化","narrative analysis, discourse, policy justification, policy framing")
add("Innovation Premium in Stock Markets","株式市場におけるイノベーション・プレミアム","イノベーティブな企業が株式市場で享受する追加的な評価（イノベーション・プレミアム）を測定する手法。R&D投資、特許ポートフォリオ、イノベーション・パイプラインが企業価値（Tobin's Q等）に与える影響を推計する。","イノベーション活動の企業価値への貢献の金融市場的測定。","イノベーション計量学",1990,"measurement","learning",["Bronwyn Hall","Adam Jaffe"],["Hall, Jaffe & Trajtenberg (2005) Market Value and Patent Citations"],"","イノベーションプレミアム,企業価値,Tobin's Q","innovation premium, firm value, Tobin's Q, market valuation")
add("Innovation Policy and Dual-Use Technology","イノベーション政策とデュアルユース技術","軍事・安全保障と民生の両方に利用可能なデュアルユース技術の研究開発・移転・輸出管理に関する政策体系。安全保障上の制約とイノベーション促進のバランスを図る制度設計。","デュアルユース技術のイノベーション政策と安全保障の両立。","イノベーション政策",2000,"policy,institutional","policy",["Wassenaar Arrangement","OECD"],["Wassenaar Arrangement Export Control Lists"],"","デュアルユース,輸出管理,安全保障","dual-use technology, export control, security, innovation policy")
add("Innovation and Cultural Policy","イノベーションと文化政策","文化政策（芸術支援、文化遺産保護、クリエイティブ産業振興等）がイノベーション活動に与える影響の分析。文化的多様性、創造性、美的感性がイノベーションの源泉となるメカニズムの実証。","文化的資源がイノベーション創出に寄与するメカニズム。","イノベーション政策",2008,"policy","policy,learning",["UNESCO","European Commission"],["UNESCO Creative Economy Reports"],"","文化政策,創造性,文化的多様性","cultural policy, creativity, cultural diversity, creative economy")
add("Innovation Intensity by Sector","セクター別イノベーション集約度","各産業セクターのイノベーション活動の集約度（R&D/売上比、イノベーティブ企業比率、新製品売上比率等）を比較する指標体系。セクター間のイノベーション・パターンの異質性を定量化する。","産業セクター間のイノベーション・パターンの定量的比較。","イノベーション計量学",1990,"measurement","learning",["OECD","Eurostat"],["OECD ISIC Technology Intensity Classification"],"","セクター別集約度,産業比較","sectoral innovation intensity, industry comparison, technology intensity")
add("Innovation and Competition Measurement","イノベーションと競争の測定","市場集中度（HHI等）、参入障壁、競争圧力等の競争環境指標とイノベーション活動指標の関係を定量的に分析する方法論。逆U字関係（Aghion et al., 2005）等の非線形効果の検出を含む。","競争環境とイノベーション活動の定量的関係分析。","イノベーション計量学",2005,"measurement","learning",["Philippe Aghion","Nick Bloom"],["Aghion et al. (2005) Competition and Innovation: An Inverted-U Relationship"],"","競争測定,HHI,逆U字関係","competition measurement, HHI, inverted-U relationship, market structure")
add("Patent Analytics for Strategic Intelligence","戦略的インテリジェンスのための特許分析","特許データの大規模分析を通じて、競合動向、技術トレンド、アライアンス機会、M&Aターゲット等の戦略的情報を抽出する手法群。企業戦略と政策立案の両方に活用される応用的特許分析。","特許データからの戦略的情報の体系的抽出。","特許分析",2010,"measurement","learning",["WIPO","various patent analytics firms"],["WIPO Patent Analytics Tools"],"","戦略的特許分析,競合分析,技術トレンド","strategic patent analytics, competitive analysis, technology trends")
add("Innovation Policy for Water Security","水安全保障のためのイノベーション政策","水処理技術、淡水化、スマート水管理、水再利用等の水関連イノベーションを促進する政策体系。気候変動と人口増加による水ストレスの増大に対応するため、水イノベーション・エコシステムの構築を目指す。","水安全保障のための技術イノベーション促進。","イノベーション政策",2015,"policy","policy",["OECD","World Bank"],["OECD Water Innovation Studies"],"","水イノベーション,水安全保障,スマート水管理","water innovation, water security, smart water management, desalination")
add("Bibliometric Mapping of Innovation Policy Research","イノベーション政策研究の計量書誌学的マッピング","イノベーション政策に関する学術研究自体を計量書誌学的手法で分析し、研究の知的構造、主要学派、トレンド、ギャップを明らかにする。メタ分析的アプローチでイノベーション政策研究の現状を俯瞰する。","イノベーション政策研究の知的構造の俯瞰的分析。","計量書誌学",2010,"measurement","learning",["Jan Fagerberg","Ben Martin"],["Fagerberg, Fosaas & Sapprasert (2012) Innovation: Exploring the knowledge base"],"","政策研究マッピング,メタ分析,知的構造","policy research mapping, meta-analysis, intellectual structure")
add("Innovation Output Measurement Beyond GDP","GDP を超えるイノベーション成果測定","GDPに計上されないイノベーションの成果（消費者余剰、環境改善、健康増進、デジタル財の無料価値等）を測定する方法論。Brynjolfssonらの研究がデジタル経済の「GDP未測定の価値」を推計。","GDP未測定のイノベーション価値の定量化。","イノベーション計量学",2014,"measurement","learning",["Erik Brynjolfsson","Andrew McAfee"],["Brynjolfsson & McAfee (2014) The Second Machine Age"],"","GDP超え,消費者余剰,デジタル価値","beyond GDP, consumer surplus, digital value, unmeasured innovation")
add("Intellectual Property Tribunal Analysis","知的財産裁判所分析","特許・商標等の知財訴訟の判決パターン、損害賠償額、差止命令率等のデータを分析し、知財裁判制度がイノベーション・インセンティブに与える影響を評価する方法論。","知財裁判制度のイノベーション・インセンティブ効果の分析。","特許分析",2005,"measurement,institutional","policy",["Alberto Galasso","Mark Schankerman"],["Galasso & Schankerman (2015) Patents and Cumulative Innovation"],"","知財訴訟分析,判決パターン,損害賠償","IP litigation analysis, judgment patterns, damages, innovation incentive")
add("Innovation and Industrial Commons","イノベーションと産業コモンズ","特定産業クラスターに共有される技術的能力、サプライヤーネットワーク、熟練労働力プール等の共有資源（産業コモンズ）がイノベーション能力に与える影響の分析。コモンズの劣化がイノベーション能力の喪失につながるメカニズム。","産業コモンズのイノベーション基盤としての役割分析。","イノベーション政策",2009,"systemic,policy","policy,learning",["Gary Pisano","Willy Shih"],["Pisano & Shih (2009) Restoring American Competitiveness"],"","産業コモンズ,共有能力,産業基盤","industrial commons, shared capabilities, industrial base, competitiveness")
add("Innovation Policy Performance Framework","イノベーション政策パフォーマンス枠組み","イノベーション政策の設計・実施・成果を統合的に評価する包括的パフォーマンス枠組み。政策のインプット（予算・人員）、プロセス（効率・品質）、アウトプット（助成件数等）、アウトカム（イノベーション促進効果）、インパクト（経済・社会的影響）の5層で評価。","イノベーション政策の5層的パフォーマンス評価枠組み。","イノベーション政策評価",2010,"measurement,policy","policy",["OECD","European Commission"],["OECD Innovation Policy Performance Framework"],"","パフォーマンス枠組み,5層評価,政策評価","performance framework, five-layer evaluation, policy assessment")
add("Innovation and Sustainability Transition Indicators","イノベーションと持続可能性移行の指標","社会-技術システムの持続可能性移行（エネルギー転換、循環経済等）の進捗をイノベーション指標で追跡する方法論。ニッチ技術の市場シェア、制度変革の進捗、既存レジームの変化等を多次元的に測定する。","持続可能性移行の進捗をイノベーション視点で追跡。","イノベーション計量学",2015,"measurement,systemic","policy,learning",["Frank Geels","Johan Schot"],["Geels et al. (2017) Sociotechnical Transitions for Deep Decarbonization"],"","移行指標,ニッチ技術,レジーム変化","transition indicators, niche technology, regime change, deep decarbonization")
add("Innovation and Mental Health Policy","イノベーションとメンタルヘルス政策","デジタルメンタルヘルス、AIベースの診断支援、VR療法等のメンタルヘルス分野のイノベーションを促進する政策体系。規制の適応、エビデンス基準の設定、デジタル治療薬（DTx）の承認プロセスの整備等を含む。","メンタルヘルス・イノベーションの促進と規制整備。","イノベーション政策",2020,"policy","policy",["FDA","NICE"],["FDA Digital Health Center of Excellence"],"","メンタルヘルスイノベーション,DTx,デジタル治療","mental health innovation, DTx, digital therapeutics, AI diagnosis")
add("Innovation Scoreboard Methodology Evolution","イノベーション・スコアボード方法論の進化","EIS等のイノベーション・スコアボードの方法論が時間とともに進化してきた過程の分析。指標の追加・削除、重み付け方法の変更、正規化手法の改善等の方法論的変遷がスコアボードの結果に与える影響を評価する。","イノベーション指標方法論の進化と結果への影響分析。","イノベーション計量学",2001,"measurement","learning",["Hugo Hollanders","European Commission"],["EIS Methodology Evolution Reports"],"","方法論進化,指標変遷,堅牢性","methodology evolution, indicator change, robustness, sensitivity")
add("Innovation Policy for Pandemic Resilience","パンデミック・レジリエンスのためのイノベーション政策","COVID-19の教訓を踏まえた、パンデミックへの備えと対応のためのイノベーション・エコシステム構築政策。ワクチン開発プラットフォーム、診断技術、サーベイランスシステム等の事前準備と緊急時活性化メカニズム。","パンデミック対応イノベーション能力の事前構築。","イノベーション政策",2021,"policy,systemic","policy",["CEPI","BARDA","WHO"],["WHO mRNA Technology Transfer Hub"],"","パンデミックレジリエンス,事前準備,mRNA","pandemic resilience, preparedness, mRNA, surveillance system")
add("Innovation and Antitrust in Digital Markets","デジタル市場における独禁法とイノベーション","デジタルプラットフォーム市場における独占禁止法の執行がイノベーション・ダイナミクスに与える影響の分析。キラー買収（潜在的競合の排除目的のM&A）、自己優遇、データ独占等の新しい競争問題とイノベーションの関係。","デジタル市場の独禁法執行のイノベーション影響分析。","イノベーション政策",2019,"policy,institutional","policy",["Lina Khan","European Commission"],["EU DMA","FTC Digital Markets Reports"],"","デジタル独禁法,キラー買収,データ独占","digital antitrust, killer acquisition, data monopoly, platform competition")
add("Innovation Governance and Institutional Quality","イノベーション・ガバナンスと制度の質","法の支配、規制の質、汚職の抑制、政治的安定性等のガバナンス指標がイノベーション・パフォーマンスに与える影響の分析。世界銀行WGI（Worldwide Governance Indicators）とイノベーション指標の相関・因果関係を検証する。","制度的ガバナンスの質がイノベーションに与える影響の分析。","イノベーション計量学",2000,"measurement,institutional","policy,learning",["Daniel Kaufmann","World Bank"],["World Bank Worldwide Governance Indicators"],"","制度の質,ガバナンス指標,WGI","institutional quality, governance indicators, WGI, rule of law")
add("Innovation System Failures Taxonomy","イノベーション・システム失敗の分類体系","イノベーション・システムの機能不全を体系的に分類する拡張版枠組み。市場の失敗、システムの失敗（ネットワーク、制度、インフラ）、変革の失敗（方向性、需要の明確化、政策調整）の三世代の失敗論を統合する。","三世代の失敗論を統合した包括的分類体系。","イノベーション政策",2018,"policy,systemic","policy,learning",["Johan Schot","W. Edward Steinmueller"],["Schot & Steinmueller (2018) Three frames for innovation policy"],"market failure only","三世代失敗論,包括的分類,政策正当化","three-generation failure, comprehensive taxonomy, policy rationale")
add("Innovation Measurement and AI","AIによるイノベーション測定の変革","機械学習・NLP・コンピュータビジョン等のAI技術がイノベーション測定自体を変革する潜在的可能性の分析。特許・論文の自動分類、製品イノベーションのWeb検出、衛星画像からの経済活動推定等の新手法。","AI技術によるイノベーション測定方法論自体の変革。","イノベーション計量学",2020,"measurement","learning",["OECD","JRC"],["OECD AI and Innovation Measurement Reports"],"","AI測定,自動分類,新手法","AI measurement, automated classification, new methods, innovation detection")
add("Innovation Policy Evaluation Meta-Analysis","イノベーション政策評価のメタ分析","R&D補助金、税額控除、クラスター政策等のイノベーション政策介入の効果に関する多数の実証研究を統合的に分析するメタ分析手法。個別研究間の効果量の異質性とその要因を体系的に解明する。","政策効果に関する実証研究群の統合的分析。","イノベーション政策評価",2010,"measurement,policy","policy,learning",["Hanna Hottenrott","Bronwyn Hall"],["Zúñiga-Vicente et al. (2014) Assessing the Effect of Public Subsidies on Firm R&D Investment"],"","メタ分析,効果量,政策効果統合","meta-analysis, effect size, policy effect synthesis, systematic review")
add("Innovation Policy and Geopolitical Bloc Formation","イノベーション政策と地政学的ブロック形成","米中技術競争を背景とした技術ブロック形成（デカップリング/デリスキング）がグローバルなイノベーション・システムに与える影響の分析。技術標準の分裂、R&D協力の制約、サプライチェーンの再編等の政策課題。","地政学的ブロック形成のイノベーション・システムへの影響。","イノベーション政策",2022,"policy,institutional","policy",["OECD","Brookings"],["OECD TIP Innovation and Geopolitics Reports"],"","技術ブロック,デリスキング,標準分裂","technology bloc, de-risking, standards fragmentation, innovation decoupling")
add("Innovation Measurement Dashboard Design","イノベーション測定ダッシュボード設計","イノベーション政策の意思決定者向けに、多次元的なイノベーション指標を直観的に表示するダッシュボードの設計原則。情報の階層構造、アラート機能、時系列比較、ドリルダウン等のUX設計と技術的実装を体系化する。","政策意思決定支援のためのイノベーション指標ダッシュボード設計。","イノベーション計量学",2018,"measurement","policy,learning",["JRC","OECD"],["JRC Innovation Dashboard Technical Reports"],"","ダッシュボード設計,UX,意思決定支援","dashboard design, UX, decision support, real-time visualization")

output_dir = os.path.dirname(os.path.abspath(__file__))
total = len(entries)
print(f"Total entries generated (batch 5): {total}")
print(f"ID range: inno_pol_679 to inno_pol_{678+total}")
print(f"Grand total pol: 378 + {total} = {378+total}")
filepath = os.path.join(output_dir, f"pol_batch_10.json")
with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(entries, f, ensure_ascii=False, indent=2)
print(f"Written {total} entries to {filepath}")
