"""
LIT-DB Phase 2 — C39 Wave 2: Digital Humanities & AI Era (50 concepts)
======================================================================
50 concepts across 5 categories:
  1. Hypertext / Electronic literature (10)
  2. AI authorship concepts (10)
  3. Creativity / text-generation concepts (10)
  4. Reception / criticism (10)
  5. Major theorist concepts (10)

subfield_id=24, code='lit_digital_ai', region='理論'
"""
from __future__ import annotations

import sys
from lit_db_helper import LitDB, LitDBError


SUBFIELD = "lit_digital_ai"
REGION = "理論"


def C(name_ja, name_en, definition, *, background=None, development=None,
      historical_context=None, url=None, src_type=None, tier="secondary",
      canon="major", importance=3, fourth=None, cd=None):
    return {
        "name_ja": name_ja,
        "name_en": name_en,
        "name_original": name_en,
        "original_script": "roman",
        "subfield_code": SUBFIELD,
        "region": REGION,
        "definition": definition,
        "background": background,
        "development": development,
        "historical_context": historical_context,
        "primary_source_url": url,
        "primary_source_type": src_type,
        "importance_score": importance,
        "source_tier": tier,
        "canonical_in_region": canon,
        "fourth_axes": fourth or [],
        "cross_domain": cd or [],
    }


CONCEPTS = [
    # === Cat 1: Hypertext / Electronic literature ===
    C("ハイパーテキスト・フィクション", "hypertext fiction",
      "ノードとリンクで構成される非線形物語。読者がリンクを選択して経路を生成し、固定された筋を持たない。Storyspace等のオーサリング環境で1990年代に隆盛した電子文学の最初期形態。",
      background="Bushの「Memex」構想とNelsonのXanaduを起源に、Joyce『afternoon』(1990)が嚆矢。",
      development="Web普及で衰退するが、Twine等のツールで再生し、インタラクティブナラティブの原型として残る。",
      historical_context="紙媒体の線形性を超克する1980-90年代ポストモダン文学運動と接続。",
      url="https://collection.eliterature.org/1/", src_type="ELO Volume 1",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "物語", "status": "rethinking",
               "rationale": "ハイパーテキストの非線形物語は、生成AIが動的に生成する分岐物語の構造的先駆である。",
               "related_ai_phenomenon": "LLMによる動的物語生成"}],
      cd=[{"target_db": "AI-Development", "link_type": "parallel",
           "target_entity_name": "interactive narrative AI",
           "description": "AI生成インタラクティブナラティブの先行構造"}]),
    C("レクシア", "lexia",
      "Roland Barthesが『S/Z』で提案した「読みの単位」を、Landowらがハイパーテキストの基本ノード概念として再定義した語。リンクで接続される自己完結的テクスト断片。",
      background="Barthes『S/Z』(1970)の読みの単位論をLandow『Hypertext』(1992)が継承。",
      development="ELOアーカイブの基本単位として定着。",
      url="https://www.eliterature.org/", src_type="ELO",
      tier="secondary", canon="major", importance=3),
    C("Storyspace", "Storyspace",
      "Eastgate Systems社が1987年に開発したハイパーテキスト・オーサリングソフト。Joyce『afternoon』、Moulthrop『Victory Garden』等の古典電子文学を生んだ環境。",
      background="Bolter, Joyce, Smithによる1987年の共同開発。",
      development="現在もEastgateが商用販売、ELO第1巻に多数収録。",
      url="http://www.eastgate.com/storyspace/", src_type="Eastgate",
      tier="primary", canon="major", importance=3),
    C("Twineナラティブ", "Twine narrative",
      "Chris Klimasが2009年に開発したオープンソースのハイパーテキスト/IFオーサリングツールおよびその作品群。インディー作家が大量に参加し、電子文学を民主化した。",
      background="Inform/TADSのプログラミング障壁を取り払うWebベースGUI。",
      development="Porpentine『Howling Dogs』等で電子文学の社会的多様性を拡張。",
      url="https://twinery.org/", src_type="Twine official",
      tier="primary", canon="major", importance=4,
      fourth=[{"axis": "作者性", "status": "partial",
               "rationale": "Twineは作家の多様化（クィア・障害・有色人種）を促し、伝統的作者像を脱中心化した。",
               "related_ai_phenomenon": "AIツールによる創作の民主化"}]),
    C("インタラクティブ・フィクション", "Interactive Fiction (IF)",
      "テキスト入力で世界を操作する物語ジャンル。Crowther & Woods『Adventure』(1976)、Infocom『Zork』(1980)等のテキストアドベンチャーが起源。Inform 7等のDSLで現代も活発に制作。",
      background="MITハッカー文化とInfocom商用化期(1980-89)が原型。",
      development="IF Comp等のコミュニティで継続、AI Dungeon等LLM駆動型へと展開。",
      url="https://ifdb.org/", src_type="IFDB",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "物語", "status": "rethinking",
               "rationale": "プレイヤー入力に応答する物語生成は、LLMチャット型物語の直接的祖先である。",
               "related_ai_phenomenon": "AI Dungeon等LLMインタラクティブ物語"}],
      cd=[{"target_db": "AI-Development", "link_type": "parallel",
           "target_entity_name": "AI Dungeon", "description": "LLMによるIF継承"}]),
    C("エルゴード文学", "ergodic literature",
      "Espen Aarseth『Cybertext』(1997)の概念。読者に「非自明な労力（nontrivial effort）」を要求するテクストを指し、ハイパーテキスト・IF・ゲームを包摂する文学カテゴリ。",
      background="物理学のエルゴード理論に由来する用語をAarsethが文学に転用。",
      development="ゲームスタディーズの基礎概念として定着。",
      url="https://www.jhupbooks.com/title/cybertext", src_type="JHU Press",
      tier="secondary", canon="core", importance=5,
      fourth=[{"axis": "受容", "status": "rethinking",
               "rationale": "受動的読みではなく能動的労力を要するエルゴード性は、AIプロンプト操作による物語生成と同型である。",
               "related_ai_phenomenon": "プロンプト工学による物語生成"}]),
    C("コードポエトリー", "code poetry",
      "プログラミング言語の構文・コンパイル可能性を詩的素材とする実験詩。Mez Breeze『mezangelle』、bpNichol等の系譜。コードと自然言語の境界を主題化する。",
      background="コンクリート・ポエトリーとハッカー美学の交叉領域。",
      development="PoetryGenerator、Code{4}libなどで継続。",
      url="https://codepoems.eu/", src_type="codepoems.eu",
      tier="secondary", canon="minor", importance=3,
      fourth=[{"axis": "言語", "status": "rethinking",
               "rationale": "人間言語と機械言語の混在は、LLMのトークン化の前史をなす。",
               "related_ai_phenomenon": "コード生成LLM(Codex/Copilot)"}]),
    C("生成文法（生成詩学）", "generative grammar",
      "言語規則と確率モデルからテクストを生成する詩学的枠組み。Queneau『百兆の詩篇』、OuLiPoのアルゴリズム作詩、現代のRNN/Transformer詩生成まで連なる系譜。",
      background="Chomsky生成文法の文学応用と、戦後フランス実験文学の交点。",
      development="Markov連鎖→RNN→Transformerと技術更新。",
      url="https://collection.eliterature.org/", src_type="ELO",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "規則による自動生成詩学は、LLMの確率的テクスト生成と直接連続する。",
               "related_ai_phenomenon": "LLMテクスト生成"}]),
    C("ウリポ", "OuLiPo",
      "1960年Queneau, Le Lionnais創設の「潜在文学工房（Ouvroir de littérature potentielle）」。形式的制約をテクスト生成の起爆剤とする実験運動。Perec『煙滅』が代表作。",
      background="超現実主義への反動と、数学的形式主義への接近。",
      development="Calvino、Mathewsらが国際化。生成AI時代に「制約付きプロンプト」として再評価。",
      historical_context="戦後フランスの構造主義的言語観の文学的展開。",
      url="https://oulipo.net/", src_type="Oulipo official",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "形式的制約による創造性産出は、プロンプト工学の前身である。",
               "related_ai_phenomenon": "constrained decoding/prompt constraints"}],
      cd=[{"target_db": "AI-Development", "link_type": "parallel",
           "target_entity_name": "constrained generation",
           "description": "形式制約とAI生成の構造同型"}]),
    C("カットアップ技法", "cut-up technique",
      "既存テクストを物理的に切断・再配置して新しい意味を生成する技法。Tristan Tzaraのダダ実験を起源とし、William Burroughs, Brion Gysinが1950-60年代に体系化。",
      background="Dada運動の偶然性詩学を散文に応用。",
      development="サンプリング音楽、デジタル・リミックス、生成AIの「マッシュアップ」へ。",
      url="https://www.gutenberg.org/", src_type="PD references",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "断片の再配置による「作者なき作品」概念は、LLMの確率的混成と同型。",
               "related_ai_phenomenon": "LLMによるテクスト混成生成"}]),

    # === Cat 2: AI authorship concepts ===
    C("AIとの共著", "co-authorship with AI",
      "人間とAIの協働でテクストを生成する制作様式。Sudowrite、ChatGPT等のツールが普及した2022年以降、文学・ジャーナリズム・学術領域で論争的トピックとなる。",
      background="GPT-3公開(2020)以降、人間-AI協働制作が大規模に出現。",
      development="ニューヨーク・タイムズ等が共著ガイドライン策定中。",
      url="https://www.nature.com/articles/d41586-023-00191-1",
      src_type="Nature 2023",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "人間-機械の共著は伝統的作者概念を根本的に書き換える。",
               "related_ai_phenomenon": "ChatGPT/Sudowriteによる共同執筆"}],
      cd=[{"target_db": "PHIL", "link_type": "shared_concept",
           "target_entity_name": "author function",
           "description": "Foucaultの作者機能の現代的更新"}]),
    C("プロンプト＝作者性", "prompt-as-authorship",
      "プロンプトを書く行為自体を作者性の中核と再定義する立場。テクスト出力ではなくプロンプト設計に作家性が宿るとする。AI時代の著作権論争の核心。",
      background="2022年以降の生成AI普及で実務上の論点として浮上。",
      development="米著作権局2023年「Zarya of the Dawn」判定が法的判断の起点。",
      url="https://www.copyright.gov/ai/",
      src_type="US Copyright Office",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "出力テクストではなく入力指示こそが作者の証であるという反転は、文学的作者性の根本再定義である。",
               "related_ai_phenomenon": "プロンプト著作権論争"}]),
    C("確率的オウム", "stochastic parrot",
      "Bender, Gebru, McMillan-Major, Mitchellの2021年論文の概念。LLMは意味理解なく統計的パターンを反復する「確率的オウム」だとする批判。AI批評の基礎用語。",
      background="2021年FAccT論文「On the Dangers of Stochastic Parrots」。",
      development="Geburの解雇問題と並行してAI倫理論争の中心概念に。",
      url="https://dl.acm.org/doi/10.1145/3442188.3445922",
      src_type="ACM FAccT 2021",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "言語", "status": "rethinking",
               "rationale": "意味なき言語生成という批判は、文学言語の意味性そのものを再考させる。",
               "related_ai_phenomenon": "LLMの意味理解論争"}],
      cd=[{"target_db": "PHIL", "link_type": "shared_concept",
           "target_entity_name": "意味理解 / understanding",
           "description": "LLMの意味理解問題の哲学的射程"},
          {"target_db": "AI-Development", "link_type": "shared_concept",
           "target_entity_name": "stochastic parrots paper"}]),
    C("ポストヒューマン作者性", "posthuman authorship",
      "N. Katherine Hayles, Cary Wolfeらが定式化した、人間中心の作者概念を脱構築する立場。サイボーグ・分散主体・非人間エージェントを作者性の構成要素として包摂する。",
      background="Hayles『How We Became Posthuman』(1999)。",
      development="生成AI時代に実務的具体性を獲得。",
      url="https://press.uchicago.edu/ucp/books/book/chicago/H/bo3769963.html",
      src_type="UChicago Press",
      tier="secondary", canon="core", importance=5,
      fourth=[{"axis": "主体", "status": "rethinking",
               "rationale": "人間-非人間の境界を解消する作者概念は、AI時代の中心テーゼである。",
               "related_ai_phenomenon": "AI共著・AIエージェント執筆"}],
      cd=[{"target_db": "PHIL", "link_type": "shared_concept",
           "target_entity_name": "posthumanism"}]),
    C("ゴーストライティング（AI）", "ghost authorship",
      "AIが実質的に執筆しながら人間名義で公表される慣行。学術不正・出版倫理の新類型として2023年以降規制議論が活発化。",
      background="GPT-3/4による論文・書籍量産が顕在化。",
      development="Springer Nature, Elsevier等が著者表記ガイドライン更新。",
      url="https://www.science.org/content/article/chatgpt-listed-author",
      src_type="Science News 2023",
      tier="primary", canon="major", importance=4,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "AI執筆の不開示は真正性概念を新たな試練にさらす。",
               "related_ai_phenomenon": "AI生成論文の著者表記問題"}]),
    C("帰属パラドクス", "attribution paradox",
      "AI生成テクストにおける「誰が書いたか」を問うこと自体が答えを得られないとするパラドクス。プロンプト・モデル・訓練データ・人間編集者の寄与が分割不可能なため。",
      background="2022-23年の著作権論争で実務的に浮上した概念。",
      development="法学者Sag, Lemleyらが理論化。",
      url="https://harvardlawreview.org/", src_type="HLR forum 2023",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "帰属の根源的不可能性は、伝統的作者法理の前提を揺るがす。",
               "related_ai_phenomenon": "AI著作権訴訟"}]),
    C("作者機能の再考", "author function reconsidered",
      "Foucault『作者とは何か』(1969)の作者機能概念を生成AI時代に再検討する潮流。テクストの統一性・所有性・責任性を機械生成に拡張可能か問う。",
      background="Foucaultの作者機能論を出発点に、Hayles, Marinoらが拡張。",
      development="2023年以降、ELO/MLA等の学会でセッション化。",
      url="https://www.foucault.info/documents/foucault.authorFunction.en/",
      src_type="Foucault archive",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "作者機能を機械エージェントに拡張する操作は、文学理論の根幹的更新を要する。",
               "related_ai_phenomenon": "AI作者性論争"}],
      cd=[{"target_db": "PHIL", "link_type": "borrowed_from",
           "target_entity_name": "Foucault author function",
           "description": "Foucault作者機能論の拡張継承"}]),
    C("機械協働", "machine collaboration",
      "AIを単なる道具ではなく協働パートナーと位置づける制作論。Marcus du SautoyやAllison Parrish等の実践者が定式化。",
      background="2010年代のヒューマン・コンピュータ・コラボレーション研究。",
      development="GPT時代に文学制作の標準モデルへ。",
      url="https://www.decontextualize.com/", src_type="Parrish blog",
      tier="secondary", canon="major", importance=3),
    C("AIゴーストライティング", "AI ghostwriting",
      "AIが裏方として執筆を代行する商業的実践。マーケティング、書籍代筆、SNS運用代行など多領域で常態化。文学倫理の境界事例。",
      background="2022年以降の生成AI民主化で爆発的拡大。",
      development="The Atlantic等が業界実態を報道(2023)。",
      url="https://www.theatlantic.com/technology/archive/2023/",
      src_type="The Atlantic 2023",
      tier="secondary", canon="minor", importance=3,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "商業的代筆が大規模化することで、文学の真正性概念は社会的に再交渉される。",
               "related_ai_phenomenon": "AI代筆業界の出現"}]),
    C("分散作者性", "distributed authorship",
      "プロンプト書き手・モデル開発者・訓練データ提供者・編集者にまたがる分散的作者概念。Bruno LatourのANTを文学制作に応用した枠組み。",
      background="Latour『Reassembling the Social』のアクター概念を継承。",
      development="2020年代にAI制作論で標準化。",
      url="http://www.bruno-latour.fr/",
      src_type="Latour archive",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "作者性", "status": "rethinking",
               "rationale": "作者を単一エージェントから分散ネットワークとして捉え直す。",
               "related_ai_phenomenon": "AI制作の分散責任論"}],
      cd=[{"target_db": "PHIL", "link_type": "borrowed_from",
           "target_entity_name": "actor-network theory"}]),

    # === Cat 3: Creativity / text generation ===
    C("機械創造性", "machine creativity",
      "機械システムが創造的成果を生む能力に関する研究領域。Boden『The Creative Mind』が探索的・組み合わせ的・変容的創造性の3類型を提示。",
      background="AI黎明期からの古典的問題系。",
      development="LLM登場で実証段階に。",
      url="https://academic.oup.com/book/", src_type="Boden 2004 OUP",
      tier="secondary", canon="core", importance=5,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "機械が創造的か否かは、文学創造性の定義そのものを問い直す。",
               "related_ai_phenomenon": "LLM創造性論争"}],
      cd=[{"target_db": "AI-Development", "link_type": "shared_concept",
           "target_entity_name": "computational creativity"}]),
    C("計算論的創造性", "computational creativity",
      "AAAI Computational Creativity Conferenceに代表される研究分野。創造性の形式モデル化と計算実装を探究する。",
      background="2010年ICCC設立で領域として確立。",
      development="生成AI普及で実用段階へ。",
      url="https://computationalcreativity.net/",
      src_type="ICCC official",
      tier="primary", canon="major", importance=4),
    C("潜在空間探索", "latent space exploration",
      "ニューラルネットワークの潜在空間を芸術的探索の場とする実践。Refik Anadolら視覚芸術家が主導、文学では潜在空間を「経由」した詩生成が実験される。",
      background="VAE/GANの潜在表現を芸術素材化する2010年代後半の動向。",
      development="diffusion model時代に多モーダル文学へ拡張。",
      url="https://refikanadol.com/", src_type="artist site",
      tier="secondary", canon="minor", importance=3,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "潜在空間を旅する作家性は、伝統的構想力概念を空間的・統計的に書き換える。",
               "related_ai_phenomenon": "diffusionモデルの潜在空間探索"}]),
    C("プロンプト工学＝芸術", "prompt engineering as art",
      "プロンプトの構成と反復を独立した芸術行為と見なす立場。midjourney/DALL-Eコミュニティから始まり文学領域にも拡張。",
      background="2022年Stable Diffusion公開後の実践共同体で形成。",
      development="プロンプトブック・プロンプト辞典が出版。",
      url="https://learnprompting.org/", src_type="Learn Prompting",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "プロンプトを芸術形式と認める動きは、創作の単位そのものを再定義する。",
               "related_ai_phenomenon": "プロンプト共有プラットフォーム"}]),
    C("スタイル転移", "style transfer",
      "あるテクストの内容を別の文体に変換する技術と詩学的概念。Gatys et al.の画像スタイル転移(2015)を起点に、テクスト領域へ拡張された。",
      background="ニューラルスタイル転移2015年論文。",
      development="LLMのin-context learningで実用化。",
      url="https://arxiv.org/abs/1508.06576",
      src_type="arXiv 2015",
      tier="primary", canon="major", importance=4,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "他者の文体を機械的に纏う技術は、文体の固有性概念を揺るがす。",
               "related_ai_phenomenon": "LLM文体模倣"}]),
    C("詩学としての幻覚", "hallucination as poetics",
      "LLMの「幻覚（hallucination）」を欠陥ではなく詩学的潜勢力として読み替える立場。Allison Parrish, Lillian-Yvonne Bertramらの詩実践。",
      background="幻覚はLLM技術上の課題だが、詩人がそれを素材化。",
      development="2023年以降、AI詩集で多数実装。",
      url="https://lillianyvonnebertram.com/",
      src_type="poet site",
      tier="secondary", canon="minor", importance=3,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "事実誤認を詩的真理に転換する操作は、真正性概念を文学的に再定義する。",
               "related_ai_phenomenon": "LLM hallucination"}]),
    C("合成テクスト", "synthetic text",
      "AIによって生成されたテクスト一般を指す総称。検出・水印・規制・読解倫理の対象として2020年代に独立カテゴリ化。",
      background="GPT-2公開以降、合成テクスト検出研究が活発化。",
      development="EU AI Act, OECDがガイドライン整備。",
      url="https://artificialanalysis.ai/", src_type="industry analysis",
      tier="secondary", canon="major", importance=4),
    C("インコンテクスト学習ナラティブ", "in-context learning narrative",
      "プロンプト中に少数事例を示すだけで物語生成を制御する手法と、その物語論的効果。Brown et al. GPT-3論文で定式化。",
      background="Brown et al. 2020 NeurIPS。",
      development="物語生成の主要技法に。",
      url="https://arxiv.org/abs/2005.14165",
      src_type="arXiv 2020",
      tier="primary", canon="major", importance=4),
    C("RAGナラティブ", "RAG narrative",
      "Retrieval-Augmented Generationを物語生成に応用する技法。外部知識を検索し物語に統合することで事実性と創造性を両立させる。",
      background="Lewis et al. 2020 RAG論文。",
      development="商用文学AIサービスの基盤技術。",
      url="https://arxiv.org/abs/2005.11401",
      src_type="arXiv 2020",
      tier="primary", canon="major", importance=4),
    C("モデル崩壊", "model collapse",
      "AI生成テクストで訓練したモデルが世代を経るにつれ多様性を失う現象。Shumailov et al. 2024 Nature論文で実証。文学言語の生態系劣化の指標。",
      background="2023年以降AI生成データの再循環問題が顕在化。",
      development="2024年Nature掲載で広く認知。",
      url="https://www.nature.com/articles/s41586-024-07566-y",
      src_type="Nature 2024",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "言語", "status": "rethinking",
               "rationale": "AIテクストの自己再帰的劣化は、言語生態系全体の脆弱性を示す。",
               "related_ai_phenomenon": "AI生成データの自己汚染"}],
      cd=[{"target_db": "AI-Development", "link_type": "shared_concept",
           "target_entity_name": "model collapse"}]),

    # === Cat 4: Reception / criticism ===
    C("AIリテラシー", "AI literacy",
      "AI生成物を読解・評価・批判する能力。OECDがコンピテンシー枠組みに組み込み、文学教育の基礎技能として2020年代に標準化。",
      background="UNESCO/OECDが2021年以降、教育枠組み策定。",
      development="国語・文学教育のカリキュラムに導入。",
      url="https://unesdoc.unesco.org/", src_type="UNESCO",
      tier="primary", canon="major", importance=4),
    C("プロンプト批評", "prompt criticism",
      "プロンプトをテクスト批評の対象とする手法。プロンプトの選択・順序・暗黙的バイアスを分析し作者性を読む。Marinoの批判的コードスタディーズの拡張。",
      background="2022年以降の生成AI普及で必要性が浮上。",
      development="ELO 2024でセッション化。",
      url="https://eliterature.org/", src_type="ELO",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "受容", "status": "rethinking",
               "rationale": "出力ではなく入力を読む批評は、批評対象そのものを反転させる。",
               "related_ai_phenomenon": "プロンプト共有・批評の制度化"}]),
    C("計算論的精読", "computational close reading",
      "計算手法を伝統的精読と組み合わせる批評技法。Tanya Clement, Stephen Ramsay等のDH学者が提唱。",
      background="2010年代のデジタル人文学方法論論争。",
      development="LLM時代に新展開。",
      url="https://dhdebates.gc.cuny.edu/",
      src_type="Debates in DH",
      tier="secondary", canon="major", importance=4),
    C("遠読", "distant reading",
      "Franco Morettiが2000年論文「Conjectures on World Literature」で提唱した、大規模コーパスを統計的に分析する批評手法。精読への対抗概念。",
      background="Moretti 2000 NLR論文。",
      development="Stanford Literary Labで実践、Jocker, Underwoodへ継承。",
      url="https://newleftreview.org/issues/ii1/articles/franco-moretti-conjectures-on-world-literature",
      src_type="NLR 2000",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "受容", "status": "rethinking",
               "rationale": "計算的距離からの読みは、AI読解との連続性をもち、批評の規模を再定義した。",
               "related_ai_phenomenon": "LLMによるコーパス分析"}],
      cd=[{"target_db": "AN", "link_type": "parallel",
           "target_entity_name": "cultural analytics",
           "description": "文化分析との方法論的近接"}]),
    C("文化分析", "cultural analytics",
      "Lev Manovichが2007年に提唱した、計算的手法で文化現象を分析する研究プログラム。文学・映像・SNS等を横断する量的方法論。",
      background="Software Studies Initiative設立(2007)。",
      development="ビッグデータ・LLMで方法拡張。",
      url="http://manovich.net/", src_type="Manovich site",
      tier="primary", canon="core", importance=5,
      cd=[{"target_db": "AN", "link_type": "shared_concept",
           "target_entity_name": "cultural analytics"}]),
    C("文学におけるアルゴリズム的バイアス", "algorithmic bias in literature",
      "推薦アルゴリズム・LLM・自動翻訳が文学正典・読者選択・翻訳実践に注入する偏向。Safiya Noble, Joy Buolamwiniらの一般理論を文学領域に適用。",
      background="Noble『Algorithms of Oppression』(2018)。",
      development="文学翻訳AIのジェンダー・人種偏向研究で具体化。",
      url="https://nyupress.org/9781479837243/algorithms-of-oppression/",
      src_type="NYU Press",
      tier="secondary", canon="core", importance=5,
      fourth=[{"axis": "正典", "status": "rethinking",
               "rationale": "アルゴリズムによる正典形成は、文学正典概念を技術政治の場に置き直す。",
               "related_ai_phenomenon": "推薦アルゴリズムによる正典再形成"}],
      cd=[{"target_db": "AN", "link_type": "shared_concept",
           "target_entity_name": "algorithmic bias"}]),
    C("AIとの共読", "AI co-reading",
      "AIアシスタントを介して文学テクストを読む実践。要約・注釈・翻訳・対話的解釈を機械が補助する読書様式。",
      background="2022年以降の対話型AI普及で日常化。",
      development="教育現場で標準化進行。",
      url="https://www.modernlanguagesopen.org/",
      src_type="MLO journal",
      tier="secondary", canon="minor", importance=3,
      fourth=[{"axis": "受容", "status": "rethinking",
               "rationale": "読書が機械を介する共同行為となることは、受容概念の構造変化である。",
               "related_ai_phenomenon": "AI読解アシスタント"}]),
    C("文学におけるAI倫理", "AI ethics in literature",
      "文学制作・流通・批評におけるAI使用の倫理的枠組み。著者表記・著作権・盗用・データ正義等を扱う。",
      background="MLA/AHA/AWPなど2023-24年に倫理声明発表。",
      development="出版界・学術界で規範化進行中。",
      url="https://www.mla.org/", src_type="MLA statements",
      tier="primary", canon="major", importance=4),
    C("ディープフェイク文学", "deepfake literature",
      "故人作家・既存作家の文体を模倣して新作を生成する実践と、その倫理的・法的問題系。村上春樹風AI小説等が論争を招いた。",
      background="2020年代のスタイル転移技術成熟で具現化。",
      development="日本では2023年以降論議活発。",
      url="https://www.copyright.gov/policy/", src_type="Copyright Office",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "故人や著名作家の文体を模倣する作品は、真正性と作家の人格権を新たに問う。",
               "related_ai_phenomenon": "AIによる作家文体模倣"}]),
    C("AIモデレーション", "AI moderation",
      "プラットフォーム上の文学的表現をAIが自動審査・削除・抑制する実践。表現の自由と安全性の緊張を生む。",
      background="2010年代後半のSNS拡大期に大規模化。",
      development="LLMモデレーションが2020年代に標準。",
      url="https://transparency.fb.com/",
      src_type="Meta Transparency",
      tier="secondary", canon="major", importance=4,
      fourth=[{"axis": "受容", "status": "rethinking",
               "rationale": "テクストの公共性をアルゴリズムが規定する状況は、文学受容の制度的前提を変える。",
               "related_ai_phenomenon": "コンテンツ・モデレーションAI"}]),

    # === Cat 5: Major theorist concepts ===
    C("Haylesポストヒューマニズム", "Hayles posthumanism",
      "N. Katherine Haylesが『How We Became Posthuman』(1999)で提示した、情報・身体・主体性を脱中心化する思想枠組み。電子文学批評の基礎。",
      background="サイバネティクス史と文学批評の交差。",
      development="『My Mother Was a Computer』『Unthought』等で展開。",
      url="https://press.uchicago.edu/ucp/books/book/chicago/H/bo3769963.html",
      src_type="UChicago Press",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "主体", "status": "rethinking",
               "rationale": "ポストヒューマン主体論はAI時代の文学的主体概念の基礎を提供する。",
               "related_ai_phenomenon": "AI主体性論争"}],
      cd=[{"target_db": "PHIL", "link_type": "shared_concept",
           "target_entity_name": "posthumanism"}]),
    C("Marino批判的コード研究", "Marino critical code studies",
      "Mark C. Marinoが2006年に提唱した、ソースコードを文学テクストとして批評的に読む方法論。『Critical Code Studies』(MIT 2020)が体系化。",
      background="DH・電子文学・ソフトウェア研究の交差。",
      development="MIT Press 2020年に書籍化、現在も研究領域として拡大。",
      url="https://mitpress.mit.edu/9780262539210/critical-code-studies/",
      src_type="MIT Press",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "言語", "status": "rethinking",
               "rationale": "コードを文学言語として読む方法論は、自然言語と機械言語の境界を問う。",
               "related_ai_phenomenon": "LLMコード生成と文学性"}]),
    C("Manovich文化分析", "Manovich cultural analytics",
      "Lev Manovichが2007年から展開する、文化現象を計算的に分析するアプローチ。『The Language of New Media』(2001)が出発点。",
      background="ニューメディア研究の体系化者。",
      development="『Cultural Analytics』(MIT 2020)で方法論を集大成。",
      url="https://mitpress.mit.edu/9780262037105/",
      src_type="MIT Press",
      tier="primary", canon="core", importance=5),
    C("Kirschenbaumメカニズム", "Kirschenbaum mechanisms",
      "Matthew Kirschenbaumが『Mechanisms』(2008)で提示した、デジタル文学の物質性（記憶媒体・ファイルシステム）を批評対象とする視座。",
      background="アーカイブ研究とDHの交点。",
      development="『Track Changes』(2016)でワードプロセッサと文学史を接続。",
      url="https://mitpress.mit.edu/9780262517409/mechanisms/",
      src_type="MIT Press",
      tier="primary", canon="major", importance=4,
      fourth=[{"axis": "真正性", "status": "rethinking",
               "rationale": "デジタル媒体の物質性を批評対象化することで、テクストの真正性概念は更新される。",
               "related_ai_phenomenon": "AI生成物のデジタル証跡"}]),
    C("Bender確率的オウム論", "Bender stochastic parrots",
      "Emily M. Benderらが2021年論文で展開した、LLM批判の理論的枠組み。意味理解なき言語生成への警鐘。",
      background="計算言語学者の立場からのAI批判。",
      development="後続論文・書籍で議論を継続。",
      url="https://dl.acm.org/doi/10.1145/3442188.3445922",
      src_type="ACM 2021",
      tier="primary", canon="core", importance=5,
      cd=[{"target_db": "AI-Development", "link_type": "shared_concept",
           "target_entity_name": "Bender et al. 2021"}]),
    C("Gebru AI倫理", "Gebru AI ethics",
      "Timnit Gebruが提唱したAI倫理・データ正義の枠組み。文学領域では訓練データの公正性・先住民データ主権論等で重要。",
      background="Google解雇事件(2020)を機に独立。",
      development="DAIR Institute設立(2021)で研究継続。",
      url="https://www.dair-institute.org/",
      src_type="DAIR Institute",
      tier="primary", canon="core", importance=5,
      cd=[{"target_db": "AI-Development", "link_type": "shared_concept",
           "target_entity_name": "Gebru data justice"}]),
    C("Risamポストコロニアルデジタル人文学", "Risam postcolonial DH",
      "Roopika Risamが『New Digital Worlds』(2018)で展開した、デジタル人文学を脱植民地化する方法論。文学正典の地政学的偏向を批判。",
      background="ポストコロニアル理論とDHの統合。",
      development="Global South DH運動の理論的支柱。",
      url="https://nupress.northwestern.edu/9780810140691/",
      src_type="Northwestern UP",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "正典", "status": "rethinking",
               "rationale": "DHのデータ・正典の植民地性を暴く視座は、AI訓練データの偏向問題に直結する。",
               "related_ai_phenomenon": "LLM訓練データの偏向"}]),
    C("Nobleアルゴリズム的抑圧", "Noble algorithmic bias",
      "Safiya Umoja Nobleが『Algorithms of Oppression』(2018)で示した、検索アルゴリズムが人種・ジェンダー偏向を再生産する分析。文学正典・推薦の偏向にも適用。",
      background="図書館情報学とブラックフェミニズム理論の統合。",
      development="UCLA Center on Race & Digital Justice設立。",
      url="https://nyupress.org/9781479837243/algorithms-of-oppression/",
      src_type="NYU Press",
      tier="primary", canon="core", importance=5,
      cd=[{"target_db": "AN", "link_type": "shared_concept",
           "target_entity_name": "algorithmic oppression"}]),
    C("McKittrickデジタル人文学批判", "McKittrick digital humanities critique",
      "Katherine McKittrickがデジタル人文学のデータ実践に潜む人種化された認識論的暴力を批判する視座。『Dear Science』(2021)が代表作。",
      background="ブラック・スタディーズと地理学の交差。",
      development="DH領域で批判的人種理論として影響。",
      url="https://www.dukeupress.edu/dear-science",
      src_type="Duke UP",
      tier="primary", canon="major", importance=4,
      fourth=[{"axis": "正典", "status": "rethinking",
               "rationale": "データ・量化の中立性神話を解体する視座は、AI時代の正典再考に不可欠。",
               "related_ai_phenomenon": "AI訓練データの認識論的偏向"}]),
    C("Chiang AIフィクション思弁", "Chiang AI fiction speculation",
      "Ted ChiangがNew Yorker等で展開するAIに関する思弁的批評。「ChatGPT Is a Blurry JPEG of the Web」等の比喩が広く参照される。",
      background="SF作家による技術批評の系譜。",
      development="2023年以降、AI公共議論の鍵概念を多数提供。",
      url="https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web",
      src_type="The New Yorker 2023",
      tier="primary", canon="core", importance=5,
      fourth=[{"axis": "創造性", "status": "rethinking",
               "rationale": "LLMを「Webのぼやけたコピー」と捉える比喩は、AI創造性論争の枠組みを変えた。",
               "related_ai_phenomenon": "LLMの圧縮的言語生成"}]),
]


def main() -> int:
    print(f"[wave2_c39_dh_ai] inserting {len(CONCEPTS)} concepts...")
    if len(CONCEPTS) != 50:
        print(f"  WARNING: expected 50 concepts, got {len(CONCEPTS)}")

    fourth_count = 0
    cd_count = 0

    with LitDB() as db:
        for raw in CONCEPTS:
            entry = dict(raw)
            fourth_axes = entry.pop("fourth_axes", [])
            cross_domain = entry.pop("cross_domain", [])
            try:
                cid = db.insert_concept(**entry)
            except LitDBError as e:
                print(f"  [error] {entry['name_ja']}: {e}")
                continue

            for axis_entry in fourth_axes:
                try:
                    db.tag_fourth_transform(cid, **axis_entry)
                    fourth_count += 1
                except LitDBError as e:
                    print(f"  [tag-error] {entry['name_ja']}/{axis_entry.get('axis')}: {e}")

            for cd in cross_domain:
                try:
                    db.insert_cross_domain(
                        lit_entity_type="concept", lit_entity_id=cid,
                        target_db=cd["target_db"], link_type=cd["link_type"],
                        target_entity_id=cd.get("target_entity_id"),
                        target_entity_name=cd.get("target_entity_name"),
                        description=cd.get("description"),
                    )
                    cd_count += 1
                except LitDBError as e:
                    print(f"  [cd-error] {entry['name_ja']}: {e}")

        summary = db.progress_summary()
        print()
        print("[wave2_c39_dh_ai] done:")
        print(f"  total concepts: {summary['concepts']}")
        print(f"  fourth_transform_tags: {summary['fourth_transform_tags']} (this run: +{fourth_count})")
        print(f"  cross_domain: {summary['cross_domain']} (this run: +{cd_count})")
        for r in db.fourth_transform_distribution():
            print(f"    {r}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
