"""LIT-DB Phase 2 Wave 2 — C18: Modern Japanese Literature (50 concepts).

Compact insertion script. Sources: Aozora Bunko (青空文庫), NDL Digital
Collections, J-STAGE academic articles. PD primary texts -> 'primary',
critical secondary literature -> 'secondary', synthetic categories -> 'tertiary'.
"""
from __future__ import annotations
import sys
from lit_db_helper import LitDB, LitDBError

PERIODS = [
    ("明治期", "Meiji", 1868, 1912, "近代化と言文一致運動、写実・自然・浪漫の三派が並走した時代。"),
    ("大正期", "Taisho", 1912, 1926, "白樺派・新感覚派・私小説の確立期、近代的自我の深化。"),
    ("昭和戦前期", "Early Showa", 1926, 1945, "プロレタリア文学の勃興と弾圧、転向、戦時動員の時代。"),
    ("戦後期", "Postwar", 1945, 1970, "戦後派・第三の新人・原爆文学を生んだ被占領と再出発の時代。"),
    ("現代", "Contemporary", 1970, 2025, "内向の世代から在日文学・ライトノベル・ウェブ小説まで多元化した時代。"),
]
AOZORA = "https://www.aozora.gr.jp/"
NDL = "https://dl.ndl.go.jp/"
JSTAGE = "https://www.jstage.jst.go.jp/"

CONCEPTS: list[dict] = []
def add(**e): CONCEPTS.append(e)

C = dict(subfield_code="lit_jp_modern", region="東アジア", original_script="japanese")
# --- 文学運動/流派 (10) ---
add(**C, name_ja="写実主義（坪内逍遥）", name_en="Japanese realism", name_original="写実主義", period_key="明治期", definition="坪内逍遥『小説神髄』（1885）が提唱した、戯作的勧善懲悪を退け人情と世態を写実的に描くべしとする近代日本小説論。江戸戯作からの離脱と西欧的近代小説観の移植を同時に行った起点的言説である。", background="江戸戯作の道徳教化主義への批判と、英文学受容を背景に成立。", development="二葉亭四迷『浮雲』に実装され、自然主義・私小説へと展開した。", historical_context="明治国家の近代化志向と文学の自律化要求の交差。", primary_source_url=AOZORA+"cards/000264/card46873.html", primary_source_type="青空文庫『小説神髄』", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="自然主義（田山花袋）", name_en="Japanese naturalism", name_original="自然主義", period_key="明治期", definition="ゾラ流の科学的自然主義を日本的に屈折させ、田山花袋『蒲団』（1907）が確立した、作者自身の卑小な性欲と告白を題材化する文学運動。後の私小説の母胎となる。", background="島村抱月・長谷川天渓らの理論導入と、フランス自然主義の翻訳受容。", development="徳田秋声・正宗白鳥に継承されつつ、私小説への転回を生んだ。", historical_context="日露戦後の青年知識層の内面化と社会変革幻滅期。", primary_source_url=AOZORA+"cards/000214/card1668.html", primary_source_type="青空文庫『蒲団』", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="浪漫主義（北村透谷）", name_en="Japanese romanticism", name_original="浪漫主義", period_key="明治期", definition="北村透谷を中心に『文学界』（1893-）に集った青年たちが、内面の自由と恋愛・宗教的超越を主題化した文学運動。島崎藤村・樋口一葉も初期に関わる。", background="自由民権運動の挫折後、政治から内面へと退却した青年知識人の精神運動。", development="藤村『若菜集』『破戒』へと展開し、自然主義への橋渡しとなる。", historical_context="近代国家の制度化と個人の内面性の発見が交差した明治20年代。", primary_source_url=AOZORA+"index_pages/person156.html", primary_source_type="青空文庫 北村透谷", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="白樺派（武者小路実篤）", name_en="Shirakaba school", name_original="白樺派", period_key="大正期", definition="雑誌『白樺』（1910-1923）を拠点に武者小路実篤・志賀直哉・有島武郎らが展開した、トルストイ的人道主義と個人主義を結ぶ理想主義文学運動。", background="学習院出身の上流階級青年たちが、西欧美術と人道思想を同時受容したことを背景とする。", development="志賀直哉の心境小説、有島の社会派長篇、武者小路の新しき村運動へ多角化。", historical_context="大正デモクラシー期の自由主義的雰囲気。", primary_source_url=AOZORA+"index_pages/person905.html", primary_source_type="青空文庫 志賀直哉", importance_score=4, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="新感覚派（横光利一）", name_en="New Sensibility school", name_original="新感覚派", period_key="昭和戦前期", definition="横光利一・川端康成らが雑誌『文藝時代』（1924-）に集い、感覚的・比喩的言語によって近代都市の経験を再構成しようとした前衛文学運動。", background="ヨーロッパのモダニズム（表現主義・未来派・ダダ）受容と関東大震災後の都市再生の影響。", development="横光『機械』、川端『伊豆の踊子』『雪国』を生み、戦後の新心理主義へ接続。", historical_context="震災後の都市文化の再構成期。", primary_source_url=AOZORA+"index_pages/person1085.html", primary_source_type="青空文庫 横光利一", importance_score=4, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="プロレタリア文学", name_en="Japanese proletarian literature", name_original="プロレタリア文学", period_key="昭和戦前期", definition="マルクス主義の影響下で労働者階級の生活と階級闘争を描いた1920-30年代の文学運動。雑誌『戦旗』を中心に、小林多喜二『蟹工船』、徳永直『太陽のない街』を代表作とする。", background="ロシア革命と社会主義運動の国際的高揚、関東大震災後の労働運動の組織化。", development="特高による弾圧と転向（1933年小林虐殺、1934年作家同盟解散）を経て戦後派・民主主義文学に接続。", historical_context="昭和恐慌と治安維持法体制下の階級的緊張。", primary_source_url=AOZORA+"cards/000156/card1465.html", primary_source_type="青空文庫『蟹工船』", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="私小説", name_en="I-novel / shi-shōsetsu", name_original="私小説", period_key="大正期", definition="作者自身の生活体験を一人称的に描き、虚構と告白の境界を意図的に曖昧化する日本近代文学独自のジャンル。田山花袋『蒲団』が起点で、葛西善蔵・嘉村礒多らの「破滅型」と志賀直哉らの「調和型」に大別される。", background="自然主義の告白的転回と西欧近代小説の主体観の屈折的移植から成立。", development="戦後にも安岡章太郎・庄野潤三らが継承、現代でも西村賢太らが書き継ぐ。", historical_context="近代日本の作家共同体（文壇）の閉鎖性と読者期待の構造。", primary_source_url=AOZORA+"cards/000214/card1668.html", primary_source_type="青空文庫『蒲団』", importance_score=5, source_tier="primary", canonical_in_region="core", fourth_axes=[{"axis":"主体","status":"rethinking","rationale":"私小説が前提する「真正な体験的主体＝作者」の同一性が、AI生成テクストの主体不在性によって相対化される。","related_ai_phenomenon":"LLM生成における作者主体の消失"},{"axis":"真正性","status":"rethinking","rationale":"私小説の核である体験的真正性が、AI共作・自動生成テクストの普及で批評的に再検討される。","related_ai_phenomenon":"AI共作・生成テクストの真正性問題"}], cross_domain=[{"target_db":"PT","link_type":"shared_concept","target_entity_name":"告白の詩学","description":"ルソー以降の西欧告白文学と日本私小説の比較詩学。"},{"target_db":"PHIL","link_type":"shared_concept","target_entity_name":"近代的自我","description":"私小説が文学形式として体現する近代的自我の哲学概念。"}])
add(**C, name_ja="戦後派", name_en="Postwar school", name_original="戦後派", period_key="戦後期", definition="敗戦直後（1946-50年代前半）に登場し、戦争体験と実存的虚無を西欧モダニズムの方法で描いた野間宏・武田泰淳・椎名麟三・大岡昇平・三島由紀夫・梅崎春生らの世代。", background="戦時動員・抑留・空襲体験と、戦後の言論解放、サルトル等の実存主義受容。", development="第一次・第二次に分かれて10年余り展開し、第三の新人世代へバトンが渡る。", historical_context="占領下の検閲緩和と思想的再編期。", primary_source_url=NDL+"info:ndljp/pid/1361903", primary_source_type="NDL所蔵 戦後派関連資料", importance_score=4, source_tier="secondary", canonical_in_region="core")
add(**C, name_ja="第三の新人", name_en="Third generation of postwar writers", name_original="第三の新人", period_key="戦後期", definition="安岡章太郎・吉行淳之介・庄野潤三・遠藤周作・小島信夫らの1950年代登場の世代。戦後派の壮大な観念性を退け、家族・性・日常の小さな破綻を心理的に描いた。", background="戦後派への反動と、私小説的伝統の戦後的更新。", development="内向の世代へと地続きに継承される。", historical_context="高度成長前夜の中産階級的日常の発見。", primary_source_url=NDL+"info:ndljp/pid/3437541", primary_source_type="NDL 第三の新人論", importance_score=3, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="内向の世代", name_en="Introverted generation", name_original="内向の世代", period_key="現代", definition="1970年前後に登場した古井由吉・後藤明生・黒井千次・小川国夫・阿部昭・坂上弘らの世代。政治の季節後の疲弊を背景に、内的経験の精緻な言語化を志向した。", background="60年安保・全共闘運動の挫折後の文学的退却。", development="現代日本文学のミニマリズム的潮流（小川洋子等）の前史となる。", historical_context="高度成長完了後の私的領域の拡張。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 日本文学研究", importance_score=3, source_tier="secondary", canonical_in_region="major")
# --- 文体/技法 (10) ---
add(**C, name_ja="言文一致", name_en="genbun itchi (unified spoken-written style)", name_original="言文一致", period_key="明治期", definition="話し言葉と書き言葉の乖離を解消し、口語に近い文体で書こうとした明治期の運動。二葉亭四迷『浮雲』（1887-89）の「だ・である」体、山田美妙、尾崎紅葉、最終的に夏目漱石の文体で完成された。", background="近代国民国家形成期の標準語政策と新聞・教育の大衆化要求。", development="戦後の口語自由詩・現代日本語散文の規範となる。", historical_context="明治の国語近代化政策と文学の連動。", primary_source_url=AOZORA+"cards/000006/card4810.html", primary_source_type="青空文庫『浮雲』", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="心境小説", name_en="shinkyō shōsetsu", name_original="心境小説", period_key="大正期", definition="私小説の調和型として、作者が達観した境地から日常の細部を静謐に観照する小説形式。志賀直哉『城の崎にて』（1917）が範型を成した。", background="白樺派的個人主義と禅的観照の文学的融合。", development="尾崎一雄、上林暁、戦後の庄野潤三へと連なる地下水脈。", historical_context="大正期の知的中産階級の精神的成熟志向。", primary_source_url=AOZORA+"cards/000001/card2543.html", primary_source_type="青空文庫『城の崎にて』", importance_score=4, source_tier="primary", canonical_in_region="major", cross_domain=[{"target_db":"PT","link_type":"parallel","target_entity_name":"観照の詩学","description":"西欧の観照詩学（contemplative poetics）と心境小説の比較。"}])
add(**C, name_ja="告白小説", name_en="confessional novel (Japan)", name_original="告白小説", period_key="明治期", definition="自己の秘めた性・罪・羞恥を告白する小説形式。田山花袋『蒲団』に始まり、岩野泡鳴『耽溺』、近松秋江『黒髪』など破滅型私小説の核を成す。", background="ルソー『告白』とロシア文学（ドストエフスキー）の翻訳受容。", development="戦後の太宰治『人間失格』、現代の私小説に継承。", historical_context="国家規範と私的欲望の緊張。", primary_source_url=AOZORA+"cards/000035/card301.html", primary_source_type="青空文庫『人間失格』", importance_score=4, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="観念小説", name_en="kannen shōsetsu (idea novel)", name_original="観念小説", period_key="明治期", definition="社会問題・倫理・思想を主題化する明治20年代の小説潮流。泉鏡花『夜行巡査』『外科室』、川上眉山らに代表され、自然主義の前段階を成した。", background="徳富蘇峰の平民主義論争などジャーナリズムの社会批評熱の文学化。", development="自然主義の出現で衰退するが、後の社会派小説の前史。", historical_context="日清戦争前後の社会問題化期。", primary_source_url=AOZORA+"cards/000050/card1077.html", primary_source_type="青空文庫『夜行巡査』", importance_score=3, source_tier="primary", canonical_in_region="major")
add(**C, name_ja="新感覚派文体", name_en="new sensibility prose style", name_original="新感覚派文体", period_key="昭和戦前期", definition="横光利一らが提唱した、擬人化・共感覚的比喩・速度感ある名詞句で都市的経験の感覚を新たに表現する文体。「真昼である。特別急行列車は満員のまま全速力で駆けていた」式の冒頭が範例。", background="ヨーロッパ・モダニズム文学（プルースト、ジョイス、エイゼンシュテイン）受容。", development="川端康成の幻想的散文、戦後の安部公房・大江健三郎の比喩文体に影響。", historical_context="震災後の都市メディア環境の変容。", primary_source_url=AOZORA+"cards/000168/card2358.html", primary_source_type="青空文庫『機械』", importance_score=4, source_tier="primary", canonical_in_region="major", cross_domain=[{"target_db":"PT","link_type":"parallel","target_entity_name":"モダニズム詩学","description":"ヨーロッパ・モダニズム詩学と新感覚派文体の比較。"}])
add(**C, name_ja="意識の流れ日本版", name_en="Japanese stream of consciousness", name_original="意識の流れ", period_key="昭和戦前期", definition="ジョイス・ウルフ流の意識の流れ手法を日本語に移植した実験的散文技法。伊藤整『得能五郎の生活と意見』、堀辰雄『風立ちぬ』に部分的に試みられた。", background="伊藤整らによる『ユリシーズ』翻訳とモダニズム理論受容。", development="戦後は中村真一郎・福永武彦らに継承されるが日本では主流化しなかった。", historical_context="昭和初期の翻訳文化と前衛詩運動。", primary_source_url=AOZORA+"cards/000168/persons168.html", primary_source_type="青空文庫 伊藤整", importance_score=3, source_tier="secondary", canonical_in_region="minor")
add(**C, name_ja="私小説的真実", name_en="shi-shōsetsu truth-claim", name_original="私小説的真実", period_key="大正期", definition="私小説が読者と取り結ぶ「作者の体験は事実である」という暗黙の契約。客観的事実性ではなく作者人格と読者共同体の文壇的信頼関係に基礎を置く独特の真実観。", background="自然主義の告白主義と文壇の閉鎖的読者構造。", development="中村光夫『風俗小説論』（1950）以降、繰り返し批評対象となる。", historical_context="日本近代文学の制度的特殊性。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 私小説論研究", importance_score=4, source_tier="secondary", canonical_in_region="core", fourth_axes=[{"axis":"真正性","status":"rethinking","rationale":"作者人格に依拠する真実契約が、AI共作・代筆問題で根本から問われる。","related_ai_phenomenon":"AI代筆と作者真正性の崩壊"}])
add(**C, name_ja="メタフィクション", name_en="metafiction (Japan)", name_original="メタフィクション", period_key="現代", definition="小説が小説であることを自己言及的に主題化する技法。筒井康隆『虚構船団』『朝のガスパール』、高橋源一郎『さようなら、ギャングたち』などポストモダン世代に顕著。", background="アメリカ・ポストモダン文学（バース、バーセルミ）と仏ヌーヴォー・ロマンの受容。", development="円城塔・佐藤友哉らの現代実験小説、舞城王太郎の自己言及スタイルに継承。", historical_context="1980年代の消費社会化と虚構性意識の高まり。", primary_source_url=NDL+"info:ndljp/pid/12612000", primary_source_type="NDL 高橋源一郎関連", importance_score=3, source_tier="secondary", canonical_in_region="major", fourth_axes=[{"axis":"物語","status":"rethinking","rationale":"メタフィクションの自己言及性が、生成AIにおける「自分が書いていることへの自己言及」の問題系と接続する。","related_ai_phenomenon":"LLMの自己言及的物語生成"}])
add(**C, name_ja="物語論的小説", name_en="narratological novel", name_original="物語論的小説", period_key="現代", definition="ジュネット・バルトらの物語論を理論的に踏まえて構築された小説。古井由吉、大江健三郎『同時代ゲーム』、丸谷才一『裏声で歌へ君が代』が範例。", background="1970年代の構造主義・物語論の翻訳受容（蓮實重彦、丹生谷貴志ら）。", development="現代純文学の理論武装の一形態として継続。", historical_context="アカデミズムと文学の接合。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 物語論研究", importance_score=3, source_tier="secondary", canonical_in_region="minor")
add(**C, name_ja="ライトノベル文体", name_en="light novel style", name_original="ライトノベル文体", period_key="現代", definition="若年読者向けに会話文・短文・キャラクター視点描写を多用し、アニメ・マンガと連動した小説文体。電撃文庫・角川スニーカー文庫等が定着させた1990年代以降の主要文体類型。", background="少年向けジュブナイル小説とゲームシナリオの文学化。", development="なろう系・異世界転生小説に発展し、海外翻訳市場でも独自カテゴリを形成。", historical_context="メディアミックスとオタク文化の市民化。", primary_source_url="https://dengekibunko.jp/", primary_source_type="電撃文庫公式", importance_score=3, source_tier="tertiary", canonical_in_region="major")
# --- 主題/世界観 (10) ---
add(**C, name_ja="近代的自我", name_en="modern self (Japan)", name_original="近代的自我", period_key="明治期", definition="共同体的桎梏から離脱し独立した内面と意志を持つ主体の理念。北村透谷・夏目漱石『私の個人主義』に明示され、日本近代文学全体の基層的問題系を成す。", background="西欧近代の個人主義の翻訳的受容と日本的家族・国家との緊張。", development="漱石『こゝろ』『道草』、戦後実存主義文学まで持続する主題。", historical_context="明治国家の臣民像と近代的個人の対立。", primary_source_url=AOZORA+"cards/000148/card773.html", primary_source_type="青空文庫『こゝろ』", importance_score=5, source_tier="primary", canonical_in_region="core", cross_domain=[{"target_db":"PHIL","link_type":"shared_concept","target_entity_name":"主体性","description":"日本哲学（西田・和辻）と文学における近代的自我概念の交差。"}])
add(**C, name_ja="煩悶青年", name_en="anguished youth", name_original="煩悶青年", period_key="明治期", definition="日露戦争前後（1903年藤村操の華厳の滝投身を象徴とする）に出現した、人生の意味を問い苦悩する青年知識層の典型。漱石『三四郎』『それから』の主人公類型を生んだ。", background="近代教育の普及と立身出世主義の限界の顕在化。", development="戦後の太宰的自意識青年、戦後派の実存的青年に変奏される。", historical_context="高等教育の急拡大と社会的飽和。", primary_source_url=AOZORA+"cards/000148/card776.html", primary_source_type="青空文庫『三四郎』", importance_score=4, source_tier="primary", canonical_in_region="major")
add(**C, name_ja="自然と人間", name_en="nature and human", name_original="自然と人間", period_key="明治期", definition="自然描写を内面の客観的相関物として精緻化する近代日本文学の中心主題。国木田独歩『武蔵野』、徳冨蘆花『自然と人生』、川端『雪国』に至る系譜を成す。", background="ワーズワースなど英国ロマン派、ロシア文学の自然描写受容。", development="戦後の宮本輝・井上靖、現代の小川洋子の風景描写へ継承。", historical_context="近代化による自然の喪失意識の文学化。", primary_source_url=AOZORA+"cards/000038/card1672.html", primary_source_type="青空文庫『武蔵野』", importance_score=4, source_tier="primary", canonical_in_region="major")
add(**C, name_ja="家族解体", name_en="dissolution of the family", name_original="家族解体", period_key="現代", definition="近代家族の制度的崩壊と機能不全を主題化する戦後・現代文学の主題系。小島信夫『抱擁家族』（1965）が記念碑、現代では桐野夏生・川上未映子に至る。", background="戦後民法改正と高度成長期の核家族化、後の少子高齢化。", development="家族論論争（上野千鶴子等）と並走しつつ深化する。", historical_context="戦後核家族イデオロギーの破綻。", primary_source_url=NDL+"info:ndljp/pid/9540716", primary_source_type="NDL『抱擁家族』", importance_score=4, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="戦争体験", name_en="war experience", name_original="戦争体験", period_key="戦後期", definition="アジア・太平洋戦争の従軍・空襲・抑留・引揚体験を主題化する戦後文学の中核主題。大岡昇平『野火』『俘虜記』、野間宏『真空地帯』が代表する。", background="戦後の言論解放と作家自身の戦争被害・加害体験の語り直し要求。", development="原爆文学・在日文学・引揚者文学などサブジャンルへ展開。", historical_context="占領期の検閲緩和と戦後民主主義言論空間。", primary_source_url=AOZORA+"cards/001157/card59013.html", primary_source_type="青空文庫『俘虜記』関連", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="原爆文学", name_en="atomic bomb literature", name_original="原爆文学", period_key="戦後期", definition="広島・長崎の原爆体験を文学化したジャンル。原民喜『夏の花』、大田洋子『屍の街』、栗原貞子の詩、井伏鱒二『黒い雨』、林京子らに代表される。", background="占領下のプレスコード解除（1949以降）と被爆作家の証言活動。", development="国際的にもヒバクシャ文学として翻訳され、核時代の倫理文学の範例となる。", historical_context="冷戦下の核兵器論争と日本の特殊性。", primary_source_url=AOZORA+"cards/000293/card4204.html", primary_source_type="青空文庫『夏の花』", importance_score=5, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="在日", name_en="Zainichi (Korean residents in Japan)", name_original="在日", period_key="戦後期", definition="植民地支配の帰結として日本に暮らす朝鮮系住民の体験を主題化する文学領域。金石範『火山島』、李恢成、金鶴泳、現代の柳美里・玄月らが日本語で書く。", background="植民地支配・解放後の南北分断・差別構造を背景とする。", development="日本語で書くことの政治性、母語と国籍の乖離が中心問題系を成す。", historical_context="戦後日本社会の単一民族神話とその限界。", primary_source_url=NDL+"info:ndljp/pid/12628000", primary_source_type="NDL 在日朝鮮人文学", importance_score=4, source_tier="secondary", canonical_in_region="major", fourth_axes=[{"axis":"主体","status":"rethinking","rationale":"国民国家・単一言語が前提する文学主体の同一性が、在日文学において根本的に揺らぐ。","related_ai_phenomenon":"多言語AI生成と国民文学概念の揺らぎ"},{"axis":"言語","status":"rethinking","rationale":"母語ではない日本語で書く実践が、AI翻訳時代の言語的真正性問題と接続する。","related_ai_phenomenon":"AIによる多言語横断執筆の倫理"}], cross_domain=[{"target_db":"AN","link_type":"shared_concept","target_entity_name":"周縁性／マイノリティ","description":"人類学のマイノリティ研究と在日文学の交差。"}])
add(**C, name_ja="周縁性", name_en="marginality", name_original="周縁性", period_key="現代", definition="国民国家・標準語・男性中心の文学的中心に対し、地方・女性・障害・マイノリティの位置から書く立場性。中上健次の路地、津島佑子の女性経験、目取真俊の沖縄が代表する。", background="ポストコロニアル批評・ジェンダー論の日本受容と近代文学批判。", development="現代日本文学の主流的問題系として制度化されつつある。", historical_context="戦後日本の均質化に対する反作用。", primary_source_url=NDL+"info:ndljp/pid/3137000", primary_source_type="NDL 中上健次関連", importance_score=4, source_tier="secondary", canonical_in_region="major", cross_domain=[{"target_db":"AN","link_type":"shared_concept","target_entity_name":"周縁性","description":"人類学的周縁性概念と文学的周縁性の交差。"}])
add(**C, name_ja="記憶/トラウマ", name_en="memory and trauma", name_original="記憶／トラウマ", period_key="現代", definition="個人的・歴史的トラウマと記憶の不可能な再構成を主題化する1990年代以降の文学。村上春樹『ねじまき鳥クロニクル』、多和田葉子、現代の朝井リョウ・上田岳弘までを貫く。", background="ホロコースト研究、トラウマ理論（カルース等）の翻訳受容、戦争責任議論の再活性化。", development="震災（阪神・東日本）後の記憶の文学として現在進行形で展開。", historical_context="戦後50年・60年の記憶論争と災害連続。", primary_source_url=NDL+"info:ndljp/pid/13001000", primary_source_type="NDL 記憶／トラウマ研究", importance_score=4, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="グローバル化と他者性", name_en="globalization and otherness", name_original="グローバル化と他者性", period_key="現代", definition="国境を越える移動・言語混淆・文化的他者性を主題化する現代日本文学の領域。多和田葉子の越境的作品、水村美苗『日本語が亡びるとき』、現代翻訳者作家まで広がる。", background="冷戦後のグローバル化と日本社会の国際化、海外日本研究の拡大。", development="日本語文学の国際的受容（村上春樹、川上弘美の英訳）と並走しつつ展開。", historical_context="ポスト冷戦の文化的越境状況。", primary_source_url=NDL+"info:ndljp/pid/9755000", primary_source_type="NDL 多和田葉子関連", importance_score=3, source_tier="secondary", canonical_in_region="major")
# --- 批評/理論 (10) ---
add(**C, name_ja="評論", name_en="hyōron (literary criticism)", name_original="評論", period_key="明治期", definition="作品論・作家論・思想論を含む日本近代独自の散文批評ジャンル。北村透谷、内田魯庵、明治末の島村抱月、戦後の小林秀雄に至り独自の文学的評論文が成立した。", background="西欧批評（マシュー・アーノルド等）と漢文評論の伝統の融合。", development="小林秀雄『様々なる意匠』『無常といふ事』が戦後に範型を確立した。", historical_context="新聞・雑誌メディアの拡大と知識人層の形成。", primary_source_url=AOZORA+"cards/000035/card2253.html", primary_source_type="青空文庫 小林秀雄", importance_score=4, source_tier="primary", canonical_in_region="core")
add(**C, name_ja="近代の超克論争", name_en="Overcoming Modernity debate", name_original="近代の超克", period_key="昭和戦前期", definition="1942年雑誌『文学界』座談会に端を発し、西欧近代の限界を東洋的伝統で乗り越えると論じた知識人の議論。京都学派（西谷啓治）、文学者（小林秀雄、中村光夫）が参加。", background="日中戦争・太平洋戦争の思想的正当化要求と、近代主義への戦前的疑念。", development="戦後、竹内好『近代の超克』再評価により、批判と継承が継続される論争史的事件。", historical_context="戦時動員と知識人の戦争協力。", primary_source_url=NDL+"info:ndljp/pid/1126000", primary_source_type="NDL『近代の超克』", importance_score=4, source_tier="secondary", canonical_in_region="core", cross_domain=[{"target_db":"PHIL","link_type":"shared_concept","target_entity_name":"近代批判","description":"哲学の近代批判（西田・京都学派）と文学的近代の超克論の交差。"}])
add(**C, name_ja="政治と文学", name_en="politics and literature debate", name_original="政治と文学", period_key="戦後期", definition="戦後すぐの中野重治・荒正人・平野謙らによる、文学の自律性と政治的責任の関係をめぐる論争。新日本文学会と『近代文学』派の対立軸として展開した。", background="戦時下の作家の戦争協力責任の追及と、戦後民主主義文学の方向性論争。", development="60年代の安保論争、70年代の三島事件と文学評論の関係まで余波が及ぶ。", historical_context="戦後思想の再編と転向問題の継続。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 戦後文学論争", importance_score=4, source_tier="secondary", canonical_in_region="core")
add(**C, name_ja="私小説論争", name_en="shi-shōsetsu debate", name_original="私小説論争", period_key="戦後期", definition="中村光夫『風俗小説論』（1950）が私小説を「日本近代小説の歪み」と批判したことに始まる、戦後の長期的な私小説評価論争。伊藤整、平野謙、戦後派批評家を巻き込んだ。", background="戦後西欧近代小説（バルザック、トルストイ）の規範意識と日本的特殊性の対比。", development="現代でも私小説の再評価／批判は繰り返される批評史的論点。", historical_context="戦後文学批評の自己反省。", primary_source_url=NDL+"info:ndljp/pid/1666000", primary_source_type="NDL『風俗小説論』", importance_score=4, source_tier="secondary", canonical_in_region="core")
add(**C, name_ja="第三人称客観", name_en="third-person objective narration", name_original="第三人称客観描写", period_key="戦後期", definition="私小説的一人称主観に対し、客観的三人称で社会総体を描くべしとする戦後派の文学的要求。野間宏『真空地帯』、大岡昇平の試みに具体化された。", background="フローベール・トルストイ流のリアリズム小説への規範意識。", development="戦後派以降、社会派長篇小説の方法論的基盤となる。", historical_context="戦後の社会総体把握への文学的要求。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 戦後派研究", importance_score=3, source_tier="secondary", canonical_in_region="minor")
add(**C, name_ja="テクスト論受容", name_en="reception of text theory", name_original="テクスト論", period_key="現代", definition="バルト・デリダ・クリステヴァらのテクスト論を1970-80年代に蓮實重彦・柄谷行人・浅田彰らが日本に導入し、作家論中心の批評からテクスト分析批評への転回を促した動向。", background="フランス現代思想の翻訳ブームと『現代思想』『批評空間』等の雑誌活動。", development="ポストモダン批評全般、現代の理論批評（東浩紀等）に継承。", historical_context="80年代の理論ブームと大学批評の隆盛。", primary_source_url=JSTAGE+"article/jjla1971/", primary_source_type="J-STAGE 現代批評理論研究", importance_score=4, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="カルチュラル・スタディーズ日本受容", name_en="Japanese reception of cultural studies", name_original="カルチュラル・スタディーズ受容", period_key="現代", definition="バーミンガム学派以降のカルチュラル・スタディーズを1990年代に上野俊哉・毛利嘉孝らが導入し、文学研究を大衆文化・サブカルチャー研究に拡張した動向。", background="サブカルチャー（マンガ・アニメ・J-POP）の学術対象化要求。", development="2000年代の「ポップカルチャー研究」、東浩紀のオタク論等に展開。", historical_context="文学研究の対象拡張と人文学の制度的再編。", primary_source_url=JSTAGE+"article/cs/", primary_source_type="J-STAGE 文化研究", importance_score=3, source_tier="secondary", canonical_in_region="minor")
add(**C, name_ja="ジェンダー批評日本受容", name_en="Japanese reception of gender criticism", name_original="ジェンダー批評", period_key="現代", definition="バトラー・スピヴァク等のジェンダー・ポストコロニアル理論を1990年代以降に上野千鶴子・水田宗子・小森陽一らが文学研究に応用した動向。日本近代文学の家父長性を批判的に再読した。", background="ウーマンリブ運動と女性学の制度化、第二波フェミニズム理論の翻訳。", development="現代の文学賞・カノン構成への批判的介入として継続。", historical_context="ポスト冷戦期の文化研究の多元化。", primary_source_url=JSTAGE+"article/joshigakuf/", primary_source_type="J-STAGE 女性学研究", importance_score=4, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="ポスト構造主義日本受容", name_en="Japanese reception of poststructuralism", name_original="ポスト構造主義受容", period_key="現代", definition="フーコー・デリダ・ドゥルーズらの思想を1980-90年代に蓮實重彦・浅田彰・柄谷行人・東浩紀らが文学批評に導入した動向。作者・主体・国民の解体的思考を促した。", background="フランス現代思想ブームとアカデミズムの理論武装。", development="現代の批評・理論研究（東浩紀『動物化するポストモダン』）に継承。", historical_context="80-90年代の高度資本主義文化の理論的把握要求。", primary_source_url=NDL+"info:ndljp/pid/12567000", primary_source_type="NDL ポスト構造主義関連", importance_score=4, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="デジタル批評", name_en="digital literary criticism", name_original="デジタル批評", period_key="現代", definition="デジタル人文学・テクストマイニング・電子書籍を対象とする2010年代以降の批評領域。文学研究の計量的転回（distant reading）と日本独自の批評ブログ・SNS批評を含む。", background="パソコン・インターネット普及と人文学の方法論的再編。", development="生成AI時代の批評（東浩紀、佐々木敦等）への接続が現在進行形。", historical_context="文学制度のデジタル変容。", primary_source_url=JSTAGE+"article/jadh/", primary_source_type="J-STAGE デジタル人文学", importance_score=3, source_tier="tertiary", canonical_in_region="minor")
# --- メタ文学/制度 (10) ---
add(**C, name_ja="文壇", name_en="bundan (literary establishment)", name_original="文壇", period_key="明治期", definition="作家・批評家・編集者の閉じた共同体として成立した日本独特の文学制度。明治後期に形成され、新人発掘・評価・正典化を内部で完結させる構造を持った。", background="新聞・総合雑誌の発達と作家の専業化。", development="戦後も同人誌・出版社・文学賞を通じ持続したが、現代では弱体化。", historical_context="近代日本のメディア構造と作家の社会的位置。", primary_source_url=NDL+"info:ndljp/pid/2982000", primary_source_type="NDL 文壇史研究", importance_score=4, source_tier="secondary", canonical_in_region="core")
add(**C, name_ja="同人誌", name_en="dōjinshi (coterie magazine)", name_original="同人誌", period_key="明治期", definition="作家グループが自費で刊行する小規模文芸誌。『白樺』『文藝時代』『近代文学』など主要文学運動の母胎となった、日本近代文学の制度的特徴。", background="出版資本主義以前の文学的結社文化。", development="戦後同人誌、現代同人即売会（コミケ）まで実践形態が連続的に拡張。", historical_context="文学運動と読者形成の共同体的基盤。", primary_source_url=NDL+"info:ndljp/pid/2900000", primary_source_type="NDL 同人誌研究", importance_score=3, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="芥川賞", name_en="Akutagawa Prize", name_original="芥川龍之介賞", period_key="昭和戦前期", definition="文藝春秋社が1935年に創設した純文学新人賞。戦後の作家登竜門として制度化され、当該文学の純文学的正統性を社会的に保証する装置となった。", background="芥川龍之介・直木三十五の急逝を契機とした菊池寛の事業。", development="石原慎太郎『太陽の季節』（1955）以降、社会的事件としての受賞も多発。", historical_context="文学制度の社会的可視化と商業性。", primary_source_url="https://www.bunshun.co.jp/shinkoukai/award/akutagawa/", primary_source_type="文藝春秋 芥川賞公式", importance_score=4, source_tier="secondary", canonical_in_region="core")
add(**C, name_ja="直木賞", name_en="Naoki Prize", name_original="直木三十五賞", period_key="昭和戦前期", definition="芥川賞と同時創設された大衆文学新人賞。純文学／大衆文学の制度的二分法を象徴し、その境界の流動化が現代の課題となっている。", background="菊池寛による文学賞の二系列化戦略。", development="現代では純文学／エンタメ境界の溶解により、両賞の意味が問い直されている。", historical_context="日本独特の純／大衆二項対立。", primary_source_url="https://www.bunshun.co.jp/shinkoukai/award/naoki/", primary_source_type="文藝春秋 直木賞公式", importance_score=3, source_tier="secondary", canonical_in_region="major", fourth_axes=[{"axis":"正典","status":"rethinking","rationale":"純文学／大衆の制度的二分法が、AI生成小説の出現で更に流動化する。","related_ai_phenomenon":"AI小説と純／大衆境界の融解"}])
add(**C, name_ja="全集", name_en="zenshū (collected works)", name_original="全集", period_key="昭和戦前期", definition="作家・テーマ別の網羅的著作集として戦前期に完成された出版形態。岩波書店『漱石全集』（1917-）が範型を成し、文学的正典化の主要装置となった。", background="円本ブーム（1926-）期の出版資本主義と読書市場の拡大。", development="戦後も主要作家の全集刊行が継続するが、現代では編集デジタル化が進む。", historical_context="近代日本の正典化制度の物質的基盤。", primary_source_url=NDL+"info:ndljp/pid/1015000", primary_source_type="NDL 漱石全集等", importance_score=3, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="文庫", name_en="bunko (paperback)", name_original="文庫", period_key="昭和戦前期", definition="岩波文庫（1927-）に始まる小型廉価の古典・現代文学普及形態。新潮文庫・角川文庫・講談社文庫などが続き、戦後の読書文化の基盤を成した。", background="ドイツのレクラム文庫を範とした文化的啓蒙事業。", development="現代では電子書籍化と並走しつつ存続するが市場縮小傾向。", historical_context="近代日本の大衆読書の制度的基盤。", primary_source_url="https://www.iwanami.co.jp/bunko/", primary_source_type="岩波文庫公式", importance_score=3, source_tier="secondary", canonical_in_region="major")
add(**C, name_ja="電子書籍", name_en="e-book (Japan)", name_original="電子書籍", period_key="現代", definition="2000年代以降普及したデジタル書籍形態。Kindle日本上陸（2012）以降本格化し、出版・読書の物質性と頒布構造を根本的に変えつつある。", background="インターネット普及と出版資本主義の構造変容。", development="ウェブ小説のセルフ電子書籍化、AI生成テクストの電子流通へ展開。", historical_context="メディア・出版のデジタル転換。", primary_source_url="https://www.amazon.co.jp/kindle-dbs/hz/", primary_source_type="Amazon Kindle Japan", importance_score=3, source_tier="tertiary", canonical_in_region="major")
add(**C, name_ja="ライトノベル", name_en="light novel", name_original="ライトノベル", period_key="現代", definition="若年読者向けにキャラクター・会話・連作性を重視した文庫小説ジャンル。1990年代に電撃文庫・角川スニーカー文庫等で確立し、メディアミックスと連動して大量市場を形成した。", background="少年向けジュブナイル小説とゲームシナリオの融合。", development="2010年代以降、なろう系・異世界転生サブジャンルが海外翻訳市場でも拡大。", historical_context="オタク文化の市民化と書籍市場の変動。", primary_source_url="https://dengekibunko.jp/", primary_source_type="電撃文庫公式", importance_score=4, source_tier="tertiary", canonical_in_region="major", fourth_axes=[{"axis":"正典","status":"rethinking","rationale":"純文学正典の外部に独自の正典・カノンを構築するライトノベルが、文学正典概念を根本的に問う。","related_ai_phenomenon":"AI生成小説と新しい正典形成"}])
add(**C, name_ja="ウェブ小説", name_en="web novel", name_original="ウェブ小説", period_key="現代", definition="「小説家になろう」「カクヨム」等のプラットフォームで連載・公開される小説。アマチュア作者が直接読者と接続し、ランキング・コメントを介した即時的フィードバックの中で書く新しい文学形態。", background="個人ホームページ時代の小説サイトと2010年代のプラットフォーム化。", development="書籍化・コミカライズ・アニメ化のパイプラインを形成し、ライトノベル市場と融合。", historical_context="プラットフォーム資本主義と文学創作。", primary_source_url="https://syosetu.com/", primary_source_type="小説家になろう", importance_score=4, source_tier="tertiary", canonical_in_region="major", fourth_axes=[{"axis":"作者性","status":"rethinking","rationale":"プラットフォーム上のアマチュア作者性は、従来の文学的作者像を解体し、AI共作との連続性をもつ。","related_ai_phenomenon":"AI共作によるアマチュア創作の量産化"},{"axis":"受容","status":"rethinking","rationale":"ランキング即時フィードバック型の創作環境が、AI推薦アルゴリズムによる読者経験設計と接続する。","related_ai_phenomenon":"アルゴリズム的読書経験の設計"}], cross_domain=[{"target_db":"AI-Development","link_type":"parallel","target_entity_name":"アルゴリズム的創作環境","description":"プラットフォーム駆動型ウェブ小説と生成AIの創作環境の構造的類似。"}])
add(**C, name_ja="小説投稿サイト", name_en="novel-posting platform", name_original="小説投稿サイト", period_key="現代", definition="「小説家になろう」「カクヨム」「pixiv小説」「アルファポリス」など、誰でも小説を投稿・公開できるWebプラットフォーム。日本の現代文学エコシステムの基盤の一つを成す。", background="Web 2.0期のユーザー生成コンテンツ文化。", development="出版社との提携、書籍化制度、AI生成小説の参入問題が現在の論点。", historical_context="文学的アマチュアリズムのデジタル制度化。", primary_source_url="https://kakuyomu.jp/", primary_source_type="カクヨム", importance_score=3, source_tier="tertiary", canonical_in_region="major")

def main() -> int:
    name_to_id: dict[str, int] = {}
    fourth_count = cd_count = 0
    with LitDB() as db:
        period_ids: dict[str, int] = {}
        for nj, ne, sy, ey, desc in PERIODS:
            pid = db.get_or_create_period(name_ja=nj, region="東アジア",
                                          start_year=sy, end_year=ey,
                                          name_en=ne, description=desc)
            period_ids[nj] = pid
        for raw in CONCEPTS:
            entry = dict(raw)
            fourth_axes = entry.pop("fourth_axes", [])
            cross_domain = entry.pop("cross_domain", [])
            pkey = entry.pop("period_key", None)
            if pkey:
                entry["period_id"] = period_ids[pkey]
            try:
                cid = db.insert_concept(**entry)
            except LitDBError as e:
                print(f"  [error] {entry['name_ja']}: {e}")
                continue
            name_to_id[entry["name_ja"]] = cid
            for ax in fourth_axes:
                db.tag_fourth_transform(cid, **ax)
                fourth_count += 1
            for cd in cross_domain:
                db.insert_cross_domain(lit_entity_type="concept", lit_entity_id=cid,
                                       target_db=cd["target_db"], link_type=cd["link_type"],
                                       target_entity_id=cd.get("target_entity_id"),
                                       target_entity_name=cd.get("target_entity_name"),
                                       description=cd.get("description"))
                cd_count += 1
        summary = db.progress_summary()
        print(f"[c18] inserted concepts (this run): {len(name_to_id)} / total: {summary['concepts']}")
        print(f"[c18] fourth_transform_tags +{fourth_count}; cross_domain +{cd_count}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
